#%RAML 1.0 DataType
(package): CartDiscount
type: CartDiscountValue
displayName: CartDiscountValueGiftLineItem
discriminatorValue: giftLineItem
properties:
  product:
    type: ProductReference
  variantId:
    type: number
    format: int64
  supplyChannel?:
    type: ChannelReference
    description: The channel must have the role `InventorySupply`
  distributionChannel?:
    type: ChannelReference
    description: The channel must have the role `ProductDistribution`
