#%RAML 1.0 DataType
(package): CartDiscount
displayName: CartDiscount
(updateType): CartDiscountUpdate
type: BaseResource
example: !include ../../examples/cart-discount.example.json
properties:
  id:
    (identifier): true
    type: string
    description: Unique identifier of the CartDiscount.
  version:
    type: number
    format: int64
    description: |
      Current version of the CartDiscount.
  createdAt:
    type: datetime
    description: |
      Date and time (UTC) the CartDiscount was initially created.
  lastModifiedAt:
    type: datetime
    description: |
      Date and time (UTC) the CartDiscount was last updated.
  lastModifiedBy?:
    type: LastModifiedBy
    (beta): true
    description: |
      IDs and references that last modified the CartDiscount.
  createdBy?:
    type: CreatedBy
    (beta): true
    description: |
      IDs and references that created the CartDiscount.
  name:
    type: LocalizedString
    description: |
      Name of the CartDiscount.
  key?:
    type: string
    description: |
      User-defined unique identifier of the CartDiscount.
    pattern: ^[A-Za-z0-9_-]+$
    minLength: 2
    maxLength: 256
  description?:
    type: LocalizedString
    description: |
      Description of the CartDiscount.
  value:
    type: CartDiscountValue
    description: |
      Effect of the CartDiscount on the `target`.
  cartPredicate:
    type: string
    description: |
      Valid [Cart Predicate](/../api/projects/predicates#cart-predicates).
  target?:
    type: CartDiscountTarget
    description: |
      Segment of the Cart that is discounted.

      Empty, if the `value` is `giftLineItem`.
  sortOrder:
    type: string
    description: |
      Value between `0` and `1` that determines the order in which the CartDiscounts are applied; a CartDiscount with a higher value is prioritized.

      It is unique among all CartDiscounts and DiscountGroups.

      If the CartDiscount is part of a DiscountGroup, it uses the sort order of the DiscountGroup.
  stores:
    type: StoreKeyReference[]
    maxItems: 500
    description: |
      - If a value exists, the Cart Discount applies on [Carts](ctp:api:type:Cart) having a [Store](ctp:api:type:Store) matching any Store defined for this field.
      - If empty, the Cart Discount applies on all [Carts](ctp:api:type:Cart), irrespective of a Store.
  isActive:
    type: boolean
    description: |
      Indicates if the CartDiscount is active and can be applied to the Cart.
  validFrom?:
    type: datetime
    description: |
      Date and time (UTC) from which the Discount is effective.
  validUntil?:
    type: datetime
    description: |
      Date and time (UTC) until which the Discount is effective.
  requiresDiscountCode:
    type: boolean
    description: |
      Indicates if the Discount is used in connection with a [DiscountCode](ctp:api:type:DiscountCode).
    default: false
  references:
    type: Reference[]
    description: |
      References of all resources that are addressed in the predicate.
      The API generates this array from the predicate.
  stackingMode:
    type: StackingMode
    description: |
      Indicates whether the application of the CartDiscount causes other discounts to be ignored.
    default: Stacking
  custom?:
    type: CustomFields
    description: |
      Custom Fields of the CartDiscount.
  discountGroup?:
    type: DiscountGroupReference
    description: |
      Reference to a DiscountGroup that the CartDiscount belongs to.
