#%RAML 1.0 DataType
(package): CartDiscount
(docs-uri): https://docs.commercetools.com/api/projects/cartDiscounts#cartdiscountresourceidentifier
(java-extends): com.commercetools.api.models.Identifiable<CartDiscount>
type: ResourceIdentifier
displayName: CartDiscountResourceIdentifier
discriminatorValue: cart-discount
description: |
  [ResourceIdentifier](ctp:api:type:ResourceIdentifier) to a [CartDiscount](ctp:api:type:CartDiscount).
properties:
  id?:
    type: string
    description: |
      Unique identifier of the referenced [CartDiscount](ctp:api:type:CartDiscount). Either `id` or `key` is required.
  key?:
    type: string
    description: |
      User-defined unique identifier of the referenced [CartDiscount](ctp:api:type:CartDiscount). Either `id` or `key` is required.
