#%RAML 1.0 DataType
(package): CartDiscount
type: CartDiscountValue
displayName: CartDiscountValueRelative
discriminatorValue: relative
example: !include ../../examples/CartDiscount/CartDiscountValueRelative.json
description: |
  Discounts the [CartDiscountTarget](ctp:api:type:CartDiscountTarget) relative to its price.
properties:
  permyriad:
    type: number
    format: int64
    description: |
      Fraction (per ten thousand) the price is reduced by. For example, `1000` will result in a 10% price reduction.
