#%RAML 1.0 DataType
(package): CartDiscount
type: CartDiscountValue
displayName: CartDiscountValueFixed
discriminatorValue: fixed
description: |
  Sets the [DiscountedLineItemPrice](ctp:api:type:DiscountedLineItemPrice) of the [CartDiscountLineItemsTarget](ctp:api:type:CartDiscountLineItemsTarget) or [CartDiscountCustomLineItemsTarget](ctp:api:type:CartDiscountCustomLineItemsTarget) to the value specified in the `money` field, if it is lower than the current Line Item price for the same currency. If the Line Item price is already discounted to a price equal to or lower than the respective price in the `money` field, this Discount is not applied.
properties:
  money:
    type: CentPrecisionMoney[]
    description: |
      Cent precision money values in different currencies.
