#%RAML 1.0 DataType
(package): CartDiscount
type: CartDiscountTarget
displayName: CartDiscountShippingCostTarget
discriminatorValue: shipping
example: !include ../../examples/CartDiscount/CartDiscountShippingCostTarget.json
description: |
  Discount is applied to the shipping costs of the [Cart](ctp:api:type:Cart).
