#%RAML 1.0 DataType
(package): CartDiscount
(docs-uri): https://docs.commercetools.com/http-api-projects-cartDiscounts.html#cartdiscount
displayName: CartDiscountDraft
type: object
properties:
  name:
    type: LocalizedString
    description: ''
  key?:
    type: string
    description: |-
      User-specific unique identifier for a cart discount.
      Must be unique across a project.
      The field can be reset using the Set Key UpdateAction.
  description?:
    type: LocalizedString
    description: ''
  value:
    type: CartDiscountValueDraft
    description: ''
  cartPredicate:
    type: string
    description: A valid Cart predicate.
  target?:
    type: CartDiscountTarget
    description:
      Must not be set when the `value` has type `giftLineItem`, otherwise a
      CartDiscountTarget must be set.
  sortOrder:
    type: string
    description: |-
      The string must contain a number between 0 and 1.
      A discount with greater sort order is prioritized higher than a discount with lower sort order.
      The sort order must be unambiguous among all cart discounts.
  isActive?:
    type: boolean
    description: |-
      Only active discount can be applied to the cart.
      Defaults to `true`.
  validFrom?:
    type: datetime
    description: ''
  validUntil?:
    type: datetime
    description: ''
  requiresDiscountCode:
    type: boolean
    description: |-
      States whether the discount can only be used in a connection with a DiscountCode.
      Defaults to `false`.
  stackingMode?:
    type: StackingMode
    description: |-
      Specifies whether the application of this discount causes the following discounts to be ignored.
      Defaults to Stacking.
  custom?:
    type: CustomFields
    description: ''
