#%RAML 1.0 DataType
(package): CartDiscount
type: CartDiscountValueDraft
displayName: CartDiscountValueAbsoluteDraft
discriminatorValue: absolute
example: !include ../../examples/CartDiscount/CartDiscountValueAbsoluteDraft.json
properties:
  money:
    type: Money[]
    description: |
      Money values in different currencies.
      An absolute Cart Discount will match a price only if the array contains a value with the same currency. For example, if it contains 10€ and 15$, the matching € price will be decreased by 10€ and the matching $ price will be decreased by 15$.

      If the array is empty or has multiple values of the same currency, the API returns an [InvalidOperation](ctp:api:type:InvalidOperationError) error.
  applicationMode?:
    type: DiscountApplicationMode
    description: |
      Determines how the discount applies on [CartDiscountLineItemTarget](ctp:api:type:CartDiscountLineItemsTarget) and [CartDiscountCustomLineItemTarget](ctp:api:type:CartDiscountCustomLineItemsTarget).

      If not set, the default behavior is `ProportionateDistribution`.
