#%RAML 1.0 DataType
(package): CartDiscount
(docs-uri): https://docs.commercetools.com/http-api-projects-cartDiscounts.html#cartdiscount
displayName: CartDiscount
(updateType): CartDiscountUpdate
type: BaseResource
(java-extends): 'com.commercetools.api.models.DomainResource<CartDiscount>'
properties:
  id:
    (identifier): true
    type: string
    description: The unique ID of the cart discount.
  version:
    type: number
    format: int64
    description: The current version of the cart discount.
  createdAt:
    type: datetime
    description: ''
  lastModifiedAt:
    type: datetime
    description: ''
  lastModifiedBy?:
    type: LastModifiedBy
    description:
      Present on resources updated after 1/02/2019 except for events not
      tracked.
  createdBy?:
    type: CreatedBy
    description:
      Present on resources created after 1/02/2019 except for events not
      tracked.
  name:
    type: LocalizedString
    description: ''
  key?:
    type: string
    description: |-
      User-specific unique identifier for a cart discount.
      Must be unique across a project.
  description?:
    type: LocalizedString
    description: ''
  value:
    type: CartDiscountValueDraft
    description: ''
  cartPredicate:
    type: string
    description: A valid Cart predicate.
  target?:
    type: CartDiscountTarget
    description: Empty when the `value` has type `giftLineItem`, otherwise a
      CartDiscountTarget is set.
  sortOrder:
    type: string
    description: |-
      The string must contain a number between 0 and 1.
      All matching cart discounts are applied to a cart in the order defined by this field.
      A discount with greater sort order is prioritized higher than a discount with lower sort order.
      The sort order is unambiguous among all cart discounts.
  isActive:
    type: boolean
    description: Only active discount can be applied to the cart.
  validFrom?:
    type: datetime
    description: ''
  validUntil?:
    type: datetime
    description: ''
  requiresDiscountCode:
    type: boolean
    description:
      States whether the discount can only be used in a connection with a
      DiscountCode.
  references:
    type: Reference[]
    description: |-
      The platform will generate this array from the predicate.
      It contains the references of all the resources that are addressed in the predicate.
  stackingMode:
    type: StackingMode
    description: |-
      Specifies whether the application of this discount causes the following discounts to be ignored.
      Defaults to Stacking.
  custom?:
    type: CustomFields
    description: ''
