#%RAML 1.0 DataType
(package): CartDiscount
displayName: CartDiscountDraft
type: object
example: !include ../../examples/cart-discount-create.example.json
properties:
  name:
    type: LocalizedString
    description: |
      Name of the CartDiscount.
  key?:
    type: string
    description: |
      User-defined unique identifier for the CartDiscount.
    pattern: ^[A-Za-z0-9_-]+$
    minLength: 2
    maxLength: 256
  description?:
    type: LocalizedString
    description: |
      Description of the CartDiscount.
  value:
    type: CartDiscountValueDraft
    description: |
      Effect of the CartDiscount on the `target`.
  cartPredicate:
    type: string
    description: |
      Valid [Cart Predicate](/../api/projects/predicates#cart-predicates).
  target?:
    type: CartDiscountTarget
    description: |
      Segment of the Cart that will be discounted.

      Must not be set if the `value` is `giftLineItem`.
  sortOrder?:
    type: string
    description: |
      Value between `0` and `1` that determines the order in which the CartDiscounts will be applied; a CartDiscount with a higher value will be prioritized.

      It must be unique among all CartDiscounts and DiscountGroups.

      If the CartDiscount is part of a DiscountGroup, it will use the sort order of the DiscountGroup.
  stores?:
    type: StoreResourceIdentifier[]
    maxItems: 500
    description: |
      - If defined, the Cart Discount applies on [Carts](ctp:api:type:Cart) having a [Store](ctp:api:type:Store) matching any Store defined for this field.
      - If not defined, the Cart Discount applies on all Carts, irrespective of a Store.

      If the referenced Stores exceed the [limit](/../api/limits#cart-discounts-stores), a [MaxStoreReferencesReached](ctp:api:type:MaxStoreReferencesReachedError) error is returned.

      If the referenced Stores exceed the [limit](/../api/limits#cart-discounts) for Cart Discounts that do not require a Discount Code, a [StoreCartDiscountsLimitReached](ctp:api:type:StoreCartDiscountsLimitReachedError) error is returned.
  isActive?:
    type: boolean
    description: |
      Only active Discounts can be applied to the Cart.
      If the [limit](/../api/limits#cart-discounts) for active Cart Discounts is reached, a [MaxCartDiscountsReached](ctp:api:type:MaxCartDiscountsReachedError) error is returned.
    default: true
  validFrom?:
    type: datetime
    description: |
      Date and time (UTC) from which the Discount is effective.
  validUntil?:
    type: datetime
    description: |
      Date and time (UTC) until which the Discount is effective.
  requiresDiscountCode?:
    type: boolean
    description: |
      States whether the Discount can only be used in a connection with a [DiscountCode](ctp:api:type:DiscountCode).
    default: false
  stackingMode?:
    type: StackingMode
    description: |
      Specifies whether the application of this discount causes the following discounts to be ignored.
    default: Stacking
  custom?:
    type: CustomFieldsDraft
    description: |
      Custom Fields of the CartDiscount.
  discountGroup?:
    type: DiscountGroupResourceIdentifier
    description: |
      Reference to a DiscountGroup that the CartDiscount must belong to.
  recurringOrderScope?:
    type: RecurringOrderScopeDraft
    description: |
      Scope of the Cart Discount for Recurring Orders.

      If not set, the default is [NonRecurringOrdersOnlyDraft](ctp:api:type:NonRecurringOrdersOnlyDraft).
