#%RAML 1.0 DataType
(package): CartDiscount
type: string
displayName: DiscountApplicationMode
description: |
  This mode determines how Discounts are distributed among items in a Cart.
(enumDescriptions):
  ProportionateDistribution: Distributes the Discount proportionately across eligible Line Items or Custom Line Items.
  EvenDistribution: Distributes the Discount evenly across eligible Line Items or Custom Line Items.
  IndividualApplication: Applies the Discount individually to eligible Line Item or Custom Line Item.
enum:
  - ProportionateDistribution
  - EvenDistribution
  - IndividualApplication
