#%RAML 1.0 DataType
(package): CartDiscount
type: CartDiscountTarget
displayName: MultiBuyCustomLineItemsTarget
discriminatorValue: multiBuyCustomLineItems
description: |
  This Discount target is similar to `MultiBuyLineItems`, but is applied on Custom Line Items instead of Line Items.
properties:
  predicate:
    type: string
    description: |
      Valid [CustomLineItems target predicate](/../api/projects/predicates#customlineitem-field-identifiers). The Discount will be applied to Custom Line Items that are matched by the predicate.
  triggerQuantity:
    type: integer
    description: |
      Number of Custom Line Items to be present in order to trigger an application of this Discount.
  discountedQuantity:
    type: integer
    description: |
      Number of Custom Line Items that are discounted per application of this Discount.
  maxOccurrence?:
    type: integer
    description: |
      Maximum number of times this Discount can be applied.
  selectionMode:
    type: SelectionMode
    description: |
      Discounts particular Line Items only according to the SelectionMode.
