#%RAML 1.0 DataType
(package): TaxCategory
type: object
displayName: TaxCategoryUpdateAction
discriminator: action
(java-extends): 'com.commercetools.api.models.ResourceUpdateAction<TaxCategoryUpdateAction>'
properties:
  action:
    type: string
