#%RAML 1.0 DataType
(package): TaxCategory
(docs-uri): https://docs.commercetools.com/api/projects/taxCategories#taxrate
type: object
displayName: TaxRate
properties:
  id?:
    type: string
    description: |
      Present if the TaxRate is part of a [TaxCategory](ctp:api:type:TaxCategory).
      Absent for external TaxRates in [LineItem](ctp:api:type:LineItem), [CustomLineItem](ctp:api:type:CustomLineItem), and [ShippingInfo](ctp:api:type:ShippingInfo).
  key?:
    type: string
    description: |
      User-defined unique identifier of the TaxRate.
      Present when set using [TaxRateDraft](ctp:api:type:TaxRateDraft). Not available for external TaxRates created using [ExternalTaxRateDraft](ctp:api:type:ExternalTaxRateDraft).
    pattern: ^[a-zA-Z0-9_-]
    minLength: 2
    maxLength: 256
  name:
    type: string
    description: |
      Name of the TaxRate.
  amount:
    type: number
    minimum: 0
    maximum: 1
    description: |
      Tax rate. If subrates are used, the amount must be the sum of all subrates.
  includedInPrice:
    type: boolean
    description: |
      If `true`, tax is included in [Embedded Prices](ctp:api:type:Price) or [Standalone Prices](ctp:api:type:StandalonePrice), and the `taxedPrice` is present on [LineItems](ctp:api:type:LineItem). In this case, the `totalNet` price on [TaxedPrice](ctp:api:type:TaxedPrice) includes the TaxRate.
  country:
    type: CountryCode
    description: |
      Country in which the tax rate is applied in [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) format.
  state?:
    type: string
    description: |
      State within the country, such as Texas in the United States.
  subRates?:
    type: SubRate[]
    description: |
      Used to calculate the [taxPortions](/../api/projects/carts#taxedprice) field in a Cart or Order. It is useful if the total tax of a country (such as the US) is a combination of multiple taxes (such as state and local taxes).
