#%RAML 1.0 DataType
(package): Extension
type: ExtensionHttpDestinationAuthentication
displayName: ExtensionAuthorizationHeaderAuthentication
discriminatorValue: AuthorizationHeader
properties:
  headerValue:
    type: string
