#%RAML 1.0 DataType
(package): Extension

type: Resource
displayName: Extension

properties:
  key?:
    type: string
  destination:
    type: ExtensionDestination
  triggers:
    type: ExtensionTrigger[]
