#%RAML 1.0 DataType
(package): Extension


type: object
displayName: ExtensionDraft


properties:
  key?:
    type: string
  destination:
    type: ExtensionDestination
  triggers:
    type: ExtensionTrigger[]
  timeoutInMs?:
    type: integer
