#%RAML 1.0 DataType
(package): TaxCategory


type: Resource
displayName: TaxCategory
(generate-collection): true
properties:
    name:
        type: string
    description?:
        type: string
    rates:
        type: TaxRate[]
