#%RAML 1.0 DataType
(package): TaxCategory


type: TaxCategoryUpdateAction
displayName: TaxCategoryReplaceTaxRateAction
discriminatorValue: replaceTaxRate
properties:
    taxRateId:
        type: string
    taxRate:
        type: TaxRateDraft
