#%RAML 1.0 DataType
(package): TaxCategory


type: TaxCategoryUpdateAction
displayName: TaxCategoryRemoveTaxRateAction
discriminatorValue: removeTaxRate
properties:
    taxRateId:
        type: string
