#%RAML 1.0 DataType
(package): TaxCategory


type: TaxCategoryUpdateAction
displayName: TaxCategorySetKeyAction
discriminatorValue: setKey
(postman-example): |
  {
    "action": "setKey",
    "key": "new Key"
  }
properties:
    key?:
        type: string
