#%RAML 1.0 DataType
(package): TaxCategory


type: TaxCategoryUpdateAction
displayName: TaxCategoryRemoveTaxRateAction
discriminatorValue: removeTaxRate
(postman-example): |
  {
    "action": "removeTaxRate",
    "taxRateId": "{{taxRateID}}"
  }
properties:
    taxRateId:
        type: string
