#%RAML 1.0 DataType
(package): StagedQuote
type: StagedQuoteUpdateAction
displayName: StagedQuoteChangeStagedQuoteStateAction
discriminatorValue: changeStagedQuoteState
example: !include ../../../examples/StagedQuote/StagedQuoteChangeStagedQuoteStateAction.json
properties:
  stagedQuoteState:
    type: StagedQuoteState
    description: New state to be set for the Staged Quote.
