#%RAML 1.0 DataType
(package): StagedQuote
type: StagedQuoteUpdateAction
displayName: StagedQuoteSetValidToAction
discriminatorValue: setValidTo
example: !include ../../../examples/StagedQuote/StagedQuoteSetValidToAction.json
properties:
  validTo?:
    type: datetime
    description: |
      If `validTo` is absent or `null`, this field will be removed if it exists.
