#%RAML 1.0 DataType
(package): Me
(docs-uri): https://docs.commercetools.com/http-api-projects-me-shoppingLists#add-textlineitem

type: MyShoppingListUpdateAction
displayName: MyShoppingListAddTextLineItemAction
discriminatorValue: addTextLineItem

properties:
  name:
    type: LocalizedString
  description?:
    type: LocalizedString
  quantity?:
    type: number
    format: int64
  addedAt?:
    type: datetime
  custom?:
    type: CustomFieldsDraft
