#%RAML 1.0 DataType
(package): Me
(docs-uri): https://docs.commercetools.com/http-api-projects-me-shoppingLists#change-lineitem-quantity

type: MyShoppingListUpdateAction
displayName: MyShoppingListChangeLineItemQuantityAction
discriminatorValue: changeLineItemQuantity

properties:
  lineItemId:
    type: string
  quantity:
    type: number
    format: int64
