#%RAML 1.0 DataType
(package): Me
(docs-uri): https://docs.commercetools.com/http-api-projects-me-shoppingLists#change-name

type: MyShoppingListUpdateAction
displayName: MyShoppingListChangeNameAction
discriminatorValue: changeName

properties:
  name:
    type: LocalizedString
