#%RAML 1.0 DataType
(annotations.package): Callbacks
displayName: Cart
type: object
properties:
  id:
    type: string
    description: The ID of the cart.
  type:
    type: CartTypeEnum
    description: |
      One of `sale`, `order`, `return`.
  cart_origin:
    type: string
    description: The name/ID of the system that created the cart.
  cart_total:
    type: integer
    description: The total cost of the cart in the smallest currency unit.
  transaction_line_items:
    type: TransactionLineItem[]
    description: Array of `TransactionLineItem` objects for items in the cart.
  tender_line_items?:
    type: Tender[]
    description: Array of Tender objects for payments on the cart.
