#%RAML 1.0 DataType
(annotations.package): Sessions
displayName: Cash
description: |-
  Cash details for the Cash tender type
type: Tender
discriminatorValue: Cash
example: !include ../../examples/sessions/cash.json
properties:
  tender_type: TenderType
