#%RAML 1.0 DataType
(annotations.package): Callbacks
displayName: ItemAttribute
type: object
example: !include ../../examples/callbacks/item-attribute.json
properties:
  label:
    description: |-
      Label for the attribute  example:
      "Brand"
    required: true
    type: string
  value:
    description: |-
      Value of the attribute  example:
      "Levi's"
    required: true
    type: string
