#%RAML 1.0 DataType
(annotations.package): Callbacks
displayName: PriceModifier
type: object
example: !include ../../examples/callbacks/price-modifier.json
properties:
  description:
    description: |-
      Description of the price modifier  example:
      "25% discount"
    required: true
    type: string
  amount:
    description: |-
      The amount of the discount in the smallest currency unit  example:
      8000
    required: true
    type: number
