#%RAML 1.0 DataType
(annotations.package): Sessions
displayName: TaxType
type: object
properties:
  code:
    description: |-
      Code representing the tax category for this entry - maps to line item tax_code  example:
      "T"
    required: true
    type: string
  total_net:
    description: |-
      Total value of the items in this tax category before tax, in minor currency units  example:
      20000
    required: true
    type: number
  total_gross:
    description: |-
      Total value of the items in this tax category, including tax, in minor currency units  example:
      24000
    required: true
    type: number
  tax_rate:
    description: |-
      Tax rate for this category expressed as a percentage  example:
      20
    required: true
    type: number
  total_tax:
    description: |-
      Tax amount associated with the given code, in minor currency units  example:
      4000
    required: true
    type: number
