#%RAML 1.0
---
title: commercetools Frontend API hub API
annotationTypes:
  package:
    type: string
    allowedTargets: TypeDeclaration
  products:
    allowedTargets:
      - API
    type: array
    items:
      type: string
(products):
  - Frontend

baseUri: https://{project}-{customer}.frontastic.io
baseUriParameters:
  project:
    description: Project Name
    type: string
    required: true
  customer:
    description: Customer Name
    type: string
    required: true
version: 2.0.0

types:
  DataSourceConfiguration: !include types/DataSourceConfiguration.raml
  DataSourceResponse: !include types/DataSourceResponse.raml
  DataSources: !include types/DataSources.raml
  Environment: !include types/Environment.raml
  Error: !include types/Error.raml
  Footer: !include types/Footer.raml
  Head: !include types/Head.raml
  LayoutElement: !include types/LayoutElement.raml
  LayoutElementConfiguration: !include types/LayoutElementConfiguration.raml
  Locale: !include types/Locale.raml
  Main: !include types/Main.raml
  Page: !include types/Page.raml
  PageDataResponse: !include types/PageDataResponse.raml
  PageFolder: !include types/PageFolder.raml
  PagePreviewContext: !include types/PagePreviewContext.raml
  PagePreviewDataResponse: !include types/PagePreviewDataResponse.raml
  PathConfiguration: !include types/PathConfiguration.raml
  ProjectContext: !include types/ProjectContext.raml
  RedirectResponse: !include types/RedirectResponse.raml
  Sections: !include types/Sections.raml
  Tastic: !include types/Tastic.raml
  TasticConfiguration: !include types/TasticConfiguration.raml
  ViewData: !include types/ViewData.raml

traits:
  right-header:
    headers:
      Accept:
        displayName: Accept Header
        type: string
        description: Accept application/json Header
        required: true
        pattern: ^application/json$
        default: application/json
  frontastic-locale:
    headers:
      Frontastic-Locale:
        displayName: Frontastic Locale
        type: Locale
        description: Locale
  action-errorable:
    responses:
      400:
        description: Action not registered.
        body:
          application/json:
            type: Error
            example: !include ./examples/action-error.json

/frontastic:
  /context: !include resources/FrontasticContext.raml
  /page: !include resources/FrontasticPage.raml
  /preview: !include resources/FrontasticPreview.raml
  /action: !include resources/FrontasticAction.raml
  /data-source: !include resources/FrontasticDataSource.raml
