#%RAML 1.0 DataType
(package): State
type: string
description: |
  Resource or object type the State can be assigned to.
(enumDescriptions):
  OrderState: Used by [Orders](ctp:api:type:Order).
  LineItemState: Used by [LineItems](ctp:api:type:LineItem) and [CustomLineItems](ctp:api:type:CustomLineItem) in [Carts](ctp:api:type:Cart) and [Orders](ctp:api:type:Order).
  ProductState: Used by [Products](ctp:api:type:Product).
  ReviewState: Used by [Reviews](ctp:api:type:Review).
  PaymentState: Used by [PaymentStatus](ctp:api:type:PaymentStatus) in [Payments](ctp:api:type:Payment).
  QuoteRequestState: Used by [QuoteRequest](ctp:api:type:QuoteRequest).
  StagedQuoteState: Used by [StagedQuote](ctp:api:type:StagedQuote).
  QuoteState: Used by [Quote](ctp:api:type:Quote).
enum:
  - OrderState
  - LineItemState
  - ProductState
  - ReviewState
  - PaymentState
  - QuoteRequestState
  - StagedQuoteState
  - QuoteState
