#%RAML 1.0 DataType
(package): ProductSearch
type: ErrorResponse
displayName: ProductSearchErrorResponse
properties:
  statusCode:
    description: The HTTP status code of the response.
    type: integer
  message:
    description: Describes the error.
    type: string
  errors?:
    description: |
      The errors that caused this error response.
    type: ErrorObject[]
