#%RAML 1.0 DataType
(package): ProductSearch
displayName: ProductSearchMatchingVariantEntry
type: object
properties:
  id:
    type: number
    format: int32
    description: |
      `id` of the [ProductVariant](ctp:api:type:ProductVariant) that matches the search query.
  sku?:
    type: string
    description: |
      `sku` of the ProductVariant that matches the search query.
