#%RAML 1.0 DataType
(package): ProductSearch
type: object
displayName: ProductSearchRequest
# example: !include ../../examples/ProductSearch/product-search-request.example.json
properties:
  query?:
    type: ProductSearchQuery
    description: The Product search query.
  postFilter?:
    type: ProductSearchQuery
  sort?:
    type: ProductSearchSorting[]
    description: Controls how results to your query are sorted. If not provided, the results are sorted by relevance in descending order.
  limit?:
    type: number
    format: int32
    default: 20
    maximum: 100
    description: The maximum number of search results to be returned.
  offset?:
    type: number
    format: int32
    default: 0
    maximum: 10000
    description: The number of search results to be skipped in the response for pagination.
  markMatchingVariants?:
    type: boolean
    default: false
    description: The search can return Products where not all Product Variants match the search criteria. If `true`, the response will include a field called `matchingVariants` that contains the `sku` of Product Variants that match the search query. If the query does not specify any variant-level criteria, `matchingVariants` will be null signifying that all Product Variants are a match.

  projection?:
    type: ProductSearchProjectionParams
    description: Contains Product Projection query parameters. Used to fetch matching Product Projection data of products matching the search query. If not included, Product Projection integration is not used.
  facets?:
    type: ProductSearchFacetExpression[]
