#%RAML 1.0 DataType
(package): ProductSearch
displayName: ProductSearchMatchingVariants
type: object
properties:
  allMatched:
    type: boolean
    description: |
      `true` if all Variants of the returned Product match the search query, or if search query does not specify any expression for a [Product Variant field](/../api/projects/product-search#field-levels).

      `false` if only a subset of the Product Variants match the search query.

      Is always `false` for query expressions on Product Variant fields.
  matchedVariants:
    type: ProductSearchMatchingVariantEntry[]
    description: |
      Identifiers of the Product Variants that match the search query.

      Empty if all Product Variants of the returned Product match.
