#%RAML 1.0 DataType
(package): ProductSearch
type: object
displayName: ProductSearchSorting
properties:
  field:
    type: string
  language?:
    type: Locale
  order:
    type: ProductSearchSortOrder
  mode?:
    type: ProductSearchSortMode
  attributeType?:
    type: ProductSearchAttributeType
  filter?:
    type: ProductSearchQueryExpression
