#%RAML 1.0 DataType
(package): ProductSearch
displayName: ProductSearchAttributeType
type: string
enum:
  - boolean
  - text
  - ltext
  - enum
  - lenum
  - number
  - money
  - date
  - datetime
  - time
  - reference
  - set_boolean
  - set_text
  - set_ltext
  - set_enum
  - set_lenum
  - set_number
  - set_money
  - set_date
  - set_datetime
  - set_time
  - set_reference
