#%RAML 1.0 DataType
(package): Customer
(docs-uri): https://docs.commercetools.com/api/projects/customers#add-billing-address-id
type: CustomerUpdateAction
displayName: CustomerAddBillingAddressIdAction
discriminatorValue: addBillingAddressId
example: !include ../../../examples/Customer/CustomerAddBillingAddressIdAction.json
description: |
  Adds an Address from the `addresses` array to `billingAddressIds`. Either `addressId` or `addressKey` is required.
properties:
  addressId?:
    type: string
    description: |
      `id` of the [Address](ctp:api:type:Address) to become a billing address.
  addressKey?:
    type: string
    description: |
      `key` of the [Address](ctp:api:type:Address) to become a billing address.
