#%RAML 1.0 DataType
(package): Customer
type: CustomerUpdateAction
displayName: CustomerSetAuthenticationModeAction
discriminatorValue: setAuthenticationMode
example: !include ../../../examples/Customer/CustomerSetAuthenticationModeAction.json
properties:
  authMode:
    type: AuthenticationMode
    description: |
      Value to set.
      Changing a Customer's `authMode` from `Password` to `ExternalAuth` deletes the Customer's password.
  password?:
    type: string
    description: |
      Required when `authMode` is `Password`.
