#%RAML 1.0 DataType
(package): Customer
type: CustomerUpdateAction
displayName: CustomerSetDefaultShippingAddressAction
discriminatorValue: setDefaultShippingAddress
example: !include ../../../examples/Customer/CustomerSetDefaultShippingAddressAction.json
description: |
  Sets the default shipping address from `addresses`.
  The action adds the `id` of the specified address to the `shippingAddressIds` if not contained already. Either `addressId` or `addressKey` is required.

  If the Tax Category of the Cart [ShippingInfo](ctp:api:type:ShippingInfo) is missing the TaxRate matching country and state given in the `shippingAddress` of that Cart, a [MissingTaxRateForCountry](ctp:api:type:MissingTaxRateForCountryError) error is returned.
properties:
  addressId?:
    type: string
    description: |
      `id` of the [Address](ctp:api:type:Address) to become the default shipping address.
  addressKey?:
    type: string
    description: |
      `key` of the [Address](ctp:api:type:Address) to become the default shipping address.
