#%RAML 1.0 DataType
(package): Customer
(docs-uri): https://docs.commercetools.com/http-api-projects-customers.html#remove-billing-address-id
type: CustomerUpdateAction
displayName: CustomerRemoveBillingAddressIdAction
discriminatorValue: removeBillingAddressId
(postman-example): !include ../../../examples/Customer/CustomerRemoveBillingAddressIdAction.json
properties:
  addressId?:
    type: string
    description: ''
  addressKey?:
    type: string
    description: ''
