#%RAML 1.0 DataType
(package): Customer
type: CustomerUpdateAction
displayName: CustomerSetDefaultBillingAddressAction
discriminatorValue: setDefaultBillingAddress
example: !include ../../../examples/Customer/CustomerSetDefaultBillingAddressAction.json
description: |
  Sets the default billing address from `addresses`.
  The action adds the `id` of the specified Address to the `billingAddressIds` if not contained already. Either `addressId` or `addressKey` is required.
properties:
  addressId?:
    type: string
    description: |
      `id` of the [Address](ctp:api:type:Address) to become the default billing address.
  addressKey?:
    type: string
    description: |
      `key` of the [Address](ctp:api:type:Address) to become the default billing address.
