#%RAML 1.0 DataType
(package): Customer
(docs-uri): https://docs.commercetools.com/api/projects/customers#set-custom-type
type: CustomerUpdateAction
displayName: CustomerSetCustomTypeAction
discriminatorValue: setCustomType
example: !include ../../../examples/Customer/CustomerSetCustomTypeAction.json
properties:
  type?:
    type: TypeResourceIdentifier
    description: |
      Defines the [Type](ctp:api:type:Type) that extends the Customer with [Custom Fields](/../api/projects/custom-fields).
      If absent, any existing Type and Custom Fields are removed from the Customer.
  fields?:
    type: FieldContainer
    description: |
      Sets the [Custom Fields](/../api/projects/custom-fields) fields for the Customer.
