#%RAML 1.0 DataType
(package): Customer
(docs-uri): https://docs.commercetools.com/api/projects/customers#change-email
type: CustomerUpdateAction
displayName: CustomerChangeEmailAction
discriminatorValue: changeEmail
example: !include ../../../examples/Customer/CustomerChangeEmailAction.json
description: |
  Changing the email of the Customer produces the [CustomerEmailChanged](ctp:api:type:CustomerEmailChangedMessage) Message.
properties:
  email:
    type: string
    description: |
      Value to set.
