#%RAML 1.0 DataType
(package): Customer
(docs-uri): https://docs.commercetools.com/http-api-projects-customers.html#set-key
type: CustomerUpdateAction
displayName: CustomerSetKeyAction
discriminatorValue: setKey
(postman-example): !include ../../../examples/Customer/CustomerSetKeyAction.json
properties:
  key?:
    type: string
    description: If `key` is absent or `null`, this field will be removed if it exists.
