#%RAML 1.0 DataType
(annotations.package): Error
(annotations.beta): true
type: ErrorObject
displayName: ConnectorFailedError
discriminatorValue: ConnectorFailed
description: |
  Returned when the payment [Connector](/payment-connectors-applications#payment-connectors) cannot be reached.
properties:
  code:
    type: string
  message:
    type: string
    description: |
      `"The connector could not be reached."`
