#%RAML 1.0 DataType
(annotations.package): Error
(annotations.beta): true
type: ErrorObject
displayName: DuplicateFieldWithConflictingResourceError
discriminatorValue: DuplicateFieldWithConflictingResource
description: |
  Returned when a field value conflicts with an existing value stored in a particular resource causing a duplicate.
properties:
  code:
    type: string
  message:
    type: string
    description: |
      `"A duplicate value $duplicateValue exists for field $field in request."`
