#%RAML 1.0 DataType
(annotations.package): Error
(annotations.beta): true
type: ErrorObject
displayName: InternalConstraintViolatedError
discriminatorValue: InternalConstraintViolated
description: |
  Returned when the referenced resources violate a constraint required for the operation, for example, when a Cart and a PaymentMethod are expected to belong to the same customer but do not.
properties:
  code:
    type: string
    description: |
      Error code, always `InternalConstraintViolated`.
  message:
    type: string
    description: |
      Description of the error.
