#%RAML 1.0 DataType
(annotations.package): Error
(annotations.beta): true
type: ErrorObject
displayName: InvalidJsonInputError
discriminatorValue: InvalidJsonInput
description: |
  Returned when an invalid JSON input has been sent.
  Either the JSON is syntactically incorrect or does not conform to the expected shape, for example, it is missing a required field.

  The client application should validate the input according to the constraints described in the error message before sending the request.
properties:
  code:
    type: string
  message:
    type: string
    description: |
      `"Request body does not contain valid JSON."`
  detailedErrorMessage?:
    type: string
    description: Further explanation about why the JSON is invalid.
