#%RAML 1.0 DataType
(package): Reservation
displayName: ReservationState
type: string
description: |
  Status of the [Reservation](ctp:api:type:Reservation).
enum:
  - Created
  - Updated
  - Released
  - Expired
  - Committed

(enumDescriptions):
  Created: |
    The `availableQuantity` of the item has been reduced by the reserved quantity, but the `quantityOnStock` remains unchanged.
  Updated: |
    The reservation has been updated. If the quantity of an item changed, the `availableQuantity` is increased or decreased accordingly, while the `quantityOnStock` remains unchanged.
  Released: |
    The reserved quantity of the item has been released. The `availableQuantity` is increased accordingly.
  Expired: |
    The reservation has expired and the `availableQuantity` is increased accordingly. Reservation expirations are [eventually consistent](/../api/general-concepts#eventual-consistency), meaning it can take a few minutes for the status to update after expiration.
  Committed: |
    The quantity of the item has been allocated for fulfillment. The `quantityOnStock` has been reduced by the reserved quantity.
