#%RAML 1.0 DataType
(package): StandalonePrice
type: StandalonePriceUpdateAction
displayName: StandalonePriceChangeActiveAction
discriminatorValue: changeActive
description: |
  Updating the value of a [StandalonePrice](ctp:api:type:StandalonePrice) produces the [StandalonePriceActiveChanged](ctp:api:type:StandalonePriceActiveChangedMessage) Message.
example: !include ../../../examples/StandalonePrice/StandalonePriceChangeActiveAction.json
properties:
  active:
    type: boolean
    description: |
      New value to set for the `active` field of the [StandalonePrice](ctp:api:type:StandalonePrice).
