#%RAML 1.0 DataType
(package): StandalonePrice
type: StandalonePriceUpdateAction
displayName: StandalonePriceChangeValueAction
discriminatorValue: changeValue
description: |
  Updating the value of a [StandalonePrice](ctp:api:type:StandalonePrice) produces the [StandalonePriceValueChangedMessage](ctp:api:type:StandalonePriceValueChangedMessage).
example: !include ../../../examples/StandalonePrice/StandalonePriceChangeValueAction.json
properties:
  value:
    type: Money
    description: |
      New value to set. Must not be empty.
  staged?:
    type: boolean
    default: false
    description: |
      If set to `true` the update action applies to the [StagedStandalonePrice](ctp:api:type:StagedStandalonePrice). If set to `false`, the update action applies to the current [StandalonePrice](ctp:api:type:StandalonePrice).
