#%RAML 1.0 DataType
(package): StandalonePrice
type: StandalonePriceUpdateAction
displayName: StandalonePriceApplyStagedChangesAction
discriminatorValue: applyStagedChanges
description: |
  Applies all staged changes to the StandalonePrice by overwriting all current values with the values in the [StagedStandalonePrice](ctp:api:type:StagedStandalonePrice). After successfully applied, the [StagedStandalonePrice](ctp:api:type:StagedStandalonePrice) will be removed from the StandalonePrice. An `applyStagedChanges` update action on a StandalonePrice that does not contain any staged changes will return a `400 Bad Request` error. Applying staged changes successfully will produce the [StandalonePriceStagedChangesApplied](ctp:api:type:StandalonePriceStagedChangesAppliedMessage) Message.
example: !include ../../../examples/StandalonePrice/StandalonePriceApplyStagedChangesAction.json
