#%RAML 1.0 DataType
(package): StandalonePrice
type: StandalonePriceUpdateAction
displayName: StandalonePriceSetValidFromAndUntilAction
discriminatorValue: setValidFromAndUntil
description: |
  Updating the `validFrom` and `validUntil` values generates the [StandalonePriceValidFromAndUntilSet](ctp:api:type:StandalonePriceValidFromAndUntilSetMessage) Message.

  As the validity dates are part of the price scope and are not allowed to overlap, this update might return the [DuplicateStandalonePriceScope](ctp:api:type:DuplicateStandalonePriceScopeError) and [OverlappingStandalonePriceValidity](ctp:api:type:OverlappingStandalonePriceValidityError) errors, respectively. A Price without validity period does not conflict with a Price defined for a time period.
example: !include ../../../examples/StandalonePrice/StandalonePriceSetValidFromAndUntilAction.json
properties:
  validFrom?:
    type: datetime
    description: |
      Value to set.
      If empty, any existing value is removed.
  validUntil?:
    type: datetime
    description: |
      Value to set.
      If empty, any existing value is removed.
