#%RAML 1.0 DataType
(package): StandalonePrice
(docs-uri): https://docs.commercetools.com/http-api-projects-standalone-prices#change-active
type: StandalonePriceUpdateAction
(beta): true
displayName: StandalonePriceChangeActiveAction
discriminatorValue: changeActive
description: |
  Updating the value of a [StandalonePrice](ctp:api:type:StandalonePrice) produces the [StandalonePriceActiveChangedMessage](ctp:api:type:StandalonePriceActiveChangedMessage).
example: !include ../../../examples/StandalonePrice/StandalonePriceChangeActiveAction.json
properties:
  active:
    type: boolean
    description: |
      New value to set for the `active` field of the [StandalonePrice](ctp:api:type:StandalonePrice).
