#%RAML 1.0 DataType
(package): StandalonePrice
type: StandalonePriceUpdateAction
displayName: StandalonePriceSetDiscountedPriceAction
discriminatorValue: setDiscountedPrice
description: |
  Discounts a Standalone Price. The referenced [ProductDiscount](ctp:api:type:ProductDiscount) in the discounted field must be of type external, active, and its predicate must match the referenced Price. Produces the [StandalonePriceExternalDiscountSet](ctp:api:type:StandalonePriceExternalDiscountSetMessage) Message.
example: !include ../../../examples/StandalonePrice/StandalonePriceSetDiscountedPriceAction.json
properties:
  discounted?:
    type: DiscountedPriceDraft
    description: |
      Value to set. If empty, any existing value will be removed.
