#%RAML 1.0 DataType
(package): ProductDiscount
(docs-uri): https://docs.commercetools.com/http-api-projects-productDiscounts.html#set-valid-from-and-until
type: ProductDiscountUpdateAction
displayName: ProductDiscountSetValidFromAndUntilAction
discriminatorValue: setValidFromAndUntil
(postman-example): !include ../../../examples/ProductDiscount/ProductDiscountSetValidFromAndUntilAction.json
properties:
  validFrom?:
    type: datetime
    description: ''
  validUntil?:
    type: datetime
    description: |-
      The timeframe for which the discount should be effective.
      Please take Eventual Consistency into account for calculated undiscounted values.
