#%RAML 1.0 DataType
(package): PaymentMethod
type: PaymentMethodUpdateAction
displayName: PaymentMethodSetCustomTypeAction
discriminatorValue: setCustomType
example: !include ../../../examples/PaymentMethod/PaymentMethodSetCustomTypeAction.json
(beta): true
description: |
  Adding or updating a Custom Type on a PaymentMethod generates the [PaymentMethodCustomTypeSet](ctp:api:type:PaymentMethodCustomTypeSetMessage) Message, removing one generates the [PaymentMethodCustomTypeRemoved](ctp:api:type:PaymentMethodCustomTypeRemovedMessage) Message.
properties:
  type?:
    type: TypeResourceIdentifier
    description: |
      Defines the [Type](ctp:api:type:Type) that extends the PaymentMethod with [Custom Fields](/../api/projects/custom-fields).
      If absent, any existing Type and Custom Fields are removed from the PaymentMethod.
  fields?:
    type: FieldContainer
    description: |
      Sets the [Custom Fields](/../api/projects/custom-fields) fields for the PaymentMethod.
