#%RAML 1.0 DataType
(package): PaymentMethod
type: PaymentMethodUpdateAction
displayName: PaymentMethodSetPaymentInterfaceAction
discriminatorValue: setPaymentInterface
example: !include ../../../examples/PaymentMethod/PaymentMethodSetPaymentInterfaceAction.json
(beta): true
description: |
  This action generates the [PaymentMethodPaymentInterfaceSet](ctp:api:type:PaymentMethodPaymentInterfaceSetMessage) Message.
properties:
  paymentInterface?:
    type: string
    description: |
      New payment service that processes the Payment—for example, a PSP.
      If empty, any existing value will be removed.
