#%RAML 1.0 DataType
(package): PaymentMethod
type: PaymentMethodUpdateAction
displayName: PaymentMethodSetDefaultAction
discriminatorValue: setDefault
example: !include ../../../examples/PaymentMethod/PaymentMethodSetDefaultAction.json
(beta): true
description: |
  This action generates the [PaymentMethodDefaultSet](ctp:api:type:PaymentMethodDefaultSetMessage) Message.

  An inactive Payment Method cannot be set as the default, and the action will return an [InvalidOperation](ctp:api:type:InvalidOperationError) error.
properties:
  default:
    type: boolean
    description: |
      Value to set.
