#%RAML 1.0 DataType
(package): PaymentMethod
type: PaymentMethodUpdateAction
displayName: PaymentMethodSetInterfaceAccountAction
discriminatorValue: setInterfaceAccount
example: !include ../../../examples/PaymentMethod/PaymentMethodSetInterfaceAccountAction.json
(beta): true
description: |
  This action generates the [PaymentMethodInterfaceAccountSet](ctp:api:type:PaymentMethodInterfaceAccountSetMessage) Message.
properties:
  interfaceAccount?:
    type: string
    description: |
      New account or instance of the payment interface.
      If empty, any existing value will be removed.
