#%RAML 1.0 DataType
(package): PaymentMethod
type: PaymentMethodUpdateAction
displayName: PaymentMethodSetMethodAction
discriminatorValue: setMethod
example: !include ../../../examples/PaymentMethod/PaymentMethodSetMethodAction.json
(beta): true
description: |
  This action generates the [PaymentMethodMethodSet](ctp:api:type:PaymentMethodMethodSetMessage) Message.
properties:
  method?:
    type: string
    description: |
      New payment method—for example, a credit card or cash advance.
      If empty, any existing value will be removed.
