#%RAML 1.0 DataType
(package): Common
(docs-uri): https://docs.commercetools.com/http-api-types#client-logging
displayName: ClientLogging
type: object
properties:
  clientId?:
    type: string
  externalUserId?:
    type: string
  customer?:
    type: CustomerReference
  anonymousId?:
    type: string
