#%RAML 1.0 DataType
(package): Common
(docs-uri): https://docs.commercetools.com/http-api-projects-products.html#discountedprice
displayName: DiscountedPrice
type: object
properties:
  value:
    type: Money
  discount:
    type: ProductDiscountReference
