#%RAML 1.0 DataType
(package): Type
(docs-uri): https://docs.commercetools.com/http-api-projects-custom-fields.html#custom
displayName: CustomFields
type: object
properties:
  type:
    description: ''
    type: TypeReference
  fields:
    type: FieldContainer
    description: A valid JSON object, based on FieldDefinition.
