#%RAML 1.0 DataType
(package): Type


type: FieldType
displayName: CustomFieldLocalizedEnumType
discriminatorValue: LocalizedEnum
properties:
    values:
        type: CustomFieldLocalizedEnumValue[]
