#%RAML 1.0 DataType
(package): Type


type: object
displayName: FieldDefinition
properties:
    type:
        type: object  # FieldType # ToDO: fix when discriminators are correctly resolved
    name:
        type: string
    label:
        type: LocalizedString
    required:
        type: boolean
    inputHint?:
        type: string
