#%RAML 1.0 DataType
(package): Type
(docs-uri): https://docs.commercetools.com/http-api-projects-types.html#fielddefinition
type: object
displayName: FieldDefinition
properties:
  type:
    type: FieldType
    description: Describes the type of the field.
  name:
    type: string
    description: |-
      The name of the field.
      The name must be between two and 36 characters long and can contain the ASCII letters A to Z in lowercase or uppercase, digits, underscores (`_`) and the hyphen-minus (`-`).
      The name must be unique for a given resource type ID.
      In case there is a field with the same name in another type it has to have the same FieldType also.
  label:
    type: LocalizedString
    description: A human-readable label for the field.
  required:
    type: boolean
    description: Whether the field is required to have a value.
  inputHint?:
    type: TypeTextInputHint
    description: |-
      Provides a visual representation type for this field.
      It is only relevant for string-based field types like StringType and LocalizedStringType.
