#%RAML 1.0 DataType


displayName: ResourceTypeId
type: string
enum:
- asset
- category
- customer
- order
- inventory-entry
- line-item
- custom-line-item
- product-price
- payment
- payment-interface-interaction
- review
