#%RAML 1.0 DataType
(package): Type
(docs-uri): https://docs.commercetools.com/http-api-projects-types.html#type
type: LoggedResource
displayName: Type
(updateType): TypeUpdate
properties:
  id:
    (identifier): true
    type: string
  version:
    type: number
    format: int64
  createdAt:
    type: datetime
  lastModifiedAt:
    type: datetime
  lastModifiedBy?:
    type: LastModifiedBy
  createdBy?:
    type: CreatedBy
  key:
    type: string
    (hasSimpleUpdateAction): changeKey
  name:
    type: LocalizedString
    (hasSimpleUpdateAction): changeName
  description?:
    type: LocalizedString
    (hasSimpleUpdateAction): setDescription
  resourceTypeIds:
    type: ResourceTypeId[]
  fieldDefinitions:
    type: FieldDefinition[]
    (hasUpdateActions):
    - action: addFieldDefinition
      docsAnchor: add-fielddefinition
      fields:
        fieldDefinition: FieldDefinition
    - action: removeFieldDefinition
      docsAnchor: remove-fielddefinition
      fields:
        fieldName: string
    - action: changeLabel
      fields:
        fieldName: string
        label: LocalizedString
    - action: addEnumValue
      docsAnchor: add-enumvalue-to-fielddefinition
      fields:
        fieldName: string
        value: CustomFieldEnumValue
    - action: addLocalizedEnumValue
      docsAnchor: add-localizedenumvalue-to-fielddefinition
      fields:
        fieldName: string
        value: CustomFieldLocalizedEnumValue
    - action: changeFieldDefinitionOrder
      docsAnchor: change-the-order-of-fielddefinitions
      fields:
        fieldNames: string[]
    - action: changeEnumValueOrder
      docsAnchor: change-the-order-of-enumvalues
      fields:
        fieldName: string
        keys: string[]
    - action: changeLocalizedEnumValueOrder
      docsAnchor: change-the-order-of-localizedenumvalues
      fields:
        fieldName: string
        keys: string[]
    - action: changeInputHint
      docsAnchor: change-inputhint
      fields:
        fieldName: string
        inputHint: TypeTextInputHint
    - action: changeEnumValueLabel
      docsAnchor: change-enumvalue-label
      fields:
        fieldName: string
        value: CustomFieldEnumValue
    - action: changeLocalizedEnumValueLabel
      docsAnchor: change-localizedenumvalue-label
      fields:
        fieldName: string
        value: CustomFieldLocalizedEnumValue
