#%RAML 1.0 DataType
(package): Type


type: TypeUpdateAction
displayName: TypeAddFieldDefinitionAction
discriminatorValue: addFieldDefinition
properties:
    fieldDefinition:
        type: FieldDefinition
