#%RAML 1.0 DataType
(package): Type


type: Resource
displayName: Type
properties:
    key:
        type: string
    name:
        type: LocalizedString
    description?:
        type: LocalizedString
    resourceTypeIds:
        type: ResourceTypeId[]
    fieldDefinitions:
        type: FieldDefinition[]
