#%RAML 1.0 DataType


type: Resource
displayName: Type
(generate-collection): true
properties:
    key:
        type: string
    name:
        type: LocalizedString
    description?:
        type: LocalizedString
    resourceTypeIds:
        type: array
    fieldDefinitions:
        type: FieldDefinition[]
