#%RAML 1.0 DataType
(package): Type


type: TypeUpdateAction
displayName: TypeAddLocalizedEnumValueAction
discriminatorValue: addLocalizedEnumValue
properties:
    fieldName:
        type: string
    value:
        type: CustomFieldLocalizedEnumValue
