#%RAML 1.0 DataType
(package): Search
type: object
displayName: SearchSorting
description: |
  Sorting parameters provided with a Search request.
properties:
  field:
    type: string
    description: |
      Use any searchable field of the resource as sort criterion, or `"score"` to sort by relevance score calculated by the API.
  language?:
    type: Locale
  order:
    type: SearchSortOrder
    description: |
      Specify the order in which the search results should be sorted.
      Can be `asc` for ascending, or `desc` for descending order.
  mode?:
    type: SearchSortMode
    description: |
      Specify the sort mode to be applied for a set-type `field`.
  fieldType?:
    type: SearchFieldType
    description: |
      Provide the data type of the given `field`.
  filter?:
    type: SearchQueryExpression
    description: |
      Allows you to apply a [sort filter](/../api/search-query-language#sort-filter).
