#%RAML 1.0 DataType
(package): Search
displayName: SearchMatchType
type: string
enum:
  - any
  - all
(enumDescriptions):
  any: |
    Returns resources for which at least one of the provided search terms match.
  all: |
    Returns only those resources for which all the provided search terms match.
