#%RAML 1.0 DataType
(package): Search
type: SearchQueryExpressionValue
displayName: SearchExactValue
properties:
  value?:
    type: any
  values?:
    type: any[]
  language?:
    type: Locale
  caseInsensitive?:
    type: boolean
