#%RAML 1.0 DataType
(package): Search
displayName: SearchFieldType
description: Possible values for the `fieldType` property on [query expressions](/../api/search-query-language#query-expressions) indicating the data type of the `field`.
type: string
enum:
  - boolean
  - text
  - ltext
  - enum
  - lenum
  - number
  - money
  - date
  - datetime
  - time
  - reference
  - set_boolean
  - set_text
  - set_ltext
  - set_enum
  - set_lenum
  - set_number
  - set_money
  - set_date
  - set_datetime
  - set_time
  - set_reference
(enumDescriptions):
  boolean: |
    For Boolean fields, [AttributeBooleanType](ctp:api:type:AttributeBooleanType) Attributes, and [BooleanType](ctp:api:type:CustomFieldBooleanType) Custom Fields.
  text: |
    For string fields, [AttributeTextType](ctp:api:type:AttributeTextType) Attributes, and [StringType](ctp:api:type:CustomFieldStringType) Custom Fields.
  ltext: |
    For [LocalizedString](types#localizedstring) fields, [AttributeLocalizableTextType](ctp:api:type:AttributeLocalizableTextType) Attributes,
    and [LocalizedStringType](ctp:api:type:CustomFieldLocalizedStringType) Custom Fields.
  enum: |
    For enum fields, [AttributeEnumType](ctp:api:type:AttributeEnumType) Attributes, and [EnumType](ctp:api:type:CustomFieldEnumType) Custom Fields.
  lenum: |
    For localized enum fields, [AttributeLocalizedEnumType](ctp:api:type:AttributeLocalizedEnumType) Attributes, and [LocalizedEnumType](ctp:api:type:CustomFieldLocalizedEnumType) Custom Fields.
  number: |
    For number fields, [AttributeNumberType](ctp:api:type:AttributeNumberType) Attributes, and [NumberType](ctp:api:type:CustomFieldNumberType) Custom Fields.
  money: |
    For [Money](types#money) fields and [AttributeMoneyType](ctp:api:type:AttributeMoneyType) Attributes.
  date: |
    For [Date](types#date) fields, [AttributeDateType](ctp:api:type:AttributeDateType) Attributes, and [DateType](ctp:api:type:CustomFieldDateType) Custom Fields.
  datetime: |
    For [DateTime](types#datetime) fields, [AttributeDateTimeType](ctp:api:type:AttributeDateTimeType) Attributes, and [DateTimeType](ctp:api:type:CustomFieldDateTimeType) Custom Fields.
  time: |
    For [Time](types#time) fields, [AttributeTimeType](ctp:api:type:AttributeTimeType) Attributes, and [TimeType](ctp:api:type:CustomFieldTimeType) Custom Fields.
  reference: |
    For [Reference](types#reference) fields and [AttributeReferenceType](ctp:api:type:AttributeReferenceType) Attributes.
  set_boolean: |
    For Set of Boolean fields, [AttributeSetType](ctp:api:type:AttributeSetType) of `boolean` Attributes, and [SetType](ctp:api:type:CustomFieldSetType) of `boolean` Custom Fields.
  set_text: |
    For Set of string fields, [AttributeSetType](ctp:api:type:AttributeSetType) of `text` Attributes, and [SetType](ctp:api:type:CustomFieldSetType) of `text` Custom Fields.
  set_ltext: |
    For Set of [LocalizedString](types#localizedstring) fields, [AttributeSetType](ctp:api:type:AttributeSetType) of `ltext` Attributes, and [SetType](ctp:api:type:CustomFieldSetType) of `ltext` Custom Fields.
  set_enum: |
    For Set of enum fields, [AttributeSetType](ctp:api:type:AttributeSetType) of `enum` Attributes, and [SetType](ctp:api:type:CustomFieldSetType) of `enum` Custom Fields.
  set_lenum: |
    For Set of localized enum fields, [AttributeSetType](ctp:api:type:AttributeSetType) of `lenum` Attributes, and [SetType](ctp:api:type:CustomFieldSetType) of `lenum` Custom Fields.
  set_number: |
    For Set of number fields, [AttributeSetType](ctp:api:type:AttributeSetType) of `number` Attributes, and [SetType](ctp:api:type:CustomFieldSetType) of `number` Custom Fields.
  set_money: |
    For Set of [Money](types#money) fields and [AttributeSetType](ctp:api:type:AttributeSetType) of `money` Attributes.
  set_date: |
    For Set of [Date](types#date) fields, [AttributeSetType](ctp:api:type:AttributeSetType) of `date` Attributes, and [SetType](ctp:api:type:CustomFieldSetType) of `date` Custom Fields.
  set_datetime: |
    For Set of [DateTime](types#datetime) fields, [AttributeSetType](ctp:api:type:AttributeSetType) of `datetime` Attributes, and [SetType](ctp:api:type:CustomFieldSetType) of `datetime` Custom Fields.
  set_time: |
    For Set of [Time](types#time) fields, [AttributeSetType](ctp:api:type:AttributeSetType) of `time` Attributes, and [SetType](ctp:api:type:CustomFieldSetType) of `time` Custom Fields.
  set_reference: |
    For Set of [Reference](types#reference) fields and [AttributeSetType](ctp:api:type:AttributeSetType) of `reference` Attributes.
