#%RAML 1.0 DataType
(package): State
(docs-uri): https://docs.commercetools.com/http-api-projects-states.html#change-state-key
type: StateUpdateAction
displayName: StateChangeKeyAction
discriminatorValue: changeKey
(postman-example): !include ../../../examples/State/StateChangeKeyAction.json
properties:
  key:
    type: string
