#%RAML 1.0 DataType
(package): RecurrencePolicy
type: Reference
displayName: RecurrencePolicyReference
discriminatorValue: recurrence-policy
description: |
  [Reference](ctp:api:type:Reference) to a [RecurrencePolicy](ctp:api:type:RecurrencePolicy).
properties:
  obj?:
    type: RecurrencePolicy
    description: |
      Contains the representation of the expanded RecurrencePolicy.
      Only present in responses to requests with [Reference Expansion](/../api/general-concepts#reference-expansion) for RecurrencePolicies.
  id:
    type: string
    description: |
      Unique identifier of the referenced [RecurrencePolicy](ctp:api:type:RecurrencePolicy).
