#%RAML 1.0 DataType
(package): RecurrencePolicy
type: RecurrencePolicySchedule
displayName: StandardSchedule
discriminatorValue: standard
description: |
  Schedule of a [RecurringOrder](ctp:api:type:RecurringOrder) that occurs at a fixed interval—for example, every two weeks or every month.
properties:
  value:
    type: number
    format: int64
    description: |
      Number of intervals between orders.
  intervalUnit:
    type: IntervalUnit
    description: |
      Interval of this schedule.
