#%RAML 1.0 DataType
(package): Customer
displayName: AnonymousCartSignInMode
type: string
description: |
  Determines how an anonymous Cart is handled when a Customer signs in. For more information, see [Cart merge during sign-in and sign-up](/../api/customers-overview#cart-merge-during-sign-in-and-sign-up).

enum:
  - MergeWithExistingCustomerCart
  - UseAsNewActiveCustomerCart
(enumDescriptions):
  MergeWithExistingCustomerCart: |
    The content of an anonymous [Cart is merged during sign-in](/../api/customers-overview#cart-merge-during-sign-in-and-sign-up) with the Customer's most recently modified active Cart.

  UseAsNewActiveCustomerCart: |
    Uses the anonymous Cart as the new active Customer Cart, replacing the existing one. No items from the previous active Cart are merged.
