#%RAML 1.0 DataType
(package): Customer
(docs-uri): https://docs.commercetools.com/api/projects/customers#customer
displayName: Customer
(updateType): CustomerUpdate
type: BaseResource
description: |
  If `stores` is not empty, the Customer is specific to those Stores.
properties:
  id:
    (identifier): true
    type: string
    description: |
      Unique identifier of the Customer.
  version:
    type: number
    format: int64
    description: |
      Current version of the Customer.
  key?:
    type: string
    description: |
      User-defined unique identifier of the Customer.
    pattern: ^[A-Za-z0-9_-]+$
    minLength: 2
    maxLength: 256
  customerNumber?:
    type: string
    description: |
      User-defined unique identifier of the Customer.

      Can be used to refer to a Customer in a human-readable way (in emails, invoices, and other correspondence).
  externalId?:
    type: string
    description: |
      Optional identifier for use in external systems like Customer Relationship Management (CRM) or Enterprise Resource Planning (ERP).
  createdAt:
    type: datetime
    description: |
      Date and time (UTC) the Customer was initially created.
  lastModifiedAt:
    type: datetime
    description: |
      Date and time (UTC) the Customer was last updated.
  lastModifiedBy?:
    type: LastModifiedBy
    (beta): true
    description: |
      Present on resources created after 1 February 2019 except for [events not tracked](/../api/general-concepts#events-tracked).
  createdBy?:
    type: CreatedBy
    (beta): true
    description: |
      Present on resources created after 1 February 2019 except for [events not tracked](/../api/general-concepts#events-tracked).
  email:
    type: string
    description: |
      Email address of the Customer that is [unique](/../api/customers-overview#customer-uniqueness) for an entire Project or to a Store the Customer is assigned to.
      It is the mandatory unique identifier of a Customer.
  password?:
    type: string
    description: |
      Present only when `authenticationMode` is set to `Password`.
  firstName?:
    type: string
    description: |
      Given name (first name) of the Customer.
  lastName?:
    type: string
    description: |
      Family name (last name) of the Customer.
  middleName?:
    type: string
    description: |
      Middle name of the Customer.
  title?:
    type: string
    description: |
      Title of the Customer, for example, 'Dr.'.
  dateOfBirth?:
    type: date-only
    description: |
      Date of birth of the Customer.
  companyName?:
    type: string
    description: |
      Company name of the Customer.
  vatId?:
    type: string
    description: |
      Individual VAT ID of the Customer.
  addresses:
    type: Address[]
    description: |
      Addresses used by the Customer.
  defaultShippingAddressId?:
    type: string
    description: |
      ID of the address in `addresses` used as the default shipping address.
  shippingAddressIds?:
    type: string[]
    description: |
      IDs of addresses in `addresses` used as shipping addresses.
  defaultBillingAddressId?:
    type: string
    description: |
      ID of the address in `addresses` used as the default billing address.
  billingAddressIds?:
    type: string[]
    description: |
      IDs of addresses in `addresses` used as billing addresses.
  isEmailVerified:
    type: boolean
    description: |
      Indicates whether the email address of the Customer is [verified](#email-verification-of-customer).
  customerGroup?:
    type: CustomerGroupReference
    description: |
      [CustomerGroup](ctp:api:type:CustomerGroup) to which the Customer belongs.
  custom?:
    type: CustomFields
    description: |
      Custom Fields for the Customer.
  locale?:
    type: Locale
    description: |
      Preferred language of the Customer.
  salutation?:
    type: string
    description: |
      Salutation of the Customer, for example, 'Mr.' or 'Mrs.'.
  stores?:
    type: StoreKeyReference[]
    description: |
      [Stores](ctp:api:type:Store) to which the Customer is assigned to.

      - If no Stores are specified, the Customer is a global customer, and can log in using the [Password Flow for global Customers](/../api/authorization#password-flow-for-global-customers).
      - If any Stores are specified, the Customer can only log in using the [Password Flow for Customers in a Store](/../api/authorization#password-flow-for-customers-in-a-store) for those specific Stores.
  authenticationMode:
    type: AuthenticationMode
    description: |
      Indicates whether the `password` is required for the Customer.
    default: Password
