#%RAML 1.0 DataType
(package): Customer
(docs-uri): https://docs.commercetools.com/api/projects/customers#customersigninresult
displayName: CustomerSignInResult
type: object
properties:
  customer:
    type: Customer
    description: |
      Customer [signed up](#create-sign-up-customer) or [signed in](#authenticate-sign-in-customer) after authentication.
  cart?:
    type: Cart
    description: |
      Cart associated with the Customer.
      If empty, the Customer does not have a Cart assigned.
