#%RAML 1.0 DataType
(package): Customer
type: object
(beta): true
displayName: CustomerGroupAssignment
example: !include ../../examples/Customer/CustomerGroupAssignment.json
description: |
  Represents an individual Customer Group assignment as a [Reference](ctp:api:type:Reference) to a [CustomerGroup](ctp:api:type:CustomerGroup).
properties:
  customerGroup:
    type: CustomerGroupReference
    description: |
      Reference to a Customer Group.
