#%RAML 1.0 DataType
(package): Customer
(docs-uri): https://docs.commercetools.com/api/projects/customers#customertoken
displayName: CustomerToken
type: object
example: !include ../../examples/Customer/CustomerToken.json
properties:
  id:
    type: string
    description: |
      Unique identifier of the token.
  customerId:
    type: string
    description: |
      The `id` of the Customer.
  value:
    type: string
    description: |
      Value of the token.
  expiresAt:
    type: datetime
    description: |
      Date and time (UTC) the token expires.
  createdAt:
    type: datetime
    description: |
      Date and time (UTC) the token was initially created.
  lastModifiedAt?:
    type: datetime
    description: |
      When the token is created, `lastModifiedAt` is set to `createdAt`.
