#%RAML 1.0 DataType
(package): Customer
displayName: CustomerSignInResult
type: object
properties:
  customer:
    type: Customer
    description: |
      Customer [signed up](ctp:api:endpoint:/{projectKey}/customers:POST) or [signed in](ctp:api:endpoint:/{projectKey}/login:POST) after authentication.
  cart?:
    type: Cart
    description: |
      Cart associated with the Customer.

      The Cart is recalculated to remove invalid Line Items and apply the latest prices, taxes, and discounts.
      During these updates, the following errors can be returned: [MatchingPriceNotFound](ctp:api:type:MatchingPriceNotFoundError) and [MissingTaxRateForCountry](ctp:api:type:MissingTaxRateForCountryError).

      For more information, see [Cart updates](/../api/carts-orders-overview#update-a-cart).
