#%RAML 1.0 DataType
(package): Customer
displayName: MyCustomerSignin
example: !include ../../examples/Customer/MyCustomerSignIn.json
type: object
properties:
  email:
    type: string
    description: |
      Email address of the Customer treated as [case-insensitive](/../api/customers-overview#email-case-insensitivity).
  password:
    type: string
    description: |
      Password of the Customer.
  activeCartSignInMode?:
    type: AnonymousCartSignInMode
    description: |
      - If `MergeWithExistingCustomerCart`, [LineItems](ctp:api:type:LineItem) of the anonymous Cart are merged with the recently modified active Customer Cart.
      - If `UseAsNewActiveCustomerCart`, the anonymous Cart is used as the new active Customer Cart, and no [LineItems](ctp:api:type:LineItem) are merged.
    default: MergeWithExistingCustomerCart
  updateProductData?:
    type: boolean
    description: |
      - If `true`, the [LineItem](ctp:api:type:LineItem) Product data (`name`, `variant`, and `productType`) of the returned Cart is updated.
      - If `false`, only the prices, discounts, and tax rates are updated.
    default: false
