#%RAML 1.0 DataType
(package): Quote
type: QuoteUpdateAction
displayName: QuoteRequestQuoteRenegotiationAction
discriminatorValue: requestQuoteRenegotiation
example: !include ../../../examples/Quote/QuoteRequestQuoteRenegotiationAction.json
description: |
  Represents the Buyer requesting renegotiation for a Quote. Valid for Quotes in a `Pending` [state](ctp:api:type:QuoteState).
properties:
  buyerComment?:
    type: string
    description: |
      Message from the [Buyer](/api/quotes-overview#buyer) regarding the Quote renegotiation request.
