#%RAML 1.0 DataType
(package): Quote
type: QuoteUpdateAction
displayName: QuoteChangeQuoteStateAction
discriminatorValue: changeQuoteState
example: !include ../../../examples/Quote/QuoteChangeQuoteStateAction.json
properties:
  quoteState:
    type: QuoteState
    description: New state to be set for the Quote.
