#%RAML 1.0 DataType
(package): Quote
type: QuoteUpdateAction
displayName: QuoteTransitionStateAction
discriminatorValue: transitionState
example: !include ../../../examples/Quote/QuoteTransitionStateAction.json
description: |
  If the existing [State](ctp:api:type:State) has set `transitions`, there must be a direct transition to the new State. If `transitions` is not set, no validation is performed. This update action produces the [Quote State Transition](ctp:api:type:QuoteStateTransitionMessage) Message.
properties:
  state:
    type: StateResourceIdentifier
    description: |
      Value to set.
      If there is no State yet, this must be an initial State.
  force?:
    type: boolean
    description: |
      Switch validations on or off.
    default: false
