#%RAML 1.0 DataType
(package): Common
displayName: LayoutElement
type: object
description: Layout Element
additionalProperties: true
properties:
  layoutElementId:
    type: string
  configuration:
    type: PageElementConfiguration
  tastics:
    type: Tastic[]
