#%RAML 1.0 DataType
#CellConfiguration in Frontastic Types
(package): Common
displayName: LayoutElementConfiguration
type: object
additionalProperties: true
properties:
  size:
    type: number
  mobile:
    type: boolean
  tablet:
    type: boolean
  desktop:
    type: boolean
