#%RAML 1.0 DataType
(package): Common
displayName: PageFolder
description: PageFolder
type: object
properties:
  pageFolderId:
    type: string
  isDynamic:
    type: boolean
  pageFolderType:
    type: string
  configuration:
    type: object
  dataSourceConfigurations:
    type: DataSourceConfiguration[]
  name:
    type: string
