#%RAML 1.0 DataType
(package): Common
displayName: Page
description: Page
type: object
(builtinType): object
properties:
  pageId:
    type: string
    (builtinType): string
  sections:
    type: Section
    (builtinType): object
    description: 3 sections "head", "main", "footer" with equal structure.
    properties:
      head:
        type: Section
        (builtinType): object
      main:
        type: Section
        (builtinType): object
      footer:
        type: Section
        (builtinType): object
