#%RAML 1.0 DataType
(package): Common
displayName: PathConfiguration
description: PathConfiguration
type: object
additionalProperties: true
properties:
  path:
    type: string
  pathTranslations:
    type: string[]
