#%RAML 1.0 DataType
(package): Common
displayName: PathConfiguration
description: PathConfiguration
type: object
(builtinType): object
additionalProperties: true
properties:
  path:
    type: string
    (builtinType): string
  pathTranslations:
    type: string[]
    (builtinType): array
