#%RAML 1.0 DataType
(package): Common
displayName: ProjectContext
type: object
properties:
  environment:
    type: Environment
    description: |
      Indicates whether the project is intended as production or development environment.
  locales:
    type: Locale[]
    description: |
      Locales that can be used in the project.
  defaultLocale:
    type: Locale
    description: |
      Locale used by default in the project.
