#%RAML 1.0 DataType
#TODO: should be renamed to TasticData in the future
(package): Common
displayName: Tastic
type: object
properties:
  tasticId:
    type: string
  tasticType:
    type: string
  configuration:
    type: TasticConfiguration
