#%RAML 1.0 DataType
(package): ProductType
type: ProductTypeUpdateAction
displayName: ProductTypeChangeEnumKeyAction
discriminatorValue: changeEnumKey
example: !include ../../../examples/ProductType/ProductTypeChangeEnumKeyAction.json
description: |
  Updates the key of a single enum `value` in an [AttributeEnumType](ctp:api:type:AttributeEnumType) AttributeDefinition, [AttributeLocalizedEnumType](ctp:api:type:AttributeLocalizedEnumType) AttributeDefinition, [AttributeSetType](ctp:api:type:AttributeSetType) of AttributeEnumType AttributeDefinition, or AttributeSetType of AttributeLocalizedEnumType AttributeDefinition.

  If the AttributeDefinition does not contain an enum with the referenced key, a [EnumKeyDoesNotExist](ctp:api:type:EnumKeyDoesNotExistError) error is returned.

  All Products will be updated to the new key in an [eventually consistent](/general-concepts#eventual-consistency) way.
properties:
  attributeName:
    type: string
    description: Name of the AttributeDefinition to update.
    pattern: ^[A-Za-z0-9_-]+$
    minLength: 2
    maxLength: 256
  key:
    type: string
    description: |
      Existing key to be changed.
  newKey:
    type: string
    description: |
      New key to be set.
