#%RAML 1.0 DataType
(package): ProductType
type: ProductTypeUpdateAction
displayName: ProductTypeChangeAttributeNameAction
discriminatorValue: changeAttributeName
example: !include ../../../examples/ProductType/ProductTypeChangeAttributeNameAction.json
description: |
  Renames an AttributeDefinition and also renames all corresponding Attributes on all [Products](/projects/products) with this ProductType. The renaming of the Attributes is [eventually consistent](/general-concepts#eventual-consistency).

  If the AttributeDefinition name to be changed does not exist, an [AttributeNameDoesNotExist](ctp:api:type:AttributeNameDoesNotExistError) error is returned.
properties:
  attributeName:
    type: string
    description: Name of the AttributeDefinition to update.
    pattern: ^[A-Za-z0-9_-]+$
    minLength: 2
    maxLength: 256
  newAttributeName:
    type: string
    pattern: ^[A-Za-z0-9_-]+$
    minLength: 2
    maxLength: 256
    description: |-
      New user-defined name of the Attribute that must be unique within the ProductType.

      To use the same `name` in multiple ProductTypes, each AttributeDefinition must have the same `type`; otherwise, an [AttributeDefinitionTypeConflict](ctp:api:type:AttributeDefinitionTypeConflictError) error is returned.
      For `enum` or `lenum` Types and sets of these AttributeTypes, the enum values can be different for each ProductType.
