#%RAML 1.0 DataType
(package): ProductType
(docs-uri): https://docs.commercetools.com/api/projects/productTypes#change-the-order-of-enumvalues
type: ProductTypeUpdateAction
displayName: ProductTypeChangePlainEnumValueOrderAction
discriminatorValue: changePlainEnumValueOrder
example: !include ../../../examples/ProductType/ProductTypeChangePlainEnumValueOrderAction.json
description: |
  Updates the order of enum `values` in an [AttributeEnumType](ctp:api:type:AttributeEnumType) AttributeDefinition. It can update an AttributeEnumType AttributeDefinition or an [AttributeSetType](ctp:api:type:AttributeSetType) of AttributeEnumType AttributeDefinition.
properties:
  attributeName:
    type: string
    description: Name of the AttributeDefinition to update.
    pattern: ^[A-Za-z0-9_-]+$
    minLength: 2
    maxLength: 256
  values:
    type: AttributePlainEnumValue[]
    description: |
      Values must be equal to the values of the Attribute enum values (except for the order). If not, an [EnumValuesMustMatch](/errors#product-types-400-enum-values-must-match) error code will be returned.
