#%RAML 1.0 DataType
(package): ProductType
(docs-uri): https://docs.commercetools.com/api/projects/productTypes#change-description
type: ProductTypeUpdateAction
displayName: ProductTypeChangeDescriptionAction
discriminatorValue: changeDescription
example: !include ../../../examples/ProductType/ProductTypeChangeDescriptionAction.json
properties:
  description:
    type: string
    description: New value to set.
