#%RAML 1.0 DataType
(package): ProductType
type: ProductTypeUpdateAction
displayName: ProductTypeChangeDescriptionAction
discriminatorValue: changeDescription
example: !include ../../../examples/ProductType/ProductTypeChangeDescriptionAction.json
properties:
  description:
    type: string
    description: New value to set.
