#%RAML 1.0 DataType
(package): ProductType
type: ProductTypeUpdateAction
displayName: ProductTypeAddAttributeDefinitionAction
discriminatorValue: addAttributeDefinition
example: !include ../../../examples/ProductType/ProductTypeAddAttributeDefinitionAction.json
properties:
  attribute:
    type: AttributeDefinitionDraft
    description: Value to append to `attributes`.
