#%RAML 1.0 DataType
(package): Store
type: StoreUpdateAction
displayName: StoreSetFaqUrlAction
discriminatorValue: setFaqUrl
example: !include ../../../examples/Store/StoreSetFaqUrlAction.json
description: |
  This update action produces the [StoreFaqUrlSet](ctp:api:type:StoreFaqUrlSetMessage) Message.
properties:
  faqUrl?:
    type: string
    description: |
      Value to set. Must be an absolute `https` URL. If empty, any existing value is removed.
