#%RAML 1.0 DataType
(package): Store
type: StoreUpdateAction
displayName: StoreSetRefundPolicyUrlAction
discriminatorValue: setRefundPolicyUrl
example: !include ../../../examples/Store/StoreSetRefundPolicyUrlAction.json
description: |
  This update action produces the [StoreRefundPolicyUrlSet](ctp:api:type:StoreRefundPolicyUrlSetMessage) Message.
properties:
  refundPolicyUrl?:
    type: string
    description: |
      Value to set. Must be an absolute `https` URL. If empty, any existing value is removed.
