#%RAML 1.0 DataType
(package): Store
(docs-uri): https://docs.commercetools.com/api/projects/stores#add-country
type: StoreUpdateAction
displayName: StoreAddCountryAction
discriminatorValue: addCountry
example: !include ../../../examples/Store/StoreAddCountryAction.json
description: |
  This update action produces the [StoreCountriesChanged](ctp:api:type:StoreCountriesChangedMessage) Message.
  It has no effect if the given country is already present in a Store.
properties:
  country:
    type: StoreCountry
    description: |
      Value to append to `countries`.
