#%RAML 1.0 DataType
(package): Store
type: StoreUpdateAction
displayName: StoreChangeProductSelectionAction
discriminatorValue: changeProductSelectionActive
example: !include ../../../examples/Store/StoreChangeProductSelectionActiveAction.json
description: |
  [ProductSelection](ctp:api:type:ProductSelection) in a Store can be activated or deactivated using this update action.
properties:
  productSelection:
    type: ProductSelectionResourceIdentifier
    description: |
      Current Product Selection of the Store to be activated or deactivated.
  active?:
    type: boolean
    description: |
      Set to `true` if all Products assigned to the Product Selection should become part of the Store's assortment.
    default: false
