#%RAML 1.0 DataType
(package): Store
(docs-uri): https://docs.commercetools.com/http-api-projects-stores#set-custom-field
type: StoreUpdateAction
displayName: StoreSetCustomFieldAction
discriminatorValue: setCustomField
(postman-example): !include ../../../examples/Store/StoreSetCustomFieldAction.json
properties:
  name:
    type: string
    description: ''
  value?:
    type: any
