#%RAML 1.0 DataType
(package): Store
(docs-uri): https://docs.commercetools.com/http-api-projects-stores#set-custom-type
type: StoreUpdateAction
displayName: StoreSetCustomTypeAction
discriminatorValue: setCustomType
(postman-example): !include ../../../examples/Store/StoreSetCustomTypeAction.json
properties:
  type?:
    type: TypeResourceIdentifier
    description: |-
      If set, the custom type is reset to this value.
      If absent, the custom type and any existing custom fields are removed.
  fields?:
    type: object
    description: |-
      A valid JSON object, based on the FieldDefinitions of the Type
      Sets the custom field to this value.
