#%RAML 1.0 DataType
(package): Store
(docs-uri): https://docs.commercetools.com/api/projects/stores#set-supply-channels
type: StoreUpdateAction
displayName: StoreSetSupplyChannelsAction
discriminatorValue: setSupplyChannels
example: !include ../../../examples/Store/StoreSetSupplyChannelsAction.json
description: |
  This update action produces the [StoreSupplyChannelsChanged](ctp:api:type:StoreSupplyChannelsChangedMessage) Message.
properties:
  supplyChannels?:
    type: ChannelResourceIdentifier[]
    description: |
      Value to set.
      If not defined, the Store's `supplyChannels` are unset.
      Any attempt to use [Channel](ctp:api:type:Channel) without the `InventorySupply` [ChannelRoleEnum](ctp:api:type:ChannelRoleEnum) will fail with a [MissingRoleOnChannel](ctp:api:type:MissingRoleOnChannelError) error.
