#%RAML 1.0 DataType
(package): Store
type: StoreUpdateAction
displayName: StoreSetPrivacyPolicyUrlAction
discriminatorValue: setPrivacyPolicyUrl
example: !include ../../../examples/Store/StoreSetPrivacyPolicyUrlAction.json
description: |
  This update action produces the [StorePrivacyPolicyUrlSet](ctp:api:type:StorePrivacyPolicyUrlSetMessage) Message.
properties:
  privacyPolicyUrl?:
    type: string
    description: |
      Value to set. Must be an absolute `https` URL. If empty, any existing value is removed.
