#%RAML 1.0 DataType
(package): Store
(docs-uri): https://docs.commercetools.com/http-api-projects-stores#set-distribution-channels
type: StoreUpdateAction
displayName: StoreSetDistributionChannelsAction
discriminatorValue: setDistributionChannels
(postman-example): !include ../../../examples/Store/StoreSetDistributionChannelsAction.json
properties:
  distributionChannels?:
    type: ChannelResourceIdentifier[]
    description: ''
