#%RAML 1.0 DataType
(package): Store
type: StoreUpdateAction
displayName: StoreRemoveDistributionChannelAction
discriminatorValue: removeDistributionChannel
example: !include ../../../examples/Store/StoreRemoveDistributionChannelAction.json
description: |
  This update action produces the [StoreDistributionChannelsChanged](ctp:api:type:StoreDistributionChannelsChangedMessage) Message.
properties:
  distributionChannel:
    type: ChannelResourceIdentifier
    description: |
      Value to remove. ResourceIdentifier of a Channel with the `ProductDistribution` [ChannelRoleEnum](ctp:api:type:ChannelRoleEnum).
