#%RAML 1.0 DataType
(package): Store
(docs-uri): https://docs.commercetools.com/http-api-projects-stores#remove-supply-channel
type: StoreUpdateAction
displayName: StoreRemoveSupplyChannelAction
discriminatorValue: removeSupplyChannel
(postman-example): !include ../../../examples/Store/StoreRemoveDistributionChannelAction.json
properties:
  supplyChannel:
    type: ChannelResourceIdentifier
    description: ''
