#%RAML 1.0 DataType
(package): Store
type: StoreUpdateAction
displayName: StoreSetLanguagesAction
discriminatorValue: setLanguages
example: !include ../../../examples/Store/StoreSetLanguagesAction.json
description: |
  This update action produces the [StoreLanguagesChanged](ctp:api:type:StoreLanguagesChangedMessage) Message.
properties:
  languages?:
    type: Locale[]
    description: |
      Value to set.

      If a language is not configured for the Project, a [ProjectNotConfiguredForLanguages](ctp:api:type:ProjectNotConfiguredForLanguagesError) error is returned.
