#%RAML 1.0 DataType
(package): Store
(docs-uri): https://docs.commercetools.com/api/projects/stores#add-supply-channel
type: StoreUpdateAction
displayName: StoreAddSupplyChannelAction
discriminatorValue: addSupplyChannel
example: !include ../../../examples/Store/StoreAddSupplyChannelAction.json
description: |
  This action has no effect if a given supply channel is already present in a Store.
  
  Adding a supply channel produces the [StoreSupplyChannelsChanged](ctp:api:type:StoreSupplyChannelsChangedMessage) Message.

  Adding a [Channel](ctp:api:type:Channel) without the `InventorySupply` [ChannelRoleEnum](ctp:api:type:ChannelRoleEnum) returns a [MissingRoleOnChannel](ctp:api:type:MissingRoleOnChannelError) error.
properties:
  supplyChannel:
    type: ChannelResourceIdentifier
    description: |
      Value to append.
