#%RAML 1.0 DataType
(package): Store
type: StoreUpdateAction
displayName: StoreSetShippingPolicyUrlAction
discriminatorValue: setShippingPolicyUrl
example: !include ../../../examples/Store/StoreSetShippingPolicyUrlAction.json
description: |
  This update action produces the [StoreShippingPolicyUrlSet](ctp:api:type:StoreShippingPolicyUrlSetMessage) Message.
properties:
  shippingPolicyUrl?:
    type: string
    description: |
      Value to set. Must be an absolute `https` URL. If empty, any existing value is removed.
