#%RAML 1.0 DataType
(package): Store
(docs-uri): https://docs.commercetools.com/api/projects/stores#add-product-selection
type: StoreUpdateAction
displayName: StoreAddProductSelectionAction
discriminatorValue: addProductSelection
example: !include ../../../examples/Store/StoreAddProductSelectionAction.json
description: |
  To make all included Products available to your customers of a given Store, add the [Product Selections](/../api/projects/product-selections) to the respective Store. This action has no effect if the given Product Selection is already present in the Store and has the same `active` flag.
properties:
  productSelection:
    type: ProductSelectionResourceIdentifier
    description: |
      Product Selection to add to the Store either activated or deactivated.
  active?:
    type: boolean
    description: |
      Set to `true` to make all Products assigned to the referenced Product Selection available in the Store.
    default: false
