#%RAML 1.0 DataType
(package): Payment
(docs-uri): https://docs.commercetools.com/http-api-projects-payments.html#change-transactiontimestamp
type: PaymentUpdateAction
displayName: PaymentChangeTransactionTimestampAction
discriminatorValue: changeTransactionTimestamp
(postman-example): !include ../../../examples/Payment/PaymentChangeTransactionTimestampAction.json
properties:
  transactionId:
    type: string
    description: ''
  timestamp:
    type: datetime
    description: ''
