#%RAML 1.0 DataType
(package): Payment
type: PaymentUpdateAction
displayName: PaymentSetMethodInfoMethodAction
discriminatorValue: setMethodInfoMethod
example: !include ../../../examples/Payment/PaymentSetMethodInfoMethodAction.json
description: |
  This action generates the [PaymentMethodInfoMethodSet](ctp:api:type:PaymentMethodInfoMethodSetMessage) Message.
properties:
  method?:
    type: string
    description: |
      Value to set.
      If empty, any existing value will be removed.
