#%RAML 1.0 DataType
(package): Payment
type: PaymentUpdateAction
displayName: PaymentSetCustomerAction
discriminatorValue: setCustomer
example: !include ../../../examples/Payment/PaymentSetCustomerAction.json
properties:
  customer?:
    type: CustomerResourceIdentifier
    description: |
      Value to set.
      If empty, any existing reference is removed.
