#%RAML 1.0 DataType
(package): Payment
(docs-uri): https://docs.commercetools.com/api/projects/payments#set-methodinfoname
type: PaymentUpdateAction
displayName: PaymentSetMethodInfoNameAction
discriminatorValue: setMethodInfoName
example: !include ../../../examples/Payment/PaymentSetMethodInfoNameAction.json
properties:
  name?:
    type: LocalizedString
    description: |
      Value to set.
      If empty, any existing value will be removed.
