#%RAML 1.0 DataType
(package): Payment
(deprecated): true
type: PaymentUpdateAction
displayName: PaymentSetAuthorizationAction
discriminatorValue: setAuthorization
properties:
  amount?:
    type: Money
  until?:
    type: datetime
