language: node_js
node_js:
- 12
services:
- docker
install:
- npm i -g yarn
- yarn install
script:
- node bin/explode-raml.js
- yarn run lint:raml
#- docker run -v$(pwd):/api vrapio/vrap -c /api/update-actions.raml
- docker run -v$(pwd):/api vrapio/vrap -rc /api/api.raml
notifications:
  slack:
    secure: UcTxolXg7qNkCl3sBxx8I35621m3f9cqfb6fweemCKOc5toLV+rDOHtUoMHnMKgd2Qo/1DlopyMnfABA0JBjji65QPYfc4tjMdkckzayI6rHwvNcbe9/wAj+KUk7B6vvoCqfQvMYI+D7j7lEbXRfZiv0K815VA1fHTRvaBiAHXdGDaPXKMkdSMvjgNBUoR+VXm1C6Q7RFcHac0D2eu2l9C8wOezjKSKiH6MvT9ze5jxNhGew6Of9spzd7C2N985RxzfpgmeUZfzAUZpDT2LiFHSyZ1Dca+4MH+QR6jJgi/9pYs0qpFN4iusNW7FDHLtZ342xqXNWZrffcdvKYopdy/THHdyYR74thi2LtzhXHNS6PWnoypZ7h30E8NvvM0JudQPXbozt6JY150+bJWr3/Jes5z9wyy5n6H7bVGE7KZy2T2nMGyLXa9VMVU75jMySPJsz381o6c6ot7ge1tT4z3W75hLbX4pnfWQSNIt3/M9759u4v5WjogjPAoBapb3bh089doIDLVQ2SoMmsokyH+zBB5PjGLE0x6zIuu7LXc4c+90ZAHj57shd6HSRIn0iknD6XW3ZOQmBlI/LJ0lHhi7zRUgR/wqp6xzlQhQT0t98zOZTAdmablZqn4iXonkiZcY24hx0TzVlHUjih/XZutJ6jThCDDPq8IdW1zZIBAE=
