language: scala
script:
- git clone https://github.com/cneijenhuis/json-schema-ref-inliner.git
- mkdir -p inlined
- cd json-schema-ref-inliner
- for f in ../schemas/*.schema.json; do file=$(basename $f); par="$par https://raw.githubusercontent.com/sphereio/sphere-api-reference/master/schemas/$file ../inlined/."; done
- sbt "run $par"
- cd ..
- git add inlined/*
- git commit -m "Inlined json schemas"
- git push origin master
