language: node_js
install:
- npm install jslint jsonlint -g
script:
- jslint schemas/*.json
- cd schemas; for file in *.json; do jsonlint $file --in-place; done; cd -
- git diff --shortstat --exit-code
