{
  "openapi": "3.0.0",
  "info": {
    "title": "Commercetools",
    "version": "undefined"
  },
  "servers": [
    {
      "url": "https://api.europe-west1.gcp.commercetools.com/"
    }
  ],
  "paths": {
    "/{projectKey}": {
      "get": {
        "description": "The Endpoint is responding a limited set of information about settings and configuration of the project.",
        "operationId": "Get project settings",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X GET https://api.europe-west1.gcp.commercetools.com/{projectKey} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "post": {
        "description": "Update project",
        "operationId": "Update project settings",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-resourceName": "ByProjectKey",
      "x-annotation-resourcePathUri": "/{projectKey}"
    },
    "/{projectKey}/api-clients": {
      "get": {
        "description": "Query api-clients",
        "operationId": "Query api-clients",
        "security": [
          {
            "oauth_2_0": [
              "manage_api_clients:{projectKey}",
              "view_api_clients:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X GET https://api.europe-west1.gcp.commercetools.com/{projectKey}/api-clients -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "post": {
        "description": "Create ApiClient",
        "operationId": "Create ApiClient",
        "security": [
          {
            "oauth_2_0": [
              "manage_api_clients:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X POST https://api.europe-west1.gcp.commercetools.com/{projectKey}/api-clients -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}' \\\n--header 'Content-Type: application/json' \\\n--data-binary @- << DATA \n{\n  \"name\" : \"api-client-name\",\n  \"scope\" : \"view_products\"\n}\nDATA"
        }
      },
      "x-annotation-resourceName": "ByProjectKeyApiClients",
      "x-annotation-resourcePathUri": "/{projectKey}/api-clients"
    },
    "/{projectKey}/api-clients/{ID}": {
      "get": {
        "description": "Get ApiClient by ID",
        "operationId": "Get ApiClient by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_api_clients:{projectKey}",
              "view_api_clients:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X GET https://api.europe-west1.gcp.commercetools.com/{projectKey}/api-clients/{ID} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "delete": {
        "description": "Delete ApiClient by ID",
        "operationId": "Delete ApiClient by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_api_clients:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X DELETE https://api.europe-west1.gcp.commercetools.com/{projectKey}/api-clients/{ID} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "x-annotation-resourceName": "ByProjectKeyApiClientsByID",
      "x-annotation-resourcePathUri": "/{projectKey}/api-clients/{ID}"
    },
    "/{projectKey}/cart-discounts": {
      "get": {
        "description": "Query cart-discounts",
        "operationId": "Query cart-discounts",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_orders:{projectKey}",
              "view_cart_discounts:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X GET https://api.europe-west1.gcp.commercetools.com/{projectKey}/cart-discounts -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "post": {
        "description": "Create CartDiscount",
        "operationId": "Create CartDiscount",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_orders:{projectKey}",
              "manage_cart_discounts:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X POST https://api.europe-west1.gcp.commercetools.com/{projectKey}/cart-discounts -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}' \\\n--header 'Content-Type: application/json' \\\n--data-binary @- << DATA \n{\n  \"name\" : {\n    \"en\" : \"Summer Sale\"\n  },\n  \"value\" : {\n    \"type\" : \"relative\",\n    \"permyriad\" : 1000\n  },\n  \"cartPredicate\" : \"1=1\",\n  \"target\" : {\n    \"type\" : \"lineItems\",\n    \"predicate\" : \"1=1\"\n  },\n  \"sortOr[...]"
        }
      },
      "x-annotation-resourceName": "ByProjectKeyCartDiscounts",
      "x-annotation-resourcePathUri": "/{projectKey}/cart-discounts"
    },
    "/{projectKey}/cart-discounts/key={key}": {
      "get": {
        "description": "Get CartDiscount by key",
        "operationId": "Get CartDiscount by key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_orders:{projectKey}",
              "view_cart_discounts:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X GET https://api.europe-west1.gcp.commercetools.com/{projectKey}/cart-discounts/key={key} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "post": {
        "description": "Update CartDiscount by key",
        "operationId": "Update CartDiscount by key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_orders:{projectKey}",
              "manage_cart_discounts:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X POST https://api.europe-west1.gcp.commercetools.com/{projectKey}/cart-discounts/key={key} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}' \\\n--header 'Content-Type: application/json' \\\n--data-binary @- << DATA \n{\n  \"version\" : 1,\n  \"actions\" : [ {\n    \"action\" : \"changeValue\",\n    \"value\" : {\n      \"type\" : \"relative\",\n      \"permyriad\" : 1000\n    }\n  } ]\n}\nDATA"
        }
      },
      "delete": {
        "description": "Delete CartDiscount by key",
        "operationId": "Delete CartDiscount by key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_orders:{projectKey}",
              "manage_cart_discounts:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X DELETE https://api.europe-west1.gcp.commercetools.com/{projectKey}/cart-discounts/key={key}?version={version} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "x-annotation-resourceName": "ByProjectKeyCartDiscountsKeyByKey",
      "x-annotation-resourcePathUri": "/{projectKey}/cart-discounts/key={key}"
    },
    "/{projectKey}/cart-discounts/{ID}": {
      "get": {
        "description": "Get CartDiscount by ID",
        "operationId": "Get CartDiscount by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_orders:{projectKey}",
              "view_cart_discounts:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X GET https://api.europe-west1.gcp.commercetools.com/{projectKey}/cart-discounts/{ID} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "post": {
        "description": "Update CartDiscount by ID",
        "operationId": "Update CartDiscount by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_orders:{projectKey}",
              "manage_cart_discounts:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X POST https://api.europe-west1.gcp.commercetools.com/{projectKey}/cart-discounts/{ID} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}' \\\n--header 'Content-Type: application/json' \\\n--data-binary @- << DATA \n{\n  \"version\" : 1,\n  \"actions\" : [ {\n    \"action\" : \"changeValue\",\n    \"value\" : {\n      \"type\" : \"relative\",\n      \"permyriad\" : 1000\n    }\n  } ]\n}\nDATA"
        }
      },
      "delete": {
        "description": "Delete CartDiscount by ID",
        "operationId": "Delete CartDiscount by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_orders:{projectKey}",
              "manage_cart_discounts:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X DELETE https://api.europe-west1.gcp.commercetools.com/{projectKey}/cart-discounts/{ID}?version={version} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "x-annotation-resourceName": "ByProjectKeyCartDiscountsByID",
      "x-annotation-resourcePathUri": "/{projectKey}/cart-discounts/{ID}"
    },
    "/{projectKey}/carts": {
      "get": {
        "description": "Query carts",
        "operationId": "Query carts",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_orders:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X GET https://api.europe-west1.gcp.commercetools.com/{projectKey}/carts -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "post": {
        "description": "Creating a cart can fail with an InvalidOperation if the referenced shipping method in the\nCartDraft has a predicate which does not match the cart.",
        "operationId": "Create Cart",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_orders:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X POST https://api.europe-west1.gcp.commercetools.com/{projectKey}/carts -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}' \\\n--header 'Content-Type: application/json' \\\n--data-binary @- << DATA \n{\n  \"currency\" : \"EUR\"\n}\nDATA"
        }
      },
      "x-annotation-resourceName": "ByProjectKeyCarts",
      "x-annotation-resourcePathUri": "/{projectKey}/carts"
    },
    "/{projectKey}/carts/customer-id={customerId}": {
      "get": {
        "description": "Retrieves the active cart of the customer that has been modified most recently.\nIt does not consider carts with CartOrigin Merchant. If no active cart exists, a 404 Not Found error is returned.\n\nThe cart may not contain up-to-date prices, discounts etc. If you want to ensure they're up-to-date,\nsend an Update request with the Recalculate update action instead.",
        "operationId": "Get Cart by customerId",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_orders:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X GET https://api.europe-west1.gcp.commercetools.com/{projectKey}/carts/customer-id={customerId} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "x-annotation-resourceName": "ByProjectKeyCartsCustomerIdByCustomerId",
      "x-annotation-resourcePathUri": "/{projectKey}/carts/customer-id={customerId}"
    },
    "/{projectKey}/carts/key={key}": {
      "get": {
        "description": "The cart may not contain up-to-date prices, discounts etc.\nIf you want to ensure they're up-to-date, send an Update request with the Recalculate update action instead.",
        "operationId": "Get Cart by key",
        "security": [
          {
            "oauth_2_0": [
              "view_orders:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X GET https://api.europe-west1.gcp.commercetools.com/{projectKey}/carts/key={key} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "post": {
        "description": "Update Cart by key",
        "operationId": "Update Cart by key",
        "security": [
          {
            "oauth_2_0": [
              "manage_orders:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X POST https://api.europe-west1.gcp.commercetools.com/{projectKey}/carts/key={key} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}' \\\n--header 'Content-Type: application/json' \\\n--data-binary @- << DATA \n{\n  \"version\" : 1,\n  \"actions\" : [ {\n    \"action\" : \"addLineItem\",\n    \"productId\" : \"9f10dcfb-5cc9-4a18-843a-c07f7e22d01f\",\n    \"variantId\" : 1,\n    \"quantity\" : 1\n  } ]\n}\nDATA"
        }
      },
      "delete": {
        "description": "Delete Cart by key",
        "operationId": "Delete Cart by key",
        "security": [
          {
            "oauth_2_0": [
              "manage_orders:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X DELETE https://api.europe-west1.gcp.commercetools.com/{projectKey}/carts/key={key}?version={version} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "x-annotation-resourceName": "ByProjectKeyCartsKeyByKey",
      "x-annotation-resourcePathUri": "/{projectKey}/carts/key={key}"
    },
    "/{projectKey}/carts/replicate": {
      "post": {
        "operationId": "Replicate cart",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_orders:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-resourceName": "ByProjectKeyCartsReplicate",
      "x-annotation-resourcePathUri": "/{projectKey}/carts/replicate"
    },
    "/{projectKey}/carts/{ID}": {
      "get": {
        "description": "The cart may not contain up-to-date prices, discounts etc.\nIf you want to ensure they're up-to-date, send an Update request with the Recalculate update action instead.",
        "operationId": "Get Cart by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_orders:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X GET https://api.europe-west1.gcp.commercetools.com/{projectKey}/carts/{ID} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "post": {
        "description": "Update Cart by ID",
        "operationId": "Update Cart by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_orders:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X POST https://api.europe-west1.gcp.commercetools.com/{projectKey}/carts/{ID} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}' \\\n--header 'Content-Type: application/json' \\\n--data-binary @- << DATA \n{\n  \"version\" : 1,\n  \"actions\" : [ {\n    \"action\" : \"addLineItem\",\n    \"productId\" : \"9f10dcfb-5cc9-4a18-843a-c07f7e22d01f\",\n    \"variantId\" : 1,\n    \"quantity\" : 1\n  } ]\n}\nDATA"
        }
      },
      "delete": {
        "description": "Delete Cart by ID",
        "operationId": "Delete Cart by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_orders:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X DELETE https://api.europe-west1.gcp.commercetools.com/{projectKey}/carts/{ID}?version={version} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "x-annotation-resourceName": "ByProjectKeyCartsByID",
      "x-annotation-resourcePathUri": "/{projectKey}/carts/{ID}"
    },
    "/{projectKey}/categories": {
      "get": {
        "description": "Query categories",
        "operationId": "Query categories",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_products:{projectKey}",
              "view_categories:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X GET https://api.europe-west1.gcp.commercetools.com/{projectKey}/categories -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "post": {
        "description": "Creating a category produces the CategoryCreated message.",
        "operationId": "Create Category",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_products:{projectKey}",
              "view_categories:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X POST https://api.europe-west1.gcp.commercetools.com/{projectKey}/categories -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}' \\\n--header 'Content-Type: application/json' \\\n--data-binary @- << DATA \n{\n  \"name\" : {\n    \"en\" : \"Top hat\"\n  },\n  \"slug\" : {\n    \"en\" : \"top-hat\"\n  },\n  \"orderHint\" : \"0.1\"\n}\nDATA"
        }
      },
      "x-annotation-resourceName": "ByProjectKeyCategories",
      "x-annotation-resourcePathUri": "/{projectKey}/categories"
    },
    "/{projectKey}/categories/key={key}": {
      "get": {
        "description": "Get Category by key",
        "operationId": "Get Category by key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_products:{projectKey}",
              "view_categories:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X GET https://api.europe-west1.gcp.commercetools.com/{projectKey}/categories/key={key} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "post": {
        "description": "Update Category by key",
        "operationId": "Update Category by key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_products:{projectKey}",
              "manage_categories:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X POST https://api.europe-west1.gcp.commercetools.com/{projectKey}/categories/key={key} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}' \\\n--header 'Content-Type: application/json' \\\n--data-binary @- << DATA \n{\n  \"version\" : 1,\n  \"actions\" : [ {\n    \"action\" : \"changeName\",\n    \"name\" : {\n      \"en\" : \"New Name\"\n    }\n  } ]\n}\nDATA"
        }
      },
      "delete": {
        "description": "Delete Category by key",
        "operationId": "Delete Category by key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_products:{projectKey}",
              "manage_categories:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X DELETE https://api.europe-west1.gcp.commercetools.com/{projectKey}/categories/key={key}?version={version} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "x-annotation-resourceName": "ByProjectKeyCategoriesKeyByKey",
      "x-annotation-resourcePathUri": "/{projectKey}/categories/key={key}"
    },
    "/{projectKey}/categories/{ID}": {
      "get": {
        "description": "Get Category by ID",
        "operationId": "Get Category by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_products:{projectKey}",
              "view_categories:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X GET https://api.europe-west1.gcp.commercetools.com/{projectKey}/categories/{ID} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "post": {
        "description": "Update Category by ID",
        "operationId": "Update Category by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_products:{projectKey}",
              "manage_categories:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X POST https://api.europe-west1.gcp.commercetools.com/{projectKey}/categories/{ID} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}' \\\n--header 'Content-Type: application/json' \\\n--data-binary @- << DATA \n{\n  \"version\" : 1,\n  \"actions\" : [ {\n    \"action\" : \"changeName\",\n    \"name\" : {\n      \"en\" : \"New Name\"\n    }\n  } ]\n}\nDATA"
        }
      },
      "delete": {
        "description": "Delete Category by ID",
        "operationId": "Delete Category by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_products:{projectKey}",
              "manage_categories:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X DELETE https://api.europe-west1.gcp.commercetools.com/{projectKey}/categories/{ID}?version={version} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "x-annotation-resourceName": "ByProjectKeyCategoriesByID",
      "x-annotation-resourcePathUri": "/{projectKey}/categories/{ID}"
    },
    "/{projectKey}/channels": {
      "get": {
        "description": "Query channels",
        "operationId": "Query channels",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_products:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X GET https://api.europe-west1.gcp.commercetools.com/{projectKey}/channels -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "post": {
        "description": "Create Channel",
        "operationId": "Create Channel",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_products:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X POST https://api.europe-west1.gcp.commercetools.com/{projectKey}/channels -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}' \\\n--header 'Content-Type: application/json' \\\n--data-binary @- << DATA \n{\n  \"key\" : \"commercetools\",\n  \"roles\" : [ \"InventorySupply\" ]\n}\nDATA"
        }
      },
      "x-annotation-resourceName": "ByProjectKeyChannels",
      "x-annotation-resourcePathUri": "/{projectKey}/channels"
    },
    "/{projectKey}/channels/{ID}": {
      "get": {
        "description": "Get Channel by ID",
        "operationId": "Get Channel by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_products:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X GET https://api.europe-west1.gcp.commercetools.com/{projectKey}/channels/{ID} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "post": {
        "description": "Update Channel by ID",
        "operationId": "Update Channel by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_products:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X POST https://api.europe-west1.gcp.commercetools.com/{projectKey}/channels/{ID} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}' \\\n--header 'Content-Type: application/json' \\\n--data-binary @- << DATA \n{\n  \"version\" : 1,\n  \"actions\" : [ {\n    \"action\" : \"changeName\",\n    \"name\" : {\n      \"en\" : \"New Name\"\n    }\n  } ]\n}\nDATA"
        }
      },
      "delete": {
        "description": "Delete Channel by ID",
        "operationId": "Delete Channel by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_products:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X DELETE https://api.europe-west1.gcp.commercetools.com/{projectKey}/channels/{ID}?version={version} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "x-annotation-resourceName": "ByProjectKeyChannelsByID",
      "x-annotation-resourcePathUri": "/{projectKey}/channels/{ID}"
    },
    "/{projectKey}/custom-objects": {
      "get": {
        "description": "The query endpoint allows to retrieve custom objects in a specific container or all custom objects.\nFor performance reasons, it is highly advisable to query only for custom objects in a container by using\nthe container field in the where predicate.",
        "operationId": "Query custom-objects",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_products:{projectKey}",
              "view_orders:{projectKey}",
              "view_customers:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X GET https://api.europe-west1.gcp.commercetools.com/{projectKey}/custom-objects -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "post": {
        "description": "Creates a new custom object or updates an existing custom object.\nIf an object with the given container/key exists,\nthe object will be replaced with the new value and the version is incremented.\nIf the request contains a version and an object with the given container/key exists then the version\nmust match the version of the existing object. Concurrent updates for the same custom object still can result\nin a Conflict (409) even if the version is not provided.\nFields [...]",
        "operationId": "Create CustomObject",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_products:{projectKey}",
              "manage_orders:{projectKey}",
              "manage_customers:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X POST https://api.europe-west1.gcp.commercetools.com/{projectKey}/custom-objects -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}' \\\n--header 'Content-Type: application/json' \\\n--data-binary @- << DATA \n{\n  \"container\" : \"test-container\",\n  \"key\" : \"test-key\",\n  \"value\" : \"test-value\"\n}\nDATA"
        }
      },
      "x-annotation-resourceName": "ByProjectKeyCustomObjects",
      "x-annotation-resourcePathUri": "/{projectKey}/custom-objects"
    },
    "/{projectKey}/custom-objects/{container}": {
      "get": {
        "description": "Get CustomObjectPagedQueryResponse by container",
        "operationId": "Get CustomObjectPagedQueryResponse by container",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_products:{projectKey}",
              "view_orders:{projectKey}",
              "view_customers:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X GET https://api.europe-west1.gcp.commercetools.com/{projectKey}/custom-objects/{container} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "x-annotation-resourceName": "ByProjectKeyCustomObjectsByContainer",
      "x-annotation-resourcePathUri": "/{projectKey}/custom-objects/{container}"
    },
    "/{projectKey}/custom-objects/{container}/{key}": {
      "get": {
        "description": "Get CustomObject by container and key",
        "operationId": "Get CustomObject by container and key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_products:{projectKey}",
              "view_orders:{projectKey}",
              "view_customers:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X GET https://api.europe-west1.gcp.commercetools.com/{projectKey}/custom-objects/{container}/{key} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "delete": {
        "description": "Delete CustomObject by container and key",
        "operationId": "Delete CustomObject by container and key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_products:{projectKey}",
              "manage_orders:{projectKey}",
              "manage_customers:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X DELETE https://api.europe-west1.gcp.commercetools.com/{projectKey}/custom-objects/{container}/{key} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "x-annotation-resourceName": "ByProjectKeyCustomObjectsByContainerByKey",
      "x-annotation-resourcePathUri": "/{projectKey}/custom-objects/{container}/{key}"
    },
    "/{projectKey}/customer-groups": {
      "get": {
        "description": "Query customer-groups",
        "operationId": "Query customer-groups",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_customers:{projectKey}",
              "view_customer_groups:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X GET https://api.europe-west1.gcp.commercetools.com/{projectKey}/customer-groups -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "post": {
        "description": "Create CustomerGroup",
        "operationId": "Create CustomerGroup",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_customers:{projectKey}",
              "manage_customer_groups:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X POST https://api.europe-west1.gcp.commercetools.com/{projectKey}/customer-groups -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}' \\\n--header 'Content-Type: application/json' \\\n--data-binary @- << DATA \n{\n  \"groupName\" : \"Webshop user\"\n}\nDATA"
        }
      },
      "x-annotation-resourceName": "ByProjectKeyCustomerGroups",
      "x-annotation-resourcePathUri": "/{projectKey}/customer-groups"
    },
    "/{projectKey}/customer-groups/key={key}": {
      "get": {
        "description": "Gets a customer group by Key.",
        "operationId": "Get CustomerGroup by key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_customers:{projectKey}",
              "view_customer_groups:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X GET https://api.europe-west1.gcp.commercetools.com/{projectKey}/customer-groups/key={key} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "post": {
        "description": "Updates a customer group by Key.",
        "operationId": "Update CustomerGroup by key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_customers:{projectKey}",
              "manage_customer_groups:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X POST https://api.europe-west1.gcp.commercetools.com/{projectKey}/customer-groups/key={key} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}' \\\n--header 'Content-Type: application/json' \\\n--data-binary @- << DATA \n{\n  \"version\" : 1,\n  \"actions\" : [ {\n    \"action\" : \"changeName\",\n    \"name\" : \"New Name\"\n  } ]\n}\nDATA"
        }
      },
      "delete": {
        "description": "Delete CustomerGroup by key",
        "operationId": "Delete CustomerGroup by key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_customers:{projectKey}",
              "manage_customer_groups:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X DELETE https://api.europe-west1.gcp.commercetools.com/{projectKey}/customer-groups/key={key}?version={version} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "x-annotation-resourceName": "ByProjectKeyCustomerGroupsKeyByKey",
      "x-annotation-resourcePathUri": "/{projectKey}/customer-groups/key={key}"
    },
    "/{projectKey}/customer-groups/{ID}": {
      "get": {
        "description": "Get CustomerGroup by ID",
        "operationId": "Get CustomerGroup by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_customers:{projectKey}",
              "view_customer_groups:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X GET https://api.europe-west1.gcp.commercetools.com/{projectKey}/customer-groups/{ID} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "post": {
        "description": "Update CustomerGroup by ID",
        "operationId": "Update CustomerGroup by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_customers:{projectKey}",
              "manage_customer_groups:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X POST https://api.europe-west1.gcp.commercetools.com/{projectKey}/customer-groups/{ID} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}' \\\n--header 'Content-Type: application/json' \\\n--data-binary @- << DATA \n{\n  \"version\" : 1,\n  \"actions\" : [ {\n    \"action\" : \"changeName\",\n    \"name\" : \"New Name\"\n  } ]\n}\nDATA"
        }
      },
      "delete": {
        "description": "Delete CustomerGroup by ID",
        "operationId": "Delete CustomerGroup by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_customers:{projectKey}",
              "manage_customer_groups:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X DELETE https://api.europe-west1.gcp.commercetools.com/{projectKey}/customer-groups/{ID}?version={version} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "x-annotation-resourceName": "ByProjectKeyCustomerGroupsByID",
      "x-annotation-resourcePathUri": "/{projectKey}/customer-groups/{ID}"
    },
    "/{projectKey}/customers": {
      "get": {
        "description": "Query customers",
        "operationId": "Query customers",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_customers:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X GET https://api.europe-west1.gcp.commercetools.com/{projectKey}/customers -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "post": {
        "description": "Creates a customer. If an anonymous cart is passed in,\nthen the cart is assigned to the created customer and the version number of the Cart will increase.\nIf the ID of an anonymous session is given, all carts and orders will be assigned to the created customer.",
        "operationId": "Create Customer",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_customers:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X POST https://api.europe-west1.gcp.commercetools.com/{projectKey}/customers -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}' \\\n--header 'Content-Type: application/json' \\\n--data-binary @- << DATA \n{\n  \"email\" : \"<random>@x-annotation-example.com\",\n  \"firstName\" : \"John\",\n  \"lastName\" : \"Doe\",\n  \"password\" : \"secret123\"\n}\nDATA"
        }
      },
      "x-annotation-resourceName": "ByProjectKeyCustomers",
      "x-annotation-resourcePathUri": "/{projectKey}/customers"
    },
    "/{projectKey}/customers/email-token": {
      "post": {
        "description": "Create a Token for verifying the Customer's Email",
        "operationId": "Create a Token for verifying the Customer's Email",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_customers:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-resourceName": "ByProjectKeyCustomersEmailToken",
      "x-annotation-resourcePathUri": "/{projectKey}/customers/email-token"
    },
    "/{projectKey}/customers/email-token={emailToken}": {
      "get": {
        "description": "Get Customer by emailToken",
        "operationId": "Get customer by email verification token",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_customers:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X GET https://api.europe-west1.gcp.commercetools.com/{projectKey}/customers/email-token={emailToken} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "x-annotation-resourceName": "ByProjectKeyCustomersEmailTokenByEmailToken",
      "x-annotation-resourcePathUri": "/{projectKey}/customers/email-token={emailToken}"
    },
    "/{projectKey}/customers/email/confirm": {
      "post": {
        "description": "Verifies customer's email using a token.",
        "operationId": "Verifies customer's email.",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_customers:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-resourceName": "ByProjectKeyCustomersEmailConfirm",
      "x-annotation-resourcePathUri": "/{projectKey}/customers/email/confirm"
    },
    "/{projectKey}/customers/key={key}": {
      "get": {
        "description": "Get Customer by key",
        "operationId": "Get Customer by key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_customers:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X GET https://api.europe-west1.gcp.commercetools.com/{projectKey}/customers/key={key} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "post": {
        "description": "Update Customer by key",
        "operationId": "Update Customer by key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_customers:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X POST https://api.europe-west1.gcp.commercetools.com/{projectKey}/customers/key={key} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}' \\\n--header 'Content-Type: application/json' \\\n--data-binary @- << DATA \n{\n  \"version\" : 3,\n  \"actions\" : [ {\n    \"action\" : \"addAddress\",\n    \"address\" : {\n      \"streetName\" : \"Any Street\",\n      \"streetNumber\" : \"1337\",\n      \"postalCode\" : \"11111\",\n      \"city\" : \"Any City\",\n      \"count[...]"
        }
      },
      "delete": {
        "description": "Delete Customer by key",
        "operationId": "Delete Customer by key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_customers:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X DELETE https://api.europe-west1.gcp.commercetools.com/{projectKey}/customers/key={key}?version={version} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "x-annotation-resourceName": "ByProjectKeyCustomersKeyByKey",
      "x-annotation-resourcePathUri": "/{projectKey}/customers/key={key}"
    },
    "/{projectKey}/customers/password": {
      "post": {
        "description": "Change a customers password",
        "operationId": "Change a customers password",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_customers:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-resourceName": "ByProjectKeyCustomersPassword",
      "x-annotation-resourcePathUri": "/{projectKey}/customers/password"
    },
    "/{projectKey}/customers/password-token": {
      "post": {
        "description": "The token value is used to reset the password of the customer with the given email. The token is\nvalid only for 10 minutes.",
        "operationId": "Create a Token for Resetting the Customer's Password",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_customers:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-resourceName": "ByProjectKeyCustomersPasswordToken",
      "x-annotation-resourcePathUri": "/{projectKey}/customers/password-token"
    },
    "/{projectKey}/customers/password-token={passwordToken}": {
      "get": {
        "description": "Get Customer by passwordToken",
        "operationId": "Get customer by password verification token",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_customers:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X GET https://api.europe-west1.gcp.commercetools.com/{projectKey}/customers/password-token={passwordToken} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "x-annotation-resourceName": "ByProjectKeyCustomersPasswordTokenByPasswordToken",
      "x-annotation-resourcePathUri": "/{projectKey}/customers/password-token={passwordToken}"
    },
    "/{projectKey}/customers/password/reset": {
      "post": {
        "description": "Set a new password using a token.",
        "operationId": "Reset Customer's Password",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_customers:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-resourceName": "ByProjectKeyCustomersPasswordReset",
      "x-annotation-resourcePathUri": "/{projectKey}/customers/password/reset"
    },
    "/{projectKey}/customers/{ID}": {
      "get": {
        "description": "Get Customer by ID",
        "operationId": "Get Customer by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_customers:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X GET https://api.europe-west1.gcp.commercetools.com/{projectKey}/customers/{ID} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "post": {
        "description": "Update Customer by ID",
        "operationId": "Update Customer by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_customers:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X POST https://api.europe-west1.gcp.commercetools.com/{projectKey}/customers/{ID} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}' \\\n--header 'Content-Type: application/json' \\\n--data-binary @- << DATA \n{\n  \"version\" : 3,\n  \"actions\" : [ {\n    \"action\" : \"addAddress\",\n    \"address\" : {\n      \"streetName\" : \"Any Street\",\n      \"streetNumber\" : \"1337\",\n      \"postalCode\" : \"11111\",\n      \"city\" : \"Any City\",\n      \"country\" [...]"
        }
      },
      "delete": {
        "description": "Delete Customer by ID",
        "operationId": "Delete Customer by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_customers:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X DELETE https://api.europe-west1.gcp.commercetools.com/{projectKey}/customers/{ID}?version={version} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "x-annotation-resourceName": "ByProjectKeyCustomersByID",
      "x-annotation-resourcePathUri": "/{projectKey}/customers/{ID}"
    },
    "/{projectKey}/discount-codes": {
      "get": {
        "description": "Query discount-codes",
        "operationId": "Query discount-codes",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_orders:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X GET https://api.europe-west1.gcp.commercetools.com/{projectKey}/discount-codes -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "post": {
        "description": "Create DiscountCode",
        "operationId": "Create DiscountCode",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_orders:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X POST https://api.europe-west1.gcp.commercetools.com/{projectKey}/discount-codes -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}' \\\n--header 'Content-Type: application/json' \\\n--data-binary @- << DATA \n{\n  \"code\" : \"SAVE10\",\n  \"name\" : {\n    \"en\" : \"Save10\"\n  },\n  \"cartDiscounts\" : [ {\n    \"typeId\" : \"cart-discount\",\n    \"id\" : \"fdbaf4ea-fbc9-4fea-bac4-1d7e6c1995b3\"\n  } ],\n  \"isActive\" : true,\n  \"cartPredicate\" : \"1=1\"\n}\[...]"
        }
      },
      "x-annotation-resourceName": "ByProjectKeyDiscountCodes",
      "x-annotation-resourcePathUri": "/{projectKey}/discount-codes"
    },
    "/{projectKey}/discount-codes/{ID}": {
      "get": {
        "description": "Get DiscountCode by ID",
        "operationId": "Get DiscountCode by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_orders:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X GET https://api.europe-west1.gcp.commercetools.com/{projectKey}/discount-codes/{ID} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "post": {
        "description": "Update DiscountCode by ID",
        "operationId": "Update DiscountCode by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_orders:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X POST https://api.europe-west1.gcp.commercetools.com/{projectKey}/discount-codes/{ID} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}' \\\n--header 'Content-Type: application/json' \\\n--data-binary @- << DATA \n{\n  \"version\" : 1,\n  \"actions\" : [ {\n    \"action\" : \"setName\",\n    \"name\" : {\n      \"en\" : \"New Name\"\n    }\n  } ]\n}\nDATA"
        }
      },
      "delete": {
        "description": "Delete DiscountCode by ID",
        "operationId": "Delete DiscountCode by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_orders:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X DELETE https://api.europe-west1.gcp.commercetools.com/{projectKey}/discount-codes/{ID}?version={version} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "x-annotation-resourceName": "ByProjectKeyDiscountCodesByID",
      "x-annotation-resourcePathUri": "/{projectKey}/discount-codes/{ID}"
    },
    "/{projectKey}/extensions": {
      "get": {
        "description": "Query extensions",
        "operationId": "Query extensions",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_extensions:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X GET https://api.europe-west1.gcp.commercetools.com/{projectKey}/extensions -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "post": {
        "description": "Currently, a maximum of 25 extensions can be created per project.",
        "operationId": "Create Extension",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_extensions:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X POST https://api.europe-west1.gcp.commercetools.com/{projectKey}/extensions -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}' \\\n--header 'Content-Type: application/json' \\\n--data-binary @- << DATA \n{\n  \"destination\" : {\n    \"type\" : \"HTTP\",\n    \"url\" : \"https://x-annotation-example.azurewebsites.net/api/extension\",\n    \"authentication\" : {\n      \"type\" : \"AzureFunctions\",\n      \"key\" : \"some-azure-function-code\"\n    }\n  },\n  \"tr[...]"
        }
      },
      "x-annotation-resourceName": "ByProjectKeyExtensions",
      "x-annotation-resourcePathUri": "/{projectKey}/extensions"
    },
    "/{projectKey}/extensions/key={key}": {
      "get": {
        "description": "Retrieves the representation of an extension by its key.",
        "operationId": "Get Extension by key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_extensions:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X GET https://api.europe-west1.gcp.commercetools.com/{projectKey}/extensions/key={key} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "post": {
        "description": "Update Extension by key",
        "operationId": "Update Extension by key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_extensions:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X POST https://api.europe-west1.gcp.commercetools.com/{projectKey}/extensions/key={key} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}' \\\n--header 'Content-Type: application/json' \\\n--data-binary @- << DATA \n{\n  \"version\" : 1,\n  \"actions\" : [ {\n    \"action\" : \"setKey\",\n    \"key\" : \"my-new-extension-key\"\n  } ]\n}\nDATA"
        }
      },
      "delete": {
        "description": "Delete Extension by key",
        "operationId": "Delete Extension by key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_extensions:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X DELETE https://api.europe-west1.gcp.commercetools.com/{projectKey}/extensions/key={key}?version={version} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "x-annotation-resourceName": "ByProjectKeyExtensionsKeyByKey",
      "x-annotation-resourcePathUri": "/{projectKey}/extensions/key={key}"
    },
    "/{projectKey}/extensions/{ID}": {
      "get": {
        "description": "Retrieves the representation of an extension by its id.",
        "operationId": "Get Extension by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_extensions:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X GET https://api.europe-west1.gcp.commercetools.com/{projectKey}/extensions/{ID} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "post": {
        "description": "Update Extension by ID",
        "operationId": "Update Extension by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_extensions:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X POST https://api.europe-west1.gcp.commercetools.com/{projectKey}/extensions/{ID} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}' \\\n--header 'Content-Type: application/json' \\\n--data-binary @- << DATA \n{\n  \"version\" : 1,\n  \"actions\" : [ {\n    \"action\" : \"setKey\",\n    \"key\" : \"my-new-extension-key\"\n  } ]\n}\nDATA"
        }
      },
      "delete": {
        "description": "Delete Extension by ID",
        "operationId": "Delete Extension by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_extensions:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X DELETE https://api.europe-west1.gcp.commercetools.com/{projectKey}/extensions/{ID}?version={version} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "x-annotation-resourceName": "ByProjectKeyExtensionsByID",
      "x-annotation-resourcePathUri": "/{projectKey}/extensions/{ID}"
    },
    "/{projectKey}/graphql": {
      "post": {
        "description": "Execute a GraphQL query",
        "operationId": "GraphQL",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_products:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X POST https://api.europe-west1.gcp.commercetools.com/{projectKey}/graphql -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}' \\\n--header 'Content-Type: application/json' \\\n--data-binary @- << DATA \n{\n  \"query\" : \"query query_1($productId: String){n        product(key:$productId){n          keyn        }n      }\",\n  \"operationName\" : \"query_1\",\n  \"variables\" : {\n    \"productId\" : \"f8ded810-a1\"\n  }\n}\nDATA"
        }
      },
      "x-annotation-resourceName": "ByProjectKeyGraphql",
      "x-annotation-resourcePathUri": "/{projectKey}/graphql"
    },
    "/{projectKey}/in-store/key={storeKey}": {
      "x-annotation-resourceName": "ByProjectKeyInStoreKeyByStoreKey",
      "x-annotation-resourcePathUri": "/{projectKey}/in-store/key={storeKey}"
    },
    "/{projectKey}/in-store/key={storeKey}/carts": {
      "get": {
        "description": "Queries carts in a specific Store. The {storeKey} path parameter maps to a Store's key.",
        "operationId": "Query carts in store",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_orders:{projectKey}",
              "view_orders:{projectKey}:{storeKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X GET https://api.europe-west1.gcp.commercetools.com/{projectKey}/in-store/key={storeKey}/carts -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "post": {
        "description": "Creates a cart in the store specified by {storeKey}. The {storeKey} path parameter maps to a Store's key.\nWhen using this endpoint the cart's store field is always set to the store specified in the path parameter.\nCreating a cart can fail with an InvalidOperation if the referenced shipping method\nin the CartDraft has a predicate which does not match the cart.",
        "operationId": "Create cart in store",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_orders:{projectKey}",
              "manage_orders:{projectKey}:{storeKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X POST https://api.europe-west1.gcp.commercetools.com/{projectKey}/in-store/key={storeKey}/carts -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}' \\\n--header 'Content-Type: application/json' \\\n--data-binary @- << DATA \n{\n  \"currency\" : \"EUR\"\n}\nDATA"
        }
      },
      "x-annotation-resourceName": "ByProjectKeyInStoreKeyByStoreKeyCarts",
      "x-annotation-resourcePathUri": "/{projectKey}/in-store/key={storeKey}/carts"
    },
    "/{projectKey}/in-store/key={storeKey}/carts/customer-id={customerId}": {
      "get": {
        "description": "Retrieves the active cart of the customer that has been modified most recently in a specific Store.\nThe {storeKey} path parameter maps to a Store's key.\n\nIf the cart exists in the commercetools project but does not have the store field, or the store field\nreferences a different store, this method returns a ResourceNotFound error.\n\nThe cart may not contain up-to-date prices, discounts etc. If you want to ensure they're up-to-date,\nsend an Update request with the Rec[...]",
        "operationId": "Get cart by customer id in store",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_orders:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X GET https://api.europe-west1.gcp.commercetools.com/{projectKey}/in-store/key={storeKey}/carts/customer-id={customerId} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "x-annotation-resourceName": "ByProjectKeyInStoreKeyByStoreKeyCartsCustomerIdByCustomerId",
      "x-annotation-resourcePathUri": "/{projectKey}/in-store/key={storeKey}/carts/customer-id={customerId}"
    },
    "/{projectKey}/in-store/key={storeKey}/carts/key={key}": {
      "get": {
        "description": "Returns a cart by its key from a specific Store. The {storeKey} path parameter maps to a Store's key.\nIf the cart exists in the commercetools project but does not have the store field,\nor the store field references a different store, this method returns a ResourceNotFound error.\nThe cart may not contain up-to-date prices, discounts etc.\nIf you want to ensure they're up-to-date, send an Update request with the Recalculate update action instead.",
        "operationId": "Get cart by key in store",
        "security": [
          {
            "oauth_2_0": [
              "view_orders:{projectKey}",
              "view_orders:{projectKey}:{storeKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X GET https://api.europe-west1.gcp.commercetools.com/{projectKey}/in-store/key={storeKey}/carts/key={key} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "post": {
        "description": "Updates a cart in the store specified by {storeKey}. The {storeKey} path parameter maps to a Store's key.\nIf the cart exists in the commercetools project but does not have the store field,\nor the store field references a different store, this method returns a ResourceNotFound error.",
        "operationId": "Update cart by key in store",
        "security": [
          {
            "oauth_2_0": [
              "manage_orders:{projectKey}",
              "manage_orders:{projectKey}:{storeKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X POST https://api.europe-west1.gcp.commercetools.com/{projectKey}/in-store/key={storeKey}/carts/key={key} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}' \\\n--header 'Content-Type: application/json' \\\n--data-binary @- << DATA \n{\n  \"version\" : 1,\n  \"actions\" : [ {\n    \"action\" : \"addLineItem\",\n    \"productId\" : \"9f10dcfb-5cc9-4a18-843a-c07f7e22d01f\",\n    \"variantId\" : 1,\n    \"quantity\" : 1\n  } ]\n}\nDATA"
        }
      },
      "delete": {
        "description": "Delete Cart by key",
        "operationId": "Delete cart by key in store",
        "security": [
          {
            "oauth_2_0": [
              "manage_orders:{projectKey}",
              "manage_orders:{projectKey}:{storeKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X DELETE https://api.europe-west1.gcp.commercetools.com/{projectKey}/in-store/key={storeKey}/carts/key={key}?version={version} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "x-annotation-resourceName": "ByProjectKeyInStoreKeyByStoreKeyCartsKeyByKey",
      "x-annotation-resourcePathUri": "/{projectKey}/in-store/key={storeKey}/carts/key={key}"
    },
    "/{projectKey}/in-store/key={storeKey}/carts/replicate": {
      "post": {
        "operationId": "Replicate cart for store",
        "security": [
          {
            "oauth_2_0": [
              "manage_orders:{projectKey}:{storeKey}",
              "manage_orders:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-resourceName": "ByProjectKeyInStoreKeyByStoreKeyCartsReplicate",
      "x-annotation-resourcePathUri": "/{projectKey}/in-store/key={storeKey}/carts/replicate"
    },
    "/{projectKey}/in-store/key={storeKey}/carts/{ID}": {
      "get": {
        "description": "Returns a cart by its ID from a specific Store. The {storeKey} path parameter maps to a Store's key.\nIf the cart exists in the commercetools project but does not have the store field,\nor the store field references a different store, this method returns a ResourceNotFound error.\nThe cart may not contain up-to-date prices, discounts etc.\nIf you want to ensure they're up-to-date, send an Update request with the Recalculate update action instead.",
        "operationId": "Get cart by id in store",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_orders:{projectKey}",
              "view_orders:{projectKey}:{storeKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X GET https://api.europe-west1.gcp.commercetools.com/{projectKey}/in-store/key={storeKey}/carts/{ID} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "post": {
        "description": "Updates a cart in the store specified by {storeKey}. The {storeKey} path parameter maps to a Store's key.\nIf the cart exists in the commercetools project but does not have the store field,\nor the store field references a different store, this method returns a ResourceNotFound error.",
        "operationId": "Update cart by id in store",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_orders:{projectKey}",
              "manage_orders:{projectKey}:{storeKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X POST https://api.europe-west1.gcp.commercetools.com/{projectKey}/in-store/key={storeKey}/carts/{ID} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}' \\\n--header 'Content-Type: application/json' \\\n--data-binary @- << DATA \n{\n  \"version\" : 1,\n  \"actions\" : [ {\n    \"action\" : \"addLineItem\",\n    \"productId\" : \"9f10dcfb-5cc9-4a18-843a-c07f7e22d01f\",\n    \"variantId\" : 1,\n    \"quantity\" : 1\n  } ]\n}\nDATA"
        }
      },
      "delete": {
        "description": "Delete Cart by ID",
        "operationId": "Delete cart by id in store",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_orders:{projectKey}",
              "manage_orders:{projectKey}:{storeKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X DELETE https://api.europe-west1.gcp.commercetools.com/{projectKey}/in-store/key={storeKey}/carts/{ID}?version={version} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "x-annotation-resourceName": "ByProjectKeyInStoreKeyByStoreKeyCartsByID",
      "x-annotation-resourcePathUri": "/{projectKey}/in-store/key={storeKey}/carts/{ID}"
    },
    "/{projectKey}/in-store/key={storeKey}/customers": {
      "get": {
        "description": "Query customers",
        "operationId": "Query customers in store",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_customers:{projectKey}",
              "view_customers:{projectKey}:{storeKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X GET https://api.europe-west1.gcp.commercetools.com/{projectKey}/in-store/key={storeKey}/customers -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "post": {
        "description": "Creates a customer in a specific Store. The {storeKey} path parameter maps to a Store's key.\nWhen using this endpoint, if omitted,\nthe customer's stores field is set to the store specified in the path parameter.\nIf an anonymous cart is passed in as when using this method,\nthen the cart is assigned to the created customer and the version number of the Cart increases.\nIf the ID of an anonymous session is given, all carts and orders will be assigned to the created custo[...]",
        "operationId": "Create customer in store",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_customers:{projectKey}",
              "manage_customers:{projectKey}:{storeKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X POST https://api.europe-west1.gcp.commercetools.com/{projectKey}/in-store/key={storeKey}/customers -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}' \\\n--header 'Content-Type: application/json' \\\n--data-binary @- << DATA \n{\n  \"email\" : \"<random>@x-annotation-example.com\",\n  \"firstName\" : \"John\",\n  \"lastName\" : \"Doe\",\n  \"password\" : \"secret123\"\n}\nDATA"
        }
      },
      "x-annotation-resourceName": "ByProjectKeyInStoreKeyByStoreKeyCustomers",
      "x-annotation-resourcePathUri": "/{projectKey}/in-store/key={storeKey}/customers"
    },
    "/{projectKey}/in-store/key={storeKey}/customers/email-token": {
      "post": {
        "description": "Create a Token for verifying the Customer's Email in store",
        "operationId": "Create a Token for verifying the Customer's Email in store",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_customers:{projectKey}",
              "manage_customers:{projectKey}:{storeKey}"
            ]
          }
        ]
      },
      "x-annotation-resourceName": "ByProjectKeyInStoreKeyByStoreKeyCustomersEmailToken",
      "x-annotation-resourcePathUri": "/{projectKey}/in-store/key={storeKey}/customers/email-token"
    },
    "/{projectKey}/in-store/key={storeKey}/customers/email-token={emailToken}": {
      "get": {
        "description": "Get Customer by emailToken",
        "operationId": "Get customer by email verification token in store",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_customers:{projectKey}",
              "view_customers:{projectKey}:{storeKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X GET https://api.europe-west1.gcp.commercetools.com/{projectKey}/in-store/key={storeKey}/customers/email-token={emailToken} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "x-annotation-resourceName": "ByProjectKeyInStoreKeyByStoreKeyCustomersEmailTokenByEmailToken",
      "x-annotation-resourcePathUri": "/{projectKey}/in-store/key={storeKey}/customers/email-token={emailToken}"
    },
    "/{projectKey}/in-store/key={storeKey}/customers/email/confirm": {
      "post": {
        "description": "Verifies customer's email using a token.",
        "operationId": "Verify Customer's Email in store",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_customers:{projectKey}",
              "manage_customers:{projectKey}:{storeKey}"
            ]
          }
        ]
      },
      "x-annotation-resourceName": "ByProjectKeyInStoreKeyByStoreKeyCustomersEmailConfirm",
      "x-annotation-resourcePathUri": "/{projectKey}/in-store/key={storeKey}/customers/email/confirm"
    },
    "/{projectKey}/in-store/key={storeKey}/customers/key={key}": {
      "get": {
        "description": "Returns a customer by its Key from a specific Store. The {storeKey} path parameter maps to a Store's key.\nIt also considers customers that do not have the stores field.\nIf the customer exists in the commercetools project but the stores field references different stores,\nthis method returns a ResourceNotFound error.",
        "operationId": "Get customer by key in store",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_customers:{projectKey}",
              "view_customers:{projectKey}:{storeKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X GET https://api.europe-west1.gcp.commercetools.com/{projectKey}/in-store/key={storeKey}/customers/key={key} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "post": {
        "description": "If the customer exists in the commercetools project but the stores field references a different store,\nthis method returns a ResourceNotFound error.",
        "operationId": "Update customer by key in store",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_customers:{projectKey}",
              "manage_customers:{projectKey}:{storeKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X POST https://api.europe-west1.gcp.commercetools.com/{projectKey}/in-store/key={storeKey}/customers/key={key} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}' \\\n--header 'Content-Type: application/json' \\\n--data-binary @- << DATA \n{\n  \"version\" : 3,\n  \"actions\" : [ {\n    \"action\" : \"addAddress\",\n    \"address\" : {\n      \"streetName\" : \"Any Street\",\n      \"streetNumber\" : \"1337\",\n      \"postalCode\" : \"11111\",\n      \"city\" : \"An[...]"
        }
      },
      "delete": {
        "description": "Delete Customer by key",
        "operationId": "Delete customer by key in store",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_customers:{projectKey}",
              "manage_customers:{projectKey}:{storeKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X DELETE https://api.europe-west1.gcp.commercetools.com/{projectKey}/in-store/key={storeKey}/customers/key={key}?version={version} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "x-annotation-resourceName": "ByProjectKeyInStoreKeyByStoreKeyCustomersKeyByKey",
      "x-annotation-resourcePathUri": "/{projectKey}/in-store/key={storeKey}/customers/key={key}"
    },
    "/{projectKey}/in-store/key={storeKey}/customers/password": {
      "post": {
        "description": "Change a customers password",
        "operationId": "Change a customers password in store",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_customers:{projectKey}",
              "manage_customers:{projectKey}:{storeKey}"
            ]
          }
        ]
      },
      "x-annotation-resourceName": "ByProjectKeyInStoreKeyByStoreKeyCustomersPassword",
      "x-annotation-resourcePathUri": "/{projectKey}/in-store/key={storeKey}/customers/password"
    },
    "/{projectKey}/in-store/key={storeKey}/customers/password-token": {
      "post": {
        "description": "The token value is used to reset the password of the customer with the given email. The token is\nvalid only for 10 minutes.",
        "operationId": "Create a Token for Resetting the Customer's Password in store",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_customers:{projectKey}",
              "manage_customers:{projectKey}:{storeKey}"
            ]
          }
        ]
      },
      "x-annotation-resourceName": "ByProjectKeyInStoreKeyByStoreKeyCustomersPasswordToken",
      "x-annotation-resourcePathUri": "/{projectKey}/in-store/key={storeKey}/customers/password-token"
    },
    "/{projectKey}/in-store/key={storeKey}/customers/password-token={passwordToken}": {
      "get": {
        "description": "Get Customer by passwordToken",
        "operationId": "Get customer by password verification token in store",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_customers:{projectKey}",
              "view_customers:{projectKey}:{storeKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X GET https://api.europe-west1.gcp.commercetools.com/{projectKey}/in-store/key={storeKey}/customers/password-token={passwordToken} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "x-annotation-resourceName": "ByProjectKeyInStoreKeyByStoreKeyCustomersPasswordTokenByPasswordToken",
      "x-annotation-resourcePathUri": "/{projectKey}/in-store/key={storeKey}/customers/password-token={passwordToken}"
    },
    "/{projectKey}/in-store/key={storeKey}/customers/password/reset": {
      "post": {
        "description": "Set a new password using a token.",
        "operationId": "Reset Customer's Password in store",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_customers:{projectKey}",
              "manage_customers:{projectKey}:{storeKey}"
            ]
          }
        ]
      },
      "x-annotation-resourceName": "ByProjectKeyInStoreKeyByStoreKeyCustomersPasswordReset",
      "x-annotation-resourcePathUri": "/{projectKey}/in-store/key={storeKey}/customers/password/reset"
    },
    "/{projectKey}/in-store/key={storeKey}/customers/{ID}": {
      "get": {
        "description": "Returns a customer by its ID from a specific Store. The {storeKey} path parameter maps to a Store's key.\nIt also considers customers that do not have the stores field.\nIf the customer exists in the commercetools project but the stores field references different stores,\nthis method returns a ResourceNotFound error.",
        "operationId": "Get customer by id in store",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_customers:{projectKey}",
              "view_customers:{projectKey}:{storeKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X GET https://api.europe-west1.gcp.commercetools.com/{projectKey}/in-store/key={storeKey}/customers/{ID} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "post": {
        "description": "Updates a customer in the store specified by {storeKey}. The {storeKey} path parameter maps to a Store's key.\nIf the customer exists in the commercetools project but the stores field references a different store,\nthis method returns a ResourceNotFound error.",
        "operationId": "Post customer by id in store",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_customers:{projectKey}",
              "manage_customers:{projectKey}:{storeKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X POST https://api.europe-west1.gcp.commercetools.com/{projectKey}/in-store/key={storeKey}/customers/{ID} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}' \\\n--header 'Content-Type: application/json' \\\n--data-binary @- << DATA \n{\n  \"version\" : 3,\n  \"actions\" : [ {\n    \"action\" : \"addAddress\",\n    \"address\" : {\n      \"streetName\" : \"Any Street\",\n      \"streetNumber\" : \"1337\",\n      \"postalCode\" : \"11111\",\n      \"city\" : \"Any Cit[...]"
        }
      },
      "delete": {
        "description": "Delete Customer by ID",
        "operationId": "Delete customer by id in store",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_customers:{projectKey}",
              "manage_customers:{projectKey}:{storeKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X DELETE https://api.europe-west1.gcp.commercetools.com/{projectKey}/in-store/key={storeKey}/customers/{ID}?version={version} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "x-annotation-resourceName": "ByProjectKeyInStoreKeyByStoreKeyCustomersByID",
      "x-annotation-resourcePathUri": "/{projectKey}/in-store/key={storeKey}/customers/{ID}"
    },
    "/{projectKey}/in-store/key={storeKey}/login": {
      "post": {
        "description": "Authenticate Customer (Sign In) in store",
        "operationId": "Authenticate Customer (Sign In) in store",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_customers:{projectKey}",
              "manage_customers:{projectKey}:{storeKey}"
            ]
          }
        ]
      },
      "x-annotation-resourceName": "ByProjectKeyInStoreKeyByStoreKeyLogin",
      "x-annotation-resourcePathUri": "/{projectKey}/in-store/key={storeKey}/login"
    },
    "/{projectKey}/in-store/key={storeKey}/me": {
      "x-annotation-resourceName": "ByProjectKeyInStoreKeyByStoreKeyMe",
      "x-annotation-resourcePathUri": "/{projectKey}/in-store/key={storeKey}/me"
    },
    "/{projectKey}/in-store/key={storeKey}/me/active-cart": {
      "get": {
        "operationId": "Get my active cart in store",
        "security": [
          {
            "oauth_2_0": [
              "manage_my_orders:{projectKey}",
              "manage_my_orders:{projectKey}:{storeKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X GET https://api.europe-west1.gcp.commercetools.com/{projectKey}/in-store/key={storeKey}/me/active-cart -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "x-annotation-resourceName": "ByProjectKeyInStoreKeyByStoreKeyMeActiveCart",
      "x-annotation-resourcePathUri": "/{projectKey}/in-store/key={storeKey}/me/active-cart"
    },
    "/{projectKey}/in-store/key={storeKey}/me/carts": {
      "get": {
        "description": "Query carts",
        "operationId": "Query my carts in store",
        "security": [
          {
            "oauth_2_0": [
              "manage_my_orders:{projectKey}",
              "manage_my_orders:{projectKey}:{storeKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X GET https://api.europe-west1.gcp.commercetools.com/{projectKey}/in-store/key={storeKey}/me/carts -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "post": {
        "description": "Create Cart",
        "operationId": "Create my cart in store",
        "security": [
          {
            "oauth_2_0": [
              "manage_my_orders:{projectKey}",
              "manage_my_orders:{projectKey}:{storeKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X POST https://api.europe-west1.gcp.commercetools.com/{projectKey}/in-store/key={storeKey}/me/carts -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}' \\\n--header 'Content-Type: application/json' \\\n--data-binary @- << DATA \n{\n  \"currency\" : \"EUR\"\n}\nDATA"
        }
      },
      "x-annotation-resourceName": "ByProjectKeyInStoreKeyByStoreKeyMeCarts",
      "x-annotation-resourcePathUri": "/{projectKey}/in-store/key={storeKey}/me/carts"
    },
    "/{projectKey}/in-store/key={storeKey}/me/carts/{ID}": {
      "get": {
        "description": "Get Cart by ID",
        "operationId": "Get my cart by id in store",
        "security": [
          {
            "oauth_2_0": [
              "manage_my_orders:{projectKey}",
              "manage_my_orders:{projectKey}:{storeKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X GET https://api.europe-west1.gcp.commercetools.com/{projectKey}/in-store/key={storeKey}/me/carts/{ID} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "post": {
        "description": "Update Cart by ID",
        "operationId": "Update my cart by id in store",
        "security": [
          {
            "oauth_2_0": [
              "manage_my_orders:{projectKey}",
              "manage_my_orders:{projectKey}:{storeKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X POST https://api.europe-west1.gcp.commercetools.com/{projectKey}/in-store/key={storeKey}/me/carts/{ID} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}' \\\n--header 'Content-Type: application/json' \\\n--data-binary @- << DATA \n{\n  \"version\" : 1,\n  \"actions\" : [ {\n    \"action\" : \"addLineItem\",\n    \"productId\" : \"9f10dcfb-5cc9-4a18-843a-c07f7e22d01f\",\n    \"variantId\" : 1,\n    \"quantity\" : 1\n  } ]\n}\nDATA"
        }
      },
      "delete": {
        "description": "Delete Cart by ID",
        "operationId": "Delete my cart by id in store",
        "security": [
          {
            "oauth_2_0": [
              "manage_my_orders:{projectKey}",
              "manage_my_orders:{projectKey}:{storeKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X DELETE https://api.europe-west1.gcp.commercetools.com/{projectKey}/in-store/key={storeKey}/me/carts/{ID}?version={version} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "x-annotation-resourceName": "ByProjectKeyInStoreKeyByStoreKeyMeCartsByID",
      "x-annotation-resourcePathUri": "/{projectKey}/in-store/key={storeKey}/me/carts/{ID}"
    },
    "/{projectKey}/in-store/key={storeKey}/me/orders": {
      "get": {
        "description": "Query orders",
        "operationId": "Query my orders in store",
        "security": [
          {
            "oauth_2_0": [
              "manage_my_orders:{projectKey}",
              "manage_my_orders:{projectKey}:{storeKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X GET https://api.europe-west1.gcp.commercetools.com/{projectKey}/in-store/key={storeKey}/me/orders -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "post": {
        "description": "Create Order",
        "operationId": "Create my order in store",
        "security": [
          {
            "oauth_2_0": [
              "manage_my_orders:{projectKey}",
              "manage_my_orders:{projectKey}:{storeKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X POST https://api.europe-west1.gcp.commercetools.com/{projectKey}/in-store/key={storeKey}/me/orders -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}' \\\n--header 'Content-Type: application/json' \\\n--data-binary @- << DATA \n{\n  \"id\" : \"7c2e2694-aefe-43d7-888e-6a99514caaca\",\n  \"version\" : 10,\n  \"orderNumber\" : \"201612010001\"\n}\nDATA"
        }
      },
      "x-annotation-resourceName": "ByProjectKeyInStoreKeyByStoreKeyMeOrders",
      "x-annotation-resourcePathUri": "/{projectKey}/in-store/key={storeKey}/me/orders"
    },
    "/{projectKey}/in-store/key={storeKey}/me/orders/{ID}": {
      "get": {
        "description": "Get Order by ID",
        "operationId": "Get my order by id in store",
        "security": [
          {
            "oauth_2_0": [
              "manage_my_orders:{projectKey}",
              "manage_my_orders:{projectKey}:{storeKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X GET https://api.europe-west1.gcp.commercetools.com/{projectKey}/in-store/key={storeKey}/me/orders/{ID} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "x-annotation-resourceName": "ByProjectKeyInStoreKeyByStoreKeyMeOrdersByID",
      "x-annotation-resourcePathUri": "/{projectKey}/in-store/key={storeKey}/me/orders/{ID}"
    },
    "/{projectKey}/in-store/key={storeKey}/me/shopping-lists": {
      "get": {
        "description": "Query shopping-lists",
        "operationId": "Get my shopping lists in store",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_shopping_lists:{projectKey}",
              "view_shopping_lists:{projectKey}:{storeKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X GET https://api.europe-west1.gcp.commercetools.com/{projectKey}/in-store/key={storeKey}/me/shopping-lists -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "post": {
        "description": "Create ShoppingList",
        "operationId": "Create my shopping lists in store",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_shopping_lists:{projectKey}",
              "manage_shopping_lists:{projectKey}:{storeKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X POST https://api.europe-west1.gcp.commercetools.com/{projectKey}/in-store/key={storeKey}/me/shopping-lists -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}' \\\n--header 'Content-Type: application/json' \\\n--data-binary @- << DATA \n{\n  \"name\" : {\n    \"en\" : \"test\"\n  },\n  \"key\" : \"test\"\n}\nDATA"
        }
      },
      "x-annotation-resourceName": "ByProjectKeyInStoreKeyByStoreKeyMeShoppingLists",
      "x-annotation-resourcePathUri": "/{projectKey}/in-store/key={storeKey}/me/shopping-lists"
    },
    "/{projectKey}/in-store/key={storeKey}/me/shopping-lists/key={key}": {
      "get": {
        "description": "Gets a shopping list by Key.",
        "operationId": "Get my shopping list by key in store",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_shopping_lists:{projectKey}",
              "view_shopping_lists:{projectKey}:{storeKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X GET https://api.europe-west1.gcp.commercetools.com/{projectKey}/in-store/key={storeKey}/me/shopping-lists/key={key} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "post": {
        "description": "Update a shopping list found by its Key.",
        "operationId": "Update my shopping list by key in store",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_shopping_lists:{projectKey}",
              "manage_shopping_lists:{projectKey}:{storeKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X POST https://api.europe-west1.gcp.commercetools.com/{projectKey}/in-store/key={storeKey}/me/shopping-lists/key={key} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}' \\\n--header 'Content-Type: application/json' \\\n--data-binary @- << DATA \n{\n  \"version\" : 1,\n  \"actions\" : [ {\n    \"action\" : \"changeName\",\n    \"name\" : {\n      \"en\" : \"New Name\"\n    }\n  } ]\n}\nDATA"
        }
      },
      "delete": {
        "description": "Delete ShoppingList by key",
        "operationId": "Delete my shopping list by key in store",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_shopping_lists:{projectKey}",
              "manage_shopping_lists:{projectKey}:{storeKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X DELETE https://api.europe-west1.gcp.commercetools.com/{projectKey}/in-store/key={storeKey}/me/shopping-lists/key={key}?version={version} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "x-annotation-resourceName": "ByProjectKeyInStoreKeyByStoreKeyMeShoppingListsKeyByKey",
      "x-annotation-resourcePathUri": "/{projectKey}/in-store/key={storeKey}/me/shopping-lists/key={key}"
    },
    "/{projectKey}/in-store/key={storeKey}/me/shopping-lists/{ID}": {
      "get": {
        "description": "Gets a shopping list by ID.",
        "operationId": "Get my shopping list by id in store",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_shopping_lists:{projectKey}",
              "view_shopping_lists:{projectKey}:{storeKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X GET https://api.europe-west1.gcp.commercetools.com/{projectKey}/in-store/key={storeKey}/me/shopping-lists/{ID} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "post": {
        "description": "Update ShoppingList by ID",
        "operationId": "Update my shopping list by id in store",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_shopping_lists:{projectKey}",
              "manage_shopping_lists:{projectKey}:{storeKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X POST https://api.europe-west1.gcp.commercetools.com/{projectKey}/in-store/key={storeKey}/me/shopping-lists/{ID} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}' \\\n--header 'Content-Type: application/json' \\\n--data-binary @- << DATA \n{\n  \"version\" : 1,\n  \"actions\" : [ {\n    \"action\" : \"changeName\",\n    \"name\" : {\n      \"en\" : \"New Name\"\n    }\n  } ]\n}\nDATA"
        }
      },
      "delete": {
        "description": "Delete ShoppingList by ID",
        "operationId": "Delete my shopping list by id in store",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_shopping_lists:{projectKey}",
              "manage_shopping_lists:{projectKey}:{storeKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X DELETE https://api.europe-west1.gcp.commercetools.com/{projectKey}/in-store/key={storeKey}/me/shopping-lists/{ID}?version={version} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "x-annotation-resourceName": "ByProjectKeyInStoreKeyByStoreKeyMeShoppingListsByID",
      "x-annotation-resourcePathUri": "/{projectKey}/in-store/key={storeKey}/me/shopping-lists/{ID}"
    },
    "/{projectKey}/in-store/key={storeKey}/orders": {
      "get": {
        "description": "Queries orders in a specific Store. The {storeKey} path parameter maps to a Store's key.",
        "operationId": "Query orders in store",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_orders:{projectKey}",
              "view_orders:{projectKey}:{storeKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X GET https://api.europe-west1.gcp.commercetools.com/{projectKey}/in-store/key={storeKey}/orders -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "post": {
        "description": "Creates an order from a Cart from a specific Store. The {storeKey} path parameter maps to a Store's key.\nWhen using this endpoint the orders's store field is always set to the store specified in the path parameter.\nThe cart must have a shipping address set before creating an order. When using the Platform TaxMode,\nthe shipping address is used for tax calculation.",
        "operationId": "Create order in store",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_orders:{projectKey}",
              "manage_orders:{projectKey}:{storeKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X POST https://api.europe-west1.gcp.commercetools.com/{projectKey}/in-store/key={storeKey}/orders -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}' \\\n--header 'Content-Type: application/json' \\\n--data-binary @- << DATA \n{\n  \"id\" : \"7c2e2694-aefe-43d7-888e-6a99514caaca\",\n  \"version\" : 10,\n  \"orderNumber\" : \"201612010001\"\n}\nDATA"
        }
      },
      "x-annotation-resourceName": "ByProjectKeyInStoreKeyByStoreKeyOrders",
      "x-annotation-resourcePathUri": "/{projectKey}/in-store/key={storeKey}/orders"
    },
    "/{projectKey}/in-store/key={storeKey}/orders/order-number={orderNumber}": {
      "get": {
        "description": "Returns an order by its order number from a specific Store.\nThe {storeKey} path parameter maps to a Store's key.\nIf the order exists in the commercetools project but does not have the store field,\nor the store field references a different store, this method returns a ResourceNotFound error.\nIn case the orderNumber does not match the regular expression [a-zA-Z0-9_-]+,\nit should be provided in URL-encoded format.",
        "operationId": "Get order by order number in store",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_orders:{projectKey}",
              "view_orders:{projectKey}:{storeKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X GET https://api.europe-west1.gcp.commercetools.com/{projectKey}/in-store/key={storeKey}/orders/order-number={orderNumber} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "post": {
        "description": "Updates an order in the store specified by {storeKey}. The {storeKey} path parameter maps to a Store's key.\nIf the order exists in the commercetools project but does not have the store field,\nor the store field references a different store, this method returns a ResourceNotFound error.\nIn case the orderNumber does not match the regular expression [a-zA-Z0-9_-]+,\nit should be provided in URL-encoded format.",
        "operationId": "Update order by order number in store",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_orders:{projectKey}",
              "manage_orders:{projectKey}:{storeKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X POST https://api.europe-west1.gcp.commercetools.com/{projectKey}/in-store/key={storeKey}/orders/order-number={orderNumber} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}' \\\n--header 'Content-Type: application/json' \\\n--data-binary @- << DATA \n{\n  \"version\" : 1,\n  \"actions\" : [ {\n    \"action\" : \"changeOrderState\",\n    \"orderState\" : \"Complete\"\n  } ]\n}\nDATA"
        }
      },
      "delete": {
        "description": "Delete Order by orderNumber",
        "operationId": "Delete order by order number in store",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_orders:{projectKey}",
              "manage_orders:{projectKey}:{storeKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X DELETE https://api.europe-west1.gcp.commercetools.com/{projectKey}/in-store/key={storeKey}/orders/order-number={orderNumber}?version={version} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "x-annotation-resourceName": "ByProjectKeyInStoreKeyByStoreKeyOrdersOrderNumberByOrderNumber",
      "x-annotation-resourcePathUri": "/{projectKey}/in-store/key={storeKey}/orders/order-number={orderNumber}"
    },
    "/{projectKey}/in-store/key={storeKey}/orders/{ID}": {
      "get": {
        "description": "Returns an order by its ID from a specific Store. The {storeKey} path parameter maps to a Store's key.\nIf the order exists in the commercetools project but does not have the store field,\nor the store field references a different store, this method returns a ResourceNotFound error.",
        "operationId": "Get order by id in store",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_orders:{projectKey}",
              "view_orders:{projectKey}:{storeKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X GET https://api.europe-west1.gcp.commercetools.com/{projectKey}/in-store/key={storeKey}/orders/{ID} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "post": {
        "description": "Updates an order in the store specified by {storeKey}. The {storeKey} path parameter maps to a Store's key.\nIf the order exists in the commercetools project but does not have the store field,\nor the store field references a different store, this method returns a ResourceNotFound error.",
        "operationId": "Update order by id in store",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_orders:{projectKey}",
              "manage_orders:{projectKey}:{storeKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X POST https://api.europe-west1.gcp.commercetools.com/{projectKey}/in-store/key={storeKey}/orders/{ID} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}' \\\n--header 'Content-Type: application/json' \\\n--data-binary @- << DATA \n{\n  \"version\" : 1,\n  \"actions\" : [ {\n    \"action\" : \"changeOrderState\",\n    \"orderState\" : \"Complete\"\n  } ]\n}\nDATA"
        }
      },
      "delete": {
        "description": "Delete Order by ID",
        "operationId": "Delete order by id in store",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_orders:{projectKey}",
              "manage_orders:{projectKey}:{storeKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X DELETE https://api.europe-west1.gcp.commercetools.com/{projectKey}/in-store/key={storeKey}/orders/{ID}?version={version} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "x-annotation-resourceName": "ByProjectKeyInStoreKeyByStoreKeyOrdersByID",
      "x-annotation-resourcePathUri": "/{projectKey}/in-store/key={storeKey}/orders/{ID}"
    },
    "/{projectKey}/in-store/key={storeKey}/shipping-methods": {
      "x-annotation-resourceName": "ByProjectKeyInStoreKeyByStoreKeyShippingMethods",
      "x-annotation-resourcePathUri": "/{projectKey}/in-store/key={storeKey}/shipping-methods"
    },
    "/{projectKey}/in-store/key={storeKey}/shipping-methods/matching-cart": {
      "get": {
        "operationId": "Get ShippingMethods for a cart in a store",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_orders:{projectKey}",
              "manage_customers:{projectKey}:{storeKey}",
              "view_shipping_methods:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X GET https://api.europe-west1.gcp.commercetools.com/{projectKey}/in-store/key={storeKey}/shipping-methods/matching-cart?cartId={cartId} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "x-annotation-resourceName": "ByProjectKeyInStoreKeyByStoreKeyShippingMethodsMatchingCart",
      "x-annotation-resourcePathUri": "/{projectKey}/in-store/key={storeKey}/shipping-methods/matching-cart"
    },
    "/{projectKey}/in-store/key={storeKey}/shopping-lists": {
      "get": {
        "description": "Query shopping-lists",
        "operationId": "Get shopping lists in store",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_shopping_lists:{projectKey}",
              "view_shopping_lists:{projectKey}:{storeKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X GET https://api.europe-west1.gcp.commercetools.com/{projectKey}/in-store/key={storeKey}/shopping-lists -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "post": {
        "description": "Create ShoppingList",
        "operationId": "Create shopping lists in store",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_shopping_lists:{projectKey}",
              "manage_shopping_lists:{projectKey}:{storeKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X POST https://api.europe-west1.gcp.commercetools.com/{projectKey}/in-store/key={storeKey}/shopping-lists -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}' \\\n--header 'Content-Type: application/json' \\\n--data-binary @- << DATA \n{\n  \"name\" : {\n    \"en\" : \"test\"\n  },\n  \"key\" : \"test\"\n}\nDATA"
        }
      },
      "x-annotation-resourceName": "ByProjectKeyInStoreKeyByStoreKeyShoppingLists",
      "x-annotation-resourcePathUri": "/{projectKey}/in-store/key={storeKey}/shopping-lists"
    },
    "/{projectKey}/in-store/key={storeKey}/shopping-lists/key={key}": {
      "get": {
        "description": "Gets a shopping list by Key.",
        "operationId": "Get shopping list by key in store",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_shopping_lists:{projectKey}",
              "view_shopping_lists:{projectKey}:{storeKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X GET https://api.europe-west1.gcp.commercetools.com/{projectKey}/in-store/key={storeKey}/shopping-lists/key={key} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "post": {
        "description": "Update a shopping list found by its Key.",
        "operationId": "Update shopping list by key in store",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_shopping_lists:{projectKey}",
              "manage_shopping_lists:{projectKey}:{storeKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X POST https://api.europe-west1.gcp.commercetools.com/{projectKey}/in-store/key={storeKey}/shopping-lists/key={key} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}' \\\n--header 'Content-Type: application/json' \\\n--data-binary @- << DATA \n{\n  \"version\" : 1,\n  \"actions\" : [ {\n    \"action\" : \"changeName\",\n    \"name\" : {\n      \"en\" : \"New Name\"\n    }\n  } ]\n}\nDATA"
        }
      },
      "delete": {
        "description": "Delete ShoppingList by key",
        "operationId": "Delete shopping list by key in store",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_shopping_lists:{projectKey}",
              "manage_shopping_lists:{projectKey}:{storeKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X DELETE https://api.europe-west1.gcp.commercetools.com/{projectKey}/in-store/key={storeKey}/shopping-lists/key={key}?version={version} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "x-annotation-resourceName": "ByProjectKeyInStoreKeyByStoreKeyShoppingListsKeyByKey",
      "x-annotation-resourcePathUri": "/{projectKey}/in-store/key={storeKey}/shopping-lists/key={key}"
    },
    "/{projectKey}/in-store/key={storeKey}/shopping-lists/{ID}": {
      "get": {
        "description": "Gets a shopping list by ID.",
        "operationId": "Get shopping list by id in store",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_shopping_lists:{projectKey}",
              "view_shopping_lists:{projectKey}:{storeKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X GET https://api.europe-west1.gcp.commercetools.com/{projectKey}/in-store/key={storeKey}/shopping-lists/{ID} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "post": {
        "description": "Update ShoppingList by ID",
        "operationId": "Update shopping list by id in store",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_shopping_lists:{projectKey}",
              "manage_shopping_lists:{projectKey}:{storeKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X POST https://api.europe-west1.gcp.commercetools.com/{projectKey}/in-store/key={storeKey}/shopping-lists/{ID} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}' \\\n--header 'Content-Type: application/json' \\\n--data-binary @- << DATA \n{\n  \"version\" : 1,\n  \"actions\" : [ {\n    \"action\" : \"changeName\",\n    \"name\" : {\n      \"en\" : \"New Name\"\n    }\n  } ]\n}\nDATA"
        }
      },
      "delete": {
        "description": "Delete ShoppingList by ID",
        "operationId": "Delete shopping list by id in store",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_shopping_lists:{projectKey}",
              "manage_shopping_lists:{projectKey}:{storeKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X DELETE https://api.europe-west1.gcp.commercetools.com/{projectKey}/in-store/key={storeKey}/shopping-lists/{ID}?version={version} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "x-annotation-resourceName": "ByProjectKeyInStoreKeyByStoreKeyShoppingListsByID",
      "x-annotation-resourcePathUri": "/{projectKey}/in-store/key={storeKey}/shopping-lists/{ID}"
    },
    "/{projectKey}/inventory": {
      "get": {
        "description": "Query inventory",
        "operationId": "Query inventory",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_products:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X GET https://api.europe-west1.gcp.commercetools.com/{projectKey}/inventory -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "post": {
        "description": "Create InventoryEntry",
        "operationId": "Create InventoryEntry",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_products:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X POST https://api.europe-west1.gcp.commercetools.com/{projectKey}/inventory -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}' \\\n--header 'Content-Type: application/json' \\\n--data-binary @- << DATA \n{\n  \"sku\" : \"sku_GIRLS_HARTBREAK_CREW_variant1_1421832124541\",\n  \"quantityOnStock\" : 4,\n  \"availableQuantity\" : 4\n}\nDATA"
        }
      },
      "x-annotation-resourceName": "ByProjectKeyInventory",
      "x-annotation-resourcePathUri": "/{projectKey}/inventory"
    },
    "/{projectKey}/inventory/{ID}": {
      "get": {
        "description": "Get InventoryEntry by ID",
        "operationId": "Get InventoryEntry by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_products:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X GET https://api.europe-west1.gcp.commercetools.com/{projectKey}/inventory/{ID} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "post": {
        "description": "Update InventoryEntry by ID",
        "operationId": "Update InventoryEntry by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_products:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X POST https://api.europe-west1.gcp.commercetools.com/{projectKey}/inventory/{ID} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}' \\\n--header 'Content-Type: application/json' \\\n--data-binary @- << DATA \n{\n  \"version\" : 1,\n  \"actions\" : [ {\n    \"action\" : \"addQuantity\",\n    \"quantity\" : 4\n  } ]\n}\nDATA"
        }
      },
      "delete": {
        "description": "Delete InventoryEntry by ID",
        "operationId": "Delete InventoryEntry by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_products:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X DELETE https://api.europe-west1.gcp.commercetools.com/{projectKey}/inventory/{ID}?version={version} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "x-annotation-resourceName": "ByProjectKeyInventoryByID",
      "x-annotation-resourcePathUri": "/{projectKey}/inventory/{ID}"
    },
    "/{projectKey}/login": {
      "post": {
        "description": "Authenticate Customer (Sign In). Retrieves the authenticated\ncustomer (a customer that matches the given email/password pair).\nIf used with an access token for Anonymous Sessions,\nall orders and carts belonging to the anonymousId will be assigned to the newly created customer.\nIf a cart is is returned as part of the CustomerSignInResult,\nit has been recalculated (It will have up-to-date prices, taxes and discounts,\nand invalid line items have been removed.).",
        "operationId": "Authenticate Customer (Sign In)",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_customers:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-resourceName": "ByProjectKeyLogin",
      "x-annotation-resourcePathUri": "/{projectKey}/login"
    },
    "/{projectKey}/me": {
      "get": {
        "operationId": "Get my customer details",
        "security": [
          {
            "oauth_2_0": [
              "manage_my_profile:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X GET https://api.europe-west1.gcp.commercetools.com/{projectKey}/me -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "post": {
        "description": "Update my customer",
        "operationId": "Update my customer",
        "security": [
          {
            "oauth_2_0": [
              "manage_my_profile:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X POST https://api.europe-west1.gcp.commercetools.com/{projectKey}/me -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}' \\\n--header 'Content-Type: application/json' \\\n--data-binary @- << DATA \n{\n  \"version\" : 3,\n  \"actions\" : [ {\n    \"action\" : \"addAddress\",\n    \"address\" : {\n      \"streetName\" : \"Any Street\",\n      \"streetNumber\" : \"1337\",\n      \"postalCode\" : \"11111\",\n      \"city\" : \"Any City\",\n      \"country\" : \"US\"\n  [...]"
        }
      },
      "delete": {
        "description": "Delete my Customer",
        "operationId": "Delete my Customer",
        "security": [
          {
            "oauth_2_0": [
              "manage_my_profile:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X DELETE https://api.europe-west1.gcp.commercetools.com/{projectKey}/me?version={version} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "x-annotation-resourceName": "ByProjectKeyMe",
      "x-annotation-resourcePathUri": "/{projectKey}/me"
    },
    "/{projectKey}/me/active-cart": {
      "get": {
        "operationId": "Get my active cart",
        "security": [
          {
            "oauth_2_0": [
              "manage_my_orders:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X GET https://api.europe-west1.gcp.commercetools.com/{projectKey}/me/active-cart -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "x-annotation-resourceName": "ByProjectKeyMeActiveCart",
      "x-annotation-resourcePathUri": "/{projectKey}/me/active-cart"
    },
    "/{projectKey}/me/carts": {
      "get": {
        "description": "Query carts",
        "operationId": "Query my carts",
        "security": [
          {
            "oauth_2_0": [
              "manage_my_orders:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X GET https://api.europe-west1.gcp.commercetools.com/{projectKey}/me/carts -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "post": {
        "description": "Create Cart",
        "operationId": "Create my cart",
        "security": [
          {
            "oauth_2_0": [
              "manage_my_orders:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X POST https://api.europe-west1.gcp.commercetools.com/{projectKey}/me/carts -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}' \\\n--header 'Content-Type: application/json' \\\n--data-binary @- << DATA \n{\n  \"currency\" : \"EUR\"\n}\nDATA"
        }
      },
      "x-annotation-resourceName": "ByProjectKeyMeCarts",
      "x-annotation-resourcePathUri": "/{projectKey}/me/carts"
    },
    "/{projectKey}/me/carts/key={key}": {
      "get": {
        "description": "Get Cart by key",
        "operationId": "Get my cart by key",
        "security": [
          {
            "oauth_2_0": [
              "manage_my_orders:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X GET https://api.europe-west1.gcp.commercetools.com/{projectKey}/me/carts/key={key} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "post": {
        "description": "Update Cart by key",
        "operationId": "Update my cart by key",
        "security": [
          {
            "oauth_2_0": [
              "manage_my_orders:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X POST https://api.europe-west1.gcp.commercetools.com/{projectKey}/me/carts/key={key} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}' \\\n--header 'Content-Type: application/json' \\\n--data-binary @- << DATA \n{\n  \"version\" : 1,\n  \"actions\" : [ {\n    \"action\" : \"addLineItem\",\n    \"productId\" : \"9f10dcfb-5cc9-4a18-843a-c07f7e22d01f\",\n    \"variantId\" : 1,\n    \"quantity\" : 1\n  } ]\n}\nDATA"
        }
      },
      "delete": {
        "description": "Delete Cart by key",
        "operationId": "Delete my cart by key",
        "security": [
          {
            "oauth_2_0": [
              "manage_my_orders:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X DELETE https://api.europe-west1.gcp.commercetools.com/{projectKey}/me/carts/key={key}?version={version} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "x-annotation-resourceName": "ByProjectKeyMeCartsKeyByKey",
      "x-annotation-resourcePathUri": "/{projectKey}/me/carts/key={key}"
    },
    "/{projectKey}/me/carts/{ID}": {
      "get": {
        "description": "Get Cart by ID",
        "operationId": "Get my cart by id",
        "security": [
          {
            "oauth_2_0": [
              "manage_my_orders:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X GET https://api.europe-west1.gcp.commercetools.com/{projectKey}/me/carts/{ID} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "post": {
        "description": "Update Cart by ID",
        "operationId": "Update my cart by id",
        "security": [
          {
            "oauth_2_0": [
              "manage_my_orders:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X POST https://api.europe-west1.gcp.commercetools.com/{projectKey}/me/carts/{ID} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}' \\\n--header 'Content-Type: application/json' \\\n--data-binary @- << DATA \n{\n  \"version\" : 1,\n  \"actions\" : [ {\n    \"action\" : \"addLineItem\",\n    \"productId\" : \"9f10dcfb-5cc9-4a18-843a-c07f7e22d01f\",\n    \"variantId\" : 1,\n    \"quantity\" : 1\n  } ]\n}\nDATA"
        }
      },
      "delete": {
        "description": "Delete Cart by ID",
        "operationId": "Delete my cart by id",
        "security": [
          {
            "oauth_2_0": [
              "manage_my_orders:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X DELETE https://api.europe-west1.gcp.commercetools.com/{projectKey}/me/carts/{ID}?version={version} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "x-annotation-resourceName": "ByProjectKeyMeCartsByID",
      "x-annotation-resourcePathUri": "/{projectKey}/me/carts/{ID}"
    },
    "/{projectKey}/me/email/confirm": {
      "post": {
        "operationId": "Verify my Customer's Email",
        "security": [
          {
            "oauth_2_0": [
              "manage_my_profile:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-resourceName": "ByProjectKeyMeEmailConfirm",
      "x-annotation-resourcePathUri": "/{projectKey}/me/email/confirm"
    },
    "/{projectKey}/me/login": {
      "post": {
        "operationId": "Authenticate my Customer (Sign In)",
        "security": [
          {
            "oauth_2_0": [
              "manage_my_profile:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-resourceName": "ByProjectKeyMeLogin",
      "x-annotation-resourcePathUri": "/{projectKey}/me/login"
    },
    "/{projectKey}/me/orders": {
      "get": {
        "description": "Query orders",
        "operationId": "Query my orders",
        "security": [
          {
            "oauth_2_0": [
              "manage_my_orders:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X GET https://api.europe-west1.gcp.commercetools.com/{projectKey}/me/orders -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "post": {
        "description": "Create Order",
        "operationId": "Create my order",
        "security": [
          {
            "oauth_2_0": [
              "manage_my_orders:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X POST https://api.europe-west1.gcp.commercetools.com/{projectKey}/me/orders -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}' \\\n--header 'Content-Type: application/json' \\\n--data-binary @- << DATA \n{\n  \"id\" : \"7c2e2694-aefe-43d7-888e-6a99514caaca\",\n  \"version\" : 10,\n  \"orderNumber\" : \"201612010001\"\n}\nDATA"
        }
      },
      "x-annotation-resourceName": "ByProjectKeyMeOrders",
      "x-annotation-resourcePathUri": "/{projectKey}/me/orders"
    },
    "/{projectKey}/me/orders/{ID}": {
      "get": {
        "description": "Get Order by ID",
        "operationId": "Get my order by id",
        "security": [
          {
            "oauth_2_0": [
              "manage_my_orders:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X GET https://api.europe-west1.gcp.commercetools.com/{projectKey}/me/orders/{ID} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "x-annotation-resourceName": "ByProjectKeyMeOrdersByID",
      "x-annotation-resourcePathUri": "/{projectKey}/me/orders/{ID}"
    },
    "/{projectKey}/me/password": {
      "post": {
        "operationId": "Change my customers password",
        "security": [
          {
            "oauth_2_0": [
              "manage_my_profile:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-resourceName": "ByProjectKeyMePassword",
      "x-annotation-resourcePathUri": "/{projectKey}/me/password"
    },
    "/{projectKey}/me/password/reset": {
      "post": {
        "operationId": "Reset my Customer's Password",
        "security": [
          {
            "oauth_2_0": [
              "manage_my_profile:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-resourceName": "ByProjectKeyMePasswordReset",
      "x-annotation-resourcePathUri": "/{projectKey}/me/password/reset"
    },
    "/{projectKey}/me/payments": {
      "get": {
        "description": "Query payments",
        "operationId": "Query my payments",
        "security": [
          {
            "oauth_2_0": [
              "manage_my_payments:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X GET https://api.europe-west1.gcp.commercetools.com/{projectKey}/me/payments -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "post": {
        "description": "Create MyPayment",
        "operationId": "Create my payment",
        "security": [
          {
            "oauth_2_0": [
              "manage_my_payments:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X POST https://api.europe-west1.gcp.commercetools.com/{projectKey}/me/payments -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}' \\\n--header 'Content-Type: application/json' \\\n--data-binary @- << DATA \n{\n  \"amountPlanned\" : {\n    \"currencyCode\" : \"USD\",\n    \"centAmount\" : 1000\n  },\n  \"paymentMethodInfo\" : {\n    \"paymentInterface\" : \"STRIPE\",\n    \"method\" : \"CREDIT_CARD\",\n    \"name\" : {\n      \"en\" : \"Credit Card\"\n    }\n  },\n  [...]"
        }
      },
      "x-annotation-resourceName": "ByProjectKeyMePayments",
      "x-annotation-resourcePathUri": "/{projectKey}/me/payments"
    },
    "/{projectKey}/me/payments/key={key}": {
      "get": {
        "description": "Get MyPayment by key",
        "operationId": "Get my payment by key",
        "security": [
          {
            "oauth_2_0": [
              "manage_my_payments:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X GET https://api.europe-west1.gcp.commercetools.com/{projectKey}/me/payments/key={key} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "post": {
        "description": "Update MyPayment by key",
        "operationId": "Update my payment by key",
        "security": [
          {
            "oauth_2_0": [
              "manage_my_payments:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X POST https://api.europe-west1.gcp.commercetools.com/{projectKey}/me/payments/key={key} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}' \\\n--header 'Content-Type: application/json' \\\n--data-binary @- << DATA \n{\n  \"version\" : 1,\n  \"actions\" : [ {\n    \"action\" : \"setMethodInfoMethod\",\n    \"method\" : \"12334567890123456\"\n  } ]\n}\nDATA"
        }
      },
      "delete": {
        "description": "Delete MyPayment by key",
        "operationId": "Delete my payment by key",
        "security": [
          {
            "oauth_2_0": [
              "manage_my_payments:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X DELETE https://api.europe-west1.gcp.commercetools.com/{projectKey}/me/payments/key={key}?version={version} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "x-annotation-resourceName": "ByProjectKeyMePaymentsKeyByKey",
      "x-annotation-resourcePathUri": "/{projectKey}/me/payments/key={key}"
    },
    "/{projectKey}/me/payments/{ID}": {
      "get": {
        "description": "Get MyPayment by ID",
        "operationId": "Get my payment by id",
        "security": [
          {
            "oauth_2_0": [
              "manage_my_payments:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X GET https://api.europe-west1.gcp.commercetools.com/{projectKey}/me/payments/{ID} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "post": {
        "description": "Update MyPayment by ID",
        "operationId": "Update my payment by id",
        "security": [
          {
            "oauth_2_0": [
              "manage_my_payments:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X POST https://api.europe-west1.gcp.commercetools.com/{projectKey}/me/payments/{ID} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}' \\\n--header 'Content-Type: application/json' \\\n--data-binary @- << DATA \n{\n  \"version\" : 1,\n  \"actions\" : [ {\n    \"action\" : \"setMethodInfoMethod\",\n    \"method\" : \"12334567890123456\"\n  } ]\n}\nDATA"
        }
      },
      "delete": {
        "description": "Delete MyPayment by ID",
        "operationId": "Delete my payment by id",
        "security": [
          {
            "oauth_2_0": [
              "manage_my_payments:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X DELETE https://api.europe-west1.gcp.commercetools.com/{projectKey}/me/payments/{ID}?version={version} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "x-annotation-resourceName": "ByProjectKeyMePaymentsByID",
      "x-annotation-resourcePathUri": "/{projectKey}/me/payments/{ID}"
    },
    "/{projectKey}/me/shopping-lists": {
      "get": {
        "description": "Query shopping-lists",
        "operationId": "Query my shopping lists",
        "security": [
          {
            "oauth_2_0": [
              "manage_my_shopping_lists:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X GET https://api.europe-west1.gcp.commercetools.com/{projectKey}/me/shopping-lists -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "post": {
        "description": "Create ShoppingList",
        "operationId": "Create my shopping list",
        "security": [
          {
            "oauth_2_0": [
              "manage_my_shopping_lists:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X POST https://api.europe-west1.gcp.commercetools.com/{projectKey}/me/shopping-lists -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}' \\\n--header 'Content-Type: application/json' \\\n--data-binary @- << DATA \n{\n  \"name\" : {\n    \"en\" : \"test\"\n  }\n}\nDATA"
        }
      },
      "x-annotation-resourceName": "ByProjectKeyMeShoppingLists",
      "x-annotation-resourcePathUri": "/{projectKey}/me/shopping-lists"
    },
    "/{projectKey}/me/shopping-lists/key={key}": {
      "get": {
        "description": "Get ShoppingList by key",
        "operationId": "Get my shopping list by key",
        "security": [
          {
            "oauth_2_0": [
              "manage_my_shopping_lists:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X GET https://api.europe-west1.gcp.commercetools.com/{projectKey}/me/shopping-lists/key={key} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "post": {
        "description": "Update ShoppingList by key",
        "operationId": "Update my shopping list by key",
        "security": [
          {
            "oauth_2_0": [
              "manage_my_shopping_lists:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X POST https://api.europe-west1.gcp.commercetools.com/{projectKey}/me/shopping-lists/key={key} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}' \\\n--header 'Content-Type: application/json' \\\n--data-binary @- << DATA \n{\n  \"version\" : 1,\n  \"actions\" : [ {\n    \"action\" : \"changeName\",\n    \"name\" : {\n      \"en\" : \"New Name\"\n    }\n  } ]\n}\nDATA"
        }
      },
      "delete": {
        "description": "Delete ShoppingList by key",
        "operationId": "Delete my shopping list by key",
        "security": [
          {
            "oauth_2_0": [
              "manage_my_shopping_lists:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X DELETE https://api.europe-west1.gcp.commercetools.com/{projectKey}/me/shopping-lists/key={key}?version={version} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "x-annotation-resourceName": "ByProjectKeyMeShoppingListsKeyByKey",
      "x-annotation-resourcePathUri": "/{projectKey}/me/shopping-lists/key={key}"
    },
    "/{projectKey}/me/shopping-lists/{ID}": {
      "get": {
        "description": "Get ShoppingList by ID",
        "operationId": "Get my shopping list by id",
        "security": [
          {
            "oauth_2_0": [
              "manage_my_shopping_lists:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X GET https://api.europe-west1.gcp.commercetools.com/{projectKey}/me/shopping-lists/{ID} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "post": {
        "description": "Update ShoppingList by ID",
        "operationId": "Update my shopping list by id",
        "security": [
          {
            "oauth_2_0": [
              "manage_my_shopping_lists:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X POST https://api.europe-west1.gcp.commercetools.com/{projectKey}/me/shopping-lists/{ID} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}' \\\n--header 'Content-Type: application/json' \\\n--data-binary @- << DATA \n{\n  \"version\" : 1,\n  \"actions\" : [ {\n    \"action\" : \"changeName\",\n    \"name\" : {\n      \"en\" : \"New Name\"\n    }\n  } ]\n}\nDATA"
        }
      },
      "delete": {
        "description": "Delete ShoppingList by ID",
        "operationId": "Delete my shopping list by id",
        "security": [
          {
            "oauth_2_0": [
              "manage_my_shopping_lists:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X DELETE https://api.europe-west1.gcp.commercetools.com/{projectKey}/me/shopping-lists/{ID}?version={version} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "x-annotation-resourceName": "ByProjectKeyMeShoppingListsByID",
      "x-annotation-resourcePathUri": "/{projectKey}/me/shopping-lists/{ID}"
    },
    "/{projectKey}/me/signup": {
      "post": {
        "operationId": "Signup my customer",
        "security": [
          {
            "oauth_2_0": [
              "manage_my_profile:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-resourceName": "ByProjectKeyMeSignup",
      "x-annotation-resourcePathUri": "/{projectKey}/me/signup"
    },
    "/{projectKey}/messages": {
      "get": {
        "description": "Query messages",
        "operationId": "Query messages",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_orders:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X GET https://api.europe-west1.gcp.commercetools.com/{projectKey}/messages -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "x-annotation-resourceName": "ByProjectKeyMessages",
      "x-annotation-resourcePathUri": "/{projectKey}/messages"
    },
    "/{projectKey}/messages/{ID}": {
      "get": {
        "description": "Get Message by ID",
        "operationId": "Get Message by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_orders:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X GET https://api.europe-west1.gcp.commercetools.com/{projectKey}/messages/{ID} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "x-annotation-resourceName": "ByProjectKeyMessagesByID",
      "x-annotation-resourcePathUri": "/{projectKey}/messages/{ID}"
    },
    "/{projectKey}/orders": {
      "get": {
        "description": "Query orders",
        "operationId": "Query orders",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_orders:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X GET https://api.europe-west1.gcp.commercetools.com/{projectKey}/orders -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "post": {
        "description": "Creates an order from a Cart.\nThe cart must have a shipping address set before creating an order.\nWhen using the Platform TaxMode, the shipping address is used for tax calculation.",
        "operationId": "Create Order",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_orders:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X POST https://api.europe-west1.gcp.commercetools.com/{projectKey}/orders -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}' \\\n--header 'Content-Type: application/json' \\\n--data-binary @- << DATA \n{\n  \"id\" : \"7c2e2694-aefe-43d7-888e-6a99514caaca\",\n  \"version\" : 10,\n  \"orderNumber\" : \"201612010001\"\n}\nDATA"
        }
      },
      "x-annotation-resourceName": "ByProjectKeyOrders",
      "x-annotation-resourcePathUri": "/{projectKey}/orders"
    },
    "/{projectKey}/orders/edits": {
      "get": {
        "description": "Query edits",
        "operationId": "Query edits",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_order_edits:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X GET https://api.europe-west1.gcp.commercetools.com/{projectKey}/orders/edits -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "post": {
        "description": "Create OrderEdit",
        "operationId": "Create OrderEdit",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_order_edits:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X POST https://api.europe-west1.gcp.commercetools.com/{projectKey}/orders/edits -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}' \\\n--header 'Content-Type: application/json' \\\n--data-binary @- << DATA \n{\n  \"key\" : \"order-edit-key\",\n  \"resource\" : {\n    \"typeId\" : \"order\",\n    \"id\" : \"ed454f4e-c43a-485f-a86f-046c691b1363\"\n  },\n  \"stagedActions\" : [ {\n    \"action\" : \"setCustomerEmail\",\n    \"email\" : \"user@localhost\"\n  } ],\n  \"c[...]"
        }
      },
      "x-annotation-resourceName": "ByProjectKeyOrdersEdits",
      "x-annotation-resourcePathUri": "/{projectKey}/orders/edits"
    },
    "/{projectKey}/orders/edits/key={key}": {
      "get": {
        "description": "Get OrderEdit by key",
        "operationId": "Get OrderEdit by key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_order_edits:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X GET https://api.europe-west1.gcp.commercetools.com/{projectKey}/orders/edits/key={key} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "post": {
        "description": "Update OrderEdit by key",
        "operationId": "Update OrderEdit by key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_order_edits:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X POST https://api.europe-west1.gcp.commercetools.com/{projectKey}/orders/edits/key={key} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}' \\\n--header 'Content-Type: application/json' \\\n--data-binary @- << DATA \n{\n  \"version\" : 7,\n  \"actions\" : [ {\n    \"action\" : \"setKey\",\n    \"key\" : \"another-key\"\n  }, {\n    \"action\" : \"addStagedAction\",\n    \"stagedAction\" : {\n      \"action\" : \"setCountry\",\n      \"country\" : \"ES\"\n    }\n  }[...]"
        }
      },
      "delete": {
        "description": "Delete OrderEdit by key",
        "operationId": "Delete OrderEdit by key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_order_edits:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X DELETE https://api.europe-west1.gcp.commercetools.com/{projectKey}/orders/edits/key={key}?version={version} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "x-annotation-resourceName": "ByProjectKeyOrdersEditsKeyByKey",
      "x-annotation-resourcePathUri": "/{projectKey}/orders/edits/key={key}"
    },
    "/{projectKey}/orders/edits/{ID}": {
      "get": {
        "description": "Get OrderEdit by ID",
        "operationId": "Get OrderEdit by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_order_edits:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X GET https://api.europe-west1.gcp.commercetools.com/{projectKey}/orders/edits/{ID} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "post": {
        "description": "Update OrderEdit by ID",
        "operationId": "Update OrderEdit by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_order_edits:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X POST https://api.europe-west1.gcp.commercetools.com/{projectKey}/orders/edits/{ID} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}' \\\n--header 'Content-Type: application/json' \\\n--data-binary @- << DATA \n{\n  \"version\" : 7,\n  \"actions\" : [ {\n    \"action\" : \"setKey\",\n    \"key\" : \"another-key\"\n  }, {\n    \"action\" : \"addStagedAction\",\n    \"stagedAction\" : {\n      \"action\" : \"setCountry\",\n      \"country\" : \"ES\"\n    }\n  } ]\n}[...]"
        }
      },
      "delete": {
        "description": "Delete OrderEdit by ID",
        "operationId": "Delete OrderEdit by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_order_edits:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X DELETE https://api.europe-west1.gcp.commercetools.com/{projectKey}/orders/edits/{ID}?version={version} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "x-annotation-resourceName": "ByProjectKeyOrdersEditsByID",
      "x-annotation-resourcePathUri": "/{projectKey}/orders/edits/{ID}"
    },
    "/{projectKey}/orders/edits/{ID}/apply": {
      "post": {
        "operationId": "Apply order edit",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_order_edits:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-resourceName": "ByProjectKeyOrdersEditsByIDApply",
      "x-annotation-resourcePathUri": "/{projectKey}/orders/edits/{ID}/apply"
    },
    "/{projectKey}/orders/import": {
      "post": {
        "description": "Create an Order by Import",
        "operationId": "Create an Order by Import",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_orders:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X POST https://api.europe-west1.gcp.commercetools.com/{projectKey}/orders/import -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}' \\\n--header 'Content-Type: application/json' \\\n--data-binary @- << DATA \n{\n  \"orderNumber\" : \"100000001\",\n  \"totalPrice\" : {\n    \"centAmount\" : 1000,\n    \"currencyCode\" : \"EUR\"\n  }\n}\nDATA"
        }
      },
      "x-annotation-resourceName": "ByProjectKeyOrdersImport",
      "x-annotation-resourcePathUri": "/{projectKey}/orders/import"
    },
    "/{projectKey}/orders/order-number={orderNumber}": {
      "get": {
        "description": "In case the orderNumber does not match the regular expression [a-zA-Z0-9_-]+,\nit should be provided in URL-encoded format.",
        "operationId": "Get Order by orderNumber",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_orders:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X GET https://api.europe-west1.gcp.commercetools.com/{projectKey}/orders/order-number={orderNumber} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "post": {
        "description": "Update Order by orderNumber",
        "operationId": "Update Order by orderNumber",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_orders:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X POST https://api.europe-west1.gcp.commercetools.com/{projectKey}/orders/order-number={orderNumber} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}' \\\n--header 'Content-Type: application/json' \\\n--data-binary @- << DATA \n{\n  \"version\" : 1,\n  \"actions\" : [ {\n    \"action\" : \"changeOrderState\",\n    \"orderState\" : \"Complete\"\n  } ]\n}\nDATA"
        }
      },
      "delete": {
        "description": "Delete Order by orderNumber",
        "operationId": "Delete Order by orderNumber",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_orders:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X DELETE https://api.europe-west1.gcp.commercetools.com/{projectKey}/orders/order-number={orderNumber}?version={version} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "x-annotation-resourceName": "ByProjectKeyOrdersOrderNumberByOrderNumber",
      "x-annotation-resourcePathUri": "/{projectKey}/orders/order-number={orderNumber}"
    },
    "/{projectKey}/orders/{ID}": {
      "get": {
        "description": "Get Order by ID",
        "operationId": "Get Order by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_orders:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X GET https://api.europe-west1.gcp.commercetools.com/{projectKey}/orders/{ID} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "post": {
        "description": "Update Order by ID",
        "operationId": "Update Order by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_orders:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X POST https://api.europe-west1.gcp.commercetools.com/{projectKey}/orders/{ID} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}' \\\n--header 'Content-Type: application/json' \\\n--data-binary @- << DATA \n{\n  \"version\" : 1,\n  \"actions\" : [ {\n    \"action\" : \"changeOrderState\",\n    \"orderState\" : \"Complete\"\n  } ]\n}\nDATA"
        }
      },
      "delete": {
        "description": "Delete Order by ID",
        "operationId": "Delete Order by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_orders:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X DELETE https://api.europe-west1.gcp.commercetools.com/{projectKey}/orders/{ID}?version={version} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "x-annotation-resourceName": "ByProjectKeyOrdersByID",
      "x-annotation-resourcePathUri": "/{projectKey}/orders/{ID}"
    },
    "/{projectKey}/payments": {
      "get": {
        "description": "Query payments",
        "operationId": "Query payments",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_payments:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X GET https://api.europe-west1.gcp.commercetools.com/{projectKey}/payments -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "post": {
        "description": "To create a payment object a payment draft object has to be given with the request.",
        "operationId": "Create Payment",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_payments:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X POST https://api.europe-west1.gcp.commercetools.com/{projectKey}/payments -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}' \\\n--header 'Content-Type: application/json' \\\n--data-binary @- << DATA \n{\n  \"externalId\" : \"123456\",\n  \"interfaceId\" : \"789011\",\n  \"amountPlanned\" : {\n    \"currencyCode\" : \"USD\",\n    \"centAmount\" : 1000\n  },\n  \"paymentMethodInfo\" : {\n    \"paymentInterface\" : \"STRIPE\",\n    \"method\" : \"CREDIT_CARD\",\n   [...]"
        }
      },
      "x-annotation-resourceName": "ByProjectKeyPayments",
      "x-annotation-resourcePathUri": "/{projectKey}/payments"
    },
    "/{projectKey}/payments/key={key}": {
      "get": {
        "description": "Get Payment by key",
        "operationId": "Get Payment by key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_payments:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X GET https://api.europe-west1.gcp.commercetools.com/{projectKey}/payments/key={key} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "post": {
        "description": "Update Payment by key",
        "operationId": "Update Payment by key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_payments:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X POST https://api.europe-west1.gcp.commercetools.com/{projectKey}/payments/key={key} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}' \\\n--header 'Content-Type: application/json' \\\n--data-binary @- << DATA \n{\n  \"version\" : 1,\n  \"actions\" : [ {\n    \"action\" : \"setInterfaceId\",\n    \"interfaceId\" : \"12334567890123456\"\n  } ]\n}\nDATA"
        }
      },
      "delete": {
        "description": "Delete Payment by key",
        "operationId": "Delete Payment by key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_payments:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X DELETE https://api.europe-west1.gcp.commercetools.com/{projectKey}/payments/key={key}?version={version} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "x-annotation-resourceName": "ByProjectKeyPaymentsKeyByKey",
      "x-annotation-resourcePathUri": "/{projectKey}/payments/key={key}"
    },
    "/{projectKey}/payments/{ID}": {
      "get": {
        "description": "Get Payment by ID",
        "operationId": "Get Payment by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_payments:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X GET https://api.europe-west1.gcp.commercetools.com/{projectKey}/payments/{ID} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "post": {
        "description": "Update Payment by ID",
        "operationId": "Update Payment by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_payments:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X POST https://api.europe-west1.gcp.commercetools.com/{projectKey}/payments/{ID} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}' \\\n--header 'Content-Type: application/json' \\\n--data-binary @- << DATA \n{\n  \"version\" : 1,\n  \"actions\" : [ {\n    \"action\" : \"setInterfaceId\",\n    \"interfaceId\" : \"12334567890123456\"\n  } ]\n}\nDATA"
        }
      },
      "delete": {
        "description": "Delete Payment by ID",
        "operationId": "Delete Payment by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_payments:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X DELETE https://api.europe-west1.gcp.commercetools.com/{projectKey}/payments/{ID}?version={version} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "x-annotation-resourceName": "ByProjectKeyPaymentsByID",
      "x-annotation-resourcePathUri": "/{projectKey}/payments/{ID}"
    },
    "/{projectKey}/product-discounts": {
      "get": {
        "description": "Query product-discounts",
        "operationId": "Query product-discounts",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_products:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X GET https://api.europe-west1.gcp.commercetools.com/{projectKey}/product-discounts -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "post": {
        "description": "Create ProductDiscount",
        "operationId": "Create ProductDiscount",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_products:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X POST https://api.europe-west1.gcp.commercetools.com/{projectKey}/product-discounts -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}' \\\n--header 'Content-Type: application/json' \\\n--data-binary @- << DATA \n{\n  \"value\" : {\n    \"type\" : \"absolute\",\n    \"money\" : [ {\n      \"currencyCode\" : \"EUR\",\n      \"centAmount\" : 100\n    } ]\n  },\n  \"predicate\" : \"1=1\",\n  \"name\" : {\n    \"en\" : \"test-discount1\"\n  },\n  \"description\" : {\n  [...]"
        }
      },
      "x-annotation-resourceName": "ByProjectKeyProductDiscounts",
      "x-annotation-resourcePathUri": "/{projectKey}/product-discounts"
    },
    "/{projectKey}/product-discounts/key={key}": {
      "get": {
        "description": "Get ProductDiscount by key",
        "operationId": "Get ProductDiscount by key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_products:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X GET https://api.europe-west1.gcp.commercetools.com/{projectKey}/product-discounts/key={key} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "post": {
        "description": "Update ProductDiscount by key",
        "operationId": "Update ProductDiscount by key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_products:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X POST https://api.europe-west1.gcp.commercetools.com/{projectKey}/product-discounts/key={key} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}' \\\n--header 'Content-Type: application/json' \\\n--data-binary @- << DATA \n{\n  \"version\" : 1,\n  \"actions\" : [ {\n    \"action\" : \"changeValue\",\n    \"value\" : {\n      \"type\" : \"absolute\",\n      \"money\" : [ {\n        \"currencyCode\" : \"EUR\",\n        \"centAmount\" : 100\n      } ]\n    }\n  } ]\n}\[...]"
        }
      },
      "delete": {
        "description": "Delete ProductDiscount by key",
        "operationId": "Delete ProductDiscount by key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_products:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X DELETE https://api.europe-west1.gcp.commercetools.com/{projectKey}/product-discounts/key={key}?version={version} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "x-annotation-resourceName": "ByProjectKeyProductDiscountsKeyByKey",
      "x-annotation-resourcePathUri": "/{projectKey}/product-discounts/key={key}"
    },
    "/{projectKey}/product-discounts/matching": {
      "post": {
        "operationId": "Get matching product discounts",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_products:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X POST https://api.europe-west1.gcp.commercetools.com/{projectKey}/product-discounts/matching -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}' \\\n--header 'Content-Type: application/json' \\\n--data-binary @- << DATA \n\"{n  \"productId\": \"123456\",n  \"variantId\": 1,n  \"staged\": false,n  \"price\": {n    \"value\": {n      \"type\": \"centPrecision\",n      \"centAmount\": 100,n      \"currencyCode\": \"EUR\",n      \"fractionDigits\": 2n    },n  \"id\": \"[...]"
        }
      },
      "x-annotation-resourceName": "ByProjectKeyProductDiscountsMatching",
      "x-annotation-resourcePathUri": "/{projectKey}/product-discounts/matching"
    },
    "/{projectKey}/product-discounts/{ID}": {
      "get": {
        "description": "Get ProductDiscount by ID",
        "operationId": "Get ProductDiscount by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_products:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X GET https://api.europe-west1.gcp.commercetools.com/{projectKey}/product-discounts/{ID} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "post": {
        "description": "Update ProductDiscount by ID",
        "operationId": "Update ProductDiscount by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_products:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X POST https://api.europe-west1.gcp.commercetools.com/{projectKey}/product-discounts/{ID} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}' \\\n--header 'Content-Type: application/json' \\\n--data-binary @- << DATA \n{\n  \"version\" : 1,\n  \"actions\" : [ {\n    \"action\" : \"changeValue\",\n    \"value\" : {\n      \"type\" : \"absolute\",\n      \"money\" : [ {\n        \"currencyCode\" : \"EUR\",\n        \"centAmount\" : 100\n      } ]\n    }\n  } ]\n}\nDATA[...]"
        }
      },
      "delete": {
        "description": "Delete ProductDiscount by ID",
        "operationId": "Delete ProductDiscount by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_products:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X DELETE https://api.europe-west1.gcp.commercetools.com/{projectKey}/product-discounts/{ID}?version={version} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "x-annotation-resourceName": "ByProjectKeyProductDiscountsByID",
      "x-annotation-resourcePathUri": "/{projectKey}/product-discounts/{ID}"
    },
    "/{projectKey}/product-projections": {
      "get": {
        "description": "You can use the product projections query endpoint to get the current or staged representations of Products.\nWhen used with an API client that has the view_published_products:{projectKey} scope,\nthis endpoint only returns published (current) product projections.",
        "operationId": "Query product-projections",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_products:{projectKey}",
              "view_published_products:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X GET https://api.europe-west1.gcp.commercetools.com/{projectKey}/product-projections -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "x-annotation-resourceName": "ByProjectKeyProductProjections",
      "x-annotation-resourcePathUri": "/{projectKey}/product-projections"
    },
    "/{projectKey}/product-projections/key={key}": {
      "get": {
        "description": "Gets the current or staged representation of a product found by Key.\nWhen used with an API client that has the view_published_products:{projectKey} scope,\nthis endpoint only returns published (current) product projections.",
        "operationId": "Get ProductProjection by key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_products:{projectKey}",
              "view_published_products:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X GET https://api.europe-west1.gcp.commercetools.com/{projectKey}/product-projections/key={key} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "x-annotation-resourceName": "ByProjectKeyProductProjectionsKeyByKey",
      "x-annotation-resourcePathUri": "/{projectKey}/product-projections/key={key}"
    },
    "/{projectKey}/product-projections/search": {
      "post": {
        "description": "Search Product Projection",
        "operationId": "Search Products by post",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_products:{projectKey}",
              "view_published_products:{projectKey}"
            ]
          }
        ]
      },
      "get": {
        "description": "Search Product Projection",
        "operationId": "Search Products by get",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_products:{projectKey}",
              "view_published_products:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X GET https://api.europe-west1.gcp.commercetools.com/{projectKey}/product-projections/search?markMatchingVariants={markMatchingVariants} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "x-annotation-resourceName": "ByProjectKeyProductProjectionsSearch",
      "x-annotation-resourcePathUri": "/{projectKey}/product-projections/search"
    },
    "/{projectKey}/product-projections/suggest": {
      "get": {
        "operationId": "Get suggestion keywords",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_products:{projectKey}",
              "view_published_products:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X GET https://api.europe-west1.gcp.commercetools.com/{projectKey}/product-projections/suggest -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "x-annotation-resourceName": "ByProjectKeyProductProjectionsSuggest",
      "x-annotation-resourcePathUri": "/{projectKey}/product-projections/suggest"
    },
    "/{projectKey}/product-projections/{ID}": {
      "get": {
        "description": "Gets the current or staged representation of a product in a catalog by ID.\nWhen used with an API client that has the view_published_products:{projectKey} scope,\nthis endpoint only returns published (current) product projections.",
        "operationId": "Get ProductProjection by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_products:{projectKey}",
              "view_published_products:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X GET https://api.europe-west1.gcp.commercetools.com/{projectKey}/product-projections/{ID} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "x-annotation-resourceName": "ByProjectKeyProductProjectionsByID",
      "x-annotation-resourcePathUri": "/{projectKey}/product-projections/{ID}"
    },
    "/{projectKey}/product-types": {
      "get": {
        "description": "Query product-types",
        "operationId": "Query product-types",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_products:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X GET https://api.europe-west1.gcp.commercetools.com/{projectKey}/product-types -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "post": {
        "description": "Create ProductType",
        "operationId": "Create ProductType",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_products:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X POST https://api.europe-west1.gcp.commercetools.com/{projectKey}/product-types -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}' \\\n--header 'Content-Type: application/json' \\\n--data-binary @- << DATA \n{\n  \"name\" : \"test_product_type\",\n  \"description\" : \"Test product type.\",\n  \"attributes\" : [ {\n    \"type\" : {\n      \"name\" : \"text\"\n    },\n    \"isSearchable\" : false,\n    \"inputHint\" : \"SingleLine\",\n    \"name\" : \"size\",\n    \[...]"
        }
      },
      "x-annotation-resourceName": "ByProjectKeyProductTypes",
      "x-annotation-resourcePathUri": "/{projectKey}/product-types"
    },
    "/{projectKey}/product-types/key={key}": {
      "get": {
        "description": "Get ProductType by key",
        "operationId": "Get ProductType by key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_products:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X GET https://api.europe-west1.gcp.commercetools.com/{projectKey}/product-types/key={key} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "post": {
        "description": "Update ProductType by key",
        "operationId": "Update ProductType by key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_products:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X POST https://api.europe-west1.gcp.commercetools.com/{projectKey}/product-types/key={key} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}' \\\n--header 'Content-Type: application/json' \\\n--data-binary @- << DATA \n{\n  \"version\" : 3,\n  \"actions\" : [ {\n    \"action\" : \"changeName\",\n    \"name\" : \"new-product-type-name\"\n  } ]\n}\nDATA"
        }
      },
      "delete": {
        "description": "Delete ProductType by key",
        "operationId": "Delete ProductType by key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_products:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X DELETE https://api.europe-west1.gcp.commercetools.com/{projectKey}/product-types/key={key}?version={version} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "x-annotation-resourceName": "ByProjectKeyProductTypesKeyByKey",
      "x-annotation-resourcePathUri": "/{projectKey}/product-types/key={key}"
    },
    "/{projectKey}/product-types/{ID}": {
      "get": {
        "description": "Get ProductType by ID",
        "operationId": "Get ProductType by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_products:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X GET https://api.europe-west1.gcp.commercetools.com/{projectKey}/product-types/{ID} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "post": {
        "description": "Update ProductType by ID",
        "operationId": "Update ProductType by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_products:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X POST https://api.europe-west1.gcp.commercetools.com/{projectKey}/product-types/{ID} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}' \\\n--header 'Content-Type: application/json' \\\n--data-binary @- << DATA \n{\n  \"version\" : 3,\n  \"actions\" : [ {\n    \"action\" : \"changeName\",\n    \"name\" : \"new-product-type-name\"\n  } ]\n}\nDATA"
        }
      },
      "delete": {
        "description": "Delete ProductType by ID",
        "operationId": "Delete ProductType by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_products:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X DELETE https://api.europe-west1.gcp.commercetools.com/{projectKey}/product-types/{ID}?version={version} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "x-annotation-resourceName": "ByProjectKeyProductTypesByID",
      "x-annotation-resourcePathUri": "/{projectKey}/product-types/{ID}"
    },
    "/{projectKey}/products": {
      "get": {
        "description": "You can use the query endpoint to get the full representations of products.\nREMARK: We suggest to use the performance optimized search endpoint which has a bunch functionalities,\nthe query API lacks like sorting on custom attributes, etc.",
        "operationId": "Query products",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_products:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X GET https://api.europe-west1.gcp.commercetools.com/{projectKey}/products -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "post": {
        "description": "To create a new product, send a representation that is going to become the initial staged representation\nof the new product in the master catalog. If price selection query parameters are provided,\nthe selected prices will be added to the response.",
        "operationId": "Create Product",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_products:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X POST https://api.europe-west1.gcp.commercetools.com/{projectKey}/products -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}' \\\n--header 'Content-Type: application/json' \\\n--data-binary @- << DATA \n{\n  \"productType\" : {\n    \"id\" : \"24f510c3-f334-4099-94e2-d6224a8eb919\",\n    \"typeId\" : \"product-type\"\n  },\n  \"categories\" : [ {\n    \"typeId\" : \"category\",\n    \"id\" : \"24f510c3-f334-4099-94e2-d6224a8eb919\"\n  } ],\n  \"name\" : {\n    \"en[...]"
        }
      },
      "x-annotation-resourceName": "ByProjectKeyProducts",
      "x-annotation-resourcePathUri": "/{projectKey}/products"
    },
    "/{projectKey}/products/key={key}": {
      "get": {
        "description": "Gets the full representation of a product by Key.",
        "operationId": "Get Product by key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_products:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X GET https://api.europe-west1.gcp.commercetools.com/{projectKey}/products/key={key} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "post": {
        "description": "Update Product by key",
        "operationId": "Update Product by key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_products:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X POST https://api.europe-west1.gcp.commercetools.com/{projectKey}/products/key={key} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}' \\\n--header 'Content-Type: application/json' \\\n--data-binary @- << DATA \n{\n  \"version\" : 2,\n  \"actions\" : [ {\n    \"action\" : \"setDescription\",\n    \"description\" : {\n      \"en\" : \"The best product ever!\"\n    }\n  } ]\n}\nDATA"
        }
      },
      "delete": {
        "description": "Delete Product by key",
        "operationId": "Delete Product by key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_products:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X DELETE https://api.europe-west1.gcp.commercetools.com/{projectKey}/products/key={key}?version={version} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "x-annotation-resourceName": "ByProjectKeyProductsKeyByKey",
      "x-annotation-resourcePathUri": "/{projectKey}/products/key={key}"
    },
    "/{projectKey}/products/{ID}": {
      "get": {
        "description": "Gets the full representation of a product by ID.",
        "operationId": "Get Product by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_products:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X GET https://api.europe-west1.gcp.commercetools.com/{projectKey}/products/{ID} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "post": {
        "description": "Update Product by ID",
        "operationId": "Update Product by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_products:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X POST https://api.europe-west1.gcp.commercetools.com/{projectKey}/products/{ID} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}' \\\n--header 'Content-Type: application/json' \\\n--data-binary @- << DATA \n{\n  \"version\" : 2,\n  \"actions\" : [ {\n    \"action\" : \"setDescription\",\n    \"description\" : {\n      \"en\" : \"The best product ever!\"\n    }\n  } ]\n}\nDATA"
        }
      },
      "delete": {
        "description": "Delete Product by ID",
        "operationId": "Delete Product by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_products:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X DELETE https://api.europe-west1.gcp.commercetools.com/{projectKey}/products/{ID}?version={version} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "x-annotation-resourceName": "ByProjectKeyProductsByID",
      "x-annotation-resourcePathUri": "/{projectKey}/products/{ID}"
    },
    "/{projectKey}/products/{ID}/images": {
      "post": {
        "description": "Uploads a binary image file to a given product variant. The supported image formats are JPEG, PNG and GIF.",
        "operationId": "Upload a product image",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_products:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-resourceName": "ByProjectKeyProductsByIDImages",
      "x-annotation-resourcePathUri": "/{projectKey}/products/{ID}/images"
    },
    "/{projectKey}/reviews": {
      "get": {
        "description": "Query reviews",
        "operationId": "Query reviews",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_products:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X GET https://api.europe-west1.gcp.commercetools.com/{projectKey}/reviews -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "post": {
        "description": "Create Review",
        "operationId": "Create Review",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_products:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X POST https://api.europe-west1.gcp.commercetools.com/{projectKey}/reviews -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}' \\\n--header 'Content-Type: application/json' \\\n--data-binary @- << DATA \n{\n  \"authorName\" : \"John Doe\",\n  \"title\" : \"Incredible\",\n  \"text\" : \"Best product ever\",\n  \"rating\" : 5,\n  \"target\" : {\n    \"typeId\" : \"product\",\n    \"id\" : \"8fddacac-6ef5-4e66-af6e-124452123456\"\n  }\n}\nDATA"
        }
      },
      "x-annotation-resourceName": "ByProjectKeyReviews",
      "x-annotation-resourcePathUri": "/{projectKey}/reviews"
    },
    "/{projectKey}/reviews/key={key}": {
      "get": {
        "description": "Get Review by key",
        "operationId": "Get Review by key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_products:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X GET https://api.europe-west1.gcp.commercetools.com/{projectKey}/reviews/key={key} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "post": {
        "description": "Update Review by key",
        "operationId": "Update Review by key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_products:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X POST https://api.europe-west1.gcp.commercetools.com/{projectKey}/reviews/key={key} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}' \\\n--header 'Content-Type: application/json' \\\n--data-binary @- << DATA \n{\n  \"version\" : 1,\n  \"actions\" : [ {\n    \"action\" : \"setAuthorName\",\n    \"authorName\" : \"John Doe\"\n  } ]\n}\nDATA"
        }
      },
      "delete": {
        "description": "Delete Review by key",
        "operationId": "Delete Review by key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_products:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X DELETE https://api.europe-west1.gcp.commercetools.com/{projectKey}/reviews/key={key}?version={version} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "x-annotation-resourceName": "ByProjectKeyReviewsKeyByKey",
      "x-annotation-resourcePathUri": "/{projectKey}/reviews/key={key}"
    },
    "/{projectKey}/reviews/{ID}": {
      "get": {
        "description": "Get Review by ID",
        "operationId": "Get Review by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_products:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X GET https://api.europe-west1.gcp.commercetools.com/{projectKey}/reviews/{ID} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "post": {
        "description": "Update Review by ID",
        "operationId": "Update Review by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_products:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X POST https://api.europe-west1.gcp.commercetools.com/{projectKey}/reviews/{ID} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}' \\\n--header 'Content-Type: application/json' \\\n--data-binary @- << DATA \n{\n  \"version\" : 1,\n  \"actions\" : [ {\n    \"action\" : \"setAuthorName\",\n    \"authorName\" : \"John Doe\"\n  } ]\n}\nDATA"
        }
      },
      "delete": {
        "description": "Delete Review by ID",
        "operationId": "Delete Review by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_products:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X DELETE https://api.europe-west1.gcp.commercetools.com/{projectKey}/reviews/{ID}?version={version} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "x-annotation-resourceName": "ByProjectKeyReviewsByID",
      "x-annotation-resourcePathUri": "/{projectKey}/reviews/{ID}"
    },
    "/{projectKey}/shipping-methods": {
      "get": {
        "description": "Query shipping-methods",
        "operationId": "Query shipping-methods",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_orders:{projectKey}",
              "view_shipping_methods:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X GET https://api.europe-west1.gcp.commercetools.com/{projectKey}/shipping-methods -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "post": {
        "description": "Create ShippingMethod",
        "operationId": "Create ShippingMethod",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_orders:{projectKey}",
              "manage_shipping_methods:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X POST https://api.europe-west1.gcp.commercetools.com/{projectKey}/shipping-methods -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}' \\\n--header 'Content-Type: application/json' \\\n--data-binary @- << DATA \n{\n  \"name\" : \"DHL\",\n  \"description\" : \"Standard delivery\",\n  \"taxCategory\" : {\n    \"typeId\" : \"tax-category\",\n    \"id\" : \"5a21f15b-34f8-4b7f-9407-d1eb82a73eba\"\n  },\n  \"zoneRates\" : [ {\n    \"zone\" : {\n      \"typeId\" : \"zone\"[...]"
        }
      },
      "x-annotation-resourceName": "ByProjectKeyShippingMethods",
      "x-annotation-resourcePathUri": "/{projectKey}/shipping-methods"
    },
    "/{projectKey}/shipping-methods/key={key}": {
      "get": {
        "description": "Get ShippingMethod by key",
        "operationId": "Get ShippingMethod by key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_orders:{projectKey}",
              "view_shipping_methods:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X GET https://api.europe-west1.gcp.commercetools.com/{projectKey}/shipping-methods/key={key} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "post": {
        "description": "Update ShippingMethod by key",
        "operationId": "Update ShippingMethod by key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_orders:{projectKey}",
              "manage_shipping_methods:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X POST https://api.europe-west1.gcp.commercetools.com/{projectKey}/shipping-methods/key={key} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}' \\\n--header 'Content-Type: application/json' \\\n--data-binary @- << DATA \n{\n  \"version\" : 1,\n  \"actions\" : [ {\n    \"action\" : \"changeName\",\n    \"name\" : \"New Name\"\n  } ]\n}\nDATA"
        }
      },
      "delete": {
        "description": "Delete ShippingMethod by key",
        "operationId": "Delete ShippingMethod by key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_orders:{projectKey}",
              "manage_shipping_methods:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X DELETE https://api.europe-west1.gcp.commercetools.com/{projectKey}/shipping-methods/key={key}?version={version} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "x-annotation-resourceName": "ByProjectKeyShippingMethodsKeyByKey",
      "x-annotation-resourcePathUri": "/{projectKey}/shipping-methods/key={key}"
    },
    "/{projectKey}/shipping-methods/matching-cart": {
      "get": {
        "operationId": "Get ShippingMethods for a cart",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_orders:{projectKey}",
              "view_shipping_methods:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X GET https://api.europe-west1.gcp.commercetools.com/{projectKey}/shipping-methods/matching-cart?cartId={cartId} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "x-annotation-resourceName": "ByProjectKeyShippingMethodsMatchingCart",
      "x-annotation-resourcePathUri": "/{projectKey}/shipping-methods/matching-cart"
    },
    "/{projectKey}/shipping-methods/matching-location": {
      "get": {
        "operationId": "Get ShippingMethods for a location",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_orders:{projectKey}",
              "view_shipping_methods:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X GET https://api.europe-west1.gcp.commercetools.com/{projectKey}/shipping-methods/matching-location?country={country} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "x-annotation-resourceName": "ByProjectKeyShippingMethodsMatchingLocation",
      "x-annotation-resourcePathUri": "/{projectKey}/shipping-methods/matching-location"
    },
    "/{projectKey}/shipping-methods/matching-orderedit": {
      "get": {
        "operationId": "Get ShippingMethods for an order edit",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_orders:{projectKey}",
              "view_shipping_methods:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X GET https://api.europe-west1.gcp.commercetools.com/{projectKey}/shipping-methods/matching-orderedit?orderEditId={orderEditId}&country={country} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "x-annotation-resourceName": "ByProjectKeyShippingMethodsMatchingOrderedit",
      "x-annotation-resourcePathUri": "/{projectKey}/shipping-methods/matching-orderedit"
    },
    "/{projectKey}/shipping-methods/{ID}": {
      "get": {
        "description": "Get ShippingMethod by ID",
        "operationId": "Get ShippingMethod by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_orders:{projectKey}",
              "view_shipping_methods:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X GET https://api.europe-west1.gcp.commercetools.com/{projectKey}/shipping-methods/{ID} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "post": {
        "description": "Update ShippingMethod by ID",
        "operationId": "Update ShippingMethod by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_orders:{projectKey}",
              "manage_shipping_methods:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X POST https://api.europe-west1.gcp.commercetools.com/{projectKey}/shipping-methods/{ID} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}' \\\n--header 'Content-Type: application/json' \\\n--data-binary @- << DATA \n{\n  \"version\" : 1,\n  \"actions\" : [ {\n    \"action\" : \"changeName\",\n    \"name\" : \"New Name\"\n  } ]\n}\nDATA"
        }
      },
      "delete": {
        "description": "Delete ShippingMethod by ID",
        "operationId": "Delete ShippingMethod by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_orders:{projectKey}",
              "manage_shipping_methods:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X DELETE https://api.europe-west1.gcp.commercetools.com/{projectKey}/shipping-methods/{ID}?version={version} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "x-annotation-resourceName": "ByProjectKeyShippingMethodsByID",
      "x-annotation-resourcePathUri": "/{projectKey}/shipping-methods/{ID}"
    },
    "/{projectKey}/shopping-lists": {
      "get": {
        "description": "Query shopping-lists",
        "operationId": "Query shopping-lists",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_shopping_lists:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X GET https://api.europe-west1.gcp.commercetools.com/{projectKey}/shopping-lists -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "post": {
        "description": "Create ShoppingList",
        "operationId": "Create ShoppingList",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_shopping_lists:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X POST https://api.europe-west1.gcp.commercetools.com/{projectKey}/shopping-lists -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}' \\\n--header 'Content-Type: application/json' \\\n--data-binary @- << DATA \n{\n  \"name\" : {\n    \"en\" : \"test\"\n  },\n  \"key\" : \"test\"\n}\nDATA"
        }
      },
      "x-annotation-resourceName": "ByProjectKeyShoppingLists",
      "x-annotation-resourcePathUri": "/{projectKey}/shopping-lists"
    },
    "/{projectKey}/shopping-lists/key={key}": {
      "get": {
        "description": "Gets a shopping list by Key.",
        "operationId": "Get ShoppingList by key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_shopping_lists:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X GET https://api.europe-west1.gcp.commercetools.com/{projectKey}/shopping-lists/key={key} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "post": {
        "description": "Update a shopping list found by its Key.",
        "operationId": "Update ShoppingList by key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_shopping_lists:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X POST https://api.europe-west1.gcp.commercetools.com/{projectKey}/shopping-lists/key={key} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}' \\\n--header 'Content-Type: application/json' \\\n--data-binary @- << DATA \n{\n  \"version\" : 1,\n  \"actions\" : [ {\n    \"action\" : \"changeName\",\n    \"name\" : {\n      \"en\" : \"New Name\"\n    }\n  } ]\n}\nDATA"
        }
      },
      "delete": {
        "description": "Delete ShoppingList by key",
        "operationId": "Delete ShoppingList by key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_shopping_lists:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X DELETE https://api.europe-west1.gcp.commercetools.com/{projectKey}/shopping-lists/key={key}?version={version} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "x-annotation-resourceName": "ByProjectKeyShoppingListsKeyByKey",
      "x-annotation-resourcePathUri": "/{projectKey}/shopping-lists/key={key}"
    },
    "/{projectKey}/shopping-lists/{ID}": {
      "get": {
        "description": "Gets a shopping list by ID.",
        "operationId": "Get ShoppingList by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_shopping_lists:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X GET https://api.europe-west1.gcp.commercetools.com/{projectKey}/shopping-lists/{ID} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "post": {
        "description": "Update ShoppingList by ID",
        "operationId": "Update ShoppingList by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_shopping_lists:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X POST https://api.europe-west1.gcp.commercetools.com/{projectKey}/shopping-lists/{ID} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}' \\\n--header 'Content-Type: application/json' \\\n--data-binary @- << DATA \n{\n  \"version\" : 1,\n  \"actions\" : [ {\n    \"action\" : \"changeName\",\n    \"name\" : {\n      \"en\" : \"New Name\"\n    }\n  } ]\n}\nDATA"
        }
      },
      "delete": {
        "description": "Delete ShoppingList by ID",
        "operationId": "Delete ShoppingList by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_shopping_lists:{projectKey}"
            ]
          }
        ],
        "x-annotation-codeExamples": {
          "curl": "curl -X DELETE https://api.europe-west1.gcp.commercetools.com/{projectKey}/shopping-lists/{ID}?version={version} -i \\\n--header 'Authorization: Bearer ${BEARER_TOKEN}'"
        }
      },
      "x-annotation-resourceName": "ByProjectKeyShoppingListsByID",
      "x-annotation-resourcePathUri": "/{projectKey}/shopping-lists/{ID}"
    },
    "/{projectKey}/states": {
      "get": {
        "description": "Query states",
        "operationId": "Query states",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_states:{projectKey}"
            ]
          }
        ],
[...]
