{
  "swagger": "2.0",
  "info": {
    "title": "Commercetools",
    "version": "v1"
  },
  "host": "api.europe-west1.gcp.commercetools.com",
  "schemes": [
    "https"
  ],
  "securityDefinitions": {
    "oauth_2_0": {
      "description": "HTTP API authorization uses [OAuth2](http://tools.ietf.org/html/rfc6750).\n\nClients must obtain an access token from the auth service using one of\nthe authorization flows described below, before they are able to make authorized requests\nto other commercetools services. On successful completion of an authorization flow,\na client will be given an `access_token`, which they need to include in requests\nto authorized service endpoints via the HTTP `Authorization` header lik[...]",
      "type": "oauth2",
      "flow": "application",
      "tokenUrl": "https://auth.europe-west1.gcp.commercetools.com/oauth/token",
      "scopes": {
        "manage_project:{projectKey}": "",
        "manage_products:{projectKey}": "",
        "view_products:{projectKey}": "",
        "manage_orders:{projectKey}": "",
        "manage_orders:{projectKey}:{storeKey}": "",
        "view_orders:{projectKey}": "",
        "view_orders:{projectKey}:{storeKey}": "",
        "manage_customers:{projectKey}": "",
        "view_customers:{projectKey}": "",
        "manage_payments:{projectKey}": "",
        "view_payments:{projectKey}": "",
        "manage_subscriptions:{projectKey}": "",
        "manage_extensions:{projectKey}": "",
        "manage_types:{projectKey}": "",
        "view_types:{projectKey}": "",
        "view_shopping_lists:{projectKey}": "",
        "manage_shopping_lists:{projectKey}": "",
        "manage_my_orders:{projectKey}": "",
        "manage_my_orders:{projectKey}:{storeKey}": "",
        "manage_my_profile:{projectKey}": "",
        "view_project_settings:{projectKey}": "",
        "view_published_products:{projectKey}": "",
        "manage_cart_discounts:{projectKey}": "",
        "view_cart_discounts:{projectKey}": "",
        "manage_customer_groups:{projectKey}": "",
        "view_customer_groups:{projectKey}": "",
        "view_shipping_methods:{projectKey}": "",
        "manage_shipping_methods:{projectKey}": "",
        "manage_tax_categories:{projectKey}": "",
        "view_tax_categories:{projectKey}": "",
        "manage_categories:{projectKey}": "",
        "view_categories:{projectKey}": ""
      }
    }
  },
  "paths": {
    "/{projectKey}": {
      "post": {
        "description": "Update project",
        "operationId": "Update project settings",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}"
            ]
          }
        ]
      },
      "get": {
        "description": "The Endpoint is responding a limited set of information about settings and configuration of the project.\n",
        "operationId": "Get project settings",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-updateable": "Project",
      "x-annotation-methodName": "withProjectKey"
    },
    "/{projectKey}/carts": {
      "get": {
        "description": "Query carts",
        "operationId": "Query carts",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_orders:{projectKey}"
            ]
          }
        ]
      },
      "post": {
        "description": "Creating a cart can fail with an InvalidOperation if the referenced shipping method in the\nCartDraft has a predicate which does not match the cart.\n",
        "operationId": "Create Cart",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_orders:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-updateable": "Cart",
      "x-annotation-deleteable": "Cart",
      "x-annotation-createable": "CartDraft"
    },
    "/{projectKey}/carts/{ID}": {
      "post": {
        "description": "Update Cart by ID",
        "operationId": "Update Cart by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_orders:{projectKey}"
            ]
          }
        ]
      },
      "get": {
        "description": "The cart may not contain up-to-date prices, discounts etc.\nIf you want to ensure they're up-to-date, send an Update request with the Recalculate update action instead.\n",
        "operationId": "Get Cart by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_orders:{projectKey}"
            ]
          }
        ]
      },
      "delete": {
        "description": "Delete Cart by ID",
        "operationId": "Delete Cart by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_orders:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-methodName": "withId"
    },
    "/{projectKey}/carts/replicate": {
      "post": {
        "operationId": "Replicate cart",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_orders:{projectKey}"
            ]
          }
        ]
      }
    },
    "/{projectKey}/carts/customer-id={customerId}": {
      "get": {
        "description": "Retrieves the active cart of the customer that has been modified most recently.\nIt does not consider carts with CartOrigin Merchant. If no active cart exists, a 404 Not Found error is returned.\n\nThe cart may not contain up-to-date prices, discounts etc. If you want to ensure they're up-to-date,\nsend an Update request with the Recalculate update action instead.\n",
        "operationId": "Get Cart by customerId",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_orders:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-methodName": "withCustomerId"
    },
    "/{projectKey}/cart-discounts": {
      "get": {
        "description": "Query cart-discounts",
        "operationId": "Query cart-discounts",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_orders:{projectKey}",
              "view_cart_discounts:{projectKey}"
            ]
          }
        ]
      },
      "post": {
        "description": "Create CartDiscount",
        "operationId": "Create CartDiscount",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_orders:{projectKey}",
              "manage_cart_discounts:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-updateable": "CartDiscount",
      "x-annotation-deleteable": "CartDiscount",
      "x-annotation-createable": "CartDiscountDraft"
    },
    "/{projectKey}/cart-discounts/key={key}": {
      "post": {
        "description": "Update CartDiscount by key",
        "operationId": "Update CartDiscount by key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_orders:{projectKey}",
              "manage_cart_discounts:{projectKey}"
            ]
          }
        ]
      },
      "get": {
        "description": "Get CartDiscount by key",
        "operationId": "Get CartDiscount by key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_orders:{projectKey}",
              "view_cart_discounts:{projectKey}"
            ]
          }
        ]
      },
      "delete": {
        "description": "Delete CartDiscount by key",
        "operationId": "Delete CartDiscount by key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_orders:{projectKey}",
              "manage_cart_discounts:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-methodName": "withKey"
    },
    "/{projectKey}/cart-discounts/{ID}": {
      "post": {
        "description": "Update CartDiscount by ID",
        "operationId": "Update CartDiscount by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_orders:{projectKey}",
              "manage_cart_discounts:{projectKey}"
            ]
          }
        ]
      },
      "get": {
        "description": "Get CartDiscount by ID",
        "operationId": "Get CartDiscount by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_orders:{projectKey}",
              "view_cart_discounts:{projectKey}"
            ]
          }
        ]
      },
      "delete": {
        "description": "Delete CartDiscount by ID",
        "operationId": "Delete CartDiscount by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_orders:{projectKey}",
              "manage_cart_discounts:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-methodName": "withId"
    },
    "/{projectKey}/categories": {
      "get": {
        "description": "Query categories",
        "operationId": "Query categories",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_products:{projectKey}",
              "view_categories:{projectKey}"
            ]
          }
        ]
      },
      "post": {
        "description": "Creating a category produces the CategoryCreated message.",
        "operationId": "Create Category",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_products:{projectKey}",
              "view_categories:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-updateable": "Category",
      "x-annotation-deleteable": "Category",
      "x-annotation-createable": "CategoryDraft"
    },
    "/{projectKey}/categories/key={key}": {
      "post": {
        "description": "Update Category by key",
        "operationId": "Update Category by key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_products:{projectKey}",
              "manage_categories:{projectKey}"
            ]
          }
        ]
      },
      "get": {
        "description": "Get Category by key",
        "operationId": "Get Category by key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_products:{projectKey}",
              "view_categories:{projectKey}"
            ]
          }
        ]
      },
      "delete": {
        "description": "Delete Category by key",
        "operationId": "Delete Category by key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_products:{projectKey}",
              "manage_categories:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-methodName": "withKey"
    },
    "/{projectKey}/categories/{ID}": {
      "post": {
        "description": "Update Category by ID",
        "operationId": "Update Category by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_products:{projectKey}",
              "manage_categories:{projectKey}"
            ]
          }
        ]
      },
      "get": {
        "description": "Get Category by ID",
        "operationId": "Get Category by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_products:{projectKey}",
              "view_categories:{projectKey}"
            ]
          }
        ]
      },
      "delete": {
        "description": "Delete Category by ID",
        "operationId": "Delete Category by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_products:{projectKey}",
              "manage_categories:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-methodName": "withId"
    },
    "/{projectKey}/channels": {
      "get": {
        "description": "Query channels",
        "operationId": "Query channels",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_products:{projectKey}"
            ]
          }
        ]
      },
      "post": {
        "description": "Create Channel",
        "operationId": "Create Channel",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_products:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-updateable": "Channel",
      "x-annotation-deleteable": "Channel",
      "x-annotation-createable": "ChannelDraft"
    },
    "/{projectKey}/channels/{ID}": {
      "post": {
        "description": "Update Channel by ID",
        "operationId": "Update Channel by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_products:{projectKey}"
            ]
          }
        ]
      },
      "get": {
        "description": "Get Channel by ID",
        "operationId": "Get Channel by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_products:{projectKey}"
            ]
          }
        ]
      },
      "delete": {
        "description": "Delete Channel by ID",
        "operationId": "Delete Channel by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_products:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-methodName": "withId"
    },
    "/{projectKey}/customers": {
      "get": {
        "description": "Query customers",
        "operationId": "Query customers",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_customers:{projectKey}"
            ]
          }
        ]
      },
      "post": {
        "description": "Creates a customer. If an anonymous cart is passed in,\nthen the cart is assigned to the created customer and the version number of the Cart will increase.\nIf the ID of an anonymous session is given, all carts and orders will be assigned to the created customer.\n",
        "operationId": "Create Customer",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_customers:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-updateable": "Customer",
      "x-annotation-deleteable": "Customer",
      "x-annotation-createable": "CustomerDraft"
    },
    "/{projectKey}/customers/key={key}": {
      "post": {
        "description": "Update Customer by key",
        "operationId": "Update Customer by key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_customers:{projectKey}"
            ]
          }
        ]
      },
      "get": {
        "description": "Get Customer by key",
        "operationId": "Get Customer by key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_customers:{projectKey}"
            ]
          }
        ]
      },
      "delete": {
        "description": "Delete Customer by key",
        "operationId": "Delete Customer by key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_customers:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-methodName": "withKey"
    },
    "/{projectKey}/customers/{ID}": {
      "post": {
        "description": "Update Customer by ID",
        "operationId": "Update Customer by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_customers:{projectKey}"
            ]
          }
        ]
      },
      "get": {
        "description": "Get Customer by ID",
        "operationId": "Get Customer by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_customers:{projectKey}"
            ]
          }
        ]
      },
      "delete": {
        "description": "Delete Customer by ID",
        "operationId": "Delete Customer by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_customers:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-methodName": "withId"
    },
    "/{projectKey}/customers/password-token={passwordToken}": {
      "get": {
        "description": "Get Customer by passwordToken",
        "operationId": "Get customer by password verification token",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_customers:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-methodName": "withPasswordToken"
    },
    "/{projectKey}/customers/email-token={emailToken}": {
      "get": {
        "description": "Get Customer by emailToken",
        "operationId": "Get customer by email verification token",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_customers:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-methodName": "withEmailToken"
    },
    "/{projectKey}/customers/email-token": {
      "post": {
        "description": "Create a Token for verifying the Customer's Email",
        "operationId": "Create a Token for verifying the Customer's Email",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_customers:{projectKey}"
            ]
          }
        ]
      }
    },
    "/{projectKey}/customers/email/confirm": {
      "post": {
        "description": "Verifies customer's email using a token.",
        "operationId": "Verifies customer's email.",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_customers:{projectKey}"
            ]
          }
        ]
      }
    },
    "/{projectKey}/customers/password": {
      "post": {
        "description": "Change a customers password",
        "operationId": "Change a customers password",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_customers:{projectKey}"
            ]
          }
        ]
      }
    },
    "/{projectKey}/customers/password/reset": {
      "post": {
        "description": "Set a new password using a token.",
        "operationId": "Reset Customer's Password",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_customers:{projectKey}"
            ]
          }
        ]
      }
    },
    "/{projectKey}/customers/password-token": {
      "post": {
        "description": "The token value is used to reset the password of the customer with the given email. The token is\nvalid only for 10 minutes.\n",
        "operationId": "Create a Token for Resetting the Customer's Password",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_customers:{projectKey}"
            ]
          }
        ]
      }
    },
    "/{projectKey}/customer-groups": {
      "get": {
        "description": "Query customer-groups",
        "operationId": "Query customer-groups",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_customers:{projectKey}",
              "view_customer_groups:{projectKey}"
            ]
          }
        ]
      },
      "post": {
        "description": "Create CustomerGroup",
        "operationId": "Create CustomerGroup",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_customers:{projectKey}",
              "manage_customer_groups:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-updateable": "CustomerGroup",
      "x-annotation-deleteable": "CustomerGroup",
      "x-annotation-createable": "CustomerGroupDraft"
    },
    "/{projectKey}/customer-groups/key={key}": {
      "post": {
        "description": "Updates a customer group by Key.",
        "operationId": "Update CustomerGroup by key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_customers:{projectKey}",
              "manage_customer_groups:{projectKey}"
            ]
          }
        ]
      },
      "get": {
        "description": "Gets a customer group by Key.",
        "operationId": "Get CustomerGroup by key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_customers:{projectKey}",
              "view_customer_groups:{projectKey}"
            ]
          }
        ]
      },
      "delete": {
        "description": "Delete CustomerGroup by key",
        "operationId": "Delete CustomerGroup by key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_customers:{projectKey}",
              "manage_customer_groups:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-methodName": "withKey"
    },
    "/{projectKey}/customer-groups/{ID}": {
      "post": {
        "description": "Update CustomerGroup by ID",
        "operationId": "Update CustomerGroup by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_customers:{projectKey}",
              "manage_customer_groups:{projectKey}"
            ]
          }
        ]
      },
      "get": {
        "description": "Get CustomerGroup by ID",
        "operationId": "Get CustomerGroup by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_customers:{projectKey}",
              "view_customer_groups:{projectKey}"
            ]
          }
        ]
      },
      "delete": {
        "description": "Delete CustomerGroup by ID",
        "operationId": "Delete CustomerGroup by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_customers:{projectKey}",
              "manage_customer_groups:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-methodName": "withId"
    },
    "/{projectKey}/discount-codes": {
      "get": {
        "description": "Query discount-codes",
        "operationId": "Query discount-codes",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_orders:{projectKey}"
            ]
          }
        ]
      },
      "post": {
        "description": "Create DiscountCode",
        "operationId": "Create DiscountCode",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_orders:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-updateable": "DiscountCode",
      "x-annotation-deleteable": "DiscountCode",
      "x-annotation-createable": "DiscountCodeDraft"
    },
    "/{projectKey}/discount-codes/{ID}": {
      "post": {
        "description": "Update DiscountCode by ID",
        "operationId": "Update DiscountCode by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_orders:{projectKey}"
            ]
          }
        ]
      },
      "get": {
        "description": "Get DiscountCode by ID",
        "operationId": "Get DiscountCode by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_orders:{projectKey}"
            ]
          }
        ]
      },
      "delete": {
        "description": "Delete DiscountCode by ID",
        "operationId": "Delete DiscountCode by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_orders:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-methodName": "withId"
    },
    "/{projectKey}/inventory": {
      "get": {
        "description": "Query inventory",
        "operationId": "Query inventory",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_products:{projectKey}"
            ]
          }
        ]
      },
      "post": {
        "description": "Create InventoryEntry",
        "operationId": "Create InventoryEntry",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_products:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-updateable": "InventoryEntry",
      "x-annotation-deleteable": "InventoryEntry",
      "x-annotation-createable": "InventoryEntryDraft"
    },
    "/{projectKey}/inventory/{ID}": {
      "post": {
        "description": "Update InventoryEntry by ID",
        "operationId": "Update InventoryEntry by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_products:{projectKey}"
            ]
          }
        ]
      },
      "get": {
        "description": "Get InventoryEntry by ID",
        "operationId": "Get InventoryEntry by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_products:{projectKey}"
            ]
          }
        ]
      },
      "delete": {
        "description": "Delete InventoryEntry by ID",
        "operationId": "Delete InventoryEntry by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_products:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-methodName": "withId"
    },
    "/{projectKey}/orders": {
      "get": {
        "description": "Query orders",
        "operationId": "Query orders",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_orders:{projectKey}"
            ]
          }
        ]
      },
      "post": {
        "description": "Creates an order from a Cart.\nThe cart must have a shipping address set before creating an order.\nWhen using the Platform TaxMode, the shipping address is used for tax calculation.\n",
        "operationId": "Create Order",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_orders:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-updateable": "Order",
      "x-annotation-deleteable": "Order",
      "x-annotation-createable": "OrderFromCartDraft"
    },
    "/{projectKey}/orders/order-number={orderNumber}": {
      "post": {
        "description": "Update Order by orderNumber",
        "operationId": "Update Order by orderNumber",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_orders:{projectKey}"
            ]
          }
        ]
      },
      "get": {
        "description": "In case the orderNumber does not match the regular expression [a-zA-Z0-9_\\-]+,\nit should be provided in URL-encoded format.\n",
        "operationId": "Get Order by orderNumber",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_orders:{projectKey}"
            ]
          }
        ]
      },
      "delete": {
        "description": "Delete Order by orderNumber",
        "operationId": "Delete Order by orderNumber",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_orders:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-methodName": "withOrderNumber"
    },
    "/{projectKey}/orders/{ID}": {
      "post": {
        "description": "Update Order by ID",
        "operationId": "Update Order by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_orders:{projectKey}"
            ]
          }
        ]
      },
      "get": {
        "description": "Get Order by ID",
        "operationId": "Get Order by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_orders:{projectKey}"
            ]
          }
        ]
      },
      "delete": {
        "description": "Delete Order by ID",
        "operationId": "Delete Order by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_orders:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-methodName": "withId"
    },
    "/{projectKey}/orders/edits": {
      "get": {
        "description": "Query edits",
        "operationId": "Query edits",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_order_edits:{projectKey}"
            ]
          }
        ]
      },
      "post": {
        "description": "Create OrderEdit",
        "operationId": "Create OrderEdit",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_order_edits:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-updateable": "OrderEdit",
      "x-annotation-deleteable": "OrderEdit",
      "x-annotation-createable": "OrderEditDraft"
    },
    "/{projectKey}/orders/edits/key={key}": {
      "post": {
        "description": "Update OrderEdit by key",
        "operationId": "Update OrderEdit by key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_order_edits:{projectKey}"
            ]
          }
        ]
      },
      "get": {
        "description": "Get OrderEdit by key",
        "operationId": "Get OrderEdit by key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_order_edits:{projectKey}"
            ]
          }
        ]
      },
      "delete": {
        "description": "Delete OrderEdit by key",
        "operationId": "Delete OrderEdit by key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_order_edits:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-methodName": "withKey"
    },
    "/{projectKey}/orders/edits/{ID}": {
      "post": {
        "description": "Update OrderEdit by ID",
        "operationId": "Update OrderEdit by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_order_edits:{projectKey}"
            ]
          }
        ]
      },
      "get": {
        "description": "Get OrderEdit by ID",
        "operationId": "Get OrderEdit by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_order_edits:{projectKey}"
            ]
          }
        ]
      },
      "delete": {
        "description": "Delete OrderEdit by ID",
        "operationId": "Delete OrderEdit by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_order_edits:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-methodName": "withId"
    },
    "/{projectKey}/orders/edits/{ID}/apply": {
      "post": {
        "operationId": "Apply order edit",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_order_edits:{projectKey}"
            ]
          }
        ]
      }
    },
    "/{projectKey}/orders/import": {
      "post": {
        "description": "Create an Order by Import",
        "operationId": "Create an Order by Import",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_orders:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-methodName": "importOrder"
    },
    "/{projectKey}/products": {
      "get": {
        "description": "You can use the query endpoint to get the full representations of products.\nREMARK: We suggest to use the performance optimized search endpoint which has a bunch functionalities,\nthe query API lacks like sorting on custom attributes, etc.\n",
        "operationId": "Query products",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_products:{projectKey}"
            ]
          }
        ]
      },
      "post": {
        "description": "To create a new product, send a representation that is going to become the initial staged representation\nof the new product in the master catalog. If price selection query parameters are provided,\nthe selected prices will be added to the response.\n",
        "operationId": "Create Product",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_products:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-updateable": "Product",
      "x-annotation-deleteable": "Product",
      "x-annotation-createable": "ProductDraft"
    },
    "/{projectKey}/products/key={key}": {
      "post": {
        "description": "Update Product by key",
        "operationId": "Update Product by key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_products:{projectKey}"
            ]
          }
        ]
      },
      "get": {
        "description": "Gets the full representation of a product by Key.",
        "operationId": "Get Product by key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_products:{projectKey}"
            ]
          }
        ]
      },
      "delete": {
        "description": "Delete Product by key",
        "operationId": "Delete Product by key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_products:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-methodName": "withKey"
    },
    "/{projectKey}/products/{ID}": {
      "post": {
        "description": "Update Product by ID",
        "operationId": "Update Product by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_products:{projectKey}"
            ]
          }
        ]
      },
      "get": {
        "description": "Gets the full representation of a product by ID.",
        "operationId": "Get Product by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_products:{projectKey}"
            ]
          }
        ]
      },
      "delete": {
        "description": "Delete Product by ID",
        "operationId": "Delete Product by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_products:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-methodName": "withId"
    },
    "/{projectKey}/products/{ID}/images": {
      "post": {
        "description": "Uploads a binary image file to a given product variant. The supported image formats are JPEG, PNG and GIF.\n",
        "operationId": "Upload a product image",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_products:{projectKey}"
            ]
          }
        ]
      }
    },
    "/{projectKey}/payments": {
      "get": {
        "description": "Query payments",
        "operationId": "Query payments",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_payments:{projectKey}"
            ]
          }
        ]
      },
      "post": {
        "description": "To create a payment object a payment draft object has to be given with the request.",
        "operationId": "Create Payment",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_payments:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-updateable": "Payment",
      "x-annotation-deleteable": "Payment",
      "x-annotation-createable": "PaymentDraft"
    },
    "/{projectKey}/payments/key={key}": {
      "post": {
        "description": "Update Payment by key",
        "operationId": "Update Payment by key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_payments:{projectKey}"
            ]
          }
        ]
      },
      "get": {
        "description": "Get Payment by key",
        "operationId": "Get Payment by key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_payments:{projectKey}"
            ]
          }
        ]
      },
      "delete": {
        "description": "Delete Payment by key",
        "operationId": "Delete Payment by key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_payments:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-methodName": "withKey"
    },
    "/{projectKey}/payments/{ID}": {
      "post": {
        "description": "Update Payment by ID",
        "operationId": "Update Payment by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_payments:{projectKey}"
            ]
          }
        ]
      },
      "get": {
        "description": "Get Payment by ID",
        "operationId": "Get Payment by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_payments:{projectKey}"
            ]
          }
        ]
      },
      "delete": {
        "description": "Delete Payment by ID",
        "operationId": "Delete Payment by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_payments:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-methodName": "withId"
    },
    "/{projectKey}/product-discounts": {
      "get": {
        "description": "Query product-discounts",
        "operationId": "Query product-discounts",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_products:{projectKey}"
            ]
          }
        ]
      },
      "post": {
        "description": "Create ProductDiscount",
        "operationId": "Create ProductDiscount",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_products:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-updateable": "ProductDiscount",
      "x-annotation-deleteable": "ProductDiscount",
      "x-annotation-createable": "ProductDiscountDraft"
    },
    "/{projectKey}/product-discounts/key={key}": {
      "post": {
        "description": "Update ProductDiscount by key",
        "operationId": "Update ProductDiscount by key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_products:{projectKey}"
            ]
          }
        ]
      },
      "get": {
        "description": "Get ProductDiscount by key",
        "operationId": "Get ProductDiscount by key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_products:{projectKey}"
            ]
          }
        ]
      },
      "delete": {
        "description": "Delete ProductDiscount by key",
        "operationId": "Delete ProductDiscount by key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_products:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-methodName": "withKey"
    },
    "/{projectKey}/product-discounts/{ID}": {
      "post": {
        "description": "Update ProductDiscount by ID",
        "operationId": "Update ProductDiscount by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_products:{projectKey}"
            ]
          }
        ]
      },
      "get": {
        "description": "Get ProductDiscount by ID",
        "operationId": "Get ProductDiscount by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_products:{projectKey}"
            ]
          }
        ]
      },
      "delete": {
        "description": "Delete ProductDiscount by ID",
        "operationId": "Delete ProductDiscount by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_products:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-methodName": "withId"
    },
    "/{projectKey}/product-discounts/matching": {
      "post": {
        "operationId": "Get matching product discounts",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_products:{projectKey}"
            ]
          }
        ]
      }
    },
    "/{projectKey}/product-types": {
      "get": {
        "description": "Query product-types",
        "operationId": "Query product-types",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_products:{projectKey}"
            ]
          }
        ]
      },
      "post": {
        "description": "Create ProductType",
        "operationId": "Create ProductType",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_products:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-updateable": "ProductType",
      "x-annotation-deleteable": "ProductType",
      "x-annotation-createable": "ProductTypeDraft"
    },
    "/{projectKey}/product-types/key={key}": {
      "post": {
        "description": "Update ProductType by key",
        "operationId": "Update ProductType by key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_products:{projectKey}"
            ]
          }
        ]
      },
      "get": {
        "description": "Get ProductType by key",
        "operationId": "Get ProductType by key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_products:{projectKey}"
            ]
          }
        ]
      },
      "delete": {
        "description": "Delete ProductType by key",
        "operationId": "Delete ProductType by key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_products:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-methodName": "withKey"
    },
    "/{projectKey}/product-types/{ID}": {
      "post": {
        "description": "Update ProductType by ID",
        "operationId": "Update ProductType by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_products:{projectKey}"
            ]
          }
        ]
      },
      "get": {
        "description": "Get ProductType by ID",
        "operationId": "Get ProductType by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_products:{projectKey}"
            ]
          }
        ]
      },
      "delete": {
        "description": "Delete ProductType by ID",
        "operationId": "Delete ProductType by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_products:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-methodName": "withId"
    },
    "/{projectKey}/shipping-methods": {
      "get": {
        "description": "Query shipping-methods",
        "operationId": "Query shipping-methods",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_orders:{projectKey}",
              "view_shipping_methods:{projectKey}"
            ]
          }
        ]
      },
      "post": {
        "description": "Create ShippingMethod",
        "operationId": "Create ShippingMethod",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_orders:{projectKey}",
              "manage_shipping_methods:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-updateable": "ShippingMethod",
      "x-annotation-deleteable": "ShippingMethod",
      "x-annotation-createable": "ShippingMethodDraft"
    },
    "/{projectKey}/shipping-methods/key={key}": {
      "post": {
        "description": "Update ShippingMethod by key",
        "operationId": "Update ShippingMethod by key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_orders:{projectKey}",
              "manage_shipping_methods:{projectKey}"
            ]
          }
        ]
      },
      "get": {
        "description": "Get ShippingMethod by key",
        "operationId": "Get ShippingMethod by key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_orders:{projectKey}",
              "view_shipping_methods:{projectKey}"
            ]
          }
        ]
      },
      "delete": {
        "description": "Delete ShippingMethod by key",
        "operationId": "Delete ShippingMethod by key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_orders:{projectKey}",
              "manage_shipping_methods:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-methodName": "withKey"
    },
    "/{projectKey}/shipping-methods/{ID}": {
      "post": {
        "description": "Update ShippingMethod by ID",
        "operationId": "Update ShippingMethod by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_orders:{projectKey}",
              "manage_shipping_methods:{projectKey}"
            ]
          }
        ]
      },
      "get": {
        "description": "Get ShippingMethod by ID",
        "operationId": "Get ShippingMethod by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_orders:{projectKey}",
              "view_shipping_methods:{projectKey}"
            ]
          }
        ]
      },
      "delete": {
        "description": "Delete ShippingMethod by ID",
        "operationId": "Delete ShippingMethod by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_orders:{projectKey}",
              "manage_shipping_methods:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-methodName": "withId"
    },
    "/{projectKey}/shipping-methods/matching-cart": {
      "get": {
        "operationId": "Get ShippingMethods for a cart",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_orders:{projectKey}",
              "view_shipping_methods:{projectKey}"
            ]
          }
        ]
      }
    },
    "/{projectKey}/shipping-methods/matching-orderedit": {
      "get": {
        "operationId": "Get ShippingMethods for an order edit",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_orders:{projectKey}",
              "view_shipping_methods:{projectKey}"
            ]
          }
        ]
      }
    },
    "/{projectKey}/shipping-methods/matching-location": {
      "get": {
        "operationId": "Get ShippingMethods for a location",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_orders:{projectKey}",
              "view_shipping_methods:{projectKey}"
            ]
          }
        ]
      }
    },
    "/{projectKey}/reviews": {
      "get": {
        "description": "Query reviews",
        "operationId": "Query reviews",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_products:{projectKey}"
            ]
          }
        ]
      },
      "post": {
        "description": "Create Review",
        "operationId": "Create Review",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_products:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-updateable": "Review",
      "x-annotation-deleteable": "Review",
      "x-annotation-createable": "ReviewDraft"
    },
    "/{projectKey}/reviews/key={key}": {
      "post": {
        "description": "Update Review by key",
        "operationId": "Update Review by key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_products:{projectKey}"
            ]
          }
        ]
      },
      "get": {
        "description": "Get Review by key",
        "operationId": "Get Review by key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_products:{projectKey}"
            ]
          }
        ]
      },
      "delete": {
        "description": "Delete Review by key",
        "operationId": "Delete Review by key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_products:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-methodName": "withKey"
    },
    "/{projectKey}/reviews/{ID}": {
      "post": {
        "description": "Update Review by ID",
        "operationId": "Update Review by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_products:{projectKey}"
            ]
          }
        ]
      },
      "get": {
        "description": "Get Review by ID",
        "operationId": "Get Review by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_products:{projectKey}"
            ]
          }
        ]
      },
      "delete": {
        "description": "Delete Review by ID",
        "operationId": "Delete Review by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_products:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-methodName": "withId"
    },
    "/{projectKey}/shopping-lists": {
      "get": {
        "description": "Query shopping-lists",
        "operationId": "Query shopping-lists",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_shopping_lists:{projectKey}"
            ]
          }
        ]
      },
      "post": {
        "description": "Create ShoppingList",
        "operationId": "Create ShoppingList",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_shopping_lists:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-updateable": "ShoppingList",
      "x-annotation-deleteable": "ShoppingList",
      "x-annotation-createable": "ShoppingListDraft"
    },
    "/{projectKey}/shopping-lists/key={key}": {
      "post": {
        "description": "Update a shopping list found by its Key.",
        "operationId": "Update ShoppingList by key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_shopping_lists:{projectKey}"
            ]
          }
        ]
      },
      "get": {
        "description": "Gets a shopping list by Key.",
        "operationId": "Get ShoppingList by key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_shopping_lists:{projectKey}"
            ]
          }
        ]
      },
      "delete": {
        "description": "Delete ShoppingList by key",
        "operationId": "Delete ShoppingList by key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_shopping_lists:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-methodName": "withKey"
    },
    "/{projectKey}/shopping-lists/{ID}": {
      "post": {
        "description": "Update ShoppingList by ID",
        "operationId": "Update ShoppingList by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_shopping_lists:{projectKey}"
            ]
          }
        ]
      },
      "get": {
        "description": "Gets a shopping list by ID.",
        "operationId": "Get ShoppingList by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_shopping_lists:{projectKey}"
            ]
          }
        ]
      },
      "delete": {
        "description": "Delete ShoppingList by ID",
        "operationId": "Delete ShoppingList by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_shopping_lists:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-methodName": "withId"
    },
    "/{projectKey}/states": {
      "get": {
        "description": "Query states",
        "operationId": "Query states",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_orders:{projectKey}"
            ]
          }
        ]
      },
      "post": {
        "description": "Create State",
        "operationId": "Create State",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_orders:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-updateable": "State",
      "x-annotation-deleteable": "State",
      "x-annotation-createable": "StateDraft"
    },
    "/{projectKey}/states/{ID}": {
      "post": {
        "description": "Update State by ID",
        "operationId": "Update State by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_orders:{projectKey}"
            ]
          }
        ]
      },
      "get": {
        "description": "Get State by ID",
        "operationId": "Get State by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_orders:{projectKey}"
            ]
          }
        ]
      },
      "delete": {
        "description": "Delete State by ID",
        "operationId": "Delete State by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_orders:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-methodName": "withId"
    },
    "/{projectKey}/subscriptions": {
      "get": {
        "description": "Query subscriptions",
        "operationId": "Query subscriptions",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_subscriptions:{projectKey}"
            ]
          }
        ]
      },
      "post": {
        "description": "The creation of a Subscription is eventually consistent, it may take up to a minute before it becomes fully active.\nIn order to test that the destination is correctly configured, a test message will be put into the queue.\nIf the message could not be delivered, the subscription will not be created.\nThe payload of the test message is a notification of type ResourceCreated for the resourceTypeId subscription.\nCurrently, a maximum of 25 subscriptions can be created per pr[...]",
        "operationId": "Create Subscription",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_subscriptions:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-updateable": "Subscription",
      "x-annotation-deleteable": "Subscription",
      "x-annotation-createable": "SubscriptionDraft"
    },
    "/{projectKey}/subscriptions/key={key}": {
      "post": {
        "description": "Update Subscription by key",
        "operationId": "Update Subscription by key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_subscriptions:{projectKey}"
            ]
          }
        ]
      },
      "get": {
        "description": "Retrieves the representation of a subscription by its key.",
        "operationId": "Get Subscription by key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_subscriptions:{projectKey}"
            ]
          }
        ]
      },
      "delete": {
        "description": "Delete Subscription by key",
        "operationId": "Delete Subscription by key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_subscriptions:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-methodName": "withKey"
    },
    "/{projectKey}/subscriptions/{ID}": {
      "post": {
        "description": "Update Subscription by ID",
        "operationId": "Update Subscription by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_subscriptions:{projectKey}"
            ]
          }
        ]
      },
      "get": {
        "description": "Retrieves the representation of a subscription by its id.",
        "operationId": "Get Subscription by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_subscriptions:{projectKey}"
            ]
          }
        ]
      },
      "delete": {
        "description": "Delete Subscription by ID",
        "operationId": "Delete Subscription by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_subscriptions:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-methodName": "withId"
    },
    "/{projectKey}/tax-categories": {
      "get": {
        "description": "Query tax-categories",
        "operationId": "Query tax-categories",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_products:{projectKey}",
              "view_tax_categories:{projectKey}"
            ]
          }
        ]
      },
      "post": {
        "description": "Create TaxCategory",
        "operationId": "Create TaxCategory",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_products:{projectKey}",
              "manage_tax_categories:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-updateable": "TaxCategory",
      "x-annotation-deleteable": "TaxCategory",
      "x-annotation-createable": "TaxCategoryDraft"
    },
    "/{projectKey}/tax-categories/key={key}": {
      "post": {
        "description": "Update TaxCategory by key",
        "operationId": "Update TaxCategory by key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_products:{projectKey}",
              "manage_tax_categories:{projectKey}"
            ]
          }
        ]
      },
      "get": {
        "description": "Get TaxCategory by key",
        "operationId": "Get TaxCategory by key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_products:{projectKey}",
              "view_tax_categories:{projectKey}"
            ]
          }
        ]
      },
      "delete": {
        "description": "Delete TaxCategory by key",
        "operationId": "Delete TaxCategory by key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_products:{projectKey}",
              "manage_tax_categories:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-methodName": "withKey"
    },
    "/{projectKey}/tax-categories/{ID}": {
      "post": {
        "description": "Update TaxCategory by ID",
        "operationId": "Update TaxCategory by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_products:{projectKey}",
              "manage_tax_categories:{projectKey}"
            ]
          }
        ]
      },
      "get": {
        "description": "Get TaxCategory by ID",
        "operationId": "Get TaxCategory by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_products:{projectKey}",
              "view_tax_categories:{projectKey}"
            ]
          }
        ]
      },
      "delete": {
        "description": "Delete TaxCategory by ID",
        "operationId": "Delete TaxCategory by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_products:{projectKey}",
              "manage_tax_categories:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-methodName": "withId"
    },
    "/{projectKey}/types": {
      "get": {
        "description": "Query types",
        "operationId": "Query types",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_types:{projectKey}"
            ]
          }
        ]
      },
      "post": {
        "description": "Create Type",
        "operationId": "Create Type",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_types:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-updateable": "Type",
      "x-annotation-deleteable": "Type",
      "x-annotation-createable": "TypeDraft"
    },
    "/{projectKey}/types/key={key}": {
      "post": {
        "description": "Update Type by key",
        "operationId": "Update Type by key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_types:{projectKey}"
            ]
          }
        ]
      },
      "get": {
        "description": "Get Type by key",
        "operationId": "Get Type by key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_types:{projectKey}"
            ]
          }
        ]
      },
      "delete": {
        "description": "Delete Type by key",
        "operationId": "Delete Type by key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_types:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-methodName": "withKey"
    },
    "/{projectKey}/types/{ID}": {
      "post": {
        "description": "Update Type by ID",
        "operationId": "Update Type by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_types:{projectKey}"
            ]
          }
        ]
      },
      "get": {
        "description": "Get Type by ID",
        "operationId": "Get Type by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_types:{projectKey}"
            ]
          }
        ]
      },
      "delete": {
        "description": "Delete Type by ID",
        "operationId": "Delete Type by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_types:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-methodName": "withId"
    },
    "/{projectKey}/zones": {
      "get": {
        "description": "Query zones",
        "operationId": "Query zones",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_orders:{projectKey}"
            ]
          }
        ]
      },
      "post": {
        "description": "Create Zone",
        "operationId": "Create Zone",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_orders:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-updateable": "Zone",
      "x-annotation-deleteable": "Zone",
      "x-annotation-createable": "ZoneDraft"
    },
    "/{projectKey}/zones/key={key}": {
      "post": {
        "description": "Update Zone by key",
        "operationId": "Update Zone by key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_orders:{projectKey}"
            ]
          }
        ]
      },
      "get": {
        "description": "Get Zone by key",
        "operationId": "Get Zone by key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_orders:{projectKey}"
            ]
          }
        ]
      },
      "delete": {
        "description": "Delete Zone by key",
        "operationId": "Delete Zone by key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_orders:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-methodName": "withKey"
    },
    "/{projectKey}/zones/{ID}": {
      "post": {
        "description": "Update Zone by ID",
        "operationId": "Update Zone by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_orders:{projectKey}"
            ]
          }
        ]
      },
      "get": {
        "description": "Get Zone by ID",
        "operationId": "Get Zone by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_orders:{projectKey}"
            ]
          }
        ]
      },
      "delete": {
        "description": "Delete Zone by ID",
        "operationId": "Delete Zone by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_orders:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-methodName": "withId"
    },
    "/{projectKey}/extensions": {
      "get": {
        "description": "Query extensions",
        "operationId": "Query extensions",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_extensions:{projectKey}"
            ]
          }
        ]
      },
      "post": {
        "description": "Currently, a maximum of 25 extensions can be created per project.",
        "operationId": "Create Extension",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_extensions:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-updateable": "Extension",
      "x-annotation-deleteable": "Extension",
      "x-annotation-createable": "ExtensionDraft"
    },
    "/{projectKey}/extensions/key={key}": {
      "post": {
        "description": "Update Extension by key",
        "operationId": "Update Extension by key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_extensions:{projectKey}"
            ]
          }
        ]
      },
      "get": {
        "description": "Retrieves the representation of an extension by its key.",
        "operationId": "Get Extension by key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_extensions:{projectKey}"
            ]
          }
        ]
      },
      "delete": {
        "description": "Delete Extension by key",
        "operationId": "Delete Extension by key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_extensions:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-methodName": "withKey"
    },
    "/{projectKey}/extensions/{ID}": {
      "post": {
        "description": "Update Extension by ID",
        "operationId": "Update Extension by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_extensions:{projectKey}"
            ]
          }
        ]
      },
      "get": {
        "description": "Retrieves the representation of an extension by its id.",
        "operationId": "Get Extension by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_extensions:{projectKey}"
            ]
          }
        ]
      },
      "delete": {
        "description": "Delete Extension by ID",
        "operationId": "Delete Extension by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_extensions:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-methodName": "withId"
    },
    "/{projectKey}/stores": {
      "get": {
        "description": "Query stores",
        "operationId": "Query stores",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_stores:{projectKey}"
            ]
          }
        ]
      },
      "post": {
        "description": "Create Store",
        "operationId": "Create Store",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_stores:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-updateable": "Store",
      "x-annotation-deleteable": "Store",
      "x-annotation-createable": "StoreDraft"
    },
    "/{projectKey}/stores/key={key}": {
      "post": {
        "description": "Update Store by key",
        "operationId": "Update Store by key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_stores:{projectKey}"
            ]
          }
        ]
      },
      "get": {
        "description": "Get Store by key",
        "operationId": "Get Store by key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_stores:{projectKey}"
            ]
          }
        ]
      },
      "delete": {
        "description": "Delete Store by key",
        "operationId": "Delete Store by key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_stores:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-methodName": "withKey"
    },
    "/{projectKey}/stores/{ID}": {
      "post": {
        "description": "Update Store by ID",
        "operationId": "Update Store by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_stores:{projectKey}"
            ]
          }
        ]
      },
      "get": {
        "description": "Get Store by ID",
        "operationId": "Get Store by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_stores:{projectKey}"
            ]
          }
        ]
      },
      "delete": {
        "description": "Delete Store by ID",
        "operationId": "Delete Store by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_stores:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-methodName": "withId"
    },
    "/{projectKey}/in-store/key={storeKey}/carts": {
      "get": {
        "description": "Queries carts in a specific Store. The {storeKey} path parameter maps to a Store's key.",
        "operationId": "Query carts",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_orders:{projectKey}",
              "view_orders:{projectKey}:{storeKey}"
            ]
          }
        ]
      },
      "post": {
        "description": "Creates a cart in the store specified by {storeKey}. The {storeKey} path parameter maps to a Store's key.\nWhen using this endpoint the cart's store field is always set to the store specified in the path parameter.\nCreating a cart can fail with an InvalidOperation if the referenced shipping method\nin the CartDraft has a predicate which does not match the cart.\n",
        "operationId": "Create Cart",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_orders:{projectKey}",
              "manage_orders:{projectKey}:{storeKey}"
            ]
          }
        ]
      },
      "x-annotation-updateable": "Cart",
      "x-annotation-deleteable": "Cart",
      "x-annotation-createable": "CartDraft"
    },
    "/{projectKey}/in-store/key={storeKey}/carts/{ID}": {
      "post": {
        "description": "Updates a cart in the store specified by {storeKey}. The {storeKey} path parameter maps to a Store's key.\nIf the cart exists in the commercetools project but does not have the store field,\nor the store field references a different store, this method returns a ResourceNotFound error.\n",
        "operationId": "Update Cart by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_orders:{projectKey}",
              "manage_orders:{projectKey}:{storeKey}"
            ]
          }
        ]
      },
      "get": {
        "description": "Returns a cart by its ID from a specific Store. The {storeKey} path parameter maps to a Store's key.\nIf the cart exists in the commercetools project but does not have the store field,\nor the store field references a different store, this method returns a ResourceNotFound error.\nThe cart may not contain up-to-date prices, discounts etc.\nIf you want to ensure they're up-to-date, send an Update request with the Recalculate update action instead.\n",
        "operationId": "Get Cart by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_orders:{projectKey}",
              "view_orders:{projectKey}:{storeKey}"
            ]
          }
        ]
      },
      "delete": {
        "description": "Delete Cart by ID",
        "operationId": "Delete Cart by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_orders:{projectKey}",
              "manage_orders:{projectKey}:{storeKey}"
            ]
          }
        ]
      },
      "x-annotation-methodName": "withId"
    },
    "/{projectKey}/in-store/key={storeKey}/carts/customer-id={customerId}": {
      "get": {
        "description": "Retrieves the active cart of the customer that has been modified most recently in a specific Store.\nThe {storeKey} path parameter maps to a Store's key.\n\nIf the cart exists in the commercetools project but does not have the store field, or the store field\nreferences a different store, this method returns a ResourceNotFound error.\n\nThe cart may not contain up-to-date prices, discounts etc. If you want to ensure they're up-to-date,\nsend an Update request with the Rec[...]",
        "operationId": "Get Cart by customerId",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_orders:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-methodName": "withCustomerId"
    },
    "/{projectKey}/in-store/key={storeKey}/orders": {
      "get": {
        "description": "Queries orders in a specific Store. The {storeKey} path parameter maps to a Store's key.",
        "operationId": "Query orders",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_orders:{projectKey}",
              "view_orders:{projectKey}:{storeKey}"
            ]
          }
        ]
      },
      "post": {
        "description": "Creates an order from a Cart from a specific Store. The {storeKey} path parameter maps to a Store's key.\nWhen using this endpoint the orders's store field is always set to the store specified in the path parameter.\nThe cart must have a shipping address set before creating an order. When using the Platform TaxMode,\nthe shipping address is used for tax calculation.\n",
        "operationId": "Create Order",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_orders:{projectKey}",
              "manage_orders:{projectKey}:{storeKey}"
            ]
          }
        ]
      },
      "x-annotation-updateable": "Order",
      "x-annotation-deleteable": "Order",
      "x-annotation-createable": "OrderFromCartDraft"
    },
    "/{projectKey}/in-store/key={storeKey}/orders/order-number={orderNumber}": {
      "post": {
        "description": "Updates an order in the store specified by {storeKey}. The {storeKey} path parameter maps to a Store's key.\nIf the order exists in the commercetools project but does not have the store field,\nor the store field references a different store, this method returns a ResourceNotFound error.\nIn case the orderNumber does not match the regular expression [a-zA-Z0-9_\\-]+,\nit should be provided in URL-encoded format.\n",
        "operationId": "Update Order by orderNumber",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_orders:{projectKey}",
              "manage_orders:{projectKey}:{storeKey}"
            ]
          }
        ]
      },
      "get": {
        "description": "Returns an order by its order number from a specific Store.\nThe {storeKey} path parameter maps to a Store's key.\nIf the order exists in the commercetools project but does not have the store field,\nor the store field references a different store, this method returns a ResourceNotFound error.\nIn case the orderNumber does not match the regular expression [a-zA-Z0-9_\\-]+,\nit should be provided in URL-encoded format.\n",
        "operationId": "Get Order by orderNumber",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_orders:{projectKey}",
              "view_orders:{projectKey}:{storeKey}"
            ]
          }
        ]
      },
      "delete": {
        "description": "Delete Order by orderNumber",
        "operationId": "Delete Order by orderNumber",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_orders:{projectKey}",
              "manage_orders:{projectKey}:{storeKey}"
            ]
          }
        ]
      },
      "x-annotation-methodName": "withOrderNumber"
    },
    "/{projectKey}/in-store/key={storeKey}/orders/{ID}": {
      "post": {
        "description": "Updates an order in the store specified by {storeKey}. The {storeKey} path parameter maps to a Store's key.\nIf the order exists in the commercetools project but does not have the store field,\nor the store field references a different store, this method returns a ResourceNotFound error.\n",
        "operationId": "Update Order by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_orders:{projectKey}",
              "manage_orders:{projectKey}:{storeKey}"
            ]
          }
        ]
      },
      "get": {
        "description": "Returns an order by its ID from a specific Store. The {storeKey} path parameter maps to a Store's key.\nIf the order exists in the commercetools project but does not have the store field,\nor the store field references a different store, this method returns a ResourceNotFound error.\n",
        "operationId": "Get Order by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_orders:{projectKey}",
              "view_orders:{projectKey}:{storeKey}"
            ]
          }
        ]
      },
      "delete": {
        "description": "Delete Order by ID",
        "operationId": "Delete Order by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_orders:{projectKey}",
              "manage_orders:{projectKey}:{storeKey}"
            ]
          }
        ]
      },
      "x-annotation-methodName": "withId"
    },
    "/{projectKey}/in-store/key={storeKey}/me/carts": {
      "get": {
        "description": "Query carts",
        "operationId": "Query carts",
        "security": [
          {
            "oauth_2_0": [
              "manage_my_orders:{projectKey}",
              "manage_my_orders:{projectKey}:{storeKey}"
            ]
          }
        ]
      },
      "post": {
        "description": "Create Cart",
        "operationId": "Create Cart",
        "security": [
          {
            "oauth_2_0": [
              "manage_my_orders:{projectKey}",
              "manage_my_orders:{projectKey}:{storeKey}"
            ]
          }
        ]
      }
    },
    "/{projectKey}/in-store/key={storeKey}/me/carts/{ID}": {
      "get": {
        "description": "Get Cart by ID",
        "operationId": "Get Cart by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_my_orders:{projectKey}",
              "manage_my_orders:{projectKey}:{storeKey}"
            ]
          }
        ]
      },
      "post": {
        "description": "Update Cart by ID",
        "operationId": "Update Cart by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_my_orders:{projectKey}",
              "manage_my_orders:{projectKey}:{storeKey}"
            ]
          }
        ]
      },
      "delete": {
        "description": "Delete Cart by ID",
        "operationId": "Delete Cart by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_my_orders:{projectKey}",
              "manage_my_orders:{projectKey}:{storeKey}"
            ]
          }
        ]
      },
      "x-annotation-methodName": "withId"
    },
    "/{projectKey}/in-store/key={storeKey}/me/orders": {
      "get": {
        "description": "Query orders",
        "operationId": "Query orders",
        "security": [
          {
            "oauth_2_0": [
              "manage_my_orders:{projectKey}",
              "manage_my_orders:{projectKey}:{storeKey}"
            ]
          }
        ]
      },
      "post": {
        "description": "Create Order",
        "operationId": "Create Order",
        "security": [
          {
            "oauth_2_0": [
              "manage_my_orders:{projectKey}",
              "manage_my_orders:{projectKey}:{storeKey}"
            ]
          }
        ]
      }
    },
    "/{projectKey}/in-store/key={storeKey}/me/orders/{ID}": {
      "get": {
        "description": "Get Order by ID",
        "operationId": "Get Order by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_my_orders:{projectKey}",
              "manage_my_orders:{projectKey}:{storeKey}"
            ]
          }
        ]
      },
      "x-annotation-methodName": "withId"
    },
    "/{projectKey}/in-store/key={storeKey}/me/active-cart": {
      "get": {
        "operationId": "Get active cart",
        "security": [
          {
            "oauth_2_0": [
              "manage_my_orders:{projectKey}",
              "manage_my_orders:{projectKey}:{storeKey}"
            ]
          }
        ]
      }
    },
    "/{projectKey}/in-store/key={storeKey}/customers": {
      "get": {
        "description": "Query customers",
        "operationId": "Query customers",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_customers:{projectKey}",
              "view_customers:{projectKey}:{storeKey}"
            ]
          }
        ]
      },
      "post": {
        "description": "Creates a customer in a specific Store. The {storeKey} path parameter maps to a Store's key.\nWhen using this endpoint, if omitted,\nthe customer's stores field is set to the store specified in the path parameter.\nIf an anonymous cart is passed in as when using this method,\nthen the cart is assigned to the created customer and the version number of the Cart increases.\nIf the ID of an anonymous session is given, all carts and orders will be assigned to the created custo[...]",
        "operationId": "Create Customer",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_customers:{projectKey}",
              "manage_customers:{projectKey}:{storeKey}"
            ]
          }
        ]
      }
    },
    "/{projectKey}/in-store/key={storeKey}/customers/password-token={passwordToken}": {
      "get": {
        "description": "Get Customer by passwordToken",
        "operationId": "Get customer by password verification token",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_customers:{projectKey}",
              "view_customers:{projectKey}:{storeKey}"
            ]
          }
        ]
      },
      "x-annotation-methodName": "withPasswordToken"
    },
    "/{projectKey}/in-store/key={storeKey}/customers/email-token={emailToken}": {
      "get": {
        "description": "Get Customer by emailToken",
        "operationId": "Get customer by email verification token",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_customers:{projectKey}",
              "view_customers:{projectKey}:{storeKey}"
            ]
          }
        ]
      },
      "x-annotation-methodName": "withEmailToken"
    },
    "/{projectKey}/in-store/key={storeKey}/customers/email-token": {
      "post": {
        "description": "Create a Token for verifying the Customer's Email",
        "operationId": "Create a Token for verifying the Customer's Email",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_customers:{projectKey}",
              "manage_customers:{projectKey}:{storeKey}"
            ]
          }
        ]
      }
    },
    "/{projectKey}/in-store/key={storeKey}/customers/email/confirm": {
      "post": {
        "description": "Verifies customer's email using a token.",
        "operationId": "Verify Customer's Email",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_customers:{projectKey}",
              "manage_customers:{projectKey}:{storeKey}"
            ]
          }
        ]
      }
    },
    "/{projectKey}/in-store/key={storeKey}/customers/password": {
      "post": {
        "description": "Change a customers password",
        "operationId": "Change a customers password",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_customers:{projectKey}",
              "manage_customers:{projectKey}:{storeKey}"
            ]
          }
        ]
      }
    },
    "/{projectKey}/in-store/key={storeKey}/customers/password/reset": {
      "post": {
        "description": "Set a new password using a token.",
        "operationId": "Reset Customer's Password",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_customers:{projectKey}",
              "manage_customers:{projectKey}:{storeKey}"
            ]
          }
        ]
      }
    },
    "/{projectKey}/in-store/key={storeKey}/customers/password-token": {
      "post": {
        "description": "The token value is used to reset the password of the customer with the given email. The token is\nvalid only for 10 minutes.\n",
        "operationId": "Create a Token for Resetting the Customer's Password",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_customers:{projectKey}",
              "manage_customers:{projectKey}:{storeKey}"
            ]
          }
        ]
      }
    },
    "/{projectKey}/in-store/key={storeKey}/customers/key={key}": {
      "get": {
        "description": "Returns a customer by its Key from a specific Store. The {storeKey} path parameter maps to a Store's key.\nIt also considers customers that do not have the stores field.\nIf the customer exists in the commercetools project but the stores field references different stores,\nthis method returns a ResourceNotFound error.\n",
        "operationId": "Get Customer by key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_customers:{projectKey}",
              "view_customers:{projectKey}:{storeKey}"
            ]
          }
        ]
      },
      "post": {
        "description": "If the customer exists in the commercetools project but the stores field references a different store,\nthis method returns a ResourceNotFound error.\n",
        "operationId": "Update Customer by key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_customers:{projectKey}",
              "manage_customers:{projectKey}:{storeKey}"
            ]
          }
        ]
      },
      "delete": {
        "description": "Delete Customer by key",
        "operationId": "Delete Customer by key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_customers:{projectKey}",
              "manage_customers:{projectKey}:{storeKey}"
            ]
          }
        ]
      },
      "x-annotation-methodName": "withKey"
    },
    "/{projectKey}/in-store/key={storeKey}/customers/{ID}": {
      "get": {
        "description": "Returns a customer by its ID from a specific Store. The {storeKey} path parameter maps to a Store's key.\nIt also considers customers that do not have the stores field.\nIf the customer exists in the commercetools project but the stores field references different stores,\nthis method returns a ResourceNotFound error.\n",
        "operationId": "Get Customer by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_customers:{projectKey}",
              "view_customers:{projectKey}:{storeKey}"
            ]
          }
        ]
      },
      "post": {
        "description": "Updates a customer in the store specified by {storeKey}. The {storeKey} path parameter maps to a Store's key.\nIf the customer exists in the commercetools project but the stores field references a different store,\nthis method returns a ResourceNotFound error.\n",
        "operationId": "Update Customer by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_customers:{projectKey}",
              "manage_customers:{projectKey}:{storeKey}"
            ]
          }
        ]
      },
      "delete": {
        "description": "Delete Customer by ID",
        "operationId": "Delete Customer by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_customers:{projectKey}",
              "manage_customers:{projectKey}:{storeKey}"
            ]
          }
        ]
      },
      "x-annotation-methodName": "withId"
    },
    "/{projectKey}/in-store/key={storeKey}/login": {
      "post": {
        "description": "Authenticate Customer (Sign In)",
        "operationId": "Authenticate Customer (Sign In)",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_customers:{projectKey}",
              "manage_customers:{projectKey}:{storeKey}"
            ]
          }
        ]
      }
    },
    "/{projectKey}/in-store/key={storeKey}/shipping-methods/matching-cart": {
      "get": {
        "operationId": "Get ShippingMethods for a cart in a store",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_orders:{projectKey}",
              "manage_customers:{projectKey}:{storeKey}",
              "view_shipping_methods:{projectKey}"
            ]
          }
        ]
      }
    },
    "/{projectKey}/me": {
      "get": {
        "operationId": "Get customer",
        "security": [
          {
            "oauth_2_0": [
              "manage_my_profile:{projectKey}"
            ]
          }
        ]
      },
      "post": {
        "description": "Create a customer",
        "operationId": "Create a customer",
        "security": [
          {
            "oauth_2_0": [
              "manage_my_profile:{projectKey}"
            ]
          }
        ]
      },
      "delete": {
        "description": "Delete a Customer",
        "operationId": "Delete a Customer",
        "security": [
          {
            "oauth_2_0": [
              "manage_my_profile:{projectKey}"
            ]
          }
        ]
      }
    },
    "/{projectKey}/me/shopping-lists": {
      "get": {
        "description": "Query shopping-lists",
        "operationId": "Query shopping-lists",
        "security": [
          {
            "oauth_2_0": [
              "manage_my_shopping_lists:{projectKey}"
            ]
          }
        ]
      },
      "post": {
        "description": "Create MyShoppingList",
        "operationId": "Create MyShoppingList",
        "security": [
          {
            "oauth_2_0": [
              "manage_my_shopping_lists:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-updateable": "MyShoppingList",
      "x-annotation-deleteable": "MyShoppingList",
      "x-annotation-createable": "MyShoppingListDraft"
    },
    "/{projectKey}/me/shopping-lists/key={key}": {
      "post": {
        "description": "Update MyShoppingList by key",
        "operationId": "Update MyShoppingList by key",
        "security": [
          {
            "oauth_2_0": [
              "manage_my_shopping_lists:{projectKey}"
            ]
          }
        ]
      },
      "get": {
        "description": "Get MyShoppingList by key",
        "operationId": "Get MyShoppingList by key",
        "security": [
          {
            "oauth_2_0": [
              "manage_my_shopping_lists:{projectKey}"
            ]
          }
        ]
      },
      "delete": {
        "description": "Delete MyShoppingList by key",
        "operationId": "Delete MyShoppingList by key",
        "security": [
          {
            "oauth_2_0": [
              "manage_my_shopping_lists:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-methodName": "withKey"
    },
    "/{projectKey}/me/shopping-lists/{ID}": {
      "post": {
        "description": "Update MyShoppingList by ID",
        "operationId": "Update MyShoppingList by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_my_shopping_lists:{projectKey}"
            ]
          }
        ]
      },
      "get": {
        "description": "Get MyShoppingList by ID",
        "operationId": "Get MyShoppingList by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_my_shopping_lists:{projectKey}"
            ]
          }
        ]
      },
      "delete": {
        "description": "Delete MyShoppingList by ID",
        "operationId": "Delete MyShoppingList by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_my_shopping_lists:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-methodName": "withId"
    },
    "/{projectKey}/me/payments": {
      "get": {
        "description": "Query payments",
        "operationId": "Query payments",
        "security": [
          {
            "oauth_2_0": [
              "manage_my_payments:{projectKey}"
            ]
          }
        ]
      },
      "post": {
        "description": "Create MyPayment",
        "operationId": "Create MyPayment",
        "security": [
          {
            "oauth_2_0": [
              "manage_my_payments:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-updateable": "MyPayment",
      "x-annotation-deleteable": "MyPayment",
      "x-annotation-createable": "MyPaymentDraft"
    },
    "/{projectKey}/me/payments/key={key}": {
      "post": {
        "description": "Update MyPayment by key",
        "operationId": "Update MyPayment by key",
        "security": [
          {
            "oauth_2_0": [
              "manage_my_payments:{projectKey}"
            ]
          }
        ]
      },
      "get": {
        "description": "Get MyPayment by key",
        "operationId": "Get MyPayment by key",
        "security": [
          {
            "oauth_2_0": [
              "manage_my_payments:{projectKey}"
            ]
          }
        ]
      },
      "delete": {
        "description": "Delete MyPayment by key",
        "operationId": "Delete MyPayment by key",
        "security": [
          {
            "oauth_2_0": [
              "manage_my_payments:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-methodName": "withKey"
    },
    "/{projectKey}/me/payments/{ID}": {
      "post": {
        "description": "Update MyPayment by ID",
        "operationId": "Update MyPayment by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_my_payments:{projectKey}"
            ]
          }
        ]
      },
      "get": {
        "description": "Get MyPayment by ID",
        "operationId": "Get MyPayment by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_my_payments:{projectKey}"
            ]
          }
        ]
      },
      "delete": {
        "description": "Delete MyPayment by ID",
        "operationId": "Delete MyPayment by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_my_payments:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-methodName": "withId"
    },
    "/{projectKey}/me/email/confirm": {
      "post": {
        "operationId": "Verify Customer's Email",
        "security": [
          {
            "oauth_2_0": [
              "manage_my_profile:{projectKey}"
            ]
          }
        ]
      }
    },
    "/{projectKey}/me/password": {
      "post": {
        "operationId": "Change a customers password",
        "security": [
          {
            "oauth_2_0": [
              "manage_my_profile:{projectKey}"
            ]
          }
        ]
      }
    },
    "/{projectKey}/me/password/reset": {
      "post": {
        "operationId": "Reset Customer's Password",
        "security": [
          {
            "oauth_2_0": [
              "manage_my_profile:{projectKey}"
            ]
          }
        ]
      }
    },
    "/{projectKey}/me/signup": {
      "post": {
        "operationId": "Signup a customer",
        "security": [
          {
            "oauth_2_0": [
              "manage_my_profile:{projectKey}"
            ]
          }
        ]
      }
    },
    "/{projectKey}/me/login": {
      "post": {
        "operationId": "Authenticate Customer (Sign In)",
        "security": [
          {
            "oauth_2_0": [
              "manage_my_profile:{projectKey}"
            ]
          }
        ]
      }
    },
    "/{projectKey}/me/active-cart": {
      "get": {
        "operationId": "Get active cart",
        "security": [
          {
            "oauth_2_0": [
              "manage_my_orders:{projectKey}"
            ]
          }
        ]
      }
    },
    "/{projectKey}/me/carts": {
      "get": {
        "description": "Query carts",
        "operationId": "Query carts",
        "security": [
          {
            "oauth_2_0": [
              "manage_my_orders:{projectKey}"
            ]
          }
        ]
      },
      "post": {
        "description": "Create MyCart",
        "operationId": "Create MyCart",
        "security": [
          {
            "oauth_2_0": [
              "manage_my_orders:{projectKey}"
            ]
          }
        ]
      }
    },
    "/{projectKey}/me/carts/{ID}": {
      "get": {
        "description": "Get MyCart by ID",
        "operationId": "Get MyCart by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_my_orders:{projectKey}"
            ]
          }
        ]
      },
      "post": {
        "description": "Update MyCart by ID",
        "operationId": "Update MyCart by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_my_orders:{projectKey}"
            ]
          }
        ]
      },
      "delete": {
        "description": "Delete MyCart by ID",
        "operationId": "Delete MyCart by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_my_orders:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-methodName": "withId"
    },
    "/{projectKey}/me/orders": {
      "get": {
        "description": "Query orders",
        "operationId": "Query orders",
        "security": [
          {
            "oauth_2_0": [
              "manage_my_orders:{projectKey}"
            ]
          }
        ]
      },
      "post": {
        "description": "Create MyOrder",
        "operationId": "Create MyOrder",
        "security": [
          {
            "oauth_2_0": [
              "manage_my_orders:{projectKey}"
            ]
          }
        ]
      }
    },
    "/{projectKey}/me/orders/{ID}": {
      "get": {
        "description": "Get MyOrder by ID",
        "operationId": "Get MyOrder by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_my_orders:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-methodName": "withId"
    },
    "/{projectKey}/custom-objects": {
      "get": {
        "description": "The query endpoint allows to retrieve custom objects in a specific container or all custom objects.\nFor performance reasons, it is highly advisable to query only for custom objects in a container by using\nthe container field in the where predicate.\n",
        "operationId": "Query custom-objects",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_products:{projectKey}",
              "view_orders:{projectKey}",
              "view_customers:{projectKey}"
            ]
          }
        ]
      },
      "post": {
        "description": "Creates a new custom object or updates an existing custom object.\nIf an object with the given container/key exists,\nthe object will be replaced with the new value and the version is incremented.\nIf the request contains a version and an object with the given container/key exists then the version\nmust match the version of the existing object. Concurrent updates for the same custom object still can result\nin a Conflict (409) even if the version is not provided.\nFields [...]",
        "operationId": "Create CustomObject",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_products:{projectKey}",
              "manage_orders:{projectKey}",
              "manage_customers:{projectKey}"
            ]
          }
        ]
      }
    },
    "/{projectKey}/custom-objects/{container}/{key}": {
      "get": {
        "description": "Get CustomObject by container and key",
        "operationId": "Get CustomObject by container and key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_products:{projectKey}",
              "view_orders:{projectKey}",
              "view_customers:{projectKey}"
            ]
          }
        ]
      },
      "delete": {
        "description": "Delete CustomObject by container and key",
        "operationId": "Delete CustomObject by container and key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_products:{projectKey}",
              "manage_orders:{projectKey}",
              "manage_customers:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-methodName": "withContainerAndKey"
    },
    "/{projectKey}/custom-objects/{ID}": {
      "get": {
        "description": "Get CustomObject by ID",
        "operationId": "Get CustomObject by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_products:{projectKey}",
              "view_orders:{projectKey}",
              "view_customers:{projectKey}"
            ]
          }
        ]
      },
      "delete": {
        "description": "The version control is optional. If the query contains a version, then it must match the version of the object.\n",
        "operationId": "Delete CustomObject by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_products:{projectKey}",
              "manage_orders:{projectKey}",
              "manage_customers:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-methodName": "withId"
    },
    "/{projectKey}/graphql": {
      "post": {
        "description": "Execute a GraphQL query",
        "operationId": "GraphQL",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_products:{projectKey}"
            ]
          }
        ]
      }
    },
    "/{projectKey}/login": {
      "post": {
        "description": "Authenticate Customer (Sign In). Retrieves the authenticated\ncustomer (a customer that matches the given email/password pair).\nIf used with an access token for Anonymous Sessions,\nall orders and carts belonging to the anonymousId will be assigned to the newly created customer.\nIf a cart is is returned as part of the CustomerSignInResult,\nit has been recalculated (It will have up-to-date prices, taxes and discounts,\nand invalid line items have been removed.).\n",
        "operationId": "Authenticate Customer (Sign In)",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_customers:{projectKey}"
            ]
          }
        ]
      }
    },
    "/{projectKey}/messages": {
      "get": {
        "description": "Query messages",
        "operationId": "Query messages",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_orders:{projectKey}"
            ]
          }
        ]
      }
    },
    "/{projectKey}/messages/{ID}": {
      "get": {
        "description": "Get Message by ID",
        "operationId": "Get Message by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_orders:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-methodName": "withId"
    },
    "/{projectKey}/product-projections": {
      "get": {
        "description": "You can use the product projections query endpoint to get the current or staged representations of Products.\nWhen used with an API client that has the view_published_products:{projectKey} scope,\nthis endpoint only returns published (current) product projections.\n",
        "operationId": "Query product-projections",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_products:{projectKey}",
              "view_published_products:{projectKey}"
            ]
          }
        ]
      }
    },
    "/{projectKey}/product-projections/search": {
      "post": {
        "description": "Search Product Projection",
        "operationId": "Search Products",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_products:{projectKey}",
              "view_published_products:{projectKey}"
            ]
          }
        ]
      },
      "get": {
        "description": "Search Product Projection",
        "operationId": "Search Products",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_products:{projectKey}",
              "view_published_products:{projectKey}"
            ]
          }
        ]
      }
    },
    "/{projectKey}/product-projections/suggest": {
      "get": {
        "operationId": "Get suggestion keywords",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_products:{projectKey}",
              "view_published_products:{projectKey}"
            ]
          }
        ]
      }
    },
    "/{projectKey}/product-projections/key={key}": {
      "get": {
        "description": "Gets the current or staged representation of a product found by Key.\nWhen used with an API client that has the view_published_products:{projectKey} scope,\nthis endpoint only returns published (current) product projections.\n",
        "operationId": "Get ProductProjection by key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_products:{projectKey}",
              "view_published_products:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-methodName": "withKey"
    },
    "/{projectKey}/product-projections/{ID}": {
      "get": {
        "description": "Gets the current or staged representation of a product in a catalog by ID.\nWhen used with an API client that has the view_published_products:{projectKey} scope,\nthis endpoint only returns published (current) product projections.\n",
        "operationId": "Get ProductProjection by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_products:{projectKey}",
              "view_published_products:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-methodName": "withId"
    },
    "/{projectKey}/api-clients": {
      "get": {
        "description": "Query api-clients",
        "operationId": "Query api-clients",
        "security": [
          {
            "oauth_2_0": [
              "manage_api_clients:{projectKey}",
              "view_api_clients:{projectKey}"
            ]
          }
        ]
      },
      "post": {
        "description": "Create ApiClient",
        "operationId": "Create ApiClient",
        "security": [
          {
            "oauth_2_0": [
              "manage_api_clients:{projectKey}"
            ]
          }
        ]
      }
    },
    "/{projectKey}/api-clients/{ID}": {
      "get": {
        "description": "Get ApiClient by ID",
        "operationId": "Get ApiClient by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_api_clients:{projectKey}",
              "view_api_clients:{projectKey}"
            ]
          }
        ]
      },
      "delete": {
        "description": "Delete ApiClient by ID",
        "operationId": "Delete ApiClient by ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_api_clients:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-methodName": "withId"
    }
  }
}