#%RAML 1.0
---
title: Commercetools
baseUri: https://api.sphere.io
version: v1
securitySchemes:
  oauth_2_0: !include securitySchemes/oauth2.raml
securedBy: [ oauth_2_0 ]
traits:
    errorable: !include traits/errorable.raml
    deprecatable: !include traits/deprecatable.raml
    expandable: !include traits/expandable.raml
    query: !include traits/query.raml
    sortable: !include traits/sortable.raml
    paging: !include traits/paging.raml
    conflicting: !include traits/conflicting.raml
    versioned: !include traits/versioned.raml
    priceSelecting: !include traits/price-selecting.raml
annotationTypes: !include types/annotations.raml
types: !include types/types.raml
mediaType: application/json
resourceTypes:
  base:
      uriParameters:
        projectKey:
            type: string
      get?:
        is:
          - errorable
          - deprecatable
      post?:
        is:
          - errorable
          - deprecatable
      delete?:
        is:
          - errorable
          - deprecatable
  baseById:
    type: base
    uriParameters:
        ID:
            type: string
            pattern: ^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$
  baseByKey:
    type: base
    uriParameters:
        key:
            type: string
  baseByToken:
    type: base
    uriParameters:
        token:
            type: string
/{projectKey}:
  type: base
  displayName: Project
  description: The Project endpoint is used to retrieve certain information from a project.
  get:
    description: The Endpoint is responding a limited set of information about settings and configuration of the project.
    securedBy: [oauth_2_0: {scopes: ["manage_project:{projectKey}"]}]
    responses:
      200:
        body:
          example: !include examples/project.example.json
          type: Project
  /categories: !include resources/categories.raml
  /carts: !include resources/carts.raml
  /cart-discounts: !include resources/cart-discounts.raml
  /channels: !include resources/channels.raml
  /customers: !include resources/customers.raml
  /customer-groups: !include resources/customer-groups.raml
  /custom-objects: !include resources/custom-objects.raml
  /discount-codes: !include resources/discount-codes.raml
  /graphql: !include resources/graphql.raml
  /inventory: !include resources/inventory.raml
  /login: !include resources/login.raml
  /messages: !include resources/messages.raml
  /orders: !include resources/orders.raml
  /payments: !include resources/payments.raml
  /products: !include resources/products.raml
  /product-discounts: !include resources/product-discounts.raml
  /product-projections: !include resources/product-projections.raml
  /product-types: !include resources/product-types.raml
  /reviews: !include resources/reviews.raml
  /shipping-methods: !include resources/shipping-methods.raml
  /shopping-lists: !include resources/shopping-lists.raml
  /states: !include resources/states.raml
  /subscriptions: !include resources/subscriptions.raml
  /tax-categories: !include resources/tax-categories.raml
  /types: !include resources/types.raml
  /zones: !include resources/zones.raml
  /me: !include resources/me.raml

