{
  "swagger": "2.0",
  "info": {
    "title": "Commercetools",
    "version": "v1"
  },
  "host": "api.sphere.io",
  "schemes": [
    "https"
  ],
  "securityDefinitions": {
    "oauth_2_0": {
      "description": "HTTP API authorization uses [OAuth2](http://tools.ietf.org/html/rfc6750){:target=\"_blank\"}.\n\nClients must obtain an access token from the auth service using one of\nthe authorization flows described below, before they are able to make authorized requests\nto other SPHERE.IO services. On successful completion of an authorization flow,\na client will be given an `access_token`, which they need to include in requests\nto authorized service endpoints via the HTTP `Authoriza[...]",
      "type": "oauth2",
      "flow": "application",
      "tokenUrl": "https://auth.sphere.io/oauth/token",
      "scopes": {
        "manage_project:{projectKey}": "",
        "manage_products:{projectKey}": "",
        "view_products:{projectKey}": "",
        "manage_orders:{projectKey}": "",
        "view_orders:{projectKey}": "",
        "manage_customers:{projectKey}": "",
        "view_customers:{projectKey}": "",
        "manage_payments:{projectKey}": "",
        "view_payments:{projectKey}": "",
        "manage_subscriptions:{projectKey}": "",
        "manage_extensions:{projectKey}": "",
        "manage_types:{projectKey}": "",
        "view_types:{projectKey}": "",
        "view_shopping_lists:{projectKey}": "",
        "manage_shopping_lists:{projectKey}": "",
        "manage_my_orders:{projectKey}": "",
        "manage_my_profile:{projectKey}": "",
        "view_project_settings:{projectKey}": ""
      }
    }
  },
  "paths": {
    "/{projectKey}": {
      "post": {
        "description": "Update project",
        "operationId": "POST_projectKey",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}"
            ]
          }
        ]
      },
      "get": {
        "description": "The Endpoint is responding a limited set of information about settings and configuration of the project.\n",
        "operationId": "GET_projectKey",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-updateable": "Project"
    },
    "/{projectKey}/carts": {
      "get": {
        "description": "Query carts",
        "operationId": "GET_projectKey-carts",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_orders:{projectKey}"
            ]
          }
        ]
      },
      "post": {
        "description": "Create Cart",
        "operationId": "POST_projectKey-carts",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_orders:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-updateable": "Cart",
      "x-annotation-deleteable": "Cart",
      "x-annotation-createable": "CartDraft"
    },
    "/{projectKey}/carts/{ID}": {
      "post": {
        "description": "Update Cart by ID",
        "operationId": "POST_projectKey-carts-ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_orders:{projectKey}"
            ]
          }
        ]
      },
      "get": {
        "description": "Get Cart by ID",
        "operationId": "GET_projectKey-carts-ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_orders:{projectKey}"
            ]
          }
        ]
      },
      "delete": {
        "description": "Delete Cart by ID",
        "operationId": "DELETE_projectKey-carts-ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_orders:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-methodName": "withId"
    },
    "/{projectKey}/carts/replicate": {
      "post": {
        "operationId": "POST_projectKey-carts-replicate",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_orders:{projectKey}"
            ]
          }
        ]
      }
    },
    "/{projectKey}/cart-discounts": {
      "get": {
        "description": "Query cart-discounts",
        "operationId": "GET_projectKey-cart-discounts",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_orders:{projectKey}"
            ]
          }
        ]
      },
      "post": {
        "description": "Create CartDiscount",
        "operationId": "POST_projectKey-cart-discounts",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_orders:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-updateable": "CartDiscount",
      "x-annotation-deleteable": "CartDiscount",
      "x-annotation-createable": "CartDiscountDraft"
    },
    "/{projectKey}/cart-discounts/{ID}": {
      "post": {
        "description": "Update CartDiscount by ID",
        "operationId": "POST_projectKey-cart-discounts-ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_orders:{projectKey}"
            ]
          }
        ]
      },
      "get": {
        "description": "Get CartDiscount by ID",
        "operationId": "GET_projectKey-cart-discounts-ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_orders:{projectKey}"
            ]
          }
        ]
      },
      "delete": {
        "description": "Delete CartDiscount by ID",
        "operationId": "DELETE_projectKey-cart-discounts-ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_orders:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-methodName": "withId"
    },
    "/{projectKey}/categories": {
      "get": {
        "description": "Query categories",
        "operationId": "GET_projectKey-categories",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_products:{projectKey}"
            ]
          }
        ]
      },
      "post": {
        "description": "Create Category",
        "operationId": "POST_projectKey-categories",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_products:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-updateable": "Category",
      "x-annotation-deleteable": "Category",
      "x-annotation-createable": "CategoryDraft"
    },
    "/{projectKey}/categories/key={key}": {
      "post": {
        "description": "Update Category by key",
        "operationId": "POST_projectKey-categories-key=key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_products:{projectKey}"
            ]
          }
        ]
      },
      "get": {
        "description": "Get Category by key",
        "operationId": "GET_projectKey-categories-key=key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_products:{projectKey}"
            ]
          }
        ]
      },
      "delete": {
        "description": "Delete Category by key",
        "operationId": "DELETE_projectKey-categories-key=key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_products:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-methodName": "withKey"
    },
    "/{projectKey}/categories/{ID}": {
      "post": {
        "description": "Update Category by ID",
        "operationId": "POST_projectKey-categories-ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_products:{projectKey}"
            ]
          }
        ]
      },
      "get": {
        "description": "Get Category by ID",
        "operationId": "GET_projectKey-categories-ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_products:{projectKey}"
            ]
          }
        ]
      },
      "delete": {
        "description": "Delete Category by ID",
        "operationId": "DELETE_projectKey-categories-ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_products:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-methodName": "withId"
    },
    "/{projectKey}/channels": {
      "get": {
        "description": "Query channels",
        "operationId": "GET_projectKey-channels",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_products:{projectKey}"
            ]
          }
        ]
      },
      "post": {
        "description": "Create Channel",
        "operationId": "POST_projectKey-channels",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_products:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-updateable": "Channel",
      "x-annotation-deleteable": "Channel",
      "x-annotation-createable": "ChannelDraft"
    },
    "/{projectKey}/channels/{ID}": {
      "post": {
        "description": "Update Channel by ID",
        "operationId": "POST_projectKey-channels-ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_products:{projectKey}"
            ]
          }
        ]
      },
      "get": {
        "description": "Get Channel by ID",
        "operationId": "GET_projectKey-channels-ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_products:{projectKey}"
            ]
          }
        ]
      },
      "delete": {
        "description": "Delete Channel by ID",
        "operationId": "DELETE_projectKey-channels-ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_products:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-methodName": "withId"
    },
    "/{projectKey}/customers": {
      "get": {
        "description": "Query customers",
        "operationId": "GET_projectKey-customers",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_customers:{projectKey}"
            ]
          }
        ]
      },
      "post": {
        "description": "Create Customer",
        "operationId": "POST_projectKey-customers",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_customers:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-updateable": "Customer",
      "x-annotation-deleteable": "Customer",
      "x-annotation-createable": "CustomerDraft"
    },
    "/{projectKey}/customers/{ID}": {
      "post": {
        "description": "Update Customer by ID",
        "operationId": "POST_projectKey-customers-ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_customers:{projectKey}"
            ]
          }
        ]
      },
      "get": {
        "description": "Get Customer by ID",
        "operationId": "GET_projectKey-customers-ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_customers:{projectKey}"
            ]
          }
        ]
      },
      "delete": {
        "description": "Delete Customer by ID",
        "operationId": "DELETE_projectKey-customers-ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_customers:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-methodName": "withId"
    },
    "/{projectKey}/customers/password-token={passwordToken}": {
      "get": {
        "description": "Get Customer by passwordToken",
        "operationId": "GET_projectKey-customers-password-token=passwordToken",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_customers:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-methodName": "withPasswordToken"
    },
    "/{projectKey}/customers/email-token={emailToken}": {
      "get": {
        "description": "Get Customer by emailToken",
        "operationId": "GET_projectKey-customers-email-token=emailToken",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_customers:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-methodName": "withEmailToken"
    },
    "/{projectKey}/customers/email-token": {
      "post": {
        "description": "Create a Token for verifying the Customer's Email",
        "operationId": "POST_projectKey-customers-email-token",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_customers:{projectKey}"
            ]
          }
        ]
      }
    },
    "/{projectKey}/customers/email/confirm": {
      "post": {
        "description": "Verifies customer's email using a token.",
        "operationId": "POST_projectKey-customers-email-confirm",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_customers:{projectKey}"
            ]
          }
        ]
      }
    },
    "/{projectKey}/customers/password": {
      "post": {
        "description": "Change a customers password",
        "operationId": "POST_projectKey-customers-password",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_customers:{projectKey}"
            ]
          }
        ]
      }
    },
    "/{projectKey}/customers/password/reset": {
      "post": {
        "description": "Set a new password using a token.",
        "operationId": "POST_projectKey-customers-password-reset",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_customers:{projectKey}"
            ]
          }
        ]
      }
    },
    "/{projectKey}/customers/password-token": {
      "post": {
        "description": "The token value is used to reset the password of the customer with the given email. The token is\nvalid only for 10 minutes.\n",
        "operationId": "POST_projectKey-customers-password-token",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_customers:{projectKey}"
            ]
          }
        ]
      }
    },
    "/{projectKey}/customer-groups": {
      "get": {
        "description": "Query customer-groups",
        "operationId": "GET_projectKey-customer-groups",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_customers:{projectKey}"
            ]
          }
        ]
      },
      "post": {
        "description": "Create CustomerGroup",
        "operationId": "POST_projectKey-customer-groups",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_customers:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-updateable": "CustomerGroup",
      "x-annotation-deleteable": "CustomerGroup",
      "x-annotation-createable": "CustomerGroupDraft"
    },
    "/{projectKey}/customer-groups/key={key}": {
      "post": {
        "description": "Update CustomerGroup by key",
        "operationId": "POST_projectKey-customer-groups-key=key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_customers:{projectKey}"
            ]
          }
        ]
      },
      "get": {
        "description": "Get CustomerGroup by key",
        "operationId": "GET_projectKey-customer-groups-key=key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_customers:{projectKey}"
            ]
          }
        ]
      },
      "delete": {
        "description": "Delete CustomerGroup by key",
        "operationId": "DELETE_projectKey-customer-groups-key=key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_customers:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-methodName": "withKey"
    },
    "/{projectKey}/customer-groups/{ID}": {
      "post": {
        "description": "Update CustomerGroup by ID",
        "operationId": "POST_projectKey-customer-groups-ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_customers:{projectKey}"
            ]
          }
        ]
      },
      "get": {
        "description": "Get CustomerGroup by ID",
        "operationId": "GET_projectKey-customer-groups-ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_customers:{projectKey}"
            ]
          }
        ]
      },
      "delete": {
        "description": "Delete CustomerGroup by ID",
        "operationId": "DELETE_projectKey-customer-groups-ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_customers:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-methodName": "withId"
    },
    "/{projectKey}/discount-codes": {
      "get": {
        "description": "Query discount-codes",
        "operationId": "GET_projectKey-discount-codes",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_orders:{projectKey}"
            ]
          }
        ]
      },
      "post": {
        "description": "Create DiscountCode",
        "operationId": "POST_projectKey-discount-codes",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_orders:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-updateable": "DiscountCode",
      "x-annotation-deleteable": "DiscountCode",
      "x-annotation-createable": "DiscountCodeDraft"
    },
    "/{projectKey}/discount-codes/{ID}": {
      "post": {
        "description": "Update DiscountCode by ID",
        "operationId": "POST_projectKey-discount-codes-ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_orders:{projectKey}"
            ]
          }
        ]
      },
      "get": {
        "description": "Get DiscountCode by ID",
        "operationId": "GET_projectKey-discount-codes-ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_orders:{projectKey}"
            ]
          }
        ]
      },
      "delete": {
        "description": "Delete DiscountCode by ID",
        "operationId": "DELETE_projectKey-discount-codes-ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_orders:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-methodName": "withId"
    },
    "/{projectKey}/inventory": {
      "get": {
        "description": "Query inventory",
        "operationId": "GET_projectKey-inventory",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_products:{projectKey}"
            ]
          }
        ]
      },
      "post": {
        "description": "Create InventoryEntry",
        "operationId": "POST_projectKey-inventory",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_products:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-updateable": "InventoryEntry",
      "x-annotation-deleteable": "InventoryEntry",
      "x-annotation-createable": "InventoryEntryDraft"
    },
    "/{projectKey}/inventory/{ID}": {
      "post": {
        "description": "Update InventoryEntry by ID",
        "operationId": "POST_projectKey-inventory-ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_products:{projectKey}"
            ]
          }
        ]
      },
      "get": {
        "description": "Get InventoryEntry by ID",
        "operationId": "GET_projectKey-inventory-ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_products:{projectKey}"
            ]
          }
        ]
      },
      "delete": {
        "description": "Delete InventoryEntry by ID",
        "operationId": "DELETE_projectKey-inventory-ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_products:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-methodName": "withId"
    },
    "/{projectKey}/orders": {
      "get": {
        "description": "Query orders",
        "operationId": "GET_projectKey-orders",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_orders:{projectKey}"
            ]
          }
        ]
      },
      "post": {
        "description": "Create Order",
        "operationId": "POST_projectKey-orders",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_orders:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-updateable": "Order",
      "x-annotation-deleteable": "Order",
      "x-annotation-createable": "OrderFromCartDraft"
    },
    "/{projectKey}/orders/order-number={orderNumber}": {
      "post": {
        "description": "Update Order by orderNumber",
        "operationId": "POST_projectKey-orders-order-number=orderNumber",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_orders:{projectKey}"
            ]
          }
        ]
      },
      "get": {
        "description": "Get Order by orderNumber",
        "operationId": "GET_projectKey-orders-order-number=orderNumber",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_orders:{projectKey}"
            ]
          }
        ]
      },
      "delete": {
        "description": "Delete Order by orderNumber",
        "operationId": "DELETE_projectKey-orders-order-number=orderNumber",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_orders:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-methodName": "withOrderNumber"
    },
    "/{projectKey}/orders/{ID}": {
      "post": {
        "description": "Update Order by ID",
        "operationId": "POST_projectKey-orders-ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_orders:{projectKey}"
            ]
          }
        ]
      },
      "get": {
        "description": "Get Order by ID",
        "operationId": "GET_projectKey-orders-ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_orders:{projectKey}"
            ]
          }
        ]
      },
      "delete": {
        "description": "Delete Order by ID",
        "operationId": "DELETE_projectKey-orders-ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_orders:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-methodName": "withId"
    },
    "/{projectKey}/orders/import": {
      "post": {
        "description": "Create an Order by Import",
        "operationId": "POST_projectKey-orders-import",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_orders:{projectKey}"
            ]
          }
        ]
      }
    },
    "/{projectKey}/orders/edits": {
      "get": {
        "description": "Query edits",
        "operationId": "GET_projectKey-orders-edits",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_order_edits:{projectKey}"
            ]
          }
        ]
      },
      "post": {
        "description": "Create OrderEdit",
        "operationId": "POST_projectKey-orders-edits",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_order_edits:{projectKey}"
            ]
          }
        ]
      }
    },
    "/{projectKey}/orders/edits/key={key}": {
      "get": {
        "description": "Get OrderEdit by ID",
        "operationId": "GET_projectKey-orders-edits-key=key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_order_edits:{projectKey}"
            ]
          }
        ]
      },
      "post": {
        "description": "Update OrderEdit by ID",
        "operationId": "POST_projectKey-orders-edits-key=key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_order_edits:{projectKey}"
            ]
          }
        ]
      },
      "delete": {
        "description": "Delete OrderEdit by ID",
        "operationId": "DELETE_projectKey-orders-edits-key=key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_order_edits:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-methodName": "withKey"
    },
    "/{projectKey}/orders/edits/{ID}": {
      "get": {
        "description": "Get OrderEdit by ID",
        "operationId": "GET_projectKey-orders-edits-ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_order_edits:{projectKey}"
            ]
          }
        ]
      },
      "post": {
        "description": "Update OrderEdit by ID",
        "operationId": "POST_projectKey-orders-edits-ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_order_edits:{projectKey}"
            ]
          }
        ]
      },
      "delete": {
        "description": "Delete OrderEdit by ID",
        "operationId": "DELETE_projectKey-orders-edits-ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_order_edits:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-methodName": "withId"
    },
    "/{projectKey}/orders/edits/{ID}/apply": {
      "post": {
        "operationId": "POST_projectKey-orders-edits-ID-apply",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_order_edits:{projectKey}"
            ]
          }
        ]
      }
    },
    "/{projectKey}/products": {
      "get": {
        "description": "Query products",
        "operationId": "GET_projectKey-products",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_products:{projectKey}"
            ]
          }
        ]
      },
      "post": {
        "description": "Create Product",
        "operationId": "POST_projectKey-products",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_products:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-updateable": "Product",
      "x-annotation-deleteable": "Product",
      "x-annotation-createable": "ProductDraft"
    },
    "/{projectKey}/products/key={key}": {
      "post": {
        "description": "Update Product by key",
        "operationId": "POST_projectKey-products-key=key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_products:{projectKey}"
            ]
          }
        ]
      },
      "get": {
        "description": "Get Product by key",
        "operationId": "GET_projectKey-products-key=key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_products:{projectKey}"
            ]
          }
        ]
      },
      "delete": {
        "description": "Delete Product by key",
        "operationId": "DELETE_projectKey-products-key=key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_products:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-methodName": "withKey"
    },
    "/{projectKey}/products/{ID}": {
      "post": {
        "description": "Update Product by ID",
        "operationId": "POST_projectKey-products-ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_products:{projectKey}"
            ]
          }
        ]
      },
      "get": {
        "description": "Get Product by ID",
        "operationId": "GET_projectKey-products-ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_products:{projectKey}"
            ]
          }
        ]
      },
      "delete": {
        "description": "Delete Product by ID",
        "operationId": "DELETE_projectKey-products-ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_products:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-methodName": "withId"
    },
    "/{projectKey}/products/{ID}/images": {
      "post": {
        "description": "Uploads a binary image file to a given product variant. The supported image formats are JPEG, PNG and GIF.\n",
        "operationId": "POST_projectKey-products-ID-images",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_products:{projectKey}"
            ]
          }
        ]
      }
    },
    "/{projectKey}/payments": {
      "get": {
        "description": "Query payments",
        "operationId": "GET_projectKey-payments",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_payments:{projectKey}"
            ]
          }
        ]
      },
      "post": {
        "description": "Create Payment",
        "operationId": "POST_projectKey-payments",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_payments:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-updateable": "Payment",
      "x-annotation-deleteable": "Payment",
      "x-annotation-createable": "PaymentDraft"
    },
    "/{projectKey}/payments/key={key}": {
      "post": {
        "description": "Update Payment by key",
        "operationId": "POST_projectKey-payments-key=key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_payments:{projectKey}"
            ]
          }
        ]
      },
      "get": {
        "description": "Get Payment by key",
        "operationId": "GET_projectKey-payments-key=key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_payments:{projectKey}"
            ]
          }
        ]
      },
      "delete": {
        "description": "Delete Payment by key",
        "operationId": "DELETE_projectKey-payments-key=key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_payments:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-methodName": "withKey"
    },
    "/{projectKey}/payments/{ID}": {
      "post": {
        "description": "Update Payment by ID",
        "operationId": "POST_projectKey-payments-ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_payments:{projectKey}"
            ]
          }
        ]
      },
      "get": {
        "description": "Get Payment by ID",
        "operationId": "GET_projectKey-payments-ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_payments:{projectKey}"
            ]
          }
        ]
      },
      "delete": {
        "description": "Delete Payment by ID",
        "operationId": "DELETE_projectKey-payments-ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_payments:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-methodName": "withId"
    },
    "/{projectKey}/product-discounts": {
      "get": {
        "description": "Query product-discounts",
        "operationId": "GET_projectKey-product-discounts",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_products:{projectKey}"
            ]
          }
        ]
      },
      "post": {
        "description": "Create ProductDiscount",
        "operationId": "POST_projectKey-product-discounts",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_products:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-updateable": "ProductDiscount",
      "x-annotation-deleteable": "ProductDiscount",
      "x-annotation-createable": "ProductDiscountDraft"
    },
    "/{projectKey}/product-discounts/{ID}": {
      "post": {
        "description": "Update ProductDiscount by ID",
        "operationId": "POST_projectKey-product-discounts-ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_products:{projectKey}"
            ]
          }
        ]
      },
      "get": {
        "description": "Get ProductDiscount by ID",
        "operationId": "GET_projectKey-product-discounts-ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_products:{projectKey}"
            ]
          }
        ]
      },
      "delete": {
        "description": "Delete ProductDiscount by ID",
        "operationId": "DELETE_projectKey-product-discounts-ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_products:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-methodName": "withId"
    },
    "/{projectKey}/product-discounts/matching": {
      "post": {
        "operationId": "POST_projectKey-product-discounts-matching",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_products:{projectKey}"
            ]
          }
        ]
      }
    },
    "/{projectKey}/product-types": {
      "get": {
        "description": "Query product-types",
        "operationId": "GET_projectKey-product-types",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_products:{projectKey}"
            ]
          }
        ]
      },
      "post": {
        "description": "Create ProductType",
        "operationId": "POST_projectKey-product-types",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_products:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-updateable": "ProductType",
      "x-annotation-deleteable": "ProductType",
      "x-annotation-createable": "ProductTypeDraft"
    },
    "/{projectKey}/product-types/key={key}": {
      "post": {
        "description": "Update ProductType by key",
        "operationId": "POST_projectKey-product-types-key=key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_products:{projectKey}"
            ]
          }
        ]
      },
      "get": {
        "description": "Get ProductType by key",
        "operationId": "GET_projectKey-product-types-key=key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_products:{projectKey}"
            ]
          }
        ]
      },
      "delete": {
        "description": "Delete ProductType by key",
        "operationId": "DELETE_projectKey-product-types-key=key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_products:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-methodName": "withKey"
    },
    "/{projectKey}/product-types/{ID}": {
      "post": {
        "description": "Update ProductType by ID",
        "operationId": "POST_projectKey-product-types-ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_products:{projectKey}"
            ]
          }
        ]
      },
      "get": {
        "description": "Get ProductType by ID",
        "operationId": "GET_projectKey-product-types-ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_products:{projectKey}"
            ]
          }
        ]
      },
      "delete": {
        "description": "Delete ProductType by ID",
        "operationId": "DELETE_projectKey-product-types-ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_products:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-methodName": "withId"
    },
    "/{projectKey}/shipping-methods": {
      "get": {
        "description": "Query shipping-methods",
        "operationId": "GET_projectKey-shipping-methods",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_orders:{projectKey}"
            ]
          }
        ]
      },
      "post": {
        "description": "Create ShippingMethod",
        "operationId": "POST_projectKey-shipping-methods",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_orders:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-updateable": "ShippingMethod",
      "x-annotation-deleteable": "ShippingMethod",
      "x-annotation-createable": "ShippingMethodDraft"
    },
    "/{projectKey}/shipping-methods/key={key}": {
      "post": {
        "description": "Update ShippingMethod by key",
        "operationId": "POST_projectKey-shipping-methods-key=key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_orders:{projectKey}"
            ]
          }
        ]
      },
      "get": {
        "description": "Get ShippingMethod by key",
        "operationId": "GET_projectKey-shipping-methods-key=key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_orders:{projectKey}"
            ]
          }
        ]
      },
      "delete": {
        "description": "Delete ShippingMethod by key",
        "operationId": "DELETE_projectKey-shipping-methods-key=key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_orders:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-methodName": "withKey"
    },
    "/{projectKey}/shipping-methods/{ID}": {
      "post": {
        "description": "Update ShippingMethod by ID",
        "operationId": "POST_projectKey-shipping-methods-ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_orders:{projectKey}"
            ]
          }
        ]
      },
      "get": {
        "description": "Get ShippingMethod by ID",
        "operationId": "GET_projectKey-shipping-methods-ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_orders:{projectKey}"
            ]
          }
        ]
      },
      "delete": {
        "description": "Delete ShippingMethod by ID",
        "operationId": "DELETE_projectKey-shipping-methods-ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_orders:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-methodName": "withId"
    },
    "/{projectKey}/reviews": {
      "get": {
        "description": "Query reviews",
        "operationId": "GET_projectKey-reviews",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_products:{projectKey}"
            ]
          }
        ]
      },
      "post": {
        "description": "Create Review",
        "operationId": "POST_projectKey-reviews",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_products:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-updateable": "Review",
      "x-annotation-deleteable": "Review",
      "x-annotation-createable": "ReviewDraft"
    },
    "/{projectKey}/reviews/key={key}": {
      "post": {
        "description": "Update Review by key",
        "operationId": "POST_projectKey-reviews-key=key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_products:{projectKey}"
            ]
          }
        ]
      },
      "get": {
        "description": "Get Review by key",
        "operationId": "GET_projectKey-reviews-key=key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_products:{projectKey}"
            ]
          }
        ]
      },
      "delete": {
        "description": "Delete Review by key",
        "operationId": "DELETE_projectKey-reviews-key=key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_products:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-methodName": "withKey"
    },
    "/{projectKey}/reviews/{ID}": {
      "post": {
        "description": "Update Review by ID",
        "operationId": "POST_projectKey-reviews-ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_products:{projectKey}"
            ]
          }
        ]
      },
      "get": {
        "description": "Get Review by ID",
        "operationId": "GET_projectKey-reviews-ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_products:{projectKey}"
            ]
          }
        ]
      },
      "delete": {
        "description": "Delete Review by ID",
        "operationId": "DELETE_projectKey-reviews-ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_products:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-methodName": "withId"
    },
    "/{projectKey}/shopping-lists": {
      "get": {
        "description": "Query shopping-lists",
        "operationId": "GET_projectKey-shopping-lists",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_shopping_lists:{projectKey}"
            ]
          }
        ]
      },
      "post": {
        "description": "Create ShoppingList",
        "operationId": "POST_projectKey-shopping-lists",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_shopping_lists:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-updateable": "ShoppingList",
      "x-annotation-deleteable": "ShoppingList",
      "x-annotation-createable": "ShoppingListDraft"
    },
    "/{projectKey}/shopping-lists/key={key}": {
      "post": {
        "description": "Update ShoppingList by key",
        "operationId": "POST_projectKey-shopping-lists-key=key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_shopping_lists:{projectKey}"
            ]
          }
        ]
      },
      "get": {
        "description": "Get ShoppingList by key",
        "operationId": "GET_projectKey-shopping-lists-key=key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_shopping_lists:{projectKey}"
            ]
          }
        ]
      },
      "delete": {
        "description": "Delete ShoppingList by key",
        "operationId": "DELETE_projectKey-shopping-lists-key=key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_shopping_lists:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-methodName": "withKey"
    },
    "/{projectKey}/shopping-lists/{ID}": {
      "post": {
        "description": "Update ShoppingList by ID",
        "operationId": "POST_projectKey-shopping-lists-ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_shopping_lists:{projectKey}"
            ]
          }
        ]
      },
      "get": {
        "description": "Get ShoppingList by ID",
        "operationId": "GET_projectKey-shopping-lists-ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_shopping_lists:{projectKey}"
            ]
          }
        ]
      },
      "delete": {
        "description": "Delete ShoppingList by ID",
        "operationId": "DELETE_projectKey-shopping-lists-ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_shopping_lists:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-methodName": "withId"
    },
    "/{projectKey}/states": {
      "get": {
        "description": "Query states",
        "operationId": "GET_projectKey-states",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_orders:{projectKey}"
            ]
          }
        ]
      },
      "post": {
        "description": "Create State",
        "operationId": "POST_projectKey-states",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_orders:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-updateable": "State",
      "x-annotation-deleteable": "State",
      "x-annotation-createable": "StateDraft"
    },
    "/{projectKey}/states/{ID}": {
      "post": {
        "description": "Update State by ID",
        "operationId": "POST_projectKey-states-ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_orders:{projectKey}"
            ]
          }
        ]
      },
      "get": {
        "description": "Get State by ID",
        "operationId": "GET_projectKey-states-ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_orders:{projectKey}"
            ]
          }
        ]
      },
      "delete": {
        "description": "Delete State by ID",
        "operationId": "DELETE_projectKey-states-ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_orders:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-methodName": "withId"
    },
    "/{projectKey}/subscriptions": {
      "get": {
        "description": "Query subscriptions",
        "operationId": "GET_projectKey-subscriptions",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_subscriptions:{projectKey}"
            ]
          }
        ]
      },
      "post": {
        "description": "Create Subscription",
        "operationId": "POST_projectKey-subscriptions",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_subscriptions:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-updateable": "Subscription",
      "x-annotation-deleteable": "Subscription",
      "x-annotation-createable": "SubscriptionDraft"
    },
    "/{projectKey}/subscriptions/key={key}": {
      "post": {
        "description": "Update Subscription by key",
        "operationId": "POST_projectKey-subscriptions-key=key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_subscriptions:{projectKey}"
            ]
          }
        ]
      },
      "get": {
        "description": "Get Subscription by key",
        "operationId": "GET_projectKey-subscriptions-key=key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_subscriptions:{projectKey}"
            ]
          }
        ]
      },
      "delete": {
        "description": "Delete Subscription by key",
        "operationId": "DELETE_projectKey-subscriptions-key=key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_subscriptions:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-methodName": "withKey"
    },
    "/{projectKey}/subscriptions/{ID}": {
      "post": {
        "description": "Update Subscription by ID",
        "operationId": "POST_projectKey-subscriptions-ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_subscriptions:{projectKey}"
            ]
          }
        ]
      },
      "get": {
        "description": "Get Subscription by ID",
        "operationId": "GET_projectKey-subscriptions-ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_subscriptions:{projectKey}"
            ]
          }
        ]
      },
      "delete": {
        "description": "Delete Subscription by ID",
        "operationId": "DELETE_projectKey-subscriptions-ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_subscriptions:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-methodName": "withId"
    },
    "/{projectKey}/tax-categories": {
      "get": {
        "description": "Query tax-categories",
        "operationId": "GET_projectKey-tax-categories",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_products:{projectKey}"
            ]
          }
        ]
      },
      "post": {
        "description": "Create TaxCategory",
        "operationId": "POST_projectKey-tax-categories",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_products:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-updateable": "TaxCategory",
      "x-annotation-deleteable": "TaxCategory",
      "x-annotation-createable": "TaxCategoryDraft"
    },
    "/{projectKey}/tax-categories/{ID}": {
      "post": {
        "description": "Update TaxCategory by ID",
        "operationId": "POST_projectKey-tax-categories-ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_products:{projectKey}"
            ]
          }
        ]
      },
      "get": {
        "description": "Get TaxCategory by ID",
        "operationId": "GET_projectKey-tax-categories-ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_products:{projectKey}"
            ]
          }
        ]
      },
      "delete": {
        "description": "Delete TaxCategory by ID",
        "operationId": "DELETE_projectKey-tax-categories-ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_products:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-methodName": "withId"
    },
    "/{projectKey}/types": {
      "get": {
        "description": "Query types",
        "operationId": "GET_projectKey-types",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_types:{projectKey}"
            ]
          }
        ]
      },
      "post": {
        "description": "Create Type",
        "operationId": "POST_projectKey-types",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_types:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-updateable": "Type",
      "x-annotation-deleteable": "Type",
      "x-annotation-createable": "TypeDraft"
    },
    "/{projectKey}/types/key={key}": {
      "post": {
        "description": "Update Type by key",
        "operationId": "POST_projectKey-types-key=key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_types:{projectKey}"
            ]
          }
        ]
      },
      "get": {
        "description": "Get Type by key",
        "operationId": "GET_projectKey-types-key=key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_types:{projectKey}"
            ]
          }
        ]
      },
      "delete": {
        "description": "Delete Type by key",
        "operationId": "DELETE_projectKey-types-key=key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_types:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-methodName": "withKey"
    },
    "/{projectKey}/types/{ID}": {
      "post": {
        "description": "Update Type by ID",
        "operationId": "POST_projectKey-types-ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_types:{projectKey}"
            ]
          }
        ]
      },
      "get": {
        "description": "Get Type by ID",
        "operationId": "GET_projectKey-types-ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_types:{projectKey}"
            ]
          }
        ]
      },
      "delete": {
        "description": "Delete Type by ID",
        "operationId": "DELETE_projectKey-types-ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_types:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-methodName": "withId"
    },
    "/{projectKey}/zones": {
      "get": {
        "description": "Query zones",
        "operationId": "GET_projectKey-zones",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_orders:{projectKey}"
            ]
          }
        ]
      },
      "post": {
        "description": "Create Zone",
        "operationId": "POST_projectKey-zones",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_orders:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-updateable": "Zone",
      "x-annotation-deleteable": "Zone",
      "x-annotation-createable": "ZoneDraft"
    },
    "/{projectKey}/zones/{ID}": {
      "post": {
        "description": "Update Zone by ID",
        "operationId": "POST_projectKey-zones-ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_orders:{projectKey}"
            ]
          }
        ]
      },
      "get": {
        "description": "Get Zone by ID",
        "operationId": "GET_projectKey-zones-ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_orders:{projectKey}"
            ]
          }
        ]
      },
      "delete": {
        "description": "Delete Zone by ID",
        "operationId": "DELETE_projectKey-zones-ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_orders:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-methodName": "withId"
    },
    "/{projectKey}/extensions": {
      "get": {
        "description": "Query extensions",
        "operationId": "GET_projectKey-extensions",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_extensions:{projectKey}"
            ]
          }
        ]
      },
      "post": {
        "description": "Create Extension",
        "operationId": "POST_projectKey-extensions",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_extensions:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-updateable": "Extension",
      "x-annotation-deleteable": "Extension",
      "x-annotation-createable": "ExtensionDraft"
    },
    "/{projectKey}/extensions/key={key}": {
      "post": {
        "description": "Update Extension by key",
        "operationId": "POST_projectKey-extensions-key=key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_extensions:{projectKey}"
            ]
          }
        ]
      },
      "get": {
        "description": "Get Extension by key",
        "operationId": "GET_projectKey-extensions-key=key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_extensions:{projectKey}"
            ]
          }
        ]
      },
      "delete": {
        "description": "Delete Extension by key",
        "operationId": "DELETE_projectKey-extensions-key=key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_extensions:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-methodName": "withKey"
    },
    "/{projectKey}/extensions/{ID}": {
      "post": {
        "description": "Update Extension by ID",
        "operationId": "POST_projectKey-extensions-ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_extensions:{projectKey}"
            ]
          }
        ]
      },
      "get": {
        "description": "Get Extension by ID",
        "operationId": "GET_projectKey-extensions-ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_extensions:{projectKey}"
            ]
          }
        ]
      },
      "delete": {
        "description": "Delete Extension by ID",
        "operationId": "DELETE_projectKey-extensions-ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_extensions:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-methodName": "withId"
    },
    "/{projectKey}/custom-objects": {
      "get": {
        "description": "Query custom-objects",
        "operationId": "GET_projectKey-custom-objects",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_products:{projectKey}",
              "view_orders:{projectKey}",
              "view_customers:{projectKey}"
            ]
          }
        ]
      },
      "post": {
        "description": "Create CustomObject",
        "operationId": "POST_projectKey-custom-objects",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_products:{projectKey}",
              "manage_orders:{projectKey}",
              "manage_customers:{projectKey}"
            ]
          }
        ]
      }
    },
    "/{projectKey}/custom-objects/{container}/{key}": {
      "get": {
        "description": "Get CustomObject by key",
        "operationId": "GET_projectKey-custom-objects-container-key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_products:{projectKey}",
              "view_orders:{projectKey}",
              "view_customers:{projectKey}"
            ]
          }
        ]
      },
      "delete": {
        "description": "Delete CustomObject by key",
        "operationId": "DELETE_projectKey-custom-objects-container-key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_products:{projectKey}",
              "manage_orders:{projectKey}",
              "manage_customers:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-methodName": "withContainerAndKey"
    },
    "/{projectKey}/custom-objects/{ID}": {
      "get": {
        "description": "Get CustomObject by container",
        "operationId": "GET_projectKey-custom-objects-ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_products:{projectKey}",
              "view_orders:{projectKey}",
              "view_customers:{projectKey}"
            ]
          }
        ]
      },
      "delete": {
        "description": "Delete CustomObject by container",
        "operationId": "DELETE_projectKey-custom-objects-ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_products:{projectKey}",
              "manage_orders:{projectKey}",
              "manage_customers:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-methodName": "withId"
    },
    "/{projectKey}/graphql": {
      "post": {
        "description": "Execute a GraphQL query",
        "operationId": "POST_projectKey-graphql",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_products:{projectKey}"
            ]
          }
        ]
      }
    },
    "/{projectKey}/login": {
      "post": {
        "description": "Authenticate Customer (Sign In)",
        "operationId": "POST_projectKey-login",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "manage_customers:{projectKey}"
            ]
          }
        ]
      }
    },
    "/{projectKey}/messages": {
      "get": {
        "description": "Query messages",
        "operationId": "GET_projectKey-messages",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_orders:{projectKey}"
            ]
          }
        ]
      }
    },
    "/{projectKey}/messages/{ID}": {
      "get": {
        "description": "Get Message by ID",
        "operationId": "GET_projectKey-messages-ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_orders:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-methodName": "withId"
    },
    "/{projectKey}/product-projections": {
      "get": {
        "description": "Query product-projections",
        "operationId": "GET_projectKey-product-projections",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_products:{projectKey}"
            ]
          }
        ]
      }
    },
    "/{projectKey}/product-projections/search": {
      "post": {
        "description": "Search Product Projection",
        "operationId": "POST_projectKey-product-projections-search",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_products:{projectKey}"
            ]
          }
        ]
      },
      "get": {
        "description": "Search Product Projection",
        "operationId": "GET_projectKey-product-projections-search",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_products:{projectKey}"
            ]
          }
        ]
      }
    },
    "/{projectKey}/product-projections/suggest": {
      "get": {
        "operationId": "GET_projectKey-product-projections-suggest",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_products:{projectKey}"
            ]
          }
        ]
      }
    },
    "/{projectKey}/product-projections/key={key}": {
      "get": {
        "description": "Get ProductProjection by key",
        "operationId": "GET_projectKey-product-projections-key=key",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_products:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-methodName": "withKey"
    },
    "/{projectKey}/product-projections/{ID}": {
      "get": {
        "description": "Get ProductProjection by ID",
        "operationId": "GET_projectKey-product-projections-ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_project:{projectKey}",
              "view_products:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-methodName": "withId"
    },
    "/{projectKey}/me": {
      "get": {
        "operationId": "GET_projectKey-me",
        "security": [
          {
            "oauth_2_0": [
              "manage_my_profile:{projectKey}"
            ]
          }
        ]
      },
      "post": {
        "description": "Create a customer",
        "operationId": "POST_projectKey-me",
        "security": [
          {
            "oauth_2_0": [
              "manage_my_profile:{projectKey}"
            ]
          }
        ]
      },
      "delete": {
        "description": "Delete a Customer",
        "operationId": "DELETE_projectKey-me",
        "security": [
          {
            "oauth_2_0": [
              "manage_my_profile:{projectKey}"
            ]
          }
        ]
      }
    },
    "/{projectKey}/me/email/confirm": {
      "post": {
        "operationId": "POST_projectKey-me-email-confirm",
        "security": [
          {
            "oauth_2_0": [
              "manage_my_profile:{projectKey}"
            ]
          }
        ]
      }
    },
    "/{projectKey}/me/password": {
      "post": {
        "operationId": "POST_projectKey-me-password",
        "security": [
          {
            "oauth_2_0": [
              "manage_my_profile:{projectKey}"
            ]
          }
        ]
      }
    },
    "/{projectKey}/me/password/reset": {
      "post": {
        "operationId": "POST_projectKey-me-password-reset",
        "security": [
          {
            "oauth_2_0": [
              "manage_my_profile:{projectKey}"
            ]
          }
        ]
      }
    },
    "/{projectKey}/me/signup": {
      "post": {
        "operationId": "POST_projectKey-me-signup",
        "security": [
          {
            "oauth_2_0": [
              "manage_my_profile:{projectKey}"
            ]
          }
        ]
      }
    },
    "/{projectKey}/me/login": {
      "post": {
        "operationId": "POST_projectKey-me-login",
        "security": [
          {
            "oauth_2_0": [
              "manage_my_profile:{projectKey}"
            ]
          }
        ]
      }
    },
    "/{projectKey}/me/active-cart": {
      "get": {
        "operationId": "GET_projectKey-me-active-cart",
        "security": [
          {
            "oauth_2_0": [
              "manage_my_orders:{projectKey}"
            ]
          }
        ]
      }
    },
    "/{projectKey}/me/carts": {
      "get": {
        "description": "Query carts",
        "operationId": "GET_projectKey-me-carts",
        "security": [
          {
            "oauth_2_0": [
              "manage_my_orders:{projectKey}"
            ]
          }
        ]
      },
      "post": {
        "description": "Create Cart",
        "operationId": "POST_projectKey-me-carts",
        "security": [
          {
            "oauth_2_0": [
              "manage_my_orders:{projectKey}"
            ]
          }
        ]
      }
    },
    "/{projectKey}/me/carts/{ID}": {
      "get": {
        "description": "Get Cart by ID",
        "operationId": "GET_projectKey-me-carts-ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_my_orders:{projectKey}"
            ]
          }
        ]
      },
      "post": {
        "description": "Update Cart by ID",
        "operationId": "POST_projectKey-me-carts-ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_my_orders:{projectKey}"
            ]
          }
        ]
      },
      "delete": {
        "description": "Delete Cart by ID",
        "operationId": "DELETE_projectKey-me-carts-ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_my_orders:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-methodName": "withId"
    },
    "/{projectKey}/me/orders": {
      "get": {
        "description": "Query orders",
        "operationId": "GET_projectKey-me-orders",
        "security": [
          {
            "oauth_2_0": [
              "manage_my_orders:{projectKey}"
            ]
          }
        ]
      },
      "post": {
        "description": "Create Order",
        "operationId": "POST_projectKey-me-orders",
        "security": [
          {
            "oauth_2_0": [
              "manage_my_orders:{projectKey}"
            ]
          }
        ]
      }
    },
    "/{projectKey}/me/orders/{ID}": {
      "get": {
        "description": "Get Order by ID",
        "operationId": "GET_projectKey-me-orders-ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_my_orders:{projectKey}"
            ]
          }
        ]
      },
      "post": {
        "description": "Update Order by ID",
        "operationId": "POST_projectKey-me-orders-ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_my_orders:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-methodName": "withId"
    },
    "/{projectKey}/api-clients": {
      "get": {
        "description": "Query api-clients",
        "operationId": "GET_projectKey-api-clients",
        "security": [
          {
            "oauth_2_0": [
              "manage_api_clients:{projectKey}",
              "view_api_clients:{projectKey}"
            ]
          }
        ]
      },
      "post": {
        "description": "Create ApiClient",
        "operationId": "POST_projectKey-api-clients",
        "security": [
          {
            "oauth_2_0": [
              "manage_api_clients:{projectKey}"
            ]
          }
        ]
      }
    },
    "/{projectKey}/api-clients/{ID}": {
      "get": {
        "description": "Get ApiClient by ID",
        "operationId": "GET_projectKey-api-clients-ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_api_clients:{projectKey}",
              "view_api_clients:{projectKey}"
            ]
          }
        ]
      },
      "delete": {
        "description": "Delete ApiClient by ID",
        "operationId": "DELETE_projectKey-api-clients-ID",
        "security": [
          {
            "oauth_2_0": [
              "manage_api_clients:{projectKey}"
            ]
          }
        ]
      },
      "x-annotation-methodName": "withId"
    }
  }
}