type: base
displayName: customer group
description: customer-groups are used to evaluate products and channels.
get:
  description: Query customer-groups
  is:
    - query:
        whereExample: name = "VIP"
    - sortable:
        sortExample: createdAt asc
    - paging
  securedBy: [oauth_2_0: {scopes: ["manage_project:{projectKey}", "view_customers:{projectKey}"]}]
  responses:
    200:
      body:
        application/json:
          example: !include examples/customer-groups.example.json
          type: CustomerGroupPagedQueryResponse
post:
  description: Create a customer-group
  securedBy: [oauth_2_0: {scopes: ["manage_project:{projectKey}", "manage_customers:{projectKey}"]}]
  body:
    application/json:
      example: !include examples/customer-group-create.example.json
      type: CustomerGroupDraft
  responses:
    201:
      body:
        application/json:
          example: !include examples/customer-group.example.json
          type: CustomerGroup
/{ID}:
  type: base
  displayName: customer-group
  get:
    description: Get customer-group by ID
    securedBy: [oauth_2_0: {scopes: ["manage_project:{projectKey}", "view_customers:{projectKey}"]}]
    responses:
      200:
        body:
          application/json:
            example: !include examples/customer-group.example.json
            type: CustomerGroup
  post:
    description: Update a customer-group
    is:
      - conflicting
    securedBy: [oauth_2_0: {scopes: ["manage_project:{projectKey}", "manage_customers:{projectKey}"]}]
    body:
      application/json:
        example: !include examples/customer-group-update.example.json
        type: CustomerGroupUpdate
    responses:
      200:
        body:
          application/json:
            example: !include examples/customer-group.example.json
            type: CustomerGroup
  delete:
    description: Delete a customer-group
    is:
      - versioned
      - conflicting
    securedBy: [oauth_2_0: {scopes: ["manage_project:{projectKey}", "manage_customers:{projectKey}"]}]
    responses:
      200:
        body:
          application/json:
            example: !include examples/customer-group.example.json
            type: CustomerGroup
