type: base
displayName: Tax categories
description: Tax Categories define how products are to be taxed in different countries.
get:
  description: Query tax categories
  is:
    - query:
        whereExample: name = "MwSt"
    - sortable:
        sortExample: name asc
    - paging
  securedBy: [oauth_2_0: {scopes: ["manage_project:{projectKey}", "view_products:{projectKey}"]}]
  responses:
    200:
      body:
        application/json:
          example: !include examples/tax-categories.example.json
          type: api.TaxCategoryPagedQueryResponse
post:
  description: Create a tax category
  securedBy: [oauth_2_0: {scopes: ["manage_project:{projectKey}", "manage_products:{projectKey}"]}]
  body:
    application/json:
      example: !include examples/tax-category-create.example.json
      type: api.TaxCategoryDraft
  responses:
    201:
      body:
        application/json:
          example: !include examples/tax-category.example.json
          type: api.TaxCategory
/{ID}:
  type: base
  displayName: Tax Category
  get:
    description: Get Tax Category by ID
    securedBy: [oauth_2_0: {scopes: ["manage_project:{projectKey}", "view_products:{projectKey}"]}]
    responses:
      200:
        body:
          application/json:
            example: !include examples/tax-category.example.json
            type: api.TaxCategory
  post:
    description: Update a Tax Category
    is:
      - conflicting
    securedBy: [oauth_2_0: {scopes: ["manage_project:{projectKey}", "manage_products:{projectKey}"]}]
    body:
      application/json:
        example: !include examples/tax-category-update.example.json
        type: api.TaxCategoryUpdate
    responses:
      200:
        body:
          application/json:
            example: !include examples/tax-category.example.json
            type: api.TaxCategory
  delete:
    description: Delete a Tax Category
    is:
      - versioned
      - conflicting
    securedBy: [oauth_2_0: {scopes: ["manage_project:{projectKey}", "manage_products:{projectKey}"]}]
    responses:
      200:
        body:
          application/json:
            example: !include examples/tax-category.example.json
            type: api.TaxCategory
