#%RAML 1.0 Extension
usage: Adds ramble fixes for our API specification
extends: api.raml
/{projectKey}:
    /categories:
        /{ID}:
            post:
                body:
                    application/json:
                        type: CategoryUpdate
    /customer-groups:
        /{ID}:
            post:
                body:
                    application/json:
                        type: CustomerGroupUpdate
    /inventory:
        /{ID}:
            post:
                body:
                    application/json:
                        type: InventoryUpdate
    /product-discounts:
        /{ID}:
            post:
                body:
                    application/json:
                        type: ProductDiscountUpdate
    /product-types:
        /key={key}:
            post:
                body:
                    application/json:
                        type: ProductTypeUpdate
        /{ID}:
            post:
                body:
                    application/json:
                        type: ProductTypeUpdate
    /states:
        /{ID}:
            post:
                body:
                    application/json:
                        type: StateUpdate
    /tax-categories:
        /{ID}:
            post:
                body:
                    application/json:
                        type: TaxCategoryUpdate
    /zones:
        /{ID}:
            post:
                body:
                    application/json:
                        type: ZoneUpdate
