#%RAML 1.0 DataType
(package): Agent
type: ErrorObject
displayName: AgentStoreDistributionChannelsUnsupportedError
discriminatorValue: StoreDistributionChannelsUnsupported
description: |
  Returned by a [/responses](/api/agents/intake-agent#create-a-cart-or-quote-request) request when the resolved [Store](ctp:api:type:Store) has more than one entry in the `distributionChannels` array, which is not supported. To resolve this error, choose a Store with zero or one distribution channel.
properties:
  code:
    type: string
  message:
    type: string
    description: |
      Plain text description of the error.
