#%RAML 1.0 DataType
(package): Agent
type: ErrorObject
displayName: AgentNoLineItemsExtractedError
discriminatorValue: NoLineItemsExtracted
description: |
  Returned by a [/responses](/api/agents/intake-agent#create-a-cart-or-quote-request) request when no Line Items could be extracted from the provided `prompt` or files.
example: !include ../../examples/agent/AgentNoLineItemsExtractedError.json
properties:
  code:
    type: string
  message:
    type: string
    description: |
      Plain text description of the error.
