#%RAML 1.0 DataType
(package): Agent
type: ErrorObject
displayName: AgentFeatureDisabledError
discriminatorValue: FeatureDisabled
description: |
  Returned by a [/responses](/api/agents/intake-agent#create-a-cart-or-quote-request) request when the Intake Agent is not enabled for the Project.
example: !include ../../examples/agent/AgentFeatureDisabledError.json
properties:
  code:
    type: string
  message:
    type: string
    description: |
      Plain text description of the error.
