#%RAML 1.0 DataType
(package): Agent
type: ErrorObject
displayName: AgentProductSearchNotEnabledError
discriminatorValue: ProductSearchNotEnabled
description: |
  Returned by a [/responses](/api/agents/intake-agent#create-a-cart-or-quote-request) request when Product Search is not enabled for the project.
properties:
  code:
    type: string
  message:
    type: string
    description: |
      Plain text description of the error.
