#%RAML 1.0 DataType
(package): ProductDiscount
(docs-uri): https://docs.commercetools.com/api/projects/productDiscounts#change-value
type: ProductDiscountUpdateAction
displayName: ProductDiscountChangeValueAction
discriminatorValue: changeValue
example: !include ../../../examples/ProductDiscount/ProductDiscountChangeValueAction.json
properties:
  value:
    type: ProductDiscountValueDraft
    description: |
      New value to set. Must not be empty.
