#%RAML 1.0 DataType
(package): ProductDiscount
(docs-uri): https://docs.commercetools.com/http-api-projects-productDiscounts.html#change-value
type: ProductDiscountUpdateAction
displayName: ProductDiscountChangeValueAction
discriminatorValue: changeValue
(postman-example): !include ../../../examples/ProductDiscount/ProductDiscountChangeValueAction.json
properties:
  value:
    type: ProductDiscountValueDraft
    description: ''
