#%RAML 1.0 DataType
(package): ProductDiscount
(docs-uri): https://docs.commercetools.com/http-api-projects-productDiscounts.html#set-valid-until
type: ProductDiscountUpdateAction
displayName: ProductDiscountSetValidUntilAction
discriminatorValue: setValidUntil
(postman-example): !include ../../../examples/ProductDiscount/ProductDiscountSetValidUntilAction.json
properties:
  validUntil?:
    type: datetime
    description: |-
      The time from which the discount should be ineffective.
      Please take Eventual Consistency into account for calculated undiscounted values.
