#%RAML 1.0 DataType
(package): ProductDiscount
(docs-uri): https://docs.commercetools.com/http-api-projects-productDiscounts.html#change-name
type: ProductDiscountUpdateAction
displayName: ProductDiscountChangeNameAction
discriminatorValue: changeName
(postman-example): !include ../../../examples/ProductDiscount/ProductDiscountChangeNameAction.json
properties:
  name:
    type: LocalizedString
    description: ''
