#%RAML 1.0 DataType
(package): Event
type: Event
displayName: ImportValidationFailedEvent
example: !include ../../examples/Event/ImportValidationFailedEvent.json
description: Generated when an [Import Operation](ctp:import:type:ImportOperation) has the `validationFailed` [ProcessingState](ctp:import:type:ProcessingState).
discriminatorValue: ImportValidationFailed
properties:
  resourceType:
    type: EventSubscriptionResourceTypeId
    enum:
      - import-api
  data:
    type: ImportValidationFailedEventData
    description: |
      An object containing details of the Import Operation with the `validationFailed` state.
