#%RAML 1.0 DataType
(package): Event
displayName: ImportWaitForMasterVariantEventData
example: !include ../../examples/Event/ImportWaitForMasterVariantEventData.json
description: The `data` of the [Import Wait For Master Variant Event](ctp:api:type:ImportWaitForMasterVariantEvent).
properties:
  id:
    type: string
    description: |
      The `id` of the Import Operation with the `waitForMasterVariant` state.
  version:
    type: integer
    description: |
      The `version` of the Import Operation with the `waitForMasterVariant` state.
  importContainerKey:
    type: string
    description: |
      The `key` of the Import Container.
