#%RAML 1.0 DataType
(package): Event
displayName: ImportUnresolvedEventData
example: !include ../../examples/Event/ImportUnresolvedEventData.json
description: The `data` of the [Import Unresolved Event](ctp:api:type:ImportUnresolvedEvent).
properties:
  id:
    type: string
    description: |
      The `id` of the Import Operation with the `unresolved` state.
  version:
    type: integer
    description: |
      The `version` of the Import Operation with the `unresolved` state.
  importContainerKey:
    type: string
    description: |
      The `key` of the Import Container.
