#%RAML 1.0 DataType
(package): ShippingMethod
(docs-uri): https://docs.commercetools.com/http-api-projects-shippingMethods.html#shippingratedraft
displayName: ShippingRateDraft
type: object
properties:
  price:
    type: Money
    description: ''
  freeAbove?:
    type: Money
    description: |-
      The shipping is free if the order total (the sum of line item prices) exceeds the freeAbove value.
      Note: `freeAbove` applies before any Cart or Product discounts, and can cause discounts to apply in invalid scenarios.
      Use a Cart Discount to set the shipping price to 0 to avoid providing free shipping in invalid discount scenarios.
  tiers?:
    type: ShippingRatePriceTier[]
    description: A list of shipping rate price tiers.
