#%RAML 1.0 DataType
(package): ShippingMethod


type: ShippingMethodUpdateAction
displayName: ShippingMethodSetDescriptionAction
discriminatorValue: setDescription
properties:
    description?:
        type: string
