#%RAML 1.0 DataType
(package): ShippingMethod
(docs-uri): https://docs.commercetools.com/http-api-projects-shippingMethods.html#shippingmethoddraft


type: object
displayName: ShippingMethodDraft
properties:
    key?:
        type: string
    name:
        type: string
    description?:
        type: string
    taxCategory:
        type: TaxCategoryResourceIdentifier
    zoneRates: ZoneRateDraft[]
    isDefault: boolean
    predicate?:
        type: string
