#%RAML 1.0 DataType
(package): ShippingMethod
(docs-uri): https://docs.commercetools.com/http-api-projects-shippingMethods.html#zonerate
displayName: ZoneRate
type: object
properties:
  zone:
    type: ZoneReference
    description: ''
  shippingRates:
    description: The array does not contain two shipping rates with the same currency.
    type: ShippingRate[]
