openapi: "3.0.0"
info:
  title: Commercetools
  version: v1

servers:
  - url: https://api.europe-west1.gcp.commercetools.com

paths:
  /{projectKey}:
    description: |-
      The Project endpoint is used to retrieve certain information from a project.
    get:
      tags:
        - "projectKey" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
      operationId: ByProjectKeyGet
      description: |-
        The Endpoint is responding a limited set of information about settings and configuration of the project.
    post:
      tags:
        - "projectKey" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
      operationId: ByProjectKeyPost
      description: |-
        Update project
  /{projectKey}/api-clients:
    description: |-
      Manage your API Clients via an API. Useful for Infrastructure-as-Code tooling, and regularly rotating API secrets.
    get:
      tags:
        - "projectKey"
        - "api-clients" 
      security:
        - oauth_2_0:
            - "manage_api_clients:{projectKey}"
            - "view_api_clients:{projectKey}"
      operationId: ByProjectKeyApiClientsGet
      description: |-
        Query api-clients
    post:
      tags:
        - "projectKey"
        - "api-clients" 
      security:
        - oauth_2_0:
            - "manage_api_clients:{projectKey}"
      operationId: ByProjectKeyApiClientsPost
      description: |-
        Create ApiClient
  /{projectKey}/api-clients/{ID}:
    get:
      tags:
        - "projectKey"
        - "api-clients"
        - "ID" 
      security:
        - oauth_2_0:
            - "manage_api_clients:{projectKey}"
            - "view_api_clients:{projectKey}"
      operationId: ByProjectKeyApiClientsByIDGet
      description: |-
        Get ApiClient by ID
    delete:
      tags:
        - "projectKey"
        - "api-clients"
        - "ID" 
      security:
        - oauth_2_0:
            - "manage_api_clients:{projectKey}"
      operationId: ByProjectKeyApiClientsByIDDelete
      description: |-
        Delete ApiClient by ID
  /{projectKey}/cart-discounts:
    description: |-
      Cart discounts are used to change the prices of different elements within a cart.
    get:
      tags:
        - "projectKey"
        - "cart-discounts" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "view_orders:{projectKey}"
            - "view_cart_discounts:{projectKey}"
      operationId: ByProjectKeyCartDiscountsGet
      description: |-
        Query cart-discounts
    post:
      tags:
        - "projectKey"
        - "cart-discounts" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_orders:{projectKey}"
            - "manage_cart_discounts:{projectKey}"
      operationId: ByProjectKeyCartDiscountsPost
      description: |-
        Create CartDiscount
  /{projectKey}/cart-discounts/key={key}:
    get:
      tags:
        - "projectKey"
        - "cart-discounts"
        - "key=key" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "view_orders:{projectKey}"
            - "view_cart_discounts:{projectKey}"
      operationId: ByProjectKeyCartDiscountsKeyByKeyGet
      description: |-
        Get CartDiscount by key
    post:
      tags:
        - "projectKey"
        - "cart-discounts"
        - "key=key" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_orders:{projectKey}"
            - "manage_cart_discounts:{projectKey}"
      operationId: ByProjectKeyCartDiscountsKeyByKeyPost
      description: |-
        Update CartDiscount by key
    delete:
      tags:
        - "projectKey"
        - "cart-discounts"
        - "key=key" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_orders:{projectKey}"
            - "manage_cart_discounts:{projectKey}"
      operationId: ByProjectKeyCartDiscountsKeyByKeyDelete
      description: |-
        Delete CartDiscount by key
  /{projectKey}/cart-discounts/{ID}:
    get:
      tags:
        - "projectKey"
        - "cart-discounts"
        - "ID" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "view_orders:{projectKey}"
            - "view_cart_discounts:{projectKey}"
      operationId: ByProjectKeyCartDiscountsByIDGet
      description: |-
        Get CartDiscount by ID
    post:
      tags:
        - "projectKey"
        - "cart-discounts"
        - "ID" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_orders:{projectKey}"
            - "manage_cart_discounts:{projectKey}"
      operationId: ByProjectKeyCartDiscountsByIDPost
      description: |-
        Update CartDiscount by ID
    delete:
      tags:
        - "projectKey"
        - "cart-discounts"
        - "ID" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_orders:{projectKey}"
            - "manage_cart_discounts:{projectKey}"
      operationId: ByProjectKeyCartDiscountsByIDDelete
      description: |-
        Delete CartDiscount by ID
  /{projectKey}/carts:
    description: |-
      A shopping cart holds product variants and can be ordered.
    get:
      tags:
        - "projectKey"
        - "carts" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "view_orders:{projectKey}"
      operationId: ByProjectKeyCartsGet
      description: |-
        Query carts
    post:
      tags:
        - "projectKey"
        - "carts" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_orders:{projectKey}"
      operationId: ByProjectKeyCartsPost
      description: |-
        Creating a cart can fail with an InvalidOperation if the referenced shipping method in the
        CartDraft has a predicate which does not match the cart.
  /{projectKey}/carts/customer-id={customerId}:
    get:
      tags:
        - "projectKey"
        - "carts"
        - "customer-id=customerId" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "view_orders:{projectKey}"
      operationId: ByProjectKeyCartsCustomerIdByCustomerIdGet
      description: |-
        Retrieves the active cart of the customer that has been modified most recently.
        It does not consider carts with CartOrigin Merchant. If no active cart exists, a 404 Not Found error is returned.

        The cart may not contain up-to-date prices, discounts etc. If you want to ensure they're up-to-date,
        send an Update request with the Recalculate update action instead.
  /{projectKey}/carts/key={key}:
    get:
      tags:
        - "projectKey"
        - "carts"
        - "key=key" 
      security:
        - oauth_2_0:
            - "view_orders:{projectKey}"
      operationId: ByProjectKeyCartsKeyByKeyGet
      description: |-
        The cart may not contain up-to-date prices, discounts etc.
        If you want to ensure they're up-to-date, send an Update request with the Recalculate update action instead.
    post:
      tags:
        - "projectKey"
        - "carts"
        - "key=key" 
      security:
        - oauth_2_0:
            - "manage_orders:{projectKey}"
      operationId: ByProjectKeyCartsKeyByKeyPost
      description: |-
        Update Cart by key
    delete:
      tags:
        - "projectKey"
        - "carts"
        - "key=key" 
      security:
        - oauth_2_0:
            - "manage_orders:{projectKey}"
      operationId: ByProjectKeyCartsKeyByKeyDelete
      description: |-
        Delete Cart by key
  /{projectKey}/carts/replicate:
    post:
      tags:
        - "projectKey"
        - "carts"
        - "replicate" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_orders:{projectKey}"
      operationId: ByProjectKeyCartsReplicatePost
  /{projectKey}/carts/{ID}:
    get:
      tags:
        - "projectKey"
        - "carts"
        - "ID" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "view_orders:{projectKey}"
      operationId: ByProjectKeyCartsByIDGet
      description: |-
        The cart may not contain up-to-date prices, discounts etc.
        If you want to ensure they're up-to-date, send an Update request with the Recalculate update action instead.
    post:
      tags:
        - "projectKey"
        - "carts"
        - "ID" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_orders:{projectKey}"
      operationId: ByProjectKeyCartsByIDPost
      description: |-
        Update Cart by ID
    delete:
      tags:
        - "projectKey"
        - "carts"
        - "ID" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_orders:{projectKey}"
      operationId: ByProjectKeyCartsByIDDelete
      description: |-
        Delete Cart by ID
  /{projectKey}/categories:
    description: |-
      Categories are used to organize products in a hierarchical structure.
    get:
      tags:
        - "projectKey"
        - "categories" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "view_products:{projectKey}"
            - "view_categories:{projectKey}"
      operationId: ByProjectKeyCategoriesGet
      description: |-
        Query categories
    post:
      tags:
        - "projectKey"
        - "categories" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_products:{projectKey}"
            - "view_categories:{projectKey}"
      operationId: ByProjectKeyCategoriesPost
      description: |-
        Creating a category produces the CategoryCreated message.
  /{projectKey}/categories/key={key}:
    get:
      tags:
        - "projectKey"
        - "categories"
        - "key=key" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "view_products:{projectKey}"
            - "view_categories:{projectKey}"
      operationId: ByProjectKeyCategoriesKeyByKeyGet
      description: |-
        Get Category by key
    post:
      tags:
        - "projectKey"
        - "categories"
        - "key=key" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_products:{projectKey}"
            - "manage_categories:{projectKey}"
      operationId: ByProjectKeyCategoriesKeyByKeyPost
      description: |-
        Update Category by key
    delete:
      tags:
        - "projectKey"
        - "categories"
        - "key=key" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_products:{projectKey}"
            - "manage_categories:{projectKey}"
      operationId: ByProjectKeyCategoriesKeyByKeyDelete
      description: |-
        Delete Category by key
  /{projectKey}/categories/{ID}:
    get:
      tags:
        - "projectKey"
        - "categories"
        - "ID" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "view_products:{projectKey}"
            - "view_categories:{projectKey}"
      operationId: ByProjectKeyCategoriesByIDGet
      description: |-
        Get Category by ID
    post:
      tags:
        - "projectKey"
        - "categories"
        - "ID" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_products:{projectKey}"
            - "manage_categories:{projectKey}"
      operationId: ByProjectKeyCategoriesByIDPost
      description: |-
        Update Category by ID
    delete:
      tags:
        - "projectKey"
        - "categories"
        - "ID" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_products:{projectKey}"
            - "manage_categories:{projectKey}"
      operationId: ByProjectKeyCategoriesByIDDelete
      description: |-
        Delete Category by ID
  /{projectKey}/channels:
    description: |-
      Channels represent a source or destination of different entities. They can be used to model warehouses or stores.
    get:
      tags:
        - "projectKey"
        - "channels" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "view_products:{projectKey}"
      operationId: ByProjectKeyChannelsGet
      description: |-
        Query channels
    post:
      tags:
        - "projectKey"
        - "channels" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_products:{projectKey}"
      operationId: ByProjectKeyChannelsPost
      description: |-
        Create Channel
  /{projectKey}/channels/{ID}:
    get:
      tags:
        - "projectKey"
        - "channels"
        - "ID" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "view_products:{projectKey}"
      operationId: ByProjectKeyChannelsByIDGet
      description: |-
        Get Channel by ID
    post:
      tags:
        - "projectKey"
        - "channels"
        - "ID" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_products:{projectKey}"
      operationId: ByProjectKeyChannelsByIDPost
      description: |-
        Update Channel by ID
    delete:
      tags:
        - "projectKey"
        - "channels"
        - "ID" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_products:{projectKey}"
      operationId: ByProjectKeyChannelsByIDDelete
      description: |-
        Delete Channel by ID
  /{projectKey}/custom-objects:
    description: |-
      Store custom JSON values.
    get:
      tags:
        - "projectKey"
        - "custom-objects" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "view_products:{projectKey}"
            - "view_orders:{projectKey}"
            - "view_customers:{projectKey}"
      operationId: ByProjectKeyCustomObjectsGet
      description: |-
        The query endpoint allows to retrieve custom objects in a specific container or all custom objects.
        For performance reasons, it is highly advisable to query only for custom objects in a container by using
        the container field in the where predicate.
    post:
      tags:
        - "projectKey"
        - "custom-objects" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_products:{projectKey}"
            - "manage_orders:{projectKey}"
            - "manage_customers:{projectKey}"
      operationId: ByProjectKeyCustomObjectsPost
      description: |-
        Creates a new custom object or updates an existing custom object.
        If an object with the given container/key exists,
        the object will be replaced with the new value and the version is incremented.
        If the request contains a version and an object with the given container/key exists then the version
        must match the version of the existing object. Concurrent updates for the same custom object still can result
        in a Conflict (409) even if the version is not provided.
        Fields with null values will not be saved.
  /{projectKey}/custom-objects/{container}:
    get:
      tags:
        - "projectKey"
        - "custom-objects"
        - "container" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "view_products:{projectKey}"
            - "view_orders:{projectKey}"
            - "view_customers:{projectKey}"
      operationId: ByProjectKeyCustomObjectsByContainerGet
      description: |-
        Get CustomObjectPagedQueryResponse by container
  /{projectKey}/custom-objects/{container}/{key}:
    get:
      tags:
        - "projectKey"
        - "custom-objects"
        - "container"
        - "key" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "view_products:{projectKey}"
            - "view_orders:{projectKey}"
            - "view_customers:{projectKey}"
      operationId: ByProjectKeyCustomObjectsByContainerByKeyGet
      description: |-
        Get CustomObject by container and key
    delete:
      tags:
        - "projectKey"
        - "custom-objects"
        - "container"
        - "key" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_products:{projectKey}"
            - "manage_orders:{projectKey}"
            - "manage_customers:{projectKey}"
      operationId: ByProjectKeyCustomObjectsByContainerByKeyDelete
      description: |-
        Delete CustomObject by container and key
  /{projectKey}/customer-groups:
    description: |-
      customer-groups are used to evaluate products and channels.
    get:
      tags:
        - "projectKey"
        - "customer-groups" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "view_customers:{projectKey}"
            - "view_customer_groups:{projectKey}"
      operationId: ByProjectKeyCustomerGroupsGet
      description: |-
        Query customer-groups
    post:
      tags:
        - "projectKey"
        - "customer-groups" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_customers:{projectKey}"
            - "manage_customer_groups:{projectKey}"
      operationId: ByProjectKeyCustomerGroupsPost
      description: |-
        Create CustomerGroup
  /{projectKey}/customer-groups/key={key}:
    get:
      tags:
        - "projectKey"
        - "customer-groups"
        - "key=key" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "view_customers:{projectKey}"
            - "view_customer_groups:{projectKey}"
      operationId: ByProjectKeyCustomerGroupsKeyByKeyGet
      description: |-
        Gets a customer group by Key.
    post:
      tags:
        - "projectKey"
        - "customer-groups"
        - "key=key" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_customers:{projectKey}"
            - "manage_customer_groups:{projectKey}"
      operationId: ByProjectKeyCustomerGroupsKeyByKeyPost
      description: |-
        Updates a customer group by Key.
    delete:
      tags:
        - "projectKey"
        - "customer-groups"
        - "key=key" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_customers:{projectKey}"
            - "manage_customer_groups:{projectKey}"
      operationId: ByProjectKeyCustomerGroupsKeyByKeyDelete
      description: |-
        Delete CustomerGroup by key
  /{projectKey}/customer-groups/{ID}:
    get:
      tags:
        - "projectKey"
        - "customer-groups"
        - "ID" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "view_customers:{projectKey}"
            - "view_customer_groups:{projectKey}"
      operationId: ByProjectKeyCustomerGroupsByIDGet
      description: |-
        Get CustomerGroup by ID
    post:
      tags:
        - "projectKey"
        - "customer-groups"
        - "ID" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_customers:{projectKey}"
            - "manage_customer_groups:{projectKey}"
      operationId: ByProjectKeyCustomerGroupsByIDPost
      description: |-
        Update CustomerGroup by ID
    delete:
      tags:
        - "projectKey"
        - "customer-groups"
        - "ID" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_customers:{projectKey}"
            - "manage_customer_groups:{projectKey}"
      operationId: ByProjectKeyCustomerGroupsByIDDelete
      description: |-
        Delete CustomerGroup by ID
  /{projectKey}/customers:
    description: |-
      A customer is a person purchasing products. customers, Orders, Comments and Reviews can be associated to a customer.
    get:
      tags:
        - "projectKey"
        - "customers" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "view_customers:{projectKey}"
      operationId: ByProjectKeyCustomersGet
      description: |-
        Query customers
    post:
      tags:
        - "projectKey"
        - "customers" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_customers:{projectKey}"
      operationId: ByProjectKeyCustomersPost
      description: |-
        Creates a customer. If an anonymous cart is passed in,
        then the cart is assigned to the created customer and the version number of the Cart will increase.
        If the ID of an anonymous session is given, all carts and orders will be assigned to the created customer.
  /{projectKey}/customers/email-token:
    description: |-
      To verify a customer's email, an email token can be created. This should be embedded in a link and sent to the
      customer via email. When the customer clicks on the link, the "verify customer's email" endpoint should be called,
      which sets customer's isVerifiedEmail field to true.
    post:
      tags:
        - "projectKey"
        - "customers"
        - "email-token" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_customers:{projectKey}"
      operationId: ByProjectKeyCustomersEmailTokenPost
      description: |-
        Create a Token for verifying the Customer's Email
  /{projectKey}/customers/email-token={emailToken}:
    get:
      tags:
        - "projectKey"
        - "customers"
        - "email-token=emailToken" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "view_customers:{projectKey}"
      operationId: ByProjectKeyCustomersEmailTokenByEmailTokenGet
      description: |-
        Get Customer by emailToken
  /{projectKey}/customers/email/confirm:
    post:
      tags:
        - "projectKey"
        - "customers"
        - "email"
        - "confirm" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_customers:{projectKey}"
      operationId: ByProjectKeyCustomersEmailConfirmPost
      description: |-
        Verifies customer's email using a token.
  /{projectKey}/customers/key={key}:
    get:
      tags:
        - "projectKey"
        - "customers"
        - "key=key" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "view_customers:{projectKey}"
      operationId: ByProjectKeyCustomersKeyByKeyGet
      description: |-
        Get Customer by key
    post:
      tags:
        - "projectKey"
        - "customers"
        - "key=key" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_customers:{projectKey}"
      operationId: ByProjectKeyCustomersKeyByKeyPost
      description: |-
        Update Customer by key
    delete:
      tags:
        - "projectKey"
        - "customers"
        - "key=key" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_customers:{projectKey}"
      operationId: ByProjectKeyCustomersKeyByKeyDelete
      description: |-
        Delete Customer by key
  /{projectKey}/customers/password:
    post:
      tags:
        - "projectKey"
        - "customers"
        - "password" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_customers:{projectKey}"
      operationId: ByProjectKeyCustomersPasswordPost
      description: |-
        Change a customers password
  /{projectKey}/customers/password-token:
    description: |-
      The following workflow can be used to reset the customer's password:

      * Create a password reset token and send it embedded in a link to the customer.
      * When the customer clicks on the link, the customer is retrieved with the token.
      * The customer enters a new password and the "reset customer's password" endpoint is called.
    post:
      tags:
        - "projectKey"
        - "customers"
        - "password-token" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_customers:{projectKey}"
      operationId: ByProjectKeyCustomersPasswordTokenPost
      description: |-
        The token value is used to reset the password of the customer with the given email. The token is
        valid only for 10 minutes.
  /{projectKey}/customers/password-token={passwordToken}:
    get:
      tags:
        - "projectKey"
        - "customers"
        - "password-token=passwordToken" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "view_customers:{projectKey}"
      operationId: ByProjectKeyCustomersPasswordTokenByPasswordTokenGet
      description: |-
        Get Customer by passwordToken
  /{projectKey}/customers/password/reset:
    post:
      tags:
        - "projectKey"
        - "customers"
        - "password"
        - "reset" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_customers:{projectKey}"
      operationId: ByProjectKeyCustomersPasswordResetPost
      description: |-
        Set a new password using a token.
  /{projectKey}/customers/{ID}:
    get:
      tags:
        - "projectKey"
        - "customers"
        - "ID" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "view_customers:{projectKey}"
      operationId: ByProjectKeyCustomersByIDGet
      description: |-
        Get Customer by ID
    post:
      tags:
        - "projectKey"
        - "customers"
        - "ID" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_customers:{projectKey}"
      operationId: ByProjectKeyCustomersByIDPost
      description: |-
        Update Customer by ID
    delete:
      tags:
        - "projectKey"
        - "customers"
        - "ID" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_customers:{projectKey}"
      operationId: ByProjectKeyCustomersByIDDelete
      description: |-
        Delete Customer by ID
  /{projectKey}/discount-codes:
    description: |-
      Discount codes can be added to a discount-code to enable certain discount-code discounts.
    get:
      tags:
        - "projectKey"
        - "discount-codes" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "view_orders:{projectKey}"
      operationId: ByProjectKeyDiscountCodesGet
      description: |-
        Query discount-codes
    post:
      tags:
        - "projectKey"
        - "discount-codes" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_orders:{projectKey}"
      operationId: ByProjectKeyDiscountCodesPost
      description: |-
        Create DiscountCode
  /{projectKey}/discount-codes/{ID}:
    get:
      tags:
        - "projectKey"
        - "discount-codes"
        - "ID" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "view_orders:{projectKey}"
      operationId: ByProjectKeyDiscountCodesByIDGet
      description: |-
        Get DiscountCode by ID
    post:
      tags:
        - "projectKey"
        - "discount-codes"
        - "ID" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_orders:{projectKey}"
      operationId: ByProjectKeyDiscountCodesByIDPost
      description: |-
        Update DiscountCode by ID
    delete:
      tags:
        - "projectKey"
        - "discount-codes"
        - "ID" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_orders:{projectKey}"
      operationId: ByProjectKeyDiscountCodesByIDDelete
      description: |-
        Delete DiscountCode by ID
  /{projectKey}/extensions:
    description: |-
      Extend the behavior of an API with your business logic
    get:
      tags:
        - "projectKey"
        - "extensions" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_extensions:{projectKey}"
      operationId: ByProjectKeyExtensionsGet
      description: |-
        Query extensions
    post:
      tags:
        - "projectKey"
        - "extensions" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_extensions:{projectKey}"
      operationId: ByProjectKeyExtensionsPost
      description: |-
        Currently, a maximum of 25 extensions can be created per project.
  /{projectKey}/extensions/key={key}:
    get:
      tags:
        - "projectKey"
        - "extensions"
        - "key=key" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_extensions:{projectKey}"
      operationId: ByProjectKeyExtensionsKeyByKeyGet
      description: |-
        Retrieves the representation of an extension by its key.
    post:
      tags:
        - "projectKey"
        - "extensions"
        - "key=key" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_extensions:{projectKey}"
      operationId: ByProjectKeyExtensionsKeyByKeyPost
      description: |-
        Update Extension by key
    delete:
      tags:
        - "projectKey"
        - "extensions"
        - "key=key" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_extensions:{projectKey}"
      operationId: ByProjectKeyExtensionsKeyByKeyDelete
      description: |-
        Delete Extension by key
  /{projectKey}/extensions/{ID}:
    get:
      tags:
        - "projectKey"
        - "extensions"
        - "ID" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_extensions:{projectKey}"
      operationId: ByProjectKeyExtensionsByIDGet
      description: |-
        Retrieves the representation of an extension by its id.
    post:
      tags:
        - "projectKey"
        - "extensions"
        - "ID" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_extensions:{projectKey}"
      operationId: ByProjectKeyExtensionsByIDPost
      description: |-
        Update Extension by ID
    delete:
      tags:
        - "projectKey"
        - "extensions"
        - "ID" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_extensions:{projectKey}"
      operationId: ByProjectKeyExtensionsByIDDelete
      description: |-
        Delete Extension by ID
  /{projectKey}/graphql:
    description: |-
      The commercetools™ platform provides a GraphQL API
    post:
      tags:
        - "projectKey"
        - "graphql" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "view_products:{projectKey}"
      operationId: ByProjectKeyGraphqlPost
      description: |-
        Execute a GraphQL query
  /{projectKey}/in-store/key={storeKey}:
  /{projectKey}/in-store/key={storeKey}/carts:
    description: |-
      A shopping cart holds product variants and can be ordered.
    get:
      tags:
        - "projectKey"
        - "in-store"
        - "key=storeKey"
        - "carts" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "view_orders:{projectKey}"
            - "view_orders:{projectKey}:{storeKey}"
      operationId: ByProjectKeyInStoreKeyByStoreKeyCartsGet
      description: |-
        Queries carts in a specific Store. The {storeKey} path parameter maps to a Store's key.
    post:
      tags:
        - "projectKey"
        - "in-store"
        - "key=storeKey"
        - "carts" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_orders:{projectKey}"
            - "manage_orders:{projectKey}:{storeKey}"
      operationId: ByProjectKeyInStoreKeyByStoreKeyCartsPost
      description: |-
        Creates a cart in the store specified by {storeKey}. The {storeKey} path parameter maps to a Store's key.
        When using this endpoint the cart's store field is always set to the store specified in the path parameter.
        Creating a cart can fail with an InvalidOperation if the referenced shipping method
        in the CartDraft has a predicate which does not match the cart.
  /{projectKey}/in-store/key={storeKey}/carts/customer-id={customerId}:
    get:
      tags:
        - "projectKey"
        - "in-store"
        - "key=storeKey"
        - "carts"
        - "customer-id=customerId" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "view_orders:{projectKey}"
      operationId: ByProjectKeyInStoreKeyByStoreKeyCartsCustomerIdByCustomerIdGet
      description: |-
        Retrieves the active cart of the customer that has been modified most recently in a specific Store.
        The {storeKey} path parameter maps to a Store's key.

        If the cart exists in the commercetools project but does not have the store field, or the store field
        references a different store, this method returns a ResourceNotFound error.

        The cart may not contain up-to-date prices, discounts etc. If you want to ensure they're up-to-date,
        send an Update request with the Recalculate update action instead.
  /{projectKey}/in-store/key={storeKey}/carts/key={key}:
    get:
      tags:
        - "projectKey"
        - "in-store"
        - "key=storeKey"
        - "carts"
        - "key=key" 
      security:
        - oauth_2_0:
            - "view_orders:{projectKey}"
            - "view_orders:{projectKey}:{storeKey}"
      operationId: ByProjectKeyInStoreKeyByStoreKeyCartsKeyByKeyGet
      description: |-
        Returns a cart by its key from a specific Store. The {storeKey} path parameter maps to a Store's key.
        If the cart exists in the commercetools project but does not have the store field,
        or the store field references a different store, this method returns a ResourceNotFound error.
        The cart may not contain up-to-date prices, discounts etc.
        If you want to ensure they're up-to-date, send an Update request with the Recalculate update action instead.
    post:
      tags:
        - "projectKey"
        - "in-store"
        - "key=storeKey"
        - "carts"
        - "key=key" 
      security:
        - oauth_2_0:
            - "manage_orders:{projectKey}"
            - "manage_orders:{projectKey}:{storeKey}"
      operationId: ByProjectKeyInStoreKeyByStoreKeyCartsKeyByKeyPost
      description: |-
        Updates a cart in the store specified by {storeKey}. The {storeKey} path parameter maps to a Store's key.
        If the cart exists in the commercetools project but does not have the store field,
        or the store field references a different store, this method returns a ResourceNotFound error.
    delete:
      tags:
        - "projectKey"
        - "in-store"
        - "key=storeKey"
        - "carts"
        - "key=key" 
      security:
        - oauth_2_0:
            - "manage_orders:{projectKey}"
            - "manage_orders:{projectKey}:{storeKey}"
      operationId: ByProjectKeyInStoreKeyByStoreKeyCartsKeyByKeyDelete
      description: |-
        Delete Cart by key
  /{projectKey}/in-store/key={storeKey}/carts/replicate:
    post:
      tags:
        - "projectKey"
        - "in-store"
        - "key=storeKey"
        - "carts"
        - "replicate" 
      security:
        - oauth_2_0:
            - "manage_orders:{projectKey}:{storeKey}"
            - "manage_orders:{projectKey}"
      operationId: ByProjectKeyInStoreKeyByStoreKeyCartsReplicatePost
  /{projectKey}/in-store/key={storeKey}/carts/{ID}:
    get:
      tags:
        - "projectKey"
        - "in-store"
        - "key=storeKey"
        - "carts"
        - "ID" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "view_orders:{projectKey}"
            - "view_orders:{projectKey}:{storeKey}"
      operationId: ByProjectKeyInStoreKeyByStoreKeyCartsByIDGet
      description: |-
        Returns a cart by its ID from a specific Store. The {storeKey} path parameter maps to a Store's key.
        If the cart exists in the commercetools project but does not have the store field,
        or the store field references a different store, this method returns a ResourceNotFound error.
        The cart may not contain up-to-date prices, discounts etc.
        If you want to ensure they're up-to-date, send an Update request with the Recalculate update action instead.
    post:
      tags:
        - "projectKey"
        - "in-store"
        - "key=storeKey"
        - "carts"
        - "ID" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_orders:{projectKey}"
            - "manage_orders:{projectKey}:{storeKey}"
      operationId: ByProjectKeyInStoreKeyByStoreKeyCartsByIDPost
      description: |-
        Updates a cart in the store specified by {storeKey}. The {storeKey} path parameter maps to a Store's key.
        If the cart exists in the commercetools project but does not have the store field,
        or the store field references a different store, this method returns a ResourceNotFound error.
    delete:
      tags:
        - "projectKey"
        - "in-store"
        - "key=storeKey"
        - "carts"
        - "ID" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_orders:{projectKey}"
            - "manage_orders:{projectKey}:{storeKey}"
      operationId: ByProjectKeyInStoreKeyByStoreKeyCartsByIDDelete
      description: |-
        Delete Cart by ID
  /{projectKey}/in-store/key={storeKey}/customers:
    description: |-
      A customer is a person purchasing products. customers, Orders,
      Comments and Reviews can be associated to a customer.
    get:
      tags:
        - "projectKey"
        - "in-store"
        - "key=storeKey"
        - "customers" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "view_customers:{projectKey}"
            - "view_customers:{projectKey}:{storeKey}"
      operationId: ByProjectKeyInStoreKeyByStoreKeyCustomersGet
      description: |-
        Query customers
    post:
      tags:
        - "projectKey"
        - "in-store"
        - "key=storeKey"
        - "customers" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_customers:{projectKey}"
            - "manage_customers:{projectKey}:{storeKey}"
      operationId: ByProjectKeyInStoreKeyByStoreKeyCustomersPost
      description: |-
        Creates a customer in a specific Store. The {storeKey} path parameter maps to a Store's key.
        When using this endpoint, if omitted,
        the customer's stores field is set to the store specified in the path parameter.
        If an anonymous cart is passed in as when using this method,
        then the cart is assigned to the created customer and the version number of the Cart increases.
        If the ID of an anonymous session is given, all carts and orders will be assigned to the created customer and
        the store specified. If you pass in a cart with a store field specified,
        the store field must reference the same store specified in the {storeKey} path parameter.
  /{projectKey}/in-store/key={storeKey}/customers/email-token:
    description: |-
      To verify a customer's email, an email token can be created. This should be embedded in a link and sent to the
      customer via email. When the customer clicks on the link,
      the "verify customer's email" endpoint should be called,
      which sets customer's isVerifiedEmail field to true.
    post:
      tags:
        - "projectKey"
        - "in-store"
        - "key=storeKey"
        - "customers"
        - "email-token" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_customers:{projectKey}"
            - "manage_customers:{projectKey}:{storeKey}"
      operationId: ByProjectKeyInStoreKeyByStoreKeyCustomersEmailTokenPost
      description: |-
        Create a Token for verifying the Customer's Email in store
  /{projectKey}/in-store/key={storeKey}/customers/email-token={emailToken}:
    get:
      tags:
        - "projectKey"
        - "in-store"
        - "key=storeKey"
        - "customers"
        - "email-token=emailToken" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "view_customers:{projectKey}"
            - "view_customers:{projectKey}:{storeKey}"
      operationId: ByProjectKeyInStoreKeyByStoreKeyCustomersEmailTokenByEmailTokenGet
      description: |-
        Get Customer by emailToken
  /{projectKey}/in-store/key={storeKey}/customers/email/confirm:
    post:
      tags:
        - "projectKey"
        - "in-store"
        - "key=storeKey"
        - "customers"
        - "email"
        - "confirm" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_customers:{projectKey}"
            - "manage_customers:{projectKey}:{storeKey}"
      operationId: ByProjectKeyInStoreKeyByStoreKeyCustomersEmailConfirmPost
      description: |-
        Verifies customer's email using a token.
  /{projectKey}/in-store/key={storeKey}/customers/key={key}:
    get:
      tags:
        - "projectKey"
        - "in-store"
        - "key=storeKey"
        - "customers"
        - "key=key" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "view_customers:{projectKey}"
            - "view_customers:{projectKey}:{storeKey}"
      operationId: ByProjectKeyInStoreKeyByStoreKeyCustomersKeyByKeyGet
      description: |-
        Returns a customer by its Key from a specific Store. The {storeKey} path parameter maps to a Store's key.
        It also considers customers that do not have the stores field.
        If the customer exists in the commercetools project but the stores field references different stores,
        this method returns a ResourceNotFound error.
    post:
      tags:
        - "projectKey"
        - "in-store"
        - "key=storeKey"
        - "customers"
        - "key=key" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_customers:{projectKey}"
            - "manage_customers:{projectKey}:{storeKey}"
      operationId: ByProjectKeyInStoreKeyByStoreKeyCustomersKeyByKeyPost
      description: |-
        If the customer exists in the commercetools project but the stores field references a different store,
        this method returns a ResourceNotFound error.
    delete:
      tags:
        - "projectKey"
        - "in-store"
        - "key=storeKey"
        - "customers"
        - "key=key" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_customers:{projectKey}"
            - "manage_customers:{projectKey}:{storeKey}"
      operationId: ByProjectKeyInStoreKeyByStoreKeyCustomersKeyByKeyDelete
      description: |-
        Delete Customer by key
  /{projectKey}/in-store/key={storeKey}/customers/password:
    post:
      tags:
        - "projectKey"
        - "in-store"
        - "key=storeKey"
        - "customers"
        - "password" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_customers:{projectKey}"
            - "manage_customers:{projectKey}:{storeKey}"
      operationId: ByProjectKeyInStoreKeyByStoreKeyCustomersPasswordPost
      description: |-
        Change a customers password
  /{projectKey}/in-store/key={storeKey}/customers/password-token:
    description: |-
      The following workflow can be used to reset the customer's password:

      * Create a password reset token and send it embedded in a link to the customer.
      * When the customer clicks on the link, the customer is retrieved with the token.
      * The customer enters a new password and the "reset customer's password" endpoint is called.
    post:
      tags:
        - "projectKey"
        - "in-store"
        - "key=storeKey"
        - "customers"
        - "password-token" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_customers:{projectKey}"
            - "manage_customers:{projectKey}:{storeKey}"
      operationId: ByProjectKeyInStoreKeyByStoreKeyCustomersPasswordTokenPost
      description: |-
        The token value is used to reset the password of the customer with the given email. The token is
        valid only for 10 minutes.
  /{projectKey}/in-store/key={storeKey}/customers/password-token={passwordToken}:
    get:
      tags:
        - "projectKey"
        - "in-store"
        - "key=storeKey"
        - "customers"
        - "password-token=passwordToken" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "view_customers:{projectKey}"
            - "view_customers:{projectKey}:{storeKey}"
      operationId: ByProjectKeyInStoreKeyByStoreKeyCustomersPasswordTokenByPasswordTokenGet
      description: |-
        Get Customer by passwordToken
  /{projectKey}/in-store/key={storeKey}/customers/password/reset:
    post:
      tags:
        - "projectKey"
        - "in-store"
        - "key=storeKey"
        - "customers"
        - "password"
        - "reset" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_customers:{projectKey}"
            - "manage_customers:{projectKey}:{storeKey}"
      operationId: ByProjectKeyInStoreKeyByStoreKeyCustomersPasswordResetPost
      description: |-
        Set a new password using a token.
  /{projectKey}/in-store/key={storeKey}/customers/{ID}:
    get:
      tags:
        - "projectKey"
        - "in-store"
        - "key=storeKey"
        - "customers"
        - "ID" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "view_customers:{projectKey}"
            - "view_customers:{projectKey}:{storeKey}"
      operationId: ByProjectKeyInStoreKeyByStoreKeyCustomersByIDGet
      description: |-
        Returns a customer by its ID from a specific Store. The {storeKey} path parameter maps to a Store's key.
        It also considers customers that do not have the stores field.
        If the customer exists in the commercetools project but the stores field references different stores,
        this method returns a ResourceNotFound error.
    post:
      tags:
        - "projectKey"
        - "in-store"
        - "key=storeKey"
        - "customers"
        - "ID" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_customers:{projectKey}"
            - "manage_customers:{projectKey}:{storeKey}"
      operationId: ByProjectKeyInStoreKeyByStoreKeyCustomersByIDPost
      description: |-
        Updates a customer in the store specified by {storeKey}. The {storeKey} path parameter maps to a Store's key.
        If the customer exists in the commercetools project but the stores field references a different store,
        this method returns a ResourceNotFound error.
    delete:
      tags:
        - "projectKey"
        - "in-store"
        - "key=storeKey"
        - "customers"
        - "ID" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_customers:{projectKey}"
            - "manage_customers:{projectKey}:{storeKey}"
      operationId: ByProjectKeyInStoreKeyByStoreKeyCustomersByIDDelete
      description: |-
        Delete Customer by ID
  /{projectKey}/in-store/key={storeKey}/login:
    description: |-
      Retrieves the authenticated customer.
    post:
      tags:
        - "projectKey"
        - "in-store"
        - "key=storeKey"
        - "login" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_customers:{projectKey}"
            - "manage_customers:{projectKey}:{storeKey}"
      operationId: ByProjectKeyInStoreKeyByStoreKeyLoginPost
      description: |-
        Authenticate Customer (Sign In) in store
  /{projectKey}/in-store/key={storeKey}/me:
  /{projectKey}/in-store/key={storeKey}/me/active-cart:
    get:
      tags:
        - "projectKey"
        - "in-store"
        - "key=storeKey"
        - "me"
        - "active-cart" 
      security:
        - oauth_2_0:
            - "manage_my_orders:{projectKey}"
            - "manage_my_orders:{projectKey}:{storeKey}"
      operationId: ByProjectKeyInStoreKeyByStoreKeyMeActiveCartGet
  /{projectKey}/in-store/key={storeKey}/me/carts:
    description: |-
      A shopping cart holds product variants and can be ordered.
    get:
      tags:
        - "projectKey"
        - "in-store"
        - "key=storeKey"
        - "me"
        - "carts" 
      security:
        - oauth_2_0:
            - "manage_my_orders:{projectKey}"
            - "manage_my_orders:{projectKey}:{storeKey}"
      operationId: ByProjectKeyInStoreKeyByStoreKeyMeCartsGet
      description: |-
        Query carts
    post:
      tags:
        - "projectKey"
        - "in-store"
        - "key=storeKey"
        - "me"
        - "carts" 
      security:
        - oauth_2_0:
            - "manage_my_orders:{projectKey}"
            - "manage_my_orders:{projectKey}:{storeKey}"
      operationId: ByProjectKeyInStoreKeyByStoreKeyMeCartsPost
      description: |-
        Create Cart
  /{projectKey}/in-store/key={storeKey}/me/carts/{ID}:
    get:
      tags:
        - "projectKey"
        - "in-store"
        - "key=storeKey"
        - "me"
        - "carts"
        - "ID" 
      security:
        - oauth_2_0:
            - "manage_my_orders:{projectKey}"
            - "manage_my_orders:{projectKey}:{storeKey}"
      operationId: ByProjectKeyInStoreKeyByStoreKeyMeCartsByIDGet
      description: |-
        Get Cart by ID
    post:
      tags:
        - "projectKey"
        - "in-store"
        - "key=storeKey"
        - "me"
        - "carts"
        - "ID" 
      security:
        - oauth_2_0:
            - "manage_my_orders:{projectKey}"
            - "manage_my_orders:{projectKey}:{storeKey}"
      operationId: ByProjectKeyInStoreKeyByStoreKeyMeCartsByIDPost
      description: |-
        Update Cart by ID
    delete:
      tags:
        - "projectKey"
        - "in-store"
        - "key=storeKey"
        - "me"
        - "carts"
        - "ID" 
      security:
        - oauth_2_0:
            - "manage_my_orders:{projectKey}"
            - "manage_my_orders:{projectKey}:{storeKey}"
      operationId: ByProjectKeyInStoreKeyByStoreKeyMeCartsByIDDelete
      description: |-
        Delete Cart by ID
  /{projectKey}/in-store/key={storeKey}/me/orders:
    description: |-
      An order can be created from a order, usually after a checkout process has been completed.
    get:
      tags:
        - "projectKey"
        - "in-store"
        - "key=storeKey"
        - "me"
        - "orders" 
      security:
        - oauth_2_0:
            - "manage_my_orders:{projectKey}"
            - "manage_my_orders:{projectKey}:{storeKey}"
      operationId: ByProjectKeyInStoreKeyByStoreKeyMeOrdersGet
      description: |-
        Query orders
    post:
      tags:
        - "projectKey"
        - "in-store"
        - "key=storeKey"
        - "me"
        - "orders" 
      security:
        - oauth_2_0:
            - "manage_my_orders:{projectKey}"
            - "manage_my_orders:{projectKey}:{storeKey}"
      operationId: ByProjectKeyInStoreKeyByStoreKeyMeOrdersPost
      description: |-
        Create Order
  /{projectKey}/in-store/key={storeKey}/me/orders/{ID}:
    get:
      tags:
        - "projectKey"
        - "in-store"
        - "key=storeKey"
        - "me"
        - "orders"
        - "ID" 
      security:
        - oauth_2_0:
            - "manage_my_orders:{projectKey}"
            - "manage_my_orders:{projectKey}:{storeKey}"
      operationId: ByProjectKeyInStoreKeyByStoreKeyMeOrdersByIDGet
      description: |-
        Get Order by ID
  /{projectKey}/in-store/key={storeKey}/me/shopping-lists:
    description: |-
      shopping-lists e.g. for wishlist support
    get:
      tags:
        - "projectKey"
        - "in-store"
        - "key=storeKey"
        - "me"
        - "shopping-lists" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "view_shopping_lists:{projectKey}"
            - "view_shopping_lists:{projectKey}:{storeKey}"
      operationId: ByProjectKeyInStoreKeyByStoreKeyMeShoppingListsGet
      description: |-
        Query shopping-lists
    post:
      tags:
        - "projectKey"
        - "in-store"
        - "key=storeKey"
        - "me"
        - "shopping-lists" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_shopping_lists:{projectKey}"
            - "manage_shopping_lists:{projectKey}:{storeKey}"
      operationId: ByProjectKeyInStoreKeyByStoreKeyMeShoppingListsPost
      description: |-
        Create ShoppingList
  /{projectKey}/in-store/key={storeKey}/me/shopping-lists/key={key}:
    get:
      tags:
        - "projectKey"
        - "in-store"
        - "key=storeKey"
        - "me"
        - "shopping-lists"
        - "key=key" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "view_shopping_lists:{projectKey}"
            - "view_shopping_lists:{projectKey}:{storeKey}"
      operationId: ByProjectKeyInStoreKeyByStoreKeyMeShoppingListsKeyByKeyGet
      description: |-
        Gets a shopping list by Key.
    post:
      tags:
        - "projectKey"
        - "in-store"
        - "key=storeKey"
        - "me"
        - "shopping-lists"
        - "key=key" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_shopping_lists:{projectKey}"
            - "manage_shopping_lists:{projectKey}:{storeKey}"
      operationId: ByProjectKeyInStoreKeyByStoreKeyMeShoppingListsKeyByKeyPost
      description: |-
        Update a shopping list found by its Key.
    delete:
      tags:
        - "projectKey"
        - "in-store"
        - "key=storeKey"
        - "me"
        - "shopping-lists"
        - "key=key" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_shopping_lists:{projectKey}"
            - "manage_shopping_lists:{projectKey}:{storeKey}"
      operationId: ByProjectKeyInStoreKeyByStoreKeyMeShoppingListsKeyByKeyDelete
      description: |-
        Delete ShoppingList by key
  /{projectKey}/in-store/key={storeKey}/me/shopping-lists/{ID}:
    get:
      tags:
        - "projectKey"
        - "in-store"
        - "key=storeKey"
        - "me"
        - "shopping-lists"
        - "ID" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "view_shopping_lists:{projectKey}"
            - "view_shopping_lists:{projectKey}:{storeKey}"
      operationId: ByProjectKeyInStoreKeyByStoreKeyMeShoppingListsByIDGet
      description: |-
        Gets a shopping list by ID.
    post:
      tags:
        - "projectKey"
        - "in-store"
        - "key=storeKey"
        - "me"
        - "shopping-lists"
        - "ID" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_shopping_lists:{projectKey}"
            - "manage_shopping_lists:{projectKey}:{storeKey}"
      operationId: ByProjectKeyInStoreKeyByStoreKeyMeShoppingListsByIDPost
      description: |-
        Update ShoppingList by ID
    delete:
      tags:
        - "projectKey"
        - "in-store"
        - "key=storeKey"
        - "me"
        - "shopping-lists"
        - "ID" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_shopping_lists:{projectKey}"
            - "manage_shopping_lists:{projectKey}:{storeKey}"
      operationId: ByProjectKeyInStoreKeyByStoreKeyMeShoppingListsByIDDelete
      description: |-
        Delete ShoppingList by ID
  /{projectKey}/in-store/key={storeKey}/orders:
    description: |-
      An order can be created from a cart, usually after a checkout process has been completed.
    get:
      tags:
        - "projectKey"
        - "in-store"
        - "key=storeKey"
        - "orders" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "view_orders:{projectKey}"
            - "view_orders:{projectKey}:{storeKey}"
      operationId: ByProjectKeyInStoreKeyByStoreKeyOrdersGet
      description: |-
        Queries orders in a specific Store. The {storeKey} path parameter maps to a Store's key.
    post:
      tags:
        - "projectKey"
        - "in-store"
        - "key=storeKey"
        - "orders" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_orders:{projectKey}"
            - "manage_orders:{projectKey}:{storeKey}"
      operationId: ByProjectKeyInStoreKeyByStoreKeyOrdersPost
      description: |-
        Creates an order from a Cart from a specific Store. The {storeKey} path parameter maps to a Store's key.
        When using this endpoint the orders's store field is always set to the store specified in the path parameter.
        The cart must have a shipping address set before creating an order. When using the Platform TaxMode,
        the shipping address is used for tax calculation.
  /{projectKey}/in-store/key={storeKey}/orders/order-number={orderNumber}:
    get:
      tags:
        - "projectKey"
        - "in-store"
        - "key=storeKey"
        - "orders"
        - "order-number=orderNumber" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "view_orders:{projectKey}"
            - "view_orders:{projectKey}:{storeKey}"
      operationId: ByProjectKeyInStoreKeyByStoreKeyOrdersOrderNumberByOrderNumberGet
      description: |-
        Returns an order by its order number from a specific Store.
        The {storeKey} path parameter maps to a Store's key.
        If the order exists in the commercetools project but does not have the store field,
        or the store field references a different store, this method returns a ResourceNotFound error.
        In case the orderNumber does not match the regular expression [a-zA-Z0-9_-]+,
        it should be provided in URL-encoded format.
    post:
      tags:
        - "projectKey"
        - "in-store"
        - "key=storeKey"
        - "orders"
        - "order-number=orderNumber" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_orders:{projectKey}"
            - "manage_orders:{projectKey}:{storeKey}"
      operationId: ByProjectKeyInStoreKeyByStoreKeyOrdersOrderNumberByOrderNumberPost
      description: |-
        Updates an order in the store specified by {storeKey}. The {storeKey} path parameter maps to a Store's key.
        If the order exists in the commercetools project but does not have the store field,
        or the store field references a different store, this method returns a ResourceNotFound error.
        In case the orderNumber does not match the regular expression [a-zA-Z0-9_-]+,
        it should be provided in URL-encoded format.
    delete:
      tags:
        - "projectKey"
        - "in-store"
        - "key=storeKey"
        - "orders"
        - "order-number=orderNumber" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_orders:{projectKey}"
            - "manage_orders:{projectKey}:{storeKey}"
      operationId: ByProjectKeyInStoreKeyByStoreKeyOrdersOrderNumberByOrderNumberDelete
      description: |-
        Delete Order by orderNumber
  /{projectKey}/in-store/key={storeKey}/orders/{ID}:
    get:
      tags:
        - "projectKey"
        - "in-store"
        - "key=storeKey"
        - "orders"
        - "ID" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "view_orders:{projectKey}"
            - "view_orders:{projectKey}:{storeKey}"
      operationId: ByProjectKeyInStoreKeyByStoreKeyOrdersByIDGet
      description: |-
        Returns an order by its ID from a specific Store. The {storeKey} path parameter maps to a Store's key.
        If the order exists in the commercetools project but does not have the store field,
        or the store field references a different store, this method returns a ResourceNotFound error.
    post:
      tags:
        - "projectKey"
        - "in-store"
        - "key=storeKey"
        - "orders"
        - "ID" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_orders:{projectKey}"
            - "manage_orders:{projectKey}:{storeKey}"
      operationId: ByProjectKeyInStoreKeyByStoreKeyOrdersByIDPost
      description: |-
        Updates an order in the store specified by {storeKey}. The {storeKey} path parameter maps to a Store's key.
        If the order exists in the commercetools project but does not have the store field,
        or the store field references a different store, this method returns a ResourceNotFound error.
    delete:
      tags:
        - "projectKey"
        - "in-store"
        - "key=storeKey"
        - "orders"
        - "ID" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_orders:{projectKey}"
            - "manage_orders:{projectKey}:{storeKey}"
      operationId: ByProjectKeyInStoreKeyByStoreKeyOrdersByIDDelete
      description: |-
        Delete Order by ID
  /{projectKey}/in-store/key={storeKey}/shipping-methods:
  /{projectKey}/in-store/key={storeKey}/shipping-methods/matching-cart:
    description: |-
      Get ShippingMethods for a cart in a store
    get:
      tags:
        - "projectKey"
        - "in-store"
        - "key=storeKey"
        - "shipping-methods"
        - "matching-cart" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "view_orders:{projectKey}"
            - "manage_customers:{projectKey}:{storeKey}"
            - "view_shipping_methods:{projectKey}"
      operationId: ByProjectKeyInStoreKeyByStoreKeyShippingMethodsMatchingCartGet
  /{projectKey}/in-store/key={storeKey}/shopping-lists:
    description: |-
      shopping-lists e.g. for wishlist support
    get:
      tags:
        - "projectKey"
        - "in-store"
        - "key=storeKey"
        - "shopping-lists" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "view_shopping_lists:{projectKey}"
            - "view_shopping_lists:{projectKey}:{storeKey}"
      operationId: ByProjectKeyInStoreKeyByStoreKeyShoppingListsGet
      description: |-
        Query shopping-lists
    post:
      tags:
        - "projectKey"
        - "in-store"
        - "key=storeKey"
        - "shopping-lists" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_shopping_lists:{projectKey}"
            - "manage_shopping_lists:{projectKey}:{storeKey}"
      operationId: ByProjectKeyInStoreKeyByStoreKeyShoppingListsPost
      description: |-
        Create ShoppingList
  /{projectKey}/in-store/key={storeKey}/shopping-lists/key={key}:
    get:
      tags:
        - "projectKey"
        - "in-store"
        - "key=storeKey"
        - "shopping-lists"
        - "key=key" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "view_shopping_lists:{projectKey}"
            - "view_shopping_lists:{projectKey}:{storeKey}"
      operationId: ByProjectKeyInStoreKeyByStoreKeyShoppingListsKeyByKeyGet
      description: |-
        Gets a shopping list by Key.
    post:
      tags:
        - "projectKey"
        - "in-store"
        - "key=storeKey"
        - "shopping-lists"
        - "key=key" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_shopping_lists:{projectKey}"
            - "manage_shopping_lists:{projectKey}:{storeKey}"
      operationId: ByProjectKeyInStoreKeyByStoreKeyShoppingListsKeyByKeyPost
      description: |-
        Update a shopping list found by its Key.
    delete:
      tags:
        - "projectKey"
        - "in-store"
        - "key=storeKey"
        - "shopping-lists"
        - "key=key" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_shopping_lists:{projectKey}"
            - "manage_shopping_lists:{projectKey}:{storeKey}"
      operationId: ByProjectKeyInStoreKeyByStoreKeyShoppingListsKeyByKeyDelete
      description: |-
        Delete ShoppingList by key
  /{projectKey}/in-store/key={storeKey}/shopping-lists/{ID}:
    get:
      tags:
        - "projectKey"
        - "in-store"
        - "key=storeKey"
        - "shopping-lists"
        - "ID" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "view_shopping_lists:{projectKey}"
            - "view_shopping_lists:{projectKey}:{storeKey}"
      operationId: ByProjectKeyInStoreKeyByStoreKeyShoppingListsByIDGet
      description: |-
        Gets a shopping list by ID.
    post:
      tags:
        - "projectKey"
        - "in-store"
        - "key=storeKey"
        - "shopping-lists"
        - "ID" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_shopping_lists:{projectKey}"
            - "manage_shopping_lists:{projectKey}:{storeKey}"
      operationId: ByProjectKeyInStoreKeyByStoreKeyShoppingListsByIDPost
      description: |-
        Update ShoppingList by ID
    delete:
      tags:
        - "projectKey"
        - "in-store"
        - "key=storeKey"
        - "shopping-lists"
        - "ID" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_shopping_lists:{projectKey}"
            - "manage_shopping_lists:{projectKey}:{storeKey}"
      operationId: ByProjectKeyInStoreKeyByStoreKeyShoppingListsByIDDelete
      description: |-
        Delete ShoppingList by ID
  /{projectKey}/inventory:
    description: |-
      Inventory allows you to track stock quantities.
    get:
      tags:
        - "projectKey"
        - "inventory" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "view_products:{projectKey}"
      operationId: ByProjectKeyInventoryGet
      description: |-
        Query inventory
    post:
      tags:
        - "projectKey"
        - "inventory" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_products:{projectKey}"
      operationId: ByProjectKeyInventoryPost
      description: |-
        Create InventoryEntry
  /{projectKey}/inventory/{ID}:
    get:
      tags:
        - "projectKey"
        - "inventory"
        - "ID" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "view_products:{projectKey}"
      operationId: ByProjectKeyInventoryByIDGet
      description: |-
        Get InventoryEntry by ID
    post:
      tags:
        - "projectKey"
        - "inventory"
        - "ID" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_products:{projectKey}"
      operationId: ByProjectKeyInventoryByIDPost
      description: |-
        Update InventoryEntry by ID
    delete:
      tags:
        - "projectKey"
        - "inventory"
        - "ID" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_products:{projectKey}"
      operationId: ByProjectKeyInventoryByIDDelete
      description: |-
        Delete InventoryEntry by ID
  /{projectKey}/login:
    description: |-
      Retrieves the authenticated customer.
    post:
      tags:
        - "projectKey"
        - "login" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_customers:{projectKey}"
      operationId: ByProjectKeyLoginPost
      description: |-
        Authenticate Customer (Sign In). Retrieves the authenticated
        customer (a customer that matches the given email/password pair).
        If used with an access token for Anonymous Sessions,
        all orders and carts belonging to the anonymousId will be assigned to the newly created customer.
        If a cart is is returned as part of the CustomerSignInResult,
        it has been recalculated (It will have up-to-date prices, taxes and discounts,
        and invalid line items have been removed.).
  /{projectKey}/me:
    get:
      tags:
        - "projectKey"
        - "me" 
      security:
        - oauth_2_0:
            - "manage_my_profile:{projectKey}"
      operationId: ByProjectKeyMeGet
    post:
      tags:
        - "projectKey"
        - "me" 
      security:
        - oauth_2_0:
            - "manage_my_profile:{projectKey}"
      operationId: ByProjectKeyMePost
      description: |-
        Update my customer
    delete:
      tags:
        - "projectKey"
        - "me" 
      security:
        - oauth_2_0:
            - "manage_my_profile:{projectKey}"
      operationId: ByProjectKeyMeDelete
      description: |-
        Delete my Customer
  /{projectKey}/me/active-cart:
    get:
      tags:
        - "projectKey"
        - "me"
        - "active-cart" 
      security:
        - oauth_2_0:
            - "manage_my_orders:{projectKey}"
      operationId: ByProjectKeyMeActiveCartGet
  /{projectKey}/me/carts:
    description: |-
      A shopping cart holds product variants and can be ordered.
    get:
      tags:
        - "projectKey"
        - "me"
        - "carts" 
      security:
        - oauth_2_0:
            - "manage_my_orders:{projectKey}"
      operationId: ByProjectKeyMeCartsGet
      description: |-
        Query carts
    post:
      tags:
        - "projectKey"
        - "me"
        - "carts" 
      security:
        - oauth_2_0:
            - "manage_my_orders:{projectKey}"
      operationId: ByProjectKeyMeCartsPost
      description: |-
        Create Cart
  /{projectKey}/me/carts/key={key}:
    get:
      tags:
        - "projectKey"
        - "me"
        - "carts"
        - "key=key" 
      security:
        - oauth_2_0:
            - "manage_my_orders:{projectKey}"
      operationId: ByProjectKeyMeCartsKeyByKeyGet
      description: |-
        Get Cart by key
    post:
      tags:
        - "projectKey"
        - "me"
        - "carts"
        - "key=key" 
      security:
        - oauth_2_0:
            - "manage_my_orders:{projectKey}"
      operationId: ByProjectKeyMeCartsKeyByKeyPost
      description: |-
        Update Cart by key
    delete:
      tags:
        - "projectKey"
        - "me"
        - "carts"
        - "key=key" 
      security:
        - oauth_2_0:
            - "manage_my_orders:{projectKey}"
      operationId: ByProjectKeyMeCartsKeyByKeyDelete
      description: |-
        Delete Cart by key
  /{projectKey}/me/carts/{ID}:
    get:
      tags:
        - "projectKey"
        - "me"
        - "carts"
        - "ID" 
      security:
        - oauth_2_0:
            - "manage_my_orders:{projectKey}"
      operationId: ByProjectKeyMeCartsByIDGet
      description: |-
        Get Cart by ID
    post:
      tags:
        - "projectKey"
        - "me"
        - "carts"
        - "ID" 
      security:
        - oauth_2_0:
            - "manage_my_orders:{projectKey}"
      operationId: ByProjectKeyMeCartsByIDPost
      description: |-
        Update Cart by ID
    delete:
      tags:
        - "projectKey"
        - "me"
        - "carts"
        - "ID" 
      security:
        - oauth_2_0:
            - "manage_my_orders:{projectKey}"
      operationId: ByProjectKeyMeCartsByIDDelete
      description: |-
        Delete Cart by ID
  /{projectKey}/me/email/confirm:
    post:
      tags:
        - "projectKey"
        - "me"
        - "email"
        - "confirm" 
      security:
        - oauth_2_0:
            - "manage_my_profile:{projectKey}"
      operationId: ByProjectKeyMeEmailConfirmPost
  /{projectKey}/me/login:
    post:
      tags:
        - "projectKey"
        - "me"
        - "login" 
      security:
        - oauth_2_0:
            - "manage_my_profile:{projectKey}"
      operationId: ByProjectKeyMeLoginPost
  /{projectKey}/me/orders:
    description: |-
      An order can be created from a cart, usually after a checkout process has been completed.
    get:
      tags:
        - "projectKey"
        - "me"
        - "orders" 
      security:
        - oauth_2_0:
            - "manage_my_orders:{projectKey}"
      operationId: ByProjectKeyMeOrdersGet
      description: |-
        Query orders
    post:
      tags:
        - "projectKey"
        - "me"
        - "orders" 
      security:
        - oauth_2_0:
            - "manage_my_orders:{projectKey}"
      operationId: ByProjectKeyMeOrdersPost
      description: |-
        Create Order
  /{projectKey}/me/orders/{ID}:
    get:
      tags:
        - "projectKey"
        - "me"
        - "orders"
        - "ID" 
      security:
        - oauth_2_0:
            - "manage_my_orders:{projectKey}"
      operationId: ByProjectKeyMeOrdersByIDGet
      description: |-
        Get Order by ID
  /{projectKey}/me/password:
    post:
      tags:
        - "projectKey"
        - "me"
        - "password" 
      security:
        - oauth_2_0:
            - "manage_my_profile:{projectKey}"
      operationId: ByProjectKeyMePasswordPost
  /{projectKey}/me/password/reset:
    post:
      tags:
        - "projectKey"
        - "me"
        - "password"
        - "reset" 
      security:
        - oauth_2_0:
            - "manage_my_profile:{projectKey}"
      operationId: ByProjectKeyMePasswordResetPost
  /{projectKey}/me/payments:
    description: |-
      The My Payments endpoint creates and provides access to payments scoped to a specific user.
    get:
      tags:
        - "projectKey"
        - "me"
        - "payments" 
      security:
        - oauth_2_0:
            - "manage_my_payments:{projectKey}"
      operationId: ByProjectKeyMePaymentsGet
      description: |-
        Query payments
    post:
      tags:
        - "projectKey"
        - "me"
        - "payments" 
      security:
        - oauth_2_0:
            - "manage_my_payments:{projectKey}"
      operationId: ByProjectKeyMePaymentsPost
      description: |-
        Create MyPayment
  /{projectKey}/me/payments/key={key}:
    get:
      tags:
        - "projectKey"
        - "me"
        - "payments"
        - "key=key" 
      security:
        - oauth_2_0:
            - "manage_my_payments:{projectKey}"
      operationId: ByProjectKeyMePaymentsKeyByKeyGet
      description: |-
        Get MyPayment by key
    post:
      tags:
        - "projectKey"
        - "me"
        - "payments"
        - "key=key" 
      security:
        - oauth_2_0:
            - "manage_my_payments:{projectKey}"
      operationId: ByProjectKeyMePaymentsKeyByKeyPost
      description: |-
        Update MyPayment by key
    delete:
      tags:
        - "projectKey"
        - "me"
        - "payments"
        - "key=key" 
      security:
        - oauth_2_0:
            - "manage_my_payments:{projectKey}"
      operationId: ByProjectKeyMePaymentsKeyByKeyDelete
      description: |-
        Delete MyPayment by key
  /{projectKey}/me/payments/{ID}:
    get:
      tags:
        - "projectKey"
        - "me"
        - "payments"
        - "ID" 
      security:
        - oauth_2_0:
            - "manage_my_payments:{projectKey}"
      operationId: ByProjectKeyMePaymentsByIDGet
      description: |-
        Get MyPayment by ID
    post:
      tags:
        - "projectKey"
        - "me"
        - "payments"
        - "ID" 
      security:
        - oauth_2_0:
            - "manage_my_payments:{projectKey}"
      operationId: ByProjectKeyMePaymentsByIDPost
      description: |-
        Update MyPayment by ID
    delete:
      tags:
        - "projectKey"
        - "me"
        - "payments"
        - "ID" 
      security:
        - oauth_2_0:
            - "manage_my_payments:{projectKey}"
      operationId: ByProjectKeyMePaymentsByIDDelete
      description: |-
        Delete MyPayment by ID
  /{projectKey}/me/shopping-lists:
    description: |-
      The My Shopping Lists endpoint creates and provides access to shopping lists scoped to a specific user.
    get:
      tags:
        - "projectKey"
        - "me"
        - "shopping-lists" 
      security:
        - oauth_2_0:
            - "manage_my_shopping_lists:{projectKey}"
      operationId: ByProjectKeyMeShoppingListsGet
      description: |-
        Query shopping-lists
    post:
      tags:
        - "projectKey"
        - "me"
        - "shopping-lists" 
      security:
        - oauth_2_0:
            - "manage_my_shopping_lists:{projectKey}"
      operationId: ByProjectKeyMeShoppingListsPost
      description: |-
        Create ShoppingList
  /{projectKey}/me/shopping-lists/key={key}:
    get:
      tags:
        - "projectKey"
        - "me"
        - "shopping-lists"
        - "key=key" 
      security:
        - oauth_2_0:
            - "manage_my_shopping_lists:{projectKey}"
      operationId: ByProjectKeyMeShoppingListsKeyByKeyGet
      description: |-
        Get ShoppingList by key
    post:
      tags:
        - "projectKey"
        - "me"
        - "shopping-lists"
        - "key=key" 
      security:
        - oauth_2_0:
            - "manage_my_shopping_lists:{projectKey}"
      operationId: ByProjectKeyMeShoppingListsKeyByKeyPost
      description: |-
        Update ShoppingList by key
    delete:
      tags:
        - "projectKey"
        - "me"
        - "shopping-lists"
        - "key=key" 
      security:
        - oauth_2_0:
            - "manage_my_shopping_lists:{projectKey}"
      operationId: ByProjectKeyMeShoppingListsKeyByKeyDelete
      description: |-
        Delete ShoppingList by key
  /{projectKey}/me/shopping-lists/{ID}:
    get:
      tags:
        - "projectKey"
        - "me"
        - "shopping-lists"
        - "ID" 
      security:
        - oauth_2_0:
            - "manage_my_shopping_lists:{projectKey}"
      operationId: ByProjectKeyMeShoppingListsByIDGet
      description: |-
        Get ShoppingList by ID
    post:
      tags:
        - "projectKey"
        - "me"
        - "shopping-lists"
        - "ID" 
      security:
        - oauth_2_0:
            - "manage_my_shopping_lists:{projectKey}"
      operationId: ByProjectKeyMeShoppingListsByIDPost
      description: |-
        Update ShoppingList by ID
    delete:
      tags:
        - "projectKey"
        - "me"
        - "shopping-lists"
        - "ID" 
      security:
        - oauth_2_0:
            - "manage_my_shopping_lists:{projectKey}"
      operationId: ByProjectKeyMeShoppingListsByIDDelete
      description: |-
        Delete ShoppingList by ID
  /{projectKey}/me/signup:
    post:
      tags:
        - "projectKey"
        - "me"
        - "signup" 
      security:
        - oauth_2_0:
            - "manage_my_profile:{projectKey}"
      operationId: ByProjectKeyMeSignupPost
  /{projectKey}/messages:
    description: |-
      A message represents a change or an action performed on a resource (like an Order or a Product).
    get:
      tags:
        - "projectKey"
        - "messages" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "view_orders:{projectKey}"
      operationId: ByProjectKeyMessagesGet
      description: |-
        Query messages
  /{projectKey}/messages/{ID}:
    get:
      tags:
        - "projectKey"
        - "messages"
        - "ID" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "view_orders:{projectKey}"
      operationId: ByProjectKeyMessagesByIDGet
      description: |-
        Get Message by ID
  /{projectKey}/orders:
    description: |-
      An order can be created from a order, usually after a checkout process has been completed.
    get:
      tags:
        - "projectKey"
        - "orders" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "view_orders:{projectKey}"
      operationId: ByProjectKeyOrdersGet
      description: |-
        Query orders
    post:
      tags:
        - "projectKey"
        - "orders" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_orders:{projectKey}"
      operationId: ByProjectKeyOrdersPost
      description: |-
        Creates an order from a Cart.
        The cart must have a shipping address set before creating an order.
        When using the Platform TaxMode, the shipping address is used for tax calculation.
  /{projectKey}/orders/edits:
    description: |-
      OrderEdit are containers for financial changes after an Order has been placed.
    get:
      tags:
        - "projectKey"
        - "orders"
        - "edits" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "view_order_edits:{projectKey}"
      operationId: ByProjectKeyOrdersEditsGet
      description: |-
        Query edits
    post:
      tags:
        - "projectKey"
        - "orders"
        - "edits" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_order_edits:{projectKey}"
      operationId: ByProjectKeyOrdersEditsPost
      description: |-
        Create OrderEdit
  /{projectKey}/orders/edits/key={key}:
    get:
      tags:
        - "projectKey"
        - "orders"
        - "edits"
        - "key=key" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "view_order_edits:{projectKey}"
      operationId: ByProjectKeyOrdersEditsKeyByKeyGet
      description: |-
        Get OrderEdit by key
    post:
      tags:
        - "projectKey"
        - "orders"
        - "edits"
        - "key=key" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_order_edits:{projectKey}"
      operationId: ByProjectKeyOrdersEditsKeyByKeyPost
      description: |-
        Update OrderEdit by key
    delete:
      tags:
        - "projectKey"
        - "orders"
        - "edits"
        - "key=key" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_order_edits:{projectKey}"
      operationId: ByProjectKeyOrdersEditsKeyByKeyDelete
      description: |-
        Delete OrderEdit by key
  /{projectKey}/orders/edits/{ID}:
    get:
      tags:
        - "projectKey"
        - "orders"
        - "edits"
        - "ID" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "view_order_edits:{projectKey}"
      operationId: ByProjectKeyOrdersEditsByIDGet
      description: |-
        Get OrderEdit by ID
    post:
      tags:
        - "projectKey"
        - "orders"
        - "edits"
        - "ID" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_order_edits:{projectKey}"
      operationId: ByProjectKeyOrdersEditsByIDPost
      description: |-
        Update OrderEdit by ID
    delete:
      tags:
        - "projectKey"
        - "orders"
        - "edits"
        - "ID" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_order_edits:{projectKey}"
      operationId: ByProjectKeyOrdersEditsByIDDelete
      description: |-
        Delete OrderEdit by ID
  /{projectKey}/orders/edits/{ID}/apply:
    post:
      tags:
        - "projectKey"
        - "orders"
        - "edits"
        - "ID"
        - "apply" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_order_edits:{projectKey}"
      operationId: ByProjectKeyOrdersEditsByIDApplyPost
  /{projectKey}/orders/import:
    post:
      tags:
        - "projectKey"
        - "orders"
        - "import" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_orders:{projectKey}"
      operationId: ByProjectKeyOrdersImportPost
      description: |-
        Create an Order by Import
  /{projectKey}/orders/order-number={orderNumber}:
    get:
      tags:
        - "projectKey"
        - "orders"
        - "order-number=orderNumber" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "view_orders:{projectKey}"
      operationId: ByProjectKeyOrdersOrderNumberByOrderNumberGet
      description: |-
        In case the orderNumber does not match the regular expression [a-zA-Z0-9_-]+,
        it should be provided in URL-encoded format.
    post:
      tags:
        - "projectKey"
        - "orders"
        - "order-number=orderNumber" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_orders:{projectKey}"
      operationId: ByProjectKeyOrdersOrderNumberByOrderNumberPost
      description: |-
        Update Order by orderNumber
    delete:
      tags:
        - "projectKey"
        - "orders"
        - "order-number=orderNumber" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_orders:{projectKey}"
      operationId: ByProjectKeyOrdersOrderNumberByOrderNumberDelete
      description: |-
        Delete Order by orderNumber
  /{projectKey}/orders/{ID}:
    get:
      tags:
        - "projectKey"
        - "orders"
        - "ID" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "view_orders:{projectKey}"
      operationId: ByProjectKeyOrdersByIDGet
      description: |-
        Get Order by ID
    post:
      tags:
        - "projectKey"
        - "orders"
        - "ID" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_orders:{projectKey}"
      operationId: ByProjectKeyOrdersByIDPost
      description: |-
        Update Order by ID
    delete:
      tags:
        - "projectKey"
        - "orders"
        - "ID" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_orders:{projectKey}"
      operationId: ByProjectKeyOrdersByIDDelete
      description: |-
        Delete Order by ID
  /{projectKey}/payments:
    description: |-
      Payments hold information about the current state of receiving and/or refunding money
    get:
      tags:
        - "projectKey"
        - "payments" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "view_payments:{projectKey}"
      operationId: ByProjectKeyPaymentsGet
      description: |-
        Query payments
    post:
      tags:
        - "projectKey"
        - "payments" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_payments:{projectKey}"
      operationId: ByProjectKeyPaymentsPost
      description: |-
        To create a payment object a payment draft object has to be given with the request.
  /{projectKey}/payments/key={key}:
    get:
      tags:
        - "projectKey"
        - "payments"
        - "key=key" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "view_payments:{projectKey}"
      operationId: ByProjectKeyPaymentsKeyByKeyGet
      description: |-
        Get Payment by key
    post:
      tags:
        - "projectKey"
        - "payments"
        - "key=key" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_payments:{projectKey}"
      operationId: ByProjectKeyPaymentsKeyByKeyPost
      description: |-
        Update Payment by key
    delete:
      tags:
        - "projectKey"
        - "payments"
        - "key=key" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_payments:{projectKey}"
      operationId: ByProjectKeyPaymentsKeyByKeyDelete
      description: |-
        Delete Payment by key
  /{projectKey}/payments/{ID}:
    get:
      tags:
        - "projectKey"
        - "payments"
        - "ID" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "view_payments:{projectKey}"
      operationId: ByProjectKeyPaymentsByIDGet
      description: |-
        Get Payment by ID
    post:
      tags:
        - "projectKey"
        - "payments"
        - "ID" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_payments:{projectKey}"
      operationId: ByProjectKeyPaymentsByIDPost
      description: |-
        Update Payment by ID
    delete:
      tags:
        - "projectKey"
        - "payments"
        - "ID" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_payments:{projectKey}"
      operationId: ByProjectKeyPaymentsByIDDelete
      description: |-
        Delete Payment by ID
  /{projectKey}/product-discounts:
    description: |-
      Product discounts are used to change certain product prices.
    get:
      tags:
        - "projectKey"
        - "product-discounts" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "view_products:{projectKey}"
      operationId: ByProjectKeyProductDiscountsGet
      description: |-
        Query product-discounts
    post:
      tags:
        - "projectKey"
        - "product-discounts" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_products:{projectKey}"
      operationId: ByProjectKeyProductDiscountsPost
      description: |-
        Create ProductDiscount
  /{projectKey}/product-discounts/key={key}:
    get:
      tags:
        - "projectKey"
        - "product-discounts"
        - "key=key" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "view_products:{projectKey}"
      operationId: ByProjectKeyProductDiscountsKeyByKeyGet
      description: |-
        Get ProductDiscount by key
    post:
      tags:
        - "projectKey"
        - "product-discounts"
        - "key=key" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_products:{projectKey}"
      operationId: ByProjectKeyProductDiscountsKeyByKeyPost
      description: |-
        Update ProductDiscount by key
    delete:
      tags:
        - "projectKey"
        - "product-discounts"
        - "key=key" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_products:{projectKey}"
      operationId: ByProjectKeyProductDiscountsKeyByKeyDelete
      description: |-
        Delete ProductDiscount by key
  /{projectKey}/product-discounts/matching:
    post:
      tags:
        - "projectKey"
        - "product-discounts"
        - "matching" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "view_products:{projectKey}"
      operationId: ByProjectKeyProductDiscountsMatchingPost
  /{projectKey}/product-discounts/{ID}:
    get:
      tags:
        - "projectKey"
        - "product-discounts"
        - "ID" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "view_products:{projectKey}"
      operationId: ByProjectKeyProductDiscountsByIDGet
      description: |-
        Get ProductDiscount by ID
    post:
      tags:
        - "projectKey"
        - "product-discounts"
        - "ID" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_products:{projectKey}"
      operationId: ByProjectKeyProductDiscountsByIDPost
      description: |-
        Update ProductDiscount by ID
    delete:
      tags:
        - "projectKey"
        - "product-discounts"
        - "ID" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_products:{projectKey}"
      operationId: ByProjectKeyProductDiscountsByIDDelete
      description: |-
        Delete ProductDiscount by ID
  /{projectKey}/product-projections:
    description: |-
      A projected representation of a product shows the product with its current or staged data. The current or staged
      representation of a product in a catalog is called a product projection.
    get:
      tags:
        - "projectKey"
        - "product-projections" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "view_products:{projectKey}"
            - "view_published_products:{projectKey}"
      operationId: ByProjectKeyProductProjectionsGet
      description: |-
        You can use the product projections query endpoint to get the current or staged representations of Products.
        When used with an API client that has the view_published_products:{projectKey} scope,
        this endpoint only returns published (current) product projections.
  /{projectKey}/product-projections/key={key}:
    get:
      tags:
        - "projectKey"
        - "product-projections"
        - "key=key" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "view_products:{projectKey}"
            - "view_published_products:{projectKey}"
      operationId: ByProjectKeyProductProjectionsKeyByKeyGet
      description: |-
        Gets the current or staged representation of a product found by Key.
        When used with an API client that has the view_published_products:{projectKey} scope,
        this endpoint only returns published (current) product projections.
  /{projectKey}/product-projections/search:
    description: |-
      This endpoint provides high performance search queries over ProductProjections. The query result contains the
      ProductProjections for which at least one ProductVariant matches the search query. This means that variants can
      be included in the result also for which the search query does not match. To determine which ProductVariants match
      the search query, the returned ProductProjections include the additional field isMatchingVariant.
    post:
      tags:
        - "projectKey"
        - "product-projections"
        - "search" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "view_products:{projectKey}"
            - "view_published_products:{projectKey}"
      operationId: ByProjectKeyProductProjectionsSearchPost
      description: |-
        Search Product Projection
    get:
      tags:
        - "projectKey"
        - "product-projections"
        - "search" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "view_products:{projectKey}"
            - "view_published_products:{projectKey}"
      operationId: ByProjectKeyProductProjectionsSearchGet
      description: |-
        Search Product Projection
  /{projectKey}/product-projections/suggest:
    description: |-
      The source of data for suggestions is the searchKeyword field in a product
    get:
      tags:
        - "projectKey"
        - "product-projections"
        - "suggest" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "view_products:{projectKey}"
            - "view_published_products:{projectKey}"
      operationId: ByProjectKeyProductProjectionsSuggestGet
  /{projectKey}/product-projections/{ID}:
    get:
      tags:
        - "projectKey"
        - "product-projections"
        - "ID" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "view_products:{projectKey}"
            - "view_published_products:{projectKey}"
      operationId: ByProjectKeyProductProjectionsByIDGet
      description: |-
        Gets the current or staged representation of a product in a catalog by ID.
        When used with an API client that has the view_published_products:{projectKey} scope,
        this endpoint only returns published (current) product projections.
  /{projectKey}/product-types:
    description: |-
      Product Types are used to describe common characteristics, most importantly common custom attributes,
      of many concrete products.
    get:
      tags:
        - "projectKey"
        - "product-types" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "view_products:{projectKey}"
      operationId: ByProjectKeyProductTypesGet
      description: |-
        Query product-types
    post:
      tags:
        - "projectKey"
        - "product-types" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_products:{projectKey}"
      operationId: ByProjectKeyProductTypesPost
      description: |-
        Create ProductType
  /{projectKey}/product-types/key={key}:
    get:
      tags:
        - "projectKey"
        - "product-types"
        - "key=key" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "view_products:{projectKey}"
      operationId: ByProjectKeyProductTypesKeyByKeyGet
      description: |-
        Get ProductType by key
    post:
      tags:
        - "projectKey"
        - "product-types"
        - "key=key" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_products:{projectKey}"
      operationId: ByProjectKeyProductTypesKeyByKeyPost
      description: |-
        Update ProductType by key
    delete:
      tags:
        - "projectKey"
        - "product-types"
        - "key=key" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_products:{projectKey}"
      operationId: ByProjectKeyProductTypesKeyByKeyDelete
      description: |-
        Delete ProductType by key
  /{projectKey}/product-types/{ID}:
    get:
      tags:
        - "projectKey"
        - "product-types"
        - "ID" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "view_products:{projectKey}"
      operationId: ByProjectKeyProductTypesByIDGet
      description: |-
        Get ProductType by ID
    post:
      tags:
        - "projectKey"
        - "product-types"
        - "ID" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_products:{projectKey}"
      operationId: ByProjectKeyProductTypesByIDPost
      description: |-
        Update ProductType by ID
    delete:
      tags:
        - "projectKey"
        - "product-types"
        - "ID" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_products:{projectKey}"
      operationId: ByProjectKeyProductTypesByIDDelete
      description: |-
        Delete ProductType by ID
  /{projectKey}/products:
    description: |-
      Products are the sellable goods in an e-commerce project on CTP. This document explains some design concepts
      of products on CTP and describes the available HTTP APIs for working with them.
    get:
      tags:
        - "projectKey"
        - "products" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "view_products:{projectKey}"
      operationId: ByProjectKeyProductsGet
      description: |-
        You can use the query endpoint to get the full representations of products.
        REMARK: We suggest to use the performance optimized search endpoint which has a bunch functionalities,
        the query API lacks like sorting on custom attributes, etc.
    post:
      tags:
        - "projectKey"
        - "products" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_products:{projectKey}"
      operationId: ByProjectKeyProductsPost
      description: |-
        To create a new product, send a representation that is going to become the initial staged representation
        of the new product in the master catalog. If price selection query parameters are provided,
        the selected prices will be added to the response.
  /{projectKey}/products/key={key}:
    get:
      tags:
        - "projectKey"
        - "products"
        - "key=key" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "view_products:{projectKey}"
      operationId: ByProjectKeyProductsKeyByKeyGet
      description: |-
        Gets the full representation of a product by Key.
    post:
      tags:
        - "projectKey"
        - "products"
        - "key=key" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_products:{projectKey}"
      operationId: ByProjectKeyProductsKeyByKeyPost
      description: |-
        Update Product by key
    delete:
      tags:
        - "projectKey"
        - "products"
        - "key=key" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_products:{projectKey}"
      operationId: ByProjectKeyProductsKeyByKeyDelete
      description: |-
        Delete Product by key
  /{projectKey}/products/{ID}:
    get:
      tags:
        - "projectKey"
        - "products"
        - "ID" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "view_products:{projectKey}"
      operationId: ByProjectKeyProductsByIDGet
      description: |-
        Gets the full representation of a product by ID.
    post:
      tags:
        - "projectKey"
        - "products"
        - "ID" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_products:{projectKey}"
      operationId: ByProjectKeyProductsByIDPost
      description: |-
        Update Product by ID
    delete:
      tags:
        - "projectKey"
        - "products"
        - "ID" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_products:{projectKey}"
      operationId: ByProjectKeyProductsByIDDelete
      description: |-
        Delete Product by ID
  /{projectKey}/products/{ID}/images:
    post:
      tags:
        - "projectKey"
        - "products"
        - "ID"
        - "images" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_products:{projectKey}"
      operationId: ByProjectKeyProductsByIDImagesPost
      description: |-
        Uploads a binary image file to a given product variant. The supported image formats are JPEG, PNG and GIF.
  /{projectKey}/reviews:
    description: |-
      Reviews are used to evaluate products and channels.
    get:
      tags:
        - "projectKey"
        - "reviews" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "view_products:{projectKey}"
      operationId: ByProjectKeyReviewsGet
      description: |-
        Query reviews
    post:
      tags:
        - "projectKey"
        - "reviews" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_products:{projectKey}"
      operationId: ByProjectKeyReviewsPost
      description: |-
        Create Review
  /{projectKey}/reviews/key={key}:
    get:
      tags:
        - "projectKey"
        - "reviews"
        - "key=key" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "view_products:{projectKey}"
      operationId: ByProjectKeyReviewsKeyByKeyGet
      description: |-
        Get Review by key
    post:
      tags:
        - "projectKey"
        - "reviews"
        - "key=key" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_products:{projectKey}"
      operationId: ByProjectKeyReviewsKeyByKeyPost
      description: |-
        Update Review by key
    delete:
      tags:
        - "projectKey"
        - "reviews"
        - "key=key" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_products:{projectKey}"
      operationId: ByProjectKeyReviewsKeyByKeyDelete
      description: |-
        Delete Review by key
  /{projectKey}/reviews/{ID}:
    get:
      tags:
        - "projectKey"
        - "reviews"
        - "ID" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "view_products:{projectKey}"
      operationId: ByProjectKeyReviewsByIDGet
      description: |-
        Get Review by ID
    post:
      tags:
        - "projectKey"
        - "reviews"
        - "ID" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_products:{projectKey}"
      operationId: ByProjectKeyReviewsByIDPost
      description: |-
        Update Review by ID
    delete:
      tags:
        - "projectKey"
        - "reviews"
        - "ID" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_products:{projectKey}"
      operationId: ByProjectKeyReviewsByIDDelete
      description: |-
        Delete Review by ID
  /{projectKey}/shipping-methods:
    description: |-
      Shipping Methods define where orders can be shipped and what the costs are.
    get:
      tags:
        - "projectKey"
        - "shipping-methods" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "view_orders:{projectKey}"
            - "view_shipping_methods:{projectKey}"
      operationId: ByProjectKeyShippingMethodsGet
      description: |-
        Query shipping-methods
    post:
      tags:
        - "projectKey"
        - "shipping-methods" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_orders:{projectKey}"
            - "manage_shipping_methods:{projectKey}"
      operationId: ByProjectKeyShippingMethodsPost
      description: |-
        Create ShippingMethod
  /{projectKey}/shipping-methods/key={key}:
    get:
      tags:
        - "projectKey"
        - "shipping-methods"
        - "key=key" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "view_orders:{projectKey}"
            - "view_shipping_methods:{projectKey}"
      operationId: ByProjectKeyShippingMethodsKeyByKeyGet
      description: |-
        Get ShippingMethod by key
    post:
      tags:
        - "projectKey"
        - "shipping-methods"
        - "key=key" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_orders:{projectKey}"
            - "manage_shipping_methods:{projectKey}"
      operationId: ByProjectKeyShippingMethodsKeyByKeyPost
      description: |-
        Update ShippingMethod by key
    delete:
      tags:
        - "projectKey"
        - "shipping-methods"
        - "key=key" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_orders:{projectKey}"
            - "manage_shipping_methods:{projectKey}"
      operationId: ByProjectKeyShippingMethodsKeyByKeyDelete
      description: |-
        Delete ShippingMethod by key
  /{projectKey}/shipping-methods/matching-cart:
    description: |-
      Get ShippingMethods for a cart
    get:
      tags:
        - "projectKey"
        - "shipping-methods"
        - "matching-cart" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "view_orders:{projectKey}"
            - "view_shipping_methods:{projectKey}"
      operationId: ByProjectKeyShippingMethodsMatchingCartGet
  /{projectKey}/shipping-methods/matching-location:
    description: |-
      Get ShippingMethods for a location
    get:
      tags:
        - "projectKey"
        - "shipping-methods"
        - "matching-location" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "view_orders:{projectKey}"
            - "view_shipping_methods:{projectKey}"
      operationId: ByProjectKeyShippingMethodsMatchingLocationGet
  /{projectKey}/shipping-methods/matching-orderedit:
    description: |-
      Get ShippingMethods for an order edit
    get:
      tags:
        - "projectKey"
        - "shipping-methods"
        - "matching-orderedit" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "view_orders:{projectKey}"
            - "view_shipping_methods:{projectKey}"
      operationId: ByProjectKeyShippingMethodsMatchingOrdereditGet
  /{projectKey}/shipping-methods/{ID}:
    get:
      tags:
        - "projectKey"
        - "shipping-methods"
        - "ID" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "view_orders:{projectKey}"
            - "view_shipping_methods:{projectKey}"
      operationId: ByProjectKeyShippingMethodsByIDGet
      description: |-
        Get ShippingMethod by ID
    post:
      tags:
        - "projectKey"
        - "shipping-methods"
        - "ID" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_orders:{projectKey}"
            - "manage_shipping_methods:{projectKey}"
      operationId: ByProjectKeyShippingMethodsByIDPost
      description: |-
        Update ShippingMethod by ID
    delete:
      tags:
        - "projectKey"
        - "shipping-methods"
        - "ID" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_orders:{projectKey}"
            - "manage_shipping_methods:{projectKey}"
      operationId: ByProjectKeyShippingMethodsByIDDelete
      description: |-
        Delete ShippingMethod by ID
  /{projectKey}/shopping-lists:
    description: |-
      shopping-lists e.g. for wishlist support
    get:
      tags:
        - "projectKey"
        - "shopping-lists" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "view_shopping_lists:{projectKey}"
      operationId: ByProjectKeyShoppingListsGet
      description: |-
        Query shopping-lists
    post:
      tags:
        - "projectKey"
        - "shopping-lists" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_shopping_lists:{projectKey}"
      operationId: ByProjectKeyShoppingListsPost
      description: |-
        Create ShoppingList
  /{projectKey}/shopping-lists/key={key}:
    get:
      tags:
        - "projectKey"
        - "shopping-lists"
        - "key=key" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "view_shopping_lists:{projectKey}"
      operationId: ByProjectKeyShoppingListsKeyByKeyGet
      description: |-
        Gets a shopping list by Key.
    post:
      tags:
        - "projectKey"
        - "shopping-lists"
        - "key=key" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_shopping_lists:{projectKey}"
      operationId: ByProjectKeyShoppingListsKeyByKeyPost
      description: |-
        Update a shopping list found by its Key.
    delete:
      tags:
        - "projectKey"
        - "shopping-lists"
        - "key=key" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_shopping_lists:{projectKey}"
      operationId: ByProjectKeyShoppingListsKeyByKeyDelete
      description: |-
        Delete ShoppingList by key
  /{projectKey}/shopping-lists/{ID}:
    get:
      tags:
        - "projectKey"
        - "shopping-lists"
        - "ID" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "view_shopping_lists:{projectKey}"
      operationId: ByProjectKeyShoppingListsByIDGet
      description: |-
        Gets a shopping list by ID.
    post:
      tags:
        - "projectKey"
        - "shopping-lists"
        - "ID" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_shopping_lists:{projectKey}"
      operationId: ByProjectKeyShoppingListsByIDPost
      description: |-
        Update ShoppingList by ID
    delete:
      tags:
        - "projectKey"
        - "shopping-lists"
        - "ID" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_shopping_lists:{projectKey}"
      operationId: ByProjectKeyShoppingListsByIDDelete
      description: |-
        Delete ShoppingList by ID
  /{projectKey}/states:
    description: |-
      The commercetools platform allows you to model states of certain objects, such as orders, line items, products,
      reviews, and payments in order to define finite state machines reflecting the business logic you'd like to
      implement.
    get:
      tags:
        - "projectKey"
        - "states" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "view_states:{projectKey}"
      operationId: ByProjectKeyStatesGet
      description: |-
        Query states
    post:
      tags:
        - "projectKey"
        - "states" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_states:{projectKey}"
      operationId: ByProjectKeyStatesPost
      description: |-
        Create State
  /{projectKey}/states/key={key}:
    get:
      tags:
        - "projectKey"
        - "states"
        - "key=key" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "view_states:{projectKey}"
      operationId: ByProjectKeyStatesKeyByKeyGet
      description: |-
        Get State by key
    post:
      tags:
        - "projectKey"
        - "states"
        - "key=key" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_states:{projectKey}"
      operationId: ByProjectKeyStatesKeyByKeyPost
      description: |-
        Update State by key
    delete:
      tags:
        - "projectKey"
        - "states"
        - "key=key" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_states:{projectKey}"
      operationId: ByProjectKeyStatesKeyByKeyDelete
      description: |-
        Delete State by key
  /{projectKey}/states/{ID}:
    get:
      tags:
        - "projectKey"
        - "states"
        - "ID" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "view_states:{projectKey}"
      operationId: ByProjectKeyStatesByIDGet
      description: |-
        Get State by ID
    post:
      tags:
        - "projectKey"
        - "states"
        - "ID" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_states:{projectKey}"
      operationId: ByProjectKeyStatesByIDPost
      description: |-
        Update State by ID
    delete:
      tags:
        - "projectKey"
        - "states"
        - "ID" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_states:{projectKey}"
      operationId: ByProjectKeyStatesByIDDelete
      description: |-
        Delete State by ID
  /{projectKey}/stores:
    description: |-
      Stores let you model the context your customers shop in.
    get:
      tags:
        - "projectKey"
        - "stores" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "view_stores:{projectKey}"
      operationId: ByProjectKeyStoresGet
      description: |-
        Query stores
    post:
      tags:
        - "projectKey"
        - "stores" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_stores:{projectKey}"
      operationId: ByProjectKeyStoresPost
      description: |-
        Create Store
  /{projectKey}/stores/key={key}:
    get:
      tags:
        - "projectKey"
        - "stores"
        - "key=key" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "view_stores:{projectKey}"
      operationId: ByProjectKeyStoresKeyByKeyGet
      description: |-
        Get Store by key
    post:
      tags:
        - "projectKey"
        - "stores"
        - "key=key" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_stores:{projectKey}"
      operationId: ByProjectKeyStoresKeyByKeyPost
      description: |-
        Update Store by key
    delete:
      tags:
        - "projectKey"
        - "stores"
        - "key=key" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_stores:{projectKey}"
      operationId: ByProjectKeyStoresKeyByKeyDelete
      description: |-
        Delete Store by key
  /{projectKey}/stores/{ID}:
    get:
      tags:
        - "projectKey"
        - "stores"
        - "ID" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "view_stores:{projectKey}"
      operationId: ByProjectKeyStoresByIDGet
      description: |-
        Get Store by ID
    post:
      tags:
        - "projectKey"
        - "stores"
        - "ID" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_stores:{projectKey}"
      operationId: ByProjectKeyStoresByIDPost
      description: |-
        Update Store by ID
    delete:
      tags:
        - "projectKey"
        - "stores"
        - "ID" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_stores:{projectKey}"
      operationId: ByProjectKeyStoresByIDDelete
      description: |-
        Delete Store by ID
  /{projectKey}/subscriptions:
    description: |-
      Subscriptions allow you to be notified of new messages or changes via a Message Queue of your choice
    get:
      tags:
        - "projectKey"
        - "subscriptions" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_subscriptions:{projectKey}"
      operationId: ByProjectKeySubscriptionsGet
      description: |-
        Query subscriptions
    post:
      tags:
        - "projectKey"
        - "subscriptions" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_subscriptions:{projectKey}"
      operationId: ByProjectKeySubscriptionsPost
      description: |-
        The creation of a Subscription is eventually consistent, it may take up to a minute before it becomes fully active.
        In order to test that the destination is correctly configured, a test message will be put into the queue.
        If the message could not be delivered, the subscription will not be created.
        The payload of the test message is a notification of type ResourceCreated for the resourceTypeId subscription.
        Currently, a maximum of 25 subscriptions can be created per project.
  /{projectKey}/subscriptions/key={key}:
    get:
      tags:
        - "projectKey"
        - "subscriptions"
        - "key=key" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_subscriptions:{projectKey}"
      operationId: ByProjectKeySubscriptionsKeyByKeyGet
      description: |-
        Retrieves the representation of a subscription by its key.
    post:
      tags:
        - "projectKey"
        - "subscriptions"
        - "key=key" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_subscriptions:{projectKey}"
      operationId: ByProjectKeySubscriptionsKeyByKeyPost
      description: |-
        Update Subscription by key
    delete:
      tags:
        - "projectKey"
        - "subscriptions"
        - "key=key" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_subscriptions:{projectKey}"
      operationId: ByProjectKeySubscriptionsKeyByKeyDelete
      description: |-
        Delete Subscription by key
  /{projectKey}/subscriptions/{ID}:
    get:
      tags:
        - "projectKey"
        - "subscriptions"
        - "ID" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_subscriptions:{projectKey}"
      operationId: ByProjectKeySubscriptionsByIDGet
      description: |-
        Retrieves the representation of a subscription by its id.
    post:
      tags:
        - "projectKey"
        - "subscriptions"
        - "ID" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_subscriptions:{projectKey}"
      operationId: ByProjectKeySubscriptionsByIDPost
      description: |-
        Update Subscription by ID
    delete:
      tags:
        - "projectKey"
        - "subscriptions"
        - "ID" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_subscriptions:{projectKey}"
      operationId: ByProjectKeySubscriptionsByIDDelete
      description: |-
        Delete Subscription by ID
  /{projectKey}/tax-categories:
    description: |-
      Tax Categories define how products are to be taxed in different countries.
    get:
      tags:
        - "projectKey"
        - "tax-categories" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "view_products:{projectKey}"
            - "view_tax_categories:{projectKey}"
      operationId: ByProjectKeyTaxCategoriesGet
      description: |-
        Query tax-categories
    post:
      tags:
        - "projectKey"
        - "tax-categories" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_products:{projectKey}"
            - "manage_tax_categories:{projectKey}"
      operationId: ByProjectKeyTaxCategoriesPost
      description: |-
        Create TaxCategory
  /{projectKey}/tax-categories/key={key}:
    get:
      tags:
        - "projectKey"
        - "tax-categories"
        - "key=key" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "view_products:{projectKey}"
            - "view_tax_categories:{projectKey}"
      operationId: ByProjectKeyTaxCategoriesKeyByKeyGet
      description: |-
        Get TaxCategory by key
    post:
      tags:
        - "projectKey"
        - "tax-categories"
        - "key=key" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_products:{projectKey}"
            - "manage_tax_categories:{projectKey}"
      operationId: ByProjectKeyTaxCategoriesKeyByKeyPost
      description: |-
        Update TaxCategory by key
    delete:
      tags:
        - "projectKey"
        - "tax-categories"
        - "key=key" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_products:{projectKey}"
            - "manage_tax_categories:{projectKey}"
      operationId: ByProjectKeyTaxCategoriesKeyByKeyDelete
      description: |-
        Delete TaxCategory by key
  /{projectKey}/tax-categories/{ID}:
    get:
      tags:
        - "projectKey"
        - "tax-categories"
        - "ID" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "view_products:{projectKey}"
            - "view_tax_categories:{projectKey}"
      operationId: ByProjectKeyTaxCategoriesByIDGet
      description: |-
        Get TaxCategory by ID
    post:
      tags:
        - "projectKey"
        - "tax-categories"
        - "ID" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_products:{projectKey}"
            - "manage_tax_categories:{projectKey}"
      operationId: ByProjectKeyTaxCategoriesByIDPost
      description: |-
        Update TaxCategory by ID
    delete:
      tags:
        - "projectKey"
        - "tax-categories"
        - "ID" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_products:{projectKey}"
            - "manage_tax_categories:{projectKey}"
      operationId: ByProjectKeyTaxCategoriesByIDDelete
      description: |-
        Delete TaxCategory by ID
  /{projectKey}/types:
    description: |-
      Types define custom fields that are used to enhance resources as you need.
    get:
      tags:
        - "projectKey"
        - "types" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "view_types:{projectKey}"
      operationId: ByProjectKeyTypesGet
      description: |-
        Query types
    post:
      tags:
        - "projectKey"
        - "types" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_types:{projectKey}"
      operationId: ByProjectKeyTypesPost
      description: |-
        Create Type
  /{projectKey}/types/key={key}:
    get:
      tags:
        - "projectKey"
        - "types"
        - "key=key" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "view_types:{projectKey}"
      operationId: ByProjectKeyTypesKeyByKeyGet
      description: |-
        Get Type by key
    post:
      tags:
        - "projectKey"
        - "types"
        - "key=key" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_types:{projectKey}"
      operationId: ByProjectKeyTypesKeyByKeyPost
      description: |-
        Update Type by key
    delete:
      tags:
        - "projectKey"
        - "types"
        - "key=key" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_types:{projectKey}"
      operationId: ByProjectKeyTypesKeyByKeyDelete
      description: |-
        Delete Type by key
  /{projectKey}/types/{ID}:
    get:
      tags:
        - "projectKey"
        - "types"
        - "ID" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "view_types:{projectKey}"
      operationId: ByProjectKeyTypesByIDGet
      description: |-
        Get Type by ID
    post:
      tags:
        - "projectKey"
        - "types"
        - "ID" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_types:{projectKey}"
      operationId: ByProjectKeyTypesByIDPost
      description: |-
        Update Type by ID
    delete:
      tags:
        - "projectKey"
        - "types"
        - "ID" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_types:{projectKey}"
      operationId: ByProjectKeyTypesByIDDelete
      description: |-
        Delete Type by ID
  /{projectKey}/zones:
    description: |-
      Zones allow defining ShippingRates for specific Locations.
    get:
      tags:
        - "projectKey"
        - "zones" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "view_orders:{projectKey}"
      operationId: ByProjectKeyZonesGet
      description: |-
        Query zones
    post:
      tags:
        - "projectKey"
        - "zones" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_orders:{projectKey}"
      operationId: ByProjectKeyZonesPost
      description: |-
        Create Zone
  /{projectKey}/zones/key={key}:
    get:
      tags:
        - "projectKey"
        - "zones"
        - "key=key" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "view_orders:{projectKey}"
      operationId: ByProjectKeyZonesKeyByKeyGet
      description: |-
        Get Zone by key
    post:
      tags:
        - "projectKey"
        - "zones"
        - "key=key" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_orders:{projectKey}"
      operationId: ByProjectKeyZonesKeyByKeyPost
      description: |-
        Update Zone by key
    delete:
      tags:
        - "projectKey"
        - "zones"
        - "key=key" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_orders:{projectKey}"
      operationId: ByProjectKeyZonesKeyByKeyDelete
      description: |-
        Delete Zone by key
  /{projectKey}/zones/{ID}:
    get:
      tags:
        - "projectKey"
        - "zones"
        - "ID" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "view_orders:{projectKey}"
      operationId: ByProjectKeyZonesByIDGet
      description: |-
        Get Zone by ID
    post:
      tags:
        - "projectKey"
        - "zones"
        - "ID" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_orders:{projectKey}"
      operationId: ByProjectKeyZonesByIDPost
      description: |-
        Update Zone by ID
    delete:
      tags:
        - "projectKey"
        - "zones"
        - "ID" 
      security:
        - oauth_2_0:
            - "manage_project:{projectKey}"
            - "manage_orders:{projectKey}"
      operationId: ByProjectKeyZonesByIDDelete
      description: |-
        Delete Zone by ID
components:
  securitySchemes:
    oauth_2_0:
      type: oauth2
      flows:
          clientCredentials:
            tokenUrl: https://auth.europe-west1.gcp.commercetools.com/oauth/token
            scopes:
              "manage_project:{projectKey}": ""
              "manage_products:{projectKey}": ""
              "view_products:{projectKey}": ""
              "manage_orders:{projectKey}": ""
              "manage_orders:{projectKey}:{storeKey}": ""
              "view_orders:{projectKey}": ""
              "view_orders:{projectKey}:{storeKey}": ""
              "manage_customers:{projectKey}": ""
              "view_customers:{projectKey}": ""
              "manage_payments:{projectKey}": ""
              "view_payments:{projectKey}": ""
              "manage_subscriptions:{projectKey}": ""
              "manage_extensions:{projectKey}": ""
              "manage_types:{projectKey}": ""
              "view_types:{projectKey}": ""
              "view_shopping_lists:{projectKey}": ""
              "manage_shopping_lists:{projectKey}": ""
              "manage_my_orders:{projectKey}": ""
              "manage_my_orders:{projectKey}:{storeKey}": ""
              "manage_my_profile:{projectKey}": ""
              "view_project_settings:{projectKey}": ""
              "view_published_products:{projectKey}": ""
              "manage_cart_discounts:{projectKey}": ""
              "view_cart_discounts:{projectKey}": ""
              "manage_customer_groups:{projectKey}": ""
              "view_customer_groups:{projectKey}": ""
              "view_shipping_methods:{projectKey}": ""
              "manage_shipping_methods:{projectKey}": ""
              "manage_tax_categories:{projectKey}": ""
              "view_tax_categories:{projectKey}": ""
              "manage_categories:{projectKey}": ""
              "view_categories:{projectKey}": ""
