#%RAML 1.0 DataType
(annotations.package): responses
type: ResponseMessage
displayName: AdyenTimeout
discriminatorValue: adyen_timeout
description: |
  Generated when a timeout error occurs while initializing the Adyen payment connector.
properties:
  code:
    type: string
    description:
  type:
    type: string
    description: \`error:psp:bad_config`
  message:
    type: string
    description: Timeout while initialising Adyen.
  payload?:
    type: object
    description: An object containing `psp`, `clientKey`, and `enviroment`.
