#%RAML 1.0 DataType
(annotations.package): responses
type: ResponseMessage
displayName: BadInputData
discriminatorValue: invalid_fields
description: |
  Generated when the [Checkout properties](/sdk#configuration-properties) contains invalid fields.
properties:
  code:
    type: string
    description:
  severity:
    type: string
    description: \`error`
  message:
    type: string
    description: Some fields are invalid.
  payload:
    type: object
    description: Contains the `invalidFields` array of objects with the related `schema`, `path`, `value` and `message` properties.
