#%RAML 1.0 DataType
(annotations.package): responses
type: ResponseMessage
displayName: CartWithExistingPayment
discriminatorValue: cart_with_exisiting_payment
description: |
  Generated when trying to add a [Payment](/../api/projects/payments) to a [Cart](/../api/projects/carts) that already references an approved Payment.
properties:
  code:
    type: string
    description:
  type:
    type: string
    description: \`error:payment:failed`
  message:
    type: string
    description: Cart with existing approved payment.
  payload?:
    type: object
    description: An object containing `cartId`.
