#%RAML 1.0 DataType
(package): responses
type: ResponseMessage
displayName: CartEmptiedDuringCheckout
discriminatorValue: cart_emptied_during_checkout
description: |
  Generated when the Cart was emptied during the checkout. It is not possible to recover from this, the customer must restart the checkout process.
properties:
  code:
    type: string
    description:
  type:
    type: string
    description: \`error:cart:empty`
  message:
    type: string
    description: Cart `{cartId}` was emptied during checkout
  payload?:
    type: object
    description: An object containing `cartId`.
