#%RAML 1.0 DataType
(annotations.package): responses
type: ResponseMessage
displayName: CheckoutCompleted
discriminatorValue: checkout_completed
description: |
  Generated when the customer completes the checkout process.
properties:
  code:
    type: string
    description:
  severity:
    type: string
    description: \`info`
  message:
    type: string
    description: Checkout for `{orderId}` completed.
  payload:
    type: object
    description: Contains the `order` object with the `id` property.
  correlationId:
    type: string
    description: Unique identifier of the event.
