#%RAML 1.0 DataType
(annotations.package): responses
type: ResponseMessage
displayName: DiscountCodeNotApplicable
discriminatorValue: discount_code_not_applicable
description: |
  Generated when the [Discount Code](/../api/projects/discountCodes) is not applicable for the current Cart.
properties:
  code:
    type: string
    description:
  severity:
    type: string
    description: \`info`
  message:
    type: string
    description: Discount code not applicable.
  correlationId:
    type: string
    description: Unique identifier of the event.
  payload:
    type: object
    description: Contains the `cartId` and `discountCode` properties.
