#%RAML 1.0 DataType
(annotations.package): responses
type: ResponseMessage
displayName: ExpressPaymentIntegrationNotAvailable
discriminatorValue: express_payment_integration_not_available
description: |
  Generated when a requested Express Payments integration is not available. This can happen when using `mountMethod()` with a payment method that is not configured or not available for the current session.
properties:
  code:
    type: string
    description:
  severity:
    type: string
    description: \`warn`
  message:
    type: string
    description: Express Payments integration not available.
  payload:
    type: object
    description: Contains the `integration` object with the `type` property indicating the requested payment integration type, and `availableMethods` array listing the available payment methods.
  correlationId:
    type: string
    description: Unique identifier of the event.
