#%RAML 1.0 DataType
(annotations.package): responses
type: Message
displayName: FailedToRefreshSession
discriminatorValue: failed_to_refresh_session
description: |
  Generated when the [Checkout Session](/installing-checkout#create-checkout-sessions) fails to refresh.
properties:
  code:
    type: string
    description:
  severity:
    type: string
    description: \`error`
  message:
    type: string
    description: Failed to refresh session.
  correlationId:
    type: string
    description: Unique identifier of the event.
