#%RAML 1.0 DataType
(annotations.package): responses
type: Message
displayName: GiftCardRedeemStarted
discriminatorValue: gift_card_redeem_started
description: |
  Generated when the customer confirms the payment by gift card and Checkout initiates the redemption of the gift card's balance.
properties:
  code:
    type: string
    description:
  severity:
    type: string
    description: \`info`
  message:
    type: string
    description: Gift card redeem started.
  correlationId:
    type: string
    description: Unique identifier of the event.
