#%RAML 1.0 DataType
(package): responses
type: ResponseMessage
displayName: InitTimeout
discriminatorValue: init_timeout
description: |
  Generated when the checkout has not received the configuration parameters passed through the `checkoutConfig` object on time.
properties:
  code:
    type: string
    description:
  type:
    type: string
    description: \`error:init:timeout`
  message:
    type: string
    description: Timeout error, no init message received
