#%RAML 1.0 DataType
(annotations.package): responses
type: Message
displayName: InvalidMode
discriminatorValue: invalid_mode
description: |
  Generated when the Application does not support the requested Checkout [mode](/../checkout/overview#complete-checkout-and-payment-only-modes).
properties:
  code:
    type: string
    description:
  severity:
    type: string
    description: \`info`
  message:
    type: string
    description: \`{mode}` mode requires an application with mode type `{modeTypeRequested}`. Current mode `{modeTypeReceived}`.
