#%RAML 1.0 DataType
(annotations.package): responses
type: object
displayName: Message
discriminator: code
description:
properties:
  code:
    description: The Message code for the event.
    type: string
  severity:
    description: |
      The severity level of the event. It can be `info`, `warn`, or `error`.
    type: string
  message:
    description: |
      A human-readable description of the event.
    type: string
