#%RAML 1.0 DataType
(annotations.package): responses
type: object
displayName: Message
discriminator: code
description:
properties:
  code:
    description: Message code for the event.
    type: string
  severity:
    description: |
      Severity level of the event. Can be `info`, `warn`, or `error`.
    type: string
  message:
    description: |
      Human-readable description of the event.
    type: string
  correlationId:
    type: string
    description: Unique identifier of the event.
