#%RAML 1.0 DataType
(annotations.package): responses
type: ResponseMessage
displayName: NoPaymentMethods
discriminatorValue: no_payment_methods
description: |
  Generated when there are no payment methods available. Add at least one **Payment method** in your [application settings in the Merchant Center](/configuring-checkout#payment-connector).
properties:
  code:
    type: string
    description:
  type:
    type: string
    description: \`error:init:bad_config`
  message:
    type: string
    description: There are no payment methods configured
