#%RAML 1.0 DataType
(annotations.package): responses
type: ResponseMessage
displayName: NotApplicableDiscountCodeRemoved
discriminatorValue: not_applicable_discount_code_removed
description: |
  Generated when using the `paymentFlow` [method](/../checkout/browser-sdk#paymentflow-method) and Checkout removes a [Discount Code](/../api/projects/discountCodes) from the Cart because it does not apply to the Cart. Checkout removes the Discount Code to avoid an order creation error when converting the Cart to an Order.
properties:
  code:
    type: string
    description:
  severity:
    type: string
    description: \`warn`
  message:
    type: string
    description: Not applicable discount code removed.
  correlationId:
    type: string
    description: Unique identifier of the event.
  payload:
    type: object
    description: Contains the `cartId` and `discountCode` properties.
