#%RAML 1.0 DataType
(annotations.package): responses
type: Message
displayName: OrderVerificationTimeout
discriminatorValue: order_verification_timeout
description: |
  Generated when the verification of the [Order](/../api/projects/orders) times out.
properties:
  code:
    type: string
    description:
  severity:
    type: string
    description: \`error`
  message:
    type: string
    description: Order verification timeout.
  correlationId:
    type: string
    description: Unique identifier of the event.
