#%RAML 1.0 DataType
(annotations.package): responses
type: Message
displayName: OrderVerificationStarted
discriminatorValue: order_verification_started
description: |
  Generated when Checkout starts verifying the [Order](/../api/projects/orders).
properties:
  code:
    type: string
    description:
  severity:
    type: string
    description: \`info`
  message:
    type: string
    description: Order verification started.
  correlationId:
    type: string
    description: Unique identifier of the event.
