#%RAML 1.0 DataType
(annotations.package): responses
type: ResponseMessage
displayName: PaymentMethodSelectionConfirmation
discriminatorValue: payment_method_selection_confirmation
description: |
  Generated when the customer has entered the payment method information and moves to the next step.
properties:
  code:
    type: string
    description:
  severity:
    type: string
    description: \`info`
  message:
    type: string
    description: Payment method selected.
  correlationId:
    type: string
    description: Unique identifier of the event.
  payload:
    type: object
    description: Contains the `method` object with the `type` and `hasVendorButton` properties.
