#%RAML 1.0 DataType
(annotations.package): responses
type: ResponseMessage
displayName: PaymentIntegrationLoading
discriminatorValue: payment_integration_loading
description: |
  Generated when the selected payment integration is loading.
properties:
  code:
    type: string
    description:
  severity:
    type: string
    description: \`info`
  message:
    type: string
    description: Payment integration loading.
  correlationId:
    type: string
    description: Unique identifier of the event.
  payload:
    type: object
    description: Contains the `integration` object with the `type` and `connectorId` properties.
