#%RAML 1.0 DataType
(annotations.package): responses
type: ResponseMessage
displayName: PaymentMethodNotAvailable
discriminatorValue: payment_method_not_available
description: |
  Generated when there is an error with the selected payment method and the payment method is unavailable.
properties:
  code:
    type: string
    description:
  severity:
    type: string
    description: \`warn`
  message:
    type: string
    description: Payment method not available.
  correlationId:
    type: string
    description: Unique identifier of the event.
  payload:
    type: object
    description: Contains the `method` object with the `type`, `id`, and `connectorId` properties.
