#%RAML 1.0 DataType
(annotations.package): responses
type: ResponseMessage
displayName: PaymentConnectorError
discriminatorValue: payment_connector_error
description: |
  Generated when the [payment Connector](/../checkout/connectors-and-applications#payment-connectors) triggers an error.
properties:
  code:
    type: string
    description:
  severity:
    type: string
    description: \`error`
  message:
    type: string
    description: Payment connector error.
  correlationId:
    type: string
    description: Unique identifier of the event.
  payload:
    type: object
    description: Contains the `connector` object with the `id` property.
