#%RAML 1.0 DataType
(annotations.package): responses
type: Message
displayName: PaymentVerificationStarted
discriminatorValue: payment_verification_started
description: |
  Generated when Checkout starts verifying the payment [authorization](/payments-lifecycle#authorization) given by the payment service provider (PSP).
properties:
  code:
    type: string
    description:
  severity:
    type: string
    description: \`info`
  message:
    type: string
    description: Payment verification started.
  correlationId:
    type: string
    description: Unique identifier of the event.
