#%RAML 1.0 DataType
(annotations.package): responses
type: ResponseMessage
displayName: PaymentIntegrationsReceived
discriminatorValue: payment_integrations_received
description: |
  Generated when Checkout receives and loads the payment integrations configured for the Application.
properties:
  code:
    type: string
    description:
  severity:
    type: string
    description: \`info`
  message:
    type: string
    description: Payment integrations received.
  correlationId:
    type: string
    description: Unique identifier of the event.
  payload:
    type: object
    description: Contains the `paymentIntegrations` array of objects with the `type` and `connectorId` properties.
