#%RAML 1.0 DataType
(annotations.package): responses
type: Message
displayName: PaymentValidationPassed
discriminatorValue: payment_validation_passed
description: |
  Generated when Checkout and the payment service provider (PSP) validate the payment information entered by the customer.
properties:
  code:
    type: string
    description:
  severity:
    type: string
    description: \`info`
  message:
    type: string
    description: Payment validation passed.
