#%RAML 1.0 DataType
(annotations.package): responses
type: Message
displayName: PermissionsNotFound
discriminatorValue: no_permissions_found
description: |
  Generated when no [permissions](/permissions-subscription) to create a Composable Commerce API Client are found. To create permissions, in the Merchant Center navigation menu, go to any page under **commercetools Checkout** and click **Confirm creation**.
properties:
  code:
    type: string
    description:
  severity:
    type: string
    description: \`warn`
  message:
    type: string
    description: No permissions are found in your commercetools Checkout.
