#%RAML 1.0 DataType
(annotations.package): responses
type: ResponseMessage
displayName: RemoveDiscountCodeError
discriminatorValue: remove_discount_code_error
description: |
  Generated when there was an error removing the Discount Code.
properties:
  code:
    type: string
    description:
  severity:
    type: string
    description: \`error`
  message:
    type: string
    description: Error removing discount code.
  payload:
    type: object
    description: Contains the `error` object.
