#%RAML 1.0 DataType
(annotations.package): responses
type: ResponseMessage
displayName: UnsupportedCountry
discriminatorValue: unsupported_country
description: |
  Generated when the country of the shipping address and/or billing address associated with the [Cart](/../api/projects/carts) does not match the countries set for the [Application](/payment-connectors-applications#applications).
properties:
  code:
    type: string
    description:
  severity:
    type: string
    description: \`error`
  message:
    type: string
    description: Cart `{cartId}` has unsupported country.
  payload:
    type: object
    description: Contains the `cart` object with the `id` property, `shippingCountry`, `billingCountry`, and the `supportedCountries` array.
