#%RAML 1.0 DataType
(annotations.package): Error
type: ErrorObject
displayName: ConnectorSpecificationFileNotFoundError
discriminatorValue: ConnectorSpecificationFileNotFound
description: |
  Returned when the Connector specification file was not found.
properties:
  code:
    type: string
  message:
    type: string
    description: |
      `"The file connect.yaml at $url with the tag $tag was not found"`
