#%RAML 1.0 DataType
(annotations.package): error
type: ErrorObject
displayName: DeploymentLogInvalidDateError
discriminatorValue: DeploymentLogInvalidDate
description: |
  Returned when trying to get a log with invalid start date or end date.
properties:
  code:
    type: string
  message:
    type: string
    description: |
      `"Invalid start/end date"`
