#%RAML 1.0 DataType
(annotations.package): error
type: ErrorObject
displayName: DeploymentProductionDeactivatedError
discriminatorValue: DeploymentProductionDeactivated
description: |
  Returned as a failed response to the [Create a Deployment](ctp:connect:endpoint:/{projectKey}/deployments:POST) request when deployments to production are disabled for the Project.
properties:
  code:
    type: string
  message:
    type: string
    description: |
      `"Deployments to production are disabled for this Project. Please contact support to enable production deployments."`
