#%RAML 1.0 DataType
(annotations.package): error
type: ErrorObject
displayName: GeneralError
discriminatorValue: General
description: |
  Returned when a server-side problem occurs.

  If you encounter this error, report it using the [Support Portal](TBC for connect).
properties:
  code:
    type: string
  message:
    type: string
    description: |
      Description about any known details of the problem, for example, `"Write operations are temporarily unavailable"`.
