#%RAML 1.0 DataType
(package): ApiClient
(docs-uri): https://docs.commercetools.com/http-api-projects-apiClients.html#apiclient

displayName: ApiClient

type: object
properties:
  id:
    type: string
  name:
    type: string
  scope:
    type: string
  createdAt?:
    type: datetime
  lastUsedAt?:
    type: date-only
  deleteAt?:
    type: datetime
  secret?:
    type: string
