#%RAML 1.0 DataType
(package): Order
displayName: Hit
type: object
properties:
  id:
    (identifier): true
    type: string
    description: Platform-generated unique identifier of the Order.
  version:
    type: number
    format: int64
    description: Current version of the Order.
  relevance:
    type: number
    minimum: 0.0
    maximum: 1.0
    format: float
    description: The higher the value is, the more relevant the hit is for the search request.
