#%RAML 1.0 DataType
(package): Order
type: object
displayName: OrderSearchQueryExpressionValue
properties:
  field:
    type: string
  boost?:
    type: number
    format: int32
  customType?:
    type: string
