#%RAML 1.0 DataType
(package): Project
type: object
displayName: BusinessUnitConfiguration
properties:
  myBusinessUnitStatusOnCreation:
    type: BusinessUnitConfigurationStatus
    description: Status of Business Units created using the [My Business Unit endpoint](/../api/projects/me-business-units#create-businessunit).
