#%RAML 1.0 DataType
(package): Project
type: string
(beta): true
displayName: BusinessUnitSearchStatus
description: |
  Specifies the status of the [Business Unit Search](/../api/projects/business-unit-search) index.
  You can change the status using the [Change Business Unit Search Status](ctp:api:type:ProjectChangeBusinessUnitSearchStatusAction) update action.
(enumDescriptions):
  Activated: indicates that the Business Unit Search feature is fully operational.
  Deactivated: indicates that the Business Unit Search feature is currently not active.
enum:
  - Activated
  - Deactivated
