#%RAML 1.0 DataType
(package): Project
displayName: CartClassificationType
type: ShippingRateInputType
example: !include ../../examples/Project/ProjectShippingRateInputTypeCartClassification.json
discriminatorValue: CartClassification
description: |
  The [ShippingRate](ctp:api:type:ShippingRate) maps to an abstract Cart categorization expressed by strings (for example, `Light`, `Medium`, or `Heavy`).
  Only keys defined in the `values` array can be used to create a tier or to set a value of the `shippingRateInput` on the [Cart](ctp:api:type:Cart).
  Keys must be unique.
properties:
  values:
    type: array
    items: CustomFieldLocalizedEnumValue
    description: The classification items that can be used for specifying any [ShippingRatePriceTier](ctp:api:type:ShippingRatePriceTier).
