#%RAML 1.0 DataType
(package): Project
type: string
displayName: DiscountCombinationMode
description: |
  Defines how Product Discounts and Cart Discounts are combined for every Cart in a Project.
(enumDescriptions):
  BestDeal: Either Product Discounts or Cart Discounts are chosen based on best deal for the customer. Only one type applies per Cart.
  Stacking: Product Discounts and Cart Discounts are both applied to the Cart, potentially increasing the total discount.
enum:
  - BestDeal
  - Stacking
