#%RAML 1.0 DataType
(package): Project
type: string
displayName: DiscountCombinationMode
description: |
  Defines how Product Discounts and Cart Discounts are combined for Line Items in every Cart of the Project.
(enumDescriptions):
  BestDeal: Either Product Discounts or Cart Discounts are chosen for each Line Item in the Cart based on the best deal for the Customer. Only one discount type applies per Line Item in the Cart.
  Stacking: Product Discounts and Cart Discounts are both applied to each Line Item in the Cart, potentially increasing the total discount.
enum:
  - BestDeal
  - Stacking
