#%RAML 1.0 DataType
(package): Project
type: object
displayName: ExternalOAuth
example: !include ../../examples/Project/ExternalOAuth.json
description: |
  Represents an RFC 7662-compliant [OAuth 2.0 Token Introspection](https://datatracker.ietf.org/doc/html/rfc7662) endpoint.
  For more information, see [Requesting an access token using an external OAuth 2.0 server](/api/authorization#request-an-access-token-using-an-external-oauth-server).

  You can only configure **one** external OAuth 2.0 endpoint per Project.
  To authenticate using multiple external services (such as social network logins), use a middle layer authentication service that delegates to those services and exposes a single RFC 7662-compliant OAuth 2.0 Token Introspection endpoint to the commercetools APIs.
  This middle layer is a custom service that you build and host.
  It receives the token introspection request from the APIs, routes the token validation to the appropriate external service, and returns the introspection response in the expected format.
properties:
  url:
    type: string
    description: |
      URL with authorization header.
  authorizationHeader:
    type: string
    description: Must not contain any leading or trailing whitespaces. Partially hidden on retrieval.
    pattern: '^[^ ].+[^ ]$'
