#%RAML 1.0 DataType
(package): Project
type: object
displayName: ExternalOAuth
example: !include ../../examples/Project/ExternalOAuth.json
description: |
  Represents a RFC 7662 compliant [OAuth 2.0 Token Introspection](https://datatracker.ietf.org/doc/html/rfc7662) endpoint. For more information, see [Requesting an access token using an external OAuth 2.0 server](/../api/authorization#request-an-access-token-using-an-external-oauth-server).

  You can only configure **one** external OAuth 2.0 endpoint per Project. To authenticate using multiple external services (such as social network logins), use a middle layer authentication service.
properties:
  url:
    type: string
    description: |
      URL with authorization header.
  authorizationHeader:
    type: string
    description: Must not contain any leading or trailing whitespaces. Partially hidden on retrieval.
    pattern: '^[^ ].+[^ ]$'
