#%RAML 1.0 DataType
(package): Project
type: string
(beta): true
displayName: OrderSearchStatus
description: Specifies the status of the [Order Search](/../api/projects/order-search) index.
(enumDescriptions):
  Activated: indicates that the [Search Orders](/../api/projects/order-search#search-orders) endpoint is fully operational.
  Deactivated: indicates that the Order Search feature is currently not active, but can be activated by [update action](#change-order-search-status).
enum:
  - Activated
  - Deactivated
