#%RAML 1.0 DataType
(package): Project
displayName: ProductSearchIndexingMode
type: string
enum:
  - ProductProjectionsSearch
  - ProductsSearch
(enumDescriptions):
  ProductProjectionsSearch: |
    For [Product Projection Search](/../api/projects/product-projection-search).
  ProductsSearch: |
    For [Product Search](/../api/projects/product-search).
