#%RAML 1.0 DataType
(package): Project
type: object
displayName: SearchIndexingConfigurationValues
properties:
  status?:
    type: SearchIndexingConfigurationStatus
  lastModifiedAt?:
    type: datetime
  lastModifiedBy?:
    type: LastModifiedBy
