#%RAML 1.0 DataType
(package): Project
type: object
displayName: SearchIndexingConfigurationValues
example: !include ../../examples/Project/SearchIndexingConfigurationValues.json
properties:
  status?:
    type: SearchIndexingConfigurationStatus
    description: Current status of resource indexing. Present on Projects from 1 February 2019.
  lastModifiedAt?:
    type: datetime
    description: |
      Date and time (UTC) the Project was last updated. Only present on Projects last modified after 1 February 2019.
  lastModifiedBy?:
    (beta): true
    type: LastModifiedBy
    description: |
      IDs and references that last modified the SearchIndexingConfigurationValues.
