#%RAML 1.0 DataType
(package): Project
type: object
displayName: SearchIndexingConfiguration
description: |
  Controls indexing of resources to be provided on high performance read-only search endpoints.
properties:
  products?:
    type: SearchIndexingConfigurationValues
    description: Configuration for the [Product Projection Search](/../api/projects/products-search) and [Product Suggestions](/../api/projects/products-suggestions) endpoints.
  productsSearch?:
    type: SearchIndexingConfigurationValues
    description: Configuration for the [Product Search](/../api/projects/product-search) feature.
  orders?:
    type: SearchIndexingConfigurationValues
    (beta): true
    description: Configuration for the [Order Search](/../api/projects/order-search) feature.
  customers?:
    type: SearchIndexingConfigurationValues
    description: Configuration for the [Customer Search](/../api/projects/customer-search) feature.
  businessUnits?:
    type: SearchIndexingConfigurationValues
    (beta): true
    description: Configuration for the [Business Unit Search](/../api/projects/business-unit-search) feature.
