#%RAML 1.0 SecurityScheme

description: |
  HTTP API authorization uses [OAuth2](http://tools.ietf.org/html/rfc6750){:target="_blank"}.

  Clients must obtain an access token from the auth service using one of
  the authorization flows described below, before they are able to make authorized requests
  to other commercetools services. On successful completion of an authorization flow,
  a client will be given an `access_token`, which they need to include in requests
  to authorized service endpoints via the HTTP `Authorization` header like this:
type: OAuth 2.0
describedBy:
  headers:
    Authorization:
      description: |
        On successful completion of an authorization flow,
        a client will be given an `access_token`, which they need to include in requests
        to authorized service endpoints via the HTTP `Authorization` header like this:

        Authorization: Bearer {access_token}
      type: string
  responses:
    401:
      description: Unauthorized
settings:
  authorizationUri: https://auth.europe-west1.gcp.commercetools.com/oauth/token
  accessTokenUri: https://auth.europe-west1.gcp.commercetools.com/oauth/token
  authorizationGrants: [client_credentials]
  (annotations.serviceRegions):
    - uri: https://auth.us-central1.gcp.commercetools.com/
      region: us-central1
      provider: gcp
      name: North America (Google Cloud, Iowa)
    #  - uri: https://auth.us-east-2.aws.commercetools.com/
    #    region: us-east-2
    #    provider: aws
    #    name: North America (AWS, Ohio)
    - uri: https://auth.europe-west1.gcp.commercetools.com
      region: europe-west1
      provider: gcp
      name: Europe (Google Cloud, Belgium)
    #  - uri: https://auth.eu-central-1.aws.commercetools.com
    #    region: eu-central-1
    #    provider: aws
    #    name: Europe (AWS, Frankfurt)
    - uri: https://auth.australia-southeast1.gcp.commercetools.com
      region: australia-southeast1
      provider: gcp
      name: Australia (Google Cloud, Sydney)
  scopes:
    - 'manage_project:{projectKey}'
    - 'view_import_sinks:{projectKey}'
    - 'manage_import_sinks:{projectKey}'
    - 'view_products:{projectKey}'
    - 'manage_products:{projectKey}'
    - 'view_orders:{projectKey}'
    - 'manage_orders:{projectKey}'
    - 'manage_import_sinks:{projectKey}'
    - 'view_import_sinks:{projectKey}'
