#%RAML 1.0 DataType
(package): Zone
type: object
displayName: ZoneUpdateAction
discriminator: action
(java-extends): 'com.commercetools.api.models.ResourceUpdateAction<ZoneUpdateAction>'
properties:
  action:
    type: string
