#%RAML 1.0 DataType
(package): Zone
(docs-uri): https://docs.commercetools.com/api/projects/zones#zonereference
(java-extends): com.commercetools.api.models.Identifiable<Zone>
type: Reference
displayName: ZoneReference
discriminatorValue: zone
description: |
  [Reference](ctp:api:type:Reference) to a [Zone](ctp:api:type:Zone).
properties:
  obj?:
    type: Zone
    description: |
      Contains the representation of the expanded Zone. Only present in responses to requests with [Reference Expansion](/../api/general-concepts#reference-expansion) for Zones.
  id:
    type: string
    description: |
      Platform-generated unique identifier of the referenced [Zone](ctp:api:type:Zone).
