#%RAML 1.0 DataType
(annotations.package): Application
type: object
displayName: ApplicationAgreement
properties:
  id:
    type: string
    description: |
      Unique identifier of the ApplicationAgreement.
  name:
    type: string
    description: |
      Unique name identifier for the ApplicationAgreement.
  type:
    type: ApplicationAgreementType
    description: |
      Type of agreement.
  status:
    type: ApplicationAgreementStatus
    description: |
      Indicates whether the agreement is active or not.
  text:
    type: LocalizedString
    description: |
      Text to display in checkout in Markdown format.
