#%RAML 1.0 DataType
(annotations.package): Application
type: string
displayName: ApplicationAgreementStatus
enum: [Active, Inactive]
(annotations.enumDescriptions):
  Active: The application agreement is active and can be used for processing payments.
  Inactive: The application agreement is inactive and cannot be used for processing payments.
