#%RAML 1.0 DataType
(annotations.package): Application
type: object
displayName: PaginatedApplication
description: |
  Paginated result containing Application.
properties:
  limit:
    type: integer
    description: |
      Number of results requested.
  offset:
    type: integer
    description: |
      Number of elements skipped.
  count:
    type: integer
    description: |
      Actual number of results returned.
  total:
    type: integer
    description: |
      Total number of results matching the query.
  results:
    type: Application[]
    description: |
      Applications matching the query.
