#%RAML 1.0 DataType
(annotations.package): Application
type: object
displayName: PaymentsConfiguration
properties:
  paymentReturnUrl?:
    type: string
    description: |
      URL where the buyer will be redirected back to after an offsite payment.
  activePaymentComponentType:
    type: PaymentComponentType
    description: |
      Indicates the type of payment components that the Application will use.
