#%RAML 1.0 DataType
(package): Inventory
(docs-uri): https://docs.commercetools.com/http-api-projects-inventory.html#remove-quantity


type: InventoryUpdateAction
displayName: InventoryRemoveQuantityAction
discriminatorValue: removeQuantity
properties:
    quantity:
        type: number
        format: int64
