#%RAML 1.0 DataType
(package): BusinessUnit
displayName: Associate
properties:
  associateRoleAssignments:
    type: AssociateRoleAssignment[]
    description: |
      Roles assigned to the Associate within a Business Unit.
  roles?:
    (deprecated): true
    type: AssociateRoleDeprecated[]
    description: |
      Deprecated type. Use `associateRoleAssignments` instead.
  customer:
    type: CustomerReference
    description: |
      The [Customer](ctp:api:type:Customer) that acts as an Associate in the Business Unit.
