#%RAML 1.0 DataType
(package): BusinessUnit
displayName: BusinessUnitDraft
discriminator: unitType
description: |
  Generic draft type to model those fields all Business Units have in common. The additional fields required for creating a [Company](ctp:api:type:Company) or [Division](ctp:api:type:Division) are represented on [CompanyDraft](ctp:api:type:CompanyDraft) and [DivisionDraft](ctp:api:type:DivisionDraft).
properties:
  key:
    type: string
    description: |
      User-defined unique and immutable identifier for the Business Unit.
    pattern: ^[A-Za-z0-9_-]+$
    minLength: 2
    maxLength: 256
  status?:
    type: BusinessUnitStatus
    description: |
      Indicates whether the Business Unit can be edited and used in [Orders](/../api/projects/orders).
    default: Active
  stores?:
    type: StoreResourceIdentifier[]
    description: |
      Sets the [Stores](ctp:api:type:Store) the Business Unit is associated with. Can only be set when `storeMode` is `Explicit`.
      Defaults to empty for [Companies](ctp:api:type:BusinessUnitType) and not set for [Divisions](ctp:api:type:BusinessUnitType).

      If the Business Unit has Stores defined, then all of its [Carts](ctp:api:type:Cart), [Orders](ctp:api:type:Order), [Quotes](ctp:api:type:Quote), or [Quote Requests](ctp:api:type:QuoteRequest) must belong to one of the Business Unit's Stores.

      If the Business Unit has no Stores, then all of its [Carts](ctp:api:type:Cart), [Orders](ctp:api:type:Order), [Quotes](ctp:api:type:Quote), or [Quote Requests](ctp:api:type:QuoteRequest) must not belong to any Store.
  storeMode?:
    type: BusinessUnitStoreMode
    description: |
      Defines whether the Stores of the Business Unit are set directly on the Business Unit or are inherited from a parent.
      `storeMode` is always `Explicit` for [Companies](ctp:api:type:BusinessUnitType) and defaults to `FromParent` for [Divisions](ctp:api:type:BusinessUnitType).
  unitType:
    type: BusinessUnitType
    description: |
      Type of the Business Unit indicating its position in a hierarchy.
  name:
    type: string
    description: |
      Name of the Business Unit.
  contactEmail?:
    type: string
    description: |
      Email address of the Business Unit.
  associateMode?:
    type: BusinessUnitAssociateMode
    description: |
      Determines whether the Business Unit can inherit Associates from a parent.
      Always `Explicit` for [Companies](ctp:api:type:BusinessUnitType) and defaults to `ExplicitAndFromParent` for [Divisions](ctp:api:type:BusinessUnitType).
  associates?:
    type: AssociateDraft[]
    description: |
      List of members that are part of the Business Unit in specific [roles](ctp:api:type:AssociateRole).
  approvalRuleMode?:
    type: BusinessUnitApprovalRuleMode
    description: |
      Determines whether the Business Unit can inherit Approval Rules from a parent.
      For [Companies](ctp:api:type:BusinessUnitType), the value of this field is always `Explicit`.
      For [Divisions](ctp:api:type:BusinessUnitType), the default value is `ExplicitAndFromParent`.
  addresses?:
    type: BaseAddress[]
    description: |
      Addresses used by the Business Unit.
  shippingAddresses?:
    type: integer[]
    description: |
      Indexes of entries in `addresses` to set as shipping addresses.
      The `shippingAddressIds` of the [Customer](ctp:api:type:Customer) will be replaced by these addresses.
  defaultShippingAddress?:
    type: integer
    description: |
      Index of the entry in `addresses` to set as the default shipping address.
  billingAddresses?:
    type: integer[]
    description: |
      Indexes of entries in `addresses` to set as billing addresses.
      The `billingAddressIds` of the [Customer](ctp:api:type:Customer) will be replaced by these addresses.
  defaultBillingAddress?:
    type: integer
    description: |
      Index of the entry in `addresses` to set as the default billing address.
  custom?:
    type: CustomFieldsDraft
    description: |
      Custom Fields for the Business Unit.
