#%RAML 1.0 DataType
(package): BusinessUnit
displayName: BusinessUnitApprovalRuleMode
type: string
description: |
  Determines whether a Business Unit can inherit [Approval Rules](/projects/approval-rules) from a parent. Only Business Units of type `Division` can use `ExplicitAndFromParent`.
enum:
  - Explicit
  - ExplicitAndFromParent
(enumDescriptions):
  Explicit: |
    Approval Rules of a Business Unit must be explicitly assigned. The Business Unit cannot inherit Approval Rules from a parent.
  ExplicitAndFromParent: |
    Approval Rules of a Business Unit are inherited from a parent and can also be explicitly assigned.
