#%RAML 1.0 DataType
(package): BusinessUnit
displayName: BusinessUnitPagedQueryResponse
type: object
description: |
  [PagedQueryResult](/../api/general-concepts#pagedqueryresult) with results containing an array of [BusinessUnit](ctp:api:type:BusinessUnit).
properties:
  limit:
    type: number
    format: int64
    description: |
      Number of requested [results](/../api/general-concepts#limit).
  offset:
    type: number
    format: int64
    description: |
      Number of elements [skipped](/../api/general-concepts#offset).
  count:
    type: number
    format: int64
    description: |
      Actual number of results returned.
  total?:
    type: number
    format: int64
    description: |
      Total number of results matching the query.
      This number is an estimation that is not [strongly consistent](/../api/general-concepts#strong-consistency).
      This field is returned by default.
      For improved performance, calculating this field can be deactivated by using the query parameter `withTotal=false`.
      When the results are filtered with a [Query Predicate](/../api/predicates/query), `total` is subject to a [limit](/../api/limits#queries).
  results:
    type: BusinessUnit[]
    description: |
      [BusinessUnits](ctp:api:type:BusinessUnit) matching the query.
