#%RAML 1.0 DataType
(package): BusinessUnit
displayName: BusinessUnitType
type: string
description: |
  The type of the Business Unit indicating its position in a hierarchy.
enum:
  - Company
  - Division
(enumDescriptions):
  Company: |
    Top-level Business Unit. Must not have a `parentUnit` defined.
  Division: |
    Business Unit with a `parentUnit` reference to a [Company](ctp:api:type:Division) or another Division.
