#%RAML 1.0 DataType
(package): BusinessUnit
displayName: BusinessUnitStatus
type: string
description: |
  Indicates whether the Business Unit can be edited and used in [Carts](ctp:api:type:Cart), [Orders](ctp:api:type:Order), [Quote Requests](ctp:api:type:QuoteRequest), or [Quotes](ctp:api:type:Quote).
enum:
  - Active
  - Inactive
(enumDescriptions):
  Active: |
    The Business Unit can be used in Carts, Orders, Quote Requests, and Quotes and can be edited.
  Inactive: |
    The Business Unit cannot be used in Carts, Orders, Quote Requests, and Quotes and can only be edited using the [general endpoint](/../api/associates-overview#through-the-general-endpoints).
    Status doesn't affect inheritance. Even if a parent unit is inactive, its children remain active and can inherit role assignments.
