#%RAML 1.0 DataType
(package): BusinessUnit
(docs-uri): https://docs.commercetools.com/api/projects/business-units#businessunitresourceidentifier
type: ResourceIdentifier
displayName: BusinessUnitResourceIdentifier
discriminatorValue: business-unit
description: |
  [ResourceIdentifier](/../api/types#resourceidentifier) to a [BusinessUnit](ctp:api:type:BusinessUnit).
properties:
  id?:
    type: string
    description: |
      Unique identifier of the referenced [BusinessUnit](ctp:api:type:BusinessUnit). Either `id` or `key` is required.
  key?:
    type: string
    description: |
      Unique key of the referenced [BusinessUnit](ctp:api:type:BusinessUnit). Either `id` or `key` is required.
