#%RAML 1.0 DataType
(package): BusinessUnit
displayName: BusinessUnit
(updateType): BusinessUnitUpdate
type: BaseResource
discriminator: unitType
description: |
  Generic type to model the fields that all types of Business Units have in common.
properties:
  id:
    (identifier): true
    type: string
    description: |
      Unique identifier of the Business Unit.
  version:
    type: number
    format: int64
    description: |
      Current version of the Business Unit.
  createdAt:
    type: datetime
    description: |
      Date and time (UTC) the Business Unit was initially created.
  lastModifiedAt:
    type: datetime
    description: |
      Date and time (UTC) the Business Unit was last updated.
  lastModifiedBy?:
    type: LastModifiedBy
    (beta): true
    description: |
      IDs and references that last modified the BusinessUnit.
  createdBy?:
    type: CreatedBy
    (beta): true
    description: |
      IDs and references that created the BusinessUnit.
  key:
    type: string
    description: |
      User-defined unique and immutable identifier of the Business Unit.
    pattern: ^[A-Za-z0-9_-]+$
    minLength: 2
    maxLength: 256
  status:
    type: BusinessUnitStatus
    description: |
      Indicates whether the Business Unit can be edited and used in [Orders](/../api/projects/orders).
  stores?:
    type: StoreKeyReference[]
    description: |
      References to [Stores](ctp:api:type:Store) the Business Unit is associated with. Only present when `storeMode` is `Explicit`.

      If the Business Unit has Stores defined, then all of its [Carts](ctp:api:type:Cart), [Orders](ctp:api:type:Order), [Quotes](ctp:api:type:Quote), or [Quote Requests](ctp:api:type:QuoteRequest) must belong to one of the Business Unit's Stores.

      If the Business Unit has no Stores, then all of its [Carts](ctp:api:type:Cart), [Orders](ctp:api:type:Order), [Quotes](ctp:api:type:Quote), or [Quote Requests](ctp:api:type:QuoteRequest) must not belong to any Store.
  storeMode:
    type: BusinessUnitStoreMode
    description: |
      Defines whether the Stores of the Business Unit are set directly on the Business Unit or are inherited from a parent.
  unitType:
    description: |
      Type of the Business Unit indicating its position in a hierarchy.
    type: BusinessUnitType
  name:
    type: string
    description: |
      Name of the Business Unit.
  contactEmail?:
    type: string
    description: |
      Email address of the Business Unit.
  custom?:
    type: CustomFields
    description: |
      Custom Fields for the Business Unit.
  addresses:
    type: Address[]
    description: |
      Addresses used by the Business Unit.
  shippingAddressIds?:
    type: string[]
    description: |
      Unique identifiers of addresses used as shipping addresses.
  defaultShippingAddressId?:
    type: string
    description: |
      Unique identifier of the address used as the default shipping address.
  billingAddressIds?:
    type: string[]
    description: |
      Unique identifiers of addresses used as billing addresses.
  defaultBillingAddressId?:
    type: string
    description: |
      Unique identifier of the address used as the default billing address.
  associateMode:
    type: BusinessUnitAssociateMode
    description: |
      Set to `Explicit` to prevent the Business Unit inheriting Associates from a parent, set to `ExplicitAndFromParent` to enable inheritance.
  associates:
    type: Associate[]
    description: |
      Associates that are part of the Business Unit in specific [roles](ctp:api:type:AssociateRole).
  inheritedAssociates?:
    type: InheritedAssociate[]
    description: |
      Associates that are inherited from a parent Business Unit. The value of this field is [eventually consistent](/../api/general-concepts#eventual-consistency) and is only present when the `associateMode` is set to `ExplicitAndFromParent`.
  parentUnit?:
    type: BusinessUnitKeyReference
    description: |
      Parent unit of the Business Unit. Only present when the `unitType` is `Division`.
  topLevelUnit:
    type: BusinessUnitKeyReference
    description: |
      Top-level unit of the Business Unit. The top-level unit is of `unitType` `Company`.
