#%RAML 1.0 DataType
(package): BusinessUnit
(docs-uri): https://docs.commercetools.com/api/projects/business-units#businessunit
displayName: Company
type: BusinessUnit
discriminatorValue: Company
description: |
  Business Unit type to represent the top level of a business.
  Contains specific fields and values that differentiate a Company from the generic [BusinessUnit](ctp:api:type:BusinessUnit).
properties:
  storeMode:
    type: BusinessUnitStoreMode
    description: |
      Is always `Explicit` since a Company cannot have a parent Business Unit that Stores can be inherited from.
  associateMode:
    type: BusinessUnitAssociateMode
    description: |
      Is always `Explicit` since a Company cannot have a parent Business Unit that Associates can be inherited from.
