#%RAML 1.0 DataType
(package): BusinessUnit
displayName: CompanyDraft
type: BusinessUnitDraft
discriminatorValue: Company
description: |
  Draft type to represent the top level of a business. Contains the fields and values of the generic [BusinessUnitDraft](ctp:api:type:BusinessUnitDraft) that are used specifically for creating a [Company](ctp:api:type:Company).
properties:
