#%RAML 1.0 DataType
(package): BusinessUnit
displayName: Division
type: BusinessUnit
discriminatorValue: Division
description: |
  Business Unit type to model divisions that are part of the [Company](ctp:api:type:Company) or a higher-order Division.
  Contains specific fields and values that differentiate a Division from the generic [BusinessUnit](ctp:api:type:BusinessUnit).
properties:
  parentUnit:
    type: BusinessUnitKeyReference
    description: |
      Parent unit of the Division.
  storeMode:
    type: BusinessUnitStoreMode
    default: FromParent
    description: |
      Defines whether the Stores of the Division are set explicitly or inherited from a parent Business Unit.
  associateMode:
    type: BusinessUnitAssociateMode
    default: ExplicitAndFromParent
    description: |
      Determines whether the Division can inherit Associates from a parent.
