#%RAML 1.0 DataType
(package): Me
displayName: MyBusinessUnitDraft
discriminator: unitType
properties:
  key:
    type: string
    description: |
      User-defined unique identifier for the BusinessUnit.
    pattern: ^[A-Za-z0-9_-]+$
    minLength: 2
    maxLength: 256
  unitType:
    type: BusinessUnitType
    description: |
      Type of the Business Unit indicating its position in a hierarchy.
  name:
    type: string
    description: |
      Name of the Business Unit.
  contactEmail?:
    type: string
    description: |
      Email address of the Business Unit.
  custom?:
    type: CustomFields
    description: |
      Custom Fields for the Business Unit.
  addresses?:
    type: BaseAddress[]
    description: |
      Addresses used by the Business Unit.
  shippingAddresses?:
    type: integer[]
    description: |
      Indexes of entries in `addresses` to set as shipping addresses.
      The `shippingAddressIds` of the [Customer](ctp:api:type:Customer) will be replaced by these addresses.
  defaultShippingAddress?:
    type: integer
    description: |
      Index of the entry in `addresses` to set as the default shipping address.
  billingAddresses?:
    type: integer[]
    description: |
      Indexes of entries in `addresses` to set as billing addresses.
      The `billingAddressIds` of the [Customer](ctp:api:type:Customer) will be replaced by these addresses.
  defaultBillingAddress?:
    type: integer
    description: |
      Index of the entry in `addresses` to set as the default billing address.
