#%RAML 1.0 DataType
(package): Me
(docs-uri): https://docs.commercetools.com/api/projects/me-business-units#mybusinessunitassociatedraft
displayName: MyBusinessUnitAssociateDraft
properties:
  version:
    type: number
    format: int64
    description: |
      Expected version of the BusinessUnit on which the changes should be applied. If the expected version does not match the actual version, a [409 Conflict](/../api/errors#409-conflict) error will be returned.
  customer:
    type: MyCustomerDraft
    description: |
      [Customer](ctp:api:type:Customer) to create and assign to the Business Unit.
  associateRoleAssignments:
    type: AssociateRoleAssignmentDraft[]
    description: |
      Roles assigned to the new Associate within a Business Unit.
    minItems: 1
