#%RAML 1.0 DataType
(package): Me
(docs-uri): https://docs.commercetools.com/http-api-projects-me-carts.html#mycartdraft
displayName: MyCartDraft
type: object
properties:
  currency:
    type: CurrencyCode
    description: A three-digit currency code as per [ISO 3166-1
      alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2).
  customerEmail?:
    type: string
    description: ''
  country?:
    type: string
    description: A two-digit country code as per [ISO 3166-1
      alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2).
  inventoryMode?:
    type: InventoryMode
    description: Default inventory mode is `None`.
  lineItems?:
    description: ''
    type: MyLineItemDraft[]
  shippingAddress?:
    type: BaseAddress
    description: ''
  billingAddress?:
    type: BaseAddress
    description: ''
  shippingMethod?:
    type: ShippingMethodResourceIdentifier
    description: ''
  custom?:
    type: CustomFieldsDraft
    description: The custom fields.
  locale?:
    type: string
    description: ''
  taxMode?:
    type: TaxMode
    description: The `TaxMode` `Disabled` can not be set on the My Carts endpoint.
  deleteDaysAfterLastModification?:
    type: number
    format: int64
    description: |-
      The cart will be deleted automatically if it hasn't been modified for the specified amount of days and it is in the `Active` CartState.
      If a ChangeSubscription for carts exists, a `ResourceDeleted` notification will be sent.
  itemShippingAddresses?:
    type: BaseAddress[]
    description: |-
      Contains addresses for orders with multiple shipping addresses.
      Each address must contain a key which is unique in this cart.
  store?:
    type: StoreKeyReference
  discountCodes?:
    type: DiscountCodeInfo[]
