#%RAML 1.0 DataType
(package): Me
(docs-uri): https://docs.commercetools.com/api/projects/business-units#businessunitdraft
displayName: MyDivisionDraft
type: MyBusinessUnitDraft
discriminatorValue: Division
description: |
  Draft type to model divisions that are part of the [Company](ctp:api:type:Company) or a higher-order [Division](ctp:api:type:Division).
  Contains the fields and values of the generic [MyBusinessUnitDraft](ctp:api:type:MyBusinessUnitDraft) that are used specifically for creating a Division.
properties:
  parentUnit:
    type: BusinessUnitResourceIdentifier
    description: |
      The parent unit of this Division. Can be a Company or a Division.
