#%RAML 1.0 DataType
(package): Me
(docs-uri): https://docs.commercetools.com/http-api-projects-me-quotes.html#myquotestate
displayName: MyQuoteState
type: string
description: |
  [QuoteStates](ctp:api:type:QuoteState) that can be set using the [Change My Quote State](ctp:api:type:MyQuoteChangeMyQuoteStateAction) update action.
enum:
  - Declined
  - Accepted
(enumDescriptions):
  Declined: |
    A state indicating that the [Buyer](/../api/quotes-overview#buyer) has declined the [Quote](ctp:api:type:Quote).
  Accepted: |
    A state indicating that the [Buyer](/../api/quotes-overview#buyer) has accepted the [Quote](ctp:api:type:Quote).
