#%RAML 1.0 DataType
(package): Me
type: object
displayName: MyQuoteRequestDraft
properties:
  cartId:
    type: string
    description: |
      `id` of the Cart from which the Quote Request is created. Carts with [Discount Codes](ctp:api:type:DiscountCode) and Carts with `Multiple` [ShippingMode](ctp:api:type:ShippingMode) are not supported.
      The Cart must have a `shippingAddress` defined, otherwise an [InvalidOperation](ctp:api:type:InvalidOperationError) error is returned when [creating a Quote Request](ctp:api:endpoint:/{projectKey}/me/quote-requests:POST).

  cartVersion:
    type: number
    format: int64
    description: Current version of the Cart.
  comment?:
    type: string
    description: Message from the Buyer included in the Quote Request.
