#%RAML 1.0 DataType
(package): OrderEdit
(docs-uri): https://docs.commercetools.com/http-api-projects-order-edits.html#addstagedaction
type: OrderEditUpdateAction
displayName: OrderEditAddStagedActionAction
discriminatorValue: addStagedAction
(postman-example): !include ../../../examples/OrderEdit/OrderEditAddStagedActionAction.json
properties:
  stagedAction:
    type: StagedOrderUpdateAction
    description: ''
