#%RAML 1.0 DataType
(package): OrderEdit
(docs-uri): https://docs.commercetools.com/http-api-projects-order-edits.html#add-returninfo
type: StagedOrderUpdateAction
displayName: StagedOrderAddReturnInfoAction
discriminatorValue: addReturnInfo
(postman-example): !include ../../../examples/OrderEdit/StagedOrderAddReturnInfoAction.json
properties:
  returnTrackingId?:
    type: string
  items:
    type: ReturnItemDraft[]
  returnDate?:
    type: datetime
