#%RAML 1.0 DataType
(package): OrderEdit
(docs-uri): https://docs.commercetools.com/http-api-projects-order-edits.html#set-lineitem-price
type: StagedOrderUpdateAction
displayName: StagedOrderSetLineItemPriceAction
discriminatorValue: setLineItemPrice
(postman-example): !include ../../../examples/OrderEdit/StagedOrderSetLineItemPriceAction.json
properties:
  lineItemId:
    type: string
  externalPrice?:
    type: Money
