#%RAML 1.0 DataType
(package): OrderEdit
(docs-uri): https://docs.commercetools.com/http-api-projects-order-edits.html#set-customer-email
type: StagedOrderUpdateAction
displayName: StagedOrderSetCustomerEmailAction
discriminatorValue: setCustomerEmail
(postman-example): !include ../../../examples/OrderEdit/StagedOrderSetCustomerEmailAction.json
properties:
  email?:
    type: string
