#%RAML 1.0 DataType
(annotations.package): Roles
type: object
displayName: Role
example: !include ../../examples/roles/role.json
properties:
  name:
    type: string
    description: |
      Name of role (must be globally unique within tenant namespace).
  description:
    type: string
    description: |
      Description of the role.
  permissions:
    type: string[]
    description: |
      If a permission isn't in the following list, then the default value from the dictionary will be used.
  tenant_id:
    type: string
    description: |
      Unique identifier of the tenant.
  updated_at:
    type: string
    description: |
      Date and time when the resource was last updated.
  created_at:
    type: string
    description: |
      Date and time when the resource was created.
  __v:
    type: number
    description: |
      Version of the resource.
  _id:
    type: string
    description: |
      Unique identifier of the resource.
