#%RAML 1.0 Library
usage: Customer import types.
(annotations.package): customers

uses:
  common: common.raml
  custom-field: custom-field.raml
  annotations: ../annotationTypes/annotations.raml

types:
  AuthenticationMode:
    default: Password
    type: string
    enum:
      - Password
      - ExternalAuth
    (annotations.enumDescriptions):
      Password: If set, the `password` field is required for the Customer.
      ExternalAuth: If set, the `password` field is optional for the Customer.
  CustomerAddress:
    description: |
      Different from [Address](/types#address) in that `key` is required and `id` is not supported.
    example: !include ../examples/customer-address.json
    properties:
      key:
        description: |
          User-defined identifier for the address.
          Must follow the pattern `[a-zA-Z0-9_\-]{2,256}` and must be unique per customer.
        type: string
      country:
        type: common.CountryCode
        description: |
          Name of the country.
      title?:
        type: string
        description: |
          Title of the contact, for example 'Dr.'
      salutation?:
        type: string
        description: |
          Salutation of the contact, for example 'Mr.' or 'Ms.'
      firstName?:
        type: string
        description: |
          Given name (first name) of the contact.
      lastName?:
        type: string
        description: |
          Family name (last name) of the contact.
      streetName?:
        type: string
        description: |
          Name of the street.
      streetNumber?:
        type: string
        description: |
          Street number.
      additionalStreetInfo?:
        type: string
        description: |
          Further information on the street address.
      postalCode?:
        type: string
        description: |
          Postal code.
      city?:
        type: string
        description: |
          Name of the city.
      region?:
        type: string
        description: |
          Name of the region.
      state?:
        type: string
        description: |
          Name of the state, for example, Colorado.
      company?:
        type: string
        description: |
          Name of the company.
      department?:
        type: string
        description: |
          Name of the department.
      building?:
        type: string
        description: |
          Number or name of the building.
      apartment?:
        type: string
        description: |
          Number or name of the apartment.
      pOBox?:
        type: string
        description: |
          Post office box number.
      phone?:
        type: string
        description: |
          Phone number of the contact.
      mobile?:
        type: string
        description: |
          Mobile phone number of the contact.
      email?:
        type: string
        description: |
          Email address of the contact.
      fax?:
        type: string
        description: |
          Fax number of the contact.
      additionalAddressInfo?:
        type: string
        description: |
          Further information on the Address.
      externalId?:
        type: string
        description: |
          ID for the contact used in an external system.
      custom?:
        description: Custom Fields for the address.
        type: custom-field.Custom
  CustomerImport:
    description: |
      The data representation for a Customer to be imported that is persisted as a [Customer](ctp:api:type:Customer) in the Project.
    type: common.ImportResource
    example: !include ../examples/customer-import.json
    properties:
      key:
        type: string
        description: User-defined unique identifier. If a [Customer](ctp:api:type:Customer) with this `key` exists, it will be updated with the imported data.
        pattern: ^[A-Za-z0-9_-]+$
        minLength: 2
        maxLength: 256
      customerNumber?:
        description: |
          Maps to `Customer.customerNumber`.
        type: string
      email:
        description: |
          Maps to `Customer.email`.
        type: string
      password?:
        description: |
          Required when `authenticationMode` is set to `Password`. Maps to `Customer.password`.
        type: string
      stores?:
        description: |
          The References to the Stores with which the Customer is associated. If referenced Stores do not exist, the `state` of the [ImportOperation](ctp:import:type:ImportOperation) will be set to `unresolved` until the necessary Stores are created.
        type: common.StoreKeyReference[]
      firstName?:
        description: |
          Maps to `Customer.firstName`.
        type: string
      lastName?:
        description: |
          Maps to `Customer.lastName`.
        type: string
      middleName?:
        description: |
          Maps to `Customer.middleName`.
        type: string
      title?:
        description: |
          Maps to `Customer.title`.
        type: string
      salutation?:
        description: |
          Maps to `Customer.salutation`.
        type: string
      externalId?:
        description: |
          Maps to `Customer.externalId`.
        type: string
      dateOfBirth?:
        description: |
          Maps to `Customer.dateOfBirth`.
        type: date-only
      companyName?:
        description: |
          Maps to `Customer.companyName`.
        type: string
      vatId?:
        description: |
          Maps to `Customer.vatId`.
        type: string
      isEmailVerified?:
        description: |
          Maps to `Customer.isEmailVerified`.
        type: boolean
      customerGroup?:
        description: |
          The Reference to the [CustomerGroup](ctp:api:type:CustomerGroup) with which the Customer is associated.
          If referenced CustomerGroup does not exist, the `state` of the [ImportOperation](ctp:import:type:ImportOperation) will be set to `unresolved` until the necessary CustomerGroup is created.
        type: common.CustomerGroupKeyReference
      addresses?:
        description: |
          Maps to `Customer.addresses`.
        type: CustomerAddress[]
      defaultBillingAddress?:
        description: |
          The index of the address in the addresses array. The `defaultBillingAddressId` of the customer will be set to the ID of that address.
        type: integer
      billingAddresses?:
        description: |
          The indices of the billing addresses in the addresses array. The `billingAddressIds` of the customer will be set to the IDs of that addresses.
        type: integer[]
      defaultShippingAddress?:
        description: |
          The index of the address in the addresses array. The `defaultShippingAddressId` of the customer will be set to the ID of that address.
        type: integer
      shippingAddresses?:
        description: |
          The indices of the shipping addresses in the addresses array. The `shippingAddressIds` of the customer will be set to the IDs of that addresses.
        type: integer[]
      locale?:
        description: |
          Maps to `Customer.locale`.
        type: string
        pattern: ^[a-zA-Z]{2,3}(?:-[a-zA-Z]{4})?(?:-(?:[a-zA-Z]{2}|\d{3}))?$
      custom?:
        description: |
          The Custom Fields for this Customer.
        type: custom-field.Custom
      authenticationMode?:
        description: |
          - Set to `Password` to make the `password` field required for the Customer.
          - Set to `ExternalAuth` when the password is not required for the Customer.
        type: AuthenticationMode
        default: Password
