#%RAML 1.0 Library
usage: Discount Code import types.
(annotations.package): discount-codes

uses:
  common: common.raml
  annotations: ../annotationTypes/annotations.raml
  custom-field: custom-field.raml

types:
  DiscountCodeImport:
    description: |
      Represents the data used to import a DiscountCode. Once imported, this data is persisted as a [DiscountCode](ctp:api:type:DiscountCode) in the Project.
    type: common.ImportResource
    example: !include ../examples/discount-code-import.json
    properties:
      key:
        description: |
          User-defined unique identifier. If a [DiscountCode](ctp:api:type:DiscountCode) with this `key` exists, it is updated with the imported data.
        type: string
        pattern: ^[A-Za-z0-9_-]+$
        minLength: 2
        maxLength: 256
      name?:
        description: |
          Maps to `DiscountCode.name`.
        type: common.LocalizedString
      description?:
        description: |
          Maps to `DiscountCode.description`.
        type: common.LocalizedString
      code:
        description: |
          Maps to `DiscountCode.code`. This value cannot be updated. Attempting to update this value will result in an [InvalidFieldsUpdate](/import-export/error#invalidfieldsupdateerror) error.
        type: string
      cartDiscounts:
        description: |
          Maps to `DiscountCode.cartDiscounts`. If the referenced [CartDiscounts](ctp:api:type:CartDiscount) do not exist, the `state` of the [ImportOperation](ctp:import:type:ImportOperation) will be set to `unresolved` until the referenced CartDiscounts are created.
        type: common.CartDiscountKeyReference[]
      cartPredicate?:
        description: |
          Maps to `DiscountCode.cartPredicate`.
        type: string
      isActive:
        description: |
          Maps to `DiscountCode.isActive`.
        type: boolean
      maxApplications?:
        type: number
        format: int64
        description: |
          Maps to `DiscountCode.maxApplications`.
      maxApplicationsPerCustomer?:
        type: number
        format: int64
        description: |
          Maps to `DiscountCode.maxApplicationsPerCustomer`.
      groups?:
        description: |
          Maps to `DiscountCode.groups`.
        type: string[]
      validFrom?:
        description: |
          Maps to `DiscountCode.validFrom`.
        type: datetime
      validUntil?:
        description: |
          Maps to `DiscountCode.validUntil`.
        type: datetime
      custom?:
        description: |
          Maps to `DiscountCode.custom`.
        type: custom-field.Custom
