#%RAML 1.0 DataType
(package): Order
(docs-uri): https://docs.commercetools.com/http-api-projects-orders.html#add-payment
type: OrderUpdateAction
displayName: OrderAddPaymentAction
discriminatorValue: addPayment
(postman-example): !include ../../../examples/Order/OrderAddPaymentAction.json
properties:
  payment:
    type: PaymentResourceIdentifier
