#%RAML 1.0 DataType
(package): Order
(docs-uri): https://docs.commercetools.com/http-api-projects-orders.html#change-orderstate
type: OrderUpdateAction
displayName: OrderChangeOrderStateAction
discriminatorValue: changeOrderState
(postman-example): !include ../../../examples/Order/OrderChangeOrderStateAction.json
properties:
  orderState:
    type: OrderState
