#%RAML 1.0 DataType
(package): Order
(docs-uri): https://docs.commercetools.com/http-api-projects-orders.html#set-locale
type: OrderUpdateAction
displayName: OrderSetLocaleAction
discriminatorValue: setLocale
(postman-example): !include ../../../examples/Order/OrderSetLocaleAction.json
properties:
  locale?:
    type: string
