#%RAML 1.0 DataType
(package): Order
(docs-uri): https://docs.commercetools.com/http-api-projects-orders.html#set-returnshipmentstate
type: OrderUpdateAction
displayName: OrderSetReturnShipmentStateAction
discriminatorValue: setReturnShipmentState
(postman-example): !include ../../../examples/Order/OrderSetReturnShipmentStateAction.json
properties:
  returnItemId:
    type: string
  shipmentState:
    type: ReturnShipmentState
