#%RAML 1.0 DataType
(package): Order

type: OrderUpdateAction
displayName: OrderRemoveParcelFromDeliveryAction
discriminatorValue: removeParcelFromDelivery
properties:
    parcelId:
        type: string
