#%RAML 1.0 DataType
(package): Order
(docs-uri): https://docs.commercetools.com/http-api-projects-orders.html#set-lineitem-custom-type
type: OrderUpdateAction
displayName: OrderSetLineItemCustomTypeAction
discriminatorValue: setLineItemCustomType
(postman-example): !include ../../../examples/Order/OrderSetLineItemCustomTypeAction.json
properties:
  lineItemId:
    type: string
  type?:
    type: TypeResourceIdentifier
  fields?:
    type: FieldContainer
