#%RAML 1.0 DataType
(package): Order

displayName: Delivery

type: object
properties:
    id:
        type: string
    createdAt:
        type: datetime
    items: DeliveryItem[]
    parcels: Parcel[]
