#%RAML 1.0 DataType
(package): Order
(docs-uri): https://docs.commercetools.com/http-api-projects-orders.html#delivery

displayName: Delivery

type: object
properties:
    id:
        type: string
    createdAt:
        type: datetime
    items: DeliveryItem[]
    parcels: Parcel[]
    address?:
      type: Address
