#%RAML 1.0 DataType
(package): Order

displayName: LineItemImportDraft

type: object
(generate-collection): true
properties:
    productId?:
        type: string
    name:
        type: LocalizedString
    variant:
        type: ProductVariantImportDraft
    price:
        type: Price
    quantity:
        type: number
    state?: ItemState[]
    supplyChannel?:
        type: ChannelReference
    taxRate?:
        type: TaxRate
    custom?:
        type: CustomFieldsDraft
