#%RAML 1.0 DataType
(package): Order
(docs-uri): https://docs.commercetools.com/http-api-projects-orders-import.html#lineitemimportdraft

displayName: LineItemImportDraft

type: object
properties:
    productId?:
        type: string
    name:
        type: LocalizedString
    variant:
        type: ProductVariantImportDraft
    price:
        type: PriceDraft
    quantity:
        type: number
    state?: ItemState[]
    supplyChannel?:
        type: ChannelReference
    taxRate?:
        type: TaxRate
    custom?:
        type: CustomFieldsDraft
    shippingDetails?:
        type: ItemShippingDetailsDraft
