#%RAML 1.0 DataType
(package): Order


type: OrderUpdateAction
displayName: OrderUpdateSyncInfoAction
discriminatorValue: updateSyncInfo
properties:
    channel:
        type: ChannelReference
    externalId?:
        type: string
    syncedAt?:
        type: datetime
