#%RAML 1.0 DataType
(package): Order


type: OrderUpdateAction
displayName: OrderTransitionCustomLineItemStateAction
discriminatorValue: transitionCustomLineItemState
properties:
    actualTransitionDate?:
        type: datetime
    customLineItemId:
        type: string
    fromState:
        type: StateReference
    quantity:
        type: number
    toState:
        type: StateReference
