#%RAML 1.0 DataType
(package): Order
(docs-uri): https://docs.commercetools.com/http-api-projects-orders-import.html#orderimportdraft

displayName: OrderImportDraft

type: object
properties:
  orderNumber?:
    type: string
  customerId?:
    type: string
  customerEmail?:
    type: string
  lineItems?: LineItemImportDraft[]
  customLineItems?: CustomLineItemDraft[]
  totalPrice: Money
  taxedPrice?:
    type: TaxedPrice
  shippingAddress?:
    type: Address
  billingAddress?:
    type: Address
  customerGroup?:
    type: CustomerGroupReference
  country?:
    type: string
  orderState?:
    type: OrderState
  shipmentState?:
    type: ShipmentState
  paymentState?:
    type: PaymentState
  shippingInfo?:
    type: ShippingInfoImportDraft
  completedAt?:
    type: datetime
  custom?:
    type: CustomFieldsDraft
  inventoryMode?:
    type: InventoryMode
  taxRoundingMode?:
    type: RoundingMode
  itemShippingAddresses?:
    type: Address[]
