#%RAML 1.0 DataType
(package): Order

type: OrderUpdateAction
displayName: OrderSetParcelTrackingDataAction
discriminatorValue: setParcelTrackingData
properties:
    parcelId:
        type: string
    trackingData:
        type: TrackingData
