#%RAML 1.0 DataType
(package): Order
(docs-uri): https://docs.commercetools.com/http-api-projects-orders.html#add-delivery


type: OrderUpdateAction
displayName: OrderAddDeliveryAction
discriminatorValue: addDelivery
properties:
    items?:
        type: DeliveryItem[]
    parcels?:
        type: ParcelDraft[]
    address?:
        type: Address
