#%RAML 1.0 DataType
(package): Order


type: OrderUpdateAction
displayName: OrderAddParcelToDeliveryAction
discriminatorValue: addParcelToDelivery
properties:
    deliveryId:
        type: string
    measurements?:
        type: ParcelMeasurements
    trackingData?:
        type: TrackingData
