#%RAML 1.0 DataType
(package): Order


type: OrderUpdateAction
displayName: OrderSetLineItemCustomTypeAction
discriminatorValue: setLineItemCustomType
properties:
    fields?:
        type: string
    lineItemId:
        type: string
    type?:
        type: Type
