#%RAML 1.0 DataType
(package): Order


type: OrderUpdateAction
displayName: OrderChangeShipmentStateAction
discriminatorValue: changeShipmentState
properties:
    shipmentState:
        type: ShipmentState
