#%RAML 1.0 DataType

displayName: ParcelMeasurements

type: object
properties:
    heightInMillimeter:
        type: number
    lengthInMillimeter:
        type: number
    widthInMillimeter:
        type: number
    weightInGram:
        type: number
