#%RAML 1.0 DataType
(package): Order
(docs-uri): https://docs.commercetools.com/http-api-projects-orders.html#parcel

displayName: Parcel

type: object
properties:
    id:
        type: string
    createdAt:
        type: datetime
    measurements?:
        (hasUpdateAction):
            action: setParcelMeasurements
            fields:
               parcelId:
                  type: string
               measurements?:
                  type: ParcelMeasurements
        type: ParcelMeasurements
    trackingData?: TrackingData
    items?:
        type: DeliveryItem[]
