#%RAML 1.0 DataType

displayName: ReturnItemDraft

type: object
(generate-collection): true
properties:
    quantity:
        type: integer
    lineItemId:
        type: string
    comment?:
        type: string
    shipmentState:
        type: ReturnShipmentState
