#%RAML 1.0 DataType
(package): Order
(docs-uri): https://docs.commercetools.com/http-api-projects-orders.html#syncinfo
displayName: SyncInfo
type: object
properties:
  channel:
    type: ChannelReference
    description: Connection to a particular synchronization destination.
  externalId?:
    type: string
    description: Can be used to reference an external order instance, file etc.
  syncedAt:
    type: datetime
    description: ''
