#%RAML 1.0 DataType
(package): Order

displayName: TrackingData

type: object
properties:
    trackingId?:
        type: string
    carrier?:
        type: string
    provider?:
        type: string
    providerTransaction?:
        type: string
    isReturn?:
        type: boolean
