#%RAML 1.0 DataType
(package): Common
displayName: Address
type: BaseAddress
properties:
  id?:
    type: string
    description: |
      Identifier of the Address used for ordering Addresses in array fields on Customers or other resources.
      It is only unique within the context of the resource that contains the Address.
  custom?:
    type: CustomFields
    description: Custom Fields defined for the Address.
