#%RAML 1.0 DataType
(package): Common
displayName: AddressRole
type: string
description: |
  Indicates the role of an address.
enum:
  - Shipping
  - Billing
(enumDescriptions):
  Shipping: |
    The address is used as a shipping address.
  Billing: |
    The address is used as a billing address.
