#%RAML 1.0 DataType
(package): Common
displayName: Address
type: BaseAddress
description: |
  Address type returned by read methods.
  Optionally, the `custom` field can be present in addition to the fields of a [BaseAddress](ctp:api:type:BaseAddress).
properties:
  custom?:
    type: CustomFields
    description: Custom Fields defined for the Address.
