#%RAML 1.0 DataType
(package): Common
displayName: AssetDimensions
type: object
description: |
  Dimensions of the Asset source specified by the number of pixels.
properties:
  w:
    type: number
    format: int32
    description: |
      Width of the Asset source.
  h:
    type: number
    format: int32
    description: |
      Height of the Asset source.
