#%RAML 1.0 DataType
(package): Common
displayName: AssetSource
type: object
properties:
  uri:
    type: string
  key?:
    type: string
  dimensions?:
    type: AssetDimensions
  contentType?:
    type: string
