#%RAML 1.0 DataType
(package): Common
displayName: AttributionSource
type: string
enum:
  - Import
  - Export
(enumDescriptions):
  Import: Resource was created or updated during import.
  Export: Resource was created or updated during export.
