#%RAML 1.0 DataType
(package): Common
displayName: CurrencyCode
type: string
description: |
  A currency code compliant with [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217) or a [non-standard currency](ctp:api:type:NonStandardCurrency).
pattern: ^[A-Z]{3}0?$
