#%RAML 1.0 DataType
(package): Common
displayName: DiscountedPriceDraft
type: object
properties:
  value:
    type: Money
    description: |
      Sets the money value for the discounted price.
      To set the money value in high precision, use [HighPrecisionMoneyDraft](ctp:api:type:HighPrecisionMoneyDraft).
  discount:
    type: ProductDiscountReference
    description: |
      Relates the referenced [ProductDiscount](ctp:api:type:ProductDiscount) to the discounted price.
