#%RAML 1.0 DataType
(package): Common
(docs-uri): https://docs.commercetools.com/http-api-types.html#money
displayName: HighPrecisionMoney
type: TypedMoney
discriminatorValue: highPrecision
description: Money object that stores an amount of a fraction of the smallest indivisible unit of the specified currency.
example: !include ../../examples/Common/HighPrecisionMoney.json
properties:
  preciseAmount:
    type: number
    format: int64
    description: |
      Amount in 1 / (10 ^ `fractionDigits`) of a currency.
  fractionDigits:
    type: number
    format: int32
    maximum: 20
    description: |
      Number of digits after the decimal separator, greater than the default number of fraction digits for a currency.
