#%RAML 1.0 DataType
(package): Common
displayName: Locale
type: string
description: |
  String matching the pattern `^[a-z]{2}(-[A-Z]{2})?$` representing an [IETF language tag](https://en.wikipedia.org/wiki/IETF_language_tag).
pattern: ^[a-z]{2}(-[A-Z]{2})?$
