#%RAML 1.0 DataType
(package): Common
(docs-uri): https://docs.commercetools.com/api/types#moneytype
displayName: MoneyType
type: string
description: Determines the type of money used.
(enumDescriptions):
  centPrecision: Use to set currency in cent precision.
  highPrecision: Use to set currency in high precision.
enum:
  - centPrecision
  - highPrecision
