#%RAML 1.0 DataType
(package): Common
(docs-uri): https://docs.commercetools.com/http-api-projects-products.html#price
displayName: Price
description: |-
  The representation for prices embedded in [LineItems](ctp:api:type:LineItem) and in [ProductVariants](ctp:api:type:ProductVariant) when the [ProductPriceMode](ctp:api:type:ProductPriceModeEnum) is `Embedded`.
  For the `Standalone` ProductPriceMode refer to [StandalonePrice](ctp:api:type:StandalonePrice).
type: object
(java-extends): 'com.commercetools.api.models.Customizable<Price>'
properties:
  id:
    type: string
    description: |
      Unique identifier of this Price.
  value:
    type: TypedMoney
    description: |
      Money value of this Price.
  country?:
    type: CountryCode
    description: |
      Country for which this Price is valid.
  customerGroup?:
    type: CustomerGroupReference
    description: |
      [CustomerGroup](ctp:api:type:CustomerGroup) for which this Price is valid.
  channel?:
    type: ChannelReference
    description: |
      `ProductDistribution` [Channel](ctp:api:type:Channel) for which this Price is valid.
  validFrom?:
    type: datetime
    description: |
      Date and time from which this Price is valid.
  validUntil?:
    type: datetime
    description: |
      Date and time until this Price is valid.
  discounted?:
    type: DiscountedPrice
    description: |
      Is set if a [ProductDiscount](ctp:api:type:ProductDiscount) has been applied.
      If set, the API uses the DiscountedPrice value for the [LineItem Price selection](/projects/carts#lineitem-price-selection).
      When a [relative discount](/../api/projects/productDiscounts#productdiscountvaluerelative) has been applied and the fraction part of the DiscountedPrice `value` is 0.5, the `value` is rounded in favor of the customer with [half down rounding](https://en.wikipedia.org/wiki/Rounding#Round_half_down).
  tiers?:
    type: PriceTier[]
    description: |
      Present if different Prices for certain [LineItem](ctp:api:type:LineItem) quantities have been specified.
  custom?:
    type: CustomFields
    description: |
      Custom Fields defined for the Price.
