#%RAML 1.0 DataType
(package): Common
displayName: PriceTierDraft
description: |
  Specifies a Price tier that applies when the minimum quantity for the [LineItem](ctp:api:type:LineItem) of a ProductVariant with the related Price is reached in a Cart.
type: object
properties:
  minimumQuantity:
    type: number
    format: int64
    description: |
      Minimum quantity this Price tier is valid for.

      The minimum quantity is always greater than or equal to 2. The base Price is interpreted as valid for a minimum quantity equal to 1.
      A [Price](ctp:api:type:Price) or [StandalonePrice](ctp:api:type:StandalonePrice) cannot contain more than one tier with the same `minimumQuantity`.
      In the case one of the constraint is not met an [InvalidField](ctp:api:type:InvalidFieldError) is returned.
  value:
    type: Money
    description: |
      Money value that applies when the `minimumQuantity` is greater than or equal to the [LineItem](ctp:api:type:LineItem) `quantity`.

      To set the money value in high precision, use [HighPrecisionMoneyDraft](ctp:api:type:HighPrecisionMoneyDraft).

      The `currencyCode` of a Price tier must be the same as the `currencyCode` in the `value` of the related Price.
