#%RAML 1.0 DataType
(package): Common
displayName: PriceTier
description: |
  A Price tier is selected instead of the default Price when a certain quantity of the [ProductVariant](ctp:api:type:ProductVariant) is [added to a Cart](/projects/carts#add-lineitem) and ordered.
  _For example: the Price can be lower if more than 10 items are ordered._
  If no Price tier is found for the Order quantity, the base Price is used.
  A Price tier is applied for the entire quantity of a Product Variant put as [LineItem](/projects/carts#lineitem) in a Cart as soon as the minimum quantity for the Price tier is reached.
  The Price tier is applied per Line Item of the Product Variant. If, for example, the same Product Variant appears in the same Cart as several Line Items, (what can be achieved by different values of a Custom Field on the Line Items) for each Line Item the minimum quantity must be reached to get the Price tier.
type: object
properties:
  minimumQuantity:
    type: number
    format: int64
    description: |
      Minimum quantity this Price tier is valid for.

      The minimum quantity is always greater than or equal to 2. The base Price is interpreted as valid for a minimum quantity equal to 1.
      A [Price](ctp:api:type:Price) or [StandalonePrice](ctp:api:type:StandalonePrice) cannot contain more than one tier with the same `minimumQuantity`.

  value:
    type: TypedMoney
    description: |
      Money value that applies when the `minimumQuantity` is greater than or equal to the [LineItem](ctp:api:type:LineItem) `quantity`.

      The `currencyCode` of a Price tier is always the same as the `currencyCode` in the `value` of the related Price.
