#%RAML 1.0 DataType
(package): Common
(docs-uri): https://docs.commercetools.com/http-api-types.html#reference
displayName: Reference
type: object
discriminator: typeId
description: |
  A Reference represents a loose reference to another resource in the same commercetools Project identified by its `id`. The `typeId` indicates the type of the referenced resource. Each resource type has its corresponding Reference type, like [ChannelReference](ctp:api:type:ChannelReference).  A referenced resource can be embedded through [Reference Expansion](/general-concepts#reference-expansion). The expanded reference is the value of an additional `obj` field then.
example: !include ../../examples/Common/Reference.json
properties:
  typeId:
    type: ReferenceTypeId
    description: |
      Type of referenced resource.
  id:
    type: string
    description: |
      Unique ID of the referenced resource.
