#%RAML 1.0 DataType
(package): Common
(docs-uri):
displayName: Sort
type: string
description: |
  Enables server-side expansion of [References](ctp:api:type:Reference). For details, see [Reference Expansion](/../api/general-concepts#reference-expansion).
