#%RAML 1.0 DataType
(package): Common
(docs-uri): https://docs.commercetools.com/http-api-types.html#money
displayName: TypedMoney
type: Money
discriminator: type
description: |
  Base polymorphic read-only Money type which is stored in cent precision or high precision. The actual type is determined by the `type` field.
properties:
  type:
    type: MoneyType
  fractionDigits:
    type: number
    format: int32
    maximum: 12
    description: |
      number of digits after the decimal separator

      * equal to the default number of fraction digits for a currency in [CentPrecisionMoney](ctp:api:type:CentPrecisionMoney).
      * greater than the default number of fraction digits for a currency in [HighPrecisionMoney](ctp:api:type:HighPrecisionMoney).
