#%RAML 1.0 DataType
(package): ProductSearch
type: ProductSearchFacetExpression
(beta): true
displayName: ProductSearchFacetStatsExpression
properties:
  stats:
    type: ProductSearchFacetStatsValue
    description: Definition of the stats facet.
