#%RAML 1.0 DataType
(package): ProductSearch
displayName: ProductSearchFacetResultCount
type: ProductSearchFacetResult
description: |
  Result of a [count facet](/../api/projects/product-search#count-facets).
properties:
  value:
    type: number
    format: int64
    description: Number of Products (or Product Variants) matching the query.
