#%RAML 1.0 DataType
(package): ProductSearch
type: object
(beta): true
displayName: ProductSearchFacetDistinctValue
properties:
  name:
    type: string
    description: Name of the distinct facet to appear in the [ProductSearchFacetResultBucket](ctp:api:type:ProductSearchFacetResultBucket).
  scope?:
    type: ProductSearchFacetScopeEnum
    default: query
    description: Whether the facet must consider only the Products resulting from the search (`query`) or all the Products (`all`).
  filter?:
    type: SearchQuery
    description: Additional filtering expression to apply to the search result before calculating the facet.
  level?:
    type: ProductSearchFacetCountLevelEnum
    default: products
    description: Specify whether to count Products (`products`) or Product Variants (`variants`).
  field:
    type: string
    description: |
      The [searchable Product field](/api/projects/product-search#searchable-product-fields) to facet on.
  includes?:
    type: string[]
    description: Specify which bucket keys the facets results should include.
  sort?:
    type: ProductSearchFacetDistinctBucketSortExpression
    description: Define how the buckets are sorted.
  limit?:
    type: number
    format: int32
    default: 10
    maximum: 200
    description: Maximum number of buckets to return.
  language?:
    type: Locale
  fieldType?:
    type: SearchFieldType
    description: If the `field` is not standard, this must be the Attribute type.
  missing?:
    type: string
    description: Default value to use if the specified field is not present on some Products.
