#%RAML 1.0 DataType
(package): ProductSearch
type: string
displayName: ProductSearchFacetDistinctBucketSortBy
enum:
  - count
  - key
(enumDescriptions):
  count: Sort buckets by the count value.
  key: Sort buckets by the bucket key.
