#%RAML 1.0 DataType
(package): ProductSearch
displayName: ProductSearchFacetCountLevelEnum
type: string
enum:
  - products
  - variants
(enumDescriptions):
  products: The query should count Products.
  variants: The query should count Product Variants.
