package:
  type: string
  allowedTargets: TypeDeclaration
identifier:
  type: boolean
  allowedTargets: TypeDeclaration
elementIdentifier:
  type: boolean
  allowedTargets: TypeDeclaration
placeholderParam:
  type: object
  allowedTargets: TypeDeclaration
  properties:
    paramName: string
    template: string
    placeholder: string
docs-uri:
  type: string
updateType:
  type: string
  allowedTargets: TypeDeclaration
updateable:
  type: string
deleteable:
  type: string
createable:
  type: string
methodName:
  type: string
asMap:
  type: object
  properties:
    key: string
    value: string
hasSimpleUpdateAction:
  type: string
  allowedTargets: TypeDeclaration
hasUpdateActions:
  allowedTargets: TypeDeclaration
  type: array
  items:
    type: object
    properties:
      action: string
      docsAnchor?: string
      required?: boolean
      fields?: object
hasUpdateAction:
  type: object
  allowedTargets: TypeDeclaration
  properties:
    action: string
    docsAnchor?: string
    required?: boolean
    fields?: object
deprecated:
  type: boolean
  allowedTargets: TypeDeclaration
markDeprecated:
  type: boolean
  allowedTargets: TypeDeclaration
abstract:
  type: boolean
  allowedTargets: TypeDeclaration
actionType:
  type: string
  allowedTargets: TypeDeclaration
csharp-extends:
  type: string
  allowedTargets: TypeDeclaration
csharp-implements:
  type: string
  allowedTargets: TypeDeclaration
java-extends:
  type: string
  allowedTargets: TypeDeclaration
java-implements:
  type: string
  allowedTargets: TypeDeclaration
beta:
  type: boolean
sdkBaseUri:
  allowedTargets:
    - API
  type: string
docsBaseUri:
  allowedTargets:
    - API
  type: string
docsBaseUriParameters:
  allowedTargets:
    - API
  type: object
enumDescriptions:
  description: |
    Describes the values of an enum type.
  type: object
  properties:
    //:
      description: |
        Adds a description for the enum value given by the key.
