#%RAML 1.0 DataType
(annotations.package): Locations
displayName: GiftCardProcessorEnum
type: string
description: |
  List of supported gift card processors.
enum:
  - None
  - Simulator
  - Custom
(annotations.enumDescriptions):
  None: |
    None configured.
  Simulator: |
    Simulation only.
  Custom: |
    Custom PSP.
