#%RAML 1.0 DataType
(annotations.package): Locations
displayName: WalletProcessorEnum
type: string
description: |
  List of supported wallet processors.
enum:
  - None
  - Citcon
(annotations.enumDescriptions):
  None: |
    None configured.
  Citcon: |
    Citcon
