#%RAML 1.0 DataType
(package): ProductType
(docs-uri): https://docs.commercetools.com/api/projects/productTypes#enumtype
type: AttributeType
displayName: AttributeEnumType
discriminatorValue: enum
description: |
  Attribute type for plain enum values. Useful for predefined language-agnostic values selectable in drop downs when only one value should be selected. Use [AttributeSetType](ctp:api:type:AttributeSetType) of AttributeEnumType instead if multiple values can be selected from the list.
properties:
  values:
    type: AttributePlainEnumValue[]
    description: |
      Available values that can be assigned to Products.
