#%RAML 1.0 DataType
(package): ProductType
displayName: AttributeDefinitionDraft
type: object
description: |
  Specify the Attribute to be created with the [ProductTypeDraft](ctp:api:type:ProductTypeDraft).
properties:
  type:
    type: AttributeType
    description: Describes the Type of the Attribute.
  name:
    type: string
    pattern: ^[A-Za-z0-9_-]+$
    minLength: 2
    maxLength: 256
    description: |-
      User-defined name of the Attribute that is unique with the [Project](ctp:api:type:Project).
      When using the same `name` for an Attribute in multiple ProductTypes, all fields of the AttributeDefinition of this Attribute must be the same across the ProductTypes. Otherwise an [AttributeDefinitionAlreadyExistsError](ctp:api:type:AttributeDefinitionAlreadyExistsError) will be returned.
      An exception to this are the values of an `enum` or `lenum` Type and sets thereof.
  label:
    type: LocalizedString
    description: Human-readable label for the Attribute.
  isRequired:
    type: boolean
    description: |
      Set to `true` if the Attribute is required to have a value on a [ProductVariant](ctp:api:type:ProductVariant).
  attributeConstraint?:
    type: AttributeConstraintEnum
    description: |
      Specifies how an Attribute or a combination of Attributes should be validated across all variants of a Product.
    default: None
  inputTip?:
    type: LocalizedString
    description: |
      Provides additional information about the Attribute that aids content managers when setting Product details.
  inputHint?:
    type: TextInputHint
    description: |
      Provides a visual representation directive for values of this Attribute (only relevant for [AttributeTextType](ctp:api:type:AttributeTextType) and [AttributeLocalizableTextType](ctp:api:type:AttributeLocalizableTextType)).
    default: SingleLine
  isSearchable?:
    type: boolean
    description: |-
      Set to `true` if the Attribute's values should be available in the [Product Projections Search API](/../api/projects/products-search) and can be used in full-text search queries, filters, and facets.
      Which exact features are available with this flag depends on the specific [AttributeType](ctp:api:type:AttributeType).
      The maximum size of a searchable field is **restricted** by the [Field content size limit](/../api/limits#field-content-size).
      This constraint is enforced at both Product creation and Product update.
      If the length of the input exceeds the maximum size, an InvalidField error is returned.
    default: true
