#%RAML 1.0 DataType
(package): ProductType
displayName: AttributeLevelEnum
type: string
(beta): true
enum:
  - Product
  - Variant
(enumDescriptions):
  Product: Attribute is defined at Product level.
  Variant: Attributes are defined at the Product Variant level.
  default: Variant
