#%RAML 1.0 DataType
(package): ProductType
type: object
displayName: ProductTypeUpdate
(java-extends): 'com.commercetools.api.models.ResourceUpdate<ProductTypeUpdate,
  ProductTypeUpdateAction>'
properties:
  version:
    type: number
    format: int64
  actions:
    type: array
    items: ProductTypeUpdateAction
