#%RAML 1.0 DataType
(package): Message
type: Message
(beta): true
displayName: ApprovalRuleDescriptionSetMessage
discriminatorValue: ApprovalRuleDescriptionSet
description: |
  Generated after a successful [Set Description](ctp:api:type:ApprovalRuleSetDescriptionAction) update action.
properties:
  description?:
    type: string
    description: |
      Description of the [ApprovalRule](ctp:api:type:ApprovalRule) after the [Set Description](ctp:api:type:ApprovalRuleSetDescriptionAction) update action.
  oldDescription?:
    type: string
    description: |
      Description of the [ApprovalRule](ctp:api:type:ApprovalRule) before the [Set Description](ctp:api:type:ApprovalRuleSetDescriptionAction) update action.
