#%RAML 1.0 DataType
(package): Message
type: Message
displayName: AssociateRolePermissionAddedMessage
discriminatorValue: AssociateRolePermissionAdded
description: |
  Generated after a successful [Add Permissions](ctp:api:type:AssociateRoleAddPermissionAction) update action.
properties:
  permission:
    type: Permission
    description: |
      The Permission that was added to the AssociateRole.
