#%RAML 1.0 DataType
(package): Message
type: Message
displayName: AssociateRoleNameSetMessage
discriminatorValue: AssociateRoleNameSet
description: |
  Generated after a successful [Set Name](ctp:api:type:AssociateRoleSetNameAction) update action.
properties:
  name:
    type: string
    description: |
      Updated name of the [AssociateRole](ctp:api:type:AssociateRole).
