#%RAML 1.0 DataType
(package): Message
type: Message
displayName: BusinessUnitAddressChangedMessage
discriminatorValue: BusinessUnitAddressChanged
description: |
  Generated after a successful [Change Address](ctp:api:type:BusinessUnitChangeAddressAction) update action.
properties:
  address:
    type: Address
    description: |
      Updated address of the Business Unit.
  addressRoles:
    type: array
    items: AddressRole
    description: |
      Indicates if the address was used for shipping or billing purposes.
