#%RAML 1.0 DataType
(package): Message
type: Message
displayName: BusinessUnitAddressRemovedMessage
discriminatorValue: BusinessUnitAddressRemoved
description: |
  Generated after a successful [Remove Address](ctp:api:type:BusinessUnitRemoveAddressAction) update action.
properties:
  address:
    type: Address
    description: |
      The address that was removed from the [Business Unit](ctp:api:type:BusinessUnit).
  addressRoles:
    type: array
    items: AddressRole
    description: |
      Indicates if the address was used for shipping or billing purposes.
