#%RAML 1.0 DataType
(package): Message
(docs-uri): https://docs.commercetools.com/http-api-projects-messages.html#businessunitdefaultshippingaddresssetmessage
type: Message
displayName: BusinessUnitDefaultShippingAddressSetMessage
discriminatorValue: BusinessUnitDefaultShippingAddressSet
description: |
  Generated after a successful [Set Default Shipping Address](ctp:api:type:BusinessUnitSetDefaultShippingAddressAction) update action.
properties:
  address?:
    type: Address
    description: |
      The address that was set as the default shipping address.
