#%RAML 1.0 DataType
(package): Message
(docs-uri): https://docs.commercetools.com/http-api-projects-messages.html#businessunitstoressetmessage
type: Message
displayName: BusinessUnitStoresSetMessage
discriminatorValue: BusinessUnitStoresSet
description: |
  Generated after a successful [Set Stores](ctp:api:type:BusinessUnitSetStoresAction) update action.
properties:
  stores:
    type: StoreKeyReference[]
    description: |
      [Stores](ctp:api:type:Store) of the [Business Unit](ctp:api:type:BusinessUnit) after the [Set Stores](ctp:api:type:BusinessUnitSetStoresAction) update action.
