#%RAML 1.0 DataType
(package): Message
(docs-uri): https://docs.commercetools.com/http-api-projects-messages.html#businessunitbillingaddressaddedmessage
type: Message
displayName: BusinessUnitBillingAddressAddedMessage
discriminatorValue: BusinessUnitBillingAddressAdded
description: |
  Generated after a successful [Add Billing Address Identifier](ctp:api:type:BusinessUnitAddBillingAddressIdAction) update action.
properties:
  address:
    type: Address
    description: |
      The address that was added to the [Business Unit](ctp:api:type:BusinessUnit) as billing address.
