#%RAML 1.0 DataType
(package): Message
type: Message
(beta): true
displayName: BusinessUnitTypeSetMessage
discriminatorValue: BusinessUnitTypeSet
description: |
  Generated after a successful [Set Unit Type](ctp:api:type:BusinessUnitSetUnitTypeAction) update action.
properties:
  parentUnit?:
    type: BusinessUnitKeyReference
    description: |
      Parent unit of the [Business Unit](ctp:api:type:BusinessUnit) after the [Set Unit Type](ctp:api:type:BusinessUnitSetUnitTypeAction) update action.
  oldParentUnit?:
    type: BusinessUnitKeyReference
    description: |
      Parent unit of the [Business Unit](ctp:api:type:BusinessUnit) before the [Set Unit Type](ctp:api:type:BusinessUnitSetUnitTypeAction) update action.
  unitType:
    type: BusinessUnitType
    description: |
      Type of the [Business Unit](ctp:api:type:BusinessUnit) after the [Set Unit Type](ctp:api:type:BusinessUnitSetUnitTypeAction) update action.
  oldUnitType:
    type: BusinessUnitType
    description: |
      Type of the [Business Unit](ctp:api:type:BusinessUnit) before the [Set Unit Type](ctp:api:type:BusinessUnitSetUnitTypeAction) update action.
