#%RAML 1.0 DataType
(package): Message
type: Message
displayName: CartDiscountDeletedMessage
discriminatorValue: CartDiscountDeleted
description: |
  Generated after a successful [Delete CartDiscount](ctp:api:endpoint:/{projectKey}/cart-discounts/{id}:DELETE) request.
properties:
