#%RAML 1.0 DataType
(package): Message
(docs-uri): https://docs.commercetools.com/http-api-projects-messages.html#category-created
type: Message
displayName: CategoryCreatedMessage
discriminatorValue: CategoryCreated
description: |
  Generated after a successful [Create Category](/../api/projects/categories#create-category) request.
properties:
  category:
    type: Category
    description: |
      [Category](ctp:api:type:Category) that was created.
