#%RAML 1.0 DataType
(package): Message
(docs-uri): https://docs.commercetools.com/http-api-projects-messages.html#categoryslugchangedmessage
type: Message
displayName: CategorySlugChangedMessage
discriminatorValue: CategorySlugChanged
properties:
  slug:
    type: LocalizedString
  oldSlug?:
    type: LocalizedString
