#%RAML 1.0 DataType
(package): Message
displayName: ContainerAndKey
type: object
description: |
  `ContainerAndKey` is specific to [Custom Objects](ctp:api:type:CustomObject). Custom Objects are grouped into containers, which can be used like namespaces. Within a given container, a user-defined key can be used to uniquely identify resources.
properties:
  key:
    type: string
    description: User-defined identifier that is unique within the given container.
  container:
    type: string
    description: Namespace to group [Custom Objects](ctp:api:type:CustomObject).
