#%RAML 1.0 DataType
(package): Message
(docs-uri): https://docs.commercetools.com/http-api-projects-messages.html#customercreatedmessage
type: Message
displayName: CustomerCreatedMessage
discriminatorValue: CustomerCreated
properties:
  customer:
    type: Customer
