#%RAML 1.0 DataType
(package): Message
(docs-uri): https://docs.commercetools.com/http-api-projects-messages.html#customeremailchangedmessage
type: Message
displayName: CustomerEmailChangedMessage
discriminatorValue: CustomerEmailChanged
properties:
  email:
    type: string
