#%RAML 1.0 DataType
(package): Message
(docs-uri): https://docs.commercetools.com/http-api-projects-messages.html#customer-address-removed
type: Message
displayName: CustomerAddressRemovedMessage
discriminatorValue: CustomerAddressRemoved
description: |
  Generated after a successful [Remove Address](ctp:api:type:CustomerRemoveAddressAction) update action.
properties:
  address:
    type: Address
    description: |
      [Address](ctp:api:type:Address) that was removed during the [Remove Address](ctp:api:type:CustomerRemoveAddressAction) update action.
