#%RAML 1.0 DataType
(package): Message
(docs-uri): https://docs.commercetools.com/http-api-projects-messages.html#customerpasswordupdatedmessage
type: Message
displayName: CustomerPasswordUpdatedMessage
discriminatorValue: CustomerPasswordUpdated
properties:
  reset:
    type: boolean
    description:
      true, if password has been updated during Customer's Password Reset
      workflow.
