#%RAML 1.0 DataType
(package): Message
type: Message
displayName: CustomerCustomFieldChangedMessage
discriminatorValue: CustomerCustomFieldChanged
description: |
  Generated after changing an existing Custom Field on a Customer using the [Set CustomField](ctp:api:type:CustomerSetCustomFieldAction) update action.
properties:
  name:
    type: string
    description: |
      Name of the Custom Field that changed.
  value:
    type: CustomFieldValue
    description: |
      [CustomFieldValue](ctp:api:type:CustomFieldValue) based on the [FieldType](ctp:api:type:FieldType) after the [Set CustomField](ctp:api:type:CustomerSetCustomFieldAction) update action.
  previousValue?:
    type: CustomFieldValue
    description: |
      [CustomFieldValue](ctp:api:type:CustomFieldValue) based on the [FieldType](ctp:api:type:FieldType) before the [Set CustomField](ctp:api:type:CustomerSetCustomFieldAction) update action.
      When there has not been a Custom Field with the `name` on the Customer before, a [Customer Custom Field Added](ctp:api:type:CustomerCustomFieldAddedMessage) Message is generated instead.
