#%RAML 1.0 DataType
(package): Message
(docs-uri): https://docs.commercetools.com/http-api-projects-messages.html#customercompanynamesetmessage
type: Message
displayName: CustomerCompanyNameSetMessage
discriminatorValue: CustomerCompanyNameSet
properties:
  companyName:
    type: string
