#%RAML 1.0 DataType
(package): Message
(docs-uri): https://docs.commercetools.com/http-api-projects-messages.html#customeraddressremovedmessage
type: Message
displayName: CustomerAddressRemovedMessage
discriminatorValue: CustomerAddressRemoved
properties:
  address:
    type: Address
