#%RAML 1.0 DataType
(package): Message
type: Message
displayName: CustomerEmailTokenCreatedMessage
discriminatorValue: CustomerEmailTokenCreated
description: |
  Generated after a successful [Create email token for Customer](ctp:api:endpoint:/{projectKey}/customers/email-token:POST) request. The `resource` property of the Message is a [CustomerEmailTokenReference](ctp:api:type:CustomerEmailTokenReference).
properties:
  customerId:
    type: string
    description: |
      Unique identifier of the Customer.
  expiresAt:
    type: datetime
    description: |
      Date and time (UTC) the email token expires.
