#%RAML 1.0 DataType
(package): Message
type: BaseResource
displayName: Message
discriminator: type
description: |
  Base representation of a Message containing common fields to all [Message Types](/../api/projects/messages#message-types).
properties:
  id:
    (identifier): true
    type: string
    description: Unique identifier of the Message. Can be used to track which Messages have been processed.
  version:
    type: number
    format: int64
    description: Version of a resource. In case of Messages, this is always `1`.
  createdAt:
    type: datetime
    description: Date and time (UTC) the Message was generated.
  lastModifiedAt:
    type: datetime
    description: Value of `createdAt`.
  lastModifiedBy?:
    type: LastModifiedBy
    (beta): true
    description: |
      IDs and references that last modified the Message.
  createdBy?:
    type: CreatedBy
    (beta): true
    description: |
      IDs and references that created the Message.
  sequenceNumber:
    type: number
    format: int64
    description: |
      Message number in relation to other Messages for a given resource. The `sequenceNumber` of the next Message for the resource is the successor of the `sequenceNumber` of the current Message. Meaning, the `sequenceNumber` of the next Message equals the `sequenceNumber` of the current Message + 1.
      `sequenceNumber` can be used to ensure that Messages are processed in the correct order for a particular resource.
  resource:
    type: Reference
    description: |
      [Reference](ctp:api:type:Reference) to the resource on which the change or action was performed.
  resourceVersion:
    type: number
    format: int64
    description: |
      Version of the resource on which the change or action was performed.
  type:
    type: string
    description: |
      [Message Type](/../api/projects/messages#message-types) of the Message.
  resourceUserProvidedIdentifiers?:
    type: UserProvidedIdentifiers
    description: |
      User-provided identifiers of the resource, such as `key` or `externalId`. Only present if the resource has such identifiers.
