#%RAML 1.0 DataType
(package): Message
type: object
displayName: MessagesConfigurationDraft
description: Defines the configuration for the [Messages Query](/../api/projects/messages) feature for the Project.
properties:
  enabled:
    type: boolean
    description: |
      Setting to `true` activates the [Messages Query](/../api/projects/messages) feature.
  deleteDaysAfterCreation:
    type: number
    minimum: 1
    maximum: 90
    format: int32
    description: |
      Specifies the number of days each Message should be available via the [Messages Query](/../api/projects/messages) API. For Messages older than the specified period, it is not guaranteed that they are still accessible via the API.
