#%RAML 1.0 DataType
(package): Message
type: OrderMessage
displayName: OrderDiscountCodeRemovedMessage
discriminatorValue: OrderDiscountCodeRemoved
description: |
  Generated after a successful [Remove DiscountCode](ctp:api:type:StagedOrderRemoveDiscountCodeAction) update action.
properties:
  discountCode:
    type: DiscountCodeReference
    description: |
      [DiscountCode](ctp:api:type:DiscountCode) that was removed.
