#%RAML 1.0 DataType
(package): Message
(docs-uri): https://docs.commercetools.com/http-api-projects-messages.html#order-custom-line-item-removed
type: OrderMessage
displayName: OrderCustomLineItemRemovedMessage
discriminatorValue: OrderCustomLineItemRemoved
description: |
  Generated after a successful [Remove Custom Line Item](ctp:api:type:StagedOrderRemoveCustomLineItemAction) update action.
properties:
  customLineItemId:
    type: string
    description: |
      Unique identifier of the [Custom Line Item](ctp:api:type:CustomLineItem).
  customLineItem:
    type: CustomLineItem
    description: |
      [Custom Line Item](ctp:api:type:CustomLineItem) that was removed from the [Order](ctp:api:type:Order).
