#%RAML 1.0 DataType
(package): Message
(docs-uri): https://docs.commercetools.com/http-api-projects-messages.html#ordershippingaddresssetmessage
type: Message
displayName: OrderShippingAddressSetMessage
discriminatorValue: OrderShippingAddressSet
properties:
  address?:
    type: Address
  oldAddress?:
    type: Address
