#%RAML 1.0 DataType
(package): Message
(docs-uri): https://docs.commercetools.com/api/message-types#orderlineitemdistributionchannelset
type: OrderMessage
displayName: OrderLineItemDistributionChannelSetMessage
discriminatorValue: OrderLineItemDistributionChannelSet
properties:
  lineItemId:
    type: string
  distributionChannel?:
    type: ChannelReference
