#%RAML 1.0 DataType
(package): Message
type: OrderMessage
displayName: OrderBillingAddressSetMessage
discriminatorValue: OrderBillingAddressSet
description: |
  Generated after a successful [Set Billing Address](ctp:api:type:OrderSetBillingAddressAction) update action.
properties:
  address?:
    type: Address
    description: |
      Billing address on the Order after the [Set Billing Address](ctp:api:type:OrderSetBillingAddressAction) update action.
  oldAddress?:
    type: Address
    description: |
      Billing address on the Order before the [Set Billing Address](ctp:api:type:OrderSetBillingAddressAction) update action.
