#%RAML 1.0 DataType
(package): Message
(docs-uri): https://docs.commercetools.com/http-api-projects-messages.html#order-discount-code-added
type: OrderMessage
displayName: OrderDiscountCodeAddedMessage
discriminatorValue: OrderDiscountCodeAdded
description: |
  Generated after a successful [Add Discount Code](ctp:api:type:StagedOrderAddDiscountCodeAction) update action.
properties:
  discountCode:
    type: DiscountCodeReference
    description: |
      [DiscountCode](ctp:api:type:DiscountCode) that was added.
