#%RAML 1.0 DataType
(package): Message
type: OrderMessage
displayName: OrderLineItemDistributionChannelSetMessage
discriminatorValue: OrderLineItemDistributionChannelSet
description: |
  Generated after a successful [Set LineItem DistributionChannel](/../api/projects/order-edits#set-lineitem-distributionchannel) update action.
properties:
  lineItemId:
    type: string
    description: |
      Unique identifier of the [Line Item](ctp:api:type:LineItem).
  lineItemKey?:
    type: string
    description: |
      User-defined unique identifier of the LineItem.
  distributionChannel?:
    type: ChannelReference
    description: |
      [Distribution Channel](ctp:api:type:Channel) that was set.
