#%RAML 1.0 DataType
(package): Message
(docs-uri): https://docs.commercetools.com/api/projects/messages#order-purchase-order-number-set
type: OrderMessage
displayName: OrderPurchaseOrderNumberSetMessage
discriminatorValue: OrderPurchaseOrderNumberSet
description: |
  Generated after a successful [Set Purchase Order Number](ctp:api:type:OrderSetPurchaseOrderNumberAction) update action.
properties:
  purchaseOrderNumber?:
    type: string
    description: |
      Purchase order number on the [Order](ctp:api:type:Order) after the [Set Purchase Order Number](ctp:api:type:OrderSetPurchaseOrderNumberAction) update action.
  oldPurchaseOrderNumber?:
    type: string
    description: |
      Purchase order number on the [Order](ctp:api:type:Order) before the [Set Purchase Order Number](ctp:api:type:OrderSetPurchaseOrderNumberAction) update action.
