#%RAML 1.0 DataType
(package): Message
(docs-uri): https://docs.commercetools.com/http-api-message-types.html#orderstoresetmessage
type: Message
displayName: OrderStoreSetMessage
discriminatorValue: OrderStoreSet
properties:
  store:
    type: StoreKeyReference
