#%RAML 1.0 DataType
(package): Message
(docs-uri): https://docs.commercetools.com/http-api-projects-messages.html#order-shipment-state-changed
type: OrderMessage
displayName: OrderShipmentStateChangedMessage
discriminatorValue: OrderShipmentStateChanged
description: |
  Generated after a successful [Change ShipmentState](ctp:api:type:OrderChangeShipmentStateAction) update action.
properties:
  shipmentState:
    type: ShipmentState
    description: |
      [ShipmentState](ctp:api:type:ShipmentState) after the [Change Shipment State](ctp:api:type:OrderChangeShipmentStateAction) update action.
  oldShipmentState:
    type: ShipmentState
    description: |
      [ShipmentState](ctp:api:type:ShipmentState) before the [Change Shipment State](ctp:api:type:OrderChangeShipmentStateAction) update action.
