#%RAML 1.0 DataType
(package): Message
(docs-uri): https://docs.commercetools.com/http-api-projects-messages.html#order-custom-line-item-quantity-changed
type: OrderMessage
displayName: OrderCustomLineItemQuantityChangedMessage
discriminatorValue: OrderCustomLineItemQuantityChanged
description: |
  Generated after a successful [Change CustomLineItem Quantity](ctp:api:type:StagedOrderChangeCustomLineItemQuantityAction) update action.
properties:
  customLineItemId:
    type: string
    description: |
      Unique identifier of the [Custom Line Item](ctp:api:type:CustomLineItem).
  quantity:
    type: number
    format: int64
    description: |
      [Custom Line Item](ctp:api:type:CustomLineItem) quantity after the [Change Custom Line Item Quantity](ctp:api:type:StagedOrderChangeCustomLineItemQuantityAction) update action.
  oldQuantity:
    type: number
    format: int64
    description: |
      [Custom Line Item](ctp:api:type:CustomLineItem) quantity before the [Change Custom Line Item Quantity](ctp:api:type:StagedOrderChangeCustomLineItemQuantityAction) update action.
