#%RAML 1.0 DataType
(package): Message
type: OrderMessage
displayName: OrderShippingRateInputSetMessage
discriminatorValue: OrderShippingRateInputSet
description: |
  Generated after a successful [Set ShippingRateInput](ctp:api:type:StagedOrderSetShippingRateInputAction) update action.
properties:
  shippingRateInput?:
    type: ShippingRateInput
    description: |
      [ShippingRateInput](ctp:api:type:ShippingRateInput) after the [Set ShippingRateInput](ctp:api:type:StagedOrderSetShippingRateInputAction) update action.
  oldShippingRateInput?:
    type: ShippingRateInput
    description: |
      [ShippingRateInput](ctp:api:type:ShippingRateInput) before the [Set ShippingRateInput](ctp:api:type:StagedOrderSetShippingRateInputAction) update action.
