#%RAML 1.0 DataType
(package): Message
type: OrderMessage
displayName: ParcelAddedToDeliveryMessage
discriminatorValue: ParcelAddedToDelivery
description: |
  Generated after a successful [Add Parcel to Delivery](ctp:api:type:OrderAddParcelToDeliveryAction) update action.
properties:
  delivery:
    type: Delivery
    description: |
      Unique identifier of the [Delivery](ctp:api:type:Delivery).
  parcel:
    type: Parcel
    description: |
      [Parcel](ctp:api:type:Parcel) that was added to the [Delivery](ctp:api:type:Delivery).
  shippingKey?:
    type: string
    description: |
      User-defined unique identifier of the Shipping Method in a Cart with `Multiple` [ShippingMode](ctp:api:type:ShippingMode).
