#%RAML 1.0 DataType
(package): Message
(docs-uri): https://docs.commercetools.com/http-api-projects-messages.html#paymenttransactionaddedmessage
type: Message
displayName: PaymentTransactionAddedMessage
discriminatorValue: PaymentTransactionAdded
properties:
  transaction:
    type: Transaction
