#%RAML 1.0 DataType
(package): Message
type: Message
displayName: PaymentMethodInfoCustomFieldRemovedMessage
discriminatorValue: PaymentMethodInfoCustomFieldRemoved
(beta): true
description: |
  Generated after removing a Custom Field from a PaymentMethodInfo using the [Set MethodInfo CustomField](ctp:api:type:PaymentSetMethodInfoCustomFieldAction) update action on Payments and the [Set MethodInfo CustomField](ctp:api:type:MyPaymentSetMethodInfoCustomFieldAction) update action on My Payments.
properties:
  name:
    type: string
    description: |
      Name of the Custom Field that was removed.
