#%RAML 1.0 DataType
(package): Message
(docs-uri): https://docs.commercetools.com/http-api-projects-messages.html#payment-status-state-transition
type: Message
displayName: PaymentStatusStateTransitionMessage
discriminatorValue: PaymentStatusStateTransition
description: |
  Generated after a successful [Transition State](ctp:api:type:PaymentTransitionStateAction) update action.
properties:
  state:
    type: StateReference
    description: |
      [State](ctp:api:type:State) of the [Payment](ctp:api:type:Payment) after the [Transition State](ctp:api:type:PaymentTransitionStateAction) update action.
  force:
    type: boolean
    description: |
      Whether [State](ctp:api:type:State) transition validations were turned off during the [Change Transaction State](ctp:api:type:PaymentChangeTransactionStateAction) update action.
