#%RAML 1.0 DataType
(package): Message
type: Message
displayName: PaymentMethodMethodSetMessage
discriminatorValue: PaymentMethodMethodSet
(beta): true
description: |
  Generated after a successful [Set Method](ctp:api:type:PaymentMethodSetMethodAction) update action.
properties:
  method?:
    type: string
    description: |
      Payment Method after the [Set Method](ctp:api:type:PaymentMethodSetMethodAction) update action.
  oldMethod?:
    type: string
    description: |
      Payment Method before the [Set Method](ctp:api:type:PaymentMethodSetMethodAction) update action.
