#%RAML 1.0 DataType
(package): Message
type: Message
displayName: PaymentTransactionInterfaceIdSetMessage
discriminatorValue: PaymentTransactionInterfaceIdSet
description: |
  Generated after a successful [Set Transaction InterfaceId](ctp:api:type:PaymentSetTransactionInterfaceIdAction) update action.
properties:
  transactionId:
    type: string
    description: |
      Unique identifier of the [Transaction](ctp:api:type:Transaction).
  newInterfaceId?:
    type: string
    description: |
      Identifier used by the payment service that processes the Payment (for example, a PSP) after [Set Transaction InterfaceId](ctp:api:type:PaymentSetTransactionInterfaceIdAction) update action.
  oldInterfaceId?:
    type: string
    description: |
      Identifier used by the payment service that processes the Payment (for example, a PSP) before the [Set Transaction InterfaceId](ctp:api:type:PaymentSetTransactionInterfaceIdAction) update action.
