#%RAML 1.0 DataType
(package): Message
type: Message
displayName: ProductAddedToCategoryMessage
discriminatorValue: ProductAddedToCategory
description: |
  Generated after a successful [Add to Category](ctp:api:type:ProductAddToCategoryAction) update action.
properties:
  category:
    type: CategoryReference
    description: |
      [Category](ctp:api:type:Category) the [Product](ctp:api:type:Product) was added to.
  staged:
    type: boolean
    description: |
      Whether the update was only applied to the staged [Product Projection](ctp:api:type:ProductProjection).
