#%RAML 1.0 DataType
(package): Message
type: Message
displayName: ProductSelectionProductAddedMessage
discriminatorValue: ProductSelectionProductAdded
properties:
  product:
    type: ProductReference
  variantSelection?:
    type: ProductVariantSelection
