#%RAML 1.0 DataType
(package): Message
(docs-uri): https://docs.commercetools.com/http-api-message-types.html#productpricediscountssetmessage
type: Message
displayName: ProductPriceDiscountsSetMessage
discriminatorValue: ProductPriceDiscountsSet
properties:
  updatedPrices:
    type: ProductPriceDiscountsSetUpdatedPrice[]
