#%RAML 1.0 DataType
(package): Message
type: Message
displayName: ProductSelectionProductExcludedMessage
discriminatorValue: ProductSelectionProductExcluded
description: |
  Generated after a successful [Exclude Product](ctp:api:type:ProductSelectionExcludeProductAction) update action.
properties:
  product:
    type: ProductReference
    description: |
      [Product](ctp:api:type:Product) that was excluded from the [Product Selection](ctp:api:type:ProductSelection).
  variantExclusion:
    type: ProductVariantExclusion
    description: |
      Product Variant Exclusion after the [Exclude Product](ctp:api:type:ProductSelectionExcludeProductAction) update action.
