#%RAML 1.0 DataType
(package): Message
type: Message
displayName: ProductDeletedMessage
discriminatorValue: ProductDeleted
description: |
  Generated after a successful [Delete Product](/../api/projects/products#delete-product) request.
properties:
  removedImageUrls:
    type: array
    items: string
    description: |
      List of image URLs that were removed during the [Delete Product](ctp:api:type:Product) request.
  currentProjection?:
    type: ProductProjection
    description: |
      Current [Product Projection](ctp:api:type:ProductProjection) of the deleted [Product](ctp:api:type:Product).
