#%RAML 1.0 DataType
(package): Message
(docs-uri): https://docs.commercetools.com/http-api-message-types.html#productpricediscountssetmessage
type: object
displayName: ProductPriceDiscountsSetUpdatedPrice
properties:
  variantId:
    type: integer
  variantKey?:
    type: string
  sku?:
    type: string
  priceId:
    type: string
  discounted?:
    type: DiscountedPrice
  staged:
    type: boolean
