#%RAML 1.0 DataType
(package): Message
(docs-uri): https://docs.commercetools.com/api/projects/messages#product-price-changed
type: Message
displayName: ProductPriceChangedMessage
discriminatorValue: ProductPriceChanged
description: |
  Generated after a successful [Change Price](ctp:api:type:ProductChangePriceAction) update action.
properties:
  variantId:
    type: number
    format: int64
    description: |
      Unique identifier of the [ProductVariant](ctp:api:type:ProductVariant) for which the Price was changed.
  oldPrice:
    type: Price
    description: |
      The current [Embedded Price](/projects/products#embedded-price) before the [Change Embedded Price](ctp:api:type:ProductChangePriceAction) update action.
  newPrice:
    type: Price
    description: |
      The [Embedded Price](/projects/products#embedded-price) after the [Change Embedded Price](ctp:api:type:ProductChangePriceAction) update action.
  staged:
    type: boolean
    description: |
      Whether the update was only applied to the staged [Product Projection](ctp:api:type:ProductProjection).
  oldStagedPrice?:
    type: Price
    description: |
      The staged [Embedded Price](/projects/products#embedded-price) before the [Change Embedded Price](ctp:api:type:ProductChangePriceAction) update action.
