#%RAML 1.0 DataType
(package): Message
type: Message
displayName: ProductPublishedMessage
discriminatorValue: ProductPublished
description: |
  Generated after a successful [Publish](ctp:api:type:ProductPublishAction) update action.
properties:
  removedImageUrls:
    type: array
    items: string
    description: |
      List of image URLs which were removed during the [Publish](ctp:api:type:ProductPublishAction) update action.
  productProjection:
    type: ProductProjection
    description: |
      Current [Product Projection](ctp:api:type:ProductProjection) of the [Product](ctp:api:type:Product) at the time of creation.
  scope:
    type: ProductPublishScope
    description: |
      [Publishing Scope](ctp:api:type:ProductPublishScope) that was used during the [Publish](ctp:api:type:ProductPublishAction) update action.
