#%RAML 1.0 DataType
(package): Message
(docs-uri): https://docs.commercetools.com/api/projects/messages#quote-change-customer
type: Message
displayName: QuoteCustomerChangedMessage
discriminatorValue: QuoteCustomerChanged
description: |
  Generated after a successful [Change Customer](ctp:api:type:QuoteChangeCustomerAction) update action.
properties:
  customer:
    type: CustomerReference
    description: |
      The [Buyer](/../api/quotes-overview#buyer) who now owns the Quote.
  previousCustomer:
    type: CustomerReference
    description: |
      The previous [Buyer](/../api/quotes-overview#buyer).
