#%RAML 1.0 DataType
(package): Message
type: Message
displayName: QuoteDeletedMessage
discriminatorValue: QuoteDeleted
description: |
  Generated after a successful [Delete Quote](/../api/projects/quotes#delete-quote) request.
