#%RAML 1.0 DataType
(package): Message
type: Message
(beta): true
displayName: RecurringOrderStateChangedMessage
discriminatorValue: RecurringOrderStateChanged
description: |
  Generated after a successful [Set RecurringOrderState](ctp:api:type:RecurringOrderSetStateAction) update action.
properties:
  state:
    type: RecurringOrderState
    description: |
      [RecurringOrderState](ctp:api:type:RecurringOrderState) after the [Set RecurringOrderState](ctp:api:type:RecurringOrderSetStateAction) update action.
  oldState?:
    type: RecurringOrderState
    description: |
      [RecurringOrderState](ctp:api:type:RecurringOrderState) before the [Set RecurringOrderState](ctp:api:type:RecurringOrderSetStateAction) update action.
