#%RAML 1.0 DataType
(package): Message
type: Message
(beta): true
displayName: RecurringOrderCustomFieldChangedMessage
discriminatorValue: RecurringOrderCustomFieldChanged
description: |
  Generated when an existing Custom Field has been changed using the [Set CustomField](ctp:api:type:RecurringOrderSetCustomFieldAction) action.
properties:
  name:
    type: string
    description: |
      Name of the Custom Field that changed.
  value:
    type: CustomFieldValue
    description: |
      [CustomFieldValue](ctp:api:type:CustomFieldValue) based on the [FieldType](ctp:api:type:FieldType) after the [Set CustomField](ctp:api:type:RecurringOrderSetCustomFieldAction) update action.
  previousValue?:
    type: CustomFieldValue
    description: |
      [CustomFieldValue](ctp:api:type:CustomFieldValue) based on the [FieldType](ctp:api:type:FieldType) before the [Set CustomField](ctp:api:type:RecurringOrderSetCustomFieldAction) update action.
      When there has not been a Custom Field with the `name` on the Order before, an [Order Custom Field Added](ctp:api:type:RecurringOrderCustomFieldAddedMessage) Message is generated instead.
