#%RAML 1.0 DataType
(package): Message
type: Message
(beta): true
displayName: RecurringOrderStateTransitionMessage
discriminatorValue: RecurringOrderStateTransition
description: |
  Generated after a successful [Transition State](ctp:api:type:RecurringOrderTransitionStateAction) update action.
properties:
  state:
    type: StateReference
    description: |
      [RecurringOrderState](ctp:api:type:RecurringOrderState) after the [Transition State](ctp:api:type:RecurringOrderTransitionStateAction) update action.
  oldState?:
    type: StateReference
    description: |
      [RecurringOrderState](ctp:api:type:RecurringOrderState) before the [Transition State](ctp:api:type:RecurringOrderTransitionStateAction) update action.
  force:
    type: boolean
    description: |
      Whether [State](ctp:api:type:State) transition validations were turned off during the [Transition State](ctp:api:type:RecurringOrderTransitionStateAction) update action.
