#%RAML 1.0 DataType
(package): Message
(docs-uri): https://docs.commercetools.com/http-api-projects-messages.html#review-rating-set
type: Message
displayName: ReviewRatingSetMessage
discriminatorValue: ReviewRatingSet
description: |
  Generated after a successful [Set Rating](ctp:api:type:ReviewSetRatingAction) update action.
properties:
  oldRating?:
    type: number
    description: |
      The `rating` of the [Review](ctp:api:type:Review) before the [Set Rating](ctp:api:type:ReviewSetRatingAction) update action.
  newRating?:
    type: number
    description: |
      The `rating` of the [Review](ctp:api:type:Review) after the [Set Rating](ctp:api:type:ReviewSetRatingAction) update action.
  includedInStatistics:
    type: boolean
    description: |
      Whether the [Review](ctp:api:type:Review) was taken into account in the ratings statistics of the target.
  target?:
    type: Reference
    description: |
      [Reference](ctp:api:type:Reference) to the resource that the [Review](ctp:api:type:Review) belongs to.
