#%RAML 1.0 DataType
(package): Message
(docs-uri): https://docs.commercetools.com/api/projects/messages#standalone-price-staged-changes-removed
type: Message
displayName: StandalonePriceStagedChangesRemovedMessage
discriminatorValue: StandalonePriceStagedChangesRemoved
description: |
  Generated after a successful [Remove Staged Changes](ctp:api:type:StandalonePriceRemoveStagedChangesAction) update action.
properties:
  stagedChanges:
    type: StagedStandalonePrice
    description: |
      Removed changes of the [StandalonePrice](ctp:api:type:StandalonePrice) after the [Remove Staged Changes](ctp:api:type:StandalonePriceRemoveStagedChangesAction) update action.
