#%RAML 1.0 DataType
(package): Message
(docs-uri): https://docs.commercetools.com/api/projects/messages#standalone-price-deleted
type: Message
displayName: StandalonePriceDeletedMessage
discriminatorValue: StandalonePriceDeleted
description: |
  Generated after a successful [Delete StandalonePrice](/../api/projects/standalone-prices#delete-standaloneprice) request.
