#%RAML 1.0 DataType
(package): Message
(docs-uri): https://docs.commercetools.com/api/message-types#standalonepricevaluechangedmessage
type: Message
displayName: StandalonePriceValueChangedMessage
discriminatorValue: StandalonePriceValueChanged
description: |
  Generated after a successful [Change Value](ctp:api:types:StandalonePriceChangeValueAction) update action.
properties:
  value:
    type: Money
    description: |
      The new value of the updated StandalonePrice.
