#%RAML 1.0 DataType
(package): Message
(docs-uri): https://docs.commercetools.com/api/message-types#standalonepricediscountsetmessage
type: Message
displayName: StandalonePriceDiscountSetMessage
discriminatorValue: StandalonePriceDiscountSet
description: |
  Emitted when the affected StandalonePrice is updated based on a [Product Discount](ctp:api:type:ProductDiscount) being applied.
properties:
  discounted?:
    type: DiscountedPrice
    description: |
      The new `discounted` value of the updated StandalonePrice.
