#%RAML 1.0 DataType
(package): Message
type: Message
displayName: StoreTermsOfServiceUrlSetMessage
discriminatorValue: StoreTermsOfServiceUrlSet
description: |
  Generated after a successful [Set Terms Of Service Url](ctp:api:type:StoreSetTermsOfServiceUrlAction) update action.
properties:
  termsOfServiceUrl?:
    type: string
    description: |
      The `termsOfServiceUrl` of the [Store](ctp:api:type:Store) after the [Set Terms Of Service Url](ctp:api:type:StoreSetTermsOfServiceUrlAction) update action.
