#%RAML 1.0 DataType
(package): Message
(docs-uri): https://docs.commercetools.com/http-api-projects-messages.html#store-created
type: Message
displayName: StoreCreatedMessage
discriminatorValue: StoreCreated
description: |
  Generated after a successful [Create Store](/../api/projects/stores#create-store) request.
properties:
  name?:
    type: LocalizedString
    description: |
      The `name` of the [Store](ctp:api:type:Store) that was created.
  languages?:
    type: string[]
    description: |
      Languages of the [Store](ctp:api:type:Store) that was created. Languages are represented as [IETF language tags](https://en.wikipedia.org/wiki/IETF_language_tag).
  distributionChannels:
    type: array
    items: ChannelReference
    description: |
      [Distribution Channels](ctp:api:type:ChannelRoleEnum) of the [Store](ctp:api:type:Store) that was created.
  supplyChannels:
    type: array
    items: ChannelReference
    description: |
      [Supply Channels](ctp:api:type:ChannelRoleEnum) of the [Store](ctp:api:type:Store) that was created.
  productSelections:
    type: array
    items: ProductSelectionSetting
    description: |
      [ProductSelectionSettings](ctp:api:type:ProductSelectionSetting) of the [Store](ctp:api:type:Store) that was created.
  custom?:
    type: CustomFields
    description: |
      [Custom Fields](ctp:api:type:CustomFields) on the [Store](ctp:api:type:Store) that was created.
