#%RAML 1.0 DataType
(package): Message
type: Message
(beta): true
displayName: VariantPublishedMessage
discriminatorValue: VariantPublished
description: |
  Generated after a successful [Publish](ctp:api:type:VariantPublishAction) update action.
properties:
  product:
    type: ProductReference
    description: |
      Reference to the Product containing the Variant.
