#%RAML 1.0 DataType
(package): Message
type: Message
(beta): true
displayName: VariantCreatedMessage
discriminatorValue: VariantCreated
description: |
  Generated after a successful [Create Variant](/../api/projects/variants#create-variant) request.
properties:
  id:
    type: string
    description: |
      Unique identifier of the Variant.
  productId:
    type: string
    description: |
      Unique identifier of the Product to which the Variant belongs.
  variantId:
    type: integer
    description: |
      Unique identifier of the Variant within its parent Product.
  key?:
    type: string
    description: |
      User-defined unique identifier of the Variant.
  sku?:
    type: string
    description: |
      SKU of the Variant.
  attributes?:
    type: Attribute[]
    description: |
      Attributes of the Variant.
  assets?:
    type: Asset[]
    description: |
      Assets of the Variant.
  images?:
    type: Image[]
    description: |
      Images of the Variant.
  publish:
    type: boolean
    description: |
      Whether the Variant was published.
