#%RAML 1.0 DataType
(package): BusinessUnit
(docs-uri): https://docs.commercetools.com/api/projects/business-units#set-default-billing-address-id
type: BusinessUnitUpdateAction
displayName: BusinessUnitSetDefaultBillingAddressAction
discriminatorValue: setDefaultBillingAddress
example: !include ../../../examples/BusinessUnit/BusinessUnitSetDefaultBillingAddressAction.json
description: |
  Setting the default billing address on a [Business Unit](ctp:api:type:BusinessUnit) generates the [BusinessUnitDefaultBillingAddressSet](ctp:api:type:BusinessUnitDefaultBillingAddressSetMessage) Message.
properties:
  addressId?:
    type: string
    description: |
      ID of the address to add as a billing address. Either `addressId` or `addressKey` is required.
  addressKey?:
    type: string
    description: |
      Key of the address to add as a billing address. Either `addressId` or `addressKey` is required.
