#%RAML 1.0 DataType
(package): BusinessUnit
(docs-uri): https://docs.commercetools.com/api/projects/business-units#add-billing-address-id
type: BusinessUnitUpdateAction
displayName: BusinessUnitAddBillingAddressIdAction
discriminatorValue: addBillingAddressId
example: !include ../../../examples/BusinessUnit/BusinessUnitAddBillingAddressIdAction.json
description: |
  Adding a billing address to a [Business Unit](ctp:api:type:BusinessUnit) generates a [BusinessUnitBillingAddressAdded](ctp:api:type:BusinessUnitBillingAddressAddedMessage) Message.
properties:
  addressId?:
    type: string
    description: |
      ID of the address to add as a billing address. Either `addressId` or `addressKey` is required.
  addressKey?:
    type: string
    description: |
      Key of the address to add as a billing address. Either `addressId` or `addressKey` is required.
