#%RAML 1.0 DataType
(package): BusinessUnit
type: BusinessUnitUpdateAction
displayName: BusinessUnitRemoveBillingAddressIdAction
discriminatorValue: removeBillingAddressId
example: !include ../../../examples/BusinessUnit/BusinessUnitRemoveBillingAddressIdAction.json
description: |
  Removing a billing address from a [Business Unit](ctp:api:type:BusinessUnit) generates a [BusinessUnitBillingAddressRemoved](ctp:api:type:BusinessUnitBillingAddressRemovedMessage) Message.
properties:
  addressId?:
    type: string
    description: |
      ID of the address to be removed from `billingAddressIds`. Either `addressId` or `addressKey` is required.
  addressKey?:
    type: string
    description: |
      Key of the address to be removed from `billingAddressIds`. Either `addressId` or `addressKey` is required.
