#%RAML 1.0 DataType
(package): BusinessUnit
type: BusinessUnitUpdateAction
displayName: BusinessUnitSetStoreModeAction
discriminatorValue: setStoreMode
example: !include ../../../examples/BusinessUnit/BusinessUnitSetStoreModeAction.json
description: |
  Only Business Units of type `Division` can be have a store mode of `FromParent`. Changing the `storeMode` to `FromParent` empties the `stores` array on the BusinessUnit.
  This update action generates a [BusinessUnitStoreModeChanged](ctp:api:type:BusinessUnitStoreModeChangedMessage) Message.
properties:
  storeMode:
    type: BusinessUnitStoreMode
    description: |
      Set to `Explicit` to specify Stores for the Business Unit. Set to `FromParent` to inherit Stores from a parent.
  stores?:
    type: StoreResourceIdentifier[]
    description: |
      Set the [Stores](ctp:api:type:Store) the Business Unit is associated with. Can only be set if `storeMode` is `Explicit`.
