#%RAML 1.0 DataType
(package): BusinessUnit
type: BusinessUnitUpdateAction
displayName: BusinessUnitAddAssociateAction
discriminatorValue: addAssociate
example: !include ../../../examples/BusinessUnit/BusinessUnitAddAssociateAction.json
description: |
  Adding an Associate to a [Business Unit](ctp:api:type:BusinessUnit) generates a [BusinessUnitAssociateAdded](ctp:api:type:BusinessUnitAssociateAddedMessage) Message.
properties:
  associate:
    type: AssociateDraft
    description: |
      The Associate to add.
