#%RAML 1.0 DataType
(package): BusinessUnit
type: BusinessUnitUpdateAction
displayName: BusinessUnitSetStoresAction
discriminatorValue: setStores
example: !include ../../../examples/BusinessUnit/BusinessUnitSetStoresAction.json
description: |
  Sets the Stores of the Business Unit. Can only be set if the Business Unit `storeMode` is `Explicit`.
  [Carts](ctp:api:type:Cart) and [Orders](ctp:api:type:Order) created after the Set Stores update must use the new Stores of
  the Business Unit and, if set, their [Product Selections](ctp:api:type:ProductSelection), and [Channels](ctp:api:type:Channel).
  Orders created before the Set Stores update action remain unchanged.
  Setting the Stores on a Business Unit generates a [BusinessUnitStoresSet](ctp:api:type:BusinessUnitStoresSetMessage) Message.
properties:
  stores?:
    type: StoreResourceIdentifier[]
    description: |
      [Stores](ctp:api:type:Store) to set. Overrides the current list of Stores.
