#%RAML 1.0 DataType
(package): BusinessUnit
(docs-uri): https://docs.commercetools.com/api/projects/business-units#add-address
type: BusinessUnitUpdateAction
displayName: BusinessUnitAddAddressAction
discriminatorValue: addAddress
example: !include ../../../examples/BusinessUnit/BusinessUnitAddAddressAction.json
description: |
  Adding an address to a [Business Unit](ctp:api:type:BusinessUnit) generates a [BusinessUnitAddressAdded](ctp:api:type:BusinessUnitAddressAddedMessage) Message.
properties:
  address:
    type: BaseAddress
    description: |
      Address to add to the addresses of the [Business Unit](ctp:api:type:BusinessUnit).
