#%RAML 1.0 DataType
(package): BusinessUnit
type: BusinessUnitUpdateAction
(beta): true
displayName: BusinessUnitSetUnitTypeAction
discriminatorValue: setUnitType
example: !include ../../../examples/BusinessUnit/BusinessUnitSetUnitType.json
description: |
  This action generates a [BusinessUnitTypeSet](ctp:api:type:BusinessUnitTypeSetMessage) Message.
properties:
  unitType:
    type: BusinessUnitType
    description: |
      New type of the [Business Unit](ctp:api:type:BusinessUnit).

      If `unitType="Company"`, the Business Unit `storeMode`, `associateMode`, and `approvalRuleMode` field values must be `Explicit`.
  parentUnit?:
    type: BusinessUnitResourceIdentifier
    description: |
      New parent unit for the [Business Unit](ctp:api:type:BusinessUnit), if `unitType="Division"`.
