#%RAML 1.0 DataType
(package): BusinessUnit
type: BusinessUnitUpdateAction
displayName: BusinessUnitChangeAssociateModeAction
discriminatorValue: changeAssociateMode
description: |
  Only Business Units of type `Division` can be changed to `ExplicitAndFromParent`.
  This update action generates a [BusinessUnitAssociateModeChanged](ctp:api:type:BusinessUnitAssociateModeChangedMessage) Message.
properties:
  associateMode:
    type: BusinessUnitAssociateMode
    description: |
      The new value for `associateMode`.
