#%RAML 1.0 DataType
(package): Error
type: GraphQLErrorObject
displayName: GraphQLInvalidFieldError
discriminatorValue: InvalidField
description: |
  Returned when a field has an invalid value.
properties:
  code:
    type: string
  field:
    type: string
    description: |
      Name of the field with the invalid value.
  invalidValue:
    type: any
    description: |
      Value invalid for the field.
  allowedValues?:
    type: array
    items: any
    description: |
      Fixed set of allowed values for the field, if any.
