#%RAML 1.0 DataType
(package): Error
type: GraphQLErrorObject
displayName: GraphQLDuplicateEnumValuesError
discriminatorValue: DuplicateEnumValues
description: |
  Returned when an [AttributeEnumType](ctp:api:type:AttributeEnumType) or [AttributeLocalizedEnumType](ctp:api:type:AttributeLocalizedEnumType) contains duplicate keys.
properties:
  code:
    type: string
  duplicates:
    type: string[]
    description: |
      Duplicate keys.
