#%RAML 1.0 DataType
(package): Error
type: GraphQLErrorObject
displayName: GraphQLSearchDeactivatedError
discriminatorValue: SearchDeactivated
description: |
  Returned when the indexing of Product information is deactivated in a Project.

  To activate indexing, call [Change Product Search Indexing Enabled](ctp:api:type:ProjectChangeProductSearchIndexingEnabledAction) and set `enabled` to `true`.
properties:
  code:
    type: string
