#%RAML 1.0 DataType
(package): Error
type: GraphQLErrorObject
(beta): true
displayName: GraphQLBulkOperationMaxItemsExceededError
discriminatorValue: BulkOperationMaxItemsExceeded
description: |
  Returned when a bulk request contains more items than the allowed maximum.

  Reduce the number of items in the request to at most `limit` and retry.
properties:
  code:
    type: string
  limit:
    type: number
    format: int32
    description: |
      Maximum number of items allowed in a single bulk request.
  provided:
    type: number
    format: int32
    description: |
      Number of items provided in the request.
