#%RAML 1.0 DataType
(package): Error
type: GraphQLErrorObject
displayName: GraphQLQueryTimedOutError
discriminatorValue: QueryTimedOut
description: |
  Returned when the query times out.

  If a query constantly times out, please check if it follows the [performance best practices](/../api/predicates/query#performance-considerations).
properties:
  code:
    type: string
