#%RAML 1.0 DataType
(package): Error
type: GraphQLErrorObject
displayName: GraphQLLanguageUsedInStoresError
discriminatorValue: LanguageUsedInStores
description: |
  Returned when a language cannot be removed from a Project as it is being used by a Store.

  The error is returned as a failed response to the [Change Languages](ctp:api:type:ProjectChangeLanguagesAction) update action.
properties:
  code:
    type: string
