#%RAML 1.0 DataType
(package): Error
type: GraphQLErrorObject
displayName: GraphQLMatchingPriceNotFoundError
discriminatorValue: MatchingPriceNotFound
description: |
  Returned when the Product Variant does not have a Price according to the [Product](ctp:api:type:Product) `priceMode` value for a selected currency, country, Customer Group, or Channel.

  The error is returned as a failed response to:

  - [Add LineItem](ctp:api:type:CartAddLineItemAction), [Add CustomLineItem](ctp:api:type:CartAddCustomLineItemAction), and [Add DiscountCode](ctp:api:type:CartAddDiscountCodeAction) update actions on Carts.
  - [Add LineItem](ctp:api:type:StagedOrderAddLineItemAction), [Add CustomLineItem](ctp:api:type:StagedOrderAddCustomLineItemAction), and [Add DiscountCode](ctp:api:type:StagedOrderAddDiscountCodeAction) update actions on Order Edits.
  - [Create Order from Cart](ctp:api:endpoint:/{projectKey}/orders:POST) and [Create Order in Store from Cart](ctp:api:endpoint:/{projectKey}/in-store/orders:POST) requests on Orders.
  - [Create Order from Cart](ctp:api:endpoint:/{projectKey}/me/orders:POST) and [Create Order in Store from Cart](ctp:api:endpoint:/{projectKey}/in-store/me/orders:POST) requests on My Orders.
properties:
  code:
    type: string
  productId:
    type: string
    description: |
      Unique identifier of a [Product](ctp:api:type:Product).
  variantId:
    type: integer
    description: |
      Unique identifier of a [ProductVariant](ctp:api:type:ProductVariant) in the Product.
  currency?:
    type: CurrencyCode
    description: |
      Currency code of the country.
  country?:
    type: CountryCode
    description: |
      Country code of the geographic location.
  customerGroup?:
    type: CustomerGroupReference
    description: |
      Customer Group associated with the Price.
  channel?:
    type: ChannelReference
    description: |
      Channel associated with the Price.
