#%RAML 1.0 DataType
(package): Error
type: GraphQLErrorObject
displayName: GraphQLDuplicateAttributeValueError
discriminatorValue: DuplicateAttributeValue
description: |
  Returned when the `Unique` [AttributeConstraint](ctp:api:type:AttributeConstraintEnum) criteria are not met during an [Update Product](/../api/projects/products#update-product) request.
properties:
  code:
    type: string
  attribute:
    type: Attribute
    description: |
      Conflicting Attributes.
