#%RAML 1.0 DataType
(package): Error
type: GraphQLErrorObject
displayName: GraphQLReferencedResourceNotFoundError
discriminatorValue: ReferencedResourceNotFound
description: |
  Returned when a resource referenced by a [Reference](ctp:api:type:Reference) or a [ResourceIdentifier](ctp:api:type:ResourceIdentifier) could not be found.
properties:
  code:
    type: string
  typeId:
    type: ReferenceTypeId
    description: |
      Type of referenced resource.
  id?:
    type: string
    description: |
      Unique identifier of the referenced resource, if known.
  key?:
    type: string
    description: |
      User-defined unique identifier of the referenced resource, if known.
