#%RAML 1.0 DataType
(package): Error
type: GraphQLErrorObject
displayName: GraphQLBadGatewayError
discriminatorValue: BadGateway
description: |
  Returned when a server-side problem is caused by scaling infrastructure resources.

  The client application should retry the request with exponential backoff up to a point where further delay is unacceptable.
properties:
  code:
    type: string
