#%RAML 1.0 DataType
(package): Error
type: GraphQLErrorObject
displayName: GraphQLAssociateMissingPermissionError
discriminatorValue: AssociateMissingPermission
description: |
  Returned when an [Associate](/projects/business-units#associate) is missing a [Permission](/projects/associate-roles#ctp:api:type:Permission) on a [B2B resource](/associates-overview#b2b-resources).
properties:
  code:
    type: string
  associate:
    type: CustomerResourceIdentifier
    description: |
      [ResourceIdentifier](ctp:api:type:CustomerResourceIdentifier) to the [Associate](ctp:api:type:Associate) that tried to perform the action.
  businessUnit:
    type: BusinessUnitResourceIdentifier
    description: |
      [ResourceIdentifier](ctp:api:type:BusinessUnitResourceIdentifier) to the [BusinessUnit](ctp:api:type:BusinessUnit).
  associateOnBehalf?:
    type: CustomerResourceIdentifier
    description: |
      [ResourceIdentifier](ctp:api:type:CustomerResourceIdentifier) of the [Associate](ctp:api:type:Associate) on whose behalf the action is performed.
  permissions:
    type: Permission[]
    description: |
      The Permissions that the [Associate](ctp:api:type:Associate) performing the action lacks. At least one of these Permissions is needed.
