#%RAML 1.0 DataType
(package): Error
type: GraphQLErrorObject
displayName: GraphQLMoneyOverflowError
discriminatorValue: MoneyOverflow
description: |
  Returned when a money operation overflows the 64-bit integer range.
properties:
  code:
    type: string
