#%RAML 1.0 DataType
(package): Error
type: GraphQLErrorObject
displayName: GraphQLRequiredFieldError
discriminatorValue: RequiredField
description: |
  Returned when a value is not defined for a required field.
properties:
  code:
    type: string
  field:
    type: string
    description: |
      Name of the field missing the value.
