#%RAML 1.0 DataType
(package): Error
type: GraphQLErrorObject
displayName: GraphQLMissingTaxRateForCountryError
discriminatorValue: MissingTaxRateForCountry
description: |
  Returned when the Tax Category of at least one of the `lineItems`, `customLineItems`, or `shippingInfo` in the [Cart](ctp:api:type:Cart) is missing the [TaxRate](ctp:api:type:TaxRate) matching `country` and `state` given in the `shippingAddress` of that Cart.

  The error is returned as a failed response to:

  - [Add LineItem](ctp:api:type:CartAddLineItemAction), [Add CustomLineItem](ctp:api:type:CartAddCustomLineItemAction), [Set Shipping Address](ctp:api:type:CartSetShippingAddressAction), [Add LineItem](ctp:api:type:MyCartAddLineItemAction), [Add LineItem](ctp:api:type:StagedOrderAddLineItemAction), and [Add CustomLineItem](ctp:api:type:StagedOrderAddCustomLineItemAction) update actions
  - [Create Order from Cart](ctp:api:endpoint:/{projectKey}/orders:POST) and [Create Order in Store from Cart](ctp:api:endpoint:/{projectKey}/in-store/orders:POST) requests.
properties:
  code:
    type: string
  taxCategoryId:
    type: string
    description: |
      Unique identifier of the [TaxCategory](ctp:api:type:TaxCategory).
  country?:
    type: CountryCode
    description: |
      Country code of the geographic location.
  state?:
    type: string
    description: |
      State within the country, such as Texas in the United States.
