#%RAML 1.0 DataType
(package): Error
type: GraphQLErrorObject
displayName: GraphQLReferenceExistsError
discriminatorValue: ReferenceExists
description: |
  Returned when a resource cannot be deleted because it is being referenced by another resource.
properties:
  code:
    type: string
  referencedBy?:
    type: ReferenceTypeId
    description: |
      Type of referenced resource.
