#%RAML 1.0 DataType
(package): Error
type: GraphQLErrorObject
displayName: GraphQLExtensionChainTooDeepError
discriminatorValue: ExtensionChainTooDeep
(beta): true
description: |
  Returned when the Extension dependency chain exceeds 3 layers.
properties:
  code:
    type: string
