#%RAML 1.0 DataType
(package): Error
type: GraphQLErrorObject
displayName: GraphQLCircularDependencyError
discriminatorValue: CircularDependency
(beta): true
description: |
  Returned when a circular reference is detected among Extension dependencies.
properties:
  code:
    type: string
