#%RAML 1.0 DataType
(package): Error
type: object
displayName: GraphQLErrorObject
discriminator: code
description: Represents a single error.
properties:
  code:
    type: string
    description: |
      Error identifier.
  //:
    type: any
    description: |
      Error-specific additional fields.
