#%RAML 1.0 DataType
(package): Error
type: GraphQLErrorObject
displayName: GraphQLResourceSizeLimitExceededError
discriminatorValue: ResourceSizeLimitExceeded
description: |
  Returned when the resource exceeds the maximum allowed size of 16 MB.
properties:
  code:
    type: string
