#%RAML 1.0 DataType
(package): Error
type: GraphQLErrorObject
displayName: GraphQLInvalidJsonInputError
discriminatorValue: InvalidJsonInput
description: |
  Returned when an invalid JSON input has been sent.
  Either the JSON is syntactically incorrect or does not conform to the expected shape (for example is missing a required field).

  The client application should validate the input according to the constraints described in the error message before sending the request.
properties:
  code:
    type: string
  detailedErrorMessage:
    type: string
    description: Further explanation about why the JSON is invalid.
