#%RAML 1.0 DataType
(package): Error
type: GraphQLErrorObject
displayName: GraphQLPendingOperationError
discriminatorValue: PendingOperation
description: |
  Returned when a previous conflicting operation is still pending and needs to finish before the request can succeed.

  The client application should retry the request with exponential backoff up to a point where further delay is unacceptable.
  If the error persists, report it using the [Support Portal](https://support.commercetools.com).
properties:
  code:
    type: string
