#%RAML 1.0 DataType
(package): Error
type: GraphQLErrorObject
displayName: GraphQLMissingDependencyError
discriminatorValue: MissingDependency
(beta): true
description: |
  Returned when a referenced Extension does not exist or is not applicable to the same trigger.
properties:
  code:
    type: string
