#%RAML 1.0 DataType
(package): Error
type: GraphQLErrorObject
displayName: GraphQLQueryComplexityLimitExceededError
discriminatorValue: QueryComplexityLimitExceeded
properties:
  code:
    type: string
