#%RAML 1.0 DataType
(package): Error
type: GraphQLErrorObject
displayName: GraphQLOverCapacityError
discriminatorValue: OverCapacity
description: |
  Returned when the service is having trouble handling the load.

  The client application should retry the request with exponential backoff up to a point where further delay is unacceptable.
properties:
  code:
    type: string
