#%RAML 1.0 DataType
(package): Error
type: GraphQLErrorObject
displayName: GraphQLLineItemQuantityAboveLimitError
discriminatorValue: LineItemQuantityAboveLimit
description: |
  Returned when attempting to create or update a [Cart](ctp:api:type:Cart) with a Line Item whose quantity exceeds the `maxCartQuantity` limit defined in the [InventoryEntry](ctp:api:type:InventoryEntry) for that Line Item's SKU.
properties:
  code:
    type: string
  quantity:
    type: integer
    description: |
      The quantity that was requested.
  maxCartQuantity:
    type: integer
    description: |
      The maximum quantity allowed for this Line Item.
  lineItem?:
    type: string
    description: |
      Reference to the Line Item that caused the error.
