#%RAML 1.0 DataType

displayName: AttributeDefinition
uses:
    api: ../types.lib.raml
type: object
(generate-collection): true
properties:
    type:
        (generator-type): api.AttributeType
        type: api.AttributeType |
            api.AttributeBooleanType |
            api.AttributeDateTimeType |
            api.AttributeDateType |
            api.AttributeTimeType |
            api.AttributeEnumType |
            api.AttributeLocalizedEnumType |
            api.AttributeMoneyType |
            api.AttributeNestedType |
            api.AttributeNumberType |
            api.AttributeReferenceType |
            api.AttributeSetType |
            api.AttributeTextType
    name:
        type: string
    label:
        type: api.LocalizedString
    isRequired:
        type: boolean
    attributeConstraint:
        (generator-type): string
        type: api.AttributeConstraintEnum
    inputTip?:
        type: api.LocalizedString
    inputHint:
        type: api.TextInputHint
    isSearchable:
        type: boolean
