#%RAML 1.0 DataType
(package): ProductType


type: ProductTypeUpdateAction
displayName: ProductTypeChangePlainEnumValueLabelAction
discriminatorValue: changePlainEnumValueLabel
properties:
    attributeName:
        type: string
    newValue:
        type: AttributePlainEnumValue
