#%RAML 1.0 DataType

uses:
    api: ../types.lib.raml
type: api.ProductTypeUpdateAction
displayName: ProductTypeChangeLocalizedEnumValueLabelAction
discriminatorValue: changeLocalizedEnumValueLabel
properties:
    attributeName:
        type: string
    newValue:
        type: api.AttributeLocalizedEnumValue
