#%RAML 1.0 DataType
(package): ProductType
(docs-uri): https://docs.commercetools.com/http-api-projects-productTypes.html#producttype

displayName: ProductType
(updateType): ProductTypeUpdate
type: Resource
properties:
  key?:
    type: string
    (hasSimpleUpdateAction): setKey
  name:
    type: string
    (hasSimpleUpdateAction): changeName
  description:
    type: string
    (hasSimpleUpdateAction): changeDescription
  attributes?:
    type: AttributeDefinition[]
    (hasUpdateActions):
      - action: addAttributeDefinition
        docsAnchor: add-attributedefinition
        fields:
          attribute: AttributeDefinitionDraft
      - action: removeAttributeDefinition
        docsAnchor: remove-attributedefinition
        fields:
          name: string
      - action: changeAttributeName
        docsAnchor: change-attributedefinition-name
        fields:
          attributeName: string
          newAttributeName: string
      - action: changeLabel
        docsAnchor: change-attributedefinition-label
        fields:
          attributeName: string
          label: LocalizedString
      - action: setInputTip
        docsAnchor: set-attributedefinition-inputtip
        fields:
          attributeName: string
          inputTip?: LocalizedString
      - action: addPlainEnumValue
        docsAnchor: add-plainenumvalue-to-attributedefinition
        fields:
          attributeName: string
          value: AttributePlainEnumValue
      - action: addLocalizedEnumValue
        docsAnchor: add-localizableenumvalue-to-attributedefinition
        fields:
          attributeName: string
          value: AttributeLocalizedEnumValue
      - action: removeEnumValues
        docsAnchor: remove-enumvalues-from-attributedefinition
        fields:
          attributeName: string
          keys: string[]
      - action: changeAttributeOrderByName
        docsAnchor: change-the-order-of-attributedefinitions
        fields:
          attributeNames: string[]
      - action: changePlainEnumValueOrder
        docsAnchor: change-the-order-of-enumvalues
        fields:
          attributeName: string
          values: AttributePlainEnumValue[]
      - action: changeLocalizedEnumValueOrder
        docsAnchor: change-the-order-of-localizedenumvalues
        fields:
          attributeName: string
          values: AttributeLocalizedEnumValue[]
      - action: changeEnumKey
        docsAnchor: change-the-key-of-an-enumvalue
        fields:
          attributeName: string
          key: string
          newKey: string
      - action: changePlainEnumValueLabel
        docsAnchor: change-the-label-of-an-enumvalue
        fields:
          attributeName: string
          newValue: AttributePlainEnumValue
      - action: changeLocalizedEnumValueLabel
        docsAnchor: change-the-label-of-an-enumvalue
        fields:
          attributeName: string
          newValue: AttributeLocalizedEnumValue
      - action: changeIsSearchable
        docsAnchor: change-attributedefinition-issearchable
        fields:
          attributeName: string
          isSearchable: boolean
      - action: changeInputHint
        docsAnchor: change-attributedefinition-inputhint
        fields:
          attributeName: string
          newValue: TextInputHint
      - action: changeAttributeConstraint
        docsAnchor: change-attributedefinition-attributeconstraint
        fields:
          attributeName: string
          newValue: AttributeConstraintEnumDraft
