#%RAML 1.0 DataType

uses:
    api: ../types.lib.raml
type: api.Reference
displayName: ProductTypeReference
discriminatorValue: product-type
(generate-collection): true
properties:
    obj?:
        type: api.ProductType
