#%RAML 1.0 DataType

displayName: ProductTypeDraft

type: object
properties:
    key?:
        type: string
    name:
        type: string
    description:
        type: string
    attributes?:
        type: AttributeDefinitionDraft[]
