#%RAML 1.0 DataType

displayName: ProductType
uses:
    api: ../types.lib.raml
type: api.Resource
(generate-collection): true
properties:
    key?:
        type: string
    name:
        type: string
    description:
        type: string
    attributes?:
        type: api.AttributeDefinition[]
