#%RAML 1.0 DataType
(package): ProductType
(docs-uri): https://docs.commercetools.com/http-api-types.html#reference-types


type: Reference
displayName: ProductTypeReference
discriminatorValue: product-type
properties:
    obj?:
        type: ProductType
