#%RAML 1.0 DataType
(package): Project
type: ProjectUpdateAction
displayName: ProjectChangeProductSearchIndexingEnabledAction
discriminatorValue: changeProductSearchIndexingEnabled
example: !include ../../../examples/Project/ProjectChangeProductSearchIndexingEnabledAction.json
properties:
  enabled:
    type: boolean
    description: |
      - If `false`, the indexing of [Product](ctp:api:type:Product) information will stop and the [Product Projection Search](/../api/projects/product-projection-search) as well as the [Product Suggestions](/../api/projects/products-suggestions) endpoint will not be available anymore for this Project. The Project's [SearchIndexingConfiguration](ctp:api:type:SearchIndexingConfiguration) `status` for `products` will be changed to `"Deactivated"`.
      - If `true`, the indexing of [Product](ctp:api:type:Product) information will start and the [Product Projection Search](/../api/projects/product-projection-search) as well as the [Product Suggestions](/../api/projects/products-suggestions) endpoint will become available soon after for this Project. Proportional to the amount of information being indexed, the Project's [SearchIndexingConfiguration](ctp:api:type:SearchIndexingConfiguration) `status` for `products` will be shown as `"Indexing"` during this time. As soon as the indexing has finished, the configuration status will be changed to `"Activated"` making the aforementioned endpoints fully available for this Project.
  mode?:
    type: ProductSearchIndexingMode
    description: |
      Controls whether the action should apply to [Product Projection Search](/../api/projects/product-projection-search) or to [Product Search](/../api/projects/product-search).
    default: ProductProjectionsSearch
