#%RAML 1.0 DataType
(package): Project
type: ProjectUpdateAction
displayName: ProjectSetDiscountsConfigurationAction
discriminatorValue: setDiscountsConfiguration
example: !include ../../../examples/Project/ProjectSetDiscountsConfigurationAction.json
properties:
  discountsConfiguration:
    type: DiscountsConfiguration
    description: |
      Configuration for the behavior of Cart and Product Discounts in the Project.
