#%RAML 1.0 DataType
(package): Project
type: ProjectUpdateAction
displayName: ProjectChangeMessagesConfigurationAction
discriminatorValue: changeMessagesConfiguration
example: !include ../../../examples/Project/updates/ProjectChangeMessagesConfigurationAction.json
properties:
  messagesConfiguration:
    type: MessagesConfigurationDraft
    description: Configuration for the [Messages Query](/../api/projects/messages) feature.
