#%RAML 1.0 DataType
(package): Project
type: ProjectUpdateAction
displayName: ProjectChangeNameAction
discriminatorValue: changeName
example: !include ../../../examples/Project/ProjectChangeNameAction.json
properties:
  name:
    type: string
    description: |
      New value to set. Must not be empty.
