#%RAML 1.0 DataType
(package): Project
(docs-uri): https://docs.commercetools.com/api/projects/project#change-languages
type: ProjectUpdateAction
displayName: ProjectChangeLanguagesAction
discriminatorValue: changeLanguages
example: !include ../../../examples/Project/ProjectChangeLanguagesAction.json
description: |
  If a language is used by a [Store](ctp:api:type:Store), it cannot be deleted. Attempts to delete such language will lead to [LanguageUsedInStores](/../api/errors#projects-400-language-used-in-stores) errors.
properties:
  languages:
    type: Locale[]
    description: |
      New value to set. Must not be empty.
