#%RAML 1.0 DataType
(package): Project
type: ProjectUpdateAction
(beta): true
displayName: ProjectChangeBusinessUnitSearchStatusAction
discriminatorValue: changeBusinessUnitSearchStatus
example: !include ../../../examples/Project/ProjectChangeBusinessUnitSearchStatusAction.json
properties:
  status:
    type: BusinessUnitSearchStatus
    description: Activates or deactivates the [Search Business Units](ctp:api:endpoint:/{projectKey}/business-units/search:POST) feature. Activation will trigger building a search index for the Business Units in the Project.
