#%RAML 1.0 DataType
(package): Project
type: ProjectUpdateAction
displayName: ProjectChangePriceRoundingModeAction
discriminatorValue: changePriceRoundingMode
example: !include ../../../examples/Project/ProjectChangePriceRoundingModeAction.json
properties:
  priceRoundingMode:
    type: RoundingMode
    description: Project-level default rounding mode for calculating the total prices on [LineItems](ctp:api:type:LineItem) and [CustomLineItems](ctp:api:type:CustomLineItem). See [CartsConfiguration](ctp:api:type:CartsConfiguration).
