#%RAML 1.0 DataType
(package): Project
(docs-uri): https://docs.commercetools.com/api/projects/project#change-my-business-unit-status-on-creation
type: ProjectUpdateAction
displayName: ProjectChangeBusinessUnitStatusOnCreationAction
discriminatorValue: changeMyBusinessUnitStatusOnCreation
example: !include ../../../examples/Project/ProjectChangeBusinessUnitStatusOnCreationAction.json
properties:
  status:
    type: BusinessUnitConfigurationStatus
    description: |
      Status for Business Units created using the [My Business Unit endpoint](/../api/projects/me-business-units#create-businessunit).
