#%RAML 1.0 DataType
(package): Me
(docs-uri): https://docs.commercetools.com/http-api-projects-customers.html#customer
displayName: MyCustomer
(updateType): MyCustomerUpdate
(actionType): MyCustomerUpdateAction
type: BaseResource
properties:
  id:
    (identifier): true
    type: string
  version:
    type: number
    format: int64
  createdAt:
    type: datetime
  lastModifiedAt:
    type: datetime
  lastModifiedBy?:
    type: LastModifiedBy
  createdBy?:
    type: CreatedBy
  customerNumber?:
    type: string
  email:
    type: string
  password:
    type: string
  firstName?:
    type: string
  lastName?:
    type: string
  middleName?:
    type: string
  title?:
    type: string
  dateOfBirth?:
    type: date-only
  companyName?:
    type: string
  vatId?:
    type: string
  addresses:
    type: Address[]
  defaultShippingAddressId?:
    type: string
  shippingAddressIds?:
    type: string[]
  defaultBillingAddressId?:
    type: string
  billingAddressIds?:
    type: string[]
  isEmailVerified:
    type: boolean
  externalId?:
    type: string
  customerGroup?:
    type: CustomerGroupReference
  custom?:
    type: CustomFields
  locale?:
    type: string
  salutation?:
    type: string
  key?:
    type: string
  stores?:
    type: StoreKeyReference[]
