#%RAML 1.0 DataType
(package): Subscription
type: object
displayName: ChangeSubscription
properties:
  resourceTypeId:
    type: string
    description: 'The following list of `resourceTypeId` are currently supported:'
