#%RAML 1.0 DataType
(package): Subscription
(docs-uri): https://docs.commercetools.com/http-api-projects-subscriptions.html#cloudevents-format-preview
type: DeliveryFormat
displayName: DeliveryCloudEventsFormat
discriminatorValue: CloudEvents
properties:
  cloudEventsVersion:
    type: string
    enum:
      - '0.1'
