#%RAML 1.0 DataType
(package): Subscription
(docs-uri): https://docs.commercetools.com/http-api-projects-subscriptions.html#payloadnotincluded
displayName: PayloadNotIncluded
type: object
properties:
  reason:
    type: string
  payloadType:
    type: string
