#%RAML 1.0 DataType
(package): Subscription
(docs-uri): https://docs.commercetools.com/http-api-projects-subscriptions.html#resourceupdated-payload
type: SubscriptionDelivery
displayName: ResourceUpdatedDelivery
discriminatorValue: ResourceUpdated
properties:
  version:
    type: number
    format: int64
  oldVersion:
    type: number
    format: int64
  modifiedAt:
    type: datetime
