#%RAML 1.0 DataType
(package): Subscription
(docs-uri): https://docs.commercetools.com/http-api-projects-subscriptions.html#delivery
type: object
displayName: SubscriptionDelivery
discriminator: notificationType
properties:
  projectKey:
    type: string
  notificationType:
    type: string
  resource:
    type: Reference
  resourceUserProvidedIdentifiers?:
    type: UserProvidedIdentifiers
