#%RAML 1.0 DataType
(package): Subscription
(docs-uri): https://docs.commercetools.com/http-api-projects-subscriptions.html#subscriptiondraft
type: object
displayName: SubscriptionDraft
properties:
  changes?:
    type: ChangeSubscription[]
  destination:
    type: Destination
  key?:
    type: string
  messages?:
    type: MessageSubscription[]
  format?:
    type: DeliveryFormat
