#%RAML 1.0 DataType
(package): Subscription
(docs-uri): https://docs.commercetools.com/http-api-projects-subscriptions.html#subscriptiondraft
type: object
displayName: SubscriptionDraft
properties:
  changes?:
    type: ChangeSubscription[]
    description: ''
  destination:
    type: Destination
    description: ''
  key?:
    type: string
    description: ''
  messages?:
    type: MessageSubscription[]
    description: ''
  format?:
    type: DeliveryFormat
    description: ''
