package:
  type: string
  allowedTargets: TypeDeclaration
identifier:
  type: boolean
  allowedTargets: TypeDeclaration
placeholderParam:
  type: object
  allowedTargets: TypeDeclaration
  properties:
    paramName: string
    template: string
    placeholder: string
builder:
  type: array
  items:
    type: object
    properties:
      paramNames: string[]
  allowedTargets: TypeDeclaration
