generator-ignore:
    type: boolean
    allowedTargets: TypeDeclaration
generator-ignore-strict:
    type: boolean
    allowedTargets: TypeDeclaration
generator-type:
    type: string
    allowedTargets: TypeDeclaration
generate-collection:
    type: boolean
    allowedTargets: TypeDeclaration
