PagedQueryResponse: !include PagedQueryResponse.raml
Update: !include Update.raml
UpdateAction: !include UpdateAction.raml
CartDiscount: !include cart-discount/CartDiscount.raml
CartDiscountCustomLineItemsTarget: !include cart-discount/CartDiscountCustomLineItemsTarget.raml
CartDiscountDraft: !include cart-discount/CartDiscountDraft.raml
CartDiscountLineItemsTarget: !include cart-discount/CartDiscountLineItemsTarget.raml
CartDiscountPagedQueryResponse: !include cart-discount/CartDiscountPagedQueryResponse.raml
CartDiscountReference: !include cart-discount/CartDiscountReference.raml
CartDiscountShippingCostTarget: !include cart-discount/CartDiscountShippingCostTarget.raml
CartDiscountTarget: !include cart-discount/CartDiscountTarget.raml
CartDiscountUpdate: !include cart-discount/CartDiscountUpdate.raml
CartDiscountUpdateAction: !include cart-discount/CartDiscountUpdateAction.raml
CartDiscountValue: !include cart-discount/CartDiscountValue.raml
CartDiscountValueAbsolute: !include cart-discount/CartDiscountValueAbsolute.raml
CartDiscountValueGiftLineItem: !include cart-discount/CartDiscountValueGiftLineItem.raml
CartDiscountValueRelative: !include cart-discount/CartDiscountValueRelative.raml
MultiBuyCustomLineItemsTarget: !include cart-discount/MultiBuyCustomLineItemsTarget.raml
MultiBuyLineItemsTarget: !include cart-discount/MultiBuyLineItemsTarget.raml
SelectionMode: !include cart-discount/SelectionMode.raml
StackingMode: !include cart-discount/StackingMode.raml
CartDiscountChangeCartPredicateAction: !include cart-discount/updates/CartDiscountChangeCartPredicateAction.raml
CartDiscountChangeIsActiveAction: !include cart-discount/updates/CartDiscountChangeIsActiveAction.raml
CartDiscountChangeNameAction: !include cart-discount/updates/CartDiscountChangeNameAction.raml
# yamllint disable-line rule:line-length
CartDiscountChangeRequiresDiscountCodeAction: !include cart-discount/updates/CartDiscountChangeRequiresDiscountCodeAction.raml
CartDiscountChangeSortOrderAction: !include cart-discount/updates/CartDiscountChangeSortOrderAction.raml
CartDiscountChangeStackingModeAction: !include cart-discount/updates/CartDiscountChangeStackingModeAction.raml
CartDiscountChangeTargetAction: !include cart-discount/updates/CartDiscountChangeTargetAction.raml
CartDiscountChangeValueAction: !include cart-discount/updates/CartDiscountChangeValueAction.raml
CartDiscountSetCustomFieldAction: !include cart-discount/updates/CartDiscountSetCustomFieldAction.raml
CartDiscountSetCustomTypeAction: !include cart-discount/updates/CartDiscountSetCustomTypeAction.raml
CartDiscountSetDescriptionAction: !include cart-discount/updates/CartDiscountSetDescriptionAction.raml
CartDiscountSetValidFromAction: !include cart-discount/updates/CartDiscountSetValidFromAction.raml
CartDiscountSetValidFromAndUntilAction: !include cart-discount/updates/CartDiscountSetValidFromAndUntilAction.raml
CartDiscountSetValidUntilAction: !include cart-discount/updates/CartDiscountSetValidUntilAction.raml
Cart: !include cart/Cart.raml
CartDraft: !include cart/CartDraft.raml
CartOrigin: !include cart/CartOrigin.raml
CartPagedQueryResponse: !include cart/CartPagedQueryResponse.raml
CartReference: !include cart/CartReference.raml
CartState: !include cart/CartState.raml
CartUpdate: !include cart/CartUpdate.raml
CartUpdateAction: !include cart/CartUpdateAction.raml
ClassificationShippingRateInput: !include cart/ClassificationShippingRateInput.raml
ClassificationShippingRateInputDraft: !include cart/ClassificationShippingRateInputDraft.raml
CustomLineItem: !include cart/CustomLineItem.raml
CustomLineItemDraft: !include cart/CustomLineItemDraft.raml
DiscountCodeInfo: !include cart/DiscountCodeInfo.raml
DiscountCodeState: !include cart/DiscountCodeState.raml
DiscountedLineItemPortion: !include cart/DiscountedLineItemPortion.raml
DiscountedLineItemPrice: !include cart/DiscountedLineItemPrice.raml
DiscountedLineItemPriceForQuantity: !include cart/DiscountedLineItemPriceForQuantity.raml
ExternalLineItemTotalPrice: !include cart/ExternalLineItemTotalPrice.raml
ExternalTaxAmountDraft: !include cart/ExternalTaxAmountDraft.raml
ExternalTaxRateDraft: !include cart/ExternalTaxRateDraft.raml
InventoryMode: !include cart/InventoryMode.raml
ItemShippingDetails: !include cart/ItemShippingDetails.raml
ItemShippingDetailsDraft: !include cart/ItemShippingDetailsDraft.raml
ItemShippingTarget: !include cart/ItemShippingTarget.raml
LineItem: !include cart/LineItem.raml
LineItemDraft: !include cart/LineItemDraft.raml
LineItemMode: !include cart/LineItemMode.raml
LineItemPriceMode: !include cart/LineItemPriceMode.raml
ReplicaCartDraft: !include cart/ReplicaCartDraft.raml
RoundingMode: !include cart/RoundingMode.raml
ScoreShippingRateInput: !include cart/ScoreShippingRateInput.raml
ScoreShippingRateInputDraft: !include cart/ScoreShippingRateInputDraft.raml
ShippingInfo: !include cart/ShippingInfo.raml
ShippingMethodState: !include cart/ShippingMethodState.raml
ShippingRateInput: !include cart/ShippingRateInput.raml
ShippingRateInputDraft: !include cart/ShippingRateInputDraft.raml
TaxCalculationMode: !include cart/TaxCalculationMode.raml
TaxMode: !include cart/TaxMode.raml
TaxPortion: !include cart/TaxPortion.raml
TaxedItemPrice: !include cart/TaxedItemPrice.raml
TaxedPrice: !include cart/TaxedPrice.raml
CartAddCustomLineItemAction: !include cart/updates/CartAddCustomLineItemAction.raml
CartAddDiscountCodeAction: !include cart/updates/CartAddDiscountCodeAction.raml
CartAddItemShippingAddressAction: !include cart/updates/CartAddItemShippingAddressAction.raml
CartAddLineItemAction: !include cart/updates/CartAddLineItemAction.raml
CartAddPaymentAction: !include cart/updates/CartAddPaymentAction.raml
CartAddShoppingListAction: !include cart/updates/CartAddShoppingListAction.raml
# yamllint disable-line rule:line-length
CartApplyDeltaToCustomLineItemShippingDetailsTargetsAction: !include cart/updates/CartApplyDeltaToCustomLineItemShippingDetailsTargetsAction.raml
# yamllint disable-line rule:line-length
CartApplyDeltaToLineItemShippingDetailsTargetsAction: !include cart/updates/CartApplyDeltaToLineItemShippingDetailsTargetsAction.raml
CartChangeCustomLineItemMoneyAction: !include cart/updates/CartChangeCustomLineItemMoneyAction.raml
CartChangeCustomLineItemQuantityAction: !include cart/updates/CartChangeCustomLineItemQuantityAction.raml
CartChangeLineItemQuantityAction: !include cart/updates/CartChangeLineItemQuantityAction.raml
CartChangeTaxCalculationModeAction: !include cart/updates/CartChangeTaxCalculationModeAction.raml
CartChangeTaxModeAction: !include cart/updates/CartChangeTaxModeAction.raml
CartChangeTaxRoundingModeAction: !include cart/updates/CartChangeTaxRoundingModeAction.raml
CartRecalculateAction: !include cart/updates/CartRecalculateAction.raml
CartRemoveCustomLineItemAction: !include cart/updates/CartRemoveCustomLineItemAction.raml
CartRemoveDiscountCodeAction: !include cart/updates/CartRemoveDiscountCodeAction.raml
CartRemoveItemShippingAddressAction: !include cart/updates/CartRemoveItemShippingAddressAction.raml
CartRemoveLineItemAction: !include cart/updates/CartRemoveLineItemAction.raml
CartRemovePaymentAction: !include cart/updates/CartRemovePaymentAction.raml
CartSetAnonymousIdAction: !include cart/updates/CartSetAnonymousIdAction.raml
CartSetBillingAddressAction: !include cart/updates/CartSetBillingAddressAction.raml
CartSetCartTotalTaxAction: !include cart/updates/CartSetCartTotalTaxAction.raml
CartSetCountryAction: !include cart/updates/CartSetCountryAction.raml
CartSetCustomFieldAction: !include cart/updates/CartSetCustomFieldAction.raml
CartSetCustomLineItemCustomFieldAction: !include cart/updates/CartSetCustomLineItemCustomFieldAction.raml
CartSetCustomLineItemCustomTypeAction: !include cart/updates/CartSetCustomLineItemCustomTypeAction.raml
CartSetCustomLineItemShippingDetailsAction: !include cart/updates/CartSetCustomLineItemShippingDetailsAction.raml
CartSetCustomLineItemTaxAmountAction: !include cart/updates/CartSetCustomLineItemTaxAmountAction.raml
CartSetCustomLineItemTaxRateAction: !include cart/updates/CartSetCustomLineItemTaxRateAction.raml
CartSetCustomShippingMethodAction: !include cart/updates/CartSetCustomShippingMethodAction.raml
CartSetCustomTypeAction: !include cart/updates/CartSetCustomTypeAction.raml
CartSetCustomerEmailAction: !include cart/updates/CartSetCustomerEmailAction.raml
CartSetCustomerGroupAction: !include cart/updates/CartSetCustomerGroupAction.raml
CartSetCustomerIdAction: !include cart/updates/CartSetCustomerIdAction.raml
CartSetDeleteDaysAfterLastModificationAction: !include cart/updates/CartSetDeleteDaysAfterLastModificationAction.raml
CartSetLineItemCustomFieldAction: !include cart/updates/CartSetLineItemCustomFieldAction.raml
CartSetLineItemCustomTypeAction: !include cart/updates/CartSetLineItemCustomTypeAction.raml
CartSetLineItemPriceAction: !include cart/updates/CartSetLineItemPriceAction.raml
CartSetLineItemShippingDetailsAction: !include cart/updates/CartSetLineItemShippingDetailsAction.raml
CartSetLineItemTaxAmountAction: !include cart/updates/CartSetLineItemTaxAmountAction.raml
CartSetLineItemTaxRateAction: !include cart/updates/CartSetLineItemTaxRateAction.raml
CartSetLineItemTotalPriceAction: !include cart/updates/CartSetLineItemTotalPriceAction.raml
CartSetLocaleAction: !include cart/updates/CartSetLocaleAction.raml
CartSetShippingAddressAction: !include cart/updates/CartSetShippingAddressAction.raml
CartSetShippingMethodAction: !include cart/updates/CartSetShippingMethodAction.raml
CartSetShippingMethodTaxAmountAction: !include cart/updates/CartSetShippingMethodTaxAmountAction.raml
CartSetShippingMethodTaxRateAction: !include cart/updates/CartSetShippingMethodTaxRateAction.raml
CartSetShippingRateInputAction: !include cart/updates/CartSetShippingRateInputAction.raml
CartUpdateItemShippingAddressAction: !include cart/updates/CartUpdateItemShippingAddressAction.raml
Category: !include category/Category.raml
CategoryDraft: !include category/CategoryDraft.raml
CategoryPagedQueryResponse: !include category/CategoryPagedQueryResponse.raml
CategoryReference: !include category/CategoryReference.raml
CategoryUpdate: !include category/CategoryUpdate.raml
CategoryUpdateAction: !include category/CategoryUpdateAction.raml
CategoryAddAssetAction: !include category/updates/CategoryAddAssetAction.raml
CategoryChangeAssetNameAction: !include category/updates/CategoryChangeAssetNameAction.raml
CategoryChangeAssetOrderAction: !include category/updates/CategoryChangeAssetOrderAction.raml
CategoryChangeNameAction: !include category/updates/CategoryChangeNameAction.raml
CategoryChangeOrderHintAction: !include category/updates/CategoryChangeOrderHintAction.raml
CategoryChangeParentAction: !include category/updates/CategoryChangeParentAction.raml
CategoryChangeSlugAction: !include category/updates/CategoryChangeSlugAction.raml
CategoryRemoveAssetAction: !include category/updates/CategoryRemoveAssetAction.raml
CategorySetAssetCustomFieldAction: !include category/updates/CategorySetAssetCustomFieldAction.raml
CategorySetAssetCustomTypeAction: !include category/updates/CategorySetAssetCustomTypeAction.raml
CategorySetAssetDescriptionAction: !include category/updates/CategorySetAssetDescriptionAction.raml
CategorySetAssetKeyAction: !include category/updates/CategorySetAssetKeyAction.raml
CategorySetAssetSourcesAction: !include category/updates/CategorySetAssetSourcesAction.raml
CategorySetAssetTagsAction: !include category/updates/CategorySetAssetTagsAction.raml
CategorySetCustomFieldAction: !include category/updates/CategorySetCustomFieldAction.raml
CategorySetCustomTypeAction: !include category/updates/CategorySetCustomTypeAction.raml
CategorySetDescriptionAction: !include category/updates/CategorySetDescriptionAction.raml
CategorySetExternalIdAction: !include category/updates/CategorySetExternalIdAction.raml
CategorySetKeyAction: !include category/updates/CategorySetKeyAction.raml
CategorySetMetaDescriptionAction: !include category/updates/CategorySetMetaDescriptionAction.raml
CategorySetMetaKeywordsAction: !include category/updates/CategorySetMetaKeywordsAction.raml
CategorySetMetaTitleAction: !include category/updates/CategorySetMetaTitleAction.raml
Channel: !include channel/Channel.raml
ChannelDraft: !include channel/ChannelDraft.raml
ChannelPagedQueryResponse: !include channel/ChannelPagedQueryResponse.raml
ChannelReference: !include channel/ChannelReference.raml
ChannelRoleEnum: !include channel/ChannelRoleEnum.raml
ChannelUpdate: !include channel/ChannelUpdate.raml
ChannelUpdateAction: !include channel/ChannelUpdateAction.raml
ChannelAddRolesAction: !include channel/updates/ChannelAddRolesAction.raml
ChannelChangeDescriptionAction: !include channel/updates/ChannelChangeDescriptionAction.raml
ChannelChangeKeyAction: !include channel/updates/ChannelChangeKeyAction.raml
ChannelChangeNameAction: !include channel/updates/ChannelChangeNameAction.raml
ChannelRemoveRolesAction: !include channel/updates/ChannelRemoveRolesAction.raml
ChannelSetAddressAction: !include channel/updates/ChannelSetAddressAction.raml
ChannelSetCustomFieldAction: !include channel/updates/ChannelSetCustomFieldAction.raml
ChannelSetCustomTypeAction: !include channel/updates/ChannelSetCustomTypeAction.raml
ChannelSetGeoLocationAction: !include channel/updates/ChannelSetGeoLocationAction.raml
ChannelSetRolesAction: !include channel/updates/ChannelSetRolesAction.raml
Address: !include common/Address.raml
Asset: !include common/Asset.raml
AssetDimensions: !include common/AssetDimensions.raml
AssetDraft: !include common/AssetDraft.raml
AssetSource: !include common/AssetSource.raml
CentPrecisionMoney: !include common/CentPrecisionMoney.raml
CountryCode: !include common/CountryCode.raml
CurrencyCode: !include common/CurrencyCode.raml
DiscountedPrice: !include common/DiscountedPrice.raml
GeoJson: !include common/GeoJson.raml
GeoJsonPoint: !include common/GeoJsonPoint.raml
HighPrecisionMoney: !include common/HighPrecisionMoney.raml
Image: !include common/Image.raml
ImageDimensions: !include common/ImageDimensions.raml
Locale: !include common/Locale.raml
LocalizedString: !include common/LocalizedString.raml
Money: !include common/Money.raml
MoneyType: !include common/MoneyType.raml
Price: !include common/Price.raml
PriceDraft: !include common/PriceDraft.raml
PriceTier: !include common/PriceTier.raml
Reference: !include common/Reference.raml
ReferenceTypeId: !include common/ReferenceTypeId.raml
Resource: !include common/Resource.raml
ResourceIdentifier: !include common/ResourceIdentifier.raml
ScopedPrice: !include common/ScopedPrice.raml
TypedMoney: !include common/TypedMoney.raml
CustomObject: !include custom-object/CustomObject.raml
CustomObjectDraft: !include custom-object/CustomObjectDraft.raml
CustomObjectPagedQueryResponse: !include custom-object/CustomObjectPagedQueryResponse.raml
CustomObjectReference: !include custom-object/CustomObjectReference.raml
CustomerGroup: !include customer-group/CustomerGroup.raml
CustomerGroupDraft: !include customer-group/CustomerGroupDraft.raml
CustomerGroupPagedQueryResponse: !include customer-group/CustomerGroupPagedQueryResponse.raml
CustomerGroupReference: !include customer-group/CustomerGroupReference.raml
CustomerGroupUpdate: !include customer-group/CustomerGroupUpdate.raml
CustomerGroupUpdateAction: !include customer-group/CustomerGroupUpdateAction.raml
CustomerGroupChangeNameAction: !include customer-group/updates/CustomerGroupChangeNameAction.raml
CustomerGroupSetCustomFieldAction: !include customer-group/updates/CustomerGroupSetCustomFieldAction.raml
CustomerGroupSetCustomTypeAction: !include customer-group/updates/CustomerGroupSetCustomTypeAction.raml
CustomerGroupSetKeyAction: !include customer-group/updates/CustomerGroupSetKeyAction.raml
AnonymousCartSignInMode: !include customer/AnonymousCartSignInMode.raml
Customer: !include customer/Customer.raml
CustomerChangePassword: !include customer/CustomerChangePassword.raml
CustomerCreateEmailToken: !include customer/CustomerCreateEmailToken.raml
CustomerCreatePasswordResetToken: !include customer/CustomerCreatePasswordResetToken.raml
CustomerDraft: !include customer/CustomerDraft.raml
CustomerEmailVerify: !include customer/CustomerEmailVerify.raml
CustomerPagedQueryResponse: !include customer/CustomerPagedQueryResponse.raml
CustomerReference: !include customer/CustomerReference.raml
CustomerResetPassword: !include customer/CustomerResetPassword.raml
CustomerSignInResult: !include customer/CustomerSignInResult.raml
CustomerSignin: !include customer/CustomerSignin.raml
CustomerToken: !include customer/CustomerToken.raml
CustomerUpdate: !include customer/CustomerUpdate.raml
CustomerUpdateAction: !include customer/CustomerUpdateAction.raml
CustomerAddAddressAction: !include customer/updates/CustomerAddAddressAction.raml
CustomerAddBillingAddressIdAction: !include customer/updates/CustomerAddBillingAddressIdAction.raml
CustomerAddShippingAddressIdAction: !include customer/updates/CustomerAddShippingAddressIdAction.raml
CustomerChangeAddressAction: !include customer/updates/CustomerChangeAddressAction.raml
CustomerChangeEmailAction: !include customer/updates/CustomerChangeEmailAction.raml
CustomerRemoveAddressAction: !include customer/updates/CustomerRemoveAddressAction.raml
CustomerRemoveBillingAddressIdAction: !include customer/updates/CustomerRemoveBillingAddressIdAction.raml
CustomerRemoveShippingAddressIdAction: !include customer/updates/CustomerRemoveShippingAddressIdAction.raml
CustomerSetCompanyNameAction: !include customer/updates/CustomerSetCompanyNameAction.raml
CustomerSetCustomFieldAction: !include customer/updates/CustomerSetCustomFieldAction.raml
CustomerSetCustomTypeAction: !include customer/updates/CustomerSetCustomTypeAction.raml
CustomerSetCustomerGroupAction: !include customer/updates/CustomerSetCustomerGroupAction.raml
CustomerSetCustomerNumberAction: !include customer/updates/CustomerSetCustomerNumberAction.raml
CustomerSetDateOfBirthAction: !include customer/updates/CustomerSetDateOfBirthAction.raml
CustomerSetDefaultBillingAddressAction: !include customer/updates/CustomerSetDefaultBillingAddressAction.raml
CustomerSetDefaultShippingAddressAction: !include customer/updates/CustomerSetDefaultShippingAddressAction.raml
CustomerSetExternalIdAction: !include customer/updates/CustomerSetExternalIdAction.raml
CustomerSetFirstNameAction: !include customer/updates/CustomerSetFirstNameAction.raml
CustomerSetKeyAction: !include customer/updates/CustomerSetKeyAction.raml
CustomerSetLastNameAction: !include customer/updates/CustomerSetLastNameAction.raml
CustomerSetLocaleAction: !include customer/updates/CustomerSetLocaleAction.raml
CustomerSetMiddleNameAction: !include customer/updates/CustomerSetMiddleNameAction.raml
CustomerSetSalutationAction: !include customer/updates/CustomerSetSalutationAction.raml
CustomerSetTitleAction: !include customer/updates/CustomerSetTitleAction.raml
CustomerSetVatIdAction: !include customer/updates/CustomerSetVatIdAction.raml
DiscountCode: !include discount-code/DiscountCode.raml
DiscountCodeDraft: !include discount-code/DiscountCodeDraft.raml
DiscountCodePagedQueryResponse: !include discount-code/DiscountCodePagedQueryResponse.raml
DiscountCodeReference: !include discount-code/DiscountCodeReference.raml
DiscountCodeUpdate: !include discount-code/DiscountCodeUpdate.raml
DiscountCodeUpdateAction: !include discount-code/DiscountCodeUpdateAction.raml
DiscountCodeChangeCartDiscountsAction: !include discount-code/updates/DiscountCodeChangeCartDiscountsAction.raml
DiscountCodeChangeGroupsAction: !include discount-code/updates/DiscountCodeChangeGroupsAction.raml
DiscountCodeChangeIsActiveAction: !include discount-code/updates/DiscountCodeChangeIsActiveAction.raml
DiscountCodeSetCartPredicateAction: !include discount-code/updates/DiscountCodeSetCartPredicateAction.raml
DiscountCodeSetCustomFieldAction: !include discount-code/updates/DiscountCodeSetCustomFieldAction.raml
DiscountCodeSetCustomTypeAction: !include discount-code/updates/DiscountCodeSetCustomTypeAction.raml
DiscountCodeSetDescriptionAction: !include discount-code/updates/DiscountCodeSetDescriptionAction.raml
DiscountCodeSetMaxApplicationsAction: !include discount-code/updates/DiscountCodeSetMaxApplicationsAction.raml
# yamllint disable-line rule:line-length
DiscountCodeSetMaxApplicationsPerCustomerAction: !include discount-code/updates/DiscountCodeSetMaxApplicationsPerCustomerAction.raml
DiscountCodeSetNameAction: !include discount-code/updates/DiscountCodeSetNameAction.raml
DiscountCodeSetValidFromAction: !include discount-code/updates/DiscountCodeSetValidFromAction.raml
DiscountCodeSetValidFromAndUntilAction: !include discount-code/updates/DiscountCodeSetValidFromAndUntilAction.raml
DiscountCodeSetValidUntilAction: !include discount-code/updates/DiscountCodeSetValidUntilAction.raml
AccessDeniedError: !include error/AccessDeniedError.raml
ConcurrentModificationError: !include error/ConcurrentModificationError.raml
DiscountCodeNonApplicableError: !include error/DiscountCodeNonApplicableError.raml
DuplicateAttributeValueError: !include error/DuplicateAttributeValueError.raml
DuplicateAttributeValuesError: !include error/DuplicateAttributeValuesError.raml
DuplicateFieldError: !include error/DuplicateFieldError.raml
DuplicatePriceScopeError: !include error/DuplicatePriceScopeError.raml
DuplicateVariantValuesError: !include error/DuplicateVariantValuesError.raml
ErrorObject: !include error/ErrorObject.raml
ErrorResponse: !include error/ErrorResponse.raml
InsufficientScopeError: !include error/InsufficientScopeError.raml
InvalidCredentialsError: !include error/InvalidCredentialsError.raml
InvalidCurrentPasswordError: !include error/InvalidCurrentPasswordError.raml
InvalidFieldError: !include error/InvalidFieldError.raml
InvalidInputError: !include error/InvalidInputError.raml
InvalidItemShippingDetailsError: !include error/InvalidItemShippingDetailsError.raml
InvalidOperationError: !include error/InvalidOperationError.raml
InvalidSubjectError: !include error/InvalidSubjectError.raml
InvalidTokenError: !include error/InvalidTokenError.raml
OutOfStockError: !include error/OutOfStockError.raml
PriceChangedError: !include error/PriceChangedError.raml
RequiredFieldError: !include error/RequiredFieldError.raml
ResourceNotFoundError: !include error/ResourceNotFoundError.raml
VariantValues: !include error/VariantValues.raml
Extension: !include extension/Extension.raml
ExtensionAWSLambdaDestination: !include extension/ExtensionAWSLambdaDestination.raml
ExtensionAction: !include extension/ExtensionAction.raml
ExtensionAuthorizationHeaderAuthentication: !include extension/ExtensionAuthorizationHeaderAuthentication.raml
ExtensionAzureFunctionsAuthentication: !include extension/ExtensionAzureFunctionsAuthentication.raml
ExtensionDestination: !include extension/ExtensionDestination.raml
ExtensionDraft: !include extension/ExtensionDraft.raml
ExtensionHttpDestination: !include extension/ExtensionHttpDestination.raml
ExtensionHttpDestinationAuthentication: !include extension/ExtensionHttpDestinationAuthentication.raml
ExtensionInput: !include extension/ExtensionInput.raml
ExtensionPagedQueryResponse: !include extension/ExtensionPagedQueryResponse.raml
ExtensionResourceTypeId: !include extension/ExtensionResourceTypeId.raml
ExtensionTrigger: !include extension/ExtensionTrigger.raml
ExtensionUpdate: !include extension/ExtensionUpdate.raml
ExtensionUpdateAction: !include extension/ExtensionUpdateAction.raml
ExtensionChangeDestinationAction: !include extension/updates/ExtensionChangeDestinationAction.raml
ExtensionChangeTriggersAction: !include extension/updates/ExtensionChangeTriggersAction.raml
ExtensionSetKeyAction: !include extension/updates/ExtensionSetKeyAction.raml
InventoryEntry: !include inventory/InventoryEntry.raml
InventoryEntryDraft: !include inventory/InventoryEntryDraft.raml
InventoryEntryReference: !include inventory/InventoryEntryReference.raml
InventoryPagedQueryResponse: !include inventory/InventoryPagedQueryResponse.raml
InventoryUpdate: !include inventory/InventoryUpdate.raml
InventoryUpdateAction: !include inventory/InventoryUpdateAction.raml
InventoryAddQuantityAction: !include inventory/updates/InventoryAddQuantityAction.raml
InventoryChangeQuantityAction: !include inventory/updates/InventoryChangeQuantityAction.raml
InventoryRemoveQuantityAction: !include inventory/updates/InventoryRemoveQuantityAction.raml
InventorySetCustomFieldAction: !include inventory/updates/InventorySetCustomFieldAction.raml
InventorySetCustomTypeAction: !include inventory/updates/InventorySetCustomTypeAction.raml
InventorySetExpectedDeliveryAction: !include inventory/updates/InventorySetExpectedDeliveryAction.raml
InventorySetRestockableInDaysAction: !include inventory/updates/InventorySetRestockableInDaysAction.raml
InventorySetSupplyChannelAction: !include inventory/updates/InventorySetSupplyChannelAction.raml
MyCartDraft: !include me/MyCartDraft.raml
MyCustomerDraft: !include me/MyCustomerDraft.raml
MyLineItemDraft: !include me/MyLineItemDraft.raml
MyOrderFromCartDraft: !include me/MyOrderFromCartDraft.raml
CategoryCreatedMessage: !include message/CategoryCreatedMessage.raml
CategorySlugChangedMessage: !include message/CategorySlugChangedMessage.raml
CustomLineItemStateTransitionMessage: !include message/CustomLineItemStateTransitionMessage.raml
CustomerAddressAddedMessage: !include message/CustomerAddressAddedMessage.raml
CustomerAddressChangedMessage: !include message/CustomerAddressChangedMessage.raml
CustomerAddressRemovedMessage: !include message/CustomerAddressRemovedMessage.raml
CustomerCompanyNameSetMessage: !include message/CustomerCompanyNameSetMessage.raml
CustomerCreatedMessage: !include message/CustomerCreatedMessage.raml
CustomerDateOfBirthSetMessage: !include message/CustomerDateOfBirthSetMessage.raml
CustomerEmailChangedMessage: !include message/CustomerEmailChangedMessage.raml
CustomerEmailVerifiedMessage: !include message/CustomerEmailVerifiedMessage.raml
CustomerGroupSetMessage: !include message/CustomerGroupSetMessage.raml
DeliveryAddedMessage: !include message/DeliveryAddedMessage.raml
DeliveryAddressSetMessage: !include message/DeliveryAddressSetMessage.raml
DeliveryItemsUpdatedMessage: !include message/DeliveryItemsUpdatedMessage.raml
DeliveryRemovedMessage: !include message/DeliveryRemovedMessage.raml
InventoryEntryDeletedMessage: !include message/InventoryEntryDeletedMessage.raml
LineItemStateTransitionMessage: !include message/LineItemStateTransitionMessage.raml
Message: !include message/Message.raml
MessageConfiguration: !include message/MessageConfiguration.raml
MessagePagedQueryResponse: !include message/MessagePagedQueryResponse.raml
OrderBillingAddressSetMessage: !include message/OrderBillingAddressSetMessage.raml
OrderCreatedMessage: !include message/OrderCreatedMessage.raml
OrderCustomerEmailSetMessage: !include message/OrderCustomerEmailSetMessage.raml
OrderCustomerSetMessage: !include message/OrderCustomerSetMessage.raml
OrderDeletedMessage: !include message/OrderDeletedMessage.raml
OrderImportedMessage: !include message/OrderImportedMessage.raml
OrderPaymentChangedMessage: !include message/OrderPaymentChangedMessage.raml
OrderReturnInfoAddedMessage: !include message/OrderReturnInfoAddedMessage.raml
OrderReturnShipmentStateChangedMessage: !include message/OrderReturnShipmentStateChangedMessage.raml
OrderShipmentStateChangedMessage: !include message/OrderShipmentStateChangedMessage.raml
OrderShippingAddressSetMessage: !include message/OrderShippingAddressSetMessage.raml
OrderStateChangedMessage: !include message/OrderStateChangedMessage.raml
OrderStateTransitionMessage: !include message/OrderStateTransitionMessage.raml
ParcelAddedToDeliveryMessage: !include message/ParcelAddedToDeliveryMessage.raml
ParcelItemsUpdatedMessage: !include message/ParcelItemsUpdatedMessage.raml
ParcelMeasurementsUpdatedMessage: !include message/ParcelMeasurementsUpdatedMessage.raml
ParcelRemovedFromDeliveryMessage: !include message/ParcelRemovedFromDeliveryMessage.raml
ParcelTrackingDataUpdatedMessage: !include message/ParcelTrackingDataUpdatedMessage.raml
PaymentCreatedMessage: !include message/PaymentCreatedMessage.raml
PaymentInteractionAddedMessage: !include message/PaymentInteractionAddedMessage.raml
PaymentStatusInterfaceCodeSetMessage: !include message/PaymentStatusInterfaceCodeSetMessage.raml
PaymentStatusStateTransitionMessage: !include message/PaymentStatusStateTransitionMessage.raml
PaymentTransactionAddedMessage: !include message/PaymentTransactionAddedMessage.raml
PaymentTransactionStateChangedMessage: !include message/PaymentTransactionStateChangedMessage.raml
ProductCreatedMessage: !include message/ProductCreatedMessage.raml
ProductDeletedMessage: !include message/ProductDeletedMessage.raml
ProductImageAddedMessage: !include message/ProductImageAddedMessage.raml
ProductPublishedMessage: !include message/ProductPublishedMessage.raml
ProductRevertedStagedChangesMessage: !include message/ProductRevertedStagedChangesMessage.raml
ProductSlugChangedMessage: !include message/ProductSlugChangedMessage.raml
ProductStateTransitionMessage: !include message/ProductStateTransitionMessage.raml
ProductUnpublishedMessage: !include message/ProductUnpublishedMessage.raml
ProductVariantDeletedMessage: !include message/ProductVariantDeletedMessage.raml
ReviewCreatedMessage: !include message/ReviewCreatedMessage.raml
ReviewRatingSetMessage: !include message/ReviewRatingSetMessage.raml
ReviewStateTransitionMessage: !include message/ReviewStateTransitionMessage.raml
Delivery: !include order/Delivery.raml
DeliveryItem: !include order/DeliveryItem.raml
DiscountedLineItemPriceDraft: !include order/DiscountedLineItemPriceDraft.raml
ItemState: !include order/ItemState.raml
LineItemImportDraft: !include order/LineItemImportDraft.raml
Order: !include order/Order.raml
OrderFromCartDraft: !include order/OrderFromCartDraft.raml
OrderImportDraft: !include order/OrderImportDraft.raml
OrderPagedQueryResponse: !include order/OrderPagedQueryResponse.raml
OrderReference: !include order/OrderReference.raml
OrderState: !include order/OrderState.raml
OrderUpdate: !include order/OrderUpdate.raml
OrderUpdateAction: !include order/OrderUpdateAction.raml
Parcel: !include order/Parcel.raml
ParcelDraft: !include order/ParcelDraft.raml
ParcelMeasurements: !include order/ParcelMeasurements.raml
PaymentInfo: !include order/PaymentInfo.raml
PaymentState: !include order/PaymentState.raml
ProductVariantImportDraft: !include order/ProductVariantImportDraft.raml
ReturnInfo: !include order/ReturnInfo.raml
ReturnItem: !include order/ReturnItem.raml
ReturnItemDraft: !include order/ReturnItemDraft.raml
ReturnPaymentState: !include order/ReturnPaymentState.raml
ReturnShipmentState: !include order/ReturnShipmentState.raml
ShipmentState: !include order/ShipmentState.raml
ShippingInfoDraft: !include order/ShippingInfoDraft.raml
SyncInfo: !include order/SyncInfo.raml
TaxedItemPriceDraft: !include order/TaxedItemPriceDraft.raml
TrackingData: !include order/TrackingData.raml
OrderAddDeliveryAction: !include order/updates/OrderAddDeliveryAction.raml
OrderAddItemShippingAddressAction: !include order/updates/OrderAddItemShippingAddressAction.raml
OrderAddParcelToDeliveryAction: !include order/updates/OrderAddParcelToDeliveryAction.raml
OrderAddPaymentAction: !include order/updates/OrderAddPaymentAction.raml
OrderAddReturnInfoAction: !include order/updates/OrderAddReturnInfoAction.raml
OrderChangeOrderStateAction: !include order/updates/OrderChangeOrderStateAction.raml
OrderChangePaymentStateAction: !include order/updates/OrderChangePaymentStateAction.raml
OrderChangeShipmentStateAction: !include order/updates/OrderChangeShipmentStateAction.raml
OrderImportCustomLineItemStateAction: !include order/updates/OrderImportCustomLineItemStateAction.raml
OrderImportLineItemStateAction: !include order/updates/OrderImportLineItemStateAction.raml
OrderRemoveDeliveryAction: !include order/updates/OrderRemoveDeliveryAction.raml
OrderRemoveItemShippingAddressAction: !include order/updates/OrderRemoveItemShippingAddressAction.raml
OrderRemoveParcelFromDeliveryAction: !include order/updates/OrderRemoveParcelFromDeliveryAction.raml
OrderRemovePaymentAction: !include order/updates/OrderRemovePaymentAction.raml
OrderSetBillingAddressAction: !include order/updates/OrderSetBillingAddressAction.raml
OrderSetCustomFieldAction: !include order/updates/OrderSetCustomFieldAction.raml
OrderSetCustomLineItemCustomFieldAction: !include order/updates/OrderSetCustomLineItemCustomFieldAction.raml
OrderSetCustomLineItemCustomTypeAction: !include order/updates/OrderSetCustomLineItemCustomTypeAction.raml
OrderSetCustomLineItemShippingDetailsAction: !include order/updates/OrderSetCustomLineItemShippingDetailsAction.raml
OrderSetCustomTypeAction: !include order/updates/OrderSetCustomTypeAction.raml
OrderSetCustomerEmailAction: !include order/updates/OrderSetCustomerEmailAction.raml
OrderSetCustomerIdAction: !include order/updates/OrderSetCustomerIdAction.raml
OrderSetDeliveryAddressAction: !include order/updates/OrderSetDeliveryAddressAction.raml
OrderSetDeliveryItemsAction: !include order/updates/OrderSetDeliveryItemsAction.raml
OrderSetLineItemCustomFieldAction: !include order/updates/OrderSetLineItemCustomFieldAction.raml
OrderSetLineItemCustomTypeAction: !include order/updates/OrderSetLineItemCustomTypeAction.raml
OrderSetLineItemShippingDetailsAction: !include order/updates/OrderSetLineItemShippingDetailsAction.raml
OrderSetLocaleAction: !include order/updates/OrderSetLocaleAction.raml
OrderSetOrderNumberAction: !include order/updates/OrderSetOrderNumberAction.raml
OrderSetParcelItemsAction: !include order/updates/OrderSetParcelItemsAction.raml
OrderSetParcelMeasurementsAction: !include order/updates/OrderSetParcelMeasurementsAction.raml
OrderSetParcelTrackingDataAction: !include order/updates/OrderSetParcelTrackingDataAction.raml
OrderSetReturnPaymentStateAction: !include order/updates/OrderSetReturnPaymentStateAction.raml
OrderSetReturnShipmentStateAction: !include order/updates/OrderSetReturnShipmentStateAction.raml
OrderSetShippingAddressAction: !include order/updates/OrderSetShippingAddressAction.raml
OrderTransitionCustomLineItemStateAction: !include order/updates/OrderTransitionCustomLineItemStateAction.raml
OrderTransitionLineItemStateAction: !include order/updates/OrderTransitionLineItemStateAction.raml
OrderTransitionStateAction: !include order/updates/OrderTransitionStateAction.raml
OrderUpdateItemShippingAddressAction: !include order/updates/OrderUpdateItemShippingAddressAction.raml
OrderUpdateSyncInfoAction: !include order/updates/OrderUpdateSyncInfoAction.raml
Payment: !include payment/Payment.raml
PaymentDraft: !include payment/PaymentDraft.raml
PaymentMethodInfo: !include payment/PaymentMethodInfo.raml
PaymentPagedQueryResponse: !include payment/PaymentPagedQueryResponse.raml
PaymentReference: !include payment/PaymentReference.raml
PaymentStatus: !include payment/PaymentStatus.raml
PaymentUpdate: !include payment/PaymentUpdate.raml
PaymentUpdateAction: !include payment/PaymentUpdateAction.raml
Transaction: !include payment/Transaction.raml
TransactionDraft: !include payment/TransactionDraft.raml
TransactionState: !include payment/TransactionState.raml
TransactionType: !include payment/TransactionType.raml
PaymentAddInterfaceInteractionAction: !include payment/updates/PaymentAddInterfaceInteractionAction.raml
PaymentAddTransactionAction: !include payment/updates/PaymentAddTransactionAction.raml
PaymentChangeAmountPlannedAction: !include payment/updates/PaymentChangeAmountPlannedAction.raml
PaymentChangeTransactionInteractionIdAction: !include payment/updates/PaymentChangeTransactionInteractionIdAction.raml
PaymentChangeTransactionStateAction: !include payment/updates/PaymentChangeTransactionStateAction.raml
PaymentChangeTransactionTimestampAction: !include payment/updates/PaymentChangeTransactionTimestampAction.raml
PaymentSetAmountPaidAction: !include payment/updates/PaymentSetAmountPaidAction.raml
PaymentSetAmountRefundedAction: !include payment/updates/PaymentSetAmountRefundedAction.raml
PaymentSetAnonymousIdAction: !include payment/updates/PaymentSetAnonymousIdAction.raml
PaymentSetAuthorizationAction: !include payment/updates/PaymentSetAuthorizationAction.raml
PaymentSetCustomFieldAction: !include payment/updates/PaymentSetCustomFieldAction.raml
PaymentSetCustomTypeAction: !include payment/updates/PaymentSetCustomTypeAction.raml
PaymentSetCustomerAction: !include payment/updates/PaymentSetCustomerAction.raml
PaymentSetExternalIdAction: !include payment/updates/PaymentSetExternalIdAction.raml
PaymentSetInterfaceIdAction: !include payment/updates/PaymentSetInterfaceIdAction.raml
PaymentSetKeyAction: !include payment/updates/PaymentSetKeyAction.raml
PaymentSetMethodInfoInterfaceAction: !include payment/updates/PaymentSetMethodInfoInterfaceAction.raml
PaymentSetMethodInfoMethodAction: !include payment/updates/PaymentSetMethodInfoMethodAction.raml
PaymentSetMethodInfoNameAction: !include payment/updates/PaymentSetMethodInfoNameAction.raml
PaymentSetStatusInterfaceCodeAction: !include payment/updates/PaymentSetStatusInterfaceCodeAction.raml
PaymentSetStatusInterfaceTextAction: !include payment/updates/PaymentSetStatusInterfaceTextAction.raml
PaymentTransitionStateAction: !include payment/updates/PaymentTransitionStateAction.raml
ProductDiscount: !include product-discount/ProductDiscount.raml
ProductDiscountDraft: !include product-discount/ProductDiscountDraft.raml
ProductDiscountMatchQuery: !include product-discount/ProductDiscountMatchQuery.raml
ProductDiscountPagedQueryResponse: !include product-discount/ProductDiscountPagedQueryResponse.raml
ProductDiscountReference: !include product-discount/ProductDiscountReference.raml
ProductDiscountUpdate: !include product-discount/ProductDiscountUpdate.raml
ProductDiscountUpdateAction: !include product-discount/ProductDiscountUpdateAction.raml
ProductDiscountValue: !include product-discount/ProductDiscountValue.raml
ProductDiscountValueAbsolute: !include product-discount/ProductDiscountValueAbsolute.raml
ProductDiscountValueExternal: !include product-discount/ProductDiscountValueExternal.raml
ProductDiscountValueRelative: !include product-discount/ProductDiscountValueRelative.raml
ProductDiscountChangeIsActiveAction: !include product-discount/updates/ProductDiscountChangeIsActiveAction.raml
ProductDiscountChangeNameAction: !include product-discount/updates/ProductDiscountChangeNameAction.raml
ProductDiscountChangePredicateAction: !include product-discount/updates/ProductDiscountChangePredicateAction.raml
ProductDiscountChangeSortOrderAction: !include product-discount/updates/ProductDiscountChangeSortOrderAction.raml
ProductDiscountChangeValueAction: !include product-discount/updates/ProductDiscountChangeValueAction.raml
ProductDiscountSetDescriptionAction: !include product-discount/updates/ProductDiscountSetDescriptionAction.raml
ProductDiscountSetValidFromAction: !include product-discount/updates/ProductDiscountSetValidFromAction.raml
# yamllint disable-line rule:line-length
ProductDiscountSetValidFromAndUntilAction: !include product-discount/updates/ProductDiscountSetValidFromAndUntilAction.raml
ProductDiscountSetValidUntilAction: !include product-discount/updates/ProductDiscountSetValidUntilAction.raml
AttributeBooleanType: !include product-type/AttributeBooleanType.raml
AttributeConstraintEnum: !include product-type/AttributeConstraintEnum.raml
AttributeDateTimeType: !include product-type/AttributeDateTimeType.raml
AttributeDateType: !include product-type/AttributeDateType.raml
AttributeDefinition: !include product-type/AttributeDefinition.raml
AttributeDefinitionDraft: !include product-type/AttributeDefinitionDraft.raml
AttributeEnumType: !include product-type/AttributeEnumType.raml
AttributeLocalizableTextType: !include product-type/AttributeLocalizableTextType.raml
AttributeLocalizedEnumType: !include product-type/AttributeLocalizedEnumType.raml
AttributeLocalizedEnumValue: !include product-type/AttributeLocalizedEnumValue.raml
AttributeMoneyType: !include product-type/AttributeMoneyType.raml
AttributeNestedType: !include product-type/AttributeNestedType.raml
AttributeNumberType: !include product-type/AttributeNumberType.raml
AttributePlainEnumValue: !include product-type/AttributePlainEnumValue.raml
AttributeReferenceType: !include product-type/AttributeReferenceType.raml
AttributeSetType: !include product-type/AttributeSetType.raml
AttributeTextType: !include product-type/AttributeTextType.raml
AttributeTimeType: !include product-type/AttributeTimeType.raml
AttributeType: !include product-type/AttributeType.raml
ProductType: !include product-type/ProductType.raml
ProductTypeDraft: !include product-type/ProductTypeDraft.raml
ProductTypePagedQueryResponse: !include product-type/ProductTypePagedQueryResponse.raml
ProductTypeReference: !include product-type/ProductTypeReference.raml
ProductTypeUpdate: !include product-type/ProductTypeUpdate.raml
ProductTypeUpdateAction: !include product-type/ProductTypeUpdateAction.raml
TextInputHint: !include product-type/TextInputHint.raml
ProductTypeAddAttributeDefinitionAction: !include product-type/updates/ProductTypeAddAttributeDefinitionAction.raml
ProductTypeAddLocalizedEnumValueAction: !include product-type/updates/ProductTypeAddLocalizedEnumValueAction.raml
ProductTypeAddPlainEnumValueAction: !include product-type/updates/ProductTypeAddPlainEnumValueAction.raml
# yamllint disable-line rule:line-length
ProductTypeChangeAttributeConstraintAction: !include product-type/updates/ProductTypeChangeAttributeConstraintAction.raml
ProductTypeChangeAttributeNameAction: !include product-type/updates/ProductTypeChangeAttributeNameAction.raml
ProductTypeChangeAttributeOrderAction: !include product-type/updates/ProductTypeChangeAttributeOrderAction.raml
ProductTypeChangeDescriptionAction: !include product-type/updates/ProductTypeChangeDescriptionAction.raml
ProductTypeChangeEnumKeyAction: !include product-type/updates/ProductTypeChangeEnumKeyAction.raml
ProductTypeChangeInputHintAction: !include product-type/updates/ProductTypeChangeInputHintAction.raml
ProductTypeChangeIsSearchableAction: !include product-type/updates/ProductTypeChangeIsSearchableAction.raml
ProductTypeChangeLabelAction: !include product-type/updates/ProductTypeChangeLabelAction.raml
# yamllint disable-line rule:line-length
ProductTypeChangeLocalizedEnumValueLabelAction: !include product-type/updates/ProductTypeChangeLocalizedEnumValueLabelAction.raml
# yamllint disable-line rule:line-length
ProductTypeChangeLocalizedEnumValueOrderAction: !include product-type/updates/ProductTypeChangeLocalizedEnumValueOrderAction.raml
ProductTypeChangeNameAction: !include product-type/updates/ProductTypeChangeNameAction.raml
# yamllint disable-line rule:line-length
ProductTypeChangePlainEnumValueLabelAction: !include product-type/updates/ProductTypeChangePlainEnumValueLabelAction.raml
# yamllint disable-line rule:line-length
ProductTypeChangePlainEnumValueOrderAction: !include product-type/updates/ProductTypeChangePlainEnumValueOrderAction.raml
# yamllint disable-line rule:line-length
ProductTypeRemoveAttributeDefinitionAction: !include product-type/updates/ProductTypeRemoveAttributeDefinitionAction.raml
ProductTypeRemoveEnumValuesAction: !include product-type/updates/ProductTypeRemoveEnumValuesAction.raml
ProductTypeSetInputTipAction: !include product-type/updates/ProductTypeSetInputTipAction.raml
ProductTypeSetKeyAction: !include product-type/updates/ProductTypeSetKeyAction.raml
Attribute: !include product/Attribute.raml
AttributeValue: !include product/AttributeValue.raml
CategoryOrderHints: !include product/CategoryOrderHints.raml
CustomTokenizer: !include product/CustomTokenizer.raml
FacetResult: !include product/FacetResult.raml
FacetResultRange: !include product/FacetResultRange.raml
FacetResultTerm: !include product/FacetResultTerm.raml
FacetResults: !include product/FacetResults.raml
FacetTypes: !include product/FacetTypes.raml
FilteredFacetResult: !include product/FilteredFacetResult.raml
Product: !include product/Product.raml
ProductCatalogData: !include product/ProductCatalogData.raml
ProductData: !include product/ProductData.raml
ProductDraft: !include product/ProductDraft.raml
ProductPagedQueryResponse: !include product/ProductPagedQueryResponse.raml
ProductProjection: !include product/ProductProjection.raml
ProductProjectionPagedQueryResponse: !include product/ProductProjectionPagedQueryResponse.raml
ProductProjectionPagedSearchResponse: !include product/ProductProjectionPagedSearchResponse.raml
ProductPublishScope: !include product/ProductPublishScope.raml
ProductReference: !include product/ProductReference.raml
ProductUpdate: !include product/ProductUpdate.raml
ProductUpdateAction: !include product/ProductUpdateAction.raml
ProductVariant: !include product/ProductVariant.raml
ProductVariantAvailability: !include product/ProductVariantAvailability.raml
ProductVariantChannelAvailability: !include product/ProductVariantChannelAvailability.raml
ProductVariantChannelAvailabilityMap: !include product/ProductVariantChannelAvailabilityMap.raml
ProductVariantDraft: !include product/ProductVariantDraft.raml
RangeFacetResult: !include product/RangeFacetResult.raml
SearchKeyword: !include product/SearchKeyword.raml
SearchKeywords: !include product/SearchKeywords.raml
SuggestTokenizer: !include product/SuggestTokenizer.raml
Suggestion: !include product/Suggestion.raml
SuggestionResult: !include product/SuggestionResult.raml
TermFacetResult: !include product/TermFacetResult.raml
TermFacetResultType: !include product/TermFacetResultType.raml
WhitespaceTokenizer: !include product/WhitespaceTokenizer.raml
ProductAddAssetAction: !include product/updates/ProductAddAssetAction.raml
ProductAddExternalImageAction: !include product/updates/ProductAddExternalImageAction.raml
ProductAddPriceAction: !include product/updates/ProductAddPriceAction.raml
ProductAddToCategoryAction: !include product/updates/ProductAddToCategoryAction.raml
ProductAddVariantAction: !include product/updates/ProductAddVariantAction.raml
ProductChangeAssetNameAction: !include product/updates/ProductChangeAssetNameAction.raml
ProductChangeAssetOrderAction: !include product/updates/ProductChangeAssetOrderAction.raml
ProductChangeMasterVariantAction: !include product/updates/ProductChangeMasterVariantAction.raml
ProductChangeNameAction: !include product/updates/ProductChangeNameAction.raml
ProductChangePriceAction: !include product/updates/ProductChangePriceAction.raml
ProductChangeSlugAction: !include product/updates/ProductChangeSlugAction.raml
ProductLegacySetSkuAction: !include product/updates/ProductLegacySetSkuAction.raml
ProductMoveImageToPositionAction: !include product/updates/ProductMoveImageToPositionAction.raml
ProductPublishAction: !include product/updates/ProductPublishAction.raml
ProductRemoveAssetAction: !include product/updates/ProductRemoveAssetAction.raml
ProductRemoveFromCategoryAction: !include product/updates/ProductRemoveFromCategoryAction.raml
ProductRemoveImageAction: !include product/updates/ProductRemoveImageAction.raml
ProductRemovePriceAction: !include product/updates/ProductRemovePriceAction.raml
ProductRemoveVariantAction: !include product/updates/ProductRemoveVariantAction.raml
ProductRevertStagedChangesAction: !include product/updates/ProductRevertStagedChangesAction.raml
ProductRevertStagedVariantChangesAction: !include product/updates/ProductRevertStagedVariantChangesAction.raml
ProductSetAssetCustomFieldAction: !include product/updates/ProductSetAssetCustomFieldAction.raml
ProductSetAssetCustomTypeAction: !include product/updates/ProductSetAssetCustomTypeAction.raml
ProductSetAssetDescriptionAction: !include product/updates/ProductSetAssetDescriptionAction.raml
ProductSetAssetKeyAction: !include product/updates/ProductSetAssetKeyAction.raml
ProductSetAssetSourcesAction: !include product/updates/ProductSetAssetSourcesAction.raml
ProductSetAssetTagsAction: !include product/updates/ProductSetAssetTagsAction.raml
ProductSetAttributeAction: !include product/updates/ProductSetAttributeAction.raml
ProductSetAttributeInAllVariantsAction: !include product/updates/ProductSetAttributeInAllVariantsAction.raml
ProductSetCategoryOrderHintAction: !include product/updates/ProductSetCategoryOrderHintAction.raml
ProductSetDescriptionAction: !include product/updates/ProductSetDescriptionAction.raml
ProductSetDiscountedPriceAction: !include product/updates/ProductSetDiscountedPriceAction.raml
ProductSetImageLabelAction: !include product/updates/ProductSetImageLabelAction.raml
ProductSetKeyAction: !include product/updates/ProductSetKeyAction.raml
ProductSetMetaDescriptionAction: !include product/updates/ProductSetMetaDescriptionAction.raml
ProductSetMetaKeywordsAction: !include product/updates/ProductSetMetaKeywordsAction.raml
ProductSetMetaTitleAction: !include product/updates/ProductSetMetaTitleAction.raml
ProductSetPricesAction: !include product/updates/ProductSetPricesAction.raml
ProductSetProductPriceCustomFieldAction: !include product/updates/ProductSetProductPriceCustomFieldAction.raml
ProductSetProductPriceCustomTypeAction: !include product/updates/ProductSetProductPriceCustomTypeAction.raml
ProductSetProductVariantKeyAction: !include product/updates/ProductSetProductVariantKeyAction.raml
ProductSetSearchKeywordsAction: !include product/updates/ProductSetSearchKeywordsAction.raml
ProductSetSkuAction: !include product/updates/ProductSetSkuAction.raml
ProductSetTaxCategoryAction: !include product/updates/ProductSetTaxCategoryAction.raml
ProductTransitionStateAction: !include product/updates/ProductTransitionStateAction.raml
ProductUnpublishAction: !include product/updates/ProductUnpublishAction.raml
CartClassificationType: !include project/CartClassificationType.raml
CartScoreType: !include project/CartScoreType.raml
CartValueType: !include project/CartValueType.raml
Project: !include project/Project.raml
ProjectUpdate: !include project/ProjectUpdate.raml
ProjectUpdateAction: !include project/ProjectUpdateAction.raml
ShippingRateInputType: !include project/ShippingRateInputType.raml
ProjectChangeCountriesAction: !include project/updates/ProjectChangeCountriesAction.raml
ProjectChangeCurrenciesAction: !include project/updates/ProjectChangeCurrenciesAction.raml
ProjectChangeLanguagesAction: !include project/updates/ProjectChangeLanguagesAction.raml
ProjectChangeMessagesEnabledAction: !include project/updates/ProjectChangeMessagesEnabledAction.raml
ProjectChangeNameAction: !include project/updates/ProjectChangeNameAction.raml
ProjectSetShippingRateInputTypeAction: !include project/updates/ProjectSetShippingRateInputTypeAction.raml
Review: !include review/Review.raml
ReviewDraft: !include review/ReviewDraft.raml
ReviewPagedQueryResponse: !include review/ReviewPagedQueryResponse.raml
ReviewRatingStatistics: !include review/ReviewRatingStatistics.raml
ReviewReference: !include review/ReviewReference.raml
ReviewUpdate: !include review/ReviewUpdate.raml
ReviewUpdateAction: !include review/ReviewUpdateAction.raml
ReviewSetAuthorNameAction: !include review/updates/ReviewSetAuthorNameAction.raml
ReviewSetCustomFieldAction: !include review/updates/ReviewSetCustomFieldAction.raml
ReviewSetCustomTypeAction: !include review/updates/ReviewSetCustomTypeAction.raml
ReviewSetCustomerAction: !include review/updates/ReviewSetCustomerAction.raml
ReviewSetKeyAction: !include review/updates/ReviewSetKeyAction.raml
ReviewSetLocaleAction: !include review/updates/ReviewSetLocaleAction.raml
ReviewSetRatingAction: !include review/updates/ReviewSetRatingAction.raml
ReviewSetTargetAction: !include review/updates/ReviewSetTargetAction.raml
ReviewSetTextAction: !include review/updates/ReviewSetTextAction.raml
ReviewSetTitleAction: !include review/updates/ReviewSetTitleAction.raml
ReviewTransitionStateAction: !include review/updates/ReviewTransitionStateAction.raml
CartClassificationTier: !include shipping-method/CartClassificationTier.raml
CartScoreTier: !include shipping-method/CartScoreTier.raml
CartValueTier: !include shipping-method/CartValueTier.raml
PriceFunction: !include shipping-method/PriceFunction.raml
ShippingMethod: !include shipping-method/ShippingMethod.raml
ShippingMethodDraft: !include shipping-method/ShippingMethodDraft.raml
ShippingMethodPagedQueryResponse: !include shipping-method/ShippingMethodPagedQueryResponse.raml
ShippingMethodReference: !include shipping-method/ShippingMethodReference.raml
ShippingMethodUpdate: !include shipping-method/ShippingMethodUpdate.raml
ShippingMethodUpdateAction: !include shipping-method/ShippingMethodUpdateAction.raml
ShippingRate: !include shipping-method/ShippingRate.raml
ShippingRateDraft: !include shipping-method/ShippingRateDraft.raml
ShippingRatePriceTier: !include shipping-method/ShippingRatePriceTier.raml
ShippingRateTierType: !include shipping-method/ShippingRateTierType.raml
ZoneRate: !include shipping-method/ZoneRate.raml
ZoneRateDraft: !include shipping-method/ZoneRateDraft.raml
ShippingMethodAddShippingRateAction: !include shipping-method/updates/ShippingMethodAddShippingRateAction.raml
ShippingMethodAddZoneAction: !include shipping-method/updates/ShippingMethodAddZoneAction.raml
ShippingMethodChangeIsDefaultAction: !include shipping-method/updates/ShippingMethodChangeIsDefaultAction.raml
ShippingMethodChangeNameAction: !include shipping-method/updates/ShippingMethodChangeNameAction.raml
ShippingMethodChangeTaxCategoryAction: !include shipping-method/updates/ShippingMethodChangeTaxCategoryAction.raml
ShippingMethodRemoveShippingRateAction: !include shipping-method/updates/ShippingMethodRemoveShippingRateAction.raml
ShippingMethodRemoveZoneAction: !include shipping-method/updates/ShippingMethodRemoveZoneAction.raml
ShippingMethodSetDescriptionAction: !include shipping-method/updates/ShippingMethodSetDescriptionAction.raml
ShippingMethodSetKeyAction: !include shipping-method/updates/ShippingMethodSetKeyAction.raml
ShippingMethodSetPredicateAction: !include shipping-method/updates/ShippingMethodSetPredicateAction.raml
ShoppingList: !include shopping-list/ShoppingList.raml
ShoppingListDraft: !include shopping-list/ShoppingListDraft.raml
ShoppingListLineItem: !include shopping-list/ShoppingListLineItem.raml
ShoppingListLineItemDraft: !include shopping-list/ShoppingListLineItemDraft.raml
ShoppingListPagedQueryResponse: !include shopping-list/ShoppingListPagedQueryResponse.raml
ShoppingListReference: !include shopping-list/ShoppingListReference.raml
ShoppingListSetTextLineItemCustomFieldAction: !include shopping-list/ShoppingListSetTextLineItemCustomFieldAction.raml
ShoppingListSetTextLineItemCustomTypeAction: !include shopping-list/ShoppingListSetTextLineItemCustomTypeAction.raml
ShoppingListSetTextLineItemDescriptionAction: !include shopping-list/ShoppingListSetTextLineItemDescriptionAction.raml
ShoppingListUpdate: !include shopping-list/ShoppingListUpdate.raml
ShoppingListUpdateAction: !include shopping-list/ShoppingListUpdateAction.raml
TextLineItem: !include shopping-list/TextLineItem.raml
TextLineItemDraft: !include shopping-list/TextLineItemDraft.raml
ShoppingListAddLineItemAction: !include shopping-list/updates/ShoppingListAddLineItemAction.raml
ShoppingListAddTextLineItemAction: !include shopping-list/updates/ShoppingListAddTextLineItemAction.raml
ShoppingListChangeLineItemQuantityAction: !include shopping-list/updates/ShoppingListChangeLineItemQuantityAction.raml
ShoppingListChangeLineItemsOrderAction: !include shopping-list/updates/ShoppingListChangeLineItemsOrderAction.raml
ShoppingListChangeNameAction: !include shopping-list/updates/ShoppingListChangeNameAction.raml
ShoppingListChangeTextLineItemNameAction: !include shopping-list/updates/ShoppingListChangeTextLineItemNameAction.raml
# yamllint disable-line rule:line-length
ShoppingListChangeTextLineItemQuantityAction: !include shopping-list/updates/ShoppingListChangeTextLineItemQuantityAction.raml
# yamllint disable-line rule:line-length
ShoppingListChangeTextLineItemsOrderAction: !include shopping-list/updates/ShoppingListChangeTextLineItemsOrderAction.raml
ShoppingListRemoveLineItemAction: !include shopping-list/updates/ShoppingListRemoveLineItemAction.raml
ShoppingListRemoveTextLineItemAction: !include shopping-list/updates/ShoppingListRemoveTextLineItemAction.raml
ShoppingListSetAnonymousIdAction: !include shopping-list/updates/ShoppingListSetAnonymousIdAction.raml
ShoppingListSetCustomFieldAction: !include shopping-list/updates/ShoppingListSetCustomFieldAction.raml
ShoppingListSetCustomTypeAction: !include shopping-list/updates/ShoppingListSetCustomTypeAction.raml
ShoppingListSetCustomerAction: !include shopping-list/updates/ShoppingListSetCustomerAction.raml
# yamllint disable-line rule:line-length
ShoppingListSetDeleteDaysAfterLastModificationAction: !include shopping-list/updates/ShoppingListSetDeleteDaysAfterLastModificationAction.raml
ShoppingListSetDescriptionAction: !include shopping-list/updates/ShoppingListSetDescriptionAction.raml
ShoppingListSetKeyAction: !include shopping-list/updates/ShoppingListSetKeyAction.raml
ShoppingListSetLineItemCustomFieldAction: !include shopping-list/updates/ShoppingListSetLineItemCustomFieldAction.raml
ShoppingListSetLineItemCustomTypeAction: !include shopping-list/updates/ShoppingListSetLineItemCustomTypeAction.raml
ShoppingListSetSlugAction: !include shopping-list/updates/ShoppingListSetSlugAction.raml
State: !include state/State.raml
StateDraft: !include state/StateDraft.raml
StatePagedQueryResponse: !include state/StatePagedQueryResponse.raml
StateReference: !include state/StateReference.raml
StateRoleEnum: !include state/StateRoleEnum.raml
StateTypeEnum: !include state/StateTypeEnum.raml
StateUpdate: !include state/StateUpdate.raml
StateUpdateAction: !include state/StateUpdateAction.raml
StateAddRolesAction: !include state/updates/StateAddRolesAction.raml
StateChangeInitialAction: !include state/updates/StateChangeInitialAction.raml
StateChangeKeyAction: !include state/updates/StateChangeKeyAction.raml
StateChangeTypeAction: !include state/updates/StateChangeTypeAction.raml
StateRemoveRolesAction: !include state/updates/StateRemoveRolesAction.raml
StateSetDescriptionAction: !include state/updates/StateSetDescriptionAction.raml
StateSetNameAction: !include state/updates/StateSetNameAction.raml
StateSetRolesAction: !include state/updates/StateSetRolesAction.raml
StateSetTransitionsAction: !include state/updates/StateSetTransitionsAction.raml
AzureEventGridDestination: !include subscription/AzureEventGridDestination.raml
AzureServiceBusDestination: !include subscription/AzureServiceBusDestination.raml
ChangeSubscription: !include subscription/ChangeSubscription.raml
Destination: !include subscription/Destination.raml
GoogleCloudPubSubDestination: !include subscription/GoogleCloudPubSubDestination.raml
IronMqDestination: !include subscription/IronMqDestination.raml
MessageDelivery: !include subscription/MessageDelivery.raml
MessageSubscription: !include subscription/MessageSubscription.raml
PayloadNotIncluded: !include subscription/PayloadNotIncluded.raml
ResourceCreatedDelivery: !include subscription/ResourceCreatedDelivery.raml
ResourceDeletedDelivery: !include subscription/ResourceDeletedDelivery.raml
ResourceUpdatedDelivery: !include subscription/ResourceUpdatedDelivery.raml
SnsDestination: !include subscription/SnsDestination.raml
SqsDestination: !include subscription/SqsDestination.raml
Subscription: !include subscription/Subscription.raml
SubscriptionDelivery: !include subscription/SubscriptionDelivery.raml
SubscriptionDraft: !include subscription/SubscriptionDraft.raml
SubscriptionPagedQueryResponse: !include subscription/SubscriptionPagedQueryResponse.raml
SubscriptionUpdate: !include subscription/SubscriptionUpdate.raml
SubscriptionUpdateAction: !include subscription/SubscriptionUpdateAction.raml
SubscriptionChangeDestinationAction: !include subscription/updates/SubscriptionChangeDestinationAction.raml
SubscriptionSetChangesAction: !include subscription/updates/SubscriptionSetChangesAction.raml
SubscriptionSetKeyAction: !include subscription/updates/SubscriptionSetKeyAction.raml
SubscriptionSetMessagesAction: !include subscription/updates/SubscriptionSetMessagesAction.raml
SubRate: !include tax-category/SubRate.raml
TaxCategory: !include tax-category/TaxCategory.raml
TaxCategoryDraft: !include tax-category/TaxCategoryDraft.raml
TaxCategoryPagedQueryResponse: !include tax-category/TaxCategoryPagedQueryResponse.raml
TaxCategoryReference: !include tax-category/TaxCategoryReference.raml
TaxCategoryUpdate: !include tax-category/TaxCategoryUpdate.raml
TaxCategoryUpdateAction: !include tax-category/TaxCategoryUpdateAction.raml
TaxRate: !include tax-category/TaxRate.raml
TaxRateDraft: !include tax-category/TaxRateDraft.raml
TaxCategoryAddTaxRateAction: !include tax-category/updates/TaxCategoryAddTaxRateAction.raml
TaxCategoryChangeNameAction: !include tax-category/updates/TaxCategoryChangeNameAction.raml
TaxCategoryRemoveTaxRateAction: !include tax-category/updates/TaxCategoryRemoveTaxRateAction.raml
TaxCategoryReplaceTaxRateAction: !include tax-category/updates/TaxCategoryReplaceTaxRateAction.raml
TaxCategorySetDescriptionAction: !include tax-category/updates/TaxCategorySetDescriptionAction.raml
TaxCategorySetKeyAction: !include tax-category/updates/TaxCategorySetKeyAction.raml
CustomFieldBooleanType: !include type/CustomFieldBooleanType.raml
CustomFieldDateTimeType: !include type/CustomFieldDateTimeType.raml
CustomFieldDateType: !include type/CustomFieldDateType.raml
CustomFieldEnumType: !include type/CustomFieldEnumType.raml
CustomFieldEnumValue: !include type/CustomFieldEnumValue.raml
CustomFieldLocalizedEnumType: !include type/CustomFieldLocalizedEnumType.raml
CustomFieldLocalizedEnumValue: !include type/CustomFieldLocalizedEnumValue.raml
CustomFieldLocalizedStringType: !include type/CustomFieldLocalizedStringType.raml
CustomFieldMoneyType: !include type/CustomFieldMoneyType.raml
CustomFieldNumberType: !include type/CustomFieldNumberType.raml
CustomFieldReferenceType: !include type/CustomFieldReferenceType.raml
CustomFieldSetType: !include type/CustomFieldSetType.raml
CustomFieldStringType: !include type/CustomFieldStringType.raml
CustomFieldTimeType: !include type/CustomFieldTimeType.raml
CustomFields: !include type/CustomFields.raml
CustomFieldsDraft: !include type/CustomFieldsDraft.raml
FieldContainer: !include type/FieldContainer.raml
FieldDefinition: !include type/FieldDefinition.raml
FieldType: !include type/FieldType.raml
ResourceTypeId: !include type/ResourceTypeId.raml
Type: !include type/Type.raml
TypeDraft: !include type/TypeDraft.raml
TypePagedQueryResponse: !include type/TypePagedQueryResponse.raml
TypeReference: !include type/TypeReference.raml
TypeUpdate: !include type/TypeUpdate.raml
TypeUpdateAction: !include type/TypeUpdateAction.raml
TypeAddEnumValueAction: !include type/updates/TypeAddEnumValueAction.raml
TypeAddFieldDefinitionAction: !include type/updates/TypeAddFieldDefinitionAction.raml
TypeAddLocalizedEnumValueAction: !include type/updates/TypeAddLocalizedEnumValueAction.raml
TypeChangeEnumValueOrderAction: !include type/updates/TypeChangeEnumValueOrderAction.raml
TypeChangeFieldDefinitionLabelAction: !include type/updates/TypeChangeFieldDefinitionLabelAction.raml
TypeChangeFieldDefinitionOrderAction: !include type/updates/TypeChangeFieldDefinitionOrderAction.raml
TypeChangeKeyAction: !include type/updates/TypeChangeKeyAction.raml
TypeChangeLabelAction: !include type/updates/TypeChangeLabelAction.raml
TypeChangeLocalizedEnumValueOrderAction: !include type/updates/TypeChangeLocalizedEnumValueOrderAction.raml
TypeChangeNameAction: !include type/updates/TypeChangeNameAction.raml
TypeRemoveFieldDefinitionAction: !include type/updates/TypeRemoveFieldDefinitionAction.raml
TypeSetDescriptionAction: !include type/updates/TypeSetDescriptionAction.raml
Location: !include zone/Location.raml
Zone: !include zone/Zone.raml
ZoneDraft: !include zone/ZoneDraft.raml
ZonePagedQueryResponse: !include zone/ZonePagedQueryResponse.raml
ZoneReference: !include zone/ZoneReference.raml
ZoneUpdate: !include zone/ZoneUpdate.raml
ZoneUpdateAction: !include zone/ZoneUpdateAction.raml
ZoneAddLocationAction: !include zone/updates/ZoneAddLocationAction.raml
ZoneChangeNameAction: !include zone/updates/ZoneChangeNameAction.raml
ZoneRemoveLocationAction: !include zone/updates/ZoneRemoveLocationAction.raml
ZoneSetDescriptionAction: !include zone/updates/ZoneSetDescriptionAction.raml
