CustomObjectDraft: !include custom-object/CustomObjectDraft.raml
CustomObjectReference: !include custom-object/CustomObjectReference.raml
CustomObjectPagedQueryResponse: !include custom-object/CustomObjectPagedQueryResponse.raml
CustomObject: !include custom-object/CustomObject.raml
PaymentStatusInterfaceCodeSetMessage: !include message/PaymentStatusInterfaceCodeSetMessage.raml
InventoryEntryDeletedMessage: !include message/InventoryEntryDeletedMessage.raml
PaymentStatusStateTransitionMessage: !include message/PaymentStatusStateTransitionMessage.raml
CustomLineItemStateTransitionMessage: !include message/CustomLineItemStateTransitionMessage.raml
ProductPublishedMessage: !include message/ProductPublishedMessage.raml
OrderReturnInfoAddedMessage: !include message/OrderReturnInfoAddedMessage.raml
ProductRevertedStagedChangesMessage: !include message/ProductRevertedStagedChangesMessage.raml
ProductUnpublishedMessage: !include message/ProductUnpublishedMessage.raml
ProductImageAddedMessage: !include message/ProductImageAddedMessage.raml
ProductCreatedMessage: !include message/ProductCreatedMessage.raml
PaymentInteractionAddedMessage: !include message/PaymentInteractionAddedMessage.raml
Message: !include message/Message.raml
ReviewCreatedMessage: !include message/ReviewCreatedMessage.raml
PaymentTransactionAddedMessage: !include message/PaymentTransactionAddedMessage.raml
ProductSlugChangedMessage: !include message/ProductSlugChangedMessage.raml
OrderStateTransitionMessage: !include message/OrderStateTransitionMessage.raml
CustomerCreatedMessage: !include message/CustomerCreatedMessage.raml
OrderStateChangedMessage: !include message/OrderStateChangedMessage.raml
DeliveryAddedMessage: !include message/DeliveryAddedMessage.raml
CategorySlugChangedMessage: !include message/CategorySlugChangedMessage.raml
OrderShippingAddressSetMessage: !include message/OrderShippingAddressSetMessage.raml
ProductStateTransitionMessage: !include message/ProductStateTransitionMessage.raml
ProductDeletedMessage: !include message/ProductDeletedMessage.raml
OrderImportedMessage: !include message/OrderImportedMessage.raml
ReviewRatingSetMessage: !include message/ReviewRatingSetMessage.raml
PaymentCreatedMessage: !include message/PaymentCreatedMessage.raml
OrderCustomerEmailSetMessage: !include message/OrderCustomerEmailSetMessage.raml
MessageConfiguration: !include message/MessageConfiguration.raml
ReviewStateTransitionMessage: !include message/ReviewStateTransitionMessage.raml
ProductVariantDeletedMessage: !include message/ProductVariantDeletedMessage.raml
PaymentTransactionStateChangedMessage: !include message/PaymentTransactionStateChangedMessage.raml
ParcelAddedToDeliveryMessage: !include message/ParcelAddedToDeliveryMessage.raml
OrderPaymentChangedMessage: !include message/OrderPaymentChangedMessage.raml
OrderCreatedMessage: !include message/OrderCreatedMessage.raml
OrderBillingAddressSetMessage: !include message/OrderBillingAddressSetMessage.raml
LineItemStateTransitionMessage: !include message/LineItemStateTransitionMessage.raml
MessagePagedQueryResponse: !include message/MessagePagedQueryResponse.raml
CategoryCreatedMessage: !include message/CategoryCreatedMessage.raml
InventoryEntryUpdate: !include inventory/InventoryEntryUpdate.raml
InventoryRemoveQuantityAction: !include inventory/InventoryRemoveQuantityAction.raml
InventorySetExpectedDeliveryAction: !include inventory/InventorySetExpectedDeliveryAction.raml
InventoryPagedQueryResponse: !include inventory/InventoryPagedQueryResponse.raml
InventorySetSupplyChannelAction: !include inventory/InventorySetSupplyChannelAction.raml
InventoryEntryReference: !include inventory/InventoryEntryReference.raml
InventorySetRestockableInDaysAction: !include inventory/InventorySetRestockableInDaysAction.raml
InventorySetCustomTypeAction: !include inventory/InventorySetCustomTypeAction.raml
InventoryChangeQuantityAction: !include inventory/InventoryChangeQuantityAction.raml
InventorySetCustomFieldAction: !include inventory/InventorySetCustomFieldAction.raml
InventoryEntry: !include inventory/InventoryEntry.raml
InventoryEntryUpdateAction: !include inventory/InventoryEntryUpdateAction.raml
InventoryEntryDraft: !include inventory/InventoryEntryDraft.raml
InventoryAddQuantityAction: !include inventory/InventoryAddQuantityAction.raml
TaxCategoryPagedQueryResponse: !include tax-category/TaxCategoryPagedQueryResponse.raml
TaxCategoryAddTaxRateAction: !include tax-category/TaxCategoryAddTaxRateAction.raml
TaxCategoryUpdate: !include tax-category/TaxCategoryUpdate.raml
TaxCategoryDraft: !include tax-category/TaxCategoryDraft.raml
TaxCategoryReplaceTaxRateAction: !include tax-category/TaxCategoryReplaceTaxRateAction.raml
SubRate: !include tax-category/SubRate.raml
TaxRateDraft: !include tax-category/TaxRateDraft.raml
TaxCategoryChangeNameAction: !include tax-category/TaxCategoryChangeNameAction.raml
TaxCategorySetDescriptionAction: !include tax-category/TaxCategorySetDescriptionAction.raml
TaxCategory: !include tax-category/TaxCategory.raml
TaxCategoryRemoveTaxRateAction: !include tax-category/TaxCategoryRemoveTaxRateAction.raml
TaxCategoryUpdateAction: !include tax-category/TaxCategoryUpdateAction.raml
TaxRate: !include tax-category/TaxRate.raml
TaxCategoryReference: !include tax-category/TaxCategoryReference.raml
ChannelChangeDescriptionAction: !include channel/ChannelChangeDescriptionAction.raml
ChannelUpdateAction: !include channel/ChannelUpdateAction.raml
ChannelSetRolesAction: !include channel/ChannelSetRolesAction.raml
ChannelPagedQueryResponse: !include channel/ChannelPagedQueryResponse.raml
ChannelRemoveRolesAction: !include channel/ChannelRemoveRolesAction.raml
ChannelSetCustomFieldAction: !include channel/ChannelSetCustomFieldAction.raml
ChannelSetGeolocationAction: !include channel/ChannelSetGeolocationAction.raml
ChannelChangeKeyAction: !include channel/ChannelChangeKeyAction.raml
ChannelRoleEnum: !include channel/ChannelRoleEnum.raml
ChannelUpdate: !include channel/ChannelUpdate.raml
ChannelAddRolesAction: !include channel/ChannelAddRolesAction.raml
ChannelSetAddressAction: !include channel/ChannelSetAddressAction.raml
ChannelSetCustomTypeAction: !include channel/ChannelSetCustomTypeAction.raml
Channel: !include channel/Channel.raml
ChannelReference: !include channel/ChannelReference.raml
ChannelDraft: !include channel/ChannelDraft.raml
ChannelChangeNameAction: !include channel/ChannelChangeNameAction.raml
ShoppingListSetTextLineItemCustomTypeAction: !include shopping-list/ShoppingListSetTextLineItemCustomTypeAction.raml
ShoppingListSetCustomTypeAction: !include shopping-list/ShoppingListSetCustomTypeAction.raml
ShoppingListSetDescriptionAction: !include shopping-list/ShoppingListSetDescriptionAction.raml
ShoppingListSetTextLineItemDescriptionAction: !include shopping-list/ShoppingListSetTextLineItemDescriptionAction.raml
TextLineItem: !include shopping-list/TextLineItem.raml
ShoppingListChangeTextLineItemQuantityAction: !include shopping-list/ShoppingListChangeTextLineItemQuantityAction.raml
ShoppingListSetKeyAction: !include shopping-list/ShoppingListSetKeyAction.raml
ShoppingListSetSlugAction: !include shopping-list/ShoppingListSetSlugAction.raml
ShoppingListChangeTextLineItemsOrderAction: !include shopping-list/ShoppingListChangeTextLineItemsOrderAction.raml
ShoppingListPagedQueryResponse: !include shopping-list/ShoppingListPagedQueryResponse.raml
ShoppingListRemoveLineItemAction: !include shopping-list/ShoppingListRemoveLineItemAction.raml
ShoppingListChangeNameAction: !include shopping-list/ShoppingListChangeNameAction.raml
ShoppingListLineItem: !include shopping-list/ShoppingListLineItem.raml
ShoppingListUpdateAction: !include shopping-list/ShoppingListUpdateAction.raml
ShoppingListRemoveTextLineItemAction: !include shopping-list/ShoppingListRemoveTextLineItemAction.raml
ShoppingListChangeLineItemsOrderAction: !include shopping-list/ShoppingListChangeLineItemsOrderAction.raml
ShoppingListSetCustomFieldAction: !include shopping-list/ShoppingListSetCustomFieldAction.raml
TextLineItemDraft: !include shopping-list/TextLineItemDraft.raml
ShoppingListSetDeleteDaysAfterLastModificationAction: !include shopping-list/ShoppingListSetDeleteDaysAfterLastModificationAction.raml
ShoppingListReference: !include shopping-list/ShoppingListReference.raml
ShoppingListAddLineItemAction: !include shopping-list/ShoppingListAddLineItemAction.raml
ShoppingListSetLineItemCustomFieldAction: !include shopping-list/ShoppingListSetLineItemCustomFieldAction.raml
ShoppingListDraft: !include shopping-list/ShoppingListDraft.raml
ShoppingListChangeTextLineItemNameAction: !include shopping-list/ShoppingListChangeTextLineItemNameAction.raml
ShoppingListSetCustomerAction: !include shopping-list/ShoppingListSetCustomerAction.raml
ShoppingListSetLineItemCustomTypeAction: !include shopping-list/ShoppingListSetLineItemCustomTypeAction.raml
ShoppingListUpdate: !include shopping-list/ShoppingListUpdate.raml
ShoppingListSetTextLineItemCustomFieldAction: !include shopping-list/ShoppingListSetTextLineItemCustomFieldAction.raml
ShoppingListLineItemDraft: !include shopping-list/ShoppingListLineItemDraft.raml
ShoppingListAddTextLineItemAction: !include shopping-list/ShoppingListAddTextLineItemAction.raml
ShoppingListChangeLineItemQuantityAction: !include shopping-list/ShoppingListChangeLineItemQuantityAction.raml
ShoppingList: !include shopping-list/ShoppingList.raml
UpdateAction: !include UpdateAction.raml
PagedQueryResponse: !include PagedQueryResponse.raml
DiscountCodeDraft: !include discount-code/DiscountCodeDraft.raml
DiscountCodeUpdateAction: !include discount-code/DiscountCodeUpdateAction.raml
DiscountCodeUpdate: !include discount-code/DiscountCodeUpdate.raml
DiscountCodeReference: !include discount-code/DiscountCodeReference.raml
DiscountCode: !include discount-code/DiscountCode.raml
DiscountCodeSetDescriptionAction: !include discount-code/DiscountCodeSetDescriptionAction.raml
DiscountCodeSetMaxApplicationsPerCustomerAction: !include discount-code/DiscountCodeSetMaxApplicationsPerCustomerAction.raml
DiscountCodeChangeCartDiscountsAction: !include discount-code/DiscountCodeChangeCartDiscountsAction.raml
DiscountCodeSetMaxApplicationsAction: !include discount-code/DiscountCodeSetMaxApplicationsAction.raml
DiscountCodeSetNameAction: !include discount-code/DiscountCodeSetNameAction.raml
DiscountCodePagedQueryResponse: !include discount-code/DiscountCodePagedQueryResponse.raml
DiscountCodeSetCartPredicateAction: !include discount-code/DiscountCodeSetCartPredicateAction.raml
CustomerUpdate: !include customer/CustomerUpdate.raml
CustomerCreatePasswordResetToken: !include customer/CustomerCreatePasswordResetToken.raml
CustomerSignin: !include customer/CustomerSignin.raml
CustomerResetPassword: !include customer/CustomerResetPassword.raml
Customer: !include customer/Customer.raml
CustomerCreateEmailToken: !include customer/CustomerCreateEmailToken.raml
CustomerUpdateAction: !include customer/CustomerUpdateAction.raml
CustomerReference: !include customer/CustomerReference.raml
CustomerToken: !include customer/CustomerToken.raml
CustomerSignInResult: !include customer/CustomerSignInResult.raml
AnonymousCartSignInMode: !include customer/AnonymousCartSignInMode.raml
CustomerPagedQueryResponse: !include customer/CustomerPagedQueryResponse.raml
CustomerDraft: !include customer/CustomerDraft.raml
CustomerEmailVerify: !include customer/CustomerEmailVerify.raml
CustomerChangePassword: !include customer/CustomerChangePassword.raml
StateRoleEnum: !include state/StateRoleEnum.raml
StateSetDescriptionAction: !include state/StateSetDescriptionAction.raml
StateReference: !include state/StateReference.raml
StatePagedQueryResponse: !include state/StatePagedQueryResponse.raml
StateUpdateAction: !include state/StateUpdateAction.raml
State: !include state/State.raml
StateChangeInitialAction: !include state/StateChangeInitialAction.raml
StateChangeKeyAction: !include state/StateChangeKeyAction.raml
StateAddRolesAction: !include state/StateAddRolesAction.raml
StateSetNameAction: !include state/StateSetNameAction.raml
StateDraft: !include state/StateDraft.raml
StateChangeTypeAction: !include state/StateChangeTypeAction.raml
StateUpdate: !include state/StateUpdate.raml
StateSetRolesAction: !include state/StateSetRolesAction.raml
StateSetTransitionsAction: !include state/StateSetTransitionsAction.raml
StateRemoveRolesAction: !include state/StateRemoveRolesAction.raml
StateTypeEnum: !include state/StateTypeEnum.raml
SubscriptionSetKeyAction: !include subscription/SubscriptionSetKeyAction.raml
ChangeSubscription: !include subscription/ChangeSubscription.raml
SubscriptionPagedQueryResponse: !include subscription/SubscriptionPagedQueryResponse.raml
IronMqDestination: !include subscription/IronMqDestination.raml
SubscriptionSetChangesAction: !include subscription/SubscriptionSetChangesAction.raml
SnsDestination: !include subscription/SnsDestination.raml
SubscriptionUpdate: !include subscription/SubscriptionUpdate.raml
SubscriptionDraft: !include subscription/SubscriptionDraft.raml
Destination: !include subscription/Destination.raml
MessageSubscription: !include subscription/MessageSubscription.raml
AzureServiceBusDestination: !include subscription/AzureServiceBusDestination.raml
Subscription: !include subscription/Subscription.raml
SubscriptionSetMessagesAction: !include subscription/SubscriptionSetMessagesAction.raml
SubscriptionUpdateAction: !include subscription/SubscriptionUpdateAction.raml
SqsDestination: !include subscription/SqsDestination.raml
CustomLineItemDraft: !include cart/CustomLineItemDraft.raml
CartSetShippingAddressAction: !include cart/CartSetShippingAddressAction.raml
CartSetCustomerIdAction: !include cart/CartSetCustomerIdAction.raml
CartSetLineItemCustomTypeAction: !include cart/CartSetLineItemCustomTypeAction.raml
CartAddCustomLineItemAction: !include cart/CartAddCustomLineItemAction.raml
CartSetBillingAddressAction: !include cart/CartSetBillingAddressAction.raml
DiscountedLineItemPortion: !include cart/DiscountedLineItemPortion.raml
ShippingInfo: !include cart/ShippingInfo.raml
CartChangeTaxRoundingModeAction: !include cart/CartChangeTaxRoundingModeAction.raml
CartUpdateAction: !include cart/CartUpdateAction.raml
ExternalLineItemTotalPrice: !include cart/ExternalLineItemTotalPrice.raml
CartPagedQueryResponse: !include cart/CartPagedQueryResponse.raml
TaxPortion: !include cart/TaxPortion.raml
CartChangeLineItemQuantityAction: !include cart/CartChangeLineItemQuantityAction.raml
CartAddDiscountCodeAction: !include cart/CartAddDiscountCodeAction.raml
CartRemoveLineItemAction: !include cart/CartRemoveLineItemAction.raml
CustomLineItem: !include cart/CustomLineItem.raml
CartAddLineItemAction: !include cart/CartAddLineItemAction.raml
CartSetLineItemCustomFieldAction: !include cart/CartSetLineItemCustomFieldAction.raml
LineItemDraft: !include cart/LineItemDraft.raml
InventoryMode: !include cart/InventoryMode.raml
TaxMode: !include cart/TaxMode.raml
CartSetCustomLineItemCustomTypeAction: !include cart/CartSetCustomLineItemCustomTypeAction.raml
DiscountCodeState: !include cart/DiscountCodeState.raml
CartSetShippingMethodTaxRateAction: !include cart/CartSetShippingMethodTaxRateAction.raml
LineItem: !include cart/LineItem.raml
CartChangeCustomLineItemQuantityAction: !include cart/CartChangeCustomLineItemQuantityAction.raml
CartState: !include cart/CartState.raml
CartSetCustomShippingMethodAction: !include cart/CartSetCustomShippingMethodAction.raml
CartChangeCustomLineItemMoneyAction: !include cart/CartChangeCustomLineItemMoneyAction.raml
CartSetCustomerGroupAction: !include cart/CartSetCustomerGroupAction.raml
CartDraft: !include cart/CartDraft.raml
CartSetLineItemPriceAction: !include cart/CartSetLineItemPriceAction.raml
CartSetDeleteDaysAfterLastModificationAction: !include cart/CartSetDeleteDaysAfterLastModificationAction.raml
CartReference: !include cart/CartReference.raml
CartAddPaymentAction: !include cart/CartAddPaymentAction.raml
CartSetCustomTypeAction: !include cart/CartSetCustomTypeAction.raml
CartSetLineItemTaxRateAction: !include cart/CartSetLineItemTaxRateAction.raml
CartSetShippingMethodAction: !include cart/CartSetShippingMethodAction.raml
CartRecalculateAction: !include cart/CartRecalculateAction.raml
CartRemoveDiscountCodeAction: !include cart/CartRemoveDiscountCodeAction.raml
CartSetCustomerEmailAction: !include cart/CartSetCustomerEmailAction.raml
DiscountCodeInfo: !include cart/DiscountCodeInfo.raml
CartSetCustomFieldAction: !include cart/CartSetCustomFieldAction.raml
RoundingMode: !include cart/RoundingMode.raml
CartUpdate: !include cart/CartUpdate.raml
CartSetLineItemTotalPriceAction: !include cart/CartSetLineItemTotalPriceAction.raml
LineItemPriceMode: !include cart/LineItemPriceMode.raml
CartSetCustomLineItemTaxRateAction: !include cart/CartSetCustomLineItemTaxRateAction.raml
CartRemovePaymentAction: !include cart/CartRemovePaymentAction.raml
CartSetLocaleAction: !include cart/CartSetLocaleAction.raml
CartRemoveCustomLineItemAction: !include cart/CartRemoveCustomLineItemAction.raml
DiscountedLineItemPrice: !include cart/DiscountedLineItemPrice.raml
CartSetCountryAction: !include cart/CartSetCountryAction.raml
CartChangeTaxModeAction: !include cart/CartChangeTaxModeAction.raml
TaxedItemPrice: !include cart/TaxedItemPrice.raml
ExternalTaxRateDraft: !include cart/ExternalTaxRateDraft.raml
DiscountedLineItemPriceForQuantity: !include cart/DiscountedLineItemPriceForQuantity.raml
CartAddShoppingListAction: !include cart/CartAddShoppingListAction.raml
TaxedPrice: !include cart/TaxedPrice.raml
Cart: !include cart/Cart.raml
LineItemMode: !include cart/LineItemMode.raml
CartSetCustomLineItemCustomFieldAction: !include cart/CartSetCustomLineItemCustomFieldAction.raml
TypeSetDescriptionAction: !include type/TypeSetDescriptionAction.raml
CustomFieldLocalizedEnumType: !include type/CustomFieldLocalizedEnumType.raml
CustomFieldDateType: !include type/CustomFieldDateType.raml
TypeUpdateAction: !include type/TypeUpdateAction.raml
CustomFieldMoneyType: !include type/CustomFieldMoneyType.raml
TypeChangeFieldDefinitionLabelAction: !include type/TypeChangeFieldDefinitionLabelAction.raml
TypeAddEnumValueAction: !include type/TypeAddEnumValueAction.raml
CustomFieldStringType: !include type/CustomFieldStringType.raml
TypeReference: !include type/TypeReference.raml
FieldDefinition: !include type/FieldDefinition.raml
FieldContainer: !include type/FieldContainer.raml
TypePagedQueryResponse: !include type/TypePagedQueryResponse.raml
TypeRemoveFieldDefinitionAction: !include type/TypeRemoveFieldDefinitionAction.raml
CustomFieldTimeType: !include type/CustomFieldTimeType.raml
CustomFieldLocalizedEnumValue: !include type/CustomFieldLocalizedEnumValue.raml
CustomFieldNumberType: !include type/CustomFieldNumberType.raml
FieldType: !include type/FieldType.raml
CustomFieldBooleanType: !include type/CustomFieldBooleanType.raml
TypeUpdate: !include type/TypeUpdate.raml
TypeDraft: !include type/TypeDraft.raml
Type: !include type/Type.raml
TypeChangeFieldDefinitionOrderAction: !include type/TypeChangeFieldDefinitionOrderAction.raml
CustomFieldSetType: !include type/CustomFieldSetType.raml
TypeAddFieldDefinitionAction: !include type/TypeAddFieldDefinitionAction.raml
TypeChangeEnumValueOrderAction: !include type/TypeChangeEnumValueOrderAction.raml
CustomFieldLocalizedStringType: !include type/CustomFieldLocalizedStringType.raml
TypeChangeLocalizedEnumValueOrderAction: !include type/TypeChangeLocalizedEnumValueOrderAction.raml
TypeChangeNameAction: !include type/TypeChangeNameAction.raml
CustomFieldDateTimeType: !include type/CustomFieldDateTimeType.raml
CustomFieldEnumType: !include type/CustomFieldEnumType.raml
TypeAddLocalizedEnumValueAction: !include type/TypeAddLocalizedEnumValueAction.raml
CustomFieldReferenceType: !include type/CustomFieldReferenceType.raml
CustomFieldEnumValue: !include type/CustomFieldEnumValue.raml
CustomFields: !include type/CustomFields.raml
TypeChangeKeyAction: !include type/TypeChangeKeyAction.raml
ResourceTypeId: !include type/ResourceTypeId.raml
CustomFieldsDraft: !include type/CustomFieldsDraft.raml
ZonePagedQueryResponse: !include zone/ZonePagedQueryResponse.raml
ZoneDraft: !include zone/ZoneDraft.raml
ZoneAddLocationAction: !include zone/ZoneAddLocationAction.raml
ZoneUpdate: !include zone/ZoneUpdate.raml
Location: !include zone/Location.raml
ZoneChangeNameAction: !include zone/ZoneChangeNameAction.raml
ZoneReference: !include zone/ZoneReference.raml
ZoneUpdateAction: !include zone/ZoneUpdateAction.raml
ZoneSetDescriptionAction: !include zone/ZoneSetDescriptionAction.raml
ZoneRemoveLocationAction: !include zone/ZoneRemoveLocationAction.raml
Zone: !include zone/Zone.raml
ProductAddToCategoryAction: !include product/ProductAddToCategoryAction.raml
FacetResult: !include product/FacetResult.raml
ProductChangeSlugAction: !include product/ProductChangeSlugAction.raml
FilteredFacetResult: !include product/FilteredFacetResult.raml
ProductSetProductPriceCustomTypeAction: !include product/ProductSetProductPriceCustomTypeAction.raml
TermFacetResultType: !include product/TermFacetResultType.raml
ProductSetDescriptionAction: !include product/ProductSetDescriptionAction.raml
ProductRemoveVariantAction: !include product/ProductRemoveVariantAction.raml
ProductDraft: !include product/ProductDraft.raml
ProductProjection: !include product/ProductProjection.raml
ProductMoveImageToPositionAction: !include product/ProductMoveImageToPositionAction.raml
FacetResultRange: !include product/FacetResultRange.raml
SuggestTokenizer: !include product/SuggestTokenizer.raml
ProductTransitionStateAction: !include product/ProductTransitionStateAction.raml
ProductSetAssetCustomFieldAction: !include product/ProductSetAssetCustomFieldAction.raml
ProductStagedProductUpdateActionImplAction: !include product/ProductStagedProductUpdateActionImplAction.raml
ProductSetAssetTagsAction: !include product/ProductSetAssetTagsAction.raml
ProductSetMetaDescriptionAction: !include product/ProductSetMetaDescriptionAction.raml
ProductAddAssetAction: !include product/ProductAddAssetAction.raml
SearchKeywords: !include product/SearchKeywords.raml
ProductProjectionPagedQueryResponse: !include product/ProductProjectionPagedQueryResponse.raml
WhitespaceTokenizer: !include product/WhitespaceTokenizer.raml
ProductSetProductVariantKeyAction: !include product/ProductSetProductVariantKeyAction.raml
ProductPublishAction: !include product/ProductPublishAction.raml
ProductSetAttributeAction: !include product/ProductSetAttributeAction.raml
ProductSetMetaKeywordsAction: !include product/ProductSetMetaKeywordsAction.raml
ProductLegacySetSkuAction: !include product/ProductLegacySetSkuAction.raml
ProductCatalogData: !include product/ProductCatalogData.raml
ProductSetAttributeInAllVariantsAction: !include product/ProductSetAttributeInAllVariantsAction.raml
FacetResultTerm: !include product/FacetResultTerm.raml
ProductReference: !include product/ProductReference.raml
ProductSetDiscountedPriceAction: !include product/ProductSetDiscountedPriceAction.raml
ProductData: !include product/ProductData.raml
ProductRemovePriceAction: !include product/ProductRemovePriceAction.raml
ProductUpdate: !include product/ProductUpdate.raml
ProductVariantChannelAvailabilityMap: !include product/ProductVariantChannelAvailabilityMap.raml
ProductSetPricesAction: !include product/ProductSetPricesAction.raml
ProductRemoveImageAction: !include product/ProductRemoveImageAction.raml
ProductRemoveAssetAction: !include product/ProductRemoveAssetAction.raml
CategoryOrderHints: !include product/CategoryOrderHints.raml
FacetResults: !include product/FacetResults.raml
ProductSetCategoryOrderHintAction: !include product/ProductSetCategoryOrderHintAction.raml
FacetTypes: !include product/FacetTypes.raml
ProductSetTaxCategoryAction: !include product/ProductSetTaxCategoryAction.raml
CustomTokenizer: !include product/CustomTokenizer.raml
ProductVariantChannelAvailability: !include product/ProductVariantChannelAvailability.raml
ProductUnpublishAction: !include product/ProductUnpublishAction.raml
ProductChangeAssetNameAction: !include product/ProductChangeAssetNameAction.raml
ProductSetSkuAction: !include product/ProductSetSkuAction.raml
ProductChangePriceAction: !include product/ProductChangePriceAction.raml
ProductSetAssetDescriptionAction: !include product/ProductSetAssetDescriptionAction.raml
ProductChangeNameAction: !include project/ProductChangeNameAction.raml
ProductSetAssetCustomTypeAction: !include product/ProductSetAssetCustomTypeAction.raml
ProductSetSearchKeywordsAction: !include product/ProductSetSearchKeywordsAction.raml
RangeFacetResult: !include product/RangeFacetResult.raml
ProductSetKeyAction: !include product/ProductSetKeyAction.raml
ProductVariant: !include product/ProductVariant.raml
ProductRevertStagedChangesAction: !include product/ProductRevertStagedChangesAction.raml
ProductVariantAvailability: !include product/ProductVariantAvailability.raml
ProductAddPriceAction: !include product/ProductAddPriceAction.raml
ProductUpdateAction: !include product/ProductUpdateAction.raml
ProductSetProductPriceCustomFieldAction: !include product/ProductSetProductPriceCustomFieldAction.raml
Attribute: !include product/Attribute.raml
ProductChangeAssetOrderAction: !include product/ProductChangeAssetOrderAction.raml
ProductVariantDraft: !include product/ProductVariantDraft.raml
ProductPagedQueryResponse: !include product/ProductPagedQueryResponse.raml
ProductProjectionPagedSearchResponse: !include product/ProductProjectionPagedSearchResponse.raml
TermFacetResult: !include product/TermFacetResult.raml
SearchKeyword: !include product/SearchKeyword.raml
ProductAddVariantAction: !include product/ProductAddVariantAction.raml
ProductRemoveFromCategoryAction: !include product/ProductRemoveFromCategoryAction.raml
ProductAddExternalImageAction: !include product/ProductAddExternalImageAction.raml
Product: !include product/Product.raml
ProductChangeMasterVariantAction: !include product/ProductChangeMasterVariantAction.raml
ProductSetMetaTitleAction: !include product/ProductSetMetaTitleAction.raml
ShippingMethod: !include shipping-method/ShippingMethod.raml
ShippingMethodAddZoneAction: !include shipping-method/ShippingMethodAddZoneAction.raml
ShippingMethodRemoveZoneAction: !include shipping-method/ShippingMethodRemoveZoneAction.raml
ShippingMethodUpdate: !include shipping-method/ShippingMethodUpdate.raml
ShippingMethodRemoveShippingRateAction: !include shipping-method/ShippingMethodRemoveShippingRateAction.raml
ShippingMethodSetKeyAction: !include shipping-method/ShippingMethodSetKeyAction.raml
ShippingMethodReference: !include shipping-method/ShippingMethodReference.raml
ShippingMethodAddShippingRateAction: !include shipping-method/ShippingMethodAddShippingRateAction.raml
ShippingRate: !include shipping-method/ShippingRate.raml
ShippingMethodPagedQueryResponse: !include shipping-method/ShippingMethodPagedQueryResponse.raml
ShippingMethodChangeNameAction: !include shipping-method/ShippingMethodChangeNameAction.raml
ShippingMethodUpdateAction: !include shipping-method/ShippingMethodUpdateAction.raml
ZoneRate: !include shipping-method/ZoneRate.raml
ShippingMethodChangeTaxCategoryAction: !include shipping-method/ShippingMethodChangeTaxCategoryAction.raml
ShippingMethodSetDescriptionAction: !include shipping-method/ShippingMethodSetDescriptionAction.raml
ShippingMethodDraft: !include shipping-method/ShippingMethodDraft.raml
ShippingMethodChangeIsDefaultAction: !include shipping-method/ShippingMethodChangeIsDefaultAction.raml
ProductChangeMessagesEnabledAction: !include project/ProductChangeMessagesEnabledAction.raml
ProductChangeLanguagesAction: !include project/ProductChangeLanguagesAction.raml
ProductChangeCurrenciesAction: !include project/ProductChangeCurrenciesAction.raml
ProductChangeCountriesAction: !include project/ProductChangeCountriesAction.raml
ProjectUpdate: !include project/ProjectUpdate.raml
ProjectUpdateAction: !include project/ProjectUpdateAction.raml
Project: !include project/Project.raml
ItemState: !include order/ItemState.raml
OrderUpdateAction: !include order/OrderUpdateAction.raml
OrderSetCustomFieldAction: !include order/OrderSetCustomFieldAction.raml
OrderAddParcelToDeliveryAction: !include order/OrderAddParcelToDeliveryAction.raml
OrderSetCustomTypeAction: !include order/OrderSetCustomTypeAction.raml
OrderAddReturnInfoAction: !include order/OrderAddReturnInfoAction.raml
OrderReference: !include order/OrderReference.raml
OrderChangeShipmentStateAction: !include order/OrderChangeShipmentStateAction.raml
OrderSetCustomLineItemCustomFieldAction: !include order/OrderSetCustomLineItemCustomFieldAction.raml
OrderTransitionLineItemLikeStateAction: !include order/OrderTransitionLineItemLikeStateAction.raml
ShipmentState: !include order/ShipmentState.raml
OrderAddPaymentAction: !include order/OrderAddPaymentAction.raml
OrderChangePaymentStateAction: !include order/OrderChangePaymentStateAction.raml
OrderUpdate: !include order/OrderUpdate.raml
OrderImportDraft: !include order/OrderImportDraft.raml
ReturnItem: !include order/ReturnItem.raml
OrderRemovePaymentAction: !include order/OrderRemovePaymentAction.raml
OrderTransitionCustomLineItemStateAction: !include order/OrderTransitionCustomLineItemStateAction.raml
SyncInfo: !include order/SyncInfo.raml
OrderSetReturnPaymentStateAction: !include order/OrderSetReturnPaymentStateAction.raml
OrderUpdateSyncInfoAction: !include order/OrderUpdateSyncInfoAction.raml
Delivery: !include order/Delivery.raml
TrackingData: !include order/TrackingData.raml
Order: !include order/Order.raml
OrderSetLocaleAction: !include order/OrderSetLocaleAction.raml
ParcelMeasurements: !include order/ParcelMeasurements.raml
OrderTransitionLineItemStateAction: !include order/OrderTransitionLineItemStateAction.raml
OrderSetLineItemCustomTypeAction: !include order/OrderSetLineItemCustomTypeAction.raml
OrderFromCartDraft: !include order/OrderFromCartDraft.raml
OrderSetCustomerEmailAction: !include order/OrderSetCustomerEmailAction.raml
ProductVariantImportDraft: !include order/ProductVariantImportDraft.raml
OrderImportLineItemStateAction: !include order/OrderImportLineItemStateAction.raml
ReturnItemDraft: !include order/ReturnItemDraft.raml
OrderState: !include order/OrderState.raml
ReturnShipmentState: !include order/ReturnShipmentState.raml
ReturnPaymentState: !include order/ReturnPaymentState.raml
PaymentState: !include order/PaymentState.raml
OrderSetBillingAddressAction: !include order/OrderSetBillingAddressAction.raml
OrderSetCustomLineItemCustomTypeAction: !include order/OrderSetCustomLineItemCustomTypeAction.raml
OrderSetReturnShipmentStateAction: !include order/OrderSetReturnShipmentStateAction.raml
PaymentInfo: !include order/PaymentInfo.raml
OrderChangeOrderStateAction: !include order/OrderChangeOrderStateAction.raml
OrderSetOrderNumberAction: !include order/OrderSetOrderNumberAction.raml
LineItemImportDraft: !include order/LineItemImportDraft.raml
OrderTransitionStateAction: !include order/OrderTransitionStateAction.raml
OrderImportCustomLineItemStateAction: !include order/OrderImportCustomLineItemStateAction.raml
ReturnInfo: !include order/ReturnInfo.raml
OrderAddDeliveryAction: !include order/OrderAddDeliveryAction.raml
OrderSetShippingAddressAction: !include order/OrderSetShippingAddressAction.raml
OrderPagedQueryResponse: !include order/OrderPagedQueryResponse.raml
Parcel: !include order/Parcel.raml
OrderSetLineItemCustomFieldAction: !include order/OrderSetLineItemCustomFieldAction.raml
DeliveryItem: !include order/DeliveryItem.raml
Locale: !include common/Locale.raml
ResourceIdentifier: !include common/ResourceIdentifier.raml
GeoJson: !include common/GeoJson.raml
DiscountedPrice: !include common/DiscountedPrice.raml
Address: !include common/Address.raml
AssetSource: !include common/AssetSource.raml
Image: !include common/Image.raml
ScopedPrice: !include common/ScopedPrice.raml
PriceDraft: !include common/PriceDraft.raml
AssetDraft: !include common/AssetDraft.raml
Money: !include common/Money.raml
PriceTier: !include common/PriceTier.raml
Price: !include common/Price.raml
LocalizedString: !include common/LocalizedString.raml
AssetDimensions: !include common/AssetDimensions.raml
ImageDimensions: !include common/ImageDimensions.raml
ReferenceTypeId: !include common/ReferenceTypeId.raml
Reference: !include common/Reference.raml
CurrencyCode: !include common/CurrencyCode.raml
Resource: !include common/Resource.raml
Asset: !include common/Asset.raml
CountryCode: !include common/CountryCode.raml
GeoJsonPoint: !include common/GeoJsonPoint.raml
ProductDiscountValueRelative: !include product-discount/ProductDiscountValueRelative.raml
ProductDiscount: !include product-discount/ProductDiscount.raml
ProductDiscountChangeSortOrderAction: !include product-discount/ProductDiscountChangeSortOrderAction.raml
ProductDiscountPagedQueryResponse: !include product-discount/ProductDiscountPagedQueryResponse.raml
ProductDiscountChangeValueAction: !include product-discount/ProductDiscountChangeValueAction.raml
ProductDiscountChangePredicateAction: !include product-discount/ProductDiscountChangePredicateAction.raml
ProductDiscountReference: !include product-discount/ProductDiscountReference.raml
ProductDiscountUpdateAction: !include product-discount/ProductDiscountUpdateAction.raml
ProductDiscountUpdate: !include product-discount/ProductDiscountUpdate.raml
ProductDiscountSetDescriptionAction: !include product-discount/ProductDiscountSetDescriptionAction.raml
ProductDiscountValueExternal: !include product-discount/ProductDiscountValueExternal.raml
ProductDiscountChangeNameAction: !include product-discount/ProductDiscountChangeNameAction.raml
ProductDiscountDraft: !include product-discount/ProductDiscountDraft.raml
ProductDiscountChangeIsActiveAction: !include product-discount/ProductDiscountChangeIsActiveAction.raml
ProductDiscountValueAbsolute: !include product-discount/ProductDiscountValueAbsolute.raml
ProductDiscountValue: !include product-discount/ProductDiscountValue.raml
TransactionType: !include payment/TransactionType.raml
PaymentPagedQueryResponse: !include payment/PaymentPagedQueryResponse.raml
PaymentSetMethodInfoMethodAction: !include payment/PaymentSetMethodInfoMethodAction.raml
PaymentChangeTransactionTimestampAction: !include payment/PaymentChangeTransactionTimestampAction.raml
PaymentSetCustomFieldAction: !include payment/PaymentSetCustomFieldAction.raml
PaymentChangeAmountPlannedAction: !include payment/PaymentChangeAmountPlannedAction.raml
PaymentReference: !include payment/PaymentReference.raml
PaymentMethodInfo: !include payment/PaymentMethodInfo.raml
PaymentSetAmountRefundedAction: !include payment/PaymentSetAmountRefundedAction.raml
PaymentSetKeyAction: !include payment/PaymentSetKeyAction.raml
PaymentUpdate: !include payment/PaymentUpdate.raml
PaymentDraft: !include payment/PaymentDraft.raml
PaymentSetCustomerAction: !include payment/PaymentSetCustomerAction.raml
PaymentSetAuthorizationAction: !include payment/PaymentSetAuthorizationAction.raml
PaymentSetStatusInterfaceCodeAction: !include payment/PaymentSetStatusInterfaceCodeAction.raml
PaymentChangeTransactionInteractionIdAction: !include payment/PaymentChangeTransactionInteractionIdAction.raml
TransactionDraft: !include payment/TransactionDraft.raml
PaymentAddTransactionAction: !include payment/PaymentAddTransactionAction.raml
PaymentChangeTransactionStateAction: !include payment/PaymentChangeTransactionStateAction.raml
TransactionState: !include payment/TransactionState.raml
PaymentTransitionStateAction: !include payment/PaymentTransitionStateAction.raml
PaymentSetCustomTypeAction: !include payment/PaymentSetCustomTypeAction.raml
PaymentSetMethodInfoInterfaceAction: !include payment/PaymentSetMethodInfoInterfaceAction.raml
PaymentAddInterfaceInteractionAction: !include payment/PaymentAddInterfaceInteractionAction.raml
Payment: !include payment/Payment.raml
PaymentUpdateAction: !include payment/PaymentUpdateAction.raml
PaymentStatus: !include payment/PaymentStatus.raml
PaymentSetExternalIdAction: !include payment/PaymentSetExternalIdAction.raml
PaymentSetStatusInterfaceTextAction: !include payment/PaymentSetStatusInterfaceTextAction.raml
PaymentSetMethodInfoNameAction: !include payment/PaymentSetMethodInfoNameAction.raml
Transaction: !include payment/Transaction.raml
PaymentSetInterfaceIdAction: !include payment/PaymentSetInterfaceIdAction.raml
PaymentSetAmountPaidAction: !include payment/PaymentSetAmountPaidAction.raml
CartDiscountDraft: !include cart-discount/CartDiscountDraft.raml
CartDiscountChangeRequiresDiscountCodeAction: !include cart-discount/CartDiscountChangeRequiresDiscountCodeAction.raml
CartDiscountValueAbsolute: !include cart-discount/CartDiscountValueAbsolute.raml
CartDiscountCustomLineItemsTarget: !include cart-discount/CartDiscountCustomLineItemsTarget.raml
CartDiscountChangeCartPredicateAction: !include cart-discount/CartDiscountChangeCartPredicateAction.raml
CartDiscountChangeTargetAction: !include cart-discount/CartDiscountChangeTargetAction.raml
CartDiscountReference: !include cart-discount/CartDiscountReference.raml
CartDiscountChangeValueAction: !include cart-discount/CartDiscountChangeValueAction.raml
CartDiscountSetValidFromAction: !include cart-discount/CartDiscountSetValidFromAction.raml
CartDiscountValueRelative: !include cart-discount/CartDiscountValueRelative.raml
CartDiscountSetValidUntilAction: !include cart-discount/CartDiscountSetValidUntilAction.raml
MultiBuyLineItemsTarget: !include cart-discount/MultiBuyLineItemsTarget.raml
CartDiscountShippingCostTarget: !include cart-discount/CartDiscountShippingCostTarget.raml
CartDiscountChangeIsActiveAction: !include cart-discount/CartDiscountChangeIsActiveAction.raml
StackingMode: !include cart-discount/StackingMode.raml
CartDiscountPagedQueryResponse: !include cart-discount/CartDiscountPagedQueryResponse.raml
CartDiscountLineItemsTarget: !include cart-discount/CartDiscountLineItemsTarget.raml
CartDiscount: !include cart-discount/CartDiscount.raml
CartDiscountValueGiftLineItem: !include cart-discount/CartDiscountValueGiftLineItem.raml
CartDiscountValue: !include cart-discount/CartDiscountValue.raml
MultiBuyCustomLineItemsTarget: !include cart-discount/MultiBuyCustomLineItemsTarget.raml
CartDiscountUpdateAction: !include cart-discount/CartDiscountUpdateAction.raml
CartDiscountChangeNameAction: !include cart-discount/CartDiscountChangeNameAction.raml
CartDiscountSetDescriptionAction: !include cart-discount/CartDiscountSetDescriptionAction.raml
CartDiscountUpdate: !include cart-discount/CartDiscountUpdate.raml
SelectionMode: !include cart-discount/SelectionMode.raml
CartDiscountTarget: !include cart-discount/CartDiscountTarget.raml
CartDiscountChangeSortOrderAction: !include cart-discount/CartDiscountChangeSortOrderAction.raml
Update: !include Update.raml
InvalidSubjectError: !include error/InvalidSubjectError.raml
ErrorResponse: !include error/ErrorResponse.raml
DuplicateFieldError: !include error/DuplicateFieldError.raml
DuplicateAttributeValueError: !include error/DuplicateAttributeValueError.raml
PriceChangedError: !include error/PriceChangedError.raml
ConcurrentModificationError: !include error/ConcurrentModificationError.raml
OutOfStockError: !include error/OutOfStockError.raml
DuplicatePriceScopeError: !include error/DuplicatePriceScopeError.raml
RequiredFieldError: !include error/RequiredFieldError.raml
DuplicateAttributeValuesError: !include error/DuplicateAttributeValuesError.raml
InvalidFieldError: !include error/InvalidFieldError.raml
DiscountCodeNonApplicableError: !include error/DiscountCodeNonApplicableError.raml
VariantValues: !include error/VariantValues.raml
ResourceNotFoundError: !include error/ResourceNotFoundError.raml
InsufficientScopeError: !include error/InsufficientScopeError.raml
InvalidTokenError: !include error/InvalidTokenError.raml
DuplicateVariantValuesError: !include error/DuplicateVariantValuesError.raml
ErrorObject: !include error/ErrorObject.raml
AccessDeniedError: !include error/AccessDeniedError.raml
InvalidCredentialsError: !include error/InvalidCredentialsError.raml
InvalidOperationError: !include error/InvalidOperationError.raml
InvalidCurrentPasswordError: !include error/InvalidCurrentPasswordError.raml
MyCartDraft: !include me/MyCartDraft.raml
MyOrderFromCartDraft: !include me/MyOrderFromCartDraft.raml
MyCustomerDraft: !include me/MyCustomerDraft.raml
MyLineItemDraft: !include me/MyLineItemDraft.raml
CategoryChangeParentAction: !include category/CategoryChangeParentAction.raml
CategorySetCustomTypeAction: !include category/CategorySetCustomTypeAction.raml
CategorySetAssetDescriptionAction: !include category/CategorySetAssetDescriptionAction.raml
Category: !include category/Category.raml
CategoryUpdateAction: !include category/CategoryUpdateAction.raml
CategoryPagedQueryResponse: !include category/CategoryPagedQueryResponse.raml
CategorySetAssetCustomFieldAction: !include category/CategorySetAssetCustomFieldAction.raml
CategoryChangeAssetNameAction: !include category/CategoryChangeAssetNameAction.raml
CategorySetAssetCustomTypeAction: !include category/CategorySetAssetCustomTypeAction.raml
CategoryChangeAssetOrderAction: !include category/CategoryChangeAssetOrderAction.raml
CategoryChangeOrderHintAction: !include category/CategoryChangeOrderHintAction.raml
CategoryChangeNameAction: !include category/CategoryChangeNameAction.raml
CategoryReference: !include category/CategoryReference.raml
CategorySetAssetTagsAction: !include category/CategorySetAssetTagsAction.raml
CategorySetExternalIdAction: !include category/CategorySetExternalIdAction.raml
CategoryUpdate: !include category/CategoryUpdate.raml
CategoryChangeSlugAction: !include category/CategoryChangeSlugAction.raml
CategorySetMetaKeywordsAction: !include category/CategorySetMetaKeywordsAction.raml
CategorySetDescriptionAction: !include category/CategorySetDescriptionAction.raml
CategoryAddAssetAction: !include category/CategoryAddAssetAction.raml
CategorySetMetaDescriptionAction: !include category/CategorySetMetaDescriptionAction.raml
CategoryDraft: !include category/CategoryDraft.raml
CategorySetAssetSourcesAction: !include category/CategorySetAssetSourcesAction.raml
CategorySetCustomFieldAction: !include category/CategorySetCustomFieldAction.raml
CategorySetKeyAction: !include category/CategorySetKeyAction.raml
CategoryRemoveAssetAction: !include category/CategoryRemoveAssetAction.raml
CategorySetMetaTitleAction: !include category/CategorySetMetaTitleAction.raml
ProductTypeChangeIsSearchableAction: !include product-type/ProductTypeChangeIsSearchableAction.raml
AttributeNestedType: !include product-type/AttributeNestedType.raml
AttributeReferenceType: !include product-type/AttributeReferenceType.raml
AttributeNumberType: !include product-type/AttributeNumberType.raml
ProductTypeRemoveAttributeDefinitionAction: !include product-type/ProductTypeRemoveAttributeDefinitionAction.raml
AttributeBooleanType: !include product-type/AttributeBooleanType.raml
ProductTypePagedQueryResponse: !include product-type/ProductTypePagedQueryResponse.raml
AttributeTimeType: !include product-type/AttributeTimeType.raml
ProductTypeChangeLabelAction: !include product-type/ProductTypeChangeLabelAction.raml
AttributeLocalizableTextType: !include product-type/AttributeLocalizableTextType.raml
ProductTypeUpdate: !include product-type/ProductTypeUpdate.raml
ProductTypeDraft: !include product-type/ProductTypeDraft.raml
ProductTypeChangePlainEnumValueLabelAction: !include product-type/ProductTypeChangePlainEnumValueLabelAction.raml
AttributeDateType: !include product-type/AttributeDateType.raml
AttributeLocalizedEnumType: !include product-type/AttributeLocalizedEnumType.raml
TextInputHint: !include product-type/TextInputHint.raml
ProductTypeAddAttributeDefinitionAction: !include product-type/ProductTypeAddAttributeDefinitionAction.raml
ProductTypeSetKeyAction: !include product-type/ProductTypeSetKeyAction.raml
ProductTypeChangeNameAction: !include product-type/ProductTypeChangeNameAction.raml
ProductTypeChangeLocalizedEnumValueOrderAction: !include product-type/ProductTypeChangeLocalizedEnumValueOrderAction.raml
ProductTypeAddLocalizedEnumValueAction: !include product-type/ProductTypeAddLocalizedEnumValueAction.raml
ProductTypeChangeLocalizedEnumValueLabelAction: !include product-type/ProductTypeChangeLocalizedEnumValueLabelAction.raml
ProductTypeChangeInputHintAction: !include product-type/ProductTypeChangeInputHintAction.raml
AttributeEnumType: !include product-type/AttributeEnumType.raml
AttributeType: !include product-type/AttributeType.raml
AttributeConstraintEnum: !include product-type/AttributeConstraintEnum.raml
AttributeLocalizedEnumValue: !include product-type/AttributeLocalizedEnumValue.raml
AttributeTextType: !include product-type/AttributeTextType.raml
AttributePlainEnumValue: !include product-type/AttributePlainEnumValue.raml
AttributeMoneyType: !include product-type/AttributeMoneyType.raml
ProductTypeChangeDescriptionAction: !include product-type/ProductTypeChangeDescriptionAction.raml
ProductType: !include product-type/ProductType.raml
AttributeDefinition: !include product-type/AttributeDefinition.raml
AttributeSetType: !include product-type/AttributeSetType.raml
ProductTypeReference: !include product-type/ProductTypeReference.raml
AttributeDefinitionDraft: !include product-type/AttributeDefinitionDraft.raml
ProductTypeChangePlainEnumValueOrderAction: !include product-type/ProductTypeChangePlainEnumValueOrderAction.raml
ProductTypeUpdateAction: !include product-type/ProductTypeUpdateAction.raml
ProductTypeSetInputTipAction: !include product-type/ProductTypeSetInputTipAction.raml
AttributeDateTimeType: !include product-type/AttributeDateTimeType.raml
ProductTypeAddPlainEnumValueAction: !include product-type/ProductTypeAddPlainEnumValueAction.raml
ProductTypeChangeAttributeOrderAction: !include product-type/ProductTypeChangeAttributeOrderAction.raml
CustomerGroupSetKeyAction: !include customer-group/CustomerGroupSetKeyAction.raml
CustomerGroupUpdate: !include customer-group/CustomerGroupUpdate.raml
CustomerGroupUpdateAction: !include customer-group/CustomerGroupUpdateAction.raml
CustomerGroupPagedQueryResponse: !include customer-group/CustomerGroupPagedQueryResponse.raml
CustomerGroupChangeNameAction: !include customer-group/CustomerGroupChangeNameAction.raml
CustomerGroup: !include customer-group/CustomerGroup.raml
CustomerGroupReference: !include customer-group/CustomerGroupReference.raml
CustomerGroupDraft: !include customer-group/CustomerGroupDraft.raml
ReviewUpdateAction: !include review/ReviewUpdateAction.raml
Review: !include review/Review.raml
ReviewSetCustomerAction: !include review/ReviewSetCustomerAction.raml
ReviewSetCustomFieldAction: !include review/ReviewSetCustomFieldAction.raml
ReviewSetRatingAction: !include review/ReviewSetRatingAction.raml
ReviewSetKeyAction: !include review/ReviewSetKeyAction.raml
ReviewRatingStatistics: !include review/ReviewRatingStatistics.raml
ReviewSetLocaleAction: !include review/ReviewSetLocaleAction.raml
ReviewTransitionStateAction: !include review/ReviewTransitionStateAction.raml
ReviewUpdate: !include review/ReviewUpdate.raml
ReviewSetTargetAction: !include review/ReviewSetTargetAction.raml
ReviewSetAuthorNameAction: !include review/ReviewSetAuthorNameAction.raml
ReviewSetCustomTypeAction: !include review/ReviewSetCustomTypeAction.raml
ReviewReference: !include review/ReviewReference.raml
ReviewSetTextAction: !include review/ReviewSetTextAction.raml
ReviewPagedQueryResponse: !include review/ReviewPagedQueryResponse.raml
ReviewSetTitleAction: !include review/ReviewSetTitleAction.raml
ReviewDraft: !include review/ReviewDraft.raml
