#%RAML 1.0 Library

annotationTypes:
    generator-ignore-strict:
        type: boolean
        allowedTargets: TypeDeclaration
    generator-type:
        type: string
        allowedTargets: TypeDeclaration
    generate-collection:
        type: boolean
        allowedTargets: TypeDeclaration
types:
    Resource: !include resource.raml
    Category: !include category.raml
    CategoryDraft: !include category-draft.raml
    LocalizedString: !include localizedstring.raml
    Reference: !include reference.raml
    ResourceIdentifier: !include resource-identifier.raml
    CategoryReference: !include category-reference.raml
    CustomFields: !include custom-fields.raml
    CustomFieldsDraft: !include custom-fields-draft.raml
    Asset: !include asset.raml
    AssetSource: !include asset-source.raml
    AssetDimensions: !include asset-dimensions.raml
    AssetDraft: !include asset-draft.raml
    PagedQueryResponse: !include paged-query-response.raml
    CategoryPagedQueryResponse:  !include category-paged-query-response.raml
    Address: !include address.raml
    Money: !include money.raml
    GeoJson: !include geojson.raml
    GeoJsonPoint: !include geojson-point.raml
    Channel: !include channel.raml
    ChannelDraft: !include channel-draft.raml
    ChannelReference: !include category-reference.raml
    ReviewRatingStatistics: !include review-rating-statistics.raml
    TypeReference: !include type-reference.raml
    Type: !include type.raml
    FieldDefinition: !include field-definition.raml
    FieldType: !include field-type.raml
