#%RAML 1.0 DataType
(package): Type
(docs-uri): https://docs.commercetools.com/http-api-projects-types.html#localizedenumtype
type: FieldType
displayName: CustomFieldLocalizedEnumType
discriminatorValue: LocalizedEnum
properties:
  values:
    type: CustomFieldLocalizedEnumValue[]
