#%RAML 1.0 DataType
(package): Project
(docs-uri): https://docs.commercetools.com/http-api-projects-project.html#cartvalue
displayName: CartValueType
type: ShippingRateInputType
discriminatorValue: CartValue
