#%RAML 1.0 DataType
(package): Order
(docs-uri): https://docs.commercetools.com/http-api-projects-orders.html#parcelmeasurements
displayName: ParcelMeasurements
type: object
properties:
  heightInMillimeter?:
    type: number
    description: ''
  lengthInMillimeter?:
    type: number
    description: ''
  widthInMillimeter?:
    type: number
    description: ''
  weightInGram?:
    type: number
    description: ''
