#%RAML 1.0 DataType
(package): CustomerGroup


type: CustomerGroupUpdateAction
displayName: CustomerGroupSetCustomTypeAction
discriminatorValue: setCustomType
example: |
  {
    "action": "setCustomType",
    "type": {
      "id": "089eaa2e-b54b-42d7-811e-23e180fe8dcc",
      "typeId": "type"
    }
  }
properties:
    fields?:
        type: string
    type?:
        type: TypeReference
