#%RAML 1.0 DataType
(package): Extension
type: ExtensionDestination
displayName: ExtensionHttpDestination
discriminatorValue: HTTP
properties:
  url:
    type: string
  authentication?:
    type: ExtensionHttpDestinationAuthentication
