#%RAML 1.0 DataType
(package): Order
(docs-uri): https://docs.commercetools.com/api/projects/orders#set-returnitem-customfield
type: OrderUpdateAction
displayName: OrderSetReturnItemCustomFieldAction
discriminatorValue: setReturnItemCustomField
example: !include ../../../examples/Order/OrderSetReturnItemCustomFieldAction.json
properties:
  returnItemId:
    type: string
  name:
    type: string
  value?:
    type: any
