#%RAML 1.0 DataType
(package): Order
(docs-uri): https://docs.commercetools.com/http-api-projects-order.html#set-returninfo
type: OrderUpdateAction
displayName: OrderSetReturnInfoAction
discriminatorValue: setReturnInfo
example: !include ../../../examples/Order/OrderSetReturnInfoAction.json
properties:
  items?:
    type: ReturnInfoDraft[]
