#%RAML 1.0 DataType
(package): Order
(docs-uri): https://docs.commercetools.com/api/projects/orders#add-returninfo
example: !include ../../../examples/Order/OrderAddReturnInfoAction.json
type: OrderUpdateAction
displayName: OrderAddReturnInfoAction
discriminatorValue: addReturnInfo
description: |
  Produces the [Return Info Added](ctp:api:type:ReturnInfoAddedMessage) Message.
properties:
  returnTrackingId?:
    type: string
    description: |
      Value to set.
  items:
    type: ReturnItemDraft[]
    minItems: 1
    description: |
      Items to be returned.
      Must not be empty.
  returnDate?:
    type: datetime
    description: |
      Value to set.
      If not set, it defaults to the current date and time.
