#%RAML 1.0 DataType
(package): Order
(docs-uri): https://docs.commercetools.com/api/projects/orders#set-billing-address-customfield
type: OrderUpdateAction
displayName: OrderSetBillingAddressCustomFieldAction
discriminatorValue: setBillingAddressCustomField
(postman-example): !include ../../../examples/Order/OrderSetBillingAddressCustomFieldAction.json
properties:
  name:
    type: string
  value?:
    type: any
