#%RAML 1.0 DataType
(package): Order
(docs-uri): https://docs.commercetools.com/api/projects/orders#set-customlineitem-customfield
example: !include ../../../examples/Order/OrderSetCustomLineItemCustomFieldAction.json
type: OrderUpdateAction
displayName: OrderSetCustomLineItemCustomFieldAction
discriminatorValue: setCustomLineItemCustomField
properties:
  customLineItemId:
    type: string
    description: |
      `id` of the [CustomLineItem](ctp:api:type:CustomLineItem) to update.
  name:
    type: string
    description: |
      Name of the [Custom Field](/../api/projects/custom-fields).
  value?:
    type: CustomFieldValue
    description: |
      If `value` is absent or `null`, this field will be removed if it exists.
      Removing a field that does not exist returns an [InvalidOperation](ctp:api:type:InvalidOperationError) error.
      If `value` is provided, it is set for the field defined by `name`.
