#%RAML 1.0 DataType
(package): Order
(docs-uri): https://docs.commercetools.com/api/projects/orders#set-parcel-items
example: !include ../../../examples/Order/OrderSetParcelItemsAction.json
type: OrderUpdateAction
displayName: OrderSetParcelItemsAction
discriminatorValue: setParcelItems
description: |
  Produces the [ParcelItemsUpdated](ctp:api:type:ParcelItemsUpdatedMessage) Message.
properties:
  parcelId?:
    type: string
    description: |
      `id` of an existing [Parcel](ctp:api:type:Parcel).

      Either `parcelId` or `parcelKey` must be provided.
  parcelKey?:
    type: string
    description: |
      `key` of an existing [Parcel](ctp:api:type:Parcel).

      Either `parcelId` or `parcelKey` must be provided.
  items:
    type: DeliveryItem[]
    description: |
      Value to set.
      If empty, any existing value is removed.
