#%RAML 1.0 DataType
(package): Order
(docs-uri): https://docs.commercetools.com/api/projects/orders#change-shipmentstate
example: !include ../../../examples/Order/OrderChangeShipmentStateAction.json
type: OrderUpdateAction
displayName: OrderChangeShipmentStateAction
discriminatorValue: changeShipmentState
description: |
  Produces the [Order Shipment State Changed](ctp:api:type:OrderShipmentStateChangedMessage) Message.
properties:
  shipmentState:
    type: ShipmentState
    description: |
      New shipment status of the Order.
