#%RAML 1.0 DataType
(package): Order
(docs-uri): https://docs.commercetools.com/api/projects/orders#import-customlineitem-state
example: !include ../../../examples/Order/OrderImportCustomLineItemStateAction.json
type: OrderUpdateAction
displayName: OrderImportCustomLineItemStateAction
discriminatorValue: importCustomLineItemState
description: |
  The import of States does not follow any predefined rules and should be only used if no transitions are defined.
  The `quantity` in the [ItemStates](ctp:api:type:ItemState) must match the sum of all Custom Line Item states' quantities.
properties:
  customLineItemId?:
    type: string
    description: |
      `id` of the [CustomLineItem](ctp:api:type:CustomLineItem) to update. Either `customLineItemId` or `customLineItemKey` is required.
  customLineItemKey?:
    type: string
    description: |
      `key` of the [CustomLineItem](ctp:api:type:CustomLineItem) to update. Either `customLineItemId` or `customLineItemKey` is required.
  state:
    type: ItemState[]
    description: |
      New status of the Custom Line Items.
