#%RAML 1.0 DataType
(package): Order
(docs-uri): https://docs.commercetools.com/api/projects/orders#change-orderstate
example: !include ../../../examples/Order/OrderChangeOrderStateAction.json
type: OrderUpdateAction
displayName: OrderChangeOrderStateAction
discriminatorValue: changeOrderState
description: |
  Produces the [Order State Changed](ctp:api:type:OrderStateChangedMessage) Message.
properties:
  orderState:
    type: OrderState
    description: |
      New status of the Order.
