#%RAML 1.0 DataType
(package): Order
(docs-uri): https://docs.commercetools.com/http-api-projects-orders.html#set-billing-address
type: OrderUpdateAction
displayName: OrderSetBillingAddressAction
discriminatorValue: setBillingAddress
(postman-example): !include ../../../examples/Order/OrderSetBillingAddressAction.json
properties:
  address?:
    type: BaseAddress
