#%RAML 1.0 DataType
(package): Order
example: !include ../../../examples/Order/OrderRemovePaymentAction.json
type: OrderUpdateAction
displayName: OrderRemovePaymentAction
discriminatorValue: removePayment
description: |
  Produces the [Order Payment Removed](ctp:api:type:OrderPaymentRemovedMessage) Message.
properties:
  payment:
    type: PaymentResourceIdentifier
    description: |
      Payment to remove from the [PaymentInfo](ctp:api:type:PaymentInfo).
