#%RAML 1.0 DataType
(package): Order
(docs-uri): https://docs.commercetools.com/api/projects/orders#set-parcel-measurements
example: !include ../../../examples/Order/OrderSetParcelMeasurementsAction.json
type: OrderUpdateAction
displayName: OrderSetParcelMeasurementsAction
discriminatorValue: setParcelMeasurements
description: |
  Produces the [ParcelMeasurementsUpdated](ctp:api:type:ParcelMeasurementsUpdatedMessage) Message.
properties:
  parcelId?:
    type: string
    description: |
      `id` of an existing [Parcel](ctp:api:type:Parcel).

      Either `parcelId` or `parcelKey` must be provided.
  parcelKey?:
    type: string
    description: |
      `key` of an existing [Parcel](ctp:api:type:Parcel).

      Either `parcelId` or `parcelKey` must be provided.
  measurements?:
    type: ParcelMeasurements
    description: |
      Value to set.
      If empty, any existing value is removed.
