#%RAML 1.0 DataType
(package): Order
type: OrderUpdateAction
displayName: OrderSetShippingCustomFieldAction
discriminatorValue: setShippingCustomField
example: !include ../../../examples/Order/OrderSetShippingCustomFieldAction.json
properties:
  shippingKey?:
    type: string
    description: |
      The `shippingKey` of the [Shipping](ctp:api:type:Shipping) to customize. Used to specify which Shipping Method to customize
      on a Order with `Multiple` [ShippingMode](ctp:api:type:ShippingMode).
      Leave this empty to customize the one and only ShippingMethod on a `Single` ShippingMode Order.
  name:
    type: string
    description: |
      Name of the [Custom Field](/../api/projects/custom-fields).
  value?:
    type: CustomFieldValue
    description: |
      If `value` is absent or `null`, this field will be removed if it exists.
      Trying to remove a field that does not exist will fail with an [InvalidOperation](ctp:api:type:InvalidOperationError) error.
      If `value` is provided, it is set for the field defined by `name`.
