#%RAML 1.0 DataType
(package): Order
(docs-uri): https://docs.commercetools.com/http-api-projects-orders.html#remove-delivery
type: OrderUpdateAction
displayName: OrderRemoveDeliveryAction
discriminatorValue: removeDelivery
example: !include ../../../examples/Order/OrderRemoveDeliveryAction.json
properties:
  deliveryId?:
    type: string
    description: Either `deliveryId` or `deliveryKey` is required for this update action.
  deliveryKey?:
    type: string
    description: Either `deliveryId` or `deliveryKey` is required for this update action.
