#%RAML 1.0 DataType
(package): Order
(docs-uri): https://docs.commercetools.com/api/projects/orders#set-returnitem-customfield
example: !include ../../../examples/Order/OrderSetReturnItemCustomFieldAction.json
type: OrderUpdateAction
displayName: OrderSetReturnItemCustomFieldAction
discriminatorValue: setReturnItemCustomField
properties:
  returnItemId?:
    type: string
    description: |
      `id` of the [ReturnItem](ctp:api:type:ReturnItem) to update. Either `returnItemId` or `returnItemKey` is required.
  returnItemKey?:
    type: string
    description: |
      `key` of the [ReturnItem](ctp:api:type:ReturnItem) to update. Either `returnItemId` or `returnItemKey` is required.
  name:
    type: string
    description: |
      Name of the [Custom Field](/../api/projects/custom-fields).
  value?:
    type: CustomFieldValue
    description: |
      If `value` is absent or `null`, this field will be removed if it exists.
      Removing a field that does not exist returns an [InvalidOperation](ctp:api:type:InvalidOperationError) error.
      If `value` is provided, it is set for the field defined by `name`.
