#%RAML 1.0 DataType
(package): Order
example: !include ../../../examples/Order/OrderAddPaymentAction.json
type: OrderUpdateAction
displayName: OrderAddPaymentAction
discriminatorValue: addPayment
description: |
  Produces the [Order Payment Added](ctp:api:type:OrderPaymentAddedMessage) Message.
properties:
  payment:
    type: PaymentResourceIdentifier
    description: |
      Payment to add to the [PaymentInfo](ctp:api:type:PaymentInfo).
      Must not be assigned to another Order or active Cart already.
