#%RAML 1.0 DataType
(package): Order
(docs-uri): https://docs.commercetools.com/api/projects/orders#set-delivery-address-custom-type
type: OrderUpdateAction
displayName: OrderSetDeliveryAddressCustomTypeAction
discriminatorValue: setDeliveryAddressCustomType
(postman-example): !include ../../../examples/Order/OrderSetDeliveryAddressCustomTypeAction.json
properties:
  deliveryId:
    type: string
  type?:
    type: TypeResourceIdentifier
  fields?:
    type: FieldContainer
