#%RAML 1.0 DataType
(package): Order
(docs-uri): https://docs.commercetools.com/api/projects/orders#remove-parcel-from-delivery
example: !include ../../../examples/Order/OrderRemoveParcelFromDeliveryAction.json
type: OrderUpdateAction
displayName: OrderRemoveParcelFromDeliveryAction
discriminatorValue: removeParcelFromDelivery
description: |
  Produces the [ParcelRemovedFromDelivery](ctp:api:type:ParcelRemovedFromDeliveryMessage) Message.
properties:
  parcelId?:
    type: string
    description: |
      `id` of an existing [Parcel](ctp:api:type:Parcel).

      Either `parcelId` or `parcelKey` must be provided.
  parcelKey?:
    type: string
    description: |
      `key` of an existing [Parcel](ctp:api:type:Parcel).

      Either `parcelId` or `parcelKey` must be provided.
