#%RAML 1.0 DataType
(package): Order
(docs-uri): https://docs.commercetools.com/api/projects/orders#set-locale
example: !include ../../../examples/Order/OrderSetLocaleAction.json
type: OrderUpdateAction
displayName: OrderSetLocaleAction
discriminatorValue: setLocale
properties:
  locale?:
    type: Locale
    description: |
      Value to set.
      Must be one of the [Project](ctp:api:type:Project)'s languages.
      If empty, any existing value is removed.
