#%RAML 1.0 DataType
(package): Project


type: ProjectUpdateAction
displayName: ProjectChangeLanguagesAction
discriminatorValue: changeLanguages
properties:
    languages:
        type: array
        items: Locale
