#%RAML 1.0 DataType
(package): Project
(docs-uri): https://docs.commercetools.com/http-api-projects-project.html#project


type: object
displayName: Project
(updateType): ProjectUpdate
properties:
  version:
    type: number
    format: int64
  key:
    type: string
  name:
    type: string
    (hasSimpleUpdateAction): changeName
  countries:
    type: CountryCode[]
    (hasSimpleUpdateAction): changeCountries
  currencies:
    type: CurrencyCode[]
    (hasSimpleUpdateAction): changeCurrencies
  languages:
    type: Locale[]
    (hasSimpleUpdateAction): changeLanguages
  createdAt:
    type: datetime
  trialUntil?:
    type: string
  messages:
    type: MessageConfiguration
    (hasUpdateAction):
      action: changeMessagesConfiguration
      fields:
        messageConfiguration: MessageConfiguration
  shippingRateInputType?:
    type: ShippingRateInputType
    (hasUpdateAction):
      action: setShippingRateInputType
      docsAnchor: set-shippingrateinputtype
