#%RAML 1.0 DataType
(package): Product


type: ProductUpdateAction
displayName: ProductChangeCurrenciesAction
discriminatorValue: changeCurrencies
properties:
    currencies:
        type: array
        items: CurrencyCode
