#%RAML 1.0 DataType
(package): Project
(docs-uri): https://docs.commercetools.com/http-api-projects-project.html#project


type: object
displayName: Project
(updateType): ProjectUpdate
properties:
    version:
        type: number
        format: int64
    key:
        type: string
    name:
        type: string
    countries:
        type: CountryCode[]
    currencies:
        type: CurrencyCode[]
    languages:
        type: Locale[]
    createdAt:
        type: datetime
    trialUntil?:
        type: date-only
    messages:
        type: MessageConfiguration
    shippingRateInputType?:
        type: ShippingRateInputType
