#%RAML 1.0 DataType

displayName: CustomObjectDraft

type: object
properties:
    container:
        type: string
    key:
        type: string
    value:
        type: any
    version?:
        type: number
        format: int64
