#%RAML 1.0 DataType
(package): TaxCategory
(docs-uri): https://docs.commercetools.com/http-api-projects-taxCategories.html#add-tax-rate
type: TaxCategoryUpdateAction
displayName: TaxCategoryAddTaxRateAction
discriminatorValue: addTaxRate
(postman-example): !include ../../../examples/TaxCategory/TaxCategoryAddTaxRateAction.json
properties:
  taxRate:
    type: TaxRateDraft
    description: ''
