#%RAML 1.0 DataType


type: object
displayName: ShoppingListLineItemDraft


properties:
    addedAt?:
       type: datetime
    custom?:
       type: CustomFields
    productId:
       type: string
    quantity?:
       type: number
    variantId?:
       type: integer
