#%RAML 1.0 DataType
(package): ShoppingList
(docs-uri): https://docs.commercetools.com/http-api-projects-shoppingLists.html#add-lineitem


type: ShoppingListUpdateAction
displayName: ShoppingListAddLineItemAction
discriminatorValue: addLineItem
properties:
    addedAt?:
        type: datetime
    custom?:
        type: CustomFieldsDraft
    productId:
        type: string
    quantity?:
        type: number
    variantId?:
        type: integer
