#%RAML 1.0 DataType


type: ShoppingListUpdateAction
displayName: ShoppingListSetTextLineItemCustomTypeAction

properties:
    fields?:
        type: string
    textLineItemId:
        type: string
    type?:
        type: Type
