#%RAML 1.0 DataType
(package): ShoppingList


type: ShoppingListUpdateAction
displayName: ShoppingListChangeTextLineItemNameAction
discriminatorValue: changeTextLineItemName
properties:
    name:
        type: LocalizedString
    textLineItemId:
        type: string
