#%RAML 1.0 DataType
(package): ShoppingList


type: ShoppingListUpdateAction
displayName: ShoppingListSetTextLineItemCustomFieldAction
discriminatorValue: setTextLineItemCustomField
properties:
    name:
        type: string
    textLineItemId:
        type: string
    value?:
        type: any
