#%RAML 1.0 DataType
(package): ShoppingList
type: object
displayName: ShoppingListUpdateAction
discriminator: action
(java-extends): 'com.commercetools.api.models.ResourceUpdateAction<ShoppingListUpdateAction>'
properties:
  action:
    type: string
