#%RAML 1.0 DataType
(package): ShoppingList
(docs-uri): https://docs.commercetools.com/http-api-projects-shoppingLists.html#change-description


type: ShoppingListUpdateAction
displayName: ShoppingListSetDescriptionAction
discriminatorValue: setDescription
properties:
    description?:
        type: LocalizedString
