#%RAML 1.0 DataType
(package): ShoppingList
(docs-uri): https://docs.commercetools.com/http-api-projects-shoppingLists.html#set-textlineitem-description


type: ShoppingListUpdateAction
displayName: ShoppingListSetTextLineItemDescriptionAction
discriminatorValue: setTextLineItemDescription
properties:
    description?:
        type: LocalizedString
    textLineItemId:
        type: string
