#%RAML 1.0 DataType
(package): ShoppingList
type: object
displayName: ShoppingListLineItem
properties:
  addedAt:
    type: datetime
  custom?:
    type: CustomFields
  deactivatedAt?:
    type: datetime
  id:
    type: string
  name:
    type: LocalizedString
  productId:
    type: string
  productSlug?:
    type: LocalizedString
  productType:
    type: ProductTypeReference
  quantity:
    type: number
    format: int32
  variant?:
    type: ProductVariant
  variantId?:
    type: number
    format: int64
