#%RAML 1.0 DataType
(package): ShoppingList


type: ShoppingListUpdateAction
displayName: ShoppingListSetDescriptionAction
discriminatorValue: setDescription
properties:
    description?:
        type: LocalizedString
