#%RAML 1.0 DataType
(package): ShoppingList


type: object
displayName: TextLineItem


properties:
  addedAt:
    type: datetime
  custom?:
    type: CustomFields
  description?:
    type: LocalizedString
  id:
    type: string
  name:
    type: LocalizedString
  quantity:
    type: number
