#%RAML 1.0 DataType
(package): Project
type: string
displayName: CustomerIndexingStatus
description: |
  The current indexing status of Customer Search.
(enumDescriptions):
  Scheduled: Indexing is scheduled.
  Indexing: Indexing is in progress.
  Ready: Indexing is complete and the [Search Customers](ctp:api:endpoint:/{projectKey}/customers/search:POST) endpoint returns up-to-date results.
  Failed: Indexing failed due to an internal error.
enum:
  - Scheduled
  - Indexing
  - Ready
  - Failed
