#%RAML 1.0 DataType
(package): CustomerSearch
displayName: CustomerSearchResult
type: object
(beta): true
properties:
  id:
    (identifier): true
    type: string
    description: |
      `id` of the [Customer](ctp:api:type:Customer) matching the search query.
  relevance:
    type: number
    description: |
      How closely this customer matches the search query.
