#%RAML 1.0 DataType
(package): ShoppingList
type: ShoppingListUpdateAction
displayName: ShoppingListSetAnonymousIdAction
discriminatorValue: setAnonymousId
example: !include ../../../examples/ShoppingList/ShoppingListSetAnonymousIdAction.json
properties:
  anonymousId?:
    type: string
    description: |
      Value to set. If empty, any existing value will be removed.
