#%RAML 1.0 DataType
(package): ShoppingList
(docs-uri): https://docs.commercetools.com/api/projects/shoppingLists#change-textlineitems-order
type: ShoppingListUpdateAction
displayName: ShoppingListChangeTextLineItemsOrderAction
discriminatorValue: changeTextLineItemsOrder
example: !include ../../../examples/ShoppingList/ShoppingListChangeTextLineItemsOrderAction.json
properties:
  textLineItemOrder:
    type: string[]
    description: |
      Must contain all existing [TextLineItem](ctp:api:type:TextLineItem) `id`s in the desired new order.
