#%RAML 1.0 DataType
(package): ShoppingList
(docs-uri): https://docs.commercetools.com/api/projects/shoppingLists#remove-textlineitem
type: ShoppingListUpdateAction
displayName: ShoppingListRemoveTextLineItemAction
discriminatorValue: removeTextLineItem
example: !include ../../../examples/ShoppingList/ShoppingListRemoveTextLineItemAction.json
properties:
  textLineItemId:
    type: string
    description: |
      The `id` of the [TextLineItem](ctp:api:type:TextLineItem) to update.
  quantity?:
    type: number
    format: int64
    minimum: 1
    description: |
      Amount to remove from the `quantity` of the TextLineItem. If not set, the TextLineItem is removed from the ShoppingList. If this value matches or exceeds the current `quantity` of the TextLineItem, the TextLineItem is removed from the ShoppingList.
