#%RAML 1.0 DataType
(package): ShoppingList
type: ShoppingListUpdateAction
displayName: ShoppingListChangeTextLineItemsOrderAction
discriminatorValue: changeTextLineItemsOrder
example: !include ../../../examples/ShoppingList/ShoppingListChangeTextLineItemsOrderAction.json
properties:
  textLineItemOrder:
    type: string[]
    description: |
      Must contain all existing [TextLineItem](ctp:api:type:TextLineItem) `id`s in the desired new order.
