#%RAML 1.0 DataType
(package): ShoppingList
(docs-uri): https://docs.commercetools.com/api/projects/shoppingLists#set-textlineitem-custom-type
type: ShoppingListUpdateAction
displayName: ShoppingListSetTextLineItemCustomTypeAction
discriminatorValue: setTextLineItemCustomType
example: !include ../../../examples/ShoppingList/ShoppingListSetTextLineItemCustomTypeAction.json
properties:
  textLineItemId:
    type: string
    description: |
      The `id` of the [TextLineItem](ctp:api:type:TextLineItem) to update.
  type?:
    type: TypeResourceIdentifier
    description: |
      Defines the [Type](ctp:api:type:Type) that extends the TextLineItem with [Custom Fields](/../api/projects/custom-fields).
      If absent, any existing Type and Custom Fields are removed from the TextLineItem.
  fields?:
    type: FieldContainer
    description: |
      Sets the [Custom Fields](/../api/projects/custom-fields) fields for the TextLineItem.
