#%RAML 1.0 DataType
(package): Type
(docs-uri): https://docs.commercetools.com/http-api-projects-types.html#add-fielddefinition
type: TypeUpdateAction
displayName: TypeAddFieldDefinitionAction
discriminatorValue: addFieldDefinition
(postman-example): !include ../../../examples/Type/TypeAddFieldDefinitionAction.json
properties:
  fieldDefinition:
    type: FieldDefinition
