#%RAML 1.0 DataType
(package): Type
type: TypeUpdateAction
displayName: TypeChangeKeyAction
discriminatorValue: changeKey
example: !include ../../../examples/Type/TypeChangeKeyAction.json
properties:
  key:
    type: string
    description: |
      New value to set.
      Must not be empty.
    pattern: ^[A-Za-z0-9_-]+$
    minLength: 2
    maxLength: 256
