#%RAML 1.0 DataType
(package): Type
(docs-uri): https://docs.commercetools.com/http-api-projects-types.html#add-enumvalue-to-fielddefinition
type: TypeUpdateAction
displayName: TypeAddEnumValueAction
discriminatorValue: addEnumValue
example: !include ../../../examples/Type/TypeAddEnumValueAction.json
description: |
  Adds a value to an [EnumType](ctp:api:type:CustomFieldEnumType).
  This update action can be used to update an [EnumType](ctp:api:type:CustomFieldEnumType) FieldDefinition and a [SetType](ctp:api:type:CustomFieldSetType) FieldDefinition of [EnumType](ctp:api:type:CustomFieldEnumType).
properties:
  fieldName:
    type: string
    description: |
      `name` of the [Field Definition](ctp:api:type:FieldDefinition) to update.
  value:
    type: CustomFieldEnumValue
    description: Value to append to the array.
