#%RAML 1.0 DataType
(package): Type
type: TypeUpdateAction
displayName: TypeChangeInputHintAction
example: !include ../../../examples/Type/TypeChangeInputHintAction.json
discriminatorValue: changeInputHint
description: |
  Changes the `inputHint` of [CustomFieldStringType](ctp:api:type:CustomFieldStringType) [FieldDefinition](ctp:api:type:FieldDefinition), a [CustomFieldLocalizedStringType](ctp:api:type:CustomFieldLocalizedStringType) [FieldDefinition](ctp:api:type:FieldDefinition), and [CustomFieldSetType](ctp:api:type:CustomFieldSetType) [FieldDefinition](ctp:api:type:FieldDefinition) of these string-based FieldTypes.
properties:
  fieldName:
    type: string
    description: |
      `name` of the [Field Definition](ctp:api:type:FieldDefinition) to update.
  inputHint:
    type: TypeTextInputHint
    description: |
      New value to set.
      Must not be empty.
