#%RAML 1.0 DataType
(package): Type
(docs-uri): https://docs.commercetools.com/http-api-projects-types.html#remove-fielddefinition
type: TypeUpdateAction
displayName: TypeRemoveFieldDefinitionAction
discriminatorValue: removeFieldDefinition
example: !include ../../../examples/Type/TypeRemoveFieldDefinitionAction.json
properties:
  fieldName:
    type: string
    description: |
      `name` of the [FieldDefinition](ctp:api:type:FieldDefinition) to remove.
      The removal of a FieldDefinition deletes [asynchronously](/../api/general-concepts#eventual-consistency) all Custom Fields using the FieldDefinition as well.
