#%RAML 1.0 DataType
(package): VariantAttributes
displayName: VariantAttributesChannelAvailabilityMap
type: object
(beta): true
(asMap):
  key: string
  value: VariantAttributesChannelAvailability
description: |
  JSON object where the keys are supply [Channel](ctp:api:type:Channel) `id`, and the values are [VariantAttributesChannelAvailability](ctp:api:type:VariantAttributesChannelAvailability).
properties:
  /^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/:
    type: VariantAttributesChannelAvailability
    description: |
      The availability for a specific supply [Channel](ctp:api:type:Channel).
