#%RAML 1.0 DataType
(package): VariantAttributes
displayName: VariantAttributesVariant
type: object
(beta): true
description: |
  A Variant with its requested Attributes and lightweight availability information.
properties:
  id:
    type: string
    description: |
      Unique identifier of the [Variant](ctp:api:type:Variant).
  sku?:
    type: string
    description: |
      SKU of the [Variant](ctp:api:type:Variant).
  key?:
    type: string
    description: |
      Key of the [Variant](ctp:api:type:Variant).
  availability?:
    type: VariantAttributesAvailability
    description: |
      Availability information for this variant.
      Present only if [InventoryEntries](ctp:api:type:InventoryEntry) exist for the variant's SKU.
  attributes:
    type: array
    items: Attribute
    description: |
      Requested [Attributes](ctp:api:type:Attribute) of the Variant.
      Only Variant-level Attributes that exist on this Variant and were requested via `filter[attributes]` are included.
