#%RAML 1.0 DataType
(package): Category
type: Reference
displayName: CategoryReference
discriminatorValue: category
description: |
  [Reference](ctp:api:type:Reference) to a [Category](ctp:api:type:Category).
properties:
  obj?:
    type: Category
    description: |
      Contains the representation of the expanded Category. Only present in responses to requests with [Reference Expansion](/../api/general-concepts#reference-expansion) for Categories.
  id:
    type: string
    description: |
      Unique identifier of the referenced [Category](ctp:api:type:Category).
