#%RAML 1.0 DataType
(package): Category
(docs-uri): https://docs.commercetools.com/api/projects/categories#category
displayName: Category
(updateType): CategoryUpdate
type: BaseResource
properties:
  id:
    (identifier): true
    type: string
    description: |
      Unique identifier of the Category.
  version:
    type: number
    format: int64
    description: |
      Current version of the Category.
  createdAt:
    type: datetime
    description: |
      Date and time (UTC) the Category was initially created.
  lastModifiedAt:
    type: datetime
    description: |
      Date and time (UTC) the Category was last updated.
  lastModifiedBy?:
    type: LastModifiedBy
    (beta): true
    description: |
      Present on resources updated after 1 February 2019 except for [events not tracked](/../api/general-concepts#events-tracked).
  createdBy?:
    type: CreatedBy
    (beta): true
    description: |
      Present on resources created after 1 February 2019 except for [events not tracked](/../api/general-concepts#events-tracked).
  name:
    type: LocalizedString
    description: |
      Name of the Category.
  slug:
    type: LocalizedString
    description: |
      User-defined identifier used as a deep-link URL to the related Category per [Locale](ctp:api:type:Locale).
      A Category can have the same slug for different Locales, but they are unique across the [Project](ctp:api:type:Project).
      Valid slugs match the pattern `^[A-Za-z0-9_-]{2,256}+$`.
      For [good performance](/../api/predicates/query#performance-considerations), indexes are provided for the first 15 `languages` set in a Project.
  description?:
    type: LocalizedString
    description: |
      Description of the Category.
  ancestors:
    description: |
      Contains the parent path towards the root Category.
    type: CategoryReference[]
  parent?:
    type: CategoryReference
    description: |
      Parent Category of this Category.
  orderHint:
    type: string
    description: |
      Decimal value between 0 and 1 used to order Categories that are on the same level in the Category tree.
  externalId?:
    type: string
    description: |
      Additional identifier for external systems like Customer Relationship Management (CRM) or Enterprise Resource Planning (ERP).
  metaTitle?:
    type: LocalizedString
    description: |
      Name of the Category used by external search engines for improved search engine performance.
  metaDescription?:
    type: LocalizedString
    description: |
      Description of the Category used by external search engines for improved search engine performance.
  metaKeywords?:
    type: LocalizedString
    description: |
      Keywords related to the Category for improved search engine performance.
  custom?:
    type: CustomFields
    description: |
      Custom Fields for the Category.
  assets?:
    type: Asset[]
    description: |
      Media related to the Category.
  key?:
    type: string
    description: |
      User-defined unique identifier of the Category.
    pattern: ^[A-Za-z0-9_-]+$
    minLength: 2
    maxLength: 256
