#%RAML 1.0 DataType
(package): Category
(docs-uri): https://docs.commercetools.com/http-api-projects-categories.html#category
(java-extends): com.commercetools.api.models.Identifiable<Category>
type: ResourceIdentifier
displayName: CategoryResourceIdentifier
discriminatorValue: category
description: |
  [ResourceIdentifier](ctp:api:type:ResourceIdentifier) to a [Category](ctp:api:type:Category).
properties:
  id?:
    type: string
    description: |
      Unique identifier of the referenced [Category](ctp:api:type:Channel). Either `id` or `key` is required.
  key?:
    type: string
    description: |
      User-defined unique identifier of the referenced [Category](ctp:api:type:Category). Either `id` or `key` is required.
