#%RAML 1.0 DataType
(package): Category
displayName: CategoryDraft
type: object
properties:
  name:
    type: LocalizedString
    description: |
      Name of the Category.
  slug:
    type: LocalizedString
    description: |
      User-defined identifier used as a deep-link URL to the related Category.
      A Category can have the same slug for different [Locales](ctp:api:type:Locale), but it must be unique across the [Project](ctp:api:type:Project).
      Valid slugs must match the pattern `^[A-Za-z0-9_-]{2,256}+$`.
  description?:
    type: LocalizedString
    description: |
      Description of the Category.
  parent?:
    description: |
      Parent Category of the Category.
      The parent can be set by its `id` or `key`.
    type: CategoryResourceIdentifier
  orderHint?:
    type: string
    description: |
      Decimal value between 0 and 1. Frontend applications can use this value for ordering Categories within the same level in the category tree.
      If not set, a random value will be assigned.
  externalId?:
    type: string
    description: |
      Additional identifier for external systems like customer relationship management (CRM) or enterprise resource planning (ERP).
  metaTitle?:
    type: LocalizedString
    description: |
      Name of the Category used by external search engines for improved search engine performance.
  metaDescription?:
    type: LocalizedString
    description: |
      Description of the Category used by external search engines for improved search engine performance.
  metaKeywords?:
    type: LocalizedString
    description: |
      Keywords related to the Category for improved search engine performance.
  custom?:
    type: CustomFieldsDraft
    description: |
      Custom Fields for the Category.
  assets?:
    type: AssetDraft[]
    description: |
      Media related to the Category.
  key?:
    type: string
    description: |
      User-defined unique identifier for the Category.

      This field is optional for backwards compatibility reasons, but we strongly recommend setting it. Keys are mandatory for importing Categories with the [Import API](/../import-export/) and the [Merchant Center](/../merchant-center/import-data).
    pattern: ^[A-Za-z0-9_-]+$
    minLength: 2
    maxLength: 256
