type:
  baseDomain:
    resourceType: Category
    resourceQueryType: CategoryPagedQueryResponse
    resourceDraft: CategoryDraft
    resourceExample: !include ../examples/category.example.json
    resourceQueryExample: !include ../examples/categories.example.json
    resourceCreateExample: !include ../examples/category-create.example.json
    readScopes: ["manage_project:{projectKey}", "view_products:{projectKey}"]
    writeScopes: ["manage_project:{projectKey}", "manage_products:{projectKey}"]
    whereExample: slug(en = "long-sleeves")
    sortExample: name.en asc
description: Categories are used to organize products in a hierarchical structure.
post:
/key={key}:
  type:
    baseResource:
      uriParameterName: key
      resourceType: Category
      resourceUpdateType: Update
      resourceExample: !include ../examples/category.example.json
      resourceUpdateExample: !include ../examples/category-update.example.json
      readScopes: ["manage_project:{projectKey}", "view_products:{projectKey}"]
      writeScopes: ["manage_project:{projectKey}", "manage_products:{projectKey}"]
  get:
  post:
  delete:
/{ID}:
  type:
    baseResource:
      uriParameterName: ID
      resourceType: Category
      resourceUpdateType: Update
      resourceUpdateExample: !include ../examples/category-update.example.json
      resourceExample: !include ../examples/category.example.json
      readScopes: ["manage_project:{projectKey}", "view_products:{projectKey}"]
      writeScopes: ["manage_project:{projectKey}", "manage_products:{projectKey}"]
  get:
  post:
  delete:
