type:
  baseDomain:
    resourceType: Channel
    resourceQueryType: ChannelPagedQueryResponse
    resourceDraft: ChannelDraft
    resourceExample: !include ../examples/channel.example.json
    resourceQueryExample: !include ../examples/channels.example.json
    resourceCreateExample: !include ../examples/channel-create.example.json
    whereExample: key = "berlin-store"
    sortExample: createdAt asc
description: Channels represent a source or destination of different entities. They can be used to model warehouses or stores.
get:
  securedBy: [oauth_2_0: {scopes: ["manage_project:{projectKey}", "view_products:{projectKey}"]}]
post:
  securedBy: [oauth_2_0: {scopes: ["manage_project:{projectKey}", "manage_products:{projectKey}"]}]
/{ID}:
  type:
    baseResource:
      uriParameterName: ID
      resourceType: Channel
      resourceUpdateType: Update
      resourceUpdateExample: !include ../examples/channel-update.example.json
      resourceExample: !include ../examples/channel.example.json
  get:
    securedBy: [oauth_2_0: {scopes: ["manage_project:{projectKey}", "view_products:{projectKey}"]}]
  post:
    securedBy: [oauth_2_0: {scopes: ["manage_project:{projectKey}", "manage_products:{projectKey}"]}]
  delete:
    securedBy: [oauth_2_0: {scopes: ["manage_project:{projectKey}", "manage_products:{projectKey}"]}]

