type:
  baseDomain:
    resourceType: CustomerGroup
    resourceQueryType: CustomerGroupPagedQueryResponse
    resourceDraft: CustomerGroupDraft
    whereExample: name = "VIP"
    sortExample: createdAt asc
description: customer-groups are used to evaluate products and channels.
get:
  securedBy: [oauth_2_0: {scopes: ["manage_project:{projectKey}", "view_customers:{projectKey}"]}]
  responses:
    200:
      body:
        application/json:
          example: !include ../examples/customer-groups.example.json
post:
  securedBy: [oauth_2_0: {scopes: ["manage_project:{projectKey}", "manage_customers:{projectKey}"]}]
  body:
    application/json:
      example: !include ../examples/customer-group-create.example.json
  responses:
    201:
      body:
        application/json:
          example: !include ../examples/customer-group.example.json
/key={key}:
  (methodName): withKey
  type:
    baseResource:
      uriParameterName: key
      resourceType: CustomerGroup
      resourceUpdateType: Update
  get:
    securedBy: [oauth_2_0: {scopes: ["manage_project:{projectKey}", "view_customers:{projectKey}"]}]
    description: Gets a customer group by Key.
    responses:
      200:
        body:
          application/json:
            example: !include ../examples/customer-group.example.json
  post:
    securedBy: [oauth_2_0: {scopes: ["manage_project:{projectKey}", "manage_customers:{projectKey}"]}]
    description: Updates a customer group by Key.
    body:
      application/json:
        example: !include ../examples/customer-group-update.example.json
    responses:
      200:
        body:
          application/json:
            example: !include ../examples/customer-group.example.json
  delete:
    securedBy: [oauth_2_0: {scopes: ["manage_project:{projectKey}", "manage_customers:{projectKey}"]}]
    responses:
      200:
        body:
          application/json:
            example: !include ../examples/customer-group.example.json
/{ID}:
  (methodName): withId
  type:
    baseResource:
      uriParameterName: ID
      resourceType: CustomerGroup
      resourceUpdateType: Update
  get:
    securedBy: [oauth_2_0: {scopes: ["manage_project:{projectKey}", "view_customers:{projectKey}"]}]
    responses:
      200:
        body:
          application/json:
            example: !include ../examples/customer-group.example.json
  post:
    securedBy: [oauth_2_0: {scopes: ["manage_project:{projectKey}", "manage_customers:{projectKey}"]}]
    body:
      application/json:
        example: !include ../examples/customer-group-update.example.json
    responses:
      200:
        body:
          application/json:
            example: !include ../examples/customer-group.example.json
  delete:
    securedBy: [oauth_2_0: {scopes: ["manage_project:{projectKey}", "manage_customers:{projectKey}"]}]
    responses:
      200:
        body:
          application/json:
            example: !include ../examples/customer-group.example.json
