type:
  baseDomain:
    resourceType: CustomerGroup
    resourceQueryType: CustomerGroupPagedQueryResponse
    resourceDraft: CustomerGroupDraft
    resourceExample: !include ../examples/customer-group.example.json
    resourceQueryExample: !include ../examples/customer-groups.example.json
    resourceCreateExample: !include ../examples/customer-group-create.example.json
    readScopes: ["manage_project:{projectKey}", "view_customers:{projectKey}"]
    writeScopes: ["manage_project:{projectKey}", "manage_customers:{projectKey}"]
    whereExample: name = "VIP"
    sortExample: createdAt asc
description: customer-groups are used to evaluate products and channels.
post:
/key={key}:
  type:
    baseResource:
      uriParameterName: key
      resourceType: CustomerGroup
      resourceUpdateType: Update
      resourceExample: !include ../examples/customer-group.example.json
      resourceUpdateExample: !include ../examples/customer-group-update.example.json
      readScopes: ["manage_project:{projectKey}", "view_customers:{projectKey}"]
      writeScopes: ["manage_project:{projectKey}", "manage_customers:{projectKey}"]
  get:
  post:
  delete:
/{ID}:
  type:
    baseResource:
      uriParameterName: ID
      resourceType: CustomerGroup
      resourceUpdateType: Update
      resourceUpdateExample: !include ../examples/customer-group-update.example.json
      resourceExample: !include ../examples/customer-group.example.json
      readScopes: ["manage_project:{projectKey}", "view_customers:{projectKey}"]
      writeScopes: ["manage_project:{projectKey}", "manage_customers:{projectKey}"]
  get:
  post:
  delete:
