type:
  baseDomain:
    resourceType: CustomObject
    resourceQueryType: CustomObjectPagedQueryResponse
    resourceDraft: CustomObjectDraft
    whereExample: value = "john.doe@example.com"
    sortExample: createdAt asc
description: Store custom JSON values.
get:
  securedBy:
    - oauth_2_0:
        scopes:
          - "manage_project:{projectKey}"
          - "view_products:{projectKey}"
          - "view_orders:{projectKey}"
          - "view_customers:{projectKey}"
  responses:
    200:
      body:
        application/json:
          example: !include ../examples/custom-objects.example.json
post:
  securedBy:
    - oauth_2_0:
        scopes:
          - "manage_project:{projectKey}"
          - "manage_products:{projectKey}"
          - "manage_orders:{projectKey}"
          - "manage_customers:{projectKey}"
  body:
    application/json:
      example: !include ../examples/custom-object-create.example.json
  responses:
    201:
      body:
        application/json:
          example: !include ../examples/custom-object.example.json
/{container}/{key}:
  (methodName): withContainerAndKey
  type:
    baseResource:
      uriParameterName: key
      resourceType: CustomObject
  get:
    securedBy:
      - oauth_2_0:
          scopes:
            - "manage_project:{projectKey}"
            - "view_products:{projectKey}"
            - "view_orders:{projectKey}"
            - "view_customers:{projectKey}"
    responses:
      200:
        body:
          application/json:
            example: !include ../examples/custom-object.example.json
  delete:
    is:
      - dataErasure
    securedBy:
      - oauth_2_0:
          scopes:
            - "manage_project:{projectKey}"
            - "manage_products:{projectKey}"
            - "manage_orders:{projectKey}"
            - "manage_customers:{projectKey}"
    queryParameters:
      version:
        required: false
    responses:
      200:
        body:
          application/json:
            example: !include ../examples/custom-object.example.json
/{ID}:
  (methodName): withId
  type:
    baseResource:
      uriParameterName: container
      resourceType: CustomObject
  get:
    securedBy:
      - oauth_2_0:
          scopes:
            - "manage_project:{projectKey}"
            - "view_products:{projectKey}"
            - "view_orders:{projectKey}"
            - "view_customers:{projectKey}"
    responses:
      200:
        body:
          application/json:
            example: !include ../examples/custom-object.example.json
  delete:
    is:
      - dataErasure
    securedBy:
      - oauth_2_0:
          scopes:
            - "manage_project:{projectKey}"
            - "manage_products:{projectKey}"
            - "manage_orders:{projectKey}"
            - "manage_customers:{projectKey}"
    queryParameters:
      version:
        required: false
    responses:
      200:
        body:
          application/json:
            example: !include ../examples/custom-object.example.json
