type:
  baseDomain:
    resourceType: DiscountCode
    resourceQueryType: DiscountCodePagedQueryResponse
    resourceDraft: DiscountCodeDraft
    resourceExample: !include ../examples/discount-code.example.json
    resourceQueryExample: !include ../examples/discount-codes.example.json
    resourceCreateExample: !include ../examples/discount-code-create.example.json
    whereExample: code = "summersale"
    sortExample: createdAt asc
description: Discount codes can be added to a cart to enable certain cart discounts.
get:
  securedBy: [oauth_2_0: {scopes: ["manage_project:{projectKey}", "view_orders:{projectKey}"]}]
post:
  securedBy: [oauth_2_0: {scopes: ["manage_project:{projectKey}", "manage_orders:{projectKey}"]}]
/{ID}:
  (methodName): withId
  type:
    baseResource:
      uriParameterName: ID
      resourceType: DiscountCode
      resourceUpdateType: Update
      resourceUpdateExample: !include ../examples/discount-code-update.example.json
      resourceExample: !include ../examples/discount-code.example.json
  get:
    securedBy: [oauth_2_0: {scopes: ["manage_project:{projectKey}", "view_orders:{projectKey}"]}]
  post:
    securedBy: [oauth_2_0: {scopes: ["manage_project:{projectKey}", "manage_orders:{projectKey}"]}]
  delete:
    is:
      - dataErasure
    securedBy: [oauth_2_0: {scopes: ["manage_project:{projectKey}", "manage_orders:{projectKey}"]}]
