type: base
get:
  is:
    - query:
        whereExample: customerEmail = "foo@bar.com"
    - sortable:
        sortExample: createdAt asc
    - paging
    - expandable
  securedBy: [oauth_2_0: {scopes: ["manage_my_profile:{projectKey}"]}]
  responses:
    200:
      body:
        application/json:
          type: Customer
post:
  description: Create a customer
  securedBy: [oauth_2_0: {scopes: ["manage_my_profile:{projectKey}"]}]
  body:
    application/json:
      example: !include ../examples/customer-update.example.json
      type: Update
  responses:
    200:
      body:
        application/json:
          example: !include ../examples/customer-update-response.example.json
          type: Customer
delete:
  description: Delete a Customer
  is:
    - versioned
    - conflicting
  securedBy: [oauth_2_0: {scopes: ["manage_my_profile:{projectKey}"]}]
  responses:
    200:
      body:
        application/json:
          example: !include ../examples/customer.example.json
          type: Customer
/email:
  /confirm:
    type: base
    post:
      securedBy: [oauth_2_0: {scopes: ["manage_my_profile:{projectKey}"]}]
/password:
  type: base
  post:
    is:
      - conflicting
    securedBy: [oauth_2_0: {scopes: ["manage_my_profile:{projectKey}"]}]
    body:
      application/json:
    responses:
      200:
        body:
          application/json:
            example: !include ../examples/customer.example.json
            type: Customer
  /reset:
    type: base
    post:
      securedBy: [oauth_2_0: {scopes: ["manage_my_profile:{projectKey}"]}]
      responses:
        200:
          body:
            application/json:
              example: !include ../examples/customer.example.json
              type: Customer
/signup:
  type: base
  post:
    securedBy: [oauth_2_0: {scopes: ["manage_my_profile:{projectKey}"]}]
    body:
      application/json:
        type: MyCustomerDraft
    responses:
      201:
        body:
          application/json:
            type: CustomerSignInResult
/login:
  type: base
  post:
    securedBy: [oauth_2_0: {scopes: ["manage_my_profile:{projectKey}"]}]
    body:
      application/json:
    responses:
      200:
        body:
          application/json:
            type: CustomerSignInResult
/active-cart:
  type: base
  get:
    securedBy: [oauth_2_0: {scopes: ["manage_my_orders:{projectKey}"]}]
    responses:
      200:
        body:
          application/json:
            type: Cart
/carts:
  type:
    baseDomain:
      resourceType: Cart
      resourceQueryType: CartPagedQueryResponse
      resourceDraft: MyCartDraft
      whereExample: customerEmail = "john.doe@example.com"
      sortExample: createdAt asc
  description: A shopping cart holds product variants and can be ordered.
  get:
    securedBy: [oauth_2_0: {scopes: ["manage_my_orders:{projectKey}"]}]
    responses:
      200:
        body:
          application/json:
            example: !include ../examples/carts.example.json
  post:
    securedBy: [oauth_2_0: {scopes: ["manage_my_orders:{projectKey}"]}]
    body:
      application/json:
        example: !include ../examples/cart-create.example.json
    responses:
      201:
        body:
          application/json:
            example: !include ../examples/cart.example.json
  /{ID}:
    (methodName): withId
    type:
      baseResource:
        uriParameterName: ID
        resourceType: Cart
        resourceUpdateType: Update
    get:
      securedBy: [oauth_2_0: {scopes: ["manage_my_orders:{projectKey}"]}]
      responses:
        200:
          body:
            application/json:
              example: !include ../examples/cart.example.json
    post:
      securedBy: [oauth_2_0: {scopes: ["manage_my_orders:{projectKey}"]}]
      body:
        application/json:
          example: !include ../examples/cart-update.example.json
      responses:
        200:
          body:
            application/json:
              example: !include ../examples/cart.example.json
    delete:
      securedBy: [oauth_2_0: {scopes: ["manage_my_orders:{projectKey}"]}]
      responses:
        200:
          body:
            application/json:
              example: !include ../examples/cart.example.json
/orders:
  type:
    baseDomain:
      resourceType: Order
      resourceQueryType: OrderPagedQueryResponse
      resourceDraft: MyOrderFromCartDraft
      whereExample: customerEmail = "john.doe@example.com"
      sortExample: createdAt asc
  description: An order can be created from a cart, usually after a checkout process has been completed.
  get:
    securedBy: [oauth_2_0: {scopes: ["manage_my_orders:{projectKey}"]}]
    responses:
      200:
        body:
          application/json:
            example: !include ../examples/orders.example.json
  post:
    securedBy: [oauth_2_0: {scopes: ["manage_my_orders:{projectKey}"]}]
    body:
      application/json:
        example: !include ../examples/order-create.example.json
    responses:
      201:
        body:
          application/json:
            example: !include ../examples/order.example.json
  /{ID}:
    (methodName): withId
    type:
      baseResource:
        uriParameterName: ID
        resourceType: Order
        resourceUpdateType: Update
    get:
      securedBy: [oauth_2_0: {scopes: ["manage_my_orders:{projectKey}"]}]
      responses:
        200:
          body:
            application/json:
              example: !include ../examples/order.example.json
    post:
      securedBy: [oauth_2_0: {scopes: ["manage_my_orders:{projectKey}"]}]
      body:
        application/json:
          example: !include ../examples/order-update.example.json
      responses:
        200:
          body:
            application/json:
              example: !include ../examples/order.example.json
/shopping-lists:
  type:
    baseDomain:
      resourceType: ShoppingList
      resourceQueryType: ShoppingListPagedQueryResponse
      resourceDraft: MyShoppingListDraft
      whereExample: name(en = "list-name")
      sortExample: createdAt asc
  description: The My Shopping Lists endpoint creates and provides access to shopping lists scoped to a specific user.
  get:
    securedBy: [oauth_2_0: {scopes: ["manage_my_shopping_lists:{projectKey}"]}]
    responses:
      200:
        body:
          application/json:
            example: !include ../examples/shopping-lists.example.json
  post:
    securedBy: [oauth_2_0: {scopes: ["manage_my_shopping_lists:{projectKey}"]}]
    body:
      application/json:
        example: !include ../examples/shopping-list-create.example.json
    responses:
      201:
        body:
          application/json:
            example: !include ../examples/shopping-list.example.json
  /{ID}:
    (methodName): withId
    type:
      baseResource:
        uriParameterName: ID
        resourceType: ShoppingList
        resourceUpdateType: Update
    get:
      securedBy: [oauth_2_0: {scopes: ["manage_my_shopping_lists:{projectKey}"]}]
      responses:
        200:
          body:
            application/json:
              example: !include ../examples/shopping-list.example.json
    post:
      securedBy: [oauth_2_0: {scopes: ["manage_my_shopping_lists:{projectKey}"]}]
      body:
        application/json:
          example: !include ../examples/shopping-list-update.example.json
      responses:
        200:
          body:
            application/json:
              example: !include ../examples/shopping-list.example.json
    delete:
      securedBy: [oauth_2_0: {scopes: ["manage_my_shopping_lists:{projectKey}"]}]
      responses:
        200:
          body:
            application/json:
              example: !include ../examples/shopping-list.example.json
