type:
  baseDomain:
    resourceType: Payment
    resourceQueryType: PaymentPagedQueryResponse
    resourceDraft: PaymentDraft
    resourceExample: !include ../examples/payment.example.json
    resourceQueryExample: !include ../examples/payments.example.json
    resourceCreateExample: !include ../examples/payment-create.example.json
    whereExample: externalId = "1234567890"
    sortExample: createdAt asc
description: Payments hold information about the current state of receiving and/or refunding money
get:
  securedBy: [oauth_2_0: {scopes: ["manage_project:{projectKey}", "view_payments:{projectKey}"]}]
post:
  securedBy: [oauth_2_0: {scopes: ["manage_project:{projectKey}", "manage_payments:{projectKey}"]}]
/key={key}:
  type:
    baseResource:
      uriParameterName: key
      resourceType: Payment
      resourceUpdateType: Update
      resourceUpdateExample: !include ../examples/payment-update.example.json
      resourceExample: !include ../examples/payment.example.json
  get:
    securedBy: [oauth_2_0: {scopes: ["manage_project:{projectKey}", "view_payments:{projectKey}"]}]
  post:
    securedBy: [oauth_2_0: {scopes: ["manage_project:{projectKey}", "manage_payments:{projectKey}"]}]
  delete:
    securedBy: [oauth_2_0: {scopes: ["manage_project:{projectKey}", "manage_payments:{projectKey}"]}]
/{ID}:
  type:
    baseResource:
      uriParameterName: ID
      resourceType: Payment
      resourceUpdateType: Update
      resourceUpdateExample: !include ../examples/payment-update.example.json
      resourceExample: !include ../examples/payment.example.json
  get:
    securedBy: [oauth_2_0: {scopes: ["manage_project:{projectKey}", "view_payments:{projectKey}"]}]
  post:
    securedBy: [oauth_2_0: {scopes: ["manage_project:{projectKey}", "manage_payments:{projectKey}"]}]
  delete:
    securedBy: [oauth_2_0: {scopes: ["manage_project:{projectKey}", "manage_payments:{projectKey}"]}]
