type:
  baseDomain:
    resourceType: ProductDiscount
    resourceQueryType: ProductDiscountPagedQueryResponse
    resourceDraft: ProductDiscountDraft
    resourceExample: !include ../examples/product-discount.example.json
    resourceQueryExample: !include ../examples/product-discounts.example.json
    resourceCreateExample: !include ../examples/product-discount-create.example.json
    readScopes: ["manage_project:{projectKey}", "view_products:{projectKey}"]
    writeScopes: ["manage_project:{projectKey}", "manage_products:{projectKey}"]
    whereExample: name(en = "Summer Sale")
    sortExample: createdAt asc
description: Product discounts are used to change certain product prices.
post:
/{ID}:
  type:
    baseResource:
      uriParameterName: ID
      resourceType: ProductDiscount
      resourceUpdateType: Update
      resourceUpdateExample: !include ../examples/product-discount-update.example.json
      resourceExample: !include ../examples/product-discount.example.json
      readScopes: ["manage_project:{projectKey}", "view_products:{projectKey}"]
      writeScopes: ["manage_project:{projectKey}", "manage_products:{projectKey}"]
  get:
  post:
  delete:
