type:
  baseDomain:
    resourceType: Review
    resourceQueryType: ReviewPagedQueryResponse
    resourceDraft: ReviewDraft
    resourceExample: !include ../examples/review.example.json
    resourceQueryExample: !include ../examples/reviews.example.json
    resourceCreateExample: !include ../examples/review-create.example.json
    whereExample: title = "ABC123"
    sortExample: createdAt asc
description: Reviews are used to evaluate products and channels.
get:
  securedBy: [oauth_2_0: {scopes: ["manage_project:{projectKey}", "view_products:{projectKey}"]}]
post:
  securedBy: [oauth_2_0: {scopes: ["manage_project:{projectKey}", "manage_products:{projectKey}"]}]
/key={key}:
  (methodName): withKey
  type:
    baseResource:
      uriParameterName: key
      resourceType: Review
      resourceUpdateType: Update
      resourceUpdateExample: !include ../examples/review-update.example.json
      resourceExample: !include ../examples/review.example.json
  get:
    securedBy: [oauth_2_0: {scopes: ["manage_project:{projectKey}", "view_products:{projectKey}"]}]
  post:
    securedBy: [oauth_2_0: {scopes: ["manage_project:{projectKey}", "manage_products:{projectKey}"]}]
  delete:
    securedBy: [oauth_2_0: {scopes: ["manage_project:{projectKey}", "manage_products:{projectKey}"]}]
/{ID}:
  (methodName): withId
  type:
    baseResource:
      uriParameterName: ID
      resourceType: Review
      resourceUpdateType: Update
      resourceUpdateExample: !include ../examples/review-update.example.json
      resourceExample: !include ../examples/review.example.json
  get:
    securedBy: [oauth_2_0: {scopes: ["manage_project:{projectKey}", "view_products:{projectKey}"]}]
  post:
    securedBy: [oauth_2_0: {scopes: ["manage_project:{projectKey}", "manage_products:{projectKey}"]}]
  delete:
    securedBy: [oauth_2_0: {scopes: ["manage_project:{projectKey}", "manage_products:{projectKey}"]}]
