type:
  baseDomain:
    resourceType: ShippingMethod
    resourceQueryType: ShippingMethodPagedQueryResponse
    resourceDraft: ShippingMethodDraft
    resourceExample: !include ../examples/shipping-method.example.json
    resourceQueryExample: !include ../examples/shipping-methods.example.json
    resourceCreateExample: !include ../examples/shipping-method-create.example.json
    readScopes: ["manage_project:{projectKey}", "view_orders:{projectKey}"]
    writeScopes: ["manage_project:{projectKey}", "manage_orders:{projectKey}"]
    whereExample: name = "DHL"
    sortExample: createdAt asc
description: Shipping Methods define where orders can be shipped and what the costs are.
get:
  queryParameters:
    cartId?:
      type: string
      description: Get ShippingMethods for a Cart
    country?:
      type: string
      description: Get ShippingMethods for a Location
    state?:
      type: string
      description: Get ShippingMethods for a Location
    currency?:
      type: string
      description: Get ShippingMethods for a Location
post:
/{ID}:
  type:
    baseResource:
      uriParameterName: ID
      resourceType: ShippingMethod
      resourceUpdateType: Update
      resourceUpdateExample: !include ../examples/shipping-method-update.example.json
      resourceExample: !include ../examples/shipping-method.example.json
      readScopes: ["manage_project:{projectKey}", "view_orders:{projectKey}"]
      writeScopes: ["manage_project:{projectKey}", "manage_orders:{projectKey}"]
  get:
  post:
  delete:
