type:
  baseDomain:
    resourceType: ShoppingList
    resourceQueryType: ShoppingListPagedQueryResponse
    resourceDraft: ShoppingListDraft
    resourceExample: !include ../examples/shopping-list.example.json
    resourceQueryExample: !include ../examples/shopping-lists.example.json
    resourceCreateExample: !include ../examples/shopping-list-create.example.json
    whereExample: key = "my-shopping-list"
    sortExample: createdAt asc
description: shopping-lists e.g. for wishlist support
get:
  securedBy: [oauth_2_0: {scopes: ["manage_project:{projectKey}", "view_shopping_lists:{projectKey}"]}]
post:
  securedBy: [oauth_2_0: {scopes: ["manage_project:{projectKey}", "manage_shopping_lists:{projectKey}"]}]
/key={key}:
  type:
    baseResource:
      uriParameterName: key
      resourceType: ShoppingList
      resourceUpdateType: Update
      resourceUpdateExample: !include ../examples/shopping-list-update.example.json
      resourceExample: !include ../examples/shopping-list.example.json
  get:
    securedBy: [oauth_2_0: {scopes: ["manage_project:{projectKey}", "view_shopping_lists:{projectKey}"]}]
  post:
    securedBy: [oauth_2_0: {scopes: ["manage_project:{projectKey}", "manage_shopping_lists:{projectKey}"]}]
  delete:
    securedBy: [oauth_2_0: {scopes: ["manage_project:{projectKey}", "manage_shopping_lists:{projectKey}"]}]
/{ID}:
  type:
    baseResource:
      uriParameterName: ID
      resourceType: ShoppingList
      resourceUpdateType: Update
      resourceUpdateExample: !include ../examples/shopping-list-update.example.json
      resourceExample: !include ../examples/shopping-list.example.json
  get:
    securedBy: [oauth_2_0: {scopes: ["manage_project:{projectKey}", "view_shopping_lists:{projectKey}"]}]
  post:
    securedBy: [oauth_2_0: {scopes: ["manage_project:{projectKey}", "manage_shopping_lists:{projectKey}"]}]
  delete:
    securedBy: [oauth_2_0: {scopes: ["manage_project:{projectKey}", "manage_shopping_lists:{projectKey}"]}]
