type:
  baseDomain:
    resourceType: State
    resourceQueryType: StatePagedQueryResponse
    resourceDraft: StateDraft
    resourceExample: !include ../examples/state.example.json
    resourceQueryExample: !include ../examples/states.example.json
    resourceCreateExample: !include ../examples/state-create.example.json
    readScopes: ["manage_project:{projectKey}", "view_orders:{projectKey}"]
    writeScopes: ["manage_project:{projectKey}", "manage_orders:{projectKey}"]
    whereExample: key = "new-order"
    sortExample: createdAt asc
description: |
  The commercetools platform allows you to model states of certain objects, such as orders, line items, products,
  reviews, and payments in order to define finite state machines reflecting the business logic you’d like to implement.
get:
  securedBy: [oauth_2_0: {scopes: ["manage_project:{projectKey}", "view_orders:{projectKey}"]}]
post:
  securedBy: [oauth_2_0: {scopes: ["manage_project:{projectKey}", "manage_orders:{projectKey}"]}]
/{ID}:
  (methodName): withId
  type:
    baseResource:
      uriParameterName: ID
      resourceType: State
      resourceUpdateType: Update
      resourceUpdateExample: !include ../examples/state-update.example.json
      resourceExample: !include ../examples/state.example.json
      readScopes: ["manage_project:{projectKey}", "view_orders:{projectKey}"]
      writeScopes: ["manage_project:{projectKey}", "manage_orders:{projectKey}"]
  get:
    securedBy: [oauth_2_0: {scopes: ["manage_project:{projectKey}", "view_orders:{projectKey}"]}]
  post:
    securedBy: [oauth_2_0: {scopes: ["manage_project:{projectKey}", "manage_orders:{projectKey}"]}]
  delete:
    securedBy: [oauth_2_0: {scopes: ["manage_project:{projectKey}", "manage_orders:{projectKey}"]}]
