type:
  baseDomain:
    resourceType: TaxCategory
    resourceQueryType: TaxCategoryPagedQueryResponse
    resourceDraft: TaxCategoryDraft
    resourceExample: !include ../examples/tax-category.example.json
    resourceQueryExample: !include ../examples/tax-categories.example.json
    resourceCreateExample: !include ../examples/tax-category-create.example.json
    whereExample: name = "MwSt"
    sortExample: name asc
description: Tax Categories define how products are to be taxed in different countries.
get:
  securedBy: [oauth_2_0: {scopes: ["manage_project:{projectKey}", "view_products:{projectKey}"]}]
post:
  securedBy: [oauth_2_0: {scopes: ["manage_project:{projectKey}", "manage_products:{projectKey}"]}]
/{ID}:
  type:
    baseResource:
      uriParameterName: ID
      resourceType: TaxCategory
      resourceUpdateType: Update
      resourceUpdateExample: !include ../examples/tax-category-update.example.json
      resourceExample: !include ../examples/tax-category.example.json
  get:
    securedBy: [oauth_2_0: {scopes: ["manage_project:{projectKey}", "view_products:{projectKey}"]}]
  post:
    securedBy: [oauth_2_0: {scopes: ["manage_project:{projectKey}", "manage_products:{projectKey}"]}]
  delete:
    securedBy: [oauth_2_0: {scopes: ["manage_project:{projectKey}", "manage_products:{projectKey}"]}]
