type:
  baseDomain:
    resourceType: Type
    resourceQueryType: TypePagedQueryResponse
    resourceDraft: TypeDraft
    resourceExample: !include ../examples/type.example.json
    resourceQueryExample: !include ../examples/types.example.json
    resourceCreateExample: !include ../examples/type-create.example.json
    readScopes: ["manage_project:{projectKey}", "view_types:{projectKey}"]
    writeScopes: ["manage_project:{projectKey}", "manage_types:{projectKey}"]
    whereExample: key = "my-type"
    sortExample: createdAt asc
description: Types define custom fields that are used to enhance resources as you need.
post:
/key={key}:
  type:
    baseResource:
      uriParameterName: key
      resourceType: Type
      resourceUpdateType: Update
      resourceUpdateExample: !include ../examples/type-update.example.json
      resourceExample: !include ../examples/type.example.json
      readScopes: ["manage_project:{projectKey}", "view_types:{projectKey}"]
      writeScopes: ["manage_project:{projectKey}", "manage_types:{projectKey}"]
  get:
  post:
  delete:
/{ID}:
  type:
    baseResource:
      uriParameterName: ID
      resourceType: Type
      resourceUpdateType: Update
      resourceUpdateExample: !include ../examples/type-update.example.json
      resourceExample: !include ../examples/type.example.json
      readScopes: ["manage_project:{projectKey}", "view_types:{projectKey}"]
      writeScopes: ["manage_project:{projectKey}", "manage_types:{projectKey}"]
  get:
  post:
  delete:
