#%RAML 1.0 DataType
(package): Zone
type: ZoneUpdateAction
displayName: ZoneAddLocationAction
discriminatorValue: addLocation
example: !include ../../../examples/Zone/ZoneAddLocationAction.json
properties:
  location:
    type: Location
    description: Location to be added to the Zone.
