#%RAML 1.0 DataType
(package): Type
(docs-uri): https://docs.commercetools.com/http-api-projects-types.html#change-key


type: TypeUpdateAction
displayName: TypeChangeKeyAction
discriminatorValue: changeKey
properties:
    key:
        type: string
