#%RAML 1.0 DataType
(package): Type
(docs-uri): https://docs.commercetools.com/http-api-projects-types.html#change-the-order-of-localizedenumvalues
type: TypeUpdateAction
displayName: TypeChangeLocalizedEnumValueOrderAction
discriminatorValue: changeLocalizedEnumValueOrder
(postman-example): !include ../../../examples/Type/TypeChangeLocalizedEnumValueOrderAction.json
properties:
  fieldName:
    type: string
  keys:
    type: string[]
