#%RAML 1.0 DataType
(package): Type
(docs-uri): https://docs.commercetools.com/http-api-projects-types.html#change-the-order-of-fielddefinitions
type: TypeUpdateAction
displayName: TypeChangeFieldDefinitionOrderAction
discriminatorValue: changeFieldDefinitionOrder
(postman-example): !include ../../../examples/Type/TypeChangeFieldDefinitionOrderAction.json
properties:
  fieldNames:
    type: string[]
