#%RAML 1.0 DataType
(package): Customer
(docs-uri): https://docs.commercetools.com/http-api-projects-customers.html#customer

displayName: Customer
(updateType): CustomerUpdate

type: Resource
properties:
  customerNumber?:
    (hasSimpleUpdateAction): setCustomerNumber
    type: string
  email:
    (hasSimpleUpdateAction): changeEmail
    type: string
  password:
    type: string
  firstName?:
    (hasSimpleUpdateAction): setFirstName
    type: string
  lastName?:
    (hasSimpleUpdateAction): setLastName
    type: string
  middleName?:
    (hasSimpleUpdateAction): setMiddleName
    type: string
  title?:
    (hasSimpleUpdateAction): setTitle
    type: string
  dateOfBirth?:
    (hasSimpleUpdateAction): setDateOfBirth
    type: date-only
  companyName?:
    (hasSimpleUpdateAction): setCompanyName
    type: string
  vatId?:
    (hasSimpleUpdateAction): setVatId
    type: string
  addresses:
    type: Address[]
    (hasUpdateActions):
      - action: addAddress
        fields:
          address: Address
      - action: changeAddress
        fields:
          addressId: string
          address: Address
      - action: removeAddress
        fields:
          addressId: string
  defaultShippingAddressId?:
    type: string
    (hasUpdateAction):
      action: setDefaultShippingAddress
      fields:
        addressId?: string
  shippingAddressIds?:
    type: string[]
    (hasUpdateActions):
      - action: addShippingAddressId
        fields:
          addressId: string
      - action: removeShippingAddressId
        fields:
          addressId: string
  defaultBillingAddressId?:
    type: string
    (hasUpdateAction):
      action: setDefaultBillingAddress
      fields:
        addressId?: string
  billingAddressIds?:
    type: string[]
    (hasUpdateActions):
      - action: addBillingAddressId
        fields:
          addressId: string
      - action: removeBillingAddressId
        fields:
          addressId: string
  isEmailVerified:
    type: boolean
  externalId?:
    (hasSimpleUpdateAction): setExternalId
    type: string
  customerGroup?:
    (hasUpdateAction):
      action: setCustomerGroup
      docsAnchor: set-customergroup
    type: CustomerGroupReference
  custom?:
    type: CustomFields
    (hasUpdateActions):
      - action: setCustomType
        fields:
          type?: TypeReference
          fields?: FieldContainer
      - action: setCustomField
        docsAnchor: set-customfield
        fields:
          name: string
          value?: any
  locale?:
    (hasSimpleUpdateAction): setLocale
    type: string
  salutation?:
    (hasSimpleUpdateAction): setSalutation
    type: string
  key?:
    (hasSimpleUpdateAction): setKey
    type: string
