#%RAML 1.0 DataType
(package): Customer
(docs-uri): https://docs.commercetools.com/http-api-projects-customers.html#customer

displayName: Customer
(updateType): CustomerUpdate

type: Resource
properties:
    customerNumber?:
        (hasUpdateAction): setCustomerNumber
        type: string
    email:
        (hasUpdateAction): changeEmail
        type: string
    password:
        type: string
    firstName?:
        (hasUpdateAction): setFirstName
        type: string
    lastName?:
        (hasUpdateAction): setLastName
        type: string
    middleName?:
        (hasUpdateAction): setMiddleName
        type: string
    title?:
        (hasUpdateAction): setTitle
        type: string
    dateOfBirth?:
        (hasUpdateAction): setDateOfBirth
        type: date-only
    companyName?:
        (hasUpdateAction): setCompanyName
        type: string
    vatId?:
        (hasUpdateAction): setVatId
        type: string
    addresses:
        type: Address[]
    defaultShippingAddressId?:
        type: string
    shippingAddressIds?:
        type: string[]
    defaultBillingAddressId?:
        type: string
    billingAddressIds?:
        type: string[]
    isEmailVerified:
        type: boolean
    externalId?:
        (hasUpdateAction): setExternalId
        type: string
    customerGroup?:
        (hasUpdateAction): setCustomerGroup
        (docsActionAnchor): set-customergroup
        type: CustomerGroupReference
    custom?:
        type: CustomFields
    locale?:
        (hasUpdateAction): setLocale
        type: string
    salutation?:
        (hasUpdateAction): setSalutation
        type: string
    key?:
        (hasUpdateAction): setKey
        type: string
