#%RAML 1.0 DataType

displayName: CustomerResetPassword

type: object
properties:
    tokenValue:
        type: string
    newPassword:
        type: string
    version?:
       type: number
       format: int64
