#%RAML 1.0 DataType
(package): Customer

displayName: CustomerDraft

type: object
properties:
    customerNumber?:
        type: string
    email:
        type: string
    password:
        type: string
    firstName?:
        type: string
    lastName?:
        type: string
    middleName?:
        type: string
    title?:
        type: string
    anonymousCartId?:
        type: string
    anonymousId?:
        type: string
    dateOfBirth?:
        type: date-only
    companyName?:
        type: string
    vatId?:
        type: string
    addresses?:
        type: Address[]
    defaultShippingAddress?:
        type: number
        format: int64
    shippingAddresses?:
        type: integer[]
    defaultBillingAddress?:
        type: number
        format: int64
    billingAddresses?:
        type: integer[]
    isEmailVerified?:
        type: boolean
    externalId?:
        type: string
    customerGroup?: CustomerGroupReference
    custom?:
        type: CustomFieldsDraft
    locale?:
        type: string
    salutation?:
        type: string
