#%RAML 1.0 DataType
(package): Review
(docs-uri): https://docs.commercetools.com/http-api-projects-reviews.html#transition-state
type: ReviewUpdateAction
displayName: ReviewTransitionStateAction
discriminatorValue: transitionState
description: |
  Transition to a new State. This update action produces the [Review State Transition](ctp:api:type:ReviewStateTransitionMessage) Message.
example: !include ../../../examples/Review/ReviewTransitionStateAction.json
properties:
  state:
    type: StateResourceIdentifier
    description: |
      Value to set. If there is no State yet, the new State must be an initial State. If the existing State has `transitions` set, there must be a direct transition to the new State. If `transitions` is not set, no validation is performed. If the new State does not have the [role](ctp:api:type:StateRoleEnum) `ReviewIncludedInStatistics`, the Review is not taken into account in the ratings statistics of the target.
  force?:
    type: boolean
    description: |
      Switch validations on or off.
    default: false
