#%RAML 1.0 DataType
(package): Review
type: ReviewUpdateAction
displayName: ReviewSetTargetAction
discriminatorValue: setTarget
example: !include ../../../examples/Review/ReviewSetTargetAction.json
properties:
  target:
    type: ProductResourceIdentifier | ChannelResourceIdentifier
    description: |
      Value to set, specified as [ProductResourceIdentifier](ctp:api:type:ProductResourceIdentifier) or [ChannelResourceIdentifier](ctp:api:type:ChannelResourceIdentifier), respectively. If empty, any existing value will be removed.
