#%RAML 1.0 DataType
(package): Review
(docs-uri): https://docs.commercetools.com/http-api-projects-reviews.html#set-locale
type: ReviewUpdateAction
displayName: ReviewSetLocaleAction
discriminatorValue: setLocale
(postman-example): !include ../../../examples/Review/ReviewSetLocaleAction.json
properties:
  locale?:
    type: string
    description: If `locale` is absent or `null`, this field will be removed if it exists.
