#%RAML 1.0 DataType
(package): ProductDiscount
(docs-uri): https://docs.commercetools.com/http-api-projects-productDiscounts.html#set-valid-from


type: ProductDiscountUpdateAction
displayName: ProductDiscountSetValidFromAction
discriminatorValue: setValidFrom
(postman-example): |
  {
    "action": "setValidFrom",
    "validFrom": "2017-01-11T15:00:00.000Z"
  }
properties:
    validFrom?:
        type: datetime
