#%RAML 1.0 DataType
(package): ProductDiscount


type: ProductDiscountUpdateAction
displayName: ProductDiscountSetDescriptionAction
discriminatorValue: setDescription
properties:
    description?:
        type: LocalizedString
