#%RAML 1.0 DataType
(package): ProductDiscount

type: object
displayName: ProductDiscountDraft
properties:
    name:
        type: LocalizedString
    description?:
        type: LocalizedString
    value: ProductDiscountValue
    predicate:
        type: string
    sortOrder:
        type: string
    isActive:
        type: boolean
