#%RAML 1.0 DataType

type: Resource
displayName: ProductDiscount
(generate-collection): true
properties:
    name:
        type: LocalizedString
    description?:
        type: LocalizedString
    value: ProductDiscountValue
    predicate:
        type: string
    sortOrder:
        type: string
    isActive:
        type: boolean
    references: Reference[]
