#%RAML 1.0 DataType
(package): ProductDiscount


type: ProductDiscountUpdateAction
displayName: ProductDiscountChangeNameAction
discriminatorValue: changeName
properties:
    name:
        type: LocalizedString
