#%RAML 1.0 DataType
(package): ProductDiscount


type: ProductDiscountUpdateAction
displayName: ProductDiscountSortOrderAction
discriminatorValue: sortOrder
properties:
    sortOrder:
        type: string
