#%RAML 1.0 DataType
(package): OrderEdit
(docs-uri): https://docs.commercetools.com/api/projects/order-edits#set-itemshipping-address-custom-type
type: OrderEditUpdateAction
displayName: OrderEditSetItemShippingAddressCustomTypeAction
discriminatorValue: setItemShippingAddressCustomType
(postman-example): !include ../../../examples/OrderEdit/OrderEditSetItemShippingAddressCustomTypeAction.json
properties:
  addressKey:
    type: string
  type?:
    type: TypeResourceIdentifier
  fields?:
    type: FieldContainer
