#%RAML 1.0 DataType
(package): OrderEdit
(docs-uri): https://docs.commercetools.com/api/projects/order-edits#set-shipping-address-custom-type
type: OrderEditUpdateAction
displayName: OrderEditSetShippingAddressCustomTypeAction
discriminatorValue: setShippingAddressCustomType
(postman-example): !include ../../../examples/OrderEdit/OrderEditSetShippingAddressCustomTypeAction.json
properties:
  type?:
    type: TypeResourceIdentifier
  fields?:
    type: FieldContainer
