#%RAML 1.0 DataType
(package): OrderEdit
example: !include ../../../examples/OrderEdit/OrderEditSetCustomTypeAction.json
type: OrderEditUpdateAction
displayName: OrderEditSetCustomTypeAction
discriminatorValue: setCustomType
properties:
  type?:
    type: TypeResourceIdentifier
    description: |
      Defines the [Type](ctp:api:type:Type) that extends the Order Edit with [Custom Fields](ctp:api:type:CustomFields).
      If absent, any existing Type and Custom Fields are removed from the Order Edit.
  fields?:
    type: FieldContainer
    description: |
      Object containing the [Custom Fields](ctp:api:type:CustomFields) fields for the Order Edit.

      Required if at least one Custom Field is defined as required in the `fieldDefinitions` of the referenced [Type](ctp:api:type:Type).
