#%RAML 1.0 DataType
(package): OrderEdit
(docs-uri): https://docs.commercetools.com/api/projects/order-edits#addstagedaction
example: !include ../../../examples/OrderEdit/OrderEditAddStagedActionAction.json
type: OrderEditUpdateAction
displayName: OrderEditAddStagedActionAction
discriminatorValue: addStagedAction
description: |
  If the [edit was applied](ctp:api:endpoint:/{projectKey}/orders/edits/{id}/apply:POST), this cannot be updated.
properties:
  stagedAction:
    type: StagedOrderUpdateAction
    description: |
      Order update action to append to the `stagedActions` array.
