#%RAML 1.0 DataType
(package): OrderEdit
(docs-uri): https://docs.commercetools.com/api/projects/order-edits#setcustom-type
example: !include ../../../examples/OrderEdit/OrderEditSetCustomTypeAction.json
type: OrderEditUpdateAction
displayName: OrderEditSetCustomTypeAction
discriminatorValue: setCustomType
properties:
  type?:
    type: TypeResourceIdentifier
    description: |
      Defines the [Type](ctp:api:type:Type) that extends the Order Edit with [Custom Fields](/../api/projects/custom-fields).
      If absent, any existing Type and Custom Fields are removed from the Order Edit.
  fields?:
    type: FieldContainer
    description: |
      Sets the [Custom Fields](/../api/projects/custom-fields) fields for the Order Edit.
