#%RAML 1.0 DataType
(package): OrderEdit
(docs-uri): https://docs.commercetools.com/http-api-projects-order-edits.html#set-customlineitemshippingdetails
type: StagedOrderUpdateAction
displayName: StagedOrderSetCustomLineItemShippingDetailsAction
discriminatorValue: setCustomLineItemShippingDetails
(postman-example): !include ../../../examples/OrderEdit/StagedOrderSetCustomLineItemShippingDetailsAction.json
properties:
  customLineItemId:
    type: string
  shippingDetails?:
    type: ItemShippingDetailsDraft
