#%RAML 1.0 DataType
(package): OrderEdit
(docs-uri): https://docs.commercetools.com/http-api-projects-order-edits.html#set-parcel-items
type: StagedOrderUpdateAction
displayName: StagedOrderSetParcelItemsAction
discriminatorValue: setParcelItems
(postman-example): !include ../../../examples/OrderEdit/StagedOrderSetParcelItemsAction.json
properties:
  parcelId:
    type: string
  items:
    type: DeliveryItem[]
