#%RAML 1.0 DataType
(package): OrderEdit
(docs-uri): https://docs.commercetools.com/http-api-projects-order-edits.html#import-state-for-customlineitems
type: StagedOrderUpdateAction
displayName: StagedOrderImportCustomLineItemStateAction
discriminatorValue: importCustomLineItemState
(postman-example): !include ../../../examples/OrderEdit/StagedOrderImportCustomLineItemStateAction.json
properties:
  customLineItemId:
    type: string
  state:
    type: ItemState[]
