#%RAML 1.0 DataType
(package): OrderEdit
example: !include ../../../examples/OrderEdit/StagedOrderAddItemShippingAddressAction.json
type: StagedOrderUpdateAction
displayName: StagedOrderAddItemShippingAddressAction
discriminatorValue: addItemShippingAddress
description: |
  Adds an address to the `itemShippingAddresses` of an Order. Use this action when shipping is defined per item. For example, when shipping items to multiple addresses or when using different Shipping Methods, even if all items share the same address.
properties:
  address:
    type: BaseAddress
    description: |
      Address to append to `itemShippingAddresses`.
      The new Address must have a `key` that is unique across this Order.
