#%RAML 1.0 DataType
(package): OrderEdit
(docs-uri): https://docs.commercetools.com/api/projects/order-edits#set-delivery-customfield
type: StagedOrderUpdateAction
displayName: StagedOrderSetDeliveryCustomFieldAction
discriminatorValue: setDeliveryCustomField
example: !include ../../../examples/OrderEdit/StagedOrderSetDeliveryCustomFieldAction.json
properties:
  name:
    type: string
  value?:
    type: any
