#%RAML 1.0 DataType
(package): OrderEdit
(docs-uri): https://docs.commercetools.com/api/projects/order-edits#remove-customlineitem
example: !include ../../../examples/OrderEdit/StagedOrderRemoveCustomLineItemAction.json
type: StagedOrderUpdateAction
displayName: StagedOrderRemoveCustomLineItemAction
discriminatorValue: removeCustomLineItem
description: |
  This update action does not support specifying a quantity, unlike the [Remove LineItem](ctp:api:type:StagedOrderRemoveLineItemAction) update action.

  If `shippingDetails` must be partially removed, use the [Change CustomLineItem Quantity](ctp:api:type:StagedOrderChangeCustomLineItemQuantityAction) update action.
properties:
  customLineItemId:
    type: string
    description: |
      `id` of the Custom Line Item to remove.
