#%RAML 1.0 DataType
(package): OrderEdit
(docs-uri): https://docs.commercetools.com/api/projects/order-edits#set-locale
example: !include ../../../examples/OrderEdit/StagedOrderSetLocaleAction.json
type: StagedOrderUpdateAction
displayName: StagedOrderSetLocaleAction
discriminatorValue: setLocale
properties:
  locale?:
    type: Locale
    description: |
      Value to set.
      Must be one of the [Project](ctp:api:type:Project)'s languages.
      If empty, any existing value is removed.
