#%RAML 1.0 DataType
(package): OrderEdit
example: !include ../../../examples/OrderEdit/StagedOrderSetShippingMethodTaxRateAction.json
type: StagedOrderUpdateAction
displayName: StagedOrderSetShippingMethodTaxRateAction
discriminatorValue: setShippingMethodTaxRate
description: |
  A Shipping Method Tax Rate can be set if the Cart has the `External` [TaxMode](ctp:api:type:TaxMode).
properties:
  shippingKey?:
    type: string
    description: |
      `key` of the [ShippingMethod](ctp:api:type:ShippingMethod) to update. This is required for Orders with `Multiple` [ShippingMode](ctp:api:type:ShippingMode).
  externalTaxRate?:
    type: ExternalTaxRateDraft
    description: |
      Value to set.
      If empty, any existing value is removed.
