#%RAML 1.0 DataType
(package): OrderEdit
(docs-uri): https://docs.commercetools.com/http-api-projects-order-edits.html#set-customlineitem-customfield
type: StagedOrderUpdateAction
displayName: StagedOrderSetCustomLineItemCustomFieldAction
discriminatorValue: setCustomLineItemCustomField
(postman-example): !include ../../../examples/OrderEdit/StagedOrderSetCustomLineItemCustomFieldAction.json
properties:
  customLineItemId:
    type: string
  name:
    type: string
  value?:
    type: any
