#%RAML 1.0 DataType
(package): OrderEdit
(docs-uri): https://docs.commercetools.com/api/projects/order-edits#set-returninfo
example: !include ../../../examples/OrderEdit/StagedOrderSetReturnInfoAction.json
type: StagedOrderUpdateAction
displayName: StagedOrderSetReturnInfoAction
discriminatorValue: setReturnInfo
description: |
  Produces the [Return Info Set](ctp:api:type:ReturnInfoSetMessage) Message.
properties:
  items?:
    type: ReturnInfoDraft[]
    description: |
      Value to set.
      If empty, any existing value will be removed.
