#%RAML 1.0 DataType
(package): OrderEdit
(docs-uri): https://docs.commercetools.com/http-api-projects-order-edits.html#remove-lineitem
type: StagedOrderUpdateAction
displayName: StagedOrderRemoveLineItemAction
discriminatorValue: removeLineItem
(postman-example): !include ../../../examples/OrderEdit/StagedOrderRemoveLineItemAction.json
properties:
  lineItemId:
    type: string
  quantity?:
    type: number
  externalPrice?:
    type: Money
  externalTotalPrice?:
    type: ExternalLineItemTotalPrice
  shippingDetailsToRemove?:
    type: ItemShippingDetailsDraft
