#%RAML 1.0 DataType
(package): OrderEdit
(docs-uri): https://docs.commercetools.com/api/projects/order-edits#remove-itemshippingaddress
example: !include ../../../examples/OrderEdit/StagedOrderRemoveItemShippingAddressAction.json
type: StagedOrderUpdateAction
displayName: StagedOrderRemoveItemShippingAddressAction
discriminatorValue: removeItemShippingAddress
description: |
  An address can only be removed if it is not referenced in any [ItemShippingTarget](ctp:api:type:ItemShippingTarget) of the Cart.
properties:
  addressKey:
    type: string
    description: |
      `key` of the Address to remove from `itemShippingAddresses`.
