#%RAML 1.0 DataType
(package): OrderEdit
(docs-uri): https://docs.commercetools.com/api/projects/order-edits#set-parcel-customfield
type: StagedOrderUpdateAction
displayName: StagedOrderSetParcelCustomFieldAction
discriminatorValue: setParcelCustomField
example: !include ../../../examples/OrderEdit/StagedOrderSetParcelCustomFieldAction.json
properties:
  parcelId?:
    type: string
    description: Either `parcelId` or `parcelKey` is required for this update action.
  parcelKey?:
    type: string
    description: Either `parcelId` or `parcelKey` is required for this update action.
  name:
    type: string
    description: |
      Name of the [Custom Field](/../api/projects/custom-fields).
  value?:
    type: CustomFieldValue
    description: |
      If `value` is absent or `null`, this field will be removed if it exists.
      Removing a field that does not exist returns an [InvalidOperation](ctp:api:type:InvalidOperationError) error.
      If `value` is provided, it is set for the field defined by `name`.
