#%RAML 1.0 DataType
(package): OrderEdit
(docs-uri): https://docs.commercetools.com/http-api-projects-order-edits#set-lineitem-distributionchannel
type: StagedOrderUpdateAction
displayName: StagedOrderSetLineItemDistributionChannelAction
discriminatorValue: setLineItemDistributionChannel
(postman-example): !include ../../../examples/OrderEdit/StagedOrderSetLineItemDistributionChannelAction.json
properties:
  lineItemId:
    type: string
  distributionChannel?:
    type: ChannelResourceIdentifier
