#%RAML 1.0 DataType
(package): OrderEdit
(docs-uri): https://docs.commercetools.com/api/projects/order-edits#change-customlineitem-money
example: !include ../../../examples/OrderEdit/StagedOrderChangeCustomLineItemMoneyAction.json
type: StagedOrderUpdateAction
displayName: StagedOrderChangeCustomLineItemMoneyAction
discriminatorValue: changeCustomLineItemMoney
properties:
  customLineItemId:
    type: string
    description: |
      `id` of the [CustomLineItem](ctp:api:type:CustomLineItem) to update.
  money:
    type: Money
    description: |
      Value to set.
      Must not be empty.
      Can be a negative amount.
