#%RAML 1.0 DataType
(package): OrderEdit
(docs-uri): https://docs.commercetools.com/http-api-projects-order-edits.html#set-customer-group
type: StagedOrderUpdateAction
displayName: StagedOrderSetCustomerGroupAction
discriminatorValue: setCustomerGroup
(postman-example): !include ../../../examples/OrderEdit/StagedOrderSetCustomerGroupAction.json
properties:
  customerGroup?:
    type: CustomerGroupResourceIdentifier
