#%RAML 1.0 DataType
(package): OrderEdit
(docs-uri): https://docs.commercetools.com/http-api-projects-order-edits.html#add-itemshippingaddress
type: StagedOrderUpdateAction
displayName: StagedOrderAddItemShippingAddressAction
discriminatorValue: addItemShippingAddress
(postman-example): !include ../../../examples/OrderEdit/StagedOrderAddItemShippingAddressAction.json
properties:
  address:
    type: BaseAddress
