#%RAML 1.0 DataType
(package): OrderEdit
(docs-uri): https://docs.commercetools.com/api/projects/order-edits#set-parcel-tracking-data
example: !include ../../../examples/OrderEdit/StagedOrderSetParcelTrackingDataAction.json
type: StagedOrderUpdateAction
displayName: StagedOrderSetParcelTrackingDataAction
discriminatorValue: setParcelTrackingData
description: |
  Produces the [ParcelTrackingDataUpdated](ctp:api:type:ParcelTrackingDataUpdatedMessage) Message.
properties:
  parcelId?:
    type: string
    description: |
      `id` of an existing [Parcel](ctp:api:type:Parcel).

      Either `parcelId` or `parcelKey` must be provided.
  parcelKey?:
    type: string
    description: |
      `key` of an existing [Parcel](ctp:api:type:Parcel).

      Either `parcelId` or `parcelKey` must be provided.
  trackingData?:
    type: TrackingData
    description: |
      Value to set.
      If empty, any existing value will be removed.
