#%RAML 1.0 DataType
(package): OrderEdit
example: !include ../../../examples/OrderEdit/StagedOrderSetOrderTotalTaxAction.json
type: StagedOrderUpdateAction
displayName: StagedOrderSetOrderTotalTaxAction
discriminatorValue: setOrderTotalTax
description: |
  Updates the total tax amount of the Order if it has the `ExternalAmount` [TaxMode](ctp:api:type:TaxMode).
properties:
  externalTotalGross:
    type: Money
    description: |
      Total gross amount of the Order (totalNet + taxes).
  externalTaxPortions?:
    type: TaxPortionDraft[]
    description: |
      Value to set.
