#%RAML 1.0 DataType
(package): OrderEdit
(docs-uri): https://docs.commercetools.com/http-api-projects-order-edits.html#set-billing-address
type: StagedOrderUpdateAction
displayName: StagedOrderSetBillingAddressAction
discriminatorValue: setBillingAddress
(postman-example): !include ../../../examples/OrderEdit/StagedOrderSetBillingAddressAction.json
properties:
  address?:
    type: BaseAddress
