#%RAML 1.0 DataType
(package): OrderEdit
(docs-uri): https://docs.commercetools.com/api/projects/order-edits#set-parcel-custom-type
type: StagedOrderUpdateAction
displayName: StagedOrderSetParcelCustomTypeAction
discriminatorValue: setParcelCustomType
example: !include ../../../examples/OrderEdit/StagedOrderSetParcelCustomTypeAction.json
properties:
  parcelId?:
    type: string
    description: Either `parcelId` or `parcelKey` is required for this update action.
  parcelKey?:
    type: string
    description: Either `parcelId` or `parcelKey` is required for this update action.
  type?:
    type: TypeResourceIdentifier
    description: |
      Defines the [Type](ctp:api:type:Type) that extends the Parcel with [Custom Fields](/../api/projects/custom-fields).
      If absent, any existing Type and Custom Fields are removed from the Parcel.
  fields?:
    type: FieldContainer
    description: |
      Sets the [Custom Fields](/../api/projects/custom-fields) fields for the Parcel.
