#%RAML 1.0 DataType
(package): OrderEdit
(docs-uri): https://docs.commercetools.com/http-api-projects-order-edits.html#set-lineitem-taxamount
type: StagedOrderUpdateAction
displayName: StagedOrderSetLineItemTaxAmountAction
discriminatorValue: setLineItemTaxAmount
(postman-example): !include ../../../examples/OrderEdit/StagedOrderSetLineItemTaxAmountAction.json
properties:
  lineItemId:
    type: string
  externalTaxAmount?:
    type: ExternalTaxAmountDraft
