#%RAML 1.0 DataType
(package): OrderEdit
(docs-uri): https://docs.commercetools.com/api/projects/order-edits#remove-payment
example: !include ../../../examples/OrderEdit/StagedOrderRemovePaymentAction.json
type: StagedOrderUpdateAction
displayName: StagedOrderRemovePaymentAction
discriminatorValue: removePayment
properties:
  payment:
    type: PaymentResourceIdentifier
    description: |
      Payment to remove from the [PaymentInfo](ctp:api:type:PaymentInfo).
