#%RAML 1.0 DataType
(package): OrderEdit
(docs-uri): https://docs.commercetools.com/http-api-projects-order-edits.html#update-itemshippingaddress
type: StagedOrderUpdateAction
displayName: StagedOrderUpdateItemShippingAddressAction
discriminatorValue: updateItemShippingAddress
(postman-example): !include ../../../examples/OrderEdit/StagedOrderUpdateItemShippingAddressAction.json
properties:
  address:
    type: BaseAddress
