#%RAML 1.0 DataType
(package): OrderEdit
example: !include ../../../examples/OrderEdit/StagedOrderSetDirectDiscountsAction.json
type: StagedOrderUpdateAction
displayName: StagedOrderSetDirectDiscountsAction
discriminatorValue: setDirectDiscounts
description: |
  Adds a [DirectDiscount](ctp:api:type:DirectDiscount), but only if no [DiscountCode](ctp:api:type:DiscountCode) has been added to the Order.
  Either a Discount Code or a Direct Discount can exist on a Order at the same time.
properties:
  discounts:
    type: DirectDiscountDraft[]
    description: |
      - If set, all existing Direct Discounts are replaced.
        The discounts apply in the order they are added to the list.
      - If empty, all existing Direct Discounts are removed and all affected prices on the Order are recalculated.
