#%RAML 1.0 DataType
(package): Customer
(docs-uri): https://docs.commercetools.com/http-api-projects-customers.html#set-custom-type
type: CustomerUpdateAction
displayName: CustomerSetCustomTypeAction
discriminatorValue: setCustomType
(postman-example): !include ../../../examples/Customer/CustomerSetCustomTypeAction.json
properties:
  type?:
    type: TypeResourceIdentifier
    description: If absent, the custom type and any existing custom fields are removed.
  fields?:
    type: FieldContainer
    description: |-
      A valid JSON object, based on the FieldDefinitions of the Type.
      Sets the custom fields to this value.
