#%RAML 1.0 DataType
(package): Customer
(docs-uri): https://docs.commercetools.com/http-api-projects-customers.html#add-billing-address-id
type: CustomerUpdateAction
displayName: CustomerAddBillingAddressIdAction
discriminatorValue: addBillingAddressId
(postman-example): !include ../../../examples/Customer/CustomerAddBillingAddressIdAction.json
properties:
  addressId?:
    type: string
    description: ''
  addressKey?:
    type: string
    description: ''
