#%RAML 1.0 DataType
(package): Subscription
type: SubscriptionUpdateAction
displayName: SubscriptionSetKeyAction
discriminatorValue: setKey
example: !include ../../../examples/Subscription/SubscriptionSetKeyAction.json
properties:
  key?:
    type: string
    description: |
      Value to set. If empty, any existing value will be removed.
    pattern: ^[A-Za-z0-9_-]+$
    minLength: 2
    maxLength: 256
