#%RAML 1.0 DataType
(package): OrderEdit
(docs-uri): https://docs.commercetools.com/http-api-projects-order-edits.html#ordereditpreviewfailure
type: OrderEditResult
displayName: OrderEditPreviewFailure
discriminatorValue: PreviewFailure
properties:
  errors:
    type: ErrorObject[]
