#%RAML 1.0 Library
usage: Generator annotation types.

annotationTypes:
  asMap:
    type: object
    properties:
      key: string
      value: string
  package:
    description: |
      Allows to specify a target package for a generator for a RAML library.
      This package name should be a language indepedent logical name (e.g. "products"), which a generator then uses to
      generate a language specific package name (e.g. "com.myapi.jvm.products") from its configuration.
    allowedTargets:
      - Library
    type: string
  enumDescriptions:
    description: |
      Allows to describe the values of an enum type.
    type: object
    properties:
      //:
        description: |
          Adds a description for the enum value given by the key.
        type: string
  updateType:
    type: string
    allowedTargets: TypeDeclaration
  identifier:
    type: boolean
    allowedTargets: TypeDeclaration
  abstract:
    type: boolean
    allowedTargets: TypeDeclaration
  methodName:
    type: string
