#%RAML 1.0 Library
usage: Category recommendations types
(annotations.package): category-recommendations

uses:
  common: ./common.raml
  annotations: ./annotations.raml

types:
  ProjectCategoryRecommendation:
    properties:
      category:
        description: A category that is recommended for a product.
        type: common.CategoryReference
      confidence:
        description: Probability score for the category recommendation.
        type: number
        format: float
      path:
        type: string
        description:
          Breadcrumb path to the recommended category. This only picks up one
          language, not all available languages for the category. English is
          prioritized, but if English data is not available, an arbitrary
          language is selected. Do not use this to identify a category,use the
          category ID from the category reference instead.
  ProjectCategoryRecommendationMeta:
    properties:
      productName:
        type: string
        required: false
        description: The product name that was used to generate recommendations.
      productImageUrl:
        type: string
        required: false
        description: The product image that was used to generate recommendations.
      generalCategoryNames:
        type: string[]
        description:
          Top 5 general categories that were used internally to generate the
          project-specific categories. These category names are not related to
          the categories defined in the project, but they provide additional
          information to understand the project-specific categories in the
          results section.
  ProjectCategoryRecommendationPagedQueryResponse:
    properties:
      count:
        type: number
        format: int64
      total:
        type: number
        format: int64
      offset:
        type: number
        format: int64
      results:
        type: ProjectCategoryRecommendation[]
      meta:
        type: ProjectCategoryRecommendationMeta
