#%RAML 1.0 DataType
(package): ProductType
(docs-uri): https://docs.commercetools.com/http-api-projects-productTypes.html#add-attributedefinition
type: ProductTypeUpdateAction
displayName: ProductTypeAddAttributeDefinitionAction
discriminatorValue: addAttributeDefinition
properties:
  attribute:
    type: AttributeDefinitionDraft
    description: ''
