#%RAML 1.0 DataType
(package): ProductType
(docs-uri): https://docs.commercetools.com/http-api-projects-productTypes.html#add-plainenumvalue-to-attributedefinition
type: ProductTypeUpdateAction
displayName: ProductTypeAddPlainEnumValueAction
discriminatorValue: addPlainEnumValue
properties:
  attributeName:
    type: string
  value:
    type: AttributePlainEnumValue
