#%RAML 1.0 DataType
(package): ProductType
(docs-uri): https://docs.commercetools.com/http-api-projects-productTypes.html#set-attributedefinition-inputtip
type: ProductTypeUpdateAction
displayName: ProductTypeSetInputTipAction
discriminatorValue: setInputTip
properties:
  attributeName:
    type: string
  inputTip?:
    type: LocalizedString
