#%RAML 1.0 DataType
(annotations.package): Connector
type: object
displayName: ConnectorUpdate
properties:
  version:
    type: number
    format: int64
    description: |
      Expected version of the Connector on which the changes apply.
  actions:
    type: array
    items: ConnectorUpdateAction
    description: |
      Update actions to be performed on the Connector.
