#%RAML 1.0 DataType
(annotations.package): Connector
displayName: ConnectorDraft
properties:
  key?:
    type: string
    description: User-defined unique identifier of the Connector.
    pattern: ^[A-Za-z0-9_-]+$
    minLength: 2
    maxLength: 256
  name:
    type: string
    description: Name of the Connector.
  description?:
    type: string
    description: Description of the Connector.
  integrationTypes?:
    type: common.IntegrationType[]
    description: Integration types of the Connector. Can be used to filter search and query results.
  creator:
    type: common.Creator
    description: Owner of the Connector.
  repository:
    type: common.Repository
    description: GitHub repository details of the Connector.
  supportedRegions?:
    type: common.Region[]
    description: If provided, Connectors can only be deployed in these Regions. If not provided, Connectors can be deployed in any [supported Region](hosts-and-authorization#hosts). For faster request processing, we recommend adding only the required Region.
  privateProjects?:
    type: common.ProjectIdentifier[]
    description: Composable Commerce Projects that can access the Connector. If empty, only the creator can access this Connector.
  documentationUrl?:
    type: string
    description: URL to the documentation of the Connector.
