#%RAML 1.0 DataType
(annotations.package): Connector
displayName: ConnectorSearchPagedQueryResponse
description: |
  [PagedQueryResult](/../api/general-concepts#pagedqueryresult) with results containing an array of [Connector](ctp:connect:type:Connector).
properties:
  limit:
    type: number
    format: int64
    description: The maximum number of Connectors returned.
  offset:
    type: number
    format: int64
    description: The offset of the Connectors returned.
  count:
    type: number
    format: int64
    description: The number of Connectors returned.
  total:
    type: number
    format: int64
    description: The total number of Connectors matching the query.
  results:
    type: Connector[]
    description: Connectors matching the query.
