#%RAML 1.0 DataType
(annotations.package): Connector
displayName: ConnectorStaged
properties:
  id:
    (annotations.identifier): true
    type: string
    description: Unique identifier of the Connector.
  key?:
    type: string
    description: User-defined unique identifier of the Connector.
    pattern: ^[A-Za-z0-9_-]+$
    minLength: 2
    maxLength: 256
  version:
    type: integer
    description: Current version of the Connector.
  name:
    type: string
    description: Name of the Connector.
  description:
    type: string
    description: Description of the Connector.
  creator:
    type: common.Creator
    description: Owner of the Connector.
  repository:
    type: common.Repository
    description: GitHub repository details of the Connector.
  configurations:
    type: common.ConnectorConfigurationApplication[]
    description: Configurations needed by Connectors for hosting. Loaded as environment variables in the workload.
  private:
    type: boolean
    description: If `true`, only Composable Commerce Projects specified in `privateProjects` can access the Connector.
  privateProjects:
    type: common.ProjectIdentifier[]
    description: If `private` is true, only these Composable Commerce Projects can access the Connector.
  supportedRegions:
    type: common.Region[]
    description: If not empty, Connectors can only be deployed in these Regions. If empty, Connectors can be deployed in any [supported Region](hosts-and-authorization#hosts).
  certificationInfo?:
    type: common.CertificationInfo
    description: Comments made during the certification process.
  status:
    type: common.ConnectorStatus
    description: Current status of the Connector.
    default: Draft
  publishingReport?:
    type: common.ConnectorReport
    description: The publishing request report of the Connector.
  alreadyListed:
    type: boolean
    description: If `true`, the Connector is published and ready for use.
  hasChanges:
    type: boolean
    description: If `true`, the ConnectorStaged data is different from the production [Connector](ctp:connect:type:Connector) data.
  isPreviewable:
    type: common.IsPreviewable
    description: The previewable status of the ConnectorStaged.
    default: none
  previewableReport?:
    type: common.ConnectorReport
    description: The previewable request report.
  documentationUrl?:
    type: string
    description: URL to the documentation of the Connector.
