#%RAML 1.0 DataType
(annotations.package): Connector
displayName: ConnectorDraft
properties:
  key?:
    type: string
    description: User-defined unique identifier of the Connector.
  name:
    type: string
    description: Name of the Connector.
  description?:
    type: string
    description: Description of the Connector.
  creator:
    type: common.Creator
    description: Owner of the Connector.
  repository:
    type: common.Repository
    description: GitHub repository details of the Connector.
  configurations?:
    type: common.ConnectorConfigurationApplication[]
    description: Configurations needed by the Connector for hosting. Loaded as environment variables in the workload.
  supportedRegions?:
    type: common.Region[]
    description: If provided, Connectors can only be deployed in these Regions. If not provided, Connectors can be deployed in any [supported Region](hosts-and-authorization#hosts).
  private?:
    type: boolean
    default: false
    description: If `true`, only Composable Commerce Projects specified in `privateCustomers` can access the Connector.
  privateCustomers?:
    type: string[]
    description: Contains Composable Commerce Project keys listed using the format "{region}:{projectKey}". If `private` is true, only these Composable Commerce Projects can access the Connector.
