#%RAML 1.0 DataType
(package): Subscription
type: Destination
displayName: GoogleCloudPubSubDestination
discriminatorValue: GoogleCloudPubSub
properties:
  projectId:
    type: string
  topic:
    type: string
