#%RAML 1.0 DataType
(package): OrderEdit
(docs-uri): https://docs.commercetools.com/api/projects/order-edits#orderedit-previewfailure
type: OrderEditResult
displayName: OrderEditPreviewFailure
discriminatorValue: PreviewFailure
description: |
  Result of a failed application of `stagedActions` to the Order. The data is calculated on the fly and is not queryable.
properties:
  errors:
    type: ErrorObject[]
    description: |
      Errors returned.
