#%RAML 1.0 DataType
(package): OrderEdit
(docs-uri): https://docs.commercetools.com/http-api-projects-order-edits.html#ordereditdraft
displayName: OrderEditDraft
type: object
properties:
  key?:
    type: string
    description: Unique identifier for this edit.
  resource:
    type: OrderReference
    description: The order to be updated with this edit.
  stagedActions?:
    type: StagedOrderUpdateAction[]
    description: The actions to apply to `resource`.
  custom?:
    type: CustomFieldsDraft
    description: The custom fields.
  comment?:
    type: string
    description:
      This field can be used to add additional textual information regarding the
      edit.
  dryRun?:
    type: boolean
    description: When set to `true` the edit is applied on the Order without persisting it.
