#%RAML 1.0 DataType
(package): OrderEdit
(java-extends): com.commercetools.api.models.Identifiable<OrderEdit>
type: ResourceIdentifier
displayName: OrderEditResourceIdentifier
discriminatorValue: order-edit
