#%RAML 1.0 DataType
(package): OrderEdit
type: OrderEditResult
displayName: OrderEditNotProcessed
discriminatorValue: NotProcessed
description: |
  Indicates that the edit has not been applied or processed in any way.
properties:
  type:
    type: string
    description: |
      This field is queryable.
