#%RAML 1.0 DataType
(package): OrderEdit
(docs-uri): https://docs.commercetools.com/api/projects/order-edits#orderedit-applied
type: OrderEditResult
displayName: OrderEditApplied
discriminatorValue: Applied
description: |
  Result of a succesful application of `stagedActions` to the Order.
properties:
  type:
    type: string
    description: |
      This field is queryable.
  appliedAt:
    type: datetime
    description: |
      Date and time (UTC) the Order was edited.
  excerptBeforeEdit:
    type: OrderExcerpt
    description: |
      Prices of the Order before the edit.
  excerptAfterEdit:
    type: OrderExcerpt
    description: |
      Prices of the Order after the edit.
