#%RAML 1.0 DataType
(package): OrderEdit
(docs-uri): https://docs.commercetools.com/http-api-projects-order-edits.html#orderexcerpt
type: object
displayName: OrderExcerpt
properties:
  totalPrice:
    type: TypedMoney
    description: ''
  taxedPrice?:
    type: TaxedPrice
    description: ''
  version:
    type: integer
    description: ''
