#%RAML 1.0 DataType
(package): OrderEdit
(java-extends): com.commercetools.api.models.Identifiable<OrderEdit>
type: ResourceIdentifier
displayName: OrderEditResourceIdentifier
discriminatorValue: order-edit
description: |
  [ResourceIdentifier](ctp:api:type:ResourceIdentifier) to a [OrderEdit](ctp:api:type:OrderEdit).
properties:
  id?:
    type: string
    description: |
      Platform-generated unique identifier of the referenced [OrderEdit](ctp:api:type:OrderEdit). Either `id` or `key` is required.
  key?:
    type: string
    description: |
      User-defined unique identifier of the referenced [OrderEdit](ctp:api:type:OrderEdit). Either `id` or `key` is required.
