#%RAML 1.0 DataType
(package): OrderEdit
(docs-uri): https://docs.commercetools.com/http-api-projects-order-edits.html#ordereditnotprocessed
type: OrderEditResult
displayName: OrderEditNotProcessed
discriminatorValue: NotProcessed
