#%RAML 1.0 DataType
(package): ProductDiscount
(docs-uri): https://docs.commercetools.com/http-api-projects-productDiscounts.html#productdiscount
type: ResourceIdentifier
displayName: ProductDiscountResourceIdentifier
discriminatorValue: product-discount
