#%RAML 1.0 DataType
(package): ProductDiscount
(docs-uri): https://docs.commercetools.com/api/projects/productDiscounts#productdiscount
type: BaseResource
displayName: ProductDiscount
(updateType): ProductDiscountUpdate
(java-extends): 'com.commercetools.api.models.DomainResource<ProductDiscount>'
example: !include ../../examples/product-discount.example.json
properties:
  id:
    (identifier): true
    type: string
    description: |
      Unique identifier of the ProductDiscount.
  version:
    type: number
    format: int64
    description: |
      Current version of the ProductDiscount.
  createdAt:
    type: datetime
    description: |
      Date and time (UTC) the ProductDiscount was initially created.
  lastModifiedAt:
    type: datetime
    description: |
      Date and time (UTC) the ProductDiscount was last updated.
  lastModifiedBy?:
    type: LastModifiedBy
    (beta): true
    description: |
      Present on resources created after 1 February 2019 except for [events not tracked](/../api/client-logging#events-tracked).
  createdBy?:
    type: CreatedBy
    (beta): true
    description: |
      Present on resources created after 1 February 2019 except for [events not tracked](/../api/client-logging#events-tracked).
  name:
    type: LocalizedString
    description: |
      Name of the ProductDiscount.
  key?:
    type: string
    description: |
      User-defined unique identifier of the ProductDiscount.
    pattern: ^[A-Za-z0-9_-]+$
    minLength: 2
    maxLength: 256
  description?:
    type: LocalizedString
    description: |
      Description of the ProductDiscount.
  value:
    type: ProductDiscountValue
    description: |
      Type of Discount and its corresponding value.
  predicate:
    type: string
    description: |
      Valid [ProductDiscount predicate](/../api/projects/predicates#productdiscount-predicates).
  sortOrder:
    type: string
    description: |
      Unique decimal value between 0 and 1 (stored as String literal) defining the order of Product Discounts to apply in case more than one is applicable and active.
      A Product Discount with a higher value is prioritized.
  isActive:
    type: boolean
    description: |
      If `true` the Product Discount is applied to Products matching the `predicate`.
  references:
    type: Reference[]
    description: |
      References of all the resources that are addressed in the `predicate`.
  validFrom?:
    type: datetime
    description: |
      Date and time (UTC) from which the Discount is effective.
      Take [Eventual Consistency](/../api/general-concepts#eventual-consistency) into account for calculated discount values.
  validUntil?:
    type: datetime
    description: |
      Date and time (UTC) until which the Discount is effective.
      Take [Eventual Consistency](/../api/general-concepts#eventual-consistency) into account for calculated undiscounted values.
