#%RAML 1.0 DataType
(package): ProductDiscount
(docs-uri): https://docs.commercetools.com/http-api-projects-productDiscounts.html#productdiscount
type: Reference
displayName: ProductDiscountReference
discriminatorValue: product-discount
properties:
  obj?:
    type: ProductDiscount
