#%RAML 1.0 DataType
(package): ProductDiscount
type: ProductDiscountValue
displayName: ProductDiscountValueExternal
discriminatorValue: external
description: |
  Discounts the Product Price by allowing the client to explicitly [set a discounted value](ctp:api:type:ProductSetDiscountedPriceAction).
  Used when setting discounts using an external service.
