#%RAML 1.0 DataType
(package): Extension
(docs-uri): https://docs.commercetools.com/http-api-projects-api-extensions.html#change-destination
type: ExtensionUpdateAction
displayName: ExtensionChangeDestinationAction
discriminatorValue: changeDestination
(postman-example): !include ../../../examples/Extension/ExtensionChangeDestinationAction.json
properties:
  destination:
    type: ExtensionDestination
    description: ''
