#%RAML 1.0 DataType
(package): Inventory
(docs-uri): https://docs.commercetools.com/api/projects/inventory#set-supplychannel
type: InventoryEntryUpdateAction
displayName: InventoryEntrySetSupplyChannelAction
discriminatorValue: setSupplyChannel
example: !include ../../../examples/Inventory/InventoryEntrySetSupplyChannelAction.json
description: If an entry with the same `sku` and `supplyChannel` already exists, this action will fail and a [400 Bad Request](/../api/errors#400-bad-request-1) `DuplicateField` error will be returned.
properties:
  supplyChannel?:
    type: ChannelResourceIdentifier
    description: |-
      Value to set. If empty, any existing value will be removed.
