#%RAML 1.0 DataType
(package): Inventory
(docs-uri): https://docs.commercetools.com/http-api-projects-inventory.html#add-quantity
type: InventoryEntryUpdateAction
displayName: InventoryEntryAddQuantityAction
discriminatorValue: addQuantity
(postman-example): !include ../../../examples/Inventory/InventoryEntryAddQuantityAction.json
properties:
  quantity:
    type: number
    format: int64
    description: ''
