#%RAML 1.0 DataType
(package): Inventory
type: InventoryEntryUpdateAction
displayName: InventoryEntryRemoveQuantityAction
discriminatorValue: removeQuantity
example: !include ../../../examples/Inventory/InventoryEntryRemoveQuantityAction.json
description: |

  Removes a specific quantity from `quantityOnStock`. This changes the `availableQuantity`, based on the number of active reservations. You can update `quantityOnStock` to values below zero.

  Carts with existing `ReserveOnCart` reservations will not be invalidated by this update action and can still be ordered.
properties:
  quantity:
    type: number
    format: int64
    description: Value to remove from `quantityOnStock`.
