#%RAML 1.0 DataType
(package): Inventory
(docs-uri): https://docs.commercetools.com/api/projects/inventory#set-restockableindays
type: InventoryEntryUpdateAction
displayName: InventoryEntrySetRestockableInDaysAction
discriminatorValue: setRestockableInDays
example: !include ../../../examples/Inventory/InventoryEntrySetRestockableInDaysAction.json
properties:
  restockableInDays?:
    type: number
    format: int64
    description: 'Value to set. If empty, any existing value will be removed.'
