#%RAML 1.0 DataType
(package): Inventory
type: InventoryEntryUpdateAction
displayName: InventoryEntryChangeQuantityAction
discriminatorValue: changeQuantity
example: !include ../../../examples/Inventory/InventoryEntryChangeQuantityAction.json
description: |
  Sets the `quantityOnStock` to an absolute value. This changes the `availableQuantity`, based on the number of active reservations.
  To make an incremental change instead, use the [InventoryEntryAddQuantityAction](ctp:api:type:InventoryEntryAddQuantityAction) update action.
properties:
  quantity:
    type: number
    format: int64
    description: Value to set for `quantityOnStock`.
