#%RAML 1.0 DataType
(package): Inventory
(docs-uri): https://docs.commercetools.com/api/projects/inventory#set-custom-type
type: InventoryEntryUpdateAction
displayName: InventoryEntrySetCustomTypeAction
discriminatorValue: setCustomType
example: !include ../../../examples/Inventory/InventoryEntrySetCustomTypeAction.json
properties:
  type?:
    type: TypeResourceIdentifier
    description: |
      Defines the [Type](ctp:api:type:Type) that extends the InventoryEntry with [Custom Fields](/../api/projects/custom-fields).
      If absent, any existing Type and Custom Fields are removed from the InventoryEntry.
  fields?:
    type: FieldContainer
    description: |
      Sets the [Custom Fields](/../api/projects/custom-fields) fields for the InventoryEntry.
