#%RAML 1.0 DataType
(annotations.package): PaymentIntegration
type: object
displayName: LastModifiedBy
description: |
  Information regarding IDs and references that last modified the Payment Integration.
properties:
  clientId?:
    type: string
    description: |
      ID of the API client that last modified the PaymentIntegration.
  sessionId?:
    type: string
    description: |
      Session ID associated with the modification of the PaymentIntegration.
  externalUserId?:
    type: string
    description: |
      External user ID that last modified the PaymentIntegration.
  anonymousId?:
    type: string
    description: |
      Anonymous ID if the resource was last modified by an anonymous user.
  customer?:
    type: Reference
    description: |
      Customer reference or customer ID if the resource was last modified by a customer.
  associate?:
    type: Reference
    description: |
      Associate (customer) reference if the resource was last modified by an associate.
  user?:
    type: Reference
    description: |
      User reference if the resource was last modified by a platform user.
  isPlatformClient?:
    type: boolean
    description: |
      Indicates whether the resource was last modified by a platform client.
