#%RAML 1.0 DataType
(annotations.package): Common
(annotations.beta): true
displayName: Region
type: string
description: |
  The Region in which the Checkout application is [hosted](/hosts-and-authorization).
enum:
  - europe-west1.gcp
  - us-central1.gcp
  - australia-southeast1.gcp
(annotations.enumDescriptions):
  europe-west1.gcp: |
    for Europe (Google Cloud, Belgium)
  us-central1.gcp: |
    for North America (Google Cloud, Iowa)
  australia-southeast1.gcp: |
    for Australia (Google Cloud, Sydney)
