#%RAML 1.0 Trait

queryParameters:
  dataErasure:
    type: boolean
    required: false
    description: |
      Defaults to `false`.
      Set to `true` if you want to [erase all related personal data](/../api/gdpr#data-erasure-of-personal-data) in compliance with GDPR.
