#%RAML 1.0 Trait

queryParameters:
  limit:
    type: number
    format: int32
    maximum: 500
    required: false
    description: Number of results returned
  offset:
    type: number
    format: int32
    required: false
    description: Number of results skipped
  withTotal:
    type: boolean
    required: false
    description: Calculate total number of results
