#%RAML 1.0 Trait

queryParameters:
  limit:
    type: number
    format: int32
    required: false
    description: |
      Number of [results requested](/../api/general-concepts#limit).
    default: 20
    minimum: 0
    maximum: 500
  offset:
    type: number
    format: int32
    required: false
    description: |
      Number of [elements skipped](/../api/general-concepts#offset).
    default: 0
    maximum: 10000
  withTotal:
    type: boolean
    default: true
    required: false
    description: |
      Controls the calculation of the [total](/../api/general-concepts#total) number of query results. Set to `false` to improve query performance when the `total` is not needed.
