#%RAML 1.0 Trait
queryParameters:
  priceCurrency?:
    type: CurrencyCode
    description: |
      Enables [Product price selection](/../api/pricing-and-discounts-overview#product-price-selection) and [Scoped Price Search](/../api/pricing-and-discounts-overview#scoped-price-search).
  priceCountry?:
    type: CountryCode
    description: |
      Enables [Product price selection](/../api/pricing-and-discounts-overview#product-price-selection) and [Scoped Price Search](/../api/pricing-and-discounts-overview#scoped-price-search).
      It can be used only *in conjunction with* the `priceCurrency` parameter.
  priceCustomerGroup?:
    type: string
    description: |
      `id` of an existing [CustomerGroup](ctp:api:type:CustomerGroup) used for [Product price selection](/../api/pricing-and-discounts-overview#product-price-selection).
      It can be used only *in conjunction with* the `priceCurrency` parameter.
  priceCustomerGroupAssignments?:
    type: string[]
    description: |
      IDs of existing [CustomerGroups](ctp:api:type:CustomerGroup) used for [Product price selection](/../api/pricing-and-discounts-overview#product-price-selection), when using [multiple Customer Groups](/../api/customers-overview#customer-groups).
      It can be used only *in conjunction with* the `priceCurrency` parameter.
  priceChannel?:
    type: string
    description: |
      `id` of an existing [Channel](ctp:api:type:Channel) used for [Product price selection](/../api/pricing-and-discounts-overview#product-price-selection).
      It can be used only *in conjunction with* the `priceCurrency` parameter.
  priceRecurrencePolicy?:
    type: string
    (beta): true
    description: |
      `id` of an existing [RecurrencePolicy](ctp:api:type:RecurrencePolicy) used for [Product price selection](/../api/pricing-and-discounts-overview#product-price-selection).
      It can be used only *in conjunction with* the `priceCurrency` parameter.
