#%RAML 1.0 Trait

queryParameters:
  priceCurrency?:
    type: CurrencyCode
    description: |
      Validated for consistency with the GET endpoint but does not affect the existence check.
  priceCountry?:
    type: CountryCode
    description: |
      Validated for consistency with the GET endpoint. Can be used only in conjunction with the `priceCurrency` parameter.
  priceCustomerGroup?:
    type: string
    description: |
      Validated for consistency with the GET endpoint. Can be used only in conjunction with the `priceCurrency` parameter.
  priceChannel?:
    type: string
    description: |
      Validated for consistency with the GET endpoint. Can be used only in conjunction with the `priceCurrency` parameter.
  localeProjection?:
    type: Locale[]
    description: |
      Validated for consistency with the GET endpoint but does not affect the existence check.
  filter[attributes]?:
    type: string[]
    description: |
      Validated for consistency with the GET endpoint but does not affect the existence check.
