#%RAML 1.0 Trait

queryParameters:
  staged?:
    type: boolean
    default: false
    description: |
      To retrieve the [staged](ctp:api:type:CurrentStaged) Product Projection (only for API Clients that have the `view_products:{projectKey}` scope), set to `true`.
