#%RAML 1.0 Trait

queryParameters:
  staged?:
    type: boolean
    default: false
    description: |
      If `false`,

      * this endpoint returns the [current](/projects/productProjections#current--staged) Product Projection if the Product is published, a [ResourceNotFound](/errors#resourcenotfound) error otherwise.

      * this endpoint returns the ProductProjection with **tailored** Product information (if a [ProductTailoring](ctp:api:type:ProductTailoring) exists for the Product) when the ProductTailoring's `published` is `true`.
      * this endpoint returns the ProductProjection with **original** Product information when the ProductTailoring's `published` is `false`.

      If `true`,

      * this endpoint returns the [staged](/projects/productProjections#current--staged) Product Projection (only for API Clients that have the `view_products:{projectKey}` scope).

      * this endpoint returns the ProductProjection with **tailored** Product information (if a ProductTailoring exists for the Product) when either the ProductTailoring's `published` or the [ProductCatalogData](ctp:api:type:ProductCatalogData) `published` is `true`.
      If `published` is `false` for both ProductTailoring and ProductCatalogData, the ProductProjection contains **original** Product information.
