#%RAML 1.0 Trait

queryParameters:
  where:
    type: string[]
    description: |
      Use to filter query responses.

      For more information, see [Query Predicates](/api/predicates/query).
    required: false
    example: [<<whereExample>>]
  /^var[.][a-zA-Z0-9]+$/:
    type: string[]
    required: false
    (placeholderParam):
      paramName: predicateVar
      template: var.<varName>
      placeholder: varName
    description: |-
      [Predicate parameter](/api/predicates/query#input-variables) values.
