#%RAML 1.0 Trait

queryParameters:
  sort:
    type: string[]
    required: false
    description: |
      A query endpoint that supports sorting does so through the sort query parameter. The provided value must be
      a valid sort expression. The default sort direction is ASC. The allowed sort paths are typically listed on
      the specific query endpoints.

      Here are some examples of sort expressions:

          name desc
          dog.age asc

      If multiple sort expressions are specified via multiple sort parameters, they are combined into a composed
      sort where the results are first sorted by the first expression, followed by equal values being sorted
      according to the second expression, and so on.

      Note: The sorting is case sensitive.
    example: [<<sortExample>>]
