#%RAML 1.0 Library

/{productId}:
  (annotations.methodName): withProductId
  uriParameters:
    productId:
      type: string
  get:
    description: |
      Response Representation: PagedQueryResult with a results array of ProjectCategoryrecommendation, sorted by confidence scores in descending order and the meta information of ProjectCategoryrecommendationMeta.
    queryParameters:
      limit?:
        default: 3
        type: integer
      offset?:
        description: |
          Support for paging results
        default: 0
        type: integer
      staged?:
        type: boolean
        description: Flag to target either the staged or the current version of a Product.
      confidenceMin?:
        type: number
        format: float
      confidenceMax?:
        type: number
        format: float
    responses:
      200:
        body:
          application/json:
            type: category-recommendations.ProjectCategoryRecommendationPagedQueryResponse
            example: !include ../examples/category-recommendations.json
