#%RAML 1.0 Library

/attributes:
  post:
    body:
      application/json:
        type: missing-data.MissingAttributesSearchRequest
    responses:
      202:
        body:
          application/json:
            type: common.TaskToken
            example: !include ../examples/missing-data-token.json
  /status:
    /{taskId}:
      (annotations.methodName): withTaskId
      uriParameters:
        taskId:
        type: string
      get:
        responses:
          200:
            body:
              application/json:
                type: missing-data.MissingDataTaskStatus
                example: !include ../examples/missing-data-response.json
/images:
  post:
    body:
      application/json:
        type: missing-data.MissingImagesSearchRequest
    responses:
      202:
        body:
          application/json:
            type: common.TaskToken
            example: !include ../examples/missing-data-token.json
  /status:
    /{taskId}:
      (annotations.methodName): withTaskId
      uriParameters:
        taskId:
        type: string
      get:
        responses:
          200:
            body:
              application/json:
                type: missing-data.MissingImagesTaskStatus
                example: !include ../examples/missing-images-response.json
/prices:
  post:
    body:
      application/json:
        type: missing-data.MissingPricesSearchRequest
    responses:
      202:
        body:
          application/json:
            type: common.TaskToken
            example: !include ../examples/missing-data-token.json
  /status:
    /{taskId}:
      (annotations.methodName): withTaskId
      uriParameters:
        taskId:
        type: string
      get:
        responses:
          200:
            body:
              application/json:
                type: missing-data.MissingPricesTaskStatus
                example: !include ../examples/missing-prices-response.json
