#%RAML 1.0 DataType
(package): Payment
(docs-uri): https://docs.commercetools.com/http-api-projects-payments.html#set-statusinterfacecode
type: PaymentUpdateAction
displayName: PaymentSetStatusInterfaceCodeAction
discriminatorValue: setStatusInterfaceCode
(postman-example): !include ../../../examples/Payment/PaymentSetStatusInterfaceCodeAction.json
properties:
  interfaceCode?:
    type: string
    description: ''
