#%RAML 1.0 DataType
(package): RecurringOrder
type: RecurringOrderUpdateAction
displayName: RecurringOrderSetStartsAtAction
(beta): true
discriminatorValue: setStartsAt
example: !include ../../../examples/RecurringOrder/RecurringOrderSetStartsAtAction.json
description: |
  To set the start date and time, the [Recurring Order](ctp:api:type:RecurringOrder) must not have been started yet.
  Setting the start date and time generates the [RecurringOrderStartsAtSet](ctp:api:type:RecurringOrderStartsAtSetMessage) Message.
properties:
  startsAt:
    type: datetime
    description: Date and time (UTC) the [Recurring Order](ctp:api:type:RecurringOrder) should be started. The date and time must be in the future.
