#%RAML 1.0 DataType
(package): RecurringOrder
type: RecurringOrderUpdateAction
displayName: RecurringOrderSetOrderSkipConfigurationAction
(beta): true
discriminatorValue: setOrderSkipConfiguration
example: !include ../../../examples/RecurringOrder/RecurringOrderSetOrderSkipConfigurationAction.json
properties:
  skipConfiguration?:
    type: SkipConfigurationDraft
    description: |
      Configuration for skipping the next orders of the [Recurring Order](ctp:api:type:RecurringOrder).
  updatedExpiresAt?:
    type: datetime
    description: |
      Date and time (UTC) the Recurring Order will resume and start to generate new orders.
