#%RAML 1.0 DataType
(package): RecurringOrder
type: RecurringOrderUpdateAction
displayName: RecurringOrderSetScheduleAction
discriminatorValue: setSchedule
example: !include ../../../examples/RecurringOrder/RecurringOrderSetScheduleAction.json
description: |
  To set the [schedule](ctp:api:type:RecurrencePolicySchedule), the [Recurring Order](ctp:api:type:RecurringOrder) must be active, with no active [Skip Configuration](ctp:api:type:SkipConfiguration) and with available prices for all Cart items for the new schedule.
  Setting the schedule generates the [RecurringOrderScheduleSet](ctp:api:type:RecurringOrderScheduleSetMessage) Message.
properties:
  recurrencePolicy:
    type: RecurrencePolicyResourceIdentifier
    description: Value to set.
