#%RAML 1.0 DataType
(package): Error
type: ErrorObject
displayName: AttributeDefinitionTypeConflictError
discriminatorValue: AttributeDefinitionTypeConflict
properties:
  conflictingProductTypeId:
    type: string
  conflictingProductTypeName:
    type: string
  conflictingAttributeName:
    type: string
