#%RAML 1.0 DataType
(package): Error
type: ErrorObject
displayName: DuplicateFieldWithConflictingResourceError
discriminatorValue: DuplicateFieldWithConflictingResource
properties:
  field:
    type: string
  duplicateValue:
    type: any
  conflictingResource:
    type: Reference
