#%RAML 1.0 DataType

uses:
    api: ../types.lib.raml
type: object
displayName: ErrorObject
discriminator: code
(generate-collection): true
properties:
    code:
        type: string
    message:
        type: string
