#%RAML 1.0 DataType
(package): Error
type: ErrorObject
displayName: ExtensionBadResponseError
discriminatorValue: ExtensionBadResponse
properties:
  localizedMessage?:
    type: LocalizedString
  extensionExtraInfo?:
    type: object
  errorByExtension:
    type: ErrorByExtension
