#%RAML 1.0 DataType
(package): Error
type: ErrorObject
displayName: MaxResourceLimitExceededError
discriminatorValue: MaxResourceLimitExceeded
properties:
  exceededResource:
    type: ReferenceTypeId
