#%RAML 1.0 DataType

uses:
    api: ../types.lib.raml
type: api.ErrorObject
displayName: OutOfStockError
discriminatorValue: OutOfStock
properties:
    lineItems:
        type: string[]
    skus:
        type: string[]
