#%RAML 1.0 DataType
(package): Error
type: ErrorObject
displayName: ReferencedResourceNotFoundError
discriminatorValue: ReferencedResourceNotFound
properties:
  typeId:
    type: ReferenceTypeId
  id?:
    type: string
  key?:
    type: string
