#%RAML 1.0 DataType

uses:
    api: ../types.lib.raml
type: object
displayName: VariantValues
properties:
    sku?:
        type: string
    prices:
        type: api.Price[]
    attributes:
        type: api.Attribute[]
