#%RAML 1.0 DataType
(package): CartDiscount
(docs-uri): https://docs.commercetools.com/http-api-projects-cartDiscounts.html#set-customfield
type: CartDiscountUpdateAction
displayName: CartDiscountSetCustomFieldAction
discriminatorValue: setCustomField
(postman-example): !include ../../../examples/CartDiscount/CartDiscountSetCustomFieldAction.json
properties:
  name:
    type: string
    description: ''
  value?:
    type: any
    description: |-
      If `value` is absent or `null`, this field will be removed if it exists.
      If `value` is provided, set the `value` of the field defined by the `name`.
      The [FieldDefinition](/http-api-projects-types.html#fielddefinition) determines the format for the `value` to be provided.
      In particular, for the fields definitions, `value` has to be provided as:
      - for [EnumType](/http-api-projects-types.html#enumtype) and [LocalizedEnumType](/http-api-projects-types.html#localizedenumtype) fields: the `key` of the [EnumValue](/http-api-projects-types.html#enumvalue) or the [LocalizedEnumValue](/http-api-projects-types.html#localizedenumvalue)
      - for [LocalizedStringType](/http-api-projects-types.html#localizedstringtype) fields: the [LocalizedString](/http-api-types.html#localizedstring) object
      - for [MoneyType](/http-api-projects-types.html#moneytype) fields: the [Money](/http-api-types.html#money) object
      - for [SetType](/http-api-projects-types.html#settype) fields: the entire `Set` object
      - for [ReferenceType](/http-api-projects-productTypes#referencetype) fields: the [Reference](/http-api-types.html#reference) object
