#%RAML 1.0 DataType
(package): Product
displayName: AttributeValue
type: string | number | datetime | date-only | time-only | boolean |
  AttributeLocalizedEnumValue | AttributePlainEnumValue | Reference | Money |
  LocalizedString | Attribute[]
