#%RAML 1.0 DataType
(package): Product
displayName: CustomTokenizer
type: SuggestTokenizer
discriminatorValue: custom
description: |
  Define arbitrary tokens that are used to match the input.
properties:
  inputs:
    type: string[]
    description: |
      Contains custom tokens.
