#%RAML 1.0 DataType
(package): Product
(docs-uri): https://docs.commercetools.com/api/projects/products#embeddedpricedraft
displayName: EmbeddedPriceDraft
type: object
description: |
  The representation sent to the server when creating a new EmbeddedPrice.
properties:
  value:
    type: Money
    description: |
      Sets the money value of the EmbeddedPrice.
  country?:
    type: CountryCode
    description: |
      Sets the country for which the EmbeddedPrice is valid. If not set, the Price is valid for any country.
  customerGroup?:
    type: CustomerGroupResourceIdentifier
    description: |
      Sets the [CustomerGroup](ctp:api:type:CustomerGroup) for which the EmbeddedPrice is valid.
  channel?:
    type: ChannelResourceIdentifier
    description: |
      Sets the product distribution [Channel](ctp:api:type:Channel) for which the EmbeddedPrice is valid.
  discounted?:
    type: DiscountedPriceDraft
    description: |
      Sets a discounted Price from an **external service**. Absolute or relative [ProductDiscount](ctp:api:type:ProductDiscount) prices are automatically added to a Product's [EmbeddedPrice](#embeddedprice) when created. The DiscountedPrice must reference a ProductDiscount with:

      - The `isActive` flag set to `true`.
      - An `external` [ProductDiscountValue](ctp:api:type:ProductDiscountValueExternal).
      - A `predicate` which matches the [ProductVariant](ctp:api:type:ProductVariant) the [EmbeddedPrice](ctp:api:type:EmbeddedPrice) is referenced from.
  validFrom?:
    type: datetime
    description: |
      Sets the date from which the EmbeddedPrice is valid.
  validUntil?:
    type: datetime
    description: |
      Sets the date until the EmbeddedPrice is valid.
  tiers?:
    type: PriceTier[]
    description: |
      Sets Price tiers.
  custom?:
    type: CustomFieldsDraft
    description: |
      Custom Fields for the EmbeddedPrice.
