#%RAML 1.0 DataType
(package): Product
displayName: FacetRange
type: object
properties:
  from:
    type: number
    description: |
      The range's lower endpoint.

      `0` represents -∞.
  fromStr:
    type: string
    description: |
      The range's lower endpoint.

      An empty string represents -∞.
  to:
    type: number
    description: |
      The range's upper endpoint.

      `0` represents +∞.
  toStr:
    type: string
    description: |
      The range's upper endpoint.

      An empty string represents +∞.
  count:
    type: number
    format: int64
    description: |
      Number of [ProductVariants](ctp:api:type:ProductVariant) for which the values in a field fall into the specified range.
  productCount?:
    type: number
    format: int64
    description: |
      Number of [Products](ctp:api:type:Product) for which the values in a field fall into the specified range.

      Present only if the `counting products` [extension](/projects/product-projection-search#counting-products) is enabled.
  total:
    type: number
    description: |
      Sum of all values contained in the range.
  min:
    type: number
    description: |
      Minimum value within the range.
  max:
    type: number
    description: |
      Maximum value within the range.
  mean:
    type: number
    description: |
      Arithmetic mean of the values within the range.
