#%RAML 1.0 DataType
(package): Product
(docs-uri): https://docs.commercetools.com/http-api-projects-products.html#productvariantavailability
displayName: ProductVariantAvailability
type: object
properties:
  isOnStock?:
    type: boolean
  restockableInDays?:
    type: number
    format: int64
  availableQuantity?:
    type: number
    format: int64
  channels?:
    type: ProductVariantChannelAvailabilityMap
