#%RAML 1.0 DataType
(package): Product
(docs-uri): https://docs.commercetools.com/http-api-projects-products.html#product
(java-extends): com.commercetools.api.models.Identifiable<Product>
type: ResourceIdentifier
displayName: ProductResourceIdentifier
discriminatorValue: product
description: |
  [ResourceIdentifier](/../api/types#resourceidentifier) to a [Product](ctp:api:type:Product).
properties:
  id?:
    type: string
    description: |
      Platform-generated unique identifier of the referenced [Product](ctp:api:type:Product). Either `id` or `key` is required.
  key?:
    type: string
    description: |
      User-defined unique identifier of the referenced [Product](ctp:api:type:Product). Either `id` or `key` is required.
