#%RAML 1.0 DataType
(package): Product
type: object
displayName: ProductUpdate
(java-extends): 'com.commercetools.api.models.ResourceUpdate<ProductUpdate,
  ProductUpdateAction>'
properties:
  version:
    type: number
    format: int64
  actions:
    type: array
    items: ProductUpdateAction
