#%RAML 1.0 DataType
(package): Product
(docs-uri): https://docs.commercetools.com/http-api-projects-products.html#product
(java-extends): com.commercetools.api.models.Identifiable<Product>
type: Reference
displayName: ProductReference
discriminatorValue: product
properties:
  obj?:
    type: Product
