#%RAML 1.0 DataType
(package): Product
(docs-uri): https://docs.commercetools.com/http-api-projects-productProjections.html#productprojection
displayName: ProductProjection
type: BaseResource
(java-extends): 'com.commercetools.api.models.DomainResource<ProductProjection>'
properties:
  id:
    (identifier): true
    type: string
    description: The unique ID of the Product.
  version:
    type: number
    format: int64
    description: The current version of the Product.
  key?:
    type: string
    description: User-specific unique identifier of the Product.
  productType:
    description: ''
    type: ProductTypeReference
  name:
    type: LocalizedString
    description: ''
  description?:
    type: LocalizedString
    description: ''
  slug:
    type: LocalizedString
    description: ''
  categories:
    description: References to categories the product is in.
    type: CategoryReference[]
  categoryOrderHints?:
    type: CategoryOrderHints
    description: ''
  metaTitle?:
    type: LocalizedString
    description: ''
  metaDescription?:
    type: LocalizedString
    description: ''
  metaKeywords?:
    type: LocalizedString
    description: ''
  searchKeywords?:
    type: SearchKeywords
    description: ''
  hasStagedChanges?:
    type: boolean
    description: ''
  published?:
    type: boolean
    description: ''
  masterVariant:
    type: ProductVariant
    description: ''
  variants:
    type: ProductVariant[]
    description: ''
  taxCategory?:
    description: ''
    type: TaxCategoryReference
  state?:
    description: ''
    type: StateReference
  reviewRatingStatistics?:
    type: ReviewRatingStatistics
    description: Statistics about the review ratings taken into account for this product.
