#%RAML 1.0 DataType
(package): Product
displayName: RangeFacetResult
type: FacetResult
discriminatorValue: range
properties:
  ranges:
    type: FacetRange[]
    description: |
      Statistical data over values for `date`, `time`, `datetime`, `number`, and `money` type fields.
