#%RAML 1.0 DataType
(package): Product
displayName: TermFacetResultType
type: string
description: |
  Data type to which the facet is applied.
enum:
  - text
  - date
  - time
  - datetime
  - boolean
  - number
(enumDescriptions):
  text: |
    For [AttributeTextType](ctp:api:type:AttributeTextType) Attributes.
  date: |
    For [AttributeDateType](ctp:api:type:AttributeDateType) Attributes.
  time: |
    For [AttributeTimeType](ctp:api:type:AttributeTimeType) Attributes.
  datetime: |
    For [AttributeDateTimeType](ctp:api:type:AttributeDateTimeType) Attributes.
  boolean: |
    For [AttributeBooleanType](ctp:api:type:AttributeBooleanType) Attributes.
  number: |
    For [AttributeNumberType](ctp:api:type:AttributeNumberType) Attributes.
