#%RAML 1.0 DataType
(package): DiscountGroup
type: DiscountGroupUpdateAction
displayName: DiscountGroupSetNameAction
discriminatorValue: setName
example: !include ../../../examples/DiscountGroup/DiscountGroupSetNameAction.json
(beta): true
properties:
  name?:
    type: LocalizedString
    description: |
      New value to set.
      If empty, any existing value will be removed.
