#%RAML 1.0 DataType
(package): DiscountGroup
type: DiscountGroupUpdateAction
displayName: DiscountGroupSetSortOrderAction
discriminatorValue: setSortOrder
example: !include ../../../examples/DiscountGroup/DiscountGroupSetSortOrderAction.json
(beta): true
description: |
  Setting the sort order generates the [DiscountGroupSortOrderSet](ctp:api:type:DiscountGroupSortOrderSetMessage) Message.
properties:
  sortOrder:
    type: string
    description: |
      New value to set (between `0` and `1`).
      A CartDiscount with a higher value will be prioritized.

      The sort order must be unique among all DiscountGroups and CartDiscounts.
