#%RAML 1.0 DataType
(package): ShippingMethod
(docs-uri): https://docs.commercetools.com/http-api-projects-shippingMethods.html#remove-zone
type: ShippingMethodUpdateAction
displayName: ShippingMethodRemoveZoneAction
discriminatorValue: removeZone
(postman-example): !include ../../../examples/ShippingMethod/ShippingMethodRemoveZoneAction.json
properties:
  zone:
    type: ZoneResourceIdentifier
    description: ''
