#%RAML 1.0 DataType
(package): ShippingMethod
(docs-uri): https://docs.commercetools.com/http-api-projects-shippingMethods.html#set-description
type: ShippingMethodUpdateAction
displayName: ShippingMethodSetDescriptionAction
discriminatorValue: setDescription
(postman-example): !include ../../../examples/ShippingMethod/ShippingMethodSetDescriptionAction.json
properties:
  description?:
    type: string
    description: ''
