#%RAML 1.0 DataType
(package): ShippingMethod
(docs-uri): https://docs.commercetools.com/http-api-projects-shippingMethods.html#change-taxcategory
type: ShippingMethodUpdateAction
displayName: ShippingMethodChangeTaxCategoryAction
discriminatorValue: changeTaxCategory
(postman-example): !include ../../../examples/ShippingMethod/ShippingMethodChangeTaxCategoryAction.json
properties:
  taxCategory:
    type: TaxCategoryResourceIdentifier
    description: ''
