#%RAML 1.0 DataType
(package): Cart


type: CartUpdateAction
displayName: CartChangeTaxCalculationModeAction
discriminatorValue: changeTaxCalculationMode
example:
  {
    "action": "changeTaxCalculationMode",
    "taxCalculationMode": "UnitPriceLevel"
  }
properties:
    taxCalculationMode:
        type: TaxCalculationMode
