#%RAML 1.0 DataType
(package): Cart
(docs-uri): https://docs.commercetools.com/http-api-projects-carts.html#set-shippingmethod-taxamount


type: CartUpdateAction
displayName: CartSetShippingMethodTaxAmountAction
discriminatorValue: setShippingMethodTaxAmount
(postman-example): |
  {
    "action": "setShippingMethodTaxAmount",
    "externalTaxAmount": {
      "totalGross": {
      "centAmount": 2000000,
      "currencyCode": "EUR"
    },
      "taxRate": {
        "name": "myTaxRate",
        "amount": 0.19,
        "country": "DE"
      }
    }
  }
properties:
    externalTaxAmount?:
        type: ExternalTaxAmountDraft
