#%RAML 1.0 DataType
(package): Cart
(docs-uri): https://docs.commercetools.com/http-api-projects-carts.html#change-customlineitem-money


type: CartUpdateAction
displayName: CartChangeCustomLineItemMoneyAction
discriminatorValue: changeCustomLineItemMoney
example: |
  {
    "action": "changeCustomLineItemMoney",
    "customLineItemId": "{{customLineItemId}}",
    "money": {
      "currencyCode": "EUR",
      "centAmount":4200
    }
  }
properties:
    customLineItemId:
        type: string
    money:
        type: Money
