#%RAML 1.0 DataType


type: CartUpdateAction
displayName: CartAddShoppingListAction
discriminatorValue: addShoppingList
properties:
    distributionChannel?:
        type: ChannelReference
    shoppingList:
        type: ShoppingListReference
    supplyChannel?:
        type: ChannelReference
