#%RAML 1.0 DataType
(package): Cart
(docs-uri): https://docs.commercetools.com/http-api-projects-carts.html#add-itemshippingaddress


type: CartUpdateAction
displayName: CartApplyDeltaToLineItemShippingDetailsTargetsAction
discriminatorValue: applyDeltaToLineItemShippingDetailsTargets
(postman-example): |
  {
    "action": "applyDeltaToLineItemShippingDetailsTargets",
    "lineItemId": "{{lineItemId}}",
    "targetsDelta": [
      {
        "addressKey": "{{addressKey}}",
        "quantity": 1
      }
    ]
  }
properties:
    lineItemId:
        type: string
    targetsDelta:
        type: ItemShippingTarget[]
