#%RAML 1.0 DataType
(package): Cart


type: CartUpdateAction
displayName: CartSetAnonymousIdAction
discriminatorValue: setAnonymousId
example:
  {
    "action": "setAnonymousId",
    "anonymousId": "myAnonymousId"
  }
properties:
    anonymousId?:
        type: string
