#%RAML 1.0 DataType
(package): Cart


type: CartUpdateAction
displayName: CartSetShippingMethodAction
discriminatorValue: setShippingMethod
properties:
    shippingMethod?:
        type: ShippingMethodReference
