#%RAML 1.0 DataType
(package): Cart


type: CartUpdateAction
displayName: CartChangeLineItemQuantityAction
discriminatorValue: changeLineItemQuantity
example: |
  {
    "action": "changeLineItemQuantity",
    "lineItemId": "{{lineItemId}}",
    "quantity": 1
  }
properties:
    lineItemId:
        type: string
    quantity:
        type: number
    externalPrice?:
        type: Money
    externalTotalPrice?:
        type: ExternalLineItemTotalPrice
