#%RAML 1.0 DataType
(package): Cart
(docs-uri): https://docs.commercetools.com/http-api-projects-carts.html#change-lineitem-quantity


type: CartUpdateAction
displayName: CartChangeLineItemQuantityAction
discriminatorValue: changeLineItemQuantity
(postman-example): |
  {
    "action": "changeLineItemQuantity",
    "lineItemId": "{{lineItemId}}",
    "quantity": 1
  }
properties:
    lineItemId:
        type: string
    quantity:
        type: number
    externalPrice?:
        type: Money
    externalTotalPrice?:
        type: ExternalLineItemTotalPrice
