#%RAML 1.0 DataType
(package): Cart


type: CartUpdateAction
displayName: CartSetDeleteDaysAfterLastModificationAction
discriminatorValue: setDeleteDaysAfterLastModification
example:
  {
    "action": "setDeleteDaysAfterLastModification",
    "deleteDaysAfterLastModification": 90
  }
properties:
    deleteDaysAfterLastModification?:
        type: integer
