#%RAML 1.0 DataType
(package): Cart


type: CartUpdateAction
displayName: CartSetCustomerGroupAction
discriminatorValue: setCustomerGroup
example:
  {
    "action": "setCustomerGroup",
    "customerGroup": {
      "typeId": "customer-group",
      "id": "0c2eaad4-833c-43c1-98a4-5d03f57e9329"
    }
  }
properties:
  customerGroup:
    type: CustomerGroupReference
