#%RAML 1.0 DataType
(package): Cart


type: CartUpdateAction
displayName: CartSetCustomerEmailAction
discriminatorValue: setCustomerEmail
example:
  {
    "action": "setCustomerEmail",
    "email": "foo@bar.com"
  }
properties:
    email:
        type: string
