#%RAML 1.0 DataType
(package): Cart


type: CartUpdateAction
displayName: CartSetLineItemPriceAction
discriminatorValue: setLineItemPrice
properties:
    externalPrice?:
        type: Money
    lineItemId:
        type: string
