#%RAML 1.0 DataType
(package): Cart
(docs-uri): https://docs.commercetools.com/http-api-projects-carts.html#add-lineitem


type: CartUpdateAction
displayName: CartAddLineItemAction
discriminatorValue: addLineItem
example: |
  {
    "action": "addLineItem",
    "productId": "e6b98eaa-631d-422b-9fc0-af67c18ff48d",
    "variantId": 1
  }
properties:
    custom?:
        type: CustomFieldsDraft
    distributionChannel?:
        type: ChannelReference
    externalTaxRate?:
        type: ExternalTaxRateDraft
    productId:
        type: string
    quantity?:
        type: number
        default: 1
    supplyChannel?:
        type: ChannelReference
    variantId:
        type: integer
    externalPrice?:
        type: Money
    externalTotalPrice?:
        type: ExternalLineItemTotalPrice
