#%RAML 1.0 DataType
(package): Cart


type: CartUpdateAction
displayName: CartSetShippingMethodAction
discriminatorValue: setShippingMethod
example:
  {
    "action": "setShippingMethod",
    "shippingMethod": {
      "id": "5fb8a475-9fb7-4f65-a08c-4a26c26c56b8",
      "typeId": "shipping-method"
    }
  }
properties:
    shippingMethod?:
        type: ShippingMethodReference
