#%RAML 1.0 DataType
(package): Cart


type: CartUpdateAction
displayName: CartSetShippingMethodTaxRateAction
discriminatorValue: setShippingMethodTaxRate
example: |
  {
    "action": "setShippingMethodTaxRate",
    "externalTaxRate": {
      "name": "myTaxRate",
      "amount": 0.19,
      "country": "DE"
    }
  }
properties:
    externalTaxRate?:
        type: ExternalTaxRateDraft
