#%RAML 1.0 DataType
(package): Cart


type: CartUpdateAction
displayName: CartRemoveCustomLineItemAction
discriminatorValue: removeCustomLineItem
example:
  {
    "action": "removeCustomLineItem",
    "customLineItemId": "{{customLineItemId}}"
  }
properties:
    customLineItemId:
        type: string
