#%RAML 1.0 DataType
(package): Cart


type: CartUpdateAction
displayName: CartSetLocaleAction
discriminatorValue: setLocale
example: |
  {
    "action": "setLocale",
    "locale": "de-DE"
  }
properties:
    locale?:
        type: string
