#%RAML 1.0 DataType
(package): Cart
(docs-uri): https://docs.commercetools.com/http-api-projects-carts.html#classificationshippingrateinput
displayName: ClassificationShippingRateInput
type: ShippingRateInput
discriminatorValue: Classification
properties:
  key:
    type: string
  label:
    type: LocalizedString
