#%RAML 1.0 DataType
(package): Cart
(docs-uri): https://docs.commercetools.com/http-api-projects-carts.html#shippinginfo

displayName: ShippingInfo

type: object
properties:
    shippingMethodName:
        type: string
    price:
        type: TypedMoney
    shippingRate:
        type: ShippingRate
    taxedPrice?:
        type: TaxedItemPrice
    taxRate?:
        type: TaxRate
    taxCategory?:
        type: TaxCategoryReference
    shippingMethod?:
        type: ShippingMethodReference
    deliveries?: Delivery[]
    discountedPrice?:
        type: DiscountedLineItemPrice
    shippingMethodState?:
        type: ShippingMethodState
