#%RAML 1.0 DataType
(package): CustomObject
(docs-uri): https://docs.commercetools.com/api/projects/custom-objects#customobjectdraft
displayName: CustomObjectDraft
example: !include ../../examples/CustomObjects/CustomObjectDraft.json
type: object
properties:
  container:
    type: string
    description: |
      Namespace to group CustomObjects.
    pattern: ^[-_~.a-zA-Z0-9]+$
  key:
    type: string
    description: |
      User-defined unique identifier of the CustomObject within the defined `container`.
    pattern: ^[-_~.a-zA-Z0-9]+$
    minLength: 1
    maxLength: 256
  value:
    type: any
    description: |
      JSON standard types Number, String, Boolean, Array, Object, and [common API data types](/../api/types).
      For values of type [Reference](ctp:api:type:Reference) the integrity of the data is not guaranteed.
      If the referenced object is deleted, the API does not delete the corresponding reference to it and the `value` points to a non-existing object in such case.
  version?:
    type: number
    format: int64
    description: |
      Current version of the CustomObject.
