#%RAML 1.0 DataType
(package): Cart
type: Allocation
(beta): true
displayName: AbsoluteAllocation
discriminatorValue: Absolute
example: !include ../../examples/Cart/AbsoluteAllocation.json
description: |
  Allocates a fixed amount of the Order total to a Payment Method.
properties:
  amount:
    type: HighPrecisionMoney
    description: |
      Amount of the Order total allocated to the Payment Method.
