#%RAML 1.0 DataType
(package): Cart
type: AllocationDraft
(beta): true
displayName: AbsoluteAllocationDraft
discriminatorValue: Absolute
example: !include ../../examples/Cart/AbsoluteAllocationDraft.json
description: |
  Allocates a fixed amount of the Order total to a Payment Method.
properties:
  amount:
    type: HighPrecisionMoneyDraft
    description: |
      Amount of the Order total allocated to the Payment Method.
