#%RAML 1.0 DataType
(package): Cart
type: object
(beta): true
displayName: AllocationDraft
discriminator: type
description: |
  Draft type that stores the share of the Order total that a [PaymentAllocationDraft](ctp:api:type:PaymentAllocationDraft) covers.
properties:
  type:
    type: string
    description: |
      Type of the Allocation.
