#%RAML 1.0 DataType
(package): Cart
(docs-uri): https://docs.commercetools.com/api/projects/carts#cartresourceidentifier
type: ResourceIdentifier
displayName: CartResourceIdentifier
discriminatorValue: cart
description: |
  [ResourceIdentifier](ctp:api:type:ResourceIdentifier) to a [Cart](ctp:api:type:Cart). Either `id` or `key` is required. If both are set, an [InvalidJsonInput](/../api/errors#invalidjsoninput) error is returned.
properties:
  id?:
    type: string
    description: |
      Unique identifier of the referenced [Cart](ctp:api:type:Cart). Required if `key` is absent.
  key?:
    type: string
    description: |
      User-defined unique identifier of the referenced [Cart](ctp:api:type:Cart). Required if `id` is absent.
