#%RAML 1.0 DataType
(package): Cart
displayName: CartLock
type: object
description: |
  Indicates that the Cart is [locked](/../api/carts-orders-overview#lock-a-cart) to prevent changes.
  Provides metadata about when the lock was created and which
  [API Client](ctp:api:type:ApiClient) initiated it.
properties:
  createdAt:
    type: datetime
    description: |
      Date and time (UTC) the Cart was locked.
  clientId:
    type: string
    description: |
      `id` of the [API Client](ctp:api:type:ApiClient) that locked the Cart.
