#%RAML 1.0 DataType
(package): Cart
(docs-uri): https://docs.commercetools.com/http-api-projects-carts.html#cart
displayName: Cart
(updateType): CartUpdate
type: BaseResource
(java-extends): 'com.commercetools.api.models.DomainResource<Cart>'
properties:
  id:
    (identifier): true
    type: string
    description: The unique ID of the cart.
  key?:
    type: string
    description: User-specific unique identifier of the cart.
  version:
    type: number
    format: int64
    description: The current version of the cart.
  createdAt:
    type: datetime
    description: ''
  lastModifiedAt:
    type: datetime
    description: ''
  lastModifiedBy?:
    type: LastModifiedBy
    description:
      Present on resources updated after 1/02/2019 except for events not
      tracked.
  createdBy?:
    type: CreatedBy
    description:
      Present on resources created after 1/02/2019 except for events not
      tracked.
  customerId?:
    type: string
    description: ''
  customerEmail?:
    type: string
    description: ''
  anonymousId?:
    type: string
    description:
      Identifies carts and orders belonging to an anonymous session (the
      customer has not signed up/in yet).
  store?:
    type: StoreKeyReference
    description: ''
  lineItems:
    type: LineItem[]
    description: ''
  customLineItems:
    type: CustomLineItem[]
    description: ''
  totalPrice:
    description: |-
      The sum of all `totalPrice` fields of the `lineItems` and `customLineItems`, as well as the `price` field of `shippingInfo` (if it exists).
      `totalPrice` may or may not include the taxes: it depends on the taxRate.includedInPrice property of each price.
    type: TypedMoney
  taxedPrice?:
    type: TaxedPrice
    description: |-
      Not set until the shipping address is set.
      Will be set automatically in the `Platform` TaxMode.
      For the `External` tax mode it will be set  as soon as the external tax rates for all line items, custom line items, and shipping in the cart are set.
  cartState:
    type: CartState
    description: ''
  shippingAddress?:
    type: Address
    description:
      The shipping address is used to determine the eligible shipping methods
      and rates as well as the tax rate of the line items.
  billingAddress?:
    type: Address
    description: ''
  inventoryMode?:
    type: InventoryMode
    description: ''
  taxMode:
    type: TaxMode
    description: ''
  taxRoundingMode:
    type: RoundingMode
    description:
      When calculating taxes for `taxedPrice`, the selected mode is used for
      rounding.
  taxCalculationMode:
    type: TaxCalculationMode
    description:
      When calculating taxes for `taxedPrice`, the selected mode is used for
      calculating the price with `LineItemLevel` (horizontally) or
      `UnitPriceLevel` (vertically) calculation mode.
  customerGroup?:
    type: CustomerGroupReference
    description: |-
      Set automatically when the customer is set and the customer is a member of a customer group.
      Used for product variant
      price selection.
  country?:
    type: CountryCode
    description: |-
      A two-digit country code as per [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2).
      Used for product variant price selection.
  shippingInfo?:
    type: ShippingInfo
    description: Set automatically once the ShippingMethod is set.
  discountCodes?:
    type: DiscountCodeInfo[]
    description: ''
  custom?:
    type: CustomFields
    description: ''
  paymentInfo?:
    type: PaymentInfo
    description: ''
  locale?:
    type: string
    description: ''
  deleteDaysAfterLastModification?:
    type: integer
    description:
      The cart will be deleted automatically if it hasn't been modified for the
      specified amount of days and it is in the `Active` CartState.
  refusedGifts:
    type: CartDiscountReference[]
    description:
      Automatically filled when a line item with LineItemMode `GiftLineItem` is
      removed from the cart.
  origin:
    type: CartOrigin
    description: |-
      The origin field indicates how this cart was created.
      The value `Customer` indicates, that the cart was created by the customer.
  shippingRateInput?:
    type: ShippingRateInput
    description: The shippingRateInput is used as an input to select a
      ShippingRatePriceTier.
  itemShippingAddresses?:
    type: Address[]
    description: |-
      Contains addresses for carts with multiple shipping addresses.
      Line items reference these addresses under their `shippingDetails`.
      The addresses captured here are not used to determine eligible shipping methods or the applicable tax rate.
      Only the cart's `shippingAddress` is used for this.
