#%RAML 1.0 DataType
(package): Cart
type: object
displayName: CartUpdate
(java-extends): 'com.commercetools.api.models.ResourceUpdate<CartUpdate, CartUpdateAction>'
properties:
  version:
    type: number
    format: int64
  actions:
    type: array
    items: CartUpdateAction
