#%RAML 1.0 DataType
(package): Cart
displayName: CustomLineItemPriceMode
type: string
enum:
  - Standard
  - External
(enumDescriptions):
  Standard: Lets Composable Commerce apply Cart Discounts for the Custom Line Item. This is the default mode for backwards compatibility.
  External: Deactivates application of Cart Discounts for the Custom Line Item despite a matching [CartDiscountCustomLineItemsTarget](ctp:api:type:CartDiscountCustomLineItemsTarget).
