#%RAML 1.0 DataType
(package): Cart
(docs-uri): https://docs.commercetools.com/api/projects/carts#directdiscount
displayName: DirectDiscount
type: object
description: |
  Represents a [CartDiscount](ctp:api:type:CartDiscount) that is only associated with a single Cart or Order.
properties:
  id:
    (identifier): true
    type: string
    description: |
      Unique identifier of the Direct Discount.
  value:
    type: CartDiscountValue
    description: |
      Effect of the Discount on the Cart.
  target?:
    type: CartDiscountTarget
    description: |
      Part of the Cart that is discounted.

      Empty when the `value` is set to `giftLineItem`.
