#%RAML 1.0 DataType
(package): Cart
(docs-uri): https://docs.commercetools.com/http-api-projects-carts.html#discountedlineitemportion
displayName: DiscountedLineItemPortion
type: object
properties:
  discount:
    type: CartDiscountReference
    description: ''
  discountedAmount:
    type: TypedMoney
    description: ''
