#%RAML 1.0 DataType
(package): Cart
(docs-uri): https://docs.commercetools.com/api/projects/carts#discountedlineitempriceforquantity
displayName: DiscountedLineItemPriceForQuantity
type: object
properties:
  quantity:
    type: number
    format: int64
    description: |
      Number of Line Items or Custom Line Items in the Cart.
  discountedPrice:
    type: DiscountedLineItemPrice
    description: |
      Discounted price of the Line Item or Custom Line Item.
