#%RAML 1.0 DataType
(package): Cart
type: object
displayName: ExternalLineItemTotalPrice
properties:
  price:
    type: Money
    description: |
      Price of the Line Item.

      To set the money value in high precision, use [HighPrecisionMoneyDraft](ctp:api:type:HighPrecisionMoneyDraft).
  totalPrice:
    type: Money
    description: |
      Total price of the Line Item.
