#%RAML 1.0 DataType
(package): Cart
(docs-uri): https://docs.commercetools.com/http-api-projects-carts.html#externaltaxratedraft
displayName: ExternalTaxRateDraft
type: object
properties:
  name:
    type: string
    description: ''
  amount?:
    type: number
    description: |-
      Percentage in the range of [0..1].
      Must be supplied if no `subRates` are specified.
      If `subRates` are specified
      then the `amount` can be omitted or it must be the sum of the amounts of all `subRates`.
  country:
    type: string
    description: A two-digit country code as per [ISO 3166-1
      alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2).
  state?:
    type: string
    description: The state in the country
  subRates?:
    type: SubRate[]
    description: |-
      For countries (e.g.
      the US) where the total tax is a combination of multiple taxes (e.g.
      state and local taxes).
  includedInPrice?:
    type: boolean
    description: The default value for `includedInPrice` is FALSE.
