#%RAML 1.0 DataType
(package): Cart
(docs-uri): https://docs.commercetools.com/http-api-projects-carts.html#itemshippingdetails
displayName: ItemShippingDetails
type: object
properties:
  targets:
    type: ItemShippingTarget[]
    description: |-
      Used to map what sub-quantity should be shipped to which address.
      Duplicate address keys are not allowed.
  valid:
    type: boolean
    description: |-
      `true` if the quantity of the Line Item or Custom Line Item is equal to the sum of the sub-quantities in `targets`, else it is `false`.
      Ordering a Cart with value as `false` returns an [InvalidItemShippingDetails](ctp:api:type:InvalidItemShippingDetailsError) error.
