#%RAML 1.0 DataType
(package): Cart
(docs-uri): https://docs.commercetools.com/api/projects/carts#itemshippingdetails
displayName: ItemShippingDetails
type: object
properties:
  targets:
    type: ItemShippingTarget[]
    description: |
      Holds information on the quantity of Line Items or Custom Line Items and the address it is shipped.
  valid:
    type: boolean
    description: |
      - `true` if the quantity of Line Items or Custom Line Items is equal to the sum of sub-quantities defined in `targets`.
      - `false` if the quantity of Line Items or Custom Line Items is not equal to the sum of sub-quantities defined in `targets`.
        Ordering a Cart when the value is `false` returns an [InvalidItemShippingDetails](ctp:api:type:InvalidItemShippingDetailsError) error.
