#%RAML 1.0 DataType
(package): Cart
displayName: LineItemMode
type: string
description: |
  Indicates how a Line Item was added to a Cart.
enum:
  - Standard
  - GiftLineItem
(enumDescriptions):
  Standard: |
    The Line Item was added during [Cart creation](ctp:api:endpoint:/{projectKey}/carts:POST) or the [Add LineItem](ctp:api:type:CartAddLineItemAction) update action.
    The Line Item quantity can be changed without restriction.
  GiftLineItem: |
    One Line Item was added automatically to a Cart by a Cart Discount with [CartDiscountValueGiftLineItemDraft](ctp:api:type:CartDiscountValueGiftLineItemDraft).

    The quantity cannot be [increased](ctp:api:type:CartChangeLineItemQuantityAction), and it won't be merged when [adding](ctp:api:type:CartAddLineItemAction) the same Line Item to the Cart.
    If the gift is [removed](ctp:api:type:CartRemoveLineItemAction), an entry is added to the `refusedGifts` array and the discount won't be applied to the Cart.

    The `totalPrice` is always `0` and cannot be changed externally via the [setLineItemTotalPrice](ctp:api:type:CartSetLineItemTotalPriceAction) action.

    All other updates, such as the ones related to Custom Fields, can be used.
