#%RAML 1.0 DataType
(package): Cart
(docs-uri): https://docs.commercetools.com/http-api-projects-carts.html#lineitem
displayName: LineItem
type: object
(java-extends): 'com.commercetools.api.models.Customizable<LineItem>'
properties:
  id:
    type: string
    description: Unique identifier of the LineItem.
  productId:
    type: string
    description: ''
  productKey?:
    type: string
    description: |-
      User-defined unique identifier of the [Product](ctp:api:type:Product).
      Only present on Line Items in a [Cart](ctp:api:type:Cart) when the `key` is available on that specific Product at the time the Line Item is created or updated on the Cart. On [Order](/ctp:api:type:Order) resources this field is only present when the `key` is available on the specific Product at the time the Order is created from the Cart. This field is in general not present on Carts that had no updates until 3 December 2021 and on Orders created before this date.
  name:
    type: LocalizedString
    description: The product name.
  productSlug?:
    type: LocalizedString
    description: |-
      The slug of a product is inserted on the fly.
      It is always up-to-date and can therefore be used to link to the product detail page of the product.
      It is empty if the product has been deleted.
      The slug is also empty if the cart or order is retrieved via Reference Expansion or is a snapshot in a Message.
  productType:
    type: ProductTypeReference
    description: ''
  variant:
    type: ProductVariant
    description: |-
      The variant data is saved when the variant is added to the cart, and not updated automatically.
      It can manually be updated with the Recalculate update action.
  price:
    type: Price
    description: |-
      The price of a line item is selected from the product variant according to the Product's [priceMode](ctp:api:type:Product) value.
      If the `priceMode` is `Embedded` [ProductPriceMode](ctp:api:type:ProductPriceModeEnum) and the `variant` field hasn't been updated, the price may not correspond to a price in `variant.prices`.
  taxedPrice?:
    type: TaxedItemPrice
    description: Set once the `taxRate` is set.
  taxedPricePortions:
    type: MethodTaxedPrice[]
    description: |-
      Taxed price of the Shipping Method that is set automatically after `perMethodTaxRate` is set.
  totalPrice:
    type: TypedMoney
    description: |-
      The total price of this line item.
      If the line item is discounted, then the `totalPrice` is the DiscountedLineItemPriceForQuantity multiplied by `quantity`.
      Otherwise the total price is the product price multiplied by the `quantity`.
      `totalPrice` may or may not include the taxes: it depends on the taxRate.includedInPrice property.
  quantity:
    type: number
    format: int64
    description: |-
      The amount of a LineItem in the cart.
      Must be a positive integer.
  addedAt?:
    type: datetime
    description: |-
      When the line item was added to the cart. Optional for backwards
      compatibility reasons only.
  state:
    description: ''
    type: ItemState[]
  taxRate?:
    type: TaxRate
    description: |-
      Will be set automatically in the `Platform` TaxMode once the shipping address is set is set.
      For the `External` tax mode the tax rate has to be set explicitly with the ExternalTaxRateDraft.
  perMethodTaxRate:
    type: MethodTaxRate[]
    description: |-
      Tax Rate per Shipping Method that is automatically set after the [Shipping Method is added](ctp:api:type:CartAddShippingMethodAction) to a Cart with the `Platform` [TaxMode](ctp:api:type:TaxMode) and `Multiple` [ShippingMode](ctp:api:type:ShippingMode).

      For the `External` [TaxMode](ctp:api:type:TaxMode), the Tax Rate must be set with [ExternalTaxRateDraft](ctp:api:type:ExternalTaxRateDraft).
  supplyChannel?:
    type: ChannelReference
    description: |-
      The supply channel identifies the inventory entries that should be reserved.
      The channel has
      the role InventorySupply.
  distributionChannel?:
    type: ChannelReference
    description: |-
      The distribution channel is used to select a ProductPrice.
      The channel has the role ProductDistribution.
  discountedPricePerQuantity:
    description: ''
    type: DiscountedLineItemPriceForQuantity[]
  priceMode:
    type: LineItemPriceMode
    description: ''
  lineItemMode:
    type: LineItemMode
    description: ''
  custom?:
    type: CustomFields
    description: ''
  inventoryMode?:
    type: InventoryMode
    description: |-
      Inventory mode specific to the line item only, valid for the entire `quantity` of the line item.
      Only present if inventory mode is different from the `inventoryMode` specified on the [Cart](ctp:api:type:Cart).
  shippingDetails?:
    type: ItemShippingDetails
    description: Container for line item specific address(es).
  lastModifiedAt?:
    type: datetime
    description: |-
      The date when the LineItem was last modified by one of the following actions
      setLineItemShippingDetails, addLineItem, removeLineItem, or changeLineItemQuantity.
      Optional only for backwards compatible reasons. When the LineItem is created lastModifiedAt is set to addedAt.
