#%RAML 1.0 DataType
(package): Cart
(docs-uri): https://docs.commercetools.com/api/projects/carts#methodtaxrate
displayName: MethodTaxRate
type: object
properties:
  shippingMethodKey:
    type: string
    description: |
      User-defined unique identifier of the Shipping Method in a Cart with `Multiple` [ShippingMode](ctp:api:type:ShippingMode).
  taxRate?:
    type: TaxRate
    description: |
      Tax Rate for the Shipping Method.
