#%RAML 1.0 DataType
(package): Reservation
type: Reference
displayName: ReservationReference
discriminatorValue: reservation
description: |
  [Reference](ctp:api:type:Reference) to a [Reservation](ctp:api:type:Reservation).
properties:
  typeId:
    type: ReferenceTypeId
    description: ''
  obj?:
    type: Reservation
    description: |
      Contains the representation of the expanded Reservation.
      Only present in responses to requests with [Reference Expansion](/../api/general-concepts#reference-expansion) for Reservations.
  id:
    type: string
    description: |
      Unique identifier of the referenced [Reservation](ctp:api:type:Reservation).
