#%RAML 1.0 DataType
(package): Cart
(docs-uri): https://docs.commercetools.com/http-api-projects-carts.html#shipping
displayName: Shipping
type: object
properties:
  shippingKey:
    type: string
    description: |
      User-defined unique identifier of the Shipping Method in a Cart with `Multi` [ShippingMode](ctp:api:type:ShippingMode).
  shippingInfo:
    type: ShippingInfo
    description: |
      Automatically set when the [Shipping Method is added](ctp:api:type:CartAddShippingMethodAction).
  shippingAddress:
    type: Address
    description: |
      Determines the shipping rates and Tax Rates of the associated Line Item quantities.
  shippingRateInput?:
    type: ShippingRateInput
    description: |
      Used as an input to select a [ShippingRatePriceTier](ctp:api:type:ShippingRatePriceTier).

      - Must be [ClassificationShippingRateInput](ctp:api:type:ClassificationShippingRateInput) if [ShippingRateInputType](ctp:api:type:ShippingRateInputType) is [CartClassificationType](ctp:api:type:CartClassificationType).
      - Must be [ScoreShippingRateInput](ctp:api:type:ScoreShippingRateInput) if [ShippingRateInputType](ctp:api:type:ShippingRateInputType) is [CartScoreType](ctp:api:type:CartScoreType).
  shippingCustomFields?:
    type: CustomFields
    description: |
      Custom Fields of Shipping.
