#%RAML 1.0 DataType
(package): Cart
(docs-uri): https://docs.commercetools.com/api/projects/carts#shippingmode
displayName: ShippingMode
type: string
enum:
  - Single
  - Multi
(enumDescriptions):
  Single: |
    Cart can contain only a single Shipping Method.
    This is the default mode for backwards compatibilty.
  Multi: |
    Cart can contain multiple Shipping Methods.
