#%RAML 1.0 DataType
(package): Cart
(docs-uri): https://docs.commercetools.com/api/projects/carts#shipping
displayName: Shipping
type: object
properties:
  shippingKey:
    type: string
    description: |
      User-defined unique identifier of the Shipping in a Cart with `Multiple` [ShippingMode](ctp:api:type:ShippingMode).
  shippingInfo:
    type: ShippingInfo
    description: |
      Automatically set when the [Shipping Method is added](ctp:api:type:CartAddShippingMethodAction).
  shippingAddress:
    type: Address
    description: |
      Determines the shipping rates and Tax Rates of associated Line Items.
  shippingRateInput?:
    type: ShippingRateInput
    description: |
      Used as an input to select a [ShippingRatePriceTier](ctp:api:type:ShippingRatePriceTier).
      The data type of this field depends on the `shippingRateInputType.type` configured in the [Project](ctp:api:type:Project):

      - If `CartClassification`, it is [ClassificationShippingRateInput](ctp:api:type:ClassificationShippingRateInput).
      - If `CartScore`, it is [ScoreShippingRateInput](ctp:api:type:ScoreShippingRateInput).
      - If `CartValue`, it cannot be used.

  shippingCustomFields?:
    type: CustomFields
    description: |
      Custom Fields of Shipping with `Multiple` [ShippingMode](ctp:api:type:ShippingMode).
