#%RAML 1.0 DataType
(package): Cart
displayName: TaxedItemPrice
type: object
properties:
  totalNet:
    type: CentPrecisionMoney
    description: |
      Total net amount of the Line Item or Custom Line Item.
  totalGross:
    type: CentPrecisionMoney
    description: |
      Total gross amount of the Line Item or Custom Line Item.
  taxPortions:
    type: TaxPortion[]
    description: |
      Taxable portions added to the total net price.

      Calculated from the [TaxRates](ctp:api:type:TaxRate).
  totalTax?:
    type: CentPrecisionMoney
    description: |
      Total tax applicable for the Line Item or Custom Line Item.
      Automatically calculated as the difference between the `totalGross` and `totalNet` values.
