#%RAML 1.0 DataType
(package): Cart
(docs-uri): https://docs.commercetools.com/api/projects/carts#taxportiondraft
displayName: TaxPortionDraft
type: object
description: |
  Represents the portions that sum up to the `totalGross` field of a [TaxedPrice](ctp:api:type:TaxedPrice).

  The portions are calculated from the [TaxRates](ctp:api:type:TaxRate).
  If a Tax Rate has [SubRates](ctp:api:type:SubRate), they are used and can be identified by name.
  Tax portions from Line Items with the same `rate` and `name` will be accumulated to the same tax portion.
properties:
  name?:
    type: string
    description: |
      Name of the tax portion.
  rate:
    type: number
    description: |
      A number in the range 0-1.
    minimum: 0
    maximum: 1
  amount:
    type: Money
    description: |
      Money value for the tax portion.
