#%RAML 1.0 DataType
(package): ApiClient
(docs-uri): https://docs.commercetools.com/api/projects/api-clients#apiclientdraft
displayName: ApiClientDraft
type: object
properties:
  name:
    type: string
    description: Name of the API Client.
  scope:
    type: string
    description: Whitespace-separated list of [OAuth scopes](/../api/scopes) that can be used when [obtaining an access token](/../api/authorization#requesting-an-access-token-using-commercetools-oauth-20-server).
  deleteDaysAfterCreation?:
    type: number
    format: int64
    description: If set, the client will be deleted after the specified amount of days.
