#%RAML 1.0 DataType
(package): Me
(docs-uri): https://docs.commercetools.com/http-api-projects-me-carts#set-custom-shipping-method

type: MyCartUpdateAction
displayName: MyCartSetCustomShippingMethodAction
discriminatorValue: setCustomShippingMethod

properties:
  shippingMethodName:
    type: string
  shippingRate:
    type: ShippingRateDraft
  taxCategory?:
    type: TaxCategoryResourceIdentifier
  externalTaxRate?:
    type: ExternalTaxRateDraft
