#%RAML 1.0 DataType
(package): Me
(docs-uri): https://docs.commercetools.com/http-api-projects-me-profile.html#set-last-name

type: MyCustomerUpdateAction
displayName: MyCustomerSetLastNameAction
discriminatorValue: setLastName

properties:
  lastName?:
    type: string
