#%RAML 1.0 DataType
(package): Me
(docs-uri): https://docs.commercetools.com/http-api-projects-me-profile.html#set-default-billing-address

type: MyCustomerUpdateAction
displayName: MyCustomerSetDefaultBillingAddressAction
discriminatorValue: setDefaultBillingAddress

properties:
  addressId?:
    type: string
  addressKey?:
    type: string
