#%RAML 1.0 DataType
(package): Me
(docs-uri): https://docs.commercetools.com/http-api-projects-me-payments#set-methodinfointerface

type: MyPaymentUpdateAction
displayName: MyPaymentSetMethodInfoInterfaceAction
discriminatorValue: setMethodInfoInterface

properties:
  interface:
    type: string
