#%RAML 1.0 DataType
(package): Me
(docs-uri): https://docs.commercetools.com/http-api-projects-me-payments#set-methodinfomethod

type: MyPaymentUpdateAction
displayName: MyPaymentSetMethodInfoMethodAction
discriminatorValue: setMethodInfoMethod

properties:
  method?:
    type: string
