#%RAML 1.0 DataType
(package): Me
(docs-uri): https://docs.commercetools.com/http-api-projects-me-shoppingLists#add-lineitem

type: MyShoppingListUpdateAction
displayName: MyShoppingListAddLineItemAction
discriminatorValue: addLineItem

properties:
  sku?:
    type: string
  productId?:
    type: string
  variantId?:
    type: number
    format: int64
  quantity?:
    type: number
    format: int64
  addedAt?:
    type: datetime
  custom?:
    type: CustomFieldsDraft
