#%RAML 1.0 DataType
(package): Me
(docs-uri): https://docs.commercetools.com/http-api-projects-me-shoppingLists#change-textlineitems-order

type: MyShoppingListUpdateAction
displayName: MyShoppingListChangeTextLineItemsOrderAction
discriminatorValue: changeTextLineItemsOrder

properties:
  textLineItemOrder:
    type: string[]
