#%RAML 1.0 DataType
(package): ApprovalFlow
displayName: ApprovalFlowStatus
type: string
description: |
  Indicates whether the [Approval Flow](ctp:api:type:ApprovalFlow) is under review, approved, or rejected.
enum:
  - Pending
  - Approved
  - Rejected
(enumDescriptions):
  Pending: |
    Default status of Approval Flows, indicating that the Approval Flow has not been fully approved or rejected.
  Approved: |
    Automatically set when all approvers from matching Approval Rules have approved. It indicates that the Approval Flow has been fully approved and is completed.
  Rejected: |
    Automatically set when a rejection occurs in the Approval Flow. A single rejection is sufficient to reject the entire Approval Flow.
