#%RAML 1.0 DataType
(package): Type
(docs-uri): https://docs.commercetools.com/http-api-projects-types.html#localizedstringtype
type: FieldType
displayName: CustomFieldLocalizedStringType
discriminatorValue: LocalizedString
