#%RAML 1.0 DataType
(package): Type
(docs-uri): https://docs.commercetools.com/http-api-projects-types.html#referencetype
type: FieldType
displayName: CustomFieldReferenceType
discriminatorValue: Reference
description: |
  Field type for [Reference](ctp:api:type:Reference) values.
properties:
  referenceTypeId:
    type: CustomFieldReferenceValue
    description: |
      Resource type the Custom Field can reference.
