#%RAML 1.0 DataType
(package): Type
displayName: FieldContainer
type: object
(expandable): true
(asMap):
  key: string
  value: any
example: !include ../../examples/Type/FieldContainer.json
properties:
  # field naming constraint: https://docs.commercetools.com/api/projects/types#fielddefinition
  /^[a-zA-Z0-9_-]{2,36}$/:
    (expandable): true
    type: CustomFieldValue
    description: |
      JSON object with keys matching the names of Custom Fields (that is, `name`s in the [FieldDefinitions](ctp:api:type:FieldDefinition)) and values given by [CustomFieldValue](ctp:api:type:CustomFieldValue).
