#%RAML 1.0 DataType
(package): Type
displayName: ResourceTypeId
type: string
enum:
  - address
  - asset
  - category
  - channel
  - customer
  - order
  - order-edit
  - inventory-entry
  - line-item
  - custom-line-item
  - product-price
  - payment
  - payment-interface-interaction
  - review
  - shipping-method
  - shopping-list
  - shopping-list-text-line-item
  - discount-code
  - cart-discount
  - customer-group
