#%RAML 1.0 DataType
(package): CustomerGroup
(docs-uri): https://docs.commercetools.com/http-api-projects-customerGroups.html#customergroup
type: Reference
displayName: CustomerGroupReference
discriminatorValue: customer-group
description: |
  [Reference](/types#reference) to a [CustomerGroup](ctp:api:type:CustomerGroup).
properties:
  obj?:
    type: CustomerGroup
    description: |
      Contains the representation of the expanded Customer Group. Only present in responses to requests with [Reference Expansion](/../api/general-concepts#reference-expansion) for Customer Groups.
  id:
    type: string
    description: |
      Unique ID of the referenced [CustomerGroup](ctp:api:type:CustomerGroup).
