#%RAML 1.0 DataType
(package): CustomerGroup
displayName: CustomerGroup
(updateType): CustomerGroupUpdate
type: BaseResource
description:
properties:
  id:
    (identifier): true
    type: string
    description: |
      Unique identifier of the CustomerGroup.
  version:
    type: number
    format: int64
    description: |
      Current version of the CustomerGroup.
  createdAt:
    type: datetime
    description: |
      Date and time (UTC) the CustomerGroup was initially created.
  lastModifiedAt:
    type: datetime
    description: |
      Date and time (UTC) the CustomerGroup was last updated.
  lastModifiedBy?:
    type: LastModifiedBy
    (beta): true
    description: |
      IDs and references that last modified the CustomerGroup.
  createdBy?:
    type: CreatedBy
    (beta): true
    description: |
      IDs and references that created the CustomerGroup.
  key?:
    type: string
    description: |
      User-defined unique identifier for the CustomerGroup.
    pattern: ^[A-Za-z0-9_-]+$
    minLength: 2
    maxLength: 256
  name:
    type: string
    description: |
      Unique name of the CustomerGroup.
  custom?:
    type: CustomFields
    description: |
      Custom Fields for the CustomerGroup.
