#%RAML 1.0 DataType
(package): ProductSelection
(docs-uri): https://docs.commercetools.com/api/projects/product-selections#individualproductselectiontype
(beta): true
(deprecated): true
type: ProductSelectionType
displayName: IndividualProductSelectionType
discriminatorValue: individual
properties:
  name:
    type: LocalizedString
    description: The name of the ProductSelection which is recommended to be unique.
