#%RAML 1.0 DataType
(package): ProductSelection
(docs-uri):
displayName: ProductSelection
(updateType): ProductSelectionUpdate
type: BaseResource
properties:
  id:
    (identifier): true
    type: string
    description: |
      Unique identifier of the ProductSelection.
  version:
    type: number
    format: int64
    description: Current version of the ProductSelection.
  createdAt:
    type: datetime
    description: |-
      Date and time (UTC) the ProductSelection was initially created.
  lastModifiedAt:
    type: datetime
    description: |-
      Date and time (UTC) the ProductSelection was last updated.
  lastModifiedBy?:
    type: LastModifiedBy
    description: |-
      Present on resources updated after 1/02/2019 except for [events not tracked](/../api/client-logging#events-tracked).
  createdBy?:
    type: CreatedBy
    description: |-
      Present on resources created after 1/02/2019 except for [events not tracked](/../api/client-logging#events-tracked).
  key?:
    type: string
    description: |
      User-defined unique identifier of the ProductSelection.
  name:
    type: LocalizedString
    description: Name of the ProductSelection.
  productCount:
    type: number
    format: int32
    description: |-
      Number of Products that are currently assigned to this ProductSelection.
  type?:
    (markDeprecated): true
    type: ProductSelectionTypeEnum
    description: |-
      Specifies in which way the Products are assigned to the ProductSelection.
      Currently, the only way of doing this is to specify each Product individually, either by [including or excluding](ctp:api:type:ProductSelectionMode) them explicitly.
  mode:
    type: ProductSelectionMode
    default: Individual
    description: |-
      Specifies in which way the Products are assigned to the ProductSelection.
      Currently, the only way of doing this is to specify each Product individually, either by [including or excluding](ctp:api:type:ProductSelectionMode) them explicitly.
  custom?:
    type: CustomFields
    description: Custom Fields of the ProductSelection.
