#%RAML 1.0 DataType
(package): ProductSelection
(docs-uri):
displayName: ProductSelectionDraft
type: object
properties:
  key?:
    type: string
    description: |-
      User-defined unique identifier for the ProductSelection.
  name:
    type: LocalizedString
    description: |-
      Name of the ProductSelection. Not checked for uniqueness, but distinct names are recommended.
  custom?:
    type: CustomFieldsDraft
    description: Custom Fields of this ProductSelection.
  type?:
    (deprecated): true
    type: ProductSelectionTypeEnum
    default: individual
    description: Type of the Product Selection.
  mode?:
    type: ProductSelectionMode
    default: Individual
    description: Mode of the Product Selection.
