#%RAML 1.0 DataType
(package): ProductSelection
type: object
displayName: ProductVariantExclusion
description: |
  Defines the Product Variants that are excluded from a Product Selection with `IndividualExclusion` [ProductSelectionMode](ctp:api:type:ProductSelectionMode). Product Variants not listed remain available in the Product Selection.
properties:
  skus:
    type: array
    items: string
    description: |
      Non-empty array of SKUs representing Product Variants to be excluded from the Product Selection with `IndividualExclusion` [ProductSelectionMode](ctp:api:type:ProductSelectionMode).
