#%RAML 1.0 DataType
(package): ProductSelection
type: ResourceIdentifier
displayName: ProductSelectionResourceIdentifier
discriminatorValue: product-selection
description: |
  [ResourceIdentifier](ctp:api:type:ResourceIdentifier) to a [ProductSelection](ctp:api:type:ProductSelection). Either `id` or `key` is required. If both are set, an [InvalidJsonInput](/../api/errors#invalidjsoninput) error is returned.
properties:
  id?:
    type: string
    description: |
      Unique identifier of the referenced [ProductSelection](ctp:api:type:ProductSelection). Required if `key` is absent.
  key?:
    type: string
    description: |
      User-defined unique identifier of the referenced [ProductSelection](ctp:api:type:ProductSelection). Required if `id` is absent.
