#%RAML 1.0 DataType
(package): ProductSelection
type: ProductVariantSelection
displayName: ProductVariantSelectionIncludeOnly
discriminatorValue: includeOnly
description: |
  Only Product Variants with explicitly stated SKUs are part of the Product Selection.
properties:
  type:
    type: ProductVariantSelectionTypeEnum
  skus:
    type: array
    items: string
    description: |
      Non-empty array of SKUs representing Product Variants to be included into the Product Selection.
