#%RAML 1.0 DataType
(package): ProductSelection
(docs-uri):
displayName: ProductSelectionDraft
type: object
properties:
  key?:
    type: string
    description: 'User-defined unique identifier for the ProductSelection. You can use `key` besides `ID` to reference the ProductSelection.'
  name:
    type: LocalizedString
    description: 'Name of the Product Selection. Not checked for uniqueness, but distinct names are recommended.'
