#%RAML 1.0 DataType
(package): ProductSelection
(docs-uri): https://docs.commercetools.com/api/projects/product-selections#productselectiontype
type: object
displayName: ProductSelectionType
discriminator: type
properties:
  type:
    type: ProductSelectionTypeEnum
