#%RAML 1.0 DataType
(package): Store
type: object
displayName: StoreUpdateAction
discriminator: action
(java-extends): 'com.commercetools.api.models.ResourceUpdateAction<StoreUpdateAction>'
properties:
  action:
    type: string
