#%RAML 1.0 DataType
(package): Agent
type: GraphQLErrorObject
displayName: GraphQLAgentMissingCountryError
discriminatorValue: MissingCountry
description: |
  Returned by a [/responses](/api/agents/intake-agent#create-a-cart-or-quote-request) request when a shipping country was not provided and could not be inferred from the input.
properties:
  code:
    type: string
