#%RAML 1.0 DataType
(package): Review
(docs-uri): https://docs.commercetools.com/http-api-projects-reviews.html#set-key


type: ReviewUpdateAction
displayName: ReviewSetKeyAction
discriminatorValue: setKey
properties:
    key?:
        type: string
