#%RAML 1.0 DataType
(package): DiscountCode
(docs-uri): https://docs.commercetools.com/http-api-projects-discountCodes.html#discountcode

type: Resource
displayName: DiscountCode
(updateType): DiscountCodeUpdate
properties:
    name?:
        (hasUpdateAction): setName
        type: LocalizedString
    description?:
        (hasUpdateAction): setDescription
        type: LocalizedString
    code:
        type: string
    cartDiscounts:
        (hasUpdateAction): changeCartDiscounts
        (docsActionAnchor): change-cartdiscounts
        type: CartDiscountReference[]
    cartPredicate?:
        (hasUpdateAction): setCartPredicate
        type: string
    isActive:
        (hasUpdateAction): changeIsActive
        (docsActionAnchor): change-isactive
        type: boolean
    references: Reference[]
    maxApplications?:
        (hasUpdateAction): setMaxApplications
        type: number
        format: int64
    maxApplicationsPerCustomer?:
        (hasUpdateAction): setMaxApplicationsPerCustomer
        type: number
        format: int64
    custom?:
        type: CustomFields
    groups:
        (hasUpdateAction): changeGroups
        type: string[]
    validFrom?:
        (hasUpdateAction): setValidFrom
        (docsActionAnchor): set-validfrom
        type: datetime
    validUntil?:
        (hasUpdateAction): setValidUntil
        (docsActionAnchor): set-validuntil
        type: datetime
