#%RAML 1.0 DataType
(package): DiscountCode


type: DiscountCodeUpdateAction
displayName: DiscountCodeChangeCartDiscountsAction
discriminatorValue: changeCartDiscounts
properties:
    cartDiscounts:
        type: Reference[]
