#%RAML 1.0 DataType
(package): DiscountCode


type: DiscountCodeUpdateAction
displayName: DiscountCodeSetDescriptionAction
discriminatorValue: setDescription
properties:
    description?:
        type: LocalizedString
