#%RAML 1.0 Library
usage: Annotations test types.

uses:
  annotations: ../annotation-types/annotations.raml

types:
  AnnotationsTestType:
    properties:
      isBetaType:
        description: Beta property. If true, a "beta" flag should appear beside the type name.
        type: string
        (annotations.beta): true
      isOptionalBetaType?:
        description: Beta property. If true, a "beta" flag should appear beside the type name.
        type: string
        (annotations.beta): true
      isDeprecatedType:
        description: Deprecated property. THIS MUST NOT BE RENDERED AT ALL (=hidden in documentation, it just stays there to keep SDKs backwards compatible).
        type: string
        (annotations.deprecated): true
