#%RAML 1.0 Library
usage: Any test types.

types:
  AnyTestType:
    description: Tests acceptance of JSON blobs. [Test Endpoint URN](ctp:test:endpoint:/{projectKey}/resource/{id}:POST) [Test Overridden Endpoint URN](ctp:test:endpoint:/{projectKey}/resource:GET)
    properties:
      anyTypeExample:
        description: A test of type "any", i.e. any JSON allowed here. To be displayed as "any JSON".
        type: any
