#%RAML 1.0 Library
usage: Object test types for the Object Hierarchy feature.

uses:
  arrays: arrays.raml

types:
  ObjectHierarchyLevel1:
    description: A typical Object type with a non-scalar property.
    properties:
      version:
        type: integer
      objectTypeProperty:
        type: ObjectHierarchyLevel2
        description: Description of the **property.** This is a longer description to test the layout of the property description.
      objectTypeProperty2:
        type: ObjectHierarchyLevel3
        description: Second `lvl` Description of the `property.` This is a longer description to test the layout of the property description. In can also include _markdown_ or  [Links](/views/links)
  ObjectHierarchyLevel2:
    description: A typical Object type with a non-scalar property.
    properties:
      version:
        type: integer
      objectTypeProperty:
        type: ObjectHierarchyLevel3
        description: Description of the **property.** This is a longer description to test the layout of the property description.
  ObjectHierarchyLevel3:
    description: A typical Object type with a non-scalar property.
    properties:
      version:
        type: integer
      objectTypeProperty:
        type: ObjectHierarchyLevel4
        description: Fourth `lvl` Description of the `property.` This is a longer description to test the layout of the property description. In can also include _markdown_ or  [Links](/views/links)
  ObjectHierarchyLevel4:
    description: A typical Object type with a non-scalar property.
    properties:
      version:
        type: integer
      objectTypeProperty:
        type: ObjectHierarchyLevel5
        description: Description of the property. This is a longer description to test the layout of the property description.
  ObjectHierarchyLevel5:
    description: A typical Object type with a non-scalar property.
    properties:
      version:
        type: integer
      objectTypeProperty:
        type: ObjectHierarchyLevel6
        description: Description of the property. This is a longer description to test the layout of the property description.
  ObjectHierarchyLevel6:
    description: A type to create an ObjectTestType. Used for testing the endpoint layout.
    properties:
      objectTypeProperty:
        type: arrays.ArrayTestType
        description: Description of the property. This is a longer description to test the layout of the property description.
