#%RAML 1.0 Library
usage: External link test type.

uses:
  scalars: scalars.raml
  overrides: type-overrides.raml

types:
  LinkToTypeOnSameSite:
    properties:
      LinkToTypeOnSameSite:
        description: A link pointing to a type the same microsite.
        type: scalars.StringTestType
  LinkToTypeOnAnotherSite:
    properties:
      LinkToTypeOnAnotherSite:
        description: A link pointing to a type in another microsite.
        type: overrides.TestTypeOnAnotherMicrosite
  LinkToTypeOnExternalSite:
    properties:
      LinkToTypeOnExternalSite:
        description: A link pointing to a type in an external website.
        type: overrides.TestTypeOnAnExternalWebsite
