#%RAML 1.0 Library
usage: Object test types.

uses:
  arrays: arrays.raml

types:
  ObjectTestType:
    description: A typical Object type with a non-scalar property.
    properties:
      version:
        type: integer
      objectTypeProperty:
        type: arrays.ArrayTestType
    example: !include ../examples/object-test-type.json
  ObjectTestTypeDraft:
    description: A type to create an ObjectTestType. Used for testing the endpoint layout.
    properties:
      objectTypeProperty:
        type: arrays.ArrayTestType
    example: !include ../examples/object-test-type-draft.json
