#%RAML 1.0 Library
usage: Optional property test types.

# Tests "optional"/required fields

types:
  OptionalPropertyTestType:
    description: Example of optional/non-optional properties.
    properties:
      requiredTrueExample:
        type: string
        description: this should be required.
        required: true
      requiredNotSetExample:
        type: string
        description: this should default to required = true.
      requiredFalseExample:
        type: string
        required: false
