#%RAML 1.0 Library
usage: Regex properties test types.

uses:
  objects: objects.raml

types:
  RegexPropertiesTypeObject:
    description: This is a type that can have arbitrary properties as long as they match a certain expression
    type: object
    properties:
      /^[a-z]{2}(-[A-Z]{2})?$/:
        description: Regular expression property with an object type. To be displayed as "Any (type) property matching this regular expression". The Slashes should appear in blue.
        type: objects.ObjectTestType
