#%RAML 1.0 DataType
(annotations.package): PaymentIntents
(annotations.beta): true
type: object
displayName: PaymentIntent
properties:
  actions:
    type: PaymentIntentAction[]
    minItems: 1
    maxItems: 1
    description: |
      Action to execute for the given Payment.
