#%RAML 1.0 DataType
(annotations.package): PaymentIntents
type: object
displayName: PaymentIntentAction
description: |
  Depending on the action specified, Checkout requests the [payment service provider](/payment-connectors-applications#supported-psps-payment-integration-types-and-payment-methods) (PSP) to capture, refund, or cancel the authorization for the given Payment.
properties:
  action:
    type: PaymentIntentOperation
    description: |
      Action to execute for the given [Payment](/../api/projects/payments#payment).
  amount?:
    type: common.Amount
    description: |
      Amount to be captured or refunded.
  merchantReference?:
    type: string
    description: |
      A merchant-defined identifier associated with the Payment to track and reconcile the Payment Intent Action on the merchant's side. For example, an invoice number.
