#%RAML 1.0 DataType
(annotations.package): PaymentIntents
(annotations.beta): true
type: object
displayName: PaymentIntentReverseAction
discriminator: action
discriminatorValue: reversePayment
example: !include ../../../checkout/examples/payments/reversePaymentAction.json
description: |
  Requests to [reverse](/payment-integration-predicates) a [Payment](/../api/projects/payments#payment). Checkout reverses the Payment, and then requests the PSP or gift card management system to proceed with the relevant process to reverse the Payment.
properties:
  action:
    type: string
  merchantReference?:
    type: string
    description: |
      A merchant-defined identifier associated with the [Payment](/../api/projects/payments#payment) to track and reconcile the [Payment Intent Action](ctp:checkout:type:PaymentIntentAction) on the merchant's side. For example, an invoice number.
