#%RAML 1.0 DataType
(package): AttributeGroup
type: object
displayName: AttributeGroupUpdateAction
discriminator: action
(java-extends): 'com.commercetools.api.models.ResourceUpdateAction<AttributeGroupUpdateAction>'
properties:
  action:
    type: string
