#%RAML 1.0 DataType
(package): AttributeGroup
(docs-uri): https://docs.commercetools.com/api/projects/attribute-groups#attributegroupresourceidentifier
type: ResourceIdentifier
displayName: AttributeGroupResourceIdentifier
discriminatorValue: attribute-group
description: |
  [ResourceIdentifier](ctp:api:type:ResourceIdentifier) to an [AttributeGroup](ctp:api:type:AttributeGroup). Either `id` or `key` is required. If both are set, an [InvalidJsonInput](/../api/errors#invalidjsoninput) error is returned.
properties:
  id?:
    type: string
    description: |
      Platform-generated unique identifier of the referenced [AttributeGroup](ctp:api:type:AttributeGroup). Required if `key` is absent.
  key?:
    type: string
    description: |
      User-generated unique identifier of the referenced [AttributeGroup](ctp:api:type:AttributeGroup). Required if `id` is absent.
