#%RAML 1.0 DataType
(package): AttributeGroup
(docs-uri): https://docs.commercetools.com/api/projects/attribute-groups#attributegrouppagedqueryresponse
displayName: AttributeGroupPagedQueryResponse
type: object
(java-extends): 'com.commercetools.api.models.ResourcePagedQueryResponse<AttributeGroup>'
description: |
  [PagedQueryResult](/../api/general-concepts#pagedqueryresult) with `results` containing an array of [AttributeGroup](ctp:api:type:AttributeGroup).
properties:
  limit:
    type: number
    format: int64
    description: |
      Number of results requested in the query request.
  offset:
    type: number
    format: int64
    description: |
      Offset supplied by the client or the server default.
      It is the number of elements skipped, not a page number.
  count:
    type: number
    format: int64
    description: |
      Actual number of results returned.
  total?:
    type: number
    format: int64
    description: |
      Total number of results matching the query.
      This number is an estimation that is not [strongly consistent](/../api/general-concepts#strong-consistency).
      This field is returned by default.
      For improved performance, calculating this field can be deactivated by using the query parameter `withTotal=false`.
      When the results are filtered with a [Query Predicate](/../api/predicates/query), `total` is subject to a [limit](/../api/limits#queries).
  results:
    type: AttributeGroup[]
    description: |
      [AttributeGroups](ctp:api:type:AttributeGroup) matching the query.
