#%RAML 1.0 DataType
(package): AttributeGroup
displayName: AttributeReference
type: object
properties:
  key:
    type: string
    description: |
      The Attribute's `name` as given in its [AttributeDefinition](ctp:api:type:AttributeDefinition).
