#%RAML 1.0 DataType
(package): Me
(docs-uri): https://docs.commercetools.com/api/projects/me-business-units#set-contact-email
type: MyBusinessUnitUpdateAction
displayName: MyBusinessUnitSetContactEmailAction
example: !include ../../../examples/BusinessUnit/BusinessUnitSetContactEmailAction.json
discriminatorValue: setContactEmail
description: |
  Setting the contact email on a [Business Unit](ctp:api:type:BusinessUnit) generates a [BusinessUnitContactEmailSet](ctp:api:type:BusinessUnitContactEmailSetMessage) Message.
properties:
  contactEmail?:
    type: string
    description: |
      Email to set.
      If `contactEmail` is absent or `null`, the existing contact email, if any, will be removed.
