#%RAML 1.0 DataType
(package): Me
(docs-uri): https://docs.commercetools.com/api/projects/me-business-units#remove-billing-address-id
type: MyBusinessUnitUpdateAction
displayName: MyBusinessUnitRemoveBillingAddressIdAction
example: !include ../../../examples/BusinessUnit/BusinessUnitRemoveBillingAddressIdAction.json
discriminatorValue: removeBillingAddressId
description: |
  Removing a billing address from a [Business Unit](ctp:api:type:BusinessUnit) generates a [BusinessUnitBillingAddressRemoved](ctp:api:type:BusinessUnitBillingAddressRemovedMessage) Message.
properties:
  addressId?:
    type: string
    description: |
      ID of the billing address to be removed. Either `addressId` or `addressKey` is required.
  addressKey?:
    type: string
    description: |
      Key of the billing address to be removed. Either `addressId` or `addressKey` is required.
