#%RAML 1.0 DataType
(package): BusinessUnit
(docs-uri): https://docs.commercetools.com/api/projects/me-business-units#change-parent-unit
type: MyBusinessUnitUpdateAction
displayName: MyBusinessUnitChangeParentUnitAction
example: !include ../../../examples/BusinessUnit/BusinessUnitChangeParentUnitAction.json
discriminatorValue: changeParentUnit
description: |
  Changing the parent of a [Business Unit](ctp:api:type:BusinessUnit) generates a [BusinessUnitParentUnitChanged](ctp:api:type:BusinessUnitParentUnitChangedMessage) Message. The user must be an Associate with the `Admin` role in the new parent unit.
properties:
  parentUnit:
    type: BusinessUnitResourceIdentifier
    description: |
      New parent unit of the [Business Unit](ctp:api:type:BusinessUnit).
