#%RAML 1.0 DataType
(package): Me
(docs-uri): https://docs.commercetools.com/http-api-projects-me-carts#add-lineitem

type: MyCartUpdateAction
displayName: MyCartAddLineItemAction
discriminatorValue: addLineItem

properties:
  custom?:
    type: CustomFieldsDraft
  distributionChannel?:
    type: ChannelResourceIdentifier
  externalTaxRate?:
    type: ExternalTaxRateDraft
  productId?:
    type: string
  variantId?:
    type: number
    format: int64
  sku?:
    type: string
  quantity?:
    type: number
    format: int64
  supplyChannel?:
    type: ChannelResourceIdentifier
  externalPrice?:
    type: Money
  externalTotalPrice?:
    type: ExternalLineItemTotalPrice
  shippingDetails?:
    type: ItemShippingDetailsDraft
  addedAt?:
    type: datetime
