#%RAML 1.0 DataType
(package): Me
type: MyCartUpdateAction
displayName: MyCartSetCustomLineItemRecurrenceInfoAction
discriminatorValue: setCustomLineItemRecurrenceInfo
example: !include ../../../examples/Cart/CartSetCustomLineItemRecurrenceInfoAction.json
description: |
  Sets the recurrence information on the [CustomLineItem](ctp:api:type:CustomLineItem).
  If the Cart is already associated with a Recurring Order, this action will fail.
properties:
  customLineItemId?:
    type: string
    description: |
      `id` of the [CustomLineItem](ctp:api:type:CustomLineItem) to update. Either `customLineItemId` or `customLineItemKey` is required.
  customLineItemKey?:
    type: string
    description: |
      `key` of the [CustomLineItem](ctp:api:type:CustomLineItem) to update. Either `customLineItemId` or `customLineItemKey` is required.
  recurrenceInfo?:
    type: CustomLineItemRecurrenceInfoDraft
    description: |
      Value to set.
      If empty, any existing value will be removed.
