#%RAML 1.0 DataType
(package): Me
(docs-uri): https://docs.commercetools.com/http-api-projects-me-carts#update-itemshippingaddress

type: MyCartUpdateAction
displayName: MyCartUpdateItemShippingAddressAction
discriminatorValue: updateItemShippingAddress

properties:
  address:
    type: BaseAddress
