#%RAML 1.0 DataType
(package): Me
type: MyCartUpdateAction
displayName: MyCartSetShippingAddressAction
discriminatorValue: setShippingAddress
example: !include ../../../examples/Cart/CartSetShippingAddressAction.json
description: |
  Setting the shipping address also sets the [TaxRate](ctp:api:type:TaxRate) of Line Items and calculates the [TaxedPrice](ctp:api:type:TaxedPrice).

  If a matching price cannot be found for the given shipping address during [Line Item price selection](/../api/pricing-and-discounts-overview#line-item-price-selection),
  a [MissingTaxRateForCountry](ctp:api:type:MissingTaxRateForCountryError) error is returned.

  If you want to allow shipping to states inside a country that are not explicitly covered by a TaxRate,
  set the `countryTaxRateFallbackEnabled` field to `true` in the [CartsConfiguration](ctp:api:type:CartsConfiguration) by using
  the [Change CountryTaxRateFallbackEnabled](ctp:api:type:ProjectChangeCountryTaxRateFallbackEnabledAction) update action.
properties:
  address?:
    type: AddressDraft
    description: |
      Value to set.
      If not set, the shipping address is unset, and the `taxedPrice` and `taxRate` are unset in all Line Items.
