#%RAML 1.0 DataType
(package): Me
type: MyCustomerUpdateAction
displayName: MyCustomerRemoveBillingAddressIdAction
discriminatorValue: removeBillingAddressId
example: !include ../../../examples/Customer/CustomerRemoveBillingAddressIdAction.json
description: |
  Removes an existing billing address from `billingAddressesIds`.
  If the billing address is the default billing address, the `defaultBillingAddressId` is unset. Either `addressId` or `addressKey` is required.
properties:
  addressId?:
    type: string
    description: |
      `id` of the [Address](ctp:api:type:Address) to remove from `billingAddressesIds`.
  addressKey?:
    type: string
    description: |
      `key` of the [Address](ctp:api:type:Address) to remove from `billingAddressesIds`.
