#%RAML 1.0 DataType
(package): Me
type: MyCustomerUpdateAction
displayName: MyCustomerSetDefaultBillingAddressAction
discriminatorValue: setDefaultBillingAddress
example: !include ../../../examples/Customer/CustomerSetDefaultBillingAddressAction.json
description: |
  Sets the default billing address from `addresses`.
  If the address is not currently a billing address, it is added to `billingAddressIds`. Either `addressId` or `addressKey` is required.
properties:
  addressId?:
    type: string
    description: |
      `id` of the [Address](ctp:api:type:Address) to become the default billing address.
  addressKey?:
    type: string
    description: |
      `key` of the [Address](ctp:api:type:Address) to become the default billing address.
