#%RAML 1.0 DataType
(package): Me
(docs-uri): https://docs.commercetools.com/api/projects/me-profile#set-salutation
type: MyCustomerUpdateAction
displayName: MyCustomerSetSalutationAction
discriminatorValue: setSalutation
example: !include ../../../examples/Customer/CustomerSetSalutationAction.json
properties:
  salutation?:
    type: string
    description: |
      Value to set.
      If empty, any existing value is removed.
