#%RAML 1.0 DataType
(package): Me
(docs-uri): https://docs.commercetools.com/http-api-projects-me-profile.html#change-email

type: MyCustomerUpdateAction
displayName: MyCustomerChangeEmailAction
discriminatorValue: changeEmail

properties:
  email:
    type: string
