#%RAML 1.0 DataType
(package): Me
type: MyCustomerUpdateAction
displayName: MyCustomerSetCustomTypeAction
example: !include ../../../examples/Customer/CustomerSetCustomTypeAction.json
discriminatorValue: setCustomType
description: |
  Adding or updating a Custom Type on a Customer generates the [CustomerCustomTypeSet](ctp:api:type:CustomerCustomTypeSetMessage) Message, removing one generates the [CustomerCustomTypeRemoved](ctp:api:type:CustomerCustomTypeRemovedMessage) Message.
properties:
  type?:
    type: TypeResourceIdentifier
    description: |
      Defines the [Type](ctp:api:type:Type) that extends the MyCustomer with [Custom Fields](ctp:api:type:CustomFields).
      If absent, any existing Type and Custom Fields are removed from the MyCustomer.
  fields?:
    type: FieldContainer
    description: |
      Object containing the [Custom Fields](ctp:api:type:CustomFields) fields for the MyCustomer.

      Required if at least one Custom Field is defined as required in the `fieldDefinitions` of the referenced [Type](ctp:api:type:Type).
