#%RAML 1.0 DataType
(package): Me
(docs-uri): https://docs.commercetools.com/api/projects/me-profile#set-default-shipping-address
type: MyCustomerUpdateAction
displayName: MyCustomerSetDefaultShippingAddressAction
discriminatorValue: setDefaultShippingAddress
example: !include ../../../examples/Customer/CustomerSetDefaultShippingAddressAction.json
description: |
  Sets the default shipping address from `addresses`.
  If the address is not currently a shipping address, it is added to `shippingAddressIds`. Either `addressId` or `addressKey` is required.
properties:
  addressId?:
    type: string
    description: |
      `id` of the [Address](ctp:api:type:Address) to become the default shipping address.
  addressKey?:
    type: string
    description: |
      `key` of the [Address](ctp:api:type:Address) to become the default shipping address.
