#%RAML 1.0 DataType
(package): Me
(docs-uri): https://docs.commercetools.com/http-api-projects-me-profile.html#change-address

type: MyCustomerUpdateAction
displayName: MyCustomerChangeAddressAction
discriminatorValue: changeAddress

properties:
  addressId?:
    type: string
  addressKey?:
    type: string
  address:
    type: BaseAddress
