#%RAML 1.0 DataType
(package): Me
type: MyCustomerUpdateAction
displayName: MyCustomerSetCustomTypeAction
example: !include ../../../examples/Customer/CustomerSetCustomTypeAction.json
discriminatorValue: setCustomType
description: |
  Adding or updating a Custom Type on a Customer generates the [CustomerCustomTypeSet](ctp:api:type:CustomerCustomTypeSetMessage) Message, removing one generates the [CustomerCustomTypeRemoved](ctp:api:type:CustomerCustomTypeRemovedMessage) Message.
properties:
  type?:
    type: TypeResourceIdentifier
    description: |
      Defines the [Type](ctp:api:type:Type) that extends the MyCustomer with [Custom Fields](/../api/projects/custom-fields).
      If absent, any existing Type and Custom Fields are removed from the MyCustomer.
  fields?:
    type: FieldContainer
    description: |
      Sets the [Custom Fields](/../api/projects/custom-fields) fields for the MyCustomer.
