#%RAML 1.0 DataType
(package): Me
type: MyPaymentUpdateAction
displayName: MyPaymentSetMethodInfoCustomTypeAction
discriminatorValue: setMethodInfoCustomType
(beta): true
example: !include ../../../examples/Payment/MyPaymentSetMethodInfoCustomTypeAction.json
description: |
  Adding or updating a Custom Type on a PaymentMethodInfo generates the [PaymentMethodInfoCustomTypeSet](ctp:api:type:PaymentMethodInfoCustomTypeSetMessage) Message, removing one generates the [PaymentMethodInfoCustomTypeRemoved](ctp:api:type:PaymentMethodInfoCustomTypeRemovedMessage) Message.
properties:
  type?:
    type: TypeResourceIdentifier
    description: |
      Defines the [Type](ctp:api:type:Type) that extends the `paymentMethodInfo` with [Custom Fields](/../api/projects/custom-fields).
  fields?:
    type: FieldContainer
    description: |
      Sets the [Custom Fields](/../api/projects/custom-fields) fields for the `paymentMethodInfo`.
