#%RAML 1.0 DataType
(package): Me
(docs-uri): https://docs.commercetools.com/api/projects/me-quotes#change-my-quote-state
type: MyQuoteUpdateAction
displayName: MyQuoteChangeMyQuoteStateAction
discriminatorValue: changeMyQuoteState
description: When accepting, declining, or renegotiating [B2B Quotes](/../api/associates-overview#b2b-resources), the Customer must have the `AcceptMyQuotes`, `DeclineMyQuotes`, or `RenegotiateMyQuotes` [Permission](ctp:api:type:Permission) respectively.
example: !include ../../../examples/my-quote-change-my-quote-state.example.json
properties:
  quoteState:
    type: MyQuoteState
    description: New state to be set for the Quote.
