#%RAML 1.0 DataType
(package): Me
type: MyQuoteRequestUpdateAction
displayName: MyQuoteRequestCancelAction
discriminatorValue: cancelQuoteRequest
description: |
  Transitions the `quoteRequestState` of the Quote Request to `Cancelled`. Can only be used when the Quote Request is in state `Submitted`.
