#%RAML 1.0 DataType
(package): Me
type: MyQuoteUpdateAction
displayName: MyQuoteChangeMyQuoteStateAction
discriminatorValue: changeMyQuoteState
description: When accepting, declining, or renegotiating [B2B Quotes](/../api/associates-overview#b2b-resources), the Customer must have the `AcceptMyQuotes`, `DeclineMyQuotes`, or `RenegotiateMyQuotes` [Permission](ctp:api:type:Permission), respectively. If the required [Permission](/projects/associate-roles#permission) is missing, an [AssociateMissingPermission](/errors#associatemissingpermission) error is returned.
example: !include ../../../examples/my-quote-change-my-quote-state.example.json
properties:
  quoteState:
    type: MyQuoteState
    description: New state to be set for the Quote.
