#%RAML 1.0 DataType
(package): Me
type: MyShoppingListUpdateAction
displayName: MyShoppingListSetLineItemCustomTypeAction
discriminatorValue: setLineItemCustomType
example: !include ../../../examples/ShoppingList/ShoppingListSetLineItemCustomTypeAction.json
properties:
  lineItemId:
    type: string
    description: |
      Unique identifier of an existing [ShoppingListLineItem](ctp:api:type:ShoppingListLineItem) in the [ShoppingList](ctp:api:type:ShoppingList).
  type?:
    type: TypeResourceIdentifier
    description: |
      Defines the [Type](ctp:api:type:Type) that extends the ShoppingListLineItem with [Custom Fields](ctp:api:type:CustomFields).
      If absent, any existing Type and Custom Fields are removed from the ShoppingListLineItem.
  fields?:
    type: FieldContainer
    description: |
      Object containing the [Custom Fields](ctp:api:type:CustomFields) fields for the ShoppingListLineItem.

      Required if at least one Custom Field is defined as required in the `fieldDefinitions` of the referenced [Type](ctp:api:type:Type).
