#%RAML 1.0 DataType
(package): Me
(docs-uri): https://docs.commercetools.com/api/projects/me-shoppingLists#set-shoppinglistlineitem-custom-type
type: MyShoppingListUpdateAction
displayName: MyShoppingListSetLineItemCustomTypeAction
discriminatorValue: setLineItemCustomType
example: !include ../../../examples/ShoppingList/ShoppingListSetLineItemCustomTypeAction.json
properties:
  lineItemId:
    type: string
    description: |
      Unique identifier of an existing [ShoppingListLineItem](ctp:api:type:ShoppingListLineItem) in the [ShoppingList](ctp:api:type:ShoppingList).
  type?:
    type: TypeResourceIdentifier
    description: |
      Defines the [Type](ctp:api:type:Type) that extends the ShoppingListLineItem with [Custom Fields](/../api/projects/custom-fields).
      If absent, any existing Type and Custom Fields are removed from the ShoppingListLineItem.
  fields?:
    type: FieldContainer
    description: |
      Sets the [Custom Fields](/../api/projects/custom-fields) fields for the ShoppingListLineItem.
