#%RAML 1.0 DataType
(package): Me
type: MyShoppingListUpdateAction
displayName: MyShoppingListChangeTextLineItemsOrderAction
discriminatorValue: changeTextLineItemsOrder
example: !include ../../../examples/ShoppingList/ShoppingListChangeTextLineItemsOrderAction.json
properties:
  textLineItemOrder:
    type: string[]
    description: |
      All existing [TextLineItem](ctp:api:type:TextLineItem) `id`s in the desired new order.
