#%RAML 1.0 DataType
(package): Me
(docs-uri): https://docs.commercetools.com/http-api-projects-me-shoppingLists#set-lineitem-custom-type

type: MyShoppingListUpdateAction
displayName: MyShoppingListSetLineItemCustomTypeAction
discriminatorValue: setLineItemCustomType

properties:
  lineItemId:
    type: string
  type?:
    type: TypeResourceIdentifier
  fields?:
    type: FieldContainer
