#%RAML 1.0 DataType
(package): Me
(docs-uri): https://docs.commercetools.com/api/projects/me-shoppingLists#change-name
type: MyShoppingListUpdateAction
displayName: MyShoppingListChangeNameAction
discriminatorValue: changeName
example: !include ../../../examples/ShoppingList/ShoppingListChangeNameAction.json
properties:
  name:
    type: LocalizedString
    description: |
      New value to set. Must not be empty.
