#%RAML 1.0 DataType
(package): Me

type: MyShoppingListUpdateAction
displayName: MyShoppingListAddLineItemAction
discriminatorValue: addLineItem
example: !include ../../../examples/ShoppingList/ShoppingListAddLineItemAction.json
properties:
  key?:
    type: string
    description: User-defined identifier of the ShoppingListLineItem. Must be unique per [ShoppingList](ctp:api:type:ShoppingList).
    pattern: ^[a-zA-Z0-9_-]
    minLength: 2
    maxLength: 256
  sku?:
    type: string
    description: |
      `sku` of the [ProductVariant](ctp:api:type:ProductVariant).
  productId?:
    type: string
    description: |
      Unique identifier of a [Product](ctp:api:type:Product).
  variantId?:
    type: number
    format: int64
    description: |
      `id` of the [ProductVariant](ctp:api:type:ProductVariant). If not set, the ShoppingListLineItem refers to the Master Variant.
  quantity?:
    type: number
    format: int64
    description: |
      Number of Products in the [ShoppingListLineItem](ctp:api:type:ShoppingListLineItem).
  addedAt?:
    type: datetime
    description: |
      Date and time the TextLineItem is added to the [ShoppingList](ctp:api:type:ShoppingList). If not set, the current date and time (UTC) is used.
  custom?:
    type: CustomFieldsDraft
    description: |
      Custom Fields defined for the ShoppingListLineItem.
