#%RAML 1.0 DataType
(package): Me
(docs-uri): https://docs.commercetools.com/api/projects/me-shoppingLists#add-textlineitem

type: MyShoppingListUpdateAction
displayName: MyShoppingListAddTextLineItemAction
discriminatorValue: addTextLineItem
example: !include ../../../examples/ShoppingList/ShoppingListAddTextLineItemAction.json
properties:
  name:
    type: LocalizedString
    description: |
      Name of the [TextLineItem](ctp:api:type:TextLineItem).
  description?:
    type: LocalizedString
    description: |
      Description of the TextLineItem.
  quantity?:
    type: number
    format: int64
    description: |
      Number of entries in the TextLineItem.
  addedAt?:
    type: datetime
    description: |
      Date and time the TextLineItem is added to the [ShoppingList](ctp:api:type:ShoppingList). If not set, the current date and time (UTC) is used.
  custom?:
    type: CustomFieldsDraft
    description: |
      Custom Fields defined for the TextLineItem.
