#%RAML 1.0 DataType
(package): CartDiscount
type: CartDiscountUpdateAction
displayName: CartDiscountChangeValueAction
discriminatorValue: changeValue
description: |
  Changes the [CartDiscountValue](ctp:api:type:CartDiscountValue) for [relative](ctp:api:type:CartDiscountValueRelative), [absolute](ctp:api:type:CartDiscountValueAbsolute) and [fixed price](ctp:api:type:CartDiscountValueFixed) CartDiscounts.
  Changing to [Gift Line Item](ctp:api:type:CartDiscountValueGiftLineItem) is not supported.
example: !include ../../../examples/CartDiscount/CartDiscountChangeValueAction.json
properties:
  value:
    type: CartDiscountValueDraft
    description: |
      New value to set.
      When trying to set a [CartDiscountValueGiftLineItemDraft](ctp:api:type:CartDiscountValueGiftLineItemDraft) an [InvalidInput](ctp:api:type:InvalidInputError) error is returned.
