#%RAML 1.0 DataType
(package): CartDiscount
type: CartDiscountUpdateAction
displayName: CartDiscountSetCustomTypeAction
discriminatorValue: setCustomType
example: !include ../../../examples/CartDiscount/CartDiscountSetCustomTypeAction.json
properties:
  type?:
    type: TypeResourceIdentifier
    description: |
      Defines the [Type](ctp:api:type:Type) that extends the CartDiscount with [Custom Fields](/../api/projects/custom-fields).
      If absent, any existing Type and Custom Fields are removed from the CartDiscount.
  fields?:
    type: FieldContainer
    description: |
      Sets the [Custom Fields](/../api/projects/custom-fields) fields for the CartDiscount.
