#%RAML 1.0 DataType
(package): CartDiscount
type: CartDiscountUpdateAction
displayName: CartDiscountSetDiscountGroupAction
discriminatorValue: setDiscountGroup
example: !include ../../../examples/CartDiscount/CartDiscountSetDiscountGroupAction.json
(beta): true
properties:
  discountGroup?:
    type: DiscountGroupResourceIdentifier
    description: |
      Reference to a DiscountGroup that the Cart Discount must belong to.
      If empty, any existing value will be removed.
  sortOrder?:
    type: string
    description: |
      New value to set (between `0` and `1`) that determines the order in which the CartDiscounts are applied; a CartDiscount with a higher value is prioritized.

      Required if `discountGroup` is absent. If `discountGroup` is set, the CartDiscount will use the sort order of the DiscountGroup.
