#%RAML 1.0 DataType
(package): CartDiscount
(beta): true
(docs-uri): https://docs.commercetools.com/api/projects/cartDiscounts#add-store
type: CartDiscountUpdateAction
displayName: CartDiscountAddStoreAction
discriminatorValue: addStore
example: !include ../../../examples/CartDiscount/CartDiscountAddStoreAction.json
description: |
  If a referenced Store does not exist, a [ReferencedResourceNotFound](ctp:api:type:ReferencedResourceNotFoundError) error is returned.
properties:
  store:
    type: StoreResourceIdentifier
    description: |
      [Store](ctp:api:type:Store) to add.

      A failed update can return the following errors:

      - If the referenced Stores exceed the [limit](/../api/limits#cart-discounts-stores), a [MaxStoreReferencesReached](ctp:api:type:MaxStoreReferencesReachedError) error is returned.
      - If the referenced Stores exceed the [limit](/../api/limits#cart-discounts) for Cart Discounts that do not require a Discount Code, a [StoreCartDiscountsLimitReached](ctp:api:type:StoreCartDiscountsLimitReachedError) error is returned.
