#%RAML 1.0 DataType
(package): Category
(docs-uri): https://docs.commercetools.com/http-api-projects-categories.html#change-orderhint
type: CategoryUpdateAction
displayName: CategoryChangeOrderHintAction
discriminatorValue: changeOrderHint
(postman-example): !include ../../../examples/Category/CategoryChangeOrderHintAction.json
properties:
  orderHint:
    type: string
    description: ''
