#%RAML 1.0 DataType
(package): Category
(docs-uri): https://docs.commercetools.com/api/projects/categories#remove-asset
type: CategoryUpdateAction
displayName: CategoryRemoveAssetAction
discriminatorValue: removeAsset
example: !include ../../../examples/Category/CategoryRemoveAssetAction.json
properties:
  assetId?:
    type: string
    description: |
      Value to remove. Either `assetId` or `assetKey` is required.
  assetKey?:
    type: string
    description: |
      Value to remove. Either `assetId` or `assetKey` is required.
