#%RAML 1.0 DataType
(package): Category
type: CategoryUpdateAction
displayName: CategorySetDescriptionAction
discriminatorValue: setDescription
example: !include ../../../examples/Category/CategorySetDescriptionAction.json
properties:
  description?:
    type: LocalizedString
    description: |
      Value to set. If empty, any existing value will be removed.
