#%RAML 1.0 DataType
(package): Category
type: CategoryUpdateAction
displayName: CategoryChangeOrderHintAction
discriminatorValue: changeOrderHint
example: !include ../../../examples/Category/CategoryChangeOrderHintAction.json
properties:
  orderHint:
    type: string
    description: |
      New value to set. Must be a decimal value between 0 and 1. When sorted in ascending order, Categories with a lower `orderHint` appear before those with a higher value (for example, `0.05` before `0.07`).
