#%RAML 1.0 DataType
(package): Category
(docs-uri): https://docs.commercetools.com/http-api-projects-categories.html#set-custom-type
type: CategoryUpdateAction
displayName: CategorySetCustomTypeAction
discriminatorValue: setCustomType
(postman-example): !include ../../../examples/Category/CategorySetCustomTypeAction.json
properties:
  type?:
    type: TypeResourceIdentifier
    description: If absent, the custom type and any existing CustomFields are removed.
  fields?:
    type: FieldContainer
    description: |-
      A valid JSON object, based on the FieldDefinitions of the Type. Sets the custom fields to this value.
