#%RAML 1.0 DataType
(package): Category
type: CategoryUpdateAction
displayName: CategoryRemoveAssetAction
discriminatorValue: removeAsset
example: !include ../../../examples/Category/CategoryRemoveAssetAction.json
properties:
  assetId?:
    type: string
    description: |
      Value to remove. Either `assetId` or `assetKey` is required.
  assetKey?:
    type: string
    description: |
      Value to remove. Either `assetId` or `assetKey` is required.
