#%RAML 1.0 DataType
(package): Category
type: CategoryUpdateAction
displayName: CategoryChangeAssetNameAction
discriminatorValue: changeAssetName
example: !include ../../../examples/Category/CategoryChangeAssetNameAction.json
properties:
  assetId?:
    type: string
    description: |
      New value to set. Either `assetId` or `assetKey` is required.
  assetKey?:
    type: string
    description: |
      New value to set. Either `assetId` or `assetKey` is required.
  name:
    type: LocalizedString
    description: |
      New value to set. Must not be empty.
