#%RAML 1.0 DataType
(package): Category
(docs-uri): https://docs.commercetools.com/api/projects/categories#set-asset-description
type: CategoryUpdateAction
displayName: CategorySetAssetDescriptionAction
discriminatorValue: setAssetDescription
example: !include ../../../examples/Category/CategorySetAssetDescriptionAction.json
properties:
  assetId?:
    type: string
    description: |
      New value to set. Either `assetId` or `assetKey` is required.
  assetKey?:
    type: string
    description: |
      New value to set. Either `assetId` or `assetKey` is required.
  description?:
    type: LocalizedString
    description: |
      Value to set. If empty, any existing value will be removed.
