#%RAML 1.0 DataType
(package): Category
type: CategoryUpdateAction
displayName: CategorySetMetaTitleAction
discriminatorValue: setMetaTitle
example: !include ../../../examples/Category/CategorySetMetaTitleAction.json
properties:
  metaTitle?:
    type: LocalizedString
    description: |
      Value to set.
