#%RAML 1.0 DataType
(package): Category
(docs-uri): https://docs.commercetools.com/http-api-projects-categories.html#change-slug
type: CategoryUpdateAction
displayName: CategoryChangeSlugAction
discriminatorValue: changeSlug
(postman-example): !include ../../../examples/Category/CategoryChangeSlugAction.json
properties:
  slug:
    type: LocalizedString
    description: |-
      Allowed are alphabetic, numeric, underscore (&#95;) and hyphen (&#45;) characters.
      Maximum size is {{ site.data.api-limits.slugLength }}.
