#%RAML 1.0 DataType
(package): Category
type: CategoryUpdateAction
displayName: CategorySetAssetCustomTypeAction
discriminatorValue: setAssetCustomType
example: !include ../../../examples/Category/CategorySetAssetCustomTypeAction.json
properties:
  assetId?:
    type: string
    description: |
      New value to set. Either `assetId` or `assetKey` is required.
  assetKey?:
    type: string
    description: |
      New value to set. Either `assetId` or `assetKey` is required.
  type?:
    type: TypeResourceIdentifier
    description: |
      Defines the [Type](ctp:api:type:Type) that extends the Asset with [Custom Fields](ctp:api:type:CustomFields).
      If absent, any existing Type and Custom Fields are removed from the Asset.
  fields?:
    type: FieldContainer
    description: |
      Object containing the [Custom Fields](ctp:api:type:CustomFields) fields for the Asset.

      Required if at least one Custom Field is defined as required in the `fieldDefinitions` of the referenced [Type](ctp:api:type:Type).
