#%RAML 1.0 DataType
(package): Category
(docs-uri): https://docs.commercetools.com/http-api-projects-categories.html#add-asset
type: CategoryUpdateAction
displayName: CategoryAddAssetAction
discriminatorValue: addAsset
(postman-example): !include ../../../examples/Category/CategoryAddAssetAction.json
properties:
  asset:
    type: AssetDraft
    description: ''
  position?:
    type: number
    format: int32
    description:
      When specified, the value might be `0` and should be lower than the total
      of the assets list.
