#%RAML 1.0 DataType
(package): Error
type: ErrorObject
displayName: ConcurrentModificationError
discriminatorValue: ConcurrentModification
description: |
  Returned when the request conflicts with the current state of the involved resources. Typically, the request attempts to modify a resource that is out of date (that is modified by another client since it was last retrieved).
  The client application should resolve the conflict (with or without involving the end user) before retrying the request.
properties:
  code:
    type: string
  message:
    type: string
    description: |
      `"Object $resourceId has a different version than expected. Expected: $expectedVersion - Actual: $currentVersion."`
  currentVersion?:
    type: number
    format: int64
    description: |
      Current version of the resource.
