#%RAML 1.0 DataType
(package): Error
type: ErrorObject
displayName: DuplicateVariantValuesError
discriminatorValue: DuplicateVariantValues
description: |
  Returned when a [Product Variant](ctp:api:type:ProductVariant) value conflicts with an existing one during an [Update Product](/../api/projects/products#update-product) request.
properties:
  code:
    type: string
  message:
    type: string
    description: |
      `"A duplicate combination of the variant values (sku, key, images, prices, attributes) exists."`
  variantValues:
    type: VariantValues
    description: |
      Every Product Variant must have a distinct combination of SKU, prices, and custom Attribute values.
