#%RAML 1.0 DataType
(package): Error
type: ErrorObject
displayName: DuplicatePriceKeyError
discriminatorValue: DuplicatePriceKey
description: |
  Returned when a Price key conflicts with an existing key.

  Keys of Embedded Prices must be unique per ProductVariant.
properties:
  code:
    type: string
  message:
    type: string
    description: |
      `"Duplicate price key: $priceKey. The price key must be unique per variant."`
  conflictingPrice:
    type: Price
    description: |
      Conflicting Embedded Price.
