#%RAML 1.0 DataType
(package): Error
type: ErrorObject
displayName: EnumKeyDoesNotExistError
discriminatorValue: EnumKeyDoesNotExist
properties:
  conflictingEnumKey:
    type: string
  conflictingAttributeName:
    type: string
