#%RAML 1.0 DataType
(package): Error
type: object
displayName: ErrorResponse
description: |
  Base representation of an error response containing common fields to all errors.
example: !include /../../examples/Error/ErrorResponse.json
properties:
  statusCode:
    type: integer
    description: |
      HTTP status code corresponding to the error.
  message:
    type: string
    description: |
      First error message in the `errors` array.
  errors?:
    type: array
    items: ErrorObject
    description: |
      Errors returned for a request.

      A single error response can contain multiple errors if the errors are related to the same HTTP status code such as `400`.
