#%RAML 1.0 DataType
(package): Error
type: object
displayName: ErrorByExtension
properties:
  id:
    type: string
    description: Unique identifier of the Extension.
  key?:
    type: string
    description: User-defined unique identifier of the Extension.
