#%RAML 1.0 DataType
(package): Error
type: ErrorObject
displayName: ExpiredCustomerEmailTokenError
discriminatorValue: ExpiredCustomerEmailToken
description: |
  Returned when the provided email token of the Customer has expired.

  The error is returned as a failed response to:

  - [Get Customer by email token](ctp:api:endpoint:/{projectKey}/customers/email-token={emailToken}:GET) and [Get Customer in Store by email token](ctp:api:endpoint:/{projectKey}/in-store/key={storeKey}/customers/email-token={emailToken}:GET) requests
  - [Verify email of Customer](ctp:api:endpoint:/{projectKey}/customers/email/confirm:POST) and [Verify email of Customer in Store](ctp:api:endpoint:/{projectKey}/in-store/key={storeKey}/customers/email/confirm:POST) requests
properties:
  code:
    type: string
  message:
    type: string
    description: |
      `"The given email token has expired."`
