#%RAML 1.0 DataType
(package): Error
type: ErrorObject
displayName: ExternalOAuthFailedError
discriminatorValue: ExternalOAuthFailed
description: |
  Returned when an [external OAuth Introspection endpoint](/../api/authorization#request-an-access-token-using-an-external-oauth-server) does not return a response within the [time limit](/../api/authorization#time-limits), or the response isn't compliant with [RFC 7662](https://www.rfc-editor.org/rfc/rfc7662.html) (for example, an HTTP status code like `500`).
properties:
  code:
    type: string
  message:
    type: string
    description: |
      Plain text description detailing the external OAuth error. For example, `"External OAuth did not respond in time."`.
