#%RAML 1.0 DataType
(package): Error
type: ErrorObject
displayName: ExtensionPredicateEvaluationFailedError
discriminatorValue: ExtensionPredicateEvaluationFailed
example: !include ../../examples/Error/ExtensionPredicateEvaluationFailed.json
description: |
  Returned when the predicate defined in the [ExtensionTrigger](ctp:api:type:ExtensionTrigger) could not be evaluated due to a missing field.
properties:
  code:
    type: string
  message:
    type: string
    description: |
      `"The compared field $fieldName is not present."`
  errorByExtension:
    type: ErrorByExtension
    description: |
      Details about the API Extension that was involved in the error.
