#%RAML 1.0 DataType
(package): Error
type: ErrorObject
displayName: InvalidFieldError
discriminatorValue: InvalidField
properties:
  field:
    type: string
  invalidValue:
    type: any
  allowedValues?:
    type: array
    items: any
