#%RAML 1.0 DataType
(package): Error
type: ErrorObject
displayName: InvalidItemShippingDetailsError
discriminatorValue: InvalidItemShippingDetails
description: |
  Returned when Line Item or Custom Line Item quantities set under [ItemShippingDetails](ctp:api:type:ItemShippingDetails) do not match the sum of the quantities in their respective shipping details.

  The error is returned as a failed response to the [Create Order from Cart](ctp:api:endpoint:/{projectKey}/orders:POST) and [Create Order in Store from Cart](ctp:api:endpoint:/{projectKey}/in-store/orders:POST) requests.
properties:
  code:
    type: string
  message:
    type: string
    description: |
      `"Inconsistent shipping details for $subject with ID $itemId. $subject quantity is $itemQuantity and shippingTargets quantity sum is $quantitySum."`
  subject:
    type: string
    description: |
      `"LineItem"` or `"CustomLineItem"`
  itemId:
    type: string
    description: |
      Unique identifier of the Line Item or Custom Line Item.
