#%RAML 1.0 DataType
(package): Error
type: ErrorObject
displayName: MissingRoleOnChannelError
discriminatorValue: MissingRoleOnChannel
properties:
  channel?:
    type: ChannelResourceIdentifier
  missingRole:
    type: ChannelRoleEnum
