#%RAML 1.0 DataType
(package): Error
type: ErrorObject
displayName: NotEnabledError
discriminatorValue: NotEnabled
description: |
  Returned when the [Project-specific category recommendations feature](/../api/projects/categoryRecommendations#project-specific-category-recommendations) is not enabled for the Project.
properties:
  code:
    type: string
  message:
    type: string
    description: |
      `"The category recommendations API is not yet enabled for your project."`
