#%RAML 1.0 DataType
(package): Error
type: ErrorObject
displayName: ObjectNotFoundError
discriminatorValue: ObjectNotFound
description: |
  Returned if the requested resource was not found or the Product Search index is [inactive](/../api/projects/product-search#activate-the-product-search-api).
properties:
  code:
    type: string
  message:
    type: string
    description: |
      `"A $resourceType with identifier $id was unexpectedly not found."` or

      `"No index found for project"`
