#%RAML 1.0 DataType
(package): Error
type: ErrorObject
displayName: OverlappingStandalonePriceValidityError
discriminatorValue: OverlappingStandalonePriceValidity
properties:
  conflictingStandalonePrice:
    type: StandalonePriceReference
  sku:
    type: string
  currency:
    type: string
  country?:
    type: string
  customerGroup?:
    type: CustomerGroupResourceIdentifier
  channel?:
    type: ChannelResourceIdentifier
  validFrom?:
    type: datetime
  validUntil?:
    type: datetime
  conflictingValidFrom?:
    type: datetime
  conflictingValidUntil?:
    type: datetime
