#%RAML 1.0 DataType
(package): Error
type: ErrorObject
displayName: QueryTimedOutError
discriminatorValue: QueryTimedOut
description: |
  Returned when the query times out.

  If a query constantly times out, please check if it follows the [performance best practices](/../api/predicates/query#performance-considerations).
properties:
  code:
    type: string
  message:
    type: string
    description: |
      `"The query timed out. If your query constantly times out, please check that it follows the performance best practices (see https://docs.commercetools.com/api/predicates/query#performance-considerations)."`
