#%RAML 1.0 DataType
(package): Error
type: ErrorObject
displayName: SemanticErrorError
discriminatorValue: SemanticError
description: |
  Returned when a [Discount predicate](/../api/predicates/predicate-operators) or [API Extension predicate](/../api/predicates/query#using-predicates-in-conditional-api-extensions) is not semantically correct.
properties:
  code:
    type: string
  message:
    type: string
    description: |
      Plain text description of the error concerning the predicate. For example, `"Invalid country code $countryCode provided for the field $fieldDefinition."`.
