#%RAML 1.0 DataType
(package): Error
type: ErrorObject
displayName: SyntaxErrorError
discriminatorValue: SyntaxError
description: |
  Returned when a [Discount predicate](/../api/predicates/predicate-operators), [API Extension predicate](/../api/predicates/query#use-predicates-in-conditional-api-extensions), or [search query](/../api/projects/products-search) does not have the correct syntax.
properties:
  code:
    type: string
  message:
    type: string
    description: |
      `"Syntax error while parsing $fieldDefinition."`
