#%RAML 1.0 Library
usage: Customer import types.
(annotations.package): customers

uses:
  common: common.raml
  custom-field: custom-field.raml
  annotations: ../annotationTypes/annotations.raml

types:
  CustomerImport:
    description: |
      Import representation for a customer.
    type: common.ImportResource
    properties:
      customerNumber?:
        description: |
          Maps to `Customer.customerNumber`.
        type: string
      email:
        description: |
          Maps to `Customer.email`.
        type: string
      password:
        description: |
          Maps to `Customer.password`.
        type: string
      firstName?:
        description: |
          Maps to `Customer.firstName`.
        type: string
      lastName?:
        description: |
          Maps to `Customer.lastName`.
        type: string
      middleName?:
        description: |
          Maps to `Customer.middleName`.
        type: string
      title?:
        description: |
          Maps to `Customer.title`.
        type: string
      salutation?:
        description: |
          Maps to `Customer.salutation`.
        type: string
      externalId?:
        description: |
          Maps to `Customer.externalId`.
        type: string
      dateOfBirth?:
        description: |
          Maps to `Customer.dateOfBirth`.
        type: date-only
      companyName?:
        description: |
          Maps to `Customer.companyName`.
        type: string
      vatId?:
        description: |
          Maps to `Customer.vatId`.
        type: string
      isEmailVerified?:
        description: |
          Maps to `Customer.isEmailVerified`.
        type: boolean
      customerGroup?:
        description: |
          References a customer group by its key.

          The customer group referenced
          must already exist in the commercetools project, or the
          import operation state is set to `Unresolved`.
        type: common.CustomerGroupKeyReference
      addresses?:
        description: |
          Maps to `Customer.addresses`.
        type: common.Address[]
      defaultBillingAddress?:
        description: |
          Maps to `Customer.defaultBillingAddress`.
        type: common.Address
      billingAddresses?:
        description: |
          Maps to `Customer.billingAddresses`.
        type: common.Address
      defaultShippingAddress?:
        description: |
          Maps to `Customer.defaultShippingAddress`.
        type: common.Address
      shippingAddresses?:
        description: |
          Maps to `Customer.shippingAddresses`.
        type: common.Address
      locale?:
        description: |
          Maps to `Customer.locale`.
        type: string
      custom?:
        description: The custom fields for this Customer.
        type: custom-field.Custom
