#%RAML 1.0 Library
usage: Custom field types.
(annotations.package): customfields

uses:
  annotations: ../annotationTypes/annotations.raml
  common: common.raml

types:
  Custom:
    description:
      The representation to be sent to the server when creating a resource with
      custom fields.
    properties:
      type:
        description: The type that provides the field definitions for this object.
        type: common.TypeKeyReference
      fields?:
        description: The custom fields of this object.
        type: FieldContainer
  FieldContainer:
    description: Maps the custom field names to the actual values.
    type: object
    (annotations.asMap):
      keyTypeHint: string
    properties:
      //:
        description: Mapping from the custom field name to the actual value.
        type: CustomField
  CustomField:
    description: Provides the value for a custom field of a specific type.
    type: object
    discriminator: type
    properties:
      type:
        description: The type of this field.
        type: string
  BooleanField:
    description: A field with a boolean value.
    type: CustomField
    discriminatorValue: Boolean
    properties:
      value: boolean
  StringField:
    description: A field with a string value.
    type: CustomField
    discriminatorValue: String
    properties:
      value: string
  LocalizedStringField:
    description: A field with a localized string value.
    type: CustomField
    discriminatorValue: LocalizedString
    properties:
      value: common.LocalizedString
  EnumField:
    description: A field with a enum value.
    type: CustomField
    discriminatorValue: Enum
    properties:
      value: string
  LocalizedEnumField:
    description: A field with a localized enum value.
    type: CustomField
    discriminatorValue: LocalizedEnum
    properties:
      value: string
  NumberField:
    description: A field with a number value.
    type: CustomField
    discriminatorValue: Number
    properties:
      value: number
  MoneyField:
    description: A field with a money value.
    type: CustomField
    discriminatorValue: Money
    properties:
      value: common.TypedMoney
  DateField:
    description: A field with a date value.
    type: CustomField
    discriminatorValue: Date
    properties:
      value: date-only
  TimeField:
    description: A field with a time value.
    type: CustomField
    discriminatorValue: Time
    properties:
      value: time-only
  DateTimeField:
    description: A field with a date time value.
    type: CustomField
    discriminatorValue: DateTime
    properties:
      value: datetime
  ReferenceField:
    description: A field with a reference value.
    type: CustomField
    discriminatorValue: Reference
    properties:
      value:
        type: common.KeyReference
        description: References a resource by its key
  BooleanSetField:
    description: A field with a boolean set value.
    type: CustomField
    discriminatorValue: BooleanSet
    properties:
      value: boolean[]
  StringSetField:
    description: A field with a string set value.
    type: CustomField
    discriminatorValue: StringSet
    properties:
      value: string[]
  LocalizedStringSetField:
    description: A field with a localized string set value.
    type: CustomField
    discriminatorValue: LocalizedStringSet
    properties:
      value: common.LocalizedString[]
  EnumSetField:
    description: A field with a enum set value.
    type: CustomField
    discriminatorValue: EnumSet
    properties:
      value: string[]
  LocalizedEnumSetField:
    description: A field with a localized enum set value.
    type: CustomField
    discriminatorValue: LocalizedEnumSet
    properties:
      value: string[]
  NumberSetField:
    description: A field with a number value.
    type: CustomField
    discriminatorValue: NumberSet
    properties:
      value: number[]
  MoneySetField:
    description: A field with a money set value.
    type: CustomField
    discriminatorValue: MoneySet
    properties:
      value: common.Money[]
  DateSetField:
    description: A field with a date set value.
    type: CustomField
    discriminatorValue: DateSet
    properties:
      value: date-only[]
  TimeSetField:
    description: A field with a time set value.
    type: CustomField
    discriminatorValue: TimeSet
    properties:
      value: time-only[]
  DateTimeSetField:
    description: A field with a date time set value.
    type: CustomField
    discriminatorValue: DateTimeSet
    properties:
      value: datetime[]
  ReferenceSetField:
    description: A field with a reference set value.
    type: CustomField
    discriminatorValue: ReferenceSet
    properties:
      value: common.KeyReference[]
