#%RAML 1.0 Library
usage: Import summary types.
(annotations.package): importsummaries

uses:
  common: common.raml
  annotations: ../annotationTypes/annotations.raml

types:
  ImportSummary:
    description: |
      Describes the status of an [ImportSink](/import-sink#importsink) by the number of resources in each [Processing State](/processing-state#the-list-of-processing-states).
      Can be used to monitor the import progress per [Import Sink](/import-sink).
    properties:
      states:
        description: |
          The import status of an [ImportSink](/import-sink#importsink) given by the number of resources in each [Processing State](/processing-state#the-list-of-processing-states).
        type: OperationStates
      total:
        description: The total number of [ImportOperations](/import-operation#importoperation) received for this Import Summary.
        type: integer
        format: long
  OperationStates:
    properties:
      #/(Accepted|ValidationFailed|Unresolved|WaitForMasterVariant|Imported|Deleted|Rejected)/:
      #description: The number of resources in each [Processing State](/processing-state#the-list-of-processing-states).
      #  type: number
      ValidationFailed:
        description: The number of resources in the `ValidationFailed` state.
        type: integer
        format: long
      Unresolved:
        description: The number of resources in the `Unresolved` state.
        type: integer
        format: long
      WaitForMasterVariant:
        description: The number of resources in the `WaitForMasterVariant` state.
        type: integer
        format: long
      Imported:
        description: The number of resources in the `Imported` state.
        type: integer
        format: long
      Rejected:
        description: The number of resources in the `Rejected` state.
        type: integer
        format: long
