#%RAML 1.0 Library
usage: Import sink types.
(annotations.package): importrequests

uses:
  common: common.raml
  import-operation: import-operation.raml
  annotations: ../annotationTypes/annotations.raml

  category-import: category-import.raml
  price-import: price-import.raml
  product-import: product-import.raml
  product-draft-import: product-draft-import.raml
  product-type-import: product-type-import.raml
  product-variant-import: product-variant-import.raml
  customer-import: customer-import.raml
  order-import: order-import.raml
  order-patch-import: order-patch-import.raml
  inventory-import: inventory-import.raml

types:
  ImportRequest:
    description: |
      An import request batches multiple import resources of the same import resource type for processing by an import sink.
    discriminator: type
    properties:
      type: common.ImportResourceType
  ImportResponse:
    description: |
      The import response contains an import operation for each import resource sent with an import request. Use it for tracking the progress of imports to a commercetools project.

      This is a generic parent type. In practice, send a specific import request type (`CategoryImportRequest`, `OrderImportRequest`, etc.) to an import sink with a matching import type.
    properties:
      operationStatus:
        type: import-operation.ImportOperationStatus[]
        maxItems: 20
  CategoryImportRequest:
    description: |
      An import request for multiple category import resources.
    type: ImportRequest
    discriminatorValue: category
    properties:
      resources:
        description: |
          The category import resources of this request.
        type: category-import.CategoryImport[]
        maxItems: 20
    example: !include ../examples/category-import-request.json
  ProductImportRequest:
    description: |
      An import request for multiple product import resources.
    type: ImportRequest
    discriminatorValue: product
    properties:
      resources:
        description: |
          The product import resources of this request.
        type: product-import.ProductImport[]
        maxItems: 20
    example: !include ../examples/product-import-request.json
  ProductDraftImportRequest:
    description: |
      An import request for multiple product draft import resources.
    type: ImportRequest
    discriminatorValue: product-draft
    properties:
      resources:
        description: |
          The product draft import resources of this request.
        type: product-draft-import.ProductDraftImport[]
        maxItems: 20
    example: !include ../examples/product-draft-import-request.json
  ProductTypeImportRequest:
    description: |
      An import request for multiple product type import resources.
    type: ImportRequest
    discriminatorValue: product-type
    properties:
      resources:
        description: |
          The product type import resources of this request.
        type: product-type-import.ProductTypeImport[]
        maxItems: 20
    example: !include ../examples/product-type-import-request.json
  ProductVariantImportRequest:
    description: |
      An import request for multiple product variant import resources.
    type: ImportRequest
    discriminatorValue: product-variant
    properties:
      resources:
        description: |
          The product variant import resources of this request.
        type: product-variant-import.ProductVariantImport[]
        maxItems: 20
    example: !include ../examples/product-variant-import-request.json
  PriceImportRequest:
    description: |
      An import request for multiple price import resources.
    type: ImportRequest
    discriminatorValue: price
    properties:
      resources:
        description: |
          The price import resources of this request.
        type: price-import.PriceImport[]
        maxItems: 20
    example: !include ../examples/price-import-request.json
  OrderImportRequest:
    description: |
      An import request for multiple order import resources.
    type: ImportRequest
    discriminatorValue: order
    properties:
      resources:
        description: |
          The order import resources of this request.
        type: order-import.OrderImport[]
        maxItems: 20
    example: !include ../examples/order-import-request.json
  OrderPatchImportRequest:
    description: |
      An import request for multiple order patch resources.
    type: ImportRequest
    discriminatorValue: order-patch
    properties:
      patches:
        description: |
          The order patches of this request
        type: order-patch-import.OrderPatchImport[]
        maxItems: 20
    example: !include ../examples/order-patch-import-request.json
  ProductVariantPatchRequest:
    description: |
      An import request for multiple product variant patch resources.
    type: ImportRequest
    discriminatorValue: product-variant-patch
    properties:
      patches:
        description: |
          The product variant patches of this request.
        type: product-variant-import.ProductVariantPatch[]
        maxItems: 20
    example: !include ../examples/product-variant-patch-import-request.json
  CustomerImportRequest:
    description: |
      An import request for multiple customer import resources.
    type: ImportRequest
    discriminatorValue: customer
    properties:
      resources:
        description: |
          The customer import resources of this request.
        type: customer-import.CustomerImport[]
        maxItems: 20
    example: !include ../examples/customer-import-request.json
  InventoryImportRequest:
    description: |
      An import request for multiple inventory import resources.
    type: ImportRequest
    discriminatorValue: inventory
    properties:
      resources:
        description: |
          The inventory import resources of this request.
        type: inventory-import.InventoryImport[]
        maxItems: 20
    example: !include ../examples/inventory-import-request.json
