#%RAML 1.0 Library
usage: Import summary types.
(annotations.package): importsummaries

uses:
  common: common.raml
  annotations: ../annotationTypes/annotations.raml

types:
  ImportSummary:
    description: |
      An import summary describes the states of import resources of a given import sink.

      It is used to track the overall progress of import resources.
    properties:
      states:
        description: The states summary for this import summary.
        type: OperationStates
      total:
        description: The total number of import operations received for this import group.
        type: integer
        format: long
  OperationStates:
    properties:
      #/(Accepted|ValidationFailed|Unresolved|WaitForMasterVariant|Imported|Deleted|Rejected)/:
      #  description: The number of import operations that are in the state given by the key.
      #  type: number
      ValidationFailed:
        description: The number of import operations that are in the state
          `ValidationFailed`.
        type: integer
        format: long
      Unresolved:
        description: The number of import operations that are in the state `Unresolved`.
        type: integer
        format: long
      WaitForMasterVariant:
        description: The number of import operations that are in the state
          `WaitForMasterVariant`.
        type: integer
        format: long
      Imported:
        description: The number of import operations that are in the state `Imported`.
        type: integer
        format: long
      Rejected:
        description: The number of import operations that are in the state `Rejected`.
        type: integer
        format: long
