#%RAML 1.0 Library
usage: Import operation types.
(annotations.package): importoperations

uses:
  common: common.raml
  error: error.raml
  annotations: ../annotationTypes/annotations.raml

types:
  ImportOperation:
    description: |
      Tracks the status of a single import resource as it is imported into the commercetools project.
    properties:
      version:
        description: The import operation version.
        type: integer
        format: long
      importSinkKey:
        description: The key of the import sink.
        type: string
      resourceKey:
        description: The key of the import resource.
        type: string
      id:
        description: The identifier of the operaton that is to be commited
        type: string
      state:
        description: |
          The status of the import resource.
        type: common.ProcessingState
      resourceVersion?:
        description:
          When the resource is successfully imported, this represents the
          imported resource version
        type: integer
        format: long
      retryCount:
        description: |
          The number of request retries for processing the import resource.
        type: integer
      errors?:
        description: |
          If an import resource does not import correctly, the state is set to `Rejected` or `ValidationFailed`
          and this property contains the errors.
        type: error.ErrorObject[]
      createdAt:
        description: When the import operation was created.
        type: datetime
      lastModifiedAt:
        description: When the import operation was modified.
        type: datetime
      expiresAt:
        description: When the import operation expires.
        type: datetime
    examples:
      unresolved: !include ../examples/import-operation-with-unresolved-references.json
      validationFailed: !include ../examples/import-operation-validation-failed.json
  ImportOperationPagedResponse:
    description: This type represents a paged import operation result.
    properties:
      limit:
        description: The maximum number of import operations returned for a page.
        type: integer
      offset:
        description:
          The offset supplied by the client or the server default. It is the
          number of elements skipped.
        type: integer
        format: long
      count:
        description: The actual number of results returned by this response.
        type: integer
        format: long
      results:
        description: The results for this paged response.
        type: ImportOperation[]
  ImportOperationState:
    description: |
      This enumeration describes the operation state of a newly created import operation.
    (annotations.enumDescriptions):
      Unresolved: This is an initial state of import resource and is currently unresolved.
      ValidationFailed: The validation of the import resource failed.
      Delete: The import resource is being deleted.
    type: string
    enum:
      - Unresolved
      - ValidationFailed
      - Delete
  ImportOperationStatus:
    description: |
      The validation status of a created operation.
    properties:
      operationId?:
        description: Id of the import operation.
        type: string
      state:
        description: Validation state of the import operation.
        type: ImportOperationState
      errors?:
        description: Validation errors for the import operation.
        type: error.ErrorObject[]
