#%RAML 1.0 Library
usage: Import operation types.
(annotations.package): importoperations

uses:
  common: common.raml
  error: error.raml
  annotations: ../annotationTypes/annotations.raml

types:
  ImportOperation:
    description: |
      Shows the import status of a specific resource.
    properties:
      version:
        description: The version of the ImportOperation.
        type: integer
        format: long
      importSinkKey:
        description: The key of the [ImportSink](/import-sink#importsink).
        type: string
      resourceKey:
        description: The key of the resource.
        type: string
      id:
        description: The ID of the ImportOperation.
        type: string
      state:
        description: |
          The import status of the resource. Set to `Rejected` or `ValidationFailed` if the import of the resource was not successful.
        type: common.ProcessingState
      resourceVersion?:
        description: The version of the impmorted resource when the import was successful.
        type: integer
        format: long
      errors?:
        description: |
          Contains an error if the import of the resource was not successful. See [Errors](/error).
        type: error.ErrorObject[]
      unresolvedReferences?:
        description: |
          In case of unresolved status this array will show the unresolved references
        type: common.KeyReference[]
      createdAt:
        description: The time when the ImportOperation was created.
        type: datetime
      lastModifiedAt:
        description: The last time When the ImportOperation was modified.
        type: datetime
      expiresAt:
        description: The expiration time of the ImportOperation.
        type: datetime
    examples:
      unresolved: !include ../examples/import-operation-with-unresolved-references.json
      validationFailed: !include ../examples/import-operation-validation-failed.json
  ImportOperationPagedResponse:
    description: |
      [PagedQueryResult](/../api/general-concepts#pagedqueryresult) for Import Operations.
      Used as a response to a query request for Import Operations.
    properties:
      limit:
        description: The number of results requested in the query request.
        type: integer
      offset:
        description: |
          The number of elements skipped, not a page number.
          Supplied by the client or the server default.
        type: integer
        format: long
      count:
        description: The actual number of results returned.
        type: integer
        format: long
      total:
        description: The total number of import operations matching the query.
        type: integer
        format: long
      results:
        description: The array of Import Operations matching the query.
        type: ImportOperation[]
  ImportOperationState:
    description: |
      Describes the validation state of a newly created [ImportOperation](#importoperation).
    (annotations.enumDescriptions):
      Unresolved: This is an initial state of import resource and is currently unresolved.
      ValidationFailed: The validation of the import resource failed.
    type: string
    enum:
      - Unresolved
      - ValidationFailed
  ImportOperationStatus:
    description: ' '
    properties:
      operationId?:
        description: The ID of the [ImportOperation](#importoperation).
        type: string
      state:
        description: The validation state of the [ImportOperation](#importoperation).
        type: ImportOperationState
      errors?:
        description: |
          The validation errors for the [ImportOperation](#importoperation).
          See [Errors](/error).
        type: error.ErrorObject[]
