#%RAML 1.0 Library
usage: Inventory import types.
(annotations.package): inventories

uses:
  common: common.raml
  custom-field: custom-field.raml
  annotations: ../annotationTypes/annotations.raml

types:
  InventoryImport:
    description: |
      The data representation for an Inventory to be imported that is persisted as a [Inventory](/../api/projects/inventory#top) in the Project.
    type: common.ImportResource
    properties:
      sku:
        type: string
      quantityOnStock:
        description: |
          Maps to `Inventory.quantityOnStock`
        type: number
      restockableInDays?:
        description: |
          Maps to `Inventory.restockableInDays`
        type: number
      expectedDelivery?:
        type: datetime
      supplyChannel?:
        type: common.ChannelKeyReference
      custom?:
        description: |
          Maps to `Inventory.custom`.
        type: custom-field.Custom
