#%RAML 1.0 DataType
(package): Extension
(docs-uri): https://docs.commercetools.com/http-api-projects-api-extensions.html#set-timeout-in-ms
type: ExtensionUpdateAction
displayName: ExtensionSetTimeoutInMsAction
discriminatorValue: setTimeoutInMs
properties:
  timeoutInMs?:
    type: integer
    description: |-
      The maximum time the commercetools platform waits for a response from the extension.
      The maximum value is 2000 ms (2 seconds).
      This limit can be increased per project after we review the performance impact.
      Please contact Support via the support and provide the region, project key and use case.
