#%RAML 1.0 DataType
(package): Channel
(docs-uri): https://docs.commercetools.com/http-api-projects-channels.html#add-roles
type: ChannelUpdateAction
displayName: ChannelAddRolesAction
discriminatorValue: addRoles
(postman-example): !include ../../../examples/Channel/ChannelAddRolesAction.json
properties:
  roles:
    type: ChannelRoleEnum[]
