#%RAML 1.0 DataType
(package): Channel
(docs-uri): https://docs.commercetools.com/api/projects/channels#set-customfield
type: ChannelUpdateAction
displayName: ChannelSetCustomFieldAction
discriminatorValue: setCustomField
example: !include ../../../examples/Channel/ChannelSetCustomFieldAction.json
properties:
  name:
    type: string
    description: |
      Name of the [Custom Field](/../api/projects/custom-fields).
  value?:
    type: CustomFieldValue
    description: |
      If `value` is absent or `null`, this field will be removed if it exists.
      Trying to remove a field that does not exist will fail with an [InvalidOperation](/../api/errors#general-400-invalid-operation) error.
      If `value` is provided, it is set for the field defined by `name`.
