#%RAML 1.0 DataType
(package): Channel
type: ChannelUpdateAction
displayName: ChannelSetGeoLocationAction
discriminatorValue: setGeoLocation
example: !include ../../../examples/Channel/updates/ChannelSetGeoLocationAction.json
properties:
  geoLocation?:
    type: GeoJson
    description: |
      Value to set.
