#%RAML 1.0 DataType
(package): Channel
type: ChannelUpdateAction
displayName: ChannelRemoveRolesAction
discriminatorValue: removeRoles
example: !include ../../../examples/Channel/updates/ChannelRemoveRolesAction.json
properties:
  roles:
    type: ChannelRoleEnum[]
    description: |
      Value to remove from the array.
