#%RAML 1.0 DataType
(package): McpServer
type: McpServerUpdateAction
displayName: McpServerSetToolCustomizationsAction
discriminatorValue: setToolCustomizations
example: !include ../../../examples/McpServer/McpServerSetToolCustomizationsAction.json
description: |
  Replaces the entire list of [tool customizations](ctp:api:type:ToolCustomization) on the MCP Server.
properties:
  toolCustomizations:
    type: array
    items: ToolCustomization
    description: |
      New list of tool customizations. Replaces the existing list entirely.
