#%RAML 1.0 DataType
(package): Product
displayName: FilteredFacetResult
type: FacetResult
discriminatorValue: filter
properties:
  count:
    type: number
    format: int64
  productCount?:
    type: number
    format: int64
