#%RAML 1.0 DataType

displayName: ProductProjection
uses:
    api: ../types.lib.raml
type: api.Resource
(generate-collection): true
properties:
    key?:
        type: string
    productType: api.ProductTypeReference
    name:
        type: api.LocalizedString
    description?:
        type: api.LocalizedString
    slug:
        type: api.LocalizedString
    categories: api.CategoryReference[]
    categoryOrderHints?:
        type: api.CategoryOrderHints
    metaTitle?:
        type: api.LocalizedString
    metaDescription?:
        type: api.LocalizedString
    metaKeywords?:
        type: api.LocalizedString
    searchKeywords?:
        type: api.SearchKeywords
    hasStagedChanges?:
        type: boolean
    published?:
        type: boolean
    masterVariant:
        type: api.ProductVariant
    variants:
        type: api.ProductVariant[]
    taxCategory?: api.TaxCategoryReference
    state?: api.StateReference
    reviewRatingStatistics?:
        type: api.ReviewRatingStatistics
