#%RAML 1.0 DataType
(package): Product


type: ProductUpdateAction
displayName: ProductRemoveVariantAction
discriminatorValue: removeVariant
properties:
    id?:
        type: integer
    sku?:
        type: string
    staged?:
        type: boolean
