#%RAML 1.0 DataType
(package): Products
(docs-uri): https://docs.commercetools.com/http-api-projects-products.html#set-asset-sources


type: ProductUpdateAction
displayName: ProductSetAssetSourcesAction
discriminatorValue: setAssetSources
properties:
    variantId?:
        type: integer
    sku?:
        type: string
    assetKey?:
        type: string
    assetId?:
        type: string
    staged?:
        type: boolean
    sources:
        type: AssetSource[]
