#%RAML 1.0 DataType
(package): Product


type: ProductUpdateAction
displayName: ProductSetAssetCustomTypeAction
discriminatorValue: setAssetCustomType
properties:
    assetId:
        type: string
    fields?:
        type: string
    sku?:
        type: string
    staged?:
        type: boolean
    type?:
        type: Type
    variantId?:
        type: integer
