#%RAML 1.0 DataType
(package): Product

displayName: ProductDraft

type: object
properties:
    productType?: ProductTypeReference
    name:
        type: LocalizedString
    slug:
        type: LocalizedString
    key?:
        type: string
    description?:
        type: LocalizedString
    categories?: CategoryReference[]
    categoryOrderHints?:
        type: CategoryOrderHints
    metaTitle?:
        type: LocalizedString
    metaDescription?:
        type: LocalizedString
    metaKeywords?:
        type: LocalizedString
    masterVariant?:
        type: ProductVariantDraft
    variants?:
        type: ProductVariantDraft[]
    taxCategory?: TaxCategoryReference
    searchKeywords?:
        type: SearchKeywords
    state?: StateReference
    publish?:
        type: boolean
