#%RAML 1.0 DataType
(package): Product
(docs-uri): https://docs.commercetools.com/http-api-projects-products.html#productdata
displayName: ProductData
type: object
properties:
  name:
    type: LocalizedString
    (hasUpdateAction):
      action: changeName
      fields:
        name: LocalizedString
        staged?: boolean
  categories:
    type: CategoryReference[]
    (hasUpdateActions):
    - action: addToCategory
      fields:
        category: CategoryResourceIdentifier
        orderHint?: string
        staged?: boolean
    - action: removeFromCategory
      fields:
        category: CategoryResourceIdentifier
        staged?: boolean
  categoryOrderHints?:
    type: CategoryOrderHints
    (hasUpdateAction):
      action: setCategoryOrderHint
      fields:
        categoryId: string
        orderHint?: string
        staged?: boolean
  description?:
    type: LocalizedString
    (hasUpdateAction):
      action: setDescription
      fields:
        description?: LocalizedString
        staged?: boolean
  slug:
    type: LocalizedString
    (hasUpdateAction):
      action: changeSlug
      fields:
        slug: LocalizedString
        staged?: boolean
  metaTitle?:
    type: LocalizedString
    (hasUpdateAction):
      action: setMetaTitle
      fields:
        metaTitle?: LocalizedString
        staged?: boolean
  metaDescription?:
    type: LocalizedString
    (hasUpdateAction):
      action: setMetaDescription
      fields:
        metaDescription?: LocalizedString
        staged?: boolean
  metaKeywords?:
    type: LocalizedString
    (hasUpdateAction):
      action: setMetaKeywords
      fields:
        metaKeywords?: LocalizedString
        staged?: boolean
  masterVariant:
    type: ProductVariant
    (hasUpdateAction):
      action: changeMasterVariant
      fields:
        variantId?:
          type: number
          format: int64
        sku?: string
        staged?: boolean
  variants:
    type: ProductVariant[]
    (hasUpdateActions):
    - action: addVariant
      docsAnchor: add-productvariant
      fields:
        sku?: string
        key?: string
        prices?: PriceDraft[]
        images?: Image[]
        attributes?: Attribute[]
        staged?: boolean
        assets?: Asset[]
    - action: removeVariant
      docsAnchor: remove-productvariant
      fields:
        id?:
          type: number
          format: int64
        sku?: string
        staged?: boolean
  searchKeywords:
    type: SearchKeywords
    (hasUpdateAction):
      action: setSearchKeywords
      docsAnchor: set-searchkeywords
      fields:
        searchKeywords: SearchKeywords
        staged?: boolean
