#%RAML 1.0 DataType

displayName: ProductVariantChannelAvailability

type: object
(generate-collection): true
properties:
    isOnStock?:
        type: boolean
    restockableInDays?:
        type: integer
    availableQuantity?:
        type: integer
