#%RAML 1.0 DataType


type: ProductUpdateAction
displayName: ProductChangePriceAction
discriminatorValue: changePrice
properties:
    price:
        type: PriceDraft
    priceId:
        type: string
    staged?:
        type: boolean
