#%RAML 1.0 DataType
(package): Product


type: ProductUpdateAction
displayName: ProductSetMetaKeywordsAction
discriminatorValue: setMetaKeywords
properties:
    metaKeywords?:
        type: LocalizedString
