#%RAML 1.0 DataType
(package): Product
(docs-uri): https://docs.commercetools.com/http-api-projects-products.html#product

displayName: Product

type: LoggedResource
(updateType): ProductUpdate
(hasUpdateActions):
  - action: revertStagedChanges
  - action: revertStagedVariantChanges
    fields:
      variantId:
        type: number
        format: int64
  - action: publish
    fields:
      scope?: ProductPublishScope
  - action: unpublish
properties:
  key?:
    type: string
    (hasSimpleUpdateAction): setKey
  productType: ProductTypeReference
  masterData:
    type: ProductCatalogData
  taxCategory?:
    type: TaxCategoryReference
    (hasUpdateAction):
      action: setTaxCategory
      docsAnchor: set-taxcategory
  state?: StateReference
  reviewRatingStatistics?:
    type: ReviewRatingStatistics
