#%RAML 1.0 DataType


type: ProductUpdateAction
displayName: ProductAddAssetAction
discriminatorValue: addAsset
properties:
    asset:
        type: AssetDraft
    sku?:
        type: string
    variantId?:
        type: integer
