#%RAML 1.0 DataType
(package): Product

displayName: ProductVariantDraft

type: object
(generate-collection): true
properties:
    sku?:
        type: string
    key?:
        type: string
    prices?:
        type: PriceDraft[]
    attributes?:
        type: Attribute[]
    images?:
        type: Image[]
    assets?:
        type: AssetDraft[]
