#%RAML 1.0 DataType
(package): Product


type: ProductUpdateAction
displayName: ProductSetProductPriceCustomFieldAction
discriminatorValue: setProductPriceCustomField
properties:
    name:
        type: string
    priceId:
        type: string
    staged?:
        type: boolean
    value?:
        type: any
