#%RAML 1.0 DataType
(package): Product
(docs-uri): https://docs.commercetools.com/http-api-projects-products.html#productdraft

displayName: ProductDraft

type: object
properties:
    productType: ProductTypeResourceIdentifier
    name:
        type: LocalizedString
    slug:
        type: LocalizedString
    key?:
        type: string
    description?:
        type: LocalizedString
    categories?: CategoryResourceIdentifier[]
    categoryOrderHints?:
        type: CategoryOrderHints
    metaTitle?:
        type: LocalizedString
    metaDescription?:
        type: LocalizedString
    metaKeywords?:
        type: LocalizedString
    masterVariant?:
        type: ProductVariantDraft
    variants?:
        type: ProductVariantDraft[]
    taxCategory?: TaxCategoryResourceIdentifier
    searchKeywords?:
        type: SearchKeywords
    state?: StateResourceIdentifier
    publish?:
        type: boolean
