#%RAML 1.0 DataType
(package): Product

displayName: SearchKeyword

type: object
(generate-collection): true
properties:
    text:
        type: string
    suggestTokenizer?:
        (generator-type): SuggestTokenizer
        type: SuggestTokenizer | WhitespaceTokenizer | CustomTokenizer
