#%RAML 1.0 DataType
(package): Product

displayName: SearchKeyword

type: object
properties:
    text:
        type: string
    suggestTokenizer?:
        type: SuggestTokenizer | WhitespaceTokenizer | CustomTokenizer
