#%RAML 1.0 DataType

displayName: SuggestTokenizer
uses:
    api: ../types.lib.raml
type: object
discriminator: type
properties:
    type:
        type: string
        enum:
        - whitespace
        - custom
