#%RAML 1.0 DataType
(package): Project
(docs-uri): https://docs.commercetools.com/http-api-projects-project.html#change-messages-enabled
(deprecated): true
type: ProjectUpdateAction
displayName: ProjectChangeMessagesEnabledAction
discriminatorValue: changeMessagesEnabled
properties:
  messagesEnabled:
    type: boolean
