#%RAML 1.0 DataType
(package): Project
(docs-uri): https://docs.commercetools.com/http-api-projects-project.html#change-name
type: ProjectUpdateAction
displayName: ProjectChangeNameAction
discriminatorValue: changeName
(postman-example): !include ../../../examples/Project/ProjectChangeNameAction.json
properties:
  name:
    type: string
    description: ''
