#%RAML 1.0 DataType
(package): Category
(docs-uri): https://docs.commercetools.com/http-api-projects-categories.html#set-customfield
type: CategoryUpdateAction
displayName: CategorySetCustomFieldAction
discriminatorValue: setCustomField
(postman-example): !include ../../../examples/Category/CategorySetCustomFieldAction.json
properties:
  name:
    type: string
    description: ''
  value?:
    type: any
