#%RAML 1.0 DataType
(package): AttributeGroup
(docs-uri): https://docs.commercetools.com/api/projects/attribute-groups#setattributes
type: AttributeGroupUpdateAction
displayName: AttributeGroupSetAttributesAction
discriminatorValue: setAttributes
example: !include ../../../examples/AttributeGroup/AttributeGroupSetAttributesAction.json
properties:
  attributes:
    type: AttributeReference[]
    description: |
      New unique values to set.
