#%RAML 1.0 DataType
(package): AttributeGroup
(docs-uri): https://docs.commercetools.com/api/projects/attribute-groups#changename
type: AttributeGroupUpdateAction
displayName: AttributeGroupChangeNameAction
discriminatorValue: changeName
example: !include ../../../examples/AttributeGroup/AttributeGroupChangeNameAction.json
properties:
  name:
    type: LocalizedString
    description: |
      New value to set.
      Must not be empty.
