#%RAML 1.0 DataType
(package): Message
type: MessagePayload
(beta): true
displayName: ApprovalFlowCreatedMessagePayload
discriminatorValue: ApprovalFlowCreated
description: |
  Generated after an [Approval Flow](ctp:api:type:ApprovalFlow) is created.
properties:
  approvalFlow:
    type: ApprovalFlow
    description: |
      The [Approval Flow](ctp:api:type:ApprovalFlow) that was created.
