#%RAML 1.0 DataType
(package): Message
type: MessagePayload
(beta): true
displayName: ApprovalFlowCompletedMessagePayload
discriminatorValue: ApprovalFlowCompleted
description: |
  Generated after an [Approval Flow](ctp:api:type:ApprovalFlow) is completed and reaches a final status.
properties:
  status:
    type: ApprovalFlowStatus
    description: |
      Final status of the [Approval Flow](ctp:api:type:ApprovalFlow).
  order:
    type: OrderReference
    description: |
      [Reference](ctp:api:type:Reference) to the [Order](ctp:api:type:Order) related to the completed [Approval Flow](ctp:api:type:ApprovalFlow).
