#%RAML 1.0 DataType
(package): Message
type: MessagePayload
displayName: ApprovalRuleRequestersSetMessagePayload
discriminatorValue: ApprovalRuleRequestersSet
description: |
  Generated after a successful [Set Requester](ctp:api:type:ApprovalRuleSetRequestersAction) update action.
properties:
  requesters:
    type: RuleRequester[]
    description: |
      RuleRequester of the [ApprovalRule](ctp:api:type:ApprovalRule) after the [Set Requester](ctp:api:type:ApprovalRuleSetRequestersAction) update action.
  oldRequesters:
    type: RuleRequester[]
    description: |
      RuleRequester of the [ApprovalRule](ctp:api:type:ApprovalRule) after the [Set Requester](ctp:api:type:ApprovalRuleSetRequestersAction) update action.
