#%RAML 1.0 DataType
(package): Message
type: MessagePayload
(beta): true
displayName: ApprovalFlowRejectedMessagePayload
discriminatorValue: ApprovalFlowRejected
description: |
  Generated after an [Approval Flow is rejected](/projects/approval-flows#reject).
properties:
  associate:
    type: CustomerReference
    description: |
      [Reference](ctp:api:type:Reference) to the [Customer](ctp:api:type:Customer) who rejected the [Approval Flow](/projects/approval-flows).
  rejectionReason?:
    type: string
    description: |
      Description of the reason why the [Approval Flow](ctp:api:type:ApprovalFlow) was rejected.
  order:
    type: OrderReference
    description: |
      [Reference](ctp:api:type:Reference) to the [Order](ctp:api:type:Order) that received the rejection.
