#%RAML 1.0 DataType
(package): Message
type: MessagePayload
displayName: ApprovalRuleStatusSetMessagePayload
discriminatorValue: ApprovalRuleStatusSet
description: |
  Generated after a successful [Set Status](ctp:api:type:ApprovalRuleSetStatusAction) update action.
properties:
  status:
    type: ApprovalRuleStatus
    description: |
      Status of the [ApprovalRule](ctp:api:type:ApprovalRule) after the [Set Status](ctp:api:type:ApprovalRuleSetStatusAction) update action.
  oldStatus:
    type: ApprovalRuleStatus
    description: |
      Status of the [ApprovalRule](ctp:api:type:ApprovalRule) before the [Set Status](ctp:api:type:ApprovalRuleSetStatusAction) update action.
