#%RAML 1.0 DataType
(package): Message
type: MessagePayload
displayName: ApprovalRuleCreatedMessagePayload
discriminatorValue: ApprovalRuleCreated
description: |
  Generated after an [Approval Rule](ctp:api:type:ApprovalRule) is created.
properties:
  approvalRule:
    type: ApprovalRule
    description: |
      The [Approval Rule](ctp:api:type:ApprovalRule) that was created.
