#%RAML 1.0 DataType
(package): Message
(docs-uri): https://docs.commercetools.com/http-api-projects-messages.html#businessunitnamechangedmessage
type: MessagePayload
displayName: BusinessUnitNameChangedMessagePayload
discriminatorValue: BusinessUnitNameChanged
description: |
  Generated after a successful [Change Name](ctp:api:type:BusinessUnitChangeNameAction) update action.
properties:
  name:
    type: string
    description: |
      Updated name of the [Business Unit](ctp:api:type:BusinessUnit).
