#%RAML 1.0 DataType
(package): Message
(docs-uri): https://docs.commercetools.com/http-api-projects-messages.html#businessunitstatuschangedmessage
type: MessagePayload
displayName: BusinessUnitStatusChangedMessagePayload
discriminatorValue: BusinessUnitStatusChanged
description: |
  Generated after a successful [Change Status](ctp:api:type:BusinessUnitChangeStatusAction) update action.
properties:
  active:
    type: BusinessUnitStatus
    description: |
      Updated status of the [Business Unit](ctp:api:type:BusinessUnit).
