#%RAML 1.0 DataType
(package): Message
(docs-uri): https://docs.commercetools.com/http-api-projects-messages.html#businessunitassociateremovedmessage
type: MessagePayload
displayName: BusinessUnitAssociateRemovedMessagePayload
discriminatorValue: BusinessUnitAssociateRemoved
description: |
  Generated after a successful [Remove Associate](ctp:api:type:BusinessUnitRemoveAssociateAction) update action.
properties:
  associate:
    type: Associate
    description: |
      The [Associate](ctp:api:type:Associate) that was removed from the [Business Unit](ctp:api:type:BusinessUnit).
