#%RAML 1.0 DataType
(package): Message
(docs-uri): https://docs.commercetools.com/http-api-projects-messages.html#businessunitshippingaddressremovedmessage
type: MessagePayload
displayName: BusinessUnitShippingAddressRemovedMessagePayload
discriminatorValue: BusinessUnitShippingAddressRemoved
description: |
  Generated after a successful [Remove Shipping Address Identifier](ctp:api:type:BusinessUnitRemoveShippingAddressIdAction) update action.
properties:
  address:
    type: Address
    description: |
      The address that was removed from shipping addresses of the [Business Unit](ctp:api:type:BusinessUnit).
