#%RAML 1.0 DataType
(package): Message
type: MessagePayload
displayName: CartDiscountCreatedMessagePayload
discriminatorValue: CartDiscountCreated
description: |
  Generated after a successful [Create CartDiscount](ctp:api:endpoint:/{projectKey}/cart-discounts:POST) request.
properties:
  cartDiscount:
    type: CartDiscount
    description: |
      The [Cart Discount](ctp:api:type:CartDiscount) that was created.
