#%RAML 1.0 DataType
(package): Message
type: MessagePayload
displayName: CartDiscountStoreAddedMessagePayload
discriminatorValue: CartDiscountStoreAdded
description: |
  Generated after a successful [Add Store](ctp:api:type:CartDiscountAddStoreAction) update action.
properties:
  store:
    type: StoreKeyReference
    description: |
      The [Store](ctp:api:type:Store) that was added to the [Cart Discount](ctp:api:type:CartDiscount).
