#%RAML 1.0 DataType
(package): Message
(docs-uri): https://docs.commercetools.com/http-api-projects-messages.html#category-slug-changed
type: MessagePayload
displayName: CategorySlugChangedMessagePayload
discriminatorValue: CategorySlugChanged
description: |
  Generated after a successful [Change Slug](ctp:api:type:CategoryChangeSlugAction) update action.
properties:
  slug:
    type: LocalizedString
    description: |
      The slug of the [Category](ctp:api:type:Category) after the [Change Slug](ctp:api:type:CategoryChangeSlugAction) update action.
  oldSlug?:
    type: LocalizedString
    description: |
      The slug of the [Category](ctp:api:type:Category) before the [Change Slug](ctp:api:type:CategoryChangeSlugAction) update action.
