#%RAML 1.0 DataType
(package): Message
type: MessagePayload
displayName: CustomerCompanyNameSetMessagePayload
discriminatorValue: CustomerCompanyNameSet
description: |
  Generated after a successful [Set Company Name](ctp:api:type:CustomerSetCompanyNameAction) update action.
properties:
  companyName?:
    type: string
    description: |
      The `companyName` that was set during the [Set Company Name](ctp:api:type:CustomerSetCompanyNameAction) update action.
