#%RAML 1.0 DataType
(package): Message
type: MessagePayload
displayName: CustomerBillingAddressRemovedMessagePayload
discriminatorValue: CustomerBillingAddressRemoved
description: |
  Generated after a successful [Remove Billing Address ID](ctp:api:type:CustomerRemoveBillingAddressIdAction) update action.
properties:
  address:
    type: Address
    description: |
      The address that was removed from the [Customer](ctp:api:type:Customer) `billingAddressIds`.
