#%RAML 1.0 DataType
(package): Message
(docs-uri): https://docs.commercetools.com/http-api-projects-messages.html#customer-last-name-set
type: MessagePayload
displayName: CustomerLastNameSetMessagePayload
discriminatorValue: CustomerLastNameSet
description: |
  Generated after a successful [Set Last Name](ctp:api:type:CustomerSetLastNameAction) update action.
properties:
  lastName?:
    type: string
    description: |
      The `lastName` that was set during the [Set Last Name](ctp:api:type:CustomerSetLastNameAction) update action.
