#%RAML 1.0 DataType
(package): Message
type: MessagePayload
displayName: CustomerDeletedMessagePayload
discriminatorValue: CustomerDeleted
description: |
  Generated after a successful [Delete Customer](/../api/projects/customers#delete-customer) request.
properties:
  email?:
    type: string
    description: |
      The email address of the Customer that was deleted.
