#%RAML 1.0 DataType
(package): Message
(docs-uri): https://docs.commercetools.com/http-api-projects-messages.html#customergroupsetmessage
type: MessagePayload
displayName: CustomerGroupSetMessagePayload
discriminatorValue: CustomerGroupSet
properties:
  customerGroup:
    type: CustomerGroupReference
