#%RAML 1.0 DataType
(package): Message
type: MessagePayload
displayName: CustomerShippingAddressRemovedMessagePayload
discriminatorValue: CustomerShippingAddressRemoved
description: |
  Generated after a successful [Remove Shipping Address ID](ctp:api:type:CustomerRemoveShippingAddressIdAction) update action.
properties:
  address:
    type: Address
    description: |
      The address that was removed from the [Customer](ctp:api:type:Customer) `shippingAddressIds`.
