#%RAML 1.0 DataType
(package): Message
(docs-uri): https://docs.commercetools.com/http-api-projects-messages.html#customer-deleted
type: MessagePayload
displayName: CustomerDeletedMessagePayload
discriminatorValue: CustomerDeleted
description: |
  Generated after a successful [Delete Customer](/../api/projects/customers#delete-customer) request.
