#%RAML 1.0 DataType
(package): Message
type: MessagePayload
displayName: CustomerEmailTokenCreatedMessagePayload
discriminatorValue: CustomerEmailTokenCreated
description: |
  Generated after a successful [Create email token for Customer](ctp:api:endpoint:/{projectKey}/customers/email-token:POST) or [Create email token for Customer in Store](ctp:api:endpoint:/{projectKey}/in-store/key={storeKey}/customers/email-token:POST) request. The `resource` property of the Message is a [CustomerEmailTokenReference](ctp:api:type:CustomerEmailTokenReference).
properties:
  customerId:
    type: string
    description: |
      Unique identifier of the Customer.
  expiresAt:
    type: datetime
    description: |
      Date and time (UTC) the email token expires.
  value?:
    type: string
    description: |
      Value of the token, present only if the token's validity is 60 minutes or less.
  invalidateOlderTokens:
    type: boolean
    description: |
      If `true`, all email tokens issued previously for the Customer are invalidated.
