#%RAML 1.0 DataType
(package): Message
(docs-uri): https://docs.commercetools.com/http-api-projects-messages.html#customer-created
type: MessagePayload
displayName: CustomerCreatedMessagePayload
discriminatorValue: CustomerCreated
description: |
  Generated after a successful [Create Customer](/../api/projects/customers#create-sign-up-customer) request.
properties:
  customer:
    type: Customer
    description: |
      [Customer](ctp:api:type:Customer) that was created.
