#%RAML 1.0 DataType
(package): Message
type: MessagePayload
displayName: DiscountCodeCreatedMessagePayload
discriminatorValue: DiscountCodeCreated
description: |
  Generated after a successful [Create DiscountCode](ctp:api:endpoint:/{projectKey}/discount-codes:POST) request.
properties:
  discountCode:
    type: DiscountCode
    description: |
      The [Discount Code](ctp:api:type:DiscountCode) that was created.
