#%RAML 1.0 DataType
(package): Message
(docs-uri): https://docs.commercetools.com/http-api-message-types#inventoryentryquantitysetmessage
type: MessagePayload
displayName: InventoryEntryQuantitySetMessagePayload
discriminatorValue: InventoryEntryQuantitySet
properties:
  oldQuantityOnStock:
    type: number
    format: int64
  newQuantityOnStock:
    type: number
    format: int64
  oldAvailableQuantity:
    type: number
    format: int64
  newAvailableQuantity:
    type: number
    format: int64
