#%RAML 1.0 DataType
(package): Message
(docs-uri): https://docs.commercetools.com/http-api-projects-messages.html#inventoryentrydeletedmessage
type: MessagePayload
displayName: InventoryEntryDeletedMessagePayload
discriminatorValue: InventoryEntryDeleted
properties:
  sku:
    type: string
  supplyChannel:
    type: ChannelReference
