#%RAML 1.0 DataType
(package): Message
(docs-uri): https://docs.commercetools.com/api/projects/messages#order-custom-field-changed
type: OrderMessagePayload
displayName: OrderCustomFieldChangedMessagePayload
discriminatorValue: OrderCustomFieldChanged
description: |
  Generated when an existing Custom Field has been changed using the [Set CustomField](ctp:api:type:OrderSetCustomFieldAction) action.
properties:
  name:
    type: string
    description: |
      Name of the Custom Field that has been changed.
  value:
    type: CustomFieldValue
    description: |
      [CustomFieldValue](ctp:api:type:CustomFieldValue) based on the [FieldType](ctp:api:type:FieldType) after the [Set CustomField](ctp:api:type:OrderSetCustomFieldAction) update action.
  previousValue?:
    type: CustomFieldValue
    description: |
      [CustomFieldValue](ctp:api:type:CustomFieldValue) based on the [FieldType](ctp:api:type:FieldType) before the [Set CustomField](ctp:api:type:OrderSetCustomFieldAction) update action.
      When there has not been a Custom Field with the `name` on the Order before, an [Order Custom Field Added](ctp:api:type:OrderCustomFieldAddedMessage) Message is generated instead.
