#%RAML 1.0 DataType
(package): Message
type: MessagePayload
displayName: OrderPaymentAddedMessagePayload
discriminatorValue: OrderPaymentAdded
description: |
  Generated after a successful [Add Payment](ctp:api:type:OrderAddPaymentAction) update action or when a [Payment](ctp:api:type:Payment) is added via [Order Edits](ctp:api:type:StagedOrderAddPaymentAction).
properties:
  paymentRef:
    type: PaymentReference
    description: |
      [Payment](ctp:api:type:Payment) that was added to the [Order](ctp:api:type:Order).
