#%RAML 1.0 DataType
(package): Message
(docs-uri): https://docs.commercetools.com/http-api-projects-messages.html#order-discount-code-state-set
type: OrderMessagePayload
displayName: OrderDiscountCodeStateSetMessagePayload
discriminatorValue: OrderDiscountCodeStateSet
description: |
  Generated after the [DiscountCodeState](ctp:api:type:DiscountCodeState) changes due to a [recalculation](/../api/projects/carts#recalculate).
properties:
  discountCode:
    type: DiscountCodeReference
    description: |
      [DiscountCode](ctp:api:type:DiscountCode) that changed due to the recalculation.
  state:
    type: DiscountCodeState
    description: |
      [DiscountCodeState](ctp:api:type:DiscountCodeState) after the recalculation.
  oldState?:
    type: DiscountCodeState
    description: |
      [DiscountCodeState](ctp:api:type:DiscountCodeState) before the recalculation.
