#%RAML 1.0 DataType
(package): Message
(docs-uri): https://docs.commercetools.com/http-api-projects-messages.html#orderlineitemremovedmessage
type: MessagePayload
displayName: OrderLineItemRemovedMessagePayload
discriminatorValue: OrderLineItemRemoved
properties:
  lineItemId:
    type: string
  removedQuantity:
    type: number
    format: int64
  newQuantity:
    type: number
    format: int64
  newState:
    type: ItemState[]
  newTotalPrice:
    type: TypedMoney
  newTaxedPrice?:
    type: TaxedItemPrice
  newPrice?:
    type: Price
  newShippingDetail?:
    type: ItemShippingDetails
