#%RAML 1.0 DataType
(package): Message
type: OrderMessagePayload
displayName: OrderImportedMessagePayload
discriminatorValue: OrderImported
description: |
  Generated after a successful [Order Import](ctp:api:endpoint:/{projectKey}/orders/import:POST).
properties:
  order:
    type: Order
    description: |
      [Order](ctp:api:type:Order) that was imported.
