#%RAML 1.0 DataType
(package): Message
(docs-uri): https://docs.commercetools.com/http-api-projects-messages.html#orderlineitemadded
type: MessagePayload
displayName: OrderLineItemAddedMessagePayload
discriminatorValue: OrderLineItemAdded
properties:
  lineItem:
    type: LineItem
  addedQuantity:
    type: number
    format: int64
