#%RAML 1.0 DataType
(package): Message
(docs-uri): https://docs.commercetools.com/http-api-projects-messages.html#ordercreatedmessage
type: MessagePayload
displayName: OrderCreatedMessagePayload
discriminatorValue: OrderCreated
properties:
  order:
    type: Order
