#%RAML 1.0 DataType
(package): Message
type: OrderMessagePayload
displayName: OrderCustomerEmailSetMessagePayload
discriminatorValue: OrderCustomerEmailSet
description: |
  Generated after a successful [Set Customer Email](ctp:api:type:OrderSetCustomerEmailAction) update action.
properties:
  email?:
    type: string
    description: |
      Email address on the [Order](ctp:api:type:Order) after the [Set Customer Email](ctp:api:type:OrderSetCustomerEmailAction) update action.
  oldEmail?:
    type: string
    description: |
      Email address on the [Order](ctp:api:type:Order) before the [Set Customer Email](ctp:api:type:OrderSetCustomerEmailAction) update action.
