#%RAML 1.0 DataType
(package): Message
type: OrderMessagePayload
displayName: OrderStateTransitionMessagePayload
discriminatorValue: OrderStateTransition
description: |
  Generated after a successful [Transition State](ctp:api:type:OrderTransitionStateAction) update action.
properties:
  state:
    type: StateReference
    description: |
      [OrderState](ctp:api:type:OrderState) after the [Transition State](ctp:api:type:OrderTransitionStateAction) update action.
  oldState?:
    type: StateReference
    description: |
      [OrderState](ctp:api:type:OrderState) before the [Transition State](ctp:api:type:OrderTransitionStateAction) update action.
  force:
    type: boolean
    description: |
      Whether [State](ctp:api:type:State) transition validations were turned off during the [Transition State](ctp:api:type:OrderTransitionStateAction) update action.
