#%RAML 1.0 DataType
(package): Message
type: OrderMessagePayload
displayName: OrderBusinessUnitSetMessagePayload
discriminatorValue: OrderBusinessUnitSet
description: |
  Generated after a successful [Set Business Unit](ctp:api:type:OrderSetBusinessUnitAction) update action on Orders or [Set Business Unit](ctp:api:type:StagedOrderSetBusinessUnitAction) update action on Order Edits.
properties:
  businessUnit?:
    type: BusinessUnitKeyReference
    description: |
      [BusinessUnit](ctp:api:type:BusinessUnit) on the [Order](ctp:api:type:Order) after the [Set Business Unit](ctp:api:type:OrderSetBusinessUnitAction) update action on Orders or [Set Business Unit](ctp:api:type:StagedOrderSetBusinessUnitAction) update action on Order Edits.
  oldbusinessUnit?:
    type: BusinessUnitKeyReference
    description: |
      [BusinessUnit](ctp:api:type:BusinessUnit) on the [Order](ctp:api:type:Order) before the [Set Business Unit](ctp:api:type:OrderSetBusinessUnitAction) update action on Orders or [Set Business Unit](ctp:api:type:StagedOrderSetBusinessUnitAction) update action on Order Edits.
