#%RAML 1.0 DataType
(package): Message
(docs-uri): https://docs.commercetools.com/http-api-projects-messages.html#order-custom-line-item-added
type: OrderMessagePayload
displayName: OrderCustomLineItemAddedMessagePayload
discriminatorValue: OrderCustomLineItemAdded
description: |
  Generated after a successful [Add Custom Line Item](ctp:api:type:StagedOrderAddCustomLineItemAction) update action.
properties:
  customLineItem:
    type: CustomLineItem
    description: |
      [Custom Line Item](ctp:api:type:CustomLineItem) that was added to the [Order](ctp:api:type:Order).
