#%RAML 1.0 DataType
(package): Message
type: OrderMessagePayload
displayName: ParcelTrackingDataUpdatedMessagePayload
discriminatorValue: ParcelTrackingDataUpdated
properties:
  deliveryId:
    type: string
  parcelId:
    type: string
  trackingData?:
    type: TrackingData
