#%RAML 1.0 DataType
(package): Message
type: MessagePayload
displayName: PaymentMethodKeySetMessagePayload
discriminatorValue: PaymentMethodKeySet
(beta): true
description: |
  Generated after a successful [Set Key](ctp:api:type:PaymentMethodSetKeyAction) update action.
properties:
  key?:
    type: string
    description: |
      `key` value of the [PaymentMethod](ctp:api:type:PaymentMethod) after the [Set Key](ctp:api:type:PaymentMethodSetKeyAction) update action.
  oldKey?:
    type: string
    description: |
      `key` value of the [PaymentMethod](ctp:api:type:PaymentMethod) before the [Set Key](ctp:api:type:PaymentMethodSetKeyAction) update action.
