#%RAML 1.0 DataType
(package): Message
type: MessagePayload
displayName: PaymentMethodInfoNameSetMessagePayload
discriminatorValue: PaymentMethodInfoNameSet
(beta): true
description: |
  Generated after a successful [Set MethodInfo Name](ctp:api:type:PaymentSetMethodInfoNameAction) update action.
properties:
  name?:
    type: LocalizedString
    description: |
      Name of the Payment Method after the [Set MethodInfo Name](ctp:api:type:PaymentSetMethodInfoNameAction) update action.
  oldName?:
    type: LocalizedString
    description: |
      Name of the Payment Method before the [Set MethodInfo Name](ctp:api:type:PaymentSetMethodInfoNameAction) update action.
