#%RAML 1.0 DataType
(package): Message
type: MessagePayload
displayName: PaymentInterfaceIdSetMessagePayload
discriminatorValue: PaymentInterfaceIdSet
(beta): true
description: |
  Generated after a successful [Set InterfaceId](ctp:api:type:PaymentSetInterfaceIdAction) update action.
properties:
  interfaceId?:
    type: string
    description: |
      Interface ID of the Payment after the [Set InterfaceId](ctp:api:type:PaymentSetInterfaceIdAction) update action.
  oldInterfaceId?:
    type: string
    description: |
      Interface ID of the Payment before the [Set InterfaceId](ctp:api:type:PaymentSetInterfaceIdAction) update action.
