#%RAML 1.0 DataType
(package): Message
type: MessagePayload
displayName: PaymentStatusInterfaceCodeSetMessagePayload
discriminatorValue: PaymentStatusInterfaceCodeSet
description: |
  Generated after a successful [Set StatusInterfaceCode](ctp:api:type:PaymentSetStatusInterfaceCodeAction) update action.
properties:
  paymentId:
    (deprecated): true
    type: string
    description: |
      Unique identifier for the [Payment](ctp:api:type:Payment) for which the [Set StatusInterfaceCode](ctp:api:type:PaymentSetStatusInterfaceCodeAction) update action was applied.
  interfaceCode?:
    type: string
    description: |
      The `interfaceCode` that was set during the [Set StatusInterfaceCode](ctp:api:type:PaymentSetStatusInterfaceCodeAction) update action.
