#%RAML 1.0 DataType
(package): Message
type: MessagePayload
displayName: PaymentMethodInfoMethodSetMessagePayload
discriminatorValue: PaymentMethodInfoMethodSet
(beta): true
description: |
  Generated after a successful [Set MethodInfo Method](ctp:api:type:PaymentSetMethodInfoMethodAction) update action.
properties:
  method?:
    type: string
    description: |
      Payment Method after the [Set MethodInfo Method](ctp:api:type:PaymentSetMethodInfoMethodAction) update action.
  oldMethod?:
    type: string
    description: |
      Payment Method before the [Set MethodInfo Method](ctp:api:type:PaymentSetMethodInfoMethodAction) update action.
