#%RAML 1.0 DataType
(package): Message
(docs-uri): https://docs.commercetools.com/api/projects/messages#product-price-mode-set
type: MessagePayload
displayName: ProductPriceModeSetMessagePayload
discriminatorValue: ProductPriceModeSet
description: |
  Generated after a successful [Set PriceMode](ctp:api:type:ProductSetPriceModeAction) update action.
properties:
  to:
    type: ProductPriceModeEnum
    description: |
      The [PriceMode](ctp:api:type:ProductPriceModeEnum) that was set.
