#%RAML 1.0 DataType
(package): Message
(docs-uri): https://docs.commercetools.com/http-api-projects-messages.html#product-variant-added
type: MessagePayload
displayName: ProductVariantAddedMessagePayload
discriminatorValue: ProductVariantAdded
description: |
  Generated after a successful [Add Product Variant](ctp:api:type:ProductAddVariantAction) update action.
properties:
  variant:
    type: ProductVariant
    description: |
      Unique identifier of the [Product Variant](ctp:api:type:ProductVariant) that was added.
  staged:
    type: boolean
    description: |
      Whether the update was only applied to the staged [Product Projection](ctp:api:type:ProductProjection).
