#%RAML 1.0 DataType
(package): Message
type: MessagePayload
displayName: ProductTailoringCreatedMessagePayload
discriminatorValue: ProductTailoringCreated
description: |
  Generated after a successful [Create Product Tailoring](/../api/projects/product-tailoring#create-producttailoring) or
  [Create Product Tailoring in Store](/../api/projects/product-tailoring#create-producttailoring-in-store) request.
properties:
  key?:
    type: string
    description: |
      User-defined unique identifier of the Product Tailoring.
  store:
    type: StoreKeyReference
    description: |
      The Store to which the Product Tailoring belongs.
  productKey?:
    type: string
    description: |
      User-defined unique identifier of the Product this Product Tailoring belongs to.
  product:
    type: ProductReference
    description: |
      Reference to the Product the Product Tailoring belongs to.
  description?:
    type: LocalizedString
    description: |
      The description of the [Product Tailoring](ctp:api:type:ProductTailoring) at the time of creation.
  name?:
    type: LocalizedString
    description: |
      The name of the [Product Tailoring](ctp:api:type:ProductTailoring) at the time of creation.
  slug?:
    type: LocalizedString
    description: |
      The slug of the [Product Tailoring](ctp:api:type:ProductTailoring) at the time of creation.
  metaTitle?:
    type: LocalizedString
    description: |
      The metaTitle of the [Product Tailoring](ctp:api:type:ProductTailoring) at the time of creation.
  metaDescription?:
    type: LocalizedString
    description: |
      The metaDescription of the [Product Tailoring](ctp:api:type:ProductTailoring) at the time of creation.
  metaKeywords?:
    type: LocalizedString
    description: |
      The metaKeywords of the [Product Tailoring](ctp:api:type:ProductTailoring) at the time of creation.
  variants?:
    type: ProductVariantTailoring[]
    description: |
      The variants of the [Product Tailoring](ctp:api:type:ProductTailoring) at the time of creation.
  attributes?:
    type: ProductTailoringAttribute[]
    (beta): true
    description: |
      Attributes of the tailored Product.
      If available, these Attributes are selectively merged into the `attributes` of the corresponding [Product](ctp:api:type:Product). If the Product contains an Attribute with the same `name`, then its `value` is overwritten. Otherwise, the Attribute and its `value` are added to the Product.
  published:
    type: boolean
    description: |
      `true` if the ProductTailoring is published.
