#%RAML 1.0 DataType
(package): Message
(docs-uri): https://docs.commercetools.com/api/projects/messages#product-price-key-set
type: MessagePayload
displayName: ProductPriceKeySetMessagePayload
discriminatorValue: ProductPriceKeySet
description: |
  Generated after a successful [Set Price Key](ctp:api:type:ProductSetPriceKeyAction) update action.
properties:
  variantId:
    type: number
    format: int64
  priceId?:
    type: string
    description: |
      Unique identifier of the [Embedded Price](ctp:api:type:Price).
  oldKey?:
    type: string
    description: |
      `key` value of the [Embedded Price](ctp:api:type:Price) before the [Set Price Key](ctp:api:type:ProductSetPriceKeyAction) update action.
    pattern: ^[A-Za-z0-9_-]+$
    minLength: 2
    maxLength: 256
  key?:
    type: string
    description: |
      `key` value of the [Embedded Price](ctp:api:type:Price) after the [Set Price Key](ctp:api:type:ProductSetPriceKeyAction) update action.
    pattern: ^[A-Za-z0-9_-]+$
    minLength: 2
    maxLength: 256
  staged:
    type: boolean
    description: |
      Whether the update was only applied to the staged [Product Projection](ctp:api:type:ProductProjection).
