#%RAML 1.0 DataType
(package): Message
(docs-uri): https://docs.commercetools.com/http-api-projects-messages.html#product-price-external-discount-set
type: MessagePayload
displayName: ProductPriceExternalDiscountSetMessagePayload
discriminatorValue: ProductPriceExternalDiscountSet
description: |
  Generated after a successful [Set Discounted Embedded Price](ctp:api:type:ProductSetDiscountedPriceAction) update action.
properties:
  variantId:
    type: integer
    description: |
      Unique identifier of the [Product Variant](ctp:api:type:ProductVariant) for which the Discount was set.
  variantKey?:
    type: string
    description: |
      Key of the [Product Variant](ctp:api:type:ProductVariant) for which the Discount was set.
  sku?:
    type: string
    description: |
      SKU of the [Product Variant](ctp:api:type:ProductVariant) for which Discount was set.
  priceId:
    type: string
    description: |
      Unique identifier of the [Price](ctp:api:type:Price).
  discounted?:
    type: DiscountedPrice
    description: |
      Discounted Price for the [Product Variant](ctp:api:type:ProductVariant) for which Discount was set.
  staged:
    type: boolean
    description: |
      Whether the update was only applied to the staged [Product Projection](ctp:api:type:ProductProjection).
