#%RAML 1.0 DataType
(package): Message
type: MessagePayload
(beta): true
displayName: ProductTailoringImageAddedMessagePayload
discriminatorValue: ProductTailoringImageAdded
description: |
  Generated after a successful [Add External Image](ctp:api:type:ProductTailoringAddExternalImageAction) update action
  or after a successful [Upload Product Tailoring image](/projects/product-tailoring#upload-product-tailoring-image) request.
properties:
  store:
    type: StoreKeyReference
    description: |
      The Store to which the Product Tailoring belongs.
  productKey?:
    type: string
    description: |
      `key` of the tailored Product.
  product:
    type: ProductReference
    description: |
      Reference to the tailored Product.
  variantId:
    type: number
    format: int64
    description: |
      `id` of the tailored [ProductVariant](ctp:api:type:ProductVariant).
  image:
    type: Image
    description: |
      [Image](ctp:api:type:Image) that was added.
