#%RAML 1.0 DataType
(package): Message
(docs-uri): https://docs.commercetools.com/http-api-projects-messages.html#product-image-added
type: MessagePayload
displayName: ProductImageAddedMessagePayload
discriminatorValue: ProductImageAdded
description: |
  Generated after a successful [Add External Image](ctp:api:type:ProductAddExternalImageAction) update action or after the successful [upload of an image](/../api/projects/products#upload-product-image).
properties:
  variantId:
    type: number
    format: int64
    description: |
      Unique identifier of the [Product Variant](ctp:api:type:ProductVariant) to which the [Image](ctp:api:type:Image) was added.
  image:
    type: Image
    description: |
      [Image](ctp:api:type:Image) that was added.
  staged:
    type: boolean
    description: |
      Whether the update was only applied to the staged [Product Projection](ctp:api:type:ProductProjection).
