#%RAML 1.0 DataType
(package): Message
(docs-uri): https://docs.commercetools.com/http-api-projects-messages.html#reviewratingsetmessage
type: MessagePayload
displayName: ReviewRatingSetMessagePayload
discriminatorValue: ReviewRatingSet
properties:
  oldRating?:
    type: number
  newRating?:
    type: number
  includedInStatistics:
    type: boolean
  target?:
    type: Reference
