#%RAML 1.0 DataType
(package): Message
type: ShoppingListMessagePayload
displayName: ShoppingListLineItemRemovedMessagePayload
discriminatorValue: ShoppingListLineItemRemoved
description: |
  Generated after a successful [Remove ShoppingListLineItem](ctp:api:type:ShoppingListRemoveLineItemAction) update action.
properties:
  lineItem:
    type: ShoppingListLineItem
    description: |
      [Line Item](ctp:api:type:ShoppingListLineItem) that was removed from the [ShoppingList](ctp:api:type:ShoppingList).
