#%RAML 1.0 DataType
(package): Message
(docs-uri): https://docs.commercetools.com/http-api-message-types#shoppingliststoreset-message
type: MessagePayload
displayName: ShoppingListStoreSetMessagePayload
discriminatorValue: ShoppingListStoreSet
properties:
  store:
    type: StoreKeyReference
