#%RAML 1.0 DataType
(package): Message
(docs-uri): https://docs.commercetools.com/api/projects/messages#stagedquotevalidtosetmessage
type: MessagePayload
displayName: StagedQuoteValidToSetMessagePayload
discriminatorValue: StagedQuoteValidToSet
description: |
  Generated after a successful [Set Valid To](ctp:api:type:StagedQuoteSetValidToAction) update action.
properties:
  validTo:
    type: datetime
    description: |
      Expiration date for the Staged Quote after the [Set Valid To](ctp:api:type:StagedQuoteSetValidToAction) update action.
