#%RAML 1.0 DataType
(package): Message
(docs-uri): https://docs.commercetools.com/api/projects/messages#standalone-price-valid-until-set
type: MessagePayload
displayName: StandalonePriceValidUntilSetMessagePayload
discriminatorValue: StandalonePriceValidUntilSet
description: |
  Generated after a successful [Set Valid Until](ctp:api:type:StandalonePriceSetValidUntilAction) update action.
properties:
  validUntil?:
    type: datetime
    description: |
      Value of [StandalonePrice](ctp:api:type:StandalonePrice) `validUntil` after the [Set Valid Until](ctp:api:type:StandalonePriceSetValidUntilAction) update action.
  previousValidUntil?:
    type: datetime
    description: |
      Value of [StandalonePrice](ctp:api:type:StandalonePrice) `validUntil` before the [Set Valid Until](ctp:api:type:StandalonePriceSetValidUntilAction) update action.
