#%RAML 1.0 DataType
(package): Message
(docs-uri): https://docs.commercetools.com/api/projects/messages#standalone-price-valid-from-and-until-set
type: MessagePayload
displayName: StandalonePriceValidFromAndUntilSetMessagePayload
discriminatorValue: StandalonePriceValidFromAndUntilSet
description: |
  Generated after a successful [Set Valid From and Until](ctp:api:type:StandalonePriceSetValidFromAndUntilAction) update action.
properties:
  validFrom?:
    type: datetime
    description: |
      Value of [StandalonePrice](ctp:api:type:StandalonePrice) `validFrom` after the [Set Valid From and Until](ctp:api:type:StandalonePriceSetValidFromAndUntilAction) update action.
  previousValidFrom?:
    type: datetime
    description: |
      Value of [StandalonePrice](ctp:api:type:StandalonePrice) `validFrom` before the [Set Valid From and Until](ctp:api:type:StandalonePriceSetValidFromAndUntilAction) update action.
  validUntil?:
    type: datetime
    description: |
      Value of [StandalonePrice](ctp:api:type:StandalonePrice) `validUntil` after the [Set Valid From and Until](ctp:api:type:StandalonePriceSetValidFromAndUntilAction) update action.
  previousValidUntil?:
    type: datetime
    description: |
      Value of [StandalonePrice](ctp:api:type:StandalonePrice) `validUntil` before the [Set Valid From and Until](ctp:api:type:StandalonePriceSetValidFromAndUntilAction) update action.
