#%RAML 1.0 DataType
(package): Message
(docs-uri): https://docs.commercetools.com/api/projects/messages#storedistributionchannelschangedmessage
type: MessagePayload
displayName: StoreDistributionChannelsChangedMessagePayload
discriminatorValue: StoreDistributionChannelsChanged
description: |
  Generated after a successful [Add Distribution Channel](ctp:api:type:StoreAddDistributionChannelAction),
  [Remove Distribution Channel](ctp:api:type:StoreRemoveDistributionChannelAction), or
  [Set Distribution Channels](ctp:api:type:StoreSetDistributionChannelsAction) update action.
properties:
  addedDistributionChannels:
    type: array
    items: ChannelReference
    description: The product distribution channels that have been added.
  removedDistributionChannels:
    type: array
    items: ChannelReference
    description: |
      The product distribution channels that have been removed.
