#%RAML 1.0 DataType
(package): Message
type: MessagePayload
displayName: StoreNameSetMessagePayload
discriminatorValue: StoreNameSet
description: |
  Generated after a successful [Set Name](ctp:api:type:StoreSetNameAction) update action.
properties:
  name?:
    type: LocalizedString
    description: |
      Name of the [Store](ctp:api:type:Store) set during the [Set Name](ctp:api:type:StoreSetNameAction) update action.
  nameAllLocales?:
    type: array
    items: LocalizedString
    description: |
      Names set for the [Store](ctp:api:type:Store) in different locales.
