#%RAML 1.0 DataType
(package): Cart
type: CartUpdateAction
displayName: CartSetDirectDiscountsIgnoreCartDiscountsAction
discriminatorValue: setDirectDiscountsIgnoreCartDiscounts
example: !include ../../../examples/Cart/CartSetDirectDiscountsIgnoreCartDiscountsAction.json
description: |
  Determines whether the [Direct Discounts](ctp:api:type:DirectDiscount) on the Cart replace the [Cart Discounts](ctp:api:type:CartDiscount) of the [Project](ctp:api:type:Project), or apply alongside them.
properties:
  directDiscountsIgnoreCartDiscounts?:
    type: boolean
    description: |
      - If `true`, only [Direct Discounts](ctp:api:type:DirectDiscount) apply to the Cart. Matching [Cart Discounts](ctp:api:type:CartDiscount) are ignored, and Discount Codes cannot be added.

      The value can be set to `true` only if the Cart does not have both `discountCodes` and `directDiscounts`.
      - If `false`, Cart Discounts, Discount Codes, and Direct Discounts apply to the Cart.
    default: true
