#%RAML 1.0 DataType
(package): Cart
type: CartUpdateAction
displayName: CartSetShippingMethodTaxAmountAction
discriminatorValue: setShippingMethodTaxAmount
example: !include ../../../examples/Cart/CartSetShippingMethodTaxAmountAction.json
description: |
  A Shipping Method tax amount can be set if the Cart has the `ExternalAmount` [TaxMode](ctp:api:type:TaxMode).
properties:
  shippingKey?:
    type: string
    description: |
      `key` of the [ShippingMethod](ctp:api:type:ShippingMethod) to update.
      This is required and valid only for Carts with `Multiple` [ShippingMode](ctp:api:type:ShippingMode).
      An [InvalidOperation](ctp:api:type:InvalidOperationError) error is returned if `shippingKey` is provided for Carts with `Single` [ShippingMode](ctp:api:type:ShippingMode), or omitted for Carts with `Multiple` [ShippingMode](ctp:api:type:ShippingMode).
  externalTaxAmount?:
    type: ExternalTaxAmountDraft
    description: |
      Value to set.
      If empty, any existing value is removed.
