#%RAML 1.0 DataType
(package): Cart
(docs-uri): https://docs.commercetools.com/api/projects/carts#set-shipping-custom-type
type: CartUpdateAction
displayName: CartSetShippingCustomTypeAction
discriminatorValue: setShippingCustomType
example: !include ../../../examples/Cart/CartSetShippingCustomTypeAction.json
properties:
  shippingKey?:
    type: string
    description: |
      User-defined unique identifier of the Shipping Method in a Cart with `Multiple` [ShippingMode](ctp:api:type:ShippingMode).
  type?:
    type: TypeResourceIdentifier
    description: |
      Defines the [Type](ctp:api:type:Type) that extends the `shippingAddress` with [Custom Fields](/../api/projects/custom-fields).
      If absent, any existing Type and Custom Fields are removed from the `shippingAddress`.
  fields?:
    type: FieldContainer
    description: |
      Sets the [Custom Fields](/../api/projects/custom-fields) fields for the `shippingAddress`.
