#%RAML 1.0 DataType
(package): Cart
(docs-uri): https://docs.commercetools.com/api/projects/carts#set-customlineitem-taxamount
type: CartUpdateAction
displayName: CartSetCustomLineItemTaxAmountAction
discriminatorValue: setCustomLineItemTaxAmount
example: !include ../../../examples/Cart/CartSetCustomLineItemTaxAmountAction.json
description: |
  Can be used if the Cart has the `ExternalAmount` [TaxMode](ctp:api:type:TaxMode).
properties:
  customLineItemId:
    type: string
    description: |
      `id` of the [CustomLineItem](ctp:api:type:CustomLineItem) to update.
  externalTaxAmount?:
    type: ExternalTaxAmountDraft
    description: |
      Value to set.
      If empty, any existing value is removed.
