#%RAML 1.0 DataType
(package): Cart
(docs-uri): https://docs.commercetools.com/api/projects/carts#set-custom-shipping-method
type: CartUpdateAction
displayName: CartSetCustomShippingMethodAction
discriminatorValue: setCustomShippingMethod
example: !include ../../../examples/Cart/CartSetCustomShippingMethodAction.json
description: |
  To set the Cart's custom Shipping Method (independent of the [ShippingMethods](ctp:api:type:ShippingMethod) managed through
  the [Shipping Methods API](/projects/shippingMethods)) the Cart must have
  the `Single` [ShippingMode](ctp:api:type:ShippingMode) and a `shippingAddress`.

  To unset a custom Shipping Method on a Cart, use the [Set ShippingMethod](ctp:api:type:CartSetShippingMethodAction) update action
  without the `shippingMethod` field instead.
properties:
  shippingMethodName:
    type: string
    description: |
      Name of the custom Shipping Method.
  shippingRate:
    type: ShippingRateDraft
    description: |
      Determines the shipping price.
  taxCategory?:
    type: TaxCategoryResourceIdentifier
    description: |
      Tax Category used to determine the Tax Rate when the Cart has the `Platform` [TaxMode](ctp:api:type:TaxMode).
  externalTaxRate?:
    type: ExternalTaxRateDraft
    description: |
      External Tax Rate for the `shippingRate` to be set if the Cart has the `External` [TaxMode](ctp:api:type:TaxMode).
