#%RAML 1.0 DataType
(package): Cart
type: CartUpdateAction
displayName: CartAddShoppingListAction
discriminatorValue: addShoppingList
example: !include ../../../examples/Cart/CartAddShoppingListAction.json
description: |
  Adds all [LineItems](ctp:api:type:LineItem) of a [ShoppingList](ctp:api:type:ShoppingList) to the Cart.
properties:
  shoppingList:
    type: ShoppingListResourceIdentifier
    description: |
      Shopping List that contains the Line Items to be added.
  distributionChannel?:
    type: ChannelResourceIdentifier
    description: |
      `distributionChannel` to set for all [LineItems](ctp:api:type:LineItem) that are added to the Cart.
      The Channel must have the `ProductDistribution` [ChannelRoleEnum](ctp:api:type:ChannelRoleEnum).
  supplyChannel?:
    type: ChannelResourceIdentifier
    description: |
      `supplyChannel` to set for all [LineItems](ctp:api:type:LineItem) that are added to the Cart.
      The Channel must have the `InventorySupply` [ChannelRoleEnum](ctp:api:type:ChannelRoleEnum).
