#%RAML 1.0 DataType
(package): Cart
(docs-uri): https://docs.commercetools.com/api/projects/carts#change-taxcalculationmode
type: CartUpdateAction
displayName: CartChangeTaxCalculationModeAction
discriminatorValue: changeTaxCalculationMode
example: !include ../../../examples/Cart/CartChangeTaxCalculationModeAction.json
description: |
  Changing the tax calculation mode leads to [recalculation of taxes](/../api/carts-orders-overview#cart-tax-calculation).
properties:
  taxCalculationMode:
    type: TaxCalculationMode
    description: |
      New value to set.
