#%RAML 1.0 DataType
(package): Cart
(docs-uri): https://docs.commercetools.com/api/projects/carts#add-shippingmethod
type: CartUpdateAction
displayName: CartAddShippingMethodAction
discriminatorValue: addShippingMethod
example: !include ../../../examples/Cart/CartAddShippingMethodAction.json
description: |
  Adds a Shipping Method for a specified shipping address to a Cart with `Multiple` [ShippingMode](ctp:api:type:ShippingMode).
properties:
  shippingKey:
    type: string
    description: |
      User-defined identifier for the [Shipping](ctp:api:type:Shipping) that must be unique across the Cart with `Multiple` [ShippingMode](ctp:api:type:ShippingMode).
  shippingMethod:
    type: ShippingMethodResourceIdentifier
    description: |
      RecourceIdentifier to a [ShippingMethod](ctp:api:type:ShippingMethod) to add to the Cart with `Multiple` [ShippingMode](ctp:api:type:ShippingMode).
      If the referenced Shipping Method has a predicate that does not match the Cart, an [InvalidOperation](ctp:api:type:InvalidOperationError) error is returned.
  shippingAddress:
    type: BaseAddress
    description: |
      Determines the shipping rate and Tax Rate of the Line Items.
  shippingRateInput?:
    type: ShippingRateInputDraft
    description: |
      Input used to select a [ShippingRatePriceTier](ctp:api:type:ShippingRatePriceTier).
      The data type of this field depends on the `shippingRateInputType.type` configured in the [Project](ctp:api:type:Project):

      - If `CartClassification`, it must be [ClassificationShippingRateInputDraft](ctp:api:type:ClassificationShippingRateInputDraft).
      - If `CartScore`, it must be [ScoreShippingRateInputDraft](ctp:api:type:ScoreShippingRateInputDraft).
      - If `CartValue`, it cannot be set.

  externalTaxRate?:
    type: ExternalTaxRateDraft
    description: |
      Tax Rate used to tax a shipping expense if the Cart has the `External` [TaxMode](ctp:api:type:TaxMode).
  deliveries?:
    type: DeliveryDraft[]
    description: |
      Deliveries to be shipped with the referenced Shipping Method.
  custom?:
    type: CustomFieldsDraft
    description: |
      Custom Fields for the Shipping Method.
