#%RAML 1.0 DataType
(package): Cart
type: CartUpdateAction
displayName: CartSetCartTotalTaxAction
discriminatorValue: setCartTotalTax
example: !include ../../../examples/Cart/CartSetCartTotalTaxAction.json
description: |
  Can be used if the Cart has the `ExternalAmount` [TaxMode](ctp:api:type:TaxMode). This update action adds the `taxedPrice` field to the Cart. It sets the `totalGross` amount, and Composable Commerce calculates the `totalNet` and `totalTax` values based on the provided `externalTotalGross`.
  You must use this update action after any price-affecting change occurs within the Cart.

properties:
  externalTotalGross:
    type: Money
    description: |
      The total gross amount of the Cart, including tax. This value is used to calculate the `totalNet` and `totalTax` fields of the Cart's `taxedPrice`.
  externalTaxPortions?:
    type: TaxPortionDraft[]
    description: |
      Set if the `externalTotalGross` price is a sum of portions with different tax rates.
