#%RAML 1.0 DataType
(package): Cart
(docs-uri): https://docs.commercetools.com/api/projects/carts#apply-deltatolineitemshippingdetailstargets
type: CartUpdateAction
displayName: CartApplyDeltaToLineItemShippingDetailsTargetsAction
discriminatorValue: applyDeltaToLineItemShippingDetailsTargets
example: !include ../../../examples/Cart/CartApplyDeltaToLineItemShippingDetailsTargetsAction.json
description: |
  To override the shipping details, see [Set LineItemShippingDetails](ctp:api:type:CartSetLineItemShippingDetailsAction).
properties:
  lineItemId?:
    type: string
    description: |
      `id` of the [LineItem](ctp:api:type:LineItem) to update. Either `lineItemId` or `lineItemKey` is required.
  lineItemKey?:
    type: string
    description: |
      `key` of the [LineItem](ctp:api:type:LineItem) to update. Either `lineItemId` or `lineItemKey` is required.
  targetsDelta:
    type: ItemShippingTarget[]
    description: |
      Using positive or negative quantities increases or decreases the number of items shipped to an address.
