#%RAML 1.0 DataType
(package): Cart
example: !include ../../../examples/Cart/CartSetPurchaseOrderNumberAction.json
type: CartUpdateAction
displayName: CartSetPurchaseOrderNumberAction
discriminatorValue: setPurchaseOrderNumber
description: |
  Updates the `purchaseOrderNumber` field and produces the [CartPurchaseOrderNumberSet](ctp:api:type:CartPurchaseOrderNumberSetMessage) Message.
properties:
  purchaseOrderNumber?:
    type: string
    description: |
      Value to set.
      If empty, any existing value is removed.
