#%RAML 1.0 DataType
(package): Cart
type: CartUpdateAction
displayName: CartFreezeCartAction
discriminatorValue: freezeCart
example: !include ../../../examples/Cart/CartFreezeCartAction.json
description: |
  Changes the [CartState](ctp:api:type:CartState) from `Active` to `Frozen`. Results in a [Frozen Cart](ctp:api:type:FrozenCarts).
  Fails with [InvalidOperation](ctp:api:type:InvalidOperationError) error when the Cart is empty.
