#%RAML 1.0 DataType
(package): Cart
(docs-uri): https://docs.commercetools.com/api/projects/carts#set-lineitem-shippingdetails
type: CartUpdateAction
displayName: CartSetLineItemShippingDetailsAction
discriminatorValue: setLineItemShippingDetails
example: !include ../../../examples/Cart/CartSetLineItemShippingDetailsAction.json
properties:
  lineItemId?:
    type: string
    description: |
      `id` of the [LineItem](ctp:api:type:LineItem) to update. Either `lineItemId` or `lineItemKey` is required.
  lineItemKey?:
    type: string
    description: |
      `key` of the [LineItem](ctp:api:type:LineItem) to update. Either `lineItemId` or `lineItemKey` is required.
  shippingDetails?:
    type: ItemShippingDetailsDraft
    description: |
      Value to set.
      If empty, the existing value is removed.
