#%RAML 1.0 DataType
(package): DiscountGroup
type: Reference
displayName: DiscountGroupReference
discriminatorValue: discount-group
(beta): true
description: |
  [Reference](ctp:api:type:Reference) to a [DiscountGroup](ctp:api:type:DiscountGroup).
properties:
  id:
    type: string
    description: |
      Unique identifier of the referenced [DiscountGroup](ctp:api:type:DiscountGroup).
  obj?:
    type: DiscountGroup
    description: |
      Contains the representation of the expanded DiscountGroup.
      Only present in responses to requests with [Reference Expansion](/../api/general-concepts#reference-expansion) for DiscountGroups.
