#%RAML 1.0 DataType
(package): DiscountGroup
displayName: DiscountGroupDraft
type: object
example: !include ../../examples/discount-group-create.example.json
(beta): true
properties:
  name?:
    type: LocalizedString
    description: |
      Name of the DiscountGroup.
  key:
    type: string
    description: |
      User-defined unique identifier for the DiscountGroup.
    pattern: ^[A-Za-z0-9_-]+$
    minLength: 2
    maxLength: 256
  description?:
    type: LocalizedString
    description: |
      Description for the DiscountGroup.
  sortOrder:
    type: string
    description: |
      Value between `0` and `1` that determines the order in which the CartDiscount from the DiscountGroup will be applied; a CartDiscount with a higher value will be prioritized.

      The sort order must be unique among all DiscountGroups and CartDiscounts.
  isActive?:
    type: boolean
    description: |
      A DiscountGroup must be active for its CartDiscounts to be considered during discount application.
    default: true
