#%RAML 1.0 DataType
(package): RecurringOrder
type: RecurringOrderScopeDraft
displayName: NonRecurringOrdersOnlyDraft
discriminatorValue: NonRecurringOrdersOnly
description: |
  Applies Cart Discounts to non-recurring Orders.
