#%RAML 1.0
---
title: commercetools MIST API
uses:
  annotations: annotations.raml
(annotations.products):
  - InStore
version: v1
mediaType: application/json
baseUri: https://api.nebulaterra.com
types: !include types/types.raml

/location: !include resources/location.raml
/role: !include resources/role.raml
/session: !include resources/session.raml
/workstation: !include resources/workstation.raml
/workstations: !include resources/workstations.raml
