#%RAML 1.0 DataType
(annotations.package): RecurringPayment
(annotations.beta): true
type: RecurringPaymentUpdateAction
displayName: RecurringPaymentSetPaymentMethodConfigurationUpdateAction
discriminatorValue: setPaymentMethodConfiguration
description: |
  Sets the PaymentMethodConfigurations of a RecurringPayment, replacing any existing ones. Checkout only supports processing this array with one PaymentMethodConfiguration.
properties:
  paymentMethodConfigurations:
    type: array
    items: PaymentMethodConfiguration
    description: |
      PaymentMethod and Connector to set.
    minItems: 1
