#%RAML 1.0 DataType
(annotations.package): RecurringPayment
(annotations.beta): true
type: RecurringPaymentUpdateAction
displayName: RecurringPaymentSetKeyUpdateAction
discriminatorValue: setKey
description: |
  Sets or unsets the key of a RecurringPayment.
properties:
  key?:
    type: string
    description: |
      Key to set. If omitted, any existing value is removed.
