#%RAML 1.0 DataType
(annotations.package): Connector
type: ConnectorUpdateAction
displayName: ConnectorSetCreatorCompanyAction
discriminatorValue: setCreatorCompany
example: !include ../../../examples/connector/updates/ConnectorSetCreatorCompanyAction.json
description: |
  Updates the company of the creator.
properties:
  creatorCompany:
    type: string
    description: Value to set.
