#%RAML 1.0 DataType
(annotations.package): Connector
type: ConnectorUpdateAction
displayName: ConnectorSetDocumentationUrlAction
discriminatorValue: setDocumentationUrl
example: !include ../../../examples/connector/updates/ConnectorSetDocumentationUrlAction.json
description: |
  Updates the documentation URL of the Connector.
properties:
  documentationUrl:
    type: string
    description: Value to set.
