#%RAML 1.0 DataType
(annotations.package): Connector
type: ConnectorUpdateAction
displayName: ConnectorAddCertificationCommentAction
discriminatorValue: addCertificationComment
example: !include ../../../examples/connector/updates/ConnectorAddCertificationCommentAction.json
description: |
  Add a comment during the certification process of the Connector.
properties:
  comment:
    type: string
    description: Comment to add.
