#%RAML 1.0 DataType
(annotations.package): Connector
type: ConnectorUpdateAction
displayName: ConnectorTriggerCertificationAction
example: !include ../../../examples/connector/updates/ConnectorTriggerCertificationAction.json
discriminatorValue: triggerCertification
description: |
  After triggering the certification process you cannot update the Connector until the review process is complete.
