#%RAML 1.0 DataType
(annotations.package): Connector
type: ConnectorUpdateAction
displayName: ConnectorSetCreatorNoOfDevelopersAction
discriminatorValue: setCreatorNoOfDevelopers
example: !include ../../../examples/connector/updates/ConnectorSetCreatorNoOfDevelopersAction.json
description: |
  Updates the number of developers within the creator's company.
properties:
  creatorNoOfDevelopers:
    type: integer
    description: Value to set.
