#%RAML 1.0 DataType
(annotations.package): Connector
type: ConnectorUpdateAction
displayName: ConnectorSetCreatorTitleAction
discriminatorValue: setCreatorTitle
example: !include ../../../examples/connector/updates/ConnectorSetCreatorTitleAction.json
description: |
  Updates the creator's title.
properties:
  creatorTitle:
    type: string
    description: Value to set.
