#%RAML 1.0 DataType
(annotations.package): Connector
type: ConnectorUpdateAction
displayName: ConnectorSetCreatorEmailAction
discriminatorValue: setCreatorEmail
example: !include ../../../examples/connector/updates/ConnectorSetCreatorEmailAction.json
description: |
  Updates the creator's contact email address.
properties:
  creatorEmail:
    type: string
    description: Value to set.
