#%RAML 1.0 DataType
(annotations.package): Connector
type: ConnectorUpdateAction
displayName: ConnectorSetSupportedRegionsAction
discriminatorValue: setSupportedRegions
example: !include ../../../examples/connector/updates/ConnectorSetSupportedRegionsAction.json
description: |
  Updates the Regions that the Connector can be deployed in.
properties:
  regions:
    type: common.Region[]
    description: Value to set. If empty, clients can choose any Region supported in Connect.
