#%RAML 1.0 DataType
(annotations.package): Connector
type: ConnectorUpdateAction
displayName: ConnectorSetRepositoryAction
discriminatorValue: setRepository
example: !include ../../../examples/connector/updates/ConnectorSetRepositoryAction.json
description: |
  Updates the GitHub repository details of the Connector.
properties:
  url:
    type: string
    description: New HTTPS or SSH GitHub URL to assign to the Connector.
  tag:
    type: string
    description: New Git tag to assign to the Connector.
