#%RAML 1.0 DataType
(annotations.package): Connector
type: ConnectorUpdateAction
displayName: ConnectorUnlistAction
example: !include ../../../examples/connector/updates/ConnectorUnlistAction.json
discriminatorValue: unlist
description: |
  Removes a certified and listed Connector from search results and listings. This update action does not affect deployed instances of the Connector.
