#%RAML 1.0 DataType
(annotations.package): Connector
type: ConnectorUpdateAction
displayName: ConnectorSetDescriptionAction
discriminatorValue: setDescription
example: !include ../../../examples/connector/updates/ConnectorSetDescriptionAction.json
description: |
  Updates the description in Connector.
properties:
  description:
    type: string
    description: Value to set.
