#%RAML 1.0 DataType
(annotations.package): Connector
type: ConnectorUpdateAction
displayName: ConnectorSetIntegrationTypesAction
discriminatorValue: setIntegrationTypes
example: !include ../../../examples/connector/updates/ConnectorSetIntegrationTypesAction.json
description: |
  Updates the integration types of the Connector.
properties:
  integrationTypes:
    type: common.IntegrationType[]
    description: New value to set.