#%RAML 1.0 DataType
(package): Inventory
(docs-uri): https://docs.commercetools.com/http-api-projects-inventory.html#set-restockableindays


type: InventoryEntryUpdateAction
displayName: InventorySetRestockableInDaysAction
discriminatorValue: setRestockableInDays
properties:
    restockableInDays?:
        type: number
        format: int64
