#%RAML 1.0 DataType
(package): Inventory
(docs-uri): https://docs.commercetools.com/http-api-projects-inventory.html#inventoryentry

displayName: InventoryEntry
(updateType): InventoryUpdate
type: LoggedResource
properties:
  sku:
    type: string
  supplyChannel?:
    (hasUpdateAction):
      action: setSupplyChannel
      docsAnchor: set-supplychannel
    type: ChannelReference
  quantityOnStock:
    type: number
    format: int64
    (hasUpdateActions):
      - action: addQuantity
        fields:
          quantity:
            type: number
            format: int64
      - action: removeQuantity
        fields:
          quantity:
            type: number
            format: int64
      - action: changeQuantity
        fields:
          quantity:
            type: number
            format: int64
  availableQuantity:
    type: number
    format: int64
  restockableInDays?:
    (hasUpdateAction):
      action: setRestockableInDays
      docsAnchor: set-restockableindays
    type: number
    format: int64
  expectedDelivery?:
    (hasUpdateAction):
      action: setExpectedDelivery
      docsAnchor: set-expecteddelivery
    type: datetime
  custom?:
    type: CustomFields
    (hasUpdateActions):
      - action: setCustomType
        fields:
          type?: TypeReference
          fields?: FieldContainer
      - action: setCustomField
        docsAnchor: set-customfield
        fields:
          name: string
          value?: any
