#%RAML 1.0 DataType
(package): Inventory


type: InventoryEntryUpdateAction
displayName: InventoryRemoveQuantityAction
discriminatorValue: removeQuantity
properties:
    quantity:
        type: number
        format: int64
