#%RAML 1.0 DataType
(package): Channel
(docs-uri): https://docs.commercetools.com/http-api-projects-channels.html#change-key
type: ChannelUpdateAction
displayName: ChannelChangeKeyAction
discriminatorValue: changeKey
(postman-example): !include ../../../examples/Channel/ChannelChangeKeyAction.json
properties:
  key:
    type: string
