#%RAML 1.0 DataType
(package): Channel

displayName: Channel

type: Resource
(generate-collection): true
properties:
    key:
        type: string
    roles:
        (generator-type): string[]
        type: ChannelRoleEnum[]
    name?:
        type: LocalizedString
    description?:
        type: LocalizedString
    address?:
        type: Address
    reviewRatingStatistics?:
        type: ReviewRatingStatistics
    custom?:
        type: CustomFields
    geoLocation?:
        type: GeoJsonPoint | GeoJson
