#%RAML 1.0 DataType
(package): Channel
(docs-uri): https://docs.commercetools.com/http-api-projects-channels.html#channel

displayName: Channel
(updateType): ChannelUpdate

type: Resource
properties:
    key:
        type: string
    roles:
        type: ChannelRoleEnum[]
    name?:
        type: LocalizedString
    description?:
        type: LocalizedString
    address?:
        type: Address
    reviewRatingStatistics?:
        type: ReviewRatingStatistics
    custom?:
        type: CustomFields
    geoLocation?:
        type: GeoJsonPoint | GeoJson
