#%RAML 1.0 DataType
(package): Channel
(docs-uri): https://docs.commercetools.com/http-api-projects-channels.html#channel

displayName: Channel
(updateType): ChannelUpdate

type: Resource
properties:
  key:
    (hasSimpleUpdateAction): changeKey
    type: string
  roles:
    type: ChannelRoleEnum[]
    (hasUpdateActions):
      - action: setRoles
        fields:
          roles: ChannelRoleEnum[]
      - action: addRoles
        fields:
          roles: ChannelRoleEnum[]
      - action: removeRoles
        fields:
          roles: ChannelRoleEnum[]
  name?:
    type: LocalizedString
    (hasUpdateAction):
      action: changeName
      required: true
  description?:
    type: LocalizedString
    (hasUpdateAction):
      action: changeDescription
      required: true
  address?:
    (hasSimpleUpdateAction): setAddress
    type: Address
  reviewRatingStatistics?:
    type: ReviewRatingStatistics
  custom?:
    type: CustomFields
    (hasUpdateActions):
      - action: setCustomType
        fields:
          type?: TypeReference
          fields?: FieldContainer
      - action: setCustomField
        docsAnchor: set-customfield
        fields:
          name: string
          value?: any
  geoLocation?:
    (hasUpdateAction):
      action: setGeoLocation
      docsAnchor: set-geolocation
    type: GeoJsonPoint | GeoJson
  lastModifiedBy?:
    type: LastModifiedBy
  createdBy?:
    type: CreatedBy
