#%RAML 1.0 DataType

displayName: ChannelDraft
uses:
    api: ../types.lib.raml
type: object
properties:
    key:
        type: string
    roles?:
        type: string[]
    name?:
        type: api.LocalizedString
    description?:
        type: api.LocalizedString
    address?:
        type: api.Address
    custom?:
        type: api.CustomFields
    geoLocation?:
        type: api.GeoJsonPoint | api.GeoJson
