#%RAML 1.0 DataType
(package): Channel


type: Update
displayName: ChannelUpdate
properties:
    actions:
        (generator-type): ChannelUpdateAction[]
        type: array
        items: ChannelUpdateAction |
            ChannelAddRolesAction |
            ChannelChangeDescriptionAction |
            ChannelChangeKeyAction |
            ChannelChangeNameAction |
            ChannelRemoveRolesAction |
            ChannelSetAddressAction |
            ChannelSetCustomFieldAction |
            ChannelSetCustomTypeAction |
            ChannelSetGeolocationAction |
            ChannelSetRolesAction
