#%RAML 1.0 DataType

displayName: Channel
uses:
    api: ../types.lib.raml
type: api.Resource
(generate-collection): true
properties:
    key:
        type: string
    roles:
        type: string[]
    name?:
        type: api.LocalizedString
    description?:
        type: api.LocalizedString
    address?:
        type: api.Address
    reviewRatingStatistics?:
        type: api.ReviewRatingStatistics
    custom?:
        type: api.CustomFields
    geoLocation?:
        type: api.GeoJsonPoint | api.GeoJson
