#%RAML 1.0 DataType
(package): Message
(docs-uri): https://docs.commercetools.com/http-api-projects-messages.html#message

type: Resource
displayName: MessageContext
properties:
  sequenceNumber:
    type: number
    format: int64
  resource:
    type: Reference
  resourceVersion:
    type: number
    format: int64
  type:
    type: string
