#%RAML 1.0 DataType
(package): Message

type: MessagePayload
displayName: OrderReturnShipmentStateChangedMessage
discriminatorValue: OrderReturnShipmentStateChanged
properties:
    returnItemId:
        type: string
    returnShipmentState:
        type: ReturnShipmentState
