#%RAML 1.0 DataType
(package): Message
(docs-uri): https://docs.commercetools.com/http-api-projects-messages.html#productvariantdeleted-message
type: Message
displayName: ProductVariantDeletedMessage
discriminatorValue: ProductVariantDeleted
properties:
  removedImageUrls:
    type: array
  variant:
    type: ProductVariant
    removedImageUrls:
      type: array
      items: string
    variant:
      type: ProductVariant
