#%RAML 1.0 DataType
(package): Message
(docs-uri): https://docs.commercetools.com/http-api-message-types.html#productpriceexternaldiscountset-message
type: Message
displayName: ProductPriceExternalDiscountSetMessage
discriminatorValue: ProductPriceExternalDiscountSet
properties:
  variantId:
    type: integer
  variantKey?:
    type: string
  sku?:
    type: string
  priceId:
    type: string
  discounted?:
    type: DiscountedPrice
  staged:
    type: boolean
  id:
    description: ''
    type: string
  version:
    description: ''
    type: number
  createdAt:
    description: ''
    type: datetime
  lastModifiedAt:
    description: ''
    type: datetime
  lastModifiedBy?:
    description: ''
    type: LastModifiedBy
  createdBy?:
    description: ''
    type: CreatedBy
  sequenceNumber:
    description: ''
    type: number
  resource:
    description: ''
    type: Reference
  resourceVersion:
    description: ''
    type: number
  resourceUserProvidedIdentifiers?:
    description: ''
    type: UserProvidedIdentifiers
