#%RAML 1.0 DataType
(package): Message
(docs-uri): https://docs.commercetools.com/http-api-projects-messages.html#productpublished-message

type: Message
displayName: ProductPublishedMessage
discriminatorValue: ProductPublished
properties:
    removedImageUrls:
        type: array
    productProjection:
        type: ProductProjection
    scope:
        type: ProductPublishScope
