#%RAML 1.0 DataType
(package): Message

type: Message
displayName: ProductDeletedMessage
discriminatorValue: ProductDeleted
properties:
    removedImageUrls:
        type: array
    currentProjection:
        type: ProductProjection
