#%RAML 1.0 DataType
(package): Message
(docs-uri): https://docs.commercetools.com/http-api-projects-messages.html#productstatetransition-message
type: Message
displayName: ProductStateTransitionMessage
discriminatorValue: ProductStateTransition
properties:
  state:
    type: StateReference
  force:
    type: boolean
  id:
    description: ''
    type: string
  version:
    description: ''
    type: number
  createdAt:
    description: ''
    type: datetime
  lastModifiedAt:
    description: ''
    type: datetime
  lastModifiedBy?:
    description: ''
    type: LastModifiedBy
  createdBy?:
    description: ''
    type: CreatedBy
  sequenceNumber:
    description: ''
    type: number
  resource:
    description: ''
    type: Reference
  resourceVersion:
    description: ''
    type: number
  resourceUserProvidedIdentifiers?:
    description: ''
    type: UserProvidedIdentifiers
