#%RAML 1.0 DataType
(package): Message
(docs-uri): https://docs.commercetools.com/http-api-projects-messages.html#reviewratingset-message
type: Message
displayName: ReviewRatingSetMessage
discriminatorValue: ReviewRatingSet
properties:
  oldRating?:
    type: number
  newRating?:
    type: number
  includedInStatistics:
    type: boolean
  target?:
    type: Reference
  id:
    description: ''
    type: string
  version:
    description: ''
    type: number
  createdAt:
    description: ''
    type: datetime
  lastModifiedAt:
    description: ''
    type: datetime
  lastModifiedBy?:
    description: ''
    type: LastModifiedBy
  createdBy?:
    description: ''
    type: CreatedBy
  sequenceNumber:
    description: ''
    type: number
  resource:
    description: ''
    type: Reference
  resourceVersion:
    description: ''
    type: number
  resourceUserProvidedIdentifiers?:
    description: ''
    type: UserProvidedIdentifiers
