#%RAML 1.0 DataType
(package): Extension
type: HttpDestinationAuthentication
displayName: AuthorizationHeaderAuthentication
discriminatorValue: AuthorizationHeader
description: |
  The `Authorization` header will be set to the content of `headerValue`. The authentication scheme (such as `Basic` or `Bearer`) should be included in the `headerValue`.

  For example, the `headerValue` for [Basic Authentication](https://datatracker.ietf.org/doc/html/rfc7617) should be set to `Basic QWxhZGRpbjpvcGVuIHNlc2FtZQ==`.
properties:
  headerValue:
    type: string
    description: |
      Partially hidden on retrieval for security reasons.
