#%RAML 1.0 DataType
(package): Extension
type: HttpDestinationAuthentication
displayName: AzureFunctionsAuthentication
discriminatorValue: AzureFunctions
description: |
  To protect your Azure Function, set its `authLevel` to `function` and provide the functions key. The commercetools Platform will set the `x-functions-key` header. For more information, see the [Azure Functions documentation](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-http-webhook#keys).

  To protect the secret key from being exposed, remove the code parameter and secret key from the URL. For example, use `https://foo.azurewebsites.net/api/bar` instead of
  `https://foo.azurewebsites.net/api/bar?code=secret`.
properties:
  key:
    type: string
    description: |
      Partially hidden on retrieval for security reasons.
