#%RAML 1.0 DataType
(package): Extension
type: string
displayName: ExtensionAction
description: |
  An Extension gets called during any of the following requests of an API call, but before the result is persisted.
enum:
  - Create
  - Update
(enumDescriptions):
  Create: An Extension gets called during a Create request.
  Update: An Extension gets called during an Update request.
