#%RAML 1.0 DataType
(package): Extension
type: Reference
displayName: ExtensionReference
discriminatorValue: extension
example: !include ../../examples/Extension/ExtensionReference.json
description: |
  [Reference](ctp:api:type:Reference) to an [Extension](ctp:api:type:Extension).
properties:
  typeId:
    type: ReferenceTypeId
    description: ''
  id:
    type: string
    description: |
      Unique identifier of the referenced [Extension](ctp:api:type:Extension).
  obj?:
    type: Extension
    description: |
      Contains the representation of the expanded Extension. Only present in responses to requests with [Reference Expansion](/../api/general-concepts#reference-expansion) for Extensions.
