#%RAML 1.0 DataType
(package): Extension
(docs-uri): https://docs.commercetools.com/api/projects/api-extensions#extension
type: BaseResource
displayName: Extension
(updateType): ExtensionUpdate
(java-extends): 'com.commercetools.api.models.DomainResource<Extension>'
properties:
  id:
    (identifier): true
    type: string
    description: |
      Unique ID of the Extension.
  version:
    type: number
    format: int64
    description: |
      Current version of the Extension.
  createdAt:
    type: datetime
    description: |
      Date and time (UTC) the Extension was initially created.
  lastModifiedAt:
    type: datetime
    description: |
      Date and time (UTC) the Extension was last updated.
  lastModifiedBy?:
    type: LastModifiedBy
    (beta): true
    description: |
      Present on resources created after 1 February 2019 except for [events not tracked](/../api/client-logging#events-tracked).
  createdBy?:
    type: CreatedBy
    (beta): true
    description: |
      Present on resources created after 1 February 2019 except for [events not tracked](/../api/client-logging#events-tracked).
  key?:
    type: string
    description: |
      User-defined unique identifier for the Extension.
      Keys can only contain alphanumeric characters, underscores, and hyphens.
    pattern: ^[A-Za-z0-9_-]+$
    minLength: 2
    maxLength: 256
  destination:
    type: ExtensionDestination
    description: |
      Information necessary for the commercetools Platform to call the Extension.
  triggers:
    type: ExtensionTrigger[]
    description: |
      Describes what triggers the Extension.
  timeoutInMs?:
    type: integer
    description: |
      Maximum time (in milliseconds) the commercetools Platform waits for a response from the Extension.
      If no timeout is provided, the default value is used for all types of Extensions.
      The maximum value is 10000 ms (10 seconds) for `payment` Extensions and 2000 ms (2 seconds) for all other Extensions.
    default: 2000
