#%RAML 1.0 DataType
(package): Extension
type: object
displayName: ExtensionDraft
properties:
  key?:
    type: string
    description: |
      User-defined unique identifier for the Extension.
    pattern: ^[A-Za-z0-9_-]+$
    minLength: 2
    maxLength: 256
  destination:
    type: ExtensionDestination
    description: |
      Defines where the Extension can be reached.
  triggers:
    type: ExtensionTrigger[]
    description: |
      Describes what triggers the Extension.
  timeoutInMs?:
    type: integer
    description: |
      Maximum time (in milliseconds) the Extension can respond within.
      If no timeout is provided, the default value is used for all types of Extensions.
      The maximum value is 10000 ms (10 seconds) for `payment` Extensions and 2000 ms (2 seconds) for all other Extensions.

      This limit can be increased per Project after we review the performance impact.
      Please contact the [Composable Commerce support team](https://support.commercetools.com) and provide the Region, Project key, and use case.
    default: 2000
