#%RAML 1.0 DataType
(package): Extension
type: object
displayName: ExtensionInput
properties:
  action:
    type: ExtensionAction
    description: |
      `Create` or `Update` request.
  resource:
    type: Reference
    description: |
      Expanded reference to the resource that triggered the Extension.
