#%RAML 1.0 DataType
(package): Payment
(docs-uri): https://docs.commercetools.com/http-api-projects-payments.html#set-anonymousid
type: PaymentUpdateAction
displayName: PaymentSetAnonymousIdAction
discriminatorValue: setAnonymousId
(postman-example): !include ../../../examples/Payment/PaymentSetAnonymousIdAction.json
properties:
  anonymousId?:
    type: string
    description: |-
      Anonymous ID of the anonymous customer that this payment belongs to.
      If this field is not set any existing `anonymousId` is removed.
