#%RAML 1.0 DataType


type: object
displayName: PaymentDraft
properties:
    customer?:
        type: CustomerReference
    externalId?:
        type: string
    interfaceId?:
        type: string
    amountPlanned:
        type: Money
    amountAuthorized?:
        type: Money
    authorizedUntil?:
        type: string
    amountPaid?:
        type: Money
    amountRefunded?:
        type: Money
    paymentMethodInfo?:
        type: PaymentMethodInfo
    paymentStatus?:
        type: PaymentStatus
    transactions?: TransactionDraft[]
    interfaceInteractions?: CustomFieldsDraft[]
    custom?:
        type: CustomFieldsDraft
    key?:
        type: string
