#%RAML 1.0 DataType
(package): Payment


type: PaymentUpdateAction
displayName: PaymentSetAuthorizationAction
discriminatorValue: setAuthorization
properties:
    amount?:
        type: Money
    until?:
        type: datetime
