#%RAML 1.0 DataType
(package): Payment
(docs-uri): https://docs.commercetools.com/http-api-projects-payments.html#transaction
type: object
displayName: Transaction
properties:
  id:
    type: string
    description: The unique ID of this object.
  timestamp?:
    type: datetime
    description: The time at which the transaction took place.
  type:
    type: TransactionType
    description: The type of this transaction.
  amount:
    type: TypedMoney
    description: ''
  interactionId?:
    type: string
    description: |-
      The identifier that is used by the interface that managed the transaction (usually the PSP).
      If a matching interaction was logged in the `interfaceInteractions` array, the corresponding interaction should be findable with this ID.
  state?:
    type: TransactionState
    description: The state of this transaction.
