#%RAML 1.0 DataType
(package): Payment


type: object
displayName: TransactionDraft
(generate-collection): true
properties:
    timestamp?:
        type: datetime
    type:
        type: TransactionType
    amount:
        type: Money
    interactionId?:
        type: string
    state?:
        type: TransactionState
