#%RAML 1.0 DataType
(annotations.package): PaymentIntegration
type: object
displayName: AutomatedReversalConfiguration
description: |
  Configuration for automated reversal of payments.
properties:
  status:
    type: string
    enum: [Active, Inactive]
    description: |
      Indicates whether the automated reversal configuration is active or not.
  predicate?:
    type: string
    description: |
      Cart-based predicate in JSONata format to determine when automated reversal should be applied.
