#%RAML 1.0 DataType
(annotations.package): PaymentIntegration
type: object
displayName: ConnectorDeploymentReference
description: |
  Reference to a connector deployment for the payment integration.
properties:
  id:
    type: string
    description: |
      Unique identifier of the referenced Connect Deployment.
  typeId:
    type: string
    description: |
      Type identifier, always `deployment` for Connector deployment references.
