#%RAML 1.0 DataType
(annotations.package): PaymentIntegration
type: object
displayName: DisplayInfo
description: |
  Display information for the payment integration in the UI.
properties:
  label?:
    type: LocalizedString
    description: |
      Label of the payment method displayed in the UI.
  logoUrl?:
    type: LocalizedUrl
    description: |
      Logo of the payment method displayed in the UI.
  description?:
    type: LocalizedString
    description: |
      Description of the payment method displayed in the UI.
  payButtonText?:
    type: LocalizedString
    description: |
      Text of the Pay button displayed in the UI when paying with the payment method.
