#%RAML 1.0 DataType
(annotations.package): PaymentIntegration
type: object
displayName: PaginatedPaymentIntegration
description: |
  Paginated result containing PaymentIntegrations.
properties:
  limit:
    type: integer
    description: |
      Number of results requested.
  offset:
    type: integer
    description: |
      Number of elements skipped.
  count:
    type: integer
    description: |
      Actual number of results returned.
  total:
    type: integer
    description: |
      Total number of results matching the query.
  results:
    type: PaymentIntegration[]
    description: |
      PaymentIntegrations matching the query.
