#%RAML 1.0 DataType
(annotations.package): PaymentIntegration
type: ResourceIdentifier
displayName: PaymentIntegrationResourceIdentifier
discriminatorValue: payment-integration
description: |
  Resource identifier to a [Payment Integration](/connectors-and-applications#payment-integrations). Either `id` or `key` is required. If both are set, an [InvalidJsonInput](/errors#invalidjsoninput) error is returned.
properties:
  id?:
    type: string
    description: |
      Unique identifier of the referenced Payment Integration. Required if `key` is absent.
  key?:
    type: string
    description: |
      User-defined unique identifier of the referenced Payment Integration. Required if `id` is absent.
