#%RAML 1.0 DataType
(annotations.package): PaymentIntegration
type: object
displayName: PaymentIntegration
properties:
  id:
    type: string
    description: |
      Unique identifier of the PaymentIntegration.
  version:
    type: number
    format: int64
    description: |
      Current version of the PaymentIntegration.
  key?:
    type: string
    description: |
      User-defined unique identifier of the PaymentIntegration. `MinLength: 2 ​MaxLength: 256 ​Pattern: ^[A-Za-z0-9_-]+$`
  application:
    type: ApplicationReference
    description: |
      Reference to an Application associated with the PaymentIntegration.
  status?:
    type: PaymentIntegrationStatus
    description: |
      Indicates whether the Payment Integration is active or not.

    default: Inactive
  type:
    type: string
    description: |
      Type of the PaymentIntegration, for example, card, Paypal, or Applepay. This field must be same as used by the payment service provider (PSP) and must be supported by the Connector.

      Use `drop-in` for drop-in Payment Integrations.
  name:
    type: string
    description: |
      Name of the PaymentIntegration in the Merchant Center.
  predicate?:
    type: string
    description: |
      Predicate in JSONata format. Applies only when `componentType` is `Component`.
  componentType:
    type: PaymentComponentType
    description: |
      Indicates the component type of Payment Integration.
  connectorDeployment:
    type: ConnectorDeploymentReference
    description: |
      Connector deployment info for the Payment Integration.
  displayInfo?:
    type: DisplayInfo
    description: |
      Customization for the information that is displayed in the UI. Applies only when `componentType` is `Component`
  sortingInfo?:
    type: SortingInfo
    description: |
      Sorting information of the Payment Integration.
  automatedReversalConfiguration?:
    type: AutomatedReversalConfiguration
    description: |
      Configuration of the Payment Integration automatic reversal.
  createdAt:
    type: datetime
    description: |
      Date and time (UTC) the PaymentIntegration was initially created.
  createdBy?:
    type: CreatedBy
    description: |
      IDs and references that created the PaymentIntegration.
  lastModifiedAt:
    type: datetime
    description: |
      Date and time (UTC) the PaymentIntegration was last updated.
  lastModifiedBy?:
    type: LastModifiedBy
    description: |
      IDs and references that last modified the PaymentIntegration.
