#%RAML 1.0 DataType
(annotations.package): PaymentIntegration
type: Reference
displayName: PaymentIntegrationReference
discriminatorValue: payment-integration
description: |
  Reference to a [Payment Integration](/payment-connectors-applications#payment-integrations).
properties:
  id:
    type: string
    description: |
      Unique identifier of the referenced Payment Integration.
