#%RAML 1.0 DataType
(package): Store
(docs-uri): https://docs.commercetools.com/http-api-projects-stores#productselectionsetting
type: object
displayName: ProductSelectionSetting
properties:
  productSelection:
    type: ProductSelectionReference
    description: Reference to a Product Selection
  active:
    type: boolean
    description:
      If `true` all Products assigned to this Product Selection are part of the Store's assortment.
