#%RAML 1.0 DataType
(package): Store
(docs-uri): https://docs.commercetools.com/api/projects/stores#storedraft
displayName: StoreDraft
type: object
properties:
  key:
    type: string
    description: |
      User-defined unique and immutable identifier for the Store.
      Keys can only contain alphanumeric characters, underscores, and hyphens.
    pattern: ^[A-Za-z0-9_-]+$
    minLength: 2
    maxLength: 256
  name?:
    type: LocalizedString
    description: |
      Name of the Store.
  languages?:
    type: Locale[]
    description: |
      Languages defined in [Project](ctp:api:type:Project). Only languages defined in the Project can be used.
  countries?:
    type: StoreCountry[]
    description: |
      Countries defined for the Store.
  distributionChannels?:
    type: ChannelResourceIdentifier[]
    description: |
      ResourceIdentifier of a Channel with `ProductDistribution` [ChannelRoleEnum](ctp:api:type:ChannelRoleEnum).
  supplyChannels?:
    type: ChannelResourceIdentifier[]
    description: |
      ResourceIdentifier of a Channel with `InventorySupply` [ChannelRoleEnum](ctp:api:type:ChannelRoleEnum).
  productSelections?:
    type: ProductSelectionSettingDraft[]
    description: |
      Controls availability of Products for this Store via active/inactive Product Selections:

      - Leave empty if all Products in the [Project](ctp:api:type:Project) should be available in this Store.
      - If only `inactive` Product Selections with `IndividualExclusion` [ProductSelectionMode](ctp:api:type:ProductSelectionMode) are provided, all the Products are available in this Store.
      - If all the Product Selections provided are `inactive` and there's at least a Product Selection of mode `Individual`, no Product is available in this Store.
      - If at least an `active` Product Selection is provided, only `active` Product Selections are considered to compute the availability in this Store.

  custom?:
    type: CustomFieldsDraft
    description: |
      Custom fields for the Store.
