#%RAML 1.0 DataType
(package): ShoppingList
(docs-uri): https://docs.commercetools.com/http-api-projects-shoppingLists.html#set-deletedaysafterlastmodification


type: ShoppingListUpdateAction
displayName: ShoppingListSetDeleteDaysAfterLastModificationAction
discriminatorValue: setDeleteDaysAfterLastModification
properties:
    deleteDaysAfterLastModification?:
        type: integer
