#%RAML 1.0 DataType
(package): ShoppingList
(docs-uri): https://docs.commercetools.com/http-api-projects-shoppingLists.html#set-lineitem-custom-type
type: ShoppingListUpdateAction
displayName: ShoppingListSetLineItemCustomTypeAction
discriminatorValue: setLineItemCustomType
(postman-example): !include ../../../examples/ShoppingList/ShoppingListSetLineItemCustomTypeAction.json
properties:
  lineItemId:
    type: string
  type?:
    type: TypeResourceIdentifier
  fields?:
    type: FieldContainer
