#%RAML 1.0 DataType
(package): ShoppingList
(docs-uri): https://docs.commercetools.com/http-api-projects-shoppingLists.html#set-custom-type
type: ShoppingListUpdateAction
displayName: ShoppingListSetCustomTypeAction
discriminatorValue: setCustomType
(postman-example): !include ../../../examples/ShoppingList/ShoppingListSetCustomTypeAction.json
properties:
  type?:
    type: TypeResourceIdentifier
    description: |-
      If set, the custom type is set to this new value.
      If absent, the custom type and any existing custom fields are removed.
  fields?:
    type: FieldContainer
    description: If set, the custom fields are set to this new value.
