#%RAML 1.0 DataType
(package): ProductTailoring
type: ProductTailoringUpdateAction
(beta): true
displayName: ProductTailoringPublishAction
discriminatorValue: publish
example: !include ../../../examples/ProductTailoring/ProductTailoringPublishAction.json
description: |
  Publishes the `staged` data of the ProductTailoring to `current`. Sets `hasStagedChanges` to `false`.
  Generates the [ProductTailoringPublished](ctp:api:type:ProductTailoringPublishedMessage) Message.
