#%RAML 1.0 DataType
(package): ProductTailoring
type: ProductTailoringUpdateAction
(beta): true
displayName: ProductTailoringSetAssetDescriptionAction
discriminatorValue: setAssetDescription
description: |
  Either `variantId` or `sku` is required to reference a [ProductVariant](ctp:api:type:ProductVariant) that exists.
  The [Asset](ctp:api:type:Asset) to update must be specified using either `assetId` or `assetKey`.
example: !include ../../../examples/ProductTailoring/ProductTailoringSetAssetDescriptionAction.json
properties:
  variantId?:
    type: number
    format: int64
    description: |
      The `id` of the tailored ProductVariant to update.
  sku?:
    type: string
    description: |
      The `sku` of the tailored ProductVariant to update.
  staged?:
    type: boolean
    description: |
      If `true`, only the staged Asset is updated. If `false`, both the current and staged Asset is updated.
    default: true
  assetId?:
    type: string
    description: |
      The `id` of the Asset to update.
  assetKey?:
    type: string
    description: |
      The `key` of the Asset to update.
  description?:
    type: LocalizedString
    description: |
      Value to set. If empty, any existing value will be removed.
