#%RAML 1.0 DataType
(package): ProductTailoring
type: ProductTailoringUpdateAction
displayName: ProductTailoringSetNameAction
discriminatorValue: setName
example: !include ../../../examples/ProductTailoring/ProductTailoringSetNameAction.json
description: |
  Generates the [ProductTailoringNameSet](ctp:api:type:ProductTailoringNameSetMessage) Message.
properties:
  name?:
    type: LocalizedString
    description: |
      Value to set. If empty, any existing value will be removed.
  staged?:
    type: boolean
    description: |
      If `true`, only the staged `name` is updated. If `false`, both the current and staged `name` are updated.
    default: true
