#%RAML 1.0 DataType
(package): ProductTailoring
type: ProductTailoringUpdateAction
(beta): true
displayName: ProductTailoringSetMetaAttributesAction
discriminatorValue: setMetaAttributes
example: !include ../../../examples/ProductTailoring/ProductTailoringSetMetaAttributesAction.json
description: Updates all meta attributes at the same time.
properties:
  metaTitle?:
    type: LocalizedString
    description: |
      Value to set. If empty, any existing value will be removed.
  metaDescription?:
    type: LocalizedString
    description: |
      Value to set. If empty, any existing value will be removed.
  metaKeywords?:
    type: LocalizedString
    description: |
      Value to set. If empty, any existing value will be removed.
  staged?:
    type: boolean
    description: |
      If `true`, only the staged attributes are updated. If `false`, both the current and staged attributes are updated.
    default: true
