#%RAML 1.0 DataType
(package): ProductTailoring
type: ProductTailoringUpdateAction
displayName: ProductTailoringChangeAssetOrderAction
discriminatorValue: changeAssetOrder
description: |
  Either `variantId` or `sku` is required to reference a [ProductVariant](ctp:api:type:ProductVariant) that exists.
example: !include ../../../examples/ProductTailoring/ProductTailoringChangeAssetOrderAction.json
properties:
  variantId?:
    type: number
    format: int64
    description: |
      The `id` of the tailored ProductVariant to update.
  sku?:
    type: string
    description: |
      The `sku` of the tailored ProductVariant to update.
  staged?:
    type: boolean
    description: |
      If `true`, only the staged `assets` is updated. If `false`, both the current and staged `assets` are updated.
    default: true
  assetOrder:
    type: string[]
    description: |
      All existing Asset `id`s of the ProductVariantTailoring in the desired new order.
