#%RAML 1.0 DataType
(package): ProductTailoring
type: ProductTailoringUpdateAction
displayName: ProductTailoringSetExternalImagesAction
discriminatorValue: setImages
description: |
  Either `variantId` or `sku` is required to reference a [ProductVariant](ctp:api:type:ProductVariant) that exists. Produces the [ProductTailoringImagesSet](/projects/messages/product-catalog-messages#product-tailoring-images-set) Message.
example: !include ../../../examples/ProductTailoring/ProductTailoringSetExternalImagesAction.json
properties:
  variantId?:
    type: number
    format: int64
    description: |
      The `id` of the tailored ProductVariant to update.
  sku?:
    type: string
    description: |
      The `sku` of the tailored ProductVariant to update.
  images?:
    type: array
    items: Image
    description: |
      Images of the tailored ProductVariant.

      Don't provide this field if you want to remove all images from the tailored Product Variant.
      Set to `[]` (empty) if you want to hide all images of the original ProductVariant on the tailored ProductVariant.
  staged?:
    type: boolean
    description: |
      If `true`, only the staged `images` is updated. If `false`, both the current and staged `images` is updated.
    default: true
