#%RAML 1.0 DataType
(annotations.package): PaymentIntegration
type: PaymentIntegrationUpdateAction
displayName: SetStatusUpdateAction
discriminatorValue: setStatus
example: !include ../../../examples/payment-integrations/setStatus.json
description: |
  Sets the status of a PaymentIntegration.
properties:
  status:
    type: PaymentIntegrationStatus
    description: |
      Value to set as the status of the PaymentIntegration.
