#%RAML 1.0 DataType
(package): StagedQuote
(docs-uri):
type: ResourceIdentifier
displayName: StagedQuoteResourceIdentifier
discriminatorValue: staged-quote
description: |
  [ResourceIdentifier](ctp:api:type:ResourceIdentifier) to a [StagedQuote](ctp:api:type:StagedQuote).
