#%RAML 1.0 DataType
(package): StagedQuote
(docs-uri): https://docs.commercetools.com/http-api-projects-staged-quotes#stagedquote
type: BaseResource
displayName: StagedQuote
(updateType): StagedQuoteUpdate
properties:
  id:
    (identifier): true
    type: string
    description: |
      The unique ID of the StagedQuote.
  version:
    type: number
    format: int64
    description: |
      Current version of the StagedQuote.
  key?:
    type: string
    description: User-specific unique identifier of the staged quote.
  createdAt:
    type: datetime
    description: |
      Date and time (UTC) the StagedQuote was initially created.
  lastModifiedAt:
    type: datetime
    description: |
      Date and time (UTC) the StagedQuote was last updated.
  lastModifiedBy?:
    type: LastModifiedBy
    (beta): true
    description: |
      Present on resources created after 1 February 2019 except for [events not tracked](/client-logging#events-tracked).
  createdBy?:
    type: CreatedBy
    (beta): true
    description: |
      Present on resources created after 1 February 2019 except for [events not tracked](/client-logging#events-tracked).
  stagedQuoteState:
    type: StagedQuoteState
  customer?:
    type: CustomerReference
    description: |
      The [Buyer](/../api/quotes-overview#buyer) who requested the quote.
  quoteRequest:
    type: QuoteRequestReference
    description: |
      The Quote Request related to this Staged Quote.
  quotationCart:
    type: CartReference
    description: |
      The [Cart](ctp:api:type:Cart) containing the offered items.
  validTo?:
    type: datetime
    description: |
      Expiration date for the quote.
  sellerComment?:
    type: string
    description: |
      The text message included in the offer from the [Seller](/../api/quotes-overview#seller).
  custom?:
    type: CustomFields
    description: 'Custom Fields of this Staged Quote.'
