#%RAML 1.0 DataType
(package): StagedQuote
(docs-uri): https://docs.commercetools.com/http-api-projects-staged-quotes.html#stagedquote
(java-extends): com.commercetools.api.models.Identifiable<StagedQuote>
type: Reference
displayName: StagedQuoteReference
discriminatorValue: staged-quote
description: |
  [Reference](ctp:api:type:Reference) to a [StagedQuote](ctp:api:type:StagedQuote).
properties:
  obj?:
    type: StagedQuote
    description: |
      Contains the representation of the expanded StagedQuote.
      Only present in responses to requests with [Reference Expansion](/../api/general-concepts#reference-expansion) for StagedQuote.
