#%RAML 1.0 DataType
(package): ProductTailoring
displayName: ProductVariantTailoring
type: object
description: |
  The tailoring of a [ProductVariant](ctp:api:type:ProductVariant).
properties:
  id:
    type: number
    format: int64
    description: |
      The `id` of the tailored [ProductVariant](ctp:api:type:ProductVariant).
  images?:
    type: Image[]
    description: |
      Images of the tailored Product Variant.
      If present, these images will override the images of the corresponding [ProductVariant](ctp:api:type:ProductVariant) in total.
  assets?:
    type: Asset[]
    description: |
      Media assets of the tailored Product Variant.
      If present, these assets will override the assets of the corresponding [ProductVariant](ctp:api:type:ProductVariant) in total.
  attributes?:
    type: ProductTailoringAttribute[]
    description: |
      Attributes of the tailored Product Variant.
      If present, these Attributes are selectively merged into the `attributes` of the corresponding [ProductVariant](ctp:api:type:ProductVariant):

      - If the ProductVariant contains an Attribute with the same `name`, its `value` is overwritten,
      - otherwise the Attribute and its value are added to the ProductVariant.
