#%RAML 1.0 DataType
(package): ProductTailoring
displayName: ProductTailoringData
type: object
description: |
  Contains all the tailored information of a Product.
properties:
  name?:
    type: LocalizedString
    description: |
      Tailored name of the Product.
  description?:
    type: LocalizedString
    description: |
      Tailored description of the Product.
  metaTitle?:
    type: LocalizedString
    description: |
      Tailored title of the Product that is used by search engines.
  metaDescription?:
    type: LocalizedString
    description: |
      Tailored description of the Product that is used by search engines.
  metaKeywords?:
    type: LocalizedString
    description: |
      Tailored keywords related to the Product that are used by search engines.
  slug?:
    type: LocalizedString
    description: |
      User-defined identifier used in a deep-link URL for the ProductTailoring.
      Matches the pattern `[a-zA-Z0-9_\\-]{2,256}`.
  variants?:
    type: ProductVariantTailoring[]
    description: |
      Tailored Variants of the Product.
  attributes?:
    type: ProductTailoringAttribute[]
    (beta): true
    description: |
      Attributes of the tailored Product.
      If available, these Attributes are selectively merged into the `attributes` of the corresponding [Product](ctp:api:type:Product). If the Product contains an Attribute with the same `name`, then its `value` is overwritten. Otherwise, the Attribute and its `value` are added to the Product.
