#%RAML 1.0 DataType
(package): ProductTailoring
type: ResourceIdentifier
displayName: ProductTailoringResourceIdentifier
discriminatorValue: product-tailoring
description: |
  [ResourceIdentifier](ctp:api:type:ResourceIdentifier) to a [ProductTailoring](ctp:api:type:ProductTailoring).
properties:
  id?:
    type: string
    description: |
      Unique identifier of the referenced [ProductTailoring](ctp:api:type:ProductTailoring). Either `id` or `key` is required.
  key?:
    type: string
    description: |
      User-defined unique identifier of the referenced [ProductTailoring](ctp:api:type:ProductTailoring). Either `id` or `key` is required.
