#%RAML 1.0 DataType
(package): Extension
type: ExtensionUpdateAction
displayName: ExtensionSetExpansionPathsAction
discriminatorValue: setExpansionPaths
example: !include ../../../examples/Extension/ExtensionSetExpansionPathsAction.json
(beta): true
properties:
  expansionPaths:
    type: array
    items: string
    maxItems: 3
    description: |
      [Expansion paths](/api/general-concepts#expansion-paths) used for reference expansion of the payload.

      Be aware of the [limits](/api/limits#api-extensions) of this feature and its [performance impact](/api/performance-tips#api-extensions).
