#%RAML 1.0 DataType
(package): Extension
type: ExtensionUpdateAction
displayName: ExtensionSetTimeoutInMsAction
discriminatorValue: setTimeoutInMs
properties:
  timeoutInMs?:
    type: integer
    default: 2000
    maximum: 10000
    description: |
      Value to set.
      If no timeout is provided, the default value is used for all [types of Extensions](ctp:api:type:ExtensionResourceTypeId).
      We recommend keeping the timeout as low as possible to avoid performance issues.

      The limit of 10000 ms (10 seconds) can be increased per Project after we review the performance impact.
      Please contact the [Composable Commerce support team](https://support.commercetools.com) and provide the Region, Project key, and use case.
