#%RAML 1.0 DataType
(package): Extension
(docs-uri): https://docs.commercetools.com/api/projects/api-extensions#change-triggers
type: ExtensionUpdateAction
displayName: ExtensionChangeTriggersAction
discriminatorValue: changeTriggers
example: !include ../../../examples/Extension/ExtensionChangeTriggersAction.json
properties:
  triggers:
    type: ExtensionTrigger[]
    description: |
      New value to set. Must not be empty.
