#%RAML 1.0 DataType
(annotations.package): RecurringPayment
(annotations.beta): true
type: object
displayName: PaginatedRecurringPayment
description: |
  Paginated result containing RecurringPayments.
properties:
  limit:
    type: integer
    description: |
      Number of results requested.
  offset:
    type: integer
    description: |
      Number of elements skipped.
  count:
    type: integer
    description: |
      Actual number of results returned.
  total?:
    type: integer
    description: |
      Total number of results matching the query. Only present when the `withTotal` query parameter is `true`.
  results:
    type: array
    items: RecurringPayment
    description: |
      RecurringPayments matching the query.
