#%RAML 1.0 DataType
(annotations.package): RecurringPayment
(annotations.beta): true
type: object
displayName: RecurringPayment
description: |
  Maps a [RecurringOrder](ctp:api:type:RecurringOrder) to the [PaymentMethod](ctp:api:type:PaymentMethod) and [Connector](/checkout/connectors-and-applications#payment-connectors) that process its future payments.
properties:
  id:
    type: string
    description: Unique identifier of the RecurringPayment.
  version:
    type: integer
    description: Current version of the RecurringPayment.
  key?:
    type: string
    description: User-defined unique identifier of the RecurringPayment.
    pattern: ^[A-Za-z0-9_-]+$
    minLength: 2
    maxLength: 256
  recurringOrder:
    type: RecurringOrderReference
    description: |
      [RecurringOrder](ctp:api:type:RecurringOrder) whose future payments are processed using Checkout.
  paymentMethodConfigurations:
    type: array
    items: PaymentMethodConfiguration
    description: |
      PaymentMethod and Connector used to pay the [RecurringOrder](ctp:api:type:RecurringOrder). Checkout only supports processing this array with one PaymentMethodConfiguration.
  createdAt:
    type: datetime
    description: Date and time (UTC) the RecurringPayment was initially created.
  lastModifiedAt:
    type: datetime
    description: Date and time (UTC) the RecurringPayment was last updated.
