#%RAML 1.0 DataType
(annotations.package): RecurringPayment
(annotations.beta): true
type: Reference
displayName: RecurringOrderReference
discriminatorValue: recurring-order
description: |
  Reference to a [RecurringOrder](ctp:api:type:RecurringOrder).
properties:
  typeId:
    type: ReferenceTypeId
    description: ''
  id:
    type: string
    description: |
      Unique identifier of the referenced [RecurringOrder](ctp:api:type:RecurringOrder).
