#%RAML 1.0 DataType
(package): Inventory
(docs-uri): https://docs.commercetools.com/http-api-projects-inventory.html#inventoryentry
displayName: InventoryEntry
(updateType): InventoryEntryUpdate
(actionType): InventoryEntryUpdateAction
type: BaseResource
(java-extends): 'com.commercetools.api.models.DomainResource<InventoryEntry>'
properties:
  id:
    (identifier): true
    type: string
    description: The unique ID of the inventory entry.
  version:
    type: number
    format: int64
    description: ''
  createdAt:
    type: datetime
    description: ''
  lastModifiedAt:
    type: datetime
    description: ''
  lastModifiedBy?:
    type: LastModifiedBy
    description:
      Present on resources updated after 1/02/2019 except for events not
      tracked.
  createdBy?:
    type: CreatedBy
    description:
      Present on resources created after 1/02/2019 except for events not
      tracked.
  sku:
    type: string
    description: ''
  supplyChannel?:
    type: ChannelReference
    description: Optional connection to a particular supplier.
  quantityOnStock:
    type: number
    format: int64
    description: |-
      Overall amount of stock.
      (available + reserved)
  availableQuantity:
    type: number
    format: int64
    description: |-
      Available amount of stock.
      (available means: `quantityOnStock` - reserved quantity)
  restockableInDays?:
    type: number
    format: int64
    description:
      The time period in days, that tells how often this inventory entry is
      restocked.
  expectedDelivery?:
    type: datetime
    description: The date and time of the next restock.
  custom?:
    type: CustomFields
    description: ''
