#%RAML 1.0 DataType
(package): Inventory
displayName: InventoryEntryStockLevels
(beta): true
type: object
description: |
  Stock level thresholds for an [InventoryEntry](ctp:api:type:InventoryEntry) that trigger Messages when stock levels reach certain points. For more information, see [Stock level notifications](/../api/inventory-overview#stock-level-notifications).
properties:
  reorderPoint?:
    type: number
    format: int32
    description: |
      When the `quantityOnStock` of the [InventoryEntry](ctp:api:type:InventoryEntry) reaches this value, an [InventoryEntryReorderPoint](ctp:api:type:InventoryEntryReorderPointMessage) Message is generated.
  safetyStock?:
    type: number
    format: int32
    description: |
      When the `quantityOnStock` of the [InventoryEntry](ctp:api:type:InventoryEntry) reaches this value, an [InventoryEntrySafetyStock](ctp:api:type:InventoryEntrySafetyStockMessage) Message is generated.
