#%RAML 1.0 DataType
(package): Inventory
displayName: InventoryEntry
(updateType): InventoryEntryUpdate
(actionType): InventoryEntryUpdateAction
type: BaseResource
properties:
  id:
    (identifier): true
    type: string
    description: |
      Unique identifier of the InventoryEntry.
  version:
    type: number
    format: int64
    description: |
      Current version of the InventoryEntry.
  createdAt:
    type: datetime
    description: |
      Date and time (UTC) the InventoryEntry was initially created.
  lastModifiedAt:
    type: datetime
    description: Date and time (UTC) the InventoryEntry was last updated.
  lastModifiedBy?:
    type: LastModifiedBy
    (beta): true
    description: |
      IDs and references that last modified the InventoryEntry.
  createdBy?:
    type: CreatedBy
    (beta): true
    description: |
      IDs and references that created the InventoryEntry.
  key?:
    type: string
    description: |
      User-defined unique identifier of the InventoryEntry.
    pattern: ^[A-Za-z0-9_-]+$
    minLength: 2
    maxLength: 256
  sku:
    type: string
    description: |
      [ProductVariant](ctp:api:type:ProductVariant) `sku` of the InventoryEntry.
  supplyChannel?:
    type: ChannelReference
    description: |
      [Channel](ctp:api:type:Channel) that supplies this InventoryEntry.
  quantityOnStock:
    type: number
    format: int64
    description: |-
      Overall amount of stock (`availableQuantity` + reserved). This value is eventually consistent with the internal SKU availability used for reservation logic, with a delay of up to 10 seconds. See [Inventory checks and consistency](/../api/inventory-overview#inventory-checks-and-consistency) for more information.
  availableQuantity:
    type: number
    format: int64
    description: |
      Available amount of stock (`quantityOnStock` - reserved). This value is eventually consistent with the internal SKU availability used for reservation logic, with a delay of up to 10 seconds. See [Inventory checks and consistency](/../api/inventory-overview#inventory-checks-and-consistency) for more information.
  minCartQuantity?:
    type: integer
    minimum: 1
    description: |
      Minimum quantity that can be added to a Cart. See [Quantity limits](/../api/inventory-overview#quantity-limits).
  maxCartQuantity?:
    type: integer
    minimum: 1
    description: |
      Maximum quantity that can be added to a Cart. See [Quantity limits](/../api/inventory-overview#quantity-limits).
  restockableInDays?:
    type: number
    format: int64
    description: How often the InventoryEntry is restocked (in days).
  expectedDelivery?:
    type: datetime
    description: |
      Date and time of the next restock.
  reservationExpirationInMinutes?:
    type: number
    format: int32
    minimum: 1
    maximum: 44640
    description: |
      Expiration time of [ReserveOnCart](ctp:api:type:InventoryMode) reservations associated with this InventoryEntry.

      - A Reservation is [ReserveOnCart](ctp:api:type:InventoryMode) if it was created for a [LineItem](ctp:api:type:LineItem) that is using the [ReserveOnCart](ctp:api:type:InventoryMode) inventory mode.
      - If this field is empty, the [Project](ctp:api:type:Project)-level reservation expiration time applies.
  stockLevels?:
    type: InventoryEntryStockLevels
    description: |
      Configuration of stock levels for the InventoryEntry. Corresponding [Messages](/../api/projects/messages/product-catalog-messages#inventory-entry-messages) are triggered when the `quantityOnStock` reaches the configured levels.
  custom?:
    type: CustomFields
    description: |
      Custom Fields of the InventoryEntry.
