#%RAML 1.0 DataType
(package): Inventory
type: object
displayName: InventoryEntryUpdate
(java-extends):
  'com.commercetools.api.models.ResourceUpdate<InventoryEntryUpdate,
  InventoryEntryUpdateAction, InventoryEntryUpdateBuilder>'
properties:
  version:
    type: number
    format: int64
    description: |
      Expected version of the InventoryEntry on which the changes should be applied. If the expected version does not match the actual version, a [ConcurrentModification](ctp:api:type:ConcurrentModificationError) error is returned.
  actions:
    type: array
    items: InventoryEntryUpdateAction
    description: |
      Update actions to be performed on the InventoryEntry.
