#%RAML 1.0 DataType
(package): ProductType
displayName: AttributeDefinitionDraft
type: object
properties:
  type:
    type: AttributeType
    description: Describes the type of the attribute.
  name:
    type: string
    description: |-
      The unique name of the attribute used in the API.
      The name must be between two and 256 characters long and can contain the ASCII letters A to Z in lowercase or uppercase, digits, underscores (`_`) and the hyphen-minus (`-`).
      When using the same `name` for an attribute in two or more product types all fields of the AttributeDefinition of this attribute need to be the same across the product types.
  label:
    type: LocalizedString
    description: A human-readable label for the attribute.
  isRequired:
    type: boolean
    description: Whether the attribute is required to have a value.
  attributeConstraint?:
    type: AttributeConstraintEnum
    description:
      Describes how an attribute or a set of attributes should be validated
      across all variants of a product.
  inputTip?:
    type: LocalizedString
    description:
      Additional information about the attribute that aids content managers when
      setting product details.
  inputHint?:
    type: TextInputHint
    description: |-
      Provides a visual representation type for this attribute.
      only relevant for text-based attribute types like TextType and LocalizableTextType.
  isSearchable?:
    type: boolean
    description: |-
      Whether the attribute's values should generally be enabled in product search.
      This determines whether the value is stored in products for matching terms in the context of full-text search queries and can be used in facets & filters as part of product search queries.
      The exact features that are enabled/disabled with this flag depend on the concrete attribute type and are described there.
