#%RAML 1.0 DataType
(package): McpServer
type: object
displayName: McpServerDraft
description: |
  Draft representation for creating a new MCP Server.
properties:
  key:
    type: string
    description: |
      User-defined unique identifier for the MCP Server. Must be unique within the Project.
    pattern: ^[A-Za-z0-9_-]+$
    minLength: 2
    maxLength: 256
  name?:
    type: LocalizedString
    description: |
      Name of the MCP Server.
  description?:
    type: LocalizedString
    description: |
      Description of the MCP Server.
  state?:
    type: McpServerState
    default: Enabled
    description: |
      State of the MCP Server.
  mcpServer:
    type: McpServerConfigDraft
    description: |
      Configuration of the MCP Server connection.
