#%RAML 1.0 DataType
(package): State
(docs-uri): https://docs.commercetools.com/http-api-projects-states.html#state
type: Reference
displayName: StateReference
discriminatorValue: state
properties:
  obj?:
    type: State
