#%RAML 1.0 DataType


type: object
displayName: StateDraft
properties:
    key:
        type: string
    type:
        (generator-type): string
        type: StateTypeEnum
    name?:
        type: LocalizedString
    description?:
        type: LocalizedString
    initial?:
        type: boolean
    roles:
        (generator-type): string[]
        type: StateRoleEnum[]
    transitions?:
        type: StateReference[]
