#%RAML 1.0 DataType

uses:
    api: ../types.lib.raml
type: api.StateUpdateAction
displayName: StateSetTransitionsAction
discriminatorValue: setTransitions
properties:
    transitions: api.StateReference[]
