#%RAML 1.0 DataType
(package): Message
type: MessagePayload
displayName: ParcelItemsUpdatedMessagePayload
discriminatorValue: ParcelItemsUpdated
properties:
  parcelId:
    type: string
  deliveryId?:
    type: string
  items:
    type: DeliveryItem[]
  oldItems:
    type: DeliveryItem[]
