#%RAML 1.0 DataType
(package): Message
type: MessagePayload
displayName: ParcelRemovedFromDeliveryMessagePayload
discriminatorValue: ParcelRemovedFromDelivery
properties:
  deliveryId:
    type: string
  parcel:
    type: Parcel
