#%RAML 1.0 DataType
(annotations.package): Deployment
type: DeploymentUpdateAction
displayName: DeploymentRedeploy
discriminatorValue: redeploy
example: !include ../../../examples/deployment/updates/DeploymentUpdateAction.json
description: |
  Update the configuration values and redeploy the Deployment.
properties:
  configurationValues:
    type: common.DeploymentConfigurationApplication[]
    description: New configuration values for Deployment.
