#%RAML 1.0 ResourceType
get:
  description: |
    Returns the structure and data of the published page displayed from commercetools Frontend.
  headers:
    Accept:
      description: |
        `application/json`
      type: string
    Commercetools-Frontend-Extension-Version:
      description: |
        [Extension version](/../frontend-development/extensions#extension-version)
      type: string
    Frontastic-Path:
      description: Path to the page folder.
      pattern: ^/.*$
      type: string
    Frontastic-Locale:
      description: Locale of the page folder.
      type: Locale
  responses:
    200:
      description: Page folder information, page structure, and data source data.
      body:
        application/json:
          type: PageDataResponse
          example: !include ../examples/pagefolder-success.json
    301:
      description: Redirect information.
      body:
        application/json:
          type: RedirectResponse
          example: !include ../examples/redirect-success.json
    404:
      description: Page folder not found.
      body:
        application/json:
          type: Error
          example: !include ../examples/pagefolder-error.json
