#%RAML 1.0 ResourceType

is: [right-header]
get:
  queryParameters:
    locale:
      displayName: Locale
      type: Locale
      description: Locale
      required: true
      pattern: ^([a-z]{2}_[A-Z]{2})|([a-z]{2})$
    previewId:
      displayName: Preview ID
      type: string
      description: Preview ID
      required: true
  description: Returns the page structure and data for a specific Preview given by its `previewId`.
  responses:
    200:
      description: Page folder information, page structure, and data source data.
      body:
        application/json:
          type: PageResource
