#%RAML 1.0 ResourceType

/{namespace}/{action}:
  uriParameters:
    namespace:
      displayName: Namespace
      type: string
      description: Namespace
    action:
      displayName: Action
      type: string
      description: Action
  is:
    - right-header
    - frontastic-locale
  get:
    is:
      - action-errorable
    description: Use the GET operation to allow the frontend to fetch data asynchronously.
    responses:
      200:
        description: We recommend to use standard HTTP response codes and application/json encoded content.
  post:
    is:
      - action-errorable
    description: Use the POST or PUT operations write data to a backend system.
    responses:
      200:
        description: We recommend to use standard HTTP response codes and application/json encoded content.
