#%RAML 1.0 DataType

uses:
    api: ../types.lib.raml
type: api.CategoryUpdateAction
displayName: CategorySetAssetSources
discriminatorValue: setAssetSources
properties:
    assetId:
        type: string
    sources:
        type: api.AssetSource[]
