#%RAML 1.0 DataType
(package): Category


type: CategoryUpdateAction
displayName: CategorySetCustomTypeAction
discriminatorValue: setCustomType
properties:
    type?: TypeReference
    fields?:
        type: object
