#%RAML 1.0 DataType
(package): Category
(docs-uri): https://docs.commercetools.com/http-api-projects-categories.html#category

displayName: Category
(updateType): CategoryUpdate

type: Resource
properties:
    name:
        (hasSimpleUpdateAction): changeName
        type: LocalizedString
    slug:
        (hasSimpleUpdateAction): changeSlug
        type: LocalizedString
    description?:
        (hasSimpleUpdateAction): setDescription
        type: LocalizedString
    ancestors: CategoryReference[]
    parent?: CategoryReference
    orderHint:
        (docsActionAnchor): change-orderhint
        (hasSimpleUpdateAction): changeOrderHint
        type: string
    externalId?:
        (hasSimpleUpdateAction): setExternalId
        type: string
    metaTitle?:
        (hasSimpleUpdateAction): setMetaTitle
        type: LocalizedString
    metaDescription?:
        (hasSimpleUpdateAction): setMetaDescription
        type: LocalizedString
    metaKeywords?:
        (hasSimpleUpdateAction): setMetaKeywords
        type: LocalizedString
    custom?:
        type: CustomFields
    assets?:
        type: Asset[]
    key?:
        (hasSimpleUpdateAction): setKey
        type: string
