#%RAML 1.0 DataType
(package): Category


type: CategoryUpdateAction
displayName: CategorySetAssetSourcesAction
discriminatorValue: setAssetSources
properties:
    assetId:
        type: string
    sources:
        type: AssetSource[]
