#%RAML 1.0 DataType
(package): Category


type: CategoryUpdateAction
displayName: CategoryChangeNameAction
discriminatorValue: changeName
example: |
  {
    "action": "changeName",
    "name": "new category name"
  }
properties:
    name:
        type: LocalizedString
