#%RAML 1.0 DataType
(package): Category
(docs-uri): https://docs.commercetools.com/http-api-projects-categories.html#category

displayName: Category
(updateType): CategoryUpdate

type: Resource
properties:
    name:
        (hasUpdateAction): changeName
        type: LocalizedString
    slug:
        (hasUpdateAction): changeSlug
        type: LocalizedString
    description?:
        (hasUpdateAction): setDescription
        type: LocalizedString
    ancestors: CategoryReference[]
    parent?: CategoryReference
    orderHint:
        (docsActionAnchor): change-orderhint
        (hasUpdateAction): changeOrderHint
        type: string
    externalId?:
        (hasUpdateAction): setExternalId
        type: string
    metaTitle?:
        (hasUpdateAction): setMetaTitle
        type: LocalizedString
    metaDescription?:
        (hasUpdateAction): setMetaDescription
        type: LocalizedString
    metaKeywords?:
        (hasUpdateAction): setMetaKeywords
        type: LocalizedString
    custom?:
        type: CustomFields
    assets?:
        type: Asset[]
    key?:
        (hasUpdateAction): setKey
        type: string
