#%RAML 1.0 DataType
(package): Category


type: Update
displayName: CategoryUpdate
properties:
    actions:
        type: array
        items: CategoryUpdateAction |
            CategoryChangeNameAction |
            CategoryChangeSlugAction |
            CategorySetDescriptionAction |
            CategoryChangeParentAction |
            CategoryChangeOrderHintAction |
            CategorySetExternalIdAction |
            CategorySetMetaTitleAction |
            CategorySetMetaDescriptionAction |
            CategorySetMetaKeywordsAction |
            CategorySetCustomTypeAction |
            CategorySetCustomFieldAction |
            CategoryAddAssetAction |
            CategoryRemoveAssetAction |
            CategoryChangeAssetOrderAction |
            CategoryChangeAssetNameAction |
            CategorySetAssetDescriptionAction |
            CategorySetAssetTagsAction |
            CategorySetAssetSourcesAction |
            CategorySetAssetCustomTypeAction |
            CategorySetAssetCustomFieldAction |
            CategorySetKeyAction
