#%RAML 1.0 DataType
(package): Category
(docs-uri): https://docs.commercetools.com/http-api-projects-categories.html#category
type: ResourceIdentifier
displayName: CategoryResourceIdentifier
discriminatorValue: category
