#%RAML 1.0 DataType
(annotations.package): Cart
type: Reference
displayName: OrderReference
discriminatorValue: order
description: |
  Reference to an [Order](/../api/projects/orders).
properties:
  id:
    type: string
    description: |
      Unique identifier of the referenced [Order](/../api/projects/orders).
