#%RAML 1.0 DataType
(annotations.package): Payment
type: Reference
displayName: PaymentReference
discriminatorValue: payment
description: |
  Reference to a [Payment](/../api/projects/payments).
properties:
  id:
    type: string
    description: |
      Unique identifier of the referenced [Payment](/../api/projects/payments).
