#%RAML 1.0 DataType
(annotations.package): Common
displayName: ReferenceTypeId
type: string
description: |
  Type of resource the value should reference. Supported resource type identifiers are:
enum:
  - cart
  - order
  - payment
  - application
  - payment-integration
(annotations.enumDescriptions):
  cart: |
    References a [Cart](/../api/projects/carts#cart).
  order: |
    References an [Order](/../api/projects/orders#order).
  payment: |
    References a [Payment](/../api/projects/payments#payment).
  application: |
    References an [Application](/connectors-and-applications#applications).
  payment-integration: |
    References a [Payment Integration](/connectors-and-applications#payment-integrations).
