#%RAML 1.0 DataType
(package): Category
(docs-uri): https://docs.commercetools.com/http-api-projects-categories.html#set-custom-type
type: CategoryUpdateAction
displayName: CategorySetCustomTypeAction
discriminatorValue: setCustomType
(postman-example): !include ../../../examples/Category/CategorySetCustomTypeAction.json
properties:
  type?:
    type: TypeResourceIdentifier
    description: If absent, the [custom](/http-api-projects-custom-fields.html#custom)
      type and any existing [CustomFields](/http-api-projects-custom-fields.html#customfields)
      are removed.
  fields?:
    type: FieldContainer
    description: |-
      A valid JSON object, based on the [FieldDefinitions](/http-api-projects-types.html#fielddefinition) of the [Type](/http-api-projects-types.html#type).
      Sets the [custom](/http-api-projects-custom-fields.html#custom) fields to this value.
