#%RAML 1.0 DataType
(package): Category
(docs-uri): https://docs.commercetools.com/http-api-projects-categories.html#set-external-id
type: CategoryUpdateAction
displayName: CategorySetExternalIdAction
discriminatorValue: setExternalId
(postman-example): !include ../../../examples/Category/CategorySetExternalIdAction.json
properties:
  externalId?:
    type: string
    description: If not defined, the external ID is unset.
