#%RAML 1.0 DataType
(package): Category
(docs-uri): https://docs.commercetools.com/http-api-projects-categories.html#set-asset-custom-type

type: CategoryUpdateAction
displayName: CategorySetAssetCustomTypeAction
discriminatorValue: setAssetCustomType
(postman-example): !include ../../../examples/Category/CategorySetAssetCustomTypeAction.json
properties:
  assetId?:
    type: string
  assetKey?:
    type: string
  type?:
    type: TypeResourceIdentifier
  fields?:
    type: object
