#%RAML 1.0 DataType

displayName: MyCustomerDraft

type: object
properties:
    email:
        type: string
    password:
        type: string
    firstName?:
        type: string
    lastName?:
        type: string
    middleName?:
        type: string
    title?:
        type: string
    dateOfBirth?:
        type: date-only
    companyName?:
        type: string
    vatId?:
        type: string
    addresses?:
        type: Address[]
    defaultShippingAddress?:
        type: number
        format: int64
    defaultBillingAddress?:
        type: number
        format: int64
    custom?:
        type: CustomFields
    locale?:
        type: string
