#%RAML 1.0 DataType

displayName: MyLineItemDraft

type: object
(generate-collection): true
properties:
    productId:
        type: string
    variantId:
        type: number
        format: int64
    quantity:
        type: number
    supplyChannel?:
        type: ChannelReference
    distributionChannel?:
        type: ChannelReference
    custom?:
        type: CustomFieldsDraft
