#%RAML 1.0 DataType
(package): Me
(docs-uri): https://docs.commercetools.com/http-api-projects-orders.html#order
displayName: MyOrder
type: LoggedResource
properties:
  completedAt?:
    type: datetime
  orderNumber?:
    type: string
  customerId?:
    type: string
  customerEmail?:
    type: string
  anonymousId?:
    type: string
  store?:
    type: StoreKeyReference
  lineItems:
    type: LineItem[]
  customLineItems:
    type: CustomLineItem[]
  totalPrice: TypedMoney
  taxedPrice?:
    type: TaxedPrice
  shippingAddress?:
    type: Address
  billingAddress?:
    type: Address
  taxMode?:
    type: TaxMode
  taxRoundingMode?:
    type: RoundingMode
  customerGroup?:
    type: CustomerGroupReference
  country?:
    type: string
  orderState:
    type: OrderState
  state?:
    type: StateReference
  shipmentState?:
    type: ShipmentState
  paymentState?:
    type: PaymentState
  shippingInfo?:
    type: ShippingInfo
  syncInfo:
    type: SyncInfo[]
  returnInfo?:
    type: ReturnInfo[]
  discountCodes?: DiscountCodeInfo[]
  lastMessageSequenceNumber:
    type: number
    format: int64
  cart?:
    type: CartReference
  custom?:
    type: CustomFields
  paymentInfo?:
    type: PaymentInfo
  locale?:
    type: string
  inventoryMode?:
    type: InventoryMode
  origin:
    type: CartOrigin
  taxCalculationMode?:
    type: TaxCalculationMode
  shippingRateInput?:
    type: ShippingRateInput
  itemShippingAddresses?:
    type: Address[]
  refusedGifts:
    type: CartDiscountReference[]
