#%RAML 1.0 DataType
(package): Me
(docs-uri): https://docs.commercetools.com/http-api-projects-me-payments#mypayment
type: object
displayName: MyPayment
(updateType): MyPaymentUpdate
(actionType): MyPaymentUpdateAction
properties:
  id:
    (identifier): true
    type: string
  version:
    type: number
    format: int64
  customer?:
    type: CustomerReference
  anonymousId?:
    type: string
  amountPlanned:
    type: TypedMoney
    (hasUpdateAction):
      action: changeAmountPlanned
      docsAnchor: change-amountplanned
      fields:
        amount: Money
  paymentMethodInfo:
    type: PaymentMethodInfo
    (hasUpdateActions):
    - action: setMethodInfoInterface
      docsAnchor: set-methodinfointerface
      fields:
        interface: string
    - action: setMethodInfoMethod
      docsAnchor: set-methodinfomethod
      fields:
        method?: string
    - action: setMethodInfoName
      docsAnchor: set-methodinfoname
      fields:
        name?: LocalizedString
  transactions:
    type: Transaction[]
    (hasUpdateActions):
    - action: addTransaction
      fields:
        transaction: TransactionDraft
  custom?:
    type: CustomFields
    (hasUpdateActions):
    - action: setCustomField
      docsAnchor: set-customfield
      fields:
        name: string
        value?: any
