#%RAML 1.0 DataType
(package): AssociateRole
type: AssociateRoleUpdateAction
displayName: AssociateRoleSetPermissionsAction
discriminatorValue: setPermissions
example: !include ../../../examples/AssociateRole/AssociateRoleSetPermissionsAction.json
description: |
  Updating the Permissions on an [AssociateRole](ctp:api:type:AssociateRole) generates an [AssociateRolePermissionsSet](ctp:api:type:AssociateRolePermissionsSetMessage) Message.
properties:
  permissions?:
    type: Permission[]
    description: |
      Overrides the current list of Permissions for the AssociateRole.
