#%RAML 1.0 DataType
(package): AssociateRole
type: AssociateRoleUpdateAction
displayName: AssociateRoleAddPermissionAction
discriminatorValue: addPermission
example: !include ../../../examples/AssociateRole/AssociateRoleAddPermissionAction.json
description: |
  Adding a Permission to an [AssociateRole](ctp:api:type:AssociateRole) generates an [AssociateRolePermissionAdded](ctp:api:type:AssociateRolePermissionAddedMessage) Message.
properties:
  permission:
    type: Permission
    description: |
      Permission to be added to the AssociateRole.
