#%RAML 1.0 DataType
(package): AssociateRole
(docs-uri): https://docs.commercetools.com/api/projects/associate-roles#remove-permission
type: AssociateRoleUpdateAction
displayName: AssociateRoleRemovePermissionAction
discriminatorValue: removePermission
example: !include ../../../examples/AssociateRole/AssociateRoleRemovePermissionAction.json
description: |
  Removing a Permission from an [AssociateRole](ctp:api:type:AssociateRole) generates an [AssociateRolePermissionRemoved](ctp:api:type:AssociateRolePermissionRemovedMessage) Message.
properties:
  permission:
    type: Permission
    description: |
      Permission to be removed from the AssociateRole.
