#%RAML 1.0 DataType
(package): ShippingMethod
displayName: CartValueTier
type: ShippingRatePriceTier
description: |

  The [ShippingRate](ctp:api:type:ShippingRate) maps to the value of the Cart and is used to select a tier.
  The value of the [Cart](ctp:api:type:Cart) is the sum of all Line Item totals and Custom Line Item totals (via the `totalPrice` field) after any Product Discounts and Cart Discounts have been applied.
  If chosen, it is not possible to set a value for the `shippingRateInput` on the [Cart](ctp:api:type:Cart).
  Tiers contain the `centAmount` (a value of `100` in the currency `USD` corresponds to `$ 1.00`), and start at `1`.'
example: !include ../../examples/ShippingMethod/CartValueTier.json
discriminatorValue: CartValue
properties:
  minimumCentAmount:
    type: integer
    format: int64
    description: |
      Minimum total price of a Cart for which a shipping rate applies.
  price:
    type: Money
    description: |
      Fixed shipping rate Price for a CartValue.
  isMatching?:
    type: boolean
    description: |
      Appears in response to [Get ShippingMethods for a Cart](ctp:api:endpoint:/{projectKey}/shipping-methods/matching-cart:GET) if the shipping rate matches the search query.
