#%RAML 1.0 DataType
(package): ShippingMethod
(docs-uri): https://docs.commercetools.com/http-api-projects-shippingMethods.html#shippingmethod
type: BaseResource
displayName: ShippingMethod
(updateType): ShippingMethodUpdate
(java-extends): 'com.commercetools.api.models.DomainResource<ShippingMethod>'
properties:
  id:
    (identifier): true
    type: string
    description: The unique ID of the shipping method.
  version:
    type: number
    format: int64
    description: The current version of the shipping method.
  createdAt:
    type: datetime
    description: ''
  lastModifiedAt:
    type: datetime
    description: ''
  lastModifiedBy?:
    type: LastModifiedBy
  createdBy?:
    type: CreatedBy
  key?:
    type: string
    description: User-specific unique identifier for the shipping method.
  name:
    type: string
    description: ''
  description?:
    type: string
    description: ''
  localizedDescription?:
    type: LocalizedString
    description: ''
  taxCategory:
    type: TaxCategoryReference
    description: ''
  zoneRates:
    type: ZoneRate[]
    description: ''
  isDefault:
    type: boolean
    description: One shipping method in a project can be default.
  predicate?:
    type: string
    description:
      A Cart predicate which can be used to more precisely select a shipping
      method for a cart.
  custom?:
    type: CustomFields
    description: ''
