#%RAML 1.0 DataType
(package): ShippingMethod
(docs-uri): https://docs.commercetools.com/api/projects/shippingMethods#shippingratedraft
displayName: ShippingRateDraft
type: object
properties:
  price:
    type: Money
    description: Money value of the ShippingRate.
  freeAbove?:
    type: Money
    description: |-
      [Free shipping](/../api/shipping-delivery-overview#free-shipping) is applied if the sum of the (Custom) Line Item Prices reaches the specified value.
  tiers?:
    type: ShippingRatePriceTier[]
    description: Price tiers for the ShippingRate.
