#%RAML 1.0 DataType
(package): ShippingMethod
(docs-uri): https://docs.commercetools.com/api/projects/shippingMethods#shippingrate
displayName: ShippingRate
type: object
properties:
  price:
    type: TypedMoney
    description: Currency amount of the ShippingRate.
  freeAbove?:
    type: TypedMoney
    description: |-
      [Free shipping](/../api/shipping-delivery-overview#free-shipping) is applied if the sum of the (Custom) Line Item Prices reaches the specified value.
  isMatching?:
    type: boolean
    description: |
      `true` if the ShippingRate matches given [Cart](ctp:api:type:Cart) or [Location](ctp:api:type:Location).
      Only appears in response to requests for [Get ShippingMethods for a Cart](ctp:api:endpoint:/{projectKey}/shipping-methods/matching-cart:GET) or
      [Get ShippingMethods for a Location](ctp:api:endpoint:/{projectKey}/shipping-methods/matching-location:GET).
  tiers:
    type: ShippingRatePriceTier[]
    description: Price tiers for the ShippingRate.
