#%RAML 1.0 DataType
(package): ShippingMethod
(docs-uri): https://docs.commercetools.com/http-api-projects-shippingMethods.html#shippingmethoddraft
type: object
displayName: ShippingMethodDraft
properties:
  key?:
    type: string
    description: ''
  name:
    type: string
    description: ''
  description?:
    type: string
    description: ''
  localizedDescription?:
    type: LocalizedString
    description: ''
  taxCategory:
    type: TaxCategoryResourceIdentifier
    description: ''
  zoneRates:
    description: ''
    type: ZoneRateDraft[]
  isDefault:
    description: If `true` the shipping method will be the default one in a project.
    type: boolean
  predicate?:
    type: string
    description:
      A Cart predicate which can be used to more precisely select a shipping
      method for a cart.
  custom?:
    type: CustomFieldsDraft
    description: ''
