#%RAML 1.0 DataType
(package): ShippingMethod
(docs-uri): https://docs.commercetools.com/api/projects/shippingMethods#shippingmethod
(java-extends): com.commercetools.api.models.Identifiable<ShippingMethod>
type: ResourceIdentifier
displayName: ShippingMethodResourceIdentifier
discriminatorValue: shipping-method
description: |
  [ResourceIdentifier](ctp:api:type:ResourceIdentifier) to a [ShippingMethod](ctp:api:type:ShippingMethod).
properties:
  id?:
    type: string
    description: |
      Unique identifier of the referenced [ShippingMethod](ctp:api:type:ShippingMethod). Either `id` or `key` is required.
  key?:
    type: string
    description: |
      User-defined unique identifier of the referenced [ShippingMethod](ctp:api:type:ShippingMethod). Either `id` or `key` is required.
