#%RAML 1.0 DataType
(package): ShippingMethod
type: object
displayName: ShippingMethodUpdate
properties:
  version:
    type: number
    format: int64
    description: |
      Expected version of the ShippingMethod on which the changes should be applied. If the expected version does not match the actual version, a 409 Conflict will be returned.
  actions:
    type: array
    items: ShippingMethodUpdateAction
    description: |
      Update actions to be performed on the [ShippingMethod](/projects/shippingMethods#shippingmethod).
