#%RAML 1.0 DataType
(package): ShippingMethod
displayName: ZoneRateDraft
type: object
properties:
  zone:
    type: ZoneResourceIdentifier
    description: |
      Sets the [Zone](ctp:api:type:Zone) for which the shippng rates are valid.
  shippingRates:
    type: ShippingRateDraft[]
    description: |
      Shipping rates for the `currencies` configured in the [Project](ctp:api:type:Project). The array must not contain two ShippingRates with the same [CurrencyCode](ctp:api:type:CurrencyCode).
