#%RAML 1.0 DataType
(annotations.package): Application
type: ApplicationUpdateAction
displayName: AddCountryUpdateAction
discriminatorValue: addCountry
example: !include ../../../examples/applications/AddCountryUpdateAction.json
properties:
  action:
    type: string
    enum: [addCountry]
  country:
    type: string
    description: |
      Country to add. Represented by two-digit country code as per ISO 3166-1 alpha-2.
