#%RAML 1.0 DataType
(annotations.package): Application
type: ApplicationUpdateAction
displayName: SetApplicationLogoUpdateAction
discriminatorValue: setApplicationLogo
example: !include ../../../examples/applications/SetApplicationLogoUpdateAction.json
properties:
  action:
    type: string
    enum: [setApplicationLogo]
  logo:
    type: ApplicationLogo
    description: |
      New logo to assign to the Application, which must be a valid url.
