#%RAML 1.0 DataType
(annotations.package): Application
type: ApplicationUpdateAction
displayName: SetApplicationAgreementStatus
discriminatorValue: setAgreementStatus
example: !include ../../../examples/applications/SetApplicationAgreementStatusUpdateAction.json
properties:
  action:
    type: string
    enum: [setAgreementStatus]
  agreementId:
    type: string
    description: |
      ID of the agreement to update.
  status:
    type: ApplicationAgreementStatus
    description: |
      New status for the agreement.
