#%RAML 1.0 DataType
(annotations.package): Application
type: ApplicationUpdateAction
displayName: SetApplicationAgreementType
discriminatorValue: setAgreementType
example: !include ../../../examples/applications/SetApplicationAgreementTypeUpdateAction.json
properties:
  action:
    type: string
    enum: [setAgreementType]
  agreementId:
    type: string
    description: |
      ID of the agreement to update.
  type:
    type: ApplicationAgreementType
    description: |
      New type for the agreement.
