#%RAML 1.0 DataType
(annotations.package): Application
type: ApplicationUpdateAction
displayName: SetApplicationAgreementName
discriminatorValue: setAgreementName
example: !include ../../../examples/applications/SetApplicationAgreementNameUpdateAction.json
properties:
  action:
    type: string
    enum: [setAgreementName]
  agreementId:
    type: string
    description: |
      ID of the agreement to update.
  name:
    type: string
    description: |
      New name for the agreement.
