#%RAML 1.0 DataType
(annotations.package): Application
type: ApplicationUpdateAction
displayName: SetCountriesUpdateAction
discriminatorValue: setCountries
example: !include ../../../examples/applications/SetCountriesUpdateAction.json
properties:
  action:
    type: string
    enum: [setCountries]
  countries:
    type: string[]
    description: |
      Sets a list of countries to the Application. Each country is represented by two-digit country code as per ISO 3166-1 alpha-2.
