#%RAML 1.0 DataType
(annotations.package): Application
type: ApplicationUpdateAction
displayName: SetDiscountsConfiguration
discriminatorValue: setDiscountsConfiguration
example: !include ../../../examples/applications/SetDiscountsConfigurationUpdateAction.json
properties:
  action:
    type: string
    enum: [setDiscountsConfiguration]
  discountsConfiguration:
    type: DiscountsConfiguration
    description: |
      New discounts configuration for the Application.
