#%RAML 1.0 DataType
(annotations.package): Application
type: ApplicationUpdateAction
displayName: SetDescriptionUpdateAction
discriminatorValue: setDescription
example: !include ../../../examples/applications/SetDescriptionUpdateAction.json
properties:
  action:
    type: string
    enum: [setDescription]
  description:
    type: LocalizedString
    description: |
      Value to set. If empty, any existing value will be removed.
