#%RAML 1.0 SecurityScheme

description: |
  HTTP API authorization uses [OAuth2](https://datatracker.ietf.org/doc/html/rfc6750).

  Clients must obtain an access token from the auth service using one of
  the authorization flows described below, before they are able to make authorized requests
  to other Composable Commerce APIs. On successful completion of an authorization flow,
  a client will be given an `access_token`, which they need to include in requests
  to authorized service endpoints via the HTTP `Authorization` header like this:
type: OAuth 2.0
describedBy:
  headers:
    Authorization:
      description: |
        On successful completion of an authorization flow,
        a client will be given an `access_token`, which they need to include in requests
        to authorized service endpoints via the HTTP `Authorization` header like this:

        Authorization: Bearer {access_token}
      type: string
  responses:
    401:
      description: Unauthorized
settings:
  authorizationUri: https://auth.europe-west1.gcp.commercetools.com/oauth/{projectKey}/customers/token
  accessTokenUri: https://auth.europe-west1.gcp.commercetools.com/oauth/{projectKey}/customers/token
  authorizationGrants: [password]
  scopes:
    - 'view_api_clients:{projectKey}'
    - 'manage_api_clients:{projectKey}'
    - 'view_approval_flows:{projectKey}'
    - 'manage_approval_flows:{projectKey}'
    - 'view_approval_rules:{projectKey}'
    - 'manage_approval_rules:{projectKey}'
    - 'view_associate_roles:{projectKey}'
    - 'manage_associate_roles:{projectKey}'
    - 'view_attribute_groups:{projectKey}'
    - 'manage_attribute_groups:{projectKey}'
    - 'view_audit_log:{projectKey}'
    - 'view_business_units:{projectKey}'
    - 'manage_business_units:{projectKey}'
    - 'view_business_units:{projectKey}:{storeKey}'
    - 'manage_business_units:{projectKey}:{storeKey}'
    - 'manage_my_business_units:{projectKey}'
    - 'view_cart_discounts:{projectKey}'
    - 'manage_cart_discounts:{projectKey}'
    - 'view_cart_discounts:{projectKey}:{storeKey}'
    - 'manage_cart_discounts:{projectKey}:{storeKey}'
    - 'view_categories:{projectKey}'
    - 'manage_categories:{projectKey}'
    - 'view_customer_groups:{projectKey}'
    - 'manage_customer_groups:{projectKey}'
    - 'view_customers:{projectKey}'
    - 'manage_customers:{projectKey}'
    - 'view_customers:{projectKey}:{storeKey}'
    - 'manage_customers:{projectKey}:{storeKey}'
    - 'manage_my_profile:{projectKey}'
    - 'manage_my_profile:{projectKey}:{storeKey}'
    - 'view_discount_codes:{projectKey}'
    - 'manage_discount_codes:{projectKey}'
    - 'manage_extensions:{projectKey}'
    - 'view_key_value_documents:{projectKey}'
    - 'manage_key_value_documents:{projectKey}'
    - 'view_messages:{projectKey}'
    - 'view_orders:{projectKey}'
    - 'manage_orders:{projectKey}'
    - 'view_orders:{projectKey}:{storeKey}'
    - 'manage_orders:{projectKey}:{storeKey}'
    - 'manage_my_orders:{projectKey}'
    - 'manage_my_orders:{projectKey}:{storeKey}'
    - 'view_order_edits:{projectKey}'
    - 'manage_order_edits:{projectKey}'
    - 'view_payment_methods:{projectKey}'
    - 'manage_payment_methods:{projectKey}'
    - 'view_payments:{projectKey}'
    - 'manage_payments:{projectKey}'
    - 'manage_my_payments:{projectKey}'
    - 'view_products:{projectKey}'
    - 'manage_products:{projectKey}'
    - 'view_published_products:{projectKey}'
    - 'view_product_selections:{projectKey}'
    - 'manage_product_selections:{projectKey}'
    - 'manage_project:{projectKey}'
    - 'view_project_settings:{projectKey}'
    - 'manage_project_settings:{projectKey}'
    - 'view_quote_requests:{projectKey}'
    - 'manage_quote_requests:{projectKey}'
    - 'view_quote_requests:{projectKey}:{storeKey}'
    - 'manage_quote_requests:{projectKey}:{storeKey}'
    - 'manage_my_quote_requests:{projectKey}'
    - 'view_quotes:{projectKey}'
    - 'manage_quotes:{projectKey}'
    - 'view_quotes:{projectKey}:{storeKey}'
    - 'manage_quotes:{projectKey}:{storeKey}'
    - 'manage_my_quotes:{projectKey}'
    - 'view_recurring_orders:{projectKey}'
    - 'manage_recurring_orders:{projectKey}'
    - 'view_shipping_methods:{projectKey}'
    - 'manage_shipping_methods:{projectKey}'
    - 'view_shopping_lists:{projectKey}'
    - 'manage_shopping_lists:{projectKey}'
    - 'view_shopping_lists:{projectKey}:{storeKey}'
    - 'manage_shopping_lists:{projectKey}:{storeKey}'
    - 'manage_my_shopping_lists:{projectKey}'
    - 'manage_my_shopping_lists:{projectKey}:{storeKey}'
    - 'view_staged_quotes:{projectKey}'
    - 'manage_staged_quotes:{projectKey}'
    - 'view_staged_quotes:{projectKey}:{storeKey}'
    - 'manage_staged_quotes:{projectKey}:{storeKey}'
    - 'view_standalone_prices:{projectKey}'
    - 'manage_standalone_prices:{projectKey}'
    - 'view_states:{projectKey}'
    - 'manage_states:{projectKey}'
    - 'view_stores:{projectKey}'
    - 'manage_stores:{projectKey}'
    - 'manage_subscriptions:{projectKey}'
    - 'view_tax_categories:{projectKey}'
    - 'manage_tax_categories:{projectKey}'
    - 'view_types:{projectKey}'
    - 'manage_types:{projectKey}'
    - 'anonymous_id:{id}'
    - 'create_anonymous_token:{projectKey}'
    - 'customer_id:{id}'
    - 'external_user_id:{externalUserId}'
    - 'introspect_oauth_tokens:{projectKey}'
