#%RAML 1.0 DataType
(package): Subscription
displayName: AwsAuthenticationMode
type: string
description: Defines the method of authentication for AWS SQS and SNS Destinations.
enum:
  - Credentials
  - IAM
(enumDescriptions):
  Credentials: |
    Subscriptions with `Credentials` authentication mode are authenticated using an `accessKey` and `accessSecret` pair. This is the default authentication mode for backwards compatibility.
  IAM: |
    Subscriptions with `IAM` authentication mode are authenticated using Identity and Access Management (IAM). In this case, the user `arn:aws:iam::362576667341:user/subscriptions` requires permissions to send messages to the queue or publish to the topic. This is the recommended authentication mode, as it doesn't require additional key management.
default: Credentials
