#%RAML 1.0 DataType
(package): Subscription
type: Destination
displayName: AzureServiceBusDestination
discriminatorValue: AzureServiceBus
example: !include ../../examples/Subscription/SubscriptionAzureServiceBusDestination.json
description: |
  [Azure Service Bus](https://azure.microsoft.com/en-us/products/service-bus/) can be used as a pull-queue with [Queues](https://learn.microsoft.com/en-us/azure/service-bus-messaging/service-bus-queues-topics-subscriptions#queues), or to fan-out notifications with [Topics and Subscriptions](https://learn.microsoft.com/en-us/azure/service-bus-messaging/service-bus-queues-topics-subscriptions).
  To set up a Subscription with Azure Service Bus, first create a queue/topic in the [Azure Portal](https://azure.microsoft.com/en-us/get-started/azure-portal/) with a Shared Access Policy including the `Send` permission.
properties:
  connectionString:
    type: string
    description: |
      SharedAccessKey is partially hidden on retrieval for security reasons.
