#%RAML 1.0 DataType
(package): Subscription
type: Destination
displayName: AzureEventGridDestination
discriminatorValue: EventGrid
example: !include ../../examples/Subscription/SubscriptionAzureEventGridDestination.json
description: |
  [Azure Event Grid](https://azure.microsoft.com/en-us/services/event-grid/) can be used to push messages to Azure Functions, HTTP endpoints (webhooks), and several other Azure tools. Event Grid can only be used with the [CloudEventsFormat](ctp:api:type:CloudEventsFormat).
  To set up a Subscription with Azure Event Grid, first create a topic in the [Azure Portal](https://azure.microsoft.com/en/features/azure-portal/). To allow Composable Commerce to push messages to your topic, provide an [access key](https://docs.microsoft.com/en-us/azure/event-grid/get-access-keys).
properties:
  uri:
    type: string
    description: |
      URI of the topic.
  accessKey:
    type: string
    description: |
      Partially hidden on retrieval for security reasons.
