#%RAML 1.0 DataType
(package): Subscription
displayName: ChangeSubscriptionResourceTypeId
type: string
description: |
  Resource types supported by [ChangeSubscriptions](ctp:api:type:ChangeSubscription):
enum:
  - associate-role
  - business-unit
  - cart
  - cart-discount
  - category
  - channel
  - customer
  - customer-email-token
  - customer-group
  - customer-password-token
  - discount-code
  - extension
  - inventory-entry
  - key-value-document
  - order
  - order-edit
  - payment
  - product
  - product-discount
  - product-price
  - product-selection
  - product-type
  - quote
  - quote-request
  - review
  - shipping-method
  - shopping-list
  - staged-quote
  - standalone-price
  - state
  - store
  - subscription
  - tax-category
  - type
  - zone
(enumDescriptions):
  associate-role: |
    Changes related to [AssociateRoles](ctp:api:type:AssociateRole).
  business-unit: |
    Changes to [BusinessUnits](ctp:api:type:BusinessUnit).
  cart: |
    Changes to [Carts](ctp:api:type:Cart).
  cart-discount: |
    Changes to [CartDiscounts](ctp:api:type:CartDiscount).
  category: |
    Changes to [Categories](ctp:api:type:Category).
  channel: |
    Changes to [Channels](ctp:api:type:Channel).
  customer: |
    Changes to [Customers](ctp:api:type:Customer).
  customer-email-token: |
    Changes to [CustomerTokens](ctp:api:type:CustomerToken).
  customer-group: |
    Changes to [CustomerGroups](ctp:api:type:CustomerGroup).
  customer-password-token: |
    Changes to [CustomerTokens](ctp:api:type:CustomerToken).
  discount-code: |
    Changes to [DiscountCodes](ctp:api:type:DiscountCode).
  extension: |
    Changes to [Extensions](ctp:api:type:Extension).
  inventory-entry: |
    Changes to [InventoryEntries](ctp:api:type:InventoryEntry).
  key-value-document: |
    Changes to [CustomObjects](ctp:api:type:CustomObject).
  order: |
    Changes to [Orders](ctp:api:type:Order). Changes to Orders via [Order Edits](/../api/projects/order-edits) do not trigger a Message. To achieve this, a [MessageSubscription](ctp:api:type:MessageSubscription) to [Order Edit Applied Message](ctp:api:type:OrderEditAppliedMessage) is necessary.
  order-edit: |
    Changes to [OrderEdits](ctp:api:type:OrderEdit).
  payment: |
    Changes to [Payments](ctp:api:type:Payment).
  product: |
    Changes to [Products](ctp:api:type:Product).
  product-discount: |
    Changes to [ProductDiscount](ctp:api:type:ProductDiscount).
  product-price: |
    Changes to [EmbeddedPrices](ctp:api:type:Price).
  product-selection: |
    Changes to [ProductSelections](ctp:api:type:ProductSelection).
  product-type: |
    Changes to [ProductTypes](ctp:api:type:ProductType).
  quote: |
    Changes to [Quotes](ctp:api:type:Quote).
  quote-request: |
    Changes to [QuoteRequests](ctp:api:type:QuoteRequest).
  review: |
    Changes to [Reviews](ctp:api:type:Review).
  shipping-method: |
    Changes to [ShippingMethods](ctp:api:type:ShippingMethod).
  shopping-list: |
    Changes to [ShoppingLists](ctp:api:type:ShoppingList).
  staged-quote: |
    Changes to [StagedQuotes](ctp:api:type:StagedQuote).
  standalone-price: |
    Changes to [StandalonePrices](ctp:api:type:StandalonePrice).
  state: |
    Changes to [States](ctp:api:type:State).
  store: |
    Changes to [Stores](ctp:api:type:Store).
  subscription: |
    Changes to [Subscriptions](ctp:api:type:Subscription).
  tax-category: |
    Changes to [TaxCategories](ctp:api:type:TaxCategory).
  type: |
    Changes to [Types](ctp:api:type:Type).
  zone: |
    Changes to [Zones](ctp:api:type:Zone).
