#%RAML 1.0 DataType
(package): Subscription
(docs-uri): https://docs.commercetools.com/api/projects/subscriptions#cloudeventsformat
type: DeliveryFormat
displayName: CloudEventsFormat
discriminatorValue: CloudEvents
description: |
  The CloudEventsFormat can be used with any [Destination](#destination), and the payload is delivered in the `JSON Event Format`. [AzureEventGridDestination](ctp:api:type:AzureEventGridDestination) offers native support to filter and route CloudEvents.
properties:
  cloudEventsVersion:
    type: string
    enum:
      - '1.0'
    description: |
      Supported versions: "1.0".
