#%RAML 1.0 DataType
(package): Subscription
type: Destination
displayName: ConfluentCloudDestination
discriminatorValue: ConfluentCloud
example: !include ../../examples/Subscription/SubscriptionConfluentCloudDestination.json
description: |
  This destination can be used to push events and messages to [Confluent Cloud](https://www.confluent.io/confluent-cloud/).
  To set up a Subscription of this type, first, create a topic in Confluent Cloud.
  Then, to allow Composable Commerce to push events and messages to your topic, generate [API keys](https://docs.confluent.io/cloud/current/access-management/authenticate/api-keys/api-keys.html) for your topic, and create the Subscription destination using the generated credentials.

  The Composable Commerce producer uses the following values: `SASL_SSL` for`security.protocol`, `PLAIN` for`sasl.mechanism`, and the default value (1048576) for `max.request.size`.
properties:
  bootstrapServer:
    type: string
    description: |
      URL to the bootstrap server including the port number in the format `<xxxxx>.<region>.<provider>.confluent.cloud:9092`.
  apiKey:
    type: string
    description: |
      Partially hidden on retrieval for security reasons.
  apiSecret:
    type: string
    description: |
      Partially hidden on retrieval for security reasons.
  acks:
    type: string
    enum:
      - '0'
      - '1'
      - 'all'
    description: |
      The Kafka `acks` value. Can be `"0"`, `"1"`, or `"all"`.
  topic:
    type: string
    description: |
      The name of the topic.
  key?:
    type: string
    description: |
      The Kafka record key.
