#%RAML 1.0 DataType
(package): Subscription
(docs-uri): https://docs.commercetools.com/http-api-projects-subscriptions.html#platform-format
type: DeliveryFormat
displayName: DeliveryPlatformFormat
discriminatorValue: Platform
