#%RAML 1.0 DataType
(package): Subscription
type: SubscriptionNotification
displayName: DeliveryPayload
discriminator: notificationType
description: |
  All payloads for the [PlatformFormat](ctp:api:type:PlatformFormat) share these common fields.
properties:
  projectKey:
    type: string
    description: |
      `key` of the [Project](ctp:api:type:Project).
      Useful for processing notifications if the Destination receives them from multiple Projects.
  resource:
    type: Reference
    description: |
      Reference to the resource that triggered the notification.
  resourceUserProvidedIdentifiers?:
    type: UserProvidedIdentifiers
    description: |
      User-defined unique identifiers of the resource.
