#%RAML 1.0 DataType
(package): Subscription
type: object
displayName: EventSubscription
description: |
  For EventSubscription, the format of the payload is custom for each specific notification.
properties:
  resourceTypeId:
    type: EventSubscriptionResourceTypeId
    description: |
      Unique identifier for the type of resource, for example, `import-api`.
  types?:
    type: EventType[]
    description: |
      Must contain valid event types for the resource.
      For example, for resource type `import-api` the event type `ImportContainerCreated` is valid.
      If no `types` are given, the Subscription will receive all events for this resource.
