#%RAML 1.0 DataType
(package): Subscription
type: SubscriptionNotification
displayName: EventDeliveryPayload
discriminatorValue: Event
example: !include ../../examples/Subscription/event-payload.example.json
description: |
  This payload is sent for an [EventSubscription](ctp:api:type:EventSubscription).
properties:
  id:
    type: string
    description: |
      Unique identifier of the Event.
  type:
    type: EventType
    description: |
      The type of Event that has occurred.
  resourceType:
    type: string
    description: |
      The type of resource targeted by the Event.
  data:
    type: object
    description: |
      The data describing the event that has taken place.
  createdAt:
    type: datetime
    description: |
      Date and time (UTC) the resource was initially created.
