#%RAML 1.0 DataType
(package): Subscription
type: Destination
displayName: EventBridgeDestination
discriminatorValue: EventBridge
example: !include ../../examples/Subscription/SubscriptionEventBridgeDestination.json
description: |
  [AWS EventBridge](https://aws.amazon.com/eventbridge/) can be used to push events and messages to a serverless event bus that can forward them to AWS SQS, SNS, Lambda, and other AWS services based on forwarding rules.
  Once the Subscription is created, an equivalent "partner event source" is created in AWS EventBridge. This event source must be associated with an event bus for the Subscription setup to be complete.
properties:
  region:
    type: string
    description: |
      AWS region that receives the events.
  accountId:
    type: string
    description: |
      ID of the AWS account that receives the events.
