#%RAML 1.0 DataType
(package): Subscription
(docs-uri): https://docs.commercetools.com/api/projects/subscriptions#messagedeliverypayload
type: DeliveryPayload
displayName: MessageDeliveryPayload
discriminatorValue: Message
example: !include ../../examples/Subscription/message-payload.example.json
description: |
  This payload is sent for a [MessageSubscription](ctp:api:type:MessageSubscription).
properties:
  id:
    type: string
    description: |
      Unique ID of the message.
  version:
    type: number
    format: int64
    description: |
      Last seen version of the resource.
  createdAt:
    type: datetime
    description: |
      Date and time (UTC) the resource was initially created.
  lastModifiedAt:
    type: datetime
    description: |
      Date and time (UTC) the resource was last modified.
  sequenceNumber:
    type: number
    format: int64
    description: |
      Used to ensure all messages of the resource are processed in correct order.
      The `sequenceNumber` of the next message of the resource is a successor of the `sequenceNumber` of the current message.
  resourceVersion:
    type: number
    format: int64
    description: |
      Version of the resource on which the change was performed.
  payloadNotIncluded?:
    type: PayloadNotIncluded
    description: |
      If the payload does not fit into the size limit or its format is not accepted by the messaging service, the `payloadNotIncluded` field is present.
