#%RAML 1.0 DataType
(package): Subscription
(docs-uri): https://docs.commercetools.com/api/projects/subscriptions#platformformat
type: DeliveryFormat
displayName: PlatformFormat
discriminatorValue: Platform
description: |
  The PlatformFormat uses constructs that are similar to the ones used in the REST API, for example, on the [Messages Query HTTP API](/../api/projects/messages).
