#%RAML 1.0 DataType
(package): Subscription
(docs-uri): https://docs.commercetools.com/http-api-projects-subscriptions.html#resourcedeleted-payload
type: SubscriptionDelivery
displayName: ResourceDeletedDelivery
discriminatorValue: ResourceDeleted
properties:
  version:
    type: number
    format: int64
  modifiedAt:
    type: datetime
  dataErasure?:
    type: boolean
