#%RAML 1.0 DataType
(package): Subscription
type: DeliveryPayload
displayName: ResourceUpdatedDeliveryPayload
discriminatorValue: ResourceUpdated
example: !include ../../examples/Subscription/resource-updated-payload.example.json
description: |
  This payload is sent for a [ChangeSubscription](ctp:api:type:ChangeSubscription) when a resource is updated. This includes updates by a background process, like a change in product availability.
properties:
  projectKey:
    type: string
    description: |
      `key` of the [Project](ctp:api:type:Project).
      Useful for processing notifications if the Destination receives them from multiple Projects.
  resource:
    type: Reference
    description: |
      Reference to the resource that triggered the notification.
  resourceUserProvidedIdentifiers?:
    type: UserProvidedIdentifiers
    description: |
      User-defined unique identifiers of the resource.
  version:
    type: number
    format: int64
    description: |
      Last seen version of the resource.
  oldVersion:
    type: number
    format: int64
    description: |
      Version of the resource before the update.
  modifiedAt:
    type: datetime
    description: |
      Date and time (UTC) the resource was last updated.
