#%RAML 1.0 DataType
(package): Subscription
type: Destination
displayName: SnsDestination
discriminatorValue: SNS
properties:
  accessKey?:
    type: string
    description: Only present if `authenticationMode` is set to `Credentials`.
  accessSecret?:
    type: string
    description: Only present if `authenticationMode` is set to `Credentials`.
  topicArn:
    type: string
  authenticationMode?:
    type: AwsAuthenticationMode
    default: Credentials
    description: Defines the method of authentication for the SNS topic.
