#%RAML 1.0 DataType
(package): Subscription
type: Destination
displayName: SqsDestination
discriminatorValue: SQS
example: !include ../../examples/Subscription/SubscriptionSqsDestination.json
description: |
  [AWS SQS](https://aws.amazon.com/sqs/) is a pull-queue on AWS.
  The queue must be a [Standard](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/standard-queues.html) queue type with a `MaximumMessageSize` of `256 KB`.

  We recommend setting `authenticationMode` to `IAM`, to avoid unnecessary key management. For IAM authentication and before creating the Subscription, give permissions to the following user account: `arn:aws:iam::362576667341:user/subscriptions`. Otherwise, a test message will not be sent.

  If you prefer to use `Credentials` for authentication, we recommend [creating an IAM user](https://docs.aws.amazon.com/sns/latest/dg/sns-setting-up.html#create-iam-user) with an `accessKey` and `accessSecret` pair specifically for each Subscription.

  The IAM user should only have the `sqs:SendMessage` permission on this queue.
properties:
  accessKey?:
    type: string
    description: Only present if `authenticationMode` is set to `Credentials`.
  accessSecret?:
    type: string
    description: Only present if `authenticationMode` is set to `Credentials`.
  queueUrl:
    type: string
    description: |
      URL of the Amazon SQS queue.
  region:
    type: string
    description: |
      [AWS Region](https://docs.aws.amazon.com/general/latest/gr/rande-manage.html) the message queue is located in.
  authenticationMode?:
    type: AwsAuthenticationMode
    default: Credentials
    description: Defines the method of authentication for the SQS queue.
