#%RAML 1.0 DataType
(package): Subscription
type: object
displayName: SubscriptionUpdateAction
discriminator: action
(java-extends): 'com.commercetools.api.models.ResourceUpdateAction<SubscriptionUpdateAction>'
properties:
  action:
    type: string
