#%RAML 1.0 DataType
(package): Subscription
type: object
displayName: SubscriptionDraft
example: !include ../../examples/subscription-create.example.json
description: |
  Either `messages`, `changes`, or `events` must be set.
properties:
  destination:
    type: Destination
    description: |
      Messaging service to which the notifications are sent.
  key?:
    type: string
    description: |
      User-defined unique identifier for the Subscription.
    pattern: ^[A-Za-z0-9_-]+$
    minLength: 2
    maxLength: 256
  messages?:
    type: MessageSubscription[]
    description: |
      Messages to be subscribed to.
  changes?:
    type: ChangeSubscription[]
    description: |
      Changes to be subscribed to.
  events?:
    type: EventSubscription[]
    (beta): true
    description: |
      Events to be subscribed to.
  format?:
    type: DeliveryFormat
    description: |
      Format in which the payload is delivered. When not provided, the [PlatformFormat](ctp:api:type:PlatformFormat) is selected by default.
