@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface AddressDraft [[AddressDraft.svg]] extends BaseAddress {
    id: String
    key: String
    country: String
    title: String
    salutation: String
    firstName: String
    lastName: String
    streetName: String
    streetNumber: String
    additionalStreetInfo: String
    postalCode: String
    city: String
    region: String
    state: String
    company: String
    department: String
    building: String
    apartment: String
    pOBox: String
    phone: String
    mobile: String
    email: String
    fax: String
    additionalAddressInfo: String
    externalId: String
    custom: [[CustomFieldsDraft.svg CustomFieldsDraft]]
}
interface BaseAddress [[BaseAddress.svg]]  {
    id: String
    key: String
    country: String
    title: String
    salutation: String
    firstName: String
    lastName: String
    streetName: String
    streetNumber: String
    additionalStreetInfo: String
    postalCode: String
    city: String
    region: String
    state: String
    company: String
    department: String
    building: String
    apartment: String
    pOBox: String
    phone: String
    mobile: String
    email: String
    fax: String
    additionalAddressInfo: String
    externalId: String
}


interface BusinessUnitDraft [[BusinessUnitDraft.svg]]  {
    key: String
    status: [[BusinessUnitStatus.svg BusinessUnitStatus]]
    stores: [[StoreResourceIdentifier.svg List<StoreResourceIdentifier>]]
    storeMode: [[BusinessUnitStoreMode.svg BusinessUnitStoreMode]]
    unitType: [[BusinessUnitType.svg BusinessUnitType]]
    name: String
    contactEmail: String
    associateMode: [[BusinessUnitAssociateMode.svg BusinessUnitAssociateMode]]
    associates: [[AssociateDraft.svg List<AssociateDraft>]]
    approvalRuleMode: [[BusinessUnitApprovalRuleMode.svg BusinessUnitApprovalRuleMode]]
    addresses: [[AddressDraft.svg List<AddressDraft>]]
    shippingAddresses: [[Integer.svg List<Integer>]]
    defaultShippingAddress: Integer
    billingAddresses: [[Integer.svg List<Integer>]]
    defaultBillingAddress: Integer
    custom: [[CustomFieldsDraft.svg CustomFieldsDraft]]
}
interface CartDraft [[CartDraft.svg]]  {
    currency: String
    key: String
    customerId: String
    customerEmail: String
    customerGroup: [[CustomerGroupResourceIdentifier.svg CustomerGroupResourceIdentifier]]
    anonymousId: String
    businessUnit: [[BusinessUnitResourceIdentifier.svg BusinessUnitResourceIdentifier]]
    store: [[StoreResourceIdentifier.svg StoreResourceIdentifier]]
    lineItems: [[LineItemDraft.svg List<LineItemDraft>]]
    customLineItems: [[CustomLineItemDraft.svg List<CustomLineItemDraft>]]
    taxMode: [[TaxMode.svg TaxMode]]
    externalTaxRateForShippingMethod: [[ExternalTaxRateDraft.svg ExternalTaxRateDraft]]
    taxRoundingMode: [[RoundingMode.svg RoundingMode]]
    taxCalculationMode: [[TaxCalculationMode.svg TaxCalculationMode]]
    inventoryMode: [[InventoryMode.svg InventoryMode]]
    billingAddress: [[AddressDraft.svg AddressDraft]]
    shippingAddress: [[AddressDraft.svg AddressDraft]]
    shippingMethod: [[ShippingMethodResourceIdentifier.svg ShippingMethodResourceIdentifier]]
    shippingRateInput: [[ShippingRateInputDraft.svg ShippingRateInputDraft]]
    shippingMode: [[ShippingMode.svg ShippingMode]]
    customShipping: [[CustomShippingDraft.svg List<CustomShippingDraft>]]
    shipping: [[ShippingDraft.svg List<ShippingDraft>]]
    itemShippingAddresses: [[AddressDraft.svg List<AddressDraft>]]
    discountCodes: [[String.svg List<String>]]
    country: String
    locale: String
    origin: [[CartOrigin.svg CartOrigin]]
    deleteDaysAfterLastModification: Long
    custom: [[CustomFieldsDraft.svg CustomFieldsDraft]]
}
interface CustomerDraft [[CustomerDraft.svg]]  {
    key: String
    customerNumber: String
    externalId: String
    email: String
    password: String
    firstName: String
    lastName: String
    middleName: String
    title: String
    anonymousCartId: String
    anonymousCart: [[CartResourceIdentifier.svg CartResourceIdentifier]]
    anonymousId: String
    dateOfBirth: Date
    companyName: String
    vatId: String
    addresses: [[AddressDraft.svg List<AddressDraft>]]
    defaultShippingAddress: Integer
    shippingAddresses: [[Integer.svg List<Integer>]]
    defaultBillingAddress: Integer
    billingAddresses: [[Integer.svg List<Integer>]]
    isEmailVerified: Boolean
    customerGroup: [[CustomerGroupResourceIdentifier.svg CustomerGroupResourceIdentifier]]
    custom: [[CustomFieldsDraft.svg CustomFieldsDraft]]
    locale: String
    salutation: String
    stores: [[StoreResourceIdentifier.svg List<StoreResourceIdentifier>]]
    authenticationMode: [[AuthenticationMode.svg AuthenticationMode]]
    customerGroupAssignments: [[CustomerGroupAssignmentDraft.svg List<CustomerGroupAssignmentDraft>]]
}
interface MyBusinessUnitDraft [[MyBusinessUnitDraft.svg]]  {
    key: String
    unitType: [[BusinessUnitType.svg BusinessUnitType]]
    name: String
    contactEmail: String
    custom: [[CustomFieldsDraft.svg CustomFieldsDraft]]
    addresses: [[AddressDraft.svg List<AddressDraft>]]
    shippingAddresses: [[Integer.svg List<Integer>]]
    defaultShippingAddress: Integer
    billingAddresses: [[Integer.svg List<Integer>]]
    defaultBillingAddress: Integer
}
interface MyCartDraft [[MyCartDraft.svg]]  {
    currency: String
    customerEmail: String
    businessUnit: [[BusinessUnitResourceIdentifier.svg BusinessUnitResourceIdentifier]]
    store: [[StoreResourceIdentifier.svg StoreResourceIdentifier]]
    lineItems: [[MyLineItemDraft.svg List<MyLineItemDraft>]]
    taxMode: [[TaxMode.svg TaxMode]]
    inventoryMode: [[InventoryMode.svg InventoryMode]]
    billingAddress: [[AddressDraft.svg AddressDraft]]
    shippingAddress: [[AddressDraft.svg AddressDraft]]
    shippingMethod: [[ShippingMethodResourceIdentifier.svg ShippingMethodResourceIdentifier]]
    itemShippingAddresses: [[AddressDraft.svg List<AddressDraft>]]
    shippingMode: [[ShippingMode.svg ShippingMode]]
    discountCodes: [[String.svg List<String>]]
    country: String
    locale: String
    deleteDaysAfterLastModification: Long
    custom: [[CustomFieldsDraft.svg CustomFieldsDraft]]
}
interface MyCustomerDraft [[MyCustomerDraft.svg]]  {
    email: String
    password: String
    firstName: String
    lastName: String
    middleName: String
    title: String
    salutation: String
    dateOfBirth: Date
    companyName: String
    vatId: String
    addresses: [[AddressDraft.svg List<AddressDraft>]]
    defaultShippingAddress: Long
    defaultBillingAddress: Long
    custom: [[CustomFieldsDraft.svg CustomFieldsDraft]]
    locale: String
    stores: [[StoreResourceIdentifier.svg List<StoreResourceIdentifier>]]
}
interface OrderImportDraft [[OrderImportDraft.svg]]  {
    orderNumber: String
    purchaseOrderNumber: String
    customerId: String
    customerEmail: String
    customerGroup: [[CustomerGroupResourceIdentifier.svg CustomerGroupResourceIdentifier]]
    businessUnit: [[BusinessUnitResourceIdentifier.svg BusinessUnitResourceIdentifier]]
    store: [[StoreResourceIdentifier.svg StoreResourceIdentifier]]
    lineItems: [[LineItemImportDraft.svg List<LineItemImportDraft>]]
    customLineItems: [[CustomLineItemImportDraft.svg List<CustomLineItemImportDraft>]]
    totalPrice: [[Money.svg Money]]
    taxedPrice: [[TaxedPriceDraft.svg TaxedPriceDraft]]
    taxRoundingMode: [[RoundingMode.svg RoundingMode]]
    taxCalculationMode: [[TaxCalculationMode.svg TaxCalculationMode]]
    inventoryMode: [[InventoryMode.svg InventoryMode]]
    billingAddress: [[AddressDraft.svg AddressDraft]]
    shippingAddress: [[AddressDraft.svg AddressDraft]]
    itemShippingAddresses: [[AddressDraft.svg List<AddressDraft>]]
    shippingInfo: [[ShippingInfoImportDraft.svg ShippingInfoImportDraft]]
    paymentInfo: [[PaymentInfo.svg PaymentInfo]]
    paymentState: [[PaymentState.svg PaymentState]]
    shipmentState: [[ShipmentState.svg ShipmentState]]
    orderState: [[OrderState.svg OrderState]]
    state: [[StateReference.svg StateReference]]
    country: String
    origin: [[CartOrigin.svg CartOrigin]]
    completedAt: DateTime
    custom: [[CustomFieldsDraft.svg CustomFieldsDraft]]
}
interface BusinessUnitAddAddressAction [[BusinessUnitAddAddressAction.svg]]  {
    action: String
    address: [[AddressDraft.svg AddressDraft]]
}
interface BusinessUnitChangeAddressAction [[BusinessUnitChangeAddressAction.svg]]  {
    action: String
    addressId: String
    addressKey: String
    address: [[AddressDraft.svg AddressDraft]]
}
interface CustomShippingDraft [[CustomShippingDraft.svg]]  {
    key: String
    shippingMethodName: String
    shippingAddress: [[AddressDraft.svg AddressDraft]]
    shippingRate: [[ShippingRateDraft.svg ShippingRateDraft]]
    shippingRateInput: [[ShippingRateInputDraft.svg ShippingRateInputDraft]]
    taxCategory: [[TaxCategoryResourceIdentifier.svg TaxCategoryResourceIdentifier]]
    externalTaxRate: [[ExternalTaxRateDraft.svg ExternalTaxRateDraft]]
    deliveries: [[DeliveryDraft.svg List<DeliveryDraft>]]
    custom: [[CustomFieldsDraft.svg CustomFieldsDraft]]
}
interface ShippingDraft [[ShippingDraft.svg]]  {
    key: String
    shippingMethod: [[ShippingMethodReference.svg ShippingMethodReference]]
    shippingAddress: [[AddressDraft.svg AddressDraft]]
    shippingRateInput: [[ShippingRateInputDraft.svg ShippingRateInputDraft]]
    externalTaxRate: [[ExternalTaxRateDraft.svg ExternalTaxRateDraft]]
    deliveries: [[DeliveryDraft.svg List<DeliveryDraft>]]
    custom: [[CustomFieldsDraft.svg CustomFieldsDraft]]
}
interface CartAddCustomShippingMethodAction [[CartAddCustomShippingMethodAction.svg]]  {
    action: String
    shippingKey: String
    shippingMethodName: String
    shippingAddress: [[AddressDraft.svg AddressDraft]]
    shippingRate: [[ShippingRateDraft.svg ShippingRateDraft]]
    shippingRateInput: [[ShippingRateInputDraft.svg ShippingRateInputDraft]]
    taxCategory: [[TaxCategoryResourceIdentifier.svg TaxCategoryResourceIdentifier]]
    externalTaxRate: [[ExternalTaxRateDraft.svg ExternalTaxRateDraft]]
    deliveries: [[DeliveryDraft.svg List<DeliveryDraft>]]
    custom: [[CustomFieldsDraft.svg CustomFieldsDraft]]
}
interface CartAddItemShippingAddressAction [[CartAddItemShippingAddressAction.svg]]  {
    action: String
    address: [[AddressDraft.svg AddressDraft]]
}
interface CartAddShippingMethodAction [[CartAddShippingMethodAction.svg]]  {
    action: String
    shippingKey: String
    shippingMethod: [[ShippingMethodResourceIdentifier.svg ShippingMethodResourceIdentifier]]
    shippingAddress: [[AddressDraft.svg AddressDraft]]
    shippingRateInput: [[ShippingRateInputDraft.svg ShippingRateInputDraft]]
    externalTaxRate: [[ExternalTaxRateDraft.svg ExternalTaxRateDraft]]
    deliveries: [[DeliveryDraft.svg List<DeliveryDraft>]]
    custom: [[CustomFieldsDraft.svg CustomFieldsDraft]]
}
interface CartSetBillingAddressAction [[CartSetBillingAddressAction.svg]]  {
    action: String
    address: [[AddressDraft.svg AddressDraft]]
}
interface CartSetShippingAddressAction [[CartSetShippingAddressAction.svg]]  {
    action: String
    address: [[AddressDraft.svg AddressDraft]]
}
interface CartUpdateItemShippingAddressAction [[CartUpdateItemShippingAddressAction.svg]]  {
    action: String
    address: [[AddressDraft.svg AddressDraft]]
}
interface ChannelDraft [[ChannelDraft.svg]]  {
    key: String
    roles: [[ChannelRoleEnum.svg List<ChannelRoleEnum>]]
    name: [[LocalizedString.svg LocalizedString]]
    description: [[LocalizedString.svg LocalizedString]]
    address: [[AddressDraft.svg AddressDraft]]
    custom: [[CustomFieldsDraft.svg CustomFieldsDraft]]
    geoLocation: [[GeoJson.svg GeoJson]]
}
interface ChannelSetAddressAction [[ChannelSetAddressAction.svg]]  {
    action: String
    address: [[AddressDraft.svg AddressDraft]]
}
interface CustomerAddAddressAction [[CustomerAddAddressAction.svg]]  {
    action: String
    address: [[AddressDraft.svg AddressDraft]]
}
interface CustomerChangeAddressAction [[CustomerChangeAddressAction.svg]]  {
    action: String
    addressId: String
    addressKey: String
    address: [[AddressDraft.svg AddressDraft]]
}
interface MyBusinessUnitAddAddressAction [[MyBusinessUnitAddAddressAction.svg]]  {
    action: String
    address: [[AddressDraft.svg AddressDraft]]
}
interface MyBusinessUnitChangeAddressAction [[MyBusinessUnitChangeAddressAction.svg]]  {
    action: String
    addressId: String
    addressKey: String
    address: [[AddressDraft.svg AddressDraft]]
}
interface MyCartAddItemShippingAddressAction [[MyCartAddItemShippingAddressAction.svg]]  {
    action: String
    address: [[AddressDraft.svg AddressDraft]]
}
interface MyCartSetBillingAddressAction [[MyCartSetBillingAddressAction.svg]]  {
    action: String
    address: [[AddressDraft.svg AddressDraft]]
}
interface MyCartSetShippingAddressAction [[MyCartSetShippingAddressAction.svg]]  {
    action: String
    address: [[AddressDraft.svg AddressDraft]]
}
interface MyCartUpdateItemShippingAddressAction [[MyCartUpdateItemShippingAddressAction.svg]]  {
    action: String
    address: [[AddressDraft.svg AddressDraft]]
}
interface MyCustomerAddAddressAction [[MyCustomerAddAddressAction.svg]]  {
    action: String
    address: [[AddressDraft.svg AddressDraft]]
}
interface MyCustomerChangeAddressAction [[MyCustomerChangeAddressAction.svg]]  {
    action: String
    addressId: String
    addressKey: String
    address: [[AddressDraft.svg AddressDraft]]
}
interface StagedOrderAddDeliveryAction [[StagedOrderAddDeliveryAction.svg]]  {
    action: String
    deliveryKey: String
    shippingKey: String
    items: [[DeliveryItem.svg List<DeliveryItem>]]
    address: [[AddressDraft.svg AddressDraft]]
    parcels: [[ParcelDraft.svg List<ParcelDraft>]]
    custom: [[CustomFieldsDraft.svg CustomFieldsDraft]]
}
interface StagedOrderAddItemShippingAddressAction [[StagedOrderAddItemShippingAddressAction.svg]]  {
    action: String
    address: [[AddressDraft.svg AddressDraft]]
}
interface StagedOrderSetBillingAddressAction [[StagedOrderSetBillingAddressAction.svg]]  {
    action: String
    address: [[AddressDraft.svg AddressDraft]]
}
interface StagedOrderSetDeliveryAddressAction [[StagedOrderSetDeliveryAddressAction.svg]]  {
    action: String
    deliveryId: String
    deliveryKey: String
    address: [[AddressDraft.svg AddressDraft]]
}
interface StagedOrderSetShippingAddressAction [[StagedOrderSetShippingAddressAction.svg]]  {
    action: String
    address: [[AddressDraft.svg AddressDraft]]
}
interface StagedOrderSetShippingAddressAndCustomShippingMethodAction [[StagedOrderSetShippingAddressAndCustomShippingMethodAction.svg]]  {
    action: String
    address: [[AddressDraft.svg AddressDraft]]
    shippingMethodName: String
    shippingRate: [[ShippingRateDraft.svg ShippingRateDraft]]
    taxCategory: [[TaxCategoryResourceIdentifier.svg TaxCategoryResourceIdentifier]]
    externalTaxRate: [[ExternalTaxRateDraft.svg ExternalTaxRateDraft]]
    custom: [[CustomFieldsDraft.svg CustomFieldsDraft]]
}
interface StagedOrderSetShippingAddressAndShippingMethodAction [[StagedOrderSetShippingAddressAndShippingMethodAction.svg]]  {
    action: String
    address: [[AddressDraft.svg AddressDraft]]
    shippingMethod: [[ShippingMethodResourceIdentifier.svg ShippingMethodResourceIdentifier]]
    externalTaxRate: [[ExternalTaxRateDraft.svg ExternalTaxRateDraft]]
}
interface StagedOrderUpdateItemShippingAddressAction [[StagedOrderUpdateItemShippingAddressAction.svg]]  {
    action: String
    address: [[AddressDraft.svg AddressDraft]]
}
interface DeliveryDraft [[DeliveryDraft.svg]]  {
    key: String
    items: [[DeliveryItem.svg List<DeliveryItem>]]
    parcels: [[ParcelDraft.svg List<ParcelDraft>]]
    address: [[AddressDraft.svg AddressDraft]]
    custom: [[CustomFieldsDraft.svg CustomFieldsDraft]]
}
interface OrderAddDeliveryAction [[OrderAddDeliveryAction.svg]]  {
    action: String
    deliveryKey: String
    shippingKey: String
    items: [[DeliveryItem.svg List<DeliveryItem>]]
    address: [[AddressDraft.svg AddressDraft]]
    parcels: [[ParcelDraft.svg List<ParcelDraft>]]
    custom: [[CustomFieldsDraft.svg CustomFieldsDraft]]
}
interface OrderAddItemShippingAddressAction [[OrderAddItemShippingAddressAction.svg]]  {
    action: String
    address: [[AddressDraft.svg AddressDraft]]
}
interface OrderSetBillingAddressAction [[OrderSetBillingAddressAction.svg]]  {
    action: String
    address: [[AddressDraft.svg AddressDraft]]
}
interface OrderSetDeliveryAddressAction [[OrderSetDeliveryAddressAction.svg]]  {
    action: String
    deliveryId: String
    deliveryKey: String
    address: [[AddressDraft.svg AddressDraft]]
}
interface OrderSetShippingAddressAction [[OrderSetShippingAddressAction.svg]]  {
    action: String
    address: [[AddressDraft.svg AddressDraft]]
}
interface OrderUpdateItemShippingAddressAction [[OrderUpdateItemShippingAddressAction.svg]]  {
    action: String
    address: [[AddressDraft.svg AddressDraft]]
}

AddressDraft --> BusinessUnitDraft #green;text:green : "addresses"
AddressDraft --> CartDraft #green;text:green : "itemShippingAddresses"
AddressDraft --> CustomerDraft #green;text:green : "addresses"
AddressDraft --> MyBusinessUnitDraft #green;text:green : "addresses"
AddressDraft --> MyCartDraft #green;text:green : "itemShippingAddresses"
AddressDraft --> MyCustomerDraft #green;text:green : "addresses"
AddressDraft --> OrderImportDraft #green;text:green : "itemShippingAddresses"
AddressDraft --> BusinessUnitAddAddressAction #green;text:green : "address"
AddressDraft --> BusinessUnitChangeAddressAction #green;text:green : "address"
AddressDraft --> CartDraft #green;text:green : "billingAddress"
AddressDraft --> CartDraft #green;text:green : "shippingAddress"
AddressDraft --> CustomShippingDraft #green;text:green : "shippingAddress"
AddressDraft --> ShippingDraft #green;text:green : "shippingAddress"
AddressDraft --> CartAddCustomShippingMethodAction #green;text:green : "shippingAddress"
AddressDraft --> CartAddItemShippingAddressAction #green;text:green : "address"
AddressDraft --> CartAddShippingMethodAction #green;text:green : "shippingAddress"
AddressDraft --> CartSetBillingAddressAction #green;text:green : "address"
AddressDraft --> CartSetShippingAddressAction #green;text:green : "address"
AddressDraft --> CartUpdateItemShippingAddressAction #green;text:green : "address"
AddressDraft --> ChannelDraft #green;text:green : "address"
AddressDraft --> ChannelSetAddressAction #green;text:green : "address"
AddressDraft --> CustomerAddAddressAction #green;text:green : "address"
AddressDraft --> CustomerChangeAddressAction #green;text:green : "address"
AddressDraft --> MyCartDraft #green;text:green : "billingAddress"
AddressDraft --> MyCartDraft #green;text:green : "shippingAddress"
AddressDraft --> MyBusinessUnitAddAddressAction #green;text:green : "address"
AddressDraft --> MyBusinessUnitChangeAddressAction #green;text:green : "address"
AddressDraft --> MyCartAddItemShippingAddressAction #green;text:green : "address"
AddressDraft --> MyCartSetBillingAddressAction #green;text:green : "address"
AddressDraft --> MyCartSetShippingAddressAction #green;text:green : "address"
AddressDraft --> MyCartUpdateItemShippingAddressAction #green;text:green : "address"
AddressDraft --> MyCustomerAddAddressAction #green;text:green : "address"
AddressDraft --> MyCustomerChangeAddressAction #green;text:green : "address"
AddressDraft --> StagedOrderAddDeliveryAction #green;text:green : "address"
AddressDraft --> StagedOrderAddItemShippingAddressAction #green;text:green : "address"
AddressDraft --> StagedOrderSetBillingAddressAction #green;text:green : "address"
AddressDraft --> StagedOrderSetDeliveryAddressAction #green;text:green : "address"
AddressDraft --> StagedOrderSetShippingAddressAction #green;text:green : "address"
AddressDraft --> StagedOrderSetShippingAddressAndCustomShippingMethodAction #green;text:green : "address"
AddressDraft --> StagedOrderSetShippingAddressAndShippingMethodAction #green;text:green : "address"
AddressDraft --> StagedOrderUpdateItemShippingAddressAction #green;text:green : "address"
AddressDraft --> DeliveryDraft #green;text:green : "address"
AddressDraft --> OrderImportDraft #green;text:green : "billingAddress"
AddressDraft --> OrderImportDraft #green;text:green : "shippingAddress"
AddressDraft --> OrderAddDeliveryAction #green;text:green : "address"
AddressDraft --> OrderAddItemShippingAddressAction #green;text:green : "address"
AddressDraft --> OrderSetBillingAddressAction #green;text:green : "address"
AddressDraft --> OrderSetDeliveryAddressAction #green;text:green : "address"
AddressDraft --> OrderSetShippingAddressAction #green;text:green : "address"
AddressDraft --> OrderUpdateItemShippingAddressAction #green;text:green : "address"
@enduml
