@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface ApprovalFlowSetCustomTypeAction [[ApprovalFlowSetCustomTypeAction.svg]] extends ApprovalFlowUpdateAction {
    action: String
    type: [[TypeResourceIdentifier.svg TypeResourceIdentifier]]
    fields: [[FieldContainer.svg FieldContainer]]
}
interface ApprovalFlowUpdateAction [[ApprovalFlowUpdateAction.svg]]  {
    action: String
}





@enduml
