@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface ApproverConjunction [[ApproverConjunction.svg]]  {
    and: [[ApproverDisjunction.svg List<ApproverDisjunction>]]
}



interface ApproverHierarchy [[ApproverHierarchy.svg]]  {
    tiers: [[ApproverConjunction.svg List<ApproverConjunction>]]
}

ApproverConjunction --> ApproverHierarchy #green;text:green : "tiers"
@enduml
