@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface ApprovalRuleUpdateAction [[ApprovalRuleUpdateAction.svg]]  {
    action: String
}


interface ApprovalRuleSetApproversAction [[ApprovalRuleSetApproversAction.svg]]  {
    action: String
    approvers: [[ApproverHierarchyDraft.svg ApproverHierarchyDraft]]
}
interface ApprovalRuleSetDescriptionAction [[ApprovalRuleSetDescriptionAction.svg]]  {
    action: String
    description: String
}
interface ApprovalRuleSetKeyAction [[ApprovalRuleSetKeyAction.svg]]  {
    action: String
    key: String
}
interface ApprovalRuleSetNameAction [[ApprovalRuleSetNameAction.svg]]  {
    action: String
    name: String
}
interface ApprovalRuleSetPredicateAction [[ApprovalRuleSetPredicateAction.svg]]  {
    action: String
    predicate: String
}
interface ApprovalRuleSetRequestersAction [[ApprovalRuleSetRequestersAction.svg]]  {
    action: String
    requesters: [[RuleRequesterDraft.svg List<RuleRequesterDraft>]]
}
interface ApprovalRuleSetStatusAction [[ApprovalRuleSetStatusAction.svg]]  {
    action: String
    status: [[ApprovalRuleStatus.svg ApprovalRuleStatus]]
}
interface ApprovalRuleUpdate [[ApprovalRuleUpdate.svg]]  {
    version: Long
    actions: [[ApprovalRuleUpdateAction.svg List<ApprovalRuleUpdateAction>]]
}
ApprovalRuleUpdateAction --> ApprovalRuleSetApproversAction #blue;text:blue : "action : setApprovers"
ApprovalRuleUpdateAction --> ApprovalRuleSetDescriptionAction #blue;text:blue : "action : setDescription"
ApprovalRuleUpdateAction --> ApprovalRuleSetKeyAction #blue;text:blue : "action : setKey"
ApprovalRuleUpdateAction --> ApprovalRuleSetNameAction #blue;text:blue : "action : setName"
ApprovalRuleUpdateAction --> ApprovalRuleSetPredicateAction #blue;text:blue : "action : setPredicate"
ApprovalRuleUpdateAction --> ApprovalRuleSetRequestersAction #blue;text:blue : "action : setRequesters"
ApprovalRuleUpdateAction --> ApprovalRuleSetStatusAction #blue;text:blue : "action : setStatus"
ApprovalRuleUpdateAction --> ApprovalRuleUpdate #green;text:green : "actions"
@enduml
