@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface ApprovalFlowUpdateAction [[ApprovalFlowUpdateAction.svg]]  {
    action: String
}


interface ApprovalFlowApproveAction [[ApprovalFlowApproveAction.svg]]  {
    action: String
}
interface ApprovalFlowRejectAction [[ApprovalFlowRejectAction.svg]]  {
    action: String
    reason: String
}
interface ApprovalFlowUpdate [[ApprovalFlowUpdate.svg]]  {
    version: Long
    actions: [[ApprovalFlowUpdateAction.svg List<ApprovalFlowUpdateAction>]]
}
ApprovalFlowUpdateAction --> ApprovalFlowApproveAction #blue;text:blue : "action : approve"
ApprovalFlowUpdateAction --> ApprovalFlowRejectAction #blue;text:blue : "action : reject"
ApprovalFlowUpdateAction --> ApprovalFlowUpdate #green;text:green : "actions"
@enduml
