@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface AssetDimensions [[AssetDimensions.svg]]  {
    w: Integer
    h: Integer
}



interface AssetSource [[AssetSource.svg]]  {
    uri: String
    key: String
    dimensions: [[AssetDimensions.svg AssetDimensions]]
    contentType: String
}

AssetDimensions --> AssetSource #green;text:green : "dimensions"
@enduml
