@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface AssociateRoleRemovePermissionAction [[AssociateRoleRemovePermissionAction.svg]] extends AssociateRoleUpdateAction {
    action: String
    permission: [[Permission.svg Permission]]
}
interface AssociateRoleUpdateAction [[AssociateRoleUpdateAction.svg]]  {
    action: String
}





@enduml
