@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface AssociateRoleResourceIdentifier [[AssociateRoleResourceIdentifier.svg]] extends ResourceIdentifier {
    typeId: [[ReferenceTypeId.svg ReferenceTypeId]]
    id: String
    key: String
}
interface ResourceIdentifier [[ResourceIdentifier.svg]]  {
    typeId: [[ReferenceTypeId.svg ReferenceTypeId]]
    id: String
    key: String
}


interface RuleApproverDraft [[RuleApproverDraft.svg]]  {
    associateRole: [[AssociateRoleResourceIdentifier.svg AssociateRoleResourceIdentifier]]
}
interface RuleRequesterDraft [[RuleRequesterDraft.svg]]  {
    associateRole: [[AssociateRoleResourceIdentifier.svg AssociateRoleResourceIdentifier]]
}
interface AssociateRoleAssignmentDraft [[AssociateRoleAssignmentDraft.svg]]  {
    associateRole: [[AssociateRoleResourceIdentifier.svg AssociateRoleResourceIdentifier]]
    inheritance: [[AssociateRoleInheritanceMode.svg AssociateRoleInheritanceMode]]
}
interface ProjectSetBusinessUnitAssociateRoleOnCreationAction [[ProjectSetBusinessUnitAssociateRoleOnCreationAction.svg]]  {
    action: String
    associateRole: [[AssociateRoleResourceIdentifier.svg AssociateRoleResourceIdentifier]]
}

AssociateRoleResourceIdentifier --> RuleApproverDraft #green;text:green : "associateRole"
AssociateRoleResourceIdentifier --> RuleRequesterDraft #green;text:green : "associateRole"
AssociateRoleResourceIdentifier --> AssociateRoleAssignmentDraft #green;text:green : "associateRole"
AssociateRoleResourceIdentifier --> ProjectSetBusinessUnitAssociateRoleOnCreationAction #green;text:green : "associateRole"
@enduml
