@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface AssociateRoleKeyReference [[AssociateRoleKeyReference.svg]] extends KeyReference {
    typeId: [[ReferenceTypeId.svg ReferenceTypeId]]
    key: String
}
interface KeyReference [[KeyReference.svg]]  {
    typeId: [[ReferenceTypeId.svg ReferenceTypeId]]
    key: String
}

interface AssociateRoleKeyReference [[AssociateRoleKeyReference.svg]]  {
    typeId: [[ReferenceTypeId.svg ReferenceTypeId]]
    key: String
}
interface AssociateRoleAssignment [[AssociateRoleAssignment.svg]]  {
    associateRole: [[AssociateRoleKeyReference.svg AssociateRoleKeyReference]]
    inheritance: [[AssociateRoleInheritanceMode.svg AssociateRoleInheritanceMode]]
}
interface InheritedAssociateRoleAssignment [[InheritedAssociateRoleAssignment.svg]]  {
    associateRole: [[AssociateRoleKeyReference.svg AssociateRoleKeyReference]]
    source: [[BusinessUnitKeyReference.svg BusinessUnitKeyReference]]
}
interface BusinessUnitConfiguration [[BusinessUnitConfiguration.svg]]  {
    myBusinessUnitStatusOnCreation: [[BusinessUnitConfigurationStatus.svg BusinessUnitConfigurationStatus]]
    myBusinessUnitAssociateRoleOnCreation: [[AssociateRoleKeyReference.svg AssociateRoleKeyReference]]
}
AssociateRoleKeyReference --> AssociateRoleKeyReference #blue;text:blue : "typeId : associate-role"
AssociateRoleKeyReference --> AssociateRoleAssignment #green;text:green : "associateRole"
AssociateRoleKeyReference --> InheritedAssociateRoleAssignment #green;text:green : "associateRole"
AssociateRoleKeyReference --> BusinessUnitConfiguration #green;text:green : "myBusinessUnitAssociateRoleOnCreation"
@enduml
