@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface Associate [[Associate.svg]]  {
    associateRoleAssignments: [[AssociateRoleAssignment.svg List<AssociateRoleAssignment>]]
    roles: [[AssociateRoleDeprecated.svg List<AssociateRoleDeprecated>]]
    customer: [[CustomerReference.svg CustomerReference]]
}



interface BusinessUnit [[BusinessUnit.svg]]  {
    id: String
    version: Long
    createdAt: DateTime
    lastModifiedAt: DateTime
    lastModifiedBy: [[LastModifiedBy.svg LastModifiedBy]]
    createdBy: [[CreatedBy.svg CreatedBy]]
    key: String
    status: [[BusinessUnitStatus.svg BusinessUnitStatus]]
    stores: [[StoreKeyReference.svg List<StoreKeyReference>]]
    inheritedStores: [[StoreKeyReference.svg List<StoreKeyReference>]]
    storeMode: [[BusinessUnitStoreMode.svg BusinessUnitStoreMode]]
    unitType: [[BusinessUnitType.svg BusinessUnitType]]
    name: String
    contactEmail: String
    custom: [[CustomFields.svg CustomFields]]
    customerGroupAssignments: [[CustomerGroupAssignment.svg List<CustomerGroupAssignment>]]
    addresses: [[Address.svg List<Address>]]
    shippingAddressIds: [[String.svg List<String>]]
    defaultShippingAddressId: String
    billingAddressIds: [[String.svg List<String>]]
    defaultBillingAddressId: String
    associateMode: [[BusinessUnitAssociateMode.svg BusinessUnitAssociateMode]]
    associates: [[Associate.svg List<Associate>]]
    inheritedAssociates: [[InheritedAssociate.svg List<InheritedAssociate>]]
    parentUnit: [[BusinessUnitKeyReference.svg BusinessUnitKeyReference]]
    topLevelUnit: [[BusinessUnitKeyReference.svg BusinessUnitKeyReference]]
    approvalRuleMode: [[BusinessUnitApprovalRuleMode.svg BusinessUnitApprovalRuleMode]]
}
interface BusinessUnitAssociatesSetMessage [[BusinessUnitAssociatesSetMessage.svg]]  {
    id: String
    version: Long
    createdAt: DateTime
    lastModifiedAt: DateTime
    lastModifiedBy: [[LastModifiedBy.svg LastModifiedBy]]
    createdBy: [[CreatedBy.svg CreatedBy]]
    sequenceNumber: Long
    resource: [[Reference.svg Reference]]
    resourceVersion: Long
    type: String
    resourceUserProvidedIdentifiers: [[UserProvidedIdentifiers.svg UserProvidedIdentifiers]]
    associates: [[Associate.svg List<Associate>]]
}
interface BusinessUnitAssociatesSetMessagePayload [[BusinessUnitAssociatesSetMessagePayload.svg]]  {
    type: String
    associates: [[Associate.svg List<Associate>]]
}
interface ApprovalFlowApproval [[ApprovalFlowApproval.svg]]  {
    approver: [[Associate.svg Associate]]
    approvedAt: DateTime
}
interface ApprovalFlowRejection [[ApprovalFlowRejection.svg]]  {
    rejecter: [[Associate.svg Associate]]
    rejectedAt: DateTime
    reason: String
}
interface BusinessUnitAssociateAddedMessage [[BusinessUnitAssociateAddedMessage.svg]]  {
    id: String
    version: Long
    createdAt: DateTime
    lastModifiedAt: DateTime
    lastModifiedBy: [[LastModifiedBy.svg LastModifiedBy]]
    createdBy: [[CreatedBy.svg CreatedBy]]
    sequenceNumber: Long
    resource: [[Reference.svg Reference]]
    resourceVersion: Long
    type: String
    resourceUserProvidedIdentifiers: [[UserProvidedIdentifiers.svg UserProvidedIdentifiers]]
    associate: [[Associate.svg Associate]]
}
interface BusinessUnitAssociateChangedMessage [[BusinessUnitAssociateChangedMessage.svg]]  {
    id: String
    version: Long
    createdAt: DateTime
    lastModifiedAt: DateTime
    lastModifiedBy: [[LastModifiedBy.svg LastModifiedBy]]
    createdBy: [[CreatedBy.svg CreatedBy]]
    sequenceNumber: Long
    resource: [[Reference.svg Reference]]
    resourceVersion: Long
    type: String
    resourceUserProvidedIdentifiers: [[UserProvidedIdentifiers.svg UserProvidedIdentifiers]]
    associate: [[Associate.svg Associate]]
}
interface BusinessUnitAssociateRemovedMessage [[BusinessUnitAssociateRemovedMessage.svg]]  {
    id: String
    version: Long
    createdAt: DateTime
    lastModifiedAt: DateTime
    lastModifiedBy: [[LastModifiedBy.svg LastModifiedBy]]
    createdBy: [[CreatedBy.svg CreatedBy]]
    sequenceNumber: Long
    resource: [[Reference.svg Reference]]
    resourceVersion: Long
    type: String
    resourceUserProvidedIdentifiers: [[UserProvidedIdentifiers.svg UserProvidedIdentifiers]]
    associate: [[Associate.svg Associate]]
}
interface BusinessUnitAssociateAddedMessagePayload [[BusinessUnitAssociateAddedMessagePayload.svg]]  {
    type: String
    associate: [[Associate.svg Associate]]
}
interface BusinessUnitAssociateChangedMessagePayload [[BusinessUnitAssociateChangedMessagePayload.svg]]  {
    type: String
    associate: [[Associate.svg Associate]]
}
interface BusinessUnitAssociateRemovedMessagePayload [[BusinessUnitAssociateRemovedMessagePayload.svg]]  {
    type: String
    associate: [[Associate.svg Associate]]
}

Associate --> BusinessUnit #green;text:green : "associates"
Associate --> BusinessUnitAssociatesSetMessage #green;text:green : "associates"
Associate --> BusinessUnitAssociatesSetMessagePayload #green;text:green : "associates"
Associate --> ApprovalFlowApproval #green;text:green : "approver"
Associate --> ApprovalFlowRejection #green;text:green : "rejecter"
Associate --> BusinessUnitAssociateAddedMessage #green;text:green : "associate"
Associate --> BusinessUnitAssociateChangedMessage #green;text:green : "associate"
Associate --> BusinessUnitAssociateRemovedMessage #green;text:green : "associate"
Associate --> BusinessUnitAssociateAddedMessagePayload #green;text:green : "associate"
Associate --> BusinessUnitAssociateChangedMessagePayload #green;text:green : "associate"
Associate --> BusinessUnitAssociateRemovedMessagePayload #green;text:green : "associate"
@enduml
