@startuml

hide methods
enum AttributeLevelEnum {
    PRODUCT
    VARIANT
}
interface AttributeDefinition [[AttributeDefinition.svg]]  {
    type: [[AttributeType.svg AttributeType]]
    name: String
    label: [[LocalizedString.svg LocalizedString]]
    isRequired: Boolean
    level: [[AttributeLevelEnum.svg AttributeLevelEnum]]
    attributeConstraint: [[AttributeConstraintEnum.svg AttributeConstraintEnum]]
    inputTip: [[LocalizedString.svg LocalizedString]]
    inputHint: [[TextInputHint.svg TextInputHint]]
    isSearchable: Boolean
}
interface AttributeDefinitionDraft [[AttributeDefinitionDraft.svg]]  {
    type: [[AttributeType.svg AttributeType]]
    name: String
    label: [[LocalizedString.svg LocalizedString]]
    isRequired: Boolean
    level: [[AttributeLevelEnum.svg AttributeLevelEnum]]
    attributeConstraint: [[AttributeConstraintEnum.svg AttributeConstraintEnum]]
    inputTip: [[LocalizedString.svg LocalizedString]]
    inputHint: [[TextInputHint.svg TextInputHint]]
    isSearchable: Boolean
}
AttributeLevelEnum --> AttributeDefinition #green;text:green : "level"
AttributeLevelEnum --> AttributeDefinitionDraft #green;text:green : "level"
@enduml
