@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface Attribute [[Attribute.svg]]  {
    name: String
    value: [[Object.svg Object]]
}



interface DuplicateAttributeValuesError [[DuplicateAttributeValuesError.svg]]  {
    code: String
    message: String
    attributes: [[Attribute.svg List<Attribute>]]
}
interface VariantValues [[VariantValues.svg]]  {
    sku: String
    prices: [[PriceDraft.svg List<PriceDraft>]]
    attributes: [[Attribute.svg List<Attribute>]]
}
interface ProductVariantImportDraft [[ProductVariantImportDraft.svg]]  {
    id: Long
    sku: String
    prices: [[PriceDraft.svg List<PriceDraft>]]
    attributes: [[Attribute.svg List<Attribute>]]
    images: [[Image.svg List<Image>]]
}
interface ProductVariant [[ProductVariant.svg]]  {
    id: Long
    sku: String
    key: String
    prices: [[Price.svg List<Price>]]
    attributes: [[Attribute.svg List<Attribute>]]
    price: [[Price.svg Price]]
    images: [[Image.svg List<Image>]]
    assets: [[Asset.svg List<Asset>]]
    availability: [[ProductVariantAvailability.svg ProductVariantAvailability]]
    isMatchingVariant: Boolean
    scopedPrice: [[ScopedPrice.svg ScopedPrice]]
    scopedPriceDiscounted: Boolean
}
interface ProductVariantDraft [[ProductVariantDraft.svg]]  {
    sku: String
    key: String
    prices: [[PriceDraft.svg List<PriceDraft>]]
    attributes: [[Attribute.svg List<Attribute>]]
    images: [[Image.svg List<Image>]]
    assets: [[AssetDraft.svg List<AssetDraft>]]
}
interface ProductAddVariantAction [[ProductAddVariantAction.svg]]  {
    action: String
    sku: String
    key: String
    prices: [[PriceDraft.svg List<PriceDraft>]]
    images: [[Image.svg List<Image>]]
    attributes: [[Attribute.svg List<Attribute>]]
    staged: Boolean
    assets: [[AssetDraft.svg List<AssetDraft>]]
}
interface DuplicateAttributeValueError [[DuplicateAttributeValueError.svg]]  {
    code: String
    message: String
    attribute: [[Attribute.svg Attribute]]
}

Attribute --> DuplicateAttributeValuesError #green;text:green : "attributes"
Attribute --> VariantValues #green;text:green : "attributes"
Attribute --> ProductVariantImportDraft #green;text:green : "attributes"
Attribute --> ProductVariant #green;text:green : "attributes"
Attribute --> ProductVariantDraft #green;text:green : "attributes"
Attribute --> ProductAddVariantAction #green;text:green : "attributes"
Attribute --> DuplicateAttributeValueError #green;text:green : "attribute"
@enduml
