@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface AttributeReference [[AttributeReference.svg]]  {
    key: String
}



interface AttributeGroup [[AttributeGroup.svg]]  {
    id: String
    version: Long
    createdAt: DateTime
    lastModifiedAt: DateTime
    lastModifiedBy: [[LastModifiedBy.svg LastModifiedBy]]
    createdBy: [[CreatedBy.svg CreatedBy]]
    name: [[LocalizedString.svg LocalizedString]]
    description: [[LocalizedString.svg LocalizedString]]
    attributes: [[AttributeReference.svg List<AttributeReference>]]
    key: String
}
interface AttributeGroupDraft [[AttributeGroupDraft.svg]]  {
    name: [[LocalizedString.svg LocalizedString]]
    description: [[LocalizedString.svg LocalizedString]]
    attributes: [[AttributeReference.svg List<AttributeReference>]]
    key: String
}
interface AttributeGroupSetAttributesAction [[AttributeGroupSetAttributesAction.svg]]  {
    action: String
    attributes: [[AttributeReference.svg List<AttributeReference>]]
}
interface AttributeGroupAddAttributeAction [[AttributeGroupAddAttributeAction.svg]]  {
    action: String
    attribute: [[AttributeReference.svg AttributeReference]]
}
interface AttributeGroupRemoveAttributeAction [[AttributeGroupRemoveAttributeAction.svg]]  {
    action: String
    attribute: [[AttributeReference.svg AttributeReference]]
}

AttributeReference --> AttributeGroup #green;text:green : "attributes"
AttributeReference --> AttributeGroupDraft #green;text:green : "attributes"
AttributeReference --> AttributeGroupSetAttributesAction #green;text:green : "attributes"
AttributeReference --> AttributeGroupAddAttributeAction #green;text:green : "attribute"
AttributeReference --> AttributeGroupRemoveAttributeAction #green;text:green : "attribute"
@enduml
