@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface AttributeGroupUpdateAction [[AttributeGroupUpdateAction.svg]]  {
    action: String
}


interface AttributeGroupAddAttributeAction [[AttributeGroupAddAttributeAction.svg]]  {
    action: String
    attribute: [[AttributeReference.svg AttributeReference]]
}
interface AttributeGroupChangeNameAction [[AttributeGroupChangeNameAction.svg]]  {
    action: String
    name: [[LocalizedString.svg LocalizedString]]
}
interface AttributeGroupRemoveAttributeAction [[AttributeGroupRemoveAttributeAction.svg]]  {
    action: String
    attribute: [[AttributeReference.svg AttributeReference]]
}
interface AttributeGroupSetAttributesAction [[AttributeGroupSetAttributesAction.svg]]  {
    action: String
    attributes: [[AttributeReference.svg List<AttributeReference>]]
}
interface AttributeGroupSetDescriptionAction [[AttributeGroupSetDescriptionAction.svg]]  {
    action: String
    description: [[LocalizedString.svg LocalizedString]]
}
interface AttributeGroupSetKeyAction [[AttributeGroupSetKeyAction.svg]]  {
    action: String
    key: String
}
interface AttributeGroupUpdate [[AttributeGroupUpdate.svg]]  {
    version: Long
    actions: [[AttributeGroupUpdateAction.svg List<AttributeGroupUpdateAction>]]
}
AttributeGroupUpdateAction --> AttributeGroupAddAttributeAction #blue;text:blue : "action : addAttribute"
AttributeGroupUpdateAction --> AttributeGroupChangeNameAction #blue;text:blue : "action : changeName"
AttributeGroupUpdateAction --> AttributeGroupRemoveAttributeAction #blue;text:blue : "action : removeAttribute"
AttributeGroupUpdateAction --> AttributeGroupSetAttributesAction #blue;text:blue : "action : setAttributes"
AttributeGroupUpdateAction --> AttributeGroupSetDescriptionAction #blue;text:blue : "action : setDescription"
AttributeGroupUpdateAction --> AttributeGroupSetKeyAction #blue;text:blue : "action : setKey"
AttributeGroupUpdateAction --> AttributeGroupUpdate #green;text:green : "actions"
@enduml
