@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface AttributeLocalizedEnumValue [[AttributeLocalizedEnumValue.svg]]  {
    key: String
    label: [[LocalizedString.svg LocalizedString]]
}



interface AttributeLocalizedEnumType [[AttributeLocalizedEnumType.svg]]  {
    name: String
    values: [[AttributeLocalizedEnumValue.svg List<AttributeLocalizedEnumValue>]]
}
interface ProductTypeChangeLocalizedEnumValueOrderAction [[ProductTypeChangeLocalizedEnumValueOrderAction.svg]]  {
    action: String
    attributeName: String
    values: [[AttributeLocalizedEnumValue.svg List<AttributeLocalizedEnumValue>]]
}
interface ProductTypeAddLocalizedEnumValueAction [[ProductTypeAddLocalizedEnumValueAction.svg]]  {
    action: String
    attributeName: String
    value: [[AttributeLocalizedEnumValue.svg AttributeLocalizedEnumValue]]
}
interface ProductTypeChangeLocalizedEnumValueLabelAction [[ProductTypeChangeLocalizedEnumValueLabelAction.svg]]  {
    action: String
    attributeName: String
    newValue: [[AttributeLocalizedEnumValue.svg AttributeLocalizedEnumValue]]
}

AttributeLocalizedEnumValue --> AttributeLocalizedEnumType #green;text:green : "values"
AttributeLocalizedEnumValue --> ProductTypeChangeLocalizedEnumValueOrderAction #green;text:green : "values"
AttributeLocalizedEnumValue --> ProductTypeAddLocalizedEnumValueAction #green;text:green : "value"
AttributeLocalizedEnumValue --> ProductTypeChangeLocalizedEnumValueLabelAction #green;text:green : "newValue"
@enduml
