@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface AuthorizationHeaderAuthentication [[AuthorizationHeaderAuthentication.svg]] extends HttpDestinationAuthentication {
    type: String
    headerValue: String
}
interface HttpDestinationAuthentication [[HttpDestinationAuthentication.svg]]  {
    type: String
}





@enduml
