@startuml

hide methods
enum BusinessUnitConfigurationStatus {
    ACTIVE
    INACTIVE
}
interface BusinessUnitConfiguration [[BusinessUnitConfiguration.svg]]  {
    myBusinessUnitStatusOnCreation: [[BusinessUnitConfigurationStatus.svg BusinessUnitConfigurationStatus]]
}
interface ProjectChangeBusinessUnitStatusOnCreationAction [[ProjectChangeBusinessUnitStatusOnCreationAction.svg]]  {
    action: String
    status: [[BusinessUnitConfigurationStatus.svg BusinessUnitConfigurationStatus]]
}
BusinessUnitConfigurationStatus --> BusinessUnitConfiguration #green;text:green : "myBusinessUnitStatusOnCreation"
BusinessUnitConfigurationStatus --> ProjectChangeBusinessUnitStatusOnCreationAction #green;text:green : "status"
@enduml
