@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface BusinessUnitSearchResult [[BusinessUnitSearchResult.svg]]  {
    id: String
    relevance: Double
}



interface BusinessUnitPagedSearchResponse [[BusinessUnitPagedSearchResponse.svg]]  {
    total: Long
    limit: Integer
    offset: Integer
    results: [[BusinessUnitSearchResult.svg List<BusinessUnitSearchResult>]]
}

BusinessUnitSearchResult --> BusinessUnitPagedSearchResponse #green;text:green : "results"
@enduml
