@startuml

hide methods
enum BusinessUnitType {
    COMPANY
    DIVISION
}
interface BusinessUnit [[BusinessUnit.svg]]  {
    id: String
    version: Long
    createdAt: DateTime
    lastModifiedAt: DateTime
    lastModifiedBy: [[LastModifiedBy.svg LastModifiedBy]]
    createdBy: [[CreatedBy.svg CreatedBy]]
    key: String
    status: [[BusinessUnitStatus.svg BusinessUnitStatus]]
    stores: [[StoreKeyReference.svg List<StoreKeyReference>]]
    inheritedStores: [[StoreKeyReference.svg List<StoreKeyReference>]]
    storeMode: [[BusinessUnitStoreMode.svg BusinessUnitStoreMode]]
    unitType: [[BusinessUnitType.svg BusinessUnitType]]
    name: String
    contactEmail: String
    custom: [[CustomFields.svg CustomFields]]
    addresses: [[Address.svg List<Address>]]
    shippingAddressIds: [[String.svg List<String>]]
    defaultShippingAddressId: String
    billingAddressIds: [[String.svg List<String>]]
    defaultBillingAddressId: String
    associateMode: [[BusinessUnitAssociateMode.svg BusinessUnitAssociateMode]]
    associates: [[Associate.svg List<Associate>]]
    inheritedAssociates: [[InheritedAssociate.svg List<InheritedAssociate>]]
    parentUnit: [[BusinessUnitKeyReference.svg BusinessUnitKeyReference]]
    topLevelUnit: [[BusinessUnitKeyReference.svg BusinessUnitKeyReference]]
    approvalRuleMode: [[BusinessUnitApprovalRuleMode.svg BusinessUnitApprovalRuleMode]]
}
interface BusinessUnitDraft [[BusinessUnitDraft.svg]]  {
    key: String
    status: [[BusinessUnitStatus.svg BusinessUnitStatus]]
    stores: [[StoreResourceIdentifier.svg List<StoreResourceIdentifier>]]
    storeMode: [[BusinessUnitStoreMode.svg BusinessUnitStoreMode]]
    unitType: [[BusinessUnitType.svg BusinessUnitType]]
    name: String
    contactEmail: String
    associateMode: [[BusinessUnitAssociateMode.svg BusinessUnitAssociateMode]]
    associates: [[AssociateDraft.svg List<AssociateDraft>]]
    approvalRuleMode: [[BusinessUnitApprovalRuleMode.svg BusinessUnitApprovalRuleMode]]
    addresses: [[BaseAddress.svg List<BaseAddress>]]
    shippingAddresses: [[Integer.svg List<Integer>]]
    defaultShippingAddress: Integer
    billingAddresses: [[Integer.svg List<Integer>]]
    defaultBillingAddress: Integer
    custom: [[CustomFieldsDraft.svg CustomFieldsDraft]]
}
interface BusinessUnitSetUnitTypeAction [[BusinessUnitSetUnitTypeAction.svg]]  {
    action: String
    unitType: [[BusinessUnitType.svg BusinessUnitType]]
    parentUnit: [[BusinessUnitResourceIdentifier.svg BusinessUnitResourceIdentifier]]
}
interface MyBusinessUnitDraft [[MyBusinessUnitDraft.svg]]  {
    key: String
    unitType: [[BusinessUnitType.svg BusinessUnitType]]
    name: String
    contactEmail: String
    custom: [[CustomFieldsDraft.svg CustomFieldsDraft]]
    addresses: [[BaseAddress.svg List<BaseAddress>]]
    shippingAddresses: [[Integer.svg List<Integer>]]
    defaultShippingAddress: Integer
    billingAddresses: [[Integer.svg List<Integer>]]
    defaultBillingAddress: Integer
}
interface BusinessUnitTypeSetMessage [[BusinessUnitTypeSetMessage.svg]]  {
    id: String
    version: Long
    createdAt: DateTime
    lastModifiedAt: DateTime
    lastModifiedBy: [[LastModifiedBy.svg LastModifiedBy]]
    createdBy: [[CreatedBy.svg CreatedBy]]
    sequenceNumber: Long
    resource: [[Reference.svg Reference]]
    resourceVersion: Long
    type: String
    resourceUserProvidedIdentifiers: [[UserProvidedIdentifiers.svg UserProvidedIdentifiers]]
    parentUnit: [[BusinessUnitKeyReference.svg BusinessUnitKeyReference]]
    oldParentUnit: [[BusinessUnitKeyReference.svg BusinessUnitKeyReference]]
    unitType: [[BusinessUnitType.svg BusinessUnitType]]
    oldUnitType: [[BusinessUnitType.svg BusinessUnitType]]
}
interface BusinessUnitTypeSetMessagePayload [[BusinessUnitTypeSetMessagePayload.svg]]  {
    type: String
    parentUnit: [[BusinessUnitKeyReference.svg BusinessUnitKeyReference]]
    oldParentUnit: [[BusinessUnitKeyReference.svg BusinessUnitKeyReference]]
    unitType: [[BusinessUnitType.svg BusinessUnitType]]
    oldUnitType: [[BusinessUnitType.svg BusinessUnitType]]
}
BusinessUnitType --> BusinessUnit #green;text:green : "unitType"
BusinessUnitType --> BusinessUnitDraft #green;text:green : "unitType"
BusinessUnitType --> BusinessUnitSetUnitTypeAction #green;text:green : "unitType"
BusinessUnitType --> MyBusinessUnitDraft #green;text:green : "unitType"
BusinessUnitType --> BusinessUnitTypeSetMessage #green;text:green : "unitType"
BusinessUnitType --> BusinessUnitTypeSetMessage #green;text:green : "oldUnitType"
BusinessUnitType --> BusinessUnitTypeSetMessagePayload #green;text:green : "unitType"
BusinessUnitType --> BusinessUnitTypeSetMessagePayload #green;text:green : "oldUnitType"
@enduml
