@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface BusinessUnitRemoveAssociateAction [[BusinessUnitRemoveAssociateAction.svg]] extends BusinessUnitUpdateAction {
    action: String
    customer: [[CustomerResourceIdentifier.svg CustomerResourceIdentifier]]
}
interface BusinessUnitUpdateAction [[BusinessUnitUpdateAction.svg]]  {
    action: String
}





@enduml
