@startuml

hide methods
enum BusinessUnitIndexingStatus {
    SCHEDULED
    INDEXING
    READY
    FAILED
}
interface BusinessUnitSearchIndexingStatusResponse [[BusinessUnitSearchIndexingStatusResponse.svg]]  {
    status: [[BusinessUnitIndexingStatus.svg BusinessUnitIndexingStatus]]
    states: [[BusinessUnitIndexingProgress.svg BusinessUnitIndexingProgress]]
    startedAt: DateTime
    lastModifiedAt: DateTime
    retryCount: Integer
}
BusinessUnitIndexingStatus --> BusinessUnitSearchIndexingStatusResponse #green;text:green : "status"
@enduml
