@startuml

hide methods
enum BusinessUnitSearchStatus {
    ACTIVATED
    DEACTIVATED
}
interface ProjectChangeBusinessUnitSearchStatusAction [[ProjectChangeBusinessUnitSearchStatusAction.svg]]  {
    action: String
    status: [[BusinessUnitSearchStatus.svg BusinessUnitSearchStatus]]
}
BusinessUnitSearchStatus --> ProjectChangeBusinessUnitSearchStatusAction #green;text:green : "status"
@enduml
