@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface CartSetLineItemPriceAction [[CartSetLineItemPriceAction.svg]] extends CartUpdateAction {
    action: String
    lineItemId: String
    externalPrice: [[Money.svg Money]]
}
interface CartUpdateAction [[CartUpdateAction.svg]]  {
    action: String
}





@enduml
