@startuml

hide methods
enum CartMergeMode {
    MERGE_WITH_EXISTING_CUSTOMER_CART
    USE_AS_NEW_ACTIVE_CUSTOMER_CART
}
interface MergeCartDraft [[MergeCartDraft.svg]]  {
    anonymousCart: [[CartResourceIdentifier.svg CartResourceIdentifier]]
    mergeMode: [[CartMergeMode.svg CartMergeMode]]
    updateProductData: Boolean
    anonymousId: String
}
CartMergeMode --> MergeCartDraft #green;text:green : "mergeMode"
@enduml
