@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface CartDiscountChangeIsActiveAction [[CartDiscountChangeIsActiveAction.svg]] extends CartDiscountUpdateAction {
    action: String
    isActive: Boolean
}
interface CartDiscountUpdateAction [[CartDiscountUpdateAction.svg]]  {
    action: String
}





@enduml
