@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface CartSetCustomLineItemCustomFieldAction [[CartSetCustomLineItemCustomFieldAction.svg]] extends CartUpdateAction {
    action: String
    customLineItemId: String
    customLineItemKey: String
    name: String
    value: [[Object.svg Object]]
}
interface CartUpdateAction [[CartUpdateAction.svg]]  {
    action: String
}





@enduml
