@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface CartAddCustomLineItemAction [[CartAddCustomLineItemAction.svg]] extends CartUpdateAction {
    action: String
    money: [[Money.svg Money]]
    name: [[LocalizedString.svg LocalizedString]]
    key: String
    quantity: Long
    slug: String
    taxCategory: [[TaxCategoryResourceIdentifier.svg TaxCategoryResourceIdentifier]]
    externalTaxRate: [[ExternalTaxRateDraft.svg ExternalTaxRateDraft]]
    shippingDetails: [[ItemShippingDetailsDraft.svg ItemShippingDetailsDraft]]
    custom: [[CustomFieldsDraft.svg CustomFieldsDraft]]
    priceMode: [[CustomLineItemPriceMode.svg CustomLineItemPriceMode]]
}
interface CartUpdateAction [[CartUpdateAction.svg]]  {
    action: String
}





@enduml
