@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface CartDiscountUpdateAction [[CartDiscountUpdateAction.svg]]  {
    action: String
}


interface CartDiscountChangeCartPredicateAction [[CartDiscountChangeCartPredicateAction.svg]]  {
    action: String
    cartPredicate: String
}
interface CartDiscountChangeIsActiveAction [[CartDiscountChangeIsActiveAction.svg]]  {
    action: String
    isActive: Boolean
}
interface CartDiscountChangeNameAction [[CartDiscountChangeNameAction.svg]]  {
    action: String
    name: [[LocalizedString.svg LocalizedString]]
}
interface CartDiscountChangeRequiresDiscountCodeAction [[CartDiscountChangeRequiresDiscountCodeAction.svg]]  {
    action: String
    requiresDiscountCode: Boolean
}
interface CartDiscountChangeSortOrderAction [[CartDiscountChangeSortOrderAction.svg]]  {
    action: String
    sortOrder: String
}
interface CartDiscountChangeStackingModeAction [[CartDiscountChangeStackingModeAction.svg]]  {
    action: String
    stackingMode: [[StackingMode.svg StackingMode]]
}
interface CartDiscountChangeTargetAction [[CartDiscountChangeTargetAction.svg]]  {
    action: String
    target: [[CartDiscountTarget.svg CartDiscountTarget]]
}
interface CartDiscountChangeValueAction [[CartDiscountChangeValueAction.svg]]  {
    action: String
    value: [[CartDiscountValueDraft.svg CartDiscountValueDraft]]
}
interface CartDiscountSetCustomFieldAction [[CartDiscountSetCustomFieldAction.svg]]  {
    action: String
    name: String
    value: [[Object.svg Object]]
}
interface CartDiscountSetCustomTypeAction [[CartDiscountSetCustomTypeAction.svg]]  {
    action: String
    type: [[TypeResourceIdentifier.svg TypeResourceIdentifier]]
    fields: [[FieldContainer.svg FieldContainer]]
}
interface CartDiscountSetDescriptionAction [[CartDiscountSetDescriptionAction.svg]]  {
    action: String
    description: [[LocalizedString.svg LocalizedString]]
}
interface CartDiscountSetKeyAction [[CartDiscountSetKeyAction.svg]]  {
    action: String
    key: String
}
interface CartDiscountSetValidFromAction [[CartDiscountSetValidFromAction.svg]]  {
    action: String
    validFrom: DateTime
}
interface CartDiscountSetValidFromAndUntilAction [[CartDiscountSetValidFromAndUntilAction.svg]]  {
    action: String
    validFrom: DateTime
    validUntil: DateTime
}
interface CartDiscountSetValidUntilAction [[CartDiscountSetValidUntilAction.svg]]  {
    action: String
    validUntil: DateTime
}
interface CartDiscountUpdate [[CartDiscountUpdate.svg]]  {
    version: Long
    actions: [[CartDiscountUpdateAction.svg List<CartDiscountUpdateAction>]]
}
CartDiscountUpdateAction --> CartDiscountChangeCartPredicateAction #blue;text:blue : "action : changeCartPredicate"
CartDiscountUpdateAction --> CartDiscountChangeIsActiveAction #blue;text:blue : "action : changeIsActive"
CartDiscountUpdateAction --> CartDiscountChangeNameAction #blue;text:blue : "action : changeName"
CartDiscountUpdateAction --> CartDiscountChangeRequiresDiscountCodeAction #blue;text:blue : "action : changeRequiresDiscountCode"
CartDiscountUpdateAction --> CartDiscountChangeSortOrderAction #blue;text:blue : "action : changeSortOrder"
CartDiscountUpdateAction --> CartDiscountChangeStackingModeAction #blue;text:blue : "action : changeStackingMode"
CartDiscountUpdateAction --> CartDiscountChangeTargetAction #blue;text:blue : "action : changeTarget"
CartDiscountUpdateAction --> CartDiscountChangeValueAction #blue;text:blue : "action : changeValue"
CartDiscountUpdateAction --> CartDiscountSetCustomFieldAction #blue;text:blue : "action : setCustomField"
CartDiscountUpdateAction --> CartDiscountSetCustomTypeAction #blue;text:blue : "action : setCustomType"
CartDiscountUpdateAction --> CartDiscountSetDescriptionAction #blue;text:blue : "action : setDescription"
CartDiscountUpdateAction --> CartDiscountSetKeyAction #blue;text:blue : "action : setKey"
CartDiscountUpdateAction --> CartDiscountSetValidFromAction #blue;text:blue : "action : setValidFrom"
CartDiscountUpdateAction --> CartDiscountSetValidFromAndUntilAction #blue;text:blue : "action : setValidFromAndUntil"
CartDiscountUpdateAction --> CartDiscountSetValidUntilAction #blue;text:blue : "action : setValidUntil"
CartDiscountUpdateAction --> CartDiscountUpdate #green;text:green : "actions"
@enduml
