@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface CartDiscountPatternTarget [[CartDiscountPatternTarget.svg]] extends CartDiscountTarget {
    type: String
    triggerPattern: [[PatternComponent.svg List<PatternComponent>]]
    targetPattern: [[PatternComponent.svg List<PatternComponent>]]
    maxOccurrence: Integer
    selectionMode: [[SelectionMode.svg SelectionMode]]
}
interface CartDiscountTarget [[CartDiscountTarget.svg]]  {
    type: String
}





@enduml
