@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface CartDiscountSetCustomTypeAction [[CartDiscountSetCustomTypeAction.svg]] extends CartDiscountUpdateAction {
    action: String
    type: [[TypeResourceIdentifier.svg TypeResourceIdentifier]]
    fields: [[FieldContainer.svg FieldContainer]]
}
interface CartDiscountUpdateAction [[CartDiscountUpdateAction.svg]]  {
    action: String
}





@enduml
