@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface CartDiscountDraft [[CartDiscountDraft.svg]]  {
    name: [[LocalizedString.svg LocalizedString]]
    key: String
    description: [[LocalizedString.svg LocalizedString]]
    value: [[CartDiscountValueDraft.svg CartDiscountValueDraft]]
    cartPredicate: String
    target: [[CartDiscountTarget.svg CartDiscountTarget]]
    sortOrder: String
    isActive: Boolean
    validFrom: DateTime
    validUntil: DateTime
    requiresDiscountCode: Boolean
    stackingMode: [[StackingMode.svg StackingMode]]
    custom: [[CustomFieldsDraft.svg CustomFieldsDraft]]
}






@enduml
