@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface CategorySetAssetTagsAction [[CategorySetAssetTagsAction.svg]] extends CategoryUpdateAction {
    action: String
    assetId: String
    assetKey: String
    tags: [[String.svg List<String>]]
}
interface CategoryUpdateAction [[CategoryUpdateAction.svg]]  {
    action: String
}





@enduml
