@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface CentPrecisionMoney [[CentPrecisionMoney.svg]] extends TypedMoney {
    centAmount: Long
    currencyCode: String
    type: [[MoneyType.svg MoneyType]]
    fractionDigits: Integer
}
interface TypedMoney [[TypedMoney.svg]]  {
    centAmount: Long
    currencyCode: String
    type: [[MoneyType.svg MoneyType]]
    fractionDigits: Integer
}


interface CartDiscountValueAbsolute [[CartDiscountValueAbsolute.svg]]  {
    type: String
    money: [[CentPrecisionMoney.svg List<CentPrecisionMoney>]]
    applicationMode: [[DiscountApplicationMode.svg DiscountApplicationMode]]
}
interface ProductDiscountValueAbsolute [[ProductDiscountValueAbsolute.svg]]  {
    type: String
    money: [[CentPrecisionMoney.svg List<CentPrecisionMoney>]]
}
interface Cart [[Cart.svg]]  {
    id: String
    version: Long
    createdAt: DateTime
    lastModifiedAt: DateTime
    key: String
    customerId: String
    customerEmail: String
    customerGroup: [[CustomerGroupReference.svg CustomerGroupReference]]
    anonymousId: String
    businessUnit: [[BusinessUnitKeyReference.svg BusinessUnitKeyReference]]
    store: [[StoreKeyReference.svg StoreKeyReference]]
    lineItems: [[LineItem.svg List<LineItem>]]
    customLineItems: [[CustomLineItem.svg List<CustomLineItem>]]
    totalLineItemQuantity: Long
    totalPrice: [[CentPrecisionMoney.svg CentPrecisionMoney]]
    taxedPrice: [[TaxedPrice.svg TaxedPrice]]
    taxedShippingPrice: [[TaxedPrice.svg TaxedPrice]]
    discountOnTotalPrice: [[DiscountOnTotalPrice.svg DiscountOnTotalPrice]]
    taxMode: [[TaxMode.svg TaxMode]]
    priceRoundingMode: [[RoundingMode.svg RoundingMode]]
    taxRoundingMode: [[RoundingMode.svg RoundingMode]]
    taxCalculationMode: [[TaxCalculationMode.svg TaxCalculationMode]]
    inventoryMode: [[InventoryMode.svg InventoryMode]]
    cartState: [[CartState.svg CartState]]
    billingAddress: [[Address.svg Address]]
    shippingAddress: [[Address.svg Address]]
    shippingMode: [[ShippingMode.svg ShippingMode]]
    shippingKey: String
    shippingInfo: [[ShippingInfo.svg ShippingInfo]]
    shippingRateInput: [[ShippingRateInput.svg ShippingRateInput]]
    shippingCustomFields: [[CustomFields.svg CustomFields]]
    shipping: [[Shipping.svg List<Shipping>]]
    itemShippingAddresses: [[Address.svg List<Address>]]
    discountCodes: [[DiscountCodeInfo.svg List<DiscountCodeInfo>]]
    directDiscounts: [[DirectDiscount.svg List<DirectDiscount>]]
    refusedGifts: [[CartDiscountReference.svg List<CartDiscountReference>]]
    paymentInfo: [[PaymentInfo.svg PaymentInfo]]
    country: String
    locale: String
    origin: [[CartOrigin.svg CartOrigin]]
    custom: [[CustomFields.svg CustomFields]]
    discountTypeCombination: [[DiscountTypeCombination.svg DiscountTypeCombination]]
    deleteDaysAfterLastModification: Integer
    lastModifiedBy: [[LastModifiedBy.svg LastModifiedBy]]
    createdBy: [[CreatedBy.svg CreatedBy]]
}
interface CustomLineItem [[CustomLineItem.svg]]  {
    id: String
    key: String
    name: [[LocalizedString.svg LocalizedString]]
    money: [[TypedMoney.svg TypedMoney]]
    taxedPrice: [[TaxedItemPrice.svg TaxedItemPrice]]
    taxedPricePortions: [[MethodTaxedPrice.svg List<MethodTaxedPrice>]]
    totalPrice: [[CentPrecisionMoney.svg CentPrecisionMoney]]
    slug: String
    quantity: Long
    state: [[ItemState.svg List<ItemState>]]
    taxCategory: [[TaxCategoryReference.svg TaxCategoryReference]]
    taxRate: [[TaxRate.svg TaxRate]]
    perMethodTaxRate: [[MethodTaxRate.svg List<MethodTaxRate>]]
    discountedPricePerQuantity: [[DiscountedLineItemPriceForQuantity.svg List<DiscountedLineItemPriceForQuantity>]]
    custom: [[CustomFields.svg CustomFields]]
    shippingDetails: [[ItemShippingDetails.svg ItemShippingDetails]]
    priceMode: [[CustomLineItemPriceMode.svg CustomLineItemPriceMode]]
}
interface LineItem [[LineItem.svg]]  {
    id: String
    key: String
    productId: String
    productKey: String
    name: [[LocalizedString.svg LocalizedString]]
    productSlug: [[LocalizedString.svg LocalizedString]]
    productType: [[ProductTypeReference.svg ProductTypeReference]]
    variant: [[ProductVariant.svg ProductVariant]]
    price: [[Price.svg Price]]
    quantity: Long
    totalPrice: [[CentPrecisionMoney.svg CentPrecisionMoney]]
    discountedPricePerQuantity: [[DiscountedLineItemPriceForQuantity.svg List<DiscountedLineItemPriceForQuantity>]]
    taxedPrice: [[TaxedItemPrice.svg TaxedItemPrice]]
    taxedPricePortions: [[MethodTaxedPrice.svg List<MethodTaxedPrice>]]
    state: [[ItemState.svg List<ItemState>]]
    taxRate: [[TaxRate.svg TaxRate]]
    perMethodTaxRate: [[MethodTaxRate.svg List<MethodTaxRate>]]
    supplyChannel: [[ChannelReference.svg ChannelReference]]
    distributionChannel: [[ChannelReference.svg ChannelReference]]
    priceMode: [[LineItemPriceMode.svg LineItemPriceMode]]
    lineItemMode: [[LineItemMode.svg LineItemMode]]
    inventoryMode: [[InventoryMode.svg InventoryMode]]
    shippingDetails: [[ItemShippingDetails.svg ItemShippingDetails]]
    custom: [[CustomFields.svg CustomFields]]
    addedAt: DateTime
    lastModifiedAt: DateTime
}
interface ShippingInfo [[ShippingInfo.svg]]  {
    shippingMethodName: String
    price: [[CentPrecisionMoney.svg CentPrecisionMoney]]
    shippingRate: [[ShippingRate.svg ShippingRate]]
    taxedPrice: [[TaxedItemPrice.svg TaxedItemPrice]]
    taxRate: [[TaxRate.svg TaxRate]]
    taxCategory: [[TaxCategoryReference.svg TaxCategoryReference]]
    shippingMethod: [[ShippingMethodReference.svg ShippingMethodReference]]
    deliveries: [[Delivery.svg List<Delivery>]]
    discountedPrice: [[DiscountedLineItemPrice.svg DiscountedLineItemPrice]]
    shippingMethodState: [[ShippingMethodState.svg ShippingMethodState]]
}
interface TaxPortion [[TaxPortion.svg]]  {
    name: String
    rate: Double
    amount: [[CentPrecisionMoney.svg CentPrecisionMoney]]
}
interface TaxedItemPrice [[TaxedItemPrice.svg]]  {
    totalNet: [[CentPrecisionMoney.svg CentPrecisionMoney]]
    totalGross: [[CentPrecisionMoney.svg CentPrecisionMoney]]
    taxPortions: [[TaxPortion.svg List<TaxPortion>]]
    totalTax: [[CentPrecisionMoney.svg CentPrecisionMoney]]
}
interface TaxedPrice [[TaxedPrice.svg]]  {
    totalNet: [[CentPrecisionMoney.svg CentPrecisionMoney]]
    totalGross: [[CentPrecisionMoney.svg CentPrecisionMoney]]
    taxPortions: [[TaxPortion.svg List<TaxPortion>]]
    totalTax: [[CentPrecisionMoney.svg CentPrecisionMoney]]
}
interface MyPayment [[MyPayment.svg]]  {
    id: String
    version: Long
    customer: [[CustomerReference.svg CustomerReference]]
    anonymousId: String
    amountPlanned: [[CentPrecisionMoney.svg CentPrecisionMoney]]
    paymentMethodInfo: [[PaymentMethodInfo.svg PaymentMethodInfo]]
    transactions: [[Transaction.svg List<Transaction>]]
    custom: [[CustomFields.svg CustomFields]]
}
interface OrderLineItemDiscountSetMessage [[OrderLineItemDiscountSetMessage.svg]]  {
    id: String
    version: Long
    createdAt: DateTime
    lastModifiedAt: DateTime
    lastModifiedBy: [[LastModifiedBy.svg LastModifiedBy]]
    createdBy: [[CreatedBy.svg CreatedBy]]
    sequenceNumber: Long
    resource: [[Reference.svg Reference]]
    resourceVersion: Long
    type: String
    resourceUserProvidedIdentifiers: [[UserProvidedIdentifiers.svg UserProvidedIdentifiers]]
    lineItemId: String
    lineItemKey: String
    discountedPricePerQuantity: [[DiscountedLineItemPriceForQuantity.svg List<DiscountedLineItemPriceForQuantity>]]
    totalPrice: [[CentPrecisionMoney.svg CentPrecisionMoney]]
    taxedPrice: [[TaxedItemPrice.svg TaxedItemPrice]]
    taxedPricePortions: [[MethodTaxedPrice.svg List<MethodTaxedPrice>]]
}
interface OrderLineItemRemovedMessage [[OrderLineItemRemovedMessage.svg]]  {
    id: String
    version: Long
    createdAt: DateTime
    lastModifiedAt: DateTime
    lastModifiedBy: [[LastModifiedBy.svg LastModifiedBy]]
    createdBy: [[CreatedBy.svg CreatedBy]]
    sequenceNumber: Long
    resource: [[Reference.svg Reference]]
    resourceVersion: Long
    type: String
    resourceUserProvidedIdentifiers: [[UserProvidedIdentifiers.svg UserProvidedIdentifiers]]
    lineItemId: String
    lineItemKey: String
    removedQuantity: Long
    newQuantity: Long
    newState: [[ItemState.svg List<ItemState>]]
    newTotalPrice: [[CentPrecisionMoney.svg CentPrecisionMoney]]
    newTaxedPrice: [[TaxedItemPrice.svg TaxedItemPrice]]
    newPrice: [[Price.svg Price]]
    newShippingDetail: [[ItemShippingDetails.svg ItemShippingDetails]]
}
interface OrderLineItemDiscountSetMessagePayload [[OrderLineItemDiscountSetMessagePayload.svg]]  {
    type: String
    lineItemId: String
    lineItemKey: String
    discountedPricePerQuantity: [[DiscountedLineItemPriceForQuantity.svg List<DiscountedLineItemPriceForQuantity>]]
    totalPrice: [[CentPrecisionMoney.svg CentPrecisionMoney]]
    taxedPrice: [[TaxedItemPrice.svg TaxedItemPrice]]
    taxedPricePortions: [[MethodTaxedPrice.svg List<MethodTaxedPrice>]]
}
interface OrderLineItemRemovedMessagePayload [[OrderLineItemRemovedMessagePayload.svg]]  {
    type: String
    lineItemId: String
    lineItemKey: String
    removedQuantity: Long
    newQuantity: Long
    newState: [[ItemState.svg List<ItemState>]]
    newTotalPrice: [[CentPrecisionMoney.svg CentPrecisionMoney]]
    newTaxedPrice: [[TaxedItemPrice.svg TaxedItemPrice]]
    newPrice: [[Price.svg Price]]
    newShippingDetail: [[ItemShippingDetails.svg ItemShippingDetails]]
}
interface Order [[Order.svg]]  {
    id: String
    version: Long
    createdAt: DateTime
    lastModifiedAt: DateTime
    orderNumber: String
    purchaseOrderNumber: String
    customerId: String
    customerEmail: String
    customerGroup: [[CustomerGroupReference.svg CustomerGroupReference]]
    anonymousId: String
    businessUnit: [[BusinessUnitKeyReference.svg BusinessUnitKeyReference]]
    store: [[StoreKeyReference.svg StoreKeyReference]]
    lineItems: [[LineItem.svg List<LineItem>]]
    customLineItems: [[CustomLineItem.svg List<CustomLineItem>]]
    totalPrice: [[CentPrecisionMoney.svg CentPrecisionMoney]]
    taxedPrice: [[TaxedPrice.svg TaxedPrice]]
    taxedShippingPrice: [[TaxedPrice.svg TaxedPrice]]
    discountOnTotalPrice: [[DiscountOnTotalPrice.svg DiscountOnTotalPrice]]
    priceRoundingMode: [[RoundingMode.svg RoundingMode]]
    taxMode: [[TaxMode.svg TaxMode]]
    taxRoundingMode: [[RoundingMode.svg RoundingMode]]
    taxCalculationMode: [[TaxCalculationMode.svg TaxCalculationMode]]
    inventoryMode: [[InventoryMode.svg InventoryMode]]
    billingAddress: [[Address.svg Address]]
    shippingAddress: [[Address.svg Address]]
    shippingMode: [[ShippingMode.svg ShippingMode]]
    shippingKey: String
    shippingInfo: [[ShippingInfo.svg ShippingInfo]]
    shippingRateInput: [[ShippingRateInput.svg ShippingRateInput]]
    shippingCustomFields: [[CustomFields.svg CustomFields]]
    shipping: [[Shipping.svg List<Shipping>]]
    itemShippingAddresses: [[Address.svg List<Address>]]
    discountCodes: [[DiscountCodeInfo.svg List<DiscountCodeInfo>]]
    directDiscounts: [[DirectDiscount.svg List<DirectDiscount>]]
    refusedGifts: [[CartDiscountReference.svg List<CartDiscountReference>]]
    paymentInfo: [[PaymentInfo.svg PaymentInfo]]
    country: String
    locale: String
    origin: [[CartOrigin.svg CartOrigin]]
    cart: [[CartReference.svg CartReference]]
    quote: [[QuoteReference.svg QuoteReference]]
    orderState: [[OrderState.svg OrderState]]
    shipmentState: [[ShipmentState.svg ShipmentState]]
    paymentState: [[PaymentState.svg PaymentState]]
    state: [[StateReference.svg StateReference]]
    syncInfo: [[SyncInfo.svg List<SyncInfo>]]
    returnInfo: [[ReturnInfo.svg List<ReturnInfo>]]
    discountTypeCombination: [[DiscountTypeCombination.svg DiscountTypeCombination]]
    lastMessageSequenceNumber: Long
    custom: [[CustomFields.svg CustomFields]]
    completedAt: DateTime
    lastModifiedBy: [[LastModifiedBy.svg LastModifiedBy]]
    createdBy: [[CreatedBy.svg CreatedBy]]
}
interface Payment [[Payment.svg]]  {
    id: String
    version: Long
    createdAt: DateTime
    lastModifiedAt: DateTime
    lastModifiedBy: [[LastModifiedBy.svg LastModifiedBy]]
    createdBy: [[CreatedBy.svg CreatedBy]]
    customer: [[CustomerReference.svg CustomerReference]]
    anonymousId: String
    externalId: String
    interfaceId: String
    amountPlanned: [[CentPrecisionMoney.svg CentPrecisionMoney]]
    amountAuthorized: [[TypedMoney.svg TypedMoney]]
    authorizedUntil: String
    amountPaid: [[TypedMoney.svg TypedMoney]]
    amountRefunded: [[TypedMoney.svg TypedMoney]]
    paymentMethodInfo: [[PaymentMethodInfo.svg PaymentMethodInfo]]
    paymentStatus: [[PaymentStatus.svg PaymentStatus]]
    transactions: [[Transaction.svg List<Transaction>]]
    interfaceInteractions: [[CustomFields.svg List<CustomFields>]]
    custom: [[CustomFields.svg CustomFields]]
    key: String
}
interface Transaction [[Transaction.svg]]  {
    id: String
    timestamp: DateTime
    type: [[TransactionType.svg TransactionType]]
    amount: [[CentPrecisionMoney.svg CentPrecisionMoney]]
    interactionId: String
    state: [[TransactionState.svg TransactionState]]
    custom: [[CustomFields.svg CustomFields]]
}
interface ShippingRate [[ShippingRate.svg]]  {
    price: [[CentPrecisionMoney.svg CentPrecisionMoney]]
    freeAbove: [[CentPrecisionMoney.svg CentPrecisionMoney]]
    isMatching: Boolean
    tiers: [[ShippingRatePriceTier.svg List<ShippingRatePriceTier>]]
}

CentPrecisionMoney --> CartDiscountValueAbsolute #green;text:green : "money"
CentPrecisionMoney --> ProductDiscountValueAbsolute #green;text:green : "money"
CentPrecisionMoney --> Cart #green;text:green : "totalPrice"
CentPrecisionMoney --> CustomLineItem #green;text:green : "totalPrice"
CentPrecisionMoney --> LineItem #green;text:green : "totalPrice"
CentPrecisionMoney --> ShippingInfo #green;text:green : "price"
CentPrecisionMoney --> TaxPortion #green;text:green : "amount"
CentPrecisionMoney --> TaxedItemPrice #green;text:green : "totalNet"
CentPrecisionMoney --> TaxedItemPrice #green;text:green : "totalGross"
CentPrecisionMoney --> TaxedItemPrice #green;text:green : "totalTax"
CentPrecisionMoney --> TaxedPrice #green;text:green : "totalNet"
CentPrecisionMoney --> TaxedPrice #green;text:green : "totalGross"
CentPrecisionMoney --> TaxedPrice #green;text:green : "totalTax"
CentPrecisionMoney --> MyPayment #green;text:green : "amountPlanned"
CentPrecisionMoney --> OrderLineItemDiscountSetMessage #green;text:green : "totalPrice"
CentPrecisionMoney --> OrderLineItemRemovedMessage #green;text:green : "newTotalPrice"
CentPrecisionMoney --> OrderLineItemDiscountSetMessagePayload #green;text:green : "totalPrice"
CentPrecisionMoney --> OrderLineItemRemovedMessagePayload #green;text:green : "newTotalPrice"
CentPrecisionMoney --> Order #green;text:green : "totalPrice"
CentPrecisionMoney --> Payment #green;text:green : "amountPlanned"
CentPrecisionMoney --> Transaction #green;text:green : "amount"
CentPrecisionMoney --> ShippingRate #green;text:green : "price"
CentPrecisionMoney --> ShippingRate #green;text:green : "freeAbove"
@enduml
