@startuml

hide methods
enum ChangeSubscriptionResourceTypeId {
    APPROVAL_FLOW
    APPROVAL_RULE
    ASSOCIATE_ROLE
    ATTRIBUTE_GROUP
    BUSINESS_UNIT
    CART
    CART_DISCOUNT
    CATEGORY
    CHANNEL
    CUSTOMER
    CUSTOMER_EMAIL_TOKEN
    CUSTOMER_GROUP
    CUSTOMER_PASSWORD_TOKEN
    DISCOUNT_CODE
    DISCOUNT_GROUP
    EXTENSION
    INVENTORY_ENTRY
    KEY_VALUE_DOCUMENT
    ORDER
    ORDER_EDIT
    PAYMENT
    PRODUCT
    PRODUCT_DISCOUNT
    PRODUCT_SELECTION
    PRODUCT_TAILORING
    PRODUCT_TYPE
    QUOTE
    QUOTE_REQUEST
    RECURRENCE_POLICY
    RECURRING_ORDER
    REVIEW
    SHIPPING_METHOD
    SHOPPING_LIST
    STAGED_QUOTE
    STANDALONE_PRICE
    STATE
    STORE
    SUBSCRIPTION
    TAX_CATEGORY
    TYPE
    ZONE
}
interface ChangeSubscription [[ChangeSubscription.svg]]  {
    resourceTypeId: [[ChangeSubscriptionResourceTypeId.svg ChangeSubscriptionResourceTypeId]]
}
ChangeSubscriptionResourceTypeId --> ChangeSubscription #green;text:green : "resourceTypeId"
@enduml
