@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface CheckoutMessagePaymentsPayloadBaseData [[CheckoutMessagePaymentsPayloadBaseData.svg]]  {
    projectKey: String
    payment: [[PaymentReference.svg PaymentReference]]
    transactionId: String
    cart: [[CartReference.svg CartReference]]
    order: [[OrderReference.svg OrderReference]]
}



interface CheckoutPaymentAuthorizationCancelledEvent [[CheckoutPaymentAuthorizationCancelledEvent.svg]]  {
    id: String
    notificationType: String
    resourceType: [[EventSubscriptionResourceTypeId.svg EventSubscriptionResourceTypeId]]
    type: [[EventType.svg EventType]]
    createdAt: DateTime
    data: [[CheckoutMessagePaymentsPayloadBaseData.svg CheckoutMessagePaymentsPayloadBaseData]]
}
interface CheckoutPaymentAuthorizationFailedEvent [[CheckoutPaymentAuthorizationFailedEvent.svg]]  {
    id: String
    notificationType: String
    resourceType: [[EventSubscriptionResourceTypeId.svg EventSubscriptionResourceTypeId]]
    type: [[EventType.svg EventType]]
    createdAt: DateTime
    data: [[CheckoutMessagePaymentsPayloadBaseData.svg CheckoutMessagePaymentsPayloadBaseData]]
}
interface CheckoutPaymentAuthorizedEvent [[CheckoutPaymentAuthorizedEvent.svg]]  {
    id: String
    notificationType: String
    resourceType: [[EventSubscriptionResourceTypeId.svg EventSubscriptionResourceTypeId]]
    type: [[EventType.svg EventType]]
    createdAt: DateTime
    data: [[CheckoutMessagePaymentsPayloadBaseData.svg CheckoutMessagePaymentsPayloadBaseData]]
}
interface CheckoutPaymentCancelAuthorizationFailedEvent [[CheckoutPaymentCancelAuthorizationFailedEvent.svg]]  {
    id: String
    notificationType: String
    resourceType: [[EventSubscriptionResourceTypeId.svg EventSubscriptionResourceTypeId]]
    type: [[EventType.svg EventType]]
    createdAt: DateTime
    data: [[CheckoutMessagePaymentsPayloadBaseData.svg CheckoutMessagePaymentsPayloadBaseData]]
}
interface CheckoutPaymentChargeFailedEvent [[CheckoutPaymentChargeFailedEvent.svg]]  {
    id: String
    notificationType: String
    resourceType: [[EventSubscriptionResourceTypeId.svg EventSubscriptionResourceTypeId]]
    type: [[EventType.svg EventType]]
    createdAt: DateTime
    data: [[CheckoutMessagePaymentsPayloadBaseData.svg CheckoutMessagePaymentsPayloadBaseData]]
}
interface CheckoutPaymentChargedEvent [[CheckoutPaymentChargedEvent.svg]]  {
    id: String
    notificationType: String
    resourceType: [[EventSubscriptionResourceTypeId.svg EventSubscriptionResourceTypeId]]
    type: [[EventType.svg EventType]]
    createdAt: DateTime
    data: [[CheckoutMessagePaymentsPayloadBaseData.svg CheckoutMessagePaymentsPayloadBaseData]]
}
interface CheckoutPaymentRefundFailedEvent [[CheckoutPaymentRefundFailedEvent.svg]]  {
    id: String
    notificationType: String
    resourceType: [[EventSubscriptionResourceTypeId.svg EventSubscriptionResourceTypeId]]
    type: [[EventType.svg EventType]]
    createdAt: DateTime
    data: [[CheckoutMessagePaymentsPayloadBaseData.svg CheckoutMessagePaymentsPayloadBaseData]]
}
interface CheckoutPaymentRefundedEvent [[CheckoutPaymentRefundedEvent.svg]]  {
    id: String
    notificationType: String
    resourceType: [[EventSubscriptionResourceTypeId.svg EventSubscriptionResourceTypeId]]
    type: [[EventType.svg EventType]]
    createdAt: DateTime
    data: [[CheckoutMessagePaymentsPayloadBaseData.svg CheckoutMessagePaymentsPayloadBaseData]]
}

CheckoutMessagePaymentsPayloadBaseData --> CheckoutPaymentAuthorizationCancelledEvent #green;text:green : "data"
CheckoutMessagePaymentsPayloadBaseData --> CheckoutPaymentAuthorizationFailedEvent #green;text:green : "data"
CheckoutMessagePaymentsPayloadBaseData --> CheckoutPaymentAuthorizedEvent #green;text:green : "data"
CheckoutMessagePaymentsPayloadBaseData --> CheckoutPaymentCancelAuthorizationFailedEvent #green;text:green : "data"
CheckoutMessagePaymentsPayloadBaseData --> CheckoutPaymentChargeFailedEvent #green;text:green : "data"
CheckoutMessagePaymentsPayloadBaseData --> CheckoutPaymentChargedEvent #green;text:green : "data"
CheckoutMessagePaymentsPayloadBaseData --> CheckoutPaymentRefundFailedEvent #green;text:green : "data"
CheckoutMessagePaymentsPayloadBaseData --> CheckoutPaymentRefundedEvent #green;text:green : "data"
@enduml
