@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface ContainerAndKey [[ContainerAndKey.svg]]  {
    key: String
    container: String
}



interface UserProvidedIdentifiers [[UserProvidedIdentifiers.svg]]  {
    key: String
    externalId: String
    orderNumber: String
    customerNumber: String
    sku: String
    slug: [[LocalizedString.svg LocalizedString]]
    containerAndKey: [[ContainerAndKey.svg ContainerAndKey]]
}

ContainerAndKey --> UserProvidedIdentifiers #green;text:green : "containerAndKey"
@enduml
