@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface CounterDraft [[CounterDraft.svg]] extends SkipConfigurationDraft {
    type: String
    totalToSkip: Integer
}
interface SkipConfigurationDraft [[SkipConfigurationDraft.svg]]  {
    type: String
}





@enduml
