@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface CountOnCustomLineItemUnits [[CountOnCustomLineItemUnits.svg]] extends PatternComponent {
    type: String
    predicate: String
    minCount: Integer
    maxCount: Integer
    excludeCount: Integer
}
interface PatternComponent [[PatternComponent.svg]]  {
    type: String
}





@enduml
