@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface CustomerSearchIndexingStatusResponse [[CustomerSearchIndexingStatusResponse.svg]]  {
    status: [[CustomerIndexingStatus.svg CustomerIndexingStatus]]
    states: [[CustomerIndexingProgress.svg CustomerIndexingProgress]]
    startedAt: DateTime
    lastModifiedAt: DateTime
    retryCount: Integer
}






@enduml
