@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface CustomFieldEnumValue [[CustomFieldEnumValue.svg]]  {
    key: String
    label: String
}



interface CustomFieldEnumType [[CustomFieldEnumType.svg]]  {
    name: String
    values: [[CustomFieldEnumValue.svg List<CustomFieldEnumValue>]]
}
interface TypeAddEnumValueAction [[TypeAddEnumValueAction.svg]]  {
    action: String
    fieldName: String
    value: [[CustomFieldEnumValue.svg CustomFieldEnumValue]]
}
interface TypeChangeEnumValueLabelAction [[TypeChangeEnumValueLabelAction.svg]]  {
    action: String
    fieldName: String
    value: [[CustomFieldEnumValue.svg CustomFieldEnumValue]]
}

CustomFieldEnumValue --> CustomFieldEnumType #green;text:green : "values"
CustomFieldEnumValue --> TypeAddEnumValueAction #green;text:green : "value"
CustomFieldEnumValue --> TypeChangeEnumValueLabelAction #green;text:green : "value"
@enduml
