@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface CustomerGroupAssignment [[CustomerGroupAssignment.svg]]  {
    customerGroup: [[CustomerGroupReference.svg CustomerGroupReference]]
}



interface Customer [[Customer.svg]]  {
    id: String
    version: Long
    createdAt: DateTime
    lastModifiedAt: DateTime
    key: String
    customerNumber: String
    externalId: String
    lastModifiedBy: [[LastModifiedBy.svg LastModifiedBy]]
    createdBy: [[CreatedBy.svg CreatedBy]]
    email: String
    password: String
    firstName: String
    lastName: String
    middleName: String
    title: String
    dateOfBirth: Date
    companyName: String
    vatId: String
    addresses: [[Address.svg List<Address>]]
    defaultShippingAddressId: String
    shippingAddressIds: [[String.svg List<String>]]
    defaultBillingAddressId: String
    billingAddressIds: [[String.svg List<String>]]
    isEmailVerified: Boolean
    customerGroup: [[CustomerGroupReference.svg CustomerGroupReference]]
    customerGroupAssignments: [[CustomerGroupAssignment.svg List<CustomerGroupAssignment>]]
    custom: [[CustomFields.svg CustomFields]]
    locale: String
    salutation: String
    stores: [[StoreKeyReference.svg List<StoreKeyReference>]]
    authenticationMode: [[AuthenticationMode.svg AuthenticationMode]]
}
interface CustomerGroupAssignmentsSetMessage [[CustomerGroupAssignmentsSetMessage.svg]]  {
    id: String
    version: Long
    createdAt: DateTime
    lastModifiedAt: DateTime
    lastModifiedBy: [[LastModifiedBy.svg LastModifiedBy]]
    createdBy: [[CreatedBy.svg CreatedBy]]
    sequenceNumber: Long
    resource: [[Reference.svg Reference]]
    resourceVersion: Long
    type: String
    resourceUserProvidedIdentifiers: [[UserProvidedIdentifiers.svg UserProvidedIdentifiers]]
    customerGroupAssignments: [[CustomerGroupAssignment.svg List<CustomerGroupAssignment>]]
    oldCustomerGroupAssignments: [[CustomerGroupAssignment.svg List<CustomerGroupAssignment>]]
}
interface CustomerGroupAssignmentsSetMessagePayload [[CustomerGroupAssignmentsSetMessagePayload.svg]]  {
    type: String
    customerGroupAssignments: [[CustomerGroupAssignment.svg List<CustomerGroupAssignment>]]
    oldCustomerGroupAssignments: [[CustomerGroupAssignment.svg List<CustomerGroupAssignment>]]
}
interface CustomerGroupAssignmentAddedMessage [[CustomerGroupAssignmentAddedMessage.svg]]  {
    id: String
    version: Long
    createdAt: DateTime
    lastModifiedAt: DateTime
    lastModifiedBy: [[LastModifiedBy.svg LastModifiedBy]]
    createdBy: [[CreatedBy.svg CreatedBy]]
    sequenceNumber: Long
    resource: [[Reference.svg Reference]]
    resourceVersion: Long
    type: String
    resourceUserProvidedIdentifiers: [[UserProvidedIdentifiers.svg UserProvidedIdentifiers]]
    customerGroupAssignment: [[CustomerGroupAssignment.svg CustomerGroupAssignment]]
}
interface CustomerGroupAssignmentRemovedMessage [[CustomerGroupAssignmentRemovedMessage.svg]]  {
    id: String
    version: Long
    createdAt: DateTime
    lastModifiedAt: DateTime
    lastModifiedBy: [[LastModifiedBy.svg LastModifiedBy]]
    createdBy: [[CreatedBy.svg CreatedBy]]
    sequenceNumber: Long
    resource: [[Reference.svg Reference]]
    resourceVersion: Long
    type: String
    resourceUserProvidedIdentifiers: [[UserProvidedIdentifiers.svg UserProvidedIdentifiers]]
    customerGroupAssignment: [[CustomerGroupAssignment.svg CustomerGroupAssignment]]
}
interface CustomerGroupAssignmentAddedMessagePayload [[CustomerGroupAssignmentAddedMessagePayload.svg]]  {
    type: String
    customerGroupAssignment: [[CustomerGroupAssignment.svg CustomerGroupAssignment]]
}
interface CustomerGroupAssignmentRemovedMessagePayload [[CustomerGroupAssignmentRemovedMessagePayload.svg]]  {
    type: String
    customerGroupAssignment: [[CustomerGroupAssignment.svg CustomerGroupAssignment]]
}

CustomerGroupAssignment --> Customer #green;text:green : "customerGroupAssignments"
CustomerGroupAssignment --> CustomerGroupAssignmentsSetMessage #green;text:green : "customerGroupAssignments"
CustomerGroupAssignment --> CustomerGroupAssignmentsSetMessage #green;text:green : "oldCustomerGroupAssignments"
CustomerGroupAssignment --> CustomerGroupAssignmentsSetMessagePayload #green;text:green : "customerGroupAssignments"
CustomerGroupAssignment --> CustomerGroupAssignmentsSetMessagePayload #green;text:green : "oldCustomerGroupAssignments"
CustomerGroupAssignment --> CustomerGroupAssignmentAddedMessage #green;text:green : "customerGroupAssignment"
CustomerGroupAssignment --> CustomerGroupAssignmentRemovedMessage #green;text:green : "customerGroupAssignment"
CustomerGroupAssignment --> CustomerGroupAssignmentAddedMessagePayload #green;text:green : "customerGroupAssignment"
CustomerGroupAssignment --> CustomerGroupAssignmentRemovedMessagePayload #green;text:green : "customerGroupAssignment"
@enduml
