@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface CustomLineItemImportDraft [[CustomLineItemImportDraft.svg]]  {
    name: [[LocalizedString.svg LocalizedString]]
    quantity: Long
    money: [[Money.svg Money]]
    slug: String
    state: [[ItemState.svg List<ItemState>]]
    taxRate: [[TaxRate.svg TaxRate]]
    taxCategory: [[TaxCategoryResourceIdentifier.svg TaxCategoryResourceIdentifier]]
    custom: [[CustomFieldsDraft.svg CustomFieldsDraft]]
    shippingDetails: [[ItemShippingDetailsDraft.svg ItemShippingDetailsDraft]]
    priceMode: [[CustomLineItemPriceMode.svg CustomLineItemPriceMode]]
}



interface OrderImportDraft [[OrderImportDraft.svg]]  {
    orderNumber: String
    customerId: String
    customerEmail: String
    lineItems: [[LineItemImportDraft.svg List<LineItemImportDraft>]]
    customLineItems: [[CustomLineItemImportDraft.svg List<CustomLineItemImportDraft>]]
    totalPrice: [[Money.svg Money]]
    taxedPrice: [[TaxedPriceDraft.svg TaxedPriceDraft]]
    shippingAddress: [[BaseAddress.svg BaseAddress]]
    billingAddress: [[BaseAddress.svg BaseAddress]]
    customerGroup: [[CustomerGroupResourceIdentifier.svg CustomerGroupResourceIdentifier]]
    country: String
    orderState: [[OrderState.svg OrderState]]
    state: [[StateReference.svg StateReference]]
    shipmentState: [[ShipmentState.svg ShipmentState]]
    paymentState: [[PaymentState.svg PaymentState]]
    shippingInfo: [[ShippingInfoImportDraft.svg ShippingInfoImportDraft]]
    paymentInfo: [[PaymentInfo.svg PaymentInfo]]
    completedAt: DateTime
    custom: [[CustomFieldsDraft.svg CustomFieldsDraft]]
    inventoryMode: [[InventoryMode.svg InventoryMode]]
    taxRoundingMode: [[RoundingMode.svg RoundingMode]]
    itemShippingAddresses: [[BaseAddress.svg List<BaseAddress>]]
    businessUnit: [[BusinessUnitResourceIdentifier.svg BusinessUnitResourceIdentifier]]
    store: [[StoreResourceIdentifier.svg StoreResourceIdentifier]]
    origin: [[CartOrigin.svg CartOrigin]]
}

CustomLineItemImportDraft --> OrderImportDraft #green;text:green : "customLineItems"
@enduml
