@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface CustomerSetMiddleNameAction [[CustomerSetMiddleNameAction.svg]] extends CustomerUpdateAction {
    action: String
    middleName: String
}
interface CustomerUpdateAction [[CustomerUpdateAction.svg]]  {
    action: String
}





@enduml
