@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface CustomLineItemRecurrenceInfoDraft [[CustomLineItemRecurrenceInfoDraft.svg]]  {
    recurrencePolicy: [[RecurrencePolicyResourceIdentifier.svg RecurrencePolicyResourceIdentifier]]
}



interface CustomLineItemDraft [[CustomLineItemDraft.svg]]  {
    name: [[LocalizedString.svg LocalizedString]]
    key: String
    quantity: Long
    money: [[Money.svg Money]]
    slug: String
    taxCategory: [[TaxCategoryResourceIdentifier.svg TaxCategoryResourceIdentifier]]
    externalTaxRate: [[ExternalTaxRateDraft.svg ExternalTaxRateDraft]]
    custom: [[CustomFieldsDraft.svg CustomFieldsDraft]]
    shippingDetails: [[ItemShippingDetailsDraft.svg ItemShippingDetailsDraft]]
    priceMode: [[CustomLineItemPriceMode.svg CustomLineItemPriceMode]]
    recurrenceInfo: [[CustomLineItemRecurrenceInfoDraft.svg CustomLineItemRecurrenceInfoDraft]]
}
interface CartAddCustomLineItemAction [[CartAddCustomLineItemAction.svg]]  {
    action: String
    money: [[Money.svg Money]]
    name: [[LocalizedString.svg LocalizedString]]
    key: String
    quantity: Long
    slug: String
    taxCategory: [[TaxCategoryResourceIdentifier.svg TaxCategoryResourceIdentifier]]
    externalTaxRate: [[ExternalTaxRateDraft.svg ExternalTaxRateDraft]]
    shippingDetails: [[ItemShippingDetailsDraft.svg ItemShippingDetailsDraft]]
    custom: [[CustomFieldsDraft.svg CustomFieldsDraft]]
    priceMode: [[CustomLineItemPriceMode.svg CustomLineItemPriceMode]]
    recurrenceInfo: [[CustomLineItemRecurrenceInfoDraft.svg CustomLineItemRecurrenceInfoDraft]]
}
interface CartSetCustomLineItemRecurrenceInfoAction [[CartSetCustomLineItemRecurrenceInfoAction.svg]]  {
    action: String
    customLineItemId: String
    customLineItemKey: String
    recurrenceInfo: [[CustomLineItemRecurrenceInfoDraft.svg CustomLineItemRecurrenceInfoDraft]]
}
interface StagedOrderAddCustomLineItemAction [[StagedOrderAddCustomLineItemAction.svg]]  {
    action: String
    money: [[Money.svg Money]]
    name: [[LocalizedString.svg LocalizedString]]
    key: String
    quantity: Long
    slug: String
    taxCategory: [[TaxCategoryResourceIdentifier.svg TaxCategoryResourceIdentifier]]
    externalTaxRate: [[ExternalTaxRateDraft.svg ExternalTaxRateDraft]]
    shippingDetails: [[ItemShippingDetailsDraft.svg ItemShippingDetailsDraft]]
    priceMode: [[CustomLineItemPriceMode.svg CustomLineItemPriceMode]]
    custom: [[CustomFieldsDraft.svg CustomFieldsDraft]]
    recurrenceInfo: [[CustomLineItemRecurrenceInfoDraft.svg CustomLineItemRecurrenceInfoDraft]]
}

CustomLineItemRecurrenceInfoDraft --> CustomLineItemDraft #green;text:green : "recurrenceInfo"
CustomLineItemRecurrenceInfoDraft --> CartAddCustomLineItemAction #green;text:green : "recurrenceInfo"
CustomLineItemRecurrenceInfoDraft --> CartSetCustomLineItemRecurrenceInfoAction #green;text:green : "recurrenceInfo"
CustomLineItemRecurrenceInfoDraft --> StagedOrderAddCustomLineItemAction #green;text:green : "recurrenceInfo"
@enduml
