@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface CustomerToken [[CustomerToken.svg]]  {
    id: String
    createdAt: DateTime
    lastModifiedAt: DateTime
    customerId: String
    expiresAt: DateTime
    value: String
}






@enduml
