@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface CustomerResourceIdentifier [[CustomerResourceIdentifier.svg]] extends ResourceIdentifier {
    typeId: [[ReferenceTypeId.svg ReferenceTypeId]]
    id: String
    key: String
}
interface ResourceIdentifier [[ResourceIdentifier.svg]]  {
    typeId: [[ReferenceTypeId.svg ReferenceTypeId]]
    id: String
    key: String
}


interface AssociateDraft [[AssociateDraft.svg]]  {
    roles: [[AssociateRole.svg List<AssociateRole>]]
    customer: [[CustomerResourceIdentifier.svg CustomerResourceIdentifier]]
}
interface BusinessUnitRemoveAssociateAction [[BusinessUnitRemoveAssociateAction.svg]]  {
    action: String
    customer: [[CustomerResourceIdentifier.svg CustomerResourceIdentifier]]
}
interface MyBusinessUnitRemoveAssociateAction [[MyBusinessUnitRemoveAssociateAction.svg]]  {
    action: String
    customer: [[CustomerResourceIdentifier.svg CustomerResourceIdentifier]]
}
interface PaymentDraft [[PaymentDraft.svg]]  {
    customer: [[CustomerResourceIdentifier.svg CustomerResourceIdentifier]]
    anonymousId: String
    externalId: String
    interfaceId: String
    amountPlanned: [[Money.svg Money]]
    amountAuthorized: [[Money.svg Money]]
    authorizedUntil: String
    amountPaid: [[Money.svg Money]]
    amountRefunded: [[Money.svg Money]]
    paymentMethodInfo: [[PaymentMethodInfo.svg PaymentMethodInfo]]
    paymentStatus: [[PaymentStatusDraft.svg PaymentStatusDraft]]
    transactions: [[TransactionDraft.svg List<TransactionDraft>]]
    interfaceInteractions: [[CustomFieldsDraft.svg List<CustomFieldsDraft>]]
    custom: [[CustomFieldsDraft.svg CustomFieldsDraft]]
    key: String
}
interface PaymentSetCustomerAction [[PaymentSetCustomerAction.svg]]  {
    action: String
    customer: [[CustomerResourceIdentifier.svg CustomerResourceIdentifier]]
}
interface ReviewDraft [[ReviewDraft.svg]]  {
    key: String
    uniquenessValue: String
    locale: String
    authorName: String
    title: String
    text: String
    target: [[Object.svg Object]]
    state: [[StateResourceIdentifier.svg StateResourceIdentifier]]
    rating: Integer
    customer: [[CustomerResourceIdentifier.svg CustomerResourceIdentifier]]
    custom: [[CustomFieldsDraft.svg CustomFieldsDraft]]
}
interface ReviewSetCustomerAction [[ReviewSetCustomerAction.svg]]  {
    action: String
    customer: [[CustomerResourceIdentifier.svg CustomerResourceIdentifier]]
}
interface ShoppingListDraft [[ShoppingListDraft.svg]]  {
    name: [[LocalizedString.svg LocalizedString]]
    slug: [[LocalizedString.svg LocalizedString]]
    customer: [[CustomerResourceIdentifier.svg CustomerResourceIdentifier]]
    key: String
    description: [[LocalizedString.svg LocalizedString]]
    anonymousId: String
    deleteDaysAfterLastModification: Long
    lineItems: [[ShoppingListLineItemDraft.svg List<ShoppingListLineItemDraft>]]
    textLineItems: [[TextLineItemDraft.svg List<TextLineItemDraft>]]
    store: [[StoreResourceIdentifier.svg StoreResourceIdentifier]]
    custom: [[CustomFieldsDraft.svg CustomFieldsDraft]]
}
interface ShoppingListSetCustomerAction [[ShoppingListSetCustomerAction.svg]]  {
    action: String
    customer: [[CustomerResourceIdentifier.svg CustomerResourceIdentifier]]
}

CustomerResourceIdentifier --> AssociateDraft #green;text:green : "customer"
CustomerResourceIdentifier --> BusinessUnitRemoveAssociateAction #green;text:green : "customer"
CustomerResourceIdentifier --> MyBusinessUnitRemoveAssociateAction #green;text:green : "customer"
CustomerResourceIdentifier --> PaymentDraft #green;text:green : "customer"
CustomerResourceIdentifier --> PaymentSetCustomerAction #green;text:green : "customer"
CustomerResourceIdentifier --> ReviewDraft #green;text:green : "customer"
CustomerResourceIdentifier --> ReviewSetCustomerAction #green;text:green : "customer"
CustomerResourceIdentifier --> ShoppingListDraft #green;text:green : "customer"
CustomerResourceIdentifier --> ShoppingListSetCustomerAction #green;text:green : "customer"
@enduml
