@startuml

hide methods
enum CustomLineItemPriceMode {
    STANDARD
    EXTERNAL
}
interface CustomLineItem [[CustomLineItem.svg]]  {
    id: String
    key: String
    name: [[LocalizedString.svg LocalizedString]]
    money: [[TypedMoney.svg TypedMoney]]
    taxedPrice: [[TaxedItemPrice.svg TaxedItemPrice]]
    taxedPricePortions: [[MethodTaxedPrice.svg List<MethodTaxedPrice>]]
    totalPrice: [[CentPrecisionMoney.svg CentPrecisionMoney]]
    slug: String
    quantity: Long
    state: [[ItemState.svg List<ItemState>]]
    taxCategory: [[TaxCategoryReference.svg TaxCategoryReference]]
    taxRate: [[TaxRate.svg TaxRate]]
    perMethodTaxRate: [[MethodTaxRate.svg List<MethodTaxRate>]]
    discountedPricePerQuantity: [[DiscountedLineItemPriceForQuantity.svg List<DiscountedLineItemPriceForQuantity>]]
    custom: [[CustomFields.svg CustomFields]]
    shippingDetails: [[ItemShippingDetails.svg ItemShippingDetails]]
    priceMode: [[CustomLineItemPriceMode.svg CustomLineItemPriceMode]]
}
interface CustomLineItemDraft [[CustomLineItemDraft.svg]]  {
    name: [[LocalizedString.svg LocalizedString]]
    key: String
    quantity: Long
    money: [[Money.svg Money]]
    slug: String
    taxCategory: [[TaxCategoryResourceIdentifier.svg TaxCategoryResourceIdentifier]]
    externalTaxRate: [[ExternalTaxRateDraft.svg ExternalTaxRateDraft]]
    custom: [[CustomFieldsDraft.svg CustomFieldsDraft]]
    shippingDetails: [[ItemShippingDetailsDraft.svg ItemShippingDetailsDraft]]
    priceMode: [[CustomLineItemPriceMode.svg CustomLineItemPriceMode]]
}
interface CartAddCustomLineItemAction [[CartAddCustomLineItemAction.svg]]  {
    action: String
    money: [[Money.svg Money]]
    name: [[LocalizedString.svg LocalizedString]]
    key: String
    quantity: Long
    slug: String
    taxCategory: [[TaxCategoryResourceIdentifier.svg TaxCategoryResourceIdentifier]]
    externalTaxRate: [[ExternalTaxRateDraft.svg ExternalTaxRateDraft]]
    shippingDetails: [[ItemShippingDetailsDraft.svg ItemShippingDetailsDraft]]
    custom: [[CustomFieldsDraft.svg CustomFieldsDraft]]
    priceMode: [[CustomLineItemPriceMode.svg CustomLineItemPriceMode]]
}
interface CartChangeCustomLineItemPriceModeAction [[CartChangeCustomLineItemPriceModeAction.svg]]  {
    action: String
    customLineItemId: String
    customLineItemKey: String
    mode: [[CustomLineItemPriceMode.svg CustomLineItemPriceMode]]
}
interface StagedOrderAddCustomLineItemAction [[StagedOrderAddCustomLineItemAction.svg]]  {
    action: String
    money: [[Money.svg Money]]
    name: [[LocalizedString.svg LocalizedString]]
    key: String
    quantity: Long
    slug: String
    taxCategory: [[TaxCategoryResourceIdentifier.svg TaxCategoryResourceIdentifier]]
    externalTaxRate: [[ExternalTaxRateDraft.svg ExternalTaxRateDraft]]
    shippingDetails: [[ItemShippingDetailsDraft.svg ItemShippingDetailsDraft]]
    priceMode: [[CustomLineItemPriceMode.svg CustomLineItemPriceMode]]
    custom: [[CustomFieldsDraft.svg CustomFieldsDraft]]
}
interface CustomLineItemImportDraft [[CustomLineItemImportDraft.svg]]  {
    name: [[LocalizedString.svg LocalizedString]]
    key: String
    slug: String
    quantity: Long
    money: [[Money.svg Money]]
    taxRate: [[TaxRate.svg TaxRate]]
    taxCategory: [[TaxCategoryResourceIdentifier.svg TaxCategoryResourceIdentifier]]
    priceMode: [[CustomLineItemPriceMode.svg CustomLineItemPriceMode]]
    shippingDetails: [[ItemShippingDetailsDraft.svg ItemShippingDetailsDraft]]
    state: [[ItemState.svg List<ItemState>]]
    custom: [[CustomFieldsDraft.svg CustomFieldsDraft]]
}
CustomLineItemPriceMode --> CustomLineItem #green;text:green : "priceMode"
CustomLineItemPriceMode --> CustomLineItemDraft #green;text:green : "priceMode"
CustomLineItemPriceMode --> CartAddCustomLineItemAction #green;text:green : "priceMode"
CustomLineItemPriceMode --> CartChangeCustomLineItemPriceModeAction #green;text:green : "mode"
CustomLineItemPriceMode --> StagedOrderAddCustomLineItemAction #green;text:green : "priceMode"
CustomLineItemPriceMode --> CustomLineItemImportDraft #green;text:green : "priceMode"
@enduml
