@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface CustomerGroupAssignmentDraft [[CustomerGroupAssignmentDraft.svg]]  {
    customerGroup: [[CustomerGroupResourceIdentifier.svg CustomerGroupResourceIdentifier]]
}



interface BusinessUnitDraft [[BusinessUnitDraft.svg]]  {
    key: String
    status: [[BusinessUnitStatus.svg BusinessUnitStatus]]
    stores: [[StoreResourceIdentifier.svg List<StoreResourceIdentifier>]]
    storeMode: [[BusinessUnitStoreMode.svg BusinessUnitStoreMode]]
    unitType: [[BusinessUnitType.svg BusinessUnitType]]
    name: String
    contactEmail: String
    associateMode: [[BusinessUnitAssociateMode.svg BusinessUnitAssociateMode]]
    associates: [[AssociateDraft.svg List<AssociateDraft>]]
    approvalRuleMode: [[BusinessUnitApprovalRuleMode.svg BusinessUnitApprovalRuleMode]]
    addresses: [[BaseAddress.svg List<BaseAddress>]]
    shippingAddresses: [[Integer.svg List<Integer>]]
    defaultShippingAddress: Integer
    billingAddresses: [[Integer.svg List<Integer>]]
    defaultBillingAddress: Integer
    custom: [[CustomFieldsDraft.svg CustomFieldsDraft]]
    customerGroupAssignments: [[CustomerGroupAssignmentDraft.svg List<CustomerGroupAssignmentDraft>]]
}
interface BusinessUnitSetCustomerGroupAssignmentsAction [[BusinessUnitSetCustomerGroupAssignmentsAction.svg]]  {
    action: String
    customerGroupAssignments: [[CustomerGroupAssignmentDraft.svg List<CustomerGroupAssignmentDraft>]]
}
interface CustomerDraft [[CustomerDraft.svg]]  {
    key: String
    customerNumber: String
    externalId: String
    email: String
    password: String
    firstName: String
    lastName: String
    middleName: String
    title: String
    anonymousCartId: String
    anonymousCart: [[CartResourceIdentifier.svg CartResourceIdentifier]]
    anonymousId: String
    dateOfBirth: Date
    companyName: String
    vatId: String
    addresses: [[BaseAddress.svg List<BaseAddress>]]
    defaultShippingAddress: Integer
    shippingAddresses: [[Integer.svg List<Integer>]]
    defaultBillingAddress: Integer
    billingAddresses: [[Integer.svg List<Integer>]]
    isEmailVerified: Boolean
    customerGroup: [[CustomerGroupResourceIdentifier.svg CustomerGroupResourceIdentifier]]
    customerGroupAssignments: [[CustomerGroupAssignmentDraft.svg List<CustomerGroupAssignmentDraft>]]
    custom: [[CustomFieldsDraft.svg CustomFieldsDraft]]
    locale: String
    salutation: String
    stores: [[StoreResourceIdentifier.svg List<StoreResourceIdentifier>]]
    authenticationMode: [[AuthenticationMode.svg AuthenticationMode]]
}
interface CustomerSetCustomerGroupAssignmentsAction [[CustomerSetCustomerGroupAssignmentsAction.svg]]  {
    action: String
    customerGroupAssignments: [[CustomerGroupAssignmentDraft.svg List<CustomerGroupAssignmentDraft>]]
}
interface BusinessUnitAddCustomerGroupAssignmentAction [[BusinessUnitAddCustomerGroupAssignmentAction.svg]]  {
    action: String
    customerGroupAssignment: [[CustomerGroupAssignmentDraft.svg CustomerGroupAssignmentDraft]]
}
interface CustomerAddCustomerGroupAssignmentAction [[CustomerAddCustomerGroupAssignmentAction.svg]]  {
    action: String
    customerGroupAssignment: [[CustomerGroupAssignmentDraft.svg CustomerGroupAssignmentDraft]]
}

CustomerGroupAssignmentDraft --> BusinessUnitDraft #green;text:green : "customerGroupAssignments"
CustomerGroupAssignmentDraft --> BusinessUnitSetCustomerGroupAssignmentsAction #green;text:green : "customerGroupAssignments"
CustomerGroupAssignmentDraft --> CustomerDraft #green;text:green : "customerGroupAssignments"
CustomerGroupAssignmentDraft --> CustomerSetCustomerGroupAssignmentsAction #green;text:green : "customerGroupAssignments"
CustomerGroupAssignmentDraft --> BusinessUnitAddCustomerGroupAssignmentAction #green;text:green : "customerGroupAssignment"
CustomerGroupAssignmentDraft --> CustomerAddCustomerGroupAssignmentAction #green;text:green : "customerGroupAssignment"
@enduml
