@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface CustomerGroupSetCustomFieldAction [[CustomerGroupSetCustomFieldAction.svg]] extends CustomerGroupUpdateAction {
    action: String
    name: String
    value: [[Object.svg Object]]
}
interface CustomerGroupUpdateAction [[CustomerGroupUpdateAction.svg]]  {
    action: String
}





@enduml
