@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface CustomFieldsDraft [[CustomFieldsDraft.svg]]  {
    type: [[TypeResourceIdentifier.svg TypeResourceIdentifier]]
    fields: [[FieldContainer.svg FieldContainer]]
}



interface PaymentDraft [[PaymentDraft.svg]]  {
    customer: [[CustomerResourceIdentifier.svg CustomerResourceIdentifier]]
    anonymousId: String
    externalId: String
    interfaceId: String
    amountPlanned: [[Money.svg Money]]
    amountAuthorized: [[Money.svg Money]]
    authorizedUntil: String
    amountPaid: [[Money.svg Money]]
    amountRefunded: [[Money.svg Money]]
    paymentMethodInfo: [[PaymentMethodInfo.svg PaymentMethodInfo]]
    paymentStatus: [[PaymentStatusDraft.svg PaymentStatusDraft]]
    transactions: [[TransactionDraft.svg List<TransactionDraft>]]
    interfaceInteractions: [[CustomFieldsDraft.svg List<CustomFieldsDraft>]]
    custom: [[CustomFieldsDraft.svg CustomFieldsDraft]]
    key: String
}
interface AssociateRoleDraft [[AssociateRoleDraft.svg]]  {
    key: String
    name: String
    buyerAssignable: Boolean
    permissions: [[Permission.svg List<Permission>]]
    custom: [[CustomFieldsDraft.svg CustomFieldsDraft]]
}
interface BusinessUnitDraft [[BusinessUnitDraft.svg]]  {
    key: String
    status: [[BusinessUnitStatus.svg BusinessUnitStatus]]
    stores: [[StoreResourceIdentifier.svg List<StoreResourceIdentifier>]]
    storeMode: [[BusinessUnitStoreMode.svg BusinessUnitStoreMode]]
    unitType: [[BusinessUnitType.svg BusinessUnitType]]
    name: String
    contactEmail: String
    associateMode: [[BusinessUnitAssociateMode.svg BusinessUnitAssociateMode]]
    associates: [[AssociateDraft.svg List<AssociateDraft>]]
    addresses: [[BaseAddress.svg List<BaseAddress>]]
    shippingAddresses: [[Integer.svg List<Integer>]]
    defaultShippingAddress: Integer
    billingAddresses: [[Integer.svg List<Integer>]]
    defaultBillingAddress: Integer
    custom: [[CustomFieldsDraft.svg CustomFieldsDraft]]
}
interface CartDiscountDraft [[CartDiscountDraft.svg]]  {
    name: [[LocalizedString.svg LocalizedString]]
    key: String
    description: [[LocalizedString.svg LocalizedString]]
    value: [[CartDiscountValueDraft.svg CartDiscountValueDraft]]
    cartPredicate: String
    target: [[CartDiscountTarget.svg CartDiscountTarget]]
    sortOrder: String
    stores: [[StoreResourceIdentifier.svg List<StoreResourceIdentifier>]]
    isActive: Boolean
    validFrom: DateTime
    validUntil: DateTime
    requiresDiscountCode: Boolean
    stackingMode: [[StackingMode.svg StackingMode]]
    custom: [[CustomFieldsDraft.svg CustomFieldsDraft]]
}
interface CartDraft [[CartDraft.svg]]  {
    currency: String
    key: String
    customerId: String
    customerEmail: String
    customerGroup: [[CustomerGroupResourceIdentifier.svg CustomerGroupResourceIdentifier]]
    anonymousId: String
    businessUnit: [[BusinessUnitResourceIdentifier.svg BusinessUnitResourceIdentifier]]
    store: [[StoreResourceIdentifier.svg StoreResourceIdentifier]]
    lineItems: [[LineItemDraft.svg List<LineItemDraft>]]
    customLineItems: [[CustomLineItemDraft.svg List<CustomLineItemDraft>]]
    taxMode: [[TaxMode.svg TaxMode]]
    externalTaxRateForShippingMethod: [[ExternalTaxRateDraft.svg ExternalTaxRateDraft]]
    taxRoundingMode: [[RoundingMode.svg RoundingMode]]
    taxCalculationMode: [[TaxCalculationMode.svg TaxCalculationMode]]
    inventoryMode: [[InventoryMode.svg InventoryMode]]
    billingAddress: [[BaseAddress.svg BaseAddress]]
    shippingAddress: [[BaseAddress.svg BaseAddress]]
    shippingMethod: [[ShippingMethodResourceIdentifier.svg ShippingMethodResourceIdentifier]]
    shippingRateInput: [[ShippingRateInputDraft.svg ShippingRateInputDraft]]
    shippingMode: [[ShippingMode.svg ShippingMode]]
    customShipping: [[CustomShippingDraft.svg List<CustomShippingDraft>]]
    shipping: [[ShippingDraft.svg List<ShippingDraft>]]
    itemShippingAddresses: [[BaseAddress.svg List<BaseAddress>]]
    discountCodes: [[String.svg List<String>]]
    country: String
    locale: String
    origin: [[CartOrigin.svg CartOrigin]]
    deleteDaysAfterLastModification: Long
    custom: [[CustomFieldsDraft.svg CustomFieldsDraft]]
}
interface CustomLineItemDraft [[CustomLineItemDraft.svg]]  {
    name: [[LocalizedString.svg LocalizedString]]
    key: String
    quantity: Long
    money: [[Money.svg Money]]
    slug: String
    taxCategory: [[TaxCategoryResourceIdentifier.svg TaxCategoryResourceIdentifier]]
    externalTaxRate: [[ExternalTaxRateDraft.svg ExternalTaxRateDraft]]
    custom: [[CustomFieldsDraft.svg CustomFieldsDraft]]
    shippingDetails: [[ItemShippingDetailsDraft.svg ItemShippingDetailsDraft]]
    priceMode: [[CustomLineItemPriceMode.svg CustomLineItemPriceMode]]
}
interface CustomShippingDraft [[CustomShippingDraft.svg]]  {
    key: String
    shippingMethodName: String
    shippingAddress: [[BaseAddress.svg BaseAddress]]
    shippingRate: [[ShippingRateDraft.svg ShippingRateDraft]]
    shippingRateInput: [[ShippingRateInputDraft.svg ShippingRateInputDraft]]
    taxCategory: [[TaxCategoryResourceIdentifier.svg TaxCategoryResourceIdentifier]]
    externalTaxRate: [[ExternalTaxRateDraft.svg ExternalTaxRateDraft]]
    deliveries: [[DeliveryDraft.svg List<DeliveryDraft>]]
    custom: [[CustomFieldsDraft.svg CustomFieldsDraft]]
}
interface LineItemDraft [[LineItemDraft.svg]]  {
    key: String
    productId: String
    variantId: Long
    sku: String
    quantity: Long
    addedAt: DateTime
    distributionChannel: [[ChannelResourceIdentifier.svg ChannelResourceIdentifier]]
    supplyChannel: [[ChannelResourceIdentifier.svg ChannelResourceIdentifier]]
    externalPrice: [[Money.svg Money]]
    externalTotalPrice: [[ExternalLineItemTotalPrice.svg ExternalLineItemTotalPrice]]
    externalTaxRate: [[ExternalTaxRateDraft.svg ExternalTaxRateDraft]]
    perMethodExternalTaxRate: [[MethodExternalTaxRateDraft.svg List<MethodExternalTaxRateDraft>]]
    inventoryMode: [[InventoryMode.svg InventoryMode]]
    shippingDetails: [[ItemShippingDetailsDraft.svg ItemShippingDetailsDraft]]
    custom: [[CustomFieldsDraft.svg CustomFieldsDraft]]
}
interface ShippingDraft [[ShippingDraft.svg]]  {
    key: String
    shippingMethod: [[ShippingMethodReference.svg ShippingMethodReference]]
    shippingAddress: [[BaseAddress.svg BaseAddress]]
    shippingRateInput: [[ShippingRateInputDraft.svg ShippingRateInputDraft]]
    externalTaxRate: [[ExternalTaxRateDraft.svg ExternalTaxRateDraft]]
    deliveries: [[DeliveryDraft.svg List<DeliveryDraft>]]
    custom: [[CustomFieldsDraft.svg CustomFieldsDraft]]
}
interface CartAddCustomLineItemAction [[CartAddCustomLineItemAction.svg]]  {
    action: String
    money: [[Money.svg Money]]
    name: [[LocalizedString.svg LocalizedString]]
    key: String
    quantity: Long
    slug: String
    taxCategory: [[TaxCategoryResourceIdentifier.svg TaxCategoryResourceIdentifier]]
    externalTaxRate: [[ExternalTaxRateDraft.svg ExternalTaxRateDraft]]
    shippingDetails: [[ItemShippingDetailsDraft.svg ItemShippingDetailsDraft]]
    custom: [[CustomFieldsDraft.svg CustomFieldsDraft]]
    priceMode: [[CustomLineItemPriceMode.svg CustomLineItemPriceMode]]
}
interface CartAddCustomShippingMethodAction [[CartAddCustomShippingMethodAction.svg]]  {
    action: String
    shippingKey: String
    shippingMethodName: String
    shippingAddress: [[BaseAddress.svg BaseAddress]]
    shippingRate: [[ShippingRateDraft.svg ShippingRateDraft]]
    shippingRateInput: [[ShippingRateInputDraft.svg ShippingRateInputDraft]]
    taxCategory: [[TaxCategoryResourceIdentifier.svg TaxCategoryResourceIdentifier]]
    externalTaxRate: [[ExternalTaxRateDraft.svg ExternalTaxRateDraft]]
    deliveries: [[DeliveryDraft.svg List<DeliveryDraft>]]
    custom: [[CustomFieldsDraft.svg CustomFieldsDraft]]
}
interface CartAddLineItemAction [[CartAddLineItemAction.svg]]  {
    action: String
    key: String
    productId: String
    variantId: Long
    sku: String
    quantity: Long
    addedAt: DateTime
    distributionChannel: [[ChannelResourceIdentifier.svg ChannelResourceIdentifier]]
    supplyChannel: [[ChannelResourceIdentifier.svg ChannelResourceIdentifier]]
    externalPrice: [[Money.svg Money]]
    externalTotalPrice: [[ExternalLineItemTotalPrice.svg ExternalLineItemTotalPrice]]
    externalTaxRate: [[ExternalTaxRateDraft.svg ExternalTaxRateDraft]]
    inventoryMode: [[InventoryMode.svg InventoryMode]]
    shippingDetails: [[ItemShippingDetailsDraft.svg ItemShippingDetailsDraft]]
    custom: [[CustomFieldsDraft.svg CustomFieldsDraft]]
}
interface CartAddShippingMethodAction [[CartAddShippingMethodAction.svg]]  {
    action: String
    shippingKey: String
    shippingMethod: [[ShippingMethodResourceIdentifier.svg ShippingMethodResourceIdentifier]]
    shippingAddress: [[BaseAddress.svg BaseAddress]]
    shippingRateInput: [[ShippingRateInputDraft.svg ShippingRateInputDraft]]
    externalTaxRate: [[ExternalTaxRateDraft.svg ExternalTaxRateDraft]]
    deliveries: [[DeliveryDraft.svg List<DeliveryDraft>]]
    custom: [[CustomFieldsDraft.svg CustomFieldsDraft]]
}
interface CategoryDraft [[CategoryDraft.svg]]  {
    name: [[LocalizedString.svg LocalizedString]]
    slug: [[LocalizedString.svg LocalizedString]]
    description: [[LocalizedString.svg LocalizedString]]
    parent: [[CategoryResourceIdentifier.svg CategoryResourceIdentifier]]
    orderHint: String
    externalId: String
    metaTitle: [[LocalizedString.svg LocalizedString]]
    metaDescription: [[LocalizedString.svg LocalizedString]]
    metaKeywords: [[LocalizedString.svg LocalizedString]]
    custom: [[CustomFieldsDraft.svg CustomFieldsDraft]]
    assets: [[AssetDraft.svg List<AssetDraft>]]
    key: String
}
interface ChannelDraft [[ChannelDraft.svg]]  {
    key: String
    roles: [[ChannelRoleEnum.svg List<ChannelRoleEnum>]]
    name: [[LocalizedString.svg LocalizedString]]
    description: [[LocalizedString.svg LocalizedString]]
    address: [[BaseAddress.svg BaseAddress]]
    custom: [[CustomFieldsDraft.svg CustomFieldsDraft]]
    geoLocation: [[GeoJson.svg GeoJson]]
}
interface AddressDraft [[AddressDraft.svg]]  {
    id: String
    key: String
    country: String
    title: String
    salutation: String
    firstName: String
    lastName: String
    streetName: String
    streetNumber: String
    additionalStreetInfo: String
    postalCode: String
    city: String
    region: String
    state: String
    company: String
    department: String
    building: String
    apartment: String
    pOBox: String
    phone: String
    mobile: String
    email: String
    fax: String
    additionalAddressInfo: String
    externalId: String
    custom: [[CustomFieldsDraft.svg CustomFieldsDraft]]
}
interface AssetDraft [[AssetDraft.svg]]  {
    sources: [[AssetSource.svg List<AssetSource>]]
    name: [[LocalizedString.svg LocalizedString]]
    description: [[LocalizedString.svg LocalizedString]]
    tags: [[String.svg List<String>]]
    custom: [[CustomFieldsDraft.svg CustomFieldsDraft]]
    key: String
}
interface PriceDraft [[PriceDraft.svg]]  {
    key: String
    value: [[Money.svg Money]]
    country: String
    customerGroup: [[CustomerGroupResourceIdentifier.svg CustomerGroupResourceIdentifier]]
    channel: [[ChannelResourceIdentifier.svg ChannelResourceIdentifier]]
    validFrom: DateTime
    validUntil: DateTime
    discounted: [[DiscountedPriceDraft.svg DiscountedPriceDraft]]
    tiers: [[PriceTierDraft.svg List<PriceTierDraft>]]
    custom: [[CustomFieldsDraft.svg CustomFieldsDraft]]
}
interface CustomerGroupDraft [[CustomerGroupDraft.svg]]  {
    key: String
    groupName: String
    custom: [[CustomFieldsDraft.svg CustomFieldsDraft]]
}
interface CustomerDraft [[CustomerDraft.svg]]  {
    key: String
    customerNumber: String
    externalId: String
    email: String
    password: String
    firstName: String
    lastName: String
    middleName: String
    title: String
    anonymousCartId: String
    anonymousCart: [[CartResourceIdentifier.svg CartResourceIdentifier]]
    anonymousId: String
    dateOfBirth: Date
    companyName: String
    vatId: String
    addresses: [[BaseAddress.svg List<BaseAddress>]]
    defaultShippingAddress: Integer
    shippingAddresses: [[Integer.svg List<Integer>]]
    defaultBillingAddress: Integer
    billingAddresses: [[Integer.svg List<Integer>]]
    isEmailVerified: Boolean
    customerGroup: [[CustomerGroupResourceIdentifier.svg CustomerGroupResourceIdentifier]]
    custom: [[CustomFieldsDraft.svg CustomFieldsDraft]]
    locale: String
    salutation: String
    stores: [[StoreResourceIdentifier.svg List<StoreResourceIdentifier>]]
    authenticationMode: [[AuthenticationMode.svg AuthenticationMode]]
}
interface DiscountCodeDraft [[DiscountCodeDraft.svg]]  {
    name: [[LocalizedString.svg LocalizedString]]
    description: [[LocalizedString.svg LocalizedString]]
    code: String
    cartDiscounts: [[CartDiscountResourceIdentifier.svg List<CartDiscountResourceIdentifier>]]
    cartPredicate: String
    isActive: Boolean
    maxApplications: Long
    maxApplicationsPerCustomer: Long
    custom: [[CustomFieldsDraft.svg CustomFieldsDraft]]
    groups: [[String.svg List<String>]]
    validFrom: DateTime
    validUntil: DateTime
}
interface InventoryEntryDraft [[InventoryEntryDraft.svg]]  {
    sku: String
    key: String
    supplyChannel: [[ChannelResourceIdentifier.svg ChannelResourceIdentifier]]
    quantityOnStock: Long
    restockableInDays: Long
    expectedDelivery: DateTime
    custom: [[CustomFieldsDraft.svg CustomFieldsDraft]]
}
interface MyCartDraft [[MyCartDraft.svg]]  {
    currency: String
    customerEmail: String
    businessUnit: [[BusinessUnitResourceIdentifier.svg BusinessUnitResourceIdentifier]]
    store: [[StoreResourceIdentifier.svg StoreResourceIdentifier]]
    lineItems: [[MyLineItemDraft.svg List<MyLineItemDraft>]]
    taxMode: [[TaxMode.svg TaxMode]]
    inventoryMode: [[InventoryMode.svg InventoryMode]]
    billingAddress: [[BaseAddress.svg BaseAddress]]
    shippingAddress: [[BaseAddress.svg BaseAddress]]
    shippingMethod: [[ShippingMethodResourceIdentifier.svg ShippingMethodResourceIdentifier]]
    itemShippingAddresses: [[BaseAddress.svg List<BaseAddress>]]
    discountCodes: [[String.svg List<String>]]
    country: String
    locale: String
    deleteDaysAfterLastModification: Long
    custom: [[CustomFieldsDraft.svg CustomFieldsDraft]]
}
interface MyCustomerDraft [[MyCustomerDraft.svg]]  {
    email: String
    password: String
    firstName: String
    lastName: String
    middleName: String
    title: String
    salutation: String
    dateOfBirth: Date
    companyName: String
    vatId: String
    addresses: [[BaseAddress.svg List<BaseAddress>]]
    defaultShippingAddress: Long
    defaultBillingAddress: Long
    custom: [[CustomFieldsDraft.svg CustomFieldsDraft]]
    locale: String
    stores: [[StoreResourceIdentifier.svg List<StoreResourceIdentifier>]]
}
interface MyLineItemDraft [[MyLineItemDraft.svg]]  {
    key: String
    productId: String
    variantId: Long
    sku: String
    quantity: Long
    addedAt: DateTime
    supplyChannel: [[ChannelResourceIdentifier.svg ChannelResourceIdentifier]]
    distributionChannel: [[ChannelResourceIdentifier.svg ChannelResourceIdentifier]]
    shippingDetails: [[ItemShippingDetailsDraft.svg ItemShippingDetailsDraft]]
    custom: [[CustomFieldsDraft.svg CustomFieldsDraft]]
}
interface MyPaymentDraft [[MyPaymentDraft.svg]]  {
    amountPlanned: [[Money.svg Money]]
    paymentMethodInfo: [[PaymentMethodInfo.svg PaymentMethodInfo]]
    custom: [[CustomFieldsDraft.svg CustomFieldsDraft]]
    transaction: [[MyTransactionDraft.svg MyTransactionDraft]]
}
interface MyShoppingListDraft [[MyShoppingListDraft.svg]]  {
    name: [[LocalizedString.svg LocalizedString]]
    description: [[LocalizedString.svg LocalizedString]]
    lineItems: [[ShoppingListLineItemDraft.svg List<ShoppingListLineItemDraft>]]
    textLineItems: [[TextLineItemDraft.svg List<TextLineItemDraft>]]
    custom: [[CustomFieldsDraft.svg CustomFieldsDraft]]
    deleteDaysAfterLastModification: Long
    store: [[StoreResourceIdentifier.svg StoreResourceIdentifier]]
}
interface MyTransactionDraft [[MyTransactionDraft.svg]]  {
    timestamp: DateTime
    type: [[TransactionType.svg TransactionType]]
    amount: [[Money.svg Money]]
    interactionId: String
    custom: [[CustomFieldsDraft.svg CustomFieldsDraft]]
}
interface MyCartAddLineItemAction [[MyCartAddLineItemAction.svg]]  {
    action: String
    key: String
    productId: String
    variantId: Long
    sku: String
    quantity: Long
    addedAt: DateTime
    distributionChannel: [[ChannelResourceIdentifier.svg ChannelResourceIdentifier]]
    supplyChannel: [[ChannelResourceIdentifier.svg ChannelResourceIdentifier]]
    shippingDetails: [[ItemShippingDetailsDraft.svg ItemShippingDetailsDraft]]
    custom: [[CustomFieldsDraft.svg CustomFieldsDraft]]
}
interface MyShoppingListAddLineItemAction [[MyShoppingListAddLineItemAction.svg]]  {
    action: String
    key: String
    sku: String
    productId: String
    variantId: Long
    quantity: Long
    addedAt: DateTime
    custom: [[CustomFieldsDraft.svg CustomFieldsDraft]]
}
interface MyShoppingListAddTextLineItemAction [[MyShoppingListAddTextLineItemAction.svg]]  {
    action: String
    name: [[LocalizedString.svg LocalizedString]]
    key: String
    description: [[LocalizedString.svg LocalizedString]]
    quantity: Long
    addedAt: DateTime
    custom: [[CustomFieldsDraft.svg CustomFieldsDraft]]
}
interface OrderEditDraft [[OrderEditDraft.svg]]  {
    key: String
    resource: [[OrderReference.svg OrderReference]]
    stagedActions: [[StagedOrderUpdateAction.svg List<StagedOrderUpdateAction>]]
    custom: [[CustomFieldsDraft.svg CustomFieldsDraft]]
    comment: String
    dryRun: Boolean
}
interface StagedOrderAddCustomLineItemAction [[StagedOrderAddCustomLineItemAction.svg]]  {
    action: String
    money: [[Money.svg Money]]
    name: [[LocalizedString.svg LocalizedString]]
    key: String
    quantity: Long
    slug: String
    taxCategory: [[TaxCategoryResourceIdentifier.svg TaxCategoryResourceIdentifier]]
    externalTaxRate: [[ExternalTaxRateDraft.svg ExternalTaxRateDraft]]
    shippingDetails: [[ItemShippingDetailsDraft.svg ItemShippingDetailsDraft]]
    priceMode: [[CustomLineItemPriceMode.svg CustomLineItemPriceMode]]
    custom: [[CustomFieldsDraft.svg CustomFieldsDraft]]
}
interface StagedOrderAddDeliveryAction [[StagedOrderAddDeliveryAction.svg]]  {
    action: String
    deliveryKey: String
    shippingKey: String
    items: [[DeliveryItem.svg List<DeliveryItem>]]
    address: [[BaseAddress.svg BaseAddress]]
    parcels: [[ParcelDraft.svg List<ParcelDraft>]]
    custom: [[CustomFieldsDraft.svg CustomFieldsDraft]]
}
interface StagedOrderAddLineItemAction [[StagedOrderAddLineItemAction.svg]]  {
    action: String
    key: String
    productId: String
    variantId: Long
    sku: String
    quantity: Long
    addedAt: DateTime
    distributionChannel: [[ChannelResourceIdentifier.svg ChannelResourceIdentifier]]
    supplyChannel: [[ChannelResourceIdentifier.svg ChannelResourceIdentifier]]
    externalPrice: [[Money.svg Money]]
    externalTotalPrice: [[ExternalLineItemTotalPrice.svg ExternalLineItemTotalPrice]]
    externalTaxRate: [[ExternalTaxRateDraft.svg ExternalTaxRateDraft]]
    inventoryMode: [[InventoryMode.svg InventoryMode]]
    shippingDetails: [[ItemShippingDetailsDraft.svg ItemShippingDetailsDraft]]
    custom: [[CustomFieldsDraft.svg CustomFieldsDraft]]
}
interface CustomLineItemImportDraft [[CustomLineItemImportDraft.svg]]  {
    name: [[LocalizedString.svg LocalizedString]]
    key: String
    slug: String
    quantity: Long
    money: [[Money.svg Money]]
    taxRate: [[TaxRate.svg TaxRate]]
    taxCategory: [[TaxCategoryResourceIdentifier.svg TaxCategoryResourceIdentifier]]
    priceMode: [[CustomLineItemPriceMode.svg CustomLineItemPriceMode]]
    shippingDetails: [[ItemShippingDetailsDraft.svg ItemShippingDetailsDraft]]
    state: [[ItemState.svg List<ItemState>]]
    custom: [[CustomFieldsDraft.svg CustomFieldsDraft]]
}
interface DeliveryDraft [[DeliveryDraft.svg]]  {
    key: String
    items: [[DeliveryItem.svg List<DeliveryItem>]]
    parcels: [[ParcelDraft.svg List<ParcelDraft>]]
    address: [[AddressDraft.svg AddressDraft]]
    custom: [[CustomFieldsDraft.svg CustomFieldsDraft]]
}
interface LineItemImportDraft [[LineItemImportDraft.svg]]  {
    name: [[LocalizedString.svg LocalizedString]]
    key: String
    variant: [[ProductVariantImportDraft.svg ProductVariantImportDraft]]
    productId: String
    quantity: Long
    price: [[PriceDraft.svg PriceDraft]]
    taxRate: [[TaxRate.svg TaxRate]]
    distributionChannel: [[ChannelResourceIdentifier.svg ChannelResourceIdentifier]]
    supplyChannel: [[ChannelResourceIdentifier.svg ChannelResourceIdentifier]]
    inventoryMode: [[InventoryMode.svg InventoryMode]]
    shippingDetails: [[ItemShippingDetailsDraft.svg ItemShippingDetailsDraft]]
    state: [[ItemState.svg List<ItemState>]]
    custom: [[CustomFieldsDraft.svg CustomFieldsDraft]]
}
interface OrderFromCartDraft [[OrderFromCartDraft.svg]]  {
    id: String
    cart: [[CartResourceIdentifier.svg CartResourceIdentifier]]
    version: Long
    orderNumber: String
    purchaseOrderNumber: String
    paymentState: [[PaymentState.svg PaymentState]]
    shipmentState: [[ShipmentState.svg ShipmentState]]
    orderState: [[OrderState.svg OrderState]]
    state: [[StateResourceIdentifier.svg StateResourceIdentifier]]
    custom: [[CustomFieldsDraft.svg CustomFieldsDraft]]
}
interface OrderImportDraft [[OrderImportDraft.svg]]  {
    orderNumber: String
    purchaseOrderNumber: String
    customerId: String
    customerEmail: String
    customerGroup: [[CustomerGroupResourceIdentifier.svg CustomerGroupResourceIdentifier]]
    businessUnit: [[BusinessUnitResourceIdentifier.svg BusinessUnitResourceIdentifier]]
    store: [[StoreResourceIdentifier.svg StoreResourceIdentifier]]
    lineItems: [[LineItemImportDraft.svg List<LineItemImportDraft>]]
    customLineItems: [[CustomLineItemImportDraft.svg List<CustomLineItemImportDraft>]]
    totalPrice: [[Money.svg Money]]
    taxedPrice: [[TaxedPriceDraft.svg TaxedPriceDraft]]
    taxRoundingMode: [[RoundingMode.svg RoundingMode]]
    taxCalculationMode: [[TaxCalculationMode.svg TaxCalculationMode]]
    inventoryMode: [[InventoryMode.svg InventoryMode]]
    billingAddress: [[BaseAddress.svg BaseAddress]]
    shippingAddress: [[BaseAddress.svg BaseAddress]]
    itemShippingAddresses: [[BaseAddress.svg List<BaseAddress>]]
    shippingInfo: [[ShippingInfoImportDraft.svg ShippingInfoImportDraft]]
    paymentInfo: [[PaymentInfo.svg PaymentInfo]]
    paymentState: [[PaymentState.svg PaymentState]]
    shipmentState: [[ShipmentState.svg ShipmentState]]
    orderState: [[OrderState.svg OrderState]]
    state: [[StateReference.svg StateReference]]
    country: String
    origin: [[CartOrigin.svg CartOrigin]]
    completedAt: DateTime
    custom: [[CustomFieldsDraft.svg CustomFieldsDraft]]
}
interface ParcelDraft [[ParcelDraft.svg]]  {
    key: String
    measurements: [[ParcelMeasurements.svg ParcelMeasurements]]
    trackingData: [[TrackingData.svg TrackingData]]
    items: [[DeliveryItem.svg List<DeliveryItem>]]
    custom: [[CustomFieldsDraft.svg CustomFieldsDraft]]
}
interface ReturnItemDraft [[ReturnItemDraft.svg]]  {
    key: String
    quantity: Long
    lineItemId: String
    customLineItemId: String
    comment: String
    shipmentState: [[ReturnShipmentState.svg ReturnShipmentState]]
    custom: [[CustomFieldsDraft.svg CustomFieldsDraft]]
}
interface OrderAddDeliveryAction [[OrderAddDeliveryAction.svg]]  {
    action: String
    deliveryKey: String
    shippingKey: String
    items: [[DeliveryItem.svg List<DeliveryItem>]]
    address: [[BaseAddress.svg BaseAddress]]
    parcels: [[ParcelDraft.svg List<ParcelDraft>]]
    custom: [[CustomFieldsDraft.svg CustomFieldsDraft]]
}
interface TransactionDraft [[TransactionDraft.svg]]  {
    timestamp: DateTime
    type: [[TransactionType.svg TransactionType]]
    amount: [[Money.svg Money]]
    interactionId: String
    state: [[TransactionState.svg TransactionState]]
    custom: [[CustomFieldsDraft.svg CustomFieldsDraft]]
}
interface ProductSelectionDraft [[ProductSelectionDraft.svg]]  {
    key: String
    name: [[LocalizedString.svg LocalizedString]]
    custom: [[CustomFieldsDraft.svg CustomFieldsDraft]]
    type: [[ProductSelectionTypeEnum.svg ProductSelectionTypeEnum]]
    mode: [[ProductSelectionMode.svg ProductSelectionMode]]
}
interface QuoteRequestDraft [[QuoteRequestDraft.svg]]  {
    cart: [[CartResourceIdentifier.svg CartResourceIdentifier]]
    cartVersion: Long
    key: String
    comment: String
    custom: [[CustomFieldsDraft.svg CustomFieldsDraft]]
    state: [[StateReference.svg StateReference]]
    purchaseOrderNumber: String
}
interface QuoteDraft [[QuoteDraft.svg]]  {
    key: String
    stagedQuote: [[StagedQuoteResourceIdentifier.svg StagedQuoteResourceIdentifier]]
    stagedQuoteVersion: Long
    stagedQuoteStateToSent: Boolean
    state: [[StateReference.svg StateReference]]
    custom: [[CustomFieldsDraft.svg CustomFieldsDraft]]
}
interface ReviewDraft [[ReviewDraft.svg]]  {
    key: String
    uniquenessValue: String
    locale: String
    authorName: String
    title: String
    text: String
    target: [[Object.svg Object]]
    state: [[StateResourceIdentifier.svg StateResourceIdentifier]]
    rating: Integer
    customer: [[CustomerResourceIdentifier.svg CustomerResourceIdentifier]]
    custom: [[CustomFieldsDraft.svg CustomFieldsDraft]]
}
interface ShippingMethodDraft [[ShippingMethodDraft.svg]]  {
    key: String
    name: String
    localizedName: [[LocalizedString.svg LocalizedString]]
    description: String
    localizedDescription: [[LocalizedString.svg LocalizedString]]
    taxCategory: [[TaxCategoryResourceIdentifier.svg TaxCategoryResourceIdentifier]]
    zoneRates: [[ZoneRateDraft.svg List<ZoneRateDraft>]]
    isDefault: Boolean
    predicate: String
    custom: [[CustomFieldsDraft.svg CustomFieldsDraft]]
}
interface ShoppingListDraft [[ShoppingListDraft.svg]]  {
    name: [[LocalizedString.svg LocalizedString]]
    slug: [[LocalizedString.svg LocalizedString]]
    customer: [[CustomerResourceIdentifier.svg CustomerResourceIdentifier]]
    key: String
    description: [[LocalizedString.svg LocalizedString]]
    anonymousId: String
    deleteDaysAfterLastModification: Long
    lineItems: [[ShoppingListLineItemDraft.svg List<ShoppingListLineItemDraft>]]
    textLineItems: [[TextLineItemDraft.svg List<TextLineItemDraft>]]
    store: [[StoreResourceIdentifier.svg StoreResourceIdentifier]]
    custom: [[CustomFieldsDraft.svg CustomFieldsDraft]]
}
interface ShoppingListLineItemDraft [[ShoppingListLineItemDraft.svg]]  {
    key: String
    productId: String
    variantId: Long
    sku: String
    addedAt: DateTime
    custom: [[CustomFieldsDraft.svg CustomFieldsDraft]]
    quantity: Long
}
interface TextLineItemDraft [[TextLineItemDraft.svg]]  {
    key: String
    addedAt: DateTime
    custom: [[CustomFieldsDraft.svg CustomFieldsDraft]]
    description: [[LocalizedString.svg LocalizedString]]
    name: [[LocalizedString.svg LocalizedString]]
    quantity: Long
}
interface ShoppingListAddLineItemAction [[ShoppingListAddLineItemAction.svg]]  {
    action: String
    key: String
    sku: String
    productId: String
    variantId: Long
    quantity: Long
    addedAt: DateTime
    custom: [[CustomFieldsDraft.svg CustomFieldsDraft]]
}
interface ShoppingListAddTextLineItemAction [[ShoppingListAddTextLineItemAction.svg]]  {
    action: String
    name: [[LocalizedString.svg LocalizedString]]
    key: String
    description: [[LocalizedString.svg LocalizedString]]
    quantity: Long
    addedAt: DateTime
    custom: [[CustomFieldsDraft.svg CustomFieldsDraft]]
}
interface StagedQuoteDraft [[StagedQuoteDraft.svg]]  {
    quoteRequest: [[QuoteRequestResourceIdentifier.svg QuoteRequestResourceIdentifier]]
    quoteRequestVersion: Long
    quoteRequestStateToAccepted: Boolean
    key: String
    custom: [[CustomFieldsDraft.svg CustomFieldsDraft]]
    state: [[StateReference.svg StateReference]]
}
interface StandalonePriceDraft [[StandalonePriceDraft.svg]]  {
    key: String
    sku: String
    value: [[Money.svg Money]]
    country: String
    customerGroup: [[CustomerGroupResourceIdentifier.svg CustomerGroupResourceIdentifier]]
    channel: [[ChannelResourceIdentifier.svg ChannelResourceIdentifier]]
    validFrom: DateTime
    validUntil: DateTime
    tiers: [[PriceTierDraft.svg List<PriceTierDraft>]]
    discounted: [[DiscountedPriceDraft.svg DiscountedPriceDraft]]
    custom: [[CustomFieldsDraft.svg CustomFieldsDraft]]
    staged: [[StagedPriceDraft.svg StagedPriceDraft]]
    active: Boolean
}
interface StoreDraft [[StoreDraft.svg]]  {
    key: String
    name: [[LocalizedString.svg LocalizedString]]
    languages: [[String.svg List<String>]]
    countries: [[StoreCountry.svg List<StoreCountry>]]
    distributionChannels: [[ChannelResourceIdentifier.svg List<ChannelResourceIdentifier>]]
    supplyChannels: [[ChannelResourceIdentifier.svg List<ChannelResourceIdentifier>]]
    productSelections: [[ProductSelectionSettingDraft.svg List<ProductSelectionSettingDraft>]]
    custom: [[CustomFieldsDraft.svg CustomFieldsDraft]]
}

CustomFieldsDraft --> PaymentDraft #green;text:green : "interfaceInteractions"
CustomFieldsDraft --> AssociateRoleDraft #green;text:green : "custom"
CustomFieldsDraft --> BusinessUnitDraft #green;text:green : "custom"
CustomFieldsDraft --> CartDiscountDraft #green;text:green : "custom"
CustomFieldsDraft --> CartDraft #green;text:green : "custom"
CustomFieldsDraft --> CustomLineItemDraft #green;text:green : "custom"
CustomFieldsDraft --> CustomShippingDraft #green;text:green : "custom"
CustomFieldsDraft --> LineItemDraft #green;text:green : "custom"
CustomFieldsDraft --> ShippingDraft #green;text:green : "custom"
CustomFieldsDraft --> CartAddCustomLineItemAction #green;text:green : "custom"
CustomFieldsDraft --> CartAddCustomShippingMethodAction #green;text:green : "custom"
CustomFieldsDraft --> CartAddLineItemAction #green;text:green : "custom"
CustomFieldsDraft --> CartAddShippingMethodAction #green;text:green : "custom"
CustomFieldsDraft --> CategoryDraft #green;text:green : "custom"
CustomFieldsDraft --> ChannelDraft #green;text:green : "custom"
CustomFieldsDraft --> AddressDraft #green;text:green : "custom"
CustomFieldsDraft --> AssetDraft #green;text:green : "custom"
CustomFieldsDraft --> PriceDraft #green;text:green : "custom"
CustomFieldsDraft --> CustomerGroupDraft #green;text:green : "custom"
CustomFieldsDraft --> CustomerDraft #green;text:green : "custom"
CustomFieldsDraft --> DiscountCodeDraft #green;text:green : "custom"
CustomFieldsDraft --> InventoryEntryDraft #green;text:green : "custom"
CustomFieldsDraft --> MyCartDraft #green;text:green : "custom"
CustomFieldsDraft --> MyCustomerDraft #green;text:green : "custom"
CustomFieldsDraft --> MyLineItemDraft #green;text:green : "custom"
CustomFieldsDraft --> MyPaymentDraft #green;text:green : "custom"
CustomFieldsDraft --> MyShoppingListDraft #green;text:green : "custom"
CustomFieldsDraft --> MyTransactionDraft #green;text:green : "custom"
CustomFieldsDraft --> MyCartAddLineItemAction #green;text:green : "custom"
CustomFieldsDraft --> MyShoppingListAddLineItemAction #green;text:green : "custom"
CustomFieldsDraft --> MyShoppingListAddTextLineItemAction #green;text:green : "custom"
CustomFieldsDraft --> OrderEditDraft #green;text:green : "custom"
CustomFieldsDraft --> StagedOrderAddCustomLineItemAction #green;text:green : "custom"
CustomFieldsDraft --> StagedOrderAddDeliveryAction #green;text:green : "custom"
CustomFieldsDraft --> StagedOrderAddLineItemAction #green;text:green : "custom"
CustomFieldsDraft --> CustomLineItemImportDraft #green;text:green : "custom"
CustomFieldsDraft --> DeliveryDraft #green;text:green : "custom"
CustomFieldsDraft --> LineItemImportDraft #green;text:green : "custom"
CustomFieldsDraft --> OrderFromCartDraft #green;text:green : "custom"
CustomFieldsDraft --> OrderImportDraft #green;text:green : "custom"
CustomFieldsDraft --> ParcelDraft #green;text:green : "custom"
CustomFieldsDraft --> ReturnItemDraft #green;text:green : "custom"
CustomFieldsDraft --> OrderAddDeliveryAction #green;text:green : "custom"
CustomFieldsDraft --> PaymentDraft #green;text:green : "custom"
CustomFieldsDraft --> TransactionDraft #green;text:green : "custom"
CustomFieldsDraft --> ProductSelectionDraft #green;text:green : "custom"
CustomFieldsDraft --> QuoteRequestDraft #green;text:green : "custom"
CustomFieldsDraft --> QuoteDraft #green;text:green : "custom"
CustomFieldsDraft --> ReviewDraft #green;text:green : "custom"
CustomFieldsDraft --> ShippingMethodDraft #green;text:green : "custom"
CustomFieldsDraft --> ShoppingListDraft #green;text:green : "custom"
CustomFieldsDraft --> ShoppingListLineItemDraft #green;text:green : "custom"
CustomFieldsDraft --> TextLineItemDraft #green;text:green : "custom"
CustomFieldsDraft --> ShoppingListAddLineItemAction #green;text:green : "custom"
CustomFieldsDraft --> ShoppingListAddTextLineItemAction #green;text:green : "custom"
CustomFieldsDraft --> StagedQuoteDraft #green;text:green : "custom"
CustomFieldsDraft --> StandalonePriceDraft #green;text:green : "custom"
CustomFieldsDraft --> StoreDraft #green;text:green : "custom"
@enduml
