@startuml

hide methods
enum CustomFieldReferenceValue {
    APPROVAL_FLOW
    ASSOCIATE_ROLE
    BUSINESS_UNIT
    CART
    CART_DISCOUNT
    CATEGORY
    CHANNEL
    CUSTOMER
    KEY_VALUE_DOCUMENT
    ORDER
    PRODUCT
    PRODUCT_TYPE
    REVIEW
    STATE
    SHIPPING_METHOD
    ZONE
}
interface CustomFieldReferenceType [[CustomFieldReferenceType.svg]]  {
    name: String
    referenceTypeId: [[CustomFieldReferenceValue.svg CustomFieldReferenceValue]]
}
CustomFieldReferenceValue --> CustomFieldReferenceType #green;text:green : "referenceTypeId"
@enduml
