@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface DayOfMonthSchedule [[DayOfMonthSchedule.svg]] extends RecurrencePolicySchedule {
    type: String
    day: Integer
}
interface RecurrencePolicySchedule [[RecurrencePolicySchedule.svg]]  {
    type: String
}





@enduml
