@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface DayOfMonthScheduleDraft [[DayOfMonthScheduleDraft.svg]] extends RecurrencePolicyScheduleDraft {
    type: String
    day: Integer
}
interface RecurrencePolicyScheduleDraft [[RecurrencePolicyScheduleDraft.svg]]  {
    type: String
}





@enduml
