@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface Delivery [[Delivery.svg]]  {
    id: String
    createdAt: DateTime
    items: [[DeliveryItem.svg List<DeliveryItem>]]
    parcels: [[Parcel.svg List<Parcel>]]
    address: [[Address.svg Address]]
    custom: [[CustomFields.svg CustomFields]]
}



interface ShippingInfo [[ShippingInfo.svg]]  {
    shippingMethodName: String
    price: [[CentPrecisionMoney.svg CentPrecisionMoney]]
    shippingRate: [[ShippingRate.svg ShippingRate]]
    taxedPrice: [[TaxedItemPrice.svg TaxedItemPrice]]
    taxRate: [[TaxRate.svg TaxRate]]
    taxCategory: [[TaxCategoryReference.svg TaxCategoryReference]]
    shippingMethod: [[ShippingMethodReference.svg ShippingMethodReference]]
    deliveries: [[Delivery.svg List<Delivery>]]
    discountedPrice: [[DiscountedLineItemPrice.svg DiscountedLineItemPrice]]
    shippingMethodState: [[ShippingMethodState.svg ShippingMethodState]]
}
interface DeliveryAddedMessage [[DeliveryAddedMessage.svg]]  {
    id: String
    version: Long
    createdAt: DateTime
    lastModifiedAt: DateTime
    lastModifiedBy: [[LastModifiedBy.svg LastModifiedBy]]
    createdBy: [[CreatedBy.svg CreatedBy]]
    sequenceNumber: Long
    resource: [[Reference.svg Reference]]
    resourceVersion: Long
    type: String
    resourceUserProvidedIdentifiers: [[UserProvidedIdentifiers.svg UserProvidedIdentifiers]]
    delivery: [[Delivery.svg Delivery]]
    shippingKey: String
}
interface DeliveryRemovedMessage [[DeliveryRemovedMessage.svg]]  {
    id: String
    version: Long
    createdAt: DateTime
    lastModifiedAt: DateTime
    lastModifiedBy: [[LastModifiedBy.svg LastModifiedBy]]
    createdBy: [[CreatedBy.svg CreatedBy]]
    sequenceNumber: Long
    resource: [[Reference.svg Reference]]
    resourceVersion: Long
    type: String
    resourceUserProvidedIdentifiers: [[UserProvidedIdentifiers.svg UserProvidedIdentifiers]]
    delivery: [[Delivery.svg Delivery]]
    shippingKey: String
}
interface ParcelAddedToDeliveryMessage [[ParcelAddedToDeliveryMessage.svg]]  {
    id: String
    version: Long
    createdAt: DateTime
    lastModifiedAt: DateTime
    lastModifiedBy: [[LastModifiedBy.svg LastModifiedBy]]
    createdBy: [[CreatedBy.svg CreatedBy]]
    sequenceNumber: Long
    resource: [[Reference.svg Reference]]
    resourceVersion: Long
    type: String
    resourceUserProvidedIdentifiers: [[UserProvidedIdentifiers.svg UserProvidedIdentifiers]]
    delivery: [[Delivery.svg Delivery]]
    parcel: [[Parcel.svg Parcel]]
    shippingKey: String
}
interface DeliveryAddedMessagePayload [[DeliveryAddedMessagePayload.svg]]  {
    type: String
    delivery: [[Delivery.svg Delivery]]
    shippingKey: String
}
interface DeliveryRemovedMessagePayload [[DeliveryRemovedMessagePayload.svg]]  {
    type: String
    delivery: [[Delivery.svg Delivery]]
    shippingKey: String
}
interface ParcelAddedToDeliveryMessagePayload [[ParcelAddedToDeliveryMessagePayload.svg]]  {
    type: String
    delivery: [[Delivery.svg Delivery]]
    parcel: [[Parcel.svg Parcel]]
    shippingKey: String
}

Delivery --> ShippingInfo #green;text:green : "deliveries"
Delivery --> DeliveryAddedMessage #green;text:green : "delivery"
Delivery --> DeliveryRemovedMessage #green;text:green : "delivery"
Delivery --> ParcelAddedToDeliveryMessage #green;text:green : "delivery"
Delivery --> DeliveryAddedMessagePayload #green;text:green : "delivery"
Delivery --> DeliveryRemovedMessagePayload #green;text:green : "delivery"
Delivery --> ParcelAddedToDeliveryMessagePayload #green;text:green : "delivery"
@enduml
