@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface DirectDiscountDraft [[DirectDiscountDraft.svg]]  {
    value: [[CartDiscountValue.svg CartDiscountValue]]
    target: [[CartDiscountTarget.svg CartDiscountTarget]]
}



interface CartSetDirectDiscountsAction [[CartSetDirectDiscountsAction.svg]]  {
    action: String
    discounts: [[DirectDiscountDraft.svg List<DirectDiscountDraft>]]
}
interface StagedOrderSetDirectDiscountsAction [[StagedOrderSetDirectDiscountsAction.svg]]  {
    action: String
    discounts: [[DirectDiscountDraft.svg List<DirectDiscountDraft>]]
}

DirectDiscountDraft --> CartSetDirectDiscountsAction #green;text:green : "discounts"
DirectDiscountDraft --> StagedOrderSetDirectDiscountsAction #green;text:green : "discounts"
@enduml
