@startuml

hide methods
enum DiscountCombinationMode {
    BEST_DEAL
    STACKING
}
interface DiscountsConfiguration [[DiscountsConfiguration.svg]]  {
    discountCombinationMode: [[DiscountCombinationMode.svg DiscountCombinationMode]]
}
DiscountCombinationMode --> DiscountsConfiguration #green;text:green : "discountCombinationMode"
@enduml
