@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface DiscountCodeSetCustomFieldAction [[DiscountCodeSetCustomFieldAction.svg]] extends DiscountCodeUpdateAction {
    action: String
    name: String
    value: [[Object.svg Object]]
}
interface DiscountCodeUpdateAction [[DiscountCodeUpdateAction.svg]]  {
    action: String
}





@enduml
