@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface DiscountedLineItemPriceForQuantity [[DiscountedLineItemPriceForQuantity.svg]]  {
    quantity: Long
    discountedPrice: [[DiscountedLineItemPrice.svg DiscountedLineItemPrice]]
}



interface CustomLineItem [[CustomLineItem.svg]]  {
    id: String
    key: String
    name: [[LocalizedString.svg LocalizedString]]
    money: [[TypedMoney.svg TypedMoney]]
    taxedPrice: [[TaxedItemPrice.svg TaxedItemPrice]]
    totalPrice: [[CentPrecisionMoney.svg CentPrecisionMoney]]
    slug: String
    quantity: Long
    state: [[ItemState.svg List<ItemState>]]
    taxCategory: [[TaxCategoryReference.svg TaxCategoryReference]]
    taxRate: [[TaxRate.svg TaxRate]]
    perMethodTaxRate: [[MethodTaxRate.svg List<MethodTaxRate>]]
    discountedPricePerQuantity: [[DiscountedLineItemPriceForQuantity.svg List<DiscountedLineItemPriceForQuantity>]]
    custom: [[CustomFields.svg CustomFields]]
    shippingDetails: [[ItemShippingDetails.svg ItemShippingDetails]]
    priceMode: [[CustomLineItemPriceMode.svg CustomLineItemPriceMode]]
}
interface LineItem [[LineItem.svg]]  {
    id: String
    key: String
    productId: String
    productKey: String
    name: [[LocalizedString.svg LocalizedString]]
    productSlug: [[LocalizedString.svg LocalizedString]]
    productType: [[ProductTypeReference.svg ProductTypeReference]]
    variant: [[ProductVariant.svg ProductVariant]]
    price: [[Price.svg Price]]
    quantity: Long
    totalPrice: [[CentPrecisionMoney.svg CentPrecisionMoney]]
    discountedPricePerQuantity: [[DiscountedLineItemPriceForQuantity.svg List<DiscountedLineItemPriceForQuantity>]]
    taxedPrice: [[TaxedItemPrice.svg TaxedItemPrice]]
    taxedPricePortions: [[MethodTaxedPrice.svg List<MethodTaxedPrice>]]
    state: [[ItemState.svg List<ItemState>]]
    taxRate: [[TaxRate.svg TaxRate]]
    perMethodTaxRate: [[MethodTaxRate.svg List<MethodTaxRate>]]
    supplyChannel: [[ChannelReference.svg ChannelReference]]
    distributionChannel: [[ChannelReference.svg ChannelReference]]
    priceMode: [[LineItemPriceMode.svg LineItemPriceMode]]
    lineItemMode: [[LineItemMode.svg LineItemMode]]
    inventoryMode: [[InventoryMode.svg InventoryMode]]
    shippingDetails: [[ItemShippingDetails.svg ItemShippingDetails]]
    custom: [[CustomFields.svg CustomFields]]
    addedAt: DateTime
    lastModifiedAt: DateTime
}
interface OrderCustomLineItemDiscountSetMessage [[OrderCustomLineItemDiscountSetMessage.svg]]  {
    id: String
    version: Long
    createdAt: DateTime
    lastModifiedAt: DateTime
    lastModifiedBy: [[LastModifiedBy.svg LastModifiedBy]]
    createdBy: [[CreatedBy.svg CreatedBy]]
    sequenceNumber: Long
    resource: [[Reference.svg Reference]]
    resourceVersion: Long
    type: String
    resourceUserProvidedIdentifiers: [[UserProvidedIdentifiers.svg UserProvidedIdentifiers]]
    customLineItemId: String
    discountedPricePerQuantity: [[DiscountedLineItemPriceForQuantity.svg List<DiscountedLineItemPriceForQuantity>]]
    taxedPrice: [[TaxedItemPrice.svg TaxedItemPrice]]
}
interface OrderLineItemDiscountSetMessage [[OrderLineItemDiscountSetMessage.svg]]  {
    id: String
    version: Long
    createdAt: DateTime
    lastModifiedAt: DateTime
    lastModifiedBy: [[LastModifiedBy.svg LastModifiedBy]]
    createdBy: [[CreatedBy.svg CreatedBy]]
    sequenceNumber: Long
    resource: [[Reference.svg Reference]]
    resourceVersion: Long
    type: String
    resourceUserProvidedIdentifiers: [[UserProvidedIdentifiers.svg UserProvidedIdentifiers]]
    lineItemId: String
    lineItemKey: String
    discountedPricePerQuantity: [[DiscountedLineItemPriceForQuantity.svg List<DiscountedLineItemPriceForQuantity>]]
    totalPrice: [[Money.svg Money]]
    taxedPrice: [[TaxedItemPrice.svg TaxedItemPrice]]
    taxedPricePortions: [[MethodTaxedPrice.svg List<MethodTaxedPrice>]]
}
interface OrderCustomLineItemDiscountSetMessagePayload [[OrderCustomLineItemDiscountSetMessagePayload.svg]]  {
    type: String
    customLineItemId: String
    discountedPricePerQuantity: [[DiscountedLineItemPriceForQuantity.svg List<DiscountedLineItemPriceForQuantity>]]
    taxedPrice: [[TaxedItemPrice.svg TaxedItemPrice]]
}
interface OrderLineItemDiscountSetMessagePayload [[OrderLineItemDiscountSetMessagePayload.svg]]  {
    type: String
    lineItemId: String
    lineItemKey: String
    discountedPricePerQuantity: [[DiscountedLineItemPriceForQuantity.svg List<DiscountedLineItemPriceForQuantity>]]
    totalPrice: [[Money.svg Money]]
    taxedPrice: [[TaxedItemPrice.svg TaxedItemPrice]]
    taxedPricePortions: [[MethodTaxedPrice.svg List<MethodTaxedPrice>]]
}

DiscountedLineItemPriceForQuantity --> CustomLineItem #green;text:green : "discountedPricePerQuantity"
DiscountedLineItemPriceForQuantity --> LineItem #green;text:green : "discountedPricePerQuantity"
DiscountedLineItemPriceForQuantity --> OrderCustomLineItemDiscountSetMessage #green;text:green : "discountedPricePerQuantity"
DiscountedLineItemPriceForQuantity --> OrderLineItemDiscountSetMessage #green;text:green : "discountedPricePerQuantity"
DiscountedLineItemPriceForQuantity --> OrderCustomLineItemDiscountSetMessagePayload #green;text:green : "discountedPricePerQuantity"
DiscountedLineItemPriceForQuantity --> OrderLineItemDiscountSetMessagePayload #green;text:green : "discountedPricePerQuantity"
@enduml
