@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface DiscountedTotalPricePortion [[DiscountedTotalPricePortion.svg]]  {
    discount: [[Reference.svg Reference]]
    discountedAmount: [[TypedMoney.svg TypedMoney]]
}



interface DiscountOnTotalPrice [[DiscountOnTotalPrice.svg]]  {
    discountedAmount: [[TypedMoney.svg TypedMoney]]
    includedDiscounts: [[DiscountedTotalPricePortion.svg List<DiscountedTotalPricePortion>]]
    discountedNetAmount: [[TypedMoney.svg TypedMoney]]
    discountedGrossAmount: [[TypedMoney.svg TypedMoney]]
}

DiscountedTotalPricePortion --> DiscountOnTotalPrice #green;text:green : "includedDiscounts"
@enduml
