@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface DiscountGroupSetDescriptionAction [[DiscountGroupSetDescriptionAction.svg]] extends DiscountGroupUpdateAction {
    action: String
    description: [[LocalizedString.svg LocalizedString]]
}
interface DiscountGroupUpdateAction [[DiscountGroupUpdateAction.svg]]  {
    action: String
}





@enduml
