@startuml

hide methods
enum DiscountApplicationMode {
    PROPORTIONATE_DISTRIBUTION
    EVEN_DISTRIBUTION
    INDIVIDUAL_APPLICATION
}
interface CartDiscountValueAbsolute [[CartDiscountValueAbsolute.svg]]  {
    type: String
    money: [[CentPrecisionMoney.svg List<CentPrecisionMoney>]]
    applicationMode: [[DiscountApplicationMode.svg DiscountApplicationMode]]
}
interface CartDiscountValueAbsoluteDraft [[CartDiscountValueAbsoluteDraft.svg]]  {
    type: String
    money: [[Money.svg List<Money>]]
    applicationMode: [[DiscountApplicationMode.svg DiscountApplicationMode]]
}
DiscountApplicationMode --> CartDiscountValueAbsolute #green;text:green : "applicationMode"
DiscountApplicationMode --> CartDiscountValueAbsoluteDraft #green;text:green : "applicationMode"
@enduml
