@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface DiscountCodeSetValidFromAction [[DiscountCodeSetValidFromAction.svg]] extends DiscountCodeUpdateAction {
    action: String
    validFrom: DateTime
}
interface DiscountCodeUpdateAction [[DiscountCodeUpdateAction.svg]]  {
    action: String
}





@enduml
