@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface DiscountedPrice [[DiscountedPrice.svg]]  {
    value: [[TypedMoney.svg TypedMoney]]
    discount: [[ProductDiscountReference.svg ProductDiscountReference]]
}



interface Price [[Price.svg]]  {
    id: String
    key: String
    value: [[TypedMoney.svg TypedMoney]]
    country: String
    customerGroup: [[CustomerGroupReference.svg CustomerGroupReference]]
    channel: [[ChannelReference.svg ChannelReference]]
    validFrom: DateTime
    validUntil: DateTime
    discounted: [[DiscountedPrice.svg DiscountedPrice]]
    tiers: [[PriceTier.svg List<PriceTier>]]
    custom: [[CustomFields.svg CustomFields]]
    recurrencePolicy: [[RecurrencePolicyReference.svg RecurrencePolicyReference]]
}
interface ScopedPrice [[ScopedPrice.svg]]  {
    id: String
    value: [[TypedMoney.svg TypedMoney]]
    currentValue: [[TypedMoney.svg TypedMoney]]
    country: String
    customerGroup: [[CustomerGroupReference.svg CustomerGroupReference]]
    channel: [[ChannelReference.svg ChannelReference]]
    validFrom: DateTime
    validUntil: DateTime
    discounted: [[DiscountedPrice.svg DiscountedPrice]]
    custom: [[CustomFields.svg CustomFields]]
}
interface ProductPriceDiscountsSetUpdatedPrice [[ProductPriceDiscountsSetUpdatedPrice.svg]]  {
    variantId: Integer
    variantKey: String
    sku: String
    priceId: String
    discounted: [[DiscountedPrice.svg DiscountedPrice]]
    staged: Boolean
}
interface ProductPriceExternalDiscountSetMessage [[ProductPriceExternalDiscountSetMessage.svg]]  {
    id: String
    version: Long
    createdAt: DateTime
    lastModifiedAt: DateTime
    lastModifiedBy: [[LastModifiedBy.svg LastModifiedBy]]
    createdBy: [[CreatedBy.svg CreatedBy]]
    sequenceNumber: Long
    resource: [[Reference.svg Reference]]
    resourceVersion: Long
    type: String
    resourceUserProvidedIdentifiers: [[UserProvidedIdentifiers.svg UserProvidedIdentifiers]]
    variantId: Integer
    variantKey: String
    sku: String
    priceId: String
    discounted: [[DiscountedPrice.svg DiscountedPrice]]
    staged: Boolean
}
interface StandalonePriceDiscountSetMessage [[StandalonePriceDiscountSetMessage.svg]]  {
    id: String
    version: Long
    createdAt: DateTime
    lastModifiedAt: DateTime
    lastModifiedBy: [[LastModifiedBy.svg LastModifiedBy]]
    createdBy: [[CreatedBy.svg CreatedBy]]
    sequenceNumber: Long
    resource: [[Reference.svg Reference]]
    resourceVersion: Long
    type: String
    resourceUserProvidedIdentifiers: [[UserProvidedIdentifiers.svg UserProvidedIdentifiers]]
    discounted: [[DiscountedPrice.svg DiscountedPrice]]
}
interface StandalonePriceExternalDiscountSetMessage [[StandalonePriceExternalDiscountSetMessage.svg]]  {
    id: String
    version: Long
    createdAt: DateTime
    lastModifiedAt: DateTime
    lastModifiedBy: [[LastModifiedBy.svg LastModifiedBy]]
    createdBy: [[CreatedBy.svg CreatedBy]]
    sequenceNumber: Long
    resource: [[Reference.svg Reference]]
    resourceVersion: Long
    type: String
    resourceUserProvidedIdentifiers: [[UserProvidedIdentifiers.svg UserProvidedIdentifiers]]
    discounted: [[DiscountedPrice.svg DiscountedPrice]]
}
interface ProductPriceExternalDiscountSetMessagePayload [[ProductPriceExternalDiscountSetMessagePayload.svg]]  {
    type: String
    variantId: Integer
    variantKey: String
    sku: String
    priceId: String
    discounted: [[DiscountedPrice.svg DiscountedPrice]]
    staged: Boolean
}
interface StandalonePriceDiscountSetMessagePayload [[StandalonePriceDiscountSetMessagePayload.svg]]  {
    type: String
    discounted: [[DiscountedPrice.svg DiscountedPrice]]
}
interface StandalonePriceExternalDiscountSetMessagePayload [[StandalonePriceExternalDiscountSetMessagePayload.svg]]  {
    type: String
    discounted: [[DiscountedPrice.svg DiscountedPrice]]
}
interface StagedStandalonePrice [[StagedStandalonePrice.svg]]  {
    value: [[TypedMoney.svg TypedMoney]]
    discounted: [[DiscountedPrice.svg DiscountedPrice]]
}
interface StandalonePrice [[StandalonePrice.svg]]  {
    id: String
    version: Long
    createdAt: DateTime
    lastModifiedAt: DateTime
    lastModifiedBy: [[LastModifiedBy.svg LastModifiedBy]]
    createdBy: [[CreatedBy.svg CreatedBy]]
    key: String
    sku: String
    value: [[TypedMoney.svg TypedMoney]]
    country: String
    customerGroup: [[CustomerGroupReference.svg CustomerGroupReference]]
    channel: [[ChannelReference.svg ChannelReference]]
    validFrom: DateTime
    validUntil: DateTime
    tiers: [[PriceTier.svg List<PriceTier>]]
    discounted: [[DiscountedPrice.svg DiscountedPrice]]
    custom: [[CustomFields.svg CustomFields]]
    staged: [[StagedStandalonePrice.svg StagedStandalonePrice]]
    active: Boolean
    recurrencePolicy: [[RecurrencePolicyReference.svg RecurrencePolicyReference]]
}

DiscountedPrice --> Price #green;text:green : "discounted"
DiscountedPrice --> ScopedPrice #green;text:green : "discounted"
DiscountedPrice --> ProductPriceDiscountsSetUpdatedPrice #green;text:green : "discounted"
DiscountedPrice --> ProductPriceExternalDiscountSetMessage #green;text:green : "discounted"
DiscountedPrice --> StandalonePriceDiscountSetMessage #green;text:green : "discounted"
DiscountedPrice --> StandalonePriceExternalDiscountSetMessage #green;text:green : "discounted"
DiscountedPrice --> ProductPriceExternalDiscountSetMessagePayload #green;text:green : "discounted"
DiscountedPrice --> StandalonePriceDiscountSetMessagePayload #green;text:green : "discounted"
DiscountedPrice --> StandalonePriceExternalDiscountSetMessagePayload #green;text:green : "discounted"
DiscountedPrice --> StagedStandalonePrice #green;text:green : "discounted"
DiscountedPrice --> StandalonePrice #green;text:green : "discounted"
@enduml
