@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface ErrorResponse [[ErrorResponse.svg]]  {
    statusCode: Integer
    message: String
    errors: [[ErrorObject.svg List<ErrorObject>]]
}

interface AuthErrorResponse [[AuthErrorResponse.svg]] extends ErrorResponse {
    statusCode: Integer
    message: String
    errors: [[ErrorObject.svg List<ErrorObject>]]
    error: String
    error_description: String
}
interface ProductSearchErrorResponse [[ProductSearchErrorResponse.svg]] extends ErrorResponse {
    statusCode: Integer
    message: String
    errors: [[ErrorObject.svg List<ErrorObject>]]
}




@enduml
