@startuml

hide methods
enum EventSubscriptionResourceTypeId {
    IMPORT_API
}
interface BaseEvent [[BaseEvent.svg]]  {
    id: String
    notificationType: String
    resourceType: [[EventSubscriptionResourceTypeId.svg EventSubscriptionResourceTypeId]]
    type: [[EventType.svg EventType]]
    data: [[Object.svg Object]]
    createdAt: DateTime
}
interface Event [[Event.svg]]  {
    id: String
    notificationType: String
    resourceType: [[EventSubscriptionResourceTypeId.svg EventSubscriptionResourceTypeId]]
    type: [[EventType.svg EventType]]
    createdAt: DateTime
}
interface ImportContainerCreatedEvent [[ImportContainerCreatedEvent.svg]]  {
    id: String
    notificationType: String
    resourceType: [[EventSubscriptionResourceTypeId.svg EventSubscriptionResourceTypeId]]
    type: [[EventType.svg EventType]]
    createdAt: DateTime
    data: [[ImportContainerCreatedEventData.svg ImportContainerCreatedEventData]]
}
interface ImportContainerDeletedEvent [[ImportContainerDeletedEvent.svg]]  {
    id: String
    notificationType: String
    resourceType: [[EventSubscriptionResourceTypeId.svg EventSubscriptionResourceTypeId]]
    type: [[EventType.svg EventType]]
    createdAt: DateTime
    data: [[ImportContainerDeletedEventData.svg ImportContainerDeletedEventData]]
}
interface ImportOperationRejectedEvent [[ImportOperationRejectedEvent.svg]]  {
    id: String
    notificationType: String
    resourceType: [[EventSubscriptionResourceTypeId.svg EventSubscriptionResourceTypeId]]
    type: [[EventType.svg EventType]]
    createdAt: DateTime
    data: [[ImportOperationRejectedEventData.svg ImportOperationRejectedEventData]]
}
interface ImportUnresolvedEvent [[ImportUnresolvedEvent.svg]]  {
    id: String
    notificationType: String
    resourceType: [[EventSubscriptionResourceTypeId.svg EventSubscriptionResourceTypeId]]
    type: [[EventType.svg EventType]]
    createdAt: DateTime
    data: [[ImportUnresolvedEventData.svg ImportUnresolvedEventData]]
}
interface ImportValidationFailedEvent [[ImportValidationFailedEvent.svg]]  {
    id: String
    notificationType: String
    resourceType: [[EventSubscriptionResourceTypeId.svg EventSubscriptionResourceTypeId]]
    type: [[EventType.svg EventType]]
    createdAt: DateTime
    data: [[ImportValidationFailedEventData.svg ImportValidationFailedEventData]]
}
interface ImportWaitForMasterVariantEvent [[ImportWaitForMasterVariantEvent.svg]]  {
    id: String
    notificationType: String
    resourceType: [[EventSubscriptionResourceTypeId.svg EventSubscriptionResourceTypeId]]
    type: [[EventType.svg EventType]]
    createdAt: DateTime
    data: [[ImportWaitForMasterVariantEventData.svg ImportWaitForMasterVariantEventData]]
}
interface EventSubscription [[EventSubscription.svg]]  {
    resourceTypeId: [[EventSubscriptionResourceTypeId.svg EventSubscriptionResourceTypeId]]
    types: [[EventType.svg List<EventType>]]
}
EventSubscriptionResourceTypeId --> BaseEvent #green;text:green : "resourceType"
EventSubscriptionResourceTypeId --> Event #green;text:green : "resourceType"
EventSubscriptionResourceTypeId --> ImportContainerCreatedEvent #green;text:green : "resourceType"
EventSubscriptionResourceTypeId --> ImportContainerDeletedEvent #green;text:green : "resourceType"
EventSubscriptionResourceTypeId --> ImportOperationRejectedEvent #green;text:green : "resourceType"
EventSubscriptionResourceTypeId --> ImportUnresolvedEvent #green;text:green : "resourceType"
EventSubscriptionResourceTypeId --> ImportValidationFailedEvent #green;text:green : "resourceType"
EventSubscriptionResourceTypeId --> ImportWaitForMasterVariantEvent #green;text:green : "resourceType"
EventSubscriptionResourceTypeId --> EventSubscription #green;text:green : "resourceTypeId"
@enduml
