@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface Event [[Event.svg]]  {
    id: String
    notificationType: String
    resourceType: [[EventSubscriptionResourceTypeId.svg EventSubscriptionResourceTypeId]]
    type: [[EventType.svg EventType]]
    createdAt: DateTime
}


interface ImportContainerCreatedEvent [[ImportContainerCreatedEvent.svg]]  {
    id: String
    notificationType: String
    resourceType: [[EventSubscriptionResourceTypeId.svg EventSubscriptionResourceTypeId]]
    type: [[EventType.svg EventType]]
    createdAt: DateTime
    data: [[ImportContainerCreatedEventData.svg ImportContainerCreatedEventData]]
}
interface ImportContainerDeletedEvent [[ImportContainerDeletedEvent.svg]]  {
    id: String
    notificationType: String
    resourceType: [[EventSubscriptionResourceTypeId.svg EventSubscriptionResourceTypeId]]
    type: [[EventType.svg EventType]]
    createdAt: DateTime
    data: [[ImportContainerDeletedEventData.svg ImportContainerDeletedEventData]]
}
interface ImportOperationRejectedEvent [[ImportOperationRejectedEvent.svg]]  {
    id: String
    notificationType: String
    resourceType: [[EventSubscriptionResourceTypeId.svg EventSubscriptionResourceTypeId]]
    type: [[EventType.svg EventType]]
    createdAt: DateTime
    data: [[ImportOperationRejectedEventData.svg ImportOperationRejectedEventData]]
}
interface ImportUnresolvedEvent [[ImportUnresolvedEvent.svg]]  {
    id: String
    notificationType: String
    resourceType: [[EventSubscriptionResourceTypeId.svg EventSubscriptionResourceTypeId]]
    type: [[EventType.svg EventType]]
    createdAt: DateTime
    data: [[ImportUnresolvedEventData.svg ImportUnresolvedEventData]]
}
interface ImportValidationFailedEvent [[ImportValidationFailedEvent.svg]]  {
    id: String
    notificationType: String
    resourceType: [[EventSubscriptionResourceTypeId.svg EventSubscriptionResourceTypeId]]
    type: [[EventType.svg EventType]]
    createdAt: DateTime
    data: [[ImportValidationFailedEventData.svg ImportValidationFailedEventData]]
}
interface ImportWaitForMasterVariantEvent [[ImportWaitForMasterVariantEvent.svg]]  {
    id: String
    notificationType: String
    resourceType: [[EventSubscriptionResourceTypeId.svg EventSubscriptionResourceTypeId]]
    type: [[EventType.svg EventType]]
    createdAt: DateTime
    data: [[ImportWaitForMasterVariantEventData.svg ImportWaitForMasterVariantEventData]]
}

Event --> ImportContainerCreatedEvent #blue;text:blue : "type : ImportContainerCreated"
Event --> ImportContainerDeletedEvent #blue;text:blue : "type : ImportContainerDeleted"
Event --> ImportOperationRejectedEvent #blue;text:blue : "type : ImportOperationRejected"
Event --> ImportUnresolvedEvent #blue;text:blue : "type : ImportUnresolved"
Event --> ImportValidationFailedEvent #blue;text:blue : "type : ImportValidationFailed"
Event --> ImportWaitForMasterVariantEvent #blue;text:blue : "type : ImportWaitForMasterVariant"

@enduml
