@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface FacetTerm [[FacetTerm.svg]]  {
    term: [[Object.svg Object]]
    count: Long
    productCount: Long
}



interface TermFacetResult [[TermFacetResult.svg]]  {
    type: [[FacetTypes.svg FacetTypes]]
    dataType: [[TermFacetResultType.svg TermFacetResultType]]
    missing: Long
    total: Long
    other: Long
    terms: [[FacetTerm.svg List<FacetTerm>]]
}

FacetTerm --> TermFacetResult #green;text:green : "terms"
FacetTerm --> TermFacetResult #green;text:green : "terms"
@enduml
