@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface FacetResults [[FacetResults.svg]]  {
}



interface ProductProjectionPagedSearchResponse [[ProductProjectionPagedSearchResponse.svg]]  {
    limit: Long
    offset: Long
    count: Long
    total: Long
    results: [[ProductProjection.svg List<ProductProjection>]]
    facets: [[FacetResults.svg FacetResults]]
}

FacetResults --> ProductProjectionPagedSearchResponse #green;text:green : "facets"
@enduml
