@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface FieldDefinition [[FieldDefinition.svg]]  {
    type: [[FieldType.svg FieldType]]
    name: String
    label: [[LocalizedString.svg LocalizedString]]
    required: Boolean
    inputHint: [[TypeTextInputHint.svg TypeTextInputHint]]
}



interface Type [[Type.svg]]  {
    id: String
    version: Long
    createdAt: DateTime
    lastModifiedAt: DateTime
    lastModifiedBy: [[LastModifiedBy.svg LastModifiedBy]]
    createdBy: [[CreatedBy.svg CreatedBy]]
    key: String
    name: [[LocalizedString.svg LocalizedString]]
    description: [[LocalizedString.svg LocalizedString]]
    resourceTypeIds: [[ResourceTypeId.svg List<ResourceTypeId>]]
    fieldDefinitions: [[FieldDefinition.svg List<FieldDefinition>]]
}
interface TypeDraft [[TypeDraft.svg]]  {
    key: String
    name: [[LocalizedString.svg LocalizedString]]
    description: [[LocalizedString.svg LocalizedString]]
    resourceTypeIds: [[ResourceTypeId.svg List<ResourceTypeId>]]
    fieldDefinitions: [[FieldDefinition.svg List<FieldDefinition>]]
}
interface TypeAddFieldDefinitionAction [[TypeAddFieldDefinitionAction.svg]]  {
    action: String
    fieldDefinition: [[FieldDefinition.svg FieldDefinition]]
}

FieldDefinition --> Type #green;text:green : "fieldDefinitions"
FieldDefinition --> TypeDraft #green;text:green : "fieldDefinitions"
FieldDefinition --> TypeAddFieldDefinitionAction #green;text:green : "fieldDefinition"
@enduml
