@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface Image [[Image.svg]]  {
    url: String
    dimensions: [[ImageDimensions.svg ImageDimensions]]
    label: String
}



interface ProductVariantImportDraft [[ProductVariantImportDraft.svg]]  {
    id: Long
    sku: String
    prices: [[PriceDraft.svg List<PriceDraft>]]
    attributes: [[Attribute.svg List<Attribute>]]
    images: [[Image.svg List<Image>]]
}
interface ProductVariantTailoring [[ProductVariantTailoring.svg]]  {
    id: Long
    images: [[Image.svg List<Image>]]
    assets: [[Asset.svg List<Asset>]]
}
interface ProductVariantTailoringDraft [[ProductVariantTailoringDraft.svg]]  {
    id: Long
    sku: String
    images: [[Image.svg List<Image>]]
    assets: [[Asset.svg List<Asset>]]
}
interface ProductTailoringAddVariantAction [[ProductTailoringAddVariantAction.svg]]  {
    action: String
    id: Long
    sku: String
    images: [[Image.svg List<Image>]]
    assets: [[AssetDraft.svg List<AssetDraft>]]
    staged: Boolean
}
interface ProductVariant [[ProductVariant.svg]]  {
    id: Long
    sku: String
    key: String
    prices: [[Price.svg List<Price>]]
    attributes: [[Attribute.svg List<Attribute>]]
    price: [[Price.svg Price]]
    images: [[Image.svg List<Image>]]
    assets: [[Asset.svg List<Asset>]]
    availability: [[ProductVariantAvailability.svg ProductVariantAvailability]]
    isMatchingVariant: Boolean
    scopedPrice: [[ScopedPrice.svg ScopedPrice]]
    scopedPriceDiscounted: Boolean
}
interface ProductVariantDraft [[ProductVariantDraft.svg]]  {
    sku: String
    key: String
    prices: [[PriceDraft.svg List<PriceDraft>]]
    attributes: [[Attribute.svg List<Attribute>]]
    images: [[Image.svg List<Image>]]
    assets: [[AssetDraft.svg List<AssetDraft>]]
}
interface ProductAddVariantAction [[ProductAddVariantAction.svg]]  {
    action: String
    sku: String
    key: String
    prices: [[PriceDraft.svg List<PriceDraft>]]
    images: [[Image.svg List<Image>]]
    attributes: [[Attribute.svg List<Attribute>]]
    staged: Boolean
    assets: [[AssetDraft.svg List<AssetDraft>]]
}
interface ProductImageAddedMessage [[ProductImageAddedMessage.svg]]  {
    id: String
    version: Long
    createdAt: DateTime
    lastModifiedAt: DateTime
    lastModifiedBy: [[LastModifiedBy.svg LastModifiedBy]]
    createdBy: [[CreatedBy.svg CreatedBy]]
    sequenceNumber: Long
    resource: [[Reference.svg Reference]]
    resourceVersion: Long
    type: String
    resourceUserProvidedIdentifiers: [[UserProvidedIdentifiers.svg UserProvidedIdentifiers]]
    variantId: Long
    image: [[Image.svg Image]]
    staged: Boolean
}
interface ProductTailoringImageAddedMessage [[ProductTailoringImageAddedMessage.svg]]  {
    id: String
    version: Long
    createdAt: DateTime
    lastModifiedAt: DateTime
    lastModifiedBy: [[LastModifiedBy.svg LastModifiedBy]]
    createdBy: [[CreatedBy.svg CreatedBy]]
    sequenceNumber: Long
    resource: [[Reference.svg Reference]]
    resourceVersion: Long
    type: String
    resourceUserProvidedIdentifiers: [[UserProvidedIdentifiers.svg UserProvidedIdentifiers]]
    store: [[StoreKeyReference.svg StoreKeyReference]]
    productKey: String
    product: [[ProductReference.svg ProductReference]]
    variantId: Long
    image: [[Image.svg Image]]
}
interface ProductImageAddedMessagePayload [[ProductImageAddedMessagePayload.svg]]  {
    type: String
    variantId: Long
    image: [[Image.svg Image]]
    staged: Boolean
}
interface ProductTailoringImageAddedMessagePayload [[ProductTailoringImageAddedMessagePayload.svg]]  {
    type: String
    store: [[StoreKeyReference.svg StoreKeyReference]]
    productKey: String
    product: [[ProductReference.svg ProductReference]]
    variantId: Long
    image: [[Image.svg Image]]
}
interface ProductTailoringAddExternalImageAction [[ProductTailoringAddExternalImageAction.svg]]  {
    action: String
    variantId: Long
    sku: String
    image: [[Image.svg Image]]
    staged: Boolean
}
interface ProductAddExternalImageAction [[ProductAddExternalImageAction.svg]]  {
    action: String
    variantId: Long
    sku: String
    image: [[Image.svg Image]]
    staged: Boolean
}
interface ProductTailoringImagesSetMessage [[ProductTailoringImagesSetMessage.svg]]  {
    id: String
    version: Long
    createdAt: DateTime
    lastModifiedAt: DateTime
    lastModifiedBy: [[LastModifiedBy.svg LastModifiedBy]]
    createdBy: [[CreatedBy.svg CreatedBy]]
    sequenceNumber: Long
    resource: [[Reference.svg Reference]]
    resourceVersion: Long
    type: String
    resourceUserProvidedIdentifiers: [[UserProvidedIdentifiers.svg UserProvidedIdentifiers]]
    store: [[StoreKeyReference.svg StoreKeyReference]]
    productKey: String
    product: [[ProductReference.svg ProductReference]]
    variantId: Long
    oldImages: [[Image.svg List<Image>]]
    images: [[Image.svg List<Image>]]
}
interface ProductTailoringImagesSetMessagePayload [[ProductTailoringImagesSetMessagePayload.svg]]  {
    type: String
    store: [[StoreKeyReference.svg StoreKeyReference]]
    productKey: String
    product: [[ProductReference.svg ProductReference]]
    variantId: Long
    oldImages: [[Image.svg List<Image>]]
    images: [[Image.svg List<Image>]]
}
interface ProductTailoringSetExternalImagesAction [[ProductTailoringSetExternalImagesAction.svg]]  {
    action: String
    variantId: Long
    sku: String
    images: [[Image.svg List<Image>]]
    staged: Boolean
}

Image --> ProductVariantImportDraft #green;text:green : "images"
Image --> ProductVariantTailoring #green;text:green : "images"
Image --> ProductVariantTailoringDraft #green;text:green : "images"
Image --> ProductTailoringAddVariantAction #green;text:green : "images"
Image --> ProductVariant #green;text:green : "images"
Image --> ProductVariantDraft #green;text:green : "images"
Image --> ProductAddVariantAction #green;text:green : "images"
Image --> ProductImageAddedMessage #green;text:green : "image"
Image --> ProductTailoringImageAddedMessage #green;text:green : "image"
Image --> ProductImageAddedMessagePayload #green;text:green : "image"
Image --> ProductTailoringImageAddedMessagePayload #green;text:green : "image"
Image --> ProductTailoringAddExternalImageAction #green;text:green : "image"
Image --> ProductAddExternalImageAction #green;text:green : "image"
Image --> ProductTailoringImagesSetMessage #green;text:green : "oldImages"
Image --> ProductTailoringImagesSetMessage #green;text:green : "images"
Image --> ProductTailoringImagesSetMessagePayload #green;text:green : "oldImages"
Image --> ProductTailoringImagesSetMessagePayload #green;text:green : "images"
Image --> ProductTailoringSetExternalImagesAction #green;text:green : "images"
@enduml
