@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface InheritedAssociateRoleAssignment [[InheritedAssociateRoleAssignment.svg]]  {
    associateRole: [[AssociateRoleKeyReference.svg AssociateRoleKeyReference]]
    source: [[BusinessUnitKeyReference.svg BusinessUnitKeyReference]]
}



interface InheritedAssociate [[InheritedAssociate.svg]]  {
    associateRoleAssignments: [[InheritedAssociateRoleAssignment.svg List<InheritedAssociateRoleAssignment>]]
    customer: [[CustomerReference.svg CustomerReference]]
}

InheritedAssociateRoleAssignment --> InheritedAssociate #green;text:green : "associateRoleAssignments"
@enduml
