@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface InventoryEntryStockLevels [[InventoryEntryStockLevels.svg]]  {
    reorderPoint: Integer
    safetyStock: Integer
}



interface InventoryEntry [[InventoryEntry.svg]]  {
    id: String
    version: Long
    createdAt: DateTime
    lastModifiedAt: DateTime
    lastModifiedBy: [[LastModifiedBy.svg LastModifiedBy]]
    createdBy: [[CreatedBy.svg CreatedBy]]
    key: String
    sku: String
    supplyChannel: [[ChannelReference.svg ChannelReference]]
    quantityOnStock: Long
    availableQuantity: Long
    minCartQuantity: Integer
    maxCartQuantity: Integer
    restockableInDays: Long
    expectedDelivery: DateTime
    reservationExpirationInMinutes: Integer
    stockLevels: [[InventoryEntryStockLevels.svg InventoryEntryStockLevels]]
    custom: [[CustomFields.svg CustomFields]]
}
interface InventoryEntryDraft [[InventoryEntryDraft.svg]]  {
    sku: String
    key: String
    supplyChannel: [[ChannelResourceIdentifier.svg ChannelResourceIdentifier]]
    quantityOnStock: Long
    minCartQuantity: Integer
    maxCartQuantity: Integer
    restockableInDays: Long
    expectedDelivery: DateTime
    reservationExpirationInMinutes: Integer
    stockLevels: [[InventoryEntryStockLevels.svg InventoryEntryStockLevels]]
    custom: [[CustomFieldsDraft.svg CustomFieldsDraft]]
}

InventoryEntryStockLevels --> InventoryEntry #green;text:green : "stockLevels"
InventoryEntryStockLevels --> InventoryEntryDraft #green;text:green : "stockLevels"
@enduml
