@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface LastModifiedBy [[LastModifiedBy.svg]] extends ClientLogging {
    clientId: String
    externalUserId: String
    customer: [[CustomerReference.svg CustomerReference]]
    anonymousId: String
    associate: [[CustomerReference.svg CustomerReference]]
    attributedTo: [[Attribution.svg Attribution]]
}
interface ClientLogging [[ClientLogging.svg]]  {
    clientId: String
    externalUserId: String
    customer: [[CustomerReference.svg CustomerReference]]
    anonymousId: String
    associate: [[CustomerReference.svg CustomerReference]]
}


interface ApprovalFlow [[ApprovalFlow.svg]]  {
    id: String
    version: Long
    createdAt: DateTime
    lastModifiedAt: DateTime
    createdBy: [[CreatedBy.svg CreatedBy]]
    lastModifiedBy: [[LastModifiedBy.svg LastModifiedBy]]
    order: [[OrderReference.svg OrderReference]]
    businessUnit: [[BusinessUnitKeyReference.svg BusinessUnitKeyReference]]
    rules: [[ApprovalRule.svg List<ApprovalRule>]]
    status: [[ApprovalFlowStatus.svg ApprovalFlowStatus]]
    rejection: [[ApprovalFlowRejection.svg ApprovalFlowRejection]]
    approvals: [[ApprovalFlowApproval.svg List<ApprovalFlowApproval>]]
    eligibleApprovers: [[RuleApprover.svg List<RuleApprover>]]
    pendingApprovers: [[RuleApprover.svg List<RuleApprover>]]
    currentTierPendingApprovers: [[RuleApprover.svg List<RuleApprover>]]
    custom: [[CustomFields.svg CustomFields]]
}
interface ApprovalRule [[ApprovalRule.svg]]  {
    id: String
    version: Long
    createdAt: DateTime
    lastModifiedAt: DateTime
    createdBy: [[CreatedBy.svg CreatedBy]]
    lastModifiedBy: [[LastModifiedBy.svg LastModifiedBy]]
    key: String
    name: String
    description: String
    status: [[ApprovalRuleStatus.svg ApprovalRuleStatus]]
    predicate: String
    approvers: [[ApproverHierarchy.svg ApproverHierarchy]]
    requesters: [[RuleRequester.svg List<RuleRequester>]]
    businessUnit: [[BusinessUnitKeyReference.svg BusinessUnitKeyReference]]
    custom: [[CustomFields.svg CustomFields]]
}
interface AssociateRole [[AssociateRole.svg]]  {
    id: String
    version: Long
    createdAt: DateTime
    lastModifiedAt: DateTime
    lastModifiedBy: [[LastModifiedBy.svg LastModifiedBy]]
    createdBy: [[CreatedBy.svg CreatedBy]]
    key: String
    buyerAssignable: Boolean
    name: String
    permissions: [[Permission.svg List<Permission>]]
    custom: [[CustomFields.svg CustomFields]]
}
interface AttributeGroup [[AttributeGroup.svg]]  {
    id: String
    version: Long
    createdAt: DateTime
    lastModifiedAt: DateTime
    lastModifiedBy: [[LastModifiedBy.svg LastModifiedBy]]
    createdBy: [[CreatedBy.svg CreatedBy]]
    name: [[LocalizedString.svg LocalizedString]]
    description: [[LocalizedString.svg LocalizedString]]
    attributes: [[AttributeReference.svg List<AttributeReference>]]
    key: String
}
interface BusinessUnit [[BusinessUnit.svg]]  {
    id: String
    version: Long
    createdAt: DateTime
    lastModifiedAt: DateTime
    lastModifiedBy: [[LastModifiedBy.svg LastModifiedBy]]
    createdBy: [[CreatedBy.svg CreatedBy]]
    key: String
    status: [[BusinessUnitStatus.svg BusinessUnitStatus]]
    stores: [[StoreKeyReference.svg List<StoreKeyReference>]]
    inheritedStores: [[StoreKeyReference.svg List<StoreKeyReference>]]
    storeMode: [[BusinessUnitStoreMode.svg BusinessUnitStoreMode]]
    unitType: [[BusinessUnitType.svg BusinessUnitType]]
    name: String
    contactEmail: String
    custom: [[CustomFields.svg CustomFields]]
    addresses: [[Address.svg List<Address>]]
    shippingAddressIds: [[String.svg List<String>]]
    defaultShippingAddressId: String
    billingAddressIds: [[String.svg List<String>]]
    defaultBillingAddressId: String
    associateMode: [[BusinessUnitAssociateMode.svg BusinessUnitAssociateMode]]
    associates: [[Associate.svg List<Associate>]]
    inheritedAssociates: [[InheritedAssociate.svg List<InheritedAssociate>]]
    parentUnit: [[BusinessUnitKeyReference.svg BusinessUnitKeyReference]]
    topLevelUnit: [[BusinessUnitKeyReference.svg BusinessUnitKeyReference]]
    approvalRuleMode: [[BusinessUnitApprovalRuleMode.svg BusinessUnitApprovalRuleMode]]
}
interface CartDiscount [[CartDiscount.svg]]  {
    id: String
    version: Long
    createdAt: DateTime
    lastModifiedAt: DateTime
    lastModifiedBy: [[LastModifiedBy.svg LastModifiedBy]]
    createdBy: [[CreatedBy.svg CreatedBy]]
    name: [[LocalizedString.svg LocalizedString]]
    key: String
    description: [[LocalizedString.svg LocalizedString]]
    value: [[CartDiscountValue.svg CartDiscountValue]]
    cartPredicate: String
    target: [[CartDiscountTarget.svg CartDiscountTarget]]
    sortOrder: String
    stores: [[StoreKeyReference.svg List<StoreKeyReference>]]
    isActive: Boolean
    validFrom: DateTime
    validUntil: DateTime
    requiresDiscountCode: Boolean
    references: [[Reference.svg List<Reference>]]
    stackingMode: [[StackingMode.svg StackingMode]]
    custom: [[CustomFields.svg CustomFields]]
    discountGroup: [[DiscountGroupReference.svg DiscountGroupReference]]
}
interface Cart [[Cart.svg]]  {
    id: String
    version: Long
    createdAt: DateTime
    lastModifiedAt: DateTime
    key: String
    customerId: String
    customerEmail: String
    customerGroup: [[CustomerGroupReference.svg CustomerGroupReference]]
    anonymousId: String
    businessUnit: [[BusinessUnitKeyReference.svg BusinessUnitKeyReference]]
    store: [[StoreKeyReference.svg StoreKeyReference]]
    lineItems: [[LineItem.svg List<LineItem>]]
    customLineItems: [[CustomLineItem.svg List<CustomLineItem>]]
    totalLineItemQuantity: Long
    totalPrice: [[CentPrecisionMoney.svg CentPrecisionMoney]]
    taxedPrice: [[TaxedPrice.svg TaxedPrice]]
    taxedShippingPrice: [[TaxedPrice.svg TaxedPrice]]
    discountOnTotalPrice: [[DiscountOnTotalPrice.svg DiscountOnTotalPrice]]
    taxMode: [[TaxMode.svg TaxMode]]
    taxRoundingMode: [[RoundingMode.svg RoundingMode]]
    taxCalculationMode: [[TaxCalculationMode.svg TaxCalculationMode]]
    inventoryMode: [[InventoryMode.svg InventoryMode]]
    cartState: [[CartState.svg CartState]]
    billingAddress: [[Address.svg Address]]
    shippingAddress: [[Address.svg Address]]
    shippingMode: [[ShippingMode.svg ShippingMode]]
    shippingKey: String
    shippingInfo: [[ShippingInfo.svg ShippingInfo]]
    shippingRateInput: [[ShippingRateInput.svg ShippingRateInput]]
    shippingCustomFields: [[CustomFields.svg CustomFields]]
    shipping: [[Shipping.svg List<Shipping>]]
    itemShippingAddresses: [[Address.svg List<Address>]]
    discountCodes: [[DiscountCodeInfo.svg List<DiscountCodeInfo>]]
    directDiscounts: [[DirectDiscount.svg List<DirectDiscount>]]
    refusedGifts: [[CartDiscountReference.svg List<CartDiscountReference>]]
    paymentInfo: [[PaymentInfo.svg PaymentInfo]]
    country: String
    locale: String
    origin: [[CartOrigin.svg CartOrigin]]
    custom: [[CustomFields.svg CustomFields]]
    discountTypeCombination: [[DiscountTypeCombination.svg DiscountTypeCombination]]
    deleteDaysAfterLastModification: Integer
    lastModifiedBy: [[LastModifiedBy.svg LastModifiedBy]]
    createdBy: [[CreatedBy.svg CreatedBy]]
}
interface Category [[Category.svg]]  {
    id: String
    version: Long
    createdAt: DateTime
    lastModifiedAt: DateTime
    lastModifiedBy: [[LastModifiedBy.svg LastModifiedBy]]
    createdBy: [[CreatedBy.svg CreatedBy]]
    name: [[LocalizedString.svg LocalizedString]]
    slug: [[LocalizedString.svg LocalizedString]]
    description: [[LocalizedString.svg LocalizedString]]
    ancestors: [[CategoryReference.svg List<CategoryReference>]]
    parent: [[CategoryReference.svg CategoryReference]]
    orderHint: String
    externalId: String
    metaTitle: [[LocalizedString.svg LocalizedString]]
    metaDescription: [[LocalizedString.svg LocalizedString]]
    metaKeywords: [[LocalizedString.svg LocalizedString]]
    custom: [[CustomFields.svg CustomFields]]
    assets: [[Asset.svg List<Asset>]]
    key: String
}
interface Channel [[Channel.svg]]  {
    id: String
    version: Long
    createdAt: DateTime
    lastModifiedAt: DateTime
    lastModifiedBy: [[LastModifiedBy.svg LastModifiedBy]]
    createdBy: [[CreatedBy.svg CreatedBy]]
    key: String
    roles: [[ChannelRoleEnum.svg List<ChannelRoleEnum>]]
    name: [[LocalizedString.svg LocalizedString]]
    description: [[LocalizedString.svg LocalizedString]]
    address: [[Address.svg Address]]
    reviewRatingStatistics: [[ReviewRatingStatistics.svg ReviewRatingStatistics]]
    custom: [[CustomFields.svg CustomFields]]
    geoLocation: [[GeoJson.svg GeoJson]]
}
interface CustomObject [[CustomObject.svg]]  {
    id: String
    version: Long
    createdAt: DateTime
    lastModifiedAt: DateTime
    lastModifiedBy: [[LastModifiedBy.svg LastModifiedBy]]
    createdBy: [[CreatedBy.svg CreatedBy]]
    container: String
    key: String
    value: [[Object.svg Object]]
}
interface CustomerGroup [[CustomerGroup.svg]]  {
    id: String
    version: Long
    createdAt: DateTime
    lastModifiedAt: DateTime
    lastModifiedBy: [[LastModifiedBy.svg LastModifiedBy]]
    createdBy: [[CreatedBy.svg CreatedBy]]
    key: String
    name: String
    custom: [[CustomFields.svg CustomFields]]
}
interface Customer [[Customer.svg]]  {
    id: String
    version: Long
    createdAt: DateTime
    lastModifiedAt: DateTime
    key: String
    customerNumber: String
    externalId: String
    lastModifiedBy: [[LastModifiedBy.svg LastModifiedBy]]
    createdBy: [[CreatedBy.svg CreatedBy]]
    email: String
    password: String
    firstName: String
    lastName: String
    middleName: String
    title: String
    dateOfBirth: Date
    companyName: String
    vatId: String
    addresses: [[Address.svg List<Address>]]
    defaultShippingAddressId: String
    shippingAddressIds: [[String.svg List<String>]]
    defaultBillingAddressId: String
    billingAddressIds: [[String.svg List<String>]]
    isEmailVerified: Boolean
    customerGroup: [[CustomerGroupReference.svg CustomerGroupReference]]
    custom: [[CustomFields.svg CustomFields]]
    locale: String
    salutation: String
    stores: [[StoreKeyReference.svg List<StoreKeyReference>]]
    authenticationMode: [[AuthenticationMode.svg AuthenticationMode]]
    customerGroupAssignments: [[CustomerGroupAssignment.svg List<CustomerGroupAssignment>]]
}
interface DiscountCode [[DiscountCode.svg]]  {
    id: String
    version: Long
    createdAt: DateTime
    lastModifiedAt: DateTime
    key: String
    lastModifiedBy: [[LastModifiedBy.svg LastModifiedBy]]
    createdBy: [[CreatedBy.svg CreatedBy]]
    name: [[LocalizedString.svg LocalizedString]]
    description: [[LocalizedString.svg LocalizedString]]
    code: String
    cartDiscounts: [[CartDiscountReference.svg List<CartDiscountReference>]]
    cartPredicate: String
    isActive: Boolean
    references: [[Reference.svg List<Reference>]]
    maxApplications: Long
    maxApplicationsPerCustomer: Long
    custom: [[CustomFields.svg CustomFields]]
    groups: [[String.svg List<String>]]
    validFrom: DateTime
    validUntil: DateTime
    applicationVersion: Long
}
interface DiscountGroup [[DiscountGroup.svg]]  {
    id: String
    version: Long
    createdAt: DateTime
    lastModifiedAt: DateTime
    name: [[LocalizedString.svg LocalizedString]]
    key: String
    description: [[LocalizedString.svg LocalizedString]]
    sortOrder: String
    lastModifiedBy: [[LastModifiedBy.svg LastModifiedBy]]
    createdBy: [[CreatedBy.svg CreatedBy]]
}
interface Extension [[Extension.svg]]  {
    id: String
    version: Long
    createdAt: DateTime
    lastModifiedAt: DateTime
    lastModifiedBy: [[LastModifiedBy.svg LastModifiedBy]]
    createdBy: [[CreatedBy.svg CreatedBy]]
    key: String
    destination: [[ExtensionDestination.svg ExtensionDestination]]
    triggers: [[ExtensionTrigger.svg List<ExtensionTrigger>]]
    timeoutInMs: Integer
}
interface InventoryEntry [[InventoryEntry.svg]]  {
    id: String
    version: Long
    createdAt: DateTime
    lastModifiedAt: DateTime
    lastModifiedBy: [[LastModifiedBy.svg LastModifiedBy]]
    createdBy: [[CreatedBy.svg CreatedBy]]
    key: String
    sku: String
    supplyChannel: [[ChannelReference.svg ChannelReference]]
    quantityOnStock: Long
    availableQuantity: Long
    restockableInDays: Long
    expectedDelivery: DateTime
    custom: [[CustomFields.svg CustomFields]]
}
interface Message [[Message.svg]]  {
    id: String
    version: Long
    createdAt: DateTime
    lastModifiedAt: DateTime
    lastModifiedBy: [[LastModifiedBy.svg LastModifiedBy]]
    createdBy: [[CreatedBy.svg CreatedBy]]
    sequenceNumber: Long
    resource: [[Reference.svg Reference]]
    resourceVersion: Long
    type: String
    resourceUserProvidedIdentifiers: [[UserProvidedIdentifiers.svg UserProvidedIdentifiers]]
}
interface OrderEdit [[OrderEdit.svg]]  {
    id: String
    version: Long
    createdAt: DateTime
    lastModifiedAt: DateTime
    key: String
    resource: [[OrderReference.svg OrderReference]]
    stagedActions: [[StagedOrderUpdateAction.svg List<StagedOrderUpdateAction>]]
    result: [[OrderEditResult.svg OrderEditResult]]
    comment: String
    custom: [[CustomFields.svg CustomFields]]
    lastModifiedBy: [[LastModifiedBy.svg LastModifiedBy]]
    createdBy: [[CreatedBy.svg CreatedBy]]
}
interface Order [[Order.svg]]  {
    id: String
    version: Long
    createdAt: DateTime
    lastModifiedAt: DateTime
    orderNumber: String
    purchaseOrderNumber: String
    customerId: String
    customerEmail: String
    customerGroup: [[CustomerGroupReference.svg CustomerGroupReference]]
    anonymousId: String
    businessUnit: [[BusinessUnitKeyReference.svg BusinessUnitKeyReference]]
    store: [[StoreKeyReference.svg StoreKeyReference]]
    lineItems: [[LineItem.svg List<LineItem>]]
    customLineItems: [[CustomLineItem.svg List<CustomLineItem>]]
    totalPrice: [[CentPrecisionMoney.svg CentPrecisionMoney]]
    taxedPrice: [[TaxedPrice.svg TaxedPrice]]
    taxedShippingPrice: [[TaxedPrice.svg TaxedPrice]]
    discountOnTotalPrice: [[DiscountOnTotalPrice.svg DiscountOnTotalPrice]]
    taxMode: [[TaxMode.svg TaxMode]]
    taxRoundingMode: [[RoundingMode.svg RoundingMode]]
    taxCalculationMode: [[TaxCalculationMode.svg TaxCalculationMode]]
    inventoryMode: [[InventoryMode.svg InventoryMode]]
    billingAddress: [[Address.svg Address]]
    shippingAddress: [[Address.svg Address]]
    shippingMode: [[ShippingMode.svg ShippingMode]]
    shippingKey: String
    shippingInfo: [[ShippingInfo.svg ShippingInfo]]
    shippingRateInput: [[ShippingRateInput.svg ShippingRateInput]]
    shippingCustomFields: [[CustomFields.svg CustomFields]]
    shipping: [[Shipping.svg List<Shipping>]]
    itemShippingAddresses: [[Address.svg List<Address>]]
    discountCodes: [[DiscountCodeInfo.svg List<DiscountCodeInfo>]]
    directDiscounts: [[DirectDiscount.svg List<DirectDiscount>]]
    refusedGifts: [[CartDiscountReference.svg List<CartDiscountReference>]]
    paymentInfo: [[PaymentInfo.svg PaymentInfo]]
    country: String
    locale: String
    origin: [[CartOrigin.svg CartOrigin]]
    cart: [[CartReference.svg CartReference]]
    quote: [[QuoteReference.svg QuoteReference]]
    orderState: [[OrderState.svg OrderState]]
    shipmentState: [[ShipmentState.svg ShipmentState]]
    paymentState: [[PaymentState.svg PaymentState]]
    state: [[StateReference.svg StateReference]]
    syncInfo: [[SyncInfo.svg List<SyncInfo>]]
    returnInfo: [[ReturnInfo.svg List<ReturnInfo>]]
    discountTypeCombination: [[DiscountTypeCombination.svg DiscountTypeCombination]]
    lastMessageSequenceNumber: Long
    custom: [[CustomFields.svg CustomFields]]
    completedAt: DateTime
    lastModifiedBy: [[LastModifiedBy.svg LastModifiedBy]]
    createdBy: [[CreatedBy.svg CreatedBy]]
}
interface Payment [[Payment.svg]]  {
    id: String
    version: Long
    createdAt: DateTime
    lastModifiedAt: DateTime
    lastModifiedBy: [[LastModifiedBy.svg LastModifiedBy]]
    createdBy: [[CreatedBy.svg CreatedBy]]
    customer: [[CustomerReference.svg CustomerReference]]
    anonymousId: String
    externalId: String
    interfaceId: String
    amountPlanned: [[CentPrecisionMoney.svg CentPrecisionMoney]]
    amountAuthorized: [[TypedMoney.svg TypedMoney]]
    authorizedUntil: String
    amountPaid: [[TypedMoney.svg TypedMoney]]
    amountRefunded: [[TypedMoney.svg TypedMoney]]
    paymentMethodInfo: [[PaymentMethodInfo.svg PaymentMethodInfo]]
    paymentStatus: [[PaymentStatus.svg PaymentStatus]]
    transactions: [[Transaction.svg List<Transaction>]]
    interfaceInteractions: [[CustomFields.svg List<CustomFields>]]
    custom: [[CustomFields.svg CustomFields]]
    key: String
}
interface ProductDiscount [[ProductDiscount.svg]]  {
    id: String
    version: Long
    createdAt: DateTime
    lastModifiedAt: DateTime
    lastModifiedBy: [[LastModifiedBy.svg LastModifiedBy]]
    createdBy: [[CreatedBy.svg CreatedBy]]
    name: [[LocalizedString.svg LocalizedString]]
    key: String
    description: [[LocalizedString.svg LocalizedString]]
    value: [[ProductDiscountValue.svg ProductDiscountValue]]
    predicate: String
    sortOrder: String
    isActive: Boolean
    references: [[Reference.svg List<Reference>]]
    validFrom: DateTime
    validUntil: DateTime
}
interface ProductSelection [[ProductSelection.svg]]  {
    id: String
    version: Long
    createdAt: DateTime
    lastModifiedAt: DateTime
    lastModifiedBy: [[LastModifiedBy.svg LastModifiedBy]]
    createdBy: [[CreatedBy.svg CreatedBy]]
    key: String
    name: [[LocalizedString.svg LocalizedString]]
    productCount: Integer
    type: [[ProductSelectionTypeEnum.svg ProductSelectionTypeEnum]]
    mode: [[ProductSelectionMode.svg ProductSelectionMode]]
    custom: [[CustomFields.svg CustomFields]]
}
interface ProductTailoring [[ProductTailoring.svg]]  {
    id: String
    version: Long
    createdAt: DateTime
    lastModifiedAt: DateTime
    lastModifiedBy: [[LastModifiedBy.svg LastModifiedBy]]
    createdBy: [[CreatedBy.svg CreatedBy]]
    key: String
    store: [[StoreKeyReference.svg StoreKeyReference]]
    product: [[ProductReference.svg ProductReference]]
    published: Boolean
    current: [[ProductTailoringData.svg ProductTailoringData]]
    staged: [[ProductTailoringData.svg ProductTailoringData]]
    hasStagedChanges: Boolean
    warnings: [[WarningObject.svg List<WarningObject>]]
}
interface ProductType [[ProductType.svg]]  {
    id: String
    version: Long
    createdAt: DateTime
    lastModifiedAt: DateTime
    lastModifiedBy: [[LastModifiedBy.svg LastModifiedBy]]
    createdBy: [[CreatedBy.svg CreatedBy]]
    key: String
    name: String
    description: String
    attributes: [[AttributeDefinition.svg List<AttributeDefinition>]]
}
interface Product [[Product.svg]]  {
    id: String
    version: Long
    createdAt: DateTime
    lastModifiedAt: DateTime
    lastModifiedBy: [[LastModifiedBy.svg LastModifiedBy]]
    createdBy: [[CreatedBy.svg CreatedBy]]
    key: String
    productType: [[ProductTypeReference.svg ProductTypeReference]]
    masterData: [[ProductCatalogData.svg ProductCatalogData]]
    taxCategory: [[TaxCategoryReference.svg TaxCategoryReference]]
    state: [[StateReference.svg StateReference]]
    reviewRatingStatistics: [[ReviewRatingStatistics.svg ReviewRatingStatistics]]
    priceMode: [[ProductPriceModeEnum.svg ProductPriceModeEnum]]
    warnings: [[WarningObject.svg List<WarningObject>]]
}
interface SearchIndexingConfigurationValues [[SearchIndexingConfigurationValues.svg]]  {
    status: [[SearchIndexingConfigurationStatus.svg SearchIndexingConfigurationStatus]]
    lastModifiedAt: DateTime
    lastModifiedBy: [[LastModifiedBy.svg LastModifiedBy]]
}
interface QuoteRequest [[QuoteRequest.svg]]  {
    id: String
    version: Long
    createdAt: DateTime
    lastModifiedAt: DateTime
    key: String
    lastModifiedBy: [[LastModifiedBy.svg LastModifiedBy]]
    createdBy: [[CreatedBy.svg CreatedBy]]
    quoteRequestState: [[QuoteRequestState.svg QuoteRequestState]]
    comment: String
    customer: [[CustomerReference.svg CustomerReference]]
    customerGroup: [[CustomerGroupReference.svg CustomerGroupReference]]
    store: [[StoreKeyReference.svg StoreKeyReference]]
    lineItems: [[LineItem.svg List<LineItem>]]
    customLineItems: [[CustomLineItem.svg List<CustomLineItem>]]
    totalPrice: [[TypedMoney.svg TypedMoney]]
    taxedPrice: [[TaxedPrice.svg TaxedPrice]]
    shippingAddress: [[Address.svg Address]]
    billingAddress: [[Address.svg Address]]
    inventoryMode: [[InventoryMode.svg InventoryMode]]
    taxMode: [[TaxMode.svg TaxMode]]
    taxRoundingMode: [[RoundingMode.svg RoundingMode]]
    taxCalculationMode: [[TaxCalculationMode.svg TaxCalculationMode]]
    country: String
    shippingInfo: [[ShippingInfo.svg ShippingInfo]]
    paymentInfo: [[PaymentInfo.svg PaymentInfo]]
    shippingRateInput: [[ShippingRateInput.svg ShippingRateInput]]
    itemShippingAddresses: [[Address.svg List<Address>]]
    directDiscounts: [[DirectDiscount.svg List<DirectDiscount>]]
    custom: [[CustomFields.svg CustomFields]]
    state: [[StateReference.svg StateReference]]
    purchaseOrderNumber: String
    cart: [[CartReference.svg CartReference]]
    businessUnit: [[BusinessUnitKeyReference.svg BusinessUnitKeyReference]]
}
interface Quote [[Quote.svg]]  {
    id: String
    version: Long
    createdAt: DateTime
    lastModifiedAt: DateTime
    key: String
    lastModifiedBy: [[LastModifiedBy.svg LastModifiedBy]]
    createdBy: [[CreatedBy.svg CreatedBy]]
    quoteRequest: [[QuoteRequestReference.svg QuoteRequestReference]]
    stagedQuote: [[StagedQuoteReference.svg StagedQuoteReference]]
    customer: [[CustomerReference.svg CustomerReference]]
    customerGroup: [[CustomerGroupReference.svg CustomerGroupReference]]
    validTo: DateTime
    sellerComment: String
    buyerComment: String
    store: [[StoreKeyReference.svg StoreKeyReference]]
    lineItems: [[LineItem.svg List<LineItem>]]
    customLineItems: [[CustomLineItem.svg List<CustomLineItem>]]
    totalPrice: [[TypedMoney.svg TypedMoney]]
    taxedPrice: [[TaxedPrice.svg TaxedPrice]]
    shippingAddress: [[Address.svg Address]]
    billingAddress: [[Address.svg Address]]
    inventoryMode: [[InventoryMode.svg InventoryMode]]
    taxMode: [[TaxMode.svg TaxMode]]
    taxRoundingMode: [[RoundingMode.svg RoundingMode]]
    taxCalculationMode: [[TaxCalculationMode.svg TaxCalculationMode]]
    country: String
    shippingInfo: [[ShippingInfo.svg ShippingInfo]]
    paymentInfo: [[PaymentInfo.svg PaymentInfo]]
    shippingRateInput: [[ShippingRateInput.svg ShippingRateInput]]
    itemShippingAddresses: [[Address.svg List<Address>]]
    directDiscounts: [[DirectDiscount.svg List<DirectDiscount>]]
    custom: [[CustomFields.svg CustomFields]]
    quoteState: [[QuoteState.svg QuoteState]]
    state: [[StateReference.svg StateReference]]
    purchaseOrderNumber: String
    businessUnit: [[BusinessUnitKeyReference.svg BusinessUnitKeyReference]]
}
interface Review [[Review.svg]]  {
    id: String
    version: Long
    createdAt: DateTime
    lastModifiedAt: DateTime
    lastModifiedBy: [[LastModifiedBy.svg LastModifiedBy]]
    createdBy: [[CreatedBy.svg CreatedBy]]
    key: String
    uniquenessValue: String
    locale: String
    authorName: String
    title: String
    text: String
    target: [[Object.svg Object]]
    includedInStatistics: Boolean
    rating: Integer
    state: [[StateReference.svg StateReference]]
    customer: [[CustomerReference.svg CustomerReference]]
    custom: [[CustomFields.svg CustomFields]]
}
interface ShippingMethod [[ShippingMethod.svg]]  {
    id: String
    version: Long
    createdAt: DateTime
    lastModifiedAt: DateTime
    lastModifiedBy: [[LastModifiedBy.svg LastModifiedBy]]
    createdBy: [[CreatedBy.svg CreatedBy]]
    key: String
    name: String
    localizedName: [[LocalizedString.svg LocalizedString]]
    description: String
    localizedDescription: [[LocalizedString.svg LocalizedString]]
    taxCategory: [[TaxCategoryReference.svg TaxCategoryReference]]
    zoneRates: [[ZoneRate.svg List<ZoneRate>]]
    active: Boolean
    isDefault: Boolean
    predicate: String
    custom: [[CustomFields.svg CustomFields]]
}
interface ShoppingList [[ShoppingList.svg]]  {
    id: String
    version: Long
    createdAt: DateTime
    lastModifiedAt: DateTime
    name: [[LocalizedString.svg LocalizedString]]
    key: String
    customer: [[CustomerReference.svg CustomerReference]]
    slug: [[LocalizedString.svg LocalizedString]]
    description: [[LocalizedString.svg LocalizedString]]
    lineItems: [[ShoppingListLineItem.svg List<ShoppingListLineItem>]]
    textLineItems: [[TextLineItem.svg List<TextLineItem>]]
    deleteDaysAfterLastModification: Long
    anonymousId: String
    store: [[StoreKeyReference.svg StoreKeyReference]]
    businessUnit: [[BusinessUnitKeyReference.svg BusinessUnitKeyReference]]
    custom: [[CustomFields.svg CustomFields]]
    lastModifiedBy: [[LastModifiedBy.svg LastModifiedBy]]
    createdBy: [[CreatedBy.svg CreatedBy]]
}
interface StagedQuote [[StagedQuote.svg]]  {
    id: String
    version: Long
    createdAt: DateTime
    lastModifiedAt: DateTime
    key: String
    lastModifiedBy: [[LastModifiedBy.svg LastModifiedBy]]
    createdBy: [[CreatedBy.svg CreatedBy]]
    stagedQuoteState: [[StagedQuoteState.svg StagedQuoteState]]
    customer: [[CustomerReference.svg CustomerReference]]
    quoteRequest: [[QuoteRequestReference.svg QuoteRequestReference]]
    quotationCart: [[CartReference.svg CartReference]]
    validTo: DateTime
    sellerComment: String
    custom: [[CustomFields.svg CustomFields]]
    state: [[StateReference.svg StateReference]]
    purchaseOrderNumber: String
    businessUnit: [[BusinessUnitKeyReference.svg BusinessUnitKeyReference]]
    store: [[StoreKeyReference.svg StoreKeyReference]]
}
interface StandalonePrice [[StandalonePrice.svg]]  {
    id: String
    version: Long
    createdAt: DateTime
    lastModifiedAt: DateTime
    lastModifiedBy: [[LastModifiedBy.svg LastModifiedBy]]
    createdBy: [[CreatedBy.svg CreatedBy]]
    key: String
    sku: String
    value: [[TypedMoney.svg TypedMoney]]
    country: String
    customerGroup: [[CustomerGroupReference.svg CustomerGroupReference]]
    channel: [[ChannelReference.svg ChannelReference]]
    validFrom: DateTime
    validUntil: DateTime
    tiers: [[PriceTier.svg List<PriceTier>]]
    discounted: [[DiscountedPrice.svg DiscountedPrice]]
    custom: [[CustomFields.svg CustomFields]]
    staged: [[StagedStandalonePrice.svg StagedStandalonePrice]]
    active: Boolean
}
interface State [[State.svg]]  {
    id: String
    version: Long
    createdAt: DateTime
    lastModifiedAt: DateTime
    lastModifiedBy: [[LastModifiedBy.svg LastModifiedBy]]
    createdBy: [[CreatedBy.svg CreatedBy]]
    key: String
    type: [[StateTypeEnum.svg StateTypeEnum]]
    name: [[LocalizedString.svg LocalizedString]]
    description: [[LocalizedString.svg LocalizedString]]
    initial: Boolean
    builtIn: Boolean
    roles: [[StateRoleEnum.svg List<StateRoleEnum>]]
    transitions: [[StateReference.svg List<StateReference>]]
}
interface Store [[Store.svg]]  {
    id: String
    version: Long
    createdAt: DateTime
    lastModifiedAt: DateTime
    lastModifiedBy: [[LastModifiedBy.svg LastModifiedBy]]
    createdBy: [[CreatedBy.svg CreatedBy]]
    key: String
    name: [[LocalizedString.svg LocalizedString]]
    languages: [[String.svg List<String>]]
    countries: [[StoreCountry.svg List<StoreCountry>]]
    distributionChannels: [[ChannelReference.svg List<ChannelReference>]]
    supplyChannels: [[ChannelReference.svg List<ChannelReference>]]
    productSelections: [[ProductSelectionSetting.svg List<ProductSelectionSetting>]]
    custom: [[CustomFields.svg CustomFields]]
}
interface Subscription [[Subscription.svg]]  {
    id: String
    version: Long
    createdAt: DateTime
    lastModifiedAt: DateTime
    lastModifiedBy: [[LastModifiedBy.svg LastModifiedBy]]
    createdBy: [[CreatedBy.svg CreatedBy]]
    destination: [[Destination.svg Destination]]
    key: String
    messages: [[MessageSubscription.svg List<MessageSubscription>]]
    changes: [[ChangeSubscription.svg List<ChangeSubscription>]]
    events: [[EventSubscription.svg List<EventSubscription>]]
    format: [[DeliveryFormat.svg DeliveryFormat]]
    status: [[SubscriptionHealthStatus.svg SubscriptionHealthStatus]]
}
interface TaxCategory [[TaxCategory.svg]]  {
    id: String
    version: Long
    createdAt: DateTime
    lastModifiedAt: DateTime
    lastModifiedBy: [[LastModifiedBy.svg LastModifiedBy]]
    createdBy: [[CreatedBy.svg CreatedBy]]
    name: String
    description: String
    rates: [[TaxRate.svg List<TaxRate>]]
    key: String
}
interface Type [[Type.svg]]  {
    id: String
    version: Long
    createdAt: DateTime
    lastModifiedAt: DateTime
    lastModifiedBy: [[LastModifiedBy.svg LastModifiedBy]]
    createdBy: [[CreatedBy.svg CreatedBy]]
    key: String
    name: [[LocalizedString.svg LocalizedString]]
    description: [[LocalizedString.svg LocalizedString]]
    resourceTypeIds: [[ResourceTypeId.svg List<ResourceTypeId>]]
    fieldDefinitions: [[FieldDefinition.svg List<FieldDefinition>]]
}
interface Zone [[Zone.svg]]  {
    id: String
    version: Long
    createdAt: DateTime
    lastModifiedAt: DateTime
    lastModifiedBy: [[LastModifiedBy.svg LastModifiedBy]]
    createdBy: [[CreatedBy.svg CreatedBy]]
    key: String
    name: String
    description: String
    locations: [[Location.svg List<Location>]]
}

LastModifiedBy --> ApprovalFlow #green;text:green : "lastModifiedBy"
LastModifiedBy --> ApprovalRule #green;text:green : "lastModifiedBy"
LastModifiedBy --> AssociateRole #green;text:green : "lastModifiedBy"
LastModifiedBy --> AttributeGroup #green;text:green : "lastModifiedBy"
LastModifiedBy --> BusinessUnit #green;text:green : "lastModifiedBy"
LastModifiedBy --> CartDiscount #green;text:green : "lastModifiedBy"
LastModifiedBy --> Cart #green;text:green : "lastModifiedBy"
LastModifiedBy --> Category #green;text:green : "lastModifiedBy"
LastModifiedBy --> Channel #green;text:green : "lastModifiedBy"
LastModifiedBy --> CustomObject #green;text:green : "lastModifiedBy"
LastModifiedBy --> CustomerGroup #green;text:green : "lastModifiedBy"
LastModifiedBy --> Customer #green;text:green : "lastModifiedBy"
LastModifiedBy --> DiscountCode #green;text:green : "lastModifiedBy"
LastModifiedBy --> DiscountGroup #green;text:green : "lastModifiedBy"
LastModifiedBy --> Extension #green;text:green : "lastModifiedBy"
LastModifiedBy --> InventoryEntry #green;text:green : "lastModifiedBy"
LastModifiedBy --> Message #green;text:green : "lastModifiedBy"
LastModifiedBy --> OrderEdit #green;text:green : "lastModifiedBy"
LastModifiedBy --> Order #green;text:green : "lastModifiedBy"
LastModifiedBy --> Payment #green;text:green : "lastModifiedBy"
LastModifiedBy --> ProductDiscount #green;text:green : "lastModifiedBy"
LastModifiedBy --> ProductSelection #green;text:green : "lastModifiedBy"
LastModifiedBy --> ProductTailoring #green;text:green : "lastModifiedBy"
LastModifiedBy --> ProductType #green;text:green : "lastModifiedBy"
LastModifiedBy --> Product #green;text:green : "lastModifiedBy"
LastModifiedBy --> SearchIndexingConfigurationValues #green;text:green : "lastModifiedBy"
LastModifiedBy --> QuoteRequest #green;text:green : "lastModifiedBy"
LastModifiedBy --> Quote #green;text:green : "lastModifiedBy"
LastModifiedBy --> Review #green;text:green : "lastModifiedBy"
LastModifiedBy --> ShippingMethod #green;text:green : "lastModifiedBy"
LastModifiedBy --> ShoppingList #green;text:green : "lastModifiedBy"
LastModifiedBy --> StagedQuote #green;text:green : "lastModifiedBy"
LastModifiedBy --> StandalonePrice #green;text:green : "lastModifiedBy"
LastModifiedBy --> State #green;text:green : "lastModifiedBy"
LastModifiedBy --> Store #green;text:green : "lastModifiedBy"
LastModifiedBy --> Subscription #green;text:green : "lastModifiedBy"
LastModifiedBy --> TaxCategory #green;text:green : "lastModifiedBy"
LastModifiedBy --> Type #green;text:green : "lastModifiedBy"
LastModifiedBy --> Zone #green;text:green : "lastModifiedBy"
@enduml
