@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface LineItemRecurrenceInfo [[LineItemRecurrenceInfo.svg]]  {
    recurrencePolicy: [[RecurrencePolicyReference.svg RecurrencePolicyReference]]
    priceSelectionMode: [[PriceSelectionMode.svg PriceSelectionMode]]
}



interface LineItem [[LineItem.svg]]  {
    id: String
    key: String
    productId: String
    productKey: String
    name: [[LocalizedString.svg LocalizedString]]
    productSlug: [[LocalizedString.svg LocalizedString]]
    productType: [[ProductTypeReference.svg ProductTypeReference]]
    variant: [[ProductVariant.svg ProductVariant]]
    price: [[Price.svg Price]]
    quantity: Long
    totalPrice: [[CentPrecisionMoney.svg CentPrecisionMoney]]
    discountedPricePerQuantity: [[DiscountedLineItemPriceForQuantity.svg List<DiscountedLineItemPriceForQuantity>]]
    taxedPrice: [[TaxedItemPrice.svg TaxedItemPrice]]
    taxedPricePortions: [[MethodTaxedPrice.svg List<MethodTaxedPrice>]]
    state: [[ItemState.svg List<ItemState>]]
    taxRate: [[TaxRate.svg TaxRate]]
    perMethodTaxRate: [[MethodTaxRate.svg List<MethodTaxRate>]]
    supplyChannel: [[ChannelReference.svg ChannelReference]]
    distributionChannel: [[ChannelReference.svg ChannelReference]]
    priceMode: [[LineItemPriceMode.svg LineItemPriceMode]]
    lineItemMode: [[LineItemMode.svg LineItemMode]]
    inventoryMode: [[InventoryMode.svg InventoryMode]]
    shippingDetails: [[ItemShippingDetails.svg ItemShippingDetails]]
    custom: [[CustomFields.svg CustomFields]]
    addedAt: DateTime
    lastModifiedAt: DateTime
    recurrenceInfo: [[LineItemRecurrenceInfo.svg LineItemRecurrenceInfo]]
}

LineItemRecurrenceInfo --> LineItem #green;text:green : "recurrenceInfo"
@enduml
