@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface McpServerUpdateAction [[McpServerUpdateAction.svg]]  {
    action: String
}


interface McpServerAddToolAction [[McpServerAddToolAction.svg]]  {
    action: String
    tool: [[McpServerTool.svg McpServerTool]]
}
interface McpServerAddToolCustomizationAction [[McpServerAddToolCustomizationAction.svg]]  {
    action: String
    toolCustomization: [[ToolCustomization.svg ToolCustomization]]
}
interface McpServerRemoveToolAction [[McpServerRemoveToolAction.svg]]  {
    action: String
    tool: [[McpServerTool.svg McpServerTool]]
}
interface McpServerRemoveToolCustomizationAction [[McpServerRemoveToolCustomizationAction.svg]]  {
    action: String
    toolCustomization: [[RemoveToolCustomizationTarget.svg RemoveToolCustomizationTarget]]
}
interface McpServerSetAuthenticationModeAction [[McpServerSetAuthenticationModeAction.svg]]  {
    action: String
    authenticationMode: [[McpServerAuthenticationMode.svg McpServerAuthenticationMode]]
}
interface McpServerSetDescriptionAction [[McpServerSetDescriptionAction.svg]]  {
    action: String
    description: [[LocalizedString.svg LocalizedString]]
}
interface McpServerSetJsonOutputFilteringAction [[McpServerSetJsonOutputFilteringAction.svg]]  {
    action: String
    jsonOutputFiltering: [[McpServerJsonOutputFiltering.svg McpServerJsonOutputFiltering]]
}
interface McpServerSetNameAction [[McpServerSetNameAction.svg]]  {
    action: String
    name: [[LocalizedString.svg LocalizedString]]
}
interface McpServerSetStateAction [[McpServerSetStateAction.svg]]  {
    action: String
    state: [[McpServerState.svg McpServerState]]
}
interface McpServerSetToolCustomizationsAction [[McpServerSetToolCustomizationsAction.svg]]  {
    action: String
    toolCustomizations: [[ToolCustomization.svg List<ToolCustomization>]]
}
interface McpServerSetToolOutputFormattingAction [[McpServerSetToolOutputFormattingAction.svg]]  {
    action: String
    toolOutputFormatting: [[McpServerToolOutputFormatting.svg McpServerToolOutputFormatting]]
}
interface McpServerSetToolsAction [[McpServerSetToolsAction.svg]]  {
    action: String
    tools: [[McpServerTool.svg List<McpServerTool>]]
}
interface McpServerUpdate [[McpServerUpdate.svg]]  {
    version: Long
    actions: [[McpServerUpdateAction.svg List<McpServerUpdateAction>]]
}
McpServerUpdateAction --> McpServerAddToolAction #blue;text:blue : "action : addTool"
McpServerUpdateAction --> McpServerAddToolCustomizationAction #blue;text:blue : "action : addToolCustomization"
McpServerUpdateAction --> McpServerRemoveToolAction #blue;text:blue : "action : removeTool"
McpServerUpdateAction --> McpServerRemoveToolCustomizationAction #blue;text:blue : "action : removeToolCustomization"
McpServerUpdateAction --> McpServerSetAuthenticationModeAction #blue;text:blue : "action : setAuthenticationMode"
McpServerUpdateAction --> McpServerSetDescriptionAction #blue;text:blue : "action : setDescription"
McpServerUpdateAction --> McpServerSetJsonOutputFilteringAction #blue;text:blue : "action : setJsonOutputFiltering"
McpServerUpdateAction --> McpServerSetNameAction #blue;text:blue : "action : setName"
McpServerUpdateAction --> McpServerSetStateAction #blue;text:blue : "action : setState"
McpServerUpdateAction --> McpServerSetToolCustomizationsAction #blue;text:blue : "action : setToolCustomizations"
McpServerUpdateAction --> McpServerSetToolOutputFormattingAction #blue;text:blue : "action : setToolOutputFormatting"
McpServerUpdateAction --> McpServerSetToolsAction #blue;text:blue : "action : setTools"
McpServerUpdateAction --> McpServerUpdate #green;text:green : "actions"
@enduml
