@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface McpServerJsonOutputFiltering [[McpServerJsonOutputFiltering.svg]]  {
    redact: [[McpServerJsonOutputFilteringMatcher.svg McpServerJsonOutputFilteringMatcher]]
    drop: [[McpServerJsonOutputFilteringMatcher.svg McpServerJsonOutputFilteringMatcher]]
    fieldPathsToKeep: [[String.svg List<String>]]
    redactedWith: String
}



interface CommerceMcpServerConfig [[CommerceMcpServerConfig.svg]]  {
    type: String
    majorVersion: String
    url: String
    tools: [[McpServerTool.svg List<McpServerTool>]]
    toolCustomizations: [[ToolCustomization.svg List<ToolCustomization>]]
    jsonOutputFiltering: [[McpServerJsonOutputFiltering.svg McpServerJsonOutputFiltering]]
    toolOutputFormatting: [[McpServerToolOutputFormatting.svg McpServerToolOutputFormatting]]
}
interface CommerceMcpServerConfigDraft [[CommerceMcpServerConfigDraft.svg]]  {
    type: String
    majorVersion: String
    tools: [[McpServerTool.svg List<McpServerTool>]]
    toolCustomizations: [[ToolCustomization.svg List<ToolCustomization>]]
    jsonOutputFiltering: [[McpServerJsonOutputFiltering.svg McpServerJsonOutputFiltering]]
    toolOutputFormatting: [[McpServerToolOutputFormatting.svg McpServerToolOutputFormatting]]
}
interface McpServerSetJsonOutputFilteringAction [[McpServerSetJsonOutputFilteringAction.svg]]  {
    action: String
    jsonOutputFiltering: [[McpServerJsonOutputFiltering.svg McpServerJsonOutputFiltering]]
}

McpServerJsonOutputFiltering --> CommerceMcpServerConfig #green;text:green : "jsonOutputFiltering"
McpServerJsonOutputFiltering --> CommerceMcpServerConfigDraft #green;text:green : "jsonOutputFiltering"
McpServerJsonOutputFiltering --> McpServerSetJsonOutputFilteringAction #green;text:green : "jsonOutputFiltering"
@enduml
