@startuml

hide methods
enum McpServerState {
    ENABLED
    DISABLED
}
interface McpServer [[McpServer.svg]]  {
    id: String
    version: Long
    createdAt: DateTime
    lastModifiedAt: DateTime
    lastModifiedBy: [[LastModifiedBy.svg LastModifiedBy]]
    createdBy: [[CreatedBy.svg CreatedBy]]
    key: String
    name: [[LocalizedString.svg LocalizedString]]
    description: [[LocalizedString.svg LocalizedString]]
    authenticationMode: [[McpServerAuthenticationMode.svg McpServerAuthenticationMode]]
    state: [[McpServerState.svg McpServerState]]
    mcpServer: [[McpServerConfig.svg McpServerConfig]]
}
interface McpServerDraft [[McpServerDraft.svg]]  {
    key: String
    name: [[LocalizedString.svg LocalizedString]]
    description: [[LocalizedString.svg LocalizedString]]
    authenticationMode: [[McpServerAuthenticationMode.svg McpServerAuthenticationMode]]
    state: [[McpServerState.svg McpServerState]]
    mcpServer: [[McpServerConfigDraft.svg McpServerConfigDraft]]
}
interface McpServerSetStateAction [[McpServerSetStateAction.svg]]  {
    action: String
    state: [[McpServerState.svg McpServerState]]
}
McpServerState --> McpServer #green;text:green : "state"
McpServerState --> McpServerDraft #green;text:green : "state"
McpServerState --> McpServerSetStateAction #green;text:green : "state"
@enduml
