@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface MergeCartDraft [[MergeCartDraft.svg]]  {
    anonymousCart: [[CartResourceIdentifier.svg CartResourceIdentifier]]
    mergeMode: [[CartMergeMode.svg CartMergeMode]]
    updateProductData: Boolean
    anonymousId: String
}






@enduml
