@startuml

hide methods
enum MessageSubscriptionResourceTypeId {
    ASSOCIATE_ROLE
    BUSINESS_UNIT
    CATEGORY
    CUSTOMER
    CUSTOMER_EMAIL_TOKEN
    CUSTOMER_GROUP
    CUSTOMER_PASSWORD_TOKEN
    INVENTORY_ENTRY
    ORDER
    PAYMENT
    PRODUCT
    PRODUCT_SELECTION
    QUOTE
    QUOTE_REQUEST
    REVIEW
    STAGED_QUOTE
    STANDALONE_PRICE
    STORE
}
interface MessageSubscription [[MessageSubscription.svg]]  {
    resourceTypeId: [[MessageSubscriptionResourceTypeId.svg MessageSubscriptionResourceTypeId]]
    types: [[String.svg List<String>]]
}
MessageSubscriptionResourceTypeId --> MessageSubscription #green;text:green : "resourceTypeId"
@enduml
