@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface MessagesConfigurationDraft [[MessagesConfigurationDraft.svg]]  {
    enabled: Boolean
    deleteDaysAfterCreation: Integer
}



interface ProjectChangeMessagesConfigurationAction [[ProjectChangeMessagesConfigurationAction.svg]]  {
    action: String
    messagesConfiguration: [[MessagesConfigurationDraft.svg MessagesConfigurationDraft]]
}

MessagesConfigurationDraft --> ProjectChangeMessagesConfigurationAction #green;text:green : "messagesConfiguration"
@enduml
