@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface MethodExternalTaxRateDraft [[MethodExternalTaxRateDraft.svg]]  {
    shippingMethodKey: String
    taxRate: [[ExternalTaxRateDraft.svg ExternalTaxRateDraft]]
}



interface LineItemDraft [[LineItemDraft.svg]]  {
    key: String
    productId: String
    variantId: Long
    sku: String
    quantity: Long
    addedAt: DateTime
    distributionChannel: [[ChannelResourceIdentifier.svg ChannelResourceIdentifier]]
    supplyChannel: [[ChannelResourceIdentifier.svg ChannelResourceIdentifier]]
    externalPrice: [[Money.svg Money]]
    externalTotalPrice: [[ExternalLineItemTotalPrice.svg ExternalLineItemTotalPrice]]
    externalTaxRate: [[ExternalTaxRateDraft.svg ExternalTaxRateDraft]]
    perMethodExternalTaxRate: [[MethodExternalTaxRateDraft.svg List<MethodExternalTaxRateDraft>]]
    inventoryMode: [[InventoryMode.svg InventoryMode]]
    shippingDetails: [[ItemShippingDetailsDraft.svg ItemShippingDetailsDraft]]
    custom: [[CustomFieldsDraft.svg CustomFieldsDraft]]
}

MethodExternalTaxRateDraft --> LineItemDraft #green;text:green : "perMethodExternalTaxRate"
@enduml
