@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface MyBusinessUnitUpdateAction [[MyBusinessUnitUpdateAction.svg]]  {
    action: String
}


interface MyBusinessUnitAddAddressAction [[MyBusinessUnitAddAddressAction.svg]]  {
    action: String
    address: [[BaseAddress.svg BaseAddress]]
}
interface MyBusinessUnitAddBillingAddressIdAction [[MyBusinessUnitAddBillingAddressIdAction.svg]]  {
    action: String
    addressId: String
    addressKey: String
}
interface MyBusinessUnitAddShippingAddressIdAction [[MyBusinessUnitAddShippingAddressIdAction.svg]]  {
    action: String
    addressId: String
    addressKey: String
}
interface MyBusinessUnitChangeAddressAction [[MyBusinessUnitChangeAddressAction.svg]]  {
    action: String
    addressId: String
    addressKey: String
    address: [[BaseAddress.svg BaseAddress]]
}
interface MyBusinessUnitChangeAssociateAction [[MyBusinessUnitChangeAssociateAction.svg]]  {
    action: String
    associate: [[AssociateDraft.svg AssociateDraft]]
}
interface MyBusinessUnitChangeNameAction [[MyBusinessUnitChangeNameAction.svg]]  {
    action: String
    name: String
}
interface MyBusinessUnitChangeParentUnitAction [[MyBusinessUnitChangeParentUnitAction.svg]]  {
    action: String
    parentUnit: [[BusinessUnitResourceIdentifier.svg BusinessUnitResourceIdentifier]]
}
interface MyBusinessUnitRemoveAddressAction [[MyBusinessUnitRemoveAddressAction.svg]]  {
    action: String
    addressId: String
    addressKey: String
}
interface MyBusinessUnitRemoveAssociateAction [[MyBusinessUnitRemoveAssociateAction.svg]]  {
    action: String
    customer: [[CustomerResourceIdentifier.svg CustomerResourceIdentifier]]
}
interface MyBusinessUnitRemoveBillingAddressIdAction [[MyBusinessUnitRemoveBillingAddressIdAction.svg]]  {
    action: String
    addressId: String
    addressKey: String
}
interface MyBusinessUnitRemoveShippingAddressIdAction [[MyBusinessUnitRemoveShippingAddressIdAction.svg]]  {
    action: String
    addressId: String
    addressKey: String
}
interface MyBusinessUnitSetAddressCustomFieldAction [[MyBusinessUnitSetAddressCustomFieldAction.svg]]  {
    action: String
    addressId: String
    name: String
    value: [[Object.svg Object]]
}
interface MyBusinessUnitSetAddressCustomTypeAction [[MyBusinessUnitSetAddressCustomTypeAction.svg]]  {
    action: String
    type: [[TypeResourceIdentifier.svg TypeResourceIdentifier]]
    fields: [[FieldContainer.svg FieldContainer]]
    addressId: String
}
interface MyBusinessUnitSetContactEmailAction [[MyBusinessUnitSetContactEmailAction.svg]]  {
    action: String
    contactEmail: String
}
interface MyBusinessUnitSetCustomFieldAction [[MyBusinessUnitSetCustomFieldAction.svg]]  {
    action: String
    name: String
    value: [[Object.svg Object]]
}
interface MyBusinessUnitSetCustomTypeAction [[MyBusinessUnitSetCustomTypeAction.svg]]  {
    action: String
    type: [[TypeResourceIdentifier.svg TypeResourceIdentifier]]
    fields: [[FieldContainer.svg FieldContainer]]
}
interface MyBusinessUnitSetDefaultBillingAddressAction [[MyBusinessUnitSetDefaultBillingAddressAction.svg]]  {
    action: String
    addressId: String
    addressKey: String
}
interface MyBusinessUnitSetDefaultShippingAddressAction [[MyBusinessUnitSetDefaultShippingAddressAction.svg]]  {
    action: String
    addressId: String
    addressKey: String
}

MyBusinessUnitUpdateAction --> MyBusinessUnitAddAddressAction #blue;text:blue : "action : addAddress"
MyBusinessUnitUpdateAction --> MyBusinessUnitAddBillingAddressIdAction #blue;text:blue : "action : addBillingAddressId"
MyBusinessUnitUpdateAction --> MyBusinessUnitAddShippingAddressIdAction #blue;text:blue : "action : addShippingAddressId"
MyBusinessUnitUpdateAction --> MyBusinessUnitChangeAddressAction #blue;text:blue : "action : changeAddress"
MyBusinessUnitUpdateAction --> MyBusinessUnitChangeAssociateAction #blue;text:blue : "action : changeAssociate"
MyBusinessUnitUpdateAction --> MyBusinessUnitChangeNameAction #blue;text:blue : "action : changeName"
MyBusinessUnitUpdateAction --> MyBusinessUnitChangeParentUnitAction #blue;text:blue : "action : changeParentUnit"
MyBusinessUnitUpdateAction --> MyBusinessUnitRemoveAddressAction #blue;text:blue : "action : removeAddress"
MyBusinessUnitUpdateAction --> MyBusinessUnitRemoveAssociateAction #blue;text:blue : "action : removeAssociate"
MyBusinessUnitUpdateAction --> MyBusinessUnitRemoveBillingAddressIdAction #blue;text:blue : "action : removeBillingAddressId"
MyBusinessUnitUpdateAction --> MyBusinessUnitRemoveShippingAddressIdAction #blue;text:blue : "action : removeShippingAddressId"
MyBusinessUnitUpdateAction --> MyBusinessUnitSetAddressCustomFieldAction #blue;text:blue : "action : setAddressCustomField"
MyBusinessUnitUpdateAction --> MyBusinessUnitSetAddressCustomTypeAction #blue;text:blue : "action : setAddressCustomType"
MyBusinessUnitUpdateAction --> MyBusinessUnitSetContactEmailAction #blue;text:blue : "action : setContactEmail"
MyBusinessUnitUpdateAction --> MyBusinessUnitSetCustomFieldAction #blue;text:blue : "action : setCustomField"
MyBusinessUnitUpdateAction --> MyBusinessUnitSetCustomTypeAction #blue;text:blue : "action : setCustomType"
MyBusinessUnitUpdateAction --> MyBusinessUnitSetDefaultBillingAddressAction #blue;text:blue : "action : setDefaultBillingAddress"
MyBusinessUnitUpdateAction --> MyBusinessUnitSetDefaultShippingAddressAction #blue;text:blue : "action : setDefaultShippingAddress"

@enduml
