@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface MyCartApplyDeltaToLineItemShippingDetailsTargetsAction [[MyCartApplyDeltaToLineItemShippingDetailsTargetsAction.svg]] extends MyCartUpdateAction {
    action: String
    lineItemId: String
    lineItemKey: String
    targetsDelta: [[ItemShippingTarget.svg List<ItemShippingTarget>]]
}
interface MyCartUpdateAction [[MyCartUpdateAction.svg]]  {
    action: String
}





@enduml
