@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface MyCartDraft [[MyCartDraft.svg]]  {
    currency: String
    customerEmail: String
    country: String
    inventoryMode: [[InventoryMode.svg InventoryMode]]
    lineItems: [[MyLineItemDraft.svg List<MyLineItemDraft>]]
    shippingAddress: [[BaseAddress.svg BaseAddress]]
    billingAddress: [[BaseAddress.svg BaseAddress]]
    shippingMethod: [[ShippingMethodResourceIdentifier.svg ShippingMethodResourceIdentifier]]
    custom: [[CustomFieldsDraft.svg CustomFieldsDraft]]
    locale: String
    taxMode: [[TaxMode.svg TaxMode]]
    deleteDaysAfterLastModification: Long
    itemShippingAddresses: [[BaseAddress.svg List<BaseAddress>]]
    businessUnit: [[BusinessUnitKeyReference.svg BusinessUnitKeyReference]]
    store: [[StoreKeyReference.svg StoreKeyReference]]
    discountCodes: [[String.svg List<String>]]
}






@enduml
