@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface MyCartUpdateAction [[MyCartUpdateAction.svg]]  {
    action: String
}


interface MyCartAddDiscountCodeAction [[MyCartAddDiscountCodeAction.svg]]  {
    action: String
    code: String
}
interface MyCartAddItemShippingAddressAction [[MyCartAddItemShippingAddressAction.svg]]  {
    action: String
    address: [[BaseAddress.svg BaseAddress]]
}
interface MyCartAddLineItemAction [[MyCartAddLineItemAction.svg]]  {
    action: String
    key: String
    productId: String
    variantId: Long
    sku: String
    quantity: Long
    addedAt: DateTime
    distributionChannel: [[ChannelResourceIdentifier.svg ChannelResourceIdentifier]]
    supplyChannel: [[ChannelResourceIdentifier.svg ChannelResourceIdentifier]]
    shippingDetails: [[ItemShippingDetailsDraft.svg ItemShippingDetailsDraft]]
    custom: [[CustomFieldsDraft.svg CustomFieldsDraft]]
}
interface MyCartAddPaymentAction [[MyCartAddPaymentAction.svg]]  {
    action: String
    payment: [[PaymentResourceIdentifier.svg PaymentResourceIdentifier]]
}
interface MyCartApplyDeltaToLineItemShippingDetailsTargetsAction [[MyCartApplyDeltaToLineItemShippingDetailsTargetsAction.svg]]  {
    action: String
    lineItemId: String
    targetsDelta: [[ItemShippingTarget.svg List<ItemShippingTarget>]]
}
interface MyCartChangeLineItemQuantityAction [[MyCartChangeLineItemQuantityAction.svg]]  {
    action: String
    lineItemId: String
    quantity: Long
    externalPrice: [[Money.svg Money]]
    externalTotalPrice: [[ExternalLineItemTotalPrice.svg ExternalLineItemTotalPrice]]
}
interface MyCartChangeTaxModeAction [[MyCartChangeTaxModeAction.svg]]  {
    action: String
    taxMode: [[TaxMode.svg TaxMode]]
}
interface MyCartRecalculateAction [[MyCartRecalculateAction.svg]]  {
    action: String
    updateProductData: Boolean
}
interface MyCartRemoveDiscountCodeAction [[MyCartRemoveDiscountCodeAction.svg]]  {
    action: String
    discountCode: [[DiscountCodeReference.svg DiscountCodeReference]]
}
interface MyCartRemoveItemShippingAddressAction [[MyCartRemoveItemShippingAddressAction.svg]]  {
    action: String
    addressKey: String
}
interface MyCartRemoveLineItemAction [[MyCartRemoveLineItemAction.svg]]  {
    action: String
    lineItemId: String
    quantity: Long
    externalPrice: [[Money.svg Money]]
    externalTotalPrice: [[ExternalLineItemTotalPrice.svg ExternalLineItemTotalPrice]]
    shippingDetailsToRemove: [[ItemShippingDetailsDraft.svg ItemShippingDetailsDraft]]
}
interface MyCartRemovePaymentAction [[MyCartRemovePaymentAction.svg]]  {
    action: String
    payment: [[PaymentResourceIdentifier.svg PaymentResourceIdentifier]]
}
interface MyCartSetBillingAddressAction [[MyCartSetBillingAddressAction.svg]]  {
    action: String
    address: [[BaseAddress.svg BaseAddress]]
}
interface MyCartSetBusinessUnitAction [[MyCartSetBusinessUnitAction.svg]]  {
    action: String
    businessUnit: [[BusinessUnitResourceIdentifier.svg BusinessUnitResourceIdentifier]]
}
interface MyCartSetCountryAction [[MyCartSetCountryAction.svg]]  {
    action: String
    country: String
}
interface MyCartSetCustomFieldAction [[MyCartSetCustomFieldAction.svg]]  {
    action: String
    name: String
    value: [[Object.svg Object]]
}
interface MyCartSetCustomTypeAction [[MyCartSetCustomTypeAction.svg]]  {
    action: String
    type: [[TypeResourceIdentifier.svg TypeResourceIdentifier]]
    fields: [[FieldContainer.svg FieldContainer]]
}
interface MyCartSetCustomerEmailAction [[MyCartSetCustomerEmailAction.svg]]  {
    action: String
    email: String
}
interface MyCartSetDeleteDaysAfterLastModificationAction [[MyCartSetDeleteDaysAfterLastModificationAction.svg]]  {
    action: String
    deleteDaysAfterLastModification: Integer
}
interface MyCartSetDirectDiscountsAction [[MyCartSetDirectDiscountsAction.svg]]  {
    action: String
    discounts: [[DirectDiscountDraft.svg List<DirectDiscountDraft>]]
}
interface MyCartSetLineItemCustomFieldAction [[MyCartSetLineItemCustomFieldAction.svg]]  {
    action: String
    lineItemId: String
    name: String
    value: [[Object.svg Object]]
}
interface MyCartSetLineItemCustomTypeAction [[MyCartSetLineItemCustomTypeAction.svg]]  {
    action: String
    lineItemId: String
    type: [[TypeResourceIdentifier.svg TypeResourceIdentifier]]
    fields: [[FieldContainer.svg FieldContainer]]
}
interface MyCartSetLineItemDistributionChannelAction [[MyCartSetLineItemDistributionChannelAction.svg]]  {
    action: String
    lineItemId: String
    distributionChannel: [[ChannelResourceIdentifier.svg ChannelResourceIdentifier]]
}
interface MyCartSetLineItemShippingDetailsAction [[MyCartSetLineItemShippingDetailsAction.svg]]  {
    action: String
    lineItemId: String
    shippingDetails: [[ItemShippingDetailsDraft.svg ItemShippingDetailsDraft]]
}
interface MyCartSetLineItemSupplyChannelAction [[MyCartSetLineItemSupplyChannelAction.svg]]  {
    action: String
    lineItemId: String
    supplyChannel: [[ChannelResourceIdentifier.svg ChannelResourceIdentifier]]
}
interface MyCartSetLocaleAction [[MyCartSetLocaleAction.svg]]  {
    action: String
    locale: String
}
interface MyCartSetShippingAddressAction [[MyCartSetShippingAddressAction.svg]]  {
    action: String
    address: [[BaseAddress.svg BaseAddress]]
}
interface MyCartSetShippingMethodAction [[MyCartSetShippingMethodAction.svg]]  {
    action: String
    shippingMethod: [[ShippingMethodResourceIdentifier.svg ShippingMethodResourceIdentifier]]
    externalTaxRate: [[ExternalTaxRateDraft.svg ExternalTaxRateDraft]]
}
interface MyCartUpdateItemShippingAddressAction [[MyCartUpdateItemShippingAddressAction.svg]]  {
    action: String
    address: [[BaseAddress.svg BaseAddress]]
}
interface MyCartUpdate [[MyCartUpdate.svg]]  {
    version: Long
    actions: [[MyCartUpdateAction.svg List<MyCartUpdateAction>]]
}
MyCartUpdateAction --> MyCartAddDiscountCodeAction #blue;text:blue : "action : addDiscountCode"
MyCartUpdateAction --> MyCartAddItemShippingAddressAction #blue;text:blue : "action : addItemShippingAddress"
MyCartUpdateAction --> MyCartAddLineItemAction #blue;text:blue : "action : addLineItem"
MyCartUpdateAction --> MyCartAddPaymentAction #blue;text:blue : "action : addPayment"
MyCartUpdateAction --> MyCartApplyDeltaToLineItemShippingDetailsTargetsAction #blue;text:blue : "action : applyDeltaToLineItemShippingDetailsTargets"
MyCartUpdateAction --> MyCartChangeLineItemQuantityAction #blue;text:blue : "action : changeLineItemQuantity"
MyCartUpdateAction --> MyCartChangeTaxModeAction #blue;text:blue : "action : changeTaxMode"
MyCartUpdateAction --> MyCartRecalculateAction #blue;text:blue : "action : recalculate"
MyCartUpdateAction --> MyCartRemoveDiscountCodeAction #blue;text:blue : "action : removeDiscountCode"
MyCartUpdateAction --> MyCartRemoveItemShippingAddressAction #blue;text:blue : "action : removeItemShippingAddress"
MyCartUpdateAction --> MyCartRemoveLineItemAction #blue;text:blue : "action : removeLineItem"
MyCartUpdateAction --> MyCartRemovePaymentAction #blue;text:blue : "action : removePayment"
MyCartUpdateAction --> MyCartSetBillingAddressAction #blue;text:blue : "action : setBillingAddress"
MyCartUpdateAction --> MyCartSetBusinessUnitAction #blue;text:blue : "action : setBusinessUnit"
MyCartUpdateAction --> MyCartSetCountryAction #blue;text:blue : "action : setCountry"
MyCartUpdateAction --> MyCartSetCustomFieldAction #blue;text:blue : "action : setCustomField"
MyCartUpdateAction --> MyCartSetCustomTypeAction #blue;text:blue : "action : setCustomType"
MyCartUpdateAction --> MyCartSetCustomerEmailAction #blue;text:blue : "action : setCustomerEmail"
MyCartUpdateAction --> MyCartSetDeleteDaysAfterLastModificationAction #blue;text:blue : "action : setDeleteDaysAfterLastModification"
MyCartUpdateAction --> MyCartSetDirectDiscountsAction #blue;text:blue : "action : setDirectDiscounts"
MyCartUpdateAction --> MyCartSetLineItemCustomFieldAction #blue;text:blue : "action : setLineItemCustomField"
MyCartUpdateAction --> MyCartSetLineItemCustomTypeAction #blue;text:blue : "action : setLineItemCustomType"
MyCartUpdateAction --> MyCartSetLineItemDistributionChannelAction #blue;text:blue : "action : setLineItemDistributionChannel"
MyCartUpdateAction --> MyCartSetLineItemShippingDetailsAction #blue;text:blue : "action : setLineItemShippingDetails"
MyCartUpdateAction --> MyCartSetLineItemSupplyChannelAction #blue;text:blue : "action : setLineItemSupplyChannel"
MyCartUpdateAction --> MyCartSetLocaleAction #blue;text:blue : "action : setLocale"
MyCartUpdateAction --> MyCartSetShippingAddressAction #blue;text:blue : "action : setShippingAddress"
MyCartUpdateAction --> MyCartSetShippingMethodAction #blue;text:blue : "action : setShippingMethod"
MyCartUpdateAction --> MyCartUpdateItemShippingAddressAction #blue;text:blue : "action : updateItemShippingAddress"
MyCartUpdateAction --> MyCartUpdate #green;text:green : "actions"
@enduml
