@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface MyTransactionDraft [[MyTransactionDraft.svg]]  {
    timestamp: DateTime
    type: [[TransactionType.svg TransactionType]]
    amount: [[Money.svg Money]]
    interactionId: String
    custom: [[CustomFieldsDraft.svg CustomFieldsDraft]]
}



interface MyPaymentDraft [[MyPaymentDraft.svg]]  {
    amountPlanned: [[Money.svg Money]]
    paymentMethodInfo: [[PaymentMethodInfoDraft.svg PaymentMethodInfoDraft]]
    custom: [[CustomFieldsDraft.svg CustomFieldsDraft]]
    transaction: [[MyTransactionDraft.svg MyTransactionDraft]]
}

MyTransactionDraft --> MyPaymentDraft #green;text:green : "transaction"
@enduml
