@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface OrderSearchSorting [[OrderSearchSorting.svg]]  {
    field: String
    language: String
    order: [[OrderSearchSortOrder.svg OrderSearchSortOrder]]
    mode: [[OrderSearchSortMode.svg OrderSearchSortMode]]
    filter: [[OrderSearchQueryExpression.svg OrderSearchQueryExpression]]
}



interface OrderSearchRequest [[OrderSearchRequest.svg]]  {
    query: [[OrderSearchQuery.svg OrderSearchQuery]]
    sort: [[OrderSearchSorting.svg List<OrderSearchSorting>]]
    limit: Integer
    offset: Integer
}

OrderSearchSorting --> OrderSearchRequest #green;text:green : "sort"
@enduml
