@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface OrderEditPreviewSuccess [[OrderEditPreviewSuccess.svg]] extends OrderEditResult {
    type: String
    preview: [[StagedOrder.svg StagedOrder]]
    messagePayloads: [[MessagePayload.svg List<MessagePayload>]]
}
interface OrderEditResult [[OrderEditResult.svg]]  {
    type: String
}





@enduml
