@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface OrderPaymentAddedMessagePayload [[OrderPaymentAddedMessagePayload.svg]] extends MessagePayload {
    type: String
    payment: [[PaymentReference.svg PaymentReference]]
}
interface MessagePayload [[MessagePayload.svg]]  {
    type: String
}





@enduml
