@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface OrderSetReturnInfoAction [[OrderSetReturnInfoAction.svg]] extends OrderUpdateAction {
    action: String
    items: [[ReturnInfoDraft.svg List<ReturnInfoDraft>]]
}
interface OrderUpdateAction [[OrderUpdateAction.svg]]  {
    action: String
}





@enduml
