@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface OrderImportCustomLineItemStateAction [[OrderImportCustomLineItemStateAction.svg]] extends OrderUpdateAction {
    action: String
    customLineItemId: String
    customLineItemKey: String
    state: [[ItemState.svg List<ItemState>]]
}
interface OrderUpdateAction [[OrderUpdateAction.svg]]  {
    action: String
}





@enduml
