@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface OrderPurchaseOrderNumberSetMessagePayload [[OrderPurchaseOrderNumberSetMessagePayload.svg]] extends OrderMessagePayload {
    type: String
    purchaseOrderNumber: String
    oldPurchaseOrderNumber: String
}
interface OrderMessagePayload [[OrderMessagePayload.svg]]  {
    type: String
}





@enduml
