@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface OrderSearchQuery [[OrderSearchQuery.svg]]  {
}



interface OrderSearchRequest [[OrderSearchRequest.svg]]  {
    query: [[OrderSearchQuery.svg OrderSearchQuery]]
    sort: [[OrderSearchSorting.svg List<OrderSearchSorting>]]
    limit: Integer
    offset: Integer
}

OrderSearchQuery --> OrderSearchRequest #green;text:green : "query"
@enduml
