@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface OrderSearchQuery [[OrderSearchQuery.svg]]  {
}

interface OrderSearchAndExpression [[OrderSearchAndExpression.svg]] extends OrderSearchCompoundExpression {
    and: [[OrderSearchQuery.svg List<OrderSearchQuery>]]
}
interface OrderSearchCompoundExpression [[OrderSearchCompoundExpression.svg]] extends OrderSearchQuery {
}
interface OrderSearchDateRangeExpression [[OrderSearchDateRangeExpression.svg]] extends OrderSearchQueryExpression {
    range: [[OrderSearchDateRangeValue.svg OrderSearchDateRangeValue]]
}
interface OrderSearchExactExpression [[OrderSearchExactExpression.svg]] extends OrderSearchQueryExpression {
    exact: [[OrderSearchAnyValue.svg OrderSearchAnyValue]]
}
interface OrderSearchExistsExpression [[OrderSearchExistsExpression.svg]] extends OrderSearchQueryExpression {
    exists: [[OrderSearchQueryExpressionValue.svg OrderSearchQueryExpressionValue]]
}
interface OrderSearchFilterExpression [[OrderSearchFilterExpression.svg]] extends OrderSearchCompoundExpression {
    filter: [[OrderSearchQueryExpression.svg List<OrderSearchQueryExpression>]]
}
interface OrderSearchFullTextExpression [[OrderSearchFullTextExpression.svg]] extends OrderSearchQueryExpression {
    fullText: [[OrderSearchFullTextValue.svg OrderSearchFullTextValue]]
}
interface OrderSearchLongRangeExpression [[OrderSearchLongRangeExpression.svg]] extends OrderSearchQueryExpression {
    range: [[OrderSearchLongRangeValue.svg OrderSearchLongRangeValue]]
}
interface OrderSearchNotExpression [[OrderSearchNotExpression.svg]] extends OrderSearchCompoundExpression {
    not: [[OrderSearchQuery.svg List<OrderSearchQuery>]]
}
interface OrderSearchNumberRangeExpression [[OrderSearchNumberRangeExpression.svg]] extends OrderSearchQueryExpression {
    range: [[OrderSearchNumberRangeValue.svg OrderSearchNumberRangeValue]]
}
interface OrderSearchOrExpression [[OrderSearchOrExpression.svg]] extends OrderSearchCompoundExpression {
    or: [[OrderSearchQuery.svg List<OrderSearchQuery>]]
}
interface OrderSearchPrefixExpression [[OrderSearchPrefixExpression.svg]] extends OrderSearchQueryExpression {
    prefix: [[OrderSearchStringValue.svg OrderSearchStringValue]]
}
interface OrderSearchQueryExpression [[OrderSearchQueryExpression.svg]] extends OrderSearchQuery {
}
interface OrderSearchWildCardExpression [[OrderSearchWildCardExpression.svg]] extends OrderSearchQueryExpression {
    wildcard: [[OrderSearchStringValue.svg OrderSearchStringValue]]
}

interface OrderSearchAndExpression [[OrderSearchAndExpression.svg]]  {
    and: [[OrderSearchQuery.svg List<OrderSearchQuery>]]
}
interface OrderSearchNotExpression [[OrderSearchNotExpression.svg]]  {
    not: [[OrderSearchQuery.svg List<OrderSearchQuery>]]
}
interface OrderSearchOrExpression [[OrderSearchOrExpression.svg]]  {
    or: [[OrderSearchQuery.svg List<OrderSearchQuery>]]
}
interface OrderSearchRequest [[OrderSearchRequest.svg]]  {
    query: [[OrderSearchQuery.svg OrderSearchQuery]]
    sort: [[OrderSearchSorting.svg List<OrderSearchSorting>]]
    limit: Integer
    offset: Integer
}

OrderSearchQuery --> OrderSearchAndExpression #green;text:green : "and"
OrderSearchQuery --> OrderSearchAndExpression #green;text:green : "and"
OrderSearchQuery --> OrderSearchNotExpression #green;text:green : "not"
OrderSearchQuery --> OrderSearchNotExpression #green;text:green : "not"
OrderSearchQuery --> OrderSearchOrExpression #green;text:green : "or"
OrderSearchQuery --> OrderSearchOrExpression #green;text:green : "or"
OrderSearchQuery --> OrderSearchRequest #green;text:green : "query"
@enduml
