@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface OrderDiscountCodeStateSetMessagePayload [[OrderDiscountCodeStateSetMessagePayload.svg]] extends OrderMessagePayload {
    type: String
    discountCode: [[DiscountCodeReference.svg DiscountCodeReference]]
    state: [[DiscountCodeState.svg DiscountCodeState]]
    oldState: [[DiscountCodeState.svg DiscountCodeState]]
}
interface OrderMessagePayload [[OrderMessagePayload.svg]]  {
    type: String
}





@enduml
