@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface OrderEditSetKeyAction [[OrderEditSetKeyAction.svg]] extends OrderEditUpdateAction {
    action: String
    key: String
}
interface OrderEditUpdateAction [[OrderEditUpdateAction.svg]]  {
    action: String
}





@enduml
