@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface OrderEditApplied [[OrderEditApplied.svg]] extends OrderEditResult {
    type: String
    appliedAt: DateTime
    excerptBeforeEdit: [[OrderExcerpt.svg OrderExcerpt]]
    excerptAfterEdit: [[OrderExcerpt.svg OrderExcerpt]]
}
interface OrderEditResult [[OrderEditResult.svg]]  {
    type: String
}


interface OrderEditAppliedMessage [[OrderEditAppliedMessage.svg]]  {
    id: String
    version: Long
    createdAt: DateTime
    lastModifiedAt: DateTime
    lastModifiedBy: [[LastModifiedBy.svg LastModifiedBy]]
    createdBy: [[CreatedBy.svg CreatedBy]]
    sequenceNumber: Long
    resource: [[Reference.svg Reference]]
    resourceVersion: Long
    type: String
    resourceUserProvidedIdentifiers: [[UserProvidedIdentifiers.svg UserProvidedIdentifiers]]
    edit: [[OrderEdit.svg OrderEdit]]
    result: [[OrderEditApplied.svg OrderEditApplied]]
}
interface OrderEditAppliedMessagePayload [[OrderEditAppliedMessagePayload.svg]]  {
    type: String
    edit: [[OrderEdit.svg OrderEdit]]
    result: [[OrderEditApplied.svg OrderEditApplied]]
}

OrderEditApplied --> OrderEditAppliedMessage #green;text:green : "result"
OrderEditApplied --> OrderEditAppliedMessagePayload #green;text:green : "result"
@enduml
