@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface OutOfStockError [[OutOfStockError.svg]] extends ErrorObject {
    code: String
    message: String
    lineItems: [[String.svg List<String>]]
    skus: [[String.svg List<String>]]
}
interface ErrorObject [[ErrorObject.svg]]  {
    code: String
    message: String
}





@enduml
