@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface ParcelRemovedFromDeliveryMessagePayload [[ParcelRemovedFromDeliveryMessagePayload.svg]] extends OrderMessagePayload {
    type: String
    deliveryId: String
    parcel: [[Parcel.svg Parcel]]
    shippingKey: String
}
interface OrderMessagePayload [[OrderMessagePayload.svg]]  {
    type: String
}





@enduml
