@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface PatternComponent [[PatternComponent.svg]]  {
    type: String
}


interface CountOnCustomLineItemUnits [[CountOnCustomLineItemUnits.svg]]  {
    type: String
    predicate: String
    minCount: Integer
    maxCount: Integer
    excludeCount: Integer
}
interface CountOnLineItemUnits [[CountOnLineItemUnits.svg]]  {
    type: String
    predicate: String
    minCount: Integer
    maxCount: Integer
    excludeCount: Integer
}
interface CartDiscountPatternTarget [[CartDiscountPatternTarget.svg]]  {
    type: String
    triggerPattern: [[PatternComponent.svg List<PatternComponent>]]
    targetPattern: [[PatternComponent.svg List<PatternComponent>]]
    maxOccurrence: Integer
    selectionMode: [[SelectionMode.svg SelectionMode]]
}
PatternComponent --> CountOnCustomLineItemUnits #blue;text:blue : "type : CountOnCustomLineItemUnits"
PatternComponent --> CountOnLineItemUnits #blue;text:blue : "type : CountOnLineItemUnits"
PatternComponent --> CartDiscountPatternTarget #green;text:green : "triggerPattern"
PatternComponent --> CartDiscountPatternTarget #green;text:green : "targetPattern"
@enduml
