@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface PaymentMethodSetPaymentMethodStatusAction [[PaymentMethodSetPaymentMethodStatusAction.svg]] extends PaymentMethodUpdateAction {
    action: String
    paymentMethodStatus: [[PaymentMethodStatus.svg PaymentMethodStatus]]
}
interface PaymentMethodUpdateAction [[PaymentMethodUpdateAction.svg]]  {
    action: String
}





@enduml
