@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface PaymentUpdateAction [[PaymentUpdateAction.svg]]  {
    action: String
}


interface PaymentAddInterfaceInteractionAction [[PaymentAddInterfaceInteractionAction.svg]]  {
    action: String
    type: [[TypeResourceIdentifier.svg TypeResourceIdentifier]]
    fields: [[FieldContainer.svg FieldContainer]]
}
interface PaymentAddTransactionAction [[PaymentAddTransactionAction.svg]]  {
    action: String
    transaction: [[TransactionDraft.svg TransactionDraft]]
}
interface PaymentChangeAmountPlannedAction [[PaymentChangeAmountPlannedAction.svg]]  {
    action: String
    amount: [[Money.svg Money]]
}
interface PaymentChangeTransactionInteractionIdAction [[PaymentChangeTransactionInteractionIdAction.svg]]  {
    action: String
    transactionId: String
    interactionId: String
}
interface PaymentChangeTransactionStateAction [[PaymentChangeTransactionStateAction.svg]]  {
    action: String
    transactionId: String
    state: [[TransactionState.svg TransactionState]]
}
interface PaymentChangeTransactionTimestampAction [[PaymentChangeTransactionTimestampAction.svg]]  {
    action: String
    transactionId: String
    timestamp: DateTime
}
interface PaymentSetAmountPaidAction [[PaymentSetAmountPaidAction.svg]]  {
    action: String
    amount: [[Money.svg Money]]
}
interface PaymentSetAmountRefundedAction [[PaymentSetAmountRefundedAction.svg]]  {
    action: String
    amount: [[Money.svg Money]]
}
interface PaymentSetAnonymousIdAction [[PaymentSetAnonymousIdAction.svg]]  {
    action: String
    anonymousId: String
}
interface PaymentSetAuthorizationAction [[PaymentSetAuthorizationAction.svg]]  {
    action: String
    amount: [[Money.svg Money]]
    until: DateTime
}
interface PaymentSetCustomFieldAction [[PaymentSetCustomFieldAction.svg]]  {
    action: String
    name: String
    value: [[Object.svg Object]]
}
interface PaymentSetCustomTypeAction [[PaymentSetCustomTypeAction.svg]]  {
    action: String
    type: [[TypeResourceIdentifier.svg TypeResourceIdentifier]]
    fields: [[FieldContainer.svg FieldContainer]]
}
interface PaymentSetCustomerAction [[PaymentSetCustomerAction.svg]]  {
    action: String
    customer: [[CustomerResourceIdentifier.svg CustomerResourceIdentifier]]
}
interface PaymentSetExternalIdAction [[PaymentSetExternalIdAction.svg]]  {
    action: String
    externalId: String
}
interface PaymentSetInterfaceIdAction [[PaymentSetInterfaceIdAction.svg]]  {
    action: String
    interfaceId: String
}
interface PaymentSetKeyAction [[PaymentSetKeyAction.svg]]  {
    action: String
    key: String
}
interface PaymentSetMethodInfoInterfaceAction [[PaymentSetMethodInfoInterfaceAction.svg]]  {
    action: String
    interface: String
}
interface PaymentSetMethodInfoMethodAction [[PaymentSetMethodInfoMethodAction.svg]]  {
    action: String
    method: String
}
interface PaymentSetMethodInfoNameAction [[PaymentSetMethodInfoNameAction.svg]]  {
    action: String
    name: [[LocalizedString.svg LocalizedString]]
}
interface PaymentSetStatusInterfaceCodeAction [[PaymentSetStatusInterfaceCodeAction.svg]]  {
    action: String
    interfaceCode: String
}
interface PaymentSetStatusInterfaceTextAction [[PaymentSetStatusInterfaceTextAction.svg]]  {
    action: String
    interfaceText: String
}
interface PaymentSetTransactionCustomFieldAction [[PaymentSetTransactionCustomFieldAction.svg]]  {
    action: String
    transactionId: String
    name: String
    value: [[Object.svg Object]]
}
interface PaymentSetTransactionCustomTypeAction [[PaymentSetTransactionCustomTypeAction.svg]]  {
    action: String
    transactionId: String
    type: [[TypeResourceIdentifier.svg TypeResourceIdentifier]]
    fields: [[FieldContainer.svg FieldContainer]]
}
interface PaymentTransitionStateAction [[PaymentTransitionStateAction.svg]]  {
    action: String
    state: [[StateResourceIdentifier.svg StateResourceIdentifier]]
    force: Boolean
}
interface PaymentUpdate [[PaymentUpdate.svg]]  {
    version: Long
    actions: [[PaymentUpdateAction.svg List<PaymentUpdateAction>]]
}
PaymentUpdateAction --> PaymentAddInterfaceInteractionAction #blue;text:blue : "action : addInterfaceInteraction"
PaymentUpdateAction --> PaymentAddTransactionAction #blue;text:blue : "action : addTransaction"
PaymentUpdateAction --> PaymentChangeAmountPlannedAction #blue;text:blue : "action : changeAmountPlanned"
PaymentUpdateAction --> PaymentChangeTransactionInteractionIdAction #blue;text:blue : "action : changeTransactionInteractionId"
PaymentUpdateAction --> PaymentChangeTransactionStateAction #blue;text:blue : "action : changeTransactionState"
PaymentUpdateAction --> PaymentChangeTransactionTimestampAction #blue;text:blue : "action : changeTransactionTimestamp"
PaymentUpdateAction --> PaymentSetAmountPaidAction #blue;text:blue : "action : setAmountPaid"
PaymentUpdateAction --> PaymentSetAmountRefundedAction #blue;text:blue : "action : setAmountRefunded"
PaymentUpdateAction --> PaymentSetAnonymousIdAction #blue;text:blue : "action : setAnonymousId"
PaymentUpdateAction --> PaymentSetAuthorizationAction #blue;text:blue : "action : setAuthorization"
PaymentUpdateAction --> PaymentSetCustomFieldAction #blue;text:blue : "action : setCustomField"
PaymentUpdateAction --> PaymentSetCustomTypeAction #blue;text:blue : "action : setCustomType"
PaymentUpdateAction --> PaymentSetCustomerAction #blue;text:blue : "action : setCustomer"
PaymentUpdateAction --> PaymentSetExternalIdAction #blue;text:blue : "action : setExternalId"
PaymentUpdateAction --> PaymentSetInterfaceIdAction #blue;text:blue : "action : setInterfaceId"
PaymentUpdateAction --> PaymentSetKeyAction #blue;text:blue : "action : setKey"
PaymentUpdateAction --> PaymentSetMethodInfoInterfaceAction #blue;text:blue : "action : setMethodInfoInterface"
PaymentUpdateAction --> PaymentSetMethodInfoMethodAction #blue;text:blue : "action : setMethodInfoMethod"
PaymentUpdateAction --> PaymentSetMethodInfoNameAction #blue;text:blue : "action : setMethodInfoName"
PaymentUpdateAction --> PaymentSetStatusInterfaceCodeAction #blue;text:blue : "action : setStatusInterfaceCode"
PaymentUpdateAction --> PaymentSetStatusInterfaceTextAction #blue;text:blue : "action : setStatusInterfaceText"
PaymentUpdateAction --> PaymentSetTransactionCustomFieldAction #blue;text:blue : "action : setTransactionCustomField"
PaymentUpdateAction --> PaymentSetTransactionCustomTypeAction #blue;text:blue : "action : setTransactionCustomType"
PaymentUpdateAction --> PaymentTransitionStateAction #blue;text:blue : "action : transitionState"
PaymentUpdateAction --> PaymentUpdate #green;text:green : "actions"
@enduml
