@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface PriceTier [[PriceTier.svg]]  {
    minimumQuantity: Long
    value: [[TypedMoney.svg TypedMoney]]
}



interface Price [[Price.svg]]  {
    id: String
    key: String
    value: [[TypedMoney.svg TypedMoney]]
    country: String
    customerGroup: [[CustomerGroupReference.svg CustomerGroupReference]]
    channel: [[ChannelReference.svg ChannelReference]]
    validFrom: DateTime
    validUntil: DateTime
    discounted: [[DiscountedPrice.svg DiscountedPrice]]
    tiers: [[PriceTier.svg List<PriceTier>]]
    custom: [[CustomFields.svg CustomFields]]
}
interface StandalonePrice [[StandalonePrice.svg]]  {
    id: String
    version: Long
    createdAt: DateTime
    lastModifiedAt: DateTime
    lastModifiedBy: [[LastModifiedBy.svg LastModifiedBy]]
    createdBy: [[CreatedBy.svg CreatedBy]]
    key: String
    sku: String
    value: [[TypedMoney.svg TypedMoney]]
    country: String
    customerGroup: [[CustomerGroupReference.svg CustomerGroupReference]]
    channel: [[ChannelReference.svg ChannelReference]]
    validFrom: DateTime
    validUntil: DateTime
    tiers: [[PriceTier.svg List<PriceTier>]]
    discounted: [[DiscountedPrice.svg DiscountedPrice]]
    custom: [[CustomFields.svg CustomFields]]
    staged: [[StagedStandalonePrice.svg StagedStandalonePrice]]
    active: Boolean
}

PriceTier --> Price #green;text:green : "tiers"
PriceTier --> StandalonePrice #green;text:green : "tiers"
@enduml
