@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface Price [[Price.svg]]  {
    id: String
    key: String
    value: [[TypedMoney.svg TypedMoney]]
    country: String
    customerGroup: [[CustomerGroupReference.svg CustomerGroupReference]]
    channel: [[ChannelReference.svg ChannelReference]]
    validFrom: DateTime
    validUntil: DateTime
    discounted: [[DiscountedPrice.svg DiscountedPrice]]
    tiers: [[PriceTier.svg List<PriceTier>]]
    custom: [[CustomFields.svg CustomFields]]
}



interface ProductPricesSetMessage [[ProductPricesSetMessage.svg]]  {
    id: String
    version: Long
    createdAt: DateTime
    lastModifiedAt: DateTime
    lastModifiedBy: [[LastModifiedBy.svg LastModifiedBy]]
    createdBy: [[CreatedBy.svg CreatedBy]]
    sequenceNumber: Long
    resource: [[Reference.svg Reference]]
    resourceVersion: Long
    type: String
    resourceUserProvidedIdentifiers: [[UserProvidedIdentifiers.svg UserProvidedIdentifiers]]
    variantId: Long
    prices: [[Price.svg List<Price>]]
    staged: Boolean
}
interface ProductPricesSetMessagePayload [[ProductPricesSetMessagePayload.svg]]  {
    type: String
    variantId: Long
    prices: [[Price.svg List<Price>]]
    staged: Boolean
}
interface ProductVariant [[ProductVariant.svg]]  {
    id: Long
    sku: String
    key: String
    prices: [[Price.svg List<Price>]]
    attributes: [[Attribute.svg List<Attribute>]]
    price: [[Price.svg Price]]
    images: [[Image.svg List<Image>]]
    assets: [[Asset.svg List<Asset>]]
    availability: [[ProductVariantAvailability.svg ProductVariantAvailability]]
    isMatchingVariant: Boolean
    scopedPrice: [[ScopedPrice.svg ScopedPrice]]
    scopedPriceDiscounted: Boolean
}
interface LineItem [[LineItem.svg]]  {
    id: String
    productId: String
    productKey: String
    name: [[LocalizedString.svg LocalizedString]]
    productSlug: [[LocalizedString.svg LocalizedString]]
    productType: [[ProductTypeReference.svg ProductTypeReference]]
    variant: [[ProductVariant.svg ProductVariant]]
    price: [[Price.svg Price]]
    taxedPrice: [[TaxedItemPrice.svg TaxedItemPrice]]
    taxedPricePortions: [[MethodTaxedPrice.svg List<MethodTaxedPrice>]]
    totalPrice: [[TypedMoney.svg TypedMoney]]
    quantity: Long
    addedAt: DateTime
    state: [[ItemState.svg List<ItemState>]]
    taxRate: [[TaxRate.svg TaxRate]]
    perMethodTaxRate: [[MethodTaxRate.svg List<MethodTaxRate>]]
    supplyChannel: [[ChannelReference.svg ChannelReference]]
    distributionChannel: [[ChannelReference.svg ChannelReference]]
    discountedPricePerQuantity: [[DiscountedLineItemPriceForQuantity.svg List<DiscountedLineItemPriceForQuantity>]]
    priceMode: [[LineItemPriceMode.svg LineItemPriceMode]]
    lineItemMode: [[LineItemMode.svg LineItemMode]]
    custom: [[CustomFields.svg CustomFields]]
    inventoryMode: [[InventoryMode.svg InventoryMode]]
    shippingDetails: [[ItemShippingDetails.svg ItemShippingDetails]]
    lastModifiedAt: DateTime
}
interface DuplicatePriceKeyError [[DuplicatePriceKeyError.svg]]  {
    code: String
    message: String
    conflictingPrice: [[Price.svg Price]]
}
interface DuplicatePriceScopeError [[DuplicatePriceScopeError.svg]]  {
    code: String
    message: String
    conflictingPrice: [[Price.svg Price]]
}
interface OrderLineItemRemovedMessage [[OrderLineItemRemovedMessage.svg]]  {
    id: String
    version: Long
    createdAt: DateTime
    lastModifiedAt: DateTime
    lastModifiedBy: [[LastModifiedBy.svg LastModifiedBy]]
    createdBy: [[CreatedBy.svg CreatedBy]]
    sequenceNumber: Long
    resource: [[Reference.svg Reference]]
    resourceVersion: Long
    type: String
    resourceUserProvidedIdentifiers: [[UserProvidedIdentifiers.svg UserProvidedIdentifiers]]
    lineItemId: String
    removedQuantity: Long
    newQuantity: Long
    newState: [[ItemState.svg List<ItemState>]]
    newTotalPrice: [[CentPrecisionMoney.svg CentPrecisionMoney]]
    newTaxedPrice: [[TaxedItemPrice.svg TaxedItemPrice]]
    newPrice: [[Price.svg Price]]
    newShippingDetail: [[ItemShippingDetails.svg ItemShippingDetails]]
}
interface ProductPriceAddedMessage [[ProductPriceAddedMessage.svg]]  {
    id: String
    version: Long
    createdAt: DateTime
    lastModifiedAt: DateTime
    lastModifiedBy: [[LastModifiedBy.svg LastModifiedBy]]
    createdBy: [[CreatedBy.svg CreatedBy]]
    sequenceNumber: Long
    resource: [[Reference.svg Reference]]
    resourceVersion: Long
    type: String
    resourceUserProvidedIdentifiers: [[UserProvidedIdentifiers.svg UserProvidedIdentifiers]]
    variantId: Long
    price: [[Price.svg Price]]
    staged: Boolean
}
interface ProductPriceChangedMessage [[ProductPriceChangedMessage.svg]]  {
    id: String
    version: Long
    createdAt: DateTime
    lastModifiedAt: DateTime
    lastModifiedBy: [[LastModifiedBy.svg LastModifiedBy]]
    createdBy: [[CreatedBy.svg CreatedBy]]
    sequenceNumber: Long
    resource: [[Reference.svg Reference]]
    resourceVersion: Long
    type: String
    resourceUserProvidedIdentifiers: [[UserProvidedIdentifiers.svg UserProvidedIdentifiers]]
    variantId: Long
    oldPrice: [[Price.svg Price]]
    newPrice: [[Price.svg Price]]
    staged: Boolean
    oldStagedPrice: [[Price.svg Price]]
}
interface ProductPriceRemovedMessage [[ProductPriceRemovedMessage.svg]]  {
    id: String
    version: Long
    createdAt: DateTime
    lastModifiedAt: DateTime
    lastModifiedBy: [[LastModifiedBy.svg LastModifiedBy]]
    createdBy: [[CreatedBy.svg CreatedBy]]
    sequenceNumber: Long
    resource: [[Reference.svg Reference]]
    resourceVersion: Long
    type: String
    resourceUserProvidedIdentifiers: [[UserProvidedIdentifiers.svg UserProvidedIdentifiers]]
    variantId: Long
    price: [[Price.svg Price]]
    staged: Boolean
}
interface OrderLineItemRemovedMessagePayload [[OrderLineItemRemovedMessagePayload.svg]]  {
    type: String
    lineItemId: String
    removedQuantity: Long
    newQuantity: Long
    newState: [[ItemState.svg List<ItemState>]]
    newTotalPrice: [[CentPrecisionMoney.svg CentPrecisionMoney]]
    newTaxedPrice: [[TaxedItemPrice.svg TaxedItemPrice]]
    newPrice: [[Price.svg Price]]
    newShippingDetail: [[ItemShippingDetails.svg ItemShippingDetails]]
}
interface ProductPriceAddedMessagePayload [[ProductPriceAddedMessagePayload.svg]]  {
    type: String
    variantId: Long
    price: [[Price.svg Price]]
    staged: Boolean
}
interface ProductPriceChangedMessagePayload [[ProductPriceChangedMessagePayload.svg]]  {
    type: String
    variantId: Long
    oldPrice: [[Price.svg Price]]
    newPrice: [[Price.svg Price]]
    staged: Boolean
    oldStagedPrice: [[Price.svg Price]]
}
interface ProductPriceRemovedMessagePayload [[ProductPriceRemovedMessagePayload.svg]]  {
    type: String
    variantId: Long
    price: [[Price.svg Price]]
    staged: Boolean
}

Price --> ProductPricesSetMessage #green;text:green : "prices"
Price --> ProductPricesSetMessagePayload #green;text:green : "prices"
Price --> ProductVariant #green;text:green : "prices"
Price --> LineItem #green;text:green : "price"
Price --> DuplicatePriceKeyError #green;text:green : "conflictingPrice"
Price --> DuplicatePriceScopeError #green;text:green : "conflictingPrice"
Price --> OrderLineItemRemovedMessage #green;text:green : "newPrice"
Price --> ProductPriceAddedMessage #green;text:green : "price"
Price --> ProductPriceChangedMessage #green;text:green : "oldPrice"
Price --> ProductPriceChangedMessage #green;text:green : "newPrice"
Price --> ProductPriceChangedMessage #green;text:green : "oldStagedPrice"
Price --> ProductPriceRemovedMessage #green;text:green : "price"
Price --> OrderLineItemRemovedMessagePayload #green;text:green : "newPrice"
Price --> ProductPriceAddedMessagePayload #green;text:green : "price"
Price --> ProductPriceChangedMessagePayload #green;text:green : "oldPrice"
Price --> ProductPriceChangedMessagePayload #green;text:green : "newPrice"
Price --> ProductPriceChangedMessagePayload #green;text:green : "oldStagedPrice"
Price --> ProductPriceRemovedMessagePayload #green;text:green : "price"
Price --> ProductVariant #green;text:green : "price"
@enduml
