@startuml

hide methods
enum ProductSelectionTypeEnum {
    INDIVIDUAL
}
interface ProductSelection [[ProductSelection.svg]]  {
    id: String
    version: Long
    createdAt: DateTime
    lastModifiedAt: DateTime
    lastModifiedBy: [[LastModifiedBy.svg LastModifiedBy]]
    createdBy: [[CreatedBy.svg CreatedBy]]
    key: String
    name: [[LocalizedString.svg LocalizedString]]
    productCount: Integer
    type: [[ProductSelectionTypeEnum.svg ProductSelectionTypeEnum]]
    custom: [[CustomFields.svg CustomFields]]
}
ProductSelectionTypeEnum --> ProductSelection #green;text:green : "type"
@enduml
