@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface ProductTypeChangeInputHintAction [[ProductTypeChangeInputHintAction.svg]] extends ProductTypeUpdateAction {
    action: String
    attributeName: String
    newValue: [[TextInputHint.svg TextInputHint]]
}
interface ProductTypeUpdateAction [[ProductTypeUpdateAction.svg]]  {
    action: String
}





@enduml
