@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface ProductReference [[ProductReference.svg]] extends Reference {
    typeId: [[ReferenceTypeId.svg ReferenceTypeId]]
    id: String
    obj: [[Product.svg Product]]
}
interface Reference [[Reference.svg]]  {
    typeId: [[ReferenceTypeId.svg ReferenceTypeId]]
    id: String
}


interface Review [[Review.svg]]  {
    id: String
    version: Long
    createdAt: DateTime
    lastModifiedAt: DateTime
    lastModifiedBy: [[LastModifiedBy.svg LastModifiedBy]]
    createdBy: [[CreatedBy.svg CreatedBy]]
    key: String
    uniquenessValue: String
    locale: String
    authorName: String
    title: String
    text: String
    target: [[Object.svg Object]]
    includedInStatistics: Boolean
    rating: Integer
    state: [[StateReference.svg StateReference]]
    customer: [[CustomerReference.svg CustomerReference]]
    custom: [[CustomFields.svg CustomFields]]
}
interface CartDiscountValueGiftLineItem [[CartDiscountValueGiftLineItem.svg]]  {
    type: String
    product: [[ProductReference.svg ProductReference]]
    variantId: Long
    supplyChannel: [[ChannelReference.svg ChannelReference]]
    distributionChannel: [[ChannelReference.svg ChannelReference]]
}
interface ProductAssignmentMissingError [[ProductAssignmentMissingError.svg]]  {
    code: String
    message: String
    product: [[ProductReference.svg ProductReference]]
}
interface ProductPresentWithDifferentVariantSelectionError [[ProductPresentWithDifferentVariantSelectionError.svg]]  {
    code: String
    message: String
    product: [[ProductReference.svg ProductReference]]
    existingVariantSelection: [[ProductVariantSelection.svg ProductVariantSelection]]
}
interface GraphQLProductAssignmentMissingError [[GraphQLProductAssignmentMissingError.svg]]  {
    code: String
    product: [[ProductReference.svg ProductReference]]
}
interface GraphQLProductPresentWithDifferentVariantSelectionError [[GraphQLProductPresentWithDifferentVariantSelectionError.svg]]  {
    code: String
    product: [[ProductReference.svg ProductReference]]
    existingVariantSelection: [[ProductVariantSelection.svg ProductVariantSelection]]
}
interface ProductSelectionProductAddedMessage [[ProductSelectionProductAddedMessage.svg]]  {
    id: String
    version: Long
    createdAt: DateTime
    lastModifiedAt: DateTime
    lastModifiedBy: [[LastModifiedBy.svg LastModifiedBy]]
    createdBy: [[CreatedBy.svg CreatedBy]]
    sequenceNumber: Long
    resource: [[Reference.svg Reference]]
    resourceVersion: Long
    type: String
    resourceUserProvidedIdentifiers: [[UserProvidedIdentifiers.svg UserProvidedIdentifiers]]
    product: [[ProductReference.svg ProductReference]]
    variantSelection: [[ProductVariantSelection.svg ProductVariantSelection]]
}
interface ProductSelectionProductExcludedMessage [[ProductSelectionProductExcludedMessage.svg]]  {
    id: String
    version: Long
    createdAt: DateTime
    lastModifiedAt: DateTime
    lastModifiedBy: [[LastModifiedBy.svg LastModifiedBy]]
    createdBy: [[CreatedBy.svg CreatedBy]]
    sequenceNumber: Long
    resource: [[Reference.svg Reference]]
    resourceVersion: Long
    type: String
    resourceUserProvidedIdentifiers: [[UserProvidedIdentifiers.svg UserProvidedIdentifiers]]
    product: [[ProductReference.svg ProductReference]]
    variantExclusion: [[ProductVariantExclusion.svg ProductVariantExclusion]]
}
interface ProductSelectionProductRemovedMessage [[ProductSelectionProductRemovedMessage.svg]]  {
    id: String
    version: Long
    createdAt: DateTime
    lastModifiedAt: DateTime
    lastModifiedBy: [[LastModifiedBy.svg LastModifiedBy]]
    createdBy: [[CreatedBy.svg CreatedBy]]
    sequenceNumber: Long
    resource: [[Reference.svg Reference]]
    resourceVersion: Long
    type: String
    resourceUserProvidedIdentifiers: [[UserProvidedIdentifiers.svg UserProvidedIdentifiers]]
    product: [[ProductReference.svg ProductReference]]
}
interface ProductSelectionVariantExclusionChangedMessage [[ProductSelectionVariantExclusionChangedMessage.svg]]  {
    id: String
    version: Long
    createdAt: DateTime
    lastModifiedAt: DateTime
    lastModifiedBy: [[LastModifiedBy.svg LastModifiedBy]]
    createdBy: [[CreatedBy.svg CreatedBy]]
    sequenceNumber: Long
    resource: [[Reference.svg Reference]]
    resourceVersion: Long
    type: String
    resourceUserProvidedIdentifiers: [[UserProvidedIdentifiers.svg UserProvidedIdentifiers]]
    product: [[ProductReference.svg ProductReference]]
    oldVariantExclusion: [[ProductVariantExclusion.svg ProductVariantExclusion]]
    newVariantExclusion: [[ProductVariantExclusion.svg ProductVariantExclusion]]
}
interface ProductSelectionVariantSelectionChangedMessage [[ProductSelectionVariantSelectionChangedMessage.svg]]  {
    id: String
    version: Long
    createdAt: DateTime
    lastModifiedAt: DateTime
    lastModifiedBy: [[LastModifiedBy.svg LastModifiedBy]]
    createdBy: [[CreatedBy.svg CreatedBy]]
    sequenceNumber: Long
    resource: [[Reference.svg Reference]]
    resourceVersion: Long
    type: String
    resourceUserProvidedIdentifiers: [[UserProvidedIdentifiers.svg UserProvidedIdentifiers]]
    product: [[ProductReference.svg ProductReference]]
    oldVariantSelection: [[ProductVariantSelection.svg ProductVariantSelection]]
    newVariantSelection: [[ProductVariantSelection.svg ProductVariantSelection]]
}
interface ProductSelectionProductAddedMessagePayload [[ProductSelectionProductAddedMessagePayload.svg]]  {
    type: String
    product: [[ProductReference.svg ProductReference]]
    variantSelection: [[ProductVariantSelection.svg ProductVariantSelection]]
}
interface ProductSelectionProductExcludedMessagePayload [[ProductSelectionProductExcludedMessagePayload.svg]]  {
    type: String
    product: [[ProductReference.svg ProductReference]]
    variantExclusion: [[ProductVariantExclusion.svg ProductVariantExclusion]]
}
interface ProductSelectionProductRemovedMessagePayload [[ProductSelectionProductRemovedMessagePayload.svg]]  {
    type: String
    product: [[ProductReference.svg ProductReference]]
}
interface ProductSelectionVariantExclusionChangedMessagePayload [[ProductSelectionVariantExclusionChangedMessagePayload.svg]]  {
    type: String
    product: [[ProductReference.svg ProductReference]]
    oldVariantExclusion: [[ProductVariantExclusion.svg ProductVariantExclusion]]
    newVariantExclusion: [[ProductVariantExclusion.svg ProductVariantExclusion]]
}
interface ProductSelectionVariantSelectionChangedMessagePayload [[ProductSelectionVariantSelectionChangedMessagePayload.svg]]  {
    type: String
    product: [[ProductReference.svg ProductReference]]
    oldVariantSelection: [[ProductVariantSelection.svg ProductVariantSelection]]
    newVariantSelection: [[ProductVariantSelection.svg ProductVariantSelection]]
}
interface AssignedProductReference [[AssignedProductReference.svg]]  {
    product: [[ProductReference.svg ProductReference]]
    variantSelection: [[ProductVariantSelection.svg ProductVariantSelection]]
    variantExclusion: [[ProductVariantExclusion.svg ProductVariantExclusion]]
}
interface ProductSelectionAssignment [[ProductSelectionAssignment.svg]]  {
    product: [[ProductReference.svg ProductReference]]
    productSelection: [[ProductSelectionReference.svg ProductSelectionReference]]
    variantSelection: [[ProductVariantSelection.svg ProductVariantSelection]]
    variantExclusion: [[ProductVariantExclusion.svg ProductVariantExclusion]]
}

ProductReference --> Review #green;text:green : "target"
ProductReference --> CartDiscountValueGiftLineItem #green;text:green : "product"
ProductReference --> ProductAssignmentMissingError #green;text:green : "product"
ProductReference --> ProductPresentWithDifferentVariantSelectionError #green;text:green : "product"
ProductReference --> GraphQLProductAssignmentMissingError #green;text:green : "product"
ProductReference --> GraphQLProductPresentWithDifferentVariantSelectionError #green;text:green : "product"
ProductReference --> ProductSelectionProductAddedMessage #green;text:green : "product"
ProductReference --> ProductSelectionProductExcludedMessage #green;text:green : "product"
ProductReference --> ProductSelectionProductRemovedMessage #green;text:green : "product"
ProductReference --> ProductSelectionVariantExclusionChangedMessage #green;text:green : "product"
ProductReference --> ProductSelectionVariantSelectionChangedMessage #green;text:green : "product"
ProductReference --> ProductSelectionProductAddedMessagePayload #green;text:green : "product"
ProductReference --> ProductSelectionProductExcludedMessagePayload #green;text:green : "product"
ProductReference --> ProductSelectionProductRemovedMessagePayload #green;text:green : "product"
ProductReference --> ProductSelectionVariantExclusionChangedMessagePayload #green;text:green : "product"
ProductReference --> ProductSelectionVariantSelectionChangedMessagePayload #green;text:green : "product"
ProductReference --> AssignedProductReference #green;text:green : "product"
ProductReference --> ProductSelectionAssignment #green;text:green : "product"
@enduml
