@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface ProductTailoringUpdateAction [[ProductTailoringUpdateAction.svg]]  {
    action: String
}


interface ProductTailoringAddAssetAction [[ProductTailoringAddAssetAction.svg]]  {
    action: String
    variantId: Long
    sku: String
    staged: Boolean
    asset: [[AssetDraft.svg AssetDraft]]
    position: Integer
}
interface ProductTailoringAddExternalImageAction [[ProductTailoringAddExternalImageAction.svg]]  {
    action: String
    variantId: Long
    sku: String
    image: [[Image.svg Image]]
    staged: Boolean
}
interface ProductTailoringAddVariantAction [[ProductTailoringAddVariantAction.svg]]  {
    action: String
    id: Long
    sku: String
    images: [[Image.svg List<Image>]]
    assets: [[AssetDraft.svg List<AssetDraft>]]
    staged: Boolean
}
interface ProductTailoringChangeAssetNameAction [[ProductTailoringChangeAssetNameAction.svg]]  {
    action: String
    variantId: Long
    sku: String
    staged: Boolean
    assetId: String
    assetKey: String
    name: [[LocalizedString.svg LocalizedString]]
}
interface ProductTailoringChangeAssetOrderAction [[ProductTailoringChangeAssetOrderAction.svg]]  {
    action: String
    variantId: Long
    sku: String
    staged: Boolean
    assetOrder: [[String.svg List<String>]]
}
interface ProductTailoringMoveImageToPositionAction [[ProductTailoringMoveImageToPositionAction.svg]]  {
    action: String
    variantId: Long
    sku: String
    imageUrl: String
    position: Long
    staged: Boolean
}
interface ProductTailoringPublishAction [[ProductTailoringPublishAction.svg]]  {
    action: String
}
interface ProductTailoringRemoveAssetAction [[ProductTailoringRemoveAssetAction.svg]]  {
    action: String
    variantId: Long
    sku: String
    staged: Boolean
    assetId: String
    assetKey: String
}
interface ProductTailoringRemoveImageAction [[ProductTailoringRemoveImageAction.svg]]  {
    action: String
    variantId: Long
    sku: String
    imageUrl: String
    staged: Boolean
}
interface ProductTailoringRemoveVariantAction [[ProductTailoringRemoveVariantAction.svg]]  {
    action: String
    id: Long
    sku: String
    staged: Boolean
}
interface ProductTailoringSetAssetCustomFieldAction [[ProductTailoringSetAssetCustomFieldAction.svg]]  {
    action: String
    variantId: Long
    sku: String
    staged: Boolean
    assetId: String
    assetKey: String
    name: String
    value: [[Object.svg Object]]
}
interface ProductTailoringSetAssetCustomTypeAction [[ProductTailoringSetAssetCustomTypeAction.svg]]  {
    action: String
    variantId: Long
    sku: String
    staged: Boolean
    assetId: String
    assetKey: String
    type: [[TypeResourceIdentifier.svg TypeResourceIdentifier]]
    fields: [[FieldContainer.svg FieldContainer]]
}
interface ProductTailoringSetAssetDescriptionAction [[ProductTailoringSetAssetDescriptionAction.svg]]  {
    action: String
    variantId: Long
    sku: String
    staged: Boolean
    assetId: String
    assetKey: String
    description: [[LocalizedString.svg LocalizedString]]
}
interface ProductTailoringSetAssetKeyAction [[ProductTailoringSetAssetKeyAction.svg]]  {
    action: String
    variantId: Long
    sku: String
    staged: Boolean
    assetId: String
    assetKey: String
}
interface ProductTailoringSetAssetSourcesAction [[ProductTailoringSetAssetSourcesAction.svg]]  {
    action: String
    variantId: Long
    sku: String
    staged: Boolean
    assetId: String
    assetKey: String
    sources: [[AssetSource.svg List<AssetSource>]]
}
interface ProductTailoringSetAssetTagsAction [[ProductTailoringSetAssetTagsAction.svg]]  {
    action: String
    variantId: Long
    sku: String
    staged: Boolean
    assetId: String
    assetKey: String
    tags: [[String.svg List<String>]]
}
interface ProductTailoringSetDescriptionAction [[ProductTailoringSetDescriptionAction.svg]]  {
    action: String
    description: [[LocalizedString.svg LocalizedString]]
    staged: Boolean
}
interface ProductTailoringSetExternalImagesAction [[ProductTailoringSetExternalImagesAction.svg]]  {
    action: String
    variantId: Long
    sku: String
    images: [[Image.svg List<Image>]]
    staged: Boolean
}
interface ProductTailoringSetImageLabelAction [[ProductTailoringSetImageLabelAction.svg]]  {
    action: String
    sku: String
    variantId: Long
    imageUrl: String
    label: String
    staged: Boolean
}
interface ProductTailoringSetMetaAttributesAction [[ProductTailoringSetMetaAttributesAction.svg]]  {
    action: String
    metaTitle: [[LocalizedString.svg LocalizedString]]
    metaDescription: [[LocalizedString.svg LocalizedString]]
    metaKeywords: [[LocalizedString.svg LocalizedString]]
    staged: Boolean
}
interface ProductTailoringSetMetaDescriptionAction [[ProductTailoringSetMetaDescriptionAction.svg]]  {
    action: String
    metaDescription: [[LocalizedString.svg LocalizedString]]
    staged: Boolean
}
interface ProductTailoringSetMetaKeywordsAction [[ProductTailoringSetMetaKeywordsAction.svg]]  {
    action: String
    metaKeywords: [[LocalizedString.svg LocalizedString]]
    staged: Boolean
}
interface ProductTailoringSetMetaTitleAction [[ProductTailoringSetMetaTitleAction.svg]]  {
    action: String
    metaTitle: [[LocalizedString.svg LocalizedString]]
    staged: Boolean
}
interface ProductTailoringSetNameAction [[ProductTailoringSetNameAction.svg]]  {
    action: String
    name: [[LocalizedString.svg LocalizedString]]
    staged: Boolean
}
interface ProductTailoringSetSlugAction [[ProductTailoringSetSlugAction.svg]]  {
    action: String
    slug: [[LocalizedString.svg LocalizedString]]
    staged: Boolean
}
interface ProductTailoringUnpublishAction [[ProductTailoringUnpublishAction.svg]]  {
    action: String
}
interface ProductTailoringUpdate [[ProductTailoringUpdate.svg]]  {
    version: Long
    actions: [[ProductTailoringUpdateAction.svg List<ProductTailoringUpdateAction>]]
}
ProductTailoringUpdateAction --> ProductTailoringAddAssetAction #blue;text:blue : "action : addAsset"
ProductTailoringUpdateAction --> ProductTailoringAddExternalImageAction #blue;text:blue : "action : addExternalImage"
ProductTailoringUpdateAction --> ProductTailoringAddVariantAction #blue;text:blue : "action : addVariant"
ProductTailoringUpdateAction --> ProductTailoringChangeAssetNameAction #blue;text:blue : "action : changeAssetName"
ProductTailoringUpdateAction --> ProductTailoringChangeAssetOrderAction #blue;text:blue : "action : changeAssetOrder"
ProductTailoringUpdateAction --> ProductTailoringMoveImageToPositionAction #blue;text:blue : "action : moveImageToPosition"
ProductTailoringUpdateAction --> ProductTailoringPublishAction #blue;text:blue : "action : publish"
ProductTailoringUpdateAction --> ProductTailoringRemoveAssetAction #blue;text:blue : "action : removeAsset"
ProductTailoringUpdateAction --> ProductTailoringRemoveImageAction #blue;text:blue : "action : removeImage"
ProductTailoringUpdateAction --> ProductTailoringRemoveVariantAction #blue;text:blue : "action : removeVariant"
ProductTailoringUpdateAction --> ProductTailoringSetAssetCustomFieldAction #blue;text:blue : "action : setAssetCustomField"
ProductTailoringUpdateAction --> ProductTailoringSetAssetCustomTypeAction #blue;text:blue : "action : setAssetCustomType"
ProductTailoringUpdateAction --> ProductTailoringSetAssetDescriptionAction #blue;text:blue : "action : setAssetDescription"
ProductTailoringUpdateAction --> ProductTailoringSetAssetKeyAction #blue;text:blue : "action : setAssetKey"
ProductTailoringUpdateAction --> ProductTailoringSetAssetSourcesAction #blue;text:blue : "action : setAssetSources"
ProductTailoringUpdateAction --> ProductTailoringSetAssetTagsAction #blue;text:blue : "action : setAssetTags"
ProductTailoringUpdateAction --> ProductTailoringSetDescriptionAction #blue;text:blue : "action : setDescription"
ProductTailoringUpdateAction --> ProductTailoringSetExternalImagesAction #blue;text:blue : "action : setImages"
ProductTailoringUpdateAction --> ProductTailoringSetImageLabelAction #blue;text:blue : "action : setImageLabel"
ProductTailoringUpdateAction --> ProductTailoringSetMetaAttributesAction #blue;text:blue : "action : setMetaAttributes"
ProductTailoringUpdateAction --> ProductTailoringSetMetaDescriptionAction #blue;text:blue : "action : setMetaDescription"
ProductTailoringUpdateAction --> ProductTailoringSetMetaKeywordsAction #blue;text:blue : "action : setMetaKeywords"
ProductTailoringUpdateAction --> ProductTailoringSetMetaTitleAction #blue;text:blue : "action : setMetaTitle"
ProductTailoringUpdateAction --> ProductTailoringSetNameAction #blue;text:blue : "action : setName"
ProductTailoringUpdateAction --> ProductTailoringSetSlugAction #blue;text:blue : "action : setSlug"
ProductTailoringUpdateAction --> ProductTailoringUnpublishAction #blue;text:blue : "action : unpublish"
ProductTailoringUpdateAction --> ProductTailoringUpdate #green;text:green : "actions"
@enduml
