@startuml

hide methods
enum ProductSearchFacetScopeEnum {
    ALL
    QUERY
}
interface ProductSearchFacetCountValue [[ProductSearchFacetCountValue.svg]]  {
    name: String
    scope: [[ProductSearchFacetScopeEnum.svg ProductSearchFacetScopeEnum]]
    filter: [[SearchQuery.svg SearchQuery]]
    level: [[ProductSearchFacetCountLevelEnum.svg ProductSearchFacetCountLevelEnum]]
}
interface ProductSearchFacetDistinctValue [[ProductSearchFacetDistinctValue.svg]]  {
    name: String
    scope: [[ProductSearchFacetScopeEnum.svg ProductSearchFacetScopeEnum]]
    filter: [[SearchQuery.svg SearchQuery]]
    level: [[ProductSearchFacetCountLevelEnum.svg ProductSearchFacetCountLevelEnum]]
    field: String
    includes: [[String.svg List<String>]]
    sort: [[ProductSearchFacetDistinctBucketSortExpression.svg ProductSearchFacetDistinctBucketSortExpression]]
    limit: Integer
    language: String
    fieldType: [[SearchFieldType.svg SearchFieldType]]
    missing: String
}
interface ProductSearchFacetRangesValue [[ProductSearchFacetRangesValue.svg]]  {
    name: String
    scope: [[ProductSearchFacetScopeEnum.svg ProductSearchFacetScopeEnum]]
    filter: [[SearchQuery.svg SearchQuery]]
    level: [[ProductSearchFacetCountLevelEnum.svg ProductSearchFacetCountLevelEnum]]
    field: String
    ranges: [[ProductSearchFacetRangesFacetRange.svg List<ProductSearchFacetRangesFacetRange>]]
    language: String
    fieldType: [[SearchFieldType.svg SearchFieldType]]
}
interface ProductSearchFacetStatsValue [[ProductSearchFacetStatsValue.svg]]  {
    name: String
    scope: [[ProductSearchFacetScopeEnum.svg ProductSearchFacetScopeEnum]]
    filter: [[SearchQuery.svg SearchQuery]]
    field: String
    fieldType: [[SearchFieldType.svg SearchFieldType]]
}
ProductSearchFacetScopeEnum --> ProductSearchFacetCountValue #green;text:green : "scope"
ProductSearchFacetScopeEnum --> ProductSearchFacetDistinctValue #green;text:green : "scope"
ProductSearchFacetScopeEnum --> ProductSearchFacetRangesValue #green;text:green : "scope"
ProductSearchFacetScopeEnum --> ProductSearchFacetStatsValue #green;text:green : "scope"
@enduml
