@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface ProductSearchCompoundExpression [[ProductSearchCompoundExpression.svg]] extends ProductSearchQuery {
}
interface ProductSearchQuery [[ProductSearchQuery.svg]]  {
}
interface ProductSearchAndExpression [[ProductSearchAndExpression.svg]] extends ProductSearchCompoundExpression {
    and: [[ProductSearchQuery.svg List<ProductSearchQuery>]]
}
interface ProductSearchFilterExpression [[ProductSearchFilterExpression.svg]] extends ProductSearchCompoundExpression {
    filter: [[ProductSearchQueryExpression.svg List<ProductSearchQueryExpression>]]
}
interface ProductSearchNotExpression [[ProductSearchNotExpression.svg]] extends ProductSearchCompoundExpression {
    not: [[ProductSearchQuery.svg List<ProductSearchQuery>]]
}
interface ProductSearchOrExpression [[ProductSearchOrExpression.svg]] extends ProductSearchCompoundExpression {
    or: [[ProductSearchQuery.svg List<ProductSearchQuery>]]
}




@enduml
