@startuml

hide methods
enum ProductSearchIndexingMode {
    PRODUCT_PROJECTIONS_SEARCH
    PRODUCTS_SEARCH
}
interface ProjectChangeProductSearchIndexingEnabledAction [[ProjectChangeProductSearchIndexingEnabledAction.svg]]  {
    action: String
    enabled: Boolean
    mode: [[ProductSearchIndexingMode.svg ProductSearchIndexingMode]]
}
ProductSearchIndexingMode --> ProjectChangeProductSearchIndexingEnabledAction #green;text:green : "mode"
@enduml
