@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface ProductVariantChannelAvailability [[ProductVariantChannelAvailability.svg]]  {
    isOnStock: Boolean
    restockableInDays: Long
    availableQuantity: Long
    id: String
    version: Long
}



interface ProductVariantChannelAvailabilityMap [[ProductVariantChannelAvailabilityMap.svg]]  {
}

ProductVariantChannelAvailability --> ProductVariantChannelAvailabilityMap #green;text:green : "/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/"
@enduml
