@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface ProductVariantSelectionInclusion [[ProductVariantSelectionInclusion.svg]] extends ProductVariantSelection {
    type: [[ProductVariantSelectionTypeEnum.svg ProductVariantSelectionTypeEnum]]
    skus: [[String.svg List<String>]]
}
interface ProductVariantSelection [[ProductVariantSelection.svg]]  {
    type: [[ProductVariantSelectionTypeEnum.svg ProductVariantSelectionTypeEnum]]
}





@enduml
