@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface ProductLegacySetSkuAction [[ProductLegacySetSkuAction.svg]] extends ProductUpdateAction {
    action: String
    sku: String
    variantId: Integer
}
interface ProductUpdateAction [[ProductUpdateAction.svg]]  {
    action: String
}





@enduml
