@startuml

hide methods
enum ProductSearchFacetEnumScope {
    ALL
    QUERY
}
interface ProductSearchFacetCountValue [[ProductSearchFacetCountValue.svg]]  {
    name: String
    scope: [[ProductSearchFacetEnumScope.svg ProductSearchFacetEnumScope]]
    filter: [[ProductSearchQuery.svg ProductSearchQuery]]
    level: [[ProductSearchFacetEnumCount.svg ProductSearchFacetEnumCount]]
}
interface ProductSearchFacetDistinctValue [[ProductSearchFacetDistinctValue.svg]]  {
    name: String
    scope: [[ProductSearchFacetEnumScope.svg ProductSearchFacetEnumScope]]
    filter: [[ProductSearchQuery.svg ProductSearchQuery]]
    count: [[ProductSearchFacetEnumCount.svg ProductSearchFacetEnumCount]]
    field: String
    includes: [[String.svg List<String>]]
    startsWith: [[ProductSearchFacetDistinctStartsWith.svg ProductSearchFacetDistinctStartsWith]]
    sort: [[ProductSearchFacetDistinctBucketSortExpression.svg ProductSearchFacetDistinctBucketSortExpression]]
    size: Integer
    language: String
    attributeType: [[ProductSearchAttributeType.svg ProductSearchAttributeType]]
    missing: String
}
interface ProductSearchFacetRangesValue [[ProductSearchFacetRangesValue.svg]]  {
    name: String
    scope: [[ProductSearchFacetEnumScope.svg ProductSearchFacetEnumScope]]
    filter: [[ProductSearchQuery.svg ProductSearchQuery]]
    count: [[ProductSearchFacetEnumCount.svg ProductSearchFacetEnumCount]]
    field: String
    ranges: [[ProductSearchFacetRangesFacetRange.svg List<ProductSearchFacetRangesFacetRange>]]
    language: String
    attributeType: [[ProductSearchAttributeType.svg ProductSearchAttributeType]]
}
ProductSearchFacetEnumScope --> ProductSearchFacetCountValue #green;text:green : "scope"
ProductSearchFacetEnumScope --> ProductSearchFacetDistinctValue #green;text:green : "scope"
ProductSearchFacetEnumScope --> ProductSearchFacetRangesValue #green;text:green : "scope"
@enduml
