@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface ProductDiscountUpdateAction [[ProductDiscountUpdateAction.svg]]  {
    action: String
}


interface ProductDiscountChangeIsActiveAction [[ProductDiscountChangeIsActiveAction.svg]]  {
    action: String
    isActive: Boolean
}
interface ProductDiscountChangeNameAction [[ProductDiscountChangeNameAction.svg]]  {
    action: String
    name: [[LocalizedString.svg LocalizedString]]
}
interface ProductDiscountChangePredicateAction [[ProductDiscountChangePredicateAction.svg]]  {
    action: String
    predicate: String
}
interface ProductDiscountChangeSortOrderAction [[ProductDiscountChangeSortOrderAction.svg]]  {
    action: String
    sortOrder: String
}
interface ProductDiscountChangeValueAction [[ProductDiscountChangeValueAction.svg]]  {
    action: String
    value: [[ProductDiscountValueDraft.svg ProductDiscountValueDraft]]
}
interface ProductDiscountSetDescriptionAction [[ProductDiscountSetDescriptionAction.svg]]  {
    action: String
    description: [[LocalizedString.svg LocalizedString]]
}
interface ProductDiscountSetKeyAction [[ProductDiscountSetKeyAction.svg]]  {
    action: String
    key: String
}
interface ProductDiscountSetValidFromAction [[ProductDiscountSetValidFromAction.svg]]  {
    action: String
    validFrom: DateTime
}
interface ProductDiscountSetValidFromAndUntilAction [[ProductDiscountSetValidFromAndUntilAction.svg]]  {
    action: String
    validFrom: DateTime
    validUntil: DateTime
}
interface ProductDiscountSetValidUntilAction [[ProductDiscountSetValidUntilAction.svg]]  {
    action: String
    validUntil: DateTime
}
interface ProductDiscountUpdate [[ProductDiscountUpdate.svg]]  {
    version: Long
    actions: [[ProductDiscountUpdateAction.svg List<ProductDiscountUpdateAction>]]
}
ProductDiscountUpdateAction --> ProductDiscountChangeIsActiveAction #blue;text:blue : "action : changeIsActive"
ProductDiscountUpdateAction --> ProductDiscountChangeNameAction #blue;text:blue : "action : changeName"
ProductDiscountUpdateAction --> ProductDiscountChangePredicateAction #blue;text:blue : "action : changePredicate"
ProductDiscountUpdateAction --> ProductDiscountChangeSortOrderAction #blue;text:blue : "action : changeSortOrder"
ProductDiscountUpdateAction --> ProductDiscountChangeValueAction #blue;text:blue : "action : changeValue"
ProductDiscountUpdateAction --> ProductDiscountSetDescriptionAction #blue;text:blue : "action : setDescription"
ProductDiscountUpdateAction --> ProductDiscountSetKeyAction #blue;text:blue : "action : setKey"
ProductDiscountUpdateAction --> ProductDiscountSetValidFromAction #blue;text:blue : "action : setValidFrom"
ProductDiscountUpdateAction --> ProductDiscountSetValidFromAndUntilAction #blue;text:blue : "action : setValidFromAndUntil"
ProductDiscountUpdateAction --> ProductDiscountSetValidUntilAction #blue;text:blue : "action : setValidUntil"
ProductDiscountUpdateAction --> ProductDiscountUpdate #green;text:green : "actions"
@enduml
