@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface ProductSelectionUpdateAction [[ProductSelectionUpdateAction.svg]]  {
    action: String
}


interface ProductSelectionAddProductAction [[ProductSelectionAddProductAction.svg]]  {
    action: String
    product: [[ProductResourceIdentifier.svg ProductResourceIdentifier]]
    variantSelection: [[ProductVariantSelection.svg ProductVariantSelection]]
}
interface ProductSelectionChangeNameAction [[ProductSelectionChangeNameAction.svg]]  {
    action: String
    name: [[LocalizedString.svg LocalizedString]]
}
interface ProductSelectionExcludeProductAction [[ProductSelectionExcludeProductAction.svg]]  {
    action: String
    product: [[ProductResourceIdentifier.svg ProductResourceIdentifier]]
    variantExclusion: [[ProductVariantExclusion.svg ProductVariantExclusion]]
}
interface ProductSelectionRemoveProductAction [[ProductSelectionRemoveProductAction.svg]]  {
    action: String
    product: [[ProductResourceIdentifier.svg ProductResourceIdentifier]]
}
interface ProductSelectionSetCustomFieldAction [[ProductSelectionSetCustomFieldAction.svg]]  {
    action: String
    name: String
    value: [[Object.svg Object]]
}
interface ProductSelectionSetCustomTypeAction [[ProductSelectionSetCustomTypeAction.svg]]  {
    action: String
    type: [[TypeResourceIdentifier.svg TypeResourceIdentifier]]
    fields: [[FieldContainer.svg FieldContainer]]
}
interface ProductSelectionSetKeyAction [[ProductSelectionSetKeyAction.svg]]  {
    action: String
    key: String
}
interface ProductSelectionSetVariantExclusionAction [[ProductSelectionSetVariantExclusionAction.svg]]  {
    action: String
    product: [[ProductResourceIdentifier.svg ProductResourceIdentifier]]
    variantExclusion: [[ProductVariantExclusion.svg ProductVariantExclusion]]
}
interface ProductSelectionSetVariantSelectionAction [[ProductSelectionSetVariantSelectionAction.svg]]  {
    action: String
    product: [[ProductResourceIdentifier.svg ProductResourceIdentifier]]
    variantSelection: [[ProductVariantSelection.svg ProductVariantSelection]]
}
interface ProductSelectionUpdate [[ProductSelectionUpdate.svg]]  {
    version: Long
    actions: [[ProductSelectionUpdateAction.svg List<ProductSelectionUpdateAction>]]
}
ProductSelectionUpdateAction --> ProductSelectionAddProductAction #blue;text:blue : "action : addProduct"
ProductSelectionUpdateAction --> ProductSelectionChangeNameAction #blue;text:blue : "action : changeName"
ProductSelectionUpdateAction --> ProductSelectionExcludeProductAction #blue;text:blue : "action : excludeProduct"
ProductSelectionUpdateAction --> ProductSelectionRemoveProductAction #blue;text:blue : "action : removeProduct"
ProductSelectionUpdateAction --> ProductSelectionSetCustomFieldAction #blue;text:blue : "action : setCustomField"
ProductSelectionUpdateAction --> ProductSelectionSetCustomTypeAction #blue;text:blue : "action : setCustomType"
ProductSelectionUpdateAction --> ProductSelectionSetKeyAction #blue;text:blue : "action : setKey"
ProductSelectionUpdateAction --> ProductSelectionSetVariantExclusionAction #blue;text:blue : "action : setVariantExclusion"
ProductSelectionUpdateAction --> ProductSelectionSetVariantSelectionAction #blue;text:blue : "action : setVariantSelection"
ProductSelectionUpdateAction --> ProductSelectionUpdate #green;text:green : "actions"
@enduml
