@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface ProductTypeRemoveAttributeDefinitionAction [[ProductTypeRemoveAttributeDefinitionAction.svg]] extends ProductTypeUpdateAction {
    action: String
    name: String
}
interface ProductTypeUpdateAction [[ProductTypeUpdateAction.svg]]  {
    action: String
}





@enduml
