@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface ProductSearchAnyValue [[ProductSearchAnyValue.svg]] extends ProductSearchQueryExpressionValue {
    field: String
    boost: Double
    attributeType: [[ProductSearchAttributeType.svg ProductSearchAttributeType]]
    value: [[Object.svg Object]]
    language: String
    caseInsensitive: Boolean
}
interface ProductSearchQueryExpressionValue [[ProductSearchQueryExpressionValue.svg]]  {
    field: String
    boost: Double
    attributeType: [[ProductSearchAttributeType.svg ProductSearchAttributeType]]
}





@enduml
