@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface ProductTailoringUpdate [[ProductTailoringUpdate.svg]]  {
    version: Long
    actions: [[ProductTailoringUpdateAction.svg List<ProductTailoringUpdateAction>]]
}






@enduml
