@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface ProductTailoringDraft [[ProductTailoringDraft.svg]]  {
    key: String
    store: [[StoreResourceIdentifier.svg StoreResourceIdentifier]]
    product: [[ProductResourceIdentifier.svg ProductResourceIdentifier]]
    name: [[LocalizedString.svg LocalizedString]]
    description: [[LocalizedString.svg LocalizedString]]
    metaTitle: [[LocalizedString.svg LocalizedString]]
    metaDescription: [[LocalizedString.svg LocalizedString]]
    metaKeywords: [[LocalizedString.svg LocalizedString]]
    slug: [[LocalizedString.svg LocalizedString]]
    publish: Boolean
}






@enduml
