@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface ProductData [[ProductData.svg]]  {
    name: [[LocalizedString.svg LocalizedString]]
    categories: [[CategoryReference.svg List<CategoryReference>]]
    categoryOrderHints: [[CategoryOrderHints.svg CategoryOrderHints]]
    description: [[LocalizedString.svg LocalizedString]]
    slug: [[LocalizedString.svg LocalizedString]]
    metaTitle: [[LocalizedString.svg LocalizedString]]
    metaDescription: [[LocalizedString.svg LocalizedString]]
    metaKeywords: [[LocalizedString.svg LocalizedString]]
    masterVariant: [[ProductVariant.svg ProductVariant]]
    variants: [[ProductVariant.svg List<ProductVariant>]]
    searchKeywords: [[SearchKeywords.svg SearchKeywords]]
    attributes: [[Attribute.svg List<Attribute>]]
}



interface ProductCatalogData [[ProductCatalogData.svg]]  {
    published: Boolean
    current: [[ProductData.svg ProductData]]
    staged: [[ProductData.svg ProductData]]
    hasStagedChanges: Boolean
}

ProductData --> ProductCatalogData #green;text:green : "current"
ProductData --> ProductCatalogData #green;text:green : "staged"
@enduml
