@startuml

hide methods
enum ProductSearchAttributeType {
    BOOLEAN
    TEXT
    LTEXT
    ENUM
    LENUM
    NUMBER
    MONEY
    DATE
    DATETIME
    TIME
    REFERENCE
    SET_BOOLEAN
    SET_TEXT
    SET_LTEXT
    SET_ENUM
    SET_LENUM
    SET_NUMBER
    SET_MONEY
    SET_DATE
    SET_DATETIME
    SET_TIME
    SET_REFERENCE
}
interface ProductSearchFacetDistinctValue [[ProductSearchFacetDistinctValue.svg]]  {
    name: String
    scope: [[ProductSearchFacetEnumScope.svg ProductSearchFacetEnumScope]]
    filter: [[ProductSearchQuery.svg ProductSearchQuery]]
    count: [[ProductSearchFacetEnumCount.svg ProductSearchFacetEnumCount]]
    field: String
    includes: [[String.svg List<String>]]
    startsWith: [[ProductSearchFacetDistinctStartsWith.svg ProductSearchFacetDistinctStartsWith]]
    sort: [[ProductSearchFacetDistinctBucketSortExpression.svg ProductSearchFacetDistinctBucketSortExpression]]
    size: Integer
    language: String
    attributeType: [[ProductSearchAttributeType.svg ProductSearchAttributeType]]
    missing: String
}
interface ProductSearchFacetRangesValue [[ProductSearchFacetRangesValue.svg]]  {
    name: String
    scope: [[ProductSearchFacetEnumScope.svg ProductSearchFacetEnumScope]]
    filter: [[ProductSearchQuery.svg ProductSearchQuery]]
    count: [[ProductSearchFacetEnumCount.svg ProductSearchFacetEnumCount]]
    field: String
    ranges: [[ProductSearchFacetRangesFacetRange.svg List<ProductSearchFacetRangesFacetRange>]]
    language: String
    attributeType: [[ProductSearchAttributeType.svg ProductSearchAttributeType]]
}
ProductSearchAttributeType --> ProductSearchFacetDistinctValue #green;text:green : "attributeType"
ProductSearchAttributeType --> ProductSearchFacetRangesValue #green;text:green : "attributeType"
@enduml
