@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface ProductSelection [[ProductSelection.svg]] extends BaseResource {
    id: String
    version: Long
    createdAt: DateTime
    lastModifiedAt: DateTime
    lastModifiedBy: [[LastModifiedBy.svg LastModifiedBy]]
    createdBy: [[CreatedBy.svg CreatedBy]]
    key: String
    name: [[LocalizedString.svg LocalizedString]]
    productCount: Integer
    type: [[ProductSelectionTypeEnum.svg ProductSelectionTypeEnum]]
    mode: [[ProductSelectionMode.svg ProductSelectionMode]]
    custom: [[CustomFields.svg CustomFields]]
}
interface BaseResource [[BaseResource.svg]]  {
    id: String
    version: Long
    createdAt: DateTime
    lastModifiedAt: DateTime
}


interface ProductSelectionPagedQueryResponse [[ProductSelectionPagedQueryResponse.svg]]  {
    limit: Long
    offset: Long
    count: Long
    total: Long
    results: [[ProductSelection.svg List<ProductSelection>]]
}
interface ProductSelectionCreatedMessage [[ProductSelectionCreatedMessage.svg]]  {
    id: String
    version: Long
    createdAt: DateTime
    lastModifiedAt: DateTime
    lastModifiedBy: [[LastModifiedBy.svg LastModifiedBy]]
    createdBy: [[CreatedBy.svg CreatedBy]]
    sequenceNumber: Long
    resource: [[Reference.svg Reference]]
    resourceVersion: Long
    type: String
    resourceUserProvidedIdentifiers: [[UserProvidedIdentifiers.svg UserProvidedIdentifiers]]
    productSelection: [[ProductSelection.svg ProductSelection]]
}
interface ProductSelectionCreatedMessagePayload [[ProductSelectionCreatedMessagePayload.svg]]  {
    type: String
    productSelection: [[ProductSelection.svg ProductSelection]]
}
interface ProductSelectionReference [[ProductSelectionReference.svg]]  {
    typeId: [[ReferenceTypeId.svg ReferenceTypeId]]
    id: String
    obj: [[ProductSelection.svg ProductSelection]]
}

ProductSelection --> ProductSelectionPagedQueryResponse #green;text:green : "results"
ProductSelection --> ProductSelectionCreatedMessage #green;text:green : "productSelection"
ProductSelection --> ProductSelectionCreatedMessagePayload #green;text:green : "productSelection"
ProductSelection --> ProductSelectionReference #green;text:green : "obj"
@enduml
