@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface ProductPriceCustomFieldsRemovedMessagePayload [[ProductPriceCustomFieldsRemovedMessagePayload.svg]] extends MessagePayload {
    type: String
    priceId: String
    variantId: Long
    staged: Boolean
}
interface MessagePayload [[MessagePayload.svg]]  {
    type: String
}





@enduml
