@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface ProductTailoringRemoveVariantAction [[ProductTailoringRemoveVariantAction.svg]] extends ProductTailoringUpdateAction {
    action: String
    id: Long
    sku: String
    staged: Boolean
}
interface ProductTailoringUpdateAction [[ProductTailoringUpdateAction.svg]]  {
    action: String
}





@enduml
