@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface ProductSelectionDraft [[ProductSelectionDraft.svg]]  {
    key: String
    name: [[LocalizedString.svg LocalizedString]]
    custom: [[CustomFieldsDraft.svg CustomFieldsDraft]]
    type: [[ProductSelectionTypeEnum.svg ProductSelectionTypeEnum]]
    mode: [[ProductSelectionMode.svg ProductSelectionMode]]
}






@enduml
