@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface ProductSelectionSetting [[ProductSelectionSetting.svg]]  {
    productSelection: [[ProductSelectionReference.svg ProductSelectionReference]]
    active: Boolean
}



interface Store [[Store.svg]]  {
    id: String
    version: Long
    createdAt: DateTime
    lastModifiedAt: DateTime
    lastModifiedBy: [[LastModifiedBy.svg LastModifiedBy]]
    createdBy: [[CreatedBy.svg CreatedBy]]
    key: String
    name: [[LocalizedString.svg LocalizedString]]
    languages: [[String.svg List<String>]]
    countries: [[StoreCountry.svg List<StoreCountry>]]
    distributionChannels: [[ChannelReference.svg List<ChannelReference>]]
    supplyChannels: [[ChannelReference.svg List<ChannelReference>]]
    productSelections: [[ProductSelectionSetting.svg List<ProductSelectionSetting>]]
    custom: [[CustomFields.svg CustomFields]]
}
interface StoreCreatedMessage [[StoreCreatedMessage.svg]]  {
    id: String
    version: Long
    createdAt: DateTime
    lastModifiedAt: DateTime
    lastModifiedBy: [[LastModifiedBy.svg LastModifiedBy]]
    createdBy: [[CreatedBy.svg CreatedBy]]
    sequenceNumber: Long
    resource: [[Reference.svg Reference]]
    resourceVersion: Long
    type: String
    resourceUserProvidedIdentifiers: [[UserProvidedIdentifiers.svg UserProvidedIdentifiers]]
    name: [[LocalizedString.svg LocalizedString]]
    languages: [[String.svg List<String>]]
    countries: [[StoreCountry.svg List<StoreCountry>]]
    distributionChannels: [[ChannelReference.svg List<ChannelReference>]]
    supplyChannels: [[ChannelReference.svg List<ChannelReference>]]
    productSelections: [[ProductSelectionSetting.svg List<ProductSelectionSetting>]]
    custom: [[CustomFields.svg CustomFields]]
}
interface StoreProductSelectionsChangedMessage [[StoreProductSelectionsChangedMessage.svg]]  {
    id: String
    version: Long
    createdAt: DateTime
    lastModifiedAt: DateTime
    lastModifiedBy: [[LastModifiedBy.svg LastModifiedBy]]
    createdBy: [[CreatedBy.svg CreatedBy]]
    sequenceNumber: Long
    resource: [[Reference.svg Reference]]
    resourceVersion: Long
    type: String
    resourceUserProvidedIdentifiers: [[UserProvidedIdentifiers.svg UserProvidedIdentifiers]]
    addedProductSelections: [[ProductSelectionSetting.svg List<ProductSelectionSetting>]]
    removedProductSelections: [[ProductSelectionSetting.svg List<ProductSelectionSetting>]]
    updatedProductSelections: [[ProductSelectionSetting.svg List<ProductSelectionSetting>]]
}
interface StoreCreatedMessagePayload [[StoreCreatedMessagePayload.svg]]  {
    type: String
    name: [[LocalizedString.svg LocalizedString]]
    languages: [[String.svg List<String>]]
    countries: [[StoreCountry.svg List<StoreCountry>]]
    distributionChannels: [[ChannelReference.svg List<ChannelReference>]]
    supplyChannels: [[ChannelReference.svg List<ChannelReference>]]
    productSelections: [[ProductSelectionSetting.svg List<ProductSelectionSetting>]]
    custom: [[CustomFields.svg CustomFields]]
}
interface StoreProductSelectionsChangedMessagePayload [[StoreProductSelectionsChangedMessagePayload.svg]]  {
    type: String
    addedProductSelections: [[ProductSelectionSetting.svg List<ProductSelectionSetting>]]
    removedProductSelections: [[ProductSelectionSetting.svg List<ProductSelectionSetting>]]
    updatedProductSelections: [[ProductSelectionSetting.svg List<ProductSelectionSetting>]]
}

ProductSelectionSetting --> Store #green;text:green : "productSelections"
ProductSelectionSetting --> StoreCreatedMessage #green;text:green : "productSelections"
ProductSelectionSetting --> StoreProductSelectionsChangedMessage #green;text:green : "addedProductSelections"
ProductSelectionSetting --> StoreProductSelectionsChangedMessage #green;text:green : "removedProductSelections"
ProductSelectionSetting --> StoreProductSelectionsChangedMessage #green;text:green : "updatedProductSelections"
ProductSelectionSetting --> StoreCreatedMessagePayload #green;text:green : "productSelections"
ProductSelectionSetting --> StoreProductSelectionsChangedMessagePayload #green;text:green : "addedProductSelections"
ProductSelectionSetting --> StoreProductSelectionsChangedMessagePayload #green;text:green : "removedProductSelections"
ProductSelectionSetting --> StoreProductSelectionsChangedMessagePayload #green;text:green : "updatedProductSelections"
@enduml
