@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface ProductCatalogData [[ProductCatalogData.svg]]  {
    published: Boolean
    current: [[ProductData.svg ProductData]]
    staged: [[ProductData.svg ProductData]]
    hasStagedChanges: Boolean
}



interface Product [[Product.svg]]  {
    id: String
    version: Long
    createdAt: DateTime
    lastModifiedAt: DateTime
    lastModifiedBy: [[LastModifiedBy.svg LastModifiedBy]]
    createdBy: [[CreatedBy.svg CreatedBy]]
    key: String
    productType: [[ProductTypeReference.svg ProductTypeReference]]
    masterData: [[ProductCatalogData.svg ProductCatalogData]]
    taxCategory: [[TaxCategoryReference.svg TaxCategoryReference]]
    state: [[StateReference.svg StateReference]]
    reviewRatingStatistics: [[ReviewRatingStatistics.svg ReviewRatingStatistics]]
    priceMode: [[ProductPriceModeEnum.svg ProductPriceModeEnum]]
    warnings: [[WarningObject.svg List<WarningObject>]]
}

ProductCatalogData --> Product #green;text:green : "masterData"
@enduml
