@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface ProductDiscountValueDraft [[ProductDiscountValueDraft.svg]]  {
    type: String
}


interface ProductDiscountValueAbsoluteDraft [[ProductDiscountValueAbsoluteDraft.svg]]  {
    type: String
    money: [[Money.svg List<Money>]]
}
interface ProductDiscountValueExternalDraft [[ProductDiscountValueExternalDraft.svg]]  {
    type: String
}
interface ProductDiscountValueRelativeDraft [[ProductDiscountValueRelativeDraft.svg]]  {
    type: String
    permyriad: Long
}
interface ProductDiscountDraft [[ProductDiscountDraft.svg]]  {
    name: [[LocalizedString.svg LocalizedString]]
    key: String
    description: [[LocalizedString.svg LocalizedString]]
    value: [[ProductDiscountValueDraft.svg ProductDiscountValueDraft]]
    predicate: String
    sortOrder: String
    isActive: Boolean
    validFrom: DateTime
    validUntil: DateTime
}
interface ProductDiscountChangeValueAction [[ProductDiscountChangeValueAction.svg]]  {
    action: String
    value: [[ProductDiscountValueDraft.svg ProductDiscountValueDraft]]
}
ProductDiscountValueDraft --> ProductDiscountValueAbsoluteDraft #blue;text:blue : "type : absolute"
ProductDiscountValueDraft --> ProductDiscountValueExternalDraft #blue;text:blue : "type : external"
ProductDiscountValueDraft --> ProductDiscountValueRelativeDraft #blue;text:blue : "type : relative"
ProductDiscountValueDraft --> ProductDiscountDraft #green;text:green : "value"
ProductDiscountValueDraft --> ProductDiscountChangeValueAction #green;text:green : "value"
@enduml
