@startuml

hide methods
enum ProductPublishScope {
    ALL
    PRICES
}
interface ProductPublishedMessage [[ProductPublishedMessage.svg]]  {
    id: String
    version: Long
    createdAt: DateTime
    lastModifiedAt: DateTime
    lastModifiedBy: [[LastModifiedBy.svg LastModifiedBy]]
    createdBy: [[CreatedBy.svg CreatedBy]]
    sequenceNumber: Long
    resource: [[Reference.svg Reference]]
    resourceVersion: Long
    type: String
    resourceUserProvidedIdentifiers: [[UserProvidedIdentifiers.svg UserProvidedIdentifiers]]
    removedImageUrls: [[String.svg List<String>]]
    productProjection: [[ProductProjection.svg ProductProjection]]
    scope: [[ProductPublishScope.svg ProductPublishScope]]
}
interface ProductPublishedMessagePayload [[ProductPublishedMessagePayload.svg]]  {
    type: String
    removedImageUrls: [[String.svg List<String>]]
    productProjection: [[ProductProjection.svg ProductProjection]]
    scope: [[ProductPublishScope.svg ProductPublishScope]]
}
interface ProductPublishAction [[ProductPublishAction.svg]]  {
    action: String
    scope: [[ProductPublishScope.svg ProductPublishScope]]
}
ProductPublishScope --> ProductPublishedMessage #green;text:green : "scope"
ProductPublishScope --> ProductPublishedMessagePayload #green;text:green : "scope"
ProductPublishScope --> ProductPublishAction #green;text:green : "scope"
@enduml
