@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface ProductSearchDateRangeValue [[ProductSearchDateRangeValue.svg]] extends ProductSearchQueryExpressionValue {
    field: String
    boost: Double
    attributeType: [[ProductSearchAttributeType.svg ProductSearchAttributeType]]
    gte: Date
    gt: Date
    lte: Date
    lt: Date
}
interface ProductSearchQueryExpressionValue [[ProductSearchQueryExpressionValue.svg]]  {
    field: String
    boost: Double
    attributeType: [[ProductSearchAttributeType.svg ProductSearchAttributeType]]
}





@enduml
