@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface ProductTypeUpdateAction [[ProductTypeUpdateAction.svg]]  {
    action: String
}


interface ProductTypeAddAttributeDefinitionAction [[ProductTypeAddAttributeDefinitionAction.svg]]  {
    action: String
    attribute: [[AttributeDefinitionDraft.svg AttributeDefinitionDraft]]
}
interface ProductTypeAddLocalizedEnumValueAction [[ProductTypeAddLocalizedEnumValueAction.svg]]  {
    action: String
    attributeName: String
    value: [[AttributeLocalizedEnumValue.svg AttributeLocalizedEnumValue]]
}
interface ProductTypeAddPlainEnumValueAction [[ProductTypeAddPlainEnumValueAction.svg]]  {
    action: String
    attributeName: String
    value: [[AttributePlainEnumValue.svg AttributePlainEnumValue]]
}
interface ProductTypeChangeAttributeConstraintAction [[ProductTypeChangeAttributeConstraintAction.svg]]  {
    action: String
    attributeName: String
    newValue: [[AttributeConstraintEnumDraft.svg AttributeConstraintEnumDraft]]
}
interface ProductTypeChangeAttributeNameAction [[ProductTypeChangeAttributeNameAction.svg]]  {
    action: String
    attributeName: String
    newAttributeName: String
}
interface ProductTypeChangeAttributeOrderAction [[ProductTypeChangeAttributeOrderAction.svg]]  {
    action: String
    attributes: [[AttributeDefinition.svg List<AttributeDefinition>]]
}
interface ProductTypeChangeAttributeOrderByNameAction [[ProductTypeChangeAttributeOrderByNameAction.svg]]  {
    action: String
    attributeNames: [[String.svg List<String>]]
}
interface ProductTypeChangeDescriptionAction [[ProductTypeChangeDescriptionAction.svg]]  {
    action: String
    description: String
}
interface ProductTypeChangeEnumKeyAction [[ProductTypeChangeEnumKeyAction.svg]]  {
    action: String
    attributeName: String
    key: String
    newKey: String
}
interface ProductTypeChangeInputHintAction [[ProductTypeChangeInputHintAction.svg]]  {
    action: String
    attributeName: String
    newValue: [[TextInputHint.svg TextInputHint]]
}
interface ProductTypeChangeIsSearchableAction [[ProductTypeChangeIsSearchableAction.svg]]  {
    action: String
    attributeName: String
    isSearchable: Boolean
}
interface ProductTypeChangeLabelAction [[ProductTypeChangeLabelAction.svg]]  {
    action: String
    attributeName: String
    label: [[LocalizedString.svg LocalizedString]]
}
interface ProductTypeChangeLocalizedEnumValueLabelAction [[ProductTypeChangeLocalizedEnumValueLabelAction.svg]]  {
    action: String
    attributeName: String
    newValue: [[AttributeLocalizedEnumValue.svg AttributeLocalizedEnumValue]]
}
interface ProductTypeChangeLocalizedEnumValueOrderAction [[ProductTypeChangeLocalizedEnumValueOrderAction.svg]]  {
    action: String
    attributeName: String
    values: [[AttributeLocalizedEnumValue.svg List<AttributeLocalizedEnumValue>]]
}
interface ProductTypeChangeNameAction [[ProductTypeChangeNameAction.svg]]  {
    action: String
    name: String
}
interface ProductTypeChangePlainEnumValueLabelAction [[ProductTypeChangePlainEnumValueLabelAction.svg]]  {
    action: String
    attributeName: String
    newValue: [[AttributePlainEnumValue.svg AttributePlainEnumValue]]
}
interface ProductTypeChangePlainEnumValueOrderAction [[ProductTypeChangePlainEnumValueOrderAction.svg]]  {
    action: String
    attributeName: String
    values: [[AttributePlainEnumValue.svg List<AttributePlainEnumValue>]]
}
interface ProductTypeRemoveAttributeDefinitionAction [[ProductTypeRemoveAttributeDefinitionAction.svg]]  {
    action: String
    name: String
}
interface ProductTypeRemoveEnumValuesAction [[ProductTypeRemoveEnumValuesAction.svg]]  {
    action: String
    attributeName: String
    keys: [[String.svg List<String>]]
}
interface ProductTypeSetInputTipAction [[ProductTypeSetInputTipAction.svg]]  {
    action: String
    attributeName: String
    inputTip: [[LocalizedString.svg LocalizedString]]
}
interface ProductTypeSetKeyAction [[ProductTypeSetKeyAction.svg]]  {
    action: String
    key: String
}
interface ProductTypeUpdate [[ProductTypeUpdate.svg]]  {
    version: Long
    actions: [[ProductTypeUpdateAction.svg List<ProductTypeUpdateAction>]]
}
ProductTypeUpdateAction --> ProductTypeAddAttributeDefinitionAction #blue;text:blue : "action : addAttributeDefinition"
ProductTypeUpdateAction --> ProductTypeAddLocalizedEnumValueAction #blue;text:blue : "action : addLocalizedEnumValue"
ProductTypeUpdateAction --> ProductTypeAddPlainEnumValueAction #blue;text:blue : "action : addPlainEnumValue"
ProductTypeUpdateAction --> ProductTypeChangeAttributeConstraintAction #blue;text:blue : "action : changeAttributeConstraint"
ProductTypeUpdateAction --> ProductTypeChangeAttributeNameAction #blue;text:blue : "action : changeAttributeName"
ProductTypeUpdateAction --> ProductTypeChangeAttributeOrderAction #blue;text:blue : "action : changeAttributeOrder"
ProductTypeUpdateAction --> ProductTypeChangeAttributeOrderByNameAction #blue;text:blue : "action : changeAttributeOrderByName"
ProductTypeUpdateAction --> ProductTypeChangeDescriptionAction #blue;text:blue : "action : changeDescription"
ProductTypeUpdateAction --> ProductTypeChangeEnumKeyAction #blue;text:blue : "action : changeEnumKey"
ProductTypeUpdateAction --> ProductTypeChangeInputHintAction #blue;text:blue : "action : changeInputHint"
ProductTypeUpdateAction --> ProductTypeChangeIsSearchableAction #blue;text:blue : "action : changeIsSearchable"
ProductTypeUpdateAction --> ProductTypeChangeLabelAction #blue;text:blue : "action : changeLabel"
ProductTypeUpdateAction --> ProductTypeChangeLocalizedEnumValueLabelAction #blue;text:blue : "action : changeLocalizedEnumValueLabel"
ProductTypeUpdateAction --> ProductTypeChangeLocalizedEnumValueOrderAction #blue;text:blue : "action : changeLocalizedEnumValueOrder"
ProductTypeUpdateAction --> ProductTypeChangeNameAction #blue;text:blue : "action : changeName"
ProductTypeUpdateAction --> ProductTypeChangePlainEnumValueLabelAction #blue;text:blue : "action : changePlainEnumValueLabel"
ProductTypeUpdateAction --> ProductTypeChangePlainEnumValueOrderAction #blue;text:blue : "action : changePlainEnumValueOrder"
ProductTypeUpdateAction --> ProductTypeRemoveAttributeDefinitionAction #blue;text:blue : "action : removeAttributeDefinition"
ProductTypeUpdateAction --> ProductTypeRemoveEnumValuesAction #blue;text:blue : "action : removeEnumValues"
ProductTypeUpdateAction --> ProductTypeSetInputTipAction #blue;text:blue : "action : setInputTip"
ProductTypeUpdateAction --> ProductTypeSetKeyAction #blue;text:blue : "action : setKey"
ProductTypeUpdateAction --> ProductTypeUpdate #green;text:green : "actions"
@enduml
