@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface ProductRemoveFromCategoryAction [[ProductRemoveFromCategoryAction.svg]] extends ProductUpdateAction {
    action: String
    category: [[CategoryResourceIdentifier.svg CategoryResourceIdentifier]]
    staged: Boolean
}
interface ProductUpdateAction [[ProductUpdateAction.svg]]  {
    action: String
}





@enduml
