@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface ProductSelectionType [[ProductSelectionType.svg]]  {
    type: [[ProductSelectionTypeEnum.svg ProductSelectionTypeEnum]]
}


interface IndividualExclusionProductSelectionType [[IndividualExclusionProductSelectionType.svg]]  {
    type: [[ProductSelectionTypeEnum.svg ProductSelectionTypeEnum]]
    name: [[LocalizedString.svg LocalizedString]]
}
interface IndividualProductSelectionType [[IndividualProductSelectionType.svg]]  {
    type: [[ProductSelectionTypeEnum.svg ProductSelectionTypeEnum]]
    name: [[LocalizedString.svg LocalizedString]]
}
interface ProductSelectionCreatedMessage [[ProductSelectionCreatedMessage.svg]]  {
    id: String
    version: Long
    createdAt: DateTime
    lastModifiedAt: DateTime
    lastModifiedBy: [[LastModifiedBy.svg LastModifiedBy]]
    createdBy: [[CreatedBy.svg CreatedBy]]
    sequenceNumber: Long
    resource: [[Reference.svg Reference]]
    resourceVersion: Long
    type: String
    resourceUserProvidedIdentifiers: [[UserProvidedIdentifiers.svg UserProvidedIdentifiers]]
    productSelection: [[ProductSelectionType.svg ProductSelectionType]]
}
interface ProductSelectionCreatedMessagePayload [[ProductSelectionCreatedMessagePayload.svg]]  {
    type: String
    productSelection: [[ProductSelectionType.svg ProductSelectionType]]
}
ProductSelectionType --> IndividualExclusionProductSelectionType #blue;text:blue : "type : individualExclusion"
ProductSelectionType --> IndividualProductSelectionType #blue;text:blue : "type : individual"
ProductSelectionType --> ProductSelectionCreatedMessage #green;text:green : "productSelection"
ProductSelectionType --> ProductSelectionCreatedMessagePayload #green;text:green : "productSelection"
@enduml
