@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface ProductDiscountReference [[ProductDiscountReference.svg]] extends Reference {
    typeId: [[ReferenceTypeId.svg ReferenceTypeId]]
    id: String
    obj: [[ProductDiscount.svg ProductDiscount]]
}
interface Reference [[Reference.svg]]  {
    typeId: [[ReferenceTypeId.svg ReferenceTypeId]]
    id: String
}


interface DiscountedPrice [[DiscountedPrice.svg]]  {
    value: [[TypedMoney.svg TypedMoney]]
    discount: [[ProductDiscountReference.svg ProductDiscountReference]]
}
interface DiscountedPriceDraft [[DiscountedPriceDraft.svg]]  {
    value: [[Money.svg Money]]
    discount: [[ProductDiscountReference.svg ProductDiscountReference]]
}

ProductDiscountReference --> DiscountedPrice #green;text:green : "discount"
ProductDiscountReference --> DiscountedPriceDraft #green;text:green : "discount"
@enduml
