@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface ProjectSetExternalOAuthAction [[ProjectSetExternalOAuthAction.svg]] extends ProjectUpdateAction {
    action: String
    externalOAuth: [[ExternalOAuth.svg ExternalOAuth]]
}
interface ProjectUpdateAction [[ProjectUpdateAction.svg]]  {
    action: String
}





@enduml
