@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface ProjectChangeBusinessUnitSearchStatusAction [[ProjectChangeBusinessUnitSearchStatusAction.svg]] extends ProjectUpdateAction {
    action: String
    status: [[BusinessUnitSearchStatus.svg BusinessUnitSearchStatus]]
}
interface ProjectUpdateAction [[ProjectUpdateAction.svg]]  {
    action: String
}





@enduml
