@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface ProjectChangeProductSearchStatusAction [[ProjectChangeProductSearchStatusAction.svg]] extends ProjectUpdateAction {
    action: String
    status: [[ProductSearchStatus.svg ProductSearchStatus]]
}
interface ProjectUpdateAction [[ProjectUpdateAction.svg]]  {
    action: String
}





@enduml
