@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface ProjectChangeCountryTaxRateFallbackEnabledAction [[ProjectChangeCountryTaxRateFallbackEnabledAction.svg]] extends ProjectUpdateAction {
    action: String
    countryTaxRateFallbackEnabled: Boolean
}
interface ProjectUpdateAction [[ProjectUpdateAction.svg]]  {
    action: String
}





@enduml
