@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface QuoteRequestDraft [[QuoteRequestDraft.svg]]  {
    cart: [[CartResourceIdentifier.svg CartResourceIdentifier]]
    cartVersion: Long
    key: String
    comment: String
    custom: [[CustomFieldsDraft.svg CustomFieldsDraft]]
    state: [[StateReference.svg StateReference]]
    purchaseOrderNumber: String
}






@enduml
