@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface RecurringOrderCreatedMessagePayload [[RecurringOrderCreatedMessagePayload.svg]] extends MessagePayload {
    type: String
    recurringOrder: [[RecurringOrder.svg RecurringOrder]]
}
interface MessagePayload [[MessagePayload.svg]]  {
    type: String
}





@enduml
