@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface RecurringOrderTransitionStateAction [[RecurringOrderTransitionStateAction.svg]] extends RecurringOrderUpdateAction {
    action: String
    state: [[StateResourceIdentifier.svg StateResourceIdentifier]]
    force: Boolean
}
interface RecurringOrderUpdateAction [[RecurringOrderUpdateAction.svg]]  {
    action: String
}





@enduml
