@startuml

hide methods
enum ReferenceTypeId {
    APPROVAL_FLOW
    APPROVAL_RULE
    ASSOCIATE_ROLE
    ATTRIBUTE_GROUP
    BUSINESS_UNIT
    CART
    CART_DISCOUNT
    CATEGORY
    CHANNEL
    CUSTOMER
    CUSTOMER_EMAIL_TOKEN
    CUSTOMER_GROUP
    CUSTOMER_PASSWORD_TOKEN
    DIRECT_DISCOUNT
    DISCOUNT_CODE
    DISCOUNT_GROUP
    EXTENSION
    INVENTORY_ENTRY
    KEY_VALUE_DOCUMENT
    ORDER
    ORDER_EDIT
    PAYMENT_METHOD
    PAYMENT
    PRODUCT
    PRODUCT_DISCOUNT
    PRODUCT_PRICE
    PRODUCT_SELECTION
    PRODUCT_TAILORING
    PRODUCT_TYPE
    QUOTE
    QUOTE_REQUEST
    RECURRENCE_POLICY
    RECURRING_ORDER
    RESERVATION
    REVIEW
    SHIPPING_METHOD
    SHOPPING_LIST
    STAGED_QUOTE
    STANDALONE_PRICE
    STATE
    STORE
    SUBSCRIPTION
    TAX_CATEGORY
    TYPE
    ZONE
}
interface AssociateRoleKeyReference [[AssociateRoleKeyReference.svg]]  {
    typeId: [[ReferenceTypeId.svg ReferenceTypeId]]
    key: String
}
interface AssociateRoleReference [[AssociateRoleReference.svg]]  {
    typeId: [[ReferenceTypeId.svg ReferenceTypeId]]
    id: String
    obj: [[AssociateRole.svg AssociateRole]]
}
interface AssociateRoleResourceIdentifier [[AssociateRoleResourceIdentifier.svg]]  {
    typeId: [[ReferenceTypeId.svg ReferenceTypeId]]
    id: String
    key: String
}
interface AttributeGroupReference [[AttributeGroupReference.svg]]  {
    typeId: [[ReferenceTypeId.svg ReferenceTypeId]]
    id: String
    obj: [[AttributeGroup.svg AttributeGroup]]
}
interface AttributeGroupResourceIdentifier [[AttributeGroupResourceIdentifier.svg]]  {
    typeId: [[ReferenceTypeId.svg ReferenceTypeId]]
    id: String
    key: String
}
interface BusinessUnitKeyReference [[BusinessUnitKeyReference.svg]]  {
    typeId: [[ReferenceTypeId.svg ReferenceTypeId]]
    key: String
}
interface BusinessUnitReference [[BusinessUnitReference.svg]]  {
    typeId: [[ReferenceTypeId.svg ReferenceTypeId]]
    id: String
    obj: [[BusinessUnit.svg BusinessUnit]]
}
interface BusinessUnitResourceIdentifier [[BusinessUnitResourceIdentifier.svg]]  {
    typeId: [[ReferenceTypeId.svg ReferenceTypeId]]
    id: String
    key: String
}
interface CartDiscountReference [[CartDiscountReference.svg]]  {
    typeId: [[ReferenceTypeId.svg ReferenceTypeId]]
    id: String
    obj: [[CartDiscount.svg CartDiscount]]
}
interface CartDiscountResourceIdentifier [[CartDiscountResourceIdentifier.svg]]  {
    typeId: [[ReferenceTypeId.svg ReferenceTypeId]]
    id: String
    key: String
}
interface CartReference [[CartReference.svg]]  {
    typeId: [[ReferenceTypeId.svg ReferenceTypeId]]
    id: String
    obj: [[Cart.svg Cart]]
}
interface CartResourceIdentifier [[CartResourceIdentifier.svg]]  {
    typeId: [[ReferenceTypeId.svg ReferenceTypeId]]
    id: String
    key: String
}
interface DirectDiscountReference [[DirectDiscountReference.svg]]  {
    typeId: [[ReferenceTypeId.svg ReferenceTypeId]]
    id: String
}
interface ReservationReference [[ReservationReference.svg]]  {
    typeId: [[ReferenceTypeId.svg ReferenceTypeId]]
    id: String
    obj: [[Reservation.svg Reservation]]
}
interface CategoryReference [[CategoryReference.svg]]  {
    typeId: [[ReferenceTypeId.svg ReferenceTypeId]]
    id: String
    obj: [[Category.svg Category]]
}
interface CategoryResourceIdentifier [[CategoryResourceIdentifier.svg]]  {
    typeId: [[ReferenceTypeId.svg ReferenceTypeId]]
    id: String
    key: String
}
interface ChannelReference [[ChannelReference.svg]]  {
    typeId: [[ReferenceTypeId.svg ReferenceTypeId]]
    id: String
    obj: [[Channel.svg Channel]]
}
interface ChannelResourceIdentifier [[ChannelResourceIdentifier.svg]]  {
    typeId: [[ReferenceTypeId.svg ReferenceTypeId]]
    id: String
    key: String
}
interface KeyReference [[KeyReference.svg]]  {
    typeId: [[ReferenceTypeId.svg ReferenceTypeId]]
    key: String
}
interface Reference [[Reference.svg]]  {
    typeId: [[ReferenceTypeId.svg ReferenceTypeId]]
    id: String
}
interface ResourceIdentifier [[ResourceIdentifier.svg]]  {
    typeId: [[ReferenceTypeId.svg ReferenceTypeId]]
    id: String
    key: String
}
interface CustomObjectReference [[CustomObjectReference.svg]]  {
    typeId: [[ReferenceTypeId.svg ReferenceTypeId]]
    id: String
    obj: [[CustomObject.svg CustomObject]]
}
interface CustomerGroupReference [[CustomerGroupReference.svg]]  {
    typeId: [[ReferenceTypeId.svg ReferenceTypeId]]
    id: String
    obj: [[CustomerGroup.svg CustomerGroup]]
}
interface CustomerGroupResourceIdentifier [[CustomerGroupResourceIdentifier.svg]]  {
    typeId: [[ReferenceTypeId.svg ReferenceTypeId]]
    id: String
    key: String
}
interface CustomerEmailTokenReference [[CustomerEmailTokenReference.svg]]  {
    typeId: [[ReferenceTypeId.svg ReferenceTypeId]]
    id: String
}
interface CustomerPasswordTokenReference [[CustomerPasswordTokenReference.svg]]  {
    typeId: [[ReferenceTypeId.svg ReferenceTypeId]]
    id: String
}
interface CustomerReference [[CustomerReference.svg]]  {
    typeId: [[ReferenceTypeId.svg ReferenceTypeId]]
    id: String
    obj: [[Customer.svg Customer]]
}
interface CustomerResourceIdentifier [[CustomerResourceIdentifier.svg]]  {
    typeId: [[ReferenceTypeId.svg ReferenceTypeId]]
    id: String
    key: String
}
interface DiscountCodeReference [[DiscountCodeReference.svg]]  {
    typeId: [[ReferenceTypeId.svg ReferenceTypeId]]
    id: String
    obj: [[DiscountCode.svg DiscountCode]]
}
interface DiscountCodeResourceIdentifier [[DiscountCodeResourceIdentifier.svg]]  {
    typeId: [[ReferenceTypeId.svg ReferenceTypeId]]
    id: String
    key: String
}
interface DiscountGroupReference [[DiscountGroupReference.svg]]  {
    typeId: [[ReferenceTypeId.svg ReferenceTypeId]]
    id: String
    obj: [[DiscountGroup.svg DiscountGroup]]
}
interface DiscountGroupResourceIdentifier [[DiscountGroupResourceIdentifier.svg]]  {
    typeId: [[ReferenceTypeId.svg ReferenceTypeId]]
    id: String
    key: String
}
interface MaxResourceLimitExceededError [[MaxResourceLimitExceededError.svg]]  {
    code: String
    message: String
    exceededResource: [[ReferenceTypeId.svg ReferenceTypeId]]
}
interface ReferenceExistsError [[ReferenceExistsError.svg]]  {
    code: String
    message: String
    referencedBy: [[ReferenceTypeId.svg ReferenceTypeId]]
}
interface ReferencedResourceNotFoundError [[ReferencedResourceNotFoundError.svg]]  {
    code: String
    message: String
    typeId: [[ReferenceTypeId.svg ReferenceTypeId]]
    id: String
    key: String
}
interface GraphQLMaxResourceLimitExceededError [[GraphQLMaxResourceLimitExceededError.svg]]  {
    code: String
    exceededResource: [[ReferenceTypeId.svg ReferenceTypeId]]
}
interface GraphQLReferenceExistsError [[GraphQLReferenceExistsError.svg]]  {
    code: String
    referencedBy: [[ReferenceTypeId.svg ReferenceTypeId]]
}
interface GraphQLReferencedResourceNotFoundError [[GraphQLReferencedResourceNotFoundError.svg]]  {
    code: String
    typeId: [[ReferenceTypeId.svg ReferenceTypeId]]
    id: String
    key: String
}
interface ExtensionReference [[ExtensionReference.svg]]  {
    typeId: [[ReferenceTypeId.svg ReferenceTypeId]]
    id: String
    obj: [[Extension.svg Extension]]
}
interface ExtensionResourceIdentifier [[ExtensionResourceIdentifier.svg]]  {
    typeId: [[ReferenceTypeId.svg ReferenceTypeId]]
    id: String
    key: String
}
interface InventoryEntryReference [[InventoryEntryReference.svg]]  {
    typeId: [[ReferenceTypeId.svg ReferenceTypeId]]
    id: String
    obj: [[InventoryEntry.svg InventoryEntry]]
}
interface InventoryEntryResourceIdentifier [[InventoryEntryResourceIdentifier.svg]]  {
    typeId: [[ReferenceTypeId.svg ReferenceTypeId]]
    id: String
    key: String
}
interface OrderEditReference [[OrderEditReference.svg]]  {
    typeId: [[ReferenceTypeId.svg ReferenceTypeId]]
    id: String
    obj: [[OrderEdit.svg OrderEdit]]
}
interface OrderEditResourceIdentifier [[OrderEditResourceIdentifier.svg]]  {
    typeId: [[ReferenceTypeId.svg ReferenceTypeId]]
    id: String
    key: String
}
interface OrderReference [[OrderReference.svg]]  {
    typeId: [[ReferenceTypeId.svg ReferenceTypeId]]
    id: String
    obj: [[Order.svg Order]]
}
interface PaymentMethodReference [[PaymentMethodReference.svg]]  {
    typeId: [[ReferenceTypeId.svg ReferenceTypeId]]
    id: String
    obj: [[PaymentMethod.svg PaymentMethod]]
}
interface PaymentReference [[PaymentReference.svg]]  {
    typeId: [[ReferenceTypeId.svg ReferenceTypeId]]
    id: String
    obj: [[Payment.svg Payment]]
}
interface PaymentResourceIdentifier [[PaymentResourceIdentifier.svg]]  {
    typeId: [[ReferenceTypeId.svg ReferenceTypeId]]
    id: String
    key: String
}
interface ProductDiscountReference [[ProductDiscountReference.svg]]  {
    typeId: [[ReferenceTypeId.svg ReferenceTypeId]]
    id: String
    obj: [[ProductDiscount.svg ProductDiscount]]
}
interface ProductDiscountResourceIdentifier [[ProductDiscountResourceIdentifier.svg]]  {
    typeId: [[ReferenceTypeId.svg ReferenceTypeId]]
    id: String
    key: String
}
interface ProductSelectionReference [[ProductSelectionReference.svg]]  {
    typeId: [[ReferenceTypeId.svg ReferenceTypeId]]
    id: String
    obj: [[ProductSelection.svg ProductSelection]]
}
interface ProductSelectionResourceIdentifier [[ProductSelectionResourceIdentifier.svg]]  {
    typeId: [[ReferenceTypeId.svg ReferenceTypeId]]
    id: String
    key: String
}
interface ProductTailoringReference [[ProductTailoringReference.svg]]  {
    typeId: [[ReferenceTypeId.svg ReferenceTypeId]]
    id: String
    obj: [[ProductTailoring.svg ProductTailoring]]
}
interface ProductTailoringResourceIdentifier [[ProductTailoringResourceIdentifier.svg]]  {
    typeId: [[ReferenceTypeId.svg ReferenceTypeId]]
    id: String
    key: String
}
interface ProductTypeReference [[ProductTypeReference.svg]]  {
    typeId: [[ReferenceTypeId.svg ReferenceTypeId]]
    id: String
    obj: [[ProductType.svg ProductType]]
}
interface ProductTypeResourceIdentifier [[ProductTypeResourceIdentifier.svg]]  {
    typeId: [[ReferenceTypeId.svg ReferenceTypeId]]
    id: String
    key: String
}
interface ProductReference [[ProductReference.svg]]  {
    typeId: [[ReferenceTypeId.svg ReferenceTypeId]]
    id: String
    obj: [[Product.svg Product]]
}
interface ProductResourceIdentifier [[ProductResourceIdentifier.svg]]  {
    typeId: [[ReferenceTypeId.svg ReferenceTypeId]]
    id: String
    key: String
}
interface QuoteRequestReference [[QuoteRequestReference.svg]]  {
    typeId: [[ReferenceTypeId.svg ReferenceTypeId]]
    id: String
    obj: [[QuoteRequest.svg QuoteRequest]]
}
interface QuoteRequestResourceIdentifier [[QuoteRequestResourceIdentifier.svg]]  {
    typeId: [[ReferenceTypeId.svg ReferenceTypeId]]
    id: String
    key: String
}
interface QuoteReference [[QuoteReference.svg]]  {
    typeId: [[ReferenceTypeId.svg ReferenceTypeId]]
    id: String
    obj: [[Quote.svg Quote]]
}
interface QuoteResourceIdentifier [[QuoteResourceIdentifier.svg]]  {
    typeId: [[ReferenceTypeId.svg ReferenceTypeId]]
    id: String
    key: String
}
interface RecurrencePolicyReference [[RecurrencePolicyReference.svg]]  {
    typeId: [[ReferenceTypeId.svg ReferenceTypeId]]
    id: String
    obj: [[RecurrencePolicy.svg RecurrencePolicy]]
}
interface RecurrencePolicyResourceIdentifier [[RecurrencePolicyResourceIdentifier.svg]]  {
    typeId: [[ReferenceTypeId.svg ReferenceTypeId]]
    id: String
    key: String
}
interface RecurringOrderReference [[RecurringOrderReference.svg]]  {
    typeId: [[ReferenceTypeId.svg ReferenceTypeId]]
    id: String
    obj: [[RecurringOrder.svg RecurringOrder]]
}
interface RecurringOrderResourceIdentifier [[RecurringOrderResourceIdentifier.svg]]  {
    typeId: [[ReferenceTypeId.svg ReferenceTypeId]]
    id: String
    key: String
}
interface ReviewReference [[ReviewReference.svg]]  {
    typeId: [[ReferenceTypeId.svg ReferenceTypeId]]
    id: String
    obj: [[Review.svg Review]]
}
interface ReviewResourceIdentifier [[ReviewResourceIdentifier.svg]]  {
    typeId: [[ReferenceTypeId.svg ReferenceTypeId]]
    id: String
    key: String
}
interface ShippingMethodReference [[ShippingMethodReference.svg]]  {
    typeId: [[ReferenceTypeId.svg ReferenceTypeId]]
    id: String
    obj: [[ShippingMethod.svg ShippingMethod]]
}
interface ShippingMethodResourceIdentifier [[ShippingMethodResourceIdentifier.svg]]  {
    typeId: [[ReferenceTypeId.svg ReferenceTypeId]]
    id: String
    key: String
}
interface ShoppingListReference [[ShoppingListReference.svg]]  {
    typeId: [[ReferenceTypeId.svg ReferenceTypeId]]
    id: String
    obj: [[ShoppingList.svg ShoppingList]]
}
interface ShoppingListResourceIdentifier [[ShoppingListResourceIdentifier.svg]]  {
    typeId: [[ReferenceTypeId.svg ReferenceTypeId]]
    id: String
    key: String
}
interface StagedQuoteReference [[StagedQuoteReference.svg]]  {
    typeId: [[ReferenceTypeId.svg ReferenceTypeId]]
    id: String
    obj: [[StagedQuote.svg StagedQuote]]
}
interface StagedQuoteResourceIdentifier [[StagedQuoteResourceIdentifier.svg]]  {
    typeId: [[ReferenceTypeId.svg ReferenceTypeId]]
    id: String
    key: String
}
interface StandalonePriceReference [[StandalonePriceReference.svg]]  {
    typeId: [[ReferenceTypeId.svg ReferenceTypeId]]
    id: String
    obj: [[StandalonePrice.svg StandalonePrice]]
}
interface StandalonePriceResourceIdentifier [[StandalonePriceResourceIdentifier.svg]]  {
    typeId: [[ReferenceTypeId.svg ReferenceTypeId]]
    id: String
    key: String
}
interface StateReference [[StateReference.svg]]  {
    typeId: [[ReferenceTypeId.svg ReferenceTypeId]]
    id: String
    obj: [[State.svg State]]
}
interface StateResourceIdentifier [[StateResourceIdentifier.svg]]  {
    typeId: [[ReferenceTypeId.svg ReferenceTypeId]]
    id: String
    key: String
}
interface StoreKeyReference [[StoreKeyReference.svg]]  {
    typeId: [[ReferenceTypeId.svg ReferenceTypeId]]
    key: String
}
interface StoreReference [[StoreReference.svg]]  {
    typeId: [[ReferenceTypeId.svg ReferenceTypeId]]
    id: String
    obj: [[Store.svg Store]]
}
interface StoreResourceIdentifier [[StoreResourceIdentifier.svg]]  {
    typeId: [[ReferenceTypeId.svg ReferenceTypeId]]
    id: String
    key: String
}
interface TaxCategoryReference [[TaxCategoryReference.svg]]  {
    typeId: [[ReferenceTypeId.svg ReferenceTypeId]]
    id: String
    obj: [[TaxCategory.svg TaxCategory]]
}
interface TaxCategoryResourceIdentifier [[TaxCategoryResourceIdentifier.svg]]  {
    typeId: [[ReferenceTypeId.svg ReferenceTypeId]]
    id: String
    key: String
}
interface TypeReference [[TypeReference.svg]]  {
    typeId: [[ReferenceTypeId.svg ReferenceTypeId]]
    id: String
    obj: [[Type.svg Type]]
}
interface TypeResourceIdentifier [[TypeResourceIdentifier.svg]]  {
    typeId: [[ReferenceTypeId.svg ReferenceTypeId]]
    id: String
    key: String
}
interface ZoneReference [[ZoneReference.svg]]  {
    typeId: [[ReferenceTypeId.svg ReferenceTypeId]]
    id: String
    obj: [[Zone.svg Zone]]
}
interface ZoneResourceIdentifier [[ZoneResourceIdentifier.svg]]  {
    typeId: [[ReferenceTypeId.svg ReferenceTypeId]]
    id: String
    key: String
}
ReferenceTypeId --> AssociateRoleKeyReference #green;text:green : "typeId"
ReferenceTypeId --> AssociateRoleReference #green;text:green : "typeId"
ReferenceTypeId --> AssociateRoleResourceIdentifier #green;text:green : "typeId"
ReferenceTypeId --> AttributeGroupReference #green;text:green : "typeId"
ReferenceTypeId --> AttributeGroupResourceIdentifier #green;text:green : "typeId"
ReferenceTypeId --> BusinessUnitKeyReference #green;text:green : "typeId"
ReferenceTypeId --> BusinessUnitReference #green;text:green : "typeId"
ReferenceTypeId --> BusinessUnitResourceIdentifier #green;text:green : "typeId"
ReferenceTypeId --> CartDiscountReference #green;text:green : "typeId"
ReferenceTypeId --> CartDiscountResourceIdentifier #green;text:green : "typeId"
ReferenceTypeId --> CartReference #green;text:green : "typeId"
ReferenceTypeId --> CartResourceIdentifier #green;text:green : "typeId"
ReferenceTypeId --> DirectDiscountReference #green;text:green : "typeId"
ReferenceTypeId --> ReservationReference #green;text:green : "typeId"
ReferenceTypeId --> CategoryReference #green;text:green : "typeId"
ReferenceTypeId --> CategoryResourceIdentifier #green;text:green : "typeId"
ReferenceTypeId --> ChannelReference #green;text:green : "typeId"
ReferenceTypeId --> ChannelResourceIdentifier #green;text:green : "typeId"
ReferenceTypeId --> KeyReference #green;text:green : "typeId"
ReferenceTypeId --> Reference #green;text:green : "typeId"
ReferenceTypeId --> ResourceIdentifier #green;text:green : "typeId"
ReferenceTypeId --> CustomObjectReference #green;text:green : "typeId"
ReferenceTypeId --> CustomerGroupReference #green;text:green : "typeId"
ReferenceTypeId --> CustomerGroupResourceIdentifier #green;text:green : "typeId"
ReferenceTypeId --> CustomerEmailTokenReference #green;text:green : "typeId"
ReferenceTypeId --> CustomerPasswordTokenReference #green;text:green : "typeId"
ReferenceTypeId --> CustomerReference #green;text:green : "typeId"
ReferenceTypeId --> CustomerResourceIdentifier #green;text:green : "typeId"
ReferenceTypeId --> DiscountCodeReference #green;text:green : "typeId"
ReferenceTypeId --> DiscountCodeResourceIdentifier #green;text:green : "typeId"
ReferenceTypeId --> DiscountGroupReference #green;text:green : "typeId"
ReferenceTypeId --> DiscountGroupResourceIdentifier #green;text:green : "typeId"
ReferenceTypeId --> MaxResourceLimitExceededError #green;text:green : "exceededResource"
ReferenceTypeId --> ReferenceExistsError #green;text:green : "referencedBy"
ReferenceTypeId --> ReferencedResourceNotFoundError #green;text:green : "typeId"
ReferenceTypeId --> GraphQLMaxResourceLimitExceededError #green;text:green : "exceededResource"
ReferenceTypeId --> GraphQLReferenceExistsError #green;text:green : "referencedBy"
ReferenceTypeId --> GraphQLReferencedResourceNotFoundError #green;text:green : "typeId"
ReferenceTypeId --> ExtensionReference #green;text:green : "typeId"
ReferenceTypeId --> ExtensionResourceIdentifier #green;text:green : "typeId"
ReferenceTypeId --> InventoryEntryReference #green;text:green : "typeId"
ReferenceTypeId --> InventoryEntryResourceIdentifier #green;text:green : "typeId"
ReferenceTypeId --> OrderEditReference #green;text:green : "typeId"
ReferenceTypeId --> OrderEditResourceIdentifier #green;text:green : "typeId"
ReferenceTypeId --> OrderReference #green;text:green : "typeId"
ReferenceTypeId --> PaymentMethodReference #green;text:green : "typeId"
ReferenceTypeId --> PaymentReference #green;text:green : "typeId"
ReferenceTypeId --> PaymentResourceIdentifier #green;text:green : "typeId"
ReferenceTypeId --> ProductDiscountReference #green;text:green : "typeId"
ReferenceTypeId --> ProductDiscountResourceIdentifier #green;text:green : "typeId"
ReferenceTypeId --> ProductSelectionReference #green;text:green : "typeId"
ReferenceTypeId --> ProductSelectionResourceIdentifier #green;text:green : "typeId"
ReferenceTypeId --> ProductTailoringReference #green;text:green : "typeId"
ReferenceTypeId --> ProductTailoringResourceIdentifier #green;text:green : "typeId"
ReferenceTypeId --> ProductTypeReference #green;text:green : "typeId"
ReferenceTypeId --> ProductTypeResourceIdentifier #green;text:green : "typeId"
ReferenceTypeId --> ProductReference #green;text:green : "typeId"
ReferenceTypeId --> ProductResourceIdentifier #green;text:green : "typeId"
ReferenceTypeId --> QuoteRequestReference #green;text:green : "typeId"
ReferenceTypeId --> QuoteRequestResourceIdentifier #green;text:green : "typeId"
ReferenceTypeId --> QuoteReference #green;text:green : "typeId"
ReferenceTypeId --> QuoteResourceIdentifier #green;text:green : "typeId"
ReferenceTypeId --> RecurrencePolicyReference #green;text:green : "typeId"
ReferenceTypeId --> RecurrencePolicyResourceIdentifier #green;text:green : "typeId"
ReferenceTypeId --> RecurringOrderReference #green;text:green : "typeId"
ReferenceTypeId --> RecurringOrderResourceIdentifier #green;text:green : "typeId"
ReferenceTypeId --> ReviewReference #green;text:green : "typeId"
ReferenceTypeId --> ReviewResourceIdentifier #green;text:green : "typeId"
ReferenceTypeId --> ShippingMethodReference #green;text:green : "typeId"
ReferenceTypeId --> ShippingMethodResourceIdentifier #green;text:green : "typeId"
ReferenceTypeId --> ShoppingListReference #green;text:green : "typeId"
ReferenceTypeId --> ShoppingListResourceIdentifier #green;text:green : "typeId"
ReferenceTypeId --> StagedQuoteReference #green;text:green : "typeId"
ReferenceTypeId --> StagedQuoteResourceIdentifier #green;text:green : "typeId"
ReferenceTypeId --> StandalonePriceReference #green;text:green : "typeId"
ReferenceTypeId --> StandalonePriceResourceIdentifier #green;text:green : "typeId"
ReferenceTypeId --> StateReference #green;text:green : "typeId"
ReferenceTypeId --> StateResourceIdentifier #green;text:green : "typeId"
ReferenceTypeId --> StoreKeyReference #green;text:green : "typeId"
ReferenceTypeId --> StoreReference #green;text:green : "typeId"
ReferenceTypeId --> StoreResourceIdentifier #green;text:green : "typeId"
ReferenceTypeId --> TaxCategoryReference #green;text:green : "typeId"
ReferenceTypeId --> TaxCategoryResourceIdentifier #green;text:green : "typeId"
ReferenceTypeId --> TypeReference #green;text:green : "typeId"
ReferenceTypeId --> TypeResourceIdentifier #green;text:green : "typeId"
ReferenceTypeId --> ZoneReference #green;text:green : "typeId"
ReferenceTypeId --> ZoneResourceIdentifier #green;text:green : "typeId"
@enduml
