@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface ResourceDeletedDeliveryPayload [[ResourceDeletedDeliveryPayload.svg]] extends DeliveryPayload {
    notificationType: String
    projectKey: String
    resource: [[Reference.svg Reference]]
    resourceUserProvidedIdentifiers: [[UserProvidedIdentifiers.svg UserProvidedIdentifiers]]
    version: Long
    modifiedAt: DateTime
    dataErasure: Boolean
}
interface DeliveryPayload [[DeliveryPayload.svg]]  {
    notificationType: String
}





@enduml
