@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface ReturnInfoDraft [[ReturnInfoDraft.svg]]  {
    items: [[ReturnItemDraft.svg List<ReturnItemDraft>]]
    returnTrackingId: String
    returnDate: DateTime
}



interface StagedOrderSetReturnInfoAction [[StagedOrderSetReturnInfoAction.svg]]  {
    action: String
    items: [[ReturnInfoDraft.svg List<ReturnInfoDraft>]]
}
interface OrderSetReturnInfoAction [[OrderSetReturnInfoAction.svg]]  {
    action: String
    items: [[ReturnInfoDraft.svg List<ReturnInfoDraft>]]
}

ReturnInfoDraft --> StagedOrderSetReturnInfoAction #green;text:green : "items"
ReturnInfoDraft --> StagedOrderSetReturnInfoAction #green;text:green : "items"
ReturnInfoDraft --> OrderSetReturnInfoAction #green;text:green : "items"
ReturnInfoDraft --> OrderSetReturnInfoAction #green;text:green : "items"
@enduml
