@startuml

hide methods
enum ReturnShipmentState {
    ADVISED
    RETURNED
    BACK_IN_STOCK
    UNUSABLE
}
interface OrderReturnShipmentStateChangedMessage [[OrderReturnShipmentStateChangedMessage.svg]]  {
    id: String
    version: Long
    createdAt: DateTime
    lastModifiedAt: DateTime
    lastModifiedBy: [[LastModifiedBy.svg LastModifiedBy]]
    createdBy: [[CreatedBy.svg CreatedBy]]
    sequenceNumber: Long
    resource: [[Reference.svg Reference]]
    resourceVersion: Long
    type: String
    resourceUserProvidedIdentifiers: [[UserProvidedIdentifiers.svg UserProvidedIdentifiers]]
    returnItemId: String
    returnShipmentState: [[ReturnShipmentState.svg ReturnShipmentState]]
}
interface OrderReturnShipmentStateChangedMessagePayload [[OrderReturnShipmentStateChangedMessagePayload.svg]]  {
    type: String
    returnItemId: String
    returnShipmentState: [[ReturnShipmentState.svg ReturnShipmentState]]
}
ReturnShipmentState --> OrderReturnShipmentStateChangedMessage #green;text:green : "returnShipmentState"
ReturnShipmentState --> OrderReturnShipmentStateChangedMessagePayload #green;text:green : "returnShipmentState"
@enduml
