@startuml

hide methods
enum SearchIndexingConfigurationStatus {
    ACTIVATED
    DEACTIVATED
    INDEXING
}
interface SearchIndexingConfigurationValues [[SearchIndexingConfigurationValues.svg]]  {
    status: [[SearchIndexingConfigurationStatus.svg SearchIndexingConfigurationStatus]]
    lastModifiedAt: DateTime
    lastModifiedBy: [[LastModifiedBy.svg LastModifiedBy]]
}
SearchIndexingConfigurationStatus --> SearchIndexingConfigurationValues #green;text:green : "status"
@enduml
