@startuml

hide methods
enum SearchSortOrder {
    ASC
    DESC
}
interface ProductSearchFacetDistinctBucketSortExpression [[ProductSearchFacetDistinctBucketSortExpression.svg]]  {
    by: [[ProductSearchFacetDistinctBucketSortBy.svg ProductSearchFacetDistinctBucketSortBy]]
    order: [[SearchSortOrder.svg SearchSortOrder]]
}
interface SearchSorting [[SearchSorting.svg]]  {
    field: String
    language: String
    order: [[SearchSortOrder.svg SearchSortOrder]]
    mode: [[SearchSortMode.svg SearchSortMode]]
    fieldType: [[SearchFieldType.svg SearchFieldType]]
    filter: [[SearchQueryExpression.svg SearchQueryExpression]]
}
SearchSortOrder --> ProductSearchFacetDistinctBucketSortExpression #green;text:green : "order"
SearchSortOrder --> SearchSorting #green;text:green : "order"
@enduml
