@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface SearchCompoundExpression [[SearchCompoundExpression.svg]] extends SearchQuery {
}
interface SearchQuery [[SearchQuery.svg]]  {
}
interface SearchAndExpression [[SearchAndExpression.svg]] extends SearchCompoundExpression {
    and: [[SearchQuery.svg List<SearchQuery>]]
}
interface SearchFilterExpression [[SearchFilterExpression.svg]] extends SearchCompoundExpression {
    filter: [[SearchQueryExpression.svg List<SearchQueryExpression>]]
}
interface SearchNotExpression [[SearchNotExpression.svg]] extends SearchCompoundExpression {
    not: [[SearchQuery.svg List<SearchQuery>]]
}
interface SearchOrExpression [[SearchOrExpression.svg]] extends SearchCompoundExpression {
    or: [[SearchQuery.svg List<SearchQuery>]]
}




@enduml
