@startuml

hide methods
enum SearchMatchType {
    ANY
    ALL
}
interface SearchFuzzyValue [[SearchFuzzyValue.svg]]  {
    field: String
    boost: Double
    fieldType: [[SearchFieldType.svg SearchFieldType]]
    value: [[Object.svg Object]]
    level: Integer
    language: String
    mustMatch: [[SearchMatchType.svg SearchMatchType]]
}
SearchMatchType --> SearchFuzzyValue #green;text:green : "mustMatch"
@enduml
