@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface SearchSorting [[SearchSorting.svg]]  {
    field: String
    language: String
    order: [[SearchSortOrder.svg SearchSortOrder]]
    mode: [[SearchSortMode.svg SearchSortMode]]
    fieldType: [[SearchFieldType.svg SearchFieldType]]
    filter: [[SearchQueryExpression.svg SearchQueryExpression]]
}



interface ProductSearchRequest [[ProductSearchRequest.svg]]  {
    query: [[SearchQuery.svg SearchQuery]]
    sort: [[SearchSorting.svg List<SearchSorting>]]
    limit: Integer
    offset: Integer
    markMatchingVariants: Boolean
    productProjectionParameters: [[ProductSearchProjectionParams.svg ProductSearchProjectionParams]]
    facets: [[ProductSearchFacetExpression.svg List<ProductSearchFacetExpression>]]
}

SearchSorting --> ProductSearchRequest #green;text:green : "sort"
@enduml
