@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface SearchExistsValue [[SearchExistsValue.svg]] extends SearchQueryExpressionValue {
    field: String
    boost: Double
    fieldType: [[SearchFieldType.svg SearchFieldType]]
    language: String
}
interface SearchQueryExpressionValue [[SearchQueryExpressionValue.svg]]  {
    field: String
    boost: Double
    fieldType: [[SearchFieldType.svg SearchFieldType]]
}





@enduml
