@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface SearchQueryExpression [[SearchQueryExpression.svg]] extends SearchQuery {
}
interface SearchQuery [[SearchQuery.svg]]  {
}
interface SearchDateRangeExpression [[SearchDateRangeExpression.svg]] extends SearchQueryExpression {
    range: [[SearchDateRangeValue.svg SearchDateRangeValue]]
}
interface SearchDateTimeRangeExpression [[SearchDateTimeRangeExpression.svg]] extends SearchQueryExpression {
    range: [[SearchDateTimeRangeValue.svg SearchDateTimeRangeValue]]
}
interface SearchExactExpression [[SearchExactExpression.svg]] extends SearchQueryExpression {
    exact: [[SearchExactValue.svg SearchExactValue]]
}
interface SearchExistsExpression [[SearchExistsExpression.svg]] extends SearchQueryExpression {
    exists: [[SearchExistsValue.svg SearchExistsValue]]
}
interface SearchFullTextExpression [[SearchFullTextExpression.svg]] extends SearchQueryExpression {
    fullText: [[SearchFullTextValue.svg SearchFullTextValue]]
}
interface SearchFullTextPrefixExpression [[SearchFullTextPrefixExpression.svg]] extends SearchQueryExpression {
    fullTextPrefix: [[SearchFullTextPrefixValue.svg SearchFullTextPrefixValue]]
}
interface SearchLongRangeExpression [[SearchLongRangeExpression.svg]] extends SearchQueryExpression {
    range: [[SearchLongRangeValue.svg SearchLongRangeValue]]
}
interface SearchNumberRangeExpression [[SearchNumberRangeExpression.svg]] extends SearchQueryExpression {
    range: [[SearchNumberRangeValue.svg SearchNumberRangeValue]]
}
interface SearchPrefixExpression [[SearchPrefixExpression.svg]] extends SearchQueryExpression {
    prefix: [[SearchAnyValue.svg SearchAnyValue]]
}
interface SearchTimeRangeExpression [[SearchTimeRangeExpression.svg]] extends SearchQueryExpression {
    range: [[SearchTimeRangeValue.svg SearchTimeRangeValue]]
}
interface SearchWildCardExpression [[SearchWildCardExpression.svg]] extends SearchQueryExpression {
    wildcard: [[SearchAnyValue.svg SearchAnyValue]]
}

interface SearchFilterExpression [[SearchFilterExpression.svg]]  {
    filter: [[SearchQueryExpression.svg List<SearchQueryExpression>]]
}

SearchQueryExpression --> SearchFilterExpression #green;text:green : "filter"
SearchQueryExpression --> SearchFilterExpression #green;text:green : "filter"
@enduml
