@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface ShippingRateInputDraft [[ShippingRateInputDraft.svg]]  {
    type: String
}


interface ClassificationShippingRateInputDraft [[ClassificationShippingRateInputDraft.svg]]  {
    type: String
    key: String
}
interface ScoreShippingRateInputDraft [[ScoreShippingRateInputDraft.svg]]  {
    type: String
    score: Long
}
interface CartDraft [[CartDraft.svg]]  {
    currency: String
    key: String
    customerId: String
    customerEmail: String
    customerGroup: [[CustomerGroupResourceIdentifier.svg CustomerGroupResourceIdentifier]]
    anonymousId: String
    businessUnit: [[BusinessUnitResourceIdentifier.svg BusinessUnitResourceIdentifier]]
    store: [[StoreResourceIdentifier.svg StoreResourceIdentifier]]
    country: String
    inventoryMode: [[InventoryMode.svg InventoryMode]]
    taxMode: [[TaxMode.svg TaxMode]]
    taxRoundingMode: [[RoundingMode.svg RoundingMode]]
    taxCalculationMode: [[TaxCalculationMode.svg TaxCalculationMode]]
    lineItems: [[LineItemDraft.svg List<LineItemDraft>]]
    customLineItems: [[CustomLineItemDraft.svg List<CustomLineItemDraft>]]
    shippingAddress: [[BaseAddress.svg BaseAddress]]
    billingAddress: [[BaseAddress.svg BaseAddress]]
    shippingMethod: [[ShippingMethodResourceIdentifier.svg ShippingMethodResourceIdentifier]]
    externalTaxRateForShippingMethod: [[ExternalTaxRateDraft.svg ExternalTaxRateDraft]]
    custom: [[CustomFieldsDraft.svg CustomFieldsDraft]]
    locale: String
    deleteDaysAfterLastModification: Long
    origin: [[CartOrigin.svg CartOrigin]]
    shippingMode: [[ShippingMode.svg ShippingMode]]
    customShipping: [[CustomShippingDraft.svg List<CustomShippingDraft>]]
    shipping: [[ShippingDraft.svg List<ShippingDraft>]]
    shippingRateInput: [[ShippingRateInputDraft.svg ShippingRateInputDraft]]
    itemShippingAddresses: [[BaseAddress.svg List<BaseAddress>]]
    discountCodes: [[String.svg List<String>]]
}
interface CustomShippingDraft [[CustomShippingDraft.svg]]  {
    key: String
    shippingMethodName: String
    shippingAddress: [[BaseAddress.svg BaseAddress]]
    shippingRate: [[ShippingRateDraft.svg ShippingRateDraft]]
    shippingRateInput: [[ShippingRateInputDraft.svg ShippingRateInputDraft]]
    taxCategory: [[TaxCategoryResourceIdentifier.svg TaxCategoryResourceIdentifier]]
    externalTaxRate: String
    deliveries: [[Delivery.svg List<Delivery>]]
    custom: String
}
interface ShippingDraft [[ShippingDraft.svg]]  {
    key: String
    shippingMethod: [[ShippingMethodReference.svg ShippingMethodReference]]
    shippingAddress: [[BaseAddress.svg BaseAddress]]
    shippingRateInput: [[ShippingRateInputDraft.svg ShippingRateInputDraft]]
    externalTaxRate: String
    deliveries: [[Delivery.svg List<Delivery>]]
    custom: String
}
interface CartAddCustomShippingMethodAction [[CartAddCustomShippingMethodAction.svg]]  {
    action: String
    shippingKey: String
    shippingMethodName: String
    shippingAddress: [[BaseAddress.svg BaseAddress]]
    shippingRate: [[ShippingRateDraft.svg ShippingRateDraft]]
    shippingRateInput: [[ShippingRateInputDraft.svg ShippingRateInputDraft]]
    taxCategory: [[TaxCategoryResourceIdentifier.svg TaxCategoryResourceIdentifier]]
    externalTaxRate: String
    deliveries: [[Delivery.svg List<Delivery>]]
    custom: String
}
interface CartAddShippingMethodAction [[CartAddShippingMethodAction.svg]]  {
    action: String
    shippingKey: String
    shippingMethod: [[ShippingMethodReference.svg ShippingMethodReference]]
    shippingAddress: [[BaseAddress.svg BaseAddress]]
    shippingRateInput: [[ShippingRateInputDraft.svg ShippingRateInputDraft]]
    externalTaxRate: String
    deliveries: [[Delivery.svg List<Delivery>]]
    custom: String
}
interface CartSetShippingRateInputAction [[CartSetShippingRateInputAction.svg]]  {
    action: String
    shippingRateInput: [[ShippingRateInputDraft.svg ShippingRateInputDraft]]
}
ShippingRateInputDraft --> ClassificationShippingRateInputDraft #blue;text:blue : "type : Classification"
ShippingRateInputDraft --> ScoreShippingRateInputDraft #blue;text:blue : "type : Score"
ShippingRateInputDraft --> CartDraft #green;text:green : "shippingRateInput"
ShippingRateInputDraft --> CustomShippingDraft #green;text:green : "shippingRateInput"
ShippingRateInputDraft --> ShippingDraft #green;text:green : "shippingRateInput"
ShippingRateInputDraft --> CartAddCustomShippingMethodAction #green;text:green : "shippingRateInput"
ShippingRateInputDraft --> CartAddShippingMethodAction #green;text:green : "shippingRateInput"
ShippingRateInputDraft --> CartSetShippingRateInputAction #green;text:green : "shippingRateInput"
@enduml
