@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface ShippingMethodSetKeyAction [[ShippingMethodSetKeyAction.svg]] extends ShippingMethodUpdateAction {
    action: String
    key: String
}
interface ShippingMethodUpdateAction [[ShippingMethodUpdateAction.svg]]  {
    action: String
}





@enduml
