@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface ShoppingListAddTextLineItemAction [[ShoppingListAddTextLineItemAction.svg]] extends ShoppingListUpdateAction {
    action: String
    name: [[LocalizedString.svg LocalizedString]]
    key: String
    description: [[LocalizedString.svg LocalizedString]]
    quantity: Long
    addedAt: DateTime
    custom: [[CustomFieldsDraft.svg CustomFieldsDraft]]
}
interface ShoppingListUpdateAction [[ShoppingListUpdateAction.svg]]  {
    action: String
}





@enduml
