@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface StagedOrderSetBillingAddressAction [[StagedOrderSetBillingAddressAction.svg]] extends StagedOrderUpdateAction {
    action: String
    address: [[BaseAddress.svg BaseAddress]]
}
interface StagedOrderUpdateAction [[StagedOrderUpdateAction.svg]]  {
    action: String
}





@enduml
