@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface StagedQuoteSetCustomTypeAction [[StagedQuoteSetCustomTypeAction.svg]] extends StagedQuoteUpdateAction {
    action: String
    type: [[TypeResourceIdentifier.svg TypeResourceIdentifier]]
    fields: [[FieldContainer.svg FieldContainer]]
}
interface StagedQuoteUpdateAction [[StagedQuoteUpdateAction.svg]]  {
    action: String
}





@enduml
