@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface StagedOrderAddLineItemAction [[StagedOrderAddLineItemAction.svg]] extends StagedOrderUpdateAction {
    action: String
    key: String
    custom: [[CustomFieldsDraft.svg CustomFieldsDraft]]
    distributionChannel: [[ChannelResourceIdentifier.svg ChannelResourceIdentifier]]
    externalTaxRate: [[ExternalTaxRateDraft.svg ExternalTaxRateDraft]]
    productId: String
    variantId: Long
    sku: String
    quantity: Long
    addedAt: DateTime
    supplyChannel: [[ChannelResourceIdentifier.svg ChannelResourceIdentifier]]
    externalPrice: [[Money.svg Money]]
    externalTotalPrice: [[ExternalLineItemTotalPrice.svg ExternalLineItemTotalPrice]]
    shippingDetails: [[ItemShippingDetailsDraft.svg ItemShippingDetailsDraft]]
}
interface StagedOrderUpdateAction [[StagedOrderUpdateAction.svg]]  {
    action: String
}





@enduml
