@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface StagedOrderImportCustomLineItemStateAction [[StagedOrderImportCustomLineItemStateAction.svg]] extends StagedOrderUpdateAction {
    action: String
    customLineItemId: String
    state: [[ItemState.svg List<ItemState>]]
}
interface StagedOrderUpdateAction [[StagedOrderUpdateAction.svg]]  {
    action: String
}





@enduml
