@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface StagedQuoteStateChangedMessagePayload [[StagedQuoteStateChangedMessagePayload.svg]] extends MessagePayload {
    type: String
    stagedQuoteState: [[StagedQuoteState.svg StagedQuoteState]]
    oldStagedQuoteState: [[StagedQuoteState.svg StagedQuoteState]]
}
interface MessagePayload [[MessagePayload.svg]]  {
    type: String
}





@enduml
