@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface StagedQuoteTransitionStateAction [[StagedQuoteTransitionStateAction.svg]] extends StagedQuoteUpdateAction {
    action: String
    state: [[StateResourceIdentifier.svg StateResourceIdentifier]]
    force: Boolean
}
interface StagedQuoteUpdateAction [[StagedQuoteUpdateAction.svg]]  {
    action: String
}





@enduml
