@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface StagedOrderSetParcelMeasurementsAction [[StagedOrderSetParcelMeasurementsAction.svg]] extends StagedOrderUpdateAction {
    action: String
    parcelId: String
    measurements: [[ParcelMeasurements.svg ParcelMeasurements]]
}
interface StagedOrderUpdateAction [[StagedOrderUpdateAction.svg]]  {
    action: String
}





@enduml
