@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface StagedOrderSetShippingCustomFieldAction [[StagedOrderSetShippingCustomFieldAction.svg]] extends StagedOrderUpdateAction {
    action: String
    shippingKey: String
    name: String
    value: [[Object.svg Object]]
}
interface StagedOrderUpdateAction [[StagedOrderUpdateAction.svg]]  {
    action: String
}





@enduml
