@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface StandalonePriceRemoveStagedChangesAction [[StandalonePriceRemoveStagedChangesAction.svg]] extends StandalonePriceUpdateAction {
    action: String
}
interface StandalonePriceUpdateAction [[StandalonePriceUpdateAction.svg]]  {
    action: String
}





@enduml
