@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface StandalonePriceSetValidFromAndUntilAction [[StandalonePriceSetValidFromAndUntilAction.svg]] extends StandalonePriceUpdateAction {
    action: String
    validFrom: DateTime
    validUntil: DateTime
}
interface StandalonePriceUpdateAction [[StandalonePriceUpdateAction.svg]]  {
    action: String
}





@enduml
