@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface StateUpdateAction [[StateUpdateAction.svg]]  {
    action: String
}


interface StateAddRolesAction [[StateAddRolesAction.svg]]  {
    action: String
    roles: [[StateRoleEnum.svg List<StateRoleEnum>]]
}
interface StateChangeInitialAction [[StateChangeInitialAction.svg]]  {
    action: String
    initial: Boolean
}
interface StateChangeKeyAction [[StateChangeKeyAction.svg]]  {
    action: String
    key: String
}
interface StateChangeTypeAction [[StateChangeTypeAction.svg]]  {
    action: String
    type: [[StateTypeEnum.svg StateTypeEnum]]
}
interface StateRemoveRolesAction [[StateRemoveRolesAction.svg]]  {
    action: String
    roles: [[StateRoleEnum.svg List<StateRoleEnum>]]
}
interface StateSetDescriptionAction [[StateSetDescriptionAction.svg]]  {
    action: String
    description: [[LocalizedString.svg LocalizedString]]
}
interface StateSetNameAction [[StateSetNameAction.svg]]  {
    action: String
    name: [[LocalizedString.svg LocalizedString]]
}
interface StateSetRolesAction [[StateSetRolesAction.svg]]  {
    action: String
    roles: [[StateRoleEnum.svg List<StateRoleEnum>]]
}
interface StateSetTransitionsAction [[StateSetTransitionsAction.svg]]  {
    action: String
    transitions: [[StateResourceIdentifier.svg List<StateResourceIdentifier>]]
}
interface StateUpdate [[StateUpdate.svg]]  {
    version: Long
    actions: [[StateUpdateAction.svg List<StateUpdateAction>]]
}
StateUpdateAction --> StateAddRolesAction #blue;text:blue : "action : addRoles"
StateUpdateAction --> StateChangeInitialAction #blue;text:blue : "action : changeInitial"
StateUpdateAction --> StateChangeKeyAction #blue;text:blue : "action : changeKey"
StateUpdateAction --> StateChangeTypeAction #blue;text:blue : "action : changeType"
StateUpdateAction --> StateRemoveRolesAction #blue;text:blue : "action : removeRoles"
StateUpdateAction --> StateSetDescriptionAction #blue;text:blue : "action : setDescription"
StateUpdateAction --> StateSetNameAction #blue;text:blue : "action : setName"
StateUpdateAction --> StateSetRolesAction #blue;text:blue : "action : setRoles"
StateUpdateAction --> StateSetTransitionsAction #blue;text:blue : "action : setTransitions"
StateUpdateAction --> StateUpdate #green;text:green : "actions"
@enduml
