@startuml

hide methods
enum StateRoleEnum {
    REVIEW_INCLUDED_IN_STATISTICS
    RETURN
}
interface State [[State.svg]]  {
    id: String
    version: Long
    createdAt: DateTime
    lastModifiedAt: DateTime
    lastModifiedBy: [[LastModifiedBy.svg LastModifiedBy]]
    createdBy: [[CreatedBy.svg CreatedBy]]
    key: String
    type: [[StateTypeEnum.svg StateTypeEnum]]
    name: [[LocalizedString.svg LocalizedString]]
    description: [[LocalizedString.svg LocalizedString]]
    initial: Boolean
    builtIn: Boolean
    roles: [[StateRoleEnum.svg List<StateRoleEnum>]]
    transitions: [[StateReference.svg List<StateReference>]]
}
interface StateDraft [[StateDraft.svg]]  {
    key: String
    type: [[StateTypeEnum.svg StateTypeEnum]]
    name: [[LocalizedString.svg LocalizedString]]
    description: [[LocalizedString.svg LocalizedString]]
    initial: Boolean
    roles: [[StateRoleEnum.svg List<StateRoleEnum>]]
    transitions: [[StateResourceIdentifier.svg List<StateResourceIdentifier>]]
}
interface StateAddRolesAction [[StateAddRolesAction.svg]]  {
    action: String
    roles: [[StateRoleEnum.svg List<StateRoleEnum>]]
}
interface StateRemoveRolesAction [[StateRemoveRolesAction.svg]]  {
    action: String
    roles: [[StateRoleEnum.svg List<StateRoleEnum>]]
}
interface StateSetRolesAction [[StateSetRolesAction.svg]]  {
    action: String
    roles: [[StateRoleEnum.svg List<StateRoleEnum>]]
}
StateRoleEnum --> State #green;text:green : "roles"
StateRoleEnum --> StateDraft #green;text:green : "roles"
StateRoleEnum --> StateAddRolesAction #green;text:green : "roles"
StateRoleEnum --> StateRemoveRolesAction #green;text:green : "roles"
StateRoleEnum --> StateSetRolesAction #green;text:green : "roles"
@enduml
