@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface StoreResourceIdentifier [[StoreResourceIdentifier.svg]] extends ResourceIdentifier {
    typeId: [[ReferenceTypeId.svg ReferenceTypeId]]
    id: String
    key: String
}
interface ResourceIdentifier [[ResourceIdentifier.svg]]  {
    typeId: [[ReferenceTypeId.svg ReferenceTypeId]]
    id: String
    key: String
}


interface BusinessUnitDraft [[BusinessUnitDraft.svg]]  {
    key: String
    status: [[BusinessUnitStatus.svg BusinessUnitStatus]]
    stores: [[StoreResourceIdentifier.svg List<StoreResourceIdentifier>]]
    storeMode: [[BusinessUnitStoreMode.svg BusinessUnitStoreMode]]
    unitType: [[BusinessUnitType.svg BusinessUnitType]]
    name: String
    contactEmail: String
    associateMode: [[BusinessUnitAssociateMode.svg BusinessUnitAssociateMode]]
    associates: [[AssociateDraft.svg List<AssociateDraft>]]
    addresses: [[BaseAddress.svg List<BaseAddress>]]
    shippingAddresses: [[Integer.svg List<Integer>]]
    defaultShippingAddress: Integer
    billingAddresses: [[Integer.svg List<Integer>]]
    defaultBillingAddress: Integer
    custom: [[CustomFieldsDraft.svg CustomFieldsDraft]]
}
interface BusinessUnitSetStoreModeAction [[BusinessUnitSetStoreModeAction.svg]]  {
    action: String
    storeMode: [[BusinessUnitStoreMode.svg BusinessUnitStoreMode]]
    stores: [[StoreResourceIdentifier.svg List<StoreResourceIdentifier>]]
}
interface BusinessUnitSetStoresAction [[BusinessUnitSetStoresAction.svg]]  {
    action: String
    stores: [[StoreResourceIdentifier.svg List<StoreResourceIdentifier>]]
}
interface CartDiscountDraft [[CartDiscountDraft.svg]]  {
    name: [[LocalizedString.svg LocalizedString]]
    key: String
    description: [[LocalizedString.svg LocalizedString]]
    value: [[CartDiscountValueDraft.svg CartDiscountValueDraft]]
    cartPredicate: String
    target: [[CartDiscountTarget.svg CartDiscountTarget]]
    sortOrder: String
    stores: [[StoreResourceIdentifier.svg List<StoreResourceIdentifier>]]
    isActive: Boolean
    validFrom: DateTime
    validUntil: DateTime
    requiresDiscountCode: Boolean
    stackingMode: [[StackingMode.svg StackingMode]]
    custom: [[CustomFieldsDraft.svg CustomFieldsDraft]]
}
interface CartDiscountSetStoresAction [[CartDiscountSetStoresAction.svg]]  {
    action: String
    stores: [[StoreResourceIdentifier.svg List<StoreResourceIdentifier>]]
}
interface CustomerDraft [[CustomerDraft.svg]]  {
    key: String
    customerNumber: String
    externalId: String
    email: String
    password: String
    firstName: String
    lastName: String
    middleName: String
    title: String
    anonymousCartId: String
    anonymousCart: [[CartResourceIdentifier.svg CartResourceIdentifier]]
    anonymousId: String
    dateOfBirth: Date
    companyName: String
    vatId: String
    addresses: [[BaseAddress.svg List<BaseAddress>]]
    defaultShippingAddress: Integer
    shippingAddresses: [[Integer.svg List<Integer>]]
    defaultBillingAddress: Integer
    billingAddresses: [[Integer.svg List<Integer>]]
    isEmailVerified: Boolean
    customerGroup: [[CustomerGroupResourceIdentifier.svg CustomerGroupResourceIdentifier]]
    custom: [[CustomFieldsDraft.svg CustomFieldsDraft]]
    locale: String
    salutation: String
    stores: [[StoreResourceIdentifier.svg List<StoreResourceIdentifier>]]
    authenticationMode: [[AuthenticationMode.svg AuthenticationMode]]
}
interface CustomerSetStoresAction [[CustomerSetStoresAction.svg]]  {
    action: String
    stores: [[StoreResourceIdentifier.svg List<StoreResourceIdentifier>]]
}
interface MyCustomerDraft [[MyCustomerDraft.svg]]  {
    email: String
    password: String
    firstName: String
    lastName: String
    middleName: String
    title: String
    salutation: String
    dateOfBirth: Date
    companyName: String
    vatId: String
    addresses: [[BaseAddress.svg List<BaseAddress>]]
    defaultShippingAddress: Long
    defaultBillingAddress: Long
    custom: [[CustomFieldsDraft.svg CustomFieldsDraft]]
    locale: String
    stores: [[StoreResourceIdentifier.svg List<StoreResourceIdentifier>]]
}
interface BusinessUnitAddStoreAction [[BusinessUnitAddStoreAction.svg]]  {
    action: String
    store: [[StoreResourceIdentifier.svg StoreResourceIdentifier]]
}
interface BusinessUnitRemoveStoreAction [[BusinessUnitRemoveStoreAction.svg]]  {
    action: String
    store: [[StoreResourceIdentifier.svg StoreResourceIdentifier]]
}
interface CartDiscountAddStoreAction [[CartDiscountAddStoreAction.svg]]  {
    action: String
    store: [[StoreResourceIdentifier.svg StoreResourceIdentifier]]
}
interface CartDiscountRemoveStoreAction [[CartDiscountRemoveStoreAction.svg]]  {
    action: String
    store: [[StoreResourceIdentifier.svg StoreResourceIdentifier]]
}
interface CartDraft [[CartDraft.svg]]  {
    currency: String
    key: String
    customerId: String
    customerEmail: String
    customerGroup: [[CustomerGroupResourceIdentifier.svg CustomerGroupResourceIdentifier]]
    anonymousId: String
    businessUnit: [[BusinessUnitResourceIdentifier.svg BusinessUnitResourceIdentifier]]
    store: [[StoreResourceIdentifier.svg StoreResourceIdentifier]]
    lineItems: [[LineItemDraft.svg List<LineItemDraft>]]
    customLineItems: [[CustomLineItemDraft.svg List<CustomLineItemDraft>]]
    taxMode: [[TaxMode.svg TaxMode]]
    externalTaxRateForShippingMethod: [[ExternalTaxRateDraft.svg ExternalTaxRateDraft]]
    taxRoundingMode: [[RoundingMode.svg RoundingMode]]
    taxCalculationMode: [[TaxCalculationMode.svg TaxCalculationMode]]
    inventoryMode: [[InventoryMode.svg InventoryMode]]
    billingAddress: [[BaseAddress.svg BaseAddress]]
    shippingAddress: [[BaseAddress.svg BaseAddress]]
    shippingMethod: [[ShippingMethodResourceIdentifier.svg ShippingMethodResourceIdentifier]]
    shippingRateInput: [[ShippingRateInputDraft.svg ShippingRateInputDraft]]
    shippingMode: [[ShippingMode.svg ShippingMode]]
    customShipping: [[CustomShippingDraft.svg List<CustomShippingDraft>]]
    shipping: [[ShippingDraft.svg List<ShippingDraft>]]
    itemShippingAddresses: [[BaseAddress.svg List<BaseAddress>]]
    discountCodes: [[String.svg List<String>]]
    country: String
    locale: String
    origin: [[CartOrigin.svg CartOrigin]]
    deleteDaysAfterLastModification: Long
    custom: [[CustomFieldsDraft.svg CustomFieldsDraft]]
}
interface CustomerAddStoreAction [[CustomerAddStoreAction.svg]]  {
    action: String
    store: [[StoreResourceIdentifier.svg StoreResourceIdentifier]]
}
interface CustomerRemoveStoreAction [[CustomerRemoveStoreAction.svg]]  {
    action: String
    store: [[StoreResourceIdentifier.svg StoreResourceIdentifier]]
}
interface MyCartDraft [[MyCartDraft.svg]]  {
    currency: String
    customerEmail: String
    businessUnit: [[BusinessUnitResourceIdentifier.svg BusinessUnitResourceIdentifier]]
    store: [[StoreResourceIdentifier.svg StoreResourceIdentifier]]
    lineItems: [[MyLineItemDraft.svg List<MyLineItemDraft>]]
    taxMode: [[TaxMode.svg TaxMode]]
    inventoryMode: [[InventoryMode.svg InventoryMode]]
    billingAddress: [[BaseAddress.svg BaseAddress]]
    shippingAddress: [[BaseAddress.svg BaseAddress]]
    shippingMethod: [[ShippingMethodResourceIdentifier.svg ShippingMethodResourceIdentifier]]
    itemShippingAddresses: [[BaseAddress.svg List<BaseAddress>]]
    shippingMode: [[ShippingMode.svg ShippingMode]]
    discountCodes: [[String.svg List<String>]]
    country: String
    locale: String
    deleteDaysAfterLastModification: Long
    custom: [[CustomFieldsDraft.svg CustomFieldsDraft]]
}
interface MyShoppingListDraft [[MyShoppingListDraft.svg]]  {
    name: [[LocalizedString.svg LocalizedString]]
    description: [[LocalizedString.svg LocalizedString]]
    lineItems: [[ShoppingListLineItemDraft.svg List<ShoppingListLineItemDraft>]]
    textLineItems: [[TextLineItemDraft.svg List<TextLineItemDraft>]]
    custom: [[CustomFieldsDraft.svg CustomFieldsDraft]]
    deleteDaysAfterLastModification: Long
    store: [[StoreResourceIdentifier.svg StoreResourceIdentifier]]
}
interface StagedOrderSetStoreAction [[StagedOrderSetStoreAction.svg]]  {
    action: String
    store: [[StoreResourceIdentifier.svg StoreResourceIdentifier]]
}
interface OrderImportDraft [[OrderImportDraft.svg]]  {
    orderNumber: String
    purchaseOrderNumber: String
    customerId: String
    customerEmail: String
    customerGroup: [[CustomerGroupResourceIdentifier.svg CustomerGroupResourceIdentifier]]
    businessUnit: [[BusinessUnitResourceIdentifier.svg BusinessUnitResourceIdentifier]]
    store: [[StoreResourceIdentifier.svg StoreResourceIdentifier]]
    lineItems: [[LineItemImportDraft.svg List<LineItemImportDraft>]]
    customLineItems: [[CustomLineItemImportDraft.svg List<CustomLineItemImportDraft>]]
    totalPrice: [[Money.svg Money]]
    taxedPrice: [[TaxedPriceDraft.svg TaxedPriceDraft]]
    taxRoundingMode: [[RoundingMode.svg RoundingMode]]
    taxCalculationMode: [[TaxCalculationMode.svg TaxCalculationMode]]
    inventoryMode: [[InventoryMode.svg InventoryMode]]
    billingAddress: [[BaseAddress.svg BaseAddress]]
    shippingAddress: [[BaseAddress.svg BaseAddress]]
    itemShippingAddresses: [[BaseAddress.svg List<BaseAddress>]]
    shippingInfo: [[ShippingInfoImportDraft.svg ShippingInfoImportDraft]]
    paymentInfo: [[PaymentInfo.svg PaymentInfo]]
    paymentState: [[PaymentState.svg PaymentState]]
    shipmentState: [[ShipmentState.svg ShipmentState]]
    orderState: [[OrderState.svg OrderState]]
    state: [[StateReference.svg StateReference]]
    country: String
    origin: [[CartOrigin.svg CartOrigin]]
    completedAt: DateTime
    custom: [[CustomFieldsDraft.svg CustomFieldsDraft]]
}
interface OrderSetStoreAction [[OrderSetStoreAction.svg]]  {
    action: String
    store: [[StoreResourceIdentifier.svg StoreResourceIdentifier]]
}
interface ProductTailoringDraft [[ProductTailoringDraft.svg]]  {
    key: String
    store: [[StoreResourceIdentifier.svg StoreResourceIdentifier]]
    product: [[ProductResourceIdentifier.svg ProductResourceIdentifier]]
    name: [[LocalizedString.svg LocalizedString]]
    description: [[LocalizedString.svg LocalizedString]]
    metaTitle: [[LocalizedString.svg LocalizedString]]
    metaDescription: [[LocalizedString.svg LocalizedString]]
    metaKeywords: [[LocalizedString.svg LocalizedString]]
    slug: [[LocalizedString.svg LocalizedString]]
    publish: Boolean
    variants: [[ProductVariantTailoringDraft.svg List<ProductVariantTailoringDraft>]]
}
interface ShoppingListDraft [[ShoppingListDraft.svg]]  {
    name: [[LocalizedString.svg LocalizedString]]
    slug: [[LocalizedString.svg LocalizedString]]
    customer: [[CustomerResourceIdentifier.svg CustomerResourceIdentifier]]
    key: String
    description: [[LocalizedString.svg LocalizedString]]
    anonymousId: String
    deleteDaysAfterLastModification: Long
    lineItems: [[ShoppingListLineItemDraft.svg List<ShoppingListLineItemDraft>]]
    textLineItems: [[TextLineItemDraft.svg List<TextLineItemDraft>]]
    store: [[StoreResourceIdentifier.svg StoreResourceIdentifier]]
    custom: [[CustomFieldsDraft.svg CustomFieldsDraft]]
}
interface ShoppingListSetStoreAction [[ShoppingListSetStoreAction.svg]]  {
    action: String
    store: [[StoreResourceIdentifier.svg StoreResourceIdentifier]]
}

StoreResourceIdentifier --> BusinessUnitDraft #green;text:green : "stores"
StoreResourceIdentifier --> BusinessUnitSetStoreModeAction #green;text:green : "stores"
StoreResourceIdentifier --> BusinessUnitSetStoresAction #green;text:green : "stores"
StoreResourceIdentifier --> CartDiscountDraft #green;text:green : "stores"
StoreResourceIdentifier --> CartDiscountSetStoresAction #green;text:green : "stores"
StoreResourceIdentifier --> CustomerDraft #green;text:green : "stores"
StoreResourceIdentifier --> CustomerSetStoresAction #green;text:green : "stores"
StoreResourceIdentifier --> MyCustomerDraft #green;text:green : "stores"
StoreResourceIdentifier --> BusinessUnitAddStoreAction #green;text:green : "store"
StoreResourceIdentifier --> BusinessUnitRemoveStoreAction #green;text:green : "store"
StoreResourceIdentifier --> CartDiscountAddStoreAction #green;text:green : "store"
StoreResourceIdentifier --> CartDiscountRemoveStoreAction #green;text:green : "store"
StoreResourceIdentifier --> CartDraft #green;text:green : "store"
StoreResourceIdentifier --> CustomerAddStoreAction #green;text:green : "store"
StoreResourceIdentifier --> CustomerRemoveStoreAction #green;text:green : "store"
StoreResourceIdentifier --> MyCartDraft #green;text:green : "store"
StoreResourceIdentifier --> MyShoppingListDraft #green;text:green : "store"
StoreResourceIdentifier --> StagedOrderSetStoreAction #green;text:green : "store"
StoreResourceIdentifier --> OrderImportDraft #green;text:green : "store"
StoreResourceIdentifier --> OrderSetStoreAction #green;text:green : "store"
StoreResourceIdentifier --> ProductTailoringDraft #green;text:green : "store"
StoreResourceIdentifier --> ShoppingListDraft #green;text:green : "store"
StoreResourceIdentifier --> ShoppingListSetStoreAction #green;text:green : "store"
@enduml
