@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface StoreCountriesChangedMessagePayload [[StoreCountriesChangedMessagePayload.svg]] extends MessagePayload {
    type: String
    addedCountries: [[StoreCountry.svg List<StoreCountry>]]
    removedCountries: [[StoreCountry.svg List<StoreCountry>]]
}
interface MessagePayload [[MessagePayload.svg]]  {
    type: String
}





@enduml
