@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface StoreUpdateAction [[StoreUpdateAction.svg]]  {
    action: String
}


interface StoreAddCountryAction [[StoreAddCountryAction.svg]]  {
    action: String
    country: [[StoreCountry.svg StoreCountry]]
}
interface StoreAddDistributionChannelAction [[StoreAddDistributionChannelAction.svg]]  {
    action: String
    distributionChannel: [[ChannelResourceIdentifier.svg ChannelResourceIdentifier]]
}
interface StoreAddProductSelectionAction [[StoreAddProductSelectionAction.svg]]  {
    action: String
    productSelection: [[ProductSelectionResourceIdentifier.svg ProductSelectionResourceIdentifier]]
    active: Boolean
}
interface StoreAddSupplyChannelAction [[StoreAddSupplyChannelAction.svg]]  {
    action: String
    supplyChannel: [[ChannelResourceIdentifier.svg ChannelResourceIdentifier]]
}
interface StoreChangeProductSelectionAction [[StoreChangeProductSelectionAction.svg]]  {
    action: String
    productSelection: [[ProductSelectionResourceIdentifier.svg ProductSelectionResourceIdentifier]]
    active: Boolean
}
interface StoreRemoveCountryAction [[StoreRemoveCountryAction.svg]]  {
    action: String
    country: [[StoreCountry.svg StoreCountry]]
}
interface StoreRemoveDistributionChannelAction [[StoreRemoveDistributionChannelAction.svg]]  {
    action: String
    distributionChannel: [[ChannelResourceIdentifier.svg ChannelResourceIdentifier]]
}
interface StoreRemoveProductSelectionAction [[StoreRemoveProductSelectionAction.svg]]  {
    action: String
    productSelection: [[ProductSelectionResourceIdentifier.svg ProductSelectionResourceIdentifier]]
}
interface StoreRemoveSupplyChannelAction [[StoreRemoveSupplyChannelAction.svg]]  {
    action: String
    supplyChannel: [[ChannelResourceIdentifier.svg ChannelResourceIdentifier]]
}
interface StoreSetCountriesAction [[StoreSetCountriesAction.svg]]  {
    action: String
    countries: [[StoreCountry.svg List<StoreCountry>]]
}
interface StoreSetCustomFieldAction [[StoreSetCustomFieldAction.svg]]  {
    action: String
    name: String
    value: [[Object.svg Object]]
}
interface StoreSetCustomTypeAction [[StoreSetCustomTypeAction.svg]]  {
    action: String
    type: [[TypeResourceIdentifier.svg TypeResourceIdentifier]]
    fields: [[FieldContainer.svg FieldContainer]]
}
interface StoreSetDistributionChannelsAction [[StoreSetDistributionChannelsAction.svg]]  {
    action: String
    distributionChannels: [[ChannelResourceIdentifier.svg List<ChannelResourceIdentifier>]]
}
interface StoreSetLanguagesAction [[StoreSetLanguagesAction.svg]]  {
    action: String
    languages: [[String.svg List<String>]]
}
interface StoreSetNameAction [[StoreSetNameAction.svg]]  {
    action: String
    name: [[LocalizedString.svg LocalizedString]]
}
interface StoreSetProductSelectionsAction [[StoreSetProductSelectionsAction.svg]]  {
    action: String
    productSelections: [[ProductSelectionSettingDraft.svg List<ProductSelectionSettingDraft>]]
}
interface StoreSetSupplyChannelsAction [[StoreSetSupplyChannelsAction.svg]]  {
    action: String
    supplyChannels: [[ChannelResourceIdentifier.svg List<ChannelResourceIdentifier>]]
}
interface StoreUpdate [[StoreUpdate.svg]]  {
    version: Long
    actions: [[StoreUpdateAction.svg List<StoreUpdateAction>]]
}
StoreUpdateAction --> StoreAddCountryAction #blue;text:blue : "action : addCountry"
StoreUpdateAction --> StoreAddDistributionChannelAction #blue;text:blue : "action : addDistributionChannel"
StoreUpdateAction --> StoreAddProductSelectionAction #blue;text:blue : "action : addProductSelection"
StoreUpdateAction --> StoreAddSupplyChannelAction #blue;text:blue : "action : addSupplyChannel"
StoreUpdateAction --> StoreChangeProductSelectionAction #blue;text:blue : "action : changeProductSelectionActive"
StoreUpdateAction --> StoreRemoveCountryAction #blue;text:blue : "action : removeCountry"
StoreUpdateAction --> StoreRemoveDistributionChannelAction #blue;text:blue : "action : removeDistributionChannel"
StoreUpdateAction --> StoreRemoveProductSelectionAction #blue;text:blue : "action : removeProductSelection"
StoreUpdateAction --> StoreRemoveSupplyChannelAction #blue;text:blue : "action : removeSupplyChannel"
StoreUpdateAction --> StoreSetCountriesAction #blue;text:blue : "action : setCountries"
StoreUpdateAction --> StoreSetCustomFieldAction #blue;text:blue : "action : setCustomField"
StoreUpdateAction --> StoreSetCustomTypeAction #blue;text:blue : "action : setCustomType"
StoreUpdateAction --> StoreSetDistributionChannelsAction #blue;text:blue : "action : setDistributionChannels"
StoreUpdateAction --> StoreSetLanguagesAction #blue;text:blue : "action : setLanguages"
StoreUpdateAction --> StoreSetNameAction #blue;text:blue : "action : setName"
StoreUpdateAction --> StoreSetProductSelectionsAction #blue;text:blue : "action : setProductSelections"
StoreUpdateAction --> StoreSetSupplyChannelsAction #blue;text:blue : "action : setSupplyChannels"
StoreUpdateAction --> StoreUpdate #green;text:green : "actions"
@enduml
