@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface Subscription [[Subscription.svg]] extends BaseResource {
    id: String
    version: Long
    createdAt: DateTime
    lastModifiedAt: DateTime
    lastModifiedBy: [[LastModifiedBy.svg LastModifiedBy]]
    createdBy: [[CreatedBy.svg CreatedBy]]
    destination: [[Destination.svg Destination]]
    key: String
    messages: [[MessageSubscription.svg List<MessageSubscription>]]
    changes: [[ChangeSubscription.svg List<ChangeSubscription>]]
    events: [[EventSubscription.svg List<EventSubscription>]]
    format: [[DeliveryFormat.svg DeliveryFormat]]
    status: [[SubscriptionHealthStatus.svg SubscriptionHealthStatus]]
}
interface BaseResource [[BaseResource.svg]]  {
    id: String
    version: Long
    createdAt: DateTime
    lastModifiedAt: DateTime
}


interface SubscriptionPagedQueryResponse [[SubscriptionPagedQueryResponse.svg]]  {
    limit: Long
    offset: Long
    count: Long
    total: Long
    results: [[Subscription.svg List<Subscription>]]
}

Subscription --> SubscriptionPagedQueryResponse #green;text:green : "results"
@enduml
