@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface SuggestTokenizer [[SuggestTokenizer.svg]]  {
    type: String
}


interface CustomTokenizer [[CustomTokenizer.svg]]  {
    type: String
    inputs: [[String.svg List<String>]]
}
interface WhitespaceTokenizer [[WhitespaceTokenizer.svg]]  {
    type: String
}
interface SearchKeyword [[SearchKeyword.svg]]  {
    text: String
    suggestTokenizer: [[SuggestTokenizer.svg SuggestTokenizer]]
}
SuggestTokenizer --> CustomTokenizer #blue;text:blue : "type : custom"
SuggestTokenizer --> WhitespaceTokenizer #blue;text:blue : "type : whitespace"
SuggestTokenizer --> SearchKeyword #green;text:green : "suggestTokenizer"
@enduml
