@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface TaxCategoryPagedQueryResponse [[TaxCategoryPagedQueryResponse.svg]]  {
    limit: Long
    offset: Long
    count: Long
    total: Long
    results: [[TaxCategory.svg List<TaxCategory>]]
}






@enduml
