@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface TaxPortion [[TaxPortion.svg]]  {
    name: String
    rate: Double
    amount: [[CentPrecisionMoney.svg CentPrecisionMoney]]
}



interface TaxedPrice [[TaxedPrice.svg]]  {
    totalNet: [[CentPrecisionMoney.svg CentPrecisionMoney]]
    totalGross: [[CentPrecisionMoney.svg CentPrecisionMoney]]
    taxPortions: [[TaxPortion.svg List<TaxPortion>]]
    totalTax: [[CentPrecisionMoney.svg CentPrecisionMoney]]
}

TaxPortion --> TaxedPrice #green;text:green : "taxPortions"
@enduml
