@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface TaxPortionDraft [[TaxPortionDraft.svg]]  {
    name: String
    rate: Double
    amount: [[Money.svg Money]]
}



interface TaxedPriceDraft [[TaxedPriceDraft.svg]]  {
    totalNet: [[Money.svg Money]]
    totalGross: [[Money.svg Money]]
    taxPortions: [[TaxPortionDraft.svg List<TaxPortionDraft>]]
}
interface CartSetCartTotalTaxAction [[CartSetCartTotalTaxAction.svg]]  {
    action: String
    externalTotalGross: [[Money.svg Money]]
    externalTaxPortions: [[TaxPortionDraft.svg List<TaxPortionDraft>]]
}
interface StagedOrderSetOrderTotalTaxAction [[StagedOrderSetOrderTotalTaxAction.svg]]  {
    action: String
    externalTotalGross: [[Money.svg Money]]
    externalTaxPortions: [[TaxPortionDraft.svg List<TaxPortionDraft>]]
}

TaxPortionDraft --> TaxedPriceDraft #green;text:green : "taxPortions"
TaxPortionDraft --> CartSetCartTotalTaxAction #green;text:green : "externalTaxPortions"
TaxPortionDraft --> StagedOrderSetOrderTotalTaxAction #green;text:green : "externalTaxPortions"
@enduml
