@startuml

hide methods
enum TaxRoundingTarget {
    NET
    TAX
}
interface ExternalTaxRateDraft [[ExternalTaxRateDraft.svg]]  {
    name: String
    amount: Double
    includedInPrice: Boolean
    country: String
    state: String
    subRates: [[SubRate.svg List<SubRate>]]
    taxRoundingTarget: [[TaxRoundingTarget.svg TaxRoundingTarget]]
}
interface TaxRate [[TaxRate.svg]]  {
    id: String
    key: String
    name: String
    amount: Double
    includedInPrice: Boolean
    country: String
    state: String
    subRates: [[SubRate.svg List<SubRate>]]
    taxRoundingTarget: [[TaxRoundingTarget.svg TaxRoundingTarget]]
}
interface TaxRateDraft [[TaxRateDraft.svg]]  {
    name: String
    amount: Double
    includedInPrice: Boolean
    country: String
    state: String
    subRates: [[SubRate.svg List<SubRate>]]
    key: String
    taxRoundingTarget: [[TaxRoundingTarget.svg TaxRoundingTarget]]
}
TaxRoundingTarget --> ExternalTaxRateDraft #green;text:green : "taxRoundingTarget"
TaxRoundingTarget --> TaxRate #green;text:green : "taxRoundingTarget"
TaxRoundingTarget --> TaxRateDraft #green;text:green : "taxRoundingTarget"
@enduml
