@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface TaxRateDraft [[TaxRateDraft.svg]]  {
    name: String
    amount: Double
    includedInPrice: Boolean
    country: String
    state: String
    subRates: [[SubRate.svg List<SubRate>]]
}



interface TaxCategoryDraft [[TaxCategoryDraft.svg]]  {
    name: String
    description: String
    rates: [[TaxRateDraft.svg List<TaxRateDraft>]]
    key: String
}
interface TaxCategoryAddTaxRateAction [[TaxCategoryAddTaxRateAction.svg]]  {
    action: String
    taxRate: [[TaxRateDraft.svg TaxRateDraft]]
}
interface TaxCategoryReplaceTaxRateAction [[TaxCategoryReplaceTaxRateAction.svg]]  {
    action: String
    taxRateId: String
    taxRate: [[TaxRateDraft.svg TaxRateDraft]]
}

TaxRateDraft --> TaxCategoryDraft #green;text:green : "rates"
TaxRateDraft --> TaxCategoryAddTaxRateAction #green;text:green : "taxRate"
TaxRateDraft --> TaxCategoryReplaceTaxRateAction #green;text:green : "taxRate"
@enduml
