@startuml

hide methods
enum TextInputHint {
    SINGLE_LINE
    MULTI_LINE
}
interface AttributeDefinition [[AttributeDefinition.svg]]  {
    type: [[AttributeType.svg AttributeType]]
    name: String
    label: [[LocalizedString.svg LocalizedString]]
    isRequired: Boolean
    attributeConstraint: [[AttributeConstraintEnum.svg AttributeConstraintEnum]]
    inputTip: [[LocalizedString.svg LocalizedString]]
    inputHint: [[TextInputHint.svg TextInputHint]]
    isSearchable: Boolean
}
interface AttributeDefinitionDraft [[AttributeDefinitionDraft.svg]]  {
    type: [[AttributeType.svg AttributeType]]
    name: String
    label: [[LocalizedString.svg LocalizedString]]
    isRequired: Boolean
    attributeConstraint: [[AttributeConstraintEnum.svg AttributeConstraintEnum]]
    inputTip: [[LocalizedString.svg LocalizedString]]
    inputHint: [[TextInputHint.svg TextInputHint]]
    isSearchable: Boolean
}
interface ProductTypeChangeInputHintAction [[ProductTypeChangeInputHintAction.svg]]  {
    action: String
    attributeName: String
    newValue: [[TextInputHint.svg TextInputHint]]
}
TextInputHint --> AttributeDefinition #green;text:green : "inputHint"
TextInputHint --> AttributeDefinitionDraft #green;text:green : "inputHint"
TextInputHint --> ProductTypeChangeInputHintAction #green;text:green : "newValue"
@enduml
