@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface ToolCustomization [[ToolCustomization.svg]]  {
    tool: [[McpServerTool.svg McpServerTool]]
    description: String
    parameters: [[ParameterOverride.svg List<ParameterOverride>]]
}



interface McpServerAddToolCustomizationAction [[McpServerAddToolCustomizationAction.svg]]  {
    action: String
    toolCustomization: [[ToolCustomization.svg ToolCustomization]]
}
interface CommerceMcpServerConfig [[CommerceMcpServerConfig.svg]]  {
    type: String
    majorVersion: String
    url: String
    tools: [[McpServerTool.svg List<McpServerTool>]]
    toolCustomizations: [[ToolCustomization.svg List<ToolCustomization>]]
    jsonOutputFiltering: [[McpServerJsonOutputFiltering.svg McpServerJsonOutputFiltering]]
    toolOutputFormatting: [[McpServerToolOutputFormatting.svg McpServerToolOutputFormatting]]
}
interface CommerceMcpServerConfigDraft [[CommerceMcpServerConfigDraft.svg]]  {
    type: String
    majorVersion: String
    tools: [[McpServerTool.svg List<McpServerTool>]]
    toolCustomizations: [[ToolCustomization.svg List<ToolCustomization>]]
    jsonOutputFiltering: [[McpServerJsonOutputFiltering.svg McpServerJsonOutputFiltering]]
    toolOutputFormatting: [[McpServerToolOutputFormatting.svg McpServerToolOutputFormatting]]
}
interface McpServerSetToolCustomizationsAction [[McpServerSetToolCustomizationsAction.svg]]  {
    action: String
    toolCustomizations: [[ToolCustomization.svg List<ToolCustomization>]]
}

ToolCustomization --> McpServerAddToolCustomizationAction #green;text:green : "toolCustomization"
ToolCustomization --> CommerceMcpServerConfig #green;text:green : "toolCustomizations"
ToolCustomization --> CommerceMcpServerConfigDraft #green;text:green : "toolCustomizations"
ToolCustomization --> McpServerSetToolCustomizationsAction #green;text:green : "toolCustomizations"
@enduml
