@startuml

hide methods
enum TransactionType {
    AUTHORIZATION
    CANCEL_AUTHORIZATION
    CHARGE
    REFUND
    CHARGEBACK
}
interface MyTransactionDraft [[MyTransactionDraft.svg]]  {
    timestamp: DateTime
    type: [[TransactionType.svg TransactionType]]
    amount: [[Money.svg Money]]
    interactionId: String
    custom: [[CustomFieldsDraft.svg CustomFieldsDraft]]
}
interface Transaction [[Transaction.svg]]  {
    id: String
    timestamp: DateTime
    type: [[TransactionType.svg TransactionType]]
    amount: [[CentPrecisionMoney.svg CentPrecisionMoney]]
    interactionId: String
    state: [[TransactionState.svg TransactionState]]
    custom: [[CustomFields.svg CustomFields]]
}
interface TransactionDraft [[TransactionDraft.svg]]  {
    timestamp: DateTime
    type: [[TransactionType.svg TransactionType]]
    amount: [[Money.svg Money]]
    interactionId: String
    state: [[TransactionState.svg TransactionState]]
    custom: [[CustomFieldsDraft.svg CustomFieldsDraft]]
}
TransactionType --> MyTransactionDraft #green;text:green : "type"
TransactionType --> Transaction #green;text:green : "type"
TransactionType --> TransactionDraft #green;text:green : "type"
@enduml
