@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface TypedMoneyDraft [[TypedMoneyDraft.svg]] extends Money {
    centAmount: Long
    currencyCode: String
    type: [[MoneyType.svg MoneyType]]
    fractionDigits: Integer
}
interface Money [[Money.svg]]  {
    centAmount: Long
    currencyCode: String
}

interface CentPrecisionMoneyDraft [[CentPrecisionMoneyDraft.svg]]  {
    centAmount: Long
    currencyCode: String
    type: [[MoneyType.svg MoneyType]]
    fractionDigits: Integer
}
interface HighPrecisionMoneyDraft [[HighPrecisionMoneyDraft.svg]]  {
    centAmount: Long
    currencyCode: String
    type: [[MoneyType.svg MoneyType]]
    fractionDigits: Integer
    preciseAmount: Long
}
interface CartDiscountValueFixedDraft [[CartDiscountValueFixedDraft.svg]]  {
    type: String
    money: [[TypedMoneyDraft.svg List<TypedMoneyDraft>]]
    applicationMode: [[DiscountApplicationMode.svg DiscountApplicationMode]]
}
interface DiscountedLineItemPortionDraft [[DiscountedLineItemPortionDraft.svg]]  {
    discount: [[Reference.svg Reference]]
    discountedAmount: [[TypedMoneyDraft.svg TypedMoneyDraft]]
}
interface TaxedPriceDraft [[TaxedPriceDraft.svg]]  {
    totalNet: [[Money.svg Money]]
    totalGross: [[Money.svg Money]]
    taxPortions: [[TaxPortionDraft.svg List<TaxPortionDraft>]]
    totalTax: [[TypedMoneyDraft.svg TypedMoneyDraft]]
}
interface StagedPriceDraft [[StagedPriceDraft.svg]]  {
    value: [[TypedMoneyDraft.svg TypedMoneyDraft]]
}
TypedMoneyDraft --> CentPrecisionMoneyDraft #blue;text:blue : "type : centPrecision"
TypedMoneyDraft --> HighPrecisionMoneyDraft #blue;text:blue : "type : highPrecision"
TypedMoneyDraft --> CartDiscountValueFixedDraft #green;text:green : "money"
TypedMoneyDraft --> DiscountedLineItemPortionDraft #green;text:green : "discountedAmount"
TypedMoneyDraft --> TaxedPriceDraft #green;text:green : "totalTax"
TypedMoneyDraft --> StagedPriceDraft #green;text:green : "value"
@enduml
