@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface VariantBulkUpdateItem [[VariantBulkUpdateItem.svg]]  {
    id: String
    key: String
    version: Long
}



interface VariantBulkUpdate [[VariantBulkUpdate.svg]]  {
    items: [[VariantBulkUpdateItem.svg List<VariantBulkUpdateItem>]]
    actions: [[VariantUpdateAction.svg List<VariantUpdateAction>]]
}

VariantBulkUpdateItem --> VariantBulkUpdate #green;text:green : "items"
@enduml
