@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface VariantAddExternalImageAction [[VariantAddExternalImageAction.svg]] extends VariantUpdateAction {
    action: String
    image: [[Image.svg Image]]
    staged: Boolean
}
interface VariantUpdateAction [[VariantUpdateAction.svg]]  {
    action: String
}





@enduml
