@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface VariantSetAssetsAction [[VariantSetAssetsAction.svg]] extends VariantUpdateAction {
    action: String
    assets: [[AssetDraft.svg List<AssetDraft>]]
    staged: Boolean
}
interface VariantUpdateAction [[VariantUpdateAction.svg]]  {
    action: String
}





@enduml
