@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface VariantBulkUpdateResource [[VariantBulkUpdateResource.svg]]  {
    id: String
    version: Long
}



interface VariantBulkUpdateSuccessResult [[VariantBulkUpdateSuccessResult.svg]]  {
    id: String
    key: String
    status: String
    resource: [[VariantBulkUpdateResource.svg VariantBulkUpdateResource]]
}

VariantBulkUpdateResource --> VariantBulkUpdateSuccessResult #green;text:green : "resource"
@enduml
