@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface VariantData [[VariantData.svg]]  {
    sku: String
    images: [[Image.svg List<Image>]]
    attributes: [[Attribute.svg List<Attribute>]]
    assets: [[Asset.svg List<Asset>]]
}



interface Variant [[Variant.svg]]  {
    id: String
    version: Long
    createdAt: DateTime
    lastModifiedAt: DateTime
    lastModifiedBy: [[LastModifiedBy.svg LastModifiedBy]]
    createdBy: [[CreatedBy.svg CreatedBy]]
    key: String
    variantId: Integer
    product: [[ProductReference.svg ProductReference]]
    published: Boolean
    current: [[VariantData.svg VariantData]]
    staged: [[VariantData.svg VariantData]]
}

VariantData --> Variant #green;text:green : "current"
VariantData --> Variant #green;text:green : "staged"
@enduml
