@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface Variant [[Variant.svg]] extends BaseResource {
    id: String
    version: Long
    createdAt: DateTime
    lastModifiedAt: DateTime
    lastModifiedBy: [[LastModifiedBy.svg LastModifiedBy]]
    createdBy: [[CreatedBy.svg CreatedBy]]
    key: String
    variantId: Integer
    product: [[ProductReference.svg ProductReference]]
    published: Boolean
    current: [[VariantData.svg VariantData]]
    staged: [[VariantData.svg VariantData]]
}
interface BaseResource [[BaseResource.svg]]  {
    id: String
    version: Long
    createdAt: DateTime
    lastModifiedAt: DateTime
}


interface VariantReference [[VariantReference.svg]]  {
    typeId: [[ReferenceTypeId.svg ReferenceTypeId]]
    id: String
    obj: [[Variant.svg Variant]]
}
interface VariantPagedQueryResponse [[VariantPagedQueryResponse.svg]]  {
    limit: Long
    offset: Long
    count: Long
    total: Long
    results: [[Variant.svg List<Variant>]]
}

Variant --> VariantReference #green;text:green : "obj"
Variant --> VariantPagedQueryResponse #green;text:green : "results"
@enduml
