@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface VariantSetAssetDescriptionAction [[VariantSetAssetDescriptionAction.svg]] extends VariantUpdateAction {
    action: String
    staged: Boolean
    assetId: String
    assetKey: String
    description: [[LocalizedString.svg LocalizedString]]
}
interface VariantUpdateAction [[VariantUpdateAction.svg]]  {
    action: String
}





@enduml
