@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface ZoneUpdate [[ZoneUpdate.svg]]  {
    version: Long
    actions: [[ZoneUpdateAction.svg List<ZoneUpdateAction>]]
}






@enduml
