@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface ZoneRateDraft [[ZoneRateDraft.svg]]  {
    zone: [[ZoneResourceIdentifier.svg ZoneResourceIdentifier]]
    shippingRates: [[ShippingRateDraft.svg List<ShippingRateDraft>]]
}



interface ShippingMethodDraft [[ShippingMethodDraft.svg]]  {
    key: String
    name: String
    localizedName: [[LocalizedString.svg LocalizedString]]
    description: String
    localizedDescription: [[LocalizedString.svg LocalizedString]]
    taxCategory: [[TaxCategoryResourceIdentifier.svg TaxCategoryResourceIdentifier]]
    zoneRates: [[ZoneRateDraft.svg List<ZoneRateDraft>]]
    isDefault: Boolean
    predicate: String
    custom: [[CustomFieldsDraft.svg CustomFieldsDraft]]
}

ZoneRateDraft --> ShippingMethodDraft #green;text:green : "zoneRates"
@enduml
