@startuml

hide empty fields
hide empty methods
legend
|= |= line |
|<back:black>   </back>| inheritance |
|<back:green>   </back>| property reference |
|<back:blue>   </back>| discriminated class |
endlegend
interface ZoneResourceIdentifier [[ZoneResourceIdentifier.svg]] extends ResourceIdentifier {
    typeId: [[ReferenceTypeId.svg ReferenceTypeId]]
    id: String
    key: String
}
interface ResourceIdentifier [[ResourceIdentifier.svg]]  {
    typeId: [[ReferenceTypeId.svg ReferenceTypeId]]
    id: String
    key: String
}


interface ZoneRateDraft [[ZoneRateDraft.svg]]  {
    zone: [[ZoneResourceIdentifier.svg ZoneResourceIdentifier]]
    shippingRates: [[ShippingRateDraft.svg List<ShippingRateDraft>]]
}
interface ShippingMethodAddShippingRateAction [[ShippingMethodAddShippingRateAction.svg]]  {
    action: String
    zone: [[ZoneResourceIdentifier.svg ZoneResourceIdentifier]]
    shippingRate: [[ShippingRateDraft.svg ShippingRateDraft]]
}
interface ShippingMethodAddZoneAction [[ShippingMethodAddZoneAction.svg]]  {
    action: String
    zone: [[ZoneResourceIdentifier.svg ZoneResourceIdentifier]]
}
interface ShippingMethodRemoveShippingRateAction [[ShippingMethodRemoveShippingRateAction.svg]]  {
    action: String
    zone: [[ZoneResourceIdentifier.svg ZoneResourceIdentifier]]
    shippingRate: [[ShippingRateDraft.svg ShippingRateDraft]]
}
interface ShippingMethodRemoveZoneAction [[ShippingMethodRemoveZoneAction.svg]]  {
    action: String
    zone: [[ZoneResourceIdentifier.svg ZoneResourceIdentifier]]
}

ZoneResourceIdentifier --> ZoneRateDraft #green;text:green : "zone"
ZoneResourceIdentifier --> ShippingMethodAddShippingRateAction #green;text:green : "zone"
ZoneResourceIdentifier --> ShippingMethodAddZoneAction #green;text:green : "zone"
ZoneResourceIdentifier --> ShippingMethodRemoveShippingRateAction #green;text:green : "zone"
ZoneResourceIdentifier --> ShippingMethodRemoveZoneAction #green;text:green : "zone"
@enduml
