#%RAML 1.0 DataType
(package): CartDiscount
(docs-uri): https://docs.commercetools.com/http-api-projects-cartDiscounts.html#set-valid-until
type: CartDiscountUpdateAction
displayName: CartDiscountSetValidUntilAction
discriminatorValue: setValidUntil
(postman-example): !include ../../../examples/CartDiscount/CartDiscountSetValidUntilAction.json
properties:
  validUntil?:
    type: datetime
    description:
      If absent, the field with the value is removed in case a value was set
      before.
