#%RAML 1.0 DataType
(package): ProductSelection
type: ProductSelectionUpdateAction
displayName: ProductSelectionAddProductAction
discriminatorValue: addProduct
example: !include ../../../examples/ProductSelection/ProductSelectionAddProductAction.json
description: |
  Adds a Product to the Product Selection.

  If the specified Product is already assigned to the Product Selection, but the existing Product Selection has a different Product Variant Selection, a [ProductPresentWithDifferentVariantSelection](ctp:api:type:ProductPresentWithDifferentVariantSelectionError) error is returned.
properties:
  product:
    type: ProductResourceIdentifier
    description: ResourceIdentifier of the Product
  variantSelection?:
    type: ProductVariantSelection
    description: |
      Defines which Variants of the Product will be included in the Product Selection.
      If not supplied all Variants are deemed to be included.
