#%RAML 1.0 DataType
(package): ProductSelection
(docs-uri): https://docs.commercetools.com/http-api-projects-product-selections.html#set-custom-type
type: ProductSelectionUpdateAction
displayName: ProductSelectionSetCustomTypeAction
discriminatorValue: setCustomType
example: !include ../../../examples/ProductSelection/ProductSelectionSetCustomTypeAction.json
properties:
  type?:
    type: TypeResourceIdentifier
    description: |
      Defines the [Type](ctp:api:type:Type) that extends the Product Selection with [Custom Fields](/../api/projects/custom-fields).
      If absent, any existing Type and any existing Custom Fields are removed from the Product Selection.
  fields?:
    type: FieldContainer
    description: |
      Sets the [Custom Fields](/../api/projects/custom-fields) fields for the Product Selection.
