#%RAML 1.0 DataType
(package): ProductSelection
(docs-uri): https://docs.commercetools.com/api/projects/product-selections#set-variant-exclusion
(beta): true
type: ProductSelectionUpdateAction
displayName: ProductSelectionSetVariantExclusionAction
discriminatorValue: setVariantExclusion
example: !include ../../../examples/ProductSelection/ProductSelectionSetVariantExclusionAction.json
description: |
  Updates the Product Variant Exclusion of an existing [Product Selection Assignment](ctp:api:type:ProductSelectionAssignment).
  A [ProductVariantExclusion](ctp:api:type:ProductVariantExclusion) can only be set if the [Product](/projects/products) has already been excluded from the [Product Selection of type Individual Exclusion](/projects/product-selections).

  If the specified Product is not assigned to the Product Selection, a [ProductAssignmentMissing](ctp:api:type:ProductAssignmentMissingError) error is returned.
properties:
  product:
    type: ProductResourceIdentifier
    description: ResourceIdentifier of the Product
  variantExclusion?:
    type: ProductVariantExclusion
    description: |
      Determines which Variants of the previously excluded Product are to be included in the Product Selection of type Individual Exclusion.
      Leave it empty to unset an existing Variant Exclusion.
