#%RAML 1.0 DataType
(package): ProductSelection
(docs-uri): https://docs.commercetools.com/http-api-projects-product-selections.html#add-product
type: ProductSelectionUpdateAction
displayName: ProductSelectionAddProductAction
discriminatorValue: addProduct
example: !include ../../../examples/ProductSelection/ProductSelectionAddProductAction.json
description: |
  Adds a Product to the Product Selection.
  If the given Product is already assigned to the Product Selection with the same Variant Selection nothing happens
  but if the existing Assignment has a different Variant Selection [ProductPresentWithDifferentVariantSelection](/errors#product-selections) is raised.'
properties:
  product:
    type: ProductResourceIdentifier
    description: ResourceIdentifier to Product
  variantSelection?:
    type: ProductVariantSelection
    description: |
      Selects which Variants of the newly added Product will be included, or excluded, from the Product Selection.
      If not supplied all Variants are deemed to be included.
