#%RAML 1.0 DataType
(package): Order
displayName: DiscountedLineItemPriceDraft
type: object
properties:
  value:
    type: Money
    description: |
      Discounted money value.
  includedDiscounts:
    type: DiscountedLineItemPortionDraft[]
    description: |
      Discounts to be applied.
