#%RAML 1.0 DataType
(package): Order
displayName: LineItemReturnItem
type: ReturnItem
discriminatorValue: LineItemReturnItem
properties:
  key?:
    type: string
    description: User-defined unique identifier of the LineItemReturnItem.
    pattern: ^[a-zA-Z0-9_-]
    minLength: 2
    maxLength: 256
  lineItemId:
    type: string
    description: |
      `id` of the returned [LineItem](ctp:api:type:LineItem).
  quantity:
    type: number
    format: int64
    description: |
      Number of Line Items returned.
