#%RAML 1.0 DataType
(package): Order
(docs-uri): https://docs.commercetools.com/http-api-projects-orders.html#order
displayName: Order
(updateType): OrderUpdate
type: BaseResource
properties:
  id:
    (identifier): true
    type: string
    description: Unique identifier of the Order.
  version:
    type: number
    format: int64
    description: The current version of the order.
  createdAt:
    type: datetime
    description: ''
  lastModifiedAt:
    type: datetime
    description: ''
  lastModifiedBy?:
    type: LastModifiedBy
    (beta): true
    description: |
      Present on resources created after 1 February 2019 except for [events not tracked](/client-logging#events-tracked).
  createdBy?:
    type: CreatedBy
    (beta): true
    description: |
      Present on resources created after 1 February 2019 except for [events not tracked](/client-logging#events-tracked).
  completedAt?:
    type: datetime
    description: This field will only be present if it was set for Order Import
  orderNumber?:
    type: string
    description: |-
      String that uniquely identifies an order.
      It can be used to create more human-readable (in contrast to ID) identifier for the order.
      It should be unique across a project.
      Once it's set it cannot be changed.
  customerId?:
    type: string
    description: ''
  customerEmail?:
    type: string
    description: ''
  anonymousId?:
    type: string
    description:
      Identifies carts and orders belonging to an anonymous session (the
      customer has not signed up/in yet).
  businessUnit?:
    type: BusinessUnitKeyReference
    (beta): true
    description: |
      The Business Unit the Order belongs to.
  store?:
    type: StoreKeyReference
    description: ''
  lineItems:
    type: LineItem[]
    description: ''
  customLineItems:
    type: CustomLineItem[]
    description: ''
  totalPrice:
    description: ''
    type: TypedMoney
  taxedPrice?:
    type: TaxedPrice
    description: The taxes are calculated based on the shipping address.
  taxedShippingPrice?:
    type: TaxedPrice
    description: |-
      Sum of `taxedPrice` of [ShippingInfo](ctp:api:type:ShippingInfo) across all Shipping Methods.
      For `Platform` [TaxMode](ctp:api:type:TaxMode), it is set automatically only if [shipping address is set](ctp:api:type:CartSetShippingAddressAction) or [Shipping Method is added](ctp:api:type:CartAddShippingMethodAction) to the Cart.
  shippingAddress?:
    type: Address
    description: |
      Holds all shipping-related information per Shipping Method.

      For `Multiple` [ShippingMode](ctp:api:typeShippingMode), it is updated automatically after the Shipping Methods are added.
  billingAddress?:
    type: Address
    description: ''
  shippingMode:
    type: ShippingMode
    description: |
      Indicates whether one or multiple Shipping Methods are added to the Cart.
    default: Single
  shippingKey?:
    type: string
    description: |
      `key` of the [ShippingMethod](ctp:api:type:ShippingMethod) for `Single` [ShippingMode](ctp:api:type:ShippingMode).
  shippingCustomFields?:
    type: CustomFields
    description: |
      Custom Fields of the Shipping Method for `Single` [ShippingMode](ctp:api:type:ShippingMode).
  shipping:
    type: Shipping[]
    description: |
      Holds all shipping-related information per Shipping Method for `Multiple` [ShippingMode](ctp:api:typeShippingMode).

      It is updated automatically after the [Shipping Method is added](ctp:api:type:CartAddShippingMethodAction).
  taxMode?:
    type: TaxMode
    description: ''
  taxRoundingMode?:
    type: RoundingMode
    description:
      When calculating taxes for `taxedPrice`, the selected mode is used for
      rouding.
  customerGroup?:
    type: CustomerGroupReference
    description: |-
      Set when the customer is set and the customer is a member of a customer group.
      Used for product variant price selection.
  country?:
    type: string
    description: |-
      A two-digit country code as per [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2).
      Used for product variant price selection.
  orderState:
    type: OrderState
    description: One of the four predefined OrderStates.
  state?:
    type: StateReference
    description: This reference can point to a state in a custom workflow.
  shipmentState?:
    type: ShipmentState
    description: ''
  paymentState?:
    type: PaymentState
    description: ''
  shippingInfo?:
    type: ShippingInfo
    description: Set if the ShippingMethod is set.
  syncInfo:
    type: SyncInfo[]
    description: ''
  returnInfo?:
    type: ReturnInfo[]
    description: ''
  purchaseOrderNumber?:
    type: string
    description: |-
      The Purchase Order Number is typically set by the [Buyer](/quotes-overview#buyer) on a [QuoteRequest](ctp:api:type:QuoteRequest) to
      track the purchase order during the [quote and order flow](/../api/quotes-overview#intended-workflow).
  discountCodes?:
    description: ''
    type: DiscountCodeInfo[]
  lastMessageSequenceNumber?:
    (markDeprecated): true
    type: number
    format: int64
    description: |-
      Internal-only field.
  cart?:
    type: CartReference
    description: |-
      Set when this order was created from a cart.
      The cart will have the state `Ordered`.
  quote?:
    type: QuoteReference
    description: |-
      Set when this order was created from a quote.
  custom?:
    type: CustomFields
    description: ''
  paymentInfo?:
    type: PaymentInfo
    description: ''
  locale?:
    type: string
    description: ''
  inventoryMode?:
    type: InventoryMode
    description: ''
  origin:
    type: CartOrigin
    description: ''
  taxCalculationMode?:
    type: TaxCalculationMode
    description:
      When calculating taxes for `taxedPrice`, the selected mode is used for
      calculating the price with LineItemLevel (horizontally) or UnitPriceLevel
      (vertically) calculation mode.
  shippingRateInput?:
    type: ShippingRateInput
    description: |
      Input used to select a [ShippingRatePriceTier](ctp:api:type:ShippingRatePriceTier).
      The data type of this field depends on the `shippingRateInputType.type` configured in the [Project](ctp:api:type:Project):

      - If `CartClassification`, it is [ClassificationShippingRateInput](ctp:api:type:ClassificationShippingRateInput).
      - If `CartScore`, it is [ScoreShippingRateInput](ctp:api:type:ScoreShippingRateInput).
      - If `CartValue`, it cannot be used.

  itemShippingAddresses?:
    type: Address[]
    description: Contains addresses for orders with multiple shipping addresses.
  refusedGifts:
    type: CartDiscountReference[]
    description:
      Automatically filled when a line item with LineItemMode `GiftLineItem` is
      removed from this order.
