#%RAML 1.0 DataType
(package): Order
type: object
displayName: OrderSearchSorting
properties:
  field:
    type: string
  language?:
    type: string
  order?:
    type: OrderSearchSortOrder
  mode?:
    type: OrderSearchSortMode
  filter?:
    type: OrderSearchQueryExpression
