#%RAML 1.0 DataType
(package): Order
(docs-uri): https://docs.commercetools.com/api/projects/orders#orderreference
type: Reference
displayName: OrderReference
discriminatorValue: order
description: |
  [Reference](ctp:api:type:Reference) to an [Order](ctp:api:type:Order).
properties:
  obj?:
    type: Order
    description: |
      Contains the representation of the expanded Order. Only present in responses to requests with [Reference Expansion](/../api/general-concepts#reference-expansion) for Orders.
  id:
    type: string
    description: |
      Unique identifier of the referenced [Order](ctp:api:type:Order).
