#%RAML 1.0 DataType
(package): Order
displayName: OrderFromQuoteDraft
type: object
properties:
  quote:
    type: QuoteResourceIdentifier
    description: |
      [ResourceIdentifier](ctp:api:type:ResourceIdentifier) to the Quote from which the Order is created.

      The [Quote](ctp:api:type:Quote) must have the `Pending` [state](ctp:api:type:QuoteState) and must be valid (not past the `validTo` date).
  version:
    type: number
    format: int64
    description: |
      `version` of the [Quote](ctp:api:type:Quote) from which the Order is created.
  quoteStateToAccepted?:
    type: boolean
    description: |
      If `true`, the `quoteState` of the referenced [Quote](ctp:api:type:Quote) will be set to `Accepted`.
    default: false
  orderNumber?:
    type: string
    description: |
      User-defined identifier for the Order that is unique across a Project.
      Once set, the value cannot be changed.
  paymentState?:
    type: PaymentState
    description: |
      Payment status for the Order.
  shipmentState?:
    type: ShipmentState
    description: |
      Shipment status for the Order.
  orderState?:
    type: OrderState
    description: |
      Current status for the Order.
    default: Open
  state?:
    type: StateResourceIdentifier
    description: |
      State of the Order in a custom workflow.
