#%RAML 1.0 DataType
(package): Order
(docs-uri): https://docs.commercetools.com/http-api-projects-orders-import.html#orderimportdraft
displayName: OrderImportDraft
type: object
properties:
  orderNumber?:
    type: string
    description: |-
      String that unique identifies an order.
      It can be used to create more human-readable (in contrast to ID) identifier for the order.
      It should be unique within a project.
  customerId?:
    type: string
    description: If given the customer with that ID must exist in the project.
  customerEmail?:
    type: string
    description:
      The customer email can be used when no check against existing Customers is
      desired during order import.
  lineItems?:
    description: If not given `customLineItems` must not be empty.
    type: LineItemImportDraft[]
  customLineItems?:
    description: If not given `lineItems` must not be empty.
    type: CustomLineItemDraft[]
  totalPrice:
    description: ''
    type: Money
  taxedPrice?:
    type: TaxedPriceDraft
    description: |-
      Order Import does not support calculation of taxes.
      When setting the draft the taxedPrice is to be provided.
  shippingAddress?:
    type: BaseAddress
    description: ''
  billingAddress?:
    type: BaseAddress
    description: ''
  customerGroup?:
    type: CustomerGroupResourceIdentifier
    description: |-
      Set when the customer is set and the customer is a member of a customer group.
      Used for product variant price selection.
  country?:
    type: string
    description: |-
      A two-digit country code as per [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2).
      Used for product variant price selection.
  orderState?:
    type: OrderState
    description: If not given the `Open` state will be assigned by default.
  shipmentState?:
    type: ShipmentState
    description: ''
  paymentState?:
    type: PaymentState
    description: ''
  shippingInfo?:
    type: ShippingInfoImportDraft
    description: Set if the ShippingMethod is set.
  completedAt?:
    type: datetime
    description: ''
  custom?:
    type: CustomFieldsDraft
    description: The custom fields.
  inventoryMode?:
    type: InventoryMode
    description: If not given the mode `None` will be assigned by default.
  taxRoundingMode?:
    type: RoundingMode
    description: If not given the tax rounding mode `HalfEven` will be assigned by default.
  itemShippingAddresses?:
    type: BaseAddress[]
    description: Contains addresses for orders with multiple shipping addresses.
  store?:
    type: StoreResourceIdentifier
    description: ''
  origin?:
    type: CartOrigin
    description: The default origin is `Customer`.
