#%RAML 1.0 DataType
(package): Order
(docs-uri): https://docs.commercetools.com/http-api-projects-orders.html#order
type: ResourceIdentifier
displayName: OrderResourceIdentifier
discriminatorValue: order
