#%RAML 1.0 DataType
(package): Order
(docs-uri): https://docs.commercetools.com/api/projects/orders-import#orderimportdraft
displayName: OrderImportDraft
type: object
description: |
  A snapshot of an Order at the time it was imported.
properties:
  orderNumber?:
    type: string
    description: |
      User-defined identifier of the Order. Must be unique across a Project.
      Once set, the value cannot be changed.
  purchaseOrderNumber?:
    type: string
    description: |-
      User-defined identifier for a purchase Order.
  customerId?:
    type: string
    description: |
      The `id` of the [Customer](ctp:api:type:Customer) the Order belongs to.
  customerEmail?:
    type: string
    description: |
      The Email address of the Customer the Order belongs to. Can be used instead of `customerId` when no check against existing [Customers](ctp:api:type:Customer) is required.
  customerGroup?:
    type: CustomerGroupResourceIdentifier
    description: |
      The Customer Group of the Customer the Order belongs to.
  businessUnit?:
    type: BusinessUnitResourceIdentifier
    description: |
      [ResourceIdentifier](ctp:api:type:ResourceIdentifier) to the Business Unit the Order should belong to.
      When the `customerId` of the Order is also set, the [Customer](ctp:api:type:Customer) must be an [Associate](ctp:api:type:Associate) of the Business Unit.
  store?:
    type: StoreResourceIdentifier
    description: |
      The Store the Order belongs to.
      Used for [filtering](#filtering).

      If a [LineItemImportDraft](ctp:api:type:LineItemImportDraft) or a [CustomLineItemImportDraft](ctp:api:type:CustomLineItemImportDraft) specifies a `distributionChannel` or a `supplyChannel` that is not defined for the referenced Store, the Order Import gets rejected.
      The same applies when the provided `country` is not defined for the referenced Store.
  lineItems?:
    description: |
      [Line Items](ctp:api:type:LineItems) to add to the Order.

      If not specified, `customLineItems` must not be empty.
    type: LineItemImportDraft[]
  customLineItems?:
    description: |
      [Custom Line Items](ctp:api:type:CustomLineItems) to add to the Cart.

      If not specified, `lineItems` must not be empty.
    type: CustomLineItemImportDraft[]
  totalPrice:
    description: |
      The total Price of the Order. The amount can be negative.
    type: Money
  taxedPrice?:
    type: TaxedPriceDraft
    description: |
      Include TaxedPrice information for the Order. If not included, and if you have Tax Rates set for Line Items and Custom Line Items, the Order total will not be recalculated.
  taxRoundingMode?:
    type: RoundingMode
    default: HalfEven
    description: |
      Determines how monetary values are rounded when calculating taxes for `taxedPrice`.
  taxCalculationMode?:
    type: TaxCalculationMode
    default: LineItemLevel
    description: |
      Determines how taxes are calculated for `taxedPrice`.
  inventoryMode?:
    type: InventoryMode
    default: None
    description: |
      Determines how stock quantities are tracked for Line Items in the Cart.
  billingAddress?:
    type: BaseAddress
    description: |
      Billing address associated with the Order.
  shippingAddress?:
    type: BaseAddress
    description: |
      Shipping address associated with the Order.
  itemShippingAddresses?:
    type: BaseAddress[]
    description: |
      Addresses for Orders with multiple shipping addresses. Addresses must include a value for `key`.
  shippingInfo?:
    type: ShippingInfoImportDraft
    description: |
      Shipping-related information of the Order.
  paymentInfo?:
    type: PaymentInfo
    description: |
      Payment information associated with the Order.
  paymentState?:
    type: PaymentState
    description: |
      Payment status of the Order.
  shipmentState?:
    type: ShipmentState
    description: |
      Shipment status of the Order.
  orderState?:
    type: OrderState
    default: Open
    description: |
      Current status of the Order.
  state?:
    type: StateReference
    description: |
      State of the Order in a custom workflow.
  country?:
    type: CountryCode
    description: |
      Include a value to associate a country with the Order.
  origin?:
    type: CartOrigin
    default: Customer
    description: |
      Indicates the origin of the Order.
  completedAt?:
    type: datetime
    description: |
      User-defined date and time for the Order. This value does not influence the `createdAt` or `lastModifiedAt` values of the Order created by the Order Import.
  custom?:
    type: CustomFieldsDraft
    description: |
      Custom Fields for the Order.
