#%RAML 1.0 DataType
(package): Order
displayName: OrderFromCartDraft
type: object
properties:
  id?:
    (markDeprecated): true
    type: string
    description: The unique id of the cart from which an order is created.
  cart?:
    type: CartResourceIdentifier
    description: ResourceIdentifier to the Cart from which this order is created.
  version:
    type: number
    format: int64
    description: ''
  orderNumber?:
    type: string
    description: |-
      String that uniquely identifies an order.
      It can be used to create more human-readable (in contrast to ID) identifier for the order.
      It should be unique across a project.
      Once it's set it cannot be changed.
      For easier use on Get, Update and Delete actions we suggest assigning order numbers that match the regular expression `[a-z0-9_\-]{2,36}`.
  paymentState?:
    type: PaymentState
    description: ''
  shipmentState?:
    type: ShipmentState
    description: ''
  orderState?:
    type: OrderState
    description: Order will be created with `Open` status by default.
  state?:
    type: StateResourceIdentifier
    description: ''
