#%RAML 1.0 DataType
(package): Order
displayName: OrderPagedQueryResponse
type: object
properties:
  limit:
    type: number
    format: int64
    description: |
      Number of [results requested](/../api/general-concepts#limit).
  count:
    type: number
    format: int64
  total?:
    type: number
    format: int64
  offset:
    type: number
    format: int64
    description: |
      Number of [elements skipped](/../api/general-concepts#offset).
  results:
    type: Order[]
