#%RAML 1.0 DataType
(package): Order
displayName: ParcelDraft
type: object
properties:
  key?:
    type: string
    description: User-defined unique identifier of the Parcel.
    pattern: ^[a-zA-Z0-9_-]
    minLength: 2
    maxLength: 256
  measurements?:
    type: ParcelMeasurements
    description: |
      Information about the dimensions for the Parcel.
  trackingData?:
    type: TrackingData
    description: |
      Shipment tracking information for the Parcel.
  items?:
    type: DeliveryItem[]
    description: |
      Line Items or Custom Line Items delivered in this Parcel.
  custom?:
    type: CustomFieldsDraft
    description: |
      Custom Fields for the Parcel.
