#%RAML 1.0 DataType
(package): Order
type: string
description: |
  Indicates the payment status for the Order.
enum:
  - BalanceDue
  - Failed
  - Pending
  - CreditOwed
  - Paid
(enumDescriptions):
  BalanceDue: |
    Indicates that payment balance is due for the Order.
  Failed: |
    Indicates that payment for the Order has failed.
  Pending: |
    Indicates that payment for the Order is pending.
  CreditOwed: |
    Indicates that payment for the Order is made on a credit basis.
  Paid: |
    Indicates that the Order is paid for.
