#%RAML 1.0 DataType
(package): Order
displayName: ReturnInfoDraft
type: object
properties:
  items:
    type: ReturnItemDraft[]
    description: |
      Information on the Line Items or Custom Line Items returned.
  returnTrackingId?:
    type: string
    description: |
      User-defined identifier for tracking the return.
  returnDate?:
    type: datetime
    description: |
      Date and time (UTC) the return is initiated.
