#%RAML 1.0 DataType
(package): Type
(docs-uri): https://docs.commercetools.com/http-api-projects-types.html#add-enumvalue-to-fielddefinition
type: TypeUpdateAction
displayName: TypeAddEnumValueAction
discriminatorValue: addEnumValue
(postman-example): !include ../../../examples/Type/TypeAddEnumValueAction.json
properties:
  fieldName:
    type: string
  value:
    type: CustomFieldEnumValue
