#%RAML 1.0 DataType
(package): Type
(docs-uri): https://docs.commercetools.com/http-api-projects-types.html#change-the-order-of-enumvalues
type: TypeUpdateAction
displayName: TypeChangeEnumValueOrderAction
discriminatorValue: changeEnumValueOrder
(postman-example): !include ../../../examples/Type/TypeChangeEnumValueOrderAction.json
properties:
  fieldName:
    type: string
  keys:
    type: string[]
