#%RAML 1.0 DataType
(package): Product
(docs-uri): https://docs.commercetools.com/http-api-projects-products.html#add-asset
type: ProductUpdateAction
displayName: ProductAddAssetAction
discriminatorValue: addAsset
(postman-example): !include ../../../examples/Product/ProductAddAssetAction.json
properties:
  variantId?:
    type: number
    format: int64
    description: ''
  sku?:
    type: string
  staged?:
    type: boolean
    description: ''
  asset:
    type: AssetDraft
    description: ''
  position?:
    type: number
    format: int32
    description:
      Position of the new asset inside the existing list (from `0` to the size
      of the list)
