#%RAML 1.0 DataType
(package): Product
(docs-uri): https://docs.commercetools.com/http-api-projects-products.html#set-searchkeywords
type: ProductUpdateAction
displayName: ProductSetSearchKeywordsAction
discriminatorValue: setSearchKeywords
(postman-example): !include ../../../examples/Product/ProductSetSearchKeywordsAction.json
properties:
  searchKeywords:
    type: SearchKeywords
    description: ''
  staged?:
    type: boolean
    description: ''
