#%RAML 1.0 DataType
(package): Product
(docs-uri): https://docs.commercetools.com/http-api-projects-products.html#add-to-category
type: ProductUpdateAction
displayName: ProductAddToCategoryAction
discriminatorValue: addToCategory
(postman-example): !include ../../../examples/Product/ProductAddToCategoryAction.json
properties:
  category:
    type: CategoryResourceIdentifier
    description: ''
  orderHint?:
    type: string
    description: ''
  staged?:
    type: boolean
    description: ''
