#%RAML 1.0 DataType
(package): Product
(docs-uri): https://docs.commercetools.com/http-api-projects-products.html#set-asset-tags
type: ProductUpdateAction
displayName: ProductSetAssetTagsAction
discriminatorValue: setAssetTags
(postman-example): !include ../../../examples/Product/ProductSetAssetTagsAction.json
properties:
  variantId?:
    type: number
    format: int64
    description: ''
  sku?:
    type: string
  staged?:
    type: boolean
    description: ''
  assetId?:
    type: string
    description: ''
  assetKey?:
    type: string
  tags?:
    type: string[]
    description: ''
