#%RAML 1.0 DataType
(package): Product
(docs-uri): https://docs.commercetools.com/http-api-projects-products.html#set-meta-keywords
type: ProductUpdateAction
displayName: ProductSetMetaKeywordsAction
discriminatorValue: setMetaKeywords
(postman-example): !include ../../../examples/Product/ProductSetMetaKeywordsAction.json
properties:
  metaKeywords?:
    type: LocalizedString
    description: ''
  staged?:
    type: boolean
    description: ''
