#%RAML 1.0 DataType
(package): Product
(docs-uri): https://docs.commercetools.com/http-api-projects-products.html#revert-staged-variant-changes
type: ProductUpdateAction
displayName: ProductRevertStagedVariantChangesAction
discriminatorValue: revertStagedVariantChanges
(postman-example): !include ../../../examples/Product/ProductRevertStagedVariantChangesAction.json
properties:
  variantId:
    type: number
    format: int64
    description: ''
