#%RAML 1.0 DataType
(package): Order
(docs-uri): https://docs.commercetools.com/http-api-projects-orders.html#change-paymentstate
type: OrderUpdateAction
displayName: OrderChangePaymentStateAction
discriminatorValue: changePaymentState
(postman-example): !include ../../../examples/Order/OrderChangePaymentStateAction.json
properties:
  paymentState?:
    type: PaymentState
