#%RAML 1.0 DataType
(package): Order
(docs-uri): https://docs.commercetools.com/http-api-projects-orders.html#change-shipmentstate
type: OrderUpdateAction
displayName: OrderChangeShipmentStateAction
discriminatorValue: changeShipmentState
(postman-example): !include ../../../examples/Order/OrderChangeShipmentStateAction.json
properties:
  shipmentState?:
    type: ShipmentState
