#%RAML 1.0 DataType
(package): Product
(docs-uri): https://docs.commercetools.com/api/projects/products#add-price
type: ProductUpdateAction
displayName: ProductAddPriceAction
discriminatorValue: addPrice
description: |
  Adds the given Price to the `prices` array of the [ProductVariant](ctp:api:type:ProductVariant).
  Either `variantId` or `sku` is required.
example: !include ../../../examples/Product/ProductAddPriceAction.json
properties:
  variantId?:
    type: number
    format: int64
    description: |
      The `id` of the ProductVariant to update.
  sku?:
    type: string
    description: |
      The `sku` of the ProductVariant to update.
  price:
    type: PriceDraft
    description: |
      Embedded Price to add to the Product Variant.
  staged?:
    type: boolean
    description: |
      If `true`, only the staged `prices` is updated. If `false`, both the current and staged `prices` are updated.
    default: true
