#%RAML 1.0 DataType
(package): Product
(docs-uri): https://docs.commercetools.com/http-api-projects-products.html#set-taxcategory
type: ProductUpdateAction
displayName: ProductSetTaxCategoryAction
discriminatorValue: setTaxCategory
(postman-example): !include ../../../examples/Product/ProductSetTaxCategoryAction.json
properties:
  taxCategory?:
    type: TaxCategoryResourceIdentifier
    description: If left blank or set to `null`, the tax category is unset/removed.
