#%RAML 1.0 DataType
(package): Product
(docs-uri): https://docs.commercetools.com/http-api-projects-products.html#add-price
type: ProductUpdateAction
displayName: ProductAddPriceAction
discriminatorValue: addPrice
(postman-example): !include ../../../examples/Product/ProductAddPriceAction.json
properties:
  variantId?:
    type: number
    format: int64
    description: ''
  sku?:
    type: string
  price:
    type: PriceDraft
    description: ''
  staged?:
    type: boolean
    description: ''
