#%RAML 1.0 DataType
(package): Product
type: ProductUpdateAction
displayName: ProductSetAssetDescriptionAction
discriminatorValue: setAssetDescription
description: |
  Either `variantId` or `sku` is required. The [Asset](ctp:api:type:Asset) to update must be specified using either `assetId` or `assetKey`.
example: !include ../../../examples/Product/ProductSetAssetDescriptionAction.json
properties:
  variantId?:
    type: number
    format: int64
    description: |
      The `id` of the ProductVariant to update.
  sku?:
    type: string
    description: |
      The `sku` of the ProductVariant to update.
  staged?:
    type: boolean
    description: |
      If `true`, only the staged Asset is updated. If `false`, both the current and staged Asset is updated.
    default: true
  assetId?:
    type: string
    description: |
      The `id` of the Asset to update.
  assetKey?:
    type: string
    description: |
      The `key` of the Asset to update.
  description?:
    type: LocalizedString
    description: |
      Value to set. If empty, any existing value will be removed.
