#%RAML 1.0 DataType
(package): Product
type: ProductUpdateAction
displayName: ProductUnpublishAction
discriminatorValue: unpublish
example: !include ../../../examples/Product/ProductUnpublishAction.json
description: |
  Sets the `published` flag on the [ProductCatalogData](ctp:api:type:ProductCatalogData) to `false`.
  This makes the [current](/../api/projects/productProjections#current--staged) representation of a Product unavailable in [Product Projection](/projects/productProjections) endpoints by default, and excludes it from [Product Search](/../api/projects/product-search).
  To retrieve unpublished Products on Product Projection endpoints, set parameter `staged=true`.

  Produces the [ProductUnpublished](ctp:api:type:ProductUnpublishedMessage) Message.

  When a Product is unpublished, any associated Line Items already present in a Cart remain unaffected and can still be ordered. To prevent this, do the following:

  - If the Product uses Embedded Prices, [remove the Embedded Prices](ctp:api:type:ProductRemovePriceAction) from the unpublished Product.
  - If the Product uses Standalone Prices, [inactivate](ctp:api:type:StandalonePriceChangeActiveAction) or [delete](/projects/standalone-prices#delete-standaloneprice) the Standalone Prices.
