#%RAML 1.0 DataType
(package): Product
(docs-uri): https://docs.commercetools.com/api/projects/products#remove-asset
type: ProductUpdateAction
displayName: ProductRemoveAssetAction
discriminatorValue: removeAsset
description: |
  Either `variantId` or `sku` is required. The Asset to remove must be specified using either `assetId` or `assetKey`.
example: !include ../../../examples/Product/ProductRemoveAssetAction.json
properties:
  variantId?:
    type: number
    format: int64
    description: |
      The `id` of the ProductVariant to update.
  sku?:
    type: string
    description: |
      The `sku` of the ProductVariant to update.
  staged?:
    type: boolean
    description: |
      If `true`, only the staged Asset is removed. If `false`, both the current and staged Asset is removed.
    default: true
  assetId?:
    type: string
    description: |
      The `id` of the Asset to remove.
  assetKey?:
    type: string
    description: |
      The `key` of the Asset to remove.
