#%RAML 1.0 DataType
(package): Product
(docs-uri): https://docs.commercetools.com/http-api-projects-products.html#revert-staged-changes
type: ProductUpdateAction
displayName: ProductRevertStagedChangesAction
discriminatorValue: revertStagedChanges
(postman-example): !include ../../../examples/Product/ProductRevertStagedChangesAction.json
