#%RAML 1.0 DataType
(package): Product
type: ProductUpdateAction
displayName: ProductChangeMasterVariantAction
discriminatorValue: changeMasterVariant
description: |
  Assigns the specified Product Variant to the `masterVariant` and removes the same from `variants` at the same time. The current Master Variant becomes part of the `variants` array.
  Either `variantId` or `sku` is required.
example: !include ../../../examples/Product/ProductChangeMasterVariantAction.json
properties:
  variantId?:
    type: number
    format: int64
    description: |
      The `id` of the ProductVariant to become the Master Variant.
  sku?:
    type: string
    description: |
      The `sku` of the ProductVariant to become the Master Variant.
  staged?:
    type: boolean
    description: |
      If `true`, only the staged Master Variant is changed. If `false`, both the current and staged Master Variant are changed.
    default: true
