#%RAML 1.0 DataType
(package): Product
type: ProductUpdateAction
displayName: ProductSetKeyAction
discriminatorValue: setKey
example: !include ../../../examples/Product/ProductSetKeyAction.json
properties:
  key?:
    type: string
    description: |
      Value to set. If empty, any existing value will be removed.

      To update a Product using the [Import API](/../api/import-export/) and the [Merchant Center](/../merchant-center/import-data), the Product `key` must match the pattern `^[A-Za-z0-9_-]{2,256}$`.
