#%RAML 1.0 DataType
(package): Product
type: ProductUpdateAction
displayName: ProductSetProductPriceCustomFieldAction
discriminatorValue: setProductPriceCustomField
example: !include ../../../examples/Product/ProductSetProductPriceCustomFieldAction.json
properties:
  priceId:
    type: string
    description: |
      The `id` of the Embedded Price to update.
  staged?:
    type: boolean
    description: |
      If `true`, only the staged Embedded Price Custom Field is updated. If `false`, both the current and staged Embedded Price Custom Field are updated.
    default: true
  name:
    type: string
    description: |
      Name of the [Custom Field](/../api/projects/custom-fields).
  value?:
    type: CustomFieldValue
    description: |
      If `value` is absent or `null`, this field will be removed if it exists.
      Removing a field that does not exist returns an [InvalidOperation](ctp:api:type:InvalidOperationError) error.
      If `value` is provided, it is set for the field defined by `name`.
