#%RAML 1.0 DataType
(package): Product
(docs-uri): https://docs.commercetools.com/api/projects/products#unpublish
type: ProductUpdateAction
displayName: ProductUnpublishAction
discriminatorValue: unpublish
description: |
  Removes the current projection of the Product. The staged projection is unaffected. Unpublished Products only appear in query/search results with `staged=false`. Produces the [ProductUnpublishedMessage](ctp:api:type:ProductUnpublishedMessage).
example: !include ../../../examples/Product/ProductUnpublishAction.json
