#%RAML 1.0 DataType
(package): Product
type: ProductUpdateAction
displayName: ProductAddVariantAction
discriminatorValue: addVariant
example: !include ../../../examples/Product/ProductAddVariantAction.json
properties:
  sku?:
    type: string
    description: |
      Value to set. Must be unique.
  key?:
    type: string
    description: |
      Value to set. Must be unique.
  prices?:
    type: PriceDraft[]
    maxItems: 100
    description: |
      Embedded Prices for the Product Variant.
  images?:
    type: Image[]
    description: |
      Images for the Product Variant.
  attributes?:
    type: Attribute[]
    description: Attributes for the Product Variant.
  staged?:
    type: boolean
    description: |
      If `true` the new Product Variant is only staged. If `false` the new Product Variant is both current and staged.
    default: true
  assets?:
    type: AssetDraft[]
    description: |
      Media assets for the Product Variant.
