#%RAML 1.0 DataType
(package): Product
(docs-uri): https://docs.commercetools.com/http-api-projects-products.html#set-product-price-custom-type
type: ProductUpdateAction
displayName: ProductSetProductPriceCustomTypeAction
discriminatorValue: setProductPriceCustomType
example: !include ../../../examples/Product/ProductSetProductPriceCustomTypeAction.json
properties:
  priceId:
    type: string
  staged?:
    type: boolean
  type?:
    type: TypeResourceIdentifier
    description: |
      Defines the [Type](ctp:api:type:Type) that extends the Price with [Custom Fields](/../api/projects/custom-fields).
      If absent, any existing Type and Custom Fields are removed from the Price.
  fields?:
    type: FieldContainer
    description: |
      Sets the [Custom Fields](/../api/projects/custom-fields) fields for the Price.
