#%RAML 1.0 DataType
(package): Product
type: ProductUpdateAction
displayName: ProductSetProductPriceCustomTypeAction
discriminatorValue: setProductPriceCustomType
example: !include ../../../examples/Product/ProductSetProductPriceCustomTypeAction.json
properties:
  priceId:
    type: string
    description: |
      The `id` of the Embedded Price to update.
  staged?:
    type: boolean
    description: |
      If `true`, only the staged Embedded Price is updated. If `false`, both the current and staged Embedded Price is updated.
    default: true
  type?:
    type: TypeResourceIdentifier
    description: |
      Defines the [Type](ctp:api:type:Type) that extends the Price with [Custom Fields](ctp:api:type:CustomFields).
      If absent, any existing Type and Custom Fields are removed from the Embedded Price.
  fields?:
    type: FieldContainer
    description: |
      Object containing the [Custom Fields](ctp:api:type:CustomFields) fields for the Embedded Price.

      Required if at least one Custom Field is defined as required in the `fieldDefinitions` of the referenced [Type](ctp:api:type:Type).
