#%RAML 1.0 DataType
(package): Product
type: ProductUpdateAction
displayName: ProductSetPriceKeyAction
discriminatorValue: setPriceKey
example: !include ../../../examples/Product/ProductSetPriceKeyAction.json
description: |
  Sets the key of an [Embedded Price](/projects/products#embedded-price). Produces the [ProductPriceKeySet](ctp:api:type:ProductPriceKeySetMessage) Message.
properties:
  priceId:
    type: string
    description: |
      The `id` of the [Price](ctp:api:type:Price) to set the key.
  staged?:
    type: boolean
    description: |
      If `true`, only the staged [Embedded Price](/projects/products#embedded-price) is updated. If `false`, both the current and staged Embedded Price are updated.
    default: true
  key?:
    type: string
    pattern: ^[A-Za-z0-9_-]+$
    minLength: 2
    maxLength: 256
    description: |
      Value to set. If empty, any existing value will be removed.
