#%RAML 1.0 DataType
(package): Product
(docs-uri): https://docs.commercetools.com/api/projects/products#remove-embedded-price
type: ProductUpdateAction
displayName: ProductRemovePriceAction
discriminatorValue: removePrice
example: !include ../../../examples/Product/ProductRemovePriceAction.json
properties:
  priceId:
    type: string
    description: |
      The `id` of the EmbeddedPrice to remove.
  staged?:
    type: boolean
    description: |
      If `true`, only the staged EmbeddedPrice is removed. If `false`, both the current and staged EmbeddedPrice are removed.
    default: true
