#%RAML 1.0 DataType
(package): Product
(docs-uri): https://docs.commercetools.com/api/projects/products#set-attribute-in-all-variants
type: ProductUpdateAction
displayName: ProductSetAttributeInAllVariantsAction
discriminatorValue: setAttributeInAllVariants
example: !include ../../../examples/Product/ProductSetAttributeInAllVariantsAction.json
description: |-
  Adds, removes, or changes a Product Attribute in all Product Variants at the same time.
  This action is useful for setting values for Attributes with the [Constraint](ctp:api:type:AttributeConstraintEnum) `SameForAll`.
properties:
  name:
    type: string
    description: |
      The name of the Attribute to set.
  value?:
    type: any
    description: |
      Value to set for the Attributes. If empty, any existing value will be removed.

      The [AttributeType](ctp:api:type:AttributeType) determines the format of the Attribute `value` to be provided:

      - For [Enum Type](ctp:api:type:AttributeEnumType) and [Localized Enum Type](ctp:api:type:AttributeLocalizedEnumType),
        use the `key` of the [Plain Enum Value](ctp:api:type:AttributePlainEnumValue) or [Localized Enum Value](ctp:api:type:AttributeLocalizedEnumValue) objects,
        or the complete objects as `value`.
      - For [Localizable Text Type](ctp:api:type:AttributeLocalizableTextType), use the [LocalizedString](ctp:api:type:LocalizedString) object as `value`.
      - For [Money Type](ctp:api:type:AttributeMoneyType) Attributes, use the [Money](ctp:api:type:Money) object as `value`.
      - For [Set Type](ctp:api:type:AttributeSetType) Attributes, use the entire `set` object  as `value`.
      - For [Nested Type](ctp:api:type:AttributeNestedType) Attributes, use the list of values of all Attributes of the nested Product as `value`.
      - For [Reference Type](ctp:api:type:AttributeReferenceType) Attributes, use the [Reference](ctp:api:type:Reference) object as `value`.
  staged?:
    type: boolean
    description: |
      If `true`, only the staged Attributes are set. If `false`, both the current and staged Attributes are set.
    default: true
