#%RAML 1.0 DataType
(package): AssociateRole
(docs-uri): https://docs.commercetools.com/api/projects/associate-roles#associateroledraft
displayName: AssociateRoleDraft
description: |
properties:
  key:
    type: string
    description: |
      User-defined unique identifier for the AssociateRole.
    pattern: ^[A-Za-z0-9_-]+$
    minLength: 2
    maxLength: 256
  name?:
    type: string
    description: |
      Name of the AssociateRole.
  buyerAssignable?:
    type: boolean
    default: true
    description: |
      Whether the AssociateRole can be assigned to an Associate by a [buyer](/../api/associates-overview#buyer).
  permissions?:
    type: Permission[]
    description: |
      List of Permissions for the AssociateRole.
  custom?:
    type: CustomFieldsDraft
    description: |
      Custom Fields for the AssociateRole.
