#%RAML 1.0 DataType
(package): AssociateRole
displayName: AssociateRoleKeyReference
type: KeyReference
discriminatorValue: associate-role
description: |
  [KeyReference](ctp:api:type:KeyReference) to an [AssociateRole](ctp:api:type:AssociateRole).
properties:
  key:
    type: string
    description: |
      Unique and immutable key of the referenced [AssociateRole](ctp:api:type:AssociateRole).
