#%RAML 1.0 DataType
(package): AssociateRole
type: ResourceIdentifier
displayName: AssociateRoleResourceIdentifier
discriminatorValue: associate-role
description: |
  [ResourceIdentifier](ctp:api:type:TypeResourceIdentifier) of an [AssociateRole](ctp:api:type:AssociateRole). Either `id` or `key` is required. If both are set, an [InvalidJsonInput](/../api/errors#invalidjsoninput) error is returned.
properties:
  id?:
    type: string
    description: |
      Unique identifier of the referenced [AssociateRole](ctp:api:type:AssociateRole). Required if `key` is absent.
  key?:
    type: string
    description: |
      Unique key of the referenced [AssociateRole](ctp:api:type:AssociateRole). Required if `id` is absent.
