#%RAML 1.0 DataType
(package): Product
(docs-uri): https://docs.commercetools.com/http-api-projects-products.html#productvariantdraft
displayName: ProductVariantDraft
type: object
properties:
  sku?:
    type: string
  key?:
    type: string
  prices?:
    type: PriceDraft[]
  attributes?:
    type: Attribute[]
  images?:
    type: Image[]
  assets?:
    type: AssetDraft[]
