#%RAML 1.0 DataType
(package): OrderEdit
(docs-uri): https://docs.commercetools.com/http-api-projects-order-edits.html#setcustomtype
type: OrderEditUpdateAction
displayName: OrderEditSetCustomTypeAction
discriminatorValue: setCustomType
(postman-example): !include ../../../examples/OrderEdit/OrderEditSetCustomTypeAction.json
properties:
  type?:
    type: TypeResourceIdentifier
    description: |-
      If set, the custom type is set to this new value.
      If absent, the custom type and any existing custom fields are removed.
  fields?:
    type: object
    description: If set, the custom fields are set to this new value.
