#%RAML 1.0 DataType
(package): OrderEdit
(docs-uri): https://docs.commercetools.com/http-api-projects-order-edits.html#set-customlineitem-taxrate
type: StagedOrderUpdateAction
displayName: StagedOrderSetCustomLineItemTaxRateAction
discriminatorValue: setCustomLineItemTaxRate
(postman-example): !include ../../../examples/OrderEdit/StagedOrderSetCustomLineItemTaxRateAction.json
properties:
  customLineItemId:
    type: string
  externalTaxRate?:
    type: ExternalTaxRateDraft
