#%RAML 1.0 DataType
(package): OrderEdit
(docs-uri): https://docs.commercetools.com/http-api-projects-order-edits.html#set-delivery-items
type: StagedOrderUpdateAction
displayName: StagedOrderSetDeliveryItemsAction
discriminatorValue: setDeliveryItems
(postman-example): !include ../../../examples/OrderEdit/StagedOrderSetDeliveryItemsAction.json
properties:
  deliveryId:
    type: string
  items:
    type: DeliveryItem[]
