#%RAML 1.0 DataType
(package): OrderEdit
(docs-uri): https://docs.commercetools.com/http-api-projects-order-edits.html#change-orderstate
type: StagedOrderUpdateAction
displayName: StagedOrderChangeOrderStateAction
discriminatorValue: changeOrderState
(postman-example): !include ../../../examples/OrderEdit/StagedOrderChangeOrderStateAction.json
properties:
  orderState:
    type: OrderState
