#%RAML 1.0 DataType
(package): OrderEdit
(docs-uri): https://docs.commercetools.com/http-api-projects-order-edits.html#add-parcel
type: StagedOrderUpdateAction
displayName: StagedOrderAddParcelToDeliveryAction
discriminatorValue: addParcelToDelivery
(postman-example): !include ../../../examples/OrderEdit/StagedOrderAddParcelToDeliveryAction.json
properties:
  deliveryId:
    type: string
  measurements?:
    type: ParcelMeasurements
  trackingData?:
    type: TrackingData
  items?:
    type: DeliveryItem[]
