#%RAML 1.0 DataType
(package): OrderEdit
(docs-uri): https://docs.commercetools.com/http-api-projects-order-edits.html#set-order-number
type: StagedOrderUpdateAction
displayName: StagedOrderSetOrderNumberAction
discriminatorValue: setOrderNumber
(postman-example): !include ../../../examples/OrderEdit/StagedOrderSetOrderNumberAction.json
properties:
  orderNumber?:
    type: string
