#%RAML 1.0 DataType
(package): OrderEdit
(docs-uri): https://docs.commercetools.com/http-api-projects-order-edits.html#update-syncinfo
type: StagedOrderUpdateAction
displayName: StagedOrderUpdateSyncInfoAction
discriminatorValue: updateSyncInfo
(postman-example): !include ../../../examples/OrderEdit/StagedOrderUpdateSyncInfoAction.json
properties:
  channel:
    type: ChannelResourceIdentifier
  externalId?:
    type: string
  syncedAt?:
    type: datetime
