#%RAML 1.0 DataType
(package): OrderEdit
(docs-uri): https://docs.commercetools.com/http-api-projects-order-edits.html#change-paymentstate
type: StagedOrderUpdateAction
displayName: StagedOrderChangePaymentStateAction
discriminatorValue: changePaymentState
(postman-example): !include ../../../examples/OrderEdit/StagedOrderChangePaymentStateAction.json
properties:
  paymentState?:
    type: PaymentState
