#%RAML 1.0 DataType
(package): OrderEdit
(docs-uri): https://docs.commercetools.com/http-api-projects-order-edits.html#set-customlineitem-taxamount
type: StagedOrderUpdateAction
displayName: StagedOrderSetCustomLineItemTaxAmountAction
discriminatorValue: setCustomLineItemTaxAmount
(postman-example): !include ../../../examples/OrderEdit/StagedOrderSetCustomLineItemTaxAmountAction.json
properties:
  customLineItemId:
    type: string
  externalTaxAmount?:
    type: ExternalTaxAmountDraft
