#%RAML 1.0 DataType
(package): OrderEdit
(docs-uri): https://docs.commercetools.com/http-api-projects-order-edits.html#set-shippingmethod-taxamount
type: StagedOrderUpdateAction
displayName: StagedOrderSetShippingMethodTaxAmountAction
discriminatorValue: setShippingMethodTaxAmount
(postman-example): !include ../../../examples/OrderEdit/StagedOrderSetShippingMethodTaxAmountAction.json
properties:
  externalTaxAmount?:
    type: ExternalTaxAmountDraft
