#%RAML 1.0 DataType
(package): Inventory
type: object
displayName: InventoryEntryUpdate
properties:
  version:
    type: number
    format: int64
  actions:
    type: array
    items: InventoryEntryUpdateAction
