#%RAML 1.0 DataType
(annotations.package): Transaction
(annotations.beta): true
displayName: TransactionItemDraft
type: object
properties:
  paymentIntegration:
    type: PaymentIntegrationResourceIdentifier
    description: Resource Identifier of the [Payment Integration](/payment-connectors-applications#payment-integrations) to use to execute the payment.
  amount?:
    type: common.Amount
    description: Money value of the Transaction Item.
