#%RAML 1.0 DataType
(annotations.package): Transaction
(annotations.beta): true
displayName: TransactionItem
type: TransactionItemDraft
description: |
  Payment information related to the [Transaction](/transactions-api#transaction).
properties:
  payment?:
    type: PaymentReference
    description: Reference to the [Payment](/../api/projects/payments#payment) associated with the Transaction Item.
  paymentIntegration:
    type: PaymentIntegrationReference
    description: Reference to the [Payment Integration](/connectors-and-applications#payment-integrations) to use to execute the payment.
