#%RAML 1.0 DataType
(annotations.package): Transaction
(annotations.beta): true
type: object
description: |
  The state of the [Transaction](/transactions-api#transaction) and the related errors in case of a failed Transaction.
displayName: TransactionStatus
properties:
  state:
    type: TransactionState
    description: State of the Transaction.
  errors?:
    type: TransactionError[]
    description: Errors returned if the Transaction is in the `Failed` state.
