#%RAML 1.0 DataType
(annotations.package): Transaction
(annotations.beta): true
type: object
displayName: TransactionDraft
properties:
  key?:
    type: string
    description: User-defined unique identifier of the Transaction.
    pattern: ^[A-Za-z0-9_-]+$
    minLength: 2
    maxLength: 256
  application:
    type: ApplicationResourceIdentifier
    description: |
      [Application](/connectors-and-applications#applications) for which the payment is executed.
  transactionItems:
    type: TransactionItemDraft[]
    description: Transaction Item associated with the Transaction.
    minItems: 1
    maxItems: 1
  cart:
    type: CartResourceIdentifier
    description: |
      [Cart](/../api/projects/carts#cart) for which the payment must be executed.
