#%RAML 1.0 DataType
(package): QuoteRequest
type: object
displayName: QuoteRequestUpdate
(java-extends): 'com.commercetools.api.models.ResourceUpdate<QuoteRequestUpdate, QuoteRequestUpdateAction, QuoteRequestUpdateBuilder>'
properties:
  version:
    type: number
    format: int64
    description: |
      Expected version of the [QuoteRequest](ctp:api:type:QuoteRequest) to which the changes should be applied.
      If the expected version does not match the actual version, a [409 Conflict](/../api/errors#409-conflict) error will be returned.
  actions:
    type: array
    items: QuoteRequestUpdateAction
    description: |
      Update actions to be performed on the [QuoteRequest](ctp:api:type:QuoteRequest).
