#%RAML 1.0 DataType
(package): QuoteRequest
(docs-uri):
(java-extends): com.commercetools.api.models.Identifiable<QuoteRequest>
type: ResourceIdentifier
displayName: QuoteRequestResourceIdentifier
discriminatorValue: quote-request
description: |
  [ResourceIdentifier](ctp:api:type:ResourceIdentifier) to a [QuoteRequest](ctp:api:type:QuoteRequest).
