#%RAML 1.0 DataType
(package): BusinessUnitSearch
displayName: BusinessUnitSearchIndexingStatusResponse
type: object
(beta): true
example: !include ../../examples/BusinessUnitSearch/BusinessUnitSearchIndexingStatusResponse.json
properties:
  status:
    type: BusinessUnitIndexingStatus
    description: Current status of indexing the Business Unit Search.
  states?:
    type: BusinessUnitIndexingProgress
    description: Progress of indexing. Only available when indexing is in progress.
  startedAt?:
    type: datetime
    description: Date and time (UTC) when the last indexing started.
  lastModifiedAt?:
    type: datetime
    description: Time when the status was last modified.
  retryCount?:
    type: number
    format: int32
    description: |
      Indicates how many times the system tried to start indexing after failed attempts. The counter is set to null after an indexing finished successfully.
