#%RAML 1.0 DataType
(package): ApprovalRule
displayName: ApproverConjunction
type: object
properties:
  and:
    description: |
      All of the nested disjunctions must be approved in order for the conjunction to be considered approved.
    type: array
    items: ApproverDisjunction
    minItems: 1
