#%RAML 1.0 DataType
(package): ApprovalRule
type: object
displayName: ApprovalRuleDraft
properties:
  key?:
    type: string
    description: |
      User-defined unique identifier of the Approval Rule. Uniqueness is enforced within the Business Unit.
    pattern: ^[A-Za-z0-9_-]+$
    minLength: 2
    maxLength: 256
  name:
    type: string
    description: |
      Name of the Approval Rule.
  description?:
    type: string
    description: |
      Description of the Approval Rule.
  status:
    type: ApprovalRuleStatus
    description: |
      Indicates whether the Approval Rule should be matched against [Orders](ctp:api:type:Order) or not.
  predicate:
    type: string
    description: |
      The [predicate](/../api/predicates/predicate-operators) describing the [Orders](ctp:api:type:Order) the Approval Rule should match against.
  approvers:
    type: ApproverHierarchyDraft
    description: |
      The hierarchy of approvers within the Approval Rule.
  requesters:
    type: array
    items: RuleRequesterDraft
    minItems: 1
    uniqueItems: true
    description: |
      The [Associate Roles](ctp:api:type:AssociateRole) customers must hold for their Order to require approval.
