#%RAML 1.0 DataType
(package): ApprovalRule
type: ApprovalRuleUpdateAction
displayName: ApprovalRuleSetPredicateAction
discriminatorValue: setPredicate
example: !include ../../examples/ApprovalRule/ApprovalRuleSetPredicateAction.json
description: |
  Setting the [Order Predicate](/../api/projects/predicates#order-predicates) for an [Approval Rule](ctp:api:type:ApprovalRule) generates an [ApprovalRulePredicateSet](ctp:api:type:ApprovalRulePredicateSetMessage) Message.
properties:
  predicate:
    type: string
    description: A valid [Order Predicate](/../api/projects/predicates#order-predicates) to set for the Approval Rule.
