#%RAML 1.0 DataType
(package): ApprovalRule
(docs-uri): https://docs.commercetools.com/api/projects/approvalrules#approverhierarchydraft
displayName: ApproverHierarchyDraft
type: object
description: |
  Describes the sequence in which [Associates](ctp:api:type:Associate) can approve an [Order](ctp:api:type:Order).
properties:
  tiers:
    description: |
      Nested conjunctions representing tiers of approvers in a hierarchy.
    type: array
    items: ApproverConjunctionDraft
    minItems: 1
    maxItems: 5
