#%RAML 1.0 DataType
(package): ApprovalRule
(docs-uri): https://docs.commercetools.com/api/projects/approvalrules#approvalrulestatus
(beta): true
displayName: ApprovalRuleStatus
type: string
description: |
  Indicates whether the Approval Rule should be matched against [Orders](ctp:api:type:Order) or not.
enum:
  - Active
  - Inactive
(enumDescriptions):
  Active: |
    The Approval Rule is in effect and will be used in evaluating approval requests for [Orders](ctp:api:type:Order).
  Inactive: |
    The Approval Rule is not in effect and will not be used in evaluating approval requests for Orders.
