#%RAML 1.0 DataType
(package): ApprovalRule
(docs-uri): https://docs.commercetools.com/api/projects/approvalrules#set-name
(beta): true
type: ApprovalRuleUpdateAction
displayName: ApprovalRuleSetNameAction
discriminatorValue: setName
example: !include ../../examples/ApprovalRule/ApprovalRuleSetNameAction.json
description: |
  Setting the name for an [Approval Rule](ctp:api:type:ApprovalRule) generates an [ApprovalRuleNameSet](ctp:api:type:ApprovalRuleNameSetMessage) Message.
properties:
  name:
    type: string
    description: New name to set for the Approval Rule.
