#%RAML 1.0 DataType
(package): ApprovalRule
displayName: RuleRequesterDraft
type: object
properties:
  associateRole:
    description: |
      The [Associate Role](ctp:api:type:AssociateRole) that an [Associate](ctp:api:type) must hold for the Approval Rule to apply to the Orders they create.
    type: AssociateRoleResourceIdentifier
