#%RAML 1.0 DataType

displayName: AssetSource
uses:
    api: ../types.lib.raml
type: object
(generate-collection): true
properties:
    uri:
        type: string
    key?:
        type: string
    dimensions?:
        type: api.AssetDimensions
    contentType?:
        type: string
