#%RAML 1.0 DataType
(package): Common
displayName: CountryCode
type: string
description: |
  A two-digit country code as per [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2).
pattern: ^[A-Z]{2}$
