#%RAML 1.0 DataType

displayName: Image

type: object
(generate-collection): true
properties:
    url:
        type: string
    dimensions:
        type: ImageDimensions
    label?:
        type: string
