#%RAML 1.0 DataType
(package): Common
displayName: LastModifiedBy
type: ClientLogging
properties:
  clientId?:
    description: ''
    type: string
  externalUserId?:
    description: ''
    type: string
  anonymousId?:
    description: ''
    type: string
  customer?:
    description: ''
    type: CustomerReference
