#%RAML 1.0 DataType

displayName: Money
uses:
    api: ../types.lib.raml
type: object
properties:
    centAmount:
        type: integer
    currencyCode:
        (generator-type): string
        type: api.CurrencyCode
