#%RAML 1.0 DataType


displayName: Reference
type: object
discriminator: typeId
(generate-collection): true
properties:
    typeId:
        (generator-type): string
        type: ReferenceTypeId
    id:
        type: string
