#%RAML 1.0 DataType
(package): Common


displayName: ResourceIdentifier
type: object
properties:
    typeId?:
        type: ReferenceTypeId
    id?:
        type: string
    key?:
        type: string
