#%RAML 1.0 DataType
(package): Common

displayName: Resource

type: object
properties:
    id:
        type: string
    version:
        type: number
        format: int64
    createdAt:
        type: datetime
    lastModifiedAt:
        type: datetime
