#%RAML 1.0 DataType
(annotations.package): Deployment
displayName: DeploymentLogCursorPagedQueryResponse
description: |
  A cursor paged query result containing an array of [DeploymentLog](ctp:connect:type:DeploymentLog).
properties:
  data:
    type: DeploymentLog[]
    description: Array of DeploymentLog objects.
  next:
    type: string
    description: The next page token.
