#%RAML 1.0 DataType
(annotations.package): Deployment
displayName: DeploymentLog
example: !include ../../examples/deployment/DeploymentLog.json
description: |
  The data representation of a Deployment log.
properties:
  type:
    type: string
    enum:
      - 'HTTP_REQUEST'
      - 'APPLICATION_TEXT'
      - 'APPLICATION_JSON'
  deploymentId:
    type: string
    description: Unique identifier of the [Deployment](ctp:connect:type:Deployment).
  applicationName:
    type: string
    description: Name of the Connect application.
  severity:
    type: string
    description: Severity of the log message.
  timestamp:
    type: datetime
    description: Timestamp of the log message.
  details:
    type: any
    description: Event details of the log message.
