#%RAML 1.0 DataType
(annotations.package): Deployment
displayName: DeploymentDraft
example: !include ../../examples/deployment/DeploymentDraft.json
properties:
  key?:
    type: string
    description: User-defined unique identifier for the Deployment.
    pattern: ^[A-Za-z0-9_-]+$
    minLength: 2
    maxLength: 256
  type?:
    type: common.DeploymentType
    description: Deployment type. If a [ConnectorStaged](ctp:connect:type:ConnectorStaged) is referenced in the `connector` field, you can send only `preview`. If a [Connector](ctp:connect:type:Connector) is referenced in the `connector` field, the value defaults to `sandbox`. However, you can send `production` when you are ready to deploy the Connector to your production environment.
  connector:
    type: common.ConnectorReference
    description: Reference to the [Connector](ctp:connect:type:Connector) or [ConnectorStaged](ctp:connect:type:ConnectorStaged) being deployed.
  configurations:
    type: common.DeploymentConfigurationApplication[]
    description: Configuration values needed by the [Connector](ctp:connect:type:Connector) for hosting. Keys should match those in the Connector's `configurations` field.
  globalConfiguration?:
    type: common.DeploymentGlobalConfiguration
    description: Global configuration values needed by the [Connector](ctp:connect:type:Connector) for hosting. Keys should match those in the Connector's `globalConfiguration` field.
  region:
    type: common.Region
    description: Region of Deployment.
