#%RAML 1.0 DataType
(package): Review
(docs-uri): https://docs.commercetools.com/http-api-projects-reviews.html#set-target
type: ReviewUpdateAction
displayName: ReviewSetTargetAction
discriminatorValue: setTarget
(postman-example): !include ../../../examples/Review/ReviewSetTargetAction.json
properties:
  target:
    type: ProductResourceIdentifier | ChannelResourceIdentifier
    description: |-
      Identifies the target of the review.
      Can be a Product or a Channel.
      If `target` is absent or `null`, this field will be removed if it exists.
