#%RAML 1.0 DataType
(package): Review
(docs-uri): https://docs.commercetools.com/http-api-projects-reviews.html#set-title
type: ReviewUpdateAction
displayName: ReviewSetTitleAction
discriminatorValue: setTitle
(postman-example): !include ../../../examples/Review/ReviewSetTitleAction.json
properties:
  title?:
    type: string
    description: If `title` is absent or `null`, this field will be removed if it exists.
