#%RAML 1.0 DataType
(package): Review
(docs-uri): https://docs.commercetools.com/http-api-projects-reviews.html#set-custom-type
type: ReviewUpdateAction
displayName: ReviewSetCustomTypeAction
discriminatorValue: setCustomType
(postman-example): !include ../../../examples/Review/ReviewSetCustomTypeAction.json
properties:
  type?:
    type: TypeResourceIdentifier
    description: If absent, the custom type and any existing custom fields are removed.
  fields?:
    type: FieldContainer
    description: |-
      A valid JSON object, based on the FieldDefinitions of the Type.
      Sets the CustomFields to this value.
