#%RAML 1.0 DataType
(package): CustomerGroup
(docs-uri): https://docs.commercetools.com/http-api-projects-customerGroups.html#set-customfield
type: CustomerGroupUpdateAction
displayName: CustomerGroupSetCustomFieldAction
discriminatorValue: setCustomField
(postman-example): !include ../../../examples/CustomerGroup/CustomerGroupSetCustomFieldAction.json
properties:
  name:
    type: string
    description: ''
  value?:
    type: any
