#%RAML 1.0 DataType
(package): Cart
(docs-uri): https://docs.commercetools.com/http-api-projects-carts.html#shippinginfo
displayName: ShippingInfo
type: object
properties:
  shippingMethodName:
    type: string
    description: ''
  price:
    type: TypedMoney
    description:
      Determined based on the ShippingRate and its tiered prices, and either the
      sum of LineItem prices or the `shippingRateInput` field.
  shippingRate:
    type: ShippingRate
    description: The shipping rate used to determine the price.
  taxedPrice?:
    type: TaxedItemPrice
    description: Set once the `taxRate` is set.
  taxRate?:
    type: TaxRate
    description: |-
      Will be set automatically in the `Platform` TaxMode once the shipping address is set is set.
      For the `External` tax mode the tax rate has to be set explicitly with the ExternalTaxRateDraft.
  taxCategory?:
    type: TaxCategoryReference
    description: ''
  shippingMethod?:
    type: ShippingMethodReference
    description: Not set if custom shipping method is used.
  deliveries?:
    description:
      Deliveries are compilations of information on how the articles are being
      delivered to the customers.
    type: Delivery[]
  discountedPrice?:
    type: DiscountedLineItemPrice
    description: ''
  shippingMethodState:
    type: ShippingMethodState
    description:
      Indicates whether the ShippingMethod referenced in this ShippingInfo is
      allowed for the cart or not.
