#%RAML 1.0 DataType
(package): CartDiscount


type: CartDiscountUpdateAction
displayName: CartDiscountChangeCartPredicateAction
discriminatorValue: changeCartPredicate
example:
  {
    "action": "changeCartPredicate",
    "cartPredicate": "lineItemTotal(1 = 1) >  \"10.00 USD\""
    }
  }
properties:
    cartPredicate:
        type: string
