#%RAML 1.0 DataType
(package): CartDiscount


type: CartDiscountUpdateAction
displayName: CartDiscountChangeNameAction
discriminatorValue: changeName
properties:
    name:
        type: LocalizedString
