#%RAML 1.0 DataType
(package): CartDiscount
(docs-uri): https://docs.commercetools.com/http-api-projects-cartDiscounts.html#change-sort-order


type: CartDiscountUpdateAction
displayName: CartDiscountChangeSortOrderAction
discriminatorValue: changeSortOrder
example: |
  {
    "action": "changeSortOrder",
    "sortOrder": "0.2"
  }
properties:
    sortOrder:
        type: string
