#%RAML 1.0 DataType
(package): CartDiscount


type: CartDiscountUpdateAction
displayName: CartDiscountChangeIsActiveAction
discriminatorValue: changeIsActive
example:
  {
    "action": "changeIsActive",
    "isActive": false
  }
properties:
    isActive:
        type: boolean
