#%RAML 1.0 DataType
(package): Message
(docs-uri): https://docs.commercetools.com/http-api-message-types#inventoryentryquantityset-message
type: MessagePayload
displayName: InventoryEntryQuantitySetMessagePayload
discriminatorValue: InventoryEntryQuantitySet
properties:
  oldQuantityOnStock:
    type: integer
  newQuantityOnStock:
    type: integer
  oldAvailableQuantity:
    type: integer
  newAvailableQuantity:
    type: integer
