#%RAML 1.0 DataType
(package): StandalonePrice
type: object
displayName: StandalonePriceUpdateAction
discriminator: action
(java-extends): 'com.commercetools.api.models.ResourceUpdateAction<StandalonePriceUpdateAction>'
properties:
  action:
    type: string
