#%RAML 1.0 DataType
(package): StandalonePrice
(docs-uri): https://docs.commercetools.com/http-api-projects-standalone-prices#standaloneprices
type: ResourceIdentifier
displayName: StandalonePriceResourceIdentifier
discriminatorValue: standalone-price
description: |
  [ResourceIdentifier](/../api/types#resourceidentifier) to a [StandalonePrice](ctp:api:type:StandalonePrice).
