#%RAML 1.0 DataType
(package): StandalonePrice
type: Reference
displayName: StandalonePriceReference
discriminatorValue: standalone-price
description: |
  [Reference](ctp:api:type:Reference) to a [StandalonePrice](ctp:api:type:StandalonePrice).
properties:
  obj?:
    type: StandalonePrice
    description: |
      Contains the representation of the expanded StandalonePrice. Only present in responses to requests with [Reference Expansion](/../api/general-concepts#reference-expansion) for StandalonePrice.
