#%RAML 1.0 DataType
(package): StandalonePrice
(docs-uri): https://docs.commercetools.com/http-api-projects-standalone-prices#standalonepricedraft
displayName: StandalonePriceDraft
type: object
description: |-
  Standalone Prices are defined with a scope consisting of `currency` and optionally `country`, `customerGroup`, and `channel` and/or a validity period (`validFrom` and/or `validTo`). For more information see [price selection](/../api/projects/products#price-selection).
  Creating a Standalone Price is rejected if there already exists a Standalone Price for the same SKU with exactly the same price scope, or with overlapping validity periods within the same price scope. A Price without validity period does not conflict with a Price defined for a time period.
properties:
  key?:
    type: string
    description: |-
      User-defined unique identifier for the StandalonePrice.
    pattern: ^[A-Za-z0-9_-]+$
    minLength: 2
    maxLength: 256
  sku:
    type: string
    description: |-
      Specifies to which [ProductVariant](ctp:api:type:ProductVariant) the Platform associates this Price.
      It is not validated to exist in product variants.
  value:
    type: Money
    description: |
      Sets the money value of this Price.
  country?:
    type: CountryCode
    description: |
      Sets the country for which this Price is valid.
  customerGroup?:
    type: CustomerGroupResourceIdentifier
    description: |
      Sets the [CustomerGroup](ctp:api:type:CustomerGroup) for which this Price is valid.
  channel?:
    type: ChannelResourceIdentifier
    description: |
      Sets the product distribution [Channel](ctp:api:type:Channel) for which this Price is valid.
  validFrom?:
    type: datetime
    description: |
      Sets the date from which the Price is valid.
  validUntil?:
    type: datetime
    description: |
      Sets the date until the Price is valid.
  tiers?:
    type: PriceTierDraft[]
    description: |
      Sets price tiers.
  discounted?:
    type: DiscountedPriceDraft
    description: |
      Sets a discounted price for this Price that is different from the base price with `value`.
  custom?:
    type: CustomFieldsDraft
    description: |
      Custom Fields for the StandalonePrice.
