#%RAML 1.0 DataType
(package): State
(docs-uri): https://docs.commercetools.com/http-api-projects-states.html#change-state-type
type: StateUpdateAction
displayName: StateChangeTypeAction
discriminatorValue: changeType
(postman-example): !include ../../../examples/State/StateChangeTypeAction.json
properties:
  type:
    type: StateTypeEnum
