#%RAML 1.0 DataType
(package): State
type: StateUpdateAction
displayName: StateChangeTypeAction
discriminatorValue: changeType
example: !include ../../../examples/State/StateChangeTypeAction.json
properties:
  type:
    type: StateTypeEnum
    description: |
      Resource or object types the State shall be assigned to.
      Must not be empty.
