#%RAML 1.0 DataType
(package): State
type: StateUpdateAction
displayName: StateSetDescriptionAction
discriminatorValue: setDescription
example: !include ../../../examples/State/StateSetDescriptionAction.json
properties:
  description:
    type: LocalizedString
    description: |
      Value to set.
      If the new value is the same as the current value, an [InvalidOperation](ctp:api:type:InvalidOperationError) error is returned.

      Set to an empty object to remove any existing value.
