type:
  baseDomain:
    resourceType: Category
    resourceQueryType: CategoryPagedQueryResponse
    resourceDraft: CategoryDraft
    whereExample: 'name(en = "main store")'
    sortExample: name.en asc
(updateable): Category
(deleteable): Category
(createable): CategoryDraft
description: Categories are used to organize products in a hierarchical structure.
get:
  description: |
    Either the [scope](/../api/scopes) `view_products:{projectKey}` or `view_categories:{projectKey}` is required.
  securedBy:
    [
      oauth_2_0:
        {
          scopes:
            ['view_products:{projectKey}', 'view_categories:{projectKey}'],
        },
    ]
  responses:
    200:
      body:
        application/json:
          example: !include ../examples/categories.example.json
head:
  securedBy:
    [
      oauth_2_0:
        {
          scopes:
            ['view_products:{projectKey}', 'view_categories:{projectKey}'],
        },
    ]
  description: Checks if one or more Categories exist for the provided query predicate. Returns a `200 OK` status if any Categories match the query predicate, or a `404 Not Found` otherwise.
  queryParameters:
    where?:
      type: QueryPredicate[]
      description: |-
        Query Predicates on Categories are limited to [Text](ctp:api:type:AttributeTextType),
        [Enum](ctp:api:type:AttributeEnumType), [Boolean](ctp:api:type:AttributeBooleanType),
        [Number](ctp:api:type:AttributeNumberType), [Date](ctp:api:type:AttributeDateType),
        [Time](ctp:api:type:AttributeTimeType), and [DateTime](ctp:api:type:AttributeDateTimeType) attribute types.
post:
  description: |
    Either the [scope](/../api/scopes) `manage_products:{projectKey}` or `manage_categories:{projectKey}` is required.

    Creating a Category produces the [CategoryCreated](ctp:api:type:CategoryCreatedMessage) Message.
  securedBy:
    [
      oauth_2_0:
        {
          scopes:
            ['manage_products:{projectKey}', 'manage_categories:{projectKey}'],
        },
    ]
  body:
    application/json:
      example: !include ../examples/category-create.example.json
  responses:
    201:
      body:
        application/json:
          example: !include ../examples/category.example.json
/key={key}:
  (methodName): withKey
  type:
    baseResource:
      uriParameterName: key
      resourceType: Category
      resourceUpdateType: CategoryUpdate
  get:
    description: |
      Either the [scope](/../api/scopes) `view_products:{projectKey}` or `view_categories:{projectKey}` is required.
    securedBy:
      [
        oauth_2_0:
          {
            scopes:
              ['view_products:{projectKey}', 'view_categories:{projectKey}'],
          },
      ]
    responses:
      200:
        body:
          application/json:
            example: !include ../examples/category.example.json
  head:
    securedBy:
      [
        oauth_2_0:
          {
            scopes:
              ['view_products:{projectKey}', 'view_categories:{projectKey}'],
          },
      ]
    description: Checks if a Category exists with the provided `key`. Returns a `200 OK` status if the Category exists or a `404 Not Found` otherwise.
  post:
    description: |
      Either the [scope](/../api/scopes) `manage_products:{projectKey}` or `manage_categories:{projectKey}` is required.
    securedBy:
      [
        oauth_2_0:
          {
            scopes:
              [
                'manage_products:{projectKey}',
                'manage_categories:{projectKey}',
              ],
          },
      ]
    body:
      application/json:
        example: !include ../examples/category-update.example.json
    responses:
      200:
        body:
          application/json:
            example: !include ../examples/category.example.json
  delete:
    description: |
      Either the [scope](/../api/scopes) `manage_products:{projectKey}` or `manage_categories:{projectKey}` is required.
    securedBy:
      [
        oauth_2_0:
          {
            scopes:
              [
                'manage_products:{projectKey}',
                'manage_categories:{projectKey}',
              ],
          },
      ]
    responses:
      200:
        body:
          application/json:
            example: !include ../examples/category.example.json
/{ID}:
  (methodName): withId
  type:
    baseResource:
      uriParameterName: ID
      resourceType: Category
      resourceUpdateType: CategoryUpdate
  get:
    description: |
      Either the [scope](/../api/scopes) `view_products:{projectKey}` or `view_categories:{projectKey}` is required.
    securedBy:
      [
        oauth_2_0:
          {
            scopes:
              ['view_products:{projectKey}', 'view_categories:{projectKey}'],
          },
      ]
    responses:
      200:
        body:
          application/json:
            example: !include ../examples/category.example.json
  head:
    securedBy:
      [
        oauth_2_0:
          {
            scopes:
              ['view_products:{projectKey}', 'view_categories:{projectKey}'],
          },
      ]
    description: Checks if a Category exists with the provided `id`. Returns a `200 OK` status if the Category exists or a `404 Not Found` otherwise.
  post:
    description: |
      Either the [scope](/../api/scopes) `manage_products:{projectKey}` or `manage_categories:{projectKey}` is required.
    securedBy:
      [
        oauth_2_0:
          {
            scopes:
              [
                'manage_products:{projectKey}',
                'manage_categories:{projectKey}',
              ],
          },
      ]
    body:
      application/json:
        example: !include ../examples/category-update.example.json
    responses:
      200:
        body:
          application/json:
            example: !include ../examples/category.example.json
  delete:
    description: |
      Either the [scope](/../api/scopes) `manage_products:{projectKey}` or `manage_categories:{projectKey}` is required.
    securedBy:
      [
        oauth_2_0:
          {
            scopes:
              [
                'manage_products:{projectKey}',
                'manage_categories:{projectKey}',
              ],
          },
      ]
    responses:
      200:
        body:
          application/json:
            example: !include ../examples/category.example.json
