type:
  baseDomain:
    resourceType: DiscountGroup
    resourceQueryType: DiscountGroupPagedQueryResponse
    resourceDraft: DiscountGroupDraft
    whereExample: 'key = "summersale"'
    sortExample: createdAt asc
(updateable): DiscountGroup
(deleteable): DiscountGroup
(createable): DiscountGroupDraft
description: Discount groups are used to group the discounts that are applied to a cart or an order.
get:
  displayName: Query DiscountGroups
  description: |
    Retrieves all DiscountGroups in the Project.
  securedBy: [oauth_2_0: { scopes: ['view_cart_discounts:{projectKey}'] }]
  responses:
    200:
      body:
        application/json:
          example: !include ../examples/discount-groups.example.json
head:
  displayName: Check if DiscountGroup exists by Query Predicate
  description: |
    Checks if one or more DiscountGroups exist for the provided query predicate.
    Returns a `200` status if any DiscountGroups match the query predicate, or a `404` status otherwise.
  securedBy: [oauth_2_0: { scopes: ['view_cart_discounts:{projectKey}'] }]
  queryParameters:
    where?:
      type: QueryPredicate[]
post:
  displayName: Create DiscountGroup
  description: |
    Creates a DiscountGroup in the Project.
    This request generates the [DiscountGroupCreated](ctp:api:type:DiscountGroupCreatedMessage) Message.
  securedBy: [oauth_2_0: { scopes: ['manage_cart_discounts:{projectKey}'] }]
  body:
    application/json:
      example: !include ../examples/discount-group-create.example.json
  responses:
    201:
      body:
        application/json:
          example: !include ../examples/discount-group.example.json
/key={key}:
  (methodName): withKey
  type:
    baseResource:
      uriParameterName: key
      resourceType: DiscountGroup
      resourceUpdateType: DiscountGroupUpdate
  get:
    displayName: Get DiscountGroup by Key
    description: |
      Retrieves a DiscountGroup with the provided `key`.
    securedBy: [oauth_2_0: { scopes: ['view_cart_discounts:{projectKey}'] }]
    responses:
      200:
        body:
          application/json:
            example: !include ../examples/discount-group.example.json
  head:
    displayName: Check if DiscountGroup exists by Key
    description: |
      Checks if a DiscountGroup exists with the provided `key`.
      Returns a `200` status if a DiscountGroup exists, or a `404` status otherwise.
    securedBy: [oauth_2_0: { scopes: ['view_cart_discounts:{projectKey}'] }]
  post:
    displayName: Update DiscountGroup by Key
    description: |
      Updates a DiscountGroup in the Project using one or more [update actions](/../api/projects/discount-groups#update-actions).
    securedBy: [oauth_2_0: { scopes: ['manage_cart_discounts:{projectKey}'] }]
    body:
      application/json:
        example: !include ../examples/discount-group-update.example.json
    responses:
      200:
        body:
          application/json:
            example: !include ../examples/discount-group-updated.example.json
  delete:
    displayName: Delete DiscountGroup by Key
    description: |
      Deletes a DiscountGroup in the Project.
      This request generates the [DiscountGroupDeleted](ctp:api:type:DiscountGroupDeletedMessage) Message.

      If the DiscountGroup is referenced by a CartDiscount, a [ReferenceExists](ctp:api:type:ReferenceExistsError) error is returned.
    securedBy: [oauth_2_0: { scopes: ['manage_cart_discounts:{projectKey}'] }]
    responses:
      200:
        body:
          application/json:
            example: !include ../examples/discount-group.example.json
/{ID}:
  (methodName): withId
  type:
    baseResource:
      uriParameterName: ID
      resourceType: DiscountGroup
      resourceUpdateType: DiscountGroupUpdate
  get:
    displayName: Get DiscountGroup by ID
    description: |
      Retrieves a DiscountGroup with the provided `id`.
    securedBy: [oauth_2_0: { scopes: ['view_cart_discounts:{projectKey}'] }]
    responses:
      200:
        body:
          application/json:
            example: !include ../examples/discount-group.example.json
  head:
    displayName: Check if DiscountGroup exists by ID
    description: |
      Checks if a DiscountGroup exists with the provided `id`.
      Returns a `200` status if a DiscountGroup exists, or a `404` status otherwise.
    securedBy: [oauth_2_0: { scopes: ['view_cart_discounts:{projectKey}'] }]
  post:
    displayName: Update DiscountGroup by ID
    description: |
      Updates a DiscountGroup in the Project using one or more [update actions](/../api/projects/discount-groups#update-actions).
    securedBy: [oauth_2_0: { scopes: ['manage_cart_discounts:{projectKey}'] }]
    body:
      application/json:
        example: !include ../examples/discount-group-update.example.json
    responses:
      200:
        body:
          application/json:
            example: !include ../examples/discount-group-updated.example.json
  delete:
    displayName: Delete DiscountGroup by ID
    description: |
      Deletes a DiscountGroup in the Project.
      This request generates the [DiscountGroupDeleted](ctp:api:type:DiscountGroupDeletedMessage) Message.

      If the DiscountGroup is referenced by a CartDiscount, a [ReferenceExists](ctp:api:type:ReferenceExistsError) error is returned.
    securedBy: [oauth_2_0: { scopes: ['manage_cart_discounts:{projectKey}'] }]
    responses:
      200:
        body:
          application/json:
            example: !include ../examples/discount-group.example.json
