type: base
displayName: Authenticate Customer (Sign In)
description: Retrieves the authenticated customer.
post:
  displayName: Authenticate Customer (Sign In)
  description: |
    Authenticate Customer (Sign In). Retrieves the authenticated
    customer (a customer that matches the given email/password pair).
    If used with an access token for Anonymous Sessions,
    all orders and carts belonging to the anonymousId will be assigned to the newly created customer.
    If a cart is is returned as part of the CustomerSignInResult,
    it has been recalculated (It will have up-to-date prices, taxes and discounts,
    and invalid line items have been removed.).
  securedBy:
    [
      oauth_2_0:
        {
          scopes:
            ['manage_project:{projectKey}', 'manage_customers:{projectKey}'],
        },
    ]
  body:
    application/json:
      type: CustomerSignin
  responses:
    201:
      body:
        application/json:
          example: !include ../examples/customer-sign-in.example.json
          type: CustomerSignInResult
