type: base
description: Retrieves the authenticated customer.
post:
  displayName: Authenticate (sign in) Customer
  description: |
    Authenticates a global Customer.

    Allows [merging](/../api/customers-overview#cart-merge-during-sign-in-and-sign-up) items from an anonymous Cart into the most recently modified active Cart of a Customer.
    If no active Cart exists, the anonymous Cart becomes the Customer's active Cart.
    If the Customer has multiple active Carts, the anonymous Cart is merged into the most recently modified active Cart.

    If an account with the given credentials is not found, an [InvalidCredentials](ctp:api:type:InvalidCredentialsError) error is returned.
  securedBy: [oauth_2_0: { scopes: ['manage_customers:{projectKey}'] }]
  body:
    application/json:
      type: CustomerSignin
      example: !include ../examples/Customer/CustomerSignIn.json
  responses:
    200:
      body:
        application/json:
          example: !include ../examples/customer-sign-in-result.example.json
          type: CustomerSignInResult
