type:
  baseDomain:
    resourceType: Order
    resourceQueryType: OrderPagedQueryResponse
    resourceDraft: OrderFromCartDraft
    whereExample: 'customerEmail = "john.doe@example.com"'
    sortExample: createdAt asc
(updateable): Order
(deleteable): Order
(createable): OrderFromCartDraft
description:
  An order can be created from a order, usually after a checkout process has
  been completed.
get:
  (java-implements):
    'com.commercetools.api.models.PagedQueryResourceRequest<ByProjectKeyOrdersGet,
    com.commercetools.api.models.order.OrderPagedQueryResponse>'
  securedBy:
    [
      oauth_2_0:
        { scopes: ['manage_project:{projectKey}', 'view_orders:{projectKey}'] },
    ]
  responses:
    200:
      body:
        application/json:
          example: !include ../examples/orders.example.json
post:
  securedBy:
    [
      oauth_2_0:
        {
          scopes: ['manage_project:{projectKey}', 'manage_orders:{projectKey}'],
        },
    ]
  description: |
    Creates an order from a Cart.
    The cart must have a shipping address set before creating an order.
    When using the Platform TaxMode, the shipping address is used for tax calculation.
  body:
    application/json:
      example: !include ../examples/order-create.example.json
  responses:
    201:
      body:
        application/json:
          example: !include ../examples/order.example.json
/import:
  (methodName): importOrder
  type: base
  displayName: import orders
  post:
    displayName: Create an Order by Import
    description: Create an Order by Import
    securedBy:
      [
        oauth_2_0:
          {
            scopes:
              ['manage_project:{projectKey}', 'manage_orders:{projectKey}'],
          },
      ]
    body:
      application/json:
        example: !include ../examples/order-import.example.json
        type: OrderImportDraft
    responses:
      201:
        body:
          application/json:
            example: !include ../examples/order.example.json
            type: Order
/order-number={orderNumber}:
  (methodName): withOrderNumber
  type:
    baseResource:
      uriParameterName: orderNumber
      resourceType: Order
      resourceUpdateType: OrderUpdate
  get:
    securedBy:
      [
        oauth_2_0:
          {
            scopes: ['manage_project:{projectKey}', 'view_orders:{projectKey}'],
          },
      ]
    description: |
      In case the orderNumber does not match the regular expression [a-zA-Z0-9_\-]+,
      it should be provided in URL-encoded format.
    responses:
      200:
        body:
          application/json:
            example: !include ../examples/order.example.json
  post:
    securedBy:
      [
        oauth_2_0:
          {
            scopes:
              ['manage_project:{projectKey}', 'manage_orders:{projectKey}'],
          },
      ]
    body:
      application/json:
        example: !include ../examples/order-update.example.json
    responses:
      200:
        body:
          application/json:
            example: !include ../examples/order.example.json
  delete:
    is:
      - dataErasure
    securedBy:
      [
        oauth_2_0:
          {
            scopes:
              ['manage_project:{projectKey}', 'manage_orders:{projectKey}'],
          },
      ]
    responses:
      200:
        body:
          application/json:
            example: !include ../examples/order.example.json
/edits:
  type:
    baseDomain:
      resourceType: OrderEdit
      resourceQueryType: OrderEditPagedQueryResponse
      resourceDraft: OrderEditDraft
      whereExample: 'resource(id = "order-id")'
      sortExample: createdAt asc
  (updateable): OrderEdit
  (deleteable): OrderEdit
  (createable): OrderEditDraft
  description:
    OrderEdit are containers for financial changes after an Order has been
    placed.
  get:
    (java-implements):
      'com.commercetools.api.models.PagedQueryResourceRequest<ByProjectKeyOrdersEditsGet,
      com.commercetools.api.models.order_edit.OrderEditPagedQueryResponse>'
    securedBy:
      [
        oauth_2_0:
          {
            scopes:
              ['manage_project:{projectKey}', 'view_order_edits:{projectKey}'],
          },
      ]
    responses:
      200:
        body:
          application/json:
            example: !include ../examples/order-edits-query.example.json
  post:
    securedBy:
      [
        oauth_2_0:
          {
            scopes:
              [
                'manage_project:{projectKey}',
                'manage_order_edits:{projectKey}',
              ],
          },
      ]
    body:
      application/json:
        example: !include ../examples/order-edits-create.example.json
        type: OrderEditDraft
    responses:
      201:
        body:
          application/json:
            example: !include ../examples/order-edits.example.json
            type: OrderEdit
  /key={key}:
    (methodName): withKey
    type:
      baseResource:
        uriParameterName: key
        resourceType: OrderEdit
        resourceUpdateType: OrderEditUpdate
    get:
      securedBy:
        [
          oauth_2_0:
            {
              scopes:
                [
                  'manage_project:{projectKey}',
                  'view_order_edits:{projectKey}',
                ],
            },
        ]
      responses:
        200:
          body:
            application/json:
              example: !include ../examples/order-edits.example.json
    post:
      securedBy:
        [
          oauth_2_0:
            {
              scopes:
                [
                  'manage_project:{projectKey}',
                  'manage_order_edits:{projectKey}',
                ],
            },
        ]
      body:
        application/json:
          example: !include ../examples/order-edits-update.example.json
      responses:
        200:
          body:
            application/json:
              example: !include ../examples/order-edits.example.json
    delete:
      securedBy:
        [
          oauth_2_0:
            {
              scopes:
                [
                  'manage_project:{projectKey}',
                  'manage_order_edits:{projectKey}',
                ],
            },
        ]
      responses:
        200:
          body:
            application/json:
              example: !include ../examples/order-edits.example.json
  /{ID}:
    (methodName): withId
    type:
      baseResource:
        uriParameterName: ID
        resourceType: OrderEdit
        resourceUpdateType: OrderEditUpdate
    get:
      securedBy:
        [
          oauth_2_0:
            {
              scopes:
                [
                  'manage_project:{projectKey}',
                  'view_order_edits:{projectKey}',
                ],
            },
        ]
      responses:
        200:
          body:
            application/json:
              example: !include ../examples/order-edits.example.json
    post:
      securedBy:
        [
          oauth_2_0:
            {
              scopes:
                [
                  'manage_project:{projectKey}',
                  'manage_order_edits:{projectKey}',
                ],
            },
        ]
      body:
        application/json:
          example: !include ../examples/order-edits-update.example.json
      responses:
        200:
          body:
            application/json:
              example: !include ../examples/order-edits.example.json
    delete:
      securedBy:
        [
          oauth_2_0:
            {
              scopes:
                [
                  'manage_project:{projectKey}',
                  'manage_order_edits:{projectKey}',
                ],
            },
        ]
      responses:
        200:
          body:
            application/json:
              example: !include ../examples/order-edits.example.json
    /apply:
      type: base
      post:
        displayName: Apply order edit
        body:
          application/json:
            type: OrderEditApply
        securedBy:
          [
            oauth_2_0:
              {
                scopes:
                  [
                    'manage_project:{projectKey}',
                    'manage_order_edits:{projectKey}',
                  ],
              },
          ]
/{ID}:
  (methodName): withId
  type:
    baseResource:
      uriParameterName: ID
      resourceType: Order
      resourceUpdateType: OrderUpdate
  get:
    securedBy:
      [
        oauth_2_0:
          {
            scopes: ['manage_project:{projectKey}', 'view_orders:{projectKey}'],
          },
      ]
    responses:
      200:
        body:
          application/json:
            example: !include ../examples/order.example.json
  post:
    securedBy:
      [
        oauth_2_0:
          {
            scopes:
              ['manage_project:{projectKey}', 'manage_orders:{projectKey}'],
          },
      ]
    body:
      application/json:
        example: !include ../examples/order-update.example.json
    responses:
      200:
        body:
          application/json:
            example: !include ../examples/order.example.json
  delete:
    is:
      - dataErasure
    securedBy:
      [
        oauth_2_0:
          {
            scopes:
              ['manage_project:{projectKey}', 'manage_orders:{projectKey}'],
          },
      ]
    responses:
      200:
        body:
          application/json:
            example: !include ../examples/order.example.json
