type:
  baseDomain:
    resourceType: Payment
    resourceQueryType: PaymentPagedQueryResponse
    resourceDraft: PaymentDraft
    whereExample: 'externalId = "1234567890"'
    sortExample: createdAt asc
(updateable): Payment
(deleteable): Payment
(createable): PaymentDraft
description:
  Payments hold information about the current state of receiving and/or
  refunding money
get:
  securedBy: [oauth_2_0: { scopes: ['view_payments:{projectKey}'] }]
  responses:
    200:
      body:
        application/json:
          example: !include ../examples/payments.example.json
post:
  securedBy: [oauth_2_0: { scopes: ['manage_payments:{projectKey}'] }]
  body:
    application/json:
      example: !include ../examples/payment-create.example.json
  description: |
    Creating a Payment produces the [PaymentCreated](ctp:api:type:PaymentCreatedMessage) Message.
  responses:
    201:
      body:
        application/json:
          example: !include ../examples/payment.example.json
/key={key}:
  (methodName): withKey
  type:
    baseResource:
      uriParameterName: key
      resourceType: Payment
      resourceUpdateType: PaymentUpdate
  get:
    securedBy: [oauth_2_0: { scopes: ['view_payments:{projectKey}'] }]
    responses:
      200:
        body:
          application/json:
            example: !include ../examples/payment.example.json
  post:
    securedBy: [oauth_2_0: { scopes: ['manage_payments:{projectKey}'] }]
    body:
      application/json:
        example: !include ../examples/payment-update.example.json
    responses:
      200:
        body:
          application/json:
            example: !include ../examples/payment.example.json
  delete:
    is:
      - dataErasure
    securedBy: [oauth_2_0: { scopes: ['manage_payments:{projectKey}'] }]
    responses:
      200:
        body:
          application/json:
            example: !include ../examples/payment.example.json
/{ID}:
  (methodName): withId
  type:
    baseResource:
      uriParameterName: ID
      resourceType: Payment
      resourceUpdateType: PaymentUpdate
  get:
    securedBy: [oauth_2_0: { scopes: ['view_payments:{projectKey}'] }]
    responses:
      200:
        body:
          application/json:
            example: !include ../examples/payment.example.json
  post:
    securedBy: [oauth_2_0: { scopes: ['manage_payments:{projectKey}'] }]
    body:
      application/json:
        example: !include ../examples/payment-update.example.json
    responses:
      200:
        body:
          application/json:
            example: !include ../examples/payment.example.json
  delete:
    is:
      - dataErasure
    securedBy: [oauth_2_0: { scopes: ['manage_payments:{projectKey}'] }]
    responses:
      200:
        body:
          application/json:
            example: !include ../examples/payment.example.json
