type:
  baseDomain:
    resourceType: ProductType
    resourceQueryType: ProductTypePagedQueryResponse
    resourceDraft: ProductTypeDraft
    whereExample: 'title = "ABC123"'
    sortExample: createdAt asc
(updateable): ProductType
(deleteable): ProductType
(createable): ProductTypeDraft
description: |
  Product Types are used to describe common characteristics, most importantly common custom attributes,
  of many concrete products.
get:
  (java-implements):
    'com.commercetools.api.models.PagedQueryResourceRequest<ByProjectKeyProductTypesGet,
    com.commercetools.api.models.product_type.ProductTypePagedQueryResponse>'
  securedBy:
    [
      oauth_2_0:
        {
          scopes: ['manage_project:{projectKey}', 'view_products:{projectKey}'],
        },
    ]
  responses:
    200:
      body:
        application/json:
          example: !include ../examples/product-types.example.json
post:
  securedBy:
    [
      oauth_2_0:
        {
          scopes:
            ['manage_project:{projectKey}', 'manage_products:{projectKey}'],
        },
    ]
  body:
    application/json:
      example: !include ../examples/product-type-create.example.json
  responses:
    201:
      body:
        application/json:
          example: !include ../examples/product-type.example.json
/key={key}:
  (methodName): withKey
  type:
    baseResource:
      uriParameterName: key
      resourceType: ProductType
      resourceUpdateType: ProductTypeUpdate
  get:
    securedBy:
      [
        oauth_2_0:
          {
            scopes:
              ['manage_project:{projectKey}', 'view_products:{projectKey}'],
          },
      ]
    responses:
      200:
        body:
          application/json:
            example: !include ../examples/product-type.example.json
  post:
    securedBy:
      [
        oauth_2_0:
          {
            scopes:
              ['manage_project:{projectKey}', 'manage_products:{projectKey}'],
          },
      ]
    body:
      application/json:
        example: !include ../examples/product-type-update.example.json
    responses:
      200:
        body:
          application/json:
            example: !include ../examples/product-type.example.json
  delete:
    securedBy:
      [
        oauth_2_0:
          {
            scopes:
              ['manage_project:{projectKey}', 'manage_products:{projectKey}'],
          },
      ]
    responses:
      200:
        body:
          application/json:
            example: !include ../examples/product-type.example.json
/{ID}:
  (methodName): withId
  type:
    baseResource:
      uriParameterName: ID
      resourceType: ProductType
      resourceUpdateType: ProductTypeUpdate
  get:
    securedBy:
      [
        oauth_2_0:
          {
            scopes:
              ['manage_project:{projectKey}', 'view_products:{projectKey}'],
          },
      ]
    responses:
      200:
        body:
          application/json:
            example: !include ../examples/product-type.example.json
  post:
    securedBy:
      [
        oauth_2_0:
          {
            scopes:
              ['manage_project:{projectKey}', 'manage_products:{projectKey}'],
          },
      ]
    body:
      application/json:
        example: !include ../examples/product-type-update.example.json
    responses:
      200:
        body:
          application/json:
            example: !include ../examples/product-type.example.json
  delete:
    securedBy:
      [
        oauth_2_0:
          {
            scopes:
              ['manage_project:{projectKey}', 'manage_products:{projectKey}'],
          },
      ]
    responses:
      200:
        body:
          application/json:
            example: !include ../examples/product-type.example.json
