type:
  baseDomain:
    resourceType: ProductTailoring
    resourceQueryType: ProductTailoringPagedQueryResponse
    resourceDraft: ProductTailoringDraft
    whereExample: 'store(key = "store-one")'
    sortExample: createdAt asc
(updateable): ProductTailoring
(deleteable): ProductTailoring
(createable): ProductTailoringDraft
description: Product tailoring are used to contextualize product data for specific stores.
get:
  securedBy: [oauth_2_0: { scopes: ['view_products:{projectKey}'] }]
  responses:
    200:
      body:
        application/json:
          example: !include ../examples/product-tailoring-list.example.json
  queryParameters:
    withTotal:
      type: boolean
      default: false
      required: false
      description: |
        Controls the calculation of the [total](/../api/general-concepts#total) number of query results. Set to `true` to get the [total](/general-concepts#total) number of query results. This may impact query performance.
head:
  securedBy: [oauth_2_0: { scopes: ['view_products:{projectKey}'] }]
  description: Checks if one or more ProductTailorings exist for the provided query predicate. Returns a `200 OK` status if any ProductTailoring match the query predicate, or a `404 Not Found` otherwise.
  queryParameters:
    where?:
      type: QueryPredicate[]
post:
  description: |
    Generates the [ProductTailoringCreated](ctp:api:type:ProductTailoringCreatedMessage) Message.
  securedBy: [oauth_2_0: { scopes: ['manage_products:{projectKey}'] }]
  body:
    application/json:
      example: !include ../examples/product-tailoring-create.example.json
  responses:
    201:
      body:
        application/json:
          example: !include ../examples/product-tailoring.example.json

/key={key}:
  (methodName): withKey
  type:
    baseResource:
      uriParameterName: key
      resourceType: ProductTailoring
      resourceUpdateType: ProductTailoringUpdate
  get:
    securedBy: [oauth_2_0: { scopes: ['view_products:{projectKey}'] }]
    responses:
      200:
        body:
          application/json:
            example: !include ../examples/product-tailoring.example.json
  post:
    securedBy: [oauth_2_0: { scopes: ['manage_products:{projectKey}'] }]
    body:
      application/json:
        example: !include ../examples/product-tailoring-update.example.json
    responses:
      200:
        body:
          application/json:
            example: !include ../examples/product-tailoring-updated.example.json
  delete:
    description: |
      Generates the [ProductTailoringDeleted](ctp:api:type:ProductTailoringDeletedMessage) Message.
    securedBy: [oauth_2_0: { scopes: ['manage_products:{projectKey}'] }]
    responses:
      200:
        body:
          application/json:
            example: !include ../examples/product-tailoring.example.json
/{ID}:
  (methodName): withId
  type:
    baseResource:
      uriParameterName: ID
      resourceType: ProductTailoring
      resourceUpdateType: ProductTailoringUpdate
  get:
    securedBy: [oauth_2_0: { scopes: ['view_products:{projectKey}'] }]
    responses:
      200:
        body:
          application/json:
            example: !include ../examples/product-tailoring.example.json
  post:
    securedBy: [oauth_2_0: { scopes: ['manage_products:{projectKey}'] }]
    body:
      application/json:
        example: !include ../examples/product-tailoring-update.example.json
    responses:
      200:
        body:
          application/json:
            example: !include ../examples/product-tailoring-updated.example.json
  delete:
    description: |
      Generates the [ProductTailoringDeleted](ctp:api:type:ProductTailoringDeletedMessage) Message.
    securedBy: [oauth_2_0: { scopes: ['manage_products:{projectKey}'] }]
    responses:
      200:
        body:
          application/json:
            example: !include ../examples/product-tailoring.example.json
