type: base
displayName: Product Projection Search
description: |
  This endpoint provides high performance search queries over ProductProjections. The query result contains the
  ProductProjections for which at least one ProductVariant matches the search query. This means that variants can
  be included in the result also for which the search query does not match. To determine which ProductVariants match
  the search query, the returned ProductProjections include the additional field isMatchingVariant.
post:
  displayName: Search Products by post
  securedBy:
    [
      oauth_2_0:
        {
          scopes:
            [
              'manage_project:{projectKey}',
              'view_products:{projectKey}',
              'view_published_products:{projectKey}',
            ],
        },
    ]
  description: Search Product Projection
  body:
    application/x-www-form-urlencoded:
      type: string
get:
  displayName: Search Products by get
  description: Search Product Projection
  queryParameters:
    fuzzy?:
      type: boolean
      description: Whether to apply fuzzy search on the text to analyze.
    fuzzyLevel?:
      type: number
      description: |
        Provide explicitly the fuzzy level desired if fuzzy is enabled. This value can not be higher than the one
        chosen by the platform by default.
    markMatchingVariants:
      type: boolean
      description: |
        if `markMatchingVariants` parameter is `true` those ProductVariants that match the search query have the additional
        field `isMatchingVariant` set to `true`. For the other variants in the same product projection this field is set to `false`.
    staged?:
      type: boolean
      description: Whether to query for the current or staged projections.
    filter?:
      type: string[]
    filter.facets?:
      type: string[]
    filter.query?:
      type: string[]
    facet?:
      type: string[]
    #TODO clarify correct syntax
    /text\.[a-z]{2}(-[A-Z]{2})?/:
      (placeholderParam):
        paramName: text
        template: text.<locale>
        placeholder: locale
      type: string[]
      required: false
  is:
    - sortable:
        sortExample: createdAt asc
    - paging
    - priceSelecting
    - expandable
  securedBy:
    [
      oauth_2_0:
        {
          scopes:
            [
              'manage_project:{projectKey}',
              'view_products:{projectKey}',
              'view_published_products:{projectKey}',
            ],
        },
    ]
  responses:
    200:
      body:
        application/json:
          example: !include ../examples/product-projections-search.example.json
          type: ProductProjectionPagedSearchResponse
