type: base
displayName: Product Projection Suggestion
description: The source of data for suggestions is the searchKeyword field in a product
get:
  displayName: Get suggestion keywords
  queryParameters:
    fuzzy?:
      type: boolean
      description: Whether to apply fuzzy search on the text to analyze.
    staged?:
      type: boolean
      description: Whether to query for the current or staged projections.
    #TODO clarify correct syntax
    /searchKeywords\.[a-z]{2}(-[A-Z]{2})?/:
      (placeholderParam):
        paramName: searchKeywords
        template: searchKeywords.<locale>
        placeholder: locale
      type: string[]
      required: false
  is:
    - sortable:
        sortExample: createdAt asc
    - paging
  securedBy:
    [
      oauth_2_0:
        {
          scopes:
            [
              'manage_project:{projectKey}',
              'view_products:{projectKey}',
              'view_published_products:{projectKey}',
            ],
        },
    ]
  responses:
    200:
      body:
        application/json:
          example: !include ../examples/product-projections.example.json
          # schema: !include schemas/product-projections.schema.json
