type:
  baseDomain:
    resourceType: ProductProjection
    resourceQueryType: ProductProjectionPagedQueryResponse
    resourceDraft: ProductProjectionDraft
    whereExample: 'slug(en = "long-sleeves")'
    sortExample: createdAt asc
description: |
  A projected representation of a product shows the product with its current or staged data. The current or staged
  representation of a product in a catalog is called a product projection.
get:
  securedBy:
    [
      oauth_2_0:
        {
          scopes:
            [
              'view_products:{projectKey}',
              'view_published_products:{projectKey}',
            ],
        },
    ]
  description: |
    Use the Product Projections query endpoint to get the current or staged representations of Products.
    When used with an API Client that has the `view_published_products:{projectKey}` scope,
    this endpoint only returns published (current) Product Projections.
  is:
    - projectionSelecting
    - priceSelecting
    - localeProjecting
    - storeProjecting
  responses:
    200:
      body:
        application/json:
          example: !include ../examples/product-projections.example.json
/search: !include product-projections-search.raml
/suggest: !include product-projections-suggest.raml
/key={key}:
  (methodName): withKey
  type:
    baseResource:
      uriParameterName: key
      resourceType: ProductProjection
  get:
    securedBy:
      [
        oauth_2_0:
          {
            scopes:
              [
                'view_products:{projectKey}',
                'view_published_products:{projectKey}',
              ],
          },
      ]
    description: |
      Gets the current or staged representation of a [Product](ctp:api:type:Product) found by Key.
      When used with an API Client that has the `view_published_products:{projectKey}` scope,
      this endpoint only returns published (current) Product Projections.
    is:
      - projectionSelecting
      - priceSelecting
      - localeProjecting
      - storeProjecting
    responses:
      200:
        body:
          application/json:
            example: !include ../examples/product-projection.example.json
/{ID}:
  (methodName): withId
  type:
    baseResource:
      uriParameterName: ID
      resourceType: ProductProjection
  get:
    securedBy:
      [
        oauth_2_0:
          {
            scopes:
              [
                'view_products:{projectKey}',
                'view_published_products:{projectKey}',
              ],
          },
      ]
    description: |
      Gets the current or staged representation of a [Product](ctp:api:type:Product) by its ID. When used with an API Client that has the `view_published_products:{projectKey}` scope, this endpoint only returns published (current) Product Projections.
    is:
      - projectionSelecting
      - priceSelecting
      - localeProjecting
      - storeProjecting
    responses:
      200:
        body:
          application/json:
            example: !include ../examples/product-projection.example.json
