type:
  baseDomain:
    resourceType: ProductDiscount
    resourceQueryType: ProductDiscountPagedQueryResponse
    resourceDraft: ProductDiscountDraft
    whereExample: 'name(en = "Summer Sale")'
    sortExample: createdAt asc
(updateable): ProductDiscount
(deleteable): ProductDiscount
(createable): ProductDiscountDraft
description: Product discounts are used to change certain product prices.
get:
  securedBy: [oauth_2_0: { scopes: ['view_products:{projectKey}'] }]
  responses:
    200:
      body:
        application/json:
          example: !include ../examples/product-discounts.example.json
head:
  securedBy: [oauth_2_0: { scopes: ['view_products:{projectKey}'] }]
  description: Checks if a ProductDiscount exists for a given Query Predicate. Returns a `200 OK` status if any ProductDiscounts match the Query Predicate, or a `404 Not Found` otherwise.
  queryParameters:
    where?:
      type: QueryPredicate[]
post:
  securedBy: [oauth_2_0: { scopes: ['manage_products:{projectKey}'] }]
  body:
    application/json:
      example: !include ../examples/product-discount-create.example.json
  responses:
    201:
      body:
        application/json:
          example: !include ../examples/product-discount.example.json
/matching:
  type: base
  post:
    displayName: Get matching product discounts
    description: |
      This endpoint can be used to simulate which Product Discounts would be applied if a specified Product Variant had a specified Price.
      Given Product and Product Variant IDs and a Price, this endpoint will return the [ProductDiscount](ctp:api:type:ProductDiscount) that would have been applied to that Price.

      If a Product Discount could not be found that could be applied to the Price of a Product Variant, a [NoMatchingProductDiscountFound](ctp:api:type:NoMatchingProductDiscountFoundError) error is returned.
    securedBy: [oauth_2_0: { scopes: ['view_products:{projectKey}'] }]
    body:
      application/json:
        type: ProductDiscountMatchQuery
        example: !include ../examples/ProductDiscount/ProductDiscountMatchQuery.json
    responses:
      200:
        body:
          application/json:
            type: ProductDiscount
            example: !include ../examples/product-discount.example.json
      404:
        body:
          application/json:
            type: NoMatchingProductDiscountFoundError
            example: !include ../examples/no-matching-product-discounts-found-error.example.json
/key={key}:
  (methodName): withKey
  type:
    baseResource:
      uriParameterName: key
      resourceType: ProductDiscount
      resourceUpdateType: ProductDiscountUpdate
  get:
    securedBy: [oauth_2_0: { scopes: ['view_products:{projectKey}'] }]
    responses:
      200:
        body:
          application/json:
            example: !include ../examples/product-discount.example.json
  head:
    securedBy: [oauth_2_0: { scopes: ['view_products:{projectKey}'] }]
    description: Checks if a ProductDiscount exists for a given `key`. Returns a `200 OK` status if the ProductDiscount exists or a `404 Not Found` otherwise.
  post:
    securedBy: [oauth_2_0: { scopes: ['manage_products:{projectKey}'] }]
    body:
      application/json:
        example: !include ../examples/product-discount-update.example.json
    responses:
      200:
        body:
          application/json:
            example: !include ../examples/product-discount-updated.example.json
  delete:
    securedBy: [oauth_2_0: { scopes: ['manage_products:{projectKey}'] }]
    responses:
      200:
        body:
          application/json:
            example: !include ../examples/product-discount.example.json
/{ID}:
  (methodName): withId
  type:
    baseResource:
      uriParameterName: ID
      resourceType: ProductDiscount
      resourceUpdateType: ProductDiscountUpdate
  get:
    securedBy: [oauth_2_0: { scopes: ['view_products:{projectKey}'] }]
    responses:
      200:
        body:
          application/json:
            example: !include ../examples/product-discount.example.json
  head:
    securedBy: [oauth_2_0: { scopes: ['view_products:{projectKey}'] }]
    description: Checks if a ProductDiscount exists for a given `id`. Returns a `200 OK` status if the ProductDiscount exists or a `404 Not Found` otherwise.
  post:
    securedBy: [oauth_2_0: { scopes: ['manage_products:{projectKey}'] }]
    body:
      application/json:
        example: !include ../examples/product-discount-update.example.json
    responses:
      200:
        body:
          application/json:
            example: !include ../examples/product-discount-updated.example.json
  delete:
    securedBy: [oauth_2_0: { scopes: ['manage_products:{projectKey}'] }]
    responses:
      200:
        body:
          application/json:
            example: !include ../examples/product-discount.example.json
