type:
  baseDomain:
    resourceType: Review
    resourceQueryType: ReviewPagedQueryResponse
    resourceDraft: ReviewDraft
    whereExample: 'title = "ABC123"'
    sortExample: createdAt asc
(updateable): Review
(deleteable): Review
(createable): ReviewDraft
description: Reviews are used to evaluate products and channels.
get:
  displayName: Query Reviews
  securedBy: [oauth_2_0: { scopes: ['view_products:{projectKey}'] }]
  responses:
    200:
      body:
        application/json:
          example: !include ../examples/reviews.example.json
head:
  displayName: Check if Review exists by Query Predicate
  securedBy: [oauth_2_0: { scopes: ['view_products:{projectKey}'] }]
  description: Checks if one or more Reviews exist for the provided query predicate. Returns a `200` status if any Reviews match the query predicate, or a `404` status otherwise.
  queryParameters:
    where?:
      type: QueryPredicate[]
      description: |-
        Query Predicates on Reviews are limited to [Text](ctp:api:type:AttributeTextType),
        [Enum](ctp:api:type:AttributeEnumType), [Boolean](ctp:api:type:AttributeBooleanType),
        [Number](ctp:api:type:AttributeNumberType), [Date](ctp:api:type:AttributeDateType),
        [Time](ctp:api:type:AttributeTimeType), and [DateTime](ctp:api:type:AttributeDateTimeType) attribute types.
post:
  displayName: Create Review
  securedBy: [oauth_2_0: { scopes: ['manage_products:{projectKey}'] }]
  body:
    application/json:
      example: !include ../examples/review-create.example.json
  responses:
    201:
      body:
        application/json:
          example: !include ../examples/review.example.json
/key={key}:
  (methodName): withKey
  type:
    baseResource:
      uriParameterName: key
      resourceType: Review
      resourceUpdateType: ReviewUpdate
  get:
    displayName: Get Review by Key
    securedBy: [oauth_2_0: { scopes: ['view_products:{projectKey}'] }]
    responses:
      200:
        body:
          application/json:
            example: !include ../examples/review.example.json
  head:
    displayName: Check if Review exists by Key
    securedBy: [oauth_2_0: { scopes: ['view_products:{projectKey}'] }]
    description: Checks if a Review exists with the provided `key`. Returns a `200` status if the Review exists, or a `404` status otherwise.
  post:
    displayName: Update Review by Key
    securedBy: [oauth_2_0: { scopes: ['manage_products:{projectKey}'] }]
    body:
      application/json:
        example: !include ../examples/review-update.example.json
    responses:
      200:
        body:
          application/json:
            example: !include ../examples/review.example.json
  delete:
    displayName: Delete Review by Key
    is:
      - dataErasure
    securedBy: [oauth_2_0: { scopes: ['manage_products:{projectKey}'] }]
    responses:
      200:
        body:
          application/json:
            example: !include ../examples/review.example.json
/{ID}:
  (methodName): withId
  type:
    baseResource:
      uriParameterName: ID
      resourceType: Review
      resourceUpdateType: ReviewUpdate
  get:
    displayName: Get Review by ID
    securedBy: [oauth_2_0: { scopes: ['view_products:{projectKey}'] }]
    responses:
      200:
        body:
          application/json:
            example: !include ../examples/review.example.json
  head:
    displayName: Check if Review exists by ID
    securedBy: [oauth_2_0: { scopes: ['view_products:{projectKey}'] }]
    description: Checks if a Review exists with the provided `id`. Returns a `200` status if the Review exists, or a `404` status otherwise.
  post:
    displayName: Update Review by ID
    securedBy: [oauth_2_0: { scopes: ['manage_products:{projectKey}'] }]
    body:
      application/json:
        example: !include ../examples/review-update.example.json
    responses:
      200:
        body:
          application/json:
            example: !include ../examples/review.example.json
  delete:
    displayName: Delete Review by ID
    is:
      - dataErasure
    securedBy: [oauth_2_0: { scopes: ['manage_products:{projectKey}'] }]
    responses:
      200:
        body:
          application/json:
            example: !include ../examples/review.example.json
