type:
  baseDomain:
    resourceType: ShoppingList
    resourceQueryType: ShoppingListPagedQueryResponse
    resourceDraft: ShoppingListDraft
    whereExample: 'key = "my-shopping-list"'
    sortExample: createdAt asc
(updateable): ShoppingList
(deleteable): ShoppingList
(createable): ShoppingListDraft
description: shopping-lists e.g. for wishlist support
get:
  (java-implements):
    'com.commercetools.api.models.PagedQueryResourceRequest<ByProjectKeyShoppingListsGet,
    com.commercetools.api.models.shopping_list.ShoppingListPagedQueryResponse>'
  securedBy:
    [
      oauth_2_0:
        {
          scopes:
            ['manage_project:{projectKey}', 'view_shopping_lists:{projectKey}'],
        },
    ]
  responses:
    200:
      body:
        application/json:
          example: !include ../examples/shopping-lists.example.json
post:
  securedBy:
    [
      oauth_2_0:
        {
          scopes:
            [
              'manage_project:{projectKey}',
              'manage_shopping_lists:{projectKey}',
            ],
        },
    ]
  body:
    application/json:
      example: !include ../examples/shopping-list-create.example.json
  responses:
    201:
      body:
        application/json:
          example: !include ../examples/shopping-list.example.json
/key={key}:
  (methodName): withKey
  type:
    baseResource:
      uriParameterName: key
      resourceType: ShoppingList
      resourceUpdateType: ShoppingListUpdate
  get:
    securedBy:
      [
        oauth_2_0:
          {
            scopes:
              [
                'manage_project:{projectKey}',
                'view_shopping_lists:{projectKey}',
              ],
          },
      ]
    description: Gets a shopping list by Key.
    responses:
      200:
        body:
          application/json:
            example: !include ../examples/shopping-list.example.json
  post:
    securedBy:
      [
        oauth_2_0:
          {
            scopes:
              [
                'manage_project:{projectKey}',
                'manage_shopping_lists:{projectKey}',
              ],
          },
      ]
    description: Update a shopping list found by its Key.
    body:
      application/json:
        example: !include ../examples/shopping-list-update.example.json
    responses:
      200:
        body:
          application/json:
            example: !include ../examples/shopping-list.example.json
  delete:
    is:
      - dataErasure
    securedBy:
      [
        oauth_2_0:
          {
            scopes:
              [
                'manage_project:{projectKey}',
                'manage_shopping_lists:{projectKey}',
              ],
          },
      ]
    responses:
      200:
        body:
          application/json:
            example: !include ../examples/shopping-list.example.json
/{ID}:
  (methodName): withId
  type:
    baseResource:
      uriParameterName: ID
      resourceType: ShoppingList
      resourceUpdateType: ShoppingListUpdate
  get:
    securedBy:
      [
        oauth_2_0:
          {
            scopes:
              [
                'manage_project:{projectKey}',
                'view_shopping_lists:{projectKey}',
              ],
          },
      ]
    description: Gets a shopping list by ID.
    responses:
      200:
        body:
          application/json:
            example: !include ../examples/shopping-list.example.json
  post:
    securedBy:
      [
        oauth_2_0:
          {
            scopes:
              [
                'manage_project:{projectKey}',
                'manage_shopping_lists:{projectKey}',
              ],
          },
      ]
    body:
      application/json:
        example: !include ../examples/shopping-list-update.example.json
    responses:
      200:
        body:
          application/json:
            example: !include ../examples/shopping-list.example.json
  delete:
    is:
      - dataErasure
    securedBy:
      [
        oauth_2_0:
          {
            scopes:
              [
                'manage_project:{projectKey}',
                'manage_shopping_lists:{projectKey}',
              ],
          },
      ]
    responses:
      200:
        body:
          application/json:
            example: !include ../examples/shopping-list.example.json
