type:
  baseDomain:
    resourceType: ShoppingList
    resourceQueryType: ShoppingListPagedQueryResponse
    resourceDraft: ShoppingListDraft
    whereExample: 'key = "my-shopping-list"'
    sortExample: createdAt asc
(updateable): ShoppingList
(deleteable): ShoppingList
(createable): ShoppingListDraft
description: shopping-lists e.g. for wishlist support
get:
  displayName: Query ShoppingLists
  securedBy: [oauth_2_0: { scopes: ['view_shopping_lists:{projectKey}'] }]
  queryParameters:
    expand:
      description: |
        When expanding `variant` and `productSlug` on [ShoppingListLineItem](ctp:api:type:ShoppingListLineItem), [expand the entire array](/general-concepts#reference-expansion). You cannot expand a single element (for example, `expand=lineItems[0].variant` is not supported).
      type: Expansion[]
      required: false
  description: Retrieves ShoppingLists in the Project.
  responses:
    200:
      body:
        application/json:
          example: !include ../examples/shopping-lists.example.json
head:
  displayName: Check if ShoppingList exists by Query Predicate
  securedBy: [oauth_2_0: { scopes: ['view_shopping_lists:{projectKey}'] }]
  description: Checks if one or more ShoppingLists exist for the provided query predicate. Returns a `200 OK` status if any ShoppingLists match the query predicate, or a `404 Not Found` otherwise.
  queryParameters:
    where?:
      type: QueryPredicate[]
post:
  displayName: Create ShoppingList
  securedBy: [oauth_2_0: { scopes: ['manage_shopping_lists:{projectKey}'] }]
  description: Create a ShoppingList in the Project.
  queryParameters:
    expand:
      description: |
        When expanding `variant` and `productSlug` on [ShoppingListLineItem](ctp:api:type:ShoppingListLineItem), [expand the entire array](/general-concepts#reference-expansion). You cannot expand a single element (for example, `expand=lineItems[0].variant` is not supported).
      type: Expansion[]
      required: false
  body:
    application/json:
      example: !include ../examples/shopping-list-create.example.json
  responses:
    201:
      body:
        application/json:
          example: !include ../examples/shopping-list.example.json
/key={key}:
  (methodName): withKey
  type:
    baseResource:
      uriParameterName: key
      resourceType: ShoppingList
      resourceUpdateType: ShoppingListUpdate
  get:
    displayName: Get ShoppingList by Key
    securedBy: [oauth_2_0: { scopes: ['view_shopping_lists:{projectKey}'] }]
    queryParameters:
      expand:
        description: |
          When expanding `variant` and `productSlug` on [ShoppingListLineItem](ctp:api:type:ShoppingListLineItem), [expand the entire array](/general-concepts#reference-expansion). You cannot expand a single element (for example, `expand=lineItems[0].variant` is not supported).
        type: Expansion[]
        required: false
    description: Retrieves a ShoppingList with the provided `key`.
    responses:
      200:
        body:
          application/json:
            example: !include ../examples/shopping-list.example.json
  head:
    displayName: Check if ShoppingList exists by Key
    securedBy: [oauth_2_0: { scopes: ['view_shopping_lists:{projectKey}'] }]
    description: Checks if a ShoppingList exists with the provided `key`. Returns a `200 OK` status if the ShoppingList exists, or [Not Found](/../api/errors#404-not-found) otherwise.
  post:
    displayName: Update ShoppingList by Key
    securedBy: [oauth_2_0: { scopes: ['manage_shopping_lists:{projectKey}'] }]
    queryParameters:
      expand:
        description: |
          When expanding `variant` and `productSlug` on [ShoppingListLineItem](ctp:api:type:ShoppingListLineItem), [expand the entire array](/general-concepts#reference-expansion). You cannot expand a single element (for example, `expand=lineItems[0].variant` is not supported).
        type: Expansion[]
        required: false
    description: Updates a ShoppingList in the Project using one or more [update actions](/../api/projects/shoppingLists#update-actions).
    body:
      application/json:
        example: !include ../examples/shopping-list-update.example.json
    responses:
      200:
        body:
          application/json:
            example: !include ../examples/shopping-list.example.json
  delete:
    displayName: Delete ShoppingList by Key
    is:
      - dataErasure
    securedBy: [oauth_2_0: { scopes: ['manage_shopping_lists:{projectKey}'] }]
    queryParameters:
      expand:
        description: |
          When expanding `variant` and `productSlug` on [ShoppingListLineItem](ctp:api:type:ShoppingListLineItem), [expand the entire array](/general-concepts#reference-expansion). You cannot expand a single element (for example, `expand=lineItems[0].variant` is not supported).
        type: Expansion[]
        required: false
    description: Deletes a ShoppingList in the Project.
    responses:
      200:
        body:
          application/json:
            example: !include ../examples/shopping-list.example.json
/{ID}:
  (methodName): withId
  type:
    baseResource:
      uriParameterName: ID
      resourceType: ShoppingList
      resourceUpdateType: ShoppingListUpdate
  get:
    displayName: Get ShoppingList by ID
    securedBy: [oauth_2_0: { scopes: ['view_shopping_lists:{projectKey}'] }]
    queryParameters:
      expand:
        description: |
          When expanding `variant` and `productSlug` on [ShoppingListLineItem](ctp:api:type:ShoppingListLineItem), [expand the entire array](/general-concepts#reference-expansion). You cannot expand a single element (for example, `expand=lineItems[0].variant` is not supported).
        type: Expansion[]
        required: false
    description: Retrieves a ShoppingList with the provided `id`.
    responses:
      200:
        body:
          application/json:
            example: !include ../examples/shopping-list.example.json
  head:
    displayName: Check if ShoppingList exists by ID
    securedBy: [oauth_2_0: { scopes: ['view_shopping_lists:{projectKey}'] }]
    description: Checks if a ShoppingList exists with the provided `id`. Returns a `200 OK` status if the ShoppingList exists, or [Not Found](/../api/errors#404-not-found) otherwise.
  post:
    displayName: Update ShoppingList by ID
    securedBy: [oauth_2_0: { scopes: ['manage_shopping_lists:{projectKey}'] }]
    queryParameters:
      expand:
        description: |
          When expanding `variant` and `productSlug` on [ShoppingListLineItem](ctp:api:type:ShoppingListLineItem), [expand the entire array](/general-concepts#reference-expansion). You cannot expand a single element (for example, `expand=lineItems[0].variant` is not supported).
        type: Expansion[]
        required: false
    description: Updates a ShoppingList in the Project using one or more [update actions](/../api/projects/shoppingLists#update-actions).
    body:
      application/json:
        example: !include ../examples/shopping-list-update.example.json
    responses:
      200:
        body:
          application/json:
            example: !include ../examples/shopping-list.example.json
  delete:
    displayName: Delete ShoppingList by ID
    is:
      - dataErasure
    securedBy: [oauth_2_0: { scopes: ['manage_shopping_lists:{projectKey}'] }]
    queryParameters:
      expand:
        description: |
          When expanding `variant` and `productSlug` on [ShoppingListLineItem](ctp:api:type:ShoppingListLineItem), [expand the entire array](/general-concepts#reference-expansion). You cannot expand a single element (for example, `expand=lineItems[0].variant` is not supported).
        type: Expansion[]
        required: false
    description: Deletes a ShoppingList in the Project.
    responses:
      200:
        body:
          application/json:
            example: !include ../examples/shopping-list.example.json
