type:
  baseDomain:
    resourceType: StandalonePrice
    resourceQueryType: StandalonePricePagedQueryResponse
    resourceDraft: StandalonePriceDraft
    whereExample: 'sku = "PT974SKT"'
    sortExample: country asc
(updateable): StandalonePrice
(deleteable): StandalonePrice
(createable): StandalonePriceDraft
description:
  A standalone price assigns a price to a product variant for a given scope.
  The API will use the standalone prices associated with a Product if its field [`priceMode`](/projects/products#pricemode) is set to `Standalone` [ProductPriceMode](ctp:api:type:ProductPriceModeEnum).
get:
  displayName: Query StandalonePrices
  securedBy: [oauth_2_0: { scopes: ['view_standalone_prices:{projectKey}'] }]
  responses:
    200:
      body:
        application/json:
          example: !include ../examples/standalone-prices.example.json
head:
  displayName: Check if StandalonePrice exists by Query Predicate
  securedBy: [oauth_2_0: { scopes: ['view_standalone_prices:{projectKey}'] }]
  description: Checks if one or more StandalonePrices exist for the provided query predicate. Returns a `200` status if any StandalonePrices match the query predicate, or a `404` status otherwise.
  queryParameters:
    where?:
      type: QueryPredicate[]
post:
  displayName: Create StandalonePrice
  description: |
    Creating a Standalone Price produces the [StandalonePriceCreated](ctp:api:type:StandalonePriceCreatedMessage) Message.

    - If the Standalone Price has the same price scope as an existing Standalone Price, a [DuplicateStandalonePriceScope](ctp:api:type:DuplicateStandalonePriceScopeError) error is returned.
    - If the Standalone Price has overlapping validity periods within the same price scope, a [OverlappingStandalonePriceValidity](ctp:api:type:OverlappingStandalonePriceValidityError) error is returned. A Price without validity period does not conflict with a Price defined for a time period.
    - If a modification is already in progress for the exact combination of SKU and price scope fields, an [ExactLockConflict](ctp:api:type:ExactLockConflictError) or [ValidityLockConflict](ctp:api:type:ValidityLockConflictError) error is returned.
  securedBy: [oauth_2_0: { scopes: ['manage_standalone_prices:{projectKey}'] }]
  body:
    application/json:
      example: !include ../examples/standalone-price-create.example.json
  responses:
    201:
      body:
        application/json:
          example: !include ../examples/standalone-price.example.json
/key={key}:
  (methodName): withKey
  type:
    baseResource:
      uriParameterName: key
      resourceType: StandalonePrice
      resourceUpdateType: StandalonePriceUpdate
  get:
    displayName: Get StandalonePrice by Key
    securedBy: [oauth_2_0: { scopes: ['view_standalone_prices:{projectKey}'] }]
    responses:
      200:
        body:
          application/json:
            example: !include ../examples/standalone-price.example.json
  head:
    displayName: Check if StandalonePrice exists by Key
    securedBy: [oauth_2_0: { scopes: ['view_standalone_prices:{projectKey}'] }]
    description: Checks if a StandalonePrice exists with the provided `key`. Returns a `200` status if the StandalonePrice exists, or a `404` status otherwise.
  post:
    displayName: Update StandalonePrice by Key
    description: |
      If a modification is already in progress for the exact combination of SKU and price scope fields, an [ExactLockConflict](ctp:api:type:ExactLockConflictError) or [ValidityLockConflict](ctp:api:type:ValidityLockConflictError) error is returned.
    securedBy:
      [oauth_2_0: { scopes: ['manage_standalone_prices:{projectKey}'] }]
    body:
      application/json:
        example: !include ../examples/standalone-price-update.example.json
    responses:
      200:
        body:
          application/json:
            example: !include ../examples/standalone-price-updated.example.json
  delete:
    displayName: Delete StandalonePrice by Key
    description: |
      Produces the [StandalonePriceDeleted](ctp:api:type:StandalonePriceDeletedMessage) Message.
    securedBy:
      [oauth_2_0: { scopes: ['manage_standalone_prices:{projectKey}'] }]
    responses:
      200:
        body:
          application/json:
            example: !include ../examples/standalone-price.example.json
/{ID}:
  (methodName): withId
  type:
    baseResource:
      uriParameterName: ID
      resourceType: StandalonePrice
      resourceUpdateType: StandalonePriceUpdate
  get:
    displayName: Get StandalonePrice by ID
    securedBy: [oauth_2_0: { scopes: ['view_standalone_prices:{projectKey}'] }]
    responses:
      200:
        body:
          application/json:
            example: !include ../examples/standalone-price.example.json
  head:
    displayName: Check if StandalonePrice exists by ID
    securedBy: [oauth_2_0: { scopes: ['view_standalone_prices:{projectKey}'] }]
    description: Checks if a StandalonePrice exists with the provided `id`. Returns a `200` status if the StandalonePrice exists, or a `404` status otherwise.
  post:
    displayName: Update StandalonePrice by ID
    description: |
      If a modification is already in progress for the exact combination of SKU and price scope fields, an [ExactLockConflict](ctp:api:type:ExactLockConflictError) or [ValidityLockConflict](ctp:api:type:ValidityLockConflictError) error is returned.
    securedBy:
      [oauth_2_0: { scopes: ['manage_standalone_prices:{projectKey}'] }]
    body:
      application/json:
        example: !include ../examples/standalone-price-update.example.json
    responses:
      200:
        body:
          application/json:
            example: !include ../examples/standalone-price-updated.example.json
  delete:
    displayName: Delete StandalonePrice by ID
    description: |
      Produces the [StandalonePriceDeleted](ctp:api:type:StandalonePriceDeletedMessage) Message.
    securedBy:
      [oauth_2_0: { scopes: ['manage_standalone_prices:{projectKey}'] }]
    responses:
      200:
        body:
          application/json:
            example: !include ../examples/standalone-price.example.json
