#%RAML 1.0 DataType
(package): Quote
type: BaseResource
displayName: Quote
(updateType): QuoteUpdate
properties:
  id:
    (identifier): true
    type: string
    description: |
      Unique identifier of the Quote.
  version:
    type: number
    format: int64
    description: |
      Current version of the Quote.
  key?:
    type: string
    description: |
      User-defined unique identifier of the Quote.
    pattern: ^[A-Za-z0-9_-]+$
    minLength: 2
    maxLength: 256
  createdAt:
    type: datetime
    description: |
      Date and time (UTC) the Quote was initially created.
  lastModifiedAt:
    type: datetime
    description: |
      Date and time (UTC) the Quote was last updated.
  lastModifiedBy?:
    type: LastModifiedBy
    (beta): true
    description: |
      Present on resources created after 1 February 2019 except for [events not tracked](/../api/general-concepts#events-tracked).
  createdBy?:
    type: CreatedBy
    (beta): true
    description: |
      Present on resources created after 1 February 2019 except for [events not tracked](/../api/general-concepts#events-tracked).
  quoteRequest:
    type: QuoteRequestReference
    description: |
      Quote Request related to the Quote.
  stagedQuote:
    type: StagedQuoteReference
    description: |
      Staged Quote related to the Quote.
  customer?:
    type: CustomerReference
    description: |
      The [Buyer](/../api/quotes-overview#buyer) who owns the Quote.
  customerGroup?:
    type: CustomerGroupReference
    description: |
      Set automatically when `customer` is set and the Customer is a member of a Customer Group.
      Not updated if Customer is changed after Quote creation.
      Used for Product Variant price selection.
  validTo?:
    type: datetime
    description: |
      Expiration date for the Quote.
  sellerComment?:
    type: string
    description: |
      Message from the [Seller](/../api/quotes-overview#seller) included in the offer.
  buyerComment?:
    type: string
    description: |
      Message from the [Buyer](/../api/quotes-overview#buyer) included in the [renegotiation request](ctp:api:type:QuoteRequestQuoteRenegotiationAction).
  store?:
    type: StoreKeyReference
    description: |
      The Store to which the [Buyer](/../api/quotes-overview#buyer) belongs.
  lineItems:
    type: LineItem[]
    description: |
      The Line Items for which the Quote is requested.
  customLineItems:
    type: CustomLineItem[]
    description: |
      The Custom Line Items for which the Quote is requested.
  totalPrice:
    description: |
      Sum of all `totalPrice` fields of the `lineItems` and `customLineItems`, as well as the `price` field of `shippingInfo` (if it exists).
      `totalPrice` may or may not include the taxes: it depends on the taxRate.includedInPrice property of each price.
    type: TypedMoney
  taxedPrice?:
    type: TaxedPrice
    description: |-
      Not set until the shipping address is set.
      Will be set automatically in the `Platform` TaxMode.
      For the `External` tax mode it will be set  as soon as the external tax rates for all line items, custom line items, and shipping in the cart are set.
  shippingAddress?:
    type: Address
    description: |
      Used to determine the eligible [ShippingMethods](ctp:api:type:ShippingMethod)
      and rates as well as the tax rate of the Line Items.
  billingAddress?:
    type: Address
    description: |
      Address used for invoicing.
  inventoryMode?:
    type: InventoryMode
    description: |
      Inventory mode of the Cart referenced in the [QuoteRequestDraft](ctp:api:type:QuoteRequestDraft).
  taxMode:
    type: TaxMode
    description: |
      Tax mode of the Cart referenced in the [QuoteRequestDraft](ctp:api:type:QuoteRequestDraft).
  taxRoundingMode:
    type: RoundingMode
    description: |
      When calculating taxes for `taxedPrice`, the selected mode is used for rounding.
  taxCalculationMode:
    type: TaxCalculationMode
    description:
      When calculating taxes for `taxedPrice`, the selected mode is used for
      calculating the price with `LineItemLevel` (horizontally) or
      `UnitPriceLevel` (vertically) calculation mode.
  country?:
    type: CountryCode
    description: |
      Used for Product Variant price selection.
  shippingInfo?:
    type: ShippingInfo
    description: |
      Set automatically once the [ShippingMethod](ctp:api:type:ShippingMethod) is set.
  paymentInfo?:
    type: PaymentInfo
    description: |
      Log of payment transactions related to the Quote.
  shippingRateInput?:
    type: ShippingRateInput
    description: |
      Used to select a [ShippingRatePriceTier](ctp:api:type:ShippingRatePriceTier).
  itemShippingAddresses?:
    type: Address[]
    description: |
      Contains addresses for carts with multiple shipping addresses.
      Line items reference these addresses under their `shippingDetails`.
      The addresses captured here are not used to determine eligible shipping methods or the applicable tax rate.
      Only the cart's `shippingAddress` is used for this.
  directDiscounts?:
    type: DirectDiscount[]
    description: |
      Discounts that are only valid for the Quote and cannot be associated to any other Cart or Order.
  custom?:
    type: CustomFields
    description: |
      Custom Fields on the Quote.
  quoteState:
    type: QuoteState
    description: |
      Predefined states tracking the status of the Quote.
  state?:
    type: StateReference
    description: |
      [State](ctp:api:type:State) of the Quote.
      This reference can point to a State in a custom workflow.
  purchaseOrderNumber?:
    type: string
    description: |
      The Purchase Order Number is typically set by the [Buyer](/quotes-overview#buyer) on a [QuoteRequest](ctp:api:type:QuoteRequest) to
      track the purchase order during the [quote and order flow](/../api/quotes-overview#intended-workflow).
  businessUnit?:
    type: BusinessUnitKeyReference
    description: |
      The [BusinessUnit](ctp:api:type:BusinessUnit) for the Quote.
