#%RAML 1.0 DataType
(package): Quote
(docs-uri): https://docs.commercetools.com/http-api-projects-quotes#quotedraft
type: object
displayName: QuoteDraft
properties:
  stagedQuote:
    type: StagedQuoteResourceIdentifier
    description: StagedQuote from which the Quote is created.
  stagedQuoteVersion:
    type: number
    format: int64
    description: |
      Current version of the StagedQuote.
  stagedQuoteStateToSent?:
    type: boolean
    description: |
      If `true`, the `stagedQuoteState` of the referenced [StagedQuote](/../api/projects/staged-quotes#stagedquote) will be set to `Sent`.
    default: false
  key?:
    type: string
    description: |
      User-defined unique identifier for the Quote.
    pattern: ^[A-Za-z0-9_-]+$
    minLength: 2
    maxLength: 256
  custom?:
    type: CustomFieldsDraft
    description: |
      [Custom Fields](/../api/projects/custom-fields) to be added to the Quote.

      - If specified, the Custom Fields are merged with the Custom Fields on the referenced [StagedQuote](/../api/projects/staged-quotes#stagedquote) and added to the Quote.
      - If empty, the Custom Fields on the referenced [StagedQuote](/../api/projects/staged-quotes#stagedquote) are added to the Quote automatically.
  state?:
    type: StateReference
    description: |
      [State](ctp:api:type:State) of the Quote.
      This reference can point to a State in a custom workflow.
