#%RAML 1.0 DataType
(package): Quote
(docs-uri): https://docs.commercetools.com/http-api-projects-quote.html#quote
type: Reference
displayName: QuoteReference
discriminatorValue: quote
description: |
  [Reference](ctp:api:type:Reference) to a [Quote](ctp:api:type:Quote).
properties:
  obj?:
    type: Quote
    description: |
      Contains the representation of the expanded Quote.
      Only present in responses to requests with [Reference Expansion](/../api/general-concepts#reference-expansion) for Quote.
