#%RAML 1.0 DataType
(package): Quote
(docs-uri): https://docs.commercetools.com/http-api-projects-quotes.html#quotestate
displayName: QuoteState
type: string
description: |
  Predefined states tracking the status of the Quote.
enum:
  - Pending
  - Declined
  - DeclinedForRenegotiation
  - RenegotiationAddressed
  - Accepted
  - Withdrawn
(enumDescriptions):
  Pending: |
    A state indicating that the [Seller](/../api/quotes-overview#seller) submitted the Quote to the [Buyer](/../api/quotes-overview#buyer), but the [Buyer](/../api/quotes-overview#buyer) has not replied yet.

    This is the default state.
  Declined: |
    A state indicating that the [Buyer](/../api/quotes-overview#buyer) has declined the Quote.
  DeclinedForRenegotiation: |
    A state indicating that the [Buyer](/../api/quotes-overview#buyer) has declined and requested to [renegotiate](ctp:api:type:QuoteRequestQuoteRenegotiationAction) the Quote.
  RenegotiationAddressed: |
    A state indicating that the [Seller](/../api/quotes-overview#seller) has created a new Quote after a renegotiation has been requested.
  Accepted: |
    A state indicating that the [Buyer](/../api/quotes-overview#buyer) has accepted the Quote.
  Withdrawn: |
    A state indicating that the [Seller](/../api/quotes-overview#seller) has withdrawn the Quote before the [Buyer](/../api/quotes-overview#buyer) has accepted it.
