#%RAML 1.0 Library
usage: Common data types.
(annotations.package): Common
(annotations.beta): true

uses:
  annotations: annotations.raml

types:
  Region:
    description: |
      The Region in which the Checkout application is [hosted](/hosts-and-authorization).
    enum:
      - europe-west1.gcp
      - us-central1.gcp
      - australia-southeast1.gcp
    (annotations.enumDescriptions):
      europe-west1.gcp: |
        for Europe (Google Cloud, Belgium)
      us-central1.gcp: |
        for North America (Google Cloud, Iowa)
      australia-southeast1.gcp: |
        for Australia (Google Cloud, Sydney)

  Amount:
    description: |
      Money in cent amounts for a specific currency.
    properties:
      centAmount:
        type: integer
        description: |
          Amount in the smallest indivisible unit of a currency, such as:

          * Cents for EUR and USD, pence for GBP, or centime for CHF (5 CHF is specified as `500`).
          * The value in the major unit for currencies without minor units, like JPY (5 JPY is specified as `5`).
      currencyCode:
        type: string
        description: |
          Currency code compliant to [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217).
        pattern: ^[A-Z]{3}$
