# Responses
ResponseMessage: !include responses/ResponseMessage.raml
Message: !include responses/Message.raml
ApplicationDeactivated: !include responses/ApplicationDeactivated.raml
ApplicationNotFound: !include responses/ApplicationNotFound.raml
CartEmptiedDuringCheckout: !include responses/CartEmptiedDuringCheckout.raml
CartEmpty: !include responses/CartEmpty.raml
CartNotFound: !include responses/CartNotFound.raml
CheckoutCancelled: !include responses/CheckoutCancelled.raml
CheckoutCompleted: !include responses/CheckoutCompleted.raml
CheckoutLoaded: !include responses/CheckoutLoaded.raml
CheckoutStarted: !include responses/CheckoutStarted.raml
InitTimeout: !include responses/InitTimeout.raml
InvalidMode: !include responses/InvalidMode.raml
BadInputData: !include responses/BadInputData.raml
InvalidToken: !include responses/InvalidToken.raml
NoPaymentMethods: !include responses/NoPaymentMethods.raml
PaymentFailed: !include responses/PaymentFailed.raml
PaymentStarted: !include responses/PaymentStarted.raml
InitError: !include responses/InitError.raml
PaymentConnectorError: !include responses/PaymentConnectorError.raml
PaymentMethodLoaded: !include responses/PaymentMethodLoaded.raml
PaymentMethodLoading: !include responses/PaymentMethodLoading.raml
PaymentMethodLoadingError: !include responses/PaymentMethodLoadingError.raml
PaymentMethodSelected: !include responses/PaymentMethodSelected.raml
PaymentMethodSelectionConfirmation: !include responses/PaymentMethodSelectionConfirmation.raml
PaymentMethodSelectionConfirmationFailed: !include responses/PaymentMethodSelectionConfirmationFailed.raml
PaymentMethodsReceived: !include responses/PaymentMethodsReceived.raml
PaymentCancelled: !include responses/PaymentCancelled.raml
PaymentValidationFailed: !include responses/PaymentValidationFailed.raml
PaymentValidationPassed: !include responses/PaymentValidationPassed.raml
PaymentValidationStarted: !include responses/PaymentValidationStarted.raml
PaymentVerificationStarted: !include responses/PaymentVerificationStarted.raml
PaymentVerificationTimeout: !include responses/PaymentVerificationTimeout.raml
ExternalTermsAndConditionsPending: !include responses/ExternalTermsAndConditionsPending.raml
SetShippingAddressError: !include responses/SetShippingAddressError.raml
NoShippingMethods: !include responses/NoShippingMethods.raml
OrderCreated: !include responses/OrderCreated.raml
ProjectIsDeactivated: !include responses/ProjectIsDeactivated.raml
UnavailableLocale: !include responses/UnavailableLocale.raml
DeprecatedFields: !include responses/DeprecatedFields.raml
OrderCreationError: !include responses/OrderCreationError.raml
CartWithExistingPayment: !include responses/CartWithExistingPayment.raml
UnsupportedCountry: !include responses/UnsupportedCountry.raml

# payments
CapturePaymentAction: !include payments/capturePaymentAction.raml
RefundPaymentAction: !include payments/refundPaymentAction.raml
CancelPaymentAction: !include payments/cancelPaymentAction.raml
Payment: !include payments/payment.raml
# Payment Errors
ErrorObject: !include payments/error/ErrorObject.raml
GeneralError: !include payments/error/GeneralError.raml
MultipleActionsNotAllowedError: !include payments/error/MultipleActionsNotAllowedError.raml
RequiredFieldError: !include payments/error/RequiredFieldError.raml
ResourceNotFoundError: !include payments/error/ResourceNotFoundError.raml
