#%RAML 1.0 DataType
(package): TaxCategory
(docs-uri): https://docs.commercetools.com/http-api-projects-taxCategories.html#set-description
type: TaxCategoryUpdateAction
displayName: TaxCategorySetDescriptionAction
discriminatorValue: setDescription
(postman-example): !include ../../../examples/TaxCategory/TaxCategorySetDescriptionAction.json
properties:
  description?:
    type: string
    description: ''
