#%RAML 1.0 DataType
(package): Product
(docs-uri): https://docs.commercetools.com/http-api-projects-products.html#transition-state
type: ProductUpdateAction
displayName: ProductTransitionStateAction
discriminatorValue: transitionState
(postman-example): !include ../../../examples/Product/ProductTransitionStateAction.json
properties:
  state?:
    type: StateResourceIdentifier
    description: ''
  force?:
    type: boolean
    description: ''
