#%RAML 1.0 DataType
(package): Product
(docs-uri): https://docs.commercetools.com/http-api-projects-products.html#publish
type: ProductUpdateAction
displayName: ProductPublishAction
discriminatorValue: publish
(postman-example): !include ../../../examples/Product/ProductPublishAction.json
properties:
  scope?:
    type: ProductPublishScope
    description: ''
