#%RAML 1.0 Library
usage: Messages inside the system.
(annotations.package): messages

uses:
  common: ../../types/common.raml
  annotations: ../../annotationTypes/annotations.raml

types:
  ImportMessageHeaders:
    description: The required headers received by each message.
    properties:
      importSinkKey:
        description: the import sink where the message is handled
        type: string
      operationId:
        description: this is the operation id, used to identifiy the operation, currently in the form of a uuid
        type: string
      type:
        description: the import resource type
        type: common.ImportResourceType
      projectKey:
        description: the project key to which this import belongs.
        type: string
  ImportMessage:
    description: this types represents the import messages that circulates between internal queues
    properties:
      id?:
        description: the message headers
        type: string
      headers:
        description: the message headers
        type: ImportMessageHeaders
      data:
        description: The type of the import resource sent to this import sink.
        type: any
