#%RAML 1.0 Library
usage: Import operation types.
(annotations.package): importoperations

uses:
  common: ../../types/common.raml
  error: ../../types/error.raml
  annotations: ../../annotationTypes/annotations.raml
  import-operation: ../../types/import-operation.raml

types:
  PublicImportOperation:
    description: |
      Tracks the status of a single import resource as it is imported into the commercetools project.
    type: import-operation.ImportOperation
  PublicImportOperationPagedResponse:
    description: This type represents a paged import operation result.
    properties:
      limit:
        description: The maximum number of import operations returned for a page.
        type: integer
      offset:
        description: The offset supplied by the client or the server default. It is the number of elements skipped.
        type: integer
        format: long
      count:
        description: The actual number of results returned by this response.
        type: integer
        format: long
      results:
        description: The results for this paged response.
        type: PublicImportOperation[]
