#%RAML 1.0 DataType
(package): TaxCategory
(docs-uri): https://docs.commercetools.com/http-api-projects-taxCategories.html#set-description
type: TaxCategoryUpdateAction
displayName: TaxCategorySetDescriptionAction
discriminatorValue: setDescription
example: !include ../../../examples/TaxCategory/TaxCategorySetDescriptionAction.json
properties:
  description?:
    type: string
    description: |
      Value to set. If empty, any existing value will be removed.
