#%RAML 1.0 DataType
(package): TaxCategory
type: TaxCategoryUpdateAction
displayName: TaxCategoryAddTaxRateAction
discriminatorValue: addTaxRate
example: !include ../../../examples/TaxCategory/TaxCategoryAddTaxRateAction.json
properties:
  taxRate:
    type: TaxRateDraft
    description: |
      Value to append to the `rates` array.
