#%RAML 1.0 DataType
(package): TaxCategory
type: TaxCategoryUpdateAction
displayName: TaxCategoryReplaceTaxRateAction
discriminatorValue: replaceTaxRate
example: !include ../../../examples/TaxCategory/TaxCategoryReplaceTaxRateAction.json
properties:
  taxRateId?:
    type: string
    description: |
      ID of the TaxRate to replace.
      Either `taxRateId` or `taxRateKey` is required for this update action.
  taxRateKey?:
    type: string
    description: |
      Key of the TaxRate to replace.
      Either `taxRateId` or `taxRateKey` is required for this update action.
  taxRate:
    type: TaxRateDraft
    description: |
      New TaxRate to replace with.
