#%RAML 1.0 DataType
(package): DiscountCode
(docs-uri): https://docs.commercetools.com/projects/discountCodes#set-custom-type
type: DiscountCodeUpdateAction
displayName: DiscountCodeSetCustomTypeAction
discriminatorValue: setCustomType
example: !include ../../../examples/DiscountCode/DiscountCodeSetCustomTypeAction.json
properties:
  type?:
    type: TypeResourceIdentifier
    description: |
      Defines the [Type](ctp:api:type:Type) that extends the DiscountCode with [Custom Fields](/../api/projects/custom-fields).
      If absent, any existing Type and Custom Fields are removed from the DiscountCode.
  fields?:
    type: FieldContainer
    description: |
      Sets the [Custom Fields](/../api/projects/custom-fields) fields for the DiscountCode.
