#%RAML 1.0 DataType
(package): DiscountCode
(docs-uri): https://docs.commercetools.com/http-api-projects-discountCodes.html#set-custom-type
type: DiscountCodeUpdateAction
displayName: DiscountCodeSetCustomTypeAction
discriminatorValue: setCustomType
(postman-example): !include ../../../examples/DiscountCode/DiscountCodeSetCustomTypeAction.json
properties:
  type?:
    type: TypeResourceIdentifier
    description: If absent, the custom type and any existing CustomFields are removed.
  fields?:
    type: FieldContainer
    description: |-
      A valid JSON object, based on the FieldDefinitions of the Type.
      Sets the custom fields to this value.
