#%RAML 1.0 DataType
(package): DiscountCode
(docs-uri): https://docs.commercetools.com/api/projects/discount-codes#set-key
type: DiscountCodeUpdateAction
displayName: DiscountCodeSetKeyAction
discriminatorValue: setKey
example: !include ../../../examples/DiscountCode/DiscountCodeSetKeyAction.json
description: |
  This action generates a [DiscountCodeKeySet](ctp:api:type:DiscountCodeKeySetMessage) Message.
properties:
  key?:
    type: string
    description: |
      Unique value to set.
      If empty, any existing value will be removed.
    pattern: ^[A-Za-z0-9_-]+$
    minLength: 2
    maxLength: 256
