#%RAML 1.0 DataType
(package): Review
(java-extends): com.commercetools.api.models.Identifiable<Review>
type: Reference
displayName: ReviewReference
discriminatorValue: review
description: |
  [Reference](ctp:api:type:Reference) to a [Review](ctp:api:type:Review).
properties:
  obj?:
    type: Review
    description: |
      Contains the representation of the expanded Review. Only present in responses to requests with [Reference Expansion](/../api/general-concepts#reference-expansion) for Reviews.
  id:
    type: string
    description: |
      Platform-generated unique identifier of the referenced [Review](ctp:api:type:Review).
