#%RAML 1.0 DataType
(package): RecurringOrder
(beta): true
type: string
description: |
  Indicates the state of the [RecurringOrder](ctp:api:type:RecurringOrder).
enum:
  - Active
  - Paused
  - Expired
  - Canceled
  - Failed
(enumDescriptions):
  Active: |
    The default state of a new RecurringOrder.
  Paused: |
    Indicates that the RecurringOrder is paused.
  Expired: |
    Indicates that the RecurringOrder has expired.
  Canceled: |
    Indicates that the RecurringOrder is canceled.
  Failed: |
    Indicates that the process of creating new orders has failed. The field `failure` stores the error encountered (inventory unavailable, etc). New orders will not be created until the issue is fixed.
