#%RAML 1.0 DataType
(package): RecurringOrder
displayName: RecurringOrder
(beta): true
(updateType): RecurringOrderUpdate
type: BaseResource
properties:
  id:
    (identifier): true
    type: string
    description: |
      Unique identifier of the RecurringOrder.
  key?:
    type: string
    description: |
      User-defined unique identifier of the RecurringOrder.
    pattern: ^[A-Za-z0-9_-]+$
    minLength: 2
    maxLength: 256
  version:
    type: number
    format: int64
    description: |
      Current version of the RecurringOrder.
  cart:
    type: CartReference
    description: |
      [Reference](ctp:api:type:Reference) to the Cart for a RecurringOrder.
      The referenced Cart will have the `RecurringOrder` [CartOrigin](ctp:api:type:CartOrigin).
  originOrder:
    type: OrderReference
    description: |
      [Reference](ctp:api:type:Reference) to the original [Order](ctp:api:type:Order) that generated this RecurringOrder.
  startsAt:
    type: datetime
    description: |
      Date and time (UTC) when the RecurringOrder starts creating new Orders.
  resumesAt?:
    type: datetime
    description: |
      Date and time (UTC) when the RecurringOrder resumes creating Orders after being unpaused.
  expiresAt?:
    type: datetime
    description: |
      Date and time (UTC) when the RecurringOrder expires.
  lastOrderAt?:
    type: datetime
    description: |
      Date and time (UTC) when the last Order was created from this RecurringOrder.
  nextOrderAt?:
    type: datetime
    description: |
      Date and time (UTC) when the next Order will be created from this RecurringOrder.
  skipConfiguration?:
    type: SkipConfiguration
    description: |
      Information about current and future skips for this RecurringOrder.
  store?:
    type: StoreKeyReference
    description: |
      [Reference](ctp:api:type:Reference) to a Store.
  businessUnit?:
    type: BusinessUnitKeyReference
    description: |
      [Reference](ctp:api:type:Reference) to the Business Unit that the RecurringOrder belongs to.
  state?:
    type: StateReference
    description: |
      [State](ctp:api:type:State) of the RecurringOrder in a custom workflow.
  recurringOrderState:
    type: RecurringOrderState
    description: |
      Current state of the RecurringOrder.
  schedule:
    type: RecurrencePolicySchedule
    description: |
      Schedule of the RecurringOrder.
  customer?:
    type: CustomerReference
    description: |
      The [Customer](ctp:api:type:Customer) that the RecurringOrder belongs to.
  customerEmail?:
    type: string
    description: |
      Email address of the Customer that the RecurringOrder belongs to.
  custom?:
    type: CustomFields
    description: |
      Custom Fields of the RecurringOrder.
  createdAt:
    type: datetime
    description: |
      Date and time (UTC) when the RecurringOrder was created.
  lastModifiedAt:
    type: datetime
    description: |
      Date and time (UTC) when the RecurringOrder was last updated.
  lastModifiedBy?:
    type: LastModifiedBy
    (beta): true
    description: |
      IDs and references that last modified the RecurringOrder.
  createdBy?:
    type: CreatedBy
    (beta): true
    description: |
      IDs and references that created the RecurringOrder.
