#%RAML 1.0 DataType
(package): RecurringOrder
type: RecurringOrderStateDraft
displayName: Expired
discriminatorValue: expired
description: |
  Changes the Recurring Order state to expired.
properties:
