#%RAML 1.0 DataType
(package): RecurringOrder
type: Reference
displayName: RecurringOrderReference
(beta): true
discriminatorValue: recurring-order
description: |
  [Reference](ctp:api:type:Reference) to a [RecurringOrder](ctp:api:type:RecurringOrder).
properties:
  obj?:
    type: RecurringOrder
    description: |
      Contains the representation of the expanded RecurringOrder.
      Only present in responses to requests with [Reference Expansion](/../api/general-concepts#reference-expansion) for RecurringOrders.
  id:
    type: string
    description: |
      Unique identifier of the referenced [RecurringOrder](ctp:api:type:RecurringOrder).
