#%RAML 1.0 DataType
(package): OrderEdit
(docs-uri): https://docs.commercetools.com/http-api-projects-order-edits.html#ordereditdraft

displayName: OrderEditDraft

type: object
properties:
  key?:
    type: string
  resource:
    type: OrderReference
  stagedActions?:
    type: StagedOrderUpdateAction[]
  custom?:
    type: CustomFieldsDraft
  comment?:
    type: string
  dryRun?:
    type: boolean
