#%RAML 1.0 DataType
(package): Payment
type: object
displayName: PaymentUpdate
properties:
  version:
    type: number
    format: int64
    description: |
      Expected version of the Payment on which the changes should be applied. If the expected version does not match the actual version, a [409 Conflict](/../api/errors#409-conflict) error will be returned.
  actions:
    type: array
    items: PaymentUpdateAction
    description: |
      Update actions to be performed on the Payment.
