#%RAML 1.0 DataType
(package): Payment
type: object
displayName: PaymentMethodInfoDraft
(beta): true
properties:
  paymentInterface?:
    type: string
    description: |
      Payment service that processes the Payment—for example, a PSP.
      The combination of `paymentInterface` and the `interfaceId` of a Payment must be unique.

      The value cannot be modified after it is set.
  method?:
    type: string
    description: |
      Payment method to use—for example, a credit card or direct debit.
  name?:
    type: LocalizedString
    description: |
      Name of the Payment Method.
  token?:
    type: PaymentMethodToken
    description: |
      Tokenized representation of the Payment Method used by the payment interface.
  interfaceAccount?:
    type: string
    description: |
      Account or instance of the payment interface when multiple accounts are used (per interface).
  custom?:
    type: CustomFieldsDraft
    description: |
      Custom fields for the PaymentMethodInfo.
