#%RAML 1.0 DataType
(package): Payment
type: object
displayName: TransactionDraft
(java-extends): 'com.commercetools.api.models.CustomizableDraft<TransactionDraft>'
properties:
  timestamp?:
    type: datetime
    description: Date and time (UTC) the Transaction took place.
  type:
    type: TransactionType
    description: Type of the Transaction.
  amount:
    type: Money
    description: |
      Money value for the Transaction.
  interactionId?:
    type: string
    description: |-
      Identifier used by the payment service that manages the Transaction.
      Can be used to correlate the Transaction to an interface interaction.
  state?:
    type: TransactionState
    description: |-
      State of the Transaction.
    default: Initial
  custom?:
    type: CustomFieldsDraft
    description: Custom Fields of the Transaction.
