#%RAML 1.0 DataType
(package): Payment
displayName: TransactionState
description: |
  Transactions can be in one of the following States:
type: string
enum:
  - Initial
  - Pending
  - Success
  - Failure
(enumDescriptions):
  Initial: |
    Initial State. The payment service has not accepted the Transaction yet.
  Pending: |
    The payment service has accepted the Transaction, but it is not completed yet.
  Success: |
    The payment service has confirmed the successful completion of the Transation.
  Failure: |
    Transaction has unrecoverably failed.
