#%RAML 1.0 DataType
(package): Payment
(docs-uri): https://docs.commercetools.com/api/projects/payments#transactiontype
displayName: TransactionType
type: string
enum:
  - Authorization
  - CancelAuthorization
  - Charge
  - Refund
  - Chargeback
(enumDescriptions):
  Authorization: |
    Financially reliable reservation of an amount. Typically does not indicate an actual transfer of money.
  CancelAuthorization: |
    Explicit cancellation of an authorized amount before its expiry.
  Charge: |
    Collection of money from the customer. Can use an authorized amount or be directly executed.
  Refund: |
    Explicit transfer of money back to the customer.
  Chargeback: |
    Customer-initiated transfer of money back to the customer.
