# Callbacks
Cart: !include callbacks/Cart.raml
CartRetrievalResponse: !include callbacks/CartRetrievalResponse.raml
CartTypeEnum: !include callbacks/CartTypeEnum.raml
Cash: !include callbacks/Cash.raml
Credit: !include callbacks/Credit.raml
GiftCard: !include callbacks/GiftCard.raml
ItemAttribute: !include callbacks/ItemAttribute.raml
PriceModifier: !include callbacks/PriceModifier.raml
TaxType: !include callbacks/TaxType.raml
Tender: !include callbacks/Tender.raml
TenderType: !include callbacks/TenderType.raml
TokenRetrievalResponse: !include callbacks/TokenRetrievalResponse.raml
TransactionLineItem: !include callbacks/TransactionLineItem.raml
Wallet: !include callbacks/Wallet.raml
# Errors
ErrorResponse: !include errors/ErrorResponse.raml
# Locations
Location: !include locations/Location.raml
CardPaymentProviderEnum: !include /locations/CardPaymentProviderEnum.raml
GiftCardProcessorEnum: !include /locations/GiftCardProcessorEnum.raml
LocationStatusEnum: !include /locations/LocationStatusEnum.raml
WalletProcessorEnum: !include /locations/WalletProcessorEnum.raml
# Roles
Role: !include roles/Role.raml
# Sessions
CashManagementRequest: !include sessions/CashManagementRequest.raml
ConfigurationToken: !include sessions/ConfigurationToken.raml
DeviceManagementRequest: !include sessions/DeviceManagementRequest.raml
InStorePermission: !include sessions/InStorePermission.raml
PaymentCart: !include sessions/PaymentCart.raml
PaymentRequest: !include sessions/PaymentRequest.raml
RefundCart: !include sessions/RefundCart.raml
RefundRequest: !include sessions/RefundRequest.raml
UserToken: !include sessions/UserToken.raml
ConfigurationTokenRequest: !include sessions/ConfigurationTokenRequest.raml
SessionToken: !include sessions/SessionToken.raml
Theme: !include sessions/Theme.raml
UserTokenRequest: !include sessions/UserTokenRequest.raml
# Workstations
Workstation: !include workstations/Workstation.raml
WorkstationMobilityEnum: !include workstations/WorkstationMobilityEnum.raml
WorkstationStatusEnum: !include workstations/WorkstationStatusEnum.raml
