#%RAML 1.0 DataType
(package): Project
(docs-uri): https://docs.commercetools.com/http-api-projects-project.html#change-currencies
type: ProjectUpdateAction
displayName: ProjectChangeCurrenciesAction
discriminatorValue: changeCurrencies
(postman-example): !include ../../../examples/Project/ProjectChangeCurrenciesAction.json
properties:
  currencies:
    type: CurrencyCode[]
    description: A three-digit currency code as per currency code.
