#%RAML 1.0 DataType
(package): Project
(docs-uri): https://docs.commercetools.com/http-api-projects-project.html#change-countries
type: ProjectUpdateAction
displayName: ProjectChangeCountriesAction
discriminatorValue: changeCountries
(postman-example): !include ../../../examples/Project/ProjectChangeCountriesAction.json
properties:
  countries:
    type: CountryCode[]
    description: A two-digit country code as per country code.
