#%RAML 1.0 DataType
(package): State
(docs-uri): https://docs.commercetools.com/http-api-projects-states.html#remove-state-roles
type: StateUpdateAction
displayName: StateRemoveRolesAction
discriminatorValue: removeRoles
(postman-example): !include ../../../examples/State/StateRemoveRolesAction.json
properties:
  roles:
    type: StateRoleEnum[]
