#%RAML 1.0 DataType
(package): ShippingMethod
type: ShippingMethodUpdateAction
displayName: ShippingMethodSetCustomFieldAction
description: |
  This action sets, overwrites, or removes any existing [Custom Field](/projects/custom-fields) for an existing ShippingMethod.
discriminatorValue: setCustomField
example: !include ../../../examples/ShippingMethod/ShippingMethodSetCustomFieldAction.json
properties:
  name:
    type: string
    description: |
      Name of the [Custom Field](/../api/projects/custom-fields).
  value?:
    type: CustomFieldValue
    description: |
      If `value` is absent or `null`, this field will be removed if it exists.
      Removing a field that does not exist returns an [InvalidOperation](ctp:api:type:InvalidOperationError) error.
      If `value` is provided, it is set for the field defined by `name`.
