#%RAML 1.0 DataType
(package): ShippingMethod
(docs-uri): https://docs.commercetools.com/http-api-projects-shippingMethods.html#set-localized-description
type: ShippingMethodUpdateAction
displayName: ShippingMethodSetLocalizedDescriptionAction
discriminatorValue: setLocalizedDescription
(postman-example): !include ../../../examples/ShippingMethod/ShippingMethodSetLocalizedDescriptionAction.json
properties:
  localizedDescription?:
    type: LocalizedString
    description: ''
