#%RAML 1.0 DataType
(package): ShippingMethod
type: ShippingMethodUpdateAction
displayName: ShippingMethodAddZoneAction
discriminatorValue: addZone
example: !include ../../../examples/ShippingMethod/ShippingMethodAddZoneAction.json
properties:
  zone:
    type: ZoneResourceIdentifier
    description: |
      Value to add to `zoneRates`.

      Adds a new [ZoneRate](ctp:api:type:ZoneRate) entry to the `zoneRates` array with the specified [Zone](ctp:api:type:Zone) and an empty `shippingRates` array. After adding the Zone, you can add [ShippingRates](ctp:api:type:ShippingRate) for this Zone using the [Add ShippingRate](ctp:api:type:ShippingMethodAddShippingRateAction) update action.
