#%RAML 1.0 DataType
(package): ShippingMethod
type: ShippingMethodUpdateAction
displayName: ShippingMethodSetStoresAction
discriminatorValue: setStores
example: !include ../../../examples/ShippingMethod/ShippingMethodSetStoresAction.json
description: |
  Sets the Stores the ShippingMethod is associated with.
  If empty, the ShippingMethod becomes a global ShippingMethod.

properties:
  stores:
    type: StoreResourceIdentifier[]
    maxItems: 100
    description: |
      ResourceIdentifiers of the Stores to set.
      Overrides the current list of Stores.
      If empty, any existing values are removed.
