#%RAML 1.0 DataType
(package): ShippingMethod
(docs-uri): https://docs.commercetools.com/http-api-projects-shippingMethods.html#set-customfield
type: ShippingMethodUpdateAction
displayName: ShippingMethodSetCustomFieldAction
discriminatorValue: setCustomField
(postman-example): !include ../../../examples/ShippingMethod/ShippingMethodSetCustomFieldAction.json
properties:
  name:
    type: string
  value?:
    type: any
