#%RAML 1.0 DataType
(package): ShippingMethod
(docs-uri): https://docs.commercetools.com/api/projects/shippingMethods#set-localized-description
type: ShippingMethodUpdateAction
displayName: ShippingMethodSetLocalizedDescriptionAction
discriminatorValue: setLocalizedDescription
example: !include ../../../examples/ShippingMethod/ShippingMethodSetLocalizedDescriptionAction.json
properties:
  localizedDescription?:
    type: LocalizedString
    description: Value to set. If empty, any existing value will be removed.
