#%RAML 1.0 DataType
(package): ShippingMethod
(docs-uri): https://docs.commercetools.com/http-api-projects-shippingMethods.html#set-customtype
type: ShippingMethodUpdateAction
displayName: ShippingMethodSetCustomTypeAction
discriminatorValue: setCustomType
example: !include ../../../examples/ShippingMethod/ShippingMethodSetCustomTypeAction.json
properties:
  type?:
    type: TypeResourceIdentifier
    description: |
      Defines the [Type](ctp:api:type:Type) that extends the ShippingMethod with [Custom Fields](/../api/projects/custom-fields).
      If absent, any existing Type and Custom Fields are removed from the ShippingMethod.
  fields?:
    type: FieldContainer
    description: |
      Sets the [Custom Fields](/../api/projects/custom-fields) fields for the ShippingMethod.
