#%RAML 1.0 DataType
(package): Channel
(docs-uri): https://docs.commercetools.com/http-api-projects-channels.html#set-geolocation
type: ChannelUpdateAction
displayName: ChannelSetGeoLocationAction
discriminatorValue: setGeoLocation
(postman-example): !include ../../../examples/Channel/ChannelSetGeoLocationAction.json
properties:
  geoLocation?:
    type: GeoJson
    description: ''
