#%RAML 1.0 DataType
(package): Variant
type: VariantBulkUpdateResult
(beta): true
displayName: VariantBulkUpdateSuccessResult
discriminatorValue: Success
example: !include ../../examples/Variant/VariantBulkUpdateSuccessResult.json
description: |
  Result for a Variant that was successfully updated in a bulk update request.
properties:
  resource:
    type: VariantBulkUpdateResource
    description: |
      A lightweight reference containing the `id` and updated `version` of the Variant.
