#%RAML 1.0 DataType
(package): Variant
type: object
(beta): true
displayName: VariantBulkUpdateResponse
example: !include ../../examples/Variant/VariantBulkUpdateResponse.json
description: |
  The response body for a bulk update of Variants. Contains the individual result for each Variant in the request.
properties:
  successCount:
    type: number
    format: int32
    description: |
      Number of Variants that were successfully updated.
  failureCount:
    type: number
    format: int32
    description: |
      Number of Variants that failed to update.
  results:
    type: array
    items: VariantBulkUpdateResult
    description: |
      Results for each Variant in the request, in the same order as the `items` in the request body.
