#%RAML 1.0
---
title: Commercetools OAuth API
version: 1
baseUri: https://auth.europe-west1.gcp.commercetools.com
securitySchemes:
  basic:
    description: |
      To obtain an access token through the client credentials flow, simply issue the following request to the
      auth service, providing your client_id and client_secret via HTTP Basic Authentication , where the username
      is the client_id and the password is the client_secret
    type: Basic Authentication
securedBy: basic
resourceTypes:
  base:
    post:
      queryParameters:
        grant_type:
          type: GrantType
        scope?:
          type: string
      responses:
        200:
          body:
            application/json:
              type: TokenResponse
        401:
          description: Unauthorized
types:
  IntrospectResponse:
    properties:
      active:
        type: boolean
      scope?:
        type: string
      exp?:
        type: number
        format: int64
  TokenResponse:
    properties:
      access_token:
        type: string
      expires_in:
        type: number
        format: int64
      scope:
        type: string
      token_type:
        type: TokenType
  RefreshTokenResponse:
    type: TokenResponse
    properties:
      refresh_token:
        type: string
  TokenType:
    type: string
    enum:
      - Bearer
  ClientCredentialsType:
    type: GrantType
    enum:
      - client_credentials
  PasswordType:
    type: GrantType
    enum:
      - password
  RefreshTokenType:
    type: GrantType
    enum:
      - refresh_token
  GrantType:
    type: string
/oauth:
  /introspect:
    post:
      queryParameters:
        token:
          type: string
      responses:
        200:
          body:
            application/json:
              type: IntrospectResponse
  /token:
    type: base
    post:
      queryParameters:
        grant_type:
          type: ClientCredentialsType | RefreshTokenType
        refresh_token?:
          type: string
  /{projectKey}:
    /customers/token:
      type: base
      post:
        description: |
          To obtain an access token through the password flow, you need to provide the email and unencrypted
          password of the customer in addition to your OAuth client credentials.

          In addition to the access token, a refresh token is issued. The refresh token may be used to get a
          new access token without supplying email and password if the access token has expired.
        queryParameters:
          grant_type:
            type: PasswordType
          username:
            type: string
          password:
            type: string
        responses:
          200:
            body:
              application/json:
                type: RefreshTokenResponse
    /anonymous/token:
      type: base
      post:
        description: |
          To obtain an access token for an Anonymous Session, the OAuth client needs the create_anonymous_token scope.
          The regular Client Credentials Flow is used.

          These access tokens are similar to those issued with the Password Flow, but they are not associated with a
          customer but with an anonymousId. In addition to the access token, a refresh token is issued. The refresh
          token is the only way to get a new access token for this particular anonymousId.

          The anonymousId is either generated by the API or an unused id may be supplied with the optional parameter
          anonymous_id.
        queryParameters:
          grant_type:
            type: ClientCredentialsType
          anonymous_id?:
            type: string
        responses:
          200:
            body:
              application/json:
                type: RefreshTokenResponse
