#%RAML 1.0 DataType
(package): Zone


type: object
displayName: Location
(generate-collection): true
properties:
    country:
        (generator-type): string
        type: CountryCode
    state?:
        type: string
