#%RAML 1.0 DataType
(package): Zone
(docs-uri): https://docs.commercetools.com/http-api-projects-zones.html#location
type: object
displayName: Location
properties:
  country:
    type: CountryCode
    description: A two-digit country code as per {% include external/country_code.html
      %}.
  state?:
    type: string
    description: ''
