#%RAML 1.0 DataType

uses:
    api: ../types.lib.raml
type: object
displayName: Location
(generate-collection): true
properties:
    country:
        (generator-type): string
        type: api.CountryCode
    state?:
        type: string
