#%RAML 1.0 DataType
(package): Zone


type: ZoneUpdateAction
displayName: ZoneChangeNameAction
discriminatorValue: changeName
example:
  {
    "action": "changeName",
    "name": "changedName"
  }
properties:
    name:
        type: string
