#%RAML 1.0 DataType
(package): Zone


type: ZoneUpdateAction
displayName: ZoneSetDescriptionAction
discriminatorValue: setDescription
#example: |
#  {
#    "action": "setDescription",
#    "description": "new ZoneDescription"
#  }
properties:
    description?:
        type: string
