on:
  pull_request:
    paths:
      - 'api-specs/**'
  workflow_dispatch:

name: "Changes"

jobs:
  diff:
    name: "Show changes"
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - name: "Checkout api reference"
        uses: actions/checkout@v3
        with:
          path: commercetools-api-reference

      - name: "Checkout previous api reference"
        uses: actions/checkout@v3
        with:
          ref: main
          path: commercetools-api-reference-main

      - name: "Install codegen"
        run: curl -o- -s https://raw.githubusercontent.com/commercetools/rmf-codegen/main/scripts/install.sh | bash

      - name: 'Calculate diff (CoCo)'
        continue-on-error: true
        id: diff_api
        run: rmf-codegen diff -f MARKDOWN -t ./changes_api.txt commercetools-api-reference-main/api-specs/api/api.raml commercetools-api-reference/api-specs/api/api.raml

      - name: 'Calculate diff (History)'
        id: diff_history
        continue-on-error: true
        run: rmf-codegen diff -f MARKDOWN -t ./changes_history.txt commercetools-api-reference-main/api-specs/history/api.raml commercetools-api-reference/api-specs/history/api.raml

      - name: 'Calculate diff (ImportAPI)'
        id: diff_importapi
        continue-on-error: true
        run: rmf-codegen diff -f MARKDOWN -t ./changes_import.txt commercetools-api-reference-main/api-specs/importapi/api.raml commercetools-api-reference/api-specs/importapi/api.raml

      - name: 'Calculate diff (ML)'
        id: diff_ml
        continue-on-error: true
        run: rmf-codegen diff -f MARKDOWN -t ./changes_ml.txt commercetools-api-reference-main/api-specs/ml/api.raml commercetools-api-reference/api-specs/ml/api.raml

      - name: 'Create comment'
        run: |
          if [ -f ./changes_api.txt ]; then
            echo "## CoCo RAML changes" >> ./changes.txt
            echo "" >> ./changes.txt
            cat ./changes_api.txt >> ./changes.txt
            echo "" >> ./changes.txt
          fi
          if [ -f ./changes_import.txt ]; then
            echo "## Import RAML changes" >> ./changes.txt
            echo "" >> ./changes.txt
            cat ./changes_import.txt >> ./changes.txt
            echo "" >> ./changes.txt
          fi
          if [ -f ./changes_history.txt ]; then
            echo "## History RAML changes" >> ./changes.txt
            echo "" >> ./changes.txt
            cat ./changes_history.txt >> ./changes.txt
            echo "" >> ./changes.txt
          fi
          if [ -f ./changes_ml.txt ]; then
            echo "## ML RAML changes" >> ./changes.txt
            echo "" >> changes.txt
            cat ./changes_ml.txt >> ./changes.txt
            echo "" >> ./changes.txt
          fi
          if [ -f ./changes.txt ]; then
            cat ./changes.txt
          fi

      - uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          header: changes
          path: changes.txt
