on:
#  push:
#    paths:
#      - 'api-specs/**'
  workflow_dispatch:

name: "SDK Generator"

permissions: {}

jobs:
  sdk:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        language:
          - java
          - csharp
          - typescript
          - php
#          - postman
        include:
          - language: java
            repository: 'commercetools/commercetools-sdk-java-v2'
            sshKey: JAVA_SDK_DEPLOY_KEY
          - language: csharp
            repository: 'commercetools/commercetools-dotnet-core-sdk-v2'
            sshKey: CSHARP_SDK_DEPLOY_KEY
          - language: typescript
            repository: 'commercetools/commercetools-sdk-typescript'
            sshKey: TS_SDK_DEPLOY_KEY
          - language: php
            repository: 'commercetools/commercetools-sdk-php-v2'
            sshKey: SDK_DEPLOY_KEY
#          - language: postman
#            repository: 'commercetools/commercetools-postman-collection'
#            sshKey: ${{ secrets.POSTMAN_DEPLOY_KEY }}
    steps:
      - name: "Checkout api reference"
        uses: actions/checkout@v3
        with:
          path: commercetools-api-reference

      - name: "Checkout SDK"
        uses: actions/checkout@v3
        with:
          repository: ${{ matrix.repository }}
          path: commercetools-sdk
          ssh-key: ${{ secrets[matrix.sshKey] }}
