#%RAML 1.0 DataType
(package): Channel
(docs-uri): https://docs.commercetools.com/http-api-projects-channels.html#channel
displayName: Channel
(updateType): ChannelUpdate
type: BaseResource
(java-extends): 'com.commercetools.api.models.DomainResource<Channel>'
properties:
  id:
    (identifier): true
    type: string
    description: The unique ID of the channel.
  version:
    type: number
    format: int64
    description: ''
  createdAt:
    type: datetime
    description: ''
  lastModifiedAt:
    type: datetime
    description: ''
  lastModifiedBy?:
    type: LastModifiedBy
    description:
      Present on resources updated after 1/02/2019 except for events not
      tracked.
  createdBy?:
    type: CreatedBy
    description:
      Present on resources created after 1/02/2019 except for events not
      tracked.
  key:
    type: string
    description:
      Any arbitrary string key that uniquely identifies this channel within the
      project.
  roles:
    type: ChannelRoleEnum[]
    description: |-
      The roles of this channel.
      Each channel must have at least one role.
  name?:
    type: LocalizedString
    description: A human-readable name of the channel.
  description?:
    type: LocalizedString
    description: A human-readable description of the channel.
  address?:
    type: Address
    description: |-
      The address where this channel is located (e.g.
      if the channel is a physical store).
  reviewRatingStatistics?:
    type: ReviewRatingStatistics
    description: Statistics about the review ratings taken into account for this channel.
  custom?:
    type: CustomFields
    description: ''
  geoLocation?:
    type: GeoJson
    description: A GeoJSON geometry object encoding the geo location of the channel.
