#%RAML 1.0 DataType
(package): Channel
displayName: ChannelDraft
type: object
properties:
  key:
    type: string
    description: |
      User-defined unique identifier for the Channel.
  roles?:
    type: ChannelRoleEnum[]
    description: |
      Roles of the Channel.
      Each channel must have at least one role.
      If not specified, then `InventorySupply` is assigned by default.
  name?:
    type: LocalizedString
    description: |
      Name of the Channel.
  description?:
    type: LocalizedString
    description: |
      Description of the Channel.
  address?:
    type: AddressDraft
    description: |
      Address where the Channel is located.
  custom?:
    type: CustomFieldsDraft
    description: |
      Custom fields defined for the Channel.
  geoLocation?:
    type: GeoJson
    description: |
      GeoJSON geometry object encoding the geo location of the Channel.
      Currently, only the [Point](ctp:api:type:GeoJsonPoint) type is supported.
