#%RAML 1.0 DataType
(package): Channel
type: object
displayName: ChannelUpdate
properties:
  version:
    type: number
    format: int64
    description: |
      Expected version of the Channel on which the changes should be applied. If the expected version does not match the actual version, a [ConcurrentModification](ctp:api:type:ConcurrentModificationError) error is returned.
  actions:
    type: array
    items: ChannelUpdateAction
    description: |
      Update actions to be performed on the Channel.
