#%RAML 1.0 DataType
(package): Channel
(docs-uri): https://docs.commercetools.com/api/projects/channels#channel
displayName: Channel
(updateType): ChannelUpdate
type: BaseResource
properties:
  id:
    (identifier): true
    type: string
    description: |
      Unique identifier of the Channel.
  version:
    type: number
    format: int64
    description: |
      Current version of the Channel.
  createdAt:
    type: datetime
    description: |
      Date and time (UTC) the Channel was initially created.
  lastModifiedAt:
    type: datetime
    description: |
      Date and time (UTC) the Channel was last updated.
  lastModifiedBy?:
    type: LastModifiedBy
    (beta): true
    description: |
      Present on resources updated after 1 February 2019 except for [events not tracked](/../api/general-concepts#events-tracked).
  createdBy?:
    type: CreatedBy
    (beta): true
    description: |
      Present on resources created after 1 February 2019 except for [events not tracked](/../api/general-concepts#events-tracked).
  key:
    type: string
    description: |
      User-defined unique identifier of the Channel.
  roles:
    type: ChannelRoleEnum[]
    description: |
      Roles of the Channel.
  name?:
    type: LocalizedString
    description: |
      Name of the Channel.
  description?:
    type: LocalizedString
    description: |
      Description of the Channel.
  address?:
    type: Address
    description: |
      Address where the Channel is located (for example, if the Channel is a physical store).
  reviewRatingStatistics?:
    type: ReviewRatingStatistics
    description: |
      Statistics about the review ratings taken into account for the Channel.
  custom?:
    type: CustomFields
    description: |
      Custom Fields defined for the Channel.
  geoLocation?:
    type: GeoJson
    description: |
      GeoJSON geometry object encoding the geo location of the Channel.
