#%RAML 1.0 DataType
(package): Channel
displayName: ChannelRoleEnum
type: string
description: |
  Describes the purpose and type of the Channel. A Channel can have one or more roles.
enum:
  - InventorySupply
  - ProductDistribution
  - OrderExport
  - OrderImport
  - Primary
(enumDescriptions):
  InventorySupply: |
    Channel can be used to track inventory entries (for example, Channels with this role can be treated as warehouses).
  ProductDistribution: |
    Channel can be used to expose Products to a specific distribution Channel.
    The Channel can be used by a Cart to [select](ctp:api:type:LineItemPriceSelection) a Product Price.
  OrderExport: |
    Channel can be used to track order export activities.
  OrderImport: |
    Channel can be used to track order import activities.
  Primary: |
    This role can be combined with the other roles (for example, with `InventorySupply`). If used, the Channel is considered as the primary or main channel among Channels of the same type.
