#%RAML 1.0 ResourceType

get:
  description: |
    Returns a list of locations associated with the current tenant.
  headers:
    token:
      displayName: Token
      description: |
        Login token generated for an admin.
      type: string
  responses:
    200:
      body:
        type: Location[]
        example: !include ../examples/locations/locations.json
    400:
      description: The request was invalid.
      body:
        type: ErrorResponse
put:
  description: |
    Updates the information of the location found using the provided database ID. Returns the amended location's info.
  headers:
    token:
      displayName: Token
      description: |
        Login token generated for an admin.
      type: string
  body:
    type: Location
  responses:
    202:
      body:
        type: Location
        example: !include ../examples/locations/location.json
    400:
      description: The request was invalid.
      body:
        type: ErrorResponse
post:
  description: |
    Creates a new location according to the provided specifications. Returns the new location's information.
  headers:
    token:
      displayName: Token
      description: |
        Login token generated for an admin.
      type: string
  body:
    type: Location
  responses:
    201:
      body:
        type: Location
        example: !include ../examples/locations/location.json
    400:
      description: The request was invalid.
      body:
        type: ErrorResponse
/{location_id}:
  uriParameters:
    location_id:
      type: string
      description: Business identifier for this location (must be unique by tenant).
  get:
    description: |
      Finds and returns a location using it's location ID.
    headers:
      token:
        displayName: Token
        description: |
          Login token generated for an admin.
        type: string
    responses:
      200:
        body:
          type: Location
          example: !include ../examples/locations/location.json
      400:
        description: The request was invalid.
        body:
          type: ErrorResponse
