/{location_id}:
  uriParameters:
    location_id:
      type: string
      description: Business identifier for this location (must be unique by tenant).
  get:
    description: Finds and returns a workstation using it's location ID.
    headers:
      token:
        displayName: Token
        description: |
          Login token generated for an admin.
        type: string
    responses:
      200:
        body:
          type: Workstation
          example: !include ../examples/workstations/workstation.json
