#%RAML 1.0 DataType
(package): ShoppingList
(docs-uri): https://docs.commercetools.com/http-api-projects-shoppingLists.html#set-key
type: ShoppingListUpdateAction
displayName: ShoppingListSetKeyAction
discriminatorValue: setKey
(postman-example): !include ../../../examples/ShoppingList/ShoppingListSetKeyAction.json
properties:
  key?:
    type: string
    description: User-specific unique identifier for the shopping list.
