#%RAML 1.0 DataType
(package): Variant
type: VariantUpdateAction
(beta): true
displayName: VariantUnpublishAction
discriminatorValue: unpublish
description: |
  Unpublishes the Variant by setting the `published` flag to `false`.
  Generates the [VariantUnpublished](ctp:api:type:VariantUnpublishedMessage) Message.
example: !include ../../../examples/Variant/VariantUnpublishAction.json
