#%RAML 1.0 DataType
(package): Variant
type: VariantUpdateAction
(beta): true
displayName: VariantSetAttributesAction
discriminatorValue: setAttributes
description: |
  Sets the attributes of the Variant. Existing attributes will be replaced with the new ones.
example: !include ../../../examples/Variant/VariantSetAttributesAction.json
properties:
  attributes:
    type: Attribute[]
    description: |
      Attributes to set for the Variant according to the respective [AttributeDefinition](ctp:api:type:AttributeDefinition).
  staged?:
    type: boolean
    description: |
      If `true`, only the staged attributes are updated. If `false`, both the current and staged attributes are updated.
    default: true
