#%RAML 1.0 DataType
(package): Variant
type: VariantUpdateAction
(beta): true
displayName: VariantSetImageLabelAction
discriminatorValue: setImageLabel
description: |
  Sets the label of a Variant's image.
example: !include ../../../examples/Variant/VariantSetImageLabelAction.json
properties:
  imageUrl:
    type: string
    description: |
      The URL of the image to set the label.
  label?:
    type: string
    description: |
      Value to set. If empty, any existing value will be removed.
  staged?:
    type: boolean
    description: |
      If `true`, only the staged image is updated. If `false`, both the current and staged image is updated.
    default: true
