#%RAML 1.0 DataType
(package): Variant
type: VariantUpdateAction
(beta): true
displayName: VariantChangeAssetOrderAction
discriminatorValue: changeAssetOrder
description: |
  Changes the order of Assets on a Variant.
example: !include ../../../examples/Variant/VariantChangeAssetOrderAction.json
properties:
  staged?:
    type: boolean
    description: |
      If `true`, only the staged `assets` is updated. If `false`, both the current and staged `assets` are updated.
    default: true
  assetOrder:
    type: array
    items: string
    description: |
      All existing Asset `id`s of the Variant in the desired new order.
