#%RAML 1.0 DataType
(package): Variant
type: VariantUpdateAction
(beta): true
displayName: VariantSetImagesAction
discriminatorValue: setImages
description: |
  Sets the images of the Variant. Existing images will be replaced with the new ones.
  Generates the [VariantImagesSet](ctp:api:type:VariantImagesSetMessage) Message.
example: !include ../../../examples/Variant/VariantSetImagesAction.json
properties:
  images:
    type: Image[]
    description: |
      Images to set for the Variant.
  staged?:
    type: boolean
    description: |
      If `true`, only the staged images are updated. If `false`, both the current and staged images are updated.
    default: true
