#%RAML 1.0 DataType
(package): ShoppingList
type: object
(expandable): true
displayName: ShoppingListLineItem
example: !include ../../examples/ShoppingList/ShoppingListLineItem.json
description: |
  ShoppingListLineItems are Line Items that contain references to [ProductVariants](ctp:api:type:ProductVariant) in a [Product](ctp:api:type:Product).

  In addition to standard [Reference Expansion](/general-concepts#reference-expansion), a ShoppingListLineItem offers expansion on `productSlug` and `variant`, defined with the query parameter `expand`.
properties:
  addedAt:
    type: datetime
    description: |
      Date and time (UTC) the ShoppingListLineItem was added to the ShoppingList.
  custom?:
    type: CustomFields
    description: |
      Custom Fields of the ShoppingListLineItem.
  deactivatedAt?:
    type: datetime
    description: |
      If the Product or Product Variant is deleted, `deactivatedAt` is the date and time (UTC) of deletion.

      This data is updated in an [eventual consistent manner](/general-concepts#eventual-consistency) when the Product Variant cannot be ordered anymore.
  id:
    type: string
    description: Unique identifier of the ShoppingListLineItem.
  key?:
    type: string
    description: User-defined identifier of the ShoppingListLineItem. It is unique per [ShoppingList](ctp:api:type:ShoppingList).
    pattern: ^[a-zA-Z0-9_-]
    minLength: 2
    maxLength: 256
  name:
    type: LocalizedString
    description: |
      Name of the Product.

      This data is updated in an [eventual consistent manner](/general-concepts#eventual-consistency) when the Product's name changes.
  productId:
    type: string
    description: |
      Unique identifier of a [Product](ctp:api:type:Product).
  productType:
    type: ProductTypeReference
    description: |
      The Product Type defining the Attributes of the [Product](ctp:api:type:Product).
  published:
    type: boolean
    description: |
      Whether the related [Product](ctp:api:type:Product) is published or not.

      This data is updated in an [eventual consistent manner](/general-concepts#eventual-consistency) when the Product's published status changes.
  quantity:
    type: number
    format: int64
    description: |
      Number of Products in the ShoppingListLineItem.
  variantId?:
    type: number
    format: int64
    description: |
      `id` of the [ProductVariant](ctp:api:type:ProductVariant) the ShoppingListLineItem refers to. If not set, the ShoppingListLineItem refers to the Master Variant.
  variant?:
    type: ProductVariant
    description: |
      Data of the [ProductVariant](ctp:api:type:ProductVariant).  This data includes all the Product Attributes and Variant Attributes to ensure the full Attribute context of the Product Variant.

      Returned when expanded using `expand=lineItems[*].variant`. You cannot expand only a single element of the array.
  productSlug?:
    type: LocalizedString
    description: |
      Slug of the current [ProductData](ctp:api:type:ProductData).

      Returned when expanded using `expand=lineItems[*].productSlug`. You cannot expand only a single element of the array.
