#%RAML 1.0 DataType
(package): ShoppingList
type: object
displayName: ShoppingListUpdate
(java-extends): 'com.commercetools.api.models.ResourceUpdate<ShoppingListUpdate,
  ShoppingListUpdateAction>'
properties:
  version:
    type: number
    format: int64
  actions:
    type: array
    items: ShoppingListUpdateAction
