#%RAML 1.0 DataType
(package): ShoppingList
(docs-uri): https://docs.commercetools.com/http-api-projects-shoppingLists.html#shoppingListDraft
type: object
displayName: ShoppingListDraft
properties:
  custom?:
    type: CustomFieldsDraft
    description: The custom fields.
  customer?:
    type: CustomerResourceIdentifier
    description: ''
  deleteDaysAfterLastModification?:
    type: number
    format: int64
    description:
      The shopping list will be deleted automatically if it hasn't been modified
      for the specified amount of days.
  description?:
    type: LocalizedString
    description: ''
  key?:
    type: string
    description: User-specific unique identifier for the shopping list.
  lineItems?:
    type: ShoppingListLineItemDraft[]
    description: ''
  name:
    type: LocalizedString
    description: ''
  slug?:
    type: LocalizedString
    description: |-
      Human-readable identifiers usually used as deep-link URL to the related shopping list.
      Each slug is unique across a project, but a shopping list can have the same slug for different languages.
      The slug must match the pattern [a-zA-Z0-9_-]{2,256}.
  textLineItems?:
    type: TextLineItemDraft[]
    description: ''
  anonymousId?:
    type: string
    description:
      Identifies shopping lists belonging to an anonymous session (the customer
      has not signed up/in yet).
  store?:
    type: StoreResourceIdentifier
    description: ''
