#%RAML 1.0 DataType
(package): ShoppingList
type: object
displayName: ShoppingListLineItemDraft
example: !include ../../examples/ShoppingList/ShoppingListLineItemDraft.json
description: |
  The [ProductVariant](ctp:api:type:ProductVariant) to be included in the ShoppingListLineItem must be specified using the `productID` and `variantID`, or by the `sku`.
properties:
  productId?:
    type: string
    description: |
      Unique identifier of a [Product](ctp:api:type:Product).
  variantId?:
    type: number
    format: int64
    description: |
      `id` of the [ProductVariant](ctp:api:type:ProductVariant). If not set, the ShoppingListLineItem refers to the Master Variant.
  sku?:
    type: string
    description: |
      `sku` of the [ProductVariant](ctp:api:type:ProductVariant).
  addedAt?:
    type: datetime
    description: |
      Date and time the ShoppingListLineItem is added to the [ShoppingList](ctp:api:type:ShoppingList). If not set, the current date and time (UTC) is used.
  custom?:
    type: CustomFieldsDraft
    description: |
      Custom Fields of the ShoppingListLineItem.
  quantity?:
    type: number
    format: int64
    default: 1
    minimum: 1
    description: |
      Number of Products in the ShoppingListLineItem.
