#%RAML 1.0 DataType
(package): ShoppingList
type: object
displayName: TextLineItem
properties:
  addedAt:
    type: datetime
    description: When the text line item was added to the shopping list.
  custom?:
    type: CustomFields
    description: ''
  description?:
    type: LocalizedString
    description: ''
  id:
    type: string
    description: The unique ID of this TextLineItem.
  name:
    type: LocalizedString
    description: ''
  quantity:
    type: number
    format: int32
    description: ''
